import type { PartialDictionary } from '@/types/i18n'
import { FAQ_CATEGORIES_FR, FAQ_ITEMS_FR } from '@/content/faq-data.fr'

/**
 * FRANÇAIS — traduction complète, structure identique à en/index.ts.
 * Les valeurs de chaîne sont traduites ; les clés, icônes et jetons
 * techniques restent inchangés. Les manques éventuels sont complétés par le
 * fallback anglais (§10). Les données FAQ proviennent de content/faq-data.fr.
 */
export const fr: PartialDictionary = {
  common: {
    tagline: "Votre partenaire fiable pour les services de traduction professionnelle.",
    nav: {
      home: "Accueil",
      services: "Services",
      quote: "Obtenir un devis",
      corporate: "Entreprises",
      partnership: "Partenariat",
      blog: "Blog",
      faq: "FAQ",
      contact: "Contact",
    },
    actions: {
      getQuote: "Obtenir un devis",
      calculatePrice: "Calculer le prix",
      uploadDocument: "Téléverser un document",
      whatsapp: "Discuter sur WhatsApp",
      learnMore: "En savoir plus",
      viewAll: "Tout voir",
      showMore: "Voir plus",
      showLess: "Voir moins",
      send: "Envoyer",
      apply: "Postuler",
      order: "Passer la commande",
      contactUs: "Nous contacter",
      openMenu: "Ouvrir le menu",
      closeMenu: "Fermer le menu",
      selectLanguage: "Choisir la langue",
      skipToContent: "Aller au contenu",
      login: "Se connecter",
      logout: "Se déconnecter",
      account: "Mon compte",
    },
    states: {
      loading: "Chargement…",
      error: "Une erreur s'est produite. Veuillez réessayer.",
      required: "Ce champ est obligatoire.",
      demoNotice: "Démo : les données du formulaire ne sont pas encore envoyées à un serveur.",
      unverified: "À vérifier",
    },
    topbar: {
      phoneLabel: "Téléphone",
      emailLabel: "E-mail",
      hoursLabel: "Horaires d'ouverture",
      afterHours: "Une assistance de traduction urgente est disponible en dehors des heures d'ouverture.",
      workingHours: "En semaine 09:00 - 18:00 | Service disponible en dehors des heures d'ouverture",
    },
  },

  home: {
    seo: {
      title: "TercümExpert — Services de traduction professionnelle",
      description:
        "Traduction assermentée, certification notariée et solutions de traduction pour entreprises. Téléversez votre document, obtenez un devis préliminaire instantané et une livraison professionnelle.",
    },
    hero: {
      title: "Votre partenaire fiable en traduction",
      titleAccent: "professionnelle",
      subtitle: "Téléversez votre document, voyez le prix, recevez une livraison professionnelle.",
      support: "Traduction assermentée • Certification notariée • Solutions pour entreprises",
    },
    trust: {
      title: "Pourquoi nous font-ils confiance ?",
      items: [
        { key: 'languages', label: "50+ langues" },
        { key: 'delivery', label: "Livraison en 24 heures" },
        { key: 'notary', label: "Certification notariée" },
        { key: 'quality', label: "Assurance qualité" },
      ],
    },
    stats: {
      title: "TercümExpert en chiffres",
      note: "Les chiffres ci-dessous ne sont pas présentés comme des affirmations définitives tant qu'ils ne sont pas vérifiés.",
      labels: {
        satisfaction: "Satisfaction client",
        completed: "Missions réalisées",
        languages: "Langues prises en charge",
        corporate: "Clients entreprises",
      },
    },
    howItWorks: {
      title: "Comment ça marche ?",
      subtitle: "La traduction professionnelle en cinq étapes.",
      steps: [
        { key: 'upload', title: "Téléverser", desc: "Téléversez votre document en toute sécurité." },
        { key: 'select', title: "Sélectionner", desc: "Choisissez la langue et le type de service." },
        { key: 'confirm', title: "Confirmer", desc: "Confirmez votre commande." },
        { key: 'track', title: "Suivre", desc: "Suivez le processus en temps réel." },
        { key: 'receive', title: "Recevoir", desc: "Recevez votre livraison professionnelle." },
      ],
    },
    services: {
      title: "Nos services",
      subtitle: "Une traduction experte pour chaque type de document.",
    },
    why: {
      title: "Pourquoi TercümExpert ?",
      subtitle: "Les atouts qui nous distinguent de la concurrence",
      features: [
        { key: 'autoQuote', title: "Calcul automatique du prix", desc: "Un prix préliminaire en quelques secondes." },
        { key: 'whatsapp', title: "Devis rapide sur WhatsApp", desc: "Contact en un clic." },
        { key: 'terminology', title: "Gestion terminologique", desc: "Un langage cohérent et professionnel." },
        { key: 'revision', title: "Droit de révision", desc: "Un processus axé sur la satisfaction." },
        { key: 'languages', title: "Prise en charge de 50+ langues", desc: "Une large couverture de paires de langues." },
        { key: 'terms', title: "Système de paiement à terme pour entreprises", desc: "Un paiement flexible pour les entreprises." },
      ],
    },
    corporateCta: {
      title: "Solutions pour entreprises",
      desc: "Des services linguistiques professionnels avec gestion terminologique, options de paiement à terme et un gestionnaire de compte dédié, adaptés à votre entreprise.",
      action: "Demander un devis entreprise",
    },
    partnershipTeaser: {
      title: "Programme de partenariat",
      subtitle: "Gagnez 20 % de commission sur chaque client que vous nous recommandez.",
      items: [
        { key: 'commission', title: "Commission transparente", desc: "20 % de commission pour chaque recommandation (sous réserve d'accord). Des gains transparents grâce à un tableau de suivi en temps réel." },
        { key: 'qr', title: "Système de QR code", desc: "Un suivi client simplifié grâce à l'intégration sur carte de visite. QR codes web et WhatsApp." },
      ],
      cta: "Devenir partenaire",
    },
    testimonials: {
      title: "Avis clients",
      subtitle: "De vrais avis clients seront ajoutés ici avant le lancement.",
      placeholderNote: "Texte provisoire — de vrais avis seront intégrés.",
      items: [
        { key: 't1', role: "Cabinet d'avocats" },
        { key: 't2', role: "Établissement de santé" },
        { key: 't3', role: "Client entreprise" },
        { key: 't4', role: "Client particulier" },
      ],
    },
    blogTeaser: {
      title: "Blog",
      subtitle: "Des contenus d'actualité issus du monde de la traduction",
      viewAll: "Voir tous les articles du blog",
    },
    finalCta: {
      title: "Commencez dès maintenant",
      desc: "Téléversez vos documents, obtenez un devis instantané et profitez de services de traduction professionnelle.",
      primary: "Obtenir un devis",
      secondary: "Nous contacter",
    },
  },

  services: {
    seo: {
      title: "Services de traduction",
      description:
        "Traduction assermentée, certifiée par notaire, juridique, technique, médicale et académique, ainsi que la localisation web/mobile. Types de documents, processus, livraison et paires de langues.",
    },
    hero: {
      title: "Services de traduction",
      subtitle: "Une traduction avec la terminologie adaptée à chaque domaine d'expertise.",
    },
    process: {
      title: "Comment se déroule le processus ?",
      steps: [
        { title: "Examen du document", desc: "Le type et l'objectif du document sont évalués." },
        { title: "Attribution à un expert", desc: "Un traducteur spécialisé dans le domaine est désigné." },
        { title: "Traduction et relecture", desc: "Traduction et relecture finale indépendante." },
        { title: "Certification et livraison", desc: "Certification notariée/apostille si nécessaire, puis livraison." },
      ],
    },
    delivery: {
      title: "Options de livraison",
      items: ["Livraison numérique (PDF/DOCX)", "Livraison physique des documents", "Livraison urgente"],
    },
    notaryApostille: {
      title: "Lien entre certification notariée et apostille",
      desc: "Lorsque cela est requis, la traduction assermentée est rendue valable auprès des institutions officielles grâce à la certification notariée et à la procédure d'apostille. L'exigence exacte dépend de l'institution auprès de laquelle le document sera présenté.",
    },
    fullService: {
      title: "Clé en main, livré à votre porte",
      note: "Envoyez-nous vos documents et nous gérons l'ensemble du processus — traduction, certification notariée et apostille inclus. Vos documents finalisés vous parviennent à votre porte par coursier. Concentrez-vous sur votre travail et laissez-nous le reste.",
    },
    cta: {
      title: "Vous ne savez pas quel service il vous faut ?",
      desc: "Téléversez votre document et nous vous indiquerons le service et le prix les plus adaptés.",
    },
    documentTypesTitle: "Types de documents concernés",
  },

  serviceItems: {
    sworn: {
      name: "Traduction assermentée",
      short: "Traduction officiellement valable avec la signature et le cachet d'un traducteur assermenté.",
      benefits: ["Valable auprès des institutions officielles", "Certifiée par un traducteur assermenté", "Processus rapide"],
    },
    notarized: {
      name: "Traduction certifiée par notaire",
      short: "Certification notariée d'une traduction assermentée.",
      benefits: ["Certification notariée", "Adaptée aux démarches officielles", "Nous gérons le processus"],
    },
    apostille: {
      name: "Accompagnement pour l'apostille",
      short: "Accompagnement dans la procédure d'apostille pour une validité à l'étranger.",
      benefits: ["Validité internationale", "Conseil sur la procédure", "Orientation vers les institutions"],
    },
    legal: {
      name: "Traduction juridique",
      short: "Traduction maîtrisant la terminologie des contrats, des documents judiciaires et officiels.",
      benefits: ["Terminologie juridique", "Garantie de confidentialité", "Traducteur expert"],
    },
    technical: {
      name: "Traduction technique",
      short: "Traduction cohérente pour les manuels, cahiers des charges et documents techniques.",
      benefits: ["Gestion terminologique", "Mise en forme préservée", "Expertise sectorielle"],
    },
    medical: {
      name: "Traduction médicale",
      short: "Traduction précise pour les comptes rendus, notices et documents médicaux.",
      benefits: ["Terminologie médicale", "Axée sur l'exactitude", "Confidentialité"],
    },
    academic: {
      name: "Traduction académique",
      short: "Un langage académique pour les thèses, articles et traductions de diplômes.",
      benefits: ["Style académique", "Cohérence avec la source", "Livraison dans les délais"],
    },
    localization: {
      name: "Localisation web et mobile",
      short: "Localisation culturellement adaptée des sites web et des applications.",
      benefits: ["Adaptation culturelle", "Intégration technique", "Compatibilité SEO"],
    },
  },

  corporate: {
    statsLabels: {
      corporate: "Clients entreprises",
      discount: "Remise sur commandes en volume",
      term: "Délai de paiement",
    },
    seo: {
      title: "Solutions pour entreprises",
      description:
        "Des services linguistiques professionnels pour les entreprises avec gestion terminologique, options de paiement à terme, commandes en volume et un gestionnaire de compte dédié.",
    },
    hero: {
      title: "Solutions pour entreprises",
      subtitle:
        "Des services linguistiques professionnels avec gestion terminologique, options de paiement à terme et un gestionnaire de compte dédié, adaptés à votre entreprise.",
      primaryCta: "Demander un devis entreprise",
      secondaryCta: "Envoyer un e-mail",
    },
    features: {
      title: "Fonctionnalités pour entreprises",
      subtitle: "Des solutions adaptées à votre activité",
      items: [
        {
          key: 'custom',
          icon: 'Target',
          title: "Service sur mesure",
          points: ["Terminologie fixe", "Préservation du ton de votre marque", "Gestionnaire de compte dédié", "Création d'un guide de style"],
        },
        {
          key: 'volume',
          icon: 'BarChart3',
          title: "Traitement en volume et paiement à terme",
          points: ["Plans de traduction mensuels", "Remises sur commandes en volume", "Délais de paiement jusqu'à 30 jours", "Système de facturation"],
        },
        {
          key: 'security',
          icon: 'Lock',
          title: "Confidentialité et sécurité",
          points: ["Protocole NDA", "Transfert de fichiers chiffré", "Processus conformes à la KVKK"],
        },
      ],
    },
    whyPackage: {
      title: "Pourquoi un forfait entreprise ?",
      items: [
        {
          key: 'terminology',
          icon: 'Building2',
          title: "Gestion terminologique fixe",
          desc: "Nous constituons une base terminologique propre à votre entreprise. Le langage de votre marque est préservé dans toutes les traductions et nous en assurons la cohérence. Nous veillons à utiliser les mêmes termes dans chaque projet.",
        },
        {
          key: 'manager',
          icon: 'Users',
          title: "Gestionnaire de compte dédié",
          desc: "Votre gestionnaire de compte dédié suit l'ensemble de vos processus. Avec une ligne d'assistance accessible, nous sommes à vos côtés dans les situations urgentes.",
        },
        {
          key: 'security',
          icon: 'ShieldCheck',
          title: "Confidentialité et sécurité",
          desc: "Nous travaillons sous protocole NDA. Vos données sont en sécurité grâce à une solide infrastructure de sécurité, un transfert de fichiers chiffré et des processus conformes à la KVKK.",
        },
      ],
    },
    payment: {
      title: "Options de paiement",
      subtitle: "Des plans de paiement flexibles adaptés à votre activité",
      recommendedLabel: "RECOMMANDÉ",
      options: [
        {
          key: 'standard',
          label: "Paiement immédiat",
          heading: "Standard",
          desc: "Paiement par carte bancaire ou virement après chaque commande",
          points: ["Paiement en plusieurs fois par carte", "Livraison immédiate"],
          recommended: false,
        },
        {
          key: 'term',
          label: "Paiement mensuel à terme",
          heading: "15-30 jours",
          desc: "Facturation mensuelle consolidée et option de paiement à terme",
          points: ["Délai de 30 jours", "Remise en volume", "Rapport mensuel"],
          recommended: true,
        },
      ],
    },
    form: {
      title: "Demande de forfait entreprise",
      desc: "Remplissez le formulaire et notre équipe d'experts vous contactera",
      fields: {
        company: "Nom de l'entreprise",
        contactName: "Nom complet du contact",
        email: "E-mail",
        phone: "Téléphone",
        need: "Parlez-nous de vos besoins en traduction",
        consent: "J'ai lu et j'approuve la déclaration d'information KVKK.",
      },
      submit: "Envoyer la demande",
      success: "Votre demande a bien été reçue. Nous vous répondrons dans les meilleurs délais.",
      note: "Nous vous répondrons sous 1 jour ouvré.",
    },
  },

  partnership: {
    seo: {
      title: "Programme de partenariat",
      description:
        "Gagnez une commission sur chaque client que vous recommandez. Rapports transparents, recommandations par QR code et assistance professionnelle.",
    },
    hero: {
      title: "Programme de partenariat",
      value: "Gagnez 20 % de commission sur chaque client que vous nous recommandez.",
      subtitle: "Un système transparent, des paiements fiables, une coopération à long terme.",
      cta: "Postuler maintenant",
    },
    advantages: {
      title: "Avantages du partenaire",
      subtitle: "Pourquoi devenir partenaire de TercümExpert ?",
      items: [
        { key: 'commission', icon: 'Wallet', title: "20 % de commission garantie", desc: "Un système de commission transparent pour chaque client que vous recommandez." },
        { key: 'qr', icon: 'QrCode', title: "Recommandation par QR code", desc: "Un suivi client simplifié grâce à l'intégration sur carte de visite." },
        { key: 'reporting', icon: 'BarChart3', title: "Rapports transparents", desc: "Un tableau de suivi des commissions et des clients en temps réel." },
        { key: 'support', icon: 'Users', title: "Assistance professionnelle", desc: "Une ligne d'assistance dédiée aux partenaires et un gestionnaire de compte." },
      ],
    },
    howItWorks: {
      title: "Comment ça marche ?",
      steps: [
        { title: "Postuler", desc: "Remplissez le formulaire de candidature en ligne. Communiquez les informations sur votre entreprise et vos coordonnées. Votre candidature est examinée sous 1 jour ouvré." },
        { title: "Devenir partenaire", desc: "Une fois votre candidature approuvée, vous accédez à votre tableau de bord partenaire dédié. Vos QR codes et liens de recommandation sont prêts." },
        { title: "Recommander des clients", desc: "Recommandez-nous vos clients par QR code, lien personnalisé ou carte de visite. Chaque recommandation est automatiquement enregistrée dans le système." },
        { title: "Gagner des commissions", desc: "Vous gagnez 20 % de commission chaque fois qu'un client que vous avez recommandé passe une commande. Vous recevez des paiements automatiques tous les 15 jours." },
      ],
    },
    sectors: {
      title: "Secteurs cibles",
      subtitle: "Pour quels secteurs est-ce idéal ?",
      items: [
        { key: 'law', icon: 'Scale', title: "Cabinets d'avocats", desc: "Besoin de traduction assermentée de dossiers, contrats et documents juridiques." },
        { key: 'visa', icon: 'Plane', title: "Conseil en visa", desc: "Documents nécessitant une traduction assermentée tels que passeports, diplômes et actes d'état civil." },
        { key: 'education', icon: 'GraduationCap', title: "Conseil en études", desc: "Traduction assermentée de documents d'étudiants et procédures d'apostille." },
        { key: 'health', icon: 'HeartPulse', title: "Tourisme médical", desc: "Traduction de comptes rendus médicaux, dossiers patients et documents de santé." },
        { key: 'patent', icon: 'Building2', title: "Offices de brevets/marques", desc: "Traduction technique de brevets, dépôts de marques et documents juridiques." },
        { key: 'realestate', icon: 'Home', title: "Agences immobilières", desc: "Traduction de titres de propriété, contrats et documents officiels pour investisseurs étrangers." },
        { key: 'hr', icon: 'Briefcase', title: "Conseil en RH", desc: "Traduction de CV, diplômes et lettres de recommandation pour placement à l'étranger." },
        { key: 'software', icon: 'Code', title: "Éditeurs de logiciels", desc: "Localisation d'applications web et mobiles, traduction de documents techniques." },
      ],
    },
    commission: {
      title: "Structure de commission",
      stats: {
        commissionLabel: "Commission standard",
        commissionSub: "Sur chaque commande",
        periodUnit: "Jours",
        periodLabel: "Période de paiement",
        feeLabel: "Frais d'inscription",
        feeSub: "Entièrement gratuit",
      },
      exampleTitle: "Exemple de calcul des gains",
      exampleOrderLabel: "Commande du client que vous avez recommandé",
      exampleRateLabel: "Taux de commission",
      exampleEarningLabel: "Vos gains",
      note: "Les taux et conditions de commission sont soumis au contrat de partenariat.",
    },
    form: {
      title: "Formulaire de candidature partenaire",
      subtitle: "Remplissez le formulaire et nous vous répondrons sous 1 jour ouvré.",
      fields: {
        company: "Nom de l'entreprise/organisation",
        sector: "Secteur",
        contactName: "Nom complet du contact",
        titleRole: "Fonction",
        email: "E-mail",
        phone: "Téléphone",
        potential: "Votre potentiel mensuel estimé de recommandations",
        note: "Toute remarque que vous souhaitez ajouter",
        agreement: "J'ai lu et j'accepte les conditions du contrat de partenariat.",
      },
      sectorPlaceholder: "Sélectionner",
      sectorOptions: ["Cabinet d'avocats", "Conseil en visa", "Conseil en études", "Tourisme médical", "Office de brevets/marques", "Immobilier", "Conseil en RH", "Logiciels", "Autre"],
      potentialOptions: ["1-5 clients", "5-10 clients", "10-20 clients", "20+ clients"],
      submit: "Envoyer la candidature",
      success: "Votre candidature a bien été reçue. Nous vous contacterons.",
      note: "Votre candidature sera examinée sous 1 jour ouvré.",
    },
  },

  quote: {
    seo: {
      title: "Calcul instantané du prix",
      description: "Téléversez votre document ou saisissez les détails et obtenez votre devis préliminaire instantané.",
    },
    hero: {
      title: "Calcul instantané du prix",
      subtitle: "Téléversez votre document ou saisissez les détails et obtenez un devis préliminaire instantané.",
    },
    upload: {
      heading: "Téléversez vos documents",
      privacy: "Vos données restent confidentielles",
      tabFile: "Téléverser un fichier",
      tabText: "Saisir le texte",
      chooseFile: "Choisissez vos documents",
      formats: ".docx, .xlsx, .pdf, .pptx, .jpg, .png et 50+ formats acceptés · Max 100 Mo par fichier",
      dropHint: "Vous pouvez glisser-déposer un ou plusieurs fichiers dans cette zone.",
      textPlaceholder: "Collez ou saisissez votre texte ici…",
      totalWords: "Nombre total de mots",
      extracting: "Comptage des mots…",
      wordsUnit: "mots",
      remove: "Retirer",
      unsupported:
        "Le comptage automatique des mots n'a pas été possible pour ce type de fichier. Veuillez coller le texte via « Saisir le texte » ; le nombre sera vérifié par notre équipe lors de l'établissement du devis.",
      empty:
        "Aucun texte sélectionnable n'a été trouvé dans le fichier (il peut s'agir d'un document scanné/d'une image). Veuillez utiliser « Saisir le texte », ou le nombre sera vérifié lors de l'établissement du devis.",
      error: "Le fichier n'a pas pu être lu. Veuillez réessayer ou utiliser « Saisir le texte ».",
      tooLarge: "Le fichier ne peut pas dépasser 100 Mo.",
      needInput: "Pour obtenir un prix, veuillez téléverser un fichier ou saisir du texte.",
    },
    fields: {
      upload: "Téléverser un document (facultatif)",
      uploadHint: "PDF, DOC, DOCX ou TXT — max 10 Mo",
      sourceLang: "Langue source",
      targetLang: "Langue cible",
      serviceType: "Type de service",
      documentType: "Type de document",
      wordCount: "Nombre de mots estimé",
      wordCountHint: "Utilisez le curseur ou saisissez le nombre manuellement.",
      options: "Options complémentaires",
      calculate: "Calculer le prix",
    },
    options: {
      urgent: "Livraison urgente",
      notarization: "Certification notariée",
      physicalDelivery: "Livraison physique",
    },
    languages: {
      tr: "Turc",
      en: "Anglais",
      de: "Allemand",
      fr: "Français",
      es: "Espagnol",
      it: "Italien",
      ru: "Russe",
      ar: "Arabe",
      nl: "Néerlandais",
    },
    documentTypes: {
      diploma: "Diplôme",
      passport: "Passeport",
      'civil-registry': "Extrait d'état civil",
      contract: "Contrat",
      'medical-report': "Compte rendu médical",
      'technical-doc': "Document technique",
      'court-doc': "Document judiciaire",
      other: "Autre",
    },
    result: {
      title: "Devis préliminaire",
      basePrice: "Frais de service de base",
      wordPrice: "Tarif au mot",
      addons: "Services complémentaires",
      total: "Total",
      vat: "TVA",
      delivery: "Délai de livraison estimé",
      deliveryUnit: "jours ouvrés",
      disclaimer: "Ceci est un devis préliminaire ; le prix final est confirmé après examen du document.",
      order: "Passer la commande",
      whatsapp: "Contacter via WhatsApp",
      estimatedWords: "Mots estimés (automatique — démo)",
    },
    orderConfirm: {
      title: "Votre commande a bien été reçue",
      number: "N° de commande",
      desc: "Votre demande et vos documents ont été enregistrés. Notre équipe d'experts examinera le document et vous contactera dans les meilleurs délais.",
      viewOrders: "Mes commandes",
      submitting: "Création de la commande…",
      error: "Un problème est survenu lors de la création de votre commande. Veuillez réessayer.",
    },
    gate: {
      title: "Votre prix est prêt",
      subtitle: "Connectez-vous ou vérifiez vos informations pour voir le prix et passer une commande.",
      loginCta: "Se connecter / S'inscrire",
      or: "ou continuer rapidement",
      firstName: "Prénom",
      lastName: "Nom",
      email: "E-mail",
      sendCode: "Envoyer le code de vérification",
      codeLabel: "Code de vérification",
      codeSentA: "a reçu un code de vérification.",
      verify: "Vérifier et voir le prix",
      resend: "Renvoyer le code",
      resent: "Un nouveau code a été envoyé.",
      back: "Modifier les informations",
      errNames: "Le prénom et le nom sont obligatoires.",
      errEmail: "Saisissez une adresse e-mail valide.",
      errCode: "Veuillez saisir le code en entier.",
      note: "Votre e-mail n'est utilisé que pour le devis et la commande.",
    },
    note: {
      label: "Remarque concernant votre commande (facultatif)",
      placeholder: "Vous pouvez indiquer ici vos demandes de livraison, de terminologie ou vos demandes particulières.",
    },
  },

  order: {
    seo: {
      title: "Suivi de commande",
      description: "Suivez l'état de votre commande.",
    },
    numberLabel: "N° de commande",
    placedOn: "Date de commande",
    estimatedLabel: "Livraison estimée de la traduction",
    cargoEstimatedLabel: "Date d'expédition estimée",
    timelineTitle: "État de la commande",
    steps: {
      received: "Votre commande a bien été reçue",
      in_progress: "En cours",
      translated: "Traduction terminée",
      shipped: "Expédiée",
      delivered: "Livrée",
      cancelled: "Commande annulée",
    },
    stepDesc: {
      received: "Votre demande et vos documents sont parvenus à notre système. Notre équipe d'experts les examinera et commencera sous peu.",
      in_progress: "Notre traducteur expert a commencé votre traduction.",
      translated: "Votre traduction est terminée et les vérifications finales ont été effectuées.",
      shipped: "Votre document a été remis au coursier ; vous pouvez le suivre à l'aide du bouton ci-dessous.",
      delivered: "Votre document vous a été envoyé par e-mail.",
      cancelled: "Cette commande a été annulée. N'hésitez pas à nous contacter pour toute question.",
    },
    cargoReady: "Votre document a été expédié. Suivez-le en un clic :",
    cargoPending: "Le code de suivi apparaîtra ici une fois votre document expédié.",
    trackCargo: "Suivre mon envoi",
    digitalPending: "Une fois votre traduction terminée, vos fichiers vous seront envoyés par e-mail.",
    digitalDelivered: "Votre traduction vous a été envoyée par e-mail. Vérifiez votre boîte de réception (et votre dossier spam).",
    detailsTitle: "Détails de la commande",
    fields: {
      service: "Service",
      langs: "Langues",
      documentType: "Type de document",
      words: "Mots",
      delivery: "Délai estimé",
      total: "Montant",
      note: "Votre remarque",
    },
    myOrders: "Mes commandes",
    backHome: "Retour à l'accueil",
    whatsapp: "Contacter via WhatsApp",
    loading: "Chargement de la commande…",
    loginRequired: {
      title: "Connectez-vous pour voir votre commande",
      desc: "Vous ne pouvez accéder aux détails de votre commande qu'après vous être connecté avec votre compte.",
      login: "Se connecter",
    },
    notFound: {
      title: "Commande introuvable",
      desc: "Ce numéro de commande ne vous appartient pas ou n'existe pas. Veuillez vérifier le lien.",
      home: "Retour à l'accueil",
    },
  },

  faq: {
    seo: {
      title: "Foire aux questions",
      description: "Questions fréquentes sur la traduction assermentée, les délais de livraison, la tarification, la certification notariée et le paiement à terme pour entreprises.",
    },
    hero: { title: "Foire aux questions", subtitle: "La réponse que vous cherchez est ici." },
    categoriesTitle: "Catégories",
    searchPlaceholder: "Rechercher des questions ou des mots-clés…",
    empty: "Aucune question ne correspond à votre recherche. Essayez un autre mot ou contactez-nous.",
    categories: FAQ_CATEGORIES_FR,
    items: FAQ_ITEMS_FR,
    notFound: {
      title: "Vous n'avez pas trouvé la réponse à votre question ?",
      contact: "Nous contacter",
      whatsapp: "Assistance WhatsApp",
    },
  },

  contact: {
    seo: {
      title: "Contact",
      description: "Contactez TercümExpert : téléphone, e-mail, WhatsApp et formulaire de contact.",
    },
    hero: { title: "Contact", subtitle: "Comment pouvons-nous vous aider ?" },
    infoTitle: "Coordonnées",
    labels: {
      phone: "Téléphone",
      email: "E-mail",
      whatsapp: "WhatsApp",
      address: "Adresse",
      hours: "Horaires d'ouverture",
    },
    form: {
      title: "Nous contacter",
      fields: {
        name: "Nom complet",
        email: "E-mail",
        phone: "Téléphone",
        subject: "Objet",
        message: "Message",
        consent: "J'ai lu et j'approuve la déclaration d'information KVKK.",
      },
      submit: "Envoyer le message",
      success: "Votre message a bien été reçu. Nous vous répondrons sous peu.",
    },
    map: {
      title: "Notre emplacement",
      subtitle: "Retrouvez-nous sur la carte",
      placeholder: "Zone de la carte",
      note: "La carte de localisation sera bientôt affichée ici.",
    },
  },

  auth: {
    seo: {
      title: "Se connecter / S'inscrire",
      description: "Connectez-vous à votre compte TercümExpert ou créez-en un nouveau.",
    },
    tabs: { login: "Se connecter", register: "S'inscrire" },
    google: "Continuer avec Google",
    or: "ou",
    fields: {
      firstName: "Prénom",
      lastName: "Nom",
      email: "E-mail",
      password: "Mot de passe",
      code: "Code de vérification",
    },
    login: {
      title: "Connectez-vous à votre compte",
      submit: "Se connecter",
      noAccount: "Vous n'avez pas de compte ?",
      switchToRegister: "S'inscrire",
    },
    register: {
      title: "Créer un nouveau compte",
      submit: "S'inscrire",
      haveAccount: "Vous avez déjà un compte ?",
      switchToLogin: "Se connecter",
      consent: "En créant un compte, j'accepte la déclaration d'information KVKK et la politique de confidentialité.",
    },
    verify: {
      title: "Vérifiez votre e-mail",
      desc: "— saisissez le code à 6 chiffres que nous avons envoyé à cette adresse.",
      submit: "Vérifier et continuer",
      spam: "Le code peut être retardé de quelques minutes ; vérifiez aussi votre dossier spam/courrier indésirable.",
      resend: "Renvoyer le code",
      resent: "Un nouveau code a été envoyé.",
      back: "Revenir en arrière",
    },
    signedIn: {
      title: "Mon compte",
      greeting: "Bienvenue",
      logout: "Se déconnecter",
    },
    orders: {
      title: "Mes commandes",
      empty: "Vous n'avez pas encore de commande. Vous pouvez créer votre première commande depuis Calculer le prix.",
      loading: "Chargement des commandes…",
      error: "Les commandes n'ont pas pu être chargées. Veuillez actualiser la page.",
      status: {
        received: "Reçue",
        in_progress: "En cours",
        translated: "Traduction terminée",
        shipped: "Expédiée",
        delivered: "Livrée",
        cancelled: "Annulée",
      },
      track: "Suivre",
    },
    errors: {
      nameRequired: "Le prénom et le nom sont obligatoires.",
      emailInvalid: "Saisissez une adresse e-mail valide.",
      passwordShort: "Le mot de passe doit comporter au moins 6 caractères.",
      codeInvalid: "Veuillez saisir le code à 6 chiffres.",
      consentRequired: "Votre accord est requis pour continuer.",
    },
  },

  blog: {
    seo: { title: "Blog", description: "Des contenus guides sur la traduction, le notariat, l'apostille et la localisation." },
    hero: { title: "Blog", subtitle: "Des guides issus du monde de la traduction." },
    searchPlaceholder: "Rechercher des articles…",
    readingTime: "min de lecture",
    relatedTitle: "Articles liés",
    allCategories: "Toutes",
    empty: "Aucun article ne correspond à ce critère.",
  },

  legal: {
    lastUpdatedLabel: "Dernière mise à jour",
    draftNotice:
      "Ce texte est un brouillon et doit être relu par un expert juridique avant sa publication. Les informations sur la société n'ont pas encore été vérifiées.",
    kvkk: {
      seo: { title: "Déclaration d'information KVKK", description: "Déclaration d'information relative à la protection des données personnelles." },
      title: "Déclaration d'information KVKK",
      sections: [
        { heading: "Responsable du traitement", body: "Le responsable du traitement et ses coordonnées seront ajoutés avant le lancement." },
        { heading: "Données personnelles traitées", body: "Le nom, les coordonnées et les données des documents peuvent être traités lors des processus de contact et de commande." },
        { heading: "Finalités du traitement", body: "Prestation de services, devis, communication et obligations légales." },
        { heading: "Bases juridiques", body: "Exécution d'un contrat, consentement explicite et intérêt légitime." },
        { heading: "Durées de conservation", body: "Les données sont conservées pendant les durées prévues par la législation applicable." },
        { heading: "Transfert", body: "Transférées uniquement dans la mesure nécessaire au service et dans le respect de la législation." },
        { heading: "Vos droits", body: "Vous pouvez exercer vos droits en vertu de l'article 11 de la KVKK." },
        { heading: "Comment exercer vos droits", body: "Vous pouvez soumettre vos demandes via les canaux de contact indiqués." },
      ],
    },
    privacy: {
      seo: { title: "Politique de confidentialité", description: "Politique relative à la confidentialité des données personnelles et des documents." },
      title: "Politique de confidentialité",
      sections: [
        { heading: "Informations collectées", body: "Coordonnées et documents téléversés." },
        { heading: "Utilisation", body: "Utilisées uniquement pour la prestation de services et la communication." },
        { heading: "Sécurité des documents", body: "Les documents sont traités avec un transfert chiffré et selon des principes de confidentialité." },
        { heading: "Cookies", body: "Les détails figurent dans la politique relative aux cookies." },
      ],
    },
    distanceSales: {
      seo: { title: "Contrat de vente à distance", description: "Contrat de vente à distance pour la vente de services." },
      title: "Contrat de vente à distance",
      sections: [
        { heading: "Parties", body: "Les informations sur le vendeur et l'acheteur seront ajoutées avant le lancement." },
        { heading: "Étendue du service", body: "L'étendue des services de traduction/certification commandés." },
        { heading: "Droit de rétractation et exceptions", body: "Des exceptions au droit de rétractation peuvent s'appliquer aux services préparés spécifiquement pour une personne/commande." },
        { heading: "Retours et annulation", body: "Les conditions de retour et d'annulation sont énoncées ici." },
      ],
    },
    cookies: {
      seo: { title: "Politique relative aux cookies", description: "Catégories de cookies utilisées sur le site et gestion des préférences." },
      title: "Politique relative aux cookies",
      sections: [
        { heading: "Qu'est-ce qu'un cookie ?", body: "Les cookies sont de petits fichiers stockés dans votre navigateur." },
        { heading: "Catégories", body: "Cookies nécessaires, d'analyse, de marketing et de préférences." },
        { heading: "Gestion des préférences", body: "Vous pouvez mettre à jour vos préférences de cookies à tout moment." },
      ],
    },
  },

  footer: {
    tagline: "Votre partenaire fiable pour les services de traduction professionnelle.",
    columns: {
      quickLinks: "Liens rapides",
      services: "Services",
      contact: "Contact",
    },
    quickLinks: {
      corporate: "Entreprises",
      services: "Nos services",
      quote: "Calculer le prix",
      blog: "Blog",
      faq: "Foire aux questions",
      contact: "Contact",
    },
    serviceLinks: {
      sworn: "Traduction assermentée",
      notarized: "Traduction certifiée par notaire",
      apostille: "Procédure d'apostille",
      corporate: "Solutions pour entreprises",
      partnership: "Programme de partenariat",
    },
    legal: {
      kvkk: "KVKK",
      privacy: "Politique de confidentialité",
      distanceSales: "Contrat de vente à distance",
      cookies: "Politique relative aux cookies",
    },
    socialTitle: "Suivez-nous",
    whatsapp: "Assistance WhatsApp",
    rights: "Tous droits réservés.",
  },

  cookie: {
    title: "Préférences de cookies",
    desc: "Nous utilisons des cookies pour améliorer votre expérience. Les cookies autres que ceux nécessaires ne s'exécutent qu'avec votre consentement.",
    accept: "Accepter",
    reject: "Refuser",
    manage: "Gérer les préférences",
    save: "Enregistrer les préférences",
    categories: {
      necessary: { label: "Nécessaires", desc: "Indispensables au fonctionnement du site ; ne peuvent pas être désactivés." },
      analytics: { label: "Analyse", desc: "Nous aident à comprendre l'utilisation." },
      marketing: { label: "Marketing", desc: "Pour des contenus et publicités pertinents." },
      preferences: { label: "Préférences", desc: "Mémorise vos préférences." },
    },
  },

  chatbot: {
    title: "Assistance TercümExpert",
    open: "Ouvrir le chat",
    close: "Fermer le chat",
    minimize: "Réduire",
    clear: "Effacer la conversation",
    inputPlaceholder: "Saisissez votre message…",
    send: "Envoyer",
    typing: "En train d'écrire…",
    welcome:
      "Bonjour et bienvenue chez TercümExpert. Je peux vous aider concernant la traduction, la tarification, la certification notariée, l'apostille ou les services pour entreprises.",
    quickQuestions: [
      "Comment le prix est-il calculé ?",
      "Qu'est-ce que la traduction assermentée ?",
      "Je veux téléverser un document",
      "Je veux un devis entreprise",
      "La certification notariée est-elle requise ?",
      "Mettez-moi en relation avec un conseiller",
    ],
    handoff: "Être mis en relation avec un conseiller",
    toWhatsapp: "Transférer vers WhatsApp",
    disclaimer: "Ces informations sont générales ; veuillez confirmer les exigences exactes auprès de l'institution concernée.",
    sensitiveWarning:
      "Veuillez ne pas partager de données personnelles sensibles via ce chat. Vous pouvez envoyer vos documents via la zone de téléversement sécurisée.",
  },

  notFound: {
    seo: { title: "Page introuvable", description: "La page que vous recherchez est introuvable." },
    title: "Page introuvable",
    desc: "La page que vous recherchez a peut-être été déplacée ou n'a jamais existé.",
    home: "Retour à l'accueil",
  },
}
