import type { PartialDictionary } from '@/types/i18n'
import { FAQ_CATEGORIES_PL, FAQ_ITEMS_PL } from '@/content/faq-data.pl'

export const pl: PartialDictionary = {
  common: {
    tagline: 'Państwa niezawodny partner w profesjonalnych usługach tłumaczeniowych.',
    nav: {
      home: 'Strona główna',
      services: 'Usługi',
      quote: 'Uzyskaj wycenę',
      corporate: 'Dla firm',
      partnership: 'Współpraca partnerska',
      blog: 'Blog',
      faq: 'FAQ',
      contact: 'Kontakt',
    },
    actions: {
      getQuote: 'Uzyskaj wycenę',
      calculatePrice: 'Oblicz cenę',
      uploadDocument: 'Prześlij dokument',
      whatsapp: 'Napisz na WhatsApp',
      learnMore: 'Dowiedz się więcej',
      viewAll: 'Zobacz wszystko',
      showMore: 'Pokaż więcej',
      showLess: 'Pokaż mniej',
      send: 'Wyślij',
      apply: 'Złóż wniosek',
      order: 'Złóż zamówienie',
      contactUs: 'Skontaktuj się z nami',
      openMenu: 'Otwórz menu',
      closeMenu: 'Zamknij menu',
      selectLanguage: 'Wybierz język',
      skipToContent: 'Przejdź do treści',
      login: 'Zaloguj się',
      logout: 'Wyloguj się',
      account: 'Moje konto',
    },
    states: {
      loading: 'Ładowanie…',
      error: 'Coś poszło nie tak. Proszę spróbować ponownie.',
      required: 'To pole jest wymagane.',
      demoNotice: 'Demo: dane formularza nie są jeszcze wysyłane na serwer.',
      unverified: 'Do zweryfikowania',
    },
    topbar: {
      phoneLabel: 'Telefon',
      emailLabel: 'E-mail',
      hoursLabel: 'Godziny pracy',
      afterHours: 'Poza godzinami pracy dostępne jest pilne wsparcie tłumaczeniowe.',
      workingHours: 'Dni powszednie 09:00 - 18:00 | Obsługa dostępna także poza godzinami pracy',
    },
  },

  home: {
    seo: {
      title: 'TercümExpert — Profesjonalne usługi tłumaczeniowe',
      description:
        'Tłumaczenia przysięgłe, poświadczenia notarialne i rozwiązania tłumaczeniowe dla firm. Prześlij dokument, otrzymaj natychmiastową wstępną wycenę i profesjonalną realizację.',
    },
    hero: {
      title: 'Państwa niezawodny partner w profesjonalnych',
      titleAccent: 'usługach tłumaczeniowych',
      subtitle: 'Prześlij dokument, zobacz cenę, otrzymaj profesjonalną realizację.',
      support: 'Tłumaczenie przysięgłe • Poświadczenie notarialne • Rozwiązania dla firm',
    },
    trust: {
      title: 'Dlaczego nam ufają?',
      items: [
        { key: 'languages', label: 'Ponad 50 języków' },
        { key: 'delivery', label: 'Realizacja w 24 godziny' },
        { key: 'notary', label: 'Poświadczenie notarialne' },
        { key: 'quality', label: 'Gwarancja jakości' },
      ],
    },
    stats: {
      title: 'TercümExpert w liczbach',
      note: 'Poniższe dane nie są przedstawiane jako ostateczne twierdzenia, dopóki nie zostaną zweryfikowane.',
      labels: {
        satisfaction: 'Zadowolenie klientów',
        completed: 'Zrealizowane zlecenia',
        languages: 'Obsługa językowa',
        corporate: 'Klienci firmowi',
      },
    },
    howItWorks: {
      title: 'Jak to działa?',
      subtitle: 'Profesjonalne tłumaczenie w pięciu krokach.',
      steps: [
        { key: 'upload', title: 'Prześlij', desc: 'Prześlij swój dokument w bezpieczny sposób.' },
        { key: 'select', title: 'Wybierz', desc: 'Wybierz język i rodzaj usługi.' },
        { key: 'confirm', title: 'Potwierdź', desc: 'Potwierdź swoje zamówienie.' },
        { key: 'track', title: 'Śledź', desc: 'Śledź proces w czasie rzeczywistym.' },
        { key: 'receive', title: 'Odbierz', desc: 'Odbierz profesjonalnie zrealizowane tłumaczenie.' },
      ],
    },
    services: {
      title: 'Nasze usługi',
      subtitle: 'Fachowe tłumaczenie każdego rodzaju dokumentu.',
    },
    why: {
      title: 'Dlaczego TercümExpert?',
      subtitle: 'Cechy, które wyróżniają nas na tle konkurencji',
      features: [
        { key: 'autoQuote', title: 'Automatyczne obliczanie ceny', desc: 'Wstępna cena w kilka sekund.' },
        { key: 'whatsapp', title: 'Szybka wycena przez WhatsApp', desc: 'Kontakt jednym dotknięciem.' },
        { key: 'terminology', title: 'Zarządzanie terminologią', desc: 'Spójny, firmowy język.' },
        { key: 'revision', title: 'Prawo do korekty', desc: 'Proces nastawiony na satysfakcję.' },
        { key: 'languages', title: 'Obsługa ponad 50 języków', desc: 'Szeroki zakres par językowych.' },
        { key: 'terms', title: 'System płatności odroczonych dla firm', desc: 'Elastyczne płatności dla firm.' },
      ],
    },
    corporateCta: {
      title: 'Rozwiązania dla firm',
      desc: 'Profesjonalne usługi językowe z zarządzaniem terminologią, opcjami płatności odroczonych i dedykowanym opiekunem klienta dostosowanym do Państwa firmy.',
      action: 'Zamów wycenę firmową',
    },
    partnershipTeaser: {
      title: 'Program partnerski',
      subtitle: 'Zarabiaj 20% prowizji od każdego poleconego nam klienta.',
      items: [
        { key: 'commission', title: 'Przejrzysta prowizja', desc: '20% prowizji za każde polecenie (zgodnie z umową). Przejrzyste zarobki dzięki panelowi śledzenia w czasie rzeczywistym.' },
        { key: 'qr', title: 'System kodów QR', desc: 'Łatwe śledzenie klientów dzięki integracji z wizytówką. Kody QR do strony internetowej i WhatsApp.' },
      ],
      cta: 'Zgłoś się jako partner',
    },
    testimonials: {
      title: 'Opinie klientów',
      subtitle: 'Prawdziwe opinie klientów zostaną tu dodane przed uruchomieniem.',
      placeholderNote: 'Element zastępczy — zostaną dodane prawdziwe opinie.',
      items: [
        { key: 't1', role: 'Kancelaria prawna' },
        { key: 't2', role: 'Placówka medyczna' },
        { key: 't3', role: 'Klient firmowy' },
        { key: 't4', role: 'Klient indywidualny' },
      ],
    },
    blogTeaser: {
      title: 'Blog',
      subtitle: 'Aktualne treści ze świata tłumaczeń',
      viewAll: 'Zobacz wszystkie wpisy na blogu',
    },
    finalCta: {
      title: 'Zacznij już teraz',
      desc: 'Prześlij dokumenty, otrzymaj natychmiastową wycenę i skorzystaj z profesjonalnych usług tłumaczeniowych.',
      primary: 'Uzyskaj wycenę',
      secondary: 'Skontaktuj się z nami',
    },
  },

  services: {
    seo: {
      title: 'Usługi tłumaczeniowe',
      description:
        'Tłumaczenia przysięgłe, poświadczone notarialnie, prawnicze, techniczne, medyczne i akademickie oraz lokalizacja stron internetowych i aplikacji mobilnych. Rodzaje dokumentów, proces, realizacja i pary językowe.',
    },
    hero: {
      title: 'Usługi tłumaczeniowe',
      subtitle: 'Tłumaczenie z właściwą terminologią dla każdej dziedziny specjalizacji.',
    },
    process: {
      title: 'Jak przebiega proces?',
      steps: [
        { title: 'Analiza dokumentu', desc: 'Oceniamy rodzaj i przeznaczenie dokumentu.' },
        { title: 'Dobór specjalisty', desc: 'Przydzielany jest tłumacz specjalizujący się w danej dziedzinie.' },
        { title: 'Tłumaczenie i redakcja', desc: 'Tłumaczenie oraz niezależna korekta końcowa.' },
        { title: 'Poświadczenie i dostawa', desc: 'W razie potrzeby poświadczenie notarialne/apostille, a następnie dostawa.' },
      ],
    },
    delivery: {
      title: 'Opcje dostawy',
      items: ['Dostawa cyfrowa (PDF/DOCX)', 'Dostawa fizyczna dokumentu', 'Dostawa ekspresowa'],
    },
    notaryApostille: {
      title: 'Powiązanie poświadczenia notarialnego i apostille',
      desc: 'W razie potrzeby tłumaczenie przysięgłe uzyskuje ważność dla instytucji urzędowych poprzez poświadczenie notarialne i proces apostille. Dokładny wymóg zależy od instytucji, do której dokument zostanie złożony.',
    },
    fullService: {
      title: 'Kompleksowo, z dostawą pod drzwi',
      note: 'Prześlij nam swoje dokumenty, a my zajmiemy się całym procesem — obejmującym tłumaczenie, poświadczenie notarialne i apostille. Gotowe dokumenty dotrą pod Państwa drzwi kurierem. Skup się na swojej pracy, a resztę zostaw nam.',
    },
    cta: {
      title: 'Nie wiesz, której usługi potrzebujesz?',
      desc: 'Prześlij dokument, a wskażemy Ci najodpowiedniejszą usługę i cenę.',
    },
    documentTypesTitle: 'Odpowiednie rodzaje dokumentów',
  },

  serviceItems: {
    sworn: {
      name: 'Tłumaczenie przysięgłe',
      short: 'Urzędowo ważne tłumaczenie z podpisem i pieczęcią tłumacza przysięgłego.',
      benefits: ['Ważne w instytucjach urzędowych', 'Poświadczenie tłumacza przysięgłego', 'Szybki proces'],
    },
    notarized: {
      name: 'Tłumaczenie z poświadczeniem notarialnym',
      short: 'Poświadczenie notarialne tłumaczenia przysięgłego.',
      benefits: ['Poświadczenie notarialne', 'Odpowiednie do wniosków urzędowych', 'Zajmujemy się całym procesem'],
    },
    apostille: {
      name: 'Wsparcie w procesie apostille',
      short: 'Wsparcie w procesie apostille zapewniającym ważność za granicą.',
      benefits: ['Ważność międzynarodowa', 'Doradztwo w procesie', 'Wskazówki dotyczące instytucji'],
    },
    legal: {
      name: 'Tłumaczenie prawnicze',
      short: 'Tłumaczenie z biegłą znajomością terminologii dla umów oraz dokumentów sądowych i urzędowych.',
      benefits: ['Terminologia prawnicza', 'Zapewnienie poufności', 'Doświadczony tłumacz'],
    },
    technical: {
      name: 'Tłumaczenie techniczne',
      short: 'Spójne tłumaczenie instrukcji, specyfikacji i dokumentów technicznych.',
      benefits: ['Zarządzanie terminologią', 'Zachowany format', 'Znajomość branży'],
    },
    medical: {
      name: 'Tłumaczenie medyczne',
      short: 'Precyzyjne tłumaczenie raportów, ulotek i dokumentów medycznych.',
      benefits: ['Terminologia medyczna', 'Nacisk na dokładność', 'Poufność'],
    },
    academic: {
      name: 'Tłumaczenie akademickie',
      short: 'Język akademicki dla prac dyplomowych, artykułów i tłumaczeń dyplomów.',
      benefits: ['Styl akademicki', 'Spójność ze źródłem', 'Terminowa realizacja'],
    },
    localization: {
      name: 'Lokalizacja stron internetowych i aplikacji mobilnych',
      short: 'Odpowiednia kulturowo lokalizacja stron internetowych i aplikacji.',
      benefits: ['Adaptacja kulturowa', 'Integracja techniczna', 'Zgodność z SEO'],
    },
  },

  corporate: {
    statsLabels: {
      corporate: 'Klienci firmowi',
      discount: 'Rabat na zamówienia hurtowe',
      term: 'Termin płatności',
    },
    seo: {
      title: 'Rozwiązania dla firm',
      description:
        'Profesjonalne usługi językowe dla firm z zarządzaniem terminologią, opcjami płatności odroczonych, zamówieniami hurtowymi i dedykowanym opiekunem klienta.',
    },
    hero: {
      title: 'Rozwiązania dla firm',
      subtitle:
        'Profesjonalne usługi językowe z zarządzaniem terminologią, opcjami płatności odroczonych i dedykowanym opiekunem klienta dostosowanym do Państwa firmy.',
      primaryCta: 'Zamów wycenę firmową',
      secondaryCta: 'Wyślij e-mail',
    },
    features: {
      title: 'Funkcje dla firm',
      subtitle: 'Rozwiązania dostosowane do Twojej działalności',
      items: [
        {
          key: 'custom',
          icon: 'Target',
          title: 'Usługa na zamówienie',
          points: ['Stała terminologia', 'Zachowanie tonu komunikacji marki', 'Dedykowany opiekun klienta', 'Opracowanie przewodnika stylu'],
        },
        {
          key: 'volume',
          icon: 'BarChart3',
          title: 'Obsługa hurtowa i płatności odroczone',
          points: ['Miesięczne plany tłumaczeń', 'Rabaty na zamówienia hurtowe', 'Płatność odroczona do 30 dni', 'System fakturowania'],
        },
        {
          key: 'security',
          icon: 'Lock',
          title: 'Prywatność i bezpieczeństwo',
          points: ['Protokół NDA', 'Szyfrowany transfer plików', 'Procesy zgodne z KVKK'],
        },
      ],
    },
    whyPackage: {
      title: 'Dlaczego pakiet firmowy?',
      items: [
        {
          key: 'terminology',
          icon: 'Building2',
          title: 'Zarządzanie stałą terminologią',
          desc: 'Tworzymy bazę terminów specyficzną dla Państwa firmy. Język Państwa marki jest zachowany we wszystkich tłumaczeniach, a my dbamy o spójność. Zwracamy uwagę, aby w każdym projekcie stosować te same terminy.',
        },
        {
          key: 'manager',
          icon: 'Users',
          title: 'Dedykowany opiekun klienta',
          desc: 'Państwa dedykowany opiekun klienta nadzoruje wszystkie procesy. Dzięki dostępnej linii wsparcia jesteśmy przy Państwu w pilnych sytuacjach.',
        },
        {
          key: 'security',
          icon: 'ShieldCheck',
          title: 'Prywatność i bezpieczeństwo',
          desc: 'Pracujemy w oparciu o protokół NDA. Państwa dane są bezpieczne dzięki silnej infrastrukturze zabezpieczeń, szyfrowanemu transferowi plików i procesom zgodnym z KVKK.',
        },
      ],
    },
    payment: {
      title: 'Opcje płatności',
      subtitle: 'Elastyczne plany płatności dostosowane do Twojej działalności',
      recommendedLabel: 'ZALECANE',
      options: [
        {
          key: 'standard',
          label: 'Płatność natychmiastowa',
          heading: 'Standard',
          desc: 'Płatność kartą kredytową lub przelewem bankowym po każdym zamówieniu',
          points: ['Raty na karcie kredytowej', 'Natychmiastowa realizacja'],
          recommended: false,
        },
        {
          key: 'term',
          label: 'Płatność odroczona miesięczna',
          heading: '15-30 dni',
          desc: 'Miesięczne zbiorcze fakturowanie i opcja płatności odroczonej',
          points: ['Termin płatności 30 dni', 'Rabat hurtowy', 'Raport miesięczny'],
          recommended: true,
        },
      ],
    },
    form: {
      title: 'Wniosek o pakiet firmowy',
      desc: 'Wypełnij formularz, a nasz zespół ekspertów skontaktuje się z Tobą',
      fields: {
        company: 'Nazwa firmy',
        contactName: 'Imię i nazwisko osoby kontaktowej',
        email: 'E-mail',
        phone: 'Telefon',
        need: 'Opowiedz nam o swoich potrzebach tłumaczeniowych',
        consent: 'Zapoznałem/am się z Klauzulą informacyjną KVKK i akceptuję ją.',
      },
      submit: 'Wyślij wniosek',
      success: 'Państwa wniosek został przyjęty. Skontaktujemy się z Państwem najszybciej, jak to możliwe.',
      note: 'Skontaktujemy się z Państwem w ciągu 1 dnia roboczego.',
    },
  },

  partnership: {
    seo: {
      title: 'Program partnerski',
      description:
        'Zarabiaj prowizję od każdego poleconego klienta. Przejrzyste raportowanie, polecenia z kodem QR i profesjonalne wsparcie.',
    },
    hero: {
      title: 'Program partnerski',
      value: 'Zarabiaj 20% prowizji od każdego poleconego nam klienta.',
      subtitle: 'Przejrzysty system, niezawodne płatności, długoterminowa współpraca.',
      cta: 'Zgłoś się teraz',
    },
    advantages: {
      title: 'Korzyści dla partnerów',
      subtitle: 'Dlaczego warto zostać partnerem TercümExpert?',
      items: [
        { key: 'commission', icon: 'Wallet', title: 'Gwarancja 20% prowizji', desc: 'Przejrzysty system prowizji za każdego poleconego klienta.' },
        { key: 'qr', icon: 'QrCode', title: 'Polecenie z kodem QR', desc: 'Łatwe śledzenie klientów dzięki integracji z wizytówką.' },
        { key: 'reporting', icon: 'BarChart3', title: 'Przejrzyste raportowanie', desc: 'Panel śledzenia prowizji i klientów w czasie rzeczywistym.' },
        { key: 'support', icon: 'Users', title: 'Profesjonalne wsparcie', desc: 'Dedykowana linia wsparcia dla partnerów i opiekun klienta.' },
      ],
    },
    howItWorks: {
      title: 'Jak to działa?',
      steps: [
        { title: 'Zgłoś się', desc: 'Wypełnij formularz zgłoszeniowy online. Podaj informacje o swojej firmie i dane kontaktowe. Twoje zgłoszenie jest rozpatrywane w ciągu 1 dnia roboczego.' },
        { title: 'Zostań partnerem', desc: 'Po zatwierdzeniu zgłoszenia uzyskujesz dostęp do dedykowanego panelu partnera. Twoje kody QR i linki polecające są gotowe.' },
        { title: 'Polecaj klientów', desc: 'Polecaj nam swoich klientów za pomocą kodu QR, dedykowanego linku lub wizytówki. Każde polecenie jest automatycznie rejestrowane w systemie.' },
        { title: 'Zarabiaj prowizję', desc: 'Zarabiasz 20% prowizji za każdym razem, gdy polecony przez Ciebie klient złoży zamówienie. Automatyczne płatności otrzymujesz co 15 dni.' },
      ],
    },
    sectors: {
      title: 'Sektory docelowe',
      subtitle: 'Dla których sektorów jest to idealne rozwiązanie?',
      items: [
        { key: 'law', icon: 'Scale', title: 'Kancelarie prawne', desc: 'Potrzeba tłumaczeń przysięgłych akt spraw, umów i dokumentów prawnych.' },
        { key: 'visa', icon: 'Plane', title: 'Doradztwo wizowe', desc: 'Dokumenty wymagające tłumaczenia przysięgłego, takie jak paszporty, dyplomy i akty stanu cywilnego.' },
        { key: 'education', icon: 'GraduationCap', title: 'Doradztwo edukacyjne', desc: 'Tłumaczenia przysięgłe dokumentów uczniów i procesy apostille.' },
        { key: 'health', icon: 'HeartPulse', title: 'Turystyka medyczna', desc: 'Tłumaczenie raportów medycznych, akt pacjentów i dokumentów zdrowotnych.' },
        { key: 'patent', icon: 'Building2', title: 'Kancelarie patentowe/rzecznicze', desc: 'Tłumaczenie techniczne patentów, dokumentów rejestracji znaków towarowych i dokumentów prawnych.' },
        { key: 'realestate', icon: 'Home', title: 'Biura nieruchomości', desc: 'Tłumaczenie aktów własności, umów i dokumentów urzędowych dla inwestorów zagranicznych.' },
        { key: 'hr', icon: 'Briefcase', title: 'Doradztwo HR', desc: 'Tłumaczenie CV, dyplomów i listów referencyjnych na potrzeby zatrudnienia za granicą.' },
        { key: 'software', icon: 'Code', title: 'Firmy programistyczne', desc: 'Lokalizacja stron internetowych i aplikacji mobilnych, tłumaczenie dokumentacji technicznej.' },
      ],
    },
    commission: {
      title: 'Struktura prowizji',
      stats: {
        commissionLabel: 'Standardowa prowizja',
        commissionSub: 'Od każdego zamówienia',
        periodUnit: 'Dni',
        periodLabel: 'Okres płatności',
        feeLabel: 'Opłata początkowa',
        feeSub: 'Całkowicie bezpłatnie',
      },
      exampleTitle: 'Przykładowe obliczenie zarobków',
      exampleOrderLabel: 'Zamówienie od poleconego klienta',
      exampleRateLabel: 'Stawka prowizji',
      exampleEarningLabel: 'Twoje zarobki',
      note: 'Stawki prowizji i warunki podlegają umowie partnerskiej.',
    },
    form: {
      title: 'Formularz zgłoszeniowy partnera',
      subtitle: 'Wypełnij formularz, a skontaktujemy się z Tobą w ciągu 1 dnia roboczego.',
      fields: {
        company: 'Nazwa firmy/organizacji',
        sector: 'Sektor',
        contactName: 'Imię i nazwisko osoby kontaktowej',
        titleRole: 'Stanowisko',
        email: 'E-mail',
        phone: 'Telefon',
        potential: 'Twój szacowany miesięczny potencjał poleceń',
        note: 'Uwagi, które chcesz dodać',
        agreement: 'Zapoznałem/am się z warunkami umowy partnerskiej i akceptuję je.',
      },
      sectorPlaceholder: 'Wybierz',
      sectorOptions: ['Kancelaria prawna', 'Doradztwo wizowe', 'Doradztwo edukacyjne', 'Turystyka medyczna', 'Kancelaria patentowa/rzecznicza', 'Nieruchomości', 'Doradztwo HR', 'Oprogramowanie', 'Inne'],
      potentialOptions: ['1-5 klientów', '5-10 klientów', '10-20 klientów', 'ponad 20 klientów'],
      submit: 'Wyślij zgłoszenie',
      success: 'Państwa zgłoszenie zostało przyjęte. Skontaktujemy się z Państwem.',
      note: 'Państwa zgłoszenie zostanie rozpatrzone w ciągu 1 dnia roboczego.',
    },
  },

  quote: {
    seo: {
      title: 'Natychmiastowe obliczanie ceny',
      description: 'Prześlij dokument lub wprowadź dane i otrzymaj natychmiastową wstępną wycenę.',
    },
    hero: {
      title: 'Natychmiastowe obliczanie ceny',
      subtitle: 'Prześlij dokument lub wprowadź dane i otrzymaj natychmiastową wstępną wycenę.',
    },
    upload: {
      heading: 'Prześlij swoje dokumenty',
      privacy: 'Państwa dane są traktowane jako poufne',
      tabFile: 'Prześlij plik',
      tabText: 'Wprowadź tekst',
      chooseFile: 'Wybierz swoje dokumenty',
      formats: '.docx, .xlsx, .pdf, .pptx, .jpg, .png i ponad 50 formatów · Maks. 100MB na plik',
      dropHint: 'Możesz przeciągnąć i upuścić jeden lub więcej plików w tym obszarze.',
      textPlaceholder: 'Wklej lub wpisz tutaj swój tekst…',
      totalWords: 'Łączna liczba słów',
      extracting: 'Liczenie słów…',
      wordsUnit: 'słów',
      remove: 'Usuń',
      unsupported:
        'Automatyczne liczenie słów nie było możliwe dla tego typu pliku. Proszę wkleić tekst za pomocą opcji „Wprowadź tekst”; liczba słów zostanie zweryfikowana przez nasz zespół podczas wyceny.',
      empty:
        'W pliku nie znaleziono zaznaczalnego tekstu (może to być skan/obraz). Proszę skorzystać z opcji „Wprowadź tekst”, w przeciwnym razie liczba słów zostanie zweryfikowana podczas wyceny.',
      error: 'Nie udało się odczytać pliku. Proszę spróbować ponownie lub skorzystać z opcji „Wprowadź tekst”.',
      tooLarge: 'Plik nie może być większy niż 100MB.',
      needInput: 'Aby otrzymać cenę, proszę przesłać plik lub wprowadzić tekst.',
    },
    fields: {
      upload: 'Prześlij dokument (opcjonalnie)',
      uploadHint: 'PDF, DOC, DOCX lub TXT — maks. 10 MB',
      sourceLang: 'Język źródłowy',
      targetLang: 'Język docelowy',
      serviceType: 'Rodzaj usługi',
      documentType: 'Rodzaj dokumentu',
      wordCount: 'Szacowana liczba słów',
      wordCountHint: 'Użyj suwaka lub wprowadź liczbę ręcznie.',
      options: 'Usługi dodatkowe',
      calculate: 'Oblicz cenę',
    },
    options: {
      urgent: 'Dostawa ekspresowa',
      notarization: 'Poświadczenie notarialne',
      physicalDelivery: 'Dostawa fizyczna',
    },
    languages: {
      tr: 'Turecki',
      en: 'Angielski',
      de: 'Niemiecki',
      fr: 'Francuski',
      es: 'Hiszpański',
      it: 'Włoski',
      ru: 'Rosyjski',
      ar: 'Arabski',
      nl: 'Niderlandzki',
      az: 'Azerski',
      pl: 'Polski',
      bg: 'Bułgarski',
      pt: 'Portugalski',
      da: 'Duński',
    },
    documentTypes: {
      diploma: 'Dyplom',
      passport: 'Paszport',
      'civil-registry': 'Odpis aktu stanu cywilnego',
      contract: 'Umowa',
      'medical-report': 'Raport medyczny',
      'technical-doc': 'Dokument techniczny',
      'court-doc': 'Dokument sądowy',
      other: 'Inne',
    },
    result: {
      title: 'Wstępna wycena',
      basePrice: 'Podstawowa opłata za usługę',
      wordPrice: 'Opłata za słowa',
      addons: 'Usługi dodatkowe',
      total: 'Razem',
      vat: 'VAT',
      delivery: 'Szacowany czas realizacji',
      deliveryUnit: 'dni roboczych',
      disclaimer: 'Jest to wstępna wycena; cena ostateczna jest potwierdzana po analizie dokumentu.',
      order: 'Złóż zamówienie',
      whatsapp: 'Kontakt przez WhatsApp',
      estimatedWords: 'Szacowana liczba słów (automatycznie — demo)',
    },
    orderConfirm: {
      title: 'Państwa zamówienie zostało przyjęte',
      number: 'Nr zamówienia',
      desc: 'Państwa zgłoszenie i dokumenty zostały zapisane. Nasz zespół ekspertów przeanalizuje dokument i skontaktuje się z Państwem najszybciej, jak to możliwe.',
      viewOrders: 'Moje zamówienia',
      submitting: 'Tworzenie zamówienia…',
      error: 'Wystąpił problem podczas tworzenia zamówienia. Proszę spróbować ponownie.',
    },
    gate: {
      title: 'Państwa cena jest gotowa',
      subtitle: 'Zaloguj się lub zweryfikuj swoje dane, aby zobaczyć cenę i złożyć zamówienie.',
      loginCta: 'Zaloguj się / Zarejestruj się',
      or: 'lub kontynuuj szybko',
      firstName: 'Imię',
      lastName: 'Nazwisko',
      email: 'E-mail',
      sendCode: 'Wyślij kod weryfikacyjny',
      codeLabel: 'Kod weryfikacyjny',
      codeSentA: 'otrzymał(a) kod weryfikacyjny.',
      verify: 'Zweryfikuj i zobacz cenę',
      resend: 'Wyślij kod ponownie',
      resent: 'Wysłano nowy kod.',
      back: 'Zmień dane',
      errNames: 'Imię i nazwisko są wymagane.',
      errEmail: 'Wprowadź prawidłowy adres e-mail.',
      errCode: 'Proszę wprowadzić pełny kod.',
      note: 'Państwa adres e-mail jest wykorzystywany wyłącznie do wyceny i zamówienia.',
    },
    note: {
      label: 'Uwaga do zamówienia (opcjonalnie)',
      placeholder: 'Tutaj możesz zapisać swoje życzenia dotyczące dostawy, terminologii lub inne specjalne prośby.',
    },
  },

  order: {
    seo: {
      title: 'Śledzenie zamówienia',
      description: 'Śledź status swojego zamówienia.',
    },
    numberLabel: 'Nr zamówienia',
    placedOn: 'Data zamówienia',
    estimatedLabel: 'Szacowana dostawa tłumaczenia',
    cargoEstimatedLabel: 'Szacowana data wysyłki',
    timelineTitle: 'Status zamówienia',
    steps: {
      received: 'Państwa zamówienie zostało przyjęte',
      in_progress: 'W trakcie realizacji',
      translated: 'Tłumaczenie ukończone',
      shipped: 'Wysłano',
      delivered: 'Dostarczono',
      cancelled: 'Zamówienie anulowane',
    },
    stepDesc: {
      received: 'Państwa zgłoszenie i dokumenty dotarły do naszego systemu. Nasz zespół ekspertów przeanalizuje je i wkrótce rozpocznie pracę.',
      in_progress: 'Nasz doświadczony tłumacz rozpoczął pracę nad Państwa tłumaczeniem.',
      translated: 'Państwa tłumaczenie jest gotowe, a kontrole końcowe zostały wykonane.',
      shipped: 'Państwa dokument został przekazany kurierowi; możesz go śledzić za pomocą przycisku poniżej.',
      delivered: 'Państwa dokument został wysłany do Państwa pocztą elektroniczną.',
      cancelled: 'To zamówienie zostało anulowane. W razie pytań prosimy o kontakt.',
    },
    cargoReady: 'Państwa dokument został wysłany. Śledź go jednym dotknięciem:',
    cargoPending: 'Kod śledzenia pojawi się tutaj po wysłaniu Państwa dokumentu.',
    trackCargo: 'Śledź moją przesyłkę',
    digitalPending: 'Po ukończeniu Państwa tłumaczenia pliki zostaną wysłane do Państwa pocztą elektroniczną.',
    digitalDelivered: 'Państwa tłumaczenie zostało wysłane do Państwa pocztą elektroniczną. Proszę sprawdzić skrzynkę odbiorczą (oraz folder ze spamem).',
    detailsTitle: 'Szczegóły zamówienia',
    fields: {
      service: 'Usługa',
      langs: 'Języki',
      documentType: 'Rodzaj dokumentu',
      words: 'Słowa',
      delivery: 'Szacowany czas',
      total: 'Kwota',
      note: 'Państwa uwaga',
    },
    myOrders: 'Moje zamówienia',
    backHome: 'Powrót do strony głównej',
    whatsapp: 'Kontakt przez WhatsApp',
    loading: 'Ładowanie zamówienia…',
    loginRequired: {
      title: 'Zaloguj się, aby zobaczyć swoje zamówienie',
      desc: 'Dostęp do szczegółów zamówienia jest możliwy wyłącznie po zalogowaniu się na swoje konto.',
      login: 'Zaloguj się',
    },
    notFound: {
      title: 'Nie znaleziono zamówienia',
      desc: 'Ten numer zamówienia nie należy do Ciebie lub nie istnieje. Proszę sprawdzić link.',
      home: 'Powrót do strony głównej',
    },
  },

  faq: {
    seo: {
      title: 'Najczęściej zadawane pytania',
      description: 'Najczęściej zadawane pytania dotyczące tłumaczeń przysięgłych, czasu realizacji, cennika, poświadczenia notarialnego i płatności odroczonych dla firm.',
    },
    hero: { title: 'Najczęściej zadawane pytania', subtitle: 'Odpowiedź, której szukasz, jest tutaj.' },
    categoriesTitle: 'Kategorie',
    searchPlaceholder: 'Szukaj pytań lub słów kluczowych…',
    empty: 'Żadne pytanie nie pasuje do Twojego wyszukiwania. Spróbuj innego słowa lub skontaktuj się z nami.',
    categories: FAQ_CATEGORIES_PL,
    items: FAQ_ITEMS_PL,
    notFound: {
      title: 'Nie znalazłeś odpowiedzi na swoje pytanie?',
      contact: 'Skontaktuj się z nami',
      whatsapp: 'Wsparcie WhatsApp',
    },
  },

  contact: {
    seo: {
      title: 'Kontakt',
      description: 'Skontaktuj się z TercümExpert: telefon, e-mail, WhatsApp i formularz kontaktowy.',
    },
    hero: { title: 'Kontakt', subtitle: 'Jak możemy Ci pomóc?' },
    infoTitle: 'Informacje kontaktowe',
    labels: {
      phone: 'Telefon',
      email: 'E-mail',
      whatsapp: 'WhatsApp',
      address: 'Adres',
      hours: 'Godziny pracy',
    },
    form: {
      title: 'Skontaktuj się z nami',
      fields: {
        name: 'Imię i nazwisko',
        email: 'E-mail',
        phone: 'Telefon',
        subject: 'Temat',
        message: 'Wiadomość',
        consent: 'Zapoznałem/am się z Klauzulą informacyjną KVKK i akceptuję ją.',
      },
      submit: 'Wyślij wiadomość',
      success: 'Państwa wiadomość została przyjęta. Skontaktujemy się z Państwem wkrótce.',
    },
    map: {
      title: 'Nasza lokalizacja',
      subtitle: 'Znajdź nas na mapie',
      placeholder: 'Obszar mapy',
      note: 'Mapa lokalizacji pojawi się tutaj wkrótce.',
    },
  },

  auth: {
    seo: {
      title: 'Zaloguj się / Zarejestruj się',
      description: 'Zaloguj się na swoje konto TercümExpert lub utwórz nowe.',
    },
    tabs: { login: 'Zaloguj się', register: 'Zarejestruj się' },
    google: 'Kontynuuj z Google',
    or: 'lub',
    fields: {
      firstName: 'Imię',
      lastName: 'Nazwisko',
      email: 'E-mail',
      password: 'Hasło',
      code: 'Kod weryfikacyjny',
    },
    login: {
      title: 'Zaloguj się na swoje konto',
      submit: 'Zaloguj się',
      noAccount: 'Nie masz konta?',
      switchToRegister: 'Zarejestruj się',
    },
    register: {
      title: 'Utwórz nowe konto',
      submit: 'Zarejestruj się',
      haveAccount: 'Masz już konto?',
      switchToLogin: 'Zaloguj się',
      consent: 'Tworząc konto, akceptuję Klauzulę informacyjną KVKK oraz Politykę prywatności.',
    },
    verify: {
      title: 'Zweryfikuj swój adres e-mail',
      desc: '— wprowadź 6-cyfrowy kod, który wysłaliśmy na ten adres.',
      submit: 'Zweryfikuj i kontynuuj',
      spam: 'Kod może dotrzeć z kilkuminutowym opóźnieniem; proszę sprawdzić także folder ze spamem/wiadomościami-śmieciami.',
      resend: 'Wyślij kod ponownie',
      resent: 'Wysłano nowy kod.',
      back: 'Wróć',
    },
    signedIn: {
      title: 'Moje konto',
      greeting: 'Witamy',
      logout: 'Wyloguj się',
    },
    orders: {
      title: 'Moje zamówienia',
      empty: 'Nie masz jeszcze żadnych zamówień. Możesz utworzyć swoje pierwsze zamówienie za pomocą opcji Oblicz cenę.',
      loading: 'Ładowanie zamówień…',
      error: 'Nie udało się załadować zamówień. Proszę odświeżyć stronę.',
      status: {
        received: 'Przyjęto',
        in_progress: 'W trakcie realizacji',
        translated: 'Tłumaczenie ukończone',
        shipped: 'Wysłano',
        delivered: 'Dostarczono',
        cancelled: 'Anulowano',
      },
      track: 'Śledź',
    },
    errors: {
      nameRequired: 'Imię i nazwisko są wymagane.',
      emailInvalid: 'Wprowadź prawidłowy adres e-mail.',
      passwordShort: 'Hasło musi mieć co najmniej 6 znaków.',
      codeInvalid: 'Proszę wprowadzić 6-cyfrowy kod.',
      consentRequired: 'Do kontynuowania wymagana jest akceptacja.',
    },
  },

  blog: {
    seo: { title: 'Blog', description: 'Treści poradnikowe dotyczące tłumaczeń, poświadczenia notarialnego, apostille i lokalizacji.' },
    hero: { title: 'Blog', subtitle: 'Poradniki ze świata tłumaczeń.' },
    searchPlaceholder: 'Szukaj wpisów…',
    readingTime: 'min czytania',
    relatedTitle: 'Powiązane wpisy',
    allCategories: 'Wszystkie',
    empty: 'Żaden wpis nie pasuje do tego kryterium.',
  },

  legal: {
    lastUpdatedLabel: 'Ostatnia aktualizacja',
    draftNotice:
      'Niniejszy tekst jest projektem i przed publikacją powinien zostać sprawdzony przez eksperta prawnego. Informacje o firmie nie zostały jeszcze zweryfikowane.',
    kvkk: {
      seo: { title: 'Klauzula informacyjna KVKK', description: 'Klauzula informacyjna dotycząca ochrony danych osobowych.' },
      title: 'Klauzula informacyjna KVKK',
      sections: [
        { heading: 'Administrator danych', body: 'Administrator danych i informacje kontaktowe zostaną dodane przed uruchomieniem.' },
        { heading: 'Przetwarzane dane osobowe', body: 'Podczas procesów kontaktu i zamówienia mogą być przetwarzane dane takie jak imię i nazwisko, informacje kontaktowe oraz dane dokumentów.' },
        { heading: 'Cele przetwarzania', body: 'Świadczenie usług, wyceny, komunikacja oraz obowiązki prawne.' },
        { heading: 'Podstawy prawne', body: 'Wykonanie umowy, wyraźna zgoda oraz prawnie uzasadniony interes.' },
        { heading: 'Okresy przechowywania', body: 'Dane są przechowywane przez okresy przewidziane w odpowiednich przepisach.' },
        { heading: 'Przekazywanie', body: 'Przekazywane wyłącznie w zakresie niezbędnym do świadczenia usługi i zgodnie z przepisami.' },
        { heading: 'Państwa prawa', body: 'Mogą Państwo korzystać z praw wynikających z art. 11 KVKK.' },
        { heading: 'Jak złożyć wniosek', body: 'Mogą Państwo składać swoje żądania za pośrednictwem wskazanych kanałów kontaktowych.' },
      ],
    },
    privacy: {
      seo: { title: 'Polityka prywatności', description: 'Polityka dotycząca poufności danych osobowych i dokumentów.' },
      title: 'Polityka prywatności',
      sections: [
        { heading: 'Gromadzone informacje', body: 'Informacje kontaktowe oraz przesłane dokumenty.' },
        { heading: 'Wykorzystanie', body: 'Wykorzystywane wyłącznie do świadczenia usług i komunikacji.' },
        { heading: 'Bezpieczeństwo dokumentów', body: 'Dokumenty są przetwarzane z zachowaniem zasad szyfrowanego transferu i poufności.' },
        { heading: 'Pliki cookie', body: 'Szczegóły znajdują się w Polityce plików cookie.' },
      ],
    },
    distanceSales: {
      seo: { title: 'Umowa sprzedaży na odległość', description: 'Umowa sprzedaży na odległość dotycząca sprzedaży usług.' },
      title: 'Umowa sprzedaży na odległość',
      sections: [
        { heading: 'Strony', body: 'Informacje o sprzedawcy i kupującym zostaną dodane przed uruchomieniem.' },
        { heading: 'Zakres usługi', body: 'Zakres zamówionych usług tłumaczenia/poświadczenia.' },
        { heading: 'Prawo odstąpienia i wyjątki', body: 'Wyjątki od prawa odstąpienia mogą dotyczyć usług przygotowanych specjalnie dla danej osoby/zamówienia.' },
        { heading: 'Zwroty i anulowanie', body: 'Warunki zwrotów i anulowania są określone tutaj.' },
      ],
    },
    cookies: {
      seo: { title: 'Polityka plików cookie', description: 'Kategorie plików cookie używanych na stronie i zarządzanie preferencjami.' },
      title: 'Polityka plików cookie',
      sections: [
        { heading: 'Czym jest plik cookie?', body: 'Pliki cookie to niewielkie pliki przechowywane w Twojej przeglądarce.' },
        { heading: 'Kategorie', body: 'Pliki cookie niezbędne, analityczne, marketingowe i preferencji.' },
        { heading: 'Zarządzanie preferencjami', body: 'Możesz w każdej chwili zaktualizować swoje preferencje dotyczące plików cookie.' },
      ],
    },
  },

  footer: {
    tagline: 'Państwa niezawodny partner w profesjonalnych usługach tłumaczeniowych.',
    columns: {
      quickLinks: 'Szybkie linki',
      services: 'Usługi',
      contact: 'Kontakt',
    },
    quickLinks: {
      corporate: 'Dla firm',
      services: 'Nasze usługi',
      quote: 'Oblicz cenę',
      blog: 'Blog',
      faq: 'Najczęściej zadawane pytania',
      contact: 'Kontakt',
    },
    serviceLinks: {
      sworn: 'Tłumaczenie przysięgłe',
      notarized: 'Tłumaczenie z poświadczeniem notarialnym',
      apostille: 'Proces apostille',
      corporate: 'Rozwiązania dla firm',
      partnership: 'Program partnerski',
    },
    legal: {
      kvkk: 'KVKK',
      privacy: 'Polityka prywatności',
      distanceSales: 'Umowa sprzedaży na odległość',
      cookies: 'Polityka plików cookie',
    },
    socialTitle: 'Obserwuj nas',
    whatsapp: 'Wsparcie WhatsApp',
    rights: 'Wszelkie prawa zastrzeżone.',
  },

  cookie: {
    title: 'Preferencje plików cookie',
    desc: 'Używamy plików cookie, aby poprawić Państwa doświadczenie. Pliki cookie inne niż niezbędne działają wyłącznie za Państwa zgodą.',
    accept: 'Akceptuj',
    reject: 'Odrzuć',
    manage: 'Zarządzaj preferencjami',
    save: 'Zapisz preferencje',
    categories: {
      necessary: { label: 'Niezbędne', desc: 'Wymagane do działania strony; nie można ich wyłączyć.' },
      analytics: { label: 'Analityczne', desc: 'Pomagają nam zrozumieć sposób korzystania.' },
      marketing: { label: 'Marketingowe', desc: 'Do odpowiednich treści i reklam.' },
      preferences: { label: 'Preferencji', desc: 'Zapamiętują Państwa preferencje.' },
    },
  },

  chatbot: {
    title: 'Wsparcie TercümExpert',
    open: 'Otwórz czat',
    close: 'Zamknij czat',
    minimize: 'Zminimalizuj',
    clear: 'Wyczyść rozmowę',
    inputPlaceholder: 'Wpisz swoją wiadomość…',
    send: 'Wyślij',
    typing: 'Pisze…',
    welcome:
      'Witamy w TercümExpert. Mogę pomóc w kwestiach tłumaczenia, cennika, poświadczenia notarialnego, apostille lub usług dla firm.',
    quickQuestions: [
      'Jak obliczana jest cena?',
      'Czym jest tłumaczenie przysięgłe?',
      'Chcę przesłać dokument',
      'Chcę uzyskać wycenę firmową',
      'Czy wymagane jest poświadczenie notarialne?',
      'Połącz mnie z konsultantem',
    ],
    handoff: 'Połącz z konsultantem',
    toWhatsapp: 'Przenieś na WhatsApp',
    disclaimer: 'Te informacje mają charakter ogólny; proszę potwierdzić dokładne wymogi w odpowiedniej instytucji.',
    sensitiveWarning:
      'Prosimy nie udostępniać wrażliwych danych osobowych za pośrednictwem tego czatu. Swoje dokumenty można przesłać przez bezpieczny obszar przesyłania.',
  },

  notFound: {
    seo: { title: 'Nie znaleziono strony', description: 'Nie udało się znaleźć szukanej strony.' },
    title: 'Nie znaleziono strony',
    desc: 'Szukana strona mogła zostać przeniesiona lub nigdy nie istniała.',
    home: 'Powrót do strony głównej',
  },
}
