import type { PartialDictionary } from '@/types/i18n'
import { FAQ_CATEGORIES_PL, FAQ_ITEMS_PL } from '@/content/faq-data.pl'

export const pl: PartialDictionary = {
  delivery: {
    "ready": "Twoje tłumaczenie jest gotowe",
    "download": "Pobierz tłumaczenie",
    "hint": "Twoje tłumaczenie zostało również wysłane na Twój adres e-mail. Sprawdź swoją skrzynkę odbiorczą (oraz folder ze spamem)."
  },

  partnerPanel: {
    qrDownload: "Pobierz kod QR",
    qrAlt: "Kod QR zaproszenia",
    colMembers: "Członkowie",
    sectorAll: "Wszystkie branże",
    back: "Wstecz",
    noPartners: "Brak partnerów.",
    "delPartner": "Usunięty partner",
    "banPartner": "Zablokowany partner",
    tabPayments: "Płatności",
    payHint: "Płatności są realizowane 2. i 17. dnia każdego miesiąca. W dniu płatności prosimy przesłać potwierdzenie każdego partnera i nacisnąć „Opłacono”; przycisk nie działa, dopóki nie przesłano potwierdzenia. Wyświetlane są tylko salda dostępne do wypłaty (po 7-dniowej blokadzie); partnerzy z saldem 0 nie są pokazywani.",
    noPayments: "Brak partnerów oczekujących na płatność.",
    paid: "Płatność zapisana, a partner powiadomiony.",
    noApplications: "Brak oczekujących wniosków.",
    approve: "Zatwierdź",
    reject: "Odrzuć",
    noIban: "Brak numerów IBAN oczekujących na zatwierdzenie.",
    approveIban: "Zatwierdź IBAN",
    adminTitle: "Zarządzanie partnerami",
    tabApplications: "Wnioski",
    tabIban: "Zatwierdzenia IBAN",
    tabPartners: "Partnerzy",
    colPartner: "Partner",
    colCompany: "Firma",
    partnerShareLabel: "Udział partnera",
    adminNet: "Pozostało (firma)",
    fltPartner: "Nazwa partnera",
    fltCompany: "Firma",
    yourEarning: "Państwa zarobek",
    tabAllOrders: "Wszystkie zamówienia",
    fltOrderNo: "Nr zamówienia",
    fltDateFrom: "Od",
    fltDateTo: "Do",
    custFilter: "Szukaj po nazwisku",
    custEmpty: "Nie pozyskali Państwo jeszcze żadnego członka. Prosimy udostępnić link z zaproszeniem.",
    colName: "Imię i nazwisko",
    colEmail: "E-mail",
    colPhone: "Telefon",
    colJoined: "Rejestracja",
    custOrderCount: "Zamówienia",
    custTotal: "Łączna kwota",
    ordEmpty: "Brak zamówień na tym etapie.",
    colOrderNo: "Zamówienie",
    colCustomer: "Klient",
    colService: "Usługa",
    colLangs: "Języki",
    colAmount: "Kwota",
    colDate: "Data",
    loadError: "Nie udało się załadować. Prosimy spróbować ponownie.",
    walPayInfo: "Państwa zarobki są dodawane do portfela po zakończeniu zlecenia; pozostają zablokowane przez 7 dni, a następnie stają się dostępne do wypłaty. Wypłaty dostępnego salda są realizowane 2. i 17. dnia każdego miesiąca.",
    ibanPending: "Państwa dane IBAN oczekują na zatwierdzenie przez administrację.",
    ibanPolicy: "Do czasu zatwierdzenia Państwa numeru IBAN i właściciela rachunku przez nasz zespół nie mogą Państwo otrzymywać płatności. W tym czasie Państwa zarobki nadal gromadzą się w portfelu. Po zatwierdzeniu danych mogą Państwo wypłacić środki, dla których upłynął 7-dniowy okres blokady od sprzedaży.",
    fillRequired: "Prosimy wypełnić wymagane pola.",
    phoneLockNote: "Numer telefonu będzie można zmienić po włączeniu weryfikacji SMS.",
    panelTitle: "Panel partnera",
    tabProfile: "Mój profil",
    tabCustomers: "Moi klienci",
    tabOrdersNew: "Otrzymane zamówienia",
    tabOrdersActive: "W realizacji",
    tabOrdersDelivery: "Oczekuje na dostawę",
    tabOrdersDone: "Zakończone",
    tabWallet: "Portfel",
    soon: "Już wkrótce.",
    save: "Zapisz",
    saved: "Zapisano.",
    statusApproved: "Zatwierdzony partner",
    ibanVerified: "IBAN zweryfikowany",
    ibanNotVerified: "IBAN niezweryfikowany",
    ibanReminder: "Prosimy podać IBAN i właściciela rachunku, aby móc otrzymywać płatności.",
    refCodeLabel: "Państwa kod zaproszenia",
    seoTitle: "Panel partnera",
    seoDesc: "Złóż wniosek partnerski i odbierz tutaj swój link z zaproszeniem.",
    loading: "Ładowanie…",
    loginTitle: "Logowanie partnera",
    loginDesc: "Prosimy zalogować się lub założyć konto, aby złożyć wniosek lub uzyskać dostęp do panelu.",
    login: "Zaloguj się / Zarejestruj się",
    setupTitle: "Konfiguracja niezakończona",
    setupDesc: "System partnerski nie jest jeszcze gotowy.",
    applyTitle: "Wniosek partnerski",
    applyDesc: "Prosimy uzupełnić dane; link z zaproszeniem zostanie aktywowany po zatwierdzeniu wniosku.",
    applyNote: "Wniosek zostanie wkrótce rozpatrzony.",
    sectorOther: "Prosimy podać branżę",
    submit: "Wyślij wniosek",
    submitting: "Wysyłanie…",
    saveError: "Nie udało się zapisać wniosku. Prosimy spróbować ponownie.",
    pendingTitle: "Wniosek otrzymany",
    pendingDesc: "Wniosek jest w trakcie weryfikacji. Po zatwierdzeniu link z zaproszeniem i panel zostaną tutaj aktywowane.",
    cancelApplication: "Anuluj wniosek",
    rejectedTitle: "Wniosek niezatwierdzony",
    rejectedDesc: "Ten wniosek nie został zatwierdzony. Można zaktualizować dane i złożyć wniosek ponownie.",
    reapply: "Złóż wniosek ponownie",
    approvedTitle: "Konto partnerskie jest aktywne",
    approvedDesc: "Klienci, którzy zarejestrują się za pośrednictwem poniższego linku z zaproszeniem, zostaną trwale przypisani do Państwa konta.",
    panelSoon: "Szczegółowy panel z klientami, zamówieniami i portfelem pojawi się tutaj już wkrótce.",
    verifyTitle: "Weryfikacja e-mail",
    verifyDesc: "Prosimy zweryfikować adres e-mail, aby móc otrzymywać płatności. Wyślemy kod weryfikacyjny.",
    verifiedLabel: "E-mail zweryfikowany",
    sendCode: "Wyślij kod weryfikacyjny",
    sending: "Wysyłanie…",
    codeSent: "Wysłaliśmy kod na adres e-mail. Prosimy sprawdzić skrzynkę odbiorczą i folder spam.",
    codePlaceholder: "6-cyfrowy kod",
    verifyBtn: "Zweryfikuj",
    verifying: "Weryfikacja…",
    verifyError: "Kod jest nieprawidłowy lub wygasł. Prosimy poprosić o nowy.",
    refTitle: "Link z zaproszeniem",
    refDesc: "Prosimy udostępnić ten link; klienci, którzy z niego skorzystają i się zarejestrują, zostaną trwale przypisani do Państwa.",
    refCopy: "Kopiuj link",
    refCopied: "Skopiowano",
  },
  adminHub: {
    tabMembers: "Członkowie",
    tabTranslators: "Tłumacze",
    tabPartners: "Partnerzy",
    tabManage: "Zarządzaj członkami",
    bMember: "Członek",
    bCustomer: "Klient",
    bTranslator: "Tłumacz",
    bPartner: "Partner",
    bReferred: "Z polecenia",
    bBanned: "Zablokowany",
    "tabDeleted": "Usunięte konta",
    "tabBanned": "Zablokowane konta",
    "delMember": "Usunięty członek",
    "delCustomer": "Usunięty klient",
    "delTranslator": "Usunięty tłumacz",
    "delPartner": "Usunięty partner",
    "banMember": "Zablokowany członek",
    "banCustomer": "Zablokowany klient",
    "banTranslator": "Zablokowany tłumacz",
    "banPartner": "Zablokowany partner",
    "delHint": "Usunięte konta. Wszystkie ich rekordy (zamówienia, tłumaczenia, aktywność partnera) są zachowywane.",
    "delNone": "Brak usuniętych kont.",
    "delAt": "Data usunięcia",
    "banHint": "Zablokowane konta. Wszystkie ich rekordy są zachowywane.",
    "banNone": "Brak zablokowanych kont.",
    filterAll: "Wszyscy",
    memHint: "Wszyscy członkowie posiadający konto w systemie, z wyjątkiem administratora.",
    memNone: "Brak członków.",
    trHint: "Wszyscy tłumacze w systemie.",
    trNone: "Brak tłumaczy.",
    trJoinedRole: "Tłumacz od",
    prtHint: "Wszyscy partnerzy w systemie.",
    prtNone: "Brak partnerów.",
    prtCompany: "Firma",
    prtJoinedRole: "Partner od",
    mgHint: "Zarządzaj członkami: blokuj lub usuwaj konta. Działania wymagają potwierdzenia.",
    mgNone: "Brak członków.",
    banBtn: "Zablokuj",
    unbanBtn: "Odblokuj",
    deleteBtn: "Usuń konto",
    banConfirm: "Czy na pewno chcesz zablokować tego członka? Nie będzie mógł się zalogować.",
    unbanConfirm: "Czy na pewno chcesz zdjąć blokadę z tego członka?",
    deleteConfirm: "Logowanie do tego konta zostanie trwale wyłączone, a konto zarchiwizowane. Wszystkie zamówienia, tłumaczenia i rekordy partnera oraz dane kontaktowe zostaną zachowane. Kontynuować?",
    confirmYes: "Tak, kontynuuj",
    confirmNo: "Anuluj",
    actionDone: "Gotowe.",
    actionFail: "Operacja nie powiodła się. Spróbuj ponownie.",
    tabChats: "Rejestry czatbota",
    "tabCustomers": "Klienci",
    "tabUploads": "Przesłane pliki",
    "loading": "Ładowanie…",
    "loadError": "Nie udało się załadować. Spróbuj ponownie.",
    "back": "Wstecz",
    custHint: "Wszyscy zarejestrowani klienci, którzy złożyli co najmniej jedno zamówienie.",
    "custSearch": "Szukaj po nazwisku, adresie e-mail lub telefonie…",
    "custName": "Imię i nazwisko",
    "custEmail": "E-mail",
    "custPhone": "Telefon",
    "custOrders": "Zamówienia",
    "custTotal": "Kwota łączna",
    "custJoined": "Data rejestracji",
    "custNone": "Brak rekordów klientów.",
    "custOrderList": "Zamówienia",
    "custNoOrders": "Ten klient nie ma zamówień.",
    "orderNo": "Numer zamówienia",
    "orderDate": "Data",
    "orderStatus": "Status",
    "upHint": "Wszystkie pliki przesłane na stronie wyceny (zapisywane nawet bez złożenia zamówienia).",
    "upFile": "Plik",
    "upUploader": "Przesłane przez",
    "upWhen": "Data",
    "upWords": "Słowa",
    "upSize": "Rozmiar",
    "upDownload": "Pobierz",
    "upNone": "Brak przesłanych plików.",
    "upGuest": "Gość"
  },

  smsVerify: {
    "sendCode": "Wyślij kod",
    "resend": "Wyślij kod ponownie",
    "codeLabel": "Kod SMS",
    "confirm": "Potwierdź",
    "verified": "Numer telefonu zweryfikowany",
    "sent": "Kod został wysłany na Państwa telefon.",
    "mustVerify": "Aby kontynuować, prosimy zweryfikować numer telefonu za pomocą wiadomości SMS.",
    "reverifyHint": "W przypadku zmiany numeru telefonu należy ponownie zweryfikować nowy numer za pomocą wiadomości SMS.",
    "invalid": "Nieprawidłowy kod. Prosimy spróbować ponownie.",
    "expired": "Kod wygasł. Prosimy poprosić o nowy.",
    "rateLimited": "Zbyt wiele prób. Prosimy chwilę odczekać i spróbować ponownie.",
    "notConfigured": "Weryfikacja SMS jest obecnie niedostępna. Prosimy spróbować ponownie później lub skontaktować się z działem wsparcia.",
    "sendFailed": "Nie udało się wysłać kodu. Prosimy sprawdzić numer i spróbować ponownie.",
    "enterPhone": "Prosimy najpierw wprowadzić prawidłowy numer telefonu.",
    "error": "Coś poszło nie tak. Prosimy spróbować ponownie.",
    "devCode": "Tryb testowy — Państwa kod weryfikacyjny: {code}"
  },
  common: {
      "brand": "TercümExpert",
    tagline: 'Państwa niezawodny partner w profesjonalnych usługach tłumaczeniowych.',
    nav: {
      home: 'Strona główna',
      services: 'Usługi',
      quote: 'Uzyskaj wycenę',
      corporate: 'Dla firm',
      partnership: 'Współpraca partnerska',
      blog: 'Blog',
      faq: 'FAQ',
      contact: 'Kontakt',
    },
    actions: {
      getQuote: 'Uzyskaj wycenę',
      calculatePrice: 'Oblicz cenę',
      uploadDocument: 'Prześlij dokument',
      whatsapp: 'Napisz na WhatsApp',
      learnMore: 'Dowiedz się więcej',
      viewAll: 'Zobacz wszystko',
      showMore: 'Pokaż więcej',
      showLess: 'Pokaż mniej',
      send: 'Wyślij',
      apply: 'Złóż wniosek',
      order: 'Złóż zamówienie',
      contactUs: 'Skontaktuj się z nami',
      openMenu: 'Otwórz menu',
      closeMenu: 'Zamknij menu',
      selectLanguage: 'Wybierz język',
      skipToContent: 'Przejdź do treści',
      login: 'Zaloguj się',
      logout: 'Wyloguj się',
      account: 'Moje konto',
      mainMenu: "Menu główne",
      menu: "Menu",
      mobileMenu: "Menu mobilne",
      countryCode: "Kod kraju",
    },
    states: {
      loading: 'Ładowanie…',
      error: 'Coś poszło nie tak. Proszę spróbować ponownie.',
      required: 'To pole jest wymagane.',
      demoNotice: 'Demo: dane formularza nie są jeszcze wysyłane na serwer.',
      unverified: 'Do zweryfikowania',
    },
    topbar: {
      phoneLabel: 'Telefon',
      emailLabel: 'E-mail',
      hoursLabel: 'Godziny pracy',
      afterHours: 'Poza godzinami pracy dostępne jest pilne wsparcie tłumaczeniowe.',
      workingHours: 'Dni powszednie 09:00 - 18:00 | Obsługa dostępna także poza godzinami pracy',
    },
  },

  home: {

    whatsappMsg: "Dzień dobry, chciałbym uzyskać informacje na temat Państwa usługi tłumaczeniowej.",
    seo: {
      title: 'TercümExpert — Profesjonalne usługi tłumaczeniowe',
      description:
        'Tłumaczenia przysięgłe, poświadczenia notarialne i rozwiązania tłumaczeniowe dla firm. Prześlij dokument, otrzymaj natychmiastową wstępną wycenę i profesjonalną realizację.',
    },
    hero: {
      title: 'Państwa niezawodny partner w profesjonalnych',
      titleAccent: 'usługach tłumaczeniowych',
      subtitle: 'Prześlij dokument, zobacz cenę, otrzymaj profesjonalną realizację.',
      support: 'Tłumaczenie przysięgłe • Poświadczenie notarialne • Rozwiązania dla firm',
    },
    trust: {
      title: 'Dlaczego nam ufają?',
      items: [
        { key: 'languages', label: 'Ponad 50 języków' },
        { key: 'delivery', label: 'Realizacja w 24 godziny' },
        { key: 'notary', label: 'Poświadczenie notarialne' },
        { key: 'quality', label: 'Gwarancja jakości' },
      ],
    },
    stats: {
      title: 'TercümExpert w liczbach',
      note: 'Poniższe dane nie są przedstawiane jako ostateczne twierdzenia, dopóki nie zostaną zweryfikowane.',
      labels: {
        satisfaction: 'Zadowolenie klientów',
        completed: 'Zrealizowane zlecenia',
        languages: 'Obsługa językowa',
        corporate: 'Klienci firmowi',
      },
    },
    howItWorks: {
      title: 'Jak to działa?',
      subtitle: 'Profesjonalne tłumaczenie w pięciu krokach.',
      steps: [
        { key: 'upload', title: 'Prześlij', desc: 'Prześlij swój dokument w bezpieczny sposób.' },
        { key: 'select', title: 'Wybierz', desc: 'Wybierz język i rodzaj usługi.' },
        { key: 'confirm', title: 'Potwierdź', desc: 'Potwierdź swoje zamówienie.' },
        { key: 'track', title: 'Śledź', desc: 'Śledź proces w czasie rzeczywistym.' },
        { key: 'receive', title: 'Odbierz', desc: 'Odbierz profesjonalnie zrealizowane tłumaczenie.' },
      ],
    },
    services: {
      title: 'Nasze usługi',
      subtitle: 'Fachowe tłumaczenie każdego rodzaju dokumentu.',
    },
    why: {
      title: 'Dlaczego TercümExpert?',
      subtitle: 'Cechy, które wyróżniają nas na tle konkurencji',
      features: [
        { key: 'autoQuote', title: 'Automatyczne obliczanie ceny', desc: 'Wstępna cena w kilka sekund.' },
        { key: 'whatsapp', title: 'Szybka wycena przez WhatsApp', desc: 'Kontakt jednym dotknięciem.' },
        { key: 'terminology', title: 'Zarządzanie terminologią', desc: 'Spójny, firmowy język.' },
        { key: 'revision', title: 'Prawo do korekty', desc: 'Proces nastawiony na satysfakcję.' },
        { key: 'languages', title: 'Obsługa ponad 50 języków', desc: 'Szeroki zakres par językowych.' },
        { key: 'terms', title: 'System płatności odroczonych dla firm', desc: 'Elastyczne płatności dla firm.' },
      ],
    },
    corporateCta: {
      title: 'Rozwiązania dla firm',
      desc: 'Profesjonalne usługi językowe z zarządzaniem terminologią, opcjami płatności odroczonych i dedykowanym opiekunem klienta dostosowanym do Państwa firmy.',
      action: 'Zamów wycenę firmową',
    },
    partnershipTeaser: {
      title: 'Program partnerski',
      subtitle: 'Zarabiaj 20% prowizji od każdego poleconego nam klienta.',
      items: [
        { key: 'commission', title: 'Przejrzysta prowizja', desc: '20% prowizji za każde polecenie (zgodnie z umową). Przejrzyste zarobki dzięki panelowi śledzenia w czasie rzeczywistym.' },
        { key: 'qr', title: 'System kodów QR', desc: 'Łatwe śledzenie klientów dzięki integracji z wizytówką. Kody QR do strony internetowej i WhatsApp.' },
      ],
      cta: 'Zgłoś się jako partner',
    },
    testimonials: {
      title: 'Opinie klientów',
      subtitle: 'Prawdziwe opinie klientów zostaną tu dodane przed uruchomieniem.',
      placeholderNote: 'Element zastępczy — zostaną dodane prawdziwe opinie.',
      items: [
        { key: 't1', role: 'Kancelaria prawna' },
        { key: 't2', role: 'Placówka medyczna' },
        { key: 't3', role: 'Klient firmowy' },
        { key: 't4', role: 'Klient indywidualny' },
      ],
    },
    blogTeaser: {
      title: 'Blog',
      subtitle: 'Aktualne treści ze świata tłumaczeń',
      viewAll: 'Zobacz wszystkie wpisy na blogu',
    },
    finalCta: {
      title: 'Zacznij już teraz',
      desc: 'Prześlij dokumenty, otrzymaj natychmiastową wycenę i skorzystaj z profesjonalnych usług tłumaczeniowych.',
      primary: 'Uzyskaj wycenę',
      secondary: 'Skontaktuj się z nami',
    },
  },

  services: {
    seo: {
      title: 'Usługi tłumaczeniowe',
      description:
        'Tłumaczenia przysięgłe, poświadczone notarialnie, prawnicze, techniczne, medyczne i akademickie oraz lokalizacja stron internetowych i aplikacji mobilnych. Rodzaje dokumentów, proces, realizacja i pary językowe.',
    },
    hero: {
      title: 'Usługi tłumaczeniowe',
      subtitle: 'Tłumaczenie z właściwą terminologią dla każdej dziedziny specjalizacji.',
    },
    process: {
      title: 'Jak przebiega proces?',
      steps: [
        { title: 'Analiza dokumentu', desc: 'Oceniamy rodzaj i przeznaczenie dokumentu.' },
        { title: 'Dobór specjalisty', desc: 'Przydzielany jest tłumacz specjalizujący się w danej dziedzinie.' },
        { title: 'Tłumaczenie i redakcja', desc: 'Tłumaczenie oraz niezależna korekta końcowa.' },
        { title: 'Poświadczenie i dostawa', desc: 'W razie potrzeby poświadczenie notarialne/apostille, a następnie dostawa.' },
      ],
    },
    delivery: {
      title: 'Opcje dostawy',
      items: ['Dostawa cyfrowa (PDF/DOCX)', 'Dostawa fizyczna dokumentu', 'Dostawa ekspresowa'],
    },
    notaryApostille: {
      title: 'Powiązanie poświadczenia notarialnego i apostille',
      desc: 'W razie potrzeby tłumaczenie przysięgłe uzyskuje ważność dla instytucji urzędowych poprzez poświadczenie notarialne i proces apostille. Dokładny wymóg zależy od instytucji, do której dokument zostanie złożony.',
    },
    fullService: {
      title: 'Kompleksowo, z dostawą pod drzwi',
      note: 'Prześlij nam swoje dokumenty, a my zajmiemy się całym procesem — obejmującym tłumaczenie, poświadczenie notarialne i apostille. Gotowe dokumenty dotrą pod Państwa drzwi kurierem. Skup się na swojej pracy, a resztę zostaw nam.',
    },
    cta: {
      title: 'Nie wiesz, której usługi potrzebujesz?',
      desc: 'Prześlij dokument, a wskażemy Ci najodpowiedniejszą usługę i cenę.',
    },
    documentTypesTitle: 'Odpowiednie rodzaje dokumentów',
  },

  serviceItems: {
    sworn: {
      name: 'Tłumaczenie przysięgłe',
      short: 'Urzędowo ważne tłumaczenie z podpisem i pieczęcią tłumacza przysięgłego.',
      benefits: ['Ważne w instytucjach urzędowych', 'Poświadczenie tłumacza przysięgłego', 'Szybki proces'],
    },
    notarized: {
      name: 'Tłumaczenie z poświadczeniem notarialnym',
      short: 'Poświadczenie notarialne tłumaczenia przysięgłego.',
      benefits: ['Poświadczenie notarialne', 'Odpowiednie do wniosków urzędowych', 'Zajmujemy się całym procesem'],
    },
    apostille: {
      name: 'Wsparcie w procesie apostille',
      short: 'Wsparcie w procesie apostille zapewniającym ważność za granicą.',
      benefits: ['Ważność międzynarodowa', 'Doradztwo w procesie', 'Wskazówki dotyczące instytucji'],
    },
    legal: {
      name: 'Tłumaczenie prawnicze',
      short: 'Tłumaczenie z biegłą znajomością terminologii dla umów oraz dokumentów sądowych i urzędowych.',
      benefits: ['Terminologia prawnicza', 'Zapewnienie poufności', 'Doświadczony tłumacz'],
    },
    technical: {
      name: 'Tłumaczenie techniczne',
      short: 'Spójne tłumaczenie instrukcji, specyfikacji i dokumentów technicznych.',
      benefits: ['Zarządzanie terminologią', 'Zachowany format', 'Znajomość branży'],
    },
    medical: {
      name: 'Tłumaczenie medyczne',
      short: 'Precyzyjne tłumaczenie raportów, ulotek i dokumentów medycznych.',
      benefits: ['Terminologia medyczna', 'Nacisk na dokładność', 'Poufność'],
    },
    academic: {
      name: 'Tłumaczenie akademickie',
      short: 'Język akademicki dla prac dyplomowych, artykułów i tłumaczeń dyplomów.',
      benefits: ['Styl akademicki', 'Spójność ze źródłem', 'Terminowa realizacja'],
    },
    localization: {
      name: 'Lokalizacja stron internetowych i aplikacji mobilnych',
      short: 'Odpowiednia kulturowo lokalizacja stron internetowych i aplikacji.',
      benefits: ['Adaptacja kulturowa', 'Integracja techniczna', 'Zgodność z SEO'],
    },
  },

  corporate: {

    formErrors: {

      company: "Nazwa firmy jest wymagana.",

      contactName: "Imię i nazwisko osoby kontaktowej jest wymagane.",

      email: "Podaj prawidłowy adres e-mail.",

      need: "Prosimy krótko opisać swoje potrzeby (co najmniej 10 znaków).",

      consent: "Aby kontynuować, wymagana jest zgoda.",

    },
    statsLabels: {
      corporate: 'Klienci firmowi',
      discount: 'Rabat na zamówienia hurtowe',
      term: 'Termin płatności',
    },
    seo: {
      title: 'Rozwiązania dla firm',
      description:
        'Profesjonalne usługi językowe dla firm z zarządzaniem terminologią, opcjami płatności odroczonych, zamówieniami hurtowymi i dedykowanym opiekunem klienta.',
    },
    hero: {
      title: 'Rozwiązania dla firm',
      subtitle:
        'Profesjonalne usługi językowe z zarządzaniem terminologią, opcjami płatności odroczonych i dedykowanym opiekunem klienta dostosowanym do Państwa firmy.',
      primaryCta: 'Zamów wycenę firmową',
      secondaryCta: 'Wyślij e-mail',
    },
    features: {
      title: 'Funkcje dla firm',
      subtitle: 'Rozwiązania dostosowane do Twojej działalności',
      items: [
        {
          key: 'custom',
          icon: 'Target',
          title: 'Usługa na zamówienie',
          points: ['Stała terminologia', 'Zachowanie tonu komunikacji marki', 'Dedykowany opiekun klienta', 'Opracowanie przewodnika stylu'],
        },
        {
          key: 'volume',
          icon: 'BarChart3',
          title: 'Obsługa hurtowa i płatności odroczone',
          points: ['Miesięczne plany tłumaczeń', 'Rabaty na zamówienia hurtowe', 'Płatność odroczona do 30 dni', 'System fakturowania'],
        },
        {
          key: 'security',
          icon: 'Lock',
          title: 'Prywatność i bezpieczeństwo',
          points: ['Protokół NDA', 'Szyfrowany transfer plików', 'Procesy zgodne z KVKK'],
        },
      ],
    },
    whyPackage: {
      title: 'Dlaczego pakiet firmowy?',
      items: [
        {
          key: 'terminology',
          icon: 'Building2',
          title: 'Zarządzanie stałą terminologią',
          desc: 'Tworzymy bazę terminów specyficzną dla Państwa firmy. Język Państwa marki jest zachowany we wszystkich tłumaczeniach, a my dbamy o spójność. Zwracamy uwagę, aby w każdym projekcie stosować te same terminy.',
        },
        {
          key: 'manager',
          icon: 'Users',
          title: 'Dedykowany opiekun klienta',
          desc: 'Państwa dedykowany opiekun klienta nadzoruje wszystkie procesy. Dzięki dostępnej linii wsparcia jesteśmy przy Państwu w pilnych sytuacjach.',
        },
        {
          key: 'security',
          icon: 'ShieldCheck',
          title: 'Prywatność i bezpieczeństwo',
          desc: 'Pracujemy w oparciu o protokół NDA. Państwa dane są bezpieczne dzięki silnej infrastrukturze zabezpieczeń, szyfrowanemu transferowi plików i procesom zgodnym z KVKK.',
        },
      ],
    },
    payment: {
      title: 'Opcje płatności',
      subtitle: 'Elastyczne plany płatności dostosowane do Twojej działalności',
      recommendedLabel: 'ZALECANE',
      options: [
        {
          key: 'standard',
          label: 'Płatność natychmiastowa',
          heading: 'Standard',
          desc: 'Płatność kartą kredytową lub przelewem bankowym po każdym zamówieniu',
          points: ['Raty na karcie kredytowej', 'Natychmiastowa realizacja'],
          recommended: false,
        },
        {
          key: 'term',
          label: 'Płatność odroczona miesięczna',
          heading: '15-30 dni',
          desc: 'Miesięczne zbiorcze fakturowanie i opcja płatności odroczonej',
          points: ['Termin płatności 30 dni', 'Rabat hurtowy', 'Raport miesięczny'],
          recommended: true,
        },
      ],
    },
    form: {
      title: 'Wniosek o pakiet firmowy',
      desc: 'Wypełnij formularz, a nasz zespół ekspertów skontaktuje się z Tobą',
      fields: {
        company: 'Nazwa firmy',
        contactName: 'Imię i nazwisko osoby kontaktowej',
        email: 'E-mail',
        phone: 'Telefon',
        need: 'Opowiedz nam o swoich potrzebach tłumaczeniowych',
        consent: 'Zapoznałem/am się z <kvkk>Klauzulą informacyjną KVKK</kvkk> i akceptuję ją.',
      },
      submit: 'Wyślij wniosek',
      success: 'Państwa wniosek został przyjęty. Skontaktujemy się z Państwem najszybciej, jak to możliwe.',
      note: 'Skontaktujemy się z Państwem w ciągu 1 dnia roboczego.',
    },
  },

  partnership: {
    seo: {
      title: 'Program partnerski',
      description:
        'Zarabiaj prowizję od każdego poleconego klienta. Przejrzyste raportowanie, polecenia z kodem QR i profesjonalne wsparcie.',
    },
    hero: {
      title: 'Program partnerski',
      value: 'Zarabiaj 20% prowizji od każdego poleconego nam klienta.',
      subtitle: 'Przejrzysty system, niezawodne płatności, długoterminowa współpraca.',
      cta: 'Zgłoś się teraz',
    },
    advantages: {
      title: 'Korzyści dla partnerów',
      subtitle: 'Dlaczego warto zostać partnerem TercümExpert?',
      items: [
        { key: 'commission', icon: 'Wallet', title: 'Gwarancja 20% prowizji', desc: 'Przejrzysty system prowizji za każdego poleconego klienta.' },
        { key: 'qr', icon: 'QrCode', title: 'Polecenie z kodem QR', desc: 'Łatwe śledzenie klientów dzięki integracji z wizytówką.' },
        { key: 'reporting', icon: 'BarChart3', title: 'Przejrzyste raportowanie', desc: 'Panel śledzenia prowizji i klientów w czasie rzeczywistym.' },
        { key: 'support', icon: 'Users', title: 'Profesjonalne wsparcie', desc: 'Dedykowana linia wsparcia dla partnerów i opiekun klienta.' },
      ],
    },
    howItWorks: {
      title: 'Jak to działa?',
      steps: [
        { title: 'Zgłoś się', desc: 'Wypełnij formularz zgłoszeniowy online. Podaj informacje o swojej firmie i dane kontaktowe. Twoje zgłoszenie jest rozpatrywane w ciągu 1 dnia roboczego.' },
        { title: 'Zostań partnerem', desc: 'Po zatwierdzeniu zgłoszenia uzyskujesz dostęp do dedykowanego panelu partnera. Twoje kody QR i linki polecające są gotowe.' },
        { title: 'Polecaj klientów', desc: 'Polecaj nam swoich klientów za pomocą kodu QR, dedykowanego linku lub wizytówki. Każde polecenie jest automatycznie rejestrowane w systemie.' },
        { title: 'Zarabiaj prowizję', desc: 'Zarabiasz 20% prowizji za każdym razem, gdy polecony przez Ciebie klient złoży zamówienie. Automatyczne płatności otrzymujesz co 15 dni.' },
      ],
    },
    sectors: {
      title: 'Sektory docelowe',
      subtitle: 'Dla których sektorów jest to idealne rozwiązanie?',
      items: [
        { key: 'law', icon: 'Scale', title: 'Kancelarie prawne', desc: 'Potrzeba tłumaczeń przysięgłych akt spraw, umów i dokumentów prawnych.' },
        { key: 'visa', icon: 'Plane', title: 'Doradztwo wizowe', desc: 'Dokumenty wymagające tłumaczenia przysięgłego, takie jak paszporty, dyplomy i akty stanu cywilnego.' },
        { key: 'education', icon: 'GraduationCap', title: 'Doradztwo edukacyjne', desc: 'Tłumaczenia przysięgłe dokumentów uczniów i procesy apostille.' },
        { key: 'health', icon: 'HeartPulse', title: 'Turystyka medyczna', desc: 'Tłumaczenie raportów medycznych, akt pacjentów i dokumentów zdrowotnych.' },
        { key: 'patent', icon: 'Building2', title: 'Kancelarie patentowe/rzecznicze', desc: 'Tłumaczenie techniczne patentów, dokumentów rejestracji znaków towarowych i dokumentów prawnych.' },
        { key: 'realestate', icon: 'Home', title: 'Biura nieruchomości', desc: 'Tłumaczenie aktów własności, umów i dokumentów urzędowych dla inwestorów zagranicznych.' },
        { key: 'hr', icon: 'Briefcase', title: 'Doradztwo HR', desc: 'Tłumaczenie CV, dyplomów i listów referencyjnych na potrzeby zatrudnienia za granicą.' },
        { key: 'software', icon: 'Code', title: 'Firmy programistyczne', desc: 'Lokalizacja stron internetowych i aplikacji mobilnych, tłumaczenie dokumentacji technicznej.' },
      ],
    },
    commission: {
      title: 'Struktura prowizji',
      stats: {
        commissionLabel: 'Standardowa prowizja',
        commissionSub: 'Od każdego zamówienia',
        periodUnit: 'Dni',
        periodLabel: 'Okres płatności',
        feeLabel: 'Opłata początkowa',
        feeSub: 'Całkowicie bezpłatnie',
      },
      exampleTitle: 'Przykładowe obliczenie zarobków',
      exampleOrderLabel: 'Zamówienie od poleconego klienta',
      exampleRateLabel: 'Stawka prowizji',
      exampleEarningLabel: 'Twoje zarobki',
      note: 'Stawki prowizji i warunki podlegają umowie partnerskiej.',
    },
    form: {
      title: 'Formularz zgłoszeniowy partnera',
      subtitle: 'Wypełnij formularz, a skontaktujemy się z Tobą w ciągu 1 dnia roboczego.',
      fields: {
        company: 'Nazwa firmy/organizacji',
        sector: 'Sektor',
        contactName: 'Imię i nazwisko osoby kontaktowej',
        titleRole: 'Stanowisko',
        email: 'E-mail',
        phone: 'Telefon',
        potential: 'Twój szacowany miesięczny potencjał poleceń',
        note: 'Uwagi, które chcesz dodać',
        agreement: 'Zapoznałem/am się z warunkami <partnership>umowy partnerskiej</partnership> i akceptuję je.',
      },
      sectorPlaceholder: 'Wybierz',
      sectorOptions: ['Kancelaria prawna', 'Doradztwo wizowe', 'Doradztwo edukacyjne', 'Turystyka medyczna', 'Kancelaria patentowa/rzecznicza', 'Nieruchomości', 'Doradztwo HR', 'Oprogramowanie', 'Inne'],
      potentialOptions: ['1-5 klientów', '5-10 klientów', '10-20 klientów', 'ponad 20 klientów'],
      submit: 'Wyślij zgłoszenie',
      success: 'Państwa zgłoszenie zostało przyjęte. Skontaktujemy się z Państwem.',
      note: 'Państwa zgłoszenie zostanie rozpatrzone w ciągu 1 dnia roboczego.',
    },
  },

  quote: {

    whatsappMsg: "Dzień dobry, chciałbym uzyskać informacje na temat wyceny.",
    cancelPolicy: "Uwaga: zamówienie można anulować ze strony zamówienia, dopóki tłumacz nie rozpocznie nad nim pracy, a płatność zostanie zwrócona. Po przyjęciu zlecenia przez tłumacza anulowanie nie jest już możliwe.",
    "areas": {
      "academic": "Tłumaczenie akademickie",
      "legal": "Tłumaczenie prawnicze",
      "official": "Tłumaczenie dokumentów urzędowych",
      "medical": "Tłumaczenie medyczne",
      "technical": "Tłumaczenie techniczne",
      "commercial": "Tłumaczenie handlowe i finansowe",
      "localization": "Lokalizacja stron i aplikacji mobilnych",
      "literary": "Tłumaczenie literackie",
      "general": "Tłumaczenie ogólne / inne"
    },
    "docTypes": {
      "diploma": "Dyplom",
      "transcript": "Wykaz ocen (transkrypt)",
      "student-certificate": "Zaświadczenie o statusie studenta",
      "diploma-supplement": "Suplement do dyplomu",
      "thesis": "Praca dyplomowa",
      "reference-letter": "List referencyjny",
      "academic-article": "Artykuł naukowy",
      "contract": "Umowa",
      "court-decision": "Orzeczenie sądu",
      "power-of-attorney": "Pełnomocnictwo",
      "petition": "Wniosek",
      "consent-statement": "Oświadczenie o wyrażeniu zgody",
      "warning-notice": "Zawiadomienie ostrzegawcze",
      "litigation-doc": "Dokumenty procesowe",
      "passport": "Paszport",
      "id-card": "Dowód osobisty",
      "civil-registry": "Odpis z rejestru stanu cywilnego",
      "birth-certificate": "Akt urodzenia",
      "marriage-certificate": "Akt małżeństwa",
      "driver-license": "Prawo jazdy",
      "criminal-record": "Zaświadczenie o niekaralności",
      "military-status": "Dokument o statusie wojskowym",
      "medical-report": "Raport medyczny",
      "epicrisis": "Epikryza (karta wypisowa)",
      "prescription": "Recepta",
      "lab-result": "Wynik badania laboratoryjnego",
      "medical-article": "Artykuł medyczny",
      "patient-consent": "Formularz zgody pacjenta",
      "user-manual": "Instrukcja obsługi",
      "technical-spec": "Specyfikacja techniczna",
      "patent": "Patent",
      "product-catalog": "Katalog produktów",
      "datasheet": "Karta katalogowa",
      "installation-guide": "Instrukcja instalacji",
      "safety-data-sheet": "Karta charakterystyki",
      "invoice": "Faktura",
      "balance-sheet": "Bilans",
      "commercial-contract": "Umowa handlowa",
      "financial-report": "Sprawozdanie finansowe",
      "tax-document": "Dokument podatkowy",
      "activity-certificate": "Zaświadczenie o działalności",
      "bank-statement": "Wyciąg bankowy",
      "website": "Strona internetowa",
      "mobile-app": "Aplikacja mobilna",
      "software-ui": "Interfejs oprogramowania",
      "game": "Gra",
      "marketing-content": "Treści marketingowe",
      "subtitle": "Napisy",
      "e-commerce": "Treści e-commerce",
      "book": "Książka",
      "short-story": "Opowiadanie",
      "poem": "Wiersz",
      "screenplay": "Scenariusz",
      "essay": "Esej",
      "article": "Artykuł",
      "general-document": "Dokument ogólny",
      "correspondence": "Korespondencja / list",
      "cv": "CV / życiorys",
      "presentation": "Prezentacja",
      "other": "Inne"
    },
    seo: {
      title: 'Natychmiastowe obliczanie ceny',
      description: 'Prześlij dokument lub wprowadź dane i otrzymaj natychmiastową wstępną wycenę.',
    },
    hero: {
      title: 'Natychmiastowe obliczanie ceny',
      subtitle: 'Prześlij dokument lub wprowadź dane i otrzymaj natychmiastową wstępną wycenę.',
    },
    upload: {
      heading: 'Prześlij swoje dokumenty',
      privacy: 'Państwa dane są traktowane jako poufne',
      tabFile: 'Prześlij plik',
      tabText: 'Wprowadź tekst',
      chooseFile: 'Wybierz swoje dokumenty',
      formats: '.docx, .xlsx, .pdf, .pptx, .jpg, .png i ponad 50 formatów · Maks. 100MB na plik',
      dropHint: 'Możesz przeciągnąć i upuścić jeden lub więcej plików w tym obszarze.',
      textPlaceholder: 'Wklej lub wpisz tutaj swój tekst…',
      totalWords: 'Łączna liczba słów',
      extracting: 'Liczenie słów…',
      wordsUnit: 'słów',
      remove: 'Usuń',
      unsupported:
        'Automatyczne liczenie słów nie było możliwe dla tego typu pliku. Proszę wkleić tekst za pomocą opcji „Wprowadź tekst”; liczba słów zostanie zweryfikowana przez nasz zespół podczas wyceny.',
      empty:
        'W pliku nie znaleziono zaznaczalnego tekstu (może to być skan/obraz). Proszę skorzystać z opcji „Wprowadź tekst”, w przeciwnym razie liczba słów zostanie zweryfikowana podczas wyceny.',
      error: 'Nie udało się odczytać pliku. Proszę spróbować ponownie lub skorzystać z opcji „Wprowadź tekst”.',
      tooLarge: 'Plik nie może być większy niż 100MB.',
      needInput: 'Aby otrzymać cenę, proszę przesłać plik lub wprowadzić tekst.',
    },
    fields: {
      upload: 'Prześlij dokument (opcjonalnie)',
      uploadHint: 'PDF, DOC, DOCX lub TXT — maks. 10 MB',
      sourceLang: 'Język źródłowy',
      targetLang: 'Język docelowy',
      serviceType: 'Rodzaj usługi',
      documentType: 'Rodzaj dokumentu',
      wordCount: 'Szacowana liczba słów',
      wordCountHint: 'Użyj suwaka lub wprowadź liczbę ręcznie.',
      options: 'Usługi dodatkowe',
      calculate: 'Oblicz cenę',
    },
    options: {
      "sworn": "Tłumaczenie przysięgłe (uwierzytelnione)",
      "apostille": "Wsparcie w procesie apostille",
      "swornNotaryHint": "Poświadczenie notarialne obejmuje już tłumaczenie przysięgłe; wystarczy wybrać jedną opcję odpowiadającą Twoim potrzebom.",
      "physicalRequiredHint": "Tłumaczenia przysięgłe i notarialne są dostarczane jako podpisane i opieczętowane oryginały, dlatego dostawa fizyczna jest dodawana automatycznie.",
      urgent: 'Dostawa ekspresowa',
      notarization: 'Poświadczenie notarialne',
      physicalDelivery: 'Dostawa fizyczna',
    },
    languages: {
      tr: 'Turecki',
      en: 'Angielski',
      de: 'Niemiecki',
      fr: 'Francuski',
      es: 'Hiszpański',
      it: 'Włoski',
      ru: 'Rosyjski',
      ar: 'Arabski',
      nl: 'Niderlandzki',
      az: 'Azerski',
      pl: 'Polski',
      bg: 'Bułgarski',
      pt: 'Portugalski',
      da: 'Duński',
    },
    documentTypes: {
      diploma: 'Dyplom',
      passport: 'Paszport',
      'civil-registry': 'Odpis aktu stanu cywilnego',
      contract: 'Umowa',
      'medical-report': 'Raport medyczny',
      'technical-doc': 'Dokument techniczny',
      'court-doc': 'Dokument sądowy',
      other: 'Inne',
    },
    result: {
      title: 'Wstępna wycena',
      basePrice: 'Podstawowa opłata za usługę',
      wordPrice: 'Opłata za słowa',
      addons: 'Usługi dodatkowe',
      total: 'Razem',
      vat: 'VAT',
      delivery: 'Szacowany czas realizacji',
      deliveryUnit: 'dni roboczych',
      disclaimer: 'Jest to wstępna wycena; cena ostateczna jest potwierdzana po analizie dokumentu.',
      order: 'Złóż zamówienie',
      whatsapp: 'Kontakt przez WhatsApp',
      estimatedWords: 'Szacowana liczba słów (automatycznie — demo)',
    },
    orderConfirm: {
      title: 'Państwa zamówienie zostało przyjęte',
      number: 'Nr zamówienia',
      desc: 'Państwa zgłoszenie i dokumenty zostały zapisane. Nasz zespół ekspertów przeanalizuje dokument i skontaktuje się z Państwem najszybciej, jak to możliwe.',
      viewOrders: 'Moje zamówienia',
      submitting: 'Tworzenie zamówienia…',
      error: 'Wystąpił problem podczas tworzenia zamówienia. Proszę spróbować ponownie.',
    },
    gate: {
      title: 'Państwa cena jest gotowa',
      subtitle: 'Zaloguj się lub zweryfikuj swoje dane, aby zobaczyć cenę i złożyć zamówienie.',
      loginCta: 'Zaloguj się / Zarejestruj się',
      or: 'lub kontynuuj szybko',
      firstName: 'Imię',
      lastName: 'Nazwisko',
      email: 'E-mail',
      phone: "Numer telefonu",
      sendCode: 'Wyślij kod weryfikacyjny',
      codeLabel: 'Kod weryfikacyjny',
      codeSentA: 'otrzymał(a) kod weryfikacyjny.',
      verify: 'Zweryfikuj i zobacz cenę',
      resend: 'Wyślij kod ponownie',
      resent: 'Wysłano nowy kod.',
      back: 'Zmień dane',
      errNames: 'Imię i nazwisko są wymagane.',
      errEmail: 'Wprowadź prawidłowy adres e-mail.',
      errPhone: "Podaj prawidłowy numer telefonu.",
      errCode: 'Proszę wprowadzić pełny kod.',
      note: 'Państwa adres e-mail jest wykorzystywany wyłącznie do wyceny i zamówienia.',
    },
    note: {
      label: 'Uwaga do zamówienia (opcjonalnie)',
      placeholder: 'Tutaj możesz zapisać swoje życzenia dotyczące dostawy, terminologii lub inne specjalne prośby.',
    },

    checkout: {
      "selectCountry": "Wybierz kraj",
      "selectCity": "Wybierz miasto / województwo",
      "cityNeedsCountry": "Najpierw wybierz kraj",
      title: "Dane do wysyłki",
      subtitle: "Państwa fizyczny/przysięgły dokument zostanie wysłany na ten adres.",
      firstName: "Imię",
      lastName: "Nazwisko",
      phone: "Telefon",
      address: "Pełny adres",
      addressPlaceholder: "Ulica, numer budynku i mieszkania…",
      city: "Miasto",
      postalCode: "Kod pocztowy",
      country: "Kraj",
      submit: "Złóż zamówienie",
      submitting: "Tworzenie zamówienia…",
      cancel: "Anuluj",
      errRequired: "Proszę wypełnić wymagane pola.",
      note: "Te dane są używane wyłącznie do dostawy kurierskiej.",
    },
  },

  order: {

    whatsappMsg: "Dzień dobry, chciałbym uzyskać informacje na temat mojego zamówienia #{no}.",
    cancel: {
      eligible: "Twoje zamówienie jest wciąż w puli; możesz je anulować i otrzymać zwrot środków, dopóki tłumacz go nie przyjmie.",
      button: "Anuluj zamówienie",
      error: "Nie udało się anulować zamówienia. Prawdopodobnie w międzyczasie przyjął je tłumacz. Prosimy odświeżyć stronę.",
      confirmTitle: "Anuluj zamówienie",
      confirmDesc: "Czy na pewno chcesz anulować to zamówienie? Tej operacji nie można cofnąć; płatność zostanie zwrócona.",
      keep: "Zachowaj",
      confirmYes: "Tak, anuluj",
      canceling: "Anulowanie…",
    },
      "trackingCodeLabel": "Numer przesyłki",
    seo: {
      title: 'Śledzenie zamówienia',
      description: 'Śledź status swojego zamówienia.',
    },
    numberLabel: 'Nr zamówienia',
    placedOn: 'Data zamówienia',
    estimatedLabel: 'Szacowana dostawa tłumaczenia',
    cargoEstimatedLabel: 'Szacowana data wysyłki',
    timelineTitle: 'Status zamówienia',
    steps: {
      received: 'Państwa zamówienie zostało przyjęte',
      in_progress: 'W trakcie realizacji',
      translated: 'Tłumaczenie ukończone',
      shipped: 'Wysłano',
      delivered: 'Dostarczono',
      cancelled: 'Zamówienie anulowane',
    },
    stepDesc: {
      received: 'Państwa zgłoszenie i dokumenty dotarły do naszego systemu. Nasz zespół ekspertów przeanalizuje je i wkrótce rozpocznie pracę.',
      in_progress: 'Nasz doświadczony tłumacz rozpoczął pracę nad Państwa tłumaczeniem.',
      translated: 'Państwa tłumaczenie jest gotowe, a kontrole końcowe zostały wykonane.',
      shipped: 'Państwa dokument został przekazany kurierowi; możesz go śledzić za pomocą przycisku poniżej.',
      delivered: 'Państwa dokument został wysłany do Państwa pocztą elektroniczną.',
      cancelled: 'To zamówienie zostało anulowane. W razie pytań prosimy o kontakt.',
    },
    cargoReady: 'Państwa dokument został wysłany. Śledź go jednym dotknięciem:',
    cargoPending: 'Kod śledzenia pojawi się tutaj po wysłaniu Państwa dokumentu.',
    trackCargo: 'Śledź moją przesyłkę',
    digitalPending: 'Po ukończeniu Państwa tłumaczenia pliki zostaną wysłane do Państwa pocztą elektroniczną.',
    digitalDelivered: 'Państwa tłumaczenie zostało wysłane do Państwa pocztą elektroniczną. Proszę sprawdzić skrzynkę odbiorczą (oraz folder ze spamem).',
    detailsTitle: 'Szczegóły zamówienia',
    fields: {
      service: 'Usługa',
      langs: 'Języki',
      documentType: 'Rodzaj dokumentu',
      words: 'Słowa',
      delivery: 'Szacowany czas',
      total: 'Kwota',
      note: 'Państwa uwaga',
      deliveryAddress: "Adres dostawy",
    },
    myOrders: 'Moje zamówienia',
    backHome: 'Powrót do strony głównej',
    whatsapp: 'Kontakt przez WhatsApp',
    loading: 'Ładowanie zamówienia…',
    loginRequired: {
      title: 'Zaloguj się, aby zobaczyć swoje zamówienie',
      desc: 'Dostęp do szczegółów zamówienia jest możliwy wyłącznie po zalogowaniu się na swoje konto.',
      login: 'Zaloguj się',
    },

    notFound: {
      title: 'Nie znaleziono zamówienia',
      desc: 'Ten numer zamówienia nie należy do Ciebie lub nie istnieje. Proszę sprawdzić link.',
      home: 'Powrót do strony głównej',
    },
  },

  faq: {

    whatsappMsg: "Dzień dobry, mam pytanie.",
    seo: {
      title: 'Najczęściej zadawane pytania',
      description: 'Najczęściej zadawane pytania dotyczące tłumaczeń przysięgłych, czasu realizacji, cennika, poświadczenia notarialnego i płatności odroczonych dla firm.',
    },
    hero: { title: 'Najczęściej zadawane pytania', subtitle: 'Odpowiedź, której szukasz, jest tutaj.' },
    categoriesTitle: 'Kategorie',
    searchPlaceholder: 'Szukaj pytań lub słów kluczowych…',
    empty: 'Żadne pytanie nie pasuje do Twojego wyszukiwania. Spróbuj innego słowa lub skontaktuj się z nami.',
    categories: FAQ_CATEGORIES_PL,
    items: FAQ_ITEMS_PL,
    notFound: {
      title: 'Nie znalazłeś odpowiedzi na swoje pytanie?',
      contact: 'Skontaktuj się z nami',
      whatsapp: 'Wsparcie WhatsApp',
    },
  },

  contact: {

    formErrors: {

      name: "Imię i nazwisko jest wymagane.",

      email: "Podaj prawidłowy adres e-mail.",

      subject: "Temat jest wymagany.",

      message: "Wiadomość musi zawierać co najmniej 10 znaków.",

      consent: "Aby kontynuować, wymagana jest zgoda.",

    },
      introTitle: `Witamy`,
      introDesc: `Zanim rozpoczniemy, czy mogę prosić o podanie Państwa imienia oraz adresu e-mail, abym mógł lepiej Państwu pomóc?`,
      start: `Rozpocznij rozmowę`,
      introError: `Prosimy o podanie Państwa imienia oraz adresu e-mail.`,
    seo: {
      title: 'Kontakt',
      description: 'Skontaktuj się z TercümExpert: telefon, e-mail, WhatsApp i formularz kontaktowy.',
    },
    hero: { title: 'Kontakt', subtitle: 'Jak możemy Ci pomóc?' },
    infoTitle: 'Informacje kontaktowe',
    labels: {
      phone: 'Telefon',
      email: 'E-mail',
      whatsapp: 'WhatsApp',
      address: 'Adres',
      hours: 'Godziny pracy',
    },
    form: {
      title: 'Skontaktuj się z nami',
      fields: {
        name: 'Imię i nazwisko',
        email: 'E-mail',
        phone: 'Telefon',
        subject: 'Temat',
        message: 'Wiadomość',
        consent: 'Zapoznałem/am się z <kvkk>Klauzulą informacyjną KVKK</kvkk> i akceptuję ją.',
      },
      submit: 'Wyślij wiadomość',
      success: 'Państwa wiadomość została przyjęta. Skontaktujemy się z Państwem wkrótce.',
    },
    map: {
      title: 'Nasza lokalizacja',
      subtitle: 'Znajdź nas na mapie',
      placeholder: 'Obszar mapy',
      note: 'Mapa lokalizacji pojawi się tutaj wkrótce.',
    },
  },

  auth: {
    seo: {
      title: 'Zaloguj się / Zarejestruj się',
      description: 'Zaloguj się na swoje konto TercümExpert lub utwórz nowe.',
    },
    tabs: { login: 'Zaloguj się', register: 'Zarejestruj się' },
    google: 'Kontynuuj z Google',
    or: 'lub',
    fields: {
      firstName: 'Imię',
      lastName: 'Nazwisko',
      email: 'E-mail',
      password: 'Hasło',
      code: 'Kod weryfikacyjny',
    },
    login: {
      title: 'Zaloguj się na swoje konto',
      submit: 'Zaloguj się',
      noAccount: 'Nie masz konta?',
      switchToRegister: 'Zarejestruj się',
    },
    register: {
      title: 'Utwórz nowe konto',
      submit: 'Zarejestruj się',
      haveAccount: 'Masz już konto?',
      switchToLogin: 'Zaloguj się',
      consent: 'Tworząc konto, akceptuję <kvkk>Klauzulę informacyjną KVKK</kvkk> oraz <privacy>Politykę prywatności</privacy>.',
    },
    verify: {
      title: 'Zweryfikuj swój adres e-mail',
      desc: '— wprowadź 6-cyfrowy kod, który wysłaliśmy na ten adres.',
      submit: 'Zweryfikuj i kontynuuj',
      spam: 'Kod może dotrzeć z kilkuminutowym opóźnieniem; proszę sprawdzić także folder ze spamem/wiadomościami-śmieciami.',
      resend: 'Wyślij kod ponownie',
      resent: 'Wysłano nowy kod.',
      back: 'Wróć',
    },
    signedIn: {
      title: 'Moje konto',
      greeting: 'Witamy',
      logout: 'Wyloguj się',
    },
    orders: {
      title: 'Moje zamówienia',
      empty: 'Nie masz jeszcze żadnych zamówień. Możesz utworzyć swoje pierwsze zamówienie za pomocą opcji Oblicz cenę.',
      loading: 'Ładowanie zamówień…',
      error: 'Nie udało się załadować zamówień. Proszę odświeżyć stronę.',
      status: {
        received: 'Przyjęto',
        in_progress: 'W trakcie realizacji',
        translated: 'Tłumaczenie ukończone',
        shipped: 'Wysłano',
        delivered: 'Dostarczono',
        cancelled: 'Anulowano',
      },
      track: 'Śledź',
    },
    errors: {
      nameRequired: 'Imię i nazwisko są wymagane.',
      emailInvalid: 'Wprowadź prawidłowy adres e-mail.',
      passwordShort: 'Hasło musi mieć co najmniej 6 znaków.',
      codeInvalid: 'Proszę wprowadzić 6-cyfrowy kod.',
      consentRequired: 'Do kontynuowania wymagana jest akceptacja.',
    },
  },

  blog: {
    seo: { title: 'Blog', description: 'Treści poradnikowe dotyczące tłumaczeń, poświadczenia notarialnego, apostille i lokalizacji.' },
    hero: { title: 'Blog', subtitle: 'Poradniki ze świata tłumaczeń.' },
    searchPlaceholder: 'Szukaj wpisów…',
    readingTime: 'min czytania',
    relatedTitle: 'Powiązane wpisy',
    allCategories: 'Wszystkie',
    empty: 'Żaden wpis nie pasuje do tego kryterium.',
  },

  legal: {
    lastUpdatedLabel: `Ostatnia aktualizacja`,
    draftNotice: `Pola oznaczone w poniższym tekście nawiasami kwadratowymi ([...]) zostaną uzupełnione danymi Państwa firmy. Teksty mają charakter wyłącznie ogólnoinformacyjny i przed publikacją zaleca się ich weryfikację przez specjalistę z zakresu prawa.`,
    kvkk: {
      seo: { title: `Klauzula informacyjna KVKK`, description: `Klauzula informacyjna dotycząca przetwarzania Państwa danych osobowych w rozumieniu ustawy KVKK nr 6698.` },
      title: `Klauzula informacyjna KVKK`,
      sections: [
        { heading: `Administrator danych`, body: `Zgodnie z ustawą nr 6698 o ochronie danych osobowych („KVKK”) Państwa dane osobowe są przetwarzane przez Samed Fazlı Atlıcı („TercümExpert”), występującą w charakterze administratora danych, w zakresie opisanym poniżej. Adres: Şeyh Şamil Mah. Eylül Sk. No: 2/D, Selçuklu, Konya. E-mail: info@tercumexpert.com. Telefon: [TELEFON].` },
        { heading: `Przetwarzane dane osobowe`, body: `Przetwarzane są Państwa dane identyfikacyjne i kontaktowe (imię, nazwisko, adres e-mail, numer telefonu), dane adresu dostawy, dane dotyczące zamówień i transakcji, dane zawarte w treści dokumentów przekazanych nam w celu tłumaczenia, a także dane dotyczące bezpieczeństwa transakcji związane z korzystaniem z witryny (adres IP, zapisy sesji i plików cookie).` },
        { heading: `Cele przetwarzania`, body: `Państwa dane osobowe są przetwarzane w celu: świadczenia usług związanych z tłumaczeniem, tłumaczeniem przysięgłym oraz poświadczeniem notarialnym i apostille, przygotowywania ofert i zarządzania zamówieniami, obsługi relacji z klientami oraz rozpatrywania zapytań i reklamacji, wypełniania obowiązków umownych i prawnych, a także zapewnienia bezpieczeństwa usług.` },
        { heading: `Podstawy prawne przetwarzania`, body: `Państwa dane są przetwarzane na podstawie tego, że jest to niezbędne do zawarcia lub wykonania umowy, w celu wypełnienia naszych obowiązków prawnych, ustalenia i ochrony przysługującego prawa oraz w oparciu o nasz prawnie uzasadniony interes, pod warunkiem nienaruszania Państwa podstawowych praw i wolności; w wymaganych przypadkach zaś na podstawie Państwa wyraźnej zgody (KVKK m.5 i m.6).` },
        { heading: `Sposób zbierania`, body: `Państwa dane osobowe są zbierane w formie elektronicznej za pośrednictwem formularzy w witrynie internetowej, procesów rejestracji i składania zamówień, poczty elektronicznej oraz innych kanałów komunikacji.` },
        { heading: `Przekazywanie danych osobowych`, body: `Państwa dane mogą być przekazywane, w zakresie niezbędnym do świadczenia usługi, naszym dostawcom mającym siedzibę w kraju i za granicą, od których korzystamy z usług hostingu, infrastruktury, uwierzytelniania, poczty elektronicznej i analityki, a także uprawnionym organom i instytucjom publicznym, zgodnie z warunkami określonymi w KVKK m.8 i m.9. Ponieważ serwery niektórych wykorzystywanych przez nas dostawców infrastruktury i usług znajdują się za granicą, Państwa dane mogą być przekazywane poza granice kraju w ramach zabezpieczeń przewidzianych w przepisach.` },
        { heading: `Okresy przechowywania`, body: `Państwa dane osobowe są przechowywane przez okres wymagany celem przetwarzania oraz przez okresy przedawnienia i przechowywania przewidziane we właściwych przepisach (takich jak przepisy podatkowe, handlowe i konsumenckie); po upływie tych okresów są usuwane, niszczone lub anonimizowane.` },
        { heading: `Prawa osoby, której dane dotyczą`, body: `Zgodnie z KVKK m.11 przysługują Państwu prawa do: uzyskania informacji, czy Państwa dane osobowe są przetwarzane, a jeśli tak, żądania informacji na ten temat, poznania celu przetwarzania i tego, czy dane są wykorzystywane zgodnie z tym celem, poznania osób trzecich, którym dane zostały przekazane w kraju lub za granicą, żądania sprostowania danych przetwarzanych w sposób niekompletny lub błędny, żądania ich usunięcia lub zniszczenia w razie zaistnienia stosownych przesłanek, żądania powiadomienia o tych czynnościach osób trzecich, którym dane przekazano, sprzeciwu wobec powstania niekorzystnego dla Państwa rozstrzygnięcia w wyniku analizy przeprowadzonej wyłącznie za pomocą systemów zautomatyzowanych, a także żądania naprawienia szkody w przypadku jej poniesienia.` },
        { heading: `Sposób składania wniosku`, body: `Wnioski dotyczące Państwa praw mogą Państwo składać na piśmie, zgodnie z „Veri Sorumlusuna Başvuru Usul ve Esasları Hakkında Tebliğ”, na adres e-mail info@tercumexpert.com lub na adres Şeyh Şamil Mah. Eylül Sk. No: 2/D, Selçuklu, Konya. Państwa wniosek zostanie rozpatrzony w możliwie najkrótszym terminie, nie później niż w ciągu trzydziestu dni, w zależności od jego charakteru.` },
      ],
    },
    privacy: {
      seo: { title: `Polityka prywatności`, description: `Nasza polityka dotycząca poufności Państwa danych osobowych i dokumentów.` },
      title: `Polityka prywatności`,
      sections: [
        { heading: `Wprowadzenie`, body: `W TercümExpert przywiązujemy wagę do Państwa prywatności. Niniejsza Polityka prywatności wyjaśnia, jakie informacje, w jakich celach zbieramy oraz w jaki sposób je chronimy w ramach usług świadczonych za pośrednictwem tercumexpert.com. Szczegółowe informacje dotyczące przetwarzania danych osobowych znajdą Państwo w Klauzuli informacyjnej KVKK.` },
        { heading: `Zbierane informacje`, body: `Możemy zbierać dane konta i kontaktowe (imię, nazwisko, e-mail, telefon), dane zamówień i dostawy, dokumenty przekazane nam do tłumaczenia wraz z ich treścią, dane transakcji dotyczące płatności oraz dane techniczne związane z korzystaniem z witryny (adres IP, informacje o przeglądarce, zapisy plików cookie).` },
        { heading: `Cele wykorzystania informacji`, body: `Wykorzystujemy Państwa informacje w celu świadczenia usług, zarządzania ofertami i zamówieniami, komunikacji z Państwem, wypełniania naszych obowiązków prawnych oraz podnoszenia jakości i bezpieczeństwa usług. Państwa dokumenty przetwarzamy wyłącznie w zakresie niezbędnym do świadczenia zamówionej usługi.` },
        { heading: `Poufność dokumentów`, body: `Państwa dokumenty przekazane do tłumaczenia traktowane są jako poufne. Dostęp do tych dokumentów mają wyłącznie upoważnieni tłumacze i pracownicy realizujący daną usługę, przez okres niezbędny do wykonania pracy; Państwa dokumenty nie są udostępniane osobom trzecim poza celem świadczenia usługi.` },
        { heading: `Zewnętrzni dostawcy usług`, body: `Świadcząc nasze usługi, korzystamy z zaufanych zewnętrznych dostawców w zakresie hostingu i infrastruktury, uwierzytelniania, wysyłki poczty elektronicznej, analityki oraz (po włączeniu) płatności. Dostawcy ci mogą uzyskać dostęp do Państwa danych wyłącznie w celu świadczenia powierzonej im usługi i pod rygorem umownych obowiązków zachowania poufności; serwery niektórych z nich mogą znajdować się za granicą.` },
        { heading: `Bezpieczeństwo danych`, body: `Aby chronić Państwa dane przed nieuprawnionym dostępem, stosujemy szyfrowanie podczas transmisji, ograniczenia dostępu oraz odpowiednie środki administracyjne i techniczne. Choć żadna metoda nie zapewnia całkowitego bezpieczeństwa, podejmujemy rozsądne i aktualne środki w celu ochrony Państwa danych.` },
        { heading: `Pliki cookie`, body: `W naszej witrynie wykorzystywane są pliki cookie i podobne technologie. Szczegółowe informacje na temat ich rodzajów i zarządzania preferencjami znajdą Państwo w Polityce plików cookie.` },
        { heading: `Państwa prawa`, body: `Mogą Państwo korzystać z przysługujących Państwu praw w ramach KVKK, w tym prawa dostępu do swoich danych osobowych, ich sprostowania i usunięcia. W sprawie swoich wniosków mogą się Państwo z nami kontaktować pod adresem info@tercumexpert.com.` },
        { heading: `Prywatność dzieci`, body: `Nasze usługi nie są skierowane do osób poniżej 18. roku życia i nie zbieramy świadomie danych osobowych dzieci.` },
        { heading: `Zmiany`, body: `Niniejsza polityka może być od czasu do czasu aktualizowana. Aktualna wersja jest zawsze publikowana na tej stronie; o istotnych zmianach informujemy w odpowiedni sposób.` },
        { heading: `Kontakt`, body: `W sprawach dotyczących prywatności: E-mail: info@tercumexpert.com · Telefon: [TELEFON] · Adres: Şeyh Şamil Mah. Eylül Sk. No: 2/D, Selçuklu, Konya.` },
      ],
    },
    distanceSales: {
      seo: { title: `Umowa sprzedaży na odległość`, description: `Umowa sprzedaży na odległość dotycząca sprzedaży usług w rozumieniu ustawy nr 6502.` },
      title: `Umowa sprzedaży na odległość`,
      sections: [
        { heading: `Strony`, body: `Niniejsza Umowa sprzedaży na odległość („Umowa”) została zawarta w formie elektronicznej, z jednej strony przez Samed Fazlı Atlıcı („Sprzedawca”; adres: Şeyh Şamil Mah. Eylül Sk. No: 2/D, Selçuklu, Konya, e-mail: info@tercumexpert.com, telefon: [TELEFON]), a z drugiej strony przez konsumenta składającego zamówienie („Kupujący”), zgodnie z ustawą nr 6502 o ochronie konsumentów oraz Mesafeli Sözleşmeler Yönetmeliği.` },
        { heading: `Przedmiot umowy`, body: `Przedmiotem Umowy jest świadczenie usług związanych z tłumaczeniem, tłumaczeniem przysięgłym oraz poświadczeniem notarialnym i apostille, zamówionych przez Kupującego w formie elektronicznej za pośrednictwem tercumexpert.com, których właściwości i cena sprzedaży zostały określone w podsumowaniu zamówienia.` },
        { heading: `Właściwości i cena usługi`, body: `Rodzaj, zakres, sposób dostarczenia (cyfrowy lub kurierski) oraz łączna cena zamówionej usługi, wraz z podatkami, są wyraźnie prezentowane Kupującemu w trakcie składania zamówienia i zawarte w potwierdzeniu zamówienia. Cena obliczana jest w zależności od wybranej usługi i właściwości dokumentów.` },
        { heading: `Płatność`, body: `Płatność jest realizowana za pomocą metod płatności udostępnionych na etapie składania zamówienia. Zamówienie jest przyjmowane do realizacji po potwierdzeniu płatności.` },
        { heading: `Wykonanie i dostawa`, body: `W przypadku dostaw cyfrowych tłumaczenie, po jego ukończeniu, jest przekazywane za pośrednictwem konta lub adresu e-mail Kupującego. W przypadku dokumentów fizycznych, z podpisem odręcznym lub poświadczonych przysięgle, dostawa jest realizowana kurierem na adres wskazany przez Kupującego. Szacowane terminy dostawy są podawane w trakcie składania zamówienia; mogą one ulec zmianie w zależności od objętości dokumentów i procesów poświadczania.` },
        { heading: `Prawo odstąpienia`, body: `Co do zasady w umowach dotyczących świadczenia usług Kupującemu przysługuje prawo odstąpienia od umowy w terminie czternastu (14) dni od dnia jej zawarcia, bez podawania jakiejkolwiek przyczyny. Zastrzega się jednak wyjątki wskazane poniżej.` },
        { heading: `Wyjątki od prawa odstąpienia`, body: `Zgodnie z Mesafeli Sözleşmeler Yönetmeliği m.15 prawo odstąpienia nie przysługuje w odniesieniu do usług, których wykonanie rozpoczęto za zgodą Kupującego i ukończono przed upływem terminu odstąpienia, a także w odniesieniu do towarów i usług przygotowanych specjalnie zgodnie z życzeniami lub indywidualnymi potrzebami Kupującego (w tym usług tłumaczenia i poświadczenia przygotowanych indywidualnie dla osoby lub dokumentu). Wnioski o anulowanie złożone przed rozpoczęciem prac tłumaczeniowych są rozpatrywane odrębnie.` },
        { heading: `Anulowanie i zwrot`, body: `W przypadku zamówień, których realizacji jeszcze nie rozpoczęto, wnioski o anulowanie można składać za pośrednictwem info@tercumexpert.com; zaakceptowane zwroty są realizowane w rozsądnym terminie tą samą metodą, którą dokonano płatności. W przypadku usług indywidualnych, których realizację rozpoczęto lub ukończono, zwrot może nie być możliwy ze względu na charakter pracy.` },
        { heading: `Rozstrzyganie sporów`, body: `W przypadku sporów mogących wyniknąć z niniejszej Umowy właściwe są Tüketici Hakem Heyetleri oraz sądy konsumenckie w miejscu zamieszkania Kupującego lub w miejscu dokonania transakcji, w granicach progów pieniężnych ogłaszanych corocznie przez Ticaret Bakanlığı.` },
        { heading: `Wejście w życie`, body: `Zatwierdzając zamówienie, Kupujący oświadcza, że zapoznał się ze wszystkimi warunkami niniejszej Umowy i je akceptuje. Umowa wchodzi w życie z chwilą zatwierdzenia zamówienia.` },
      ],
    },
    cookies: {
      seo: { title: `Polityka plików cookie`, description: `Informacje o plikach cookie stosowanych w naszej witrynie oraz o zarządzaniu preferencjami.` },
      title: `Polityka plików cookie`,
      sections: [
        { heading: `Czym są pliki cookie?`, body: `Pliki cookie to niewielkie pliki tekstowe zapisywane w Państwa przeglądarce podczas odwiedzania witryny internetowej. Są one wykorzystywane, aby uczynić witrynę bezpieczniejszą i bardziej funkcjonalną, zapamiętać Państwa preferencje oraz uzyskać statystyki dotyczące korzystania.` },
        { heading: `Dlaczego używamy plików cookie?`, body: `Wykorzystujemy pliki cookie, aby zapewnić podstawowe funkcje witryny, chronić bezpieczeństwo sesji, mierzyć wydajność oraz — w zależności od Państwa zgody — rozwijać nasze usługi i prowadzić działania marketingowe.` },
        { heading: `Kategorie plików cookie`, body: `Niezbędne pliki cookie są konieczne do działania i bezpieczeństwa witryny i nie można ich wyłączyć. Pliki cookie wydajnościowe i analityczne pomagają nam zrozumieć interakcje odwiedzających. Marketingowe pliki cookie wspierają dostarczanie treści i reklam odpowiadających Państwa zainteresowaniom. Pliki cookie preferencji zapamiętują Państwa wybory, takie jak język. Analityczne i marketingowe pliki cookie działają wyłącznie za Państwa wyraźną zgodą.` },
        { heading: `Pliki cookie osób trzecich`, body: `W celach analitycznych i marketingowych możemy korzystać z usług osób trzecich (na przykład narzędzi do statystyki odwiedzających i pomiaru skuteczności reklam). Usługi te mogą umieszczać własne pliki cookie i przetwarzać dane w ramach własnych polityk prywatności.` },
        { heading: `Zarządzanie preferencjami plików cookie`, body: `Preferencje dotyczące plików cookie innych niż niezbędne mogą Państwo wyrazić lub zmienić w dowolnym momencie za pośrednictwem narzędzia do zarządzania preferencjami plików cookie dostępnego w witrynie. Mogą Państwo również usuwać lub blokować pliki cookie w ustawieniach przeglądarki; w takim przypadku niektóre części witryny mogą jednak nie działać prawidłowo.` },
        { heading: `Okresy przechowywania`, body: `Pliki cookie, w zależności od ich rodzaju, są przechowywane przez czas trwania sesji lub przez określony okres. Sesyjne pliki cookie są usuwane po zamknięciu przeglądarki, natomiast trwałe pliki cookie wygasają po upływie ustalonego okresu lub po ich usunięciu przez Państwa.` },
        { heading: `Zmiany`, body: `Niniejsza Polityka plików cookie może być od czasu do czasu aktualizowana. Aktualna wersja jest zawsze publikowana na tej stronie.` },
      ],
    },
    partnership: {
      seo: { title: "Umowa partnerska", description: "Warunki programu partnerskiego (poleceń) TercümExpert." },
      title: "Umowa partnerska",
      sections: [
        { heading: "Strony i przedmiot", body: "Niniejsza Umowa partnerska zostaje zawarta pomiędzy [NAZWA FIRMY] („TercümExpert”) z jednej strony a partnerem biznesowym, który składa wniosek do programu i zostaje zatwierdzony („Partner”), z drugiej strony, w celu uregulowania warunków programu poleceń (partnerskiego) TercümExpert." },
        { heading: "Wniosek i zatwierdzenie", body: "Status Partnera uzyskuje się poprzez wypełnienie formularza wniosku na stronie partnerskiej i uzyskanie zatwierdzenia przez TercümExpert. Zatwierdzenie zależy od uznania TercümExpert, a wniosek może zostać odrzucony. Partner weryfikuje swój adres e-mail w ramach programu; za przystąpienie nie pobiera się opłaty początkowej." },
        { heading: "Link z zaproszeniem i przypisanie klientów", body: "Każdemu zatwierdzonemu Partnerowi przydzielany jest unikalny, osobisty link z zaproszeniem oraz powiązany z nim kod QR. Klient, który wejdzie za pośrednictwem tego linku lub kodu QR i zarejestruje się po raz pierwszy, zostaje trwale przypisany do tego Partnera; przypisanie następuje w chwili pierwszej rejestracji i nie może być później zmienione. Prowizja powstaje wyłącznie z zamówień klientów przypisanych do Partnera w ten sposób." },
        { heading: "Struktura prowizji", body: "Udział Partnera oblicza się z wyłączeniem podatku od towarów i usług (VAT) oraz różnic za usługi dodatkowe, w następujący sposób: 20% podstawowej kwoty tłumaczenia; jeśli wybrano dostawę ekspresową, 20% różnicy za dostawę ekspresową; jeśli wybrano tłumaczenie przysięgłe, 10% różnicy za tłumaczenie przysięgłe. Z opłat za poświadczenie notarialne, wsparcie apostille oraz dostawę fizyczną (kurierską) Partnerowi nie wypłaca się żadnego udziału, a VAT nie stanowi podstawy prowizji. Te procenty są stałe; stawki pozostają w mocy nawet w przypadku zmiany cen. TercümExpert może aktualizować stawki i warunki za uprzednim powiadomieniem." },
        { heading: "Naliczanie i portfel", body: "Prowizja jest dodawana do portfela Partnera po zakończeniu zamówienia poleconego klienta i pozostaje zablokowana przez siedem (7) dni od daty dodania; po upływie tego okresu staje się dostępna do wypłaty. Zamówienia anulowane, zwrócone lub nieopłacone nie stanowią podstawy prowizji." },
        { heading: "Płatności", body: "Salda dostępne do wypłaty są wypłacane na podany przez Partnera numer IBAN 2. i 17. dnia każdego miesiąca. Aby dokonać płatności, obowiązkowe pola w profilu Partnera muszą być w pełni wypełnione, a numer IBAN i dane właściciela rachunku muszą być zatwierdzone przez TercümExpert. Obowiązki podatkowe związane z płatnościami podlegają obowiązującym przepisom." },
        { heading: "Obowiązki Partnera", body: "Partner zobowiązuje się do stosowania w swojej promocji rzetelnych i niewprowadzających w błąd informacji, do powstrzymania się od działań szkodzących marce i reputacji TercümExpert, do aktualizowania swoich danych kontaktowych i płatniczych oraz do przestrzegania obowiązujących przepisów." },
        { heading: "Zachowania zabronione", body: "Zabronione są spam i niezamówione masowe wiadomości, wprowadzająca w błąd reklama, fałszywe lub własne polecenia (w tym składanie zamówień przez Partnera za pośrednictwem własnego konta) oraz zachowania stanowiące nieuczciwą konkurencję. Takie naruszenia stanowią podstawę do anulowania odpowiednich prowizji i rozwiązania Umowy." },
        { heading: "Korzystanie z marki", body: "Partner może korzystać z marki, logo i materiałów promocyjnych TercümExpert wyłącznie za pisemną zgodą TercümExpert i w ramach dostarczonych przez nią zasad." },
        { heading: "Poufność i dane osobowe", body: "Strony zobowiązują się chronić informacje poufne uzyskane na podstawie Umowy. Partner przetwarza dane osobowe poleconych klientów wyłącznie w celu programu i zgodnie z obowiązującymi przepisami o ochronie danych." },
        { heading: "Strona niezależna", body: "Partner jest stroną niezależną; nie jest pracownikiem, przedstawicielem ani agentem TercümExpert i nie może zaciągać zobowiązań wobec osób trzecich w imieniu TercümExpert." },
        { heading: "Okres obowiązywania i rozwiązanie", body: "Umowa pozostaje w mocy do czasu, gdy jedna ze stron powiadomi o jej rozwiązaniu. TercümExpert może rozwiązać Umowę ze skutkiem natychmiastowym w przypadku naruszenia obowiązków; prowizje wynikające z nieprawidłowych lub nadużywających poleceń nie są wypłacane. W przypadku rozwiązania odblokowane, zgodne z prawem salda są wypłacane zgodnie z obowiązującymi warunkami." },
        { heading: "Zmiany, spory i wejście w życie", body: "TercümExpert może od czasu do czasu aktualizować niniejszą Umowę; aktualna wersja jest zawsze publikowana na tej stronie. Umowa podlega prawu Republiki Türkiye. Potwierdzając wniosek, Partner oświadcza, że zapoznał się ze wszystkimi warunkami Umowy i je akceptuje." },
      ],
    },
  },

  admin: {
    attachmentImage: 'Obraz',
    attachmentFile: 'Dokument',
    title: "Panel administracyjny",
    summary: `{total} rozmów · {leads} zapytań kontaktowych`,
    onlyLeads: `Tylko zapytania kontaktowe`,
    loading: `Ładowanie rejestru…`,
    error: `Nie udało się odczytać rejestru. Proszę sprawdzić, czy tabela Supabase oraz uprawnienia (RLS) zostały poprawnie skonfigurowane.`,
    empty: `Brak zapisanych rekordów.`,
    selectHint: `Proszę wybrać rozmowę po lewej stronie, aby ją wyświetlić.`,
    contactRequest: `Zapytanie kontaktowe`,
    contactInfo: `Dane kontaktowe`,
    fieldName: `Imię i nazwisko`,
    fieldEmail: `Adres e-mail`,
    fieldPhone: `Telefon`,
    fieldMessage: `Wiadomość`,
    requestBadge: `zapytanie`,
    noMessages: `Ten rekord nie zawiera wiadomości (wyłącznie zapytanie kontaktowe).`,
    loginTitle: `Wymagane logowanie`,
    loginDesc: `Aby wyświetlić tę stronę, proszę zalogować się na konto administratora.`,
    login: `Zaloguj się`,
    noAccessTitle: `Brak uprawnień dostępu`,
    noAccessDesc: `Ta strona jest dostępna wyłącznie dla administratorów.`,
    loadingAuth: `Ładowanie…`,
  },
  footer: {
    tagline: 'Państwa niezawodny partner w profesjonalnych usługach tłumaczeniowych.',
    columns: {
      quickLinks: 'Szybkie linki',
      services: 'Usługi',
      contact: 'Kontakt',
    },
    quickLinks: {
      corporate: 'Dla firm',
      services: 'Nasze usługi',
      quote: 'Oblicz cenę',
      blog: 'Blog',
      faq: 'Najczęściej zadawane pytania',
      contact: 'Kontakt',
    },
    serviceLinks: {
      sworn: 'Tłumaczenie przysięgłe',
      notarized: 'Tłumaczenie z poświadczeniem notarialnym',
      apostille: 'Proces apostille',
      corporate: 'Rozwiązania dla firm',
      partnership: 'Program partnerski',
    },
    legal: {
      kvkk: 'KVKK',
      privacy: 'Polityka prywatności',
      distanceSales: 'Umowa sprzedaży na odległość',
      cookies: 'Polityka plików cookie',
    },
    socialTitle: 'Obserwuj nas',
    whatsapp: 'Wsparcie WhatsApp',
    rights: 'Wszelkie prawa zastrzeżone.',
  },

  cookie: {
    title: "Panel administracyjny",
    desc: 'Używamy plików cookie, aby poprawić Państwa doświadczenie. Pliki cookie inne niż niezbędne działają wyłącznie za Państwa zgodą.',
    accept: 'Akceptuj',
    reject: 'Odrzuć',
    manage: 'Zarządzaj preferencjami',
    save: 'Zapisz preferencje',
    categories: {
      necessary: { label: 'Niezbędne', desc: 'Wymagane do działania strony; nie można ich wyłączyć.' },
      analytics: { label: 'Analityczne', desc: 'Pomagają nam zrozumieć sposób korzystania.' },
      marketing: { label: 'Marketingowe', desc: 'Do odpowiednich treści i reklam.' },
      preferences: { label: 'Preferencji', desc: 'Zapamiętują Państwa preferencje.' },
    },
  },

  chatbot: {
    attach: {
      button: 'Załącz plik',
      tooLarge: 'Plik jest za duży (maks. 25 MB).',
      unsupported: 'Nie mogę analizować plików audio ani wideo na czacie. Możesz je przesłać na stronie wyceny.',
      cannotRead: 'Nie udało mi się odczytać tego pliku. Możesz przesłać go na stronie wyceny lub spróbować innego formatu.',
      reading: 'Odczytywanie pliku…',
      remove: 'Usuń',
    },
    nudge: 'W czym mogę pomóc?',
    title: 'Wsparcie TercümExpert',
    open: 'Otwórz czat',
    close: 'Zamknij czat',
    minimize: 'Zminimalizuj',
    clear: 'Wyczyść rozmowę',
    inputPlaceholder: 'Wpisz swoją wiadomość…',
    send: 'Wyślij',
    typing: 'Pisze…',
    welcome:
      'Witamy w TercümExpert. Mogę pomóc w kwestiach tłumaczenia, cennika, poświadczenia notarialnego, apostille lub usług dla firm.',
    quickQuestions: [
      'Jak obliczana jest cena?',
      'Czym jest tłumaczenie przysięgłe?',
      'Chcę przesłać dokument',
      'Chcę uzyskać wycenę firmową',
      'Czy wymagane jest poświadczenie notarialne?',
      'Połącz mnie z konsultantem',
    ],
    handoff: 'Połącz z konsultantem',
    toWhatsapp: 'Przenieś na WhatsApp',
    disclaimer: 'Te informacje mają charakter ogólny; proszę potwierdzić dokładne wymogi w odpowiedniej instytucji.',
    sensitiveWarning:
      'Prosimy nie udostępniać wrażliwych danych osobowych za pośrednictwem tego czatu. Swoje dokumenty można przesłać przez bezpieczny obszar przesyłania.',
    answers: [
      `Cena jest ustalana na podstawie liczby słów w dokumencie, pary językowej, rodzaju usługi (tłumaczenie przysięgłe, poświadczenie notarialne, apostille) oraz terminu realizacji. Aby natychmiast otrzymać orientacyjną wycenę, mogą Państwo przesłać dokument lub wprowadzić dane na stronie Oblicz Cenę.`,
      `Tłumaczenie przysięgłe to tłumaczenie urzędowe wykonane przez tłumacza przysięgłego i poświadczone jego podpisem oraz pieczęcią. Instytucje urzędowe najczęściej wymagają tłumaczenia przysięgłego; w razie potrzeby można dodatkowo uzyskać poświadczenie notarialne.`,
      `Dokument mogą Państwo przesłać za pośrednictwem bezpiecznego formularza przesyłania plików na stronie Oblicz Cenę. Po przesłaniu od razu zobaczą Państwo orientacyjną wycenę i będą mogli sfinalizować zamówienie.`,
      `Na potrzeby firm oferujemy specjalne warunki cenowe oraz priorytetową realizację przy regularnych i obszernych zleceniach tłumaczeniowych. Szczegóły znajdą Państwo na naszej stronie dla Klientów Biznesowych lub mogą Państwo skontaktować się z nami bezpośrednio.`,
      `Konieczność poświadczenia notarialnego zależy od instytucji, której przedłożą Państwo dokument, oraz od rodzaju sprawy. Niektóre procedury akceptują wyłącznie tłumaczenie przysięgłe, inne wymagają dodatkowo poświadczenia notarialnego. Jeśli nie mają Państwo pewności, chętnie pomożemy.`,
      `Już łączymy Państwa z naszym konsultantem obsługi klienta. Korzystając z poniższego przycisku, mogą Państwo napisać do nas przez WhatsApp.`,
    ],
    fallback: `W Państwa sprawie najlepszej pomocy udzieli nasz konsultant obsługi klienta. Korzystając z poniższego przycisku, mogą Państwo napisać do nas przez WhatsApp; Państwa wiadomość zostanie przekazana w gotowej formie.`,
    contact: {
      "introTitle": "Witamy",
      "introDesc": "Aby móc lepiej Ci pomóc, czy mogę najpierw poznać Twoje imię i adres e-mail?",
      "start": "Rozpocznij czat",
      "introError": "Prosimy podać imię oraz adres e-mail.",
      whatsapp: `WhatsApp`,
      email: `E-mail`,
      phone: `Telefon`,
      leaveInfo: `Zostaw moje dane kontaktowe`,
      formTitle: `Skontaktujemy się z Państwem`,
      formDesc: `Prosimy o pozostawienie swoich danych, a nasz zespół skontaktuje się z Państwem w najkrótszym możliwym terminie.`,
      name: `Imię i nazwisko`,
      emailField: `E-mail`,
      phoneField: `Telefon`,
      message: `Wiadomość (opcjonalnie)`,
      submit: `Wyślij`,
      submitting: `Wysyłanie…`,
      thanks: `Dziękujemy, nasz zespół skontaktuje się z Państwem w najkrótszym możliwym terminie.`,
      errorRequired: `Prosimy podać adres e-mail lub numer telefonu.`,
      back: `Wstecz`,
    },
  },

  translator: {
    "seo": {
      "title": "Panel tłumacza — TercümExpert",
      "description": "Wniosek tłumacza i panel pracy."
    },
    "loading": "Ładowanie…",
    "loginTitle": "Wymagane logowanie",
    "loginDesc": "Ta sekcja jest przeznaczona wyłącznie dla tłumaczy i administratorów. Zaloguj się, aby kontynuować.",
    "login": "Zaloguj się",
    "setupTitle": "Panel nie jest jeszcze gotowy",
    "setupDesc": "Infrastruktura tłumaczy (baza danych) nie została jeszcze skonfigurowana. Panel zostanie aktywowany po zakończeniu konfiguracji.",
    "applyTitle": "Wniosek tłumacza",
    "applyDesc": "Uzupełnij swoje dane, aby dołączyć do naszej sieci tłumaczy freelancerów. Twój wniosek zostanie aktywowany po zatwierdzeniu przez administratora.",
    "applyNote": "Twoje dane są wykorzystywane wyłącznie do oceny i realizacji płatności.",
    "form": {
      "fullName": "Imię i nazwisko",
      "birthDate": "Data urodzenia",
      "phone": "Telefon",
      "country": "Kraj",
      "city": "Miasto / Województwo",
      "selectCountry": "Wybierz kraj",
      "selectCity": "Wybierz miasto / województwo",
      "cityNeedsCountry": "Najpierw wybierz kraj",
      "address": "Pełny adres",
      "isSworn": "Czy jesteś tłumaczem przysięgłym?",
      "isSwornHint": "Zaznacz, jeśli posiadasz wpis do rejestru tłumaczy przysięgłych. Otrzymasz pierwszeństwo przy zleceniach wymagających tłumaczenia przysięgłego.",
      "iban": "IBAN",
      "ibanName": "Właściciel rachunku IBAN (imię i nazwisko)",
      "languagePairs": "Pary językowe",
      "source": "Język źródłowy",
      "target": "Język docelowy",
      "addPair": "Dodaj",
      "removePair": "Usuń",
      "swap": "Zamień kierunek",
      "expertise": "Obszary specjalizacji",
      "submit": "Wyślij wniosek",
      "submitting": "Wysyłanie…",
      "saved": "Twoje dane zostały zapisane.",
      "saveError": "Nie udało się zapisać. Spróbuj ponownie.",
      "required": "Uzupełnij wymagane pola.",
      "atLeastOnePair": "Dodaj co najmniej jedną parę językową."
    },
    "expertiseLabels": {
      "legal": "Prawne",
      "medical": "Medyczne",
      "technical": "Techniczne",
      "academic": "Akademickie",
      "commercial": "Handlowe",
      "financial": "Finansowe",
      "literary": "Literackie",
      "official": "Dokumenty urzędowe",
      "localization": "Web / Oprogramowanie",
      "general": "Ogólne"
    },
    "pendingTitle": "Twój wniosek jest w trakcie weryfikacji",
    "pendingDesc": "Otrzymaliśmy Twój wniosek tłumacza. Dostęp do panelu zostanie przyznany po weryfikacji przez administratora.",
    "rejectedTitle": "Wniosek nie został zatwierdzony",
    "rejectedDesc": "Twój wniosek nie został tym razem zatwierdzony. Możesz zaktualizować swoje dane i spróbować ponownie.",
    "reapply": "Spróbuj ponownie",
    "cancelApplication": "Anuluj wniosek",
    "cancelConfirm": "Czy na pewno chcesz anulować swój wniosek? Twój rekord zostanie usunięty; w razie potrzeby możesz złożyć wniosek ponownie później.",
    "panelTitle": "Panel tłumacza",
    "tabs": {
      "profile": "Mój profil",
      "pool": "Pula tłumaczeń",
      "active": "Aktywne zlecenia",
      "pending": "Oczekujące na zatwierdzenie",
      "approved": "Zatwierdzone",
      "completed": "Zakończone",
      "wallet": "Portfel"
    },
    "soon": "Ta sekcja pojawi się w następnym kroku.",
    "jobs": {
      "empty": "W tej sekcji nie ma obecnie żadnych zleceń.",
      "translator": "Tłumacz",
      "sourceFiles": "Dokumenty źródłowe",
      "trDeleted": "Usunięty tłumacz",
      "trBanned": "Zablokowany tłumacz",
      "translationFiles": "Przesłane tłumaczenie",
      "tracking": "Śledzenie",
      "rejectionReason": "Powód odrzucenia",
      "chooseFiles": "Wybierz pliki tłumaczenia",
      "filesSelected": "wybrany(-e) plik(i)",
      "uploadHint": "Prześlij swoje tłumaczenie oraz, w razie potrzeby, cyfrową kopię dokumentu źródłowego, a następnie wyślij je do zatwierdzenia.",
      "submit": "Wyślij do zatwierdzenia",
      "sending": "Wysyłanie…",
      "needFiles": "Wybierz co najmniej jeden plik.",
      "uploadError": "Nie udało się przesłać plików. Spróbuj ponownie.",
      "submittedMsg": "Tłumaczenie wysłane do zatwierdzenia.",
      "actionError": "Nie udało się wykonać czynności. Spróbuj ponownie.",
      "waitingApproval": "Twoje tłumaczenie oczekuje na zatwierdzenie przez kierownictwo. Po zatwierdzeniu etap dostawy pojawi się w sekcji „Zatwierdzone”.",
      "trackingPlaceholder": "Numer / link do śledzenia przesyłki",
      "needTracking": "Numer śledzenia jest wymagany przy dostawie kurierskiej.",
      "markShipped": "Wysłano — zakończ",
      "markDelivered": "Dostarczono — zakończ",
      "completedMsg": "Zlecenie zakończone. Twoje wynagrodzenie zostało dodane do portfela.",
      "reasonPlaceholder": "W przypadku odrzucenia wpisz powód (widoczny dla tłumacza)…",
      "approve": "Zatwierdź",
      "reject": "Odrzuć",
      "needReason": "Wpisz powód odrzucenia.",
      "approvedMsg": "Tłumaczenie zatwierdzone.",
      "rejectedMsg": "Tłumaczenie odrzucone; zwrócone do tłumacza.",
      "statusLabel": "Status",
      "status_claimed": "W trakcie realizacji",
      "status_submitted": "Oczekuje na zatwierdzenie",
      "status_approved": "Zatwierdzone — etap dostawy",
      "status_completed": "Zakończone"
    },
    "pool": {
      "loading": "Ładowanie puli…",
      "empty": "Obecnie nie ma oczekujących zleceń pasujących do Twoich par językowych i specjalizacji.",
      "error": "Nie udało się załadować puli. Spróbuj ponownie.",
      "orderNo": "Zamówienie",
      "service": "Rodzaj usługi",
      "documentType": "Typ dokumentu",
      "langPair": "Para językowa",
      "words": "Słowa",
      "pagesUnit": "stron",
      "deadline": "Termin",
      "daysUnit": "dni roboczych",
      "note": "Uwaga klienta",
      "customerInfo": "Dane klienta",
      "deliveryInfo": "Dane klienta i dostawy",
      "customerName": "Imię i nazwisko",
      "customerEmail": "E-mail",
      "customerPhone": "Telefon",
      "deliveryAddress": "Adres dostawy",
      "text": "Treść zamówienia",
      "files": "Dokumenty",
      "earning": "Twoje wynagrodzenie za to zlecenie",
      "urgent": "Pilne",
      "sworn": "Przysięgłe",
      "notary": "Notarialne",
      "apostille": "Apostille",
      "cargo": "Dostawa kurierska",
      "digital": "Dostawa cyfrowa",
      "claim": "Podejmij to zlecenie",
      "claiming": "Podejmowanie…",
      "claimed": "Pomyślnie podjąłeś zlecenie.",
      "claimError": "Nie udało się podjąć zlecenia. Mogło zostać podjęte przez kogoś innego; odśwież listę.",
      "ibanRequired": "Zanim będziesz mógł podejmować zlecenia, Twoje dane IBAN muszą zostać zweryfikowane przez kierownictwo. Wprowadź swój IBAN w profilu; po weryfikacji będziesz mógł podejmować zlecenia z puli."
    },
    "profile": {
      "statusApproved": "Zatwierdzony tłumacz",
      "verifiedIban": "IBAN zweryfikowany",
      "unverifiedIban": "IBAN niezweryfikowany",
      "current": "Zapisano",
      "edit": "Zapisz dane",
      "ibanReminder": "Aby otrzymywać płatności, wprowadź i zapisz swoje dane IBAN. Po weryfikacji przez administratora płatności będą realizowane na ten rachunek.",
      "lockedHint": "Nie można zmienić po zatwierdzeniu",
      "revokeTitle": "Ta zmiana cofnie Twoje zatwierdzenie",
      "revokeWarning": "Jeśli zmienisz swoje pary językowe, status tłumacza przysięgłego lub obszary specjalizacji, Twoje konto wróci do weryfikacji przez kierownictwo (status oczekujący). Twoje zlecenia, rekordy i portfel zostaną ZACHOWANE; po ponownym zatwierdzeniu kontynuujesz od miejsca, w którym skończyłeś.",
      "consent": "Przeczytałem(-am) i akceptuję",
      "ibanReverify": "Zmieniasz swój IBAN. Nowy IBAN zostanie ponownie skierowany do weryfikacji przez kierownictwo; Twoje konto pozostaje aktywne, ale nie możesz podejmować nowych zleceń z puli, dopóki IBAN nie zostanie zweryfikowany."
    },
    "admin": {
      "title": "Panel zarządzania",
      "translatorsTab": "Tłumacze",
      "applicationsTab": "Wnioski",
      "ibanTab": "Zatwierdzenia IBAN",
      "ordersTab": "Zamówienia",
      "paymentsTab": "Płatności",
      "noIbanPending": "Brak tłumaczy oczekujących na zatwierdzenie IBAN.",
      "ibanHint": "Zatwierdzaj tutaj nowo wprowadzone lub zmienione numery IBAN. Do czasu zatwierdzenia tłumacz nie może podejmować nowych zleceń z puli.",
      "ibanApprove": "Zatwierdź IBAN",
      "paymentsHint": "W dniu płatności (1. i 16. dnia każdego miesiąca): dla każdego opłaconego tłumacza prześlij potwierdzenie i kliknij „Oznacz jako opłacone”. Przycisk nie zadziała bez potwierdzenia. Tłumacze z zerowym saldem nie są tutaj wyświetlani.",
      "noPayments": "Brak tłumaczy z saldem do wypłaty.",
      "paymentAmount": "Kwota do wypłaty",
      "uploadReceipt": "Prześlij potwierdzenie",
      "receiptUploaded": "Potwierdzenie przesłane",
      "receiptRequired": "Najpierw prześlij potwierdzenie",
      "uploading": "Przesyłanie…",
      "markPaid": "Oznacz jako opłacone",
      "paid": "Płatność zarejestrowana, a tłumacz został powiadomiony wraz z potwierdzeniem.",
      "panelHint": "Śledź zatwierdzonych tłumaczy według profilu, przeglądaj wnioski i zarządzaj obiegiem pracy wszystkich zamówień.",
      "summary": "{total} tłumaczy · {pending} oczekujących wniosków",
      "applicationsSummary": "{total} wniosków · {pending} oczekujących na weryfikację",
      "noApproved": "Brak zatwierdzonych tłumaczy.",
      "noPending": "Brak oczekujących wniosków.",
      "noMatch": "Żaden rekord nie pasuje do filtrów.",
      "loadError": "Nie udało się załadować rekordów. Sprawdź bazę danych i uprawnienia (RLS).",
      "noApplications": "Brak rekordów tłumaczy.",
      "filters": {
        "namePlaceholder": "Szukaj według nazwy…",
        "country": "Kraj",
        "city": "Miasto / Województwo",
        "anyCountry": "Wszystkie kraje",
        "anyCity": "Wszystkie miasta",
        "cityNeedsCountry": "Najpierw wybierz kraj",
        "sourceLang": "Język źródłowy",
        "targetLang": "Język docelowy",
        "anyLang": "Dowolny",
        "eitherDirection": "Dowolny kierunek (źródłowy↔docelowy)",
        "expertise": "Obszary specjalizacji",
        "clear": "Wyczyść filtry",
        "results": "{n} rekordów"
      },
      "orders": {
        "loadError": "Nie udało się załadować zamówień. Spróbuj ponownie.",
        "empty": "Brak zamówień.",
        "searchPlaceholder": "Szukaj według numeru zamówienia lub nazwy klienta…",
        "results": "{n} zamówień",
        "customer": "Klient",
        "translator": "Tłumacz",
        "unassigned": "Nieprzypisane",
        "status": "Status",
        "done": "Zakończone",
        "inProgress": "W trakcie realizacji",
        "completedOn": "Zakończono dnia",
        "placedOn": "Data zamówienia",
        "total": "Suma",
        "statusAvailable": "W puli (niepodjęte)",
        "statusClaimed": "W tłumaczeniu",
        "statusSubmitted": "Oczekuje na zatwierdzenie",
        "statusApproved": "Etap dostawy",
        "statusCompleted": "Zakończone",
        "statusCancelled": "Anulowane"
      },
      "profile": {
        "back": "Powrót do tłumaczy",
        "adminOnly": "Ten profil jest dostępny wyłącznie dla kierownictwa; tłumacz go nie widzi.",
        "infoTitle": "Dane",
        "walletTitle": "Portfel",
        "jobsTitle": "Zlecenia",
        "noJobs": "Ten tłumacz nie ma jeszcze żadnych zleceń."
      },
      "approve": "Zatwierdź",
      "reject": "Odrzuć",
      "colLangs": "Pary językowe",
      "colExpertise": "Specjalizacja",
      "colLocation": "Miasto / Kraj",
      "swornBadge": "Przysięgły",
      "returningBadge": "Powracający tłumacz",
      "ibanVerified": "IBAN zweryfikowany",
      "ibanNotVerified": "IBAN niezweryfikowany",
      "verifyIban": "Zweryfikuj IBAN",
      "unverifyIban": "Cofnij weryfikację",
      "statusPending": "Oczekujący",
      "statusApproved": "Zatwierdzony",
      "statusRejected": "Odrzucony",
      "actionError": "Nie udało się wykonać czynności."
    },
    "wallet": {
      "total": "Całkowite zarobki",
      "locked": "Zablokowane",
      "withdrawable": "Dostępne do wypłaty",
      "paid": "Wypłacone",
      "payInfo": "Zarobki są dodawane do Twojego portfela po zakończeniu zlecenia; pozostają zablokowane przez 7 dni, a następnie stają się dostępne do wypłaty. Płatności są realizowane z salda dostępnego do wypłaty 1. i 16. dnia każdego miesiąca.",
      "empty": "Brak zarobków. Zarobki z zakończonych zleceń pojawią się tutaj.",
      "entryOrder": "Zamówienie",
      "date": "Data",
      "statusCol": "Status",
      "amount": "Kwota",
      "statusPaid": "Wypłacone",
      "statusUnlocked": "Dostępne do wypłaty",
      "statusPending": "Zablokowane",
      "loadError": "Nie udało się załadować portfela. Spróbuj ponownie."
    },
    "adminWallet": {
      "firmShare": "Udział firmy (z VAT)",
      "firmShareHint": "Udział firmy = suma zakończonych zamówień (z VAT) pomniejszona o zarobki tłumaczy.",
      "ciro": "Całkowity przychód (z VAT)",
      "kdv": "VAT (dla państwa)",
      "payouts": "Wypłacone tłumaczom",
      "net": "Zysk netto firmy",
      "count": "{n} zakończonych zamówień",
      "empty": "Brak zakończonych zamówień.",
      "colOrder": "Zamówienie",
      "colTranslator": "Tłumacz",
      "colDate": "Data",
      "colTotal": "Suma (z VAT)",
      "colPayout": "Tłumacz",
      "colFirm": "Udział firmy",
      "loadError": "Nie udało się załadować portfela. Spróbuj ponownie."
    }
  },
  authx: {
    "rememberMe": "Zapamiętaj mnie",
    "showPassword": "Pokaż hasło",
    "hidePassword": "Ukryj hasło",
    "forgot": "Nie pamiętam hasła",
    "forgotTitle": "Resetowanie hasła",
    "forgotDesc": "Podaj zarejestrowany adres e-mail, a wyślemy Ci jednorazowy link do zresetowania hasła.",
    "forgotEmail": "Adres e-mail",
    "forgotSubmit": "Wyślij link resetujący",
    "forgotSent": "Link został wysłany na Twój adres e-mail. Sprawdź skrzynkę odbiorczą (oraz folder spam).",
    "forgotBack": "Powrót do logowania",
    "resetTitle": "Ustaw nowe hasło",
    "resetDesc": "Wprowadź nowe hasło i potwierdź je, wpisując je ponownie.",
    "newPassword": "Nowe hasło",
    "newPasswordRepeat": "Nowe hasło (powtórz)",
    "mismatch": "Hasła nie są zgodne.",
    "weak": "Hasło musi zawierać co najmniej 6 znaków.",
    "resetSubmit": "Zaktualizuj hasło",
    "resetSuccess": "Twoje hasło zostało zaktualizowane. Możesz teraz zalogować się przy użyciu nowego hasła.",
    "resetInvalid": "Link jest nieprawidłowy lub wygasł. Poproś o nowy link resetujący.",
    "goLogin": "Zaloguj się",
    err: {
      "invalidCredentials": "Nieprawidłowy adres e-mail lub hasło. Prosimy sprawdzić wprowadzone dane i spróbować ponownie.",
      "emailNotConfirmed": "Pana/Pani adres e-mail nie został jeszcze zweryfikowany. Prosimy kliknąć link weryfikacyjny w otrzymanej wiadomości.",
      "alreadyRegistered": "Ten adres e-mail jest już zarejestrowany. Prosimy spróbować się zalogować lub zresetować hasło.",
      "weakPassword": "Hasło musi zawierać co najmniej 6 znaków.",
      "otpInvalid": "Kod weryfikacyjny jest nieprawidłowy lub wygasł. Prosimy poprosić o nowy kod.",
      "rateLimited": "Zbyt wiele prób. Prosimy chwilę odczekać i spróbować ponownie.",
      "generic": "Wystąpił błąd. Prosimy spróbować ponownie później."
    }
  },
  notFound: {
    seo: { title: 'Nie znaleziono strony', description: 'Nie udało się znaleźć szukanej strony.' },
    title: 'Nie znaleziono strony',
    desc: 'Szukana strona mogła zostać przeniesiona lub nigdy nie istniała.',
    home: 'Powrót do strony głównej',
  },
}
