import type { PartialDictionary } from '@/types/i18n'
import { FAQ_CATEGORIES_IT, FAQ_ITEMS_IT } from '@/content/faq-data.it'

/**
 * ITALIANO — traduzione completa, struttura identica a en/index.ts.
 * I valori delle stringhe sono tradotti; le chiavi, le icone e i token
 * tecnici restano invariati. Eventuali chiavi mancanti ricadono sul
 * fallback inglese (§10). I dati della FAQ provengono da content/faq-data.it.
 */
export const it: PartialDictionary = {
  common: {
    tagline: "Il suo partner affidabile nei servizi di traduzione professionale.",
    nav: {
      home: "Home",
      services: "Servizi",
      quote: "Richiedi un preventivo",
      corporate: "Aziende",
      partnership: "Partnership",
      blog: "Blog",
      faq: "FAQ",
      contact: "Contatti",
    },
    actions: {
      getQuote: "Richiedi un preventivo",
      calculatePrice: "Calcola il prezzo",
      uploadDocument: "Carica il documento",
      whatsapp: "Scrivici su WhatsApp",
      learnMore: "Scopri di più",
      viewAll: "Vedi tutto",
      showMore: "Mostra di più",
      showLess: "Mostra di meno",
      send: "Invia",
      apply: "Candidati",
      order: "Effettua l'ordine",
      contactUs: "Contattaci",
      openMenu: "Apri il menu",
      closeMenu: "Chiudi il menu",
      selectLanguage: "Seleziona la lingua",
      skipToContent: "Vai al contenuto",
      login: "Accedi",
      logout: "Esci",
      account: "Il mio account",
    },
    states: {
      loading: "Caricamento…",
      error: "Si è verificato un errore. Riprovi.",
      required: "Questo campo è obbligatorio.",
      demoNotice: "Demo: i dati del modulo non vengono ancora inviati a un server.",
      unverified: "Da verificare",
    },
    topbar: {
      phoneLabel: "Telefono",
      emailLabel: "E-mail",
      hoursLabel: "Orari di apertura",
      afterHours: "È disponibile un servizio di traduzione urgente al di fuori dell'orario di lavoro.",
      workingHours: "Nei giorni feriali 09:00 - 18:00 | Servizio disponibile fuori orario",
    },
  },

  home: {
    seo: {
      title: "TercümExpert — Servizi di traduzione professionale",
      description:
        "Traduzione giurata, autenticazione notarile e soluzioni di traduzione per aziende. Carichi il suo documento, ottenga un preventivo preliminare immediato e una consegna professionale.",
    },
    hero: {
      title: "Il suo partner affidabile nella traduzione",
      titleAccent: "professionale",
      subtitle: "Carichi il suo documento, veda il prezzo, riceva una consegna professionale.",
      support: "Traduzione giurata • Autenticazione notarile • Soluzioni per aziende",
    },
    trust: {
      title: "Perché si fidano di noi?",
      items: [
        { key: 'languages', label: "50+ lingue" },
        { key: 'delivery', label: "Consegna in 24 ore" },
        { key: 'notary', label: "Autenticazione notarile" },
        { key: 'quality', label: "Garanzia di qualità" },
      ],
    },
    stats: {
      title: "TercümExpert in numeri",
      note: "Le cifre riportate di seguito non sono presentate come affermazioni definitive finché non vengono verificate.",
      labels: {
        satisfaction: "Soddisfazione dei clienti",
        completed: "Lavori completati",
        languages: "Lingue supportate",
        corporate: "Clienti aziendali",
      },
    },
    howItWorks: {
      title: "Come funziona?",
      subtitle: "La traduzione professionale in cinque passaggi.",
      steps: [
        { key: 'upload', title: "Carica", desc: "Carichi il suo documento in tutta sicurezza." },
        { key: 'select', title: "Seleziona", desc: "Scelga la lingua e il tipo di servizio." },
        { key: 'confirm', title: "Conferma", desc: "Confermi il suo ordine." },
        { key: 'track', title: "Monitora", desc: "Segua il processo in tempo reale." },
        { key: 'receive', title: "Ricevi", desc: "Riceva la sua consegna professionale." },
      ],
    },
    services: {
      title: "I nostri servizi",
      subtitle: "Una traduzione esperta per ogni tipo di documento.",
    },
    why: {
      title: "Perché TercümExpert?",
      subtitle: "I punti di forza che ci distinguono dalla concorrenza",
      features: [
        { key: 'autoQuote', title: "Calcolo automatico del prezzo", desc: "Un prezzo preliminare in pochi secondi." },
        { key: 'whatsapp', title: "Preventivo rapido su WhatsApp", desc: "Contatto con un tocco." },
        { key: 'terminology', title: "Gestione della terminologia", desc: "Un linguaggio coerente e professionale." },
        { key: 'revision', title: "Diritto di revisione", desc: "Un processo orientato alla soddisfazione." },
        { key: 'languages', title: "Supporto per oltre 50 lingue", desc: "Un'ampia copertura di combinazioni linguistiche." },
        { key: 'terms', title: "Sistema di pagamento dilazionato per aziende", desc: "Un pagamento flessibile per le aziende." },
      ],
    },
    corporateCta: {
      title: "Soluzioni per aziende",
      desc: "Servizi linguistici professionali con gestione della terminologia, opzioni di pagamento dilazionato e un account manager dedicato, su misura per la sua azienda.",
      action: "Richiedi un preventivo aziendale",
    },
    partnershipTeaser: {
      title: "Programma di partnership",
      subtitle: "Guadagni il 20% di commissione su ogni cliente che ci segnala.",
      items: [
        { key: 'commission', title: "Commissione trasparente", desc: "20% di commissione per ogni segnalazione (previo accordo). Guadagni trasparenti grazie a un pannello di monitoraggio in tempo reale." },
        { key: 'qr', title: "Sistema con codice QR", desc: "Un monitoraggio dei clienti semplificato grazie all'integrazione sul biglietto da visita. Codici QR per web e WhatsApp." },
      ],
      cta: "Diventa partner",
    },
    testimonials: {
      title: "Recensioni dei clienti",
      subtitle: "Recensioni reali dei clienti verranno aggiunte qui prima del lancio.",
      placeholderNote: "Testo provvisorio — verranno integrate recensioni reali.",
      items: [
        { key: 't1', role: "Studio legale" },
        { key: 't2', role: "Struttura sanitaria" },
        { key: 't3', role: "Cliente aziendale" },
        { key: 't4', role: "Cliente privato" },
      ],
    },
    blogTeaser: {
      title: "Blog",
      subtitle: "Contenuti di attualità dal mondo della traduzione",
      viewAll: "Vedi tutti gli articoli del blog",
    },
    finalCta: {
      title: "Inizia subito",
      desc: "Carichi i suoi documenti, ottenga un preventivo immediato e approfitti dei servizi di traduzione professionale.",
      primary: "Richiedi un preventivo",
      secondary: "Contattaci",
    },
  },

  services: {
    seo: {
      title: "Servizi di traduzione",
      description:
        "Traduzione giurata, con autenticazione notarile, legale, tecnica, medica e accademica, oltre alla localizzazione web/mobile. Tipi di documenti, processo, consegna e combinazioni linguistiche.",
    },
    hero: {
      title: "Servizi di traduzione",
      subtitle: "Una traduzione con la terminologia adeguata a ogni ambito di competenza.",
    },
    process: {
      title: "Come si svolge il processo?",
      steps: [
        { title: "Esame del documento", desc: "Vengono valutati il tipo e lo scopo del documento." },
        { title: "Assegnazione a un esperto", desc: "Viene assegnato un traduttore specializzato nel settore." },
        { title: "Traduzione e revisione", desc: "Traduzione e revisione finale indipendente." },
        { title: "Autenticazione e consegna", desc: "Autenticazione notarile/apostille se necessario, quindi consegna." },
      ],
    },
    delivery: {
      title: "Opzioni di consegna",
      items: ["Consegna digitale (PDF/DOCX)", "Consegna fisica dei documenti", "Consegna urgente"],
    },
    notaryApostille: {
      title: "Rapporto tra autenticazione notarile e apostille",
      desc: "Quando richiesto, la traduzione giurata viene resa valida presso le istituzioni ufficiali tramite l'autenticazione notarile e la procedura di apostille. Il requisito esatto dipende dall'istituzione presso cui il documento verrà presentato.",
    },
    fullService: {
      title: "Chiavi in mano, consegnato a casa sua",
      note: "Ci invii i suoi documenti e gestiremo l'intero processo — traduzione, autenticazione notarile e apostille inclusi. I suoi documenti finiti arrivano a casa sua tramite corriere. Si concentri sul suo lavoro e lasci il resto a noi.",
    },
    cta: {
      title: "Non sa quale servizio le occorre?",
      desc: "Carichi il suo documento e le indicheremo il servizio e il prezzo più adatti.",
    },
    documentTypesTitle: "Tipi di documenti idonei",
  },

  serviceItems: {
    sworn: {
      name: "Traduzione giurata",
      short: "Traduzione ufficialmente valida con la firma e il timbro di un traduttore giurato.",
      benefits: ["Valida presso le istituzioni ufficiali", "Certificata da un traduttore giurato", "Processo rapido"],
    },
    notarized: {
      name: "Traduzione con autenticazione notarile",
      short: "Autenticazione notarile di una traduzione giurata.",
      benefits: ["Autenticazione notarile", "Adatta alle pratiche ufficiali", "Gestiamo noi il processo"],
    },
    apostille: {
      name: "Assistenza per la procedura di apostille",
      short: "Assistenza nella procedura di apostille per la validità all'estero.",
      benefits: ["Validità internazionale", "Consulenza sulla procedura", "Orientamento verso le istituzioni"],
    },
    legal: {
      name: "Traduzione legale",
      short: "Traduzione con padronanza della terminologia di contratti, documenti giudiziari e ufficiali.",
      benefits: ["Terminologia legale", "Garanzia di riservatezza", "Traduttore esperto"],
    },
    technical: {
      name: "Traduzione tecnica",
      short: "Traduzione coerente per manuali, capitolati e documenti tecnici.",
      benefits: ["Gestione della terminologia", "Formattazione preservata", "Competenza settoriale"],
    },
    medical: {
      name: "Traduzione medica",
      short: "Traduzione precisa per referti, foglietti illustrativi e documenti medici.",
      benefits: ["Terminologia medica", "Orientata all'accuratezza", "Riservatezza"],
    },
    academic: {
      name: "Traduzione accademica",
      short: "Un linguaggio accademico per tesi, articoli e traduzioni di diplomi.",
      benefits: ["Stile accademico", "Coerenza con la fonte", "Consegna puntuale"],
    },
    localization: {
      name: "Localizzazione web e mobile",
      short: "Localizzazione culturalmente adeguata di siti web e applicazioni.",
      benefits: ["Adattamento culturale", "Integrazione tecnica", "Compatibilità SEO"],
    },
  },

  corporate: {
    statsLabels: {
      corporate: "Clienti aziendali",
      discount: "Sconto su ordini in volume",
      term: "Termine di pagamento",
    },
    seo: {
      title: "Soluzioni per aziende",
      description:
        "Servizi linguistici professionali per le aziende con gestione della terminologia, opzioni di pagamento dilazionato, ordini in volume e un account manager dedicato.",
    },
    hero: {
      title: "Soluzioni per aziende",
      subtitle:
        "Servizi linguistici professionali con gestione della terminologia, opzioni di pagamento dilazionato e un account manager dedicato, su misura per la sua azienda.",
      primaryCta: "Richiedi un preventivo aziendale",
      secondaryCta: "Invia e-mail",
    },
    features: {
      title: "Funzionalità per aziende",
      subtitle: "Soluzioni su misura per la sua attività",
      items: [
        {
          key: 'custom',
          icon: 'Target',
          title: "Servizio personalizzato",
          points: ["Terminologia fissa", "Mantenimento del tono di voce del marchio", "Account manager dedicato", "Creazione di una guida di stile"],
        },
        {
          key: 'volume',
          icon: 'BarChart3',
          title: "Elaborazione in volume e pagamento dilazionato",
          points: ["Piani di traduzione mensili", "Sconti su ordini in volume", "Dilazioni fino a 30 giorni", "Sistema di fatturazione"],
        },
        {
          key: 'security',
          icon: 'Lock',
          title: "Riservatezza e sicurezza",
          points: ["Protocollo NDA", "Trasferimento di file crittografato", "Processi conformi al KVKK"],
        },
      ],
    },
    whyPackage: {
      title: "Perché un pacchetto aziendale?",
      items: [
        {
          key: 'terminology',
          icon: 'Building2',
          title: "Gestione della terminologia fissa",
          desc: "Costruiamo una banca terminologica specifica per la sua azienda. Il linguaggio del suo marchio viene preservato in tutte le traduzioni e ne garantiamo la coerenza. Ci impegniamo a utilizzare gli stessi termini in ogni progetto.",
        },
        {
          key: 'manager',
          icon: 'Users',
          title: "Account manager dedicato",
          desc: "Il suo account manager dedicato segue tutti i suoi processi. Con una linea di assistenza accessibile, siamo al suo fianco nelle situazioni urgenti.",
        },
        {
          key: 'security',
          icon: 'ShieldCheck',
          title: "Riservatezza e sicurezza",
          desc: "Lavoriamo secondo un protocollo NDA. I suoi dati sono al sicuro grazie a una solida infrastruttura di sicurezza, al trasferimento di file crittografato e a processi conformi al KVKK.",
        },
      ],
    },
    payment: {
      title: "Opzioni di pagamento",
      subtitle: "Piani di pagamento flessibili adatti alla sua attività",
      recommendedLabel: "CONSIGLIATO",
      options: [
        {
          key: 'standard',
          label: "Pagamento immediato",
          heading: "Standard",
          desc: "Pagamento con carta di credito o bonifico bancario dopo ogni ordine",
          points: ["Rateizzazione con carta di credito", "Consegna immediata"],
          recommended: false,
        },
        {
          key: 'term',
          label: "Dilazione mensile",
          heading: "15-30 giorni",
          desc: "Fatturazione mensile consolidata e opzione di pagamento dilazionato",
          points: ["Dilazione a 30 giorni", "Sconto sul volume", "Report mensile"],
          recommended: true,
        },
      ],
    },
    form: {
      title: "Richiesta di pacchetto aziendale",
      desc: "Compili il modulo e il nostro team di esperti la contatterà",
      fields: {
        company: "Nome dell'azienda",
        contactName: "Nome e cognome del referente",
        email: "E-mail",
        phone: "Telefono",
        need: "Ci parli delle sue esigenze di traduzione",
        consent: "Ho letto e approvo l'<kvkk>Informativa KVKK</kvkk>.",
      },
      submit: "Invia la richiesta",
      success: "La sua richiesta è stata ricevuta. Le risponderemo il prima possibile.",
      note: "Le risponderemo entro 1 giorno lavorativo.",
    },
  },

  partnership: {
    seo: {
      title: "Programma di partnership",
      description:
        "Guadagni una commissione su ogni cliente che segnala. Report trasparenti, segnalazioni con codice QR e assistenza professionale.",
    },
    hero: {
      title: "Programma di partnership",
      value: "Guadagni il 20% di commissione su ogni cliente che ci segnala.",
      subtitle: "Un sistema trasparente, pagamenti affidabili, una collaborazione a lungo termine.",
      cta: "Candidati ora",
    },
    advantages: {
      title: "Vantaggi per il partner",
      subtitle: "Perché diventare partner di TercümExpert?",
      items: [
        { key: 'commission', icon: 'Wallet', title: "20% di commissione garantita", desc: "Un sistema di commissioni trasparente per ogni cliente che segnala." },
        { key: 'qr', icon: 'QrCode', title: "Segnalazione con codice QR", desc: "Un monitoraggio dei clienti semplificato grazie all'integrazione sul biglietto da visita." },
        { key: 'reporting', icon: 'BarChart3', title: "Report trasparenti", desc: "Un pannello di monitoraggio delle commissioni e dei clienti in tempo reale." },
        { key: 'support', icon: 'Users', title: "Assistenza professionale", desc: "Una linea di assistenza dedicata ai partner e un account manager." },
      ],
    },
    howItWorks: {
      title: "Come funziona?",
      steps: [
        { title: "Candidati", desc: "Compili il modulo di candidatura online. Ci comunichi le informazioni sulla sua azienda e i suoi dati di contatto. La sua candidatura viene esaminata entro 1 giorno lavorativo." },
        { title: "Diventa partner", desc: "Una volta approvata la sua candidatura, ottiene l'accesso al suo pannello partner dedicato. I suoi codici QR e i link di segnalazione sono pronti." },
        { title: "Segnala i clienti", desc: "Ci segnali i suoi clienti tramite codice QR, link personalizzato o biglietto da visita. Ogni segnalazione viene registrata automaticamente nel sistema." },
        { title: "Guadagna commissioni", desc: "Guadagna il 20% di commissione ogni volta che un cliente da lei segnalato effettua un ordine. Riceve pagamenti automatici ogni 15 giorni." },
      ],
    },
    sectors: {
      title: "Settori target",
      subtitle: "Per quali settori è ideale?",
      items: [
        { key: 'law', icon: 'Scale', title: "Studi legali", desc: "Necessità di traduzione giurata di fascicoli, contratti e documenti legali." },
        { key: 'visa', icon: 'Plane', title: "Consulenza per visti", desc: "Documenti che richiedono una traduzione giurata come passaporti, diplomi e atti di stato civile." },
        { key: 'education', icon: 'GraduationCap', title: "Consulenza per gli studi", desc: "Traduzione giurata di documenti degli studenti e procedure di apostille." },
        { key: 'health', icon: 'HeartPulse', title: "Turismo sanitario", desc: "Traduzione di referti medici, cartelle cliniche e documenti sanitari." },
        { key: 'patent', icon: 'Building2', title: "Uffici brevetti/marchi", desc: "Traduzione tecnica di brevetti, registrazioni di marchi e documenti legali." },
        { key: 'realestate', icon: 'Home', title: "Agenzie immobiliari", desc: "Traduzione di atti di proprietà, contratti e documenti ufficiali per investitori stranieri." },
        { key: 'hr', icon: 'Briefcase', title: "Consulenza HR", desc: "Traduzione di CV, diplomi e lettere di referenze per collocamento all'estero." },
        { key: 'software', icon: 'Code', title: "Aziende di software", desc: "Localizzazione di applicazioni web e mobile, traduzione di documenti tecnici." },
      ],
    },
    commission: {
      title: "Struttura delle commissioni",
      stats: {
        commissionLabel: "Commissione standard",
        commissionSub: "Su ogni ordine",
        periodUnit: "Giorni",
        periodLabel: "Periodo di pagamento",
        feeLabel: "Costo di attivazione",
        feeSub: "Completamente gratuito",
      },
      exampleTitle: "Esempio di calcolo dei guadagni",
      exampleOrderLabel: "Ordine del cliente da lei segnalato",
      exampleRateLabel: "Tasso di commissione",
      exampleEarningLabel: "I suoi guadagni",
      note: "I tassi e le condizioni delle commissioni sono soggetti al contratto di partnership.",
    },
    form: {
      title: "Modulo di candidatura partner",
      subtitle: "Compili il modulo e le risponderemo entro 1 giorno lavorativo.",
      fields: {
        company: "Nome dell'azienda/organizzazione",
        sector: "Settore",
        contactName: "Nome e cognome del referente",
        titleRole: "Qualifica",
        email: "E-mail",
        phone: "Telefono",
        potential: "Il suo potenziale mensile stimato di segnalazioni",
        note: "Eventuali note che desidera aggiungere",
        agreement: "Ho letto e accetto le condizioni del <partnership>contratto di partnership</partnership>.",
      },
      sectorPlaceholder: "Seleziona",
      sectorOptions: ["Studio legale", "Consulenza per visti", "Consulenza per gli studi", "Turismo sanitario", "Ufficio brevetti/marchi", "Immobiliare", "Consulenza HR", "Software", "Altro"],
      potentialOptions: ["1-5 clienti", "5-10 clienti", "10-20 clienti", "20+ clienti"],
      submit: "Invia la candidatura",
      success: "La sua candidatura è stata ricevuta. La contatteremo.",
      note: "La sua candidatura sarà esaminata entro 1 giorno lavorativo.",
    },
  },

  quote: {
    seo: {
      title: "Calcolo immediato del prezzo",
      description: "Carichi il suo documento o inserisca i dettagli e ottenga il suo preventivo preliminare immediato.",
    },
    hero: {
      title: "Calcolo immediato del prezzo",
      subtitle: "Carichi il suo documento o inserisca i dettagli e ottenga un preventivo preliminare immediato.",
    },
    upload: {
      heading: "Carichi i suoi documenti",
      privacy: "I suoi dati sono trattati in modo riservato",
      tabFile: "Carica un file",
      tabText: "Inserisci il testo",
      chooseFile: "Scelga i suoi documenti",
      formats: ".docx, .xlsx, .pdf, .pptx, .jpg, .png e 50+ formati accettati · Max 100MB per file",
      dropHint: "Può trascinare e rilasciare uno o più file in quest'area.",
      textPlaceholder: "Incolli o digiti qui il suo testo…",
      totalWords: "Numero totale di parole",
      extracting: "Conteggio delle parole…",
      wordsUnit: "parole",
      remove: "Rimuovi",
      unsupported:
        "Il conteggio automatico delle parole non è stato possibile per questo tipo di file. Incolli il testo tramite \"Inserisci il testo\"; il conteggio sarà verificato dal nostro team in fase di preventivo.",
      empty:
        "Nessun testo selezionabile è stato trovato nel file (potrebbe trattarsi di una scansione/di un'immagine). Utilizzi \"Inserisci il testo\", altrimenti il conteggio sarà verificato in fase di preventivo.",
      error: "Non è stato possibile leggere il file. Riprovi o utilizzi \"Inserisci il testo\".",
      tooLarge: "Il file non può superare i 100MB.",
      needInput: "Per ottenere un prezzo, carichi un file o inserisca del testo.",
    },
    fields: {
      upload: "Carica un documento (facoltativo)",
      uploadHint: "PDF, DOC, DOCX o TXT — max 10 MB",
      sourceLang: "Lingua di partenza",
      targetLang: "Lingua di destinazione",
      serviceType: "Tipo di servizio",
      documentType: "Tipo di documento",
      wordCount: "Numero di parole stimato",
      wordCountHint: "Utilizzi il cursore o inserisca il numero manualmente.",
      options: "Opzioni aggiuntive",
      calculate: "Calcola il prezzo",
    },
    options: {
      urgent: "Consegna urgente",
      notarization: "Autenticazione notarile",
      physicalDelivery: "Consegna fisica",
    },
    languages: {
      tr: "Turco",
      en: "Inglese",
      de: "Tedesco",
      fr: "Francese",
      es: "Spagnolo",
      it: "Italiano",
      ru: "Russo",
      ar: "Arabo",
      nl: "Olandese",
      az: "Azero",
      pl: "Polacco",
      bg: "Bulgaro",
      pt: "Portoghese",
      da: "Danese",
    },
    documentTypes: {
      diploma: "Diploma",
      passport: "Passaporto",
      'civil-registry': "Estratto dello stato civile",
      contract: "Contratto",
      'medical-report': "Referto medico",
      'technical-doc': "Documento tecnico",
      'court-doc': "Documento giudiziario",
      other: "Altro",
    },
    result: {
      title: "Preventivo preliminare",
      basePrice: "Costo del servizio di base",
      wordPrice: "Tariffa a parola",
      addons: "Servizi aggiuntivi",
      total: "Totale",
      vat: "IVA",
      delivery: "Tempi di consegna stimati",
      deliveryUnit: "giorni lavorativi",
      disclaimer: "Questo è un preventivo preliminare; il prezzo finale viene confermato dopo l'esame del documento.",
      order: "Effettua l'ordine",
      whatsapp: "Contattaci su WhatsApp",
      estimatedWords: "Parole stimate (automatico — demo)",
    },
    orderConfirm: {
      title: "Il suo ordine è stato ricevuto",
      number: "N. ordine",
      desc: "La sua richiesta e i suoi documenti sono stati salvati. Il nostro team di esperti esaminerà il documento e la contatterà il prima possibile.",
      viewOrders: "I miei ordini",
      submitting: "Creazione dell'ordine…",
      error: "Si è verificato un problema durante la creazione del suo ordine. Riprovi.",
    },
    gate: {
      title: "Il suo prezzo è pronto",
      subtitle: "Acceda o verifichi i suoi dati per vedere il prezzo ed effettuare un ordine.",
      loginCta: "Accedi / Registrati",
      or: "oppure prosegua rapidamente",
      firstName: "Nome",
      lastName: "Cognome",
      email: "E-mail",
      phone: "Numero di telefono",
      sendCode: "Invia il codice di verifica",
      codeLabel: "Codice di verifica",
      codeSentA: "ha ricevuto un codice di verifica.",
      verify: "Verifica e vedi il prezzo",
      resend: "Reinvia il codice",
      resent: "È stato inviato un nuovo codice.",
      back: "Modifica i dati",
      errNames: "Nome e cognome sono obbligatori.",
      errEmail: "Inserisca un'e-mail valida.",
      errPhone: "Inserisca un numero di telefono valido.",
      errCode: "Inserisca il codice per intero.",
      note: "La sua e-mail viene utilizzata solo per il preventivo e l'ordine.",
    },
    note: {
      label: "Nota sul suo ordine (facoltativo)",
      placeholder: "Può indicare qui le sue richieste di consegna, terminologia o richieste particolari.",
    },

    checkout: {
      title: "Dettagli di consegna",
      subtitle: "Il suo documento fisico/giurato sarà spedito a questo indirizzo.",
      firstName: "Nome",
      lastName: "Cognome",
      phone: "Telefono",
      address: "Indirizzo completo",
      addressPlaceholder: "Via, numero civico e interno…",
      city: "Città",
      postalCode: "Codice postale",
      country: "Paese",
      submit: "Completa l'ordine",
      submitting: "Creazione dell'ordine…",
      cancel: "Annulla",
      errRequired: "Compili i campi obbligatori.",
      note: "Queste informazioni sono utilizzate solo per la consegna tramite corriere.",
    },
  },

  order: {
    seo: {
      title: "Monitoraggio dell'ordine",
      description: "Segua lo stato del suo ordine.",
    },
    numberLabel: "N. ordine",
    placedOn: "Data dell'ordine",
    estimatedLabel: "Consegna stimata della traduzione",
    cargoEstimatedLabel: "Data di spedizione stimata",
    timelineTitle: "Stato dell'ordine",
    steps: {
      received: "Il suo ordine è stato ricevuto",
      in_progress: "In lavorazione",
      translated: "Traduzione completata",
      shipped: "Spedito",
      delivered: "Consegnato",
      cancelled: "Ordine annullato",
    },
    stepDesc: {
      received: "La sua richiesta e i suoi documenti sono arrivati nel nostro sistema. Il nostro team di esperti li esaminerà e inizierà a breve.",
      in_progress: "Il nostro traduttore esperto ha iniziato la sua traduzione.",
      translated: "La sua traduzione è completata e i controlli finali sono stati effettuati.",
      shipped: "Il suo documento è stato consegnato al corriere; può monitorarlo con il pulsante qui sotto.",
      delivered: "Il suo documento le è stato inviato via e-mail.",
      cancelled: "Questo ordine è stato annullato. Non esiti a contattarci per qualsiasi domanda.",
    },
    cargoReady: "Il suo documento è stato spedito. Lo segua con un tocco:",
    cargoPending: "Il codice di tracciamento apparirà qui una volta spedito il suo documento.",
    trackCargo: "Traccia la mia spedizione",
    digitalPending: "Una volta completata la sua traduzione, i suoi file le verranno inviati via e-mail.",
    digitalDelivered: "La sua traduzione le è stata inviata via e-mail. Controlli la sua casella di posta (e la cartella spam).",
    detailsTitle: "Dettagli dell'ordine",
    fields: {
      service: "Servizio",
      langs: "Lingue",
      documentType: "Tipo di documento",
      words: "Parole",
      delivery: "Tempo stimato",
      total: "Importo",
      note: "La sua nota",
      deliveryAddress: "Indirizzo di consegna",
    },
    myOrders: "I miei ordini",
    backHome: "Torna alla home",
    whatsapp: "Contattaci su WhatsApp",
    loading: "Caricamento dell'ordine…",
    loginRequired: {
      title: "Acceda per visualizzare il suo ordine",
      desc: "Può accedere ai dettagli del suo ordine solo dopo aver effettuato l'accesso con il suo account.",
      login: "Accedi",
    },
    notFound: {
      title: "Ordine non trovato",
      desc: "Questo numero d'ordine non le appartiene o non esiste. Verifichi il link.",
      home: "Torna alla home",
    },
  },

  faq: {
    seo: {
      title: "Domande frequenti",
      description: "Domande frequenti su traduzione giurata, tempi di consegna, prezzi, autenticazione notarile e pagamento dilazionato per aziende.",
    },
    hero: { title: "Domande frequenti", subtitle: "La risposta che cerca è qui." },
    categoriesTitle: "Categorie",
    searchPlaceholder: "Cerca domande o parole chiave…",
    empty: "Nessuna domanda corrisponde alla sua ricerca. Provi con un'altra parola o ci contatti.",
    categories: FAQ_CATEGORIES_IT,
    items: FAQ_ITEMS_IT,
    notFound: {
      title: "Non ha trovato la risposta alla sua domanda?",
      contact: "Contattaci",
      whatsapp: "Assistenza WhatsApp",
    },
  },

  contact: {
      introTitle: `Benvenuto`,
      introDesc: `Prima di iniziare, posso avere il Suo nome e il Suo indirizzo e-mail per poterLa assistere al meglio?`,
      start: `Inizia la chat`,
      introError: `La preghiamo di inserire il Suo nome e il Suo indirizzo e-mail.`,
    seo: {
      title: "Contatti",
      description: "Si metta in contatto con TercümExpert: telefono, e-mail, WhatsApp e modulo di contatto.",
    },
    hero: { title: "Contatti", subtitle: "Come possiamo aiutarla?" },
    infoTitle: "Informazioni di contatto",
    labels: {
      phone: "Telefono",
      email: "E-mail",
      whatsapp: "WhatsApp",
      address: "Indirizzo",
      hours: "Orari di apertura",
    },
    form: {
      title: "Contattaci",
      fields: {
        name: "Nome e cognome",
        email: "E-mail",
        phone: "Telefono",
        subject: "Oggetto",
        message: "Messaggio",
        consent: "Ho letto e approvo l'<kvkk>Informativa KVKK</kvkk>.",
      },
      submit: "Invia il messaggio",
      success: "Il suo messaggio è stato ricevuto. Le risponderemo a breve.",
    },
    map: {
      title: "La nostra sede",
      subtitle: "Ci trovi sulla mappa",
      placeholder: "Area della mappa",
      note: "La mappa della sede verrà mostrata qui a breve.",
    },
  },

  auth: {
    seo: {
      title: "Accedi / Registrati",
      description: "Acceda al suo account TercümExpert o ne crei uno nuovo.",
    },
    tabs: { login: "Accedi", register: "Registrati" },
    google: "Continua con Google",
    or: "oppure",
    fields: {
      firstName: "Nome",
      lastName: "Cognome",
      email: "E-mail",
      password: "Password",
      code: "Codice di verifica",
    },
    login: {
      title: "Acceda al suo account",
      submit: "Accedi",
      noAccount: "Non ha un account?",
      switchToRegister: "Registrati",
    },
    register: {
      title: "Crea un nuovo account",
      submit: "Registrati",
      haveAccount: "Ha già un account?",
      switchToLogin: "Accedi",
      consent: "Creando un account, accetto l'<kvkk>Informativa KVKK</kvkk> e l'<privacy>Informativa sulla privacy</privacy>.",
    },
    verify: {
      title: "Verifichi la sua e-mail",
      desc: "— inserisca il codice a 6 cifre che abbiamo inviato a questo indirizzo.",
      submit: "Verifica e continua",
      spam: "Il codice potrebbe ritardare di alcuni minuti; controlli anche la cartella spam/posta indesiderata.",
      resend: "Reinvia il codice",
      resent: "È stato inviato un nuovo codice.",
      back: "Torna indietro",
    },
    signedIn: {
      title: "Il mio account",
      greeting: "Benvenuto",
      logout: "Esci",
    },
    orders: {
      title: "I miei ordini",
      empty: "Non ha ancora ordini. Può creare il suo primo ordine da Calcola il prezzo.",
      loading: "Caricamento degli ordini…",
      error: "Non è stato possibile caricare gli ordini. Aggiorni la pagina.",
      status: {
        received: "Ricevuto",
        in_progress: "In lavorazione",
        translated: "Traduzione completata",
        shipped: "Spedito",
        delivered: "Consegnato",
        cancelled: "Annullato",
      },
      track: "Traccia",
    },
    errors: {
      nameRequired: "Nome e cognome sono obbligatori.",
      emailInvalid: "Inserisca un'e-mail valida.",
      passwordShort: "La password deve contenere almeno 6 caratteri.",
      codeInvalid: "Inserisca il codice a 6 cifre.",
      consentRequired: "È necessaria l'approvazione per continuare.",
    },
  },

  blog: {
    seo: { title: "Blog", description: "Contenuti guida su traduzione, notariato, apostille e localizzazione." },
    hero: { title: "Blog", subtitle: "Guide dal mondo della traduzione." },
    searchPlaceholder: "Cerca articoli…",
    readingTime: "min di lettura",
    relatedTitle: "Articoli correlati",
    allCategories: "Tutte",
    empty: "Nessun articolo corrisponde a questo criterio.",
  },

  legal: {
    lastUpdatedLabel: `Ultimo aggiornamento`,
    draftNotice: `Nel testo che segue, i campi indicati tra parentesi quadre ([...]) dovranno essere compilati con i dati della Sua azienda. I testi hanno finalità meramente informative e se ne raccomanda la revisione da parte di un professionista legale prima della pubblicazione.`,
    kvkk: {
      seo: { title: `Informativa KVKK`, description: `Informativa relativa al trattamento dei Suoi dati personali ai sensi della legge KVKK n. 6698.` },
      title: `Informativa KVKK`,
      sections: [
        { heading: `Titolare del trattamento`, body: `Ai sensi della legge sulla protezione dei dati personali n. 6698 (“KVKK”), i Suoi dati personali sono trattati, in qualità di titolare del trattamento, da [ŞİRKET ÜNVANI] (“TercümExpert”) nell'ambito di seguito descritto. Indirizzo: [ADRES]. E-mail: [E-POSTA]. Telefono: [TELEFON].` },
        { heading: `Dati personali trattati`, body: `Sono trattati i Suoi dati anagrafici e di contatto (nome, cognome, indirizzo e-mail, numero di telefono), i dati relativi all'indirizzo di consegna, i dati relativi agli ordini e alle transazioni, i dati contenuti nei documenti da Lei trasmessici ai fini della traduzione, nonché i dati di sicurezza delle transazioni relativi al Suo utilizzo del sito (indirizzo IP, registri di sessione e cookie).` },
        { heading: `Finalità del trattamento`, body: `I Suoi dati personali sono trattati al fine di erogare i servizi relativi a traduzioni, traduzioni giurate, autenticazioni notarili e apostille, di elaborare i preventivi e gestire gli ordini, di gestire i rapporti con la clientela nonché le richieste e i reclami, di adempiere agli obblighi contrattuali e di legge e di garantire la sicurezza del servizio.` },
        { heading: `Basi giuridiche del trattamento`, body: `I Suoi dati sono trattati sulla base delle seguenti basi giuridiche: la necessità ai fini della conclusione o dell'esecuzione di un contratto, l'adempimento dei nostri obblighi di legge, l'accertamento e la tutela di un diritto e il nostro legittimo interesse, a condizione di non arrecare pregiudizio ai Suoi diritti e alle Sue libertà fondamentali; ove necessario, il trattamento avviene sulla base del Suo consenso esplicito (KVKK m.5 e m.6).` },
        { heading: `Modalità di raccolta`, body: `I Suoi dati personali sono raccolti in formato elettronico tramite i moduli presenti sul sito web, i processi di registrazione e di ordine, la posta elettronica e gli altri canali di comunicazione.` },
        { heading: `Trasferimento dei dati personali`, body: `Nella misura richiesta dal servizio, i Suoi dati possono essere trasferiti ai nostri fornitori situati in Turchia e all'estero dai quali riceviamo servizi di hosting, infrastruttura, autenticazione, posta elettronica e analisi, nonché alle autorità e agli enti pubblici competenti, in conformità alle condizioni previste dagli artt. KVKK m.8 e m.9. Poiché i server di alcuni fornitori di infrastruttura e servizi da noi utilizzati si trovano all'estero, i Suoi dati possono essere trasferiti all'estero nel rispetto delle garanzie previste dalla normativa.` },
        { heading: `Periodi di conservazione`, body: `I Suoi dati personali sono conservati per il periodo richiesto dalla finalità del trattamento e per i termini di prescrizione e di conservazione previsti dalla normativa applicabile (quale la normativa fiscale, commerciale e in materia di consumo); allo scadere di tali termini vengono cancellati, distrutti o resi anonimi.` },
        { heading: `Diritti dell'interessato`, body: `Ai sensi dell'art. KVKK m.11, Lei ha il diritto di: sapere se i Suoi dati personali siano trattati e, in caso affermativo, richiedere informazioni al riguardo; conoscere la finalità del trattamento e se i dati siano utilizzati conformemente a tale finalità; conoscere i terzi a cui i dati siano stati trasferiti, in Turchia o all'estero; richiedere la rettifica dei dati trattati in modo incompleto o inesatto e, ove ne ricorrano le condizioni, la loro cancellazione o distruzione; richiedere che tali operazioni siano comunicate ai terzi a cui i dati siano stati trasferiti; opporsi al verificarsi di un risultato a Suo sfavore derivante dall'analisi esclusivamente mediante sistemi automatizzati; e richiedere il risarcimento del danno in caso di pregiudizio subito.` },
        { heading: `Modalità di presentazione della richiesta`, body: `Le richieste relative ai Suoi diritti possono essere trasmesse per iscritto all'indirizzo [E-POSTA] o all'indirizzo [ADRES], in conformità al “Veri Sorumlusuna Başvuru Usul ve Esasları Hakkında Tebliğ”. La Sua richiesta sarà evasa nel più breve tempo possibile e comunque entro trenta giorni, in base alla sua natura.` },
      ],
    },
    privacy: {
      seo: { title: `Informativa sulla privacy`, description: `La nostra informativa in materia di riservatezza dei Suoi dati personali e documenti.` },
      title: `Informativa sulla privacy`,
      sections: [
        { heading: `Introduzione`, body: `In TercümExpert teniamo alla Sua riservatezza. La presente Informativa sulla privacy illustra quali informazioni raccogliamo, per quali finalità e come le proteggiamo nell'ambito dei servizi offerti tramite [WEB ADRESİ]. Per informazioni dettagliate sul trattamento dei dati personali può consultare l'Informativa KVKK.` },
        { heading: `Informazioni che raccogliamo`, body: `Possiamo raccogliere informazioni relative all'account e ai contatti (nome, cognome, e-mail, telefono), informazioni relative all'ordine e alla consegna, i documenti da Lei trasmessici per la traduzione e i loro contenuti, le informazioni sulle transazioni di pagamento e i dati tecnici relativi al Suo utilizzo del sito (indirizzo IP, informazioni sul browser, registri dei cookie).` },
        { heading: `Finalità di utilizzo delle informazioni`, body: `Utilizziamo le Sue informazioni per erogare i servizi, gestire preventivi e ordini, comunicare con Lei, adempiere ai nostri obblighi di legge e migliorare la qualità e la sicurezza del servizio. Trattiamo i Suoi documenti esclusivamente nella misura richiesta dal servizio da Lei richiesto.` },
        { heading: `Riservatezza dei documenti`, body: `I documenti oggetto di traduzione sono considerati riservati. A tali documenti accedono esclusivamente il traduttore e il personale autorizzato che eseguono il relativo servizio, per il tempo richiesto dall'incarico; i Suoi documenti non sono condivisi con terzi per finalità diverse da quelle del servizio.` },
        { heading: `Fornitori di servizi terzi`, body: `Nell'erogazione dei nostri servizi ci avvaliamo di fornitori terzi affidabili negli ambiti dell'hosting e dell'infrastruttura, dell'autenticazione, dell'invio di e-mail, dell'analisi e (ove attivato) dei pagamenti. Tali fornitori possono accedere ai Suoi dati esclusivamente al fine di erogare il servizio loro affidato e sono soggetti a obblighi contrattuali di riservatezza; i server di alcuni di essi possono trovarsi all'estero.` },
        { heading: `Sicurezza dei dati`, body: `Per proteggere i Suoi dati da accessi non autorizzati, applichiamo la cifratura durante la trasmissione, restrizioni di accesso e adeguate misure amministrative e tecniche. Sebbene nessun metodo possa garantire una sicurezza assoluta, adottiamo misure ragionevoli e aggiornate per proteggere i Suoi dati.` },
        { heading: `Cookie`, body: `Sul nostro sito vengono utilizzati cookie e tecnologie analoghe. Per informazioni dettagliate sulle tipologie e sulla gestione delle preferenze può consultare l'Informativa sui cookie.` },
        { heading: `I Suoi diritti`, body: `Può esercitare i Suoi diritti previsti dalla KVKK, compresi quelli di accesso, rettifica e cancellazione dei Suoi dati personali. Per le Sue richieste può contattarci all'indirizzo [E-POSTA].` },
        { heading: `Riservatezza dei minori`, body: `I nostri servizi non sono rivolti a persone di età inferiore ai 18 anni e non raccogliamo consapevolmente dati personali di minori.` },
        { heading: `Modifiche`, body: `La presente informativa può essere aggiornata di tanto in tanto. La versione aggiornata è sempre pubblicata su questa pagina; in caso di modifiche rilevanti sarà fornita opportuna comunicazione con modalità adeguate.` },
        { heading: `Contatti`, body: `Per domande relative alla privacy: E-mail: [E-POSTA] · Telefono: [TELEFON] · Indirizzo: [ADRES].` },
      ],
    },
    distanceSales: {
      seo: { title: `Contratto di vendita a distanza`, description: `Contratto di vendita a distanza relativo alla vendita di servizi ai sensi della legge n. 6502.` },
      title: `Contratto di vendita a distanza`,
      sections: [
        { heading: `Parti`, body: `Il presente Contratto di vendita a distanza (“Contratto”) è concluso in formato elettronico, da una parte tra [ŞİRKET ÜNVANI] (“Venditore”; indirizzo: [ADRES], e-mail: [E-POSTA], telefono: [TELEFON]) e dall'altra il consumatore che effettua l'ordine (“Acquirente”), ai sensi della legge sulla tutela del consumatore n. 6502 e del Mesafeli Sözleşmeler Yönetmeliği.` },
        { heading: `Oggetto del contratto`, body: `Oggetto del Contratto è l'erogazione dei servizi relativi a traduzioni, traduzioni giurate, autenticazioni notarili e apostille, ordinati dall'Acquirente in formato elettronico tramite [WEB ADRESİ], le cui caratteristiche e il cui prezzo di vendita sono indicati nel riepilogo dell'ordine.` },
        { heading: `Caratteristiche e prezzo del servizio`, body: `La tipologia, l'ambito, la modalità di consegna (digitale o tramite corriere) e il prezzo totale comprensivo di imposte del servizio ordinato sono indicati chiaramente all'Acquirente al momento dell'ordine e riportati nella conferma d'ordine. Il prezzo è calcolato in base al servizio selezionato e alle caratteristiche del documento.` },
        { heading: `Pagamento`, body: `Il pagamento è effettuato mediante i metodi di pagamento proposti nella fase di ordine. L'ordine è preso in carico dopo la conferma del pagamento.` },
        { heading: `Esecuzione e consegna`, body: `Per le consegne digitali, la traduzione viene trasmessa, una volta completata, tramite l'account o l'e-mail dell'Acquirente. Per i documenti fisici, con firma autografa o giurati, la consegna avviene tramite corriere all'indirizzo indicato dall'Acquirente. I tempi di consegna stimati sono indicati al momento dell'ordine; possono variare in base alla mole del documento e ai processi di autenticazione.` },
        { heading: `Diritto di recesso`, body: `Di regola, nei contratti relativi all'erogazione di servizi, l'Acquirente ha il diritto di recedere entro quattordici (14) giorni dalla data di conclusione del contratto senza dover fornire alcuna motivazione. Restano tuttavia salve le eccezioni di seguito indicate.` },
        { heading: `Eccezioni al diritto di recesso`, body: `Ai sensi dell'art. m.15 del Mesafeli Sözleşmeler Yönetmeliği, il diritto di recesso non può essere esercitato per i servizi la cui esecuzione sia iniziata con il consenso dell'Acquirente e sia stata completata prima della scadenza del termine di recesso, nonché per i beni e servizi predisposti su misura in base alle richieste o alle esigenze personali dell'Acquirente (compresi i servizi di traduzione e autenticazione predisposti su misura per la persona o per il documento). Le richieste di annullamento trasmesse prima dell'inizio del lavoro di traduzione sono valutate separatamente.` },
        { heading: `Annullamento e rimborso`, body: `Per gli ordini la cui esecuzione non sia ancora iniziata, le richieste di annullamento possono essere trasmesse all'indirizzo [E-POSTA]; i rimborsi ritenuti ammissibili sono effettuati entro un termine ragionevole con il medesimo metodo utilizzato per il pagamento. Per i servizi su misura la cui esecuzione sia iniziata o sia stata completata, il rimborso può non essere possibile in ragione della natura dell'incarico.` },
        { heading: `Risoluzione delle controversie`, body: `Per le controversie che dovessero sorgere dal presente Contratto sono competenti, entro i limiti monetari annualmente stabiliti dal Ticaret Bakanlığı, i Tüketici Hakem Heyetleri del luogo di residenza dell'Acquirente o del luogo in cui è stata effettuata la transazione, nonché i Tribunali del Consumatore.` },
        { heading: `Entrata in vigore`, body: `Confermando l'ordine, l'Acquirente dichiara di aver letto e accettato tutte le condizioni del presente Contratto. Il Contratto entra in vigore con la conferma dell'ordine.` },
      ],
    },
    cookies: {
      seo: { title: `Informativa sui cookie`, description: `Informazioni sui cookie utilizzati sul nostro sito e sulla gestione delle preferenze.` },
      title: `Informativa sui cookie`,
      sections: [
        { heading: `Che cosa sono i cookie?`, body: `I cookie sono piccoli file di testo che vengono salvati nel Suo browser quando visita un sito web. Sono utilizzati per rendere il sito più sicuro e funzionale, per ricordare le Sue preferenze e per ottenere statistiche di utilizzo.` },
        { heading: `Perché utilizziamo i cookie?`, body: `Utilizziamo i cookie per garantire le funzionalità essenziali del sito, tutelare la sicurezza della sessione, misurare le prestazioni e, previo Suo consenso, migliorare i nostri servizi e svolgere attività di marketing.` },
        { heading: `Categorie di cookie`, body: `I cookie necessari sono indispensabili per il funzionamento e la sicurezza del sito e non possono essere disattivati. I cookie di prestazione e analitici ci aiutano a comprendere l'interazione dei visitatori. I cookie di marketing contribuiscono a fornire contenuti e annunci pubblicitari in linea con i Suoi interessi. I cookie di preferenza ricordano le Sue scelte, quali la lingua. I cookie analitici e di marketing operano esclusivamente previo Suo consenso esplicito.` },
        { heading: `Cookie di terze parti`, body: `Per finalità analitiche e di marketing possiamo avvalerci di servizi di terze parti (ad esempio strumenti di statistica dei visitatori e di misurazione della pubblicità). Tali servizi possono installare propri cookie e trattare i dati nell'ambito delle rispettive informative sulla privacy.` },
        { heading: `Gestione delle preferenze sui cookie`, body: `Può esprimere o modificare in qualsiasi momento le Sue preferenze relative ai cookie non necessari tramite lo strumento di gestione delle preferenze sui cookie presente sul sito. Può inoltre eliminare o bloccare i cookie dalle impostazioni del Suo browser; in tal caso, tuttavia, alcune sezioni del sito potrebbero non funzionare correttamente.` },
        { heading: `Periodi di conservazione`, body: `I cookie, a seconda della tipologia, sono conservati per la durata della sessione o per un periodo determinato. I cookie di sessione vengono eliminati alla chiusura del browser; i cookie persistenti scadono invece al termine del periodo stabilito o quando Lei li elimina.` },
        { heading: `Modifiche`, body: `La presente Informativa sui cookie può essere aggiornata di tanto in tanto. La versione aggiornata è sempre pubblicata su questa pagina.` },
      ],
    },
    partnership: {
      seo: { title: `Contratto di Partnership`, description: `I termini del programma di partnership (partner) di TercümExpert.` },
      title: `Contratto di Partnership`,
      sections: [
        { heading: `Parti e Oggetto`, body: `Il presente Contratto di Partnership è stipulato, da una parte, tra [ŞİRKET ÜNVANI] (“TercümExpert”) e, dall'altra parte, il partner che aderisce al programma (“Partner”), allo scopo di disciplinare i termini e le condizioni del programma di partnership (segnalazione) di TercümExpert.` },
        { heading: `Ambito del Programma`, body: `Il Partner segnala clienti a TercümExpert attraverso la propria rete e i propri canali. Qualora il cliente segnalato acquisti un servizio tramite TercümExpert, il Partner matura il diritto alla commissione indicata nel presente Contratto.` },
        { heading: `Commissione`, body: `Per ogni segnalazione valida e approvata, il Partner matura il diritto a una commissione pari al %20 del corrispettivo del servizio pagato dal cliente segnalato. L'aliquota e le condizioni della commissione possono essere aggiornate da TercümExpert previa comunicazione. Le operazioni annullate, rimborsate o il cui pagamento non sia stato completato non sono considerate ai fini della commissione.` },
        { heading: `Tracciamento e Maturazione`, body: `Le segnalazioni sono associate mediante il link di tracciamento fornito al Partner, il codice QR o il metodo stabilito da TercümExpert. Il diritto alla commissione sorge esclusivamente per le operazioni correttamente associate tramite tali metodi e il cui pagamento sia stato completato.` },
        { heading: `Pagamento`, body: `Le commissioni maturate sono corrisposte sul conto indicato dal Partner. Il periodo e le condizioni di pagamento sono stabiliti separatamente tra le parti. Gli obblighi fiscali relativi al pagamento sono soggetti alla normativa vigente.` },
        { heading: `Obblighi del Partner`, body: `Il Partner si impegna a utilizzare, nelle proprie attività promozionali, informazioni corrette e non ingannevoli, ad astenersi da comportamenti lesivi del marchio e della reputazione di TercümExpert e a rispettare la normativa vigente.` },
        { heading: `Comportamenti Vietati`, body: `Sono vietati l'invio di spam e di comunicazioni massive indesiderate, la pubblicità ingannevole, nonché i comportamenti che integrano concorrenza sleale mediante segnalazioni false o autosegnalazioni. Tali comportamenti costituiscono motivo di annullamento della commissione e di risoluzione del Contratto.` },
        { heading: `Utilizzo del Marchio`, body: `Il Partner può utilizzare il marchio, il logo e i materiali promozionali di TercümExpert esclusivamente previo consenso scritto di TercümExpert e nel rispetto delle regole da quest'ultima fornite.` },
        { heading: `Riservatezza`, body: `Le parti si impegnano a proteggere le informazioni riservate acquisite nell'ambito del presente Contratto e a utilizzarle esclusivamente per le finalità del programma.` },
        { heading: `Parte Indipendente`, body: `Il Partner è una parte indipendente; non è un dipendente, un rappresentante o un agente di TercümExpert e non può assumere impegni nei confronti di terzi in nome di TercümExpert.` },
        { heading: `Durata e Risoluzione`, body: `Il Contratto rimane in vigore fino a quando una delle parti non ne comunichi la risoluzione. TercümExpert può risolvere immediatamente il Contratto in caso di inadempimento degli obblighi; in tal caso non sono corrisposte le commissioni derivanti da segnalazioni irregolari.` },
        { heading: `Controversie e Legge Applicabile`, body: `Il presente Contratto è soggetto al diritto della Türkiye Cumhuriyeti. Il Partner, confermando la propria adesione, dichiara di aver letto e accettato i termini del Contratto.` },
      ],
    },
  },

  admin: {
    attachmentImage: 'Immagine',
    attachmentFile: 'Documento',
    title: `Registri delle conversazioni`,
    summary: `{total} conversazioni · {leads} richieste di contatto`,
    onlyLeads: `Solo richieste di contatto`,
    loading: `Caricamento dei registri…`,
    error: `Impossibile leggere i registri. Verifichi che la tabella Supabase e le relative autorizzazioni (RLS) siano configurate.`,
    empty: `Nessun registro presente al momento.`,
    selectHint: `Selezioni una conversazione dalla colonna a sinistra per visualizzarla.`,
    contactRequest: `Richiesta di contatto`,
    contactInfo: `Informazioni di contatto`,
    fieldName: `Nome`,
    fieldEmail: `E-mail`,
    fieldPhone: `Telefono`,
    fieldMessage: `Messaggio`,
    requestBadge: `richiesta`,
    noMessages: `Nessun messaggio in questo registro (solo richiesta di contatto).`,
    loginTitle: `Accesso richiesto`,
    loginDesc: `Per visualizzare questa pagina, effettui l'accesso con un account amministratore.`,
    login: `Accedi`,
    noAccessTitle: `Non dispone dei permessi di accesso`,
    noAccessDesc: `Questa pagina è riservata esclusivamente agli amministratori.`,
    loadingAuth: `Caricamento…`,
  },
  footer: {
    tagline: "Il suo partner affidabile nei servizi di traduzione professionale.",
    columns: {
      quickLinks: "Link rapidi",
      services: "Servizi",
      contact: "Contatti",
    },
    quickLinks: {
      corporate: "Aziende",
      services: "I nostri servizi",
      quote: "Calcola il prezzo",
      blog: "Blog",
      faq: "Domande frequenti",
      contact: "Contatti",
    },
    serviceLinks: {
      sworn: "Traduzione giurata",
      notarized: "Traduzione con autenticazione notarile",
      apostille: "Procedura di apostille",
      corporate: "Soluzioni per aziende",
      partnership: "Programma di partnership",
    },
    legal: {
      kvkk: "KVKK",
      privacy: "Informativa sulla privacy",
      distanceSales: "Contratto di vendita a distanza",
      cookies: "Informativa sui cookie",
    },
    socialTitle: "Ci segua",
    whatsapp: "Assistenza WhatsApp",
    rights: "Tutti i diritti riservati.",
  },

  cookie: {
    title: "Preferenze sui cookie",
    desc: "Utilizziamo i cookie per migliorare la sua esperienza. I cookie diversi da quelli necessari vengono eseguiti solo con il suo consenso.",
    accept: "Accetta",
    reject: "Rifiuta",
    manage: "Gestisci le preferenze",
    save: "Salva le preferenze",
    categories: {
      necessary: { label: "Necessari", desc: "Indispensabili al funzionamento del sito; non possono essere disattivati." },
      analytics: { label: "Analitici", desc: "Ci aiutano a comprendere l'utilizzo." },
      marketing: { label: "Marketing", desc: "Per contenuti e annunci pertinenti." },
      preferences: { label: "Preferenze", desc: "Memorizza le sue preferenze." },
    },
  },

  chatbot: {
    attach: {
      button: 'Allega file',
      tooLarge: 'Il file è troppo grande (max 25 MB).',
      unsupported: 'Non posso analizzare file audio o video nella chat. Puoi caricarli nella pagina del preventivo.',
      cannotRead: 'Non sono riuscito a leggere questo file. Puoi caricarlo nella pagina del preventivo o provare un altro formato.',
      reading: 'Lettura del file…',
      remove: 'Rimuovi',
    },
    nudge: 'Come posso aiutarla?',
    title: "Assistenza TercümExpert",
    open: "Apri la chat",
    close: "Chiudi la chat",
    minimize: "Riduci a icona",
    clear: "Cancella la conversazione",
    inputPlaceholder: "Digiti il suo messaggio…",
    send: "Invia",
    typing: "Sta scrivendo…",
    welcome:
      "Salve e benvenuto in TercümExpert. Posso aiutarla con traduzione, prezzi, autenticazione notarile, apostille o servizi per aziende.",
    quickQuestions: [
      "Come viene calcolato il prezzo?",
      "Che cos'è la traduzione giurata?",
      "Voglio caricare un documento",
      "Vorrei un preventivo aziendale",
      "È necessaria l'autenticazione notarile?",
      "Mettimi in contatto con un operatore",
    ],
    handoff: "Contatta un operatore",
    toWhatsapp: "Trasferisci su WhatsApp",
    disclaimer: "Queste informazioni sono di carattere generale; confermi i requisiti esatti presso l'istituzione competente.",
    sensitiveWarning:
      "La preghiamo di non condividere dati personali sensibili tramite questa chat. Può inviare i suoi documenti attraverso l'area di caricamento sicura.",
    answers: [
      `Il prezzo viene calcolato in base al numero di parole del Suo documento, alla combinazione linguistica, al tipo di servizio (traduzione giurata, asseverata o con apostille) e ai tempi di consegna. Per ottenere subito un preventivo indicativo, può caricare il Suo documento o inserire i dati necessari nella pagina Calcola Prezzo.`,
      `La traduzione giurata è una traduzione ufficiale eseguita da un traduttore giurato e certificata con la sua firma e il suo timbro. Gli enti ufficiali richiedono nella maggior parte dei casi una traduzione giurata; se necessario, è possibile aggiungere anche l'asseverazione notarile.`,
      `Può inviarci il Suo documento tramite l'area di caricamento sicura disponibile nella pagina Calcola Prezzo. Al termine del caricamento vedrà immediatamente il preventivo indicativo e potrà completare il Suo ordine.`,
      `Per le Sue esigenze aziendali offriamo tariffe dedicate e consegna prioritaria in caso di traduzioni regolari e di grande volume. Per maggiori dettagli può consultare la nostra pagina Aziende oppure contattarci direttamente.`,
      `La necessità dell'asseverazione notarile dipende dall'ente a cui presenterà il documento e dal tipo di pratica. Alcune procedure accettano soltanto la traduzione giurata, mentre altre richiedono anche l'asseverazione notarile. Se ha dei dubbi, saremo lieti di aiutarLa.`,
      `La mettiamo subito in contatto con un nostro operatore. Può scriverci tramite WhatsApp utilizzando il pulsante qui sotto.`,
    ],
    fallback: `Per la Sua domanda, un nostro operatore potrà offrirLe l'assistenza più adeguata. Può scriverci tramite WhatsApp utilizzando il pulsante qui sotto; il Suo messaggio verrà inoltrato già pronto.`,
    contact: {
      whatsapp: `WhatsApp`,
      email: `Email`,
      phone: `Telefono`,
      leaveInfo: `Lascia i miei dati di contatto`,
      formTitle: `Lasci che La contattiamo`,
      formDesc: `Lasci i Suoi dati, il nostro team La contatterà al più presto.`,
      name: `Il Suo nome`,
      emailField: `Email`,
      phoneField: `Telefono`,
      message: `Il Suo messaggio (facoltativo)`,
      submit: `Invia`,
      submitting: `Invio in corso…`,
      thanks: `Grazie, il nostro team La contatterà al più presto.`,
      errorRequired: `Inserisca un'email o un numero di telefono.`,
      back: `Indietro`,
    },
  },

  translator: {
    "seo": {
      "title": "Pannello Traduttore — TercümExpert",
      "description": "Candidatura traduttore e pannello di lavoro."
    },
    "loading": "Caricamento in corso…",
    "loginTitle": "Accesso richiesto",
    "loginDesc": "Questa area è riservata esclusivamente ai traduttori e agli amministratori. La preghiamo di accedere per continuare.",
    "login": "Accedi",
    "setupTitle": "Pannello non ancora pronto",
    "setupDesc": "L'infrastruttura per i traduttori (database) non è ancora stata configurata. Il pannello si attiverà una volta completata la configurazione.",
    "applyTitle": "Candidatura Traduttore",
    "applyDesc": "Compili i Suoi dati per entrare a far parte della nostra rete di traduttori freelance. La Sua candidatura viene attivata dopo l'approvazione dell'amministratore.",
    "applyNote": "Le Sue informazioni vengono utilizzate esclusivamente per la valutazione e il pagamento.",
    "form": {
      "fullName": "Nome e cognome",
      "birthDate": "Data di nascita",
      "phone": "Telefono",
      "country": "Paese",
      "city": "Città / Provincia",
      "selectCountry": "Selezioni il Paese",
      "selectCity": "Selezioni la città / provincia",
      "cityNeedsCountry": "Selezioni prima un Paese",
      "address": "Indirizzo completo",
      "isSworn": "È un traduttore giurato (certificato)?",
      "isSwornHint": "Selezioni questa opzione se dispone di un verbale di giuramento notarile. Avrà la priorità per gli incarichi che richiedono traduzioni giurate.",
      "iban": "IBAN",
      "ibanName": "Intestatario dell'IBAN (nome e cognome)",
      "languagePairs": "Combinazioni linguistiche",
      "source": "Lingua di partenza",
      "target": "Lingua di arrivo",
      "addPair": "Aggiungi",
      "removePair": "Rimuovi",
      "swap": "Inverti direzione",
      "expertise": "Ambiti di specializzazione",
      "submit": "Invia candidatura",
      "submitting": "Invio in corso…",
      "saved": "I Suoi dati sono stati salvati.",
      "saveError": "Impossibile salvare. La preghiamo di riprovare.",
      "required": "La preghiamo di compilare i campi obbligatori.",
      "atLeastOnePair": "Aggiunga almeno una combinazione linguistica."
    },
    "expertiseLabels": {
      "legal": "Legale",
      "medical": "Medico",
      "technical": "Tecnico",
      "academic": "Accademico",
      "commercial": "Commerciale",
      "financial": "Finanziario",
      "literary": "Letterario",
      "official": "Documenti ufficiali",
      "localization": "Web / Software",
      "general": "Generale"
    },
    "pendingTitle": "La Sua candidatura è in fase di revisione",
    "pendingDesc": "Abbiamo ricevuto la Sua candidatura come traduttore. L'accesso al pannello verrà attivato dopo la revisione da parte dell'amministratore.",
    "rejectedTitle": "Candidatura non approvata",
    "rejectedDesc": "La Sua candidatura non è stata approvata in questo momento. Può aggiornare i Suoi dati e riprovare.",
    "reapply": "Riprova",
    "cancelApplication": "Annulla candidatura",
    "cancelConfirm": "È sicuro di voler annullare la Sua candidatura? Il Suo record verrà eliminato; potrà candidarsi nuovamente in seguito, se lo desidera.",
    "panelTitle": "Pannello Traduttore",
    "tabs": {
      "profile": "Il Mio Profilo",
      "pool": "Bacino Traduzioni",
      "active": "Incarichi Attivi",
      "pending": "In Attesa di Approvazione",
      "approved": "Approvati",
      "completed": "Completati",
      "wallet": "Portafoglio"
    },
    "soon": "Questa sezione sarà disponibile nel prossimo passaggio.",
    "jobs": {
      "empty": "Al momento non ci sono incarichi in questa sezione.",
      "translator": "Traduttore",
      "sourceFiles": "Documenti di partenza",
      "translationFiles": "Traduzione caricata",
      "tracking": "Tracciamento",
      "rejectionReason": "Motivo del rifiuto",
      "chooseFiles": "Scelga i file della traduzione",
      "filesSelected": "file selezionati",
      "uploadHint": "Carichi la Sua traduzione e, se necessario, una copia digitale del documento di partenza, quindi la invii per l'approvazione.",
      "submit": "Invia per l'approvazione",
      "sending": "Invio in corso…",
      "needFiles": "La preghiamo di selezionare almeno un file.",
      "uploadError": "Impossibile caricare i file. La preghiamo di riprovare.",
      "submittedMsg": "Traduzione inviata per l'approvazione.",
      "actionError": "Impossibile completare l'operazione. La preghiamo di riprovare.",
      "waitingApproval": "La Sua traduzione è in attesa di approvazione da parte della direzione. Una volta approvata, la fase di consegna comparirà sotto “Approvati”.",
      "trackingPlaceholder": "Numero di tracciamento / link",
      "needTracking": "Per la consegna tramite corriere è richiesto un numero di tracciamento.",
      "markShipped": "Spedito — completa",
      "markDelivered": "Consegnato — completa",
      "completedMsg": "Incarico completato. Il Suo compenso è stato aggiunto al Suo portafoglio.",
      "reasonPlaceholder": "In caso di rifiuto, scriva il motivo (visibile al traduttore)…",
      "approve": "Approva",
      "reject": "Rifiuta",
      "needReason": "Scriva un motivo per rifiutare.",
      "approvedMsg": "Traduzione approvata.",
      "rejectedMsg": "Traduzione rifiutata; restituita al traduttore.",
      "statusLabel": "Stato",
      "status_claimed": "In corso",
      "status_submitted": "In attesa di approvazione",
      "status_approved": "Approvata — fase di consegna",
      "status_completed": "Completata"
    },
    "pool": {
      "loading": "Caricamento del bacino…",
      "empty": "Al momento non ci sono ordini in attesa corrispondenti alle Sue combinazioni linguistiche e ai Suoi ambiti di specializzazione.",
      "error": "Impossibile caricare il bacino. La preghiamo di riprovare.",
      "orderNo": "Ordine",
      "service": "Tipo di servizio",
      "documentType": "Tipo di documento",
      "langPair": "Combinazione linguistica",
      "words": "Parole",
      "pagesUnit": "pagine",
      "deadline": "Scadenza",
      "daysUnit": "giorni lavorativi",
      "note": "Nota del cliente",
      "customerInfo": "Dati del cliente",
      "deliveryInfo": "Dati del cliente e della consegna",
      "customerName": "Nome e cognome",
      "customerEmail": "Email",
      "customerPhone": "Telefono",
      "deliveryAddress": "Indirizzo di consegna",
      "text": "Testo dell'ordine",
      "files": "Documenti",
      "earning": "Il Suo compenso per questo incarico",
      "urgent": "Urgente",
      "sworn": "Giurata",
      "notary": "Notarile",
      "apostille": "Apostille",
      "cargo": "Consegna tramite corriere",
      "digital": "Consegna digitale",
      "claim": "Accetta questo incarico",
      "claiming": "Accettazione in corso…",
      "claimed": "Ha accettato l'incarico con successo.",
      "claimError": "Impossibile accettare l'incarico. Potrebbe essere stato accettato da qualcun altro; aggiorni l'elenco.",
      "ibanRequired": "Prima di poter accettare incarichi, i Suoi dati IBAN devono essere verificati dalla direzione. Inserisca il Suo IBAN nel Suo profilo; una volta verificato potrà accettare incarichi dal bacino."
    },
    "profile": {
      "statusApproved": "Traduttore approvato",
      "verifiedIban": "IBAN verificato",
      "unverifiedIban": "IBAN non verificato",
      "current": "Salvato",
      "edit": "Salva dati",
      "ibanReminder": "Per ricevere i Suoi pagamenti, La preghiamo di inserire e salvare i Suoi dati IBAN. Una volta verificati dall'amministratore, i pagamenti verranno effettuati su questo conto.",
      "lockedHint": "Non modificabile dopo l'approvazione",
      "revokeTitle": "Questa modifica revocherà la Sua approvazione",
      "revokeWarning": "Se modifica le Sue combinazioni linguistiche, lo stato di traduttore giurato o gli ambiti di specializzazione, il Suo account tornerà in revisione presso la direzione (impostato su in attesa). I Suoi incarichi, record e portafoglio vengono CONSERVATI; una volta riapprovato potrà riprendere da dove aveva interrotto.",
      "consent": "Ho letto e accetto",
      "ibanReverify": "Sta modificando il Suo IBAN. Il nuovo IBAN torna in revisione presso la direzione; il Suo account resta attivo, ma non potrà accettare nuovi incarichi dal bacino finché l'IBAN non sarà verificato."
    },
    "admin": {
      "title": "Pannello di Direzione",
      "translatorsTab": "Traduttori",
      "applicationsTab": "Candidature",
      "ibanTab": "Approvazioni IBAN",
      "ordersTab": "Ordini",
      "paymentsTab": "Pagamenti",
      "noIbanPending": "Nessun traduttore in attesa di approvazione IBAN.",
      "ibanHint": "Approvi qui gli IBAN appena inseriti o modificati. Fino all'approvazione, il traduttore non può accettare nuovi incarichi dal bacino.",
      "ibanApprove": "Approva IBAN",
      "paymentsHint": "Il giorno del pagamento (il 1° e il 16 di ogni mese): per ogni traduttore che ha pagato, carichi la ricevuta e clicchi su “Segna come pagato”. Il pulsante non funzionerà senza una ricevuta. I traduttori con saldo pari a zero non compaiono in questo elenco.",
      "noPayments": "Nessun traduttore con un saldo da pagare.",
      "paymentAmount": "Importo da pagare",
      "uploadReceipt": "Carica ricevuta",
      "receiptUploaded": "Ricevuta caricata",
      "receiptRequired": "Carichi prima una ricevuta",
      "uploading": "Caricamento in corso…",
      "markPaid": "Segna come pagato",
      "paid": "Pagamento registrato e traduttore notificato con la ricevuta.",
      "panelHint": "Monitori i traduttori approvati per profilo, esamini le candidature e gestisca il flusso di lavoro di tutti gli ordini.",
      "summary": "{total} traduttori · {pending} candidature in attesa",
      "applicationsSummary": "{total} candidature · {pending} in attesa di revisione",
      "noApproved": "Ancora nessun traduttore approvato.",
      "noPending": "Nessuna candidatura in attesa.",
      "noMatch": "Nessun record corrisponde ai filtri.",
      "loadError": "Impossibile caricare i record. Verifichi il database e i permessi (RLS).",
      "noApplications": "Ancora nessun record di traduttore.",
      "filters": {
        "namePlaceholder": "Cerca per nome…",
        "country": "Paese",
        "city": "Città / Provincia",
        "anyCountry": "Tutti i Paesi",
        "anyCity": "Tutte le città",
        "cityNeedsCountry": "Selezioni prima un Paese",
        "sourceLang": "Lingua di partenza",
        "targetLang": "Lingua di arrivo",
        "anyLang": "Qualsiasi",
        "eitherDirection": "Entrambe le direzioni (partenza↔arrivo)",
        "expertise": "Ambiti di specializzazione",
        "clear": "Cancella filtri",
        "results": "{n} record"
      },
      "orders": {
        "loadError": "Impossibile caricare gli ordini. La preghiamo di riprovare.",
        "empty": "Ancora nessun ordine.",
        "searchPlaceholder": "Cerca per numero d'ordine o nome del cliente…",
        "results": "{n} ordini",
        "customer": "Cliente",
        "translator": "Traduttore",
        "unassigned": "Non assegnato",
        "status": "Stato",
        "done": "Completato",
        "inProgress": "In corso",
        "completedOn": "Completato il",
        "placedOn": "Data dell'ordine",
        "total": "Totale",
        "statusAvailable": "Nel bacino (non accettato)",
        "statusClaimed": "In traduzione",
        "statusSubmitted": "In attesa di approvazione",
        "statusApproved": "Fase di consegna",
        "statusCompleted": "Completato",
        "statusCancelled": "Annullato"
      },
      "profile": {
        "back": "Torna ai traduttori",
        "adminOnly": "Questo profilo è riservato alla direzione; il traduttore non può visualizzarlo.",
        "infoTitle": "Dettagli",
        "walletTitle": "Portafoglio",
        "jobsTitle": "Incarichi",
        "noJobs": "Questo traduttore non ha ancora incarichi."
      },
      "approve": "Approva",
      "reject": "Rifiuta",
      "colLangs": "Combinazioni linguistiche",
      "colExpertise": "Specializzazione",
      "colLocation": "Città / Paese",
      "swornBadge": "Giurato",
      "returningBadge": "Traduttore di ritorno",
      "ibanVerified": "IBAN verificato",
      "ibanNotVerified": "IBAN non verificato",
      "verifyIban": "Verifica IBAN",
      "unverifyIban": "Annulla verifica",
      "statusPending": "In attesa",
      "statusApproved": "Approvato",
      "statusRejected": "Rifiutato",
      "actionError": "Impossibile completare l'operazione."
    },
    "wallet": {
      "total": "Guadagni totali",
      "locked": "Bloccato",
      "withdrawable": "Prelevabile",
      "paid": "Liquidato",
      "payInfo": "I compensi vengono aggiunti al Suo portafoglio al completamento di un incarico; restano bloccati per 7 giorni, dopodiché diventano prelevabili. I pagamenti vengono effettuati sul saldo prelevabile il 1° e il 16 di ogni mese.",
      "empty": "Ancora nessun guadagno. I compensi degli incarichi completati compariranno qui.",
      "entryOrder": "Ordine",
      "date": "Data",
      "statusCol": "Stato",
      "amount": "Importo",
      "statusPaid": "Pagato",
      "statusUnlocked": "Prelevabile",
      "statusPending": "Bloccato",
      "loadError": "Impossibile caricare il portafoglio. La preghiamo di riprovare."
    },
    "adminWallet": {
      "firmShare": "Quota aziendale (IVA inclusa)",
      "firmShareHint": "Quota aziendale = totale degli ordini completati (IVA inclusa) meno i compensi dei traduttori.",
      "ciro": "Fatturato totale (IVA inclusa)",
      "kdv": "IVA (allo Stato)",
      "payouts": "Pagato ai traduttori",
      "net": "Netto aziendale",
      "count": "{n} ordini completati",
      "empty": "Ancora nessun ordine completato.",
      "colOrder": "Ordine",
      "colTranslator": "Traduttore",
      "colDate": "Data",
      "colTotal": "Totale (IVA inclusa)",
      "colPayout": "Traduttore",
      "colFirm": "Quota aziendale",
      "loadError": "Impossibile caricare il portafoglio. La preghiamo di riprovare."
    }
  },
  authx: {
    "rememberMe": "Ricordami",
    "showPassword": "Mostra password",
    "hidePassword": "Nascondi password",
    "forgot": "Ho dimenticato la password",
    "forgotTitle": "Reimposta password",
    "forgotDesc": "Inserisca l'indirizzo email con cui si è registrato e le invieremo un link monouso per reimpostare la password.",
    "forgotEmail": "Email",
    "forgotSubmit": "Invia link di reimpostazione",
    "forgotSent": "Il link è stato inviato alla sua email. Controlli la sua casella di posta (e la cartella spam).",
    "forgotBack": "Torna all'accesso",
    "resetTitle": "Imposta una nuova password",
    "resetDesc": "Inserisca la sua nuova password e la confermi digitandola di nuovo.",
    "newPassword": "Nuova password",
    "newPasswordRepeat": "Nuova password (ripeti)",
    "mismatch": "Le password non corrispondono.",
    "weak": "La password deve contenere almeno 6 caratteri.",
    "resetSubmit": "Aggiorna password",
    "resetSuccess": "La sua password è stata aggiornata. Ora può accedere con la sua nuova password.",
    "resetInvalid": "Il link non è valido o è scaduto. La preghiamo di richiedere un nuovo link di reimpostazione.",
    "goLogin": "Accedi"
  },
  notFound: {
    seo: { title: "Pagina non trovata", description: "La pagina che sta cercando non è stata trovata." },
    title: "Pagina non trovata",
    desc: "La pagina che sta cercando potrebbe essere stata spostata o non essere mai esistita.",
    home: "Torna alla home",
  },
}
