import type { PartialDictionary } from '@/types/i18n'
import { FAQ_CATEGORIES_NL, FAQ_ITEMS_NL } from '@/content/faq-data.nl'

/**
 * NEDERLANDS — volledige vertaling, identieke structuur als en/index.ts.
 * Alleen de tekstwaarden zijn vertaald; sleutels, iconen en technische
 * tokens blijven ongewijzigd. Ontbrekende sleutels vallen terug op het
 * Engels (§10). De FAQ-gegevens komen uit content/faq-data.nl.
 */
export const nl: PartialDictionary = {
  delivery: {
    "ready": "Uw vertaling is klaar",
    "download": "Vertaling downloaden",
    "hint": "Uw vertaling is ook naar uw e-mailadres verzonden. Controleer uw inbox (en uw spammap)."
  },

  partnerPanel: {
    qrDownload: "QR-code downloaden",
    qrAlt: "Uitnodigings-QR-code",
    colMembers: "Leden",
    sectorAll: "Alle sectoren",
    back: "Terug",
    noPartners: "Nog geen partners.",
    tabPayments: "Betalingen",
    payHint: "Betalingen worden gedaan op de 2e en 17e van elke maand. Upload op de betaaldag het betalingsbewijs van elke partner en druk op “Betaald”; de knop werkt pas nadat een bewijs is geüpload. Alleen opneembare saldi (na de wachttijd van 7 dagen) worden weergegeven; partners met een saldo van 0 verschijnen niet.",
    noPayments: "Geen partners die op betaling wachten.",
    paid: "Betaling geregistreerd en partner op de hoogte gebracht.",
    noApplications: "Geen openstaande aanvragen.",
    approve: "Goedkeuren",
    reject: "Afwijzen",
    noIban: "Geen IBAN’s die op goedkeuring wachten.",
    approveIban: "IBAN goedkeuren",
    adminTitle: "Partnerbeheer",
    tabApplications: "Aanvragen",
    tabIban: "IBAN-goedkeuringen",
    tabPartners: "Partners",
    colPartner: "Partner",
    colCompany: "Bedrijf",
    partnerShareLabel: "Partneraandeel",
    adminNet: "Resterend (bedrijf)",
    fltPartner: "Partnernaam",
    fltCompany: "Bedrijf",
    yourEarning: "Uw commissie",
    tabAllOrders: "Alle bestellingen",
    fltOrderNo: "Bestelnr.",
    fltDateFrom: "Van",
    fltDateTo: "Tot",
    custFilter: "Zoeken op naam",
    custEmpty: "U heeft nog geen leden aangebracht. Deel uw uitnodigingslink.",
    colName: "Naam",
    colEmail: "E-mail",
    colPhone: "Telefoon",
    colJoined: "Aangemeld",
    custOrderCount: "Bestellingen",
    custTotal: "Totaalbedrag",
    ordEmpty: "Geen bestellingen in deze fase.",
    colOrderNo: "Bestelling",
    colCustomer: "Klant",
    colService: "Dienst",
    colLangs: "Talen",
    colAmount: "Bedrag",
    colDate: "Datum",
    loadError: "Laden mislukt. Probeer het opnieuw.",
    walPayInfo: "Uw verdiensten worden aan uw portemonnee toegevoegd zodra de opdracht is voltooid; ze blijven 7 dagen geblokkeerd en worden daarna opneembaar. Betalingen op het opneembare saldo worden op de 2e en 17e van elke maand gedaan.",
    ibanPending: "Uw IBAN-gegevens wachten op goedkeuring door de beheerder.",
    ibanPolicy: "Zolang uw IBAN en de rekeninghouder niet door ons team zijn goedgekeurd, kunt u geen betalingen ontvangen. Uw verdiensten blijven in deze periode in uw portemonnee oplopen. Zodra uw gegevens zijn goedgekeurd, kunt u saldi opnemen waarvan de wachttijd van 7 dagen na de verkoop is verstreken en die niet langer geblokkeerd zijn.",
    fillRequired: "Vul de verplichte velden in.",
    phoneLockNote: "Uw telefoonnummer kan worden gewijzigd zodra SMS-verificatie is ingeschakeld.",
    panelTitle: "Partnerpaneel",
    tabProfile: "Mijn profiel",
    tabCustomers: "Mijn klanten",
    tabOrdersNew: "Binnengekomen bestellingen",
    tabOrdersActive: "In behandeling",
    tabOrdersDelivery: "Wacht op levering",
    tabOrdersDone: "Voltooid",
    tabWallet: "Portemonnee",
    soon: "Zeer binnenkort.",
    save: "Opslaan",
    saved: "Opgeslagen.",
    statusApproved: "Goedgekeurde partner",
    ibanVerified: "IBAN geverifieerd",
    ibanNotVerified: "IBAN niet geverifieerd",
    ibanReminder: "Voer uw IBAN en de rekeninghouder in zodat u betalingen kunt ontvangen.",
    refCodeLabel: "Uw uitnodigingscode",
    seoTitle: "Partnerpaneel",
    seoDesc: "Dien uw partneraanvraag in en ontvang hier uw uitnodigingslink.",
    loading: "Laden…",
    loginTitle: "Partner-aanmelding",
    loginDesc: "Meld u aan of maak een account om u aan te melden of uw paneel te openen.",
    login: "Aanmelden / Registreren",
    setupTitle: "Installatie niet voltooid",
    setupDesc: "Het partnersysteem is nog niet gereed.",
    applyTitle: "Partneraanvraag",
    applyDesc: "Vul uw gegevens in; uw uitnodigingslink wordt geactiveerd zodra uw aanvraag is goedgekeurd.",
    applyNote: "Uw aanvraag wordt binnenkort beoordeeld.",
    sectorOther: "Voer uw sector in",
    submit: "Aanvraag versturen",
    submitting: "Versturen…",
    saveError: "Uw aanvraag kon niet worden opgeslagen. Probeer het opnieuw.",
    pendingTitle: "Aanvraag ontvangen",
    pendingDesc: "Uw aanvraag wordt beoordeeld. Na goedkeuring worden uw uitnodigingslink en paneel hier geactiveerd.",
    cancelApplication: "Aanvraag annuleren",
    rejectedTitle: "Aanvraag niet goedgekeurd",
    rejectedDesc: "Deze aanvraag is niet goedgekeurd. U kunt uw gegevens bijwerken en opnieuw aanvragen.",
    reapply: "Opnieuw aanvragen",
    approvedTitle: "Uw partneraccount is actief",
    approvedDesc: "Klanten die zich via uw onderstaande uitnodigingslink registreren, worden permanent aan uw account gekoppeld.",
    panelSoon: "Een gedetailleerd paneel met uw klanten, bestellingen en portemonnee komt hier zeer binnenkort.",
    verifyTitle: "E-mailverificatie",
    verifyDesc: "Verifieer uw e-mailadres zodat u betalingen kunt ontvangen. We sturen u een verificatiecode.",
    verifiedLabel: "E-mail geverifieerd",
    sendCode: "Verificatiecode versturen",
    sending: "Versturen…",
    codeSent: "We hebben de code naar uw e-mailadres gestuurd. Controleer uw inbox en spam-map.",
    codePlaceholder: "6-cijferige code",
    verifyBtn: "Verifiëren",
    verifying: "Verifiëren…",
    verifyError: "De code is ongeldig of verlopen. Vraag een nieuwe aan.",
    refTitle: "Uw uitnodigingslink",
    refDesc: "Deel deze link; klanten die via deze link binnenkomen en zich registreren, worden permanent aan u gekoppeld.",
    refCopy: "Link kopiëren",
    refCopied: "Gekopieerd",
  },
  adminHub: {
    "tabChats": "Gesprekken",
    "tabCustomers": "Klanten",
    "tabUploads": "Geüploade bestanden",
    "loading": "Laden…",
    "loadError": "Laden mislukt. Probeer het opnieuw.",
    "back": "Terug",
    "custHint": "Alle in het systeem geregistreerde klanten (vertalers uitgezonderd).",
    "custSearch": "Zoek op naam, e-mail of telefoon…",
    "custName": "Volledige naam",
    "custEmail": "E-mail",
    "custPhone": "Telefoon",
    "custOrders": "Bestellingen",
    "custTotal": "Totaalbedrag",
    "custJoined": "Aangemeld",
    "custNone": "Nog geen klantgegevens.",
    "custOrderList": "Bestellingen",
    "custNoOrders": "Deze klant heeft geen bestellingen.",
    "orderNo": "Bestelnr.",
    "orderDate": "Datum",
    "orderStatus": "Status",
    "upHint": "Alle bestanden die op de offertepagina zijn geüpload (ook opgeslagen zonder bestelling).",
    "upFile": "Bestand",
    "upUploader": "Geüpload door",
    "upWhen": "Datum",
    "upWords": "Woorden",
    "upSize": "Grootte",
    "upDownload": "Downloaden",
    "upNone": "Nog geen geüploade bestanden.",
    "upGuest": "Gast"
  },

  smsVerify: {
    "sendCode": "Code verzenden",
    "resend": "Code opnieuw verzenden",
    "codeLabel": "Sms-code",
    "confirm": "Bevestigen",
    "verified": "Telefoon geverifieerd",
    "sent": "Er is een code naar uw telefoon verzonden.",
    "mustVerify": "Verifieer uw telefoonnummer via sms om verder te gaan.",
    "reverifyHint": "Als u uw telefoonnummer wijzigt, moet u het nieuwe nummer opnieuw verifiëren via sms.",
    "invalid": "Onjuiste code. Probeer het opnieuw.",
    "expired": "De code is verlopen. Vraag een nieuwe aan.",
    "rateLimited": "Te veel pogingen. Wacht een moment en probeer het opnieuw.",
    "notConfigured": "Sms-verificatie is momenteel niet beschikbaar. Probeer het later opnieuw of neem contact op met de klantenservice.",
    "sendFailed": "De code kon niet worden verzonden. Controleer uw nummer en probeer het opnieuw.",
    "enterPhone": "Voer eerst een geldig telefoonnummer in.",
    "error": "Er is iets misgegaan. Probeer het opnieuw.",
    "devCode": "Testmodus — uw verificatiecode: {code}"
  },
  common: {
      "brand": "TercümExpert",
    tagline: "Uw betrouwbare partner voor professionele vertaaldiensten.",
    nav: {
      home: "Home",
      services: "Diensten",
      quote: "Offerte aanvragen",
      corporate: "Zakelijk",
      partnership: "Partnerschap",
      blog: "Blog",
      faq: "Veelgestelde vragen",
      contact: "Contact",
    },
    actions: {
      getQuote: "Offerte aanvragen",
      calculatePrice: "Prijs berekenen",
      uploadDocument: "Document uploaden",
      whatsapp: "Chat via WhatsApp",
      learnMore: "Meer informatie",
      viewAll: "Alles bekijken",
      showMore: "Meer tonen",
      showLess: "Minder tonen",
      send: "Verzenden",
      apply: "Aanmelden",
      order: "Bestelling plaatsen",
      contactUs: "Neem contact op",
      openMenu: "Menu openen",
      closeMenu: "Menu sluiten",
      selectLanguage: "Taal selecteren",
      skipToContent: "Naar de inhoud",
      login: "Inloggen",
      logout: "Uitloggen",
      account: "Mijn account",
    },
    states: {
      loading: "Laden…",
      error: "Er is iets misgegaan. Probeer het opnieuw.",
      required: "Dit veld is verplicht.",
      demoNotice: "Demo: formuliergegevens worden nog niet naar een server verzonden.",
      unverified: "Nog te verifiëren",
    },
    topbar: {
      phoneLabel: "Telefoon",
      emailLabel: "E-mail",
      hoursLabel: "Openingstijden",
      afterHours: "Buiten kantooruren is spoedvertaalondersteuning beschikbaar.",
      workingHours: "Werkdagen 09:00 - 18:00 | Service buiten kantooruren beschikbaar",
    },
  },

  home: {
    seo: {
      title: "TercümExpert — Professionele vertaaldiensten",
      description:
        "Beëdigde vertaling, notariële bekrachtiging en zakelijke vertaaloplossingen. Upload uw document, ontvang direct een voorlopige offerte en professionele levering.",
    },
    hero: {
      title: "Uw betrouwbare partner voor professionele",
      titleAccent: "vertaaldiensten",
      subtitle: "Upload uw document, bekijk de prijs en ontvang professionele levering.",
      support: "Beëdigde vertaling • Notariële bekrachtiging • Zakelijke oplossingen",
    },
    trust: {
      title: "Waarom vertrouwen zij ons?",
      items: [
        { key: 'languages', label: "50+ talen" },
        { key: 'delivery', label: "Levering binnen 24 uur" },
        { key: 'notary', label: "Notariële bekrachtiging" },
        { key: 'quality', label: "Kwaliteitsgarantie" },
      ],
    },
    stats: {
      title: "TercümExpert in cijfers",
      note: "De onderstaande cijfers worden niet als definitieve claims gepresenteerd zolang ze niet zijn geverifieerd.",
      labels: {
        satisfaction: "Klanttevredenheid",
        completed: "Voltooide opdrachten",
        languages: "Talenondersteuning",
        corporate: "Zakelijke klanten",
      },
    },
    howItWorks: {
      title: "Hoe werkt het?",
      subtitle: "Professionele vertaling in vijf stappen.",
      steps: [
        { key: 'upload', title: "Uploaden", desc: "Upload uw document veilig." },
        { key: 'select', title: "Selecteren", desc: "Kies de taal en het type dienst." },
        { key: 'confirm', title: "Bevestigen", desc: "Bevestig uw bestelling." },
        { key: 'track', title: "Volgen", desc: "Volg het proces in realtime." },
        { key: 'receive', title: "Ontvangen", desc: "Ontvang uw professionele levering." },
      ],
    },
    services: {
      title: "Onze diensten",
      subtitle: "Deskundige vertaling voor elk documenttype.",
    },
    why: {
      title: "Waarom TercümExpert?",
      subtitle: "De kenmerken die ons onderscheiden van de concurrentie",
      features: [
        { key: 'autoQuote', title: "Automatische prijsberekening", desc: "Een voorlopige prijs in enkele seconden." },
        { key: 'whatsapp', title: "Snelle offerte via WhatsApp", desc: "Contact met één tik." },
        { key: 'terminology', title: "Terminologiebeheer", desc: "Consistente, zakelijke taal." },
        { key: 'revision', title: "Recht op revisie", desc: "Een proces gericht op tevredenheid." },
        { key: 'languages', title: "Ondersteuning voor 50+ talen", desc: "Brede dekking van talenparen." },
        { key: 'terms', title: "Zakelijk betalingssysteem", desc: "Flexibele betaling voor bedrijven." },
      ],
    },
    corporateCta: {
      title: "Zakelijke oplossingen",
      desc: "Professionele taaldiensten met terminologiebeheer, betalingsopties en een toegewijde accountmanager, afgestemd op uw bedrijf.",
      action: "Zakelijke offerte aanvragen",
    },
    partnershipTeaser: {
      title: "Partnerprogramma",
      subtitle: "Verdien 20% commissie op elke klant die u naar ons doorverwijst.",
      items: [
        { key: 'commission', title: "Transparante commissie", desc: "20% commissie voor elke doorverwijzing (afhankelijk van overeenkomst). Transparante inkomsten met een realtime volgpaneel." },
        { key: 'qr', title: "QR-codesysteem", desc: "Eenvoudige klantregistratie met integratie op uw visitekaartje. QR-codes voor web en WhatsApp." },
      ],
      cta: "Aanmelden als partner",
    },
    testimonials: {
      title: "Klantbeoordelingen",
      subtitle: "Echte klantbeoordelingen worden hier vóór de lancering toegevoegd.",
      placeholderNote: "Tijdelijke tekst — echte beoordelingen worden geïntegreerd.",
      items: [
        { key: 't1', role: "Advocatenkantoor" },
        { key: 't2', role: "Zorginstelling" },
        { key: 't3', role: "Zakelijke klant" },
        { key: 't4', role: "Particuliere klant" },
      ],
    },
    blogTeaser: {
      title: "Blog",
      subtitle: "Actuele content uit de wereld van vertalen",
      viewAll: "Alle blogberichten bekijken",
    },
    finalCta: {
      title: "Begin nu",
      desc: "Upload uw documenten, ontvang direct een offerte en profiteer van professionele vertaaldiensten.",
      primary: "Offerte aanvragen",
      secondary: "Neem contact op",
    },
  },

  services: {
    seo: {
      title: "Vertaaldiensten",
      description:
        "Beëdigde, notarieel bekrachtigde, juridische, technische, medische en academische vertaling plus web-/mobiele lokalisatie. Documenttypen, proces, levering en talenparen.",
    },
    hero: {
      title: "Vertaaldiensten",
      subtitle: "Vertaling met de juiste terminologie voor elk vakgebied.",
    },
    process: {
      title: "Hoe verloopt het proces?",
      steps: [
        { title: "Documentbeoordeling", desc: "Het type en doel van het document worden beoordeeld." },
        { title: "Expertkoppeling", desc: "Een gespecialiseerde vertaler in het vakgebied wordt toegewezen." },
        { title: "Vertaling & redactie", desc: "Vertaling en een onafhankelijke eindcontrole." },
        { title: "Goedkeuring & levering", desc: "Indien nodig notariële bekrachtiging/apostille, daarna levering." },
      ],
    },
    delivery: {
      title: "Leveringsopties",
      items: ["Digitale levering (PDF/DOCX)", "Fysieke levering van documenten", "Spoedlevering"],
    },
    notaryApostille: {
      title: "Verband tussen notariële bekrachtiging en apostille",
      desc: "Indien vereist wordt een beëdigde vertaling geldig gemaakt voor officiële instanties via notariële bekrachtiging en het apostilleproces. De precieze vereiste hangt af van de instantie waar het document wordt ingediend.",
    },
    fullService: {
      title: "Kant-en-klaar, tot aan uw deur bezorgd",
      note: "Stuur ons uw documenten en wij regelen het hele proces — vertaling, notariële bekrachtiging en apostille inbegrepen. Uw voltooide documenten worden per koerier bij u thuis bezorgd. Concentreer u op uw werk en laat de rest aan ons over.",
    },
    cta: {
      title: "Weet u niet zeker welke dienst u nodig heeft?",
      desc: "Upload uw document en wij tonen u de meest geschikte dienst en prijs.",
    },
    documentTypesTitle: "Geschikte documenttypen",
  },

  serviceItems: {
    sworn: {
      name: "Beëdigde vertaling",
      short: "Officieel geldige vertaling met de handtekening en stempel van een beëdigd vertaler.",
      benefits: ["Geldig bij officiële instanties", "Goedkeuring door beëdigd vertaler", "Snel proces"],
    },
    notarized: {
      name: "Notarieel bekrachtigde vertaling",
      short: "Notariële bekrachtiging van een beëdigde vertaling.",
      benefits: ["Notariële bekrachtiging", "Geschikt voor officiële aanvragen", "Wij regelen het proces"],
    },
    apostille: {
      name: "Ondersteuning bij apostilleproces",
      short: "Begeleiding door het apostilleproces voor rechtsgeldigheid in het buitenland.",
      benefits: ["Internationale rechtsgeldigheid", "Procesadvies", "Begeleiding bij instanties"],
    },
    legal: {
      name: "Juridische vertaling",
      short: "Vertaling met beheersing van terminologie voor contracten, rechtbank- en officiële documenten.",
      benefits: ["Juridische terminologie", "Vertrouwelijkheidsgarantie", "Deskundige vertaler"],
    },
    technical: {
      name: "Technische vertaling",
      short: "Consistente vertaling voor handleidingen, specificaties en technische documenten.",
      benefits: ["Terminologiebeheer", "Opmaak behouden", "Vakkennis"],
    },
    medical: {
      name: "Medische vertaling",
      short: "Nauwkeurige vertaling voor rapporten, bijsluiters en medische documenten.",
      benefits: ["Medische terminologie", "Gericht op nauwkeurigheid", "Vertrouwelijkheid"],
    },
    academic: {
      name: "Academische vertaling",
      short: "Academische taal voor scripties, artikelen en diplomavertalingen.",
      benefits: ["Academische stijl", "Consistentie met de bron", "Tijdige levering"],
    },
    localization: {
      name: "Web- en mobiele lokalisatie",
      short: "Cultureel passende lokalisatie van websites en applicaties.",
      benefits: ["Culturele aanpassing", "Technische integratie", "SEO-compatibiliteit"],
    },
  },

  corporate: {
    statsLabels: {
      corporate: "Zakelijke klanten",
      discount: "Korting bij bulkbestellingen",
      term: "Betalingstermijn",
    },
    seo: {
      title: "Zakelijke oplossingen",
      description:
        "Professionele taaldiensten voor bedrijven met terminologiebeheer, betalingsopties, bulkbestellingen en een toegewijde accountmanager.",
    },
    hero: {
      title: "Zakelijke oplossingen",
      subtitle:
        "Professionele taaldiensten met terminologiebeheer, betalingsopties en een toegewijde accountmanager, afgestemd op uw bedrijf.",
      primaryCta: "Zakelijke offerte aanvragen",
      secondaryCta: "E-mail versturen",
    },
    features: {
      title: "Zakelijke kenmerken",
      subtitle: "Oplossingen op maat van uw bedrijf",
      items: [
        {
          key: 'custom',
          icon: 'Target',
          title: "Service op maat",
          points: ["Vaste terminologie", "Behoud van de merktoon", "Toegewijde accountmanager", "Opstellen van een stijlgids"],
        },
        {
          key: 'volume',
          icon: 'BarChart3',
          title: "Bulkverwerking en betalingstermijnen",
          points: ["Maandelijkse vertaalplannen", "Kortingen bij bulkbestellingen", "Termijnen tot 30 dagen", "Facturatiesysteem"],
        },
        {
          key: 'security',
          icon: 'Lock',
          title: "Privacy en beveiliging",
          points: ["NDA-protocol", "Versleutelde bestandsoverdracht", "KVKK-conforme processen"],
        },
      ],
    },
    whyPackage: {
      title: "Waarom een zakelijk pakket?",
      items: [
        {
          key: 'terminology',
          icon: 'Building2',
          title: "Vast terminologiebeheer",
          desc: "Wij bouwen een termenbank die specifiek is voor uw bedrijf. Uw merktaal blijft in alle vertalingen behouden en wij zorgen voor consistentie. Wij letten erop in elk project dezelfde termen te gebruiken.",
        },
        {
          key: 'manager',
          icon: 'Users',
          title: "Toegewijde accountmanager",
          desc: "Uw toegewijde accountmanager volgt al uw processen. Met een bereikbare supportlijn staan wij in spoedeisende situaties aan uw zijde.",
        },
        {
          key: 'security',
          icon: 'ShieldCheck',
          title: "Privacy en beveiliging",
          desc: "Wij werken onder een NDA-protocol. Uw gegevens zijn veilig dankzij een sterke beveiligingsinfrastructuur, versleutelde bestandsoverdracht en KVKK-conforme processen.",
        },
      ],
    },
    payment: {
      title: "Betalingsopties",
      subtitle: "Flexibele betalingsplannen die bij uw bedrijf passen",
      recommendedLabel: "AANBEVOLEN",
      options: [
        {
          key: 'standard',
          label: "Directe betaling",
          heading: "Standaard",
          desc: "Betaling per creditcard of bankoverschrijving na elke bestelling",
          points: ["Creditcardtermijnen", "Directe levering"],
          recommended: false,
        },
        {
          key: 'term',
          label: "Maandelijkse termijn",
          heading: "15-30 dagen",
          desc: "Maandelijkse gebundelde facturatie en betalingstermijnoptie",
          points: ["Termijn van 30 dagen", "Bulkkorting", "Maandelijks rapport"],
          recommended: true,
        },
      ],
    },
    form: {
      title: "Aanvraag zakelijk pakket",
      desc: "Vul het formulier in en ons deskundige team neemt contact met u op",
      fields: {
        company: "Bedrijfsnaam",
        contactName: "Volledige naam contactpersoon",
        email: "E-mail",
        phone: "Telefoon",
        need: "Vertel ons over uw vertaalbehoeften",
        consent: "Ik heb de <kvkk>KVKK-informatieverklaring</kvkk> gelezen en ga hiermee akkoord.",
      },
      submit: "Aanvraag indienen",
      success: "Uw aanvraag is ontvangen. Wij nemen zo snel mogelijk contact met u op.",
      note: "Wij nemen binnen 1 werkdag contact met u op.",
    },
  },

  partnership: {
    seo: {
      title: "Partnerprogramma",
      description:
        "Verdien commissie op elke klant die u doorverwijst. Transparante rapportage, doorverwijzingen via QR-code en professionele ondersteuning.",
    },
    hero: {
      title: "Partnerprogramma",
      value: "Verdien 20% commissie op elke klant die u naar ons doorverwijst.",
      subtitle: "Een transparant systeem, betrouwbare uitbetalingen, langdurige samenwerking.",
      cta: "Nu aanmelden",
    },
    advantages: {
      title: "Voordelen voor partners",
      subtitle: "Waarom partner worden van TercümExpert?",
      items: [
        { key: 'commission', icon: 'Wallet', title: "20% commissiegarantie", desc: "Een transparant commissiesysteem voor elke klant die u doorverwijst." },
        { key: 'qr', icon: 'QrCode', title: "Doorverwijzing via QR-code", desc: "Eenvoudige klantregistratie met integratie op uw visitekaartje." },
        { key: 'reporting', icon: 'BarChart3', title: "Transparante rapportage", desc: "Realtime volgpaneel voor commissie en klanten." },
        { key: 'support', icon: 'Users', title: "Professionele ondersteuning", desc: "Een toegewijde supportlijn voor partners en een accountmanager." },
      ],
    },
    howItWorks: {
      title: "Hoe werkt het?",
      steps: [
        { title: "Aanmelden", desc: "Vul het online aanmeldformulier in. Deel uw bedrijfsgegevens en contactgegevens. Uw aanvraag wordt binnen 1 werkdag beoordeeld." },
        { title: "Partner worden", desc: "Zodra uw aanvraag is goedgekeurd, krijgt u toegang tot uw eigen partnerpaneel. Uw QR-codes en doorverwijslinks staan klaar." },
        { title: "Klanten doorverwijzen", desc: "Verwijs uw klanten naar ons door via QR-code, een persoonlijke link of visitekaartje. Elke doorverwijzing wordt automatisch in het systeem geregistreerd." },
        { title: "Commissie verdienen", desc: "U verdient 20% commissie telkens wanneer een door u doorverwezen klant een bestelling plaatst. U ontvangt elke 15 dagen automatisch een uitbetaling." },
      ],
    },
    sectors: {
      title: "Doelsectoren",
      subtitle: "Voor welke sectoren is het ideaal?",
      items: [
        { key: 'law', icon: 'Scale', title: "Advocatenkantoren", desc: "Behoefte aan beëdigde vertaling van dossiers, contracten en juridische documenten." },
        { key: 'visa', icon: 'Plane', title: "Visumadvies", desc: "Documenten die een beëdigde vertaling vereisen, zoals paspoorten, diploma's en aktes uit de burgerlijke stand." },
        { key: 'education', icon: 'GraduationCap', title: "Onderwijsadvies", desc: "Beëdigde vertaling van studentendocumenten en apostilleprocessen." },
        { key: 'health', icon: 'HeartPulse', title: "Gezondheidstoerisme", desc: "Vertaling van medische rapporten, patiëntendossiers en gezondheidsdocumenten." },
        { key: 'patent', icon: 'Building2', title: "Octrooi-/merkenbureaus", desc: "Technische vertaling van octrooi-, merkregistratie- en juridische documenten." },
        { key: 'realestate', icon: 'Home', title: "Makelaarskantoren", desc: "Vertaling van eigendomsakten, contracten en officiële documenten voor buitenlandse investeerders." },
        { key: 'hr', icon: 'Briefcase', title: "HR-advies", desc: "Vertaling van cv's, diploma's en referentiebrieven voor plaatsing in het buitenland." },
        { key: 'software', icon: 'Code', title: "Softwarebedrijven", desc: "Lokalisatie van web- en mobiele apps, vertaling van technische documenten." },
      ],
    },
    commission: {
      title: "Commissiestructuur",
      stats: {
        commissionLabel: "Standaardcommissie",
        commissionSub: "Op elke bestelling",
        periodUnit: "Dagen",
        periodLabel: "Uitbetalingsperiode",
        feeLabel: "Aansluitkosten",
        feeSub: "Volledig gratis",
      },
      exampleTitle: "Voorbeeldberekening van inkomsten",
      exampleOrderLabel: "Bestelling van de klant die u heeft doorverwezen",
      exampleRateLabel: "Commissiepercentage",
      exampleEarningLabel: "Uw inkomsten",
      note: "Commissiepercentages en voorwaarden zijn afhankelijk van de partnerovereenkomst.",
    },
    form: {
      title: "Aanmeldformulier voor partners",
      subtitle: "Vul het formulier in en wij nemen binnen 1 werkdag contact met u op.",
      fields: {
        company: "Naam bedrijf/organisatie",
        sector: "Sector",
        contactName: "Volledige naam contactpersoon",
        titleRole: "Functie",
        email: "E-mail",
        phone: "Telefoon",
        potential: "Uw geschatte maandelijkse doorverwijspotentieel",
        note: "Eventuele opmerkingen die u wilt toevoegen",
        agreement: "Ik heb de voorwaarden van de <partnership>partnerovereenkomst</partnership> gelezen en ga hiermee akkoord.",
      },
      sectorPlaceholder: "Selecteren",
      sectorOptions: ["Advocatenkantoor", "Visumadvies", "Onderwijsadvies", "Gezondheidstoerisme", "Octrooi-/merkenbureau", "Vastgoed", "HR-advies", "Software", "Overig"],
      potentialOptions: ["1-5 klanten", "5-10 klanten", "10-20 klanten", "20+ klanten"],
      submit: "Aanvraag indienen",
      success: "Uw aanvraag is ontvangen. Wij nemen contact met u op.",
      note: "Uw aanvraag wordt binnen 1 werkdag beoordeeld.",
    },
  },

  quote: {
    "areas": {
      "academic": "Academische vertaling",
      "legal": "Juridische vertaling",
      "official": "Vertaling van officiële documenten",
      "medical": "Medische vertaling",
      "technical": "Technische vertaling",
      "commercial": "Commerciële en financiële vertaling",
      "localization": "Web- en mobiele lokalisatie",
      "literary": "Literaire vertaling",
      "general": "Algemene / overige vertaling"
    },
    "docTypes": {
      "diploma": "Diploma",
      "transcript": "Cijferlijst",
      "student-certificate": "Bewijs van inschrijving",
      "diploma-supplement": "Diplomasupplement",
      "thesis": "Scriptie",
      "reference-letter": "Aanbevelingsbrief",
      "academic-article": "Wetenschappelijk artikel",
      "contract": "Contract",
      "court-decision": "Rechterlijke uitspraak",
      "power-of-attorney": "Volmacht",
      "petition": "Verzoekschrift",
      "consent-statement": "Toestemmingsverklaring",
      "warning-notice": "Ingebrekestelling",
      "litigation-doc": "Procesdocumenten",
      "passport": "Paspoort",
      "id-card": "Identiteitskaart",
      "civil-registry": "Uittreksel uit de burgerlijke stand",
      "birth-certificate": "Geboorteakte",
      "marriage-certificate": "Huwelijksakte",
      "driver-license": "Rijbewijs",
      "criminal-record": "Verklaring omtrent het gedrag",
      "military-status": "Bewijs van militaire status",
      "medical-report": "Medisch rapport",
      "epicrisis": "Ontslagbrief (epicrise)",
      "prescription": "Recept",
      "lab-result": "Laboratorium- / testuitslag",
      "medical-article": "Medisch artikel",
      "patient-consent": "Toestemmingsformulier voor patiënten",
      "user-manual": "Gebruikershandleiding",
      "technical-spec": "Technische specificatie",
      "patent": "Octrooi",
      "product-catalog": "Productcatalogus",
      "datasheet": "Datablad",
      "installation-guide": "Installatiehandleiding",
      "safety-data-sheet": "Veiligheidsinformatieblad",
      "invoice": "Factuur",
      "balance-sheet": "Balans",
      "commercial-contract": "Handelscontract",
      "financial-report": "Financieel verslag",
      "tax-document": "Belastingdocument",
      "activity-certificate": "Bedrijfsverklaring",
      "bank-statement": "Bankafschrift",
      "website": "Website",
      "mobile-app": "Mobiele app",
      "software-ui": "Software-interface",
      "game": "Game",
      "marketing-content": "Marketingcontent",
      "subtitle": "Ondertiteling",
      "e-commerce": "E-commercecontent",
      "book": "Boek",
      "short-story": "Kort verhaal",
      "poem": "Gedicht",
      "screenplay": "Filmscenario",
      "essay": "Essay",
      "article": "Artikel",
      "general-document": "Algemeen document",
      "correspondence": "Correspondentie / brief",
      "cv": "Cv",
      "presentation": "Presentatie",
      "other": "Overig"
    },
    seo: {
      title: "Directe prijsberekening",
      description: "Upload uw document of voer de details in en ontvang direct uw voorlopige offerte.",
    },
    hero: {
      title: "Directe prijsberekening",
      subtitle: "Upload uw document of voer de details in en ontvang direct een voorlopige offerte.",
    },
    upload: {
      heading: "Upload uw documenten",
      privacy: "Uw gegevens worden vertrouwelijk behandeld",
      tabFile: "Bestand uploaden",
      tabText: "Tekst invoeren",
      chooseFile: "Kies uw documenten",
      formats: ".docx, .xlsx, .pdf, .pptx, .jpg, .png en 50+ formaten geaccepteerd · Max. 100MB per bestand",
      dropHint: "U kunt een of meer bestanden naar dit gebied slepen.",
      textPlaceholder: "Plak of typ uw tekst hier…",
      totalWords: "Totaal aantal woorden",
      extracting: "Woorden tellen…",
      wordsUnit: "woorden",
      remove: "Verwijderen",
      unsupported:
        "Automatisch woorden tellen was niet mogelijk voor dit bestandstype. Plak de tekst via \"Tekst invoeren\"; het aantal wordt bij de offerte door ons team geverifieerd.",
      empty:
        "Er is geen selecteerbare tekst in het bestand gevonden (het kan gescand zijn/een afbeelding). Gebruik \"Tekst invoeren\", of het aantal wordt tijdens de offerte geverifieerd.",
      error: "Het bestand kon niet worden gelezen. Probeer het opnieuw of gebruik \"Tekst invoeren\".",
      tooLarge: "Het bestand mag niet groter zijn dan 100MB.",
      needInput: "Upload een bestand of voer tekst in om een prijs te ontvangen.",
    },
    fields: {
      upload: "Document uploaden (optioneel)",
      uploadHint: "PDF, DOC, DOCX of TXT — max. 10 MB",
      sourceLang: "Brontaal",
      targetLang: "Doeltaal",
      serviceType: "Type dienst",
      documentType: "Documenttype",
      wordCount: "Geschat aantal woorden",
      wordCountHint: "Gebruik de schuifregelaar of voer het aantal handmatig in.",
      options: "Aanvullende opties",
      calculate: "Prijs berekenen",
    },
    options: {
      "sworn": "Beëdigde (gecertificeerde) vertaling",
      "apostille": "Ondersteuning bij de apostilleprocedure",
      "swornNotaryHint": "Notariële bekrachtiging omvat al de beëdigde vertaling; u hoeft alleen de ene optie te selecteren die bij uw behoefte past.",
      "physicalRequiredHint": "Beëdigde en notarieel bekrachtigde vertalingen worden geleverd als ondertekende/gestempelde originelen, dus fysieke bezorging wordt automatisch toegevoegd.",
      urgent: "Spoedlevering",
      notarization: "Notariële bekrachtiging",
      physicalDelivery: "Fysieke levering",
    },
    languages: {
      tr: "Turks",
      en: "Engels",
      de: "Duits",
      fr: "Frans",
      es: "Spaans",
      it: "Italiaans",
      ru: "Russisch",
      ar: "Arabisch",
      nl: "Nederlands",
      az: "Azerbeidzjaans",
      pl: "Pools",
      bg: "Bulgaars",
      pt: "Portugees",
      da: "Deens",
    },
    documentTypes: {
      diploma: "Diploma",
      passport: "Paspoort",
      'civil-registry': "Uittreksel burgerlijke stand",
      contract: "Contract",
      'medical-report': "Medisch rapport",
      'technical-doc': "Technisch document",
      'court-doc': "Gerechtelijk document",
      other: "Overig",
    },
    result: {
      title: "Voorlopige offerte",
      basePrice: "Basisservicekosten",
      wordPrice: "Woordtarief",
      addons: "Aanvullende diensten",
      total: "Totaal",
      vat: "btw",
      delivery: "Geschatte levertijd",
      deliveryUnit: "werkdagen",
      disclaimer: "Dit is een voorlopige offerte; de definitieve prijs wordt bevestigd na beoordeling van het document.",
      order: "Bestelling plaatsen",
      whatsapp: "Contact via WhatsApp",
      estimatedWords: "Geschat aantal woorden (automatisch — demo)",
    },
    orderConfirm: {
      title: "Uw bestelling is ontvangen",
      number: "Bestelnr.",
      desc: "Uw aanvraag en documenten zijn opgeslagen. Ons deskundige team beoordeelt het document en neemt zo snel mogelijk contact met u op.",
      viewOrders: "Mijn bestellingen",
      submitting: "Bestelling aanmaken…",
      error: "Er is een probleem opgetreden bij het aanmaken van uw bestelling. Probeer het opnieuw.",
    },
    gate: {
      title: "Uw prijs is klaar",
      subtitle: "Log in of verifieer uw gegevens om de prijs te zien en een bestelling te plaatsen.",
      loginCta: "Inloggen / Registreren",
      or: "of ga snel verder",
      firstName: "Voornaam",
      lastName: "Achternaam",
      email: "E-mail",
      phone: "Telefoonnummer",
      sendCode: "Verificatiecode verzenden",
      codeLabel: "Verificatiecode",
      codeSentA: "heeft een verificatiecode ontvangen.",
      verify: "Verifiëren en prijs bekijken",
      resend: "Code opnieuw verzenden",
      resent: "Er is een nieuwe code verzonden.",
      back: "Gegevens wijzigen",
      errNames: "Voor- en achternaam zijn verplicht.",
      errEmail: "Voer een geldig e-mailadres in.",
      errPhone: "Voer een geldig telefoonnummer in.",
      errCode: "Voer de code volledig in.",
      note: "Uw e-mailadres wordt alleen gebruikt voor de offerte en bestelling.",
    },
    note: {
      label: "Opmerking bij uw bestelling (optioneel)",
      placeholder: "U kunt hier uw wensen over levering, terminologie of speciale verzoeken noteren.",
    },

    checkout: {
      "selectCountry": "Land selecteren",
      "selectCity": "Stad / provincie selecteren",
      "cityNeedsCountry": "Selecteer eerst een land",
      title: "Bezorggegevens",
      subtitle: "Uw fysieke/beëdigde document wordt naar dit adres verzonden.",
      firstName: "Voornaam",
      lastName: "Achternaam",
      phone: "Telefoon",
      address: "Volledig adres",
      addressPlaceholder: "Straat, huis- en appartementnummer…",
      city: "Plaats",
      postalCode: "Postcode",
      country: "Land",
      submit: "Bestelling afronden",
      submitting: "Bestelling wordt aangemaakt…",
      cancel: "Annuleren",
      errRequired: "Vul de verplichte velden in.",
      note: "Deze gegevens worden alleen gebruikt voor bezorging per koerier.",
    },
  },

  order: {
      "trackingCodeLabel": "Trackingnummer",
    seo: {
      title: "Bestelling volgen",
      description: "Volg de status van uw bestelling.",
    },
    numberLabel: "Bestelnr.",
    placedOn: "Besteldatum",
    estimatedLabel: "Geschatte levering van de vertaling",
    cargoEstimatedLabel: "Geschatte verzenddatum",
    timelineTitle: "Status bestelling",
    steps: {
      received: "Uw bestelling is ontvangen",
      in_progress: "In behandeling",
      translated: "Vertaling voltooid",
      shipped: "Verzonden",
      delivered: "Bezorgd",
      cancelled: "Bestelling geannuleerd",
    },
    stepDesc: {
      received: "Uw aanvraag en documenten zijn in ons systeem aangekomen. Ons deskundige team beoordeelt het en begint binnenkort.",
      in_progress: "Onze deskundige vertaler is met uw vertaling begonnen.",
      translated: "Uw vertaling is voltooid en de laatste controles zijn uitgevoerd.",
      shipped: "Uw document is aan de koerier overhandigd; u kunt het volgen met de onderstaande knop.",
      delivered: "Uw document is per e-mail naar u verzonden.",
      cancelled: "Deze bestelling is geannuleerd. Neem bij vragen contact met ons op.",
    },
    cargoReady: "Uw document is verzonden. Volg het met één tik:",
    cargoPending: "De trackingcode verschijnt hier zodra uw document is verzonden.",
    trackCargo: "Mijn zending volgen",
    digitalPending: "Zodra uw vertaling voltooid is, worden uw bestanden per e-mail naar u verzonden.",
    digitalDelivered: "Uw vertaling is per e-mail naar u verzonden. Controleer uw inbox (en spammap).",
    detailsTitle: "Bestelgegevens",
    fields: {
      service: "Dienst",
      langs: "Talen",
      documentType: "Documenttype",
      words: "Woorden",
      delivery: "Geschatte tijd",
      total: "Bedrag",
      note: "Uw opmerking",
      deliveryAddress: "Bezorgadres",
    },
    myOrders: "Mijn bestellingen",
    backHome: "Terug naar Home",
    whatsapp: "Contact via WhatsApp",
    loading: "Bestelling laden…",
    loginRequired: {
      title: "Log in om uw bestelling te bekijken",
      desc: "U heeft alleen toegang tot uw bestelgegevens nadat u met uw account bent ingelogd.",
      login: "Inloggen",
    },

    notFound: {
      title: "Bestelling niet gevonden",
      desc: "Dit bestelnummer hoort niet bij u of bestaat niet. Controleer de link.",
      home: "Terug naar Home",
    },
  },

  faq: {
    seo: {
      title: "Veelgestelde vragen",
      description: "Veelgestelde vragen over beëdigde vertaling, levertijd, prijzen, notariële bekrachtiging en zakelijke betalingstermijnen.",
    },
    hero: { title: "Veelgestelde vragen", subtitle: "Het antwoord dat u zoekt, vindt u hier." },
    categoriesTitle: "Categorieën",
    searchPlaceholder: "Zoek op vragen of trefwoorden…",
    empty: "Geen vragen kwamen overeen met uw zoekopdracht. Probeer een ander woord of neem contact met ons op.",
    categories: FAQ_CATEGORIES_NL,
    items: FAQ_ITEMS_NL,
    notFound: {
      title: "Heeft u het antwoord op uw vraag niet gevonden?",
      contact: "Neem contact op",
      whatsapp: "WhatsApp-ondersteuning",
    },
  },

  contact: {
      introTitle: `Welkom`,
      introDesc: `Mag ik eerst uw naam en e-mailadres, zodat ik u beter van dienst kan zijn?`,
      start: `Chat starten`,
      introError: `Voer uw naam en e-mailadres in.`,
    seo: {
      title: "Contact",
      description: "Neem contact op met TercümExpert: telefoon, e-mail, WhatsApp en contactformulier.",
    },
    hero: { title: "Contact", subtitle: "Hoe kunnen wij u helpen?" },
    infoTitle: "Contactgegevens",
    labels: {
      phone: "Telefoon",
      email: "E-mail",
      whatsapp: "WhatsApp",
      address: "Adres",
      hours: "Openingstijden",
    },
    form: {
      title: "Neem contact op",
      fields: {
        name: "Volledige naam",
        email: "E-mail",
        phone: "Telefoon",
        subject: "Onderwerp",
        message: "Bericht",
        consent: "Ik heb de <kvkk>KVKK-informatieverklaring</kvkk> gelezen en ga hiermee akkoord.",
      },
      submit: "Bericht verzenden",
      success: "Uw bericht is ontvangen. Wij nemen binnenkort contact met u op.",
    },
    map: {
      title: "Onze locatie",
      subtitle: "Vind ons op de kaart",
      placeholder: "Kaartgebied",
      note: "De locatiekaart wordt hier binnenkort weergegeven.",
    },
  },

  auth: {
    seo: {
      title: "Inloggen / Registreren",
      description: "Log in op uw TercümExpert-account of maak een nieuw account aan.",
    },
    tabs: { login: "Inloggen", register: "Registreren" },
    google: "Doorgaan met Google",
    or: "of",
    fields: {
      firstName: "Voornaam",
      lastName: "Achternaam",
      email: "E-mail",
      password: "Wachtwoord",
      code: "Verificatiecode",
    },
    login: {
      title: "Log in op uw account",
      submit: "Inloggen",
      noAccount: "Heeft u nog geen account?",
      switchToRegister: "Registreren",
    },
    register: {
      title: "Een nieuw account aanmaken",
      submit: "Registreren",
      haveAccount: "Heeft u al een account?",
      switchToLogin: "Inloggen",
      consent: "Door een account aan te maken, ga ik akkoord met de <kvkk>KVKK-informatieverklaring</kvkk> en het <privacy>privacybeleid</privacy>.",
    },
    verify: {
      title: "Verifieer uw e-mailadres",
      desc: "— voer de 6-cijferige code in die wij naar dit adres hebben gestuurd.",
      submit: "Verifiëren en doorgaan",
      spam: "De code kan enkele minuten vertraging hebben; controleer ook uw spam-/ongewenste map.",
      resend: "Code opnieuw verzenden",
      resent: "Er is een nieuwe code verzonden.",
      back: "Terug",
    },
    signedIn: {
      title: "Mijn account",
      greeting: "Welkom",
      logout: "Uitloggen",
    },
    orders: {
      title: "Mijn bestellingen",
      empty: "U heeft nog geen bestellingen. U kunt uw eerste bestelling aanmaken via Prijs berekenen.",
      loading: "Bestellingen laden…",
      error: "Bestellingen konden niet worden geladen. Vernieuw de pagina.",
      status: {
        received: "Ontvangen",
        in_progress: "In behandeling",
        translated: "Vertaling voltooid",
        shipped: "Verzonden",
        delivered: "Bezorgd",
        cancelled: "Geannuleerd",
      },
      track: "Volgen",
    },
    errors: {
      nameRequired: "Voor- en achternaam zijn verplicht.",
      emailInvalid: "Voer een geldig e-mailadres in.",
      passwordShort: "Het wachtwoord moet minimaal 6 tekens bevatten.",
      codeInvalid: "Voer de 6-cijferige code in.",
      consentRequired: "Akkoord is vereist om door te gaan.",
    },
  },

  blog: {
    seo: { title: "Blog", description: "Gidsen over vertaling, notariële bekrachtiging, apostille en lokalisatie." },
    hero: { title: "Blog", subtitle: "Gidsen uit de wereld van vertalen." },
    searchPlaceholder: "Zoek berichten…",
    readingTime: "min leestijd",
    relatedTitle: "Gerelateerde berichten",
    allCategories: "Alle",
    empty: "Geen berichten kwamen overeen met dit criterium.",
  },

  legal: {
    lastUpdatedLabel: `Laatst bijgewerkt`,
    draftNotice: `In de onderstaande tekst worden de velden die tussen vierkante haken ([...]) staan aangevuld met de gegevens van uw onderneming. De teksten dienen uitsluitend ter algemene informatie en het wordt aanbevolen deze vóór publicatie door een juridisch deskundige te laten controleren.`,
    kvkk: {
      seo: { title: `KVKK-informatieverklaring`, description: `Informatieverklaring over de verwerking van uw persoonsgegevens in het kader van de KVKK (wet nr. 6698).` },
      title: `KVKK-informatieverklaring`,
      sections: [
        { heading: `Verwerkingsverantwoordelijke`, body: `In overeenstemming met de Turkse wet nr. 6698 inzake de bescherming van persoonsgegevens (“KVKK”) worden uw persoonsgegevens verwerkt door [ŞİRKET ÜNVANI] (“TercümExpert”), in de hoedanigheid van verwerkingsverantwoordelijke, binnen de hieronder beschreven reikwijdte. Adres: [ADRES]. E-mail: [E-POSTA]. Telefoon: [TELEFON].` },
        { heading: `Verwerkte persoonsgegevens`, body: `Verwerkt worden: uw identiteits- en contactgegevens (voornaam, achternaam, e-mailadres, telefoonnummer), uw bezorgadresgegevens, uw bestel- en transactiegegevens, de gegevens in de inhoud van de documenten die u ons ter vertaling toestuurt, alsmede transactieveiligheidsgegevens met betrekking tot uw gebruik van de website (IP-adres, sessie- en cookiegegevens).` },
        { heading: `Doeleinden van de verwerking`, body: `Uw persoonsgegevens worden verwerkt met het oog op het verlenen van diensten in verband met vertaling, beëdigde vertaling en notariële en apostilleverklaringen, het opstellen van offertes en het beheer van bestellingen, het beheer van klantrelaties en van verzoeken en klachten, het nakomen van contractuele en wettelijke verplichtingen en het waarborgen van de veiligheid van de dienstverlening.` },
        { heading: `Rechtsgronden voor de verwerking`, body: `Uw gegevens worden verwerkt op grond van de volgende rechtsgronden: de noodzaak voor het sluiten of uitvoeren van een overeenkomst, het nakomen van onze wettelijke verplichtingen, de vaststelling en verdediging van een recht, alsmede onze gerechtvaardigde belangen, mits daarbij geen afbreuk wordt gedaan aan uw grondrechten en fundamentele vrijheden; waar nodig worden zij verwerkt op basis van uw uitdrukkelijke toestemming (KVKK m.5 en m.6).` },
        { heading: `Wijze van verzameling`, body: `Uw persoonsgegevens worden langs elektronische weg verzameld via de formulieren op de website, de registratie- en bestelprocessen, e-mail en andere communicatiekanalen.` },
        { heading: `Doorgifte van persoonsgegevens`, body: `Uw gegevens kunnen, voor zover de dienstverlening dit vereist, worden doorgegeven aan onze in binnen- en buitenland gevestigde leveranciers van wie wij hosting-, infrastructuur-, authenticatie-, e-mail- en analysediensten afnemen, alsmede aan bevoegde overheidsinstellingen en -organen, in overeenstemming met de voorwaarden van KVKK m.8 en m.9. Aangezien de servers van sommige door ons gebruikte infrastructuur- en dienstverleners zich in het buitenland bevinden, kunnen uw gegevens naar het buitenland worden doorgegeven binnen het kader van de in de regelgeving voorziene waarborgen.` },
        { heading: `Bewaartermijnen`, body: `Uw persoonsgegevens worden bewaard gedurende de termijn die het verwerkingsdoel vereist en gedurende de verjarings- en bewaartermijnen die zijn voorgeschreven in de toepasselijke regelgeving (zoals de belasting-, handels- en consumentenwetgeving); na afloop van deze termijnen worden zij gewist, vernietigd of geanonimiseerd.` },
        { heading: `Rechten van de betrokkene`, body: `Op grond van KVKK m.11 heeft u het recht om te vernemen of uw persoonsgegevens worden verwerkt, om, indien dat het geval is, hierover informatie te verlangen, om het doel van de verwerking te vernemen en of de gegevens overeenkomstig dat doel worden gebruikt, om te weten aan welke derden in binnen- of buitenland de gegevens zijn doorgegeven, om, indien de gegevens onvolledig of onjuist zijn verwerkt, rectificatie te verlangen, om, wanneer de voorwaarden daartoe zijn vervuld, wissing of vernietiging te verlangen, om te verlangen dat deze handelingen worden meegedeeld aan de derden aan wie de gegevens zijn doorgegeven, om bezwaar te maken tegen een voor u nadelig resultaat dat voortvloeit uit uitsluitend geautomatiseerde analyse, en om, indien u schade lijdt, vergoeding van die schade te vorderen.` },
        { heading: `Wijze van verzoekindiening`, body: `U kunt uw verzoeken met betrekking tot uw rechten schriftelijk indienen, in overeenstemming met de “Veri Sorumlusuna Başvuru Usul ve Esasları Hakkında Tebliğ”, via het adres [E-POSTA] of op het adres [ADRES]. Uw verzoek wordt, naargelang de aard ervan, zo spoedig mogelijk en uiterlijk binnen dertig dagen afgehandeld.` },
      ],
    },
    privacy: {
      seo: { title: `Privacybeleid`, description: `Ons beleid met betrekking tot de vertrouwelijkheid van uw persoonsgegevens en documenten.` },
      title: `Privacybeleid`,
      sections: [
        { heading: `Inleiding`, body: `Bij TercümExpert hechten wij belang aan uw privacy. Dit Privacybeleid beschrijft welke gegevens wij, voor welke doeleinden, verzamelen en hoe wij deze beschermen bij de diensten die wij aanbieden via [WEB ADRESİ]. Uitgebreide informatie over de verwerking van persoonsgegevens vindt u in de KVKK-informatieverklaring.` },
        { heading: `Gegevens die wij verzamelen`, body: `Wij kunnen de volgende gegevens verzamelen: account- en contactgegevens (voornaam, achternaam, e-mail, telefoon), bestel- en bezorggegevens, de documenten die u ons ter vertaling toestuurt en de inhoud daarvan, transactiegegevens met betrekking tot betalingen en technische gegevens over uw gebruik van de website (IP-adres, browsergegevens, cookiegegevens).` },
        { heading: `Doeleinden waarvoor wij gegevens gebruiken`, body: `Wij gebruiken uw gegevens om de diensten te verlenen, offertes en bestellingen te beheren, met u te communiceren, onze wettelijke verplichtingen na te komen en de kwaliteit en veiligheid van de dienstverlening te verbeteren. Wij verwerken uw documenten uitsluitend voor zover de door u gevraagde dienst dit vereist.` },
        { heading: `Vertrouwelijkheid van documenten`, body: `De aan ons voor vertaling toevertrouwde documenten worden als vertrouwelijk behandeld. Alleen de bevoegde vertaler en het personeel dat de betreffende dienst uitvoert, hebben toegang tot deze documenten gedurende de tijd die het werk vereist; uw documenten worden niet met derden gedeeld voor andere doeleinden dan de dienstverlening.` },
        { heading: `Externe dienstverleners`, body: `Bij het verlenen van onze diensten maken wij gebruik van betrouwbare externe dienstverleners op het gebied van hosting en infrastructuur, authenticatie, e-mailverzending, analyse en (wanneer geactiveerd) betalingen. Deze dienstverleners hebben uitsluitend toegang tot uw gegevens om de hun opgedragen dienst te verlenen en zijn gebonden aan contractuele geheimhoudingsverplichtingen; de servers van sommige daarvan kunnen zich in het buitenland bevinden.` },
        { heading: `Gegevensbeveiliging`, body: `Om uw gegevens te beschermen tegen ongeoorloofde toegang passen wij versleuteling tijdens de overdracht, toegangsbeperkingen en passende organisatorische en technische maatregelen toe. Hoewel geen enkele methode absolute veiligheid kan bieden, treffen wij redelijke en actuele maatregelen om uw gegevens te beschermen.` },
        { heading: `Cookies`, body: `Op onze website worden cookies en soortgelijke technologieën gebruikt. Voor uitgebreide informatie over de soorten cookies en het beheer van uw voorkeuren kunt u het Cookiebeleid raadplegen.` },
        { heading: `Uw rechten`, body: `U kunt uw rechten in het kader van de KVKK uitoefenen, waaronder het recht op inzage, rectificatie en wissing van uw persoonsgegevens. Voor uw verzoeken kunt u contact met ons opnemen via het adres [E-POSTA].` },
        { heading: `Privacy van kinderen`, body: `Onze diensten zijn niet gericht op personen jonger dan 18 jaar en wij verzamelen niet bewust persoonsgegevens van kinderen.` },
        { heading: `Wijzigingen`, body: `Dit beleid kan van tijd tot tijd worden bijgewerkt. De actuele versie wordt steeds op deze pagina gepubliceerd; bij belangrijke wijzigingen wordt u op passende wijze geïnformeerd.` },
        { heading: `Contact`, body: `Voor vragen over privacy: E-mail: [E-POSTA] · Telefoon: [TELEFON] · Adres: [ADRES].` },
      ],
    },
    distanceSales: {
      seo: { title: `Overeenkomst op afstand`, description: `Overeenkomst op afstand met betrekking tot de verkoop van diensten in het kader van wet nr. 6502.` },
      title: `Overeenkomst op afstand`,
      sections: [
        { heading: `Partijen`, body: `Deze Overeenkomst op afstand (“Overeenkomst”) is langs elektronische weg tot stand gekomen tussen enerzijds [ŞİRKET ÜNVANI] (“Verkoper”; adres: [ADRES], e-mail: [E-POSTA], telefoon: [TELEFON]) en anderzijds de consument die de bestelling plaatst (“Koper”), in overeenstemming met de Turkse wet nr. 6502 inzake consumentenbescherming en de Mesafeli Sözleşmeler Yönetmeliği.` },
        { heading: `Onderwerp van de Overeenkomst`, body: `Het onderwerp van de Overeenkomst is het verlenen van de diensten in verband met vertaling, beëdigde vertaling en notariële en apostilleverklaringen die de Koper langs elektronische weg via [WEB ADRESİ] heeft besteld en waarvan de kenmerken en de verkoopprijs in het besteloverzicht zijn vermeld.` },
        { heading: `Kenmerken en prijs van de dienst`, body: `De aard en de omvang van de bestelde dienst, de wijze van levering (digitaal of per koerier) en de totale prijs inclusief belastingen worden bij de bestelling duidelijk aan de Koper getoond en zijn opgenomen in de bevestiging van de bestelling. De prijsstelling wordt berekend op basis van de gekozen dienst en de kenmerken van het document.` },
        { heading: `Betaling`, body: `De betaling wordt verricht met de betaalmethoden die tijdens de bestelstap worden aangeboden. De bestelling wordt in behandeling genomen nadat de betaling is bevestigd.` },
        { heading: `Uitvoering en levering`, body: `Bij digitale leveringen wordt de vertaling na voltooiing aan de Koper toegezonden via zijn account of e-mail. Bij fysieke, nat ondertekende of beëdigde documenten vindt de levering per koerier plaats naar het door de Koper opgegeven adres. De geschatte levertermijnen worden bij de bestelling vermeld; deze kunnen variëren afhankelijk van de omvang van het document en de goedkeuringsprocessen.` },
        { heading: `Herroepingsrecht`, body: `De Koper heeft bij overeenkomsten inzake dienstverlening in beginsel het recht om de overeenkomst binnen veertien (14) dagen na de datum van totstandkoming zonder opgave van redenen te herroepen. De hieronder vermelde uitzonderingen blijven evenwel voorbehouden.` },
        { heading: `Uitzonderingen op het herroepingsrecht`, body: `Op grond van m.15 van de Mesafeli Sözleşmeler Yönetmeliği kan het herroepingsrecht niet worden uitgeoefend bij diensten waarvan met instemming van de Koper met de uitvoering is begonnen en die vóór het verstrijken van de herroepingstermijn zijn voltooid, alsmede bij goederen en diensten die speciaal zijn vervaardigd overeenkomstig de wensen of persoonlijke behoeften van de Koper (met inbegrip van vertaal- en goedkeuringsdiensten die op maat van de persoon of het document zijn opgesteld). Annuleringsverzoeken die worden ingediend voordat met het vertaalwerk is begonnen, worden afzonderlijk beoordeeld.` },
        { heading: `Annulering en terugbetaling`, body: `Bij bestellingen waarvan de uitvoering nog niet is aangevangen, kunnen annuleringsverzoeken worden ingediend via [E-POSTA]; goedgekeurde terugbetalingen worden binnen een redelijke termijn verricht met de methode waarmee de betaling is gedaan. Bij op maat gemaakte diensten waarvan de uitvoering is aangevangen of voltooid, kan terugbetaling gezien de aard van het werk niet mogelijk zijn.` },
        { heading: `Beslechting van geschillen`, body: `Bij geschillen die uit deze Overeenkomst kunnen voortvloeien zijn, binnen de door de Ticaret Bakanlığı jaarlijks bekendgemaakte financiële grenzen, de Tüketici Hakem Heyetleri en de consumentenrechtbanken van de woonplaats van de Koper of van de plaats waar de transactie is verricht, bevoegd.` },
        { heading: `Inwerkingtreding`, body: `Door de bestelling te bevestigen verklaart de Koper alle voorwaarden van deze Overeenkomst te hebben gelezen en te aanvaarden. De Overeenkomst treedt in werking met de bevestiging van de bestelling.` },
      ],
    },
    cookies: {
      seo: { title: `Cookiebeleid`, description: `Informatie over de op onze website gebruikte cookies en het beheer van voorkeuren.` },
      title: `Cookiebeleid`,
      sections: [
        { heading: `Wat is een cookie?`, body: `Cookies zijn kleine tekstbestanden die op uw browser worden opgeslagen wanneer u een website bezoekt. Zij worden gebruikt om de website veiliger en functioneler te maken, uw voorkeuren te onthouden en gebruiksstatistieken te verkrijgen.` },
        { heading: `Waarom gebruiken wij cookies?`, body: `Wij gebruiken cookies om de basisfuncties van de website te bieden, de veiligheid van de sessie te waarborgen, de prestaties te meten en, afhankelijk van uw toestemming, onze diensten te verbeteren en marketingactiviteiten uit te voeren.` },
        { heading: `Categorieën cookies`, body: `Noodzakelijke cookies zijn vereist voor de werking en de veiligheid van de website en kunnen niet worden uitgeschakeld. Prestatie- en analysecookies helpen ons de interactie van bezoekers te begrijpen. Marketingcookies ondersteunen het aanbieden van inhoud en advertenties die aansluiten bij uw interesses. Voorkeurscookies onthouden uw keuzes, zoals de taal. Analyse- en marketingcookies werken uitsluitend met uw uitdrukkelijke toestemming.` },
        { heading: `Cookies van derden`, body: `Voor analyse- en marketingdoeleinden kunnen wij gebruikmaken van diensten van derden (bijvoorbeeld hulpmiddelen voor bezoekersstatistieken en advertentiemeting). Deze diensten kunnen hun eigen cookies plaatsen en gegevens verwerken in het kader van hun eigen privacybeleid.` },
        { heading: `Beheer van cookievoorkeuren`, body: `U kunt uw voorkeuren met betrekking tot niet-noodzakelijke cookies op elk gewenst moment geven of wijzigen via het cookievoorkeurshulpmiddel dat op de website wordt aangeboden. Daarnaast kunt u cookies verwijderen of blokkeren via de instellingen van uw browser; in dat geval kunnen echter bepaalde onderdelen van de website niet naar behoren functioneren.` },
        { heading: `Bewaartermijnen`, body: `Cookies worden, afhankelijk van hun type, gedurende de sessie of voor een bepaalde periode bewaard. Sessiecookies worden verwijderd wanneer de browser wordt gesloten; permanente cookies verstrijken na de vastgestelde periode of wanneer u ze verwijdert.` },
        { heading: `Wijzigingen`, body: `Dit Cookiebeleid kan van tijd tot tijd worden bijgewerkt. De actuele versie wordt steeds op deze pagina gepubliceerd.` },
      ],
    },
    partnership: {
      seo: { title: `Partnerschapsovereenkomst`, description: `De voorwaarden van het partnerprogramma (partnership) van TercümExpert.` },
      title: `Partnerschapsovereenkomst`,
      sections: [
        { heading: `Partijen en Onderwerp`, body: `Deze Partnerschapsovereenkomst is tot stand gekomen tussen enerzijds [ŞİRKET ÜNVANI] (“TercümExpert”) en anderzijds de partner die zich voor het programma aanmeldt (“Partner”), met als doel de voorwaarden en bepalingen van het partnerprogramma (verwijzingsprogramma) van TercümExpert te regelen.` },
        { heading: `Reikwijdte van het Programma`, body: `De Partner verwijst via zijn eigen netwerk en kanalen klanten naar TercümExpert. Indien de verwezen klant via TercümExpert een dienst aankoopt, verwerft de Partner het recht op de in deze Overeenkomst vermelde commissie.` },
        { heading: `Commissie`, body: `De Partner verwerft voor iedere geldige en goedgekeurde verwijzing recht op een commissie ten belope van %20 over de door de verwezen klant betaalde dienstvergoeding. Het commissiepercentage en de daaraan verbonden voorwaarden kunnen door TercümExpert worden gewijzigd, mits voorafgaande kennisgeving. Geannuleerde, terugbetaalde of niet volledig betaalde transacties komen niet in aanmerking voor commissie.` },
        { heading: `Registratie en Verwerving van Rechten`, body: `Verwijzingen worden gekoppeld via de aan de Partner verstrekte trackinglink, QR-code of een door TercümExpert bepaalde methode. Het recht op commissie ontstaat uitsluitend voor transacties die op correcte wijze via deze methoden worden gekoppeld en waarvan de betaling is voltooid.` },
        { heading: `Betaling`, body: `De verworven commissies worden uitbetaald op de door de Partner opgegeven rekening. De betalingsperiode en de daaraan verbonden voorwaarden worden nader tussen partijen overeengekomen. De fiscale verplichtingen met betrekking tot de betaling zijn onderworpen aan de geldende wet- en regelgeving.` },
        { heading: `Verplichtingen van de Partner`, body: `De Partner verbindt zich ertoe in zijn promotieactiviteiten juiste en niet-misleidende informatie te gebruiken, zich te onthouden van gedragingen die het merk en de reputatie van TercümExpert kunnen schaden, en de geldende wet- en regelgeving na te leven.` },
        { heading: `Verboden Gedragingen`, body: `Spam en het verzenden van ongewenste bulkberichten, misleidende reclame, valse of zelf-verwijzingen en gedragingen die oneerlijke concurrentie vormen, zijn verboden. Dergelijke gedragingen vormen een grond voor annulering van de commissie en ontbinding van de Overeenkomst.` },
        { heading: `Gebruik van het Merk`, body: `De Partner mag het merk, het logo en het promotiemateriaal van TercümExpert uitsluitend gebruiken binnen het kader van de schriftelijke toestemming en de door TercümExpert verstrekte regels.` },
        { heading: `Vertrouwelijkheid`, body: `Partijen verbinden zich ertoe de vertrouwelijke informatie die zij in het kader van deze Overeenkomst verkrijgen te beschermen en uitsluitend te gebruiken ten behoeve van het doel van het programma.` },
        { heading: `Onafhankelijke Partij`, body: `De Partner is een onafhankelijke partij; hij is geen werknemer, vertegenwoordiger of agent van TercümExpert en kan namens TercümExpert geen verbintenissen aangaan jegens derden.` },
        { heading: `Duur en Ontbinding`, body: `De Overeenkomst blijft van kracht totdat een van de partijen de ontbinding ervan meedeelt. TercümExpert kan de Overeenkomst in geval van niet-nakoming van de verplichtingen met onmiddellijke ingang ontbinden; in dat geval worden commissies voortvloeiend uit onrechtmatige verwijzingen niet uitbetaald.` },
        { heading: `Geschillen en Toepasselijk Recht`, body: `Deze Overeenkomst is onderworpen aan het recht van de Türkiye Cumhuriyeti. Door de aanmelding te bevestigen, verklaart de Partner de voorwaarden van de Overeenkomst te hebben gelezen en te aanvaarden.` },
      ],
    },
  },

  admin: {
    attachmentImage: 'Afbeelding',
    attachmentFile: 'Document',
    title: `Chatlogboeken`,
    summary: `{total} gesprekken · {leads} contactverzoeken`,
    onlyLeads: `Alleen contactverzoeken`,
    loading: `Logboeken worden geladen…`,
    error: `De logboeken konden niet worden gelezen. Controleer of de Supabase-tabel en de bijbehorende rechten (RLS) correct zijn ingesteld.`,
    empty: `Er zijn nog geen logboeken.`,
    selectHint: `Selecteer links een gesprek om het te bekijken.`,
    contactRequest: `Contactverzoek`,
    contactInfo: `Contactgegevens`,
    fieldName: `Naam`,
    fieldEmail: `E-mail`,
    fieldPhone: `Telefoon`,
    fieldMessage: `Bericht`,
    requestBadge: `verzoek`,
    noMessages: `Dit logboek bevat geen berichten (alleen een contactverzoek).`,
    loginTitle: `Aanmelden vereist`,
    loginDesc: `Meld u met een beheerdersaccount aan om deze pagina te bekijken.`,
    login: `Aanmelden`,
    noAccessTitle: `U heeft geen toegang`,
    noAccessDesc: `Deze pagina is alleen toegankelijk voor beheerders.`,
    loadingAuth: `Bezig met laden…`,
  },
  footer: {
    tagline: "Uw betrouwbare partner voor professionele vertaaldiensten.",
    columns: {
      quickLinks: "Snelle links",
      services: "Diensten",
      contact: "Contact",
    },
    quickLinks: {
      corporate: "Zakelijk",
      services: "Onze diensten",
      quote: "Prijs berekenen",
      blog: "Blog",
      faq: "Veelgestelde vragen",
      contact: "Contact",
    },
    serviceLinks: {
      sworn: "Beëdigde vertaling",
      notarized: "Notarieel bekrachtigde vertaling",
      apostille: "Apostilleproces",
      corporate: "Zakelijke oplossingen",
      partnership: "Partnerprogramma",
    },
    legal: {
      kvkk: "KVKK",
      privacy: "Privacybeleid",
      distanceSales: "Overeenkomst op afstand",
      cookies: "Cookiebeleid",
    },
    socialTitle: "Volg ons",
    whatsapp: "WhatsApp-ondersteuning",
    rights: "Alle rechten voorbehouden.",
  },

  cookie: {
    title: "Cookievoorkeuren",
    desc: "Wij gebruiken cookies om uw ervaring te verbeteren. Andere cookies dan de noodzakelijke worden alleen met uw toestemming ingezet.",
    accept: "Accepteren",
    reject: "Weigeren",
    manage: "Voorkeuren beheren",
    save: "Voorkeuren opslaan",
    categories: {
      necessary: { label: "Noodzakelijk", desc: "Vereist voor het functioneren van de site; kan niet worden uitgeschakeld." },
      analytics: { label: "Analytisch", desc: "Helpt ons het gebruik te begrijpen." },
      marketing: { label: "Marketing", desc: "Voor relevante content en advertenties." },
      preferences: { label: "Voorkeuren", desc: "Onthoudt uw voorkeuren." },
    },
  },

  chatbot: {
    attach: {
      button: 'Bestand bijvoegen',
      tooLarge: 'Bestand is te groot (max. 25 MB).',
      unsupported: 'Ik kan audio- of videobestanden niet in de chat analyseren. U kunt ze uploaden op de offertepagina.',
      cannotRead: 'Ik kon dit bestand niet lezen. U kunt het uploaden op de offertepagina of een ander formaat proberen.',
      reading: 'Bestand wordt gelezen…',
      remove: 'Verwijderen',
    },
    nudge: 'Hoe kan ik u helpen?',
    title: "TercümExpert-ondersteuning",
    open: "Chat openen",
    close: "Chat sluiten",
    minimize: "Minimaliseren",
    clear: "Gesprek wissen",
    inputPlaceholder: "Typ uw bericht…",
    send: "Verzenden",
    typing: "Aan het typen…",
    welcome:
      "Hallo en welkom bij TercümExpert. Ik kan u helpen met vertaling, prijzen, notariële bekrachtiging, apostille of zakelijke diensten.",
    quickQuestions: [
      "Hoe wordt de prijs berekend?",
      "Wat is een beëdigde vertaling?",
      "Ik wil een document uploaden",
      "Ik wil een zakelijke offerte",
      "Is notariële bekrachtiging vereist?",
      "Verbind mij met een medewerker",
    ],
    handoff: "Verbinden met een medewerker",
    toWhatsapp: "Overzetten naar WhatsApp",
    disclaimer: "Deze informatie is algemeen; bevestig de exacte vereisten bij de betreffende instantie.",
    sensitiveWarning:
      "Deel geen gevoelige persoonsgegevens via deze chat. U kunt uw documenten versturen via het beveiligde uploadgebied.",
    answers: [
      `De prijs wordt berekend op basis van het aantal woorden in uw document, de talencombinatie, het type dienst (beëdigd, notarieel gewaarmerkt, apostille) en de gewenste levertijd. Voor een directe prijsindicatie kunt u uw document uploaden of de gegevens invoeren op de pagina Prijs Berekenen.`,
      `Een beëdigde vertaling is een officiële vertaling die door een beëdigd vertaler wordt gemaakt en met diens handtekening en stempel wordt gewaarmerkt. Officiële instanties vragen meestal om een beëdigde vertaling; indien nodig kan hier ook een notariële waarmerking aan worden toegevoegd.`,
      `U kunt uw document veilig aanleveren via de beveiligde uploadfunctie op de pagina Prijs Berekenen. Direct na het uploaden ziet u de geschatte prijs en kunt u uw bestelling afronden.`,
      `Voor uw zakelijke behoeften bieden wij bij regelmatige en grootschalige vertalingen speciale tarieven en levering met voorrang. Voor meer informatie kunt u onze pagina voor Zakelijke Klanten raadplegen of contact met ons opnemen.`,
      `Of een notariële waarmerking nodig is, hangt af van de instantie waar u het document indient en van het type procedure. Sommige procedures accepteren uitsluitend een beëdigde vertaling, terwijl andere ook een notariële waarmerking vereisen. Weet u het niet zeker, dan helpen wij u graag verder.`,
      `Wij verbinden u direct met een van onze medewerkers. Via de onderstaande knop kunt u ons een bericht sturen via WhatsApp.`,
    ],
    fallback: `Een van onze medewerkers kan u het beste van dienst zijn met uw vraag. Via de onderstaande knop kunt u ons een bericht sturen via WhatsApp; uw bericht wordt alvast voor u klaargezet.`,
    contact: {
      "introTitle": "Welkom",
      "introDesc": "Om u beter te kunnen helpen, mag ik eerst uw naam en e-mailadres noteren?",
      "start": "Chat starten",
      "introError": "Voer uw naam en e-mailadres in.",
      whatsapp: `WhatsApp`,
      email: `E-mail`,
      phone: `Telefoon`,
      leaveInfo: `Laat mijn contactgegevens achter`,
      formTitle: `Laat ons contact met u opnemen`,
      formDesc: `Laat uw gegevens achter, dan neemt ons team zo spoedig mogelijk contact met u op.`,
      name: `Uw naam`,
      emailField: `E-mail`,
      phoneField: `Telefoon`,
      message: `Uw bericht (optioneel)`,
      submit: `Verzenden`,
      submitting: `Bezig met verzenden…`,
      thanks: `Bedankt, ons team neemt zo spoedig mogelijk contact met u op.`,
      errorRequired: `Voer een e-mailadres of telefoonnummer in.`,
      back: `Terug`,
    },
  },

  translator: {
    "seo": {
      "title": "Vertalerspaneel — TercümExpert",
      "description": "Vertalersaanmelding en werkpaneel."
    },
    "loading": "Laden…",
    "loginTitle": "Aanmelden vereist",
    "loginDesc": "Dit gedeelte is uitsluitend bedoeld voor vertalers en beheerders. Meld u aan om verder te gaan.",
    "login": "Aanmelden",
    "setupTitle": "Paneel nog niet gereed",
    "setupDesc": "De vertalersinfrastructuur (database) is nog niet ingericht. Het paneel wordt geactiveerd zodra de configuratie is voltooid.",
    "applyTitle": "Vertalersaanmelding",
    "applyDesc": "Vul uw gegevens in om deel te nemen aan ons netwerk van freelance vertalers. Uw aanmelding wordt geactiveerd na goedkeuring door de beheerder.",
    "applyNote": "Uw gegevens worden uitsluitend gebruikt voor beoordeling en betaling.",
    "form": {
      "fullName": "Volledige naam",
      "birthDate": "Geboortedatum",
      "phone": "Telefoon",
      "country": "Land",
      "city": "Stad / provincie",
      "selectCountry": "Selecteer land",
      "selectCity": "Selecteer stad / provincie",
      "cityNeedsCountry": "Selecteer eerst een land",
      "address": "Volledig adres",
      "isSworn": "Bent u een beëdigd (gecertificeerd) vertaler?",
      "isSwornHint": "Vink dit aan als u beschikt over een notarieel bekrachtigde beëdiging. U krijgt voorrang voor opdrachten waarvoor een beëdigde vertaling vereist is.",
      "iban": "IBAN",
      "ibanName": "IBAN-houder (volledige naam)",
      "languagePairs": "Talenparen",
      "source": "Brontaal",
      "target": "Doeltaal",
      "addPair": "Toevoegen",
      "removePair": "Verwijderen",
      "swap": "Richting omwisselen",
      "expertise": "Vakgebieden",
      "submit": "Aanmelding versturen",
      "submitting": "Versturen…",
      "saved": "Uw gegevens zijn opgeslagen.",
      "saveError": "Opslaan is niet gelukt. Probeer het opnieuw.",
      "required": "Vul de verplichte velden in.",
      "atLeastOnePair": "Voeg ten minste één talenpaar toe."
    },
    "expertiseLabels": {
      "legal": "Juridisch",
      "medical": "Medisch",
      "technical": "Technisch",
      "academic": "Academisch",
      "commercial": "Commercieel",
      "financial": "Financieel",
      "literary": "Literair",
      "official": "Officiële documenten",
      "localization": "Web / Software",
      "general": "Algemeen"
    },
    "pendingTitle": "Uw aanmelding wordt beoordeeld",
    "pendingDesc": "Wij hebben uw vertalersaanmelding ontvangen. Toegang tot het paneel wordt verleend na beoordeling door de beheerder.",
    "rejectedTitle": "Aanmelding niet goedgekeurd",
    "rejectedDesc": "Uw aanmelding is op dit moment niet goedgekeurd. U kunt uw gegevens bijwerken en het opnieuw proberen.",
    "reapply": "Opnieuw proberen",
    "cancelApplication": "Aanmelding annuleren",
    "cancelConfirm": "Weet u zeker dat u uw aanmelding wilt annuleren? Uw gegevens worden verwijderd; u kunt zich later desgewenst opnieuw aanmelden.",
    "panelTitle": "Vertalerspaneel",
    "tabs": {
      "profile": "Mijn profiel",
      "pool": "Vertaalpool",
      "active": "Actieve opdrachten",
      "pending": "In afwachting van goedkeuring",
      "approved": "Goedgekeurd",
      "completed": "Voltooid",
      "wallet": "Portemonnee"
    },
    "soon": "Dit gedeelte komt in de volgende stap beschikbaar.",
    "jobs": {
      "empty": "Er zijn op dit moment geen opdrachten in dit gedeelte.",
      "translator": "Vertaler",
      "sourceFiles": "Brondocumenten",
      "translationFiles": "Geüploade vertaling",
      "tracking": "Tracking",
      "rejectionReason": "Reden van afwijzing",
      "chooseFiles": "Vertaalbestanden kiezen",
      "filesSelected": "bestand(en) geselecteerd",
      "uploadHint": "Upload uw vertaling en, indien nodig, een digitale kopie van de brontekst, en stuur deze vervolgens ter goedkeuring in.",
      "submit": "Ter goedkeuring versturen",
      "sending": "Versturen…",
      "needFiles": "Selecteer ten minste één bestand.",
      "uploadError": "De bestanden konden niet worden geüpload. Probeer het opnieuw.",
      "submittedMsg": "Vertaling ter goedkeuring verstuurd.",
      "actionError": "De actie kon niet worden voltooid. Probeer het opnieuw.",
      "waitingApproval": "Uw vertaling wacht op goedkeuring door het management. Zodra deze is goedgekeurd, verschijnt de leverstap onder “Goedgekeurd”.",
      "trackingPlaceholder": "Trackingnummer / link",
      "needTracking": "Voor bezorging per koerier is een trackingnummer vereist.",
      "markShipped": "Verzonden — voltooien",
      "markDelivered": "Bezorgd — voltooien",
      "completedMsg": "Opdracht voltooid. Uw verdiensten zijn aan uw portemonnee toegevoegd.",
      "reasonPlaceholder": "Bij afwijzing de reden vermelden (zichtbaar voor de vertaler)…",
      "approve": "Goedkeuren",
      "reject": "Afwijzen",
      "needReason": "Vermeld een reden om af te wijzen.",
      "approvedMsg": "Vertaling goedgekeurd.",
      "rejectedMsg": "Vertaling afgewezen; teruggestuurd naar de vertaler.",
      "statusLabel": "Status",
      "status_claimed": "In behandeling",
      "status_submitted": "In afwachting van goedkeuring",
      "status_approved": "Goedgekeurd — leverfase",
      "status_completed": "Voltooid"
    },
    "pool": {
      "loading": "Pool laden…",
      "empty": "Er zijn op dit moment geen openstaande opdrachten die overeenkomen met uw talenparen en vakgebieden.",
      "error": "De pool kon niet worden geladen. Probeer het opnieuw.",
      "orderNo": "Bestelling",
      "service": "Type dienst",
      "documentType": "Documenttype",
      "langPair": "Talenpaar",
      "words": "Woorden",
      "pagesUnit": "pagina's",
      "deadline": "Deadline",
      "daysUnit": "werkdagen",
      "note": "Opmerking van de klant",
      "customerInfo": "Klantgegevens",
      "deliveryInfo": "Klant- en bezorggegevens",
      "customerName": "Volledige naam",
      "customerEmail": "E-mail",
      "customerPhone": "Telefoon",
      "deliveryAddress": "Bezorgadres",
      "text": "Besteltekst",
      "files": "Documenten",
      "earning": "Uw verdiensten voor deze opdracht",
      "urgent": "Spoed",
      "sworn": "Beëdigd",
      "notary": "Notarieel bekrachtigd",
      "apostille": "Apostille",
      "cargo": "Bezorging per koerier",
      "digital": "Digitale levering",
      "claim": "Deze opdracht aannemen",
      "claiming": "Aannemen…",
      "claimed": "U hebt de opdracht succesvol aangenomen.",
      "claimError": "De opdracht kon niet worden aangenomen. Mogelijk is deze al door iemand anders aangenomen; vernieuw de lijst.",
      "ibanRequired": "Voordat u opdrachten kunt aannemen, moeten uw IBAN-gegevens door het management worden geverifieerd. Voer uw IBAN in uw profiel in; zodra deze is geverifieerd, kunt u opdrachten uit de pool aannemen."
    },
    "profile": {
      "statusApproved": "Goedgekeurde vertaler",
      "verifiedIban": "IBAN geverifieerd",
      "unverifiedIban": "IBAN niet geverifieerd",
      "current": "Opgeslagen",
      "edit": "Gegevens opslaan",
      "ibanReminder": "Om uw betalingen te ontvangen, voert u uw IBAN-gegevens in en slaat u deze op. Zodra deze door de beheerder zijn geverifieerd, worden betalingen op deze rekening gedaan.",
      "lockedHint": "Kan na goedkeuring niet worden gewijzigd",
      "revokeTitle": "Deze wijziging trekt uw goedkeuring in",
      "revokeWarning": "Als u uw talenparen, beëdigingsstatus of vakgebieden wijzigt, wordt uw account opnieuw ter beoordeling aan het management voorgelegd (op in afwachting gezet). Uw opdrachten, gegevens en portemonnee blijven BEHOUDEN; zodra u opnieuw bent goedgekeurd, gaat u verder waar u was gebleven.",
      "consent": "Ik heb dit gelezen en ga akkoord",
      "ibanReverify": "U wijzigt uw IBAN. De nieuwe IBAN wordt opnieuw ter beoordeling aan het management voorgelegd; uw account blijft actief, maar u kunt geen nieuwe opdrachten uit de pool aannemen totdat de IBAN is geverifieerd."
    },
    "admin": {
      "title": "Beheerpaneel",
      "translatorsTab": "Vertalers",
      "applicationsTab": "Aanmeldingen",
      "ibanTab": "IBAN-goedkeuringen",
      "ordersTab": "Bestellingen",
      "paymentsTab": "Betalingen",
      "noIbanPending": "Geen vertalers in afwachting van IBAN-goedkeuring.",
      "ibanHint": "Keur hier nieuw ingevoerde of gewijzigde IBAN's goed. Zolang deze niet zijn goedgekeurd, kan de vertaler geen nieuwe opdrachten uit de pool aannemen.",
      "ibanApprove": "IBAN goedkeuren",
      "paymentsHint": "Op de betaaldag (de 1e en de 16e van elke maand): upload voor elke vertaler die u hebt betaald het betalingsbewijs en klik op “Als betaald markeren”. De knop werkt niet zonder betalingsbewijs. Vertalers met een saldo van nul worden hier niet vermeld.",
      "noPayments": "Geen vertalers met een uit te betalen saldo.",
      "paymentAmount": "Uit te betalen bedrag",
      "uploadReceipt": "Betalingsbewijs uploaden",
      "receiptUploaded": "Betalingsbewijs geüpload",
      "receiptRequired": "Upload eerst een betalingsbewijs",
      "uploading": "Uploaden…",
      "markPaid": "Als betaald markeren",
      "paid": "Betaling geregistreerd en de vertaler is met het betalingsbewijs op de hoogte gebracht.",
      "panelHint": "Volg goedgekeurde vertalers per profiel, beoordeel aanmeldingen en beheer de workflow van alle bestellingen.",
      "summary": "{total} vertalers · {pending} aanmeldingen in afwachting",
      "applicationsSummary": "{total} aanmeldingen · {pending} in afwachting van beoordeling",
      "noApproved": "Nog geen goedgekeurde vertalers.",
      "noPending": "Geen aanmeldingen in afwachting.",
      "noMatch": "Geen gegevens komen overeen met de filters.",
      "loadError": "De gegevens konden niet worden geladen. Controleer de database en machtigingen (RLS).",
      "noApplications": "Nog geen vertalersgegevens.",
      "filters": {
        "namePlaceholder": "Zoeken op naam…",
        "country": "Land",
        "city": "Stad / provincie",
        "anyCountry": "Alle landen",
        "anyCity": "Alle steden",
        "cityNeedsCountry": "Selecteer eerst een land",
        "sourceLang": "Brontaal",
        "targetLang": "Doeltaal",
        "anyLang": "Alle",
        "eitherDirection": "Beide richtingen (bron↔doel)",
        "expertise": "Vakgebieden",
        "clear": "Filters wissen",
        "results": "{n} gegevens"
      },
      "orders": {
        "loadError": "De bestellingen konden niet worden geladen. Probeer het opnieuw.",
        "empty": "Nog geen bestellingen.",
        "searchPlaceholder": "Zoeken op bestelnummer of klantnaam…",
        "results": "{n} bestellingen",
        "customer": "Klant",
        "translator": "Vertaler",
        "unassigned": "Niet toegewezen",
        "status": "Status",
        "done": "Voltooid",
        "inProgress": "In behandeling",
        "completedOn": "Voltooid op",
        "placedOn": "Besteldatum",
        "total": "Totaal",
        "statusAvailable": "In pool (niet aangenomen)",
        "statusClaimed": "In vertaling",
        "statusSubmitted": "In afwachting van goedkeuring",
        "statusApproved": "Leverfase",
        "statusCompleted": "Voltooid",
        "statusCancelled": "Geannuleerd"
      },
      "profile": {
        "back": "Terug naar vertalers",
        "adminOnly": "Dit profiel is uitsluitend voor het management; de vertaler kan het niet zien.",
        "infoTitle": "Gegevens",
        "walletTitle": "Portemonnee",
        "jobsTitle": "Opdrachten",
        "noJobs": "Deze vertaler heeft nog geen opdrachten."
      },
      "approve": "Goedkeuren",
      "reject": "Afwijzen",
      "colLangs": "Talenparen",
      "colExpertise": "Vakgebied",
      "colLocation": "Stad / land",
      "swornBadge": "Beëdigd",
      "returningBadge": "Terugkerende vertaler",
      "ibanVerified": "IBAN geverifieerd",
      "ibanNotVerified": "IBAN niet geverifieerd",
      "verifyIban": "IBAN verifiëren",
      "unverifyIban": "Verificatie opheffen",
      "statusPending": "In afwachting",
      "statusApproved": "Goedgekeurd",
      "statusRejected": "Afgewezen",
      "actionError": "De actie kon niet worden voltooid."
    },
    "wallet": {
      "total": "Totale verdiensten",
      "locked": "Vergrendeld",
      "withdrawable": "Opneembaar",
      "paid": "Uitbetaald",
      "payInfo": "Verdiensten worden aan uw portemonnee toegevoegd zodra een opdracht is voltooid; ze blijven 7 dagen vergrendeld en worden daarna opneembaar. Betalingen worden op de 1e en de 16e van elke maand op het opneembare saldo gedaan.",
      "empty": "Nog geen verdiensten. Verdiensten uit voltooide opdrachten verschijnen hier.",
      "entryOrder": "Bestelling",
      "date": "Datum",
      "statusCol": "Status",
      "amount": "Bedrag",
      "statusPaid": "Betaald",
      "statusUnlocked": "Opneembaar",
      "statusPending": "Vergrendeld",
      "loadError": "De portemonnee kon niet worden geladen. Probeer het opnieuw."
    },
    "adminWallet": {
      "firmShare": "Bedrijfsaandeel (incl. btw)",
      "firmShareHint": "Bedrijfsaandeel = totaal van voltooide bestellingen (incl. btw) minus de verdiensten van de vertalers.",
      "ciro": "Totale omzet (incl. btw)",
      "kdv": "Btw (aan de staat)",
      "payouts": "Uitbetaald aan vertalers",
      "net": "Netto bedrijfsresultaat",
      "count": "{n} voltooide bestellingen",
      "empty": "Nog geen voltooide bestellingen.",
      "colOrder": "Bestelling",
      "colTranslator": "Vertaler",
      "colDate": "Datum",
      "colTotal": "Totaal (incl. btw)",
      "colPayout": "Vertaler",
      "colFirm": "Bedrijfsaandeel",
      "loadError": "De portemonnee kon niet worden geladen. Probeer het opnieuw."
    }
  },
  authx: {
    "rememberMe": "Aangemeld blijven",
    "showPassword": "Wachtwoord tonen",
    "hidePassword": "Wachtwoord verbergen",
    "forgot": "Wachtwoord vergeten",
    "forgotTitle": "Wachtwoord opnieuw instellen",
    "forgotDesc": "Voer uw geregistreerde e-mailadres in en wij sturen u een eenmalige link om uw wachtwoord opnieuw in te stellen.",
    "forgotEmail": "E-mail",
    "forgotSubmit": "Herstellink verzenden",
    "forgotSent": "De link is naar uw e-mailadres verzonden. Controleer uw postvak IN (en uw map met ongewenste e-mail).",
    "forgotBack": "Terug naar inloggen",
    "resetTitle": "Nieuw wachtwoord instellen",
    "resetDesc": "Voer uw nieuwe wachtwoord in en bevestig het door het opnieuw te typen.",
    "newPassword": "Nieuw wachtwoord",
    "newPasswordRepeat": "Nieuw wachtwoord (herhalen)",
    "mismatch": "De wachtwoorden komen niet overeen.",
    "weak": "Het wachtwoord moet minimaal 6 tekens lang zijn.",
    "resetSubmit": "Wachtwoord bijwerken",
    "resetSuccess": "Uw wachtwoord is bijgewerkt. U kunt nu inloggen met uw nieuwe wachtwoord.",
    "resetInvalid": "De link is ongeldig of verlopen. Vraag een nieuwe herstellink aan.",
    "goLogin": "Inloggen",
    err: {
      "invalidCredentials": "Onjuist e-mailadres of wachtwoord. Controleer uw gegevens en probeer het opnieuw.",
      "emailNotConfirmed": "Uw e-mailadres is nog niet geverifieerd. Klik op de verificatielink in uw inbox.",
      "alreadyRegistered": "Dit e-mailadres is al geregistreerd. Probeer in te loggen of uw wachtwoord opnieuw in te stellen.",
      "weakPassword": "Het wachtwoord moet minimaal 6 tekens bevatten.",
      "otpInvalid": "De verificatiecode is onjuist of verlopen. Vraag een nieuwe code aan.",
      "rateLimited": "Te veel pogingen. Wacht een moment en probeer het opnieuw.",
      "generic": "Er is iets misgegaan. Probeer het later opnieuw."
    }
  },
  notFound: {
    seo: { title: "Pagina niet gevonden", description: "De pagina die u zoekt, kon niet worden gevonden." },
    title: "Pagina niet gevonden",
    desc: "De pagina die u zoekt, is mogelijk verplaatst of heeft misschien nooit bestaan.",
    home: "Terug naar home",
  },
}
