import type { PartialDictionary } from '@/types/i18n'
import { FAQ_CATEGORIES_ES, FAQ_ITEMS_ES } from '@/content/faq-data.es'

/**
 * ESPAÑOL — traducción completa basada en la versión inglesa.
 * Cadena de reserva: TR (origen) <- EN (base) <- otros idiomas.
 * Las preguntas/respuestas de FAQ (faq.categories / faq.items) provienen de un
 * conjunto de datos propio y específico del idioma (content/faq-data.es).
 */
export const es: PartialDictionary = {
  common: {
    tagline: 'Su socio de confianza en servicios profesionales de traducción.',
    nav: {
      home: 'Inicio',
      services: 'Servicios',
      quote: 'Solicitar presupuesto',
      corporate: 'Empresas',
      partnership: 'Colaboración',
      blog: 'Blog',
      faq: 'Preguntas frecuentes',
      contact: 'Contacto',
    },
    actions: {
      getQuote: 'Solicitar presupuesto',
      calculatePrice: 'Calcular precio',
      uploadDocument: 'Subir documento',
      whatsapp: 'Escribir por WhatsApp',
      learnMore: 'Más información',
      viewAll: 'Ver todo',
      showMore: 'Ver más',
      showLess: 'Ver menos',
      send: 'Enviar',
      apply: 'Solicitar',
      order: 'Realizar pedido',
      contactUs: 'Contáctenos',
      openMenu: 'Abrir menú',
      closeMenu: 'Cerrar menú',
      selectLanguage: 'Seleccionar idioma',
      skipToContent: 'Saltar al contenido',
      login: 'Iniciar sesión',
      logout: 'Cerrar sesión',
      account: 'Mi cuenta',
    },
    states: {
      loading: 'Cargando…',
      error: 'Algo salió mal. Vuelva a intentarlo.',
      required: 'Este campo es obligatorio.',
      demoNotice: 'Demo: los datos del formulario aún no se envían a un servidor.',
      unverified: 'Por verificar',
    },
    topbar: {
      phoneLabel: 'Teléfono',
      emailLabel: 'Correo electrónico',
      hoursLabel: 'Horario de atención',
      afterHours: 'Disponemos de soporte de traducción urgente fuera del horario habitual.',
      workingHours: 'Días laborables 09:00 - 18:00 | Servicio disponible fuera de horario',
    },
  },

  home: {
    seo: {
      title: 'TercümExpert — Servicios profesionales de traducción',
      description:
        'Soluciones de traducción jurada, certificación notarial y traducción corporativa. Suba su documento, obtenga un presupuesto preliminar al instante y una entrega profesional.',
    },
    hero: {
      title: 'Su socio de confianza en servicios profesionales de',
      titleAccent: 'Traducción',
      subtitle: 'Suba su documento, consulte el precio y obtenga una entrega profesional.',
      support: 'Traducción jurada • Certificación notarial • Soluciones para empresas',
    },
    trust: {
      title: '¿Por qué confían en nosotros?',
      items: [
        { key: 'languages', label: '50+ idiomas' },
        { key: 'delivery', label: 'Entrega en 24 horas' },
        { key: 'notary', label: 'Certificación notarial' },
        { key: 'quality', label: 'Control de calidad' },
      ],
    },
    stats: {
      title: 'TercümExpert en cifras',
      note: 'Las cifras que se muestran a continuación no se presentan como afirmaciones definitivas hasta su verificación.',
      labels: {
        satisfaction: 'Satisfacción del cliente',
        completed: 'Trabajos completados',
        languages: 'Idiomas disponibles',
        corporate: 'Clientes corporativos',
      },
    },
    howItWorks: {
      title: '¿Cómo funciona?',
      subtitle: 'Traducción profesional en cinco pasos.',
      steps: [
        { key: 'upload', title: 'Subir', desc: 'Suba su documento de forma segura.' },
        { key: 'select', title: 'Seleccionar', desc: 'Elija el idioma y el tipo de servicio.' },
        { key: 'confirm', title: 'Confirmar', desc: 'Confirme su pedido.' },
        { key: 'track', title: 'Seguir', desc: 'Siga el proceso en tiempo real.' },
        { key: 'receive', title: 'Recibir', desc: 'Reciba su entrega profesional.' },
      ],
    },
    services: {
      title: 'Nuestros servicios',
      subtitle: 'Traducción experta para cada tipo de documento.',
    },
    why: {
      title: '¿Por qué TercümExpert?',
      subtitle: 'Las características que nos distinguen de la competencia',
      features: [
        { key: 'autoQuote', title: 'Cálculo automático del precio', desc: 'Un precio preliminar en segundos.' },
        { key: 'whatsapp', title: 'Presupuesto rápido por WhatsApp', desc: 'Contacto con un solo toque.' },
        { key: 'terminology', title: 'Gestión terminológica', desc: 'Un lenguaje corporativo coherente.' },
        { key: 'revision', title: 'Derecho a revisión', desc: 'Un proceso centrado en la satisfacción.' },
        { key: 'languages', title: 'Soporte de más de 50 idiomas', desc: 'Amplia cobertura de pares de idiomas.' },
        { key: 'terms', title: 'Sistema de pago aplazado para empresas', desc: 'Pago flexible para empresas.' },
      ],
    },
    corporateCta: {
      title: 'Soluciones para empresas',
      desc: 'Servicios lingüísticos profesionales con gestión terminológica, opciones de pago aplazado y un gestor de cuentas dedicado adaptado a su empresa.',
      action: 'Solicitar un presupuesto para empresas',
    },
    partnershipTeaser: {
      title: 'Programa de colaboración',
      subtitle: 'Gane un 20% de comisión por cada cliente que nos recomiende.',
      items: [
        { key: 'commission', title: 'Comisión transparente', desc: '20% de comisión por cada recomendación (sujeto a acuerdo). Ingresos transparentes con un panel de seguimiento en tiempo real.' },
        { key: 'qr', title: 'Sistema de código QR', desc: 'Seguimiento sencillo de clientes con integración en tarjetas de visita. Códigos QR para web y WhatsApp.' },
      ],
      cta: 'Solicitar ser colaborador',
    },
    testimonials: {
      title: 'Opiniones de clientes',
      subtitle: 'Aquí se añadirán opiniones reales de clientes antes del lanzamiento.',
      placeholderNote: 'Marcador de posición — se integrarán opiniones reales.',
      items: [
        { key: 't1', role: 'Bufete de abogados' },
        { key: 't2', role: 'Organización sanitaria' },
        { key: 't3', role: 'Cliente corporativo' },
        { key: 't4', role: 'Cliente particular' },
      ],
    },
    blogTeaser: {
      title: 'Blog',
      subtitle: 'Contenido actual del mundo de la traducción',
      viewAll: 'Ver todas las entradas del blog',
    },
    finalCta: {
      title: 'Comience ahora',
      desc: 'Suba sus documentos, obtenga un presupuesto al instante y benefíciese de servicios profesionales de traducción.',
      primary: 'Solicitar presupuesto',
      secondary: 'Contáctenos',
    },
  },

  services: {
    seo: {
      title: 'Servicios de traducción',
      description:
        'Traducción jurada, con certificación notarial, jurídica, técnica, médica y académica, además de localización web y móvil. Tipos de documentos, proceso, entrega y pares de idiomas.',
    },
    hero: {
      title: 'Servicios de traducción',
      subtitle: 'Traducción con la terminología adecuada para cada campo de especialización.',
    },
    process: {
      title: '¿Cómo funciona el proceso?',
      steps: [
        { title: 'Revisión del documento', desc: 'Se evalúan el tipo de documento y su finalidad.' },
        { title: 'Asignación del experto', desc: 'Se asigna un traductor especializado en el campo.' },
        { title: 'Traducción y edición', desc: 'Traducción y una revisión final independiente.' },
        { title: 'Aprobación y entrega', desc: 'Certificación notarial o apostilla si es necesario, y luego la entrega.' },
      ],
    },
    delivery: {
      title: 'Opciones de entrega',
      items: ['Entrega digital (PDF/DOCX)', 'Entrega física de documentos', 'Entrega urgente'],
    },
    notaryApostille: {
      title: 'Relación entre certificación notarial y apostilla',
      desc: 'Cuando es necesario, la traducción jurada adquiere validez ante instituciones oficiales mediante la certificación notarial y el proceso de apostilla. El requisito exacto depende de la institución ante la que se presente el documento.',
    },
    fullService: {
      title: 'Servicio integral, entregado en su puerta',
      note: 'Envíenos sus documentos y nosotros gestionamos todo el proceso, incluidas la traducción, la certificación notarial y la apostilla. Sus documentos terminados llegan a su puerta por mensajería. Céntrese en su trabajo y déjenos el resto a nosotros.',
    },
    cta: {
      title: '¿No está seguro de qué servicio necesita?',
      desc: 'Suba su documento y le mostraremos el servicio y el precio más adecuados.',
    },
    documentTypesTitle: 'Tipos de documentos adecuados',
  },

  serviceItems: {
    sworn: {
      name: 'Traducción jurada',
      short: 'Traducción con validez oficial con la firma y el sello de un traductor jurado.',
      benefits: ['Válida ante instituciones oficiales', 'Certificación de traductor jurado', 'Proceso rápido'],
    },
    notarized: {
      name: 'Traducción con certificación notarial',
      short: 'Certificación notarial de una traducción jurada.',
      benefits: ['Certificación notarial', 'Apta para trámites oficiales', 'Nos encargamos del proceso'],
    },
    apostille: {
      name: 'Apoyo en el proceso de apostilla',
      short: 'Orientación durante el proceso de apostilla para su validez en el extranjero.',
      benefits: ['Validez internacional', 'Asesoramiento sobre el proceso', 'Orientación institucional'],
    },
    legal: {
      name: 'Traducción jurídica',
      short: 'Traducción con dominio de la terminología para contratos, documentos judiciales y oficiales.',
      benefits: ['Terminología jurídica', 'Garantía de confidencialidad', 'Traductor experto'],
    },
    technical: {
      name: 'Traducción técnica',
      short: 'Traducción coherente para manuales, especificaciones y documentos técnicos.',
      benefits: ['Gestión terminológica', 'Formato conservado', 'Especialización sectorial'],
    },
    medical: {
      name: 'Traducción médica',
      short: 'Traducción precisa para informes, prospectos y documentos médicos.',
      benefits: ['Terminología médica', 'Enfoque en la precisión', 'Confidencialidad'],
    },
    academic: {
      name: 'Traducción académica',
      short: 'Lenguaje académico para tesis, artículos y traducciones de diplomas.',
      benefits: ['Estilo académico', 'Coherencia con el original', 'Entrega puntual'],
    },
    localization: {
      name: 'Localización web y móvil',
      short: 'Localización culturalmente apropiada de sitios web y aplicaciones.',
      benefits: ['Adaptación cultural', 'Integración técnica', 'Compatibilidad con SEO'],
    },
  },

  corporate: {
    statsLabels: {
      corporate: 'Clientes corporativos',
      discount: 'Descuento por pedidos al por mayor',
      term: 'Plazo de pago',
    },
    seo: {
      title: 'Soluciones para empresas',
      description:
        'Servicios lingüísticos profesionales para empresas con gestión terminológica, opciones de pago aplazado, pedidos al por mayor y un gestor de cuentas dedicado.',
    },
    hero: {
      title: 'Soluciones para empresas',
      subtitle:
        'Servicios lingüísticos profesionales con gestión terminológica, opciones de pago aplazado y un gestor de cuentas dedicado adaptado a su empresa.',
      primaryCta: 'Solicitar un presupuesto para empresas',
      secondaryCta: 'Enviar correo electrónico',
    },
    features: {
      title: 'Características para empresas',
      subtitle: 'Soluciones adaptadas a su negocio',
      items: [
        {
          key: 'custom',
          icon: 'Target',
          title: 'Servicio personalizado',
          points: ['Terminología fija', 'Conservación del tono de voz de la marca', 'Gestor de cuentas dedicado', 'Creación de guía de estilo'],
        },
        {
          key: 'volume',
          icon: 'BarChart3',
          title: 'Procesamiento por volumen y pago aplazado',
          points: ['Planes mensuales de traducción', 'Descuentos por pedidos al por mayor', 'Plazos de hasta 30 días', 'Sistema de facturación'],
        },
        {
          key: 'security',
          icon: 'Lock',
          title: 'Privacidad y seguridad',
          points: ['Protocolo NDA', 'Transferencia cifrada de archivos', 'Procesos conformes con la KVKK'],
        },
      ],
    },
    whyPackage: {
      title: '¿Por qué un paquete para empresas?',
      items: [
        {
          key: 'terminology',
          icon: 'Building2',
          title: 'Gestión de terminología fija',
          desc: 'Creamos un banco de términos específico para su empresa. El lenguaje de su marca se conserva en todas las traducciones y garantizamos la coherencia. Nos ocupamos de emplear los mismos términos en cada proyecto.',
        },
        {
          key: 'manager',
          icon: 'Users',
          title: 'Gestor de cuentas dedicado',
          desc: 'Su gestor de cuentas dedicado supervisa todos sus procesos. Con una línea de soporte accesible, estamos a su lado en situaciones urgentes.',
        },
        {
          key: 'security',
          icon: 'ShieldCheck',
          title: 'Privacidad y seguridad',
          desc: 'Trabajamos bajo un protocolo NDA. Sus datos están seguros con una sólida infraestructura de seguridad, transferencia cifrada de archivos y procesos conformes con la KVKK.',
        },
      ],
    },
    payment: {
      title: 'Opciones de pago',
      subtitle: 'Planes de pago flexibles adaptados a su negocio',
      recommendedLabel: 'RECOMENDADO',
      options: [
        {
          key: 'standard',
          label: 'Pago inmediato',
          heading: 'Estándar',
          desc: 'Pago con tarjeta de crédito o transferencia bancaria después de cada pedido',
          points: ['Pago a plazos con tarjeta de crédito', 'Entrega inmediata'],
          recommended: false,
        },
        {
          key: 'term',
          label: 'Pago mensual aplazado',
          heading: '15-30 días',
          desc: 'Facturación mensual consolidada y opción de pago aplazado',
          points: ['Plazo de 30 días', 'Descuento por volumen', 'Informe mensual'],
          recommended: true,
        },
      ],
    },
    form: {
      title: 'Solicitud de paquete para empresas',
      desc: 'Rellene el formulario y nuestro equipo de expertos se pondrá en contacto con usted',
      fields: {
        company: 'Nombre de la empresa',
        contactName: 'Nombre completo de contacto',
        email: 'Correo electrónico',
        phone: 'Teléfono',
        need: 'Cuéntenos sus necesidades de traducción',
        consent: 'He leído y acepto la <kvkk>Cláusula Informativa de la KVKK</kvkk>.',
      },
      submit: 'Enviar solicitud',
      success: 'Hemos recibido su solicitud. Nos pondremos en contacto con usted lo antes posible.',
      note: 'Le responderemos en un plazo de 1 día laborable.',
    },
  },

  partnership: {
    seo: {
      title: 'Programa de colaboración',
      description:
        'Gane comisiones por cada cliente que recomiende. Informes transparentes, recomendaciones mediante código QR y soporte profesional.',
    },
    hero: {
      title: 'Programa de colaboración',
      value: 'Gane un 20% de comisión por cada cliente que nos recomiende.',
      subtitle: 'Un sistema transparente, pagos fiables y una cooperación a largo plazo.',
      cta: 'Solicitar ahora',
    },
    advantages: {
      title: 'Ventajas para colaboradores',
      subtitle: '¿Por qué convertirse en colaborador de TercümExpert?',
      items: [
        { key: 'commission', icon: 'Wallet', title: 'Garantía del 20% de comisión', desc: 'Un sistema de comisiones transparente por cada cliente que recomiende.' },
        { key: 'qr', icon: 'QrCode', title: 'Recomendación por código QR', desc: 'Seguimiento sencillo de clientes con integración en tarjetas de visita.' },
        { key: 'reporting', icon: 'BarChart3', title: 'Informes transparentes', desc: 'Panel de seguimiento de comisiones y clientes en tiempo real.' },
        { key: 'support', icon: 'Users', title: 'Soporte profesional', desc: 'Una línea de soporte para colaboradores y un gestor de cuentas dedicados.' },
      ],
    },
    howItWorks: {
      title: '¿Cómo funciona?',
      steps: [
        { title: 'Solicitar', desc: 'Rellene el formulario de solicitud en línea. Comparta la información de su empresa y sus datos de contacto. Su solicitud se revisa en un plazo de 1 día laborable.' },
        { title: 'Convertirse en colaborador', desc: 'Una vez aprobada su solicitud, obtiene acceso a su panel de colaborador dedicado. Sus códigos QR y enlaces de recomendación quedan listos.' },
        { title: 'Recomendar clientes', desc: 'Recomiéndenos a sus clientes mediante código QR, un enlace personalizado o una tarjeta de visita. Cada recomendación se registra automáticamente en el sistema.' },
        { title: 'Ganar comisiones', desc: 'Gana un 20% de comisión cada vez que un cliente que ha recomendado realiza un pedido. Recibe pagos automáticos cada 15 días.' },
      ],
    },
    sectors: {
      title: 'Sectores objetivo',
      subtitle: '¿Para qué sectores es ideal?',
      items: [
        { key: 'law', icon: 'Scale', title: 'Bufetes de abogados', desc: 'Necesidad de traducción jurada de expedientes, contratos y documentos legales.' },
        { key: 'visa', icon: 'Plane', title: 'Asesorías de visados', desc: 'Documentos que requieren traducción jurada, como pasaportes, diplomas y registros civiles.' },
        { key: 'education', icon: 'GraduationCap', title: 'Asesorías educativas', desc: 'Traducción jurada de documentos de estudiantes y procesos de apostilla.' },
        { key: 'health', icon: 'HeartPulse', title: 'Turismo sanitario', desc: 'Traducción de informes médicos, historiales de pacientes y documentos sanitarios.' },
        { key: 'patent', icon: 'Building2', title: 'Oficinas de patentes/marcas', desc: 'Traducción técnica de patentes, registros de marcas y documentos legales.' },
        { key: 'realestate', icon: 'Home', title: 'Agencias inmobiliarias', desc: 'Traducción de escrituras, contratos y documentos oficiales para inversores extranjeros.' },
        { key: 'hr', icon: 'Briefcase', title: 'Asesorías de RR. HH.', desc: 'Traducción de currículos, diplomas y cartas de referencia para colocación en el extranjero.' },
        { key: 'software', icon: 'Code', title: 'Empresas de software', desc: 'Localización de aplicaciones web y móviles, traducción de documentación técnica.' },
      ],
    },
    commission: {
      title: 'Estructura de comisiones',
      stats: {
        commissionLabel: 'Comisión estándar',
        commissionSub: 'En cada pedido',
        periodUnit: 'Días',
        periodLabel: 'Periodo de pago',
        feeLabel: 'Cuota de alta',
        feeSub: 'Totalmente gratis',
      },
      exampleTitle: 'Cálculo de ingresos de ejemplo',
      exampleOrderLabel: 'Pedido del cliente que ha recomendado',
      exampleRateLabel: 'Tasa de comisión',
      exampleEarningLabel: 'Sus ingresos',
      note: 'Las tasas de comisión y las condiciones están sujetas al acuerdo de colaboración.',
    },
    form: {
      title: 'Formulario de solicitud de colaborador',
      subtitle: 'Rellene el formulario y le responderemos en un plazo de 1 día laborable.',
      fields: {
        company: 'Nombre de la empresa/organización',
        sector: 'Sector',
        contactName: 'Nombre completo de contacto',
        titleRole: 'Cargo',
        email: 'Correo electrónico',
        phone: 'Teléfono',
        potential: 'Su potencial mensual estimado de recomendaciones',
        note: 'Cualquier nota que desee añadir',
        agreement: 'He leído y acepto las condiciones del <partnership>acuerdo de colaboración</partnership>.',
      },
      sectorPlaceholder: 'Seleccionar',
      sectorOptions: ['Bufete de abogados', 'Asesoría de visados', 'Asesoría educativa', 'Turismo sanitario', 'Oficina de patentes/marcas', 'Inmobiliaria', 'Asesoría de RR. HH.', 'Software', 'Otro'],
      potentialOptions: ['1-5 clientes', '5-10 clientes', '10-20 clientes', 'Más de 20 clientes'],
      submit: 'Enviar solicitud',
      success: 'Hemos recibido su solicitud. Nos pondremos en contacto con usted.',
      note: 'Su solicitud se revisará en un plazo de 1 día laborable.',
    },
  },

  quote: {
    seo: {
      title: 'Cálculo de precio al instante',
      description: 'Suba su documento o introduzca los datos y obtenga su presupuesto preliminar al instante.',
    },
    hero: {
      title: 'Cálculo de precio al instante',
      subtitle: 'Suba su documento o introduzca los datos y obtenga un presupuesto preliminar al instante.',
    },
    upload: {
      heading: 'Suba sus documentos',
      privacy: 'Sus datos se tratan de forma confidencial',
      tabFile: 'Subir archivo',
      tabText: 'Introducir texto',
      chooseFile: 'Elija sus documentos',
      formats: 'Se aceptan .docx, .xlsx, .pdf, .pptx, .jpg, .png y más de 50 formatos · Máx. 100MB por archivo',
      dropHint: 'Puede arrastrar y soltar uno o varios archivos en esta zona.',
      textPlaceholder: 'Pegue o escriba su texto aquí…',
      totalWords: 'Recuento total de palabras',
      extracting: 'Contando palabras…',
      wordsUnit: 'palabras',
      remove: 'Eliminar',
      unsupported:
        'No fue posible contar las palabras automáticamente para este tipo de archivo. Pegue el texto mediante "Introducir texto"; nuestro equipo verificará el recuento al elaborar el presupuesto.',
      empty:
        'No se encontró texto seleccionable en el archivo (puede estar escaneado o ser una imagen). Utilice "Introducir texto" o el recuento se verificará durante la elaboración del presupuesto.',
      error: 'No se pudo leer el archivo. Vuelva a intentarlo o utilice "Introducir texto".',
      tooLarge: 'El archivo no puede superar los 100MB.',
      needInput: 'Para obtener un precio, suba un archivo o introduzca texto.',
    },
    fields: {
      upload: 'Subir documento (opcional)',
      uploadHint: 'PDF, DOC, DOCX o TXT — máx. 10 MB',
      sourceLang: 'Idioma de origen',
      targetLang: 'Idioma de destino',
      serviceType: 'Tipo de servicio',
      documentType: 'Tipo de documento',
      wordCount: 'Recuento estimado de palabras',
      wordCountHint: 'Utilice el control deslizante o introduzca el número manualmente.',
      options: 'Opciones adicionales',
      calculate: 'Calcular precio',
    },
    options: {
      urgent: 'Entrega urgente',
      notarization: 'Certificación notarial',
      physicalDelivery: 'Entrega física',
    },
    languages: {
      tr: 'Turco',
      en: 'Inglés',
      de: 'Alemán',
      fr: 'Francés',
      es: 'Español',
      it: 'Italiano',
      ru: 'Ruso',
      ar: 'Árabe',
      nl: 'Neerlandés',
      az: 'Azerí',
      pl: 'Polaco',
      bg: 'Búlgaro',
      pt: 'Portugués',
      da: 'Danés',
    },
    documentTypes: {
      diploma: 'Diploma',
      passport: 'Pasaporte',
      'civil-registry': 'Certificado del registro civil',
      contract: 'Contrato',
      'medical-report': 'Informe médico',
      'technical-doc': 'Documento técnico',
      'court-doc': 'Documento judicial',
      other: 'Otro',
    },
    result: {
      title: 'Presupuesto preliminar',
      basePrice: 'Tarifa base del servicio',
      wordPrice: 'Tarifa por palabra',
      addons: 'Servicios adicionales',
      total: 'Total',
      vat: 'IVA',
      delivery: 'Plazo de entrega estimado',
      deliveryUnit: 'días laborables',
      disclaimer: 'Este es un presupuesto preliminar; el precio final se confirma tras la revisión del documento.',
      order: 'Realizar pedido',
      whatsapp: 'Contactar por WhatsApp',
      estimatedWords: 'Palabras estimadas (automático — demo)',
    },
    orderConfirm: {
      title: 'Hemos recibido su pedido',
      number: 'N.º de pedido',
      desc: 'Su solicitud y sus documentos se han guardado. Nuestro equipo de expertos revisará el documento y se pondrá en contacto con usted lo antes posible.',
      viewOrders: 'Mis pedidos',
      submitting: 'Creando pedido…',
      error: 'Hubo un problema al crear su pedido. Vuelva a intentarlo.',
    },
    gate: {
      title: 'Su precio está listo',
      subtitle: 'Inicie sesión o verifique sus datos para ver el precio y realizar un pedido.',
      loginCta: 'Iniciar sesión / Registrarse',
      or: 'o continúe de forma rápida',
      firstName: 'Nombre',
      lastName: 'Apellidos',
      email: 'Correo electrónico',
      phone: "Número de teléfono",
      sendCode: 'Enviar código de verificación',
      codeLabel: 'Código de verificación',
      codeSentA: 'ha recibido un código de verificación.',
      verify: 'Verificar y ver el precio',
      resend: 'Reenviar código',
      resent: 'Se ha enviado un nuevo código.',
      back: 'Cambiar datos',
      errNames: 'El nombre y los apellidos son obligatorios.',
      errEmail: 'Introduzca un correo electrónico válido.',
      errPhone: "Introduzca un número de teléfono válido.",
      errCode: 'Introduzca el código completo.',
      note: 'Su correo electrónico se utiliza únicamente para el presupuesto y el pedido.',
    },
    note: {
      label: 'Nota sobre su pedido (opcional)',
      placeholder: 'Aquí puede escribir sus solicitudes de entrega, terminología o peticiones especiales.',
    },

    checkout: {
      title: "Detalles de entrega",
      subtitle: "Su documento físico/jurado se enviará a esta dirección.",
      firstName: "Nombre",
      lastName: "Apellidos",
      phone: "Teléfono",
      address: "Dirección completa",
      addressPlaceholder: "Calle, número de edificio y piso…",
      city: "Ciudad",
      postalCode: "Código postal",
      country: "País",
      submit: "Completar pedido",
      submitting: "Creando el pedido…",
      cancel: "Cancelar",
      errRequired: "Por favor, rellene los campos obligatorios.",
      note: "Esta información se utiliza únicamente para la entrega por mensajería.",
    },
  },

  order: {
    seo: {
      title: 'Seguimiento del pedido',
      description: 'Siga el estado de su pedido.',
    },
    numberLabel: 'N.º de pedido',
    placedOn: 'Fecha del pedido',
    estimatedLabel: 'Entrega estimada de la traducción',
    cargoEstimatedLabel: 'Fecha de envío estimada',
    timelineTitle: 'Estado del pedido',
    steps: {
      received: 'Hemos recibido su pedido',
      in_progress: 'En proceso',
      translated: 'Traducción completada',
      shipped: 'Enviado',
      delivered: 'Entregado',
      cancelled: 'Pedido cancelado',
    },
    stepDesc: {
      received: 'Su solicitud y sus documentos han llegado a nuestro sistema. Nuestro equipo de expertos los revisará y comenzará en breve.',
      in_progress: 'Nuestro traductor experto ha comenzado su traducción.',
      translated: 'Su traducción está completa y se han realizado las comprobaciones finales.',
      shipped: 'Su documento se ha entregado a la mensajería; puede seguirlo con el botón de abajo.',
      delivered: 'Su documento se le ha enviado por correo electrónico.',
      cancelled: 'Este pedido se ha cancelado. Si tiene alguna pregunta, contáctenos.',
    },
    cargoReady: 'Su documento se ha enviado. Sígalo con un solo toque:',
    cargoPending: 'El código de seguimiento aparecerá aquí una vez que se envíe su documento.',
    trackCargo: 'Seguir mi envío',
    digitalPending: 'Una vez completada su traducción, sus archivos se le enviarán por correo electrónico.',
    digitalDelivered: 'Su traducción se le ha enviado por correo electrónico. Revise su bandeja de entrada (y la carpeta de spam).',
    detailsTitle: 'Detalles del pedido',
    fields: {
      service: 'Servicio',
      langs: 'Idiomas',
      documentType: 'Tipo de documento',
      words: 'Palabras',
      delivery: 'Plazo estimado',
      total: 'Importe',
      note: 'Su nota',
      deliveryAddress: "Dirección de entrega",
    },
    myOrders: 'Mis pedidos',
    backHome: 'Volver al inicio',
    whatsapp: 'Contactar por WhatsApp',
    loading: 'Cargando pedido…',
    loginRequired: {
      title: 'Inicie sesión para ver su pedido',
      desc: 'Solo puede acceder a los detalles de su pedido tras iniciar sesión con su cuenta.',
      login: 'Iniciar sesión',
    },
    notFound: {
      title: 'Pedido no encontrado',
      desc: 'Este número de pedido no le pertenece o no existe. Compruebe el enlace.',
      home: 'Volver al inicio',
    },
  },

  faq: {
    seo: {
      title: 'Preguntas frecuentes',
      description: 'Preguntas frecuentes sobre traducción jurada, plazo de entrega, precios, certificación notarial y condiciones para empresas.',
    },
    hero: { title: 'Preguntas frecuentes', subtitle: 'La respuesta que busca está aquí.' },
    categoriesTitle: 'Categorías',
    searchPlaceholder: 'Busque preguntas o palabras clave…',
    empty: 'Ninguna pregunta coincidió con su búsqueda. Pruebe con otra palabra o contáctenos.',
    categories: FAQ_CATEGORIES_ES,
    items: FAQ_ITEMS_ES,
    notFound: {
      title: '¿No ha encontrado la respuesta a su pregunta?',
      contact: 'Contáctenos',
      whatsapp: 'Soporte por WhatsApp',
    },
  },

  contact: {
      introTitle: `Bienvenido`,
      introDesc: `Antes de comenzar, ¿podría facilitarme su nombre y su dirección de correo electrónico para poder ayudarle mejor?`,
      start: `Iniciar chat`,
      introError: `Por favor, introduzca su nombre y su dirección de correo electrónico.`,
    seo: {
      title: 'Contacto',
      description: 'Póngase en contacto con TercümExpert: teléfono, correo electrónico, WhatsApp y formulario de contacto.',
    },
    hero: { title: 'Contacto', subtitle: '¿En qué podemos ayudarle?' },
    infoTitle: 'Información de contacto',
    labels: {
      phone: 'Teléfono',
      email: 'Correo electrónico',
      whatsapp: 'WhatsApp',
      address: 'Dirección',
      hours: 'Horario de atención',
    },
    form: {
      title: 'Contáctenos',
      fields: {
        name: 'Nombre completo',
        email: 'Correo electrónico',
        phone: 'Teléfono',
        subject: 'Asunto',
        message: 'Mensaje',
        consent: 'He leído y acepto la <kvkk>Cláusula Informativa de la KVKK</kvkk>.',
      },
      submit: 'Enviar mensaje',
      success: 'Hemos recibido su mensaje. Nos pondremos en contacto con usted en breve.',
    },
    map: {
      title: 'Nuestra ubicación',
      subtitle: 'Encuéntrenos en el mapa',
      placeholder: 'Zona del mapa',
      note: 'El mapa de ubicación se mostrará aquí próximamente.',
    },
  },

  auth: {
    seo: {
      title: 'Iniciar sesión / Registrarse',
      description: 'Inicie sesión en su cuenta de TercümExpert o cree una nueva.',
    },
    tabs: { login: 'Iniciar sesión', register: 'Registrarse' },
    google: 'Continuar con Google',
    or: 'o',
    fields: {
      firstName: 'Nombre',
      lastName: 'Apellidos',
      email: 'Correo electrónico',
      password: 'Contraseña',
      code: 'Código de verificación',
    },
    login: {
      title: 'Inicie sesión en su cuenta',
      submit: 'Iniciar sesión',
      noAccount: '¿No tiene una cuenta?',
      switchToRegister: 'Regístrese',
    },
    register: {
      title: 'Cree una cuenta nueva',
      submit: 'Registrarse',
      haveAccount: '¿Ya tiene una cuenta?',
      switchToLogin: 'Inicie sesión',
      consent: 'Al crear una cuenta, acepto la <kvkk>Cláusula Informativa de la KVKK</kvkk> y la <privacy>Política de Privacidad</privacy>.',
    },
    verify: {
      title: 'Verifique su correo electrónico',
      desc: '— introduzca el código de 6 dígitos que enviamos a esta dirección.',
      submit: 'Verificar y continuar',
      spam: 'El código puede tardar unos minutos; revise también su carpeta de spam o correo no deseado.',
      resend: 'Reenviar código',
      resent: 'Se ha enviado un nuevo código.',
      back: 'Volver',
    },
    signedIn: {
      title: 'Mi cuenta',
      greeting: 'Bienvenido',
      logout: 'Cerrar sesión',
    },
    orders: {
      title: 'Mis pedidos',
      empty: 'Todavía no tiene pedidos. Puede crear su primer pedido desde Calcular precio.',
      loading: 'Cargando pedidos…',
      error: 'No se pudieron cargar los pedidos. Actualice la página.',
      status: {
        received: 'Recibido',
        in_progress: 'En proceso',
        translated: 'Traducción completada',
        shipped: 'Enviado',
        delivered: 'Entregado',
        cancelled: 'Cancelado',
      },
      track: 'Seguir',
    },
    errors: {
      nameRequired: 'El nombre y los apellidos son obligatorios.',
      emailInvalid: 'Introduzca un correo electrónico válido.',
      passwordShort: 'La contraseña debe tener al menos 6 caracteres.',
      codeInvalid: 'Introduzca el código de 6 dígitos.',
      consentRequired: 'Es necesaria la aceptación para continuar.',
    },
  },

  blog: {
    seo: { title: 'Blog', description: 'Contenido guía sobre traducción, certificación notarial, apostilla y localización.' },
    hero: { title: 'Blog', subtitle: 'Guías del mundo de la traducción.' },
    searchPlaceholder: 'Buscar entradas…',
    readingTime: 'min de lectura',
    relatedTitle: 'Entradas relacionadas',
    allCategories: 'Todas',
    empty: 'Ninguna entrada coincidió con este criterio.',
  },

  legal: {
    lastUpdatedLabel: `Última actualización`,
    draftNotice: `En el siguiente texto, los campos indicados entre corchetes ([...]) se completarán con los datos de su empresa. Los textos tienen carácter meramente informativo y se recomienda que sean revisados por un profesional del derecho antes de su publicación.`,
    kvkk: {
      seo: { title: `Aviso de Información sobre la KVKK`, description: `Aviso de información relativo al tratamiento de sus datos personales en el marco de la Ley n.º 6698 (KVKK).` },
      title: `Aviso de Información sobre la KVKK`,
      sections: [
        { heading: `Responsable del Tratamiento`, body: `De conformidad con la Ley n.º 6698 de Protección de Datos Personales (“KVKK”), sus datos personales son tratados por [ŞİRKET ÜNVANI] (“TercümExpert”), en calidad de responsable del tratamiento, con el alcance que se describe a continuación. Dirección: [ADRES]. Correo electrónico: [E-POSTA]. Teléfono: [TELEFON].` },
        { heading: `Datos Personales Tratados`, body: `Se tratan sus datos de identidad y de contacto (nombre, apellidos, dirección de correo electrónico, número de teléfono), sus datos de dirección de entrega, sus datos de pedidos y transacciones, los datos contenidos en los documentos que nos remite con fines de traducción, así como los datos de seguridad de las transacciones relativos a su uso del sitio (dirección IP, registros de sesión y de cookies).` },
        { heading: `Finalidades del Tratamiento`, body: `Sus datos personales se tratan con el fin de prestar los servicios relacionados con la traducción, la traducción jurada y la certificación notarial y de apostilla, elaborar presupuestos y gestionar los pedidos, mantener las relaciones con los clientes y gestionar las solicitudes y reclamaciones, cumplir las obligaciones contractuales y legales, y garantizar la seguridad del servicio.` },
        { heading: `Fundamentos Jurídicos del Tratamiento`, body: `Sus datos se tratan sobre la base de los siguientes fundamentos jurídicos: la necesidad para la celebración o ejecución de un contrato, el cumplimiento de nuestras obligaciones legales, el establecimiento y la defensa de un derecho, y nuestros intereses legítimos, siempre que no se lesionen sus derechos y libertades fundamentales; y, cuando resulte necesario, sobre la base de su consentimiento expreso (KVKK m.5 y m.6).` },
        { heading: `Método de Recogida`, body: `Sus datos personales se recogen por medios electrónicos a través de los formularios del sitio web, los procesos de registro y de pedido, el correo electrónico y otros canales de comunicación.` },
        { heading: `Transferencia de los Datos Personales`, body: `En la medida en que lo exija el servicio, sus datos podrán transferirse a nuestros proveedores situados en el territorio nacional y en el extranjero de los que recibimos servicios de alojamiento, infraestructura, autenticación, correo electrónico y analítica, así como a los organismos e instituciones públicas competentes, con arreglo a las condiciones establecidas en los artículos KVKK m.8 y m.9. Dado que los servidores de algunos de los proveedores de infraestructura y de servicios que utilizamos se encuentran en el extranjero, sus datos podrán transferirse al exterior en el marco de las garantías previstas por la legislación.` },
        { heading: `Plazos de Conservación`, body: `Sus datos personales se conservarán durante el tiempo que exija la finalidad del tratamiento y durante los plazos de prescripción y de conservación previstos en la legislación aplicable (como la normativa fiscal, mercantil y de consumo); una vez vencidos dichos plazos, se suprimirán, se destruirán o se anonimizarán.` },
        { heading: `Derechos del Interesado`, body: `De conformidad con el artículo KVKK m.11, usted tiene derecho a: conocer si sus datos personales están siendo tratados; solicitar información al respecto si lo están; conocer la finalidad del tratamiento y si se utilizan conforme a dicha finalidad; conocer los terceros a los que se han transferido en el territorio nacional o en el extranjero; solicitar su rectificación si se han tratado de forma incompleta o incorrecta; solicitar su supresión o destrucción cuando concurran los requisitos; solicitar que estas operaciones se notifiquen a los terceros a los que se hayan transferido; oponerse a que se produzca un resultado en su contra derivado del análisis exclusivamente por medios automatizados; y solicitar la reparación del daño en caso de que sufra un perjuicio.` },
        { heading: `Método de Solicitud`, body: `Podrá dirigir las solicitudes relativas a sus derechos por escrito a la dirección [E-POSTA] o a la dirección [ADRES], de conformidad con el “Veri Sorumlusuna Başvuru Usul ve Esasları Hakkında Tebliğ”. Su solicitud se resolverá a la mayor brevedad posible, según su naturaleza, y en un plazo máximo de treinta días.` },
      ],
    },
    privacy: {
      seo: { title: `Política de Privacidad`, description: `Nuestra política relativa a la confidencialidad de sus datos personales y de sus documentos.` },
      title: `Política de Privacidad`,
      sections: [
        { heading: `Introducción`, body: `En TercümExpert concedemos gran importancia a su privacidad. La presente Política de Privacidad explica qué información recogemos, con qué finalidades y cómo la protegemos en los servicios que ofrecemos a través de [WEB ADRESİ]. Puede consultar información detallada sobre el tratamiento de datos personales en el Aviso de Información sobre la KVKK.` },
        { heading: `Información que Recogemos`, body: `Podemos recoger sus datos de cuenta y de contacto (nombre, apellidos, correo electrónico, teléfono), los datos de pedido y de entrega, los documentos que nos remite para su traducción y su contenido, los datos de las transacciones relativas al pago y los datos técnicos relativos a su uso del sitio (dirección IP, información del navegador, registros de cookies).` },
        { heading: `Finalidades de Uso de la Información`, body: `Utilizamos su información para prestar los servicios, gestionar los presupuestos y los pedidos, comunicarnos con usted, cumplir nuestras obligaciones legales y mejorar la calidad y la seguridad del servicio. Tratamos sus documentos únicamente en la medida en que lo exija el servicio que usted solicite.` },
        { heading: `Confidencialidad de los Documentos`, body: `Los documentos objeto de traducción se consideran confidenciales. A dichos documentos solo acceden, durante el tiempo que exija el trabajo, el traductor y el personal autorizados que ejecutan el servicio correspondiente; sus documentos no se comparten con terceros para fines ajenos a la prestación del servicio.` },
        { heading: `Proveedores de Servicios de Terceros`, body: `Para prestar nuestros servicios recurrimos a proveedores de terceros de confianza en los ámbitos del alojamiento y la infraestructura, la autenticación, el envío de correo electrónico, la analítica y (cuando esté activado) el pago. Estos proveedores solo pueden acceder a sus datos con el fin de prestar el servicio que se les ha encomendado y bajo obligaciones contractuales de confidencialidad; los servidores de algunos de ellos pueden encontrarse en el extranjero.` },
        { heading: `Seguridad de los Datos`, body: `Para proteger sus datos frente a accesos no autorizados, aplicamos el cifrado en la transmisión, restricciones de acceso y las medidas administrativas y técnicas adecuadas. Si bien ningún método garantiza una seguridad absoluta, adoptamos medidas razonables y actualizadas para proteger sus datos.` },
        { heading: `Cookies`, body: `En nuestro sitio se utilizan cookies y tecnologías similares. Para obtener información detallada sobre sus tipos y la gestión de preferencias, puede consultar la Política de Cookies.` },
        { heading: `Sus Derechos`, body: `Puede ejercer los derechos que le reconoce la KVKK, incluidos los de acceso, rectificación y supresión de sus datos personales. Para sus solicitudes, puede ponerse en contacto con nosotros a través de la dirección [E-POSTA].` },
        { heading: `Privacidad de los Menores`, body: `Nuestros servicios no están dirigidos a personas menores de 18 años y no recogemos conscientemente datos personales de menores.` },
        { heading: `Modificaciones`, body: `La presente política podrá actualizarse periódicamente. La versión vigente se publicará siempre en esta página; en caso de cambios significativos, se informará por los medios adecuados.` },
        { heading: `Contacto`, body: `Para cualquier consulta relacionada con la privacidad: Correo electrónico: [E-POSTA] · Teléfono: [TELEFON] · Dirección: [ADRES].` },
      ],
    },
    distanceSales: {
      seo: { title: `Contrato de Venta a Distancia`, description: `Contrato de venta a distancia relativo a la venta de servicios en el marco de la Ley n.º 6502.` },
      title: `Contrato de Venta a Distancia`,
      sections: [
        { heading: `Partes`, body: `El presente Contrato de Venta a Distancia (“Contrato”) se celebra por medios electrónicos entre, de una parte, [ŞİRKET ÜNVANI] (“Vendedor”; dirección: [ADRES], correo electrónico: [E-POSTA], teléfono: [TELEFON]) y, de otra parte, el consumidor que realiza el pedido (“Comprador”), de conformidad con la Ley n.º 6502 de Protección del Consumidor y con el Mesafeli Sözleşmeler Yönetmeliği.` },
        { heading: `Objeto del Contrato`, body: `El objeto del Contrato es la prestación de los servicios relacionados con la traducción, la traducción jurada y la certificación notarial y de apostilla que el Comprador ha pedido por medios electrónicos a través de [WEB ADRESİ], cuyas características y precio de venta se indican en el resumen del pedido.` },
        { heading: `Características y Precio del Servicio`, body: `El tipo, el alcance, la forma de entrega (digital o por mensajería) y el precio total, impuestos incluidos, del servicio pedido se muestran claramente al Comprador durante la realización del pedido y constan en la confirmación del pedido. El precio se calcula en función del servicio seleccionado y de las características del documento.` },
        { heading: `Pago`, body: `El pago se efectúa mediante los métodos de pago ofrecidos en el paso del pedido. El pedido se tramita tras la confirmación del pago.` },
        { heading: `Ejecución y Entrega`, body: `En las entregas digitales, la traducción se remite, una vez finalizada, a través de la cuenta o del correo electrónico del Comprador. En el caso de documentos físicos, con firma manuscrita o jurados, la entrega se realiza por mensajería a la dirección indicada por el Comprador. Los plazos estimados de entrega se indican durante la realización del pedido; pueden variar en función del volumen de documentación y de los procesos de certificación.` },
        { heading: `Derecho de Desistimiento`, body: `Por regla general, en los contratos relativos a la prestación de servicios, el Comprador dispone del derecho a desistir, sin necesidad de justificación alguna, en el plazo de catorce (14) días contados desde la fecha de celebración del contrato. No obstante, quedan a salvo las excepciones que se indican a continuación.` },
        { heading: `Excepciones al Derecho de Desistimiento`, body: `De conformidad con el artículo m.15 del Mesafeli Sözleşmeler Yönetmeliği, no podrá ejercerse el derecho de desistimiento en el caso de los servicios cuya ejecución se haya iniciado con el consentimiento del Comprador y hayan finalizado antes de que expire el plazo de desistimiento, así como en el caso de los bienes y servicios preparados especialmente conforme a las solicitudes o necesidades personales del Comprador (incluidos los servicios de traducción y certificación preparados a medida de la persona o del documento). Las solicitudes de cancelación remitidas antes de iniciarse el trabajo de traducción se valorarán de forma independiente.` },
        { heading: `Cancelación y Devolución`, body: `En los pedidos cuya ejecución no se haya iniciado, las solicitudes de cancelación pueden remitirse a través de [E-POSTA]; las devoluciones que se consideren procedentes se efectúan mediante el mismo método con el que se realizó el pago, en un plazo razonable. En los servicios a medida cuya ejecución se haya iniciado o finalizado, la devolución puede no ser posible por la propia naturaleza del trabajo.` },
        { heading: `Resolución de Controversias`, body: `En las controversias que puedan derivarse del presente Contrato, son competentes, dentro de los límites cuantitativos anunciados cada año por el Ticaret Bakanlığı, los Tüketici Hakem Heyetleri y los Juzgados de Consumo del lugar de residencia del Comprador o del lugar en que se haya realizado la transacción.` },
        { heading: `Entrada en Vigor`, body: `Al confirmar el pedido, el Comprador declara haber leído y aceptado todas las condiciones del presente Contrato. El Contrato entra en vigor con la confirmación del pedido.` },
      ],
    },
    cookies: {
      seo: { title: `Política de Cookies`, description: `Información sobre las cookies utilizadas en nuestro sitio y la gestión de preferencias.` },
      title: `Política de Cookies`,
      sections: [
        { heading: `¿Qué es una Cookie?`, body: `Las cookies son pequeños archivos de texto que se almacenan en su navegador cuando visita un sitio web. Se utilizan para hacer el sitio más seguro y funcional, recordar sus preferencias y obtener estadísticas de uso.` },
        { heading: `¿Por qué Utilizamos Cookies?`, body: `Utilizamos las cookies para garantizar las funciones básicas del sitio, preservar la seguridad de la sesión, medir el rendimiento y, en función de su consentimiento, mejorar nuestros servicios y llevar a cabo actividades de marketing.` },
        { heading: `Categorías de Cookies`, body: `Las cookies obligatorias son necesarias para el funcionamiento y la seguridad del sitio y no pueden desactivarse. Las cookies de rendimiento y analíticas nos ayudan a comprender la interacción de los visitantes. Las cookies de marketing contribuyen a ofrecer contenidos y anuncios adecuados a sus intereses. Las cookies de preferencias recuerdan sus elecciones, como el idioma. Las cookies analíticas y de marketing solo funcionan con su consentimiento expreso.` },
        { heading: `Cookies de Terceros`, body: `Con fines analíticos y de marketing, podemos recurrir a servicios de terceros (por ejemplo, herramientas de estadística de visitantes y de medición de publicidad). Estos servicios pueden instalar sus propias cookies y tratar los datos con arreglo a sus propias políticas de privacidad.` },
        { heading: `Gestión de las Preferencias de Cookies`, body: `Puede otorgar o modificar en cualquier momento sus preferencias relativas a las cookies no obligatorias a través de la herramienta de preferencias de cookies disponible en el sitio. Asimismo, puede suprimir o bloquear las cookies desde la configuración de su navegador; no obstante, en tal caso algunas secciones del sitio podrían no funcionar correctamente.` },
        { heading: `Plazos de Conservación`, body: `Las cookies se conservan, según su tipo, durante la sesión o durante un período determinado. Las cookies de sesión se suprimen al cerrar el navegador; las cookies persistentes expiran al término del período establecido o cuando usted las suprime.` },
        { heading: `Modificaciones`, body: `La presente Política de Cookies podrá actualizarse periódicamente. La versión vigente se publicará siempre en esta página.` },
      ],
    },
    partnership: {
      seo: { title: `Contrato de Colaboración Comercial`, description: `Condiciones del programa de colaboración comercial (partner) de TercümExpert.` },
      title: `Contrato de Colaboración Comercial`,
      sections: [
        { heading: `Partes y Objeto`, body: `El presente Contrato de Colaboración Comercial se celebra entre, por una parte, [ŞİRKET ÜNVANI] (“TercümExpert”) y, por otra parte, el colaborador que se adhiere al programa (“Colaborador”), con la finalidad de regular los términos y condiciones del programa de colaboración comercial (de recomendación) de TercümExpert.` },
        { heading: `Ámbito del Programa`, body: `El Colaborador remite clientes a TercümExpert a través de su propia red y de sus canales. En caso de que el cliente remitido adquiera un servicio a través de TercümExpert, el Colaborador tendrá derecho a la comisión establecida en el presente Contrato.` },
        { heading: `Comisión`, body: `El Colaborador tendrá derecho a una comisión equivalente al %20 sobre el importe del servicio abonado por el cliente remitido, por cada recomendación válida y aprobada. La tasa de comisión y sus condiciones podrán ser actualizadas por TercümExpert previa notificación. Las operaciones canceladas, reembolsadas o cuyo pago no se haya completado no serán consideradas a efectos del cálculo de la comisión.` },
        { heading: `Seguimiento y Devengo`, body: `Las recomendaciones se vincularán mediante el enlace de seguimiento facilitado al Colaborador, el código QR o el método que TercümExpert determine. El derecho a la comisión únicamente se devengará respecto de las operaciones correctamente vinculadas a través de dichos métodos y cuyo pago se haya completado.` },
        { heading: `Pago`, body: `Las comisiones devengadas se abonarán en la cuenta indicada por el Colaborador. El período y las condiciones de pago se determinarán por separado entre las partes. Las obligaciones fiscales relativas al pago quedan sujetas a la normativa vigente.` },
        { heading: `Obligaciones del Colaborador`, body: `El Colaborador se compromete a utilizar información veraz y no engañosa en sus actividades promocionales, a abstenerse de conductas que perjudiquen la marca y la reputación de TercümExpert y a cumplir con la normativa vigente.` },
        { heading: `Conductas Prohibidas`, body: `Quedan prohibidos el envío de spam y de mensajes masivos no solicitados, la publicidad engañosa, así como las conductas que generen competencia desleal mediante recomendaciones falsas o autorreferidas. Tales conductas constituyen causa de cancelación de la comisión y de resolución del Contrato.` },
        { heading: `Uso de la Marca`, body: `El Colaborador podrá utilizar la marca, el logotipo y los materiales promocionales de TercümExpert únicamente con la autorización escrita de TercümExpert y conforme a las directrices que esta facilite.` },
        { heading: `Confidencialidad`, body: `Las partes se comprometen a proteger la información confidencial obtenida en el marco del presente Contrato y a utilizarla exclusivamente con la finalidad del programa.` },
        { heading: `Parte Independiente`, body: `El Colaborador es una parte independiente; no es empleado, representante ni agente de TercümExpert y no podrá asumir compromisos frente a terceros en nombre de TercümExpert.` },
        { heading: `Duración y Resolución`, body: `El Contrato permanecerá en vigor hasta que una de las partes notifique su resolución. TercümExpert podrá resolver el Contrato de forma inmediata en caso de incumplimiento de las obligaciones; en tal supuesto, no se abonarán las comisiones derivadas de recomendaciones irregulares.` },
        { heading: `Controversias y Legislación Aplicable`, body: `El presente Contrato se rige por el derecho de la Türkiye Cumhuriyeti. El Colaborador, al aprobar su solicitud, declara haber leído y aceptado los términos del Contrato.` },
      ],
    },
  },

  admin: {
    title: `Registros de conversaciones`,
    summary: `{total} conversaciones · {leads} solicitudes de contacto`,
    onlyLeads: `Solo solicitudes de contacto`,
    loading: `Cargando registros…`,
    error: `No se pudieron leer los registros. Compruebe si la tabla de Supabase y los permisos (RLS) están configurados.`,
    empty: `Aún no hay registros.`,
    selectHint: `Seleccione una conversación de la izquierda para visualizarla.`,
    contactRequest: `Solicitud de contacto`,
    contactInfo: `Información de contacto`,
    fieldName: `Nombre`,
    fieldEmail: `Correo electrónico`,
    fieldPhone: `Teléfono`,
    fieldMessage: `Mensaje`,
    requestBadge: `solicitud`,
    noMessages: `Este registro no contiene mensajes (solo una solicitud de contacto).`,
    loginTitle: `Inicio de sesión requerido`,
    loginDesc: `Inicie sesión con una cuenta de administrador para visualizar esta página.`,
    login: `Iniciar sesión`,
    noAccessTitle: `No tiene permiso de acceso`,
    noAccessDesc: `Esta página está disponible únicamente para los administradores.`,
    loadingAuth: `Cargando…`,
  },
  footer: {
    tagline: 'Su socio de confianza en servicios profesionales de traducción.',
    columns: {
      quickLinks: 'Enlaces rápidos',
      services: 'Servicios',
      contact: 'Contacto',
    },
    quickLinks: {
      corporate: 'Empresas',
      services: 'Nuestros servicios',
      quote: 'Calcular precio',
      blog: 'Blog',
      faq: 'Preguntas frecuentes',
      contact: 'Contacto',
    },
    serviceLinks: {
      sworn: 'Traducción jurada',
      notarized: 'Traducción con certificación notarial',
      apostille: 'Proceso de apostilla',
      corporate: 'Soluciones para empresas',
      partnership: 'Programa de colaboración',
    },
    legal: {
      kvkk: 'KVKK',
      privacy: 'Política de Privacidad',
      distanceSales: 'Contrato de Venta a Distancia',
      cookies: 'Política de Cookies',
    },
    socialTitle: 'Síganos',
    whatsapp: 'Soporte por WhatsApp',
    rights: 'Todos los derechos reservados.',
  },

  cookie: {
    title: 'Preferencias de cookies',
    desc: 'Utilizamos cookies para mejorar su experiencia. Las cookies distintas de las necesarias solo se activan con su consentimiento.',
    accept: 'Aceptar',
    reject: 'Rechazar',
    manage: 'Gestionar preferencias',
    save: 'Guardar preferencias',
    categories: {
      necessary: { label: 'Necesarias', desc: 'Imprescindibles para el funcionamiento del sitio; no se pueden desactivar.' },
      analytics: { label: 'Analíticas', desc: 'Nos ayudan a comprender el uso.' },
      marketing: { label: 'Marketing', desc: 'Para contenido y anuncios relevantes.' },
      preferences: { label: 'Preferencias', desc: 'Recuerda sus preferencias.' },
    },
  },

  chatbot: {
    attach: {
      button: 'Adjuntar archivo',
      tooLarge: 'El archivo es demasiado grande (máx. 25 MB).',
      unsupported: 'No puedo analizar archivos de audio o vídeo en el chat. Puede subirlos en la página de presupuesto.',
      cannotRead: 'No pude leer este archivo. Puede subirlo en la página de presupuesto o probar con otro formato.',
      reading: 'Leyendo el archivo…',
      remove: 'Quitar',
    },
    nudge: '¿En qué puedo ayudarle?',
    title: 'Soporte de TercümExpert',
    open: 'Abrir chat',
    close: 'Cerrar chat',
    minimize: 'Minimizar',
    clear: 'Borrar conversación',
    inputPlaceholder: 'Escriba su mensaje…',
    send: 'Enviar',
    typing: 'Escribiendo…',
    welcome:
      'Hola y bienvenido a TercümExpert. Puedo ayudarle con traducción, precios, certificación notarial, apostilla o servicios para empresas.',
    quickQuestions: [
      '¿Cómo se calcula el precio?',
      '¿Qué es la traducción jurada?',
      'Quiero subir un documento',
      'Quiero un presupuesto para empresas',
      '¿Es necesaria la certificación notarial?',
      'Póngame en contacto con un representante',
    ],
    handoff: 'Conectar con un representante',
    toWhatsapp: 'Transferir a WhatsApp',
    disclaimer: 'Esta información es general; confirme los requisitos exactos con la institución correspondiente.',
    sensitiveWarning:
      'No comparta datos personales sensibles a través de este chat. Puede enviar sus documentos mediante la zona de carga segura.',
    answers: [
      `El precio se calcula en función del número de palabras del documento, la combinación de idiomas, el tipo de servicio (traducción jurada, certificación notarial, apostilla) y el plazo de entrega. Para obtener un presupuesto estimado al instante, puede subir su documento o introducir los datos en la página Calcular Precio.`,
      `La traducción jurada es una traducción oficial realizada por un traductor jurado y validada con su firma y sello. Las entidades oficiales suelen exigir traducciones juradas; cuando sea necesario, también puede añadirse la certificación notarial.`,
      `Puede enviarnos su documento a través del área de carga segura de la página Calcular Precio. Una vez subido, verá el presupuesto estimado al instante y podrá completar su pedido.`,
      `Para sus necesidades corporativas, ofrecemos precios especiales y entrega prioritaria en traducciones periódicas y de gran volumen. Para más detalles, puede consultar nuestra página Corporativa o ponerse en contacto con nosotros.`,
      `La necesidad de certificación notarial depende de la entidad a la que vaya a presentar el documento y del tipo de trámite. Algunos trámites aceptan únicamente la traducción jurada, mientras que otros también requieren certificación notarial. Si tiene dudas, permítanos ayudarle.`,
      `Le ponemos en contacto de inmediato con uno de nuestros representantes de atención al cliente. Puede escribirnos a través de WhatsApp mediante el botón que aparece a continuación.`,
    ],
    fallback: `Uno de nuestros representantes de atención al cliente podrá ofrecerle la ayuda más adecuada para su consulta. Puede escribirnos a través de WhatsApp mediante el botón que aparece a continuación; su mensaje se enviará ya redactado.`,
    contact: {
      whatsapp: `WhatsApp`,
      email: `Correo electrónico`,
      phone: `Teléfono`,
      leaveInfo: `Dejar mis datos de contacto`,
      formTitle: `Póngase en contacto con nosotros`,
      formDesc: `Deje sus datos y nuestro equipo se pondrá en contacto con usted lo antes posible.`,
      name: `Su nombre`,
      emailField: `Correo electrónico`,
      phoneField: `Teléfono`,
      message: `Su mensaje (opcional)`,
      submit: `Enviar`,
      submitting: `Enviando…`,
      thanks: `Gracias, nuestro equipo se pondrá en contacto con usted lo antes posible.`,
      errorRequired: `Introduzca un correo electrónico o un teléfono.`,
      back: `Atrás`,
    },
  },

  notFound: {
    seo: { title: 'Página no encontrada', description: 'No se pudo encontrar la página que busca.' },
    title: 'Página no encontrada',
    desc: 'Es posible que la página que busca se haya movido o que nunca haya existido.',
    home: 'Volver al inicio',
  },
}
