/**
 * TÜRKÇE — tam içerik (Şartname §10: TR tam içerik). Bu sözlük, `Dictionary`
 * tipinin KAYNAĞIDIR (typeof); diğer diller bunun DeepPartial'ıdır ve fallback'le
 * tamamlanır. Metinler JSX'e gömülmez; buradan yönetilir (§4).
 */
import { FAQ_CATEGORIES, FAQ_ITEMS } from '@/content/faq-data'

export const tr = {
  common: {
    brand: 'TercümExpert',
    tagline: 'Profesyonel çeviri hizmetlerinde güvenilir çözüm ortağınız.',
    nav: {
      home: 'Anasayfa',
      services: 'Hizmetler',
      quote: 'Fiyat Hesapla',
      corporate: 'Kurumsal',
      partnership: 'İş Ortaklığı',
      blog: 'Blog',
      faq: 'S.S.S.',
      contact: 'İletişim',
    },
    actions: {
      getQuote: 'Hemen Teklif Al',
      calculatePrice: 'Fiyat Hesapla',
      uploadDocument: 'Belge Yükle',
      whatsapp: "WhatsApp'tan Yaz",
      learnMore: 'Detaylı Bilgi',
      viewAll: 'Tümünü Gör',
      showMore: 'Daha Fazla Göster',
      showLess: 'Daha Az Göster',
      send: 'Gönder',
      apply: 'Başvur',
      order: 'Sipariş Ver',
      contactUs: 'İletişime Geçin',
      openMenu: 'Menüyü aç',
      closeMenu: 'Menüyü kapat',
      selectLanguage: 'Dil seçin',
      skipToContent: 'İçeriğe geç',
      login: 'Giriş Yap',
      logout: 'Çıkış Yap',
      account: 'Hesabım',
      mainMenu: "Ana menü",
      menu: "Menü",
      mobileMenu: "Mobil menü",
      countryCode: "Ülke kodu",
    },
    states: {
      loading: 'Yükleniyor…',
      error: 'Bir sorun oluştu. Lütfen tekrar deneyin.',
      required: 'Bu alan zorunludur.',
      demoNotice: 'Demo: Form verileri henüz sunucuya gönderilmemektedir.',
      unverified: 'Doğrulanacak',
    },
    topbar: {
      phoneLabel: 'Telefon',
      emailLabel: 'E-posta',
      hoursLabel: 'Çalışma Saatleri',
      afterHours: 'Mesai dışı acil çeviri desteği mevcuttur.',
      workingHours: 'Hafta İçi 09:00 - 18:00 | Mesai dışı hizmet mevcuttur',
    },
  },

  home: {

    whatsappMsg: "Merhaba, çeviri hizmeti hakkında bilgi almak istiyorum.",
    seo: {
      title: 'TercümExpert — Profesyonel Çeviri Hizmetleri',
      description:
        'Yeminli tercüme, noter onayı ve kurumsal çeviri çözümleri. Belgenizi yükleyin, anında ön fiyat teklifini alın, profesyonel teslimat alın.',
    },
    hero: {
      title: 'Profesyonel Çeviri Hizmetlerinde',
      titleAccent: 'Güvenilir Çözüm Ortağınız',
      subtitle: 'Belgenizi yükleyin, fiyatı görün, profesyonel teslimat alın.',
      support: 'Yeminli tercüme • Noter onayı • Kurumsal çözümler',
    },
    trust: {
      title: 'Neden bize güveniyorlar?',
      items: [
        { key: 'languages', label: '50+ Dil Desteği' },
        { key: 'delivery', label: '24 Saat Teslimat' },
        { key: 'notary', label: 'Noter Onayı' },
        { key: 'quality', label: 'Kalite Güvencesi' },
      ],
    },
    stats: {
      title: 'Rakamlarla TercümExpert',
      note: 'Aşağıdaki değerler doğrulanana kadar kesin iddia olarak sunulmaz.',
      labels: {
        satisfaction: 'Müşteri Memnuniyeti',
        completed: 'Tamamlanan İş',
        languages: 'Dil Desteği',
        corporate: 'Kurumsal Müşteri',
      },
    },
    howItWorks: {
      title: 'Nasıl çalışır?',
      subtitle: 'Beş adımda profesyonel çeviri.',
      steps: [
        { key: 'upload', title: 'Yükle', desc: 'Belgeni güvenle yükle.' },
        { key: 'select', title: 'Seç', desc: 'Dil ve hizmet türünü seç.' },
        { key: 'confirm', title: 'Onayla', desc: 'Siparişi onayla.' },
        { key: 'track', title: 'Takip Et', desc: 'Süreci anlık takip et.' },
        { key: 'receive', title: 'Teslim Al', desc: 'Profesyonel teslimatını al.' },
      ],
    },
    services: {
      title: 'Hizmetlerimiz',
      subtitle: 'Her belge türü için uzman çeviri.',
    },
    why: {
      title: 'Neden TercümExpert?',
      subtitle: 'Rakiplerimizden bizi ayıran özellikler',
      features: [
        { key: 'autoQuote', title: 'Otomatik fiyat hesaplama', desc: 'Saniyeler içinde ön fiyat.' },
        { key: 'whatsapp', title: 'WhatsApp hızlı teklif', desc: 'Tek dokunuşla iletişim.' },
        { key: 'terminology', title: 'Terminoloji yönetimi', desc: 'Tutarlı, kurumsal dil.' },
        { key: 'revision', title: 'Revize hakkı', desc: 'Memnuniyet odaklı süreç.' },
        { key: 'languages', title: '50+ dil desteği', desc: 'Geniş dil çifti kapsamı.' },
        { key: 'terms', title: 'Kurumsal vade sistemi', desc: 'Şirketlere esnek ödeme.' },
      ],
    },
    corporateCta: {
      title: 'Kurumsal Çözümler',
      desc: 'Şirketinize özel terminoloji yönetimi, vade seçenekleri ve özel hesap yöneticisi ile profesyonel dil hizmetleri.',
      action: 'Kurumsal Teklif İste',
    },
    partnershipTeaser: {
      title: 'İş Ortaklığı Programı',
      subtitle: 'Bize yönlendirdiğiniz her müşteriden %20 komisyon kazanın.',
      items: [
        { key: 'commission', title: 'Şeffaf Komisyon', desc: 'Her yönlendirme için %20 komisyon (sözleşmeye tabidir). Anlık takip paneli ile şeffaf kazanç.' },
        { key: 'qr', title: 'QR Kodlu Sistem', desc: 'Kartvizit entegrasyonu ile kolay müşteri takibi. Web ve WhatsApp QR kodları.' },
      ],
      cta: 'Partner Başvurusu Yap',
    },
    testimonials: {
      title: 'Müşteri Değerlendirmeleri',
      subtitle: 'Gerçek müşteri yorumları yayın öncesi buraya eklenecek.',
      placeholderNote: 'Yer tutucu — gerçek yorumlar entegre edilecek.',
      items: [
        { key: 't1', role: 'Hukuk Bürosu' },
        { key: 't2', role: 'Sağlık Kuruluşu' },
        { key: 't3', role: 'Kurumsal Müşteri' },
        { key: 't4', role: 'Bireysel Müşteri' },
      ],
    },
    blogTeaser: {
      title: 'Blog',
      subtitle: 'Çeviri dünyasından güncel içerikler',
      viewAll: 'Tüm Blog Yazılarını Gör',
      empty: 'Blog içeriklerimiz çok yakında burada olacak. Takipte kalın.',
    },
    finalCta: {
      title: 'Hemen Başlayın',
      desc: 'Belgelerinizi yükleyin, anında fiyat teklifi alın ve profesyonel tercüme hizmetinden yararlanın.',
      primary: 'Hemen Teklif Al',
      secondary: 'İletişime Geçin',
    },
  },

  services: {
    seo: {
      title: 'Çeviri Hizmetleri',
      description:
        'Yeminli, noter onaylı, hukuki, teknik, medikal ve akademik çeviri ile web/mobil lokalizasyon. Belge türleri, süreç, teslim ve dil çiftleri.',
    },
    hero: {
      title: 'Çeviri Hizmetleri',
      subtitle: 'Uzmanlık alanına göre, doğru terminolojiyle çeviri.',
    },
    process: {
      title: 'Süreç nasıl işler?',
      steps: [
        { title: 'Belge incelemesi', desc: 'Belge türü ve amaç değerlendirilir.' },
        { title: 'Uzman eşleştirme', desc: 'Alanın uzmanı çevirmene atanır.' },
        { title: 'Çeviri & editör', desc: 'Çeviri ve bağımsız son okuma.' },
        { title: 'Onay & teslim', desc: 'Gerekliyse noter onayı, sonra teslim.' },
      ],
    },
    delivery: {
      title: 'Teslim seçenekleri',
      items: ['Dijital teslimat (PDF/DOCX)', 'Fiziksel belge teslimatı', 'Acil teslimat'],
    },
    notaryApostille: {
      title: 'Noter ve apostil ilişkisi',
      desc: 'Yeminli çeviri, gerektiğinde noter onayıyla resmî kurumlarda geçerli hâle getirilebilir; noter onayı sürecini sizin adınıza yürütebiliriz. Apostil işlemini biz yürütmeyiz; apostil, yetkili makamdan bizzat alınır ve biz yalnızca apostilli/resmî belgelerinizin çevirisini yaparız. Kesin gereklilik, belgenin sunulacağı kuruma göre değişir.',
    },
    fullService: {
      title: 'Kapınıza Kadar Anahtar Teslim',
      note: 'Belgelerinizi bize iletin; çeviri ve gerektiğinde noter onayı sürecini biz yönetelim. Hazır belgeleriniz kapınıza kadar kargoyla gelsin. Siz işinize odaklanın, gerisini bize bırakın.',
    },
    cta: {
      title: 'Hangi hizmete ihtiyacınız olduğundan emin değil misiniz?',
      desc: 'Belgenizi yükleyin, size en uygun hizmeti ve fiyatı gösterelim.',
    },
    documentTypesTitle: 'Uygun belge türleri',
  },

  /** Hizmet kalemleri — id'ler config/services ile eşleşir. */
  serviceItems: {
    sworn: {
      name: 'Yeminli Tercüme',
      short: 'Yeminli çevirmen imzası ve kaşesiyle resmî geçerli çeviri.',
      benefits: ['Resmî kurumlarda geçerli', 'Yeminli çevirmen onayı', 'Hızlı süreç'],
    },
    notarized: {
      name: 'Noter Onaylı Tercüme',
      short: 'Yeminli çevirinin noter tarafından onaylanması.',
      benefits: ['Noter tasdiki', 'Resmî başvurulara uygun', 'Süreç yönetimi bizde'],
    },
    legal: {
      name: 'Hukuki Çeviri',
      short: 'Sözleşme, mahkeme ve resmî belgelerde terminolojiye hâkim çeviri.',
      benefits: ['Hukuk terminolojisi', 'Gizlilik güvencesi', 'Uzman çevirmen'],
    },
    technical: {
      name: 'Teknik Çeviri',
      short: 'Kılavuz, şartname ve teknik dokümanlarda tutarlı çeviri.',
      benefits: ['Terminoloji yönetimi', 'Format korunur', 'Sektör uzmanlığı'],
    },
    medical: {
      name: 'Medikal Çeviri',
      short: 'Rapor, prospektüs ve tıbbi belgelerde hassas çeviri.',
      benefits: ['Tıbbi terminoloji', 'Doğruluk odaklı', 'Gizlilik'],
    },
    academic: {
      name: 'Akademik Çeviri',
      short: 'Tez, makale ve diploma çevirilerinde akademik dil.',
      benefits: ['Akademik üslup', 'Kaynak tutarlılığı', 'Zamanında teslim'],
    },
    localization: {
      name: 'Web ve Mobil Lokalizasyon',
      short: 'Web sitesi ve uygulamaların kültüre uygun yerelleştirilmesi.',
      benefits: ['Kültürel uyum', 'Teknik entegrasyon', 'SEO uyumu'],
    },
  },

  corporate: {

    formErrors: {

      company: "Şirket adı zorunludur.",

      contactName: "Yetkili adı zorunludur.",

      email: "Geçerli bir e-posta girin.",

      need: "Lütfen ihtiyacınızı kısaca açıklayın (en az 10 karakter).",

      consent: "Devam etmek için onay gereklidir.",

    },
    statsLabels: {
      corporate: 'Kurumsal müşteri',
      discount: 'Toplu sipariş indirimi',
      term: 'Ödeme vadesi',
    },
    seo: {
      title: 'Kurumsal Çözümler',
      description:
        'Şirketlere özel terminoloji yönetimi, vade seçenekleri, toplu sipariş ve hesap yöneticisi ile profesyonel dil hizmetleri.',
    },
    hero: {
      title: 'Kurumsal Çözümler',
      subtitle:
        'Şirketinize özel terminoloji yönetimi, vade seçenekleri ve özel hesap yöneticisi ile profesyonel dil hizmetleri.',
      primaryCta: 'Kurumsal Teklif İste',
      secondaryCta: 'E-posta Gönder',
    },
    features: {
      title: 'Kurumsal Özellikler',
      subtitle: 'İşinize özel çözümler',
      items: [
        {
          key: 'custom',
          icon: 'Target',
          title: 'Özelleştirilmiş Hizmet',
          points: ['Sabit terminoloji', 'Marka dil tonunu koruma', 'Özel hesap yöneticisi', 'Stil kılavuzu oluşturma'],
        },
        {
          key: 'volume',
          icon: 'BarChart3',
          title: 'Toplu İşlem ve Vade',
          points: ['Aylık çeviri planları', 'Toplu sipariş indirimleri', '30 güne kadar vade', 'Fatura sistemi'],
        },
        {
          key: 'security',
          icon: 'Lock',
          title: 'Gizlilik ve Güvenlik',
          points: ['NDA protokolü', 'Şifreli dosya transferi', 'KVKK uyumlu süreçler'],
        },
      ],
    },
    whyPackage: {
      title: 'Neden Kurumsal Paket?',
      items: [
        {
          key: 'terminology',
          icon: 'Building2',
          title: 'Sabit Terminoloji Yönetimi',
          desc: 'Şirketinize özel terim bankası oluşturuyoruz. Tüm çevirilerde marka diliniz korunur, tutarlılık sağlarız. Her projede aynı terimlerin kullanılmasına özen gösteririz.',
        },
        {
          key: 'manager',
          icon: 'Users',
          title: 'Özel Hesap Yöneticisi',
          desc: 'Size özel atanan hesap yöneticiniz tüm süreçlerinizi takip eder. Erişilebilir destek hattı ile acil durumlarınızda yanınızdayız.',
        },
        {
          key: 'security',
          icon: 'ShieldCheck',
          title: 'Gizlilik ve Güvenlik',
          desc: 'NDA protokolü ile çalışıyoruz. Güçlü güvenlik altyapısı, şifreli dosya transferi ve KVKK uyumlu süreçler ile verileriniz güvende.',
        },
      ],
    },
    payment: {
      title: 'Ödeme Seçenekleri',
      subtitle: 'İşletmenize uygun esnek ödeme planları',
      recommendedLabel: 'ÖNERİLEN',
      options: [
        {
          key: 'standard',
          label: 'Anlık Ödeme',
          heading: 'Standart',
          desc: 'Her sipariş sonrası kredi kartı veya havale ile ödeme',
          points: ['Kredi kartı taksit', 'Anında teslimat'],
          recommended: false,
        },
        {
          key: 'term',
          label: 'Aylık Vade',
          heading: '15-30 Gün',
          desc: 'Aylık toplu faturalama ve vade seçeneği',
          points: ['30 gün vade', 'Toplu indirim', 'Aylık rapor'],
          recommended: true,
        },
      ],
    },
    form: {
      title: 'Kurumsal Paket Başvurusu',
      desc: 'Formu doldurun, uzman ekibimiz sizinle iletişime geçsin',
      fields: {
        company: 'Şirket Adı',
        contactName: 'Yetkili Adı Soyadı',
        email: 'E-posta',
        phone: 'Telefon',
        need: 'Çeviri ihtiyacınız hakkında bilgi verin',
        consent: '<kvkk>KVKK Aydınlatma Metni</kvkk>’ni okudum ve onaylıyorum.',
      },
      submit: 'Başvuru Gönder',
      success: 'Başvurunuz alındı. En kısa sürede dönüş yapacağız.',
      note: '1 iş günü içinde size geri dönüş yapacağız.',
    },
  },

  partnership: {
    seo: {
      title: 'İş Ortaklığı Programı',
      description:
        'Yönlendirdiğiniz her müşteriden komisyon kazanın. Şeffaf raporlama, QR kodlu yönlendirme ve profesyonel destek.',
    },
    hero: {
      title: 'İş Ortaklığı Programı',
      value: 'Bize yönlendirdiğiniz her müşteriden %20 komisyon kazanın.',
      subtitle: 'Şeffaf sistem, güvenilir ödemeler, uzun vadeli iş birliği.',
      cta: 'Hemen Başvur',
    },
    advantages: {
      title: 'Partner Avantajları',
      subtitle: 'Neden TercümExpert partneri olmalısınız?',
      items: [
        { key: 'commission', icon: 'Wallet', title: '%20 Komisyon Garantisi', desc: 'Her yönlendirdiğiniz müşteriden şeffaf komisyon sistemi.' },
        { key: 'qr', icon: 'QrCode', title: 'QR Kodlu Yönlendirme', desc: 'Kartvizit entegrasyonu ile kolay müşteri takibi.' },
        { key: 'reporting', icon: 'BarChart3', title: 'Şeffaf Raporlama', desc: 'Anlık komisyon ve müşteri takip paneli.' },
        { key: 'support', icon: 'Users', title: 'Profesyonel Destek', desc: 'Özel partner destek hattı ve hesap yöneticisi.' },
      ],
    },
    howItWorks: {
      title: 'Nasıl Çalışır?',
      steps: [
        { title: 'Başvuru Yapın', desc: 'Online başvuru formunu doldurun. Şirket bilgileriniz ve iletişim detaylarınızı paylaşın. 1 iş günü içinde başvurunuz değerlendirilir.' },
        { title: 'Partner Olun', desc: 'Başvurunuz onaylandıktan sonra özel partner panelinize erişim kazanırsınız. QR kodlarınız ve yönlendirme linkleriniz hazır olur.' },
        { title: 'Müşteri Yönlendirin', desc: 'QR kod, özel link veya kartvizit yoluyla müşterilerinizi bize yönlendirin. Her yönlendirme otomatik olarak sisteme kaydedilir.' },
        { title: 'Komisyon Kazanın', desc: 'Yönlendirdiğiniz müşteri her sipariş verdiğinde %20 komisyon kazanırsınız. Her 15 günde bir otomatik ödeme alırsınız.' },
      ],
    },
    sectors: {
      title: 'Hedef Sektörler',
      subtitle: 'Hangi sektörler için ideal?',
      items: [
        { key: 'law', icon: 'Scale', title: 'Hukuk Büroları', desc: 'Dava dosyaları, sözleşmeler ve hukuki belgelerde yeminli tercüme ihtiyacı.' },
        { key: 'visa', icon: 'Plane', title: 'Vize Danışmanlık', desc: 'Pasaport, diploma, nüfus belgesi gibi yeminli tercüme gerektiren evraklar.' },
        { key: 'education', icon: 'GraduationCap', title: 'Eğitim Danışmanlık', desc: 'Öğrenci belgelerinin ve apostilli evrakların yeminli tercümesi.' },
        { key: 'health', icon: 'HeartPulse', title: 'Sağlık Turizmi', desc: 'Tıbbi raporlar, hasta dosyaları ve sağlık belgelerinin çevirisi.' },
        { key: 'patent', icon: 'Building2', title: 'Patent/Marka Ofisleri', desc: 'Patent, marka tescili ve hukuki belgelerin teknik çevirisi.' },
        { key: 'realestate', icon: 'Home', title: 'Emlak Ofisleri', desc: 'Yabancı yatırımcılar için tapu, sözleşme ve resmi evrak çevirisi.' },
        { key: 'hr', icon: 'Briefcase', title: 'İK Danışmanlık', desc: 'Yurtdışı işe yerleştirmede CV, diploma ve referans mektubu çevirisi.' },
        { key: 'software', icon: 'Code', title: 'Yazılım Şirketleri', desc: 'Web ve mobil uygulama lokalizasyonu, teknik doküman çevirisi.' },
      ],
    },
    commission: {
      title: 'Komisyon Yapısı',
      stats: {
        commissionLabel: 'Standart Komisyon',
        commissionSub: 'Her siparişten',
        periodUnit: 'Gün',
        periodLabel: 'Ödeme periyodu',
        feeLabel: 'Başlangıç Ücreti',
        feeSub: 'Tamamen ücretsiz',
      },
      exampleTitle: 'Örnek Kazanç Hesabı',
      exampleOrderLabel: 'Yönlendirdiğiniz müşteri siparişi',
      exampleRateLabel: 'Komisyon oranı',
      exampleEarningLabel: 'Sizin kazancınız',
      note: 'Komisyon oran ve koşulları partner sözleşmesine tabidir.',
    },
    form: {
      title: 'Partner Başvuru Formu',
      subtitle: 'Formu doldurun, 1 iş günü içinde geri dönüş yapalım.',
      fields: {
        company: 'Şirket/Kurum Adı',
        sector: 'Sektör',
        contactName: 'Yetkili Adı Soyadı',
        titleRole: 'Ünvan',
        email: 'E-posta',
        phone: 'Telefon',
        potential: 'Aylık tahmini yönlendirme potansiyeliniz',
        note: 'Eklemek istediğiniz notlar',
        agreement: '<partnership>Partner sözleşmesi</partnership> şartlarını okudum ve kabul ediyorum.',
      },
      sectorPlaceholder: 'Seçiniz',
      sectorOptions: ['Hukuk Bürosu', 'Vize Danışmanlık', 'Eğitim Danışmanlık', 'Sağlık Turizmi', 'Patent/Marka Ofisi', 'Emlak', 'İK Danışmanlık', 'Yazılım', 'Diğer'],
      potentialOptions: ['1-5 müşteri', '5-10 müşteri', '10-20 müşteri', '20+ müşteri'],
      submit: 'Başvuruyu Gönder',
      success: 'Başvurunuz alındı. Sizinle iletişime geçeceğiz.',
      note: 'Başvurunuz 1 iş günü içinde değerlendirilecektir.',
    },
  },

  quote: {

    whatsappMsg: "Merhaba, fiyat teklifi hakkında bilgi almak istiyorum.",
    cancelPolicy: "Bilgilendirme: Siparişiniz, bir tercüman tarafından işleme alınana kadar sipariş sayfanızdan iptal edilebilir ve ödemeniz iade edilir. Bir tercüman işi üstlendikten sonra iptal mümkün değildir.",
    seo: {
      title: 'Anında Fiyat Hesaplama',
      description: 'Belgenizi yükleyin veya detayları girin, anında ön fiyat teklifinizi alın.',
    },
    hero: {
      title: 'Anında Fiyat Hesaplama',
      subtitle: 'Belgeni yükle veya detayları gir, anında ön fiyat teklifini al.',
    },
    upload: {
      heading: 'Belgelerinizi Yükleyin',
      privacy: 'Verileriniz gizli tutulmaktadır',
      tabFile: 'Dosya Yükle',
      tabText: 'Metin Gir',
      chooseFile: 'Belgelerinizi Seçin',
      formats: ".docx, .xlsx, .pdf, .pptx, .jpg, .png ve 50'den fazla format kabul edilir · Dosya başına maks. 100MB",
      dropHint: 'Bir veya birden fazla dosyayı bu alana sürükleyip bırakabilirsiniz.',
      textPlaceholder: 'Metninizi buraya yapıştırın veya yazın…',
      totalWords: 'Toplam kelime sayısı',
      extracting: 'Kelimeler sayılıyor…',
      wordsUnit: 'kelime',
      remove: 'Kaldır',
      unsupported:
        'Bu dosya türünden otomatik kelime sayımı yapılamadı. Lütfen "Metin Gir" ile metni yapıştırın; sayı teklif sırasında ekibimizce doğrulanır.',
      empty:
        'Dosyada seçilebilir metin bulunamadı (taranmış/görsel olabilir). Lütfen "Metin Gir" kullanın veya sayı teklif sırasında doğrulanacaktır.',
      error: 'Dosya okunamadı. Lütfen tekrar deneyin veya "Metin Gir" kullanın.',
      tooLarge: "Dosya 100MB'den büyük olamaz.",
      needInput: 'Fiyat için lütfen bir dosya yükleyin veya metin girin.',
    },
    fields: {
      upload: 'Belge Yükle (opsiyonel)',
      uploadHint: 'PDF, DOC, DOCX veya TXT — en fazla 10 MB',
      sourceLang: 'Kaynak Dil',
      targetLang: 'Hedef Dil',
      serviceType: 'Hizmet Türü',
      documentType: 'Belge Türü',
      wordCount: 'Tahmini Kelime Sayısı',
      wordCountHint: 'Kaydırıcıyı kullanın veya sayıyı elle girin.',
      options: 'Ek seçenekler',
      calculate: 'Fiyat Hesapla',
    },
    options: {
      urgent: 'Acil Teslimat',
      sworn: 'Yeminli Tercüme',
      notarization: 'Noter Onayı',
      physicalDelivery: 'Fiziksel Teslimat',
      swornNotaryHint: 'Noter onayı, yeminli tercümeyi kapsar; ihtiyacınıza uygun olan tek seçeneği işaretlemeniz yeterlidir.',
      physicalRequiredHint: 'Yeminli ve noter onaylı çeviriler imzalı/kaşeli asıl nüsha olarak teslim edildiğinden fiziksel teslimat otomatik eklenir.',
    },
    areas: {
      academic: 'Akademik Çeviri',
      legal: 'Hukuki Çeviri',
      official: 'Resmi Belge Çevirisi',
      medical: 'Medikal Çeviri',
      technical: 'Teknik Çeviri',
      commercial: 'Ticari & Finansal Çeviri',
      localization: 'Web & Mobil Lokalizasyon',
      literary: 'Edebi Çeviri',
      general: 'Genel / Diğer Çeviri',
    },
    docTypes: {
      diploma: 'Diploma',
      transcript: 'Transkript',
      'student-certificate': 'Öğrenci Belgesi',
      'diploma-supplement': 'Diploma Eki',
      thesis: 'Tez',
      'reference-letter': 'Referans Mektubu',
      'academic-article': 'Akademik Makale',
      contract: 'Sözleşme',
      'court-decision': 'Mahkeme Kararı',
      'power-of-attorney': 'Vekaletname',
      petition: 'Dilekçe',
      'consent-statement': 'Muvafakatname',
      'warning-notice': 'İhtarname',
      'litigation-doc': 'Dava Belgeleri',
      passport: 'Pasaport',
      'id-card': 'Kimlik Kartı',
      'civil-registry': 'Nüfus Kayıt Örneği',
      'birth-certificate': 'Doğum Belgesi',
      'marriage-certificate': 'Evlilik Cüzdanı',
      'driver-license': 'Sürücü Belgesi',
      'criminal-record': 'Adli Sicil Kaydı',
      'military-status': 'Askerlik Durum Belgesi',
      apostille: "Apostil Belgesi",
      'medical-report': 'Medikal Rapor',
      epicrisis: 'Epikriz (Hasta Çıkış Özeti)',
      prescription: 'Reçete',
      'lab-result': 'Tahlil / Laboratuvar Sonucu',
      'medical-article': 'Tıbbi Makale',
      'patient-consent': 'Hasta Onam Formu',
      'user-manual': 'Kullanım Kılavuzu',
      'technical-spec': 'Teknik Şartname',
      patent: 'Patent',
      'product-catalog': 'Ürün Kataloğu',
      datasheet: 'Veri Sayfası',
      'installation-guide': 'Kurulum Kılavuzu',
      'safety-data-sheet': 'Güvenlik Bilgi Formu',
      invoice: 'Fatura',
      'balance-sheet': 'Bilanço',
      'commercial-contract': 'Ticari Sözleşme',
      'financial-report': 'Finansal Rapor',
      'tax-document': 'Vergi Belgesi',
      'activity-certificate': 'Faaliyet Belgesi',
      'bank-statement': 'Banka Ekstresi',
      website: 'Web Sitesi',
      'mobile-app': 'Mobil Uygulama',
      'software-ui': 'Yazılım Arayüzü',
      game: 'Oyun',
      'marketing-content': 'Pazarlama İçeriği',
      subtitle: 'Altyazı',
      'e-commerce': 'E-ticaret İçeriği',
      book: 'Kitap',
      'short-story': 'Öykü',
      poem: 'Şiir',
      screenplay: 'Senaryo',
      essay: 'Deneme',
      article: 'Makale',
      'general-document': 'Genel Belge',
      correspondence: 'Yazışma / Mektup',
      cv: 'Özgeçmiş (CV)',
      presentation: 'Sunum',
      other: 'Diğer',
    },
    languages: {
      tr: 'Türkçe',
      en: 'İngilizce',
      de: 'Almanca',
      fr: 'Fransızca',
      es: 'İspanyolca',
      it: 'İtalyanca',
      ru: 'Rusça',
      ar: 'Arapça',
      nl: 'Felemenkçe',
      az: 'Azerice',
      pl: 'Lehçe',
      bg: 'Bulgarca',
      pt: 'Portekizce',
      da: 'Danca',
    },
    documentTypes: {
      diploma: 'Diploma',
      passport: 'Pasaport',
      'civil-registry': 'Nüfus Kayıt Örneği',
      contract: 'Sözleşme',
      'medical-report': 'Medikal Rapor',
      'technical-doc': 'Teknik Doküman',
      'court-doc': 'Mahkeme Belgesi',
      other: 'Diğer',
    },
    result: {
      title: 'Ön Fiyat Teklifi',
      basePrice: 'Temel hizmet bedeli',
      wordPrice: 'Kelime bedeli',
      addons: 'Ek hizmetler',
      total: 'Toplam',
      vat: 'KDV',
      delivery: 'Tahmini teslim süresi',
      deliveryUnit: 'iş günü',
      disclaimer: 'Bu bir ön fiyat teklifidir; nihai fiyat belge incelemesi sonrası netleşir.',
      order: 'Sipariş Ver',
      whatsapp: "WhatsApp'tan İletişime Geç",
      estimatedWords: 'Tahmini kelime (otomatik — demo)',
    },
    orderConfirm: {
      title: 'Siparişiniz alındı',
      number: 'Sipariş No',
      desc: 'Talebiniz ve belgeleriniz kaydedildi. Uzman ekibimiz belgeyi inceleyip en kısa sürede sizinle iletişime geçecek.',
      viewOrders: 'Siparişlerim',
      submitting: 'Sipariş oluşturuluyor…',
      error: 'Sipariş oluşturulurken bir sorun oldu. Lütfen tekrar deneyin.',
    },
    gate: {
      title: 'Fiyatınız hazır',
      subtitle: 'Fiyatı görmek ve sipariş vermek için giriş yapın ya da bilgilerinizi doğrulayın.',
      loginCta: 'Giriş Yap / Üye Ol',
      or: 'veya hızlı devam edin',
      firstName: 'Ad',
      lastName: 'Soyad',
      email: 'E-posta',
      phone: 'Telefon numarası',
      sendCode: 'Doğrulama Kodu Gönder',
      codeLabel: 'Doğrulama Kodu',
      codeSentA: 'adresine bir doğrulama kodu gönderdik.',
      verify: 'Doğrula ve Fiyatı Gör',
      resend: 'Kodu yeniden gönder',
      resent: 'Yeni kod gönderildi.',
      back: 'Bilgileri değiştir',
      errNames: 'Ad ve soyad zorunludur.',
      errEmail: 'Geçerli bir e-posta girin.',
      errPhone: 'Geçerli bir telefon numarası girin.',
      errCode: 'Lütfen kodu eksiksiz girin.',
      note: 'E-postanız yalnızca fiyat teklifi ve sipariş için kullanılır.',
    },
    note: {
      label: 'Siparişinizle ilgili not (isteğe bağlı)',
      placeholder: 'Teslimat, terminoloji veya özel isteklerinizi buraya yazabilirsiniz.',
    },
    checkout: {
      title: 'Teslimat Bilgileri',
      subtitle: 'Fiziksel/yeminli belgeniz bu adrese kargoyla teslim edilecektir.',
      firstName: 'Ad',
      lastName: 'Soyad',
      phone: 'Telefon',
      address: 'Açık Adres',
      addressPlaceholder: 'Mahalle, cadde/sokak, bina ve daire no…',
      city: 'Şehir / İl',
      postalCode: 'Posta Kodu',
      country: 'Ülke',
      selectCountry: 'Ülke seçin',
      selectCity: 'Şehir / eyalet seçin',
      cityNeedsCountry: 'Önce ülke seçin',
      submit: 'Siparişi Tamamla',
      submitting: 'Sipariş oluşturuluyor…',
      cancel: 'Vazgeç',
      errRequired: 'Lütfen zorunlu alanları doldurun.',
      note: 'Bu bilgiler yalnızca kargo teslimatı için kullanılır.',
    },
  },

  order: {

    whatsappMsg: "Merhaba, #{no} numaralı siparişim hakkında bilgi almak istiyorum.",
    cancel: {
      eligible: "Siparişiniz henüz havuzda; bir tercüman işi üstlenene kadar iptal edebilir ve ödemenizin iadesini alabilirsiniz.",
      button: "Siparişi iptal et",
      error: "Sipariş iptal edilemedi. Muhtemelen bir tercüman işi bu sırada üstlendi. Lütfen sayfayı yenileyin.",
      confirmTitle: "Siparişi iptal et",
      confirmDesc: "Bu siparişi iptal etmek istediğinize emin misiniz? Bu işlem geri alınamaz; ödemeniz iade edilir.",
      keep: "Vazgeç",
      confirmYes: "Evet, iptal et",
      canceling: "İptal ediliyor…",
    },
    seo: {
      title: 'Sipariş Takibi',
      description: 'Siparişinizin durumunu takip edin.',
    },
    numberLabel: 'Sipariş No',
    placedOn: 'Sipariş tarihi',
    estimatedLabel: 'Tahmini çeviri teslimi',
    cargoEstimatedLabel: 'Tahmini kargo tarihi',
    timelineTitle: 'Sipariş durumu',
    steps: {
      received: 'Siparişiniz alındı',
      in_progress: 'İşleme alındı',
      translated: 'Çeviri tamamlandı',
      shipped: 'Kargoya verildi',
      delivered: 'Teslim edildi',
      cancelled: 'Sipariş iptal edildi',
    },
    stepDesc: {
      received: 'Talebiniz ve belgeleriniz sistemimize ulaştı. Uzman ekibimiz en kısa sürede inceleyip işleme alacak.',
      in_progress: 'Uzman tercümanımız çevirinize başladı.',
      translated: 'Çeviriniz tamamlandı ve son kontrolleri yapıldı.',
      shipped: 'Belgeniz kargoya teslim edildi; aşağıdaki butondan takip edebilirsiniz.',
      delivered: 'Belgeniz e-posta ile tarafınıza iletildi.',
      cancelled: 'Bu sipariş iptal edilmiştir. Sorularınız için bizimle iletişime geçebilirsiniz.',
    },
    cargoReady: 'Belgeniz kargoya verildi. Tek tuşla takip edebilirsiniz:',
    cargoPending: 'Kargo takip kodu, belgeniz kargoya verildiğinde burada görünecek.',
    trackCargo: 'Kargonu Takip Et',
    trackingCodeLabel: 'Kargo takip numarası',
    digitalPending: 'Çeviriniz tamamlandığında dosyalarınız e-posta ile tarafınıza iletilecek.',
    digitalDelivered: 'Çeviriniz e-posta ile tarafınıza iletildi. Gelen kutunuzu (ve spam klasörünü) kontrol edin.',
    detailsTitle: 'Sipariş detayları',
    fields: {
      service: 'Hizmet',
      langs: 'Diller',
      documentType: 'Belge türü',
      words: 'Kelime',
      delivery: 'Tahmini süre',
      total: 'Tutar',
      note: 'Notunuz',
      deliveryAddress: 'Teslimat adresi',
    },
    myOrders: 'Siparişlerim',
    backHome: 'Ana Sayfaya Dön',
    whatsapp: "WhatsApp'tan İletişime Geç",
    loading: 'Sipariş yükleniyor…',
    loginRequired: {
      title: 'Siparişinizi görmek için giriş yapın',
      desc: 'Sipariş detaylarınıza yalnızca hesabınızla giriş yaptıktan sonra ulaşabilirsiniz.',
      login: 'Giriş Yap',
    },
    notFound: {
      title: 'Sipariş bulunamadı',
      desc: 'Bu sipariş numarası size ait değil veya mevcut değil. Lütfen bağlantıyı kontrol edin.',
      home: 'Ana Sayfaya Dön',
    },
  },

  faq: {

    whatsappMsg: "Merhaba, bir sorum var.",
    seo: {
      title: 'Sık Sorulan Sorular',
      description: 'Yeminli tercüme, teslim süresi, fiyatlandırma, noter onayı ve kurumsal şartlar hakkında sık sorulan sorular.',
    },
    hero: { title: 'Sık Sorulan Sorular', subtitle: 'Aradığınız cevap burada.' },
    categoriesTitle: 'Kategoriler',
    searchPlaceholder: 'Soru veya anahtar kelime ara…',
    empty: 'Aramanızla eşleşen soru bulunamadı. Farklı bir kelime deneyin veya bizimle iletişime geçin.',
    categories: FAQ_CATEGORIES,
    items: FAQ_ITEMS,
    notFound: {
      title: 'Sorunuzun cevabını bulamadınız mı?',
      contact: 'İletişime Geçin',
      whatsapp: 'WhatsApp Destek',
    },
  },

  contact: {

    formErrors: {

      name: "Ad Soyad zorunludur.",

      email: "Geçerli bir e-posta girin.",

      subject: "Konu zorunludur.",

      message: "Mesaj en az 10 karakter olmalıdır.",

      consent: "Devam etmek için onay gereklidir.",

    },
    seo: {
      title: 'İletişim',
      description: 'TercümExpert ile iletişime geçin: telefon, e-posta, WhatsApp ve iletişim formu.',
    },
    hero: { title: 'İletişim', subtitle: 'Size nasıl yardımcı olabiliriz?' },
    infoTitle: 'İletişim bilgileri',
    labels: {
      phone: 'Telefon',
      email: 'E-posta',
      whatsapp: 'WhatsApp',
      address: 'Adres',
      hours: 'Çalışma saatleri',
    },
    form: {
      title: 'Bize yazın',
      fields: {
        name: 'Ad Soyad',
        email: 'E-posta',
        phone: 'Telefon',
        subject: 'Konu',
        message: 'Mesaj',
        consent: '<kvkk>KVKK Aydınlatma Metni</kvkk>’ni okudum ve onaylıyorum.',
      },
      submit: 'Mesajı Gönder',
      success: 'Mesajınız alındı. En kısa sürede dönüş yapacağız.',
    },
    map: {
      title: 'Konumumuz',
      subtitle: 'Bizi haritada bulun',
      placeholder: 'Harita alanı',
      note: 'Konum haritası yakında burada gösterilecek.',
    },
  },

  auth: {
    seo: {
      title: 'Giriş Yap / Üye Ol',
      description: 'TercümExpert hesabınıza giriş yapın veya yeni bir hesap oluşturun.',
    },
    tabs: { login: 'Giriş Yap', register: 'Üye Ol' },
    google: 'Google ile devam et',
    or: 'veya',
    fields: {
      firstName: 'Ad',
      lastName: 'Soyad',
      email: 'E-posta',
      password: 'Şifre',
      code: 'Doğrulama Kodu',
    },
    login: {
      title: 'Hesabınıza giriş yapın',
      submit: 'Giriş Yap',
      noAccount: 'Hesabınız yok mu?',
      switchToRegister: 'Üye olun',
    },
    register: {
      title: 'Yeni hesap oluşturun',
      submit: 'Üye Ol',
      haveAccount: 'Zaten hesabınız var mı?',
      switchToLogin: 'Giriş yapın',
      consent: 'Üyelik oluşturarak <kvkk>KVKK Aydınlatma Metni</kvkk>’ni ve <privacy>Gizlilik Politikası</privacy>’nı kabul ediyorum.',
    },
    verify: {
      title: 'E-postanızı doğrulayın',
      desc: 'adresine gönderdiğimiz 6 haneli kodu girin.',
      submit: 'Doğrula ve Devam Et',
      spam: 'Kod birkaç dakika gecikebilir; spam / gereksiz klasörünü de kontrol edin.',
      resend: 'Kodu yeniden gönder',
      resent: 'Yeni kod gönderildi.',
      back: 'Geri dön',
    },
    signedIn: {
      title: 'Hesabım',
      greeting: 'Hoş geldiniz',
      logout: 'Çıkış Yap',
    },
    orders: {
      title: 'Siparişlerim',
      empty: 'Henüz siparişiniz yok. Fiyat Hesapla’dan ilk siparişinizi oluşturabilirsiniz.',
      loading: 'Siparişler yükleniyor…',
      error: 'Siparişler yüklenemedi. Lütfen sayfayı yenileyin.',
      status: {
        received: 'Alındı',
        in_progress: 'İşleme alındı',
        translated: 'Çeviri tamamlandı',
        shipped: 'Kargoya verildi',
        delivered: 'Teslim edildi',
        cancelled: 'İptal edildi',
      },
      track: 'Takip Et',
    },
    errors: {
      nameRequired: 'Ad ve soyad zorunludur.',
      emailInvalid: 'Geçerli bir e-posta girin.',
      passwordShort: 'Şifre en az 6 karakter olmalıdır.',
      codeInvalid: 'Lütfen 6 haneli kodu girin.',
      consentRequired: 'Devam etmek için onay gereklidir.',
    },
  },

  blog: {
    seo: { title: 'Blog', description: 'Çeviri, noter, apostil ve lokalizasyon üzerine rehber içerikler.' },
    hero: { title: 'Blog', subtitle: 'Çeviri dünyasından rehberler.' },
    searchPlaceholder: 'Yazılarda ara…',
    readingTime: 'dk okuma',
    relatedTitle: 'İlgili yazılar',
    allCategories: 'Tümü',
    empty: 'Bu kritere uygun yazı bulunamadı.',
    cta: {
      needService: 'Bu hizmete mi ihtiyacınız var?',
      quickPrice: 'Saniyeler içinde fiyatınızı hesaplayın.',
      button: 'Hemen Fiyat Hesapla',
      genericTitle: 'Çeviri İhtiyacınız Mı Var?',
      genericHeading: 'Her Alanda Profesyonel Çeviri',
      genericDesc: 'Alanında uzman tercümanlarımız 7/24 hizmetinizde!',
    },
    share: {
      title: 'Paylaş',
      copy: 'Linki Kopyala',
      copied: 'Kopyalandı',
    },
  },

  legal: {
    lastUpdatedLabel: `Son güncelleme`,
    draftNotice: `Aşağıdaki metinde köşeli parantezle gösterilen alanlar ([...]) şirket bilgilerinizle doldurulacaktır. Metinler genel bilgilendirme amaçlıdır ve yayına almadan önce bir hukuk uzmanı tarafından gözden geçirilmesi önerilir.`,
    kvkk: {
      seo: { title: `KVKK Aydınlatma Metni`, description: `6698 sayılı KVKK kapsamında kişisel verilerinizin işlenmesine ilişkin aydınlatma metni.` },
      title: `KVKK Aydınlatma Metni`,
      sections: [
        { heading: `Veri Sorumlusu`, body: `6698 sayılı Kişisel Verilerin Korunması Kanunu (“KVKK”) uyarınca kişisel verileriniz, veri sorumlusu sıfatıyla Samed Fazlı Atlıcı (“TercümExpert”) tarafından aşağıda açıklanan kapsamda işlenmektedir. Adres: Şeyh Şamil Mah. Eylül Sk. No: 2/D, Selçuklu, Konya. E-posta: info@tercumexpert.com. Telefon: [TELEFON].` },
        { heading: `İşlenen Kişisel Veriler`, body: `Kimlik ve iletişim verileriniz (ad, soyad, e-posta adresi, telefon numarası), teslimat adresi bilgileriniz, sipariş ve işlem verileriniz, çeviri amacıyla tarafımıza ilettiğiniz belgelerin içeriğindeki veriler ile siteyi kullanımınıza ilişkin işlem güvenliği verileri (IP adresi, oturum ve çerez kayıtları) işlenmektedir.` },
        { heading: `İşleme Amaçları`, body: `Kişisel verileriniz; çeviri, yeminli tercüme, noter onayı ile ilgili hizmetlerin sunulması, tekliflerin oluşturulması ve siparişlerin yönetimi, müşteri ilişkileri ile talep ve şikâyetlerin yönetimi, sözleşmesel ve yasal yükümlülüklerin yerine getirilmesi ve hizmet güvenliğinin sağlanması amaçlarıyla işlenir.` },
        { heading: `İşlemenin Hukuki Sebepleri`, body: `Verileriniz; bir sözleşmenin kurulması veya ifası için gerekli olması, hukuki yükümlülüklerimizin yerine getirilmesi, bir hakkın tesisi ve korunması ve temel hak ve özgürlüklerinize zarar vermemek kaydıyla meşru menfaatlerimiz hukuki sebeplerine dayanılarak; gereken hâllerde ise açık rızanıza istinaden işlenir (KVKK m.5 ve m.6).` },
        { heading: `Toplama Yöntemi`, body: `Kişisel verileriniz; web sitesindeki formlar, üyelik ve sipariş süreçleri, e-posta ve diğer iletişim kanalları aracılığıyla elektronik ortamda toplanır.` },
        { heading: `Kişisel Verilerin Aktarılması`, body: `Verileriniz, hizmetin gerektirdiği ölçüde; barındırma, altyapı, kimlik doğrulama, e-posta ve analitik hizmeti aldığımız yurt içinde ve yurt dışında bulunan tedarikçilerimize ve yetkili kamu kurum ve kuruluşlarına, KVKK m.8 ve m.9’daki şartlara uygun olarak aktarılabilir. Kullandığımız bazı altyapı ve hizmet sağlayıcıların sunucuları yurt dışında bulunduğundan, verileriniz mevzuatta öngörülen güvenceler çerçevesinde yurt dışına aktarılabilir.` },
        { heading: `Saklama Süreleri`, body: `Kişisel verileriniz, işleme amacının gerektirdiği süre ile ilgili mevzuatta (vergi, ticaret ve tüketici mevzuatı gibi) öngörülen zamanaşımı ve saklama süreleri boyunca saklanır; sürelerin sona ermesiyle silinir, yok edilir veya anonim hâle getirilir.` },
        { heading: `İlgili Kişinin Hakları`, body: `KVKK m.11 uyarınca; kişisel verilerinizin işlenip işlenmediğini öğrenme, işlenmişse bilgi talep etme, işlenme amacını ve amacına uygun kullanılıp kullanılmadığını öğrenme, yurt içinde veya yurt dışında aktarıldığı üçüncü kişileri bilme, eksik veya yanlış işlenmişse düzeltilmesini, şartları oluştuğunda silinmesini veya yok edilmesini isteme, bu işlemlerin aktarıldığı üçüncü kişilere bildirilmesini isteme, münhasıran otomatik sistemlerle analiz sonucu aleyhinize bir sonucun ortaya çıkmasına itiraz etme ve zarara uğramanız hâlinde zararın giderilmesini talep etme haklarına sahipsiniz.` },
        { heading: `Başvuru Yöntemi`, body: `Haklarınıza ilişkin taleplerinizi, “Veri Sorumlusuna Başvuru Usul ve Esasları Hakkında Tebliğ”e uygun olarak info@tercumexpert.com adresine veya Şeyh Şamil Mah. Eylül Sk. No: 2/D, Selçuklu, Konya adresine yazılı olarak iletebilirsiniz. Talebiniz, niteliğine göre en kısa sürede ve en geç otuz gün içinde sonuçlandırılır.` },
      ],
    },
    privacy: {
      seo: { title: `Gizlilik Politikası`, description: `Kişisel verilerinizin ve belgelerinizin gizliliğine ilişkin politikamız.` },
      title: `Gizlilik Politikası`,
      sections: [
        { heading: `Giriş`, body: `TercümExpert olarak gizliliğinize önem veriyoruz. Bu Gizlilik Politikası, tercumexpert.com üzerinden sunduğumuz hizmetlerde hangi bilgileri, hangi amaçlarla topladığımızı ve nasıl koruduğumuzu açıklar. Kişisel verilerin işlenmesine ilişkin ayrıntılı bilgiye KVKK Aydınlatma Metni’nden ulaşabilirsiniz.` },
        { heading: `Topladığımız Bilgiler`, body: `Hesap ve iletişim bilgileri (ad, soyad, e-posta, telefon), sipariş ve teslimat bilgileri, çeviri için tarafımıza ilettiğiniz belgeler ve içerikleri, ödemeye ilişkin işlem bilgileri ve siteyi kullanımınıza dair teknik veriler (IP adresi, tarayıcı bilgisi, çerez kayıtları) tarafımızca toplanabilir.` },
        { heading: `Bilgileri Kullanım Amaçlarımız`, body: `Bilgilerinizi; hizmetleri sunmak, teklif ve siparişleri yönetmek, sizinle iletişim kurmak, yasal yükümlülüklerimizi yerine getirmek ve hizmet kalitesi ile güvenliğini geliştirmek için kullanırız. Belgelerinizi yalnızca talep ettiğiniz hizmetin gerektirdiği ölçüde işleriz.` },
        { heading: `Belge Gizliliği`, body: `Çeviriye konu belgeleriniz gizli olarak değerlendirilir. Bu belgelere yalnızca ilgili hizmeti yürüten yetkili çevirmen ve personel, işin gerektirdiği süre boyunca erişir; belgeleriniz hizmet amacı dışında üçüncü kişilerle paylaşılmaz.` },
        { heading: `Üçüncü Taraf Hizmet Sağlayıcılar`, body: `Hizmetlerimizi sunarken barındırma ve altyapı, kimlik doğrulama, e-posta gönderimi, analitik ve (etkinleştirildiğinde) ödeme alanlarında güvenilir üçüncü taraf sağlayıcılardan yararlanırız. Bu sağlayıcılar verilerinize yalnızca kendilerine verilen hizmeti sunmak amacıyla ve sözleşmesel gizlilik yükümlülükleri altında erişebilir; bir kısmının sunucuları yurt dışında bulunabilir.` },
        { heading: `Veri Güvenliği`, body: `Verilerinizi yetkisiz erişime karşı korumak için aktarımda şifreleme, erişim kısıtlamaları ve uygun idari ve teknik tedbirleri uygularız. Hiçbir yöntem mutlak güvenlik sağlayamasa da verilerinizi korumak için makul ve güncel önlemleri alırız.` },
        { heading: `Çerezler`, body: `Sitemizde çerezler ve benzeri teknolojiler kullanılır. Türleri ve tercih yönetimi hakkında ayrıntılı bilgi için Çerez Politikası’nı inceleyebilirsiniz.` },
        { heading: `Haklarınız`, body: `Kişisel verilerinize erişme, düzeltme ve silme dâhil KVKK kapsamındaki haklarınızı kullanabilirsiniz. Talepleriniz için info@tercumexpert.com adresi üzerinden bizimle iletişime geçebilirsiniz.` },
        { heading: `Çocukların Gizliliği`, body: `Hizmetlerimiz 18 yaşın altındaki kişilere yönelik değildir ve bilerek çocuklara ait kişisel veri toplamayız.` },
        { heading: `Değişiklikler`, body: `Bu politika zaman zaman güncellenebilir. Güncel sürüm daima bu sayfada yayımlanır; önemli değişikliklerde uygun yöntemlerle bilgilendirme yapılır.` },
        { heading: `İletişim`, body: `Gizlilik ile ilgili sorularınız için: E-posta: info@tercumexpert.com · Telefon: [TELEFON] · Adres: Şeyh Şamil Mah. Eylül Sk. No: 2/D, Selçuklu, Konya.` },
      ],
    },
    distanceSales: {
      seo: { title: `Mesafeli Satış Sözleşmesi`, description: `6502 sayılı Kanun kapsamında hizmet satışına ilişkin mesafeli satış sözleşmesi.` },
      title: `Mesafeli Satış Sözleşmesi`,
      sections: [
        { heading: `Taraflar`, body: `İşbu Mesafeli Satış Sözleşmesi (“Sözleşme”); bir tarafta Samed Fazlı Atlıcı (“Satıcı”; adres: Şeyh Şamil Mah. Eylül Sk. No: 2/D, Selçuklu, Konya, e-posta: info@tercumexpert.com, telefon: [TELEFON]) ile diğer tarafta siparişi veren tüketici (“Alıcı”) arasında, 6502 sayılı Tüketicinin Korunması Hakkında Kanun ve Mesafeli Sözleşmeler Yönetmeliği uyarınca elektronik ortamda kurulmuştur.` },
        { heading: `Sözleşmenin Konusu`, body: `Sözleşme’nin konusu; Alıcı’nın tercumexpert.com üzerinden elektronik ortamda sipariş ettiği, nitelikleri ve satış bedeli sipariş özetinde belirtilen çeviri, yeminli tercüme, noter onayı ile ilgili hizmetlerin sunulmasıdır.` },
        { heading: `Hizmetin Nitelikleri ve Bedeli`, body: `Sipariş edilen hizmetin türü, kapsamı, teslim şekli (dijital veya kargo) ve vergiler dâhil toplam bedeli, sipariş sırasında Alıcı’ya açıkça gösterilir ve sipariş onayında yer alır. Fiyatlandırma, seçilen hizmete ve belge özelliklerine göre hesaplanır.` },
        { heading: `Ödeme`, body: `Ödeme, sipariş adımında sunulan ödeme yöntemleriyle gerçekleştirilir. Sipariş, ödemenin onaylanmasının ardından işleme alınır.` },
        { heading: `İfa ve Teslimat`, body: `Dijital teslimatlarda çeviri, tamamlanmasının ardından Alıcı’nın hesabı veya e-postası üzerinden iletilir. Fiziki, ıslak imzalı veya yeminli belgelerde teslimat, Alıcı’nın bildirdiği adrese kargo ile yapılır. Tahmini teslim süreleri sipariş sırasında belirtilir; belge yoğunluğuna ve onay süreçlerine göre değişebilir.` },
        { heading: `Cayma Hakkı`, body: `Alıcı, kural olarak hizmet sunumuna ilişkin sözleşmelerde, sözleşmenin kurulduğu tarihten itibaren on dört (14) gün içinde herhangi bir gerekçe göstermeksizin cayma hakkına sahiptir. Ancak aşağıda belirtilen istisnalar saklıdır.` },
        { heading: `Cayma Hakkının İstisnaları`, body: `Mesafeli Sözleşmeler Yönetmeliği m.15 uyarınca; Alıcı’nın onayıyla ifasına başlanan ve cayma süresi dolmadan tamamlanan hizmetler ile Alıcı’nın istekleri veya kişisel ihtiyaçları doğrultusunda özel olarak hazırlanan mal ve hizmetlerde (kişiye ya da belgeye özel hazırlanan çeviri ve onay hizmetleri dâhil) cayma hakkı kullanılamaz. Çeviri işine başlanmadan önce iletilen iptal talepleri ayrıca değerlendirilir.` },
        { heading: `İptal ve İade`, body: `Henüz bir tercüman tarafından üstlenilmemiş (işleme alınmamış) siparişler, sipariş sayfanızdaki iptal seçeneğiyle doğrudan iptal edilebilir; dilerseniz iptal talebinizi info@tercumexpert.com üzerinden de iletebilirsiniz. Uygun görülen iadeler, ödemenin yapıldığı yöntemle makul süre içinde gerçekleştirilir. Çeviri bir tercüman tarafından işleme alındıktan sonra, işin kişiye özel niteliği gereği iade yapılmaz.` },
        { heading: `Uyuşmazlıkların Çözümü`, body: `İşbu Sözleşme’den doğabilecek uyuşmazlıklarda, Ticaret Bakanlığı’nca her yıl ilan edilen parasal sınırlar dâhilinde Alıcı’nın yerleşim yerindeki veya işlemin yapıldığı yerdeki Tüketici Hakem Heyetleri ile Tüketici Mahkemeleri yetkilidir.` },
        { heading: `Yürürlük`, body: `Alıcı, siparişi onaylamakla işbu Sözleşme’nin tüm koşullarını okuduğunu ve kabul ettiğini beyan eder. Sözleşme, siparişin onaylanması ile yürürlüğe girer.` },
      ],
    },
    cookies: {
      seo: { title: `Çerez Politikası`, description: `Sitemizde kullanılan çerezler ve tercih yönetimi hakkında bilgi.` },
      title: `Çerez Politikası`,
      sections: [
        { heading: `Çerez Nedir?`, body: `Çerezler, bir web sitesini ziyaret ettiğinizde tarayıcınıza kaydedilen küçük metin dosyalarıdır. Siteyi daha güvenli ve işlevsel hâle getirmek, tercihlerinizi hatırlamak ve kullanım istatistikleri elde etmek için kullanılırlar.` },
        { heading: `Neden Çerez Kullanıyoruz?`, body: `Çerezleri; sitenin temel işlevlerini sağlamak, oturum güvenliğini korumak, performansı ölçmek ve onayınıza bağlı olarak hizmetlerimizi geliştirmek ile pazarlama faaliyetlerini yürütmek için kullanırız.` },
        { heading: `Çerez Kategorileri`, body: `Zorunlu çerezler sitenin çalışması ve güvenliği için gereklidir ve kapatılamaz. Performans ve analitik çerezler ziyaretçi etkileşimini anlamamıza yardımcı olur. Pazarlama çerezleri ilgi alanlarınıza uygun içerik ve reklam sunulmasına destek olur. Tercih çerezleri dil gibi seçimlerinizi hatırlar. Analitik ve pazarlama çerezleri yalnızca açık onayınızla çalışır.` },
        { heading: `Üçüncü Taraf Çerezleri`, body: `Analitik ve pazarlama amacıyla üçüncü taraf hizmetlerden (örneğin ziyaretçi istatistiği ve reklam ölçümleme araçlarından) yararlanabiliriz. Bu hizmetler kendi çerezlerini yerleştirebilir ve verileri kendi gizlilik politikaları kapsamında işleyebilir.` },
        { heading: `Çerez Tercihlerinin Yönetimi`, body: `Zorunlu olmayan çerezlere ilişkin tercihlerinizi, sitede sunulan çerez tercih aracı üzerinden dilediğiniz zaman verebilir veya değiştirebilirsiniz. Ayrıca tarayıcınızın ayarlarından çerezleri silebilir ya da engelleyebilirsiniz; ancak bu durumda sitenin bazı bölümleri düzgün çalışmayabilir.` },
        { heading: `Saklama Süreleri`, body: `Çerezler, türüne göre oturum boyunca veya belirli bir süre için saklanır. Oturum çerezleri tarayıcı kapatıldığında silinir; kalıcı çerezler ise belirlenen süre sonunda veya siz sildiğinizde sona erer.` },
        { heading: `Değişiklikler`, body: `Bu Çerez Politikası zaman zaman güncellenebilir. Güncel sürüm daima bu sayfada yayımlanır.` },
      ],
    },
    partnership: {
      seo: { title: "İş Ortaklığı Sözleşmesi", description: "TercümExpert iş ortaklığı (partner) programının şart ve koşulları." },
      title: "İş Ortaklığı Sözleşmesi",
      sections: [
        { heading: "Taraflar ve Konu", body: "İşbu İş Ortaklığı Sözleşmesi, bir tarafta Samed Fazlı Atlıcı (“TercümExpert”) ile diğer tarafta programa başvurup onaylanan iş ortağı (“Partner”) arasında, TercümExpert yönlendirme (iş ortaklığı) programının şart ve koşullarını düzenlemek amacıyla kurulmuştur." },
        { heading: "Başvuru ve Onay", body: "Partner statüsü, iş ortaklığı sayfasındaki başvuru formunun doldurulması ve TercümExpert tarafından onaylanmasıyla kazanılır. Onay TercümExpert’in takdirindedir ve başvuru reddedilebilir. Partner, program kapsamında e-posta adresini doğrular; programa katılım için başlangıç ücreti alınmaz." },
        { heading: "Davet Bağlantısı ve Müşteri Atfı", body: "Onaylanan her Partner’e kendisine özel, benzersiz bir davet bağlantısı ve buna bağlı bir QR kodu tahsis edilir. Bu bağlantı veya QR kod aracılığıyla siteye gelip ilk kez üye olan müşteri, kalıcı olarak ilgili Partner’e bağlanır; atıf ilk üyelik anında gerçekleşir ve sonradan değiştirilemez. Komisyon hakkı yalnızca bu şekilde Partner’e bağlanmış müşterilerin siparişlerinden doğar." },
        { heading: "Komisyon Yapısı", body: "Partner payı, katma değer vergisi (KDV) ve ek hizmet farkları hariç tutularak hesaplanır: ana çeviri bedelinin %20’si; acil teslimat seçilmişse acil teslimat farkının %20’si; yeminli tercüme seçilmişse yeminli tercüme farkının %10’u. Noter onayı ve fiziksel (kargo) teslimat bedellerinden Partner’e pay verilmez ve KDV komisyona esas alınmaz. Bu yüzdeler sabittir; fiyatlar değişse dahi oranlar geçerliliğini korur. TercümExpert, önceden bildirimde bulunmak kaydıyla oran ve koşulları güncelleyebilir." },
        { heading: "Hak Ediş ve Cüzdan", body: "Komisyon, yönlendirilen müşterinin ilgili siparişi tamamlandığında Partner’in cüzdanına eklenir ve eklendiği tarihten itibaren yedi (7) gün boyunca kilitli kalır; bu sürenin dolmasıyla çekilebilir hâle gelir. İptal edilen, iade edilen veya ödemesi tamamlanmayan siparişler komisyona esas alınmaz." },
        { heading: "Ödemeler", body: "Çekilebilir bakiyeler, her ayın 2’si ve 17’sinde Partner’in bildirdiği IBAN’a ödenir. Ödeme yapılabilmesi için Partner’in profilindeki zorunlu bilgilerin eksiksiz doldurulmuş ve IBAN ile IBAN sahibi bilgilerinin TercümExpert tarafından onaylanmış olması gerekir. Ödemelere ilişkin vergisel yükümlülükler yürürlükteki mevzuata tabidir." },
        { heading: "Partner’in Yükümlülükleri", body: "Partner; tanıtımlarında doğru ve yanıltıcı olmayan bilgi kullanmayı, TercümExpert’in marka ve itibarına zarar verecek davranışlardan kaçınmayı, iletişim ve ödeme bilgilerini güncel tutmayı ve yürürlükteki mevzuata uymayı kabul eder." },
        { heading: "Yasaklı Davranışlar", body: "Spam ve istenmeyen toplu ileti gönderimi, yanıltıcı reklam, sahte ya da kendi kendine yönlendirme (Partner’in kendi hesabıyla sipariş vermesi dâhil) ve haksız rekabet oluşturan davranışlar yasaktır. Bu tür ihlaller, ilgili komisyonların iptali ve Sözleşme’nin feshi sebebidir." },
        { heading: "Marka Kullanımı", body: "Partner, TercümExpert marka, logo ve tanıtım materyallerini yalnızca TercümExpert’in yazılı onayı ve sağladığı kurallar çerçevesinde kullanabilir." },
        { heading: "Gizlilik ve Kişisel Veriler", body: "Taraflar, Sözleşme kapsamında edindikleri gizli bilgileri korumayı taahhüt eder. Partner, yönlendirdiği müşterilere ilişkin kişisel verileri yalnızca programın amacı doğrultusunda ve yürürlükteki veri koruma mevzuatına uygun olarak işler." },
        { heading: "Bağımsız Taraf", body: "Partner bağımsız bir taraftır; TercümExpert’in çalışanı, temsilcisi veya acentesi değildir ve TercümExpert adına üçüncü kişilere karşı taahhütte bulunamaz." },
        { heading: "Süre ve Fesih", body: "Sözleşme, taraflardan biri feshini bildirene kadar yürürlükte kalır. TercümExpert, yükümlülüklere aykırılık hâlinde Sözleşme’yi derhâl feshedebilir; usulsüz veya kötüye kullanım niteliğindeki yönlendirmelerden doğan komisyonlar ödenmez. Fesih hâlinde kilidi açılmış meşru bakiyeler yürürlükteki koşullara göre ödenir." },
        { heading: "Değişiklikler, Uyuşmazlık ve Yürürlük", body: "TercümExpert işbu Sözleşme’yi zaman zaman güncelleyebilir; güncel sürüm daima bu sayfada yayımlanır. Sözleşme Türkiye Cumhuriyeti hukukuna tabidir. Partner, başvuruyu onaylayarak Sözleşme’nin tüm şartlarını okuduğunu ve kabul ettiğini beyan eder." },
      ],
    },
  },

  admin: {
    attachmentImage: 'Görsel',
    attachmentFile: 'Belge',
    title: "Yönetim Paneli",
    summary: '{total} sohbet · {leads} iletişim talebi',
    onlyLeads: 'Sadece iletişim talepleri',
    loading: 'Kayıtlar yükleniyor…',
    error: 'Kayıtlar okunamadı. Supabase tablosu ve izinleri (RLS) kurulu mu kontrol edin.',
    empty: 'Henüz kayıt yok.',
    selectHint: 'Görüntülemek için soldan bir sohbet seçin.',
    contactRequest: 'İletişim talebi',
    contactInfo: 'İletişim bilgileri',
    fieldName: 'Ad',
    fieldEmail: 'E-posta',
    fieldPhone: 'Telefon',
    fieldMessage: 'Mesaj',
    requestBadge: 'talep',
    noMessages: 'Bu kayıtta mesaj yok (yalnızca iletişim talebi).',
    loginTitle: 'Giriş gerekli',
    loginDesc: 'Bu sayfayı görüntülemek için yönetici hesabıyla giriş yapın.',
    login: 'Giriş Yap',
    noAccessTitle: 'Erişim yetkiniz yok',
    noAccessDesc: 'Bu sayfa yalnızca yöneticilere açıktır.',
    loadingAuth: 'Yükleniyor…',
  },
  footer: {
    tagline: 'Profesyonel çeviri hizmetlerinde güvenilir çözüm ortağınız.',
    columns: {
      quickLinks: 'Hızlı Bağlantılar',
      services: 'Hizmetler',
      contact: 'İletişim',
    },
    quickLinks: {
      corporate: 'Kurumsal',
      services: 'Hizmetlerimiz',
      quote: 'Fiyat Hesapla',
      blog: 'Blog',
      faq: 'Sık Sorulan Sorular',
      contact: 'İletişim',
    },
    serviceLinks: {
      sworn: 'Yeminli Tercüme',
      notarized: 'Noter Onaylı Tercüme',
      corporate: 'Kurumsal Çözümler',
      partnership: 'İş Ortaklığı Programı',
    },
    legal: {
      kvkk: 'KVKK',
      privacy: 'Gizlilik Politikası',
      distanceSales: 'Mesafeli Satış Sözleşmesi',
      cookies: 'Çerez Politikası',
    },
    socialTitle: 'Bizi takip edin',
    whatsapp: 'WhatsApp Destek',
    rights: 'Tüm hakları saklıdır.',
  },

  cookie: {
    title: 'Çerez tercihleri',
    desc: 'Deneyiminizi iyileştirmek için çerezler kullanıyoruz. Zorunlu çerezler dışındakiler yalnızca onayınızla çalışır.',
    accept: 'Kabul Et',
    reject: 'Reddet',
    manage: 'Tercihleri Yönet',
    save: 'Tercihleri Kaydet',
    categories: {
      necessary: { label: 'Zorunlu', desc: 'Sitenin çalışması için gereklidir; kapatılamaz.' },
      analytics: { label: 'Analitik', desc: 'Kullanımı anlamamıza yardımcı olur.' },
      marketing: { label: 'Pazarlama', desc: 'İlgili içerik ve reklamlar için.' },
      preferences: { label: 'Tercihler', desc: 'Tercihlerinizi hatırlar.' },
    },
  },

  chatbot: {
    attach: {
      button: 'Dosya ekle',
      tooLarge: 'Dosya çok büyük (en fazla 25 MB).',
      unsupported: 'Ses ve video dosyalarını sohbet içinde inceleyemiyorum. Bunları fiyat hesaplama sayfasından yükleyebilirsiniz.',
      cannotRead: 'Bu dosyayı okuyamadım. Fiyat hesaplama sayfasından yükleyebilir veya farklı bir biçim deneyebilirsiniz.',
      reading: 'Dosya okunuyor…',
      remove: 'Kaldır',
    },
    nudge: 'Size nasıl yardımcı olabilirim?',
    title: 'TercümExpert Destek',
    open: 'Sohbeti aç',
    close: 'Sohbeti kapat',
    minimize: 'Küçült',
    clear: 'Konuşmayı temizle',
    inputPlaceholder: 'Mesajınızı yazın…',
    send: 'Gönder',
    typing: 'Yazıyor…',
    welcome:
      "Merhaba, TercümExpert'e hoş geldiniz. Çeviri, fiyatlandırma, noter onayı veya kurumsal hizmetler hakkında size yardımcı olabilirim.",
    quickQuestions: [
      'Fiyat nasıl hesaplanıyor?',
      'Yeminli tercüme nedir?',
      'Belge yüklemek istiyorum',
      'Kurumsal teklif almak istiyorum',
      'Noter onayı gerekiyor mu?',
      'Bir müşteri temsilcisine bağlan',
    ],
    handoff: 'Müşteri temsilcisine bağlan',
    toWhatsapp: "WhatsApp'a aktar",
    disclaimer: 'Bu bilgi genel bilgilendirmedir; kesin gereklilik için ilgili kurumdan teyit alınız.',
    sensitiveWarning:
      'Lütfen bu sohbet üzerinden hassas kişisel veri paylaşmayın. Belgelerinizi güvenli yükleme alanından iletebilirsiniz.',
    answers: [
      `Fiyat; belgenizin kelime sayısı, dil çifti, hizmet türü (yeminli, noter onaylı) ve teslim süresine göre hesaplanır. Anında tahmini fiyat için Fiyat Hesapla sayfasından belgenizi yükleyebilir veya bilgileri girebilirsiniz.`,
      `Yeminli tercüme, yeminli bir tercüman tarafından yapılan ve tercümanın imza ve kaşesiyle onaylanan resmî çeviridir. Resmî kurumlar çoğunlukla yeminli çeviri talep eder; gerektiğinde noter onayı da eklenebilir.`,
      `Belgenizi Fiyat Hesapla sayfasındaki güvenli yükleme alanından iletebilirsiniz. Yükleme sonrası anında tahmini fiyatı görür ve siparişinizi tamamlayabilirsiniz.`,
      `Kurumsal ihtiyaçlarınız için düzenli ve hacimli çevirilerde özel fiyatlandırma ve öncelikli teslim sunuyoruz. Ayrıntılar için Kurumsal sayfamızı inceleyebilir veya bizimle iletişime geçebilirsiniz.`,
      `Noter onayı ihtiyacı, belgeyi sunacağınız kuruma ve işlemin türüne göre değişir. Bazı işlemler yalnızca yeminli çeviriyi kabul ederken bazıları noter onayı da ister. Emin değilseniz size yardımcı olalım.`,
      `Sizi hemen bir müşteri temsilcimize bağlayalım. Aşağıdaki butondan WhatsApp üzerinden bize yazabilirsiniz.`,
    ],
    fallback: `Sorunuzda size en doğru yardımı bir müşteri temsilcimiz verebilir. Aşağıdaki butondan WhatsApp üzerinden bize yazabilirsiniz; mesajınız hazır olarak iletilecektir.`,
    contact: {
      whatsapp: 'WhatsApp',
      email: 'E-posta',
      phone: 'Telefon',
      leaveInfo: 'İletişim bilgilerimi bırak',
      formTitle: 'Sizinle iletişime geçelim',
      formDesc: 'Bilgilerinizi bırakın, ekibimiz en kısa sürede size ulaşsın.',
      name: 'Adınız',
      emailField: 'E-posta',
      phoneField: 'Telefon',
      message: 'Mesajınız (opsiyonel)',
      submit: 'Gönder',
      submitting: 'Gönderiliyor…',
      thanks: 'Teşekkürler, ekibimiz en kısa sürede sizinle iletişime geçecek.',
      errorRequired: 'Lütfen e-posta veya telefon girin.',
      back: 'Geri',
      introTitle: 'Hoş geldiniz',
      introDesc: 'Size daha iyi yardımcı olabilmem için önce adınızı ve e-posta adresinizi alabilir miyim?',
      start: 'Sohbete başla',
      introError: 'Lütfen adınızı ve e-posta adresinizi girin.',
    },
  },

  translator: {
    seo: {
      title: 'Tercüman Paneli — TercümExpert',
      description: 'Tercüman başvurusu ve iş paneli.',
    },
    loading: 'Yükleniyor…',
    loginTitle: 'Giriş gerekli',
    loginDesc: 'Bu alan yalnızca tercümanlara ve yöneticilere açıktır. Devam etmek için giriş yapın.',
    login: 'Giriş yap',
    setupTitle: 'Panel henüz hazır değil',
    setupDesc: 'Tercüman altyapısı (veritabanı) henüz kurulmadı. Kurulum tamamlanınca panel etkinleşir.',
    applyTitle: 'Tercüman Başvurusu',
    applyDesc: 'Serbest tercüman ağımıza katılmak için bilgilerinizi doldurun. Başvurunuz yönetim onayından sonra etkinleşir.',
    applyNote: 'Bilgileriniz yalnızca değerlendirme ve ödeme amacıyla kullanılır.',
    form: {
      fullName: 'Ad Soyad',
      birthDate: 'Doğum tarihi',
      phone: 'Telefon',
      country: 'Ülke',
      city: 'Şehir / İl',
      selectCountry: 'Ülke seçin',
      selectCity: 'Şehir / eyalet seçin',
      cityNeedsCountry: 'Önce ülke seçin',
      address: 'Açık adres',
      isSworn: 'Yeminli tercüman mısınız?',
      isSwornHint: 'Bir noterde yemin zaptınız varsa işaretleyin. Yeminli tercüme gerektiren işlerde önceliklendirilirsiniz.',
      iban: 'IBAN',
      ibanName: 'IBAN sahibi (ad soyad)',
      languagePairs: 'Dil çiftleri',
      source: 'Kaynak dil',
      target: 'Hedef dil',
      addPair: 'Ekle',
      removePair: 'Kaldır',
      swap: 'Yön değiştir',
      expertise: 'Uzmanlık alanları',
      submit: 'Başvuruyu gönder',
      submitting: 'Gönderiliyor…',
      saved: 'Bilgileriniz kaydedildi.',
      saveError: 'Kaydedilemedi. Lütfen tekrar deneyin.',
      required: 'Lütfen zorunlu alanları doldurun.',
      atLeastOnePair: 'En az bir dil çifti ekleyin.',
      cv: "CV / Özgeçmiş",
      cvHint: "PDF veya Word dosyası yükleyin (zorunlu).",
      cvChoose: "Dosya seç",
      cvNone: "Dosya seçilmedi",
      cvRequired: "Başvuru için CV yüklemeniz zorunludur.",
      cvUploadError: "CV yüklenemedi. Lütfen tekrar deneyin.",
    },
    expertiseLabels: {
      legal: 'Hukuk',
      medical: 'Tıp / Sağlık',
      technical: 'Teknik',
      academic: 'Akademik',
      commercial: 'Ticari',
      financial: 'Finans',
      literary: 'Edebi',
      official: 'Resmi belge',
      localization: 'Web / Yazılım',
      general: 'Genel',
    },
    pendingTitle: 'Başvurunuz inceleniyor',
    pendingDesc: 'Tercüman başvurunuz alındı. Yönetim değerlendirmesinden sonra panel erişiminiz açılacaktır.',
    rejectedTitle: 'Başvuru onaylanmadı',
    rejectedDesc: 'Başvurunuz şu an için onaylanmadı. Bilgilerinizi güncelleyip tekrar deneyebilirsiniz.',
    reapply: 'Tekrar dene',
    cancelApplication: 'Başvuruyu iptal et',
    cancelConfirm: 'Başvurunuzu iptal etmek istediğinize emin misiniz? Kaydınız silinecek; dilerseniz daha sonra yeniden başvurabilirsiniz.',
    panelTitle: 'Tercüman Paneli',
    tabs: {
      profile: 'Profilim',
      pool: 'Tercüme Havuzu',
      active: 'Aktif İşler',
      pending: 'Onay Bekleyen',
      approved: 'Onaylanan',
      completed: 'Tamamlanan',
      wallet: 'Cüzdan',
    },
    soon: 'Bu bölüm bir sonraki adımda geliyor.',
    jobs: {
      empty: 'Bu bölümde şu an iş yok.',
      translator: 'Tercüman',
      sourceFiles: 'Kaynak belgeler',
      "trDeleted": "Kaydı silinmiş tercüman",
      "trBanned": "Yasaklı tercüman",
      translationFiles: 'Yüklenen çeviri',
      tracking: 'Kargo takip',
      rejectionReason: 'Reddedilme sebebi',
      // Tercüman — Aktif İşler
      chooseFiles: 'Çeviri dosyalarını seç',
      filesSelected: 'dosya seçildi',
      uploadHint: 'Çevirinizi ve gerekiyorsa kaynağın dijital hâlini yükleyin, sonra onaya gönderin.',
      submit: 'Onaya gönder',
      sending: 'Gönderiliyor…',
      needFiles: 'Lütfen en az bir dosya seçin.',
      uploadError: 'Dosyalar yüklenemedi. Lütfen tekrar deneyin.',
      submittedMsg: 'Çeviri onaya gönderildi.',
      actionError: 'İşlem gerçekleştirilemedi. Lütfen tekrar deneyin.',
      // Tercüman — Onay Bekleyen
      waitingApproval: 'Çeviriniz yönetim onayı bekliyor. Onaylanınca “Onaylanan” sekmesinde teslim adımını görürsünüz.',
      // Tercüman — Onaylanan (teslim)
      trackingPlaceholder: 'Kargo takip numarası / linki',
      needTracking: 'Kargo teslim için takip numarası zorunludur.',
      markShipped: 'Kargoya verdim — tamamla',
      markDelivered: 'Teslim ettim — tamamla',
      completedMsg: 'İş tamamlandı. Kazancınız cüzdanınıza eklendi.',
      // Admin — Onay Bekleyen (onay/red)
      reasonPlaceholder: 'Reddediyorsanız sebebini yazın (tercüman görecek)…',
      approve: 'Onayla',
      reject: 'Reddet',
      needReason: 'Reddetmek için bir sebep yazın.',
      approvedMsg: 'Çeviri onaylandı.',
      rejectedMsg: 'Çeviri reddedildi; tercümana geri gönderildi.',
      // Salt-okunur durum
      statusLabel: 'Durum',
      status_claimed: 'Devam ediyor',
      status_submitted: 'Onay bekliyor',
      status_approved: 'Onaylandı — teslim aşaması',
      status_completed: 'Tamamlandı',
    },
    pool: {
      loading: 'Havuz yükleniyor…',
      empty: 'Şu an dil çiftinize ve uzmanlık alanınıza uygun bekleyen sipariş yok.',
      error: 'Havuz yüklenemedi. Lütfen tekrar deneyin.',
      orderNo: 'Sipariş',
      service: 'Hizmet türü',
      documentType: 'Belge türü',
      langPair: 'Dil çifti',
      words: 'Kelime',
      pagesUnit: 'sayfa',
      deadline: 'Termin',
      daysUnit: 'iş günü',
      note: 'Müşteri notu',
      customerInfo: 'Müşteri bilgileri',
      deliveryInfo: 'Müşteri & teslimat bilgileri',
      customerName: 'Ad Soyad',
      customerEmail: 'E-posta',
      customerPhone: 'Telefon',
      deliveryAddress: 'Teslimat adresi',
      text: 'Sipariş metni',
      files: 'Belgeler',
      earning: 'Bu işten kazancınız',
      urgent: 'Acil',
      sworn: 'Yeminli',
      notary: 'Noter onaylı',
      cargo: 'Kargo teslim',
      digital: 'Dijital teslim',
      claim: 'İşi üstlen',
      claiming: 'Üstleniliyor…',
      claimed: 'İşi başarıyla üstlendiniz.',
      claimError: 'İş üstlenilemedi. Sipariş başkası tarafından alınmış olabilir; listeyi yenileyin.',
      ibanRequired: 'İş üstlenebilmek için önce IBAN bilgilerinizin yönetim tarafından onaylanması gerekir. Profilinizden IBAN girin; yönetim doğruladıktan sonra havuzdan iş alabilirsiniz.',
    },
    profile: {
      statusApproved: 'Onaylı tercüman',
      verifiedIban: 'IBAN doğrulandı',
      unverifiedIban: 'IBAN doğrulanmadı',
      current: 'Kayıtlı',
      edit: 'Bilgileri kaydet',
      ibanReminder: 'Ödemelerinizi alabilmek için lütfen IBAN bilgilerinizi girip kaydedin. Yönetim doğruladıktan sonra ödemeler bu hesaba yapılır.',
      lockedHint: 'Onaydan sonra değiştirilemez',
      revokeTitle: 'Bu değişiklik onayınızı düşürür',
      revokeWarning: 'Dil çifti, yeminlilik veya uzmanlık alanlarını değiştirirseniz hesabınız yeniden yönetim onayına düşer (beklemeye alınır). İşleriniz, kayıtlarınız ve cüzdanınız KORUNUR; yönetim onayladığında kaldığınız yerden devam edersiniz.',
      consent: 'Okudum, onaylıyorum',
      ibanReverify: 'IBAN bilgilerinizi değiştiriyorsunuz. Yeni IBAN yönetim onayına düşer; hesabınız açık kalır ancak IBAN onaylanana kadar havuzdan yeni iş üstlenemezsiniz.',
    },
    admin: {
      title: 'Yönetim Paneli',
      translatorsTab: 'Tercümanlar',
      applicationsTab: 'Başvurular',
      ibanTab: 'IBAN Onayları',
      ordersTab: 'Siparişler',
      paymentsTab: 'Ödemeler',
      noIbanPending: 'IBAN onayı bekleyen tercüman yok.',
      ibanHint: 'Yeni girilen veya değiştirilen IBAN’ları burada onaylayın. Onaylanana kadar tercüman havuzdan yeni iş üstlenemez.',
      ibanApprove: 'IBAN’ı onayla',
      paymentsHint: 'Ödeme günü (her ayın 1’i ve 16’sı) geldiğinde: ödemesini gerçekleştirdiğiniz her tercümanın dekontunu yükleyip “Ödendi”ye basın. Dekont yüklenmeden buton çalışmaz. Bakiyesi 0 olan tercümanlar burada listelenmez.',
      noPayments: 'Ödeme bekleyen (bakiyesi olan) tercüman yok.',
      paymentAmount: 'Ödenecek tutar',
      uploadReceipt: 'Dekont yükle',
      receiptUploaded: 'Dekont yüklendi',
      receiptRequired: 'Önce dekont yükleyin',
      uploading: 'Yükleniyor…',
      markPaid: 'Ödendi',
      paid: 'Ödeme kaydedildi ve tercümana dekontla birlikte bildirildi.',
      panelHint: 'Onaylı tercümanları profil bazlı takip edin, başvuruları değerlendirin ve tüm siparişlerin iş akışını yönetin.',
      summary: '{total} tercüman · {pending} başvuru bekliyor',
      applicationsSummary: '{total} başvuru · {pending} tanesi değerlendirme bekliyor',
      noApproved: 'Henüz onaylı tercüman yok.',
      noPending: 'Bekleyen başvuru yok.',
      noMatch: 'Filtrelere uyan kayıt yok.',
      loadError: 'Kayıtlar okunamadı. Veritabanı ve izinler (RLS) kurulu mu kontrol edin.',
      noApplications: 'Henüz tercüman kaydı yok.',
      filters: {
        namePlaceholder: 'Ad soyad ile ara…',
        country: 'Ülke',
        city: 'Şehir / İl',
        anyCountry: 'Tüm ülkeler',
        anyCity: 'Tüm şehirler',
        cityNeedsCountry: 'Önce ülke seçin',
        sourceLang: 'Kaynak dil',
        targetLang: 'Hedef dil',
        anyLang: 'Fark etmez',
        eitherDirection: 'Her iki yön (kaynak↔hedef)',
        expertise: 'Uzmanlık alanları',
        clear: 'Filtreleri temizle',
        results: '{n} kayıt',
      },
      orders: {
        loadError: 'Siparişler yüklenemedi. Lütfen tekrar deneyin.',
        empty: 'Henüz sipariş yok.',
        searchPlaceholder: 'Sipariş no veya müşteri adı ile ara…',
        results: '{n} sipariş',
        customer: 'Müşteri',
        translator: 'Tercüman',
        unassigned: 'Atanmadı',
        status: 'Durum',
        done: 'Tamamlandı',
        inProgress: 'Devam ediyor',
        completedOn: 'Tamamlanma',
        placedOn: 'Sipariş tarihi',
        total: 'Tutar',
        statusAvailable: 'Havuzda (üstlenilmedi)',
        statusClaimed: 'Tercümede',
        statusSubmitted: 'Onay bekliyor',
        statusApproved: 'Teslim aşamasında',
        statusCompleted: 'Tamamlandı',
        statusCancelled: 'İptal edildi',
      },
      profile: {
        back: 'Tercümanlara dön',
        adminOnly: 'Bu profil yalnızca yönetime özeldir; tercümanın kendisi göremez.',
        infoTitle: 'Bilgiler',
        walletTitle: 'Cüzdan',
        jobsTitle: 'İşler',
        noJobs: 'Bu tercümanın henüz işi yok.',
      },
      approve: 'Onayla',
      reject: 'Reddet',
      colLangs: 'Dil çiftleri',
      colExpertise: 'Uzmanlık',
      colLocation: 'Şehir / Ülke',
      swornBadge: 'Yeminli',
      cvDownload: "CV indir",
      returningBadge: 'Eski tercüman',
      ibanVerified: 'IBAN doğrulandı',
      ibanNotVerified: 'IBAN doğrulanmadı',
      verifyIban: 'IBAN doğrula',
      unverifyIban: 'Doğrulamayı kaldır',
      statusPending: 'Beklemede',
      statusApproved: 'Onaylı',
      statusRejected: 'Reddedildi',
      actionError: 'İşlem gerçekleştirilemedi.',
    },
    wallet: {
      total: 'Toplam kazanç',
      locked: 'Kilitli',
      withdrawable: 'Çekilebilir',
      paid: 'Ödenen',
      payInfo: 'Kazancınız iş tamamlanınca cüzdana eklenir; 7 gün kilitli kalır, sonra çekilebilir olur. Ödemeler her ayın 1\'i ve 16\'sında çekilebilir bakiyeye yapılır.',
      empty: 'Henüz kazanç yok. Tamamladığınız işlerin kazancı burada görünür.',
      entryOrder: 'Sipariş',
      date: 'Tarih',
      statusCol: 'Durum',
      amount: 'Tutar',
      statusPaid: 'Ödendi',
      statusUnlocked: 'Çekilebilir',
      statusPending: 'Kilitli',
      loadError: 'Cüzdan yüklenemedi. Lütfen tekrar deneyin.',
    },
    adminWallet: {
      firmShare: 'Firma payı (KDV dahil)',
      firmShareHint: 'Tamamlanan siparişlerin toplamından (KDV dahil) tercüman kazançları düşülmüş firma payı.',
      ciro: 'Toplam ciro (KDV dahil)',
      kdv: 'KDV (devlete)',
      payouts: 'Tercümanlara giden',
      net: 'Firma net payı',
      count: '{n} tamamlanan sipariş',
      empty: 'Henüz tamamlanan sipariş yok.',
      colOrder: 'Sipariş',
      colTranslator: 'Tercüman',
      colDate: 'Tarih',
      colTotal: 'Tutar (KDV dahil)',
      colPayout: 'Tercüman',
      colFirm: 'Firma payı',
      loadError: 'Cüzdan yüklenemedi. Lütfen tekrar deneyin.',
    },
  },

  authx: {
    rememberMe: 'Beni hatırla',
    showPassword: 'Şifreyi göster',
    hidePassword: 'Şifreyi gizle',
    forgot: 'Şifremi unuttum',
    forgotTitle: 'Şifre sıfırlama',
    forgotDesc: 'Kayıtlı e-posta adresinizi girin; şifrenizi yenilemeniz için tek kullanımlık bir bağlantı gönderelim.',
    forgotEmail: 'E-posta',
    forgotSubmit: 'Sıfırlama bağlantısı gönder',
    forgotSent: 'Bağlantı e-postanıza gönderildi. Gelen kutunuzu (ve spam klasörünü) kontrol edin.',
    forgotBack: 'Girişe dön',
    resetTitle: 'Yeni şifre belirle',
    resetDesc: 'Yeni şifrenizi girin ve tekrar yazarak onaylayın.',
    newPassword: 'Yeni şifre',
    newPasswordRepeat: 'Yeni şifre (tekrar)',
    mismatch: 'Şifreler birbiriyle aynı değil.',
    weak: 'Şifre en az 6 karakter olmalıdır.',
    resetSubmit: 'Şifreyi güncelle',
    resetSuccess: 'Şifreniz güncellendi. Artık yeni şifrenizle giriş yapabilirsiniz.',
    resetInvalid: 'Bağlantı geçersiz veya süresi dolmuş. Lütfen yeniden sıfırlama bağlantısı isteyin.',
    goLogin: 'Giriş yap',
    err: {
      invalidCredentials: 'E-posta veya şifre hatalı. Lütfen bilgilerinizi kontrol edip tekrar deneyin.',
      emailNotConfirmed: 'E-posta adresiniz henüz doğrulanmamış. Gelen kutunuzdaki doğrulama bağlantısına tıklayın.',
      alreadyRegistered: 'Bu e-posta adresi zaten kayıtlı. Giriş yapmayı veya şifrenizi sıfırlamayı deneyin.',
      weakPassword: 'Şifre en az 6 karakter olmalıdır.',
      otpInvalid: 'Doğrulama kodu hatalı veya süresi dolmuş. Yeni bir kod isteyin.',
      rateLimited: 'Çok fazla deneme yaptınız. Lütfen bir süre bekleyip tekrar deneyin.',
      generic: 'Bir şeyler ters gitti. Lütfen daha sonra tekrar deneyin.',
    },
  },

  delivery: {
    ready: 'Çeviriniz hazır',
    download: 'Çeviriyi indir',
    hint: 'Çeviriniz ayrıca e-posta adresinize de gönderildi. Gelen kutunuzu (ve spam klasörünü) kontrol edin.',
  },

  partnerPanel: {
    qrDownload: "QR kodunu indir",
    qrAlt: "Davet QR kodu",
    colMembers: "Üye",
    sectorAll: "Tüm sektörler",
    back: "Geri",
    noPartners: "Henüz partner yok.",
    "delPartner": "Kaydı silinmiş partner",
    "banPartner": "Yasaklı partner",
    tabPayments: "Ödemeler",
    payHint: "Ödemeler her ayın 2’si ve 17’sinde yapılır. Ödeme gününde ödemesini gerçekleştirdiğiniz her partnerin dekontunu yükleyip “Ödendi”ye basın; dekont yüklenmeden buton çalışmaz. Yalnızca çekilebilir (7 günü dolmuş) bakiyeler listelenir; bakiyesi 0 olan partnerler görünmez.",
    noPayments: "Ödeme bekleyen (bakiyesi olan) partner yok.",
    paid: "Ödeme kaydedildi ve partnere bildirildi.",
    noApplications: "Bekleyen başvuru yok.",
    approve: "Onayla",
    reject: "Reddet",
    noIban: "Onay bekleyen IBAN yok.",
    approveIban: "IBAN’ı onayla",
    adminTitle: "Partner Yönetimi",
    tabApplications: "Başvurular",
    tabIban: "IBAN Onayları",
    tabPartners: "Partnerler",
    colPartner: "Partner",
    colCompany: "Şirket/Kurum",
    partnerShareLabel: "Partner payı",
    adminNet: "Kalan (firma)",
    fltPartner: "Partner adı",
    fltCompany: "Şirket/kurum",
    yourEarning: "Sizin kazancınız",
    tabAllOrders: "Tüm Siparişler",
    fltOrderNo: "Sipariş no",
    fltDateFrom: "Başlangıç",
    fltDateTo: "Bitiş",
    custFilter: "İsimle ara",
    custEmpty: "Henüz getirdiğiniz bir üye yok. Davet bağlantınızı paylaşın.",
    colName: "Ad Soyad",
    colEmail: "E-posta",
    colPhone: "Telefon",
    colJoined: "Kayıt tarihi",
    custOrderCount: "Sipariş",
    custTotal: "Toplam tutar",
    ordEmpty: "Bu aşamada sipariş yok.",
    colOrderNo: "Sipariş",
    colCustomer: "Müşteri",
    colService: "Hizmet",
    colLangs: "Diller",
    colAmount: "Tutar",
    colDate: "Tarih",
    loadError: "Yüklenemedi. Lütfen tekrar deneyin.",
    walPayInfo: "Kazancınız iş tamamlanınca cüzdana eklenir; 7 gün kilitli kalır, sonra çekilebilir olur. Ödemeler her ayın 2’si ve 17’sinde çekilebilir bakiyeye yapılır.",
    ibanPending: "IBAN bilgileriniz yönetim onayı bekliyor.",
    ibanPolicy: "IBAN ve IBAN sahibi bilgileriniz yönetim tarafından onaylanana kadar ödeme alamazsınız. Bu süreçte elde ettiğiniz kazançlar cüzdanınızda birikmeye devam eder. Bilgileriniz onaylandığında, satışınızın üzerinden 7 gün geçmiş ve kilidi kalkmış bakiyelerinizi çekebilirsiniz.",
    fillRequired: "Lütfen zorunlu alanları doldurun.",
    phoneLockNote: "Telefon numaranız, SMS doğrulaması devreye girdiğinde güncellenebilecek.",
    panelTitle: "Partner Paneli",
    tabProfile: "Profilim",
    tabCustomers: "Müşterilerim",
    tabOrdersNew: "Alınan Siparişler",
    tabOrdersActive: "İşleme Alındı",
    tabOrdersDelivery: "Teslimat Bekleniyor",
    tabOrdersDone: "Tamamlanan",
    tabWallet: "Cüzdan",
    soon: "Çok yakında.",
    save: "Kaydet",
    saved: "Kaydedildi.",
    statusApproved: "Onaylı partner",
    ibanVerified: "IBAN doğrulandı",
    ibanNotVerified: "IBAN doğrulanmadı",
    ibanReminder: "Ödeme alabilmek için IBAN ve IBAN sahibi bilgilerinizi girin.",
    refCodeLabel: "Davet kodunuz",
    seoTitle: "Partner Paneli",
    seoDesc: "İş ortağı başvurunuzu yapın ve davet bağlantınızı buradan alın.",
    loading: "Yükleniyor…",
    loginTitle: "Partner girişi",
    loginDesc: "Başvuru yapmak veya panelinize erişmek için giriş yapın ya da üye olun.",
    login: "Giriş yap / Üye ol",
    setupTitle: "Kurulum tamamlanmadı",
    setupDesc: "Partner sistemi henüz hazır değil.",
    applyTitle: "İş Ortağı Başvurusu",
    applyDesc: "Bilgilerinizi doldurun; başvurunuz onaylandığında davet bağlantınız etkinleşir.",
    applyNote: "Başvurunuz kısa süre içinde değerlendirilecektir.",
    sectorOther: "Sektörünüzü yazın",
    submit: "Başvuruyu gönder",
    submitting: "Gönderiliyor…",
    saveError: "Başvuru kaydedilemedi. Lütfen tekrar deneyin.",
    pendingTitle: "Başvurunuz alındı",
    pendingDesc: "Başvurunuz inceleniyor. Onaylandığında davet bağlantınız ve paneliniz burada etkinleşecek.",
    cancelApplication: "Başvuruyu iptal et",
    rejectedTitle: "Başvuru onaylanmadı",
    rejectedDesc: "Bu başvuru onaylanmadı. Bilgilerinizi güncelleyip tekrar başvurabilirsiniz.",
    reapply: "Tekrar başvur",
    approvedTitle: "Partner hesabınız aktif",
    approvedDesc: "Aşağıdaki davet bağlantısıyla gelip üye olan müşteriler kalıcı olarak hesabınıza bağlanır.",
    panelSoon: "Müşterileriniz, siparişler ve cüzdanınızın yer alacağı ayrıntılı panel çok yakında burada olacak.",
    verifyTitle: "E-posta doğrulama",
    verifyDesc: "Ödeme alabilmeniz için e-posta adresinizi doğrulayın. Size bir doğrulama kodu göndereceğiz.",
    verifiedLabel: "E-posta doğrulandı",
    sendCode: "Doğrulama kodu gönder",
    sending: "Gönderiliyor…",
    codeSent: "Kodu e-postanıza gönderdik. Gelen kutunuzu ve spam klasörünü kontrol edin.",
    codePlaceholder: "6 haneli kod",
    verifyBtn: "Doğrula",
    verifying: "Doğrulanıyor…",
    verifyError: "Kod geçersiz veya süresi dolmuş. Yeni bir kod isteyin.",
    refTitle: "Davet bağlantınız",
    refDesc: "Bu bağlantıyı paylaşın; bağlantıyla gelip üye olan müşteriler kalıcı olarak size bağlanır.",
    refCopy: "Bağlantıyı kopyala",
    refCopied: "Kopyalandı",
  },
  adminHub: {
    tabMembers: "Üyeler",
    tabTranslators: "Tercümanlar",
    tabPartners: "Partnerler",
    tabManage: "Üyeleri Yönet",
    bMember: "Üye",
    bCustomer: "Müşteri",
    bTranslator: "Tercüman",
    bPartner: "Partner",
    bReferred: "Partnerden",
    bBanned: "Yasaklı",
    "tabDeleted": "Kaydı Silinen Kullanıcılar",
    "tabBanned": "Yasaklanan Kullanıcılar",
    "delMember": "Kaydı silinmiş üye",
    "delCustomer": "Kaydı silinmiş müşteri",
    "delTranslator": "Kaydı silinmiş tercüman",
    "delPartner": "Kaydı silinmiş partner",
    "banMember": "Yasaklı üye",
    "banCustomer": "Yasaklı müşteri",
    "banTranslator": "Yasaklı tercüman",
    "banPartner": "Yasaklı partner",
    "delHint": "Kaydı silinen hesaplar. Tüm geçmiş kayıtları (sipariş, tercüme, partner) korunur.",
    "delNone": "Kaydı silinen kullanıcı yok.",
    "delAt": "Silinme tarihi",
    "banHint": "Yasaklanan hesaplar. Tüm geçmiş kayıtları korunur.",
    "banNone": "Yasaklı kullanıcı yok.",
    filterAll: "Tümü",
    memHint: "Admin hariç, sistemde hesabı olan tüm üyeler.",
    memNone: "Üye yok.",
    trHint: "Sistemdeki tüm tercümanlar.",
    trNone: "Tercüman kaydı yok.",
    trJoinedRole: "Tercümanlık kaydı",
    prtHint: "Sistemdeki tüm partnerler.",
    prtNone: "Partner kaydı yok.",
    prtCompany: "Şirket/Kurum",
    prtJoinedRole: "Partnerlik kaydı",
    mgHint: "Üyeleri yönetin: hesabı yasaklayın veya silin. İşlemler onay ister.",
    mgNone: "Üye yok.",
    banBtn: "Yasakla",
    unbanBtn: "Yasağı kaldır",
    deleteBtn: "Hesabı sil",
    banConfirm: "Bu üyeyi yasaklamak istediğinize emin misiniz? Üye giriş yapamayacak.",
    unbanConfirm: "Bu üyenin yasağını kaldırmak istediğinize emin misiniz?",
    deleteConfirm: "Bu hesabın girişi kalıcı olarak kapatılacak ve kayıt arşivlenecek. Tüm sipariş, tercüme ve partner kayıtları ile iletişim bilgileri korunacak. Devam edilsin mi?",
    confirmYes: "Evet, devam et",
    confirmNo: "Vazgeç",
    actionDone: "İşlem tamamlandı.",
    actionFail: "İşlem başarısız. Lütfen tekrar deneyin.",
    tabChats: "Chatbot Kayıtları",
    tabCustomers: 'Müşteriler',
    tabUploads: 'Yüklenen Dosyalar',
    loading: 'Yükleniyor…',
    loadError: 'Yüklenemedi. Lütfen tekrar deneyin.',
    back: 'Geri',
    custHint: "En az bir sipariş vermiş, sistemde kayıtlı tüm müşteriler.",
    custSearch: 'Ad, e-posta veya telefon ara…',
    custName: 'Ad Soyad',
    custEmail: 'E-posta',
    custPhone: 'Telefon',
    custOrders: 'Sipariş',
    custTotal: 'Toplam tutar',
    custJoined: 'Kayıt tarihi',
    custNone: 'Henüz müşteri kaydı yok.',
    custOrderList: 'Siparişler',
    custNoOrders: 'Bu müşterinin siparişi yok.',
    orderNo: 'Sipariş No',
    orderDate: 'Tarih',
    orderStatus: 'Durum',
    upHint: 'Fiyat sayfasında yüklenen tüm dosyalar (siparişe dönmese de kaydedilir).',
    upFile: 'Dosya',
    upUploader: 'Yükleyen',
    upWhen: 'Tarih',
    upWords: 'Kelime',
    upSize: 'Boyut',
    upDownload: 'İndir',
    upNone: 'Henüz yüklenen dosya yok.',
    upGuest: 'Misafir',
  },

  smsVerify: {
    sendCode: 'Kod gönder',
    resend: 'Kodu tekrar gönder',
    codeLabel: 'SMS kodu',
    confirm: 'Onayla',
    verified: 'Telefon doğrulandı',
    sent: 'Kod telefonunuza gönderildi.',
    mustVerify: 'Devam etmek için telefon numaranızı SMS ile doğrulayın.',
    reverifyHint: 'Telefon numaranızı değiştirirseniz, yeni numarayı SMS ile yeniden doğrulamanız gerekir.',
    invalid: 'Kod hatalı. Lütfen tekrar deneyin.',
    expired: 'Kodun süresi doldu. Lütfen yeni bir kod isteyin.',
    rateLimited: 'Çok sık denediniz. Lütfen biraz bekleyip tekrar deneyin.',
    notConfigured: 'SMS doğrulama şu anda kullanılamıyor. Lütfen daha sonra tekrar deneyin veya destek ile iletişime geçin.',
    sendFailed: 'Kod gönderilemedi. Numaranızı kontrol edip tekrar deneyin.',
    enterPhone: 'Lütfen önce geçerli bir telefon numarası girin.',
    error: 'Bir sorun oluştu. Lütfen tekrar deneyin.',
    devCode: 'Test modu — doğrulama kodunuz: {code}',
  },

  notFound: {
    seo: { title: 'Sayfa bulunamadı', description: 'Aradığınız sayfa bulunamadı.' },
    title: 'Sayfa bulunamadı',
    desc: 'Aradığınız sayfa taşınmış veya hiç var olmamış olabilir.',
    home: 'Anasayfaya dön',
  },
} as const
