import type { PartialDictionary } from '@/types/i18n'
import { FAQ_CATEGORIES_EN, FAQ_ITEMS_EN } from '@/content/faq-data.en'

/**
 * ENGLISH — full base translation. English is the fallback base (§10):
 * TR (source) <- EN (base) <- other locales. Keeping EN complete means no
 * Turkish leaks into any other language; untranslated keys fall back to EN.
 * NOTE: FAQ questions/answers (faq.categories / faq.items) are shared Turkish
 * data (content/faq-data.ts) and are intentionally not overridden here — they
 * require a per-locale FAQ dataset, handled as a separate task.
 */
export const en: PartialDictionary = {
  common: {
      "brand": "TercümExpert",
    tagline: 'Your reliable partner in professional translation services.',
    nav: {
      home: 'Home',
      services: 'Services',
      quote: 'Get a Quote',
      corporate: 'Corporate',
      partnership: 'Partnership',
      blog: 'Blog',
      faq: 'FAQ',
      contact: 'Contact',
    },
    actions: {
      getQuote: 'Get a Quote',
      calculatePrice: 'Calculate Price',
      uploadDocument: 'Upload Document',
      whatsapp: 'Chat on WhatsApp',
      learnMore: 'Learn More',
      viewAll: 'View All',
      showMore: 'Show More',
      showLess: 'Show Less',
      send: 'Send',
      apply: 'Apply',
      order: 'Place Order',
      contactUs: 'Contact Us',
      openMenu: 'Open menu',
      closeMenu: 'Close menu',
      selectLanguage: 'Select language',
      skipToContent: 'Skip to content',
      login: 'Log In',
      logout: 'Log Out',
      account: 'My Account',
    },
    states: {
      loading: 'Loading…',
      error: 'Something went wrong. Please try again.',
      required: 'This field is required.',
      demoNotice: 'Demo: form data is not yet sent to a server.',
      unverified: 'To be verified',
    },
    topbar: {
      phoneLabel: 'Phone',
      emailLabel: 'Email',
      hoursLabel: 'Working Hours',
      afterHours: 'After-hours urgent translation support is available.',
      workingHours: 'Weekdays 09:00 - 18:00 | After-hours service available',
    },
  },

  home: {
    seo: {
      title: 'TercümExpert — Professional Translation Services',
      description:
        'Sworn translation, notarization and corporate translation solutions. Upload your document, get an instant preliminary quote and professional delivery.',
    },
    hero: {
      title: 'Your Reliable Partner in Professional',
      titleAccent: 'Translation Services',
      subtitle: 'Upload your document, see the price, get professional delivery.',
      support: 'Sworn translation • Notarization • Corporate solutions',
    },
    trust: {
      title: 'Why do they trust us?',
      items: [
        { key: 'languages', label: '50+ Languages' },
        { key: 'delivery', label: '24-Hour Delivery' },
        { key: 'notary', label: 'Notary Approval' },
        { key: 'quality', label: 'Quality Assurance' },
      ],
    },
    stats: {
      title: 'TercümExpert in Numbers',
      note: 'The figures below are not presented as definitive claims until verified.',
      labels: {
        satisfaction: 'Customer Satisfaction',
        completed: 'Completed Jobs',
        languages: 'Language Support',
        corporate: 'Corporate Clients',
      },
    },
    howItWorks: {
      title: 'How does it work?',
      subtitle: 'Professional translation in five steps.',
      steps: [
        { key: 'upload', title: 'Upload', desc: 'Upload your document securely.' },
        { key: 'select', title: 'Select', desc: 'Choose the language and service type.' },
        { key: 'confirm', title: 'Confirm', desc: 'Confirm your order.' },
        { key: 'track', title: 'Track', desc: 'Follow the process in real time.' },
        { key: 'receive', title: 'Receive', desc: 'Get your professional delivery.' },
      ],
    },
    services: {
      title: 'Our Services',
      subtitle: 'Expert translation for every document type.',
    },
    why: {
      title: 'Why TercümExpert?',
      subtitle: 'The features that set us apart from the competition',
      features: [
        { key: 'autoQuote', title: 'Automatic price calculation', desc: 'A preliminary price in seconds.' },
        { key: 'whatsapp', title: 'Quick WhatsApp quote', desc: 'One-tap contact.' },
        { key: 'terminology', title: 'Terminology management', desc: 'Consistent, corporate language.' },
        { key: 'revision', title: 'Revision rights', desc: 'A satisfaction-focused process.' },
        { key: 'languages', title: '50+ language support', desc: 'Broad language-pair coverage.' },
        { key: 'terms', title: 'Corporate term system', desc: 'Flexible payment for companies.' },
      ],
    },
    corporateCta: {
      title: 'Corporate Solutions',
      desc: 'Professional language services with terminology management, term options and a dedicated account manager tailored to your company.',
      action: 'Request a Corporate Quote',
    },
    partnershipTeaser: {
      title: 'Partnership Program',
      subtitle: 'Earn 20% commission on every customer you refer to us.',
      items: [
        { key: 'commission', title: 'Transparent Commission', desc: '20% commission for every referral (subject to agreement). Transparent earnings with a real-time tracking panel.' },
        { key: 'qr', title: 'QR Code System', desc: 'Easy customer tracking with business-card integration. Web and WhatsApp QR codes.' },
      ],
      cta: 'Apply as a Partner',
    },
    testimonials: {
      title: 'Customer Reviews',
      subtitle: 'Real customer reviews will be added here before launch.',
      placeholderNote: 'Placeholder — real reviews will be integrated.',
      items: [
        { key: 't1', role: 'Law Firm' },
        { key: 't2', role: 'Healthcare Organization' },
        { key: 't3', role: 'Corporate Client' },
        { key: 't4', role: 'Individual Client' },
      ],
    },
    blogTeaser: {
      title: 'Blog',
      subtitle: 'Current content from the world of translation',
      viewAll: 'View All Blog Posts',
    },
    finalCta: {
      title: 'Get Started Now',
      desc: 'Upload your documents, get an instant quote and benefit from professional translation services.',
      primary: 'Get a Quote',
      secondary: 'Contact Us',
    },
  },

  services: {
    seo: {
      title: 'Translation Services',
      description:
        'Sworn, notarized, legal, technical, medical and academic translation plus web/mobile localization. Document types, process, delivery and language pairs.',
    },
    hero: {
      title: 'Translation Services',
      subtitle: 'Translation with the right terminology for each field of expertise.',
    },
    process: {
      title: 'How does the process work?',
      steps: [
        { title: 'Document review', desc: 'The document type and purpose are assessed.' },
        { title: 'Expert matching', desc: 'A specialist translator in the field is assigned.' },
        { title: 'Translation & editing', desc: 'Translation and an independent final review.' },
        { title: 'Approval & delivery', desc: 'Notary/apostille if required, then delivery.' },
      ],
    },
    delivery: {
      title: 'Delivery options',
      items: ['Digital delivery (PDF/DOCX)', 'Physical document delivery', 'Urgent delivery'],
    },
    notaryApostille: {
      title: 'Notary and apostille relationship',
      desc: 'When required, sworn translation is made valid for official institutions through notary approval and the apostille process. The exact requirement depends on the institution where the document will be submitted.',
    },
    fullService: {
      title: 'Turnkey, Delivered to Your Door',
      note: 'Send us your documents and we will manage the entire process — translation, notary approval and apostille included. Your finished documents arrive at your door by courier. Focus on your work and leave the rest to us.',
    },
    cta: {
      title: 'Not sure which service you need?',
      desc: 'Upload your document and we will show you the most suitable service and price.',
    },
    documentTypesTitle: 'Suitable document types',
  },

  serviceItems: {
    sworn: {
      name: 'Sworn Translation',
      short: 'Officially valid translation with a sworn translator’s signature and stamp.',
      benefits: ['Valid at official institutions', 'Sworn translator approval', 'Fast process'],
    },
    notarized: {
      name: 'Notarized Translation',
      short: 'Notary approval of a sworn translation.',
      benefits: ['Notary certification', 'Suitable for official applications', 'We handle the process'],
    },
    apostille: {
      name: 'Apostille Process Support',
      short: 'Guidance through the apostille process for validity abroad.',
      benefits: ['International validity', 'Process consultancy', 'Institution guidance'],
    },
    legal: {
      name: 'Legal Translation',
      short: 'Translation with command of terminology for contracts, court and official documents.',
      benefits: ['Legal terminology', 'Confidentiality assurance', 'Expert translator'],
    },
    technical: {
      name: 'Technical Translation',
      short: 'Consistent translation for manuals, specifications and technical documents.',
      benefits: ['Terminology management', 'Format preserved', 'Industry expertise'],
    },
    medical: {
      name: 'Medical Translation',
      short: 'Precise translation for reports, package inserts and medical documents.',
      benefits: ['Medical terminology', 'Accuracy-focused', 'Confidentiality'],
    },
    academic: {
      name: 'Academic Translation',
      short: 'Academic language for theses, articles and diploma translations.',
      benefits: ['Academic style', 'Source consistency', 'On-time delivery'],
    },
    localization: {
      name: 'Web and Mobile Localization',
      short: 'Culturally appropriate localization of websites and applications.',
      benefits: ['Cultural adaptation', 'Technical integration', 'SEO compatibility'],
    },
  },

  corporate: {
    statsLabels: {
      corporate: 'Corporate clients',
      discount: 'Bulk order discount',
      term: 'Payment term',
    },
    seo: {
      title: 'Corporate Solutions',
      description:
        'Professional language services for companies with terminology management, term options, bulk orders and a dedicated account manager.',
    },
    hero: {
      title: 'Corporate Solutions',
      subtitle:
        'Professional language services with terminology management, term options and a dedicated account manager tailored to your company.',
      primaryCta: 'Request a Corporate Quote',
      secondaryCta: 'Send Email',
    },
    features: {
      title: 'Corporate Features',
      subtitle: 'Solutions tailored to your business',
      items: [
        {
          key: 'custom',
          icon: 'Target',
          title: 'Customized Service',
          points: ['Fixed terminology', 'Preserving brand tone of voice', 'Dedicated account manager', 'Style guide creation'],
        },
        {
          key: 'volume',
          icon: 'BarChart3',
          title: 'Bulk Processing and Terms',
          points: ['Monthly translation plans', 'Bulk order discounts', 'Terms up to 30 days', 'Invoicing system'],
        },
        {
          key: 'security',
          icon: 'Lock',
          title: 'Privacy and Security',
          points: ['NDA protocol', 'Encrypted file transfer', 'KVKK-compliant processes'],
        },
      ],
    },
    whyPackage: {
      title: 'Why a Corporate Package?',
      items: [
        {
          key: 'terminology',
          icon: 'Building2',
          title: 'Fixed Terminology Management',
          desc: 'We build a term bank specific to your company. Your brand language is preserved across all translations and we ensure consistency. We take care to use the same terms in every project.',
        },
        {
          key: 'manager',
          icon: 'Users',
          title: 'Dedicated Account Manager',
          desc: 'Your dedicated account manager follows all your processes. With an accessible support line, we are by your side in urgent situations.',
        },
        {
          key: 'security',
          icon: 'ShieldCheck',
          title: 'Privacy and Security',
          desc: 'We work under an NDA protocol. Your data is safe with a strong security infrastructure, encrypted file transfer and KVKK-compliant processes.',
        },
      ],
    },
    payment: {
      title: 'Payment Options',
      subtitle: 'Flexible payment plans suited to your business',
      recommendedLabel: 'RECOMMENDED',
      options: [
        {
          key: 'standard',
          label: 'Instant Payment',
          heading: 'Standard',
          desc: 'Payment by credit card or bank transfer after each order',
          points: ['Credit card installments', 'Instant delivery'],
          recommended: false,
        },
        {
          key: 'term',
          label: 'Monthly Term',
          heading: '15-30 Days',
          desc: 'Monthly consolidated invoicing and term option',
          points: ['30-day term', 'Bulk discount', 'Monthly report'],
          recommended: true,
        },
      ],
    },
    form: {
      title: 'Corporate Package Application',
      desc: 'Fill out the form and our expert team will contact you',
      fields: {
        company: 'Company Name',
        contactName: 'Contact Full Name',
        email: 'Email',
        phone: 'Phone',
        need: 'Tell us about your translation needs',
        consent: 'I have read and approve the <kvkk>KVKK Disclosure Statement</kvkk>.',
      },
      submit: 'Submit Application',
      success: 'Your application has been received. We will get back to you as soon as possible.',
      note: 'We will get back to you within 1 business day.',
    },
  },

  partnership: {
    seo: {
      title: 'Partnership Program',
      description:
        'Earn commission on every customer you refer. Transparent reporting, QR-code referrals and professional support.',
    },
    hero: {
      title: 'Partnership Program',
      value: 'Earn 20% commission on every customer you refer to us.',
      subtitle: 'A transparent system, reliable payments, long-term cooperation.',
      cta: 'Apply Now',
    },
    advantages: {
      title: 'Partner Advantages',
      subtitle: 'Why become a TercümExpert partner?',
      items: [
        { key: 'commission', icon: 'Wallet', title: '20% Commission Guarantee', desc: 'A transparent commission system for every customer you refer.' },
        { key: 'qr', icon: 'QrCode', title: 'QR-Code Referral', desc: 'Easy customer tracking with business-card integration.' },
        { key: 'reporting', icon: 'BarChart3', title: 'Transparent Reporting', desc: 'Real-time commission and customer tracking panel.' },
        { key: 'support', icon: 'Users', title: 'Professional Support', desc: 'A dedicated partner support line and account manager.' },
      ],
    },
    howItWorks: {
      title: 'How Does It Work?',
      steps: [
        { title: 'Apply', desc: 'Fill out the online application form. Share your company information and contact details. Your application is reviewed within 1 business day.' },
        { title: 'Become a Partner', desc: 'Once your application is approved, you gain access to your dedicated partner panel. Your QR codes and referral links are ready.' },
        { title: 'Refer Customers', desc: 'Refer your customers to us via QR code, a custom link or business card. Every referral is automatically recorded in the system.' },
        { title: 'Earn Commission', desc: 'You earn 20% commission every time a customer you referred places an order. You receive automatic payments every 15 days.' },
      ],
    },
    sectors: {
      title: 'Target Sectors',
      subtitle: 'Which sectors is it ideal for?',
      items: [
        { key: 'law', icon: 'Scale', title: 'Law Firms', desc: 'Need for sworn translation of case files, contracts and legal documents.' },
        { key: 'visa', icon: 'Plane', title: 'Visa Consultancy', desc: 'Documents requiring sworn translation such as passports, diplomas and civil records.' },
        { key: 'education', icon: 'GraduationCap', title: 'Education Consultancy', desc: 'Sworn translation of student documents and apostille processes.' },
        { key: 'health', icon: 'HeartPulse', title: 'Health Tourism', desc: 'Translation of medical reports, patient files and health documents.' },
        { key: 'patent', icon: 'Building2', title: 'Patent/Trademark Offices', desc: 'Technical translation of patent, trademark registration and legal documents.' },
        { key: 'realestate', icon: 'Home', title: 'Real Estate Offices', desc: 'Title deed, contract and official document translation for foreign investors.' },
        { key: 'hr', icon: 'Briefcase', title: 'HR Consultancy', desc: 'CV, diploma and reference letter translation for overseas placement.' },
        { key: 'software', icon: 'Code', title: 'Software Companies', desc: 'Web and mobile app localization, technical document translation.' },
      ],
    },
    commission: {
      title: 'Commission Structure',
      stats: {
        commissionLabel: 'Standard Commission',
        commissionSub: 'On every order',
        periodUnit: 'Days',
        periodLabel: 'Payment period',
        feeLabel: 'Start-up Fee',
        feeSub: 'Completely free',
      },
      exampleTitle: 'Sample Earnings Calculation',
      exampleOrderLabel: 'Order from the customer you referred',
      exampleRateLabel: 'Commission rate',
      exampleEarningLabel: 'Your earnings',
      note: 'Commission rates and terms are subject to the partner agreement.',
    },
    form: {
      title: 'Partner Application Form',
      subtitle: 'Fill out the form and we will get back to you within 1 business day.',
      fields: {
        company: 'Company/Organization Name',
        sector: 'Sector',
        contactName: 'Contact Full Name',
        titleRole: 'Title',
        email: 'Email',
        phone: 'Phone',
        potential: 'Your estimated monthly referral potential',
        note: 'Any notes you would like to add',
        agreement: 'I have read and accept the terms of the <partnership>partner agreement</partnership>.',
      },
      sectorPlaceholder: 'Select',
      sectorOptions: ['Law Firm', 'Visa Consultancy', 'Education Consultancy', 'Health Tourism', 'Patent/Trademark Office', 'Real Estate', 'HR Consultancy', 'Software', 'Other'],
      potentialOptions: ['1-5 customers', '5-10 customers', '10-20 customers', '20+ customers'],
      submit: 'Submit Application',
      success: 'Your application has been received. We will contact you.',
      note: 'Your application will be reviewed within 1 business day.',
    },
  },

  quote: {
    seo: {
      title: 'Instant Price Calculation',
      description: 'Upload your document or enter the details and get your instant preliminary quote.',
    },
    hero: {
      title: 'Instant Price Calculation',
      subtitle: 'Upload your document or enter the details and get an instant preliminary quote.',
    },
    upload: {
      heading: 'Upload Your Documents',
      privacy: 'Your data is kept confidential',
      tabFile: 'Upload File',
      tabText: 'Enter Text',
      chooseFile: 'Choose Your Documents',
      formats: '.docx, .xlsx, .pdf, .pptx, .jpg, .png and 50+ formats accepted · Max 100MB per file',
      dropHint: 'You can drag and drop one or more files into this area.',
      textPlaceholder: 'Paste or type your text here…',
      totalWords: 'Total word count',
      extracting: 'Counting words…',
      wordsUnit: 'words',
      remove: 'Remove',
      unsupported:
        'Automatic word counting was not possible for this file type. Please paste the text using "Enter Text"; the count will be verified by our team when quoting.',
      empty:
        'No selectable text was found in the file (it may be scanned/an image). Please use "Enter Text", or the count will be verified during quoting.',
      error: 'The file could not be read. Please try again or use "Enter Text".',
      tooLarge: 'The file cannot be larger than 100MB.',
      needInput: 'For a price, please upload a file or enter text.',
    },
    fields: {
      upload: 'Upload Document (optional)',
      uploadHint: 'PDF, DOC, DOCX or TXT — max 10 MB',
      sourceLang: 'Source Language',
      targetLang: 'Target Language',
      serviceType: 'Service Type',
      documentType: 'Document Type',
      wordCount: 'Estimated Word Count',
      wordCountHint: 'Use the slider or enter the number manually.',
      options: 'Additional options',
      calculate: 'Calculate Price',
    },
    options: {
      urgent: 'Urgent Delivery',
      sworn: 'Sworn (Certified) Translation',
      notarization: 'Notary Approval',
      apostille: 'Apostille Process Support',
      physicalDelivery: 'Physical Delivery',
      swornNotaryHint: 'Notary approval already covers sworn translation; you only need to select the single option that suits your need.',
      physicalRequiredHint: 'Sworn and notarized translations are delivered as signed/stamped originals, so physical delivery is added automatically.',
    },
    areas: {
      academic: 'Academic Translation',
      legal: 'Legal Translation',
      official: 'Official Document Translation',
      medical: 'Medical Translation',
      technical: 'Technical Translation',
      commercial: 'Commercial & Financial Translation',
      localization: 'Web & Mobile Localization',
      literary: 'Literary Translation',
      general: 'General / Other Translation',
    },
    docTypes: {
      diploma: 'Diploma',
      transcript: 'Transcript',
      'student-certificate': 'Student Certificate',
      'diploma-supplement': 'Diploma Supplement',
      thesis: 'Thesis',
      'reference-letter': 'Reference Letter',
      'academic-article': 'Academic Article',
      contract: 'Contract',
      'court-decision': 'Court Decision',
      'power-of-attorney': 'Power of Attorney',
      petition: 'Petition',
      'consent-statement': 'Consent Statement',
      'warning-notice': 'Warning Notice',
      'litigation-doc': 'Litigation Documents',
      passport: 'Passport',
      'id-card': 'ID Card',
      'civil-registry': 'Civil Registry Extract',
      'birth-certificate': 'Birth Certificate',
      'marriage-certificate': 'Marriage Certificate',
      'driver-license': 'Driver License',
      'criminal-record': 'Criminal Record',
      'military-status': 'Military Status Document',
      'medical-report': 'Medical Report',
      epicrisis: 'Epicrisis (Discharge Summary)',
      prescription: 'Prescription',
      'lab-result': 'Lab / Test Result',
      'medical-article': 'Medical Article',
      'patient-consent': 'Patient Consent Form',
      'user-manual': 'User Manual',
      'technical-spec': 'Technical Specification',
      patent: 'Patent',
      'product-catalog': 'Product Catalog',
      datasheet: 'Datasheet',
      'installation-guide': 'Installation Guide',
      'safety-data-sheet': 'Safety Data Sheet',
      invoice: 'Invoice',
      'balance-sheet': 'Balance Sheet',
      'commercial-contract': 'Commercial Contract',
      'financial-report': 'Financial Report',
      'tax-document': 'Tax Document',
      'activity-certificate': 'Activity Certificate',
      'bank-statement': 'Bank Statement',
      website: 'Website',
      'mobile-app': 'Mobile App',
      'software-ui': 'Software UI',
      game: 'Game',
      'marketing-content': 'Marketing Content',
      subtitle: 'Subtitles',
      'e-commerce': 'E-commerce Content',
      book: 'Book',
      'short-story': 'Short Story',
      poem: 'Poem',
      screenplay: 'Screenplay',
      essay: 'Essay',
      article: 'Article',
      'general-document': 'General Document',
      correspondence: 'Correspondence / Letter',
      cv: 'CV / Resume',
      presentation: 'Presentation',
      other: 'Other',
    },
    languages: {
      tr: 'Turkish',
      en: 'English',
      de: 'German',
      fr: 'French',
      es: 'Spanish',
      it: 'Italian',
      ru: 'Russian',
      ar: 'Arabic',
      nl: 'Dutch',
      az: 'Azerbaijani',
      pl: 'Polish',
      bg: 'Bulgarian',
      pt: 'Portuguese',
      da: 'Danish',
    },
    documentTypes: {
      diploma: 'Diploma',
      passport: 'Passport',
      'civil-registry': 'Civil Registry Extract',
      contract: 'Contract',
      'medical-report': 'Medical Report',
      'technical-doc': 'Technical Document',
      'court-doc': 'Court Document',
      other: 'Other',
    },
    result: {
      title: 'Preliminary Quote',
      basePrice: 'Base service fee',
      wordPrice: 'Word fee',
      addons: 'Additional services',
      total: 'Total',
      vat: 'VAT',
      delivery: 'Estimated delivery time',
      deliveryUnit: 'business days',
      disclaimer: 'This is a preliminary quote; the final price is confirmed after document review.',
      order: 'Place Order',
      whatsapp: 'Contact via WhatsApp',
      estimatedWords: 'Estimated words (automatic — demo)',
    },
    orderConfirm: {
      title: 'Your order has been received',
      number: 'Order No',
      desc: 'Your request and documents have been saved. Our expert team will review the document and contact you as soon as possible.',
      viewOrders: 'My Orders',
      submitting: 'Creating order…',
      error: 'There was a problem creating your order. Please try again.',
    },
    gate: {
      title: 'Your price is ready',
      subtitle: 'Log in or verify your details to see the price and place an order.',
      loginCta: 'Log In / Sign Up',
      or: 'or continue quickly',
      firstName: 'First name',
      lastName: 'Last name',
      email: 'Email',
      phone: 'Phone number',
      sendCode: 'Send Verification Code',
      codeLabel: 'Verification Code',
      codeSentA: 'has been sent a verification code.',
      verify: 'Verify and See Price',
      resend: 'Resend code',
      resent: 'A new code has been sent.',
      back: 'Change details',
      errNames: 'First and last name are required.',
      errEmail: 'Enter a valid email.',
      errPhone: 'Enter a valid phone number.',
      errCode: 'Please enter the code in full.',
      note: 'Your email is used only for the quote and order.',
    },
    note: {
      label: 'Note about your order (optional)',
      placeholder: 'You can write your delivery, terminology or special requests here.',
    },
    checkout: {
      title: 'Delivery Details',
      subtitle: 'Your physical/sworn document will be shipped to this address.',
      firstName: 'First name',
      lastName: 'Last name',
      phone: 'Phone',
      address: 'Full address',
      addressPlaceholder: 'Street, building and apartment no…',
      city: 'City / State',
      postalCode: 'Postal code',
      country: 'Country',
      selectCountry: 'Select country',
      selectCity: 'Select city / state',
      cityNeedsCountry: 'Select a country first',
      submit: 'Complete Order',
      submitting: 'Creating order…',
      cancel: 'Cancel',
      errRequired: 'Please fill in the required fields.',
      note: 'This information is used only for courier delivery.',
    },
  },

  order: {
    seo: {
      title: 'Order Tracking',
      description: 'Track the status of your order.',
    },
    numberLabel: 'Order No',
    placedOn: 'Order date',
    estimatedLabel: 'Estimated translation delivery',
    cargoEstimatedLabel: 'Estimated shipping date',
    timelineTitle: 'Order status',
    steps: {
      received: 'Your order has been received',
      in_progress: 'In progress',
      translated: 'Translation completed',
      shipped: 'Shipped',
      delivered: 'Delivered',
      cancelled: 'Order cancelled',
    },
    stepDesc: {
      received: 'Your request and documents have reached our system. Our expert team will review it and start shortly.',
      in_progress: 'Our expert translator has started your translation.',
      translated: 'Your translation is complete and final checks have been done.',
      shipped: 'Your document has been handed to the courier; you can track it with the button below.',
      delivered: 'Your document has been sent to you by email.',
      cancelled: 'This order has been cancelled. Please contact us with any questions.',
    },
    cargoReady: 'Your document has been shipped. Track it with one tap:',
    cargoPending: 'The tracking code will appear here once your document is shipped.',
    trackCargo: 'Track My Shipment',
    trackingCodeLabel: 'Tracking number',
    digitalPending: 'Once your translation is complete, your files will be sent to you by email.',
    digitalDelivered: 'Your translation has been sent to you by email. Check your inbox (and spam folder).',
    detailsTitle: 'Order details',
    fields: {
      service: 'Service',
      langs: 'Languages',
      documentType: 'Document type',
      words: 'Words',
      delivery: 'Estimated time',
      total: 'Amount',
      note: 'Your note',
      deliveryAddress: 'Delivery address',
    },
    myOrders: 'My Orders',
    backHome: 'Back to Home',
    whatsapp: 'Contact via WhatsApp',
    loading: 'Loading order…',
    loginRequired: {
      title: 'Log in to view your order',
      desc: 'You can access your order details only after logging in with your account.',
      login: 'Log In',
    },
    notFound: {
      title: 'Order not found',
      desc: 'This order number does not belong to you or does not exist. Please check the link.',
      home: 'Back to Home',
    },
  },

  faq: {
    seo: {
      title: 'Frequently Asked Questions',
      description: 'Frequently asked questions about sworn translation, delivery time, pricing, notary approval and corporate terms.',
    },
    hero: { title: 'Frequently Asked Questions', subtitle: 'The answer you’re looking for is here.' },
    categoriesTitle: 'Categories',
    searchPlaceholder: 'Search questions or keywords…',
    empty: 'No questions matched your search. Try a different word or contact us.',
    categories: FAQ_CATEGORIES_EN,
    items: FAQ_ITEMS_EN,
    notFound: {
      title: 'Didn’t find the answer to your question?',
      contact: 'Contact Us',
      whatsapp: 'WhatsApp Support',
    },
  },

  contact: {
      introTitle: `Welcome`,
      introDesc: `Before we begin, may I kindly have your name and email address so that I can assist you more effectively?`,
      start: `Start Chat`,
      introError: `Please enter your name and email address.`,
    seo: {
      title: 'Contact',
      description: 'Get in touch with TercümExpert: phone, email, WhatsApp and contact form.',
    },
    hero: { title: 'Contact', subtitle: 'How can we help you?' },
    infoTitle: 'Contact information',
    labels: {
      phone: 'Phone',
      email: 'Email',
      whatsapp: 'WhatsApp',
      address: 'Address',
      hours: 'Working hours',
    },
    form: {
      title: 'Contact Us',
      fields: {
        name: 'Full Name',
        email: 'Email',
        phone: 'Phone',
        subject: 'Subject',
        message: 'Message',
        consent: 'I have read and approve the <kvkk>KVKK Disclosure Statement</kvkk>.',
      },
      submit: 'Send Message',
      success: 'Your message has been received. We will get back to you shortly.',
    },
    map: {
      title: 'Our Location',
      subtitle: 'Find us on the map',
      placeholder: 'Map area',
      note: 'The location map will be shown here soon.',
    },
  },

  auth: {
    seo: {
      title: 'Log In / Sign Up',
      description: 'Log in to your TercümExpert account or create a new one.',
    },
    tabs: { login: 'Log In', register: 'Sign Up' },
    google: 'Continue with Google',
    or: 'or',
    fields: {
      firstName: 'First Name',
      lastName: 'Last Name',
      email: 'Email',
      password: 'Password',
      code: 'Verification Code',
    },
    login: {
      title: 'Log in to your account',
      submit: 'Log In',
      noAccount: 'Don’t have an account?',
      switchToRegister: 'Sign up',
    },
    register: {
      title: 'Create a new account',
      submit: 'Sign Up',
      haveAccount: 'Already have an account?',
      switchToLogin: 'Log in',
      consent: 'By creating an account, I accept the <kvkk>KVKK Disclosure Statement</kvkk> and the <privacy>Privacy Policy</privacy>.',
    },
    verify: {
      title: 'Verify your email',
      desc: '— enter the 6-digit code we sent to this address.',
      submit: 'Verify and Continue',
      spam: 'The code may be delayed by a few minutes; also check your spam/junk folder.',
      resend: 'Resend code',
      resent: 'A new code has been sent.',
      back: 'Go back',
    },
    signedIn: {
      title: 'My Account',
      greeting: 'Welcome',
      logout: 'Log Out',
    },
    orders: {
      title: 'My Orders',
      empty: 'You have no orders yet. You can create your first order from Calculate Price.',
      loading: 'Loading orders…',
      error: 'Orders could not be loaded. Please refresh the page.',
      status: {
        received: 'Received',
        in_progress: 'In progress',
        translated: 'Translation completed',
        shipped: 'Shipped',
        delivered: 'Delivered',
        cancelled: 'Cancelled',
      },
      track: 'Track',
    },
    errors: {
      nameRequired: 'First and last name are required.',
      emailInvalid: 'Enter a valid email.',
      passwordShort: 'The password must be at least 6 characters.',
      codeInvalid: 'Please enter the 6-digit code.',
      consentRequired: 'Approval is required to continue.',
    },
  },

  blog: {
    seo: { title: 'Blog', description: 'Guide content on translation, notary, apostille and localization.' },
    hero: { title: 'Blog', subtitle: 'Guides from the world of translation.' },
    searchPlaceholder: 'Search posts…',
    readingTime: 'min read',
    relatedTitle: 'Related posts',
    allCategories: 'All',
    empty: 'No posts matched this criterion.',
  },

  legal: {
    lastUpdatedLabel: `Last updated`,
    draftNotice: `In the text below, the fields shown in square brackets ([...]) are to be completed with your company's information. These texts are provided for general informational purposes and should be reviewed by a legal professional before being published.`,
    kvkk: {
      seo: { title: `KVKK Data Protection Notice`, description: `Data protection notice regarding the processing of your personal data under Law No. 6698 (KVKK).` },
      title: `KVKK Data Protection Notice`,
      sections: [
        { heading: `Data Controller`, body: `Pursuant to the Personal Data Protection Law No. 6698 (“KVKK”), your personal data is processed by [ŞİRKET ÜNVANI] (“TercümExpert”), acting in its capacity as data controller, within the scope described below. Address: [ADRES]. E-mail: [E-POSTA]. Telephone: [TELEFON].` },
        { heading: `Personal Data Processed`, body: `We process your identity and contact data (first name, last name, e-mail address, telephone number), your delivery address information, your order and transaction data, the data contained within the documents you submit to us for translation, and the transaction security data relating to your use of the site (IP address, session and cookie records).` },
        { heading: `Purposes of Processing`, body: `Your personal data is processed for the purposes of providing translation, sworn translation, notary and apostille certification services, preparing quotations and managing orders, managing customer relations and handling requests and complaints, fulfilling contractual and legal obligations, and ensuring the security of our services.` },
        { heading: `Legal Grounds for Processing`, body: `Your data is processed on the legal grounds that processing is necessary for the establishment or performance of a contract, for the fulfilment of our legal obligations, for the establishment and protection of a right, and for our legitimate interests, provided that this does not harm your fundamental rights and freedoms; and, where required, on the basis of your explicit consent (KVKK m.5 and m.6).` },
        { heading: `Method of Collection`, body: `Your personal data is collected electronically through the forms on our website, membership and order processes, e-mail and other communication channels.` },
        { heading: `Transfer of Personal Data`, body: `To the extent required by the service, your data may be transferred to our domestic and international suppliers from whom we obtain hosting, infrastructure, authentication, e-mail and analytics services, as well as to authorised public institutions and organisations, in accordance with the conditions set out in KVKK m.8 and m.9. Since the servers of some of the infrastructure and service providers we use are located abroad, your data may be transferred abroad within the framework of the safeguards prescribed by the legislation.` },
        { heading: `Retention Periods`, body: `Your personal data is retained for the period required by the purpose of processing and throughout the statutes of limitation and retention periods stipulated in the relevant legislation (such as tax, commercial and consumer legislation); upon expiry of these periods, it is deleted, destroyed or anonymised.` },
        { heading: `Rights of the Data Subject`, body: `Pursuant to KVKK m.11, you have the right to: learn whether your personal data is being processed; request information if it has been processed; learn the purpose of processing and whether it is used in accordance with that purpose; know the third parties to whom it has been transferred domestically or abroad; request the correction of your data if it has been processed incompletely or incorrectly; request its deletion or destruction where the relevant conditions are met; request that these actions be notified to the third parties to whom the data has been transferred; object to any outcome to your detriment arising from the analysis of your data solely by automated systems; and claim compensation for any damage you incur.` },
        { heading: `Application Method`, body: `You may submit your requests concerning your rights in writing, in accordance with the “Veri Sorumlusuna Başvuru Usul ve Esasları Hakkında Tebliğ”, to [E-POSTA] or to the address [ADRES]. Your request will be concluded as soon as possible and, in any event, within thirty days at the latest, depending on its nature.` },
      ],
    },
    privacy: {
      seo: { title: `Privacy Policy`, description: `Our policy regarding the confidentiality of your personal data and documents.` },
      title: `Privacy Policy`,
      sections: [
        { heading: `Introduction`, body: `At TercümExpert, we value your privacy. This Privacy Policy explains what information we collect, for what purposes, and how we protect it in the services we provide through [WEB ADRESİ]. For detailed information regarding the processing of personal data, please refer to the KVKK Data Protection Notice.` },
        { heading: `Information We Collect`, body: `We may collect account and contact information (first name, last name, e-mail, telephone), order and delivery information, the documents you submit to us for translation and their contents, transaction information relating to payment, and technical data concerning your use of the site (IP address, browser information, cookie records).` },
        { heading: `Purposes for Which We Use Information`, body: `We use your information to provide our services, manage quotations and orders, communicate with you, fulfil our legal obligations, and improve the quality and security of our services. We process your documents only to the extent required by the service you have requested.` },
        { heading: `Document Confidentiality`, body: `The documents you submit for translation are treated as confidential. Only the authorised translators and personnel carrying out the relevant service may access these documents, for as long as the work requires; your documents are not shared with third parties for purposes other than the service.` },
        { heading: `Third-Party Service Providers`, body: `In providing our services, we make use of trusted third-party providers for hosting and infrastructure, authentication, e-mail delivery, analytics and (where enabled) payment. These providers may access your data solely for the purpose of providing the service assigned to them and are subject to contractual confidentiality obligations; the servers of some of them may be located abroad.` },
        { heading: `Data Security`, body: `To protect your data against unauthorised access, we apply encryption in transit, access restrictions and appropriate administrative and technical measures. Although no method can guarantee absolute security, we take reasonable and up-to-date measures to protect your data.` },
        { heading: `Cookies`, body: `Cookies and similar technologies are used on our site. For detailed information about their types and the management of your preferences, please review the Cookie Policy.` },
        { heading: `Your Rights`, body: `You may exercise your rights under the KVKK, including the rights to access, correct and delete your personal data. You may contact us at [E-POSTA] regarding your requests.` },
        { heading: `Children's Privacy`, body: `Our services are not directed at individuals under the age of 18, and we do not knowingly collect personal data belonging to children.` },
        { heading: `Changes`, body: `This policy may be updated from time to time. The current version is always published on this page; in the event of significant changes, notice will be given by appropriate means.` },
        { heading: `Contact`, body: `For questions relating to privacy: E-mail: [E-POSTA] · Telephone: [TELEFON] · Address: [ADRES].` },
      ],
    },
    distanceSales: {
      seo: { title: `Distance Sales Agreement`, description: `Distance sales agreement relating to the sale of services under Law No. 6502.` },
      title: `Distance Sales Agreement`,
      sections: [
        { heading: `Parties`, body: `This Distance Sales Agreement (“Agreement”) is concluded electronically between [ŞİRKET ÜNVANI] (“Seller”; address: [ADRES], e-mail: [E-POSTA], telephone: [TELEFON]) on the one part and the consumer placing the order (“Buyer”) on the other part, in accordance with the Consumer Protection Law No. 6502 and the Mesafeli Sözleşmeler Yönetmeliği.` },
        { heading: `Subject of the Agreement`, body: `The subject of the Agreement is the provision of translation, sworn translation, notary and apostille certification services, whose characteristics and sale price are set out in the order summary, ordered electronically by the Buyer via [WEB ADRESİ].` },
        { heading: `Characteristics and Price of the Service`, body: `The type and scope of the service ordered, the method of delivery (digital or courier), and the total price including taxes are clearly displayed to the Buyer at the time of the order and are included in the order confirmation. Pricing is calculated according to the selected service and the characteristics of the document.` },
        { heading: `Payment`, body: `Payment is made through the payment methods offered at the order step. The order is processed after payment has been confirmed.` },
        { heading: `Performance and Delivery`, body: `For digital deliveries, the translation is transmitted to the Buyer via their account or e-mail once completed. For physical, wet-signed or sworn documents, delivery is made by courier to the address notified by the Buyer. Estimated delivery times are stated at the time of the order; they may vary depending on the volume of documents and the certification processes.` },
        { heading: `Right of Withdrawal`, body: `As a general rule, in contracts for the provision of services, the Buyer has the right to withdraw within fourteen (14) days from the date on which the contract is concluded, without providing any justification. However, the exceptions set out below are reserved.` },
        { heading: `Exceptions to the Right of Withdrawal`, body: `Pursuant to m.15 of the Mesafeli Sözleşmeler Yönetmeliği, the right of withdrawal cannot be exercised in respect of services whose performance has commenced with the Buyer's consent and has been completed before the withdrawal period expires, nor in respect of goods and services prepared specifically in line with the Buyer's requests or personal needs (including translation and certification services prepared specifically for a person or document). Cancellation requests submitted before the translation work begins are assessed separately.` },
        { heading: `Cancellation and Refund`, body: `For orders whose performance has not commenced, cancellation requests may be submitted via [E-POSTA]; approved refunds are made within a reasonable period using the method by which payment was made. For person-specific services whose performance has commenced or been completed, a refund may not be possible due to the nature of the work.` },
        { heading: `Resolution of Disputes`, body: `For disputes that may arise from this Agreement, the Tüketici Hakem Heyetleri and the Consumer Courts located at the Buyer's place of residence or at the place where the transaction was carried out have jurisdiction, within the monetary limits announced each year by the Ticaret Bakanlığı.` },
        { heading: `Entry into Force`, body: `By confirming the order, the Buyer declares that they have read and accepted all the terms of this Agreement. The Agreement enters into force upon confirmation of the order.` },
      ],
    },
    cookies: {
      seo: { title: `Cookie Policy`, description: `Information about the cookies used on our site and the management of preferences.` },
      title: `Cookie Policy`,
      sections: [
        { heading: `What Is a Cookie?`, body: `Cookies are small text files stored in your browser when you visit a website. They are used to make the site more secure and functional, to remember your preferences, and to obtain usage statistics.` },
        { heading: `Why Do We Use Cookies?`, body: `We use cookies to provide the core functions of the site, to maintain session security, to measure performance, and, subject to your consent, to improve our services and carry out marketing activities.` },
        { heading: `Categories of Cookies`, body: `Strictly necessary cookies are required for the operation and security of the site and cannot be disabled. Performance and analytics cookies help us understand visitor interaction. Marketing cookies support the delivery of content and advertising suited to your interests. Preference cookies remember your choices, such as language. Analytics and marketing cookies operate only with your explicit consent.` },
        { heading: `Third-Party Cookies`, body: `We may make use of third-party services for analytics and marketing purposes (for example, visitor statistics and advertising measurement tools). These services may place their own cookies and process data within the scope of their own privacy policies.` },
        { heading: `Managing Cookie Preferences`, body: `You may set or change your preferences regarding non-essential cookies at any time through the cookie preference tool provided on the site. You may also delete or block cookies through your browser settings; however, in that case, some parts of the site may not function properly.` },
        { heading: `Retention Periods`, body: `Depending on their type, cookies are stored for the duration of the session or for a specific period. Session cookies are deleted when the browser is closed; persistent cookies expire at the end of the specified period or when you delete them.` },
        { heading: `Changes`, body: `This Cookie Policy may be updated from time to time. The current version is always published on this page.` },
      ],
    },
    partnership: {
      seo: { title: `Partnership Agreement`, description: `The terms of the TercümExpert partnership (partner) programme.` },
      title: `Partnership Agreement`,
      sections: [
        { heading: `Parties and Subject Matter`, body: `This Partnership Agreement is entered into by and between [ŞİRKET ÜNVANI] (“TercümExpert”) on the one part and the partner applying to the programme (“Partner”) on the other part, for the purpose of governing the terms and conditions of the TercümExpert partnership (referral) programme.` },
        { heading: `Scope of the Programme`, body: `The Partner refers customers to TercümExpert through its own network and channels. In the event that a referred customer purchases a service through TercümExpert, the Partner shall be entitled to the commission set forth in this Agreement.` },
        { heading: `Commission`, body: `For each valid and approved referral, the Partner shall be entitled to a commission at the rate of %20 of the service fee paid by the referred customer. The commission rate and its conditions may be updated by TercümExpert subject to prior notice. Transactions that are cancelled, refunded, or for which payment is not completed shall not be taken as a basis for commission.` },
        { heading: `Tracking and Accrual`, body: `Referrals shall be associated by means of the tracking link, QR code, or the method designated by TercümExpert that is provided to the Partner. The accrual of commission shall arise only for transactions that are correctly associated by such methods and for which payment has been completed.` },
        { heading: `Payment`, body: `Accrued commissions shall be paid to the account notified by the Partner. The payment period and conditions shall be determined separately between the parties. Tax obligations relating to payment shall be subject to the applicable legislation.` },
        { heading: `Obligations of the Partner`, body: `The Partner agrees to use accurate and non-misleading information in its promotions, to refrain from any conduct that would harm the brand and reputation of TercümExpert, and to comply with the applicable legislation.` },
        { heading: `Prohibited Conduct`, body: `Sending spam and unsolicited bulk messages, misleading advertising, and conduct constituting unfair competition through fraudulent or self-referrals are prohibited. Such conduct shall constitute grounds for the cancellation of the commission and the termination of the Agreement.` },
        { heading: `Use of the Brand`, body: `The Partner may use the TercümExpert brand, logo, and promotional materials only within the framework of the written approval of TercümExpert and the rules it provides.` },
        { heading: `Confidentiality`, body: `The parties undertake to protect the confidential information they obtain under this Agreement and to use it solely for the purpose of the programme.` },
        { heading: `Independent Party`, body: `The Partner is an independent party; it is not an employee, representative, or agent of TercümExpert and may not make any commitment to third parties on behalf of TercümExpert.` },
        { heading: `Term and Termination`, body: `The Agreement shall remain in force until either party gives notice of its termination. TercümExpert may terminate the Agreement immediately in the event of a breach of obligations; in such case, commissions arising from improper referrals shall not be paid.` },
        { heading: `Disputes and Governing Law`, body: `This Agreement is subject to the laws of the Republic of Türkiye. By approving the application, the Partner declares that it has read and accepted the terms of the Agreement.` },
      ],
    },
  },

  admin: {
    attachmentImage: 'Image',
    attachmentFile: 'Document',
    title: `Chat Records`,
    summary: `{total} chats · {leads} contact requests`,
    onlyLeads: `Contact requests only`,
    loading: `Loading records…`,
    error: `Records could not be read. Please check that the Supabase table and permissions (RLS) are set up.`,
    empty: `No records yet.`,
    selectHint: `Select a chat from the left to view it.`,
    contactRequest: `Contact request`,
    contactInfo: `Contact information`,
    fieldName: `Name`,
    fieldEmail: `Email`,
    fieldPhone: `Phone`,
    fieldMessage: `Message`,
    requestBadge: `request`,
    noMessages: `No messages in this record (contact request only).`,
    loginTitle: `Login required`,
    loginDesc: `Sign in with an administrator account to view this page.`,
    login: `Sign In`,
    noAccessTitle: `You do not have access`,
    noAccessDesc: `This page is available to administrators only.`,
    loadingAuth: `Loading…`,
  },
  footer: {
    tagline: 'Your reliable partner in professional translation services.',
    columns: {
      quickLinks: 'Quick Links',
      services: 'Services',
      contact: 'Contact',
    },
    quickLinks: {
      corporate: 'Corporate',
      services: 'Our Services',
      quote: 'Calculate Price',
      blog: 'Blog',
      faq: 'Frequently Asked Questions',
      contact: 'Contact',
    },
    serviceLinks: {
      sworn: 'Sworn Translation',
      notarized: 'Notarized Translation',
      apostille: 'Apostille Process',
      corporate: 'Corporate Solutions',
      partnership: 'Partnership Program',
    },
    legal: {
      kvkk: 'KVKK',
      privacy: 'Privacy Policy',
      distanceSales: 'Distance Sales Agreement',
      cookies: 'Cookie Policy',
    },
    socialTitle: 'Follow us',
    whatsapp: 'WhatsApp Support',
    rights: 'All rights reserved.',
  },

  cookie: {
    title: 'Cookie preferences',
    desc: 'We use cookies to improve your experience. Cookies other than necessary ones run only with your consent.',
    accept: 'Accept',
    reject: 'Reject',
    manage: 'Manage Preferences',
    save: 'Save Preferences',
    categories: {
      necessary: { label: 'Necessary', desc: 'Required for the site to function; cannot be disabled.' },
      analytics: { label: 'Analytics', desc: 'Helps us understand usage.' },
      marketing: { label: 'Marketing', desc: 'For relevant content and ads.' },
      preferences: { label: 'Preferences', desc: 'Remembers your preferences.' },
    },
  },

  chatbot: {
    attach: {
      button: 'Attach file',
      tooLarge: 'File is too large (max 25 MB).',
      unsupported: "I can't review audio or video files in the chat. You can upload them on the quote page.",
      cannotRead: "I couldn't read this file. You can upload it on the quote page or try a different format.",
      reading: 'Reading file…',
      remove: 'Remove',
    },
    nudge: 'How can I help you?',
    title: 'TercümExpert Support',
    open: 'Open chat',
    close: 'Close chat',
    minimize: 'Minimize',
    clear: 'Clear conversation',
    inputPlaceholder: 'Type your message…',
    send: 'Send',
    typing: 'Typing…',
    welcome:
      'Hello and welcome to TercümExpert. I can help you with translation, pricing, notary approval, apostille or corporate services.',
    quickQuestions: [
      'How is the price calculated?',
      'What is sworn translation?',
      'I want to upload a document',
      'I want a corporate quote',
      'Is notary approval required?',
      'Connect me to a representative',
    ],
    handoff: 'Connect to a representative',
    toWhatsapp: 'Transfer to WhatsApp',
    disclaimer: 'This information is general; please confirm exact requirements with the relevant institution.',
    sensitiveWarning:
      'Please do not share sensitive personal data via this chat. You can send your documents through the secure upload area.',
    answers: [
      `The price is calculated based on your document's word count, language pair, service type (sworn, notarized, apostille), and delivery time. For an instant estimate, you can upload your document or enter the details on the Calculate Price page.`,
      `A sworn translation is an official translation carried out by a sworn translator and certified with the translator's signature and stamp. Official institutions most often require sworn translations, and notary approval can be added when needed.`,
      `You can submit your document through the secure upload area on the Calculate Price page. Once uploaded, you will see an instant estimate right away and can complete your order.`,
      `For your corporate needs, we offer special pricing and priority delivery on regular, high-volume translations. For details, please visit our Corporate page or get in touch with us.`,
      `Whether notary approval is needed depends on the institution the document is being submitted to and the type of transaction. Some processes accept only sworn translations, while others also require notary approval. If you are unsure, we would be glad to help.`,
      `Let us connect you with one of our customer representatives right away. You can message us via WhatsApp using the button below.`,
    ],
    fallback: `One of our customer representatives can give you the most accurate assistance with your question. You can message us via WhatsApp using the button below, and your message will be forwarded ready to send.`,
    contact: {
      "introTitle": "Welcome",
      "introDesc": "So I can assist you better, may I first have your name and email address?",
      "start": "Start chat",
      "introError": "Please enter your name and email address.",
      whatsapp: `WhatsApp`,
      email: `Email`,
      phone: `Phone`,
      leaveInfo: `Leave my contact details`,
      formTitle: `Let us contact you`,
      formDesc: `Leave your details and our team will reach out to you as soon as possible.`,
      name: `Your name`,
      emailField: `Email`,
      phoneField: `Phone`,
      message: `Your message (optional)`,
      submit: `Send`,
      submitting: `Sending…`,
      thanks: `Thank you, our team will contact you as soon as possible.`,
      errorRequired: `Please enter an email or phone number.`,
      back: `Back`,
    },
  },

  translator: {
    seo: {
      title: 'Translator Panel — TercümExpert',
      description: 'Translator application and work panel.',
    },
    loading: 'Loading…',
    loginTitle: 'Sign in required',
    loginDesc: 'This area is only for translators and administrators. Please sign in to continue.',
    login: 'Sign in',
    setupTitle: 'Panel not ready yet',
    setupDesc: 'The translator infrastructure (database) has not been set up yet. The panel activates once setup is complete.',
    applyTitle: 'Translator Application',
    applyDesc: 'Fill in your details to join our freelance translator network. Your application is activated after admin approval.',
    applyNote: 'Your information is used only for evaluation and payment.',
    form: {
      fullName: 'Full name',
      birthDate: 'Date of birth',
      phone: 'Phone',
      country: 'Country',
      city: 'City / State',
      selectCountry: 'Select country',
      selectCity: 'Select city / state',
      cityNeedsCountry: 'Select a country first',
      address: 'Full address',
      isSworn: 'Are you a sworn (certified) translator?',
      isSwornHint: 'Check this if you hold a notarized oath record. You will be prioritized for jobs requiring sworn translation.',
      iban: 'IBAN',
      ibanName: 'IBAN holder (full name)',
      languagePairs: 'Language pairs',
      source: 'Source language',
      target: 'Target language',
      addPair: 'Add',
      removePair: 'Remove',
      swap: 'Swap direction',
      expertise: 'Areas of expertise',
      submit: 'Submit application',
      submitting: 'Submitting…',
      saved: 'Your details have been saved.',
      saveError: 'Could not save. Please try again.',
      required: 'Please fill in the required fields.',
      atLeastOnePair: 'Add at least one language pair.',
    },
    expertiseLabels: {
      legal: 'Legal',
      medical: 'Medical',
      technical: 'Technical',
      academic: 'Academic',
      commercial: 'Commercial',
      financial: 'Financial',
      literary: 'Literary',
      official: 'Official documents',
      localization: 'Web / Software',
      general: 'General',
    },
    pendingTitle: 'Your application is under review',
    pendingDesc: 'We have received your translator application. Panel access opens after admin review.',
    rejectedTitle: 'Application not approved',
    rejectedDesc: 'Your application was not approved at this time. You can update your details and try again.',
    reapply: 'Try again',
    cancelApplication: 'Cancel application',
    cancelConfirm: 'Are you sure you want to cancel your application? Your record will be deleted; you can re-apply later if you wish.',
    panelTitle: 'Translator Panel',
    tabs: {
      profile: 'My Profile',
      pool: 'Translation Pool',
      active: 'Active Jobs',
      pending: 'Awaiting Approval',
      approved: 'Approved',
      completed: 'Completed',
      wallet: 'Wallet',
    },
    soon: 'This section is coming in the next step.',
    jobs: {
      empty: 'There are no jobs in this section right now.',
      translator: 'Translator',
      sourceFiles: 'Source documents',
      translationFiles: 'Uploaded translation',
      tracking: 'Tracking',
      rejectionReason: 'Rejection reason',
      // Translator — Active Jobs
      chooseFiles: 'Choose translation files',
      filesSelected: 'file(s) selected',
      uploadHint: 'Upload your translation and, if needed, a digital copy of the source, then send it for approval.',
      submit: 'Send for approval',
      sending: 'Sending…',
      needFiles: 'Please select at least one file.',
      uploadError: 'Files could not be uploaded. Please try again.',
      submittedMsg: 'Translation sent for approval.',
      actionError: 'The action could not be completed. Please try again.',
      // Translator — Awaiting Approval
      waitingApproval: 'Your translation is awaiting management approval. Once approved, the delivery step appears under “Approved”.',
      // Translator — Approved (delivery)
      trackingPlaceholder: 'Tracking number / link',
      needTracking: 'A tracking number is required for cargo delivery.',
      markShipped: 'Shipped — complete',
      markDelivered: 'Delivered — complete',
      completedMsg: 'Job completed. Your earning has been added to your wallet.',
      // Admin — Awaiting Approval (approve/reject)
      reasonPlaceholder: 'If rejecting, write the reason (visible to the translator)…',
      approve: 'Approve',
      reject: 'Reject',
      needReason: 'Write a reason to reject.',
      approvedMsg: 'Translation approved.',
      rejectedMsg: 'Translation rejected; returned to the translator.',
      // Read-only status
      statusLabel: 'Status',
      status_claimed: 'In progress',
      status_submitted: 'Awaiting approval',
      status_approved: 'Approved — delivery stage',
      status_completed: 'Completed',
    },
    pool: {
      loading: 'Loading pool…',
      empty: 'There are no pending orders matching your language pairs and expertise right now.',
      error: 'Could not load the pool. Please try again.',
      orderNo: 'Order',
      service: 'Service type',
      documentType: 'Document type',
      langPair: 'Language pair',
      words: 'Words',
      pagesUnit: 'pages',
      deadline: 'Deadline',
      daysUnit: 'business days',
      note: 'Customer note',
      customerInfo: 'Customer details',
      deliveryInfo: 'Customer & delivery details',
      customerName: 'Full name',
      customerEmail: 'Email',
      customerPhone: 'Phone',
      deliveryAddress: 'Delivery address',
      text: 'Order text',
      files: 'Documents',
      earning: 'Your earning for this job',
      urgent: 'Urgent',
      sworn: 'Sworn',
      notary: 'Notarized',
      apostille: 'Apostille',
      cargo: 'Cargo delivery',
      digital: 'Digital delivery',
      claim: 'Take this job',
      claiming: 'Taking…',
      claimed: 'You have successfully taken the job.',
      claimError: 'Could not take the job. It may have been taken by someone else; refresh the list.',
      ibanRequired: 'Before you can take jobs, your IBAN details must be verified by management. Enter your IBAN in your profile; once verified you can take jobs from the pool.',
    },
    profile: {
      statusApproved: 'Approved translator',
      verifiedIban: 'IBAN verified',
      unverifiedIban: 'IBAN not verified',
      current: 'Saved',
      edit: 'Save details',
      ibanReminder: 'To receive your payments, please enter and save your IBAN details. Once verified by admin, payments will be made to this account.',
      lockedHint: 'Cannot be changed after approval',
      revokeTitle: 'This change will revoke your approval',
      revokeWarning: 'If you change your language pairs, sworn status, or areas of expertise, your account returns to management review (set to pending). Your jobs, records, and wallet are PRESERVED; once re-approved you continue where you left off.',
      consent: 'I have read and I accept',
      ibanReverify: 'You are changing your IBAN. The new IBAN goes back to management review; your account stays active, but you cannot take new jobs from the pool until the IBAN is verified.',
    },
    admin: {
      title: 'Management Panel',
      translatorsTab: 'Translators',
      applicationsTab: 'Applications',
      ibanTab: 'IBAN Approvals',
      ordersTab: 'Orders',
      paymentsTab: 'Payments',
      noIbanPending: 'No translators awaiting IBAN approval.',
      ibanHint: 'Approve newly entered or changed IBANs here. Until approved, the translator cannot take new jobs from the pool.',
      ibanApprove: 'Approve IBAN',
      paymentsHint: 'On payment day (the 1st and 16th of each month): for each translator you have paid, upload the receipt and click “Mark paid”. The button will not work without a receipt. Translators with a zero balance are not listed here.',
      noPayments: 'No translators with a balance to pay.',
      paymentAmount: 'Amount to pay',
      uploadReceipt: 'Upload receipt',
      receiptUploaded: 'Receipt uploaded',
      receiptRequired: 'Upload a receipt first',
      uploading: 'Uploading…',
      markPaid: 'Mark paid',
      paid: 'Payment recorded and the translator was notified with the receipt.',
      panelHint: 'Track approved translators by profile, review applications, and manage the workflow of all orders.',
      summary: '{total} translators · {pending} pending applications',
      applicationsSummary: '{total} applications · {pending} awaiting review',
      noApproved: 'No approved translators yet.',
      noPending: 'No pending applications.',
      noMatch: 'No records match the filters.',
      loadError: 'Could not load records. Check the database and permissions (RLS).',
      noApplications: 'No translator records yet.',
      filters: {
        namePlaceholder: 'Search by name…',
        country: 'Country',
        city: 'City / State',
        anyCountry: 'All countries',
        anyCity: 'All cities',
        cityNeedsCountry: 'Select a country first',
        sourceLang: 'Source language',
        targetLang: 'Target language',
        anyLang: 'Any',
        eitherDirection: 'Either direction (source↔target)',
        expertise: 'Areas of expertise',
        clear: 'Clear filters',
        results: '{n} records',
      },
      orders: {
        loadError: 'Could not load orders. Please try again.',
        empty: 'No orders yet.',
        searchPlaceholder: 'Search by order no or customer name…',
        results: '{n} orders',
        customer: 'Customer',
        translator: 'Translator',
        unassigned: 'Unassigned',
        status: 'Status',
        done: 'Completed',
        inProgress: 'In progress',
        completedOn: 'Completed on',
        placedOn: 'Order date',
        total: 'Total',
        statusAvailable: 'In pool (unclaimed)',
        statusClaimed: 'In translation',
        statusSubmitted: 'Awaiting approval',
        statusApproved: 'Delivery stage',
        statusCompleted: 'Completed',
        statusCancelled: 'Cancelled',
      },
      profile: {
        back: 'Back to translators',
        adminOnly: 'This profile is management-only; the translator cannot see it.',
        infoTitle: 'Details',
        walletTitle: 'Wallet',
        jobsTitle: 'Jobs',
        noJobs: 'This translator has no jobs yet.',
      },
      approve: 'Approve',
      reject: 'Reject',
      colLangs: 'Language pairs',
      colExpertise: 'Expertise',
      colLocation: 'City / Country',
      swornBadge: 'Sworn',
      returningBadge: 'Returning translator',
      ibanVerified: 'IBAN verified',
      ibanNotVerified: 'IBAN not verified',
      verifyIban: 'Verify IBAN',
      unverifyIban: 'Unverify',
      statusPending: 'Pending',
      statusApproved: 'Approved',
      statusRejected: 'Rejected',
      actionError: 'Action could not be completed.',
    },
    wallet: {
      total: 'Total earnings',
      locked: 'Locked',
      withdrawable: 'Withdrawable',
      paid: 'Paid out',
      payInfo: 'Earnings are added to your wallet when a job completes; they stay locked for 7 days, then become withdrawable. Payments are made to the withdrawable balance on the 1st and 16th of each month.',
      empty: 'No earnings yet. Earnings from completed jobs appear here.',
      entryOrder: 'Order',
      date: 'Date',
      statusCol: 'Status',
      amount: 'Amount',
      statusPaid: 'Paid',
      statusUnlocked: 'Withdrawable',
      statusPending: 'Locked',
      loadError: 'Could not load the wallet. Please try again.',
    },
    adminWallet: {
      firmShare: 'Company share (incl. VAT)',
      firmShareHint: 'Company share = total of completed orders (incl. VAT) minus translator earnings.',
      ciro: 'Total revenue (incl. VAT)',
      kdv: 'VAT (to the state)',
      payouts: 'Paid to translators',
      net: 'Company net',
      count: '{n} completed orders',
      empty: 'No completed orders yet.',
      colOrder: 'Order',
      colTranslator: 'Translator',
      colDate: 'Date',
      colTotal: 'Total (incl. VAT)',
      colPayout: 'Translator',
      colFirm: 'Company share',
      loadError: 'Could not load the wallet. Please try again.',
    },
  },

  authx: {
    rememberMe: 'Remember me',
    showPassword: 'Show password',
    hidePassword: 'Hide password',
    forgot: 'Forgot my password',
    forgotTitle: 'Reset password',
    forgotDesc: 'Enter your registered email address and we will send you a one-time link to reset your password.',
    forgotEmail: 'Email',
    forgotSubmit: 'Send reset link',
    forgotSent: 'The link has been sent to your email. Check your inbox (and your spam folder).',
    forgotBack: 'Back to login',
    resetTitle: 'Set a new password',
    resetDesc: 'Enter your new password and confirm it by typing it again.',
    newPassword: 'New password',
    newPasswordRepeat: 'New password (repeat)',
    mismatch: 'The passwords do not match.',
    weak: 'The password must be at least 6 characters.',
    resetSubmit: 'Update password',
    resetSuccess: 'Your password has been updated. You can now log in with your new password.',
    resetInvalid: 'The link is invalid or has expired. Please request a new reset link.',
    goLogin: 'Log in',
    err: {
      invalidCredentials: 'Incorrect email or password. Please check your details and try again.',
      emailNotConfirmed: 'Your email address has not been verified yet. Click the verification link in your inbox.',
      alreadyRegistered: 'This email address is already registered. Try logging in or resetting your password.',
      weakPassword: 'The password must be at least 6 characters.',
      otpInvalid: 'The verification code is incorrect or has expired. Request a new code.',
      rateLimited: 'Too many attempts. Please wait a moment and try again.',
      generic: 'Something went wrong. Please try again later.',
    },
  },

  delivery: {
    ready: 'Your translation is ready',
    download: 'Download translation',
    hint: 'Your translation has also been sent to your email address. Check your inbox (and spam folder).',
  },

  partnerPanel: {
    yourEarning: "Your earning",
    tabAllOrders: "All Orders",
    fltOrderNo: "Order no",
    fltDateFrom: "From",
    fltDateTo: "To",
    custFilter: "Search by name",
    custEmpty: "You have not referred any members yet. Share your invitation link.",
    colName: "Name",
    colEmail: "E-mail",
    colPhone: "Phone",
    colJoined: "Joined",
    custOrderCount: "Orders",
    custTotal: "Total amount",
    ordEmpty: "No orders at this stage.",
    colOrderNo: "Order",
    colCustomer: "Customer",
    colService: "Service",
    colLangs: "Languages",
    colAmount: "Amount",
    colDate: "Date",
    loadError: "Could not load. Please try again.",
    walPayInfo: "Your earnings are added to your wallet when the job is completed; they stay locked for 7 days, then become withdrawable. Payments to the withdrawable balance are made on the 2nd and 17th of each month.",
    ibanPending: "Your IBAN details are awaiting administrator approval.",
    ibanPolicy: "Until your IBAN and account holder details are approved by our team, you cannot receive payments. Your earnings continue to accumulate in your wallet during this time. Once your details are approved, you can withdraw balances that have passed the 7-day hold since the sale and are no longer locked.",
    fillRequired: "Please fill in the required fields.",
    phoneLockNote: "Your phone number can be updated once SMS verification is enabled.",
    panelTitle: "Partner Panel",
    tabProfile: "My Profile",
    tabCustomers: "My Customers",
    tabOrdersNew: "Incoming Orders",
    tabOrdersActive: "In Progress",
    tabOrdersDelivery: "Awaiting Delivery",
    tabOrdersDone: "Completed",
    tabWallet: "Wallet",
    soon: "Coming soon.",
    save: "Save",
    saved: "Saved.",
    statusApproved: "Approved partner",
    ibanVerified: "IBAN verified",
    ibanNotVerified: "IBAN not verified",
    ibanReminder: "Enter your IBAN and account holder details so you can receive payments.",
    refCodeLabel: "Your invitation code",
    seoTitle: "Partner Panel",
    seoDesc: "Submit your partner application and get your invitation link here.",
    loading: "Loading…",
    loginTitle: "Partner sign-in",
    loginDesc: "Sign in or create an account to apply or access your panel.",
    login: "Sign in / Sign up",
    setupTitle: "Setup not complete",
    setupDesc: "The partner system is not ready yet.",
    applyTitle: "Partner Application",
    applyDesc: "Fill in your details; your invitation link activates once your application is approved.",
    applyNote: "Your application will be reviewed shortly.",
    sectorOther: "Enter your sector",
    submit: "Submit application",
    submitting: "Submitting…",
    saveError: "Your application could not be saved. Please try again.",
    pendingTitle: "Application received",
    pendingDesc: "Your application is under review. Once approved, your invitation link and panel will activate here.",
    cancelApplication: "Cancel application",
    rejectedTitle: "Application not approved",
    rejectedDesc: "This application was not approved. You can update your details and apply again.",
    reapply: "Apply again",
    approvedTitle: "Your partner account is active",
    approvedDesc: "Customers who sign up through your invitation link below are permanently linked to your account.",
    panelSoon: "A detailed panel with your customers, orders and wallet is coming here very soon.",
    verifyTitle: "E-mail verification",
    verifyDesc: "Verify your e-mail address so you can receive payments. We will send you a verification code.",
    verifiedLabel: "E-mail verified",
    sendCode: "Send verification code",
    sending: "Sending…",
    codeSent: "We've sent the code to your e-mail. Please check your inbox and spam folder.",
    codePlaceholder: "6-digit code",
    verifyBtn: "Verify",
    verifying: "Verifying…",
    verifyError: "The code is invalid or has expired. Request a new one.",
    refTitle: "Your invitation link",
    refDesc: "Share this link; customers who arrive through it and sign up are permanently linked to you.",
    refCopy: "Copy link",
    refCopied: "Copied",
  },
  adminHub: {
    tabChats: 'Conversations',
    tabCustomers: 'Customers',
    tabUploads: 'Uploaded Files',
    loading: 'Loading…',
    loadError: 'Could not load. Please try again.',
    back: 'Back',
    custHint: 'All customers registered in the system (translators excluded).',
    custSearch: 'Search name, email or phone…',
    custName: 'Full name',
    custEmail: 'Email',
    custPhone: 'Phone',
    custOrders: 'Orders',
    custTotal: 'Total amount',
    custJoined: 'Joined',
    custNone: 'No customer records yet.',
    custOrderList: 'Orders',
    custNoOrders: 'This customer has no orders.',
    orderNo: 'Order No',
    orderDate: 'Date',
    orderStatus: 'Status',
    upHint: 'All files uploaded on the quote page (saved even if no order is placed).',
    upFile: 'File',
    upUploader: 'Uploaded by',
    upWhen: 'Date',
    upWords: 'Words',
    upSize: 'Size',
    upDownload: 'Download',
    upNone: 'No uploaded files yet.',
    upGuest: 'Guest',
  },

  smsVerify: {
    sendCode: 'Send code',
    resend: 'Resend code',
    codeLabel: 'SMS code',
    confirm: 'Confirm',
    verified: 'Phone verified',
    sent: 'A code has been sent to your phone.',
    mustVerify: 'To continue, verify your phone number via SMS.',
    reverifyHint: 'If you change your phone number, you must verify the new number again via SMS.',
    invalid: 'Incorrect code. Please try again.',
    expired: 'The code has expired. Please request a new one.',
    rateLimited: 'Too many attempts. Please wait a moment and try again.',
    notConfigured: 'SMS verification is currently unavailable. Please try again later or contact support.',
    sendFailed: 'The code could not be sent. Check your number and try again.',
    enterPhone: 'Please enter a valid phone number first.',
    error: 'Something went wrong. Please try again.',
    devCode: 'Test mode — your verification code: {code}',
  },

  notFound: {
    seo: { title: 'Page not found', description: 'The page you are looking for could not be found.' },
    title: 'Page not found',
    desc: 'The page you are looking for may have been moved or may never have existed.',
    home: 'Back to home',
  },
}
