import type { PartialDictionary } from '@/types/i18n'
import { FAQ_CATEGORIES_AZ, FAQ_ITEMS_AZ } from '@/content/faq-data.az'

export const az: PartialDictionary = {
  common: {
    tagline: 'Peşəkar tərcümə xidmətlərində etibarlı tərəfdaşınız.',
    nav: {
      home: 'Ana səhifə',
      services: 'Xidmətlər',
      quote: 'Qiymət al',
      corporate: 'Korporativ',
      partnership: 'Tərəfdaşlıq',
      blog: 'Bloq',
      faq: 'FAQ',
      contact: 'Əlaqə',
    },
    actions: {
      getQuote: 'Qiymət al',
      calculatePrice: 'Qiyməti hesabla',
      uploadDocument: 'Sənəd yüklə',
      whatsapp: 'WhatsApp-da yazın',
      learnMore: 'Ətraflı öyrənin',
      viewAll: 'Hamısına baxın',
      showMore: 'Daha çox göstər',
      showLess: 'Daha az göstər',
      send: 'Göndər',
      apply: 'Müraciət et',
      order: 'Sifariş ver',
      contactUs: 'Bizimlə əlaqə',
      openMenu: 'Menyunu aç',
      closeMenu: 'Menyunu bağla',
      selectLanguage: 'Dil seçin',
      skipToContent: 'Məzmuna keç',
      login: 'Daxil ol',
      logout: 'Çıxış',
      account: 'Hesabım',
    },
    states: {
      loading: 'Yüklənir…',
      error: 'Xəta baş verdi. Zəhmət olmasa yenidən cəhd edin.',
      required: 'Bu xana mütləq doldurulmalıdır.',
      demoNotice: 'Demo: forma məlumatları hələ serverə göndərilmir.',
      unverified: 'Təsdiqlənəcək',
    },
    topbar: {
      phoneLabel: 'Telefon',
      emailLabel: 'E-poçt',
      hoursLabel: 'İş saatları',
      afterHours: 'İş saatlarından sonra təcili tərcümə dəstəyi mövcuddur.',
      workingHours: 'İş günləri 09:00 - 18:00 | İş saatlarından sonra xidmət mövcuddur',
    },
  },

  home: {
    seo: {
      title: 'TercümExpert — Peşəkar Tərcümə Xidmətləri',
      description:
        'Andlı tərcümə, notariat təsdiqi və korporativ tərcümə həlləri. Sənədinizi yükləyin, dərhal ilkin qiymət alın və peşəkar çatdırılmadan yararlanın.',
    },
    hero: {
      title: 'Peşəkar Sahədə Etibarlı Tərəfdaşınız',
      titleAccent: 'Tərcümə Xidmətləri',
      subtitle: 'Sənədinizi yükləyin, qiyməti görün, peşəkar çatdırılma alın.',
      support: 'Andlı tərcümə • Notariat təsdiqi • Korporativ həllər',
    },
    trust: {
      title: 'Nə üçün bizə etibar edirlər?',
      items: [
        { key: 'languages', label: '50+ Dil' },
        { key: 'delivery', label: '24 Saatlıq Çatdırılma' },
        { key: 'notary', label: 'Notariat Təsdiqi' },
        { key: 'quality', label: 'Keyfiyyət Zəmanəti' },
      ],
    },
    stats: {
      title: 'Rəqəmlərlə TercümExpert',
      note: 'Aşağıdakı rəqəmlər təsdiqlənənə qədər qəti iddia kimi təqdim edilmir.',
      labels: {
        satisfaction: 'Müştəri Məmnuniyyəti',
        completed: 'Tamamlanmış İşlər',
        languages: 'Dil Dəstəyi',
        corporate: 'Korporativ Müştərilər',
      },
    },
    howItWorks: {
      title: 'Necə işləyir?',
      subtitle: 'Beş addımda peşəkar tərcümə.',
      steps: [
        { key: 'upload', title: 'Yükləyin', desc: 'Sənədinizi təhlükəsiz şəkildə yükləyin.' },
        { key: 'select', title: 'Seçin', desc: 'Dili və xidmət növünü seçin.' },
        { key: 'confirm', title: 'Təsdiqləyin', desc: 'Sifarişinizi təsdiqləyin.' },
        { key: 'track', title: 'İzləyin', desc: 'Prosesi real vaxtda izləyin.' },
        { key: 'receive', title: 'Qəbul edin', desc: 'Peşəkar çatdırılmanızı alın.' },
      ],
    },
    services: {
      title: 'Xidmətlərimiz',
      subtitle: 'Hər sənəd növü üçün ekspert tərcümə.',
    },
    why: {
      title: 'Nə üçün TercümExpert?',
      subtitle: 'Bizi rəqiblərimizdən fərqləndirən xüsusiyyətlər',
      features: [
        { key: 'autoQuote', title: 'Avtomatik qiymət hesablama', desc: 'Saniyələr içində ilkin qiymət.' },
        { key: 'whatsapp', title: 'Sürətli WhatsApp qiyməti', desc: 'Bir toxunuşla əlaqə.' },
        { key: 'terminology', title: 'Terminologiya idarəetməsi', desc: 'Ardıcıl, korporativ dil.' },
        { key: 'revision', title: 'Redaktə hüququ', desc: 'Məmnuniyyətə yönəlmiş proses.' },
        { key: 'languages', title: '50+ dil dəstəyi', desc: 'Geniş dil cütü əhatəsi.' },
        { key: 'terms', title: 'Korporativ vaxt sistemi', desc: 'Şirkətlər üçün çevik ödəniş.' },
      ],
    },
    corporateCta: {
      title: 'Korporativ Həllər',
      desc: 'Şirkətinizə uyğunlaşdırılmış terminologiya idarəetməsi, vaxt seçimləri və fərdi hesab meneceri ilə peşəkar dil xidmətləri.',
      action: 'Korporativ Qiymət İstəyin',
    },
    partnershipTeaser: {
      title: 'Tərəfdaşlıq Proqramı',
      subtitle: 'Bizə yönləndirdiyiniz hər müştəriyə görə 20% komissiya qazanın.',
      items: [
        { key: 'commission', title: 'Şəffaf Komissiya', desc: 'Hər yönləndirməyə görə 20% komissiya (razılaşmaya əsasən). Real vaxt izləmə paneli ilə şəffaf qazanc.' },
        { key: 'qr', title: 'QR Kod Sistemi', desc: 'Vizit kartı inteqrasiyası ilə asan müştəri izləmə. Veb və WhatsApp QR kodları.' },
      ],
      cta: 'Tərəfdaş kimi müraciət edin',
    },
    testimonials: {
      title: 'Müştəri Rəyləri',
      subtitle: 'Real müştəri rəyləri istifadəyə verilməzdən əvvəl burada əlavə olunacaq.',
      placeholderNote: 'Yer tutucu — real rəylər inteqrasiya olunacaq.',
      items: [
        { key: 't1', role: 'Hüquq Bürosu' },
        { key: 't2', role: 'Səhiyyə Təşkilatı' },
        { key: 't3', role: 'Korporativ Müştəri' },
        { key: 't4', role: 'Fərdi Müştəri' },
      ],
    },
    blogTeaser: {
      title: 'Bloq',
      subtitle: 'Tərcümə dünyasından aktual məzmun',
      viewAll: 'Bütün Bloq Yazılarına Baxın',
    },
    finalCta: {
      title: 'İndi Başlayın',
      desc: 'Sənədlərinizi yükləyin, dərhal qiymət alın və peşəkar tərcümə xidmətlərindən yararlanın.',
      primary: 'Qiymət al',
      secondary: 'Bizimlə əlaqə',
    },
  },

  services: {
    seo: {
      title: 'Tərcümə Xidmətləri',
      description:
        'Andlı, notariat təsdiqli, hüquqi, texniki, tibbi və akademik tərcümə, həmçinin veb/mobil lokallaşdırma. Sənəd növləri, proses, çatdırılma və dil cütləri.',
    },
    hero: {
      title: 'Tərcümə Xidmətləri',
      subtitle: 'Hər ixtisas sahəsi üçün düzgün terminologiya ilə tərcümə.',
    },
    process: {
      title: 'Proses necə işləyir?',
      steps: [
        { title: 'Sənəd baxışı', desc: 'Sənədin növü və məqsədi qiymətləndirilir.' },
        { title: 'Ekspert təyinatı', desc: 'Sahə üzrə ixtisaslaşmış tərcüməçi təyin edilir.' },
        { title: 'Tərcümə və redaktə', desc: 'Tərcümə və müstəqil yekun baxış.' },
        { title: 'Təsdiq və çatdırılma', desc: 'Lazım olduqda notariat/apostil, sonra çatdırılma.' },
      ],
    },
    delivery: {
      title: 'Çatdırılma seçimləri',
      items: ['Rəqəmsal çatdırılma (PDF/DOCX)', 'Fiziki sənəd çatdırılması', 'Təcili çatdırılma'],
    },
    notaryApostille: {
      title: 'Notariat və apostil əlaqəsi',
      desc: 'Tələb olunduqda andlı tərcümə notariat təsdiqi və apostil prosesi vasitəsilə rəsmi qurumlar üçün etibarlı edilir. Dəqiq tələb sənədin təqdim olunacağı quruma görə dəyişir.',
    },
    fullService: {
      title: 'Açar Təslim, Qapınıza Qədər Çatdırılır',
      note: 'Sənədlərinizi bizə göndərin, bütün prosesi — tərcümə, notariat təsdiqi və apostil daxil — biz idarə edək. Hazır sənədləriniz kuryer vasitəsilə qapınıza çatdırılır. Siz işinizə fokuslanın, qalanını bizə buraxın.',
    },
    cta: {
      title: 'Hansı xidmətə ehtiyacınız olduğundan əmin deyilsiniz?',
      desc: 'Sənədinizi yükləyin, sizə ən uyğun xidməti və qiyməti göstərək.',
    },
    documentTypesTitle: 'Uyğun sənəd növləri',
  },

  serviceItems: {
    sworn: {
      name: 'Andlı Tərcümə',
      short: 'Andlı tərcüməçinin imzası və möhürü ilə rəsmi etibarlı tərcümə.',
      benefits: ['Rəsmi qurumlarda etibarlı', 'Andlı tərcüməçi təsdiqi', 'Sürətli proses'],
    },
    notarized: {
      name: 'Notariat Təsdiqli Tərcümə',
      short: 'Andlı tərcümənin notariat təsdiqi.',
      benefits: ['Notariat təsdiqi', 'Rəsmi müraciətlər üçün uyğun', 'Prosesi biz idarə edirik'],
    },
    apostille: {
      name: 'Apostil Prosesi Dəstəyi',
      short: 'Xaricdə etibarlılıq üçün apostil prosesində bələdçilik.',
      benefits: ['Beynəlxalq etibarlılıq', 'Proses məsləhəti', 'Qurum bələdçiliyi'],
    },
    legal: {
      name: 'Hüquqi Tərcümə',
      short: 'Müqavilələr, məhkəmə və rəsmi sənədlər üçün terminologiyaya hakim tərcümə.',
      benefits: ['Hüquqi terminologiya', 'Məxfilik zəmanəti', 'Ekspert tərcüməçi'],
    },
    technical: {
      name: 'Texniki Tərcümə',
      short: 'Təlimatlar, spesifikasiyalar və texniki sənədlər üçün ardıcıl tərcümə.',
      benefits: ['Terminologiya idarəetməsi', 'Format qorunur', 'Sənaye təcrübəsi'],
    },
    medical: {
      name: 'Tibbi Tərcümə',
      short: 'Hesabatlar, təlimatlar və tibbi sənədlər üçün dəqiq tərcümə.',
      benefits: ['Tibbi terminologiya', 'Dəqiqliyə yönəlmiş', 'Məxfilik'],
    },
    academic: {
      name: 'Akademik Tərcümə',
      short: 'Dissertasiyalar, məqalələr və diplom tərcümələri üçün akademik dil.',
      benefits: ['Akademik üslub', 'Mənbə ardıcıllığı', 'Vaxtında çatdırılma'],
    },
    localization: {
      name: 'Veb və Mobil Lokallaşdırma',
      short: 'Vebsaytların və tətbiqlərin mədəni cəhətdən uyğun lokallaşdırılması.',
      benefits: ['Mədəni uyğunlaşdırma', 'Texniki inteqrasiya', 'SEO uyğunluğu'],
    },
  },

  corporate: {
    statsLabels: {
      corporate: 'Korporativ müştərilər',
      discount: 'Toplu sifariş endirimi',
      term: 'Ödəniş vaxtı',
    },
    seo: {
      title: 'Korporativ Həllər',
      description:
        'Terminologiya idarəetməsi, vaxt seçimləri, toplu sifarişlər və fərdi hesab meneceri ilə şirkətlər üçün peşəkar dil xidmətləri.',
    },
    hero: {
      title: 'Korporativ Həllər',
      subtitle:
        'Şirkətinizə uyğunlaşdırılmış terminologiya idarəetməsi, vaxt seçimləri və fərdi hesab meneceri ilə peşəkar dil xidmətləri.',
      primaryCta: 'Korporativ Qiymət İstəyin',
      secondaryCta: 'E-poçt Göndər',
    },
    features: {
      title: 'Korporativ Xüsusiyyətlər',
      subtitle: 'Biznesinizə uyğunlaşdırılmış həllər',
      items: [
        {
          key: 'custom',
          icon: 'Target',
          title: 'Fərdiləşdirilmiş Xidmət',
          points: ['Sabit terminologiya', 'Brendin səs tonunun qorunması', 'Fərdi hesab meneceri', 'Üslub bələdçisinin yaradılması'],
        },
        {
          key: 'volume',
          icon: 'BarChart3',
          title: 'Toplu Emal və Vaxt Seçimləri',
          points: ['Aylıq tərcümə planları', 'Toplu sifariş endirimləri', '30 günə qədər vaxt', 'Fakturalaşdırma sistemi'],
        },
        {
          key: 'security',
          icon: 'Lock',
          title: 'Məxfilik və Təhlükəsizlik',
          points: ['NDA protokolu', 'Şifrələnmiş fayl ötürülməsi', 'KVKK-uyğun proseslər'],
        },
      ],
    },
    whyPackage: {
      title: 'Nə üçün Korporativ Paket?',
      items: [
        {
          key: 'terminology',
          icon: 'Building2',
          title: 'Sabit Terminologiya İdarəetməsi',
          desc: 'Şirkətinizə xas termin bankı qururuq. Brend diliniz bütün tərcümələrdə qorunur və ardıcıllığı təmin edirik. Hər layihədə eyni terminlərin işlədilməsinə diqqət yetiririk.',
        },
        {
          key: 'manager',
          icon: 'Users',
          title: 'Fərdi Hesab Meneceri',
          desc: 'Fərdi hesab meneceriniz bütün proseslərinizi izləyir. Əlçatan dəstək xətti ilə təcili vəziyyətlərdə yanınızdayıq.',
        },
        {
          key: 'security',
          icon: 'ShieldCheck',
          title: 'Məxfilik və Təhlükəsizlik',
          desc: 'NDA protokolu altında işləyirik. Güclü təhlükəsizlik infrastrukturu, şifrələnmiş fayl ötürülməsi və KVKK-uyğun proseslərlə məlumatlarınız təhlükəsizdir.',
        },
      ],
    },
    payment: {
      title: 'Ödəniş Seçimləri',
      subtitle: 'Biznesinizə uyğun çevik ödəniş planları',
      recommendedLabel: 'TÖVSİYƏ OLUNUR',
      options: [
        {
          key: 'standard',
          label: 'Dərhal Ödəniş',
          heading: 'Standart',
          desc: 'Hər sifarişdən sonra kredit kartı və ya bank köçürməsi ilə ödəniş',
          points: ['Kredit kartı ilə hissə-hissə', 'Dərhal çatdırılma'],
          recommended: false,
        },
        {
          key: 'term',
          label: 'Aylıq Vaxt',
          heading: '15-30 Gün',
          desc: 'Aylıq birləşdirilmiş fakturalaşdırma və vaxt seçimi',
          points: ['30 günlük vaxt', 'Toplu endirim', 'Aylıq hesabat'],
          recommended: true,
        },
      ],
    },
    form: {
      title: 'Korporativ Paket Müraciəti',
      desc: 'Formanı doldurun, ekspert komandamız sizinlə əlaqə saxlayacaq',
      fields: {
        company: 'Şirkət Adı',
        contactName: 'Əlaqədar Şəxsin Adı və Soyadı',
        email: 'E-poçt',
        phone: 'Telefon',
        need: 'Tərcümə ehtiyaclarınız haqqında bizə məlumat verin',
        consent: 'KVKK Məlumatlandırma Bəyanatını oxudum və qəbul edirəm.',
      },
      submit: 'Müraciəti Göndər',
      success: 'Müraciətiniz qəbul olundu. Ən qısa zamanda sizinlə əlaqə saxlayacağıq.',
      note: '1 iş günü ərzində sizinlə əlaqə saxlayacağıq.',
    },
  },

  partnership: {
    seo: {
      title: 'Tərəfdaşlıq Proqramı',
      description:
        'Yönləndirdiyiniz hər müştəriyə görə komissiya qazanın. Şəffaf hesabatlıq, QR kod yönləndirmələri və peşəkar dəstək.',
    },
    hero: {
      title: 'Tərəfdaşlıq Proqramı',
      value: 'Bizə yönləndirdiyiniz hər müştəriyə görə 20% komissiya qazanın.',
      subtitle: 'Şəffaf sistem, etibarlı ödənişlər, uzunmüddətli əməkdaşlıq.',
      cta: 'İndi Müraciət Edin',
    },
    advantages: {
      title: 'Tərəfdaş Üstünlükləri',
      subtitle: 'Nə üçün TercümExpert tərəfdaşı olmalısınız?',
      items: [
        { key: 'commission', icon: 'Wallet', title: '20% Komissiya Zəmanəti', desc: 'Yönləndirdiyiniz hər müştəri üçün şəffaf komissiya sistemi.' },
        { key: 'qr', icon: 'QrCode', title: 'QR Kod Yönləndirmə', desc: 'Vizit kartı inteqrasiyası ilə asan müştəri izləmə.' },
        { key: 'reporting', icon: 'BarChart3', title: 'Şəffaf Hesabatlıq', desc: 'Real vaxt komissiya və müştəri izləmə paneli.' },
        { key: 'support', icon: 'Users', title: 'Peşəkar Dəstək', desc: 'Fərdi tərəfdaş dəstək xətti və hesab meneceri.' },
      ],
    },
    howItWorks: {
      title: 'Necə İşləyir?',
      steps: [
        { title: 'Müraciət Edin', desc: 'Onlayn müraciət formasını doldurun. Şirkət məlumatlarınızı və əlaqə məlumatlarınızı paylaşın. Müraciətiniz 1 iş günü ərzində nəzərdən keçirilir.' },
        { title: 'Tərəfdaş Olun', desc: 'Müraciətiniz təsdiqləndikdən sonra fərdi tərəfdaş panelinizə giriş əldə edirsiniz. QR kodlarınız və yönləndirmə linkləriniz hazırdır.' },
        { title: 'Müştəri Yönləndirin', desc: 'Müştərilərinizi QR kod, xüsusi link və ya vizit kartı vasitəsilə bizə yönləndirin. Hər yönləndirmə sistemə avtomatik qeyd olunur.' },
        { title: 'Komissiya Qazanın', desc: 'Yönləndirdiyiniz müştəri hər dəfə sifariş verdikdə 20% komissiya qazanırsınız. Hər 15 gündən bir avtomatik ödənişlər alırsınız.' },
      ],
    },
    sectors: {
      title: 'Hədəf Sektorlar',
      subtitle: 'Hansı sektorlar üçün idealdır?',
      items: [
        { key: 'law', icon: 'Scale', title: 'Hüquq Büroları', desc: 'İş sənədləri, müqavilələr və hüquqi sənədlərin andlı tərcüməsinə ehtiyac.' },
        { key: 'visa', icon: 'Plane', title: 'Viza Məsləhətçiliyi', desc: 'Pasport, diplom və vətəndaşlıq sənədləri kimi andlı tərcümə tələb edən sənədlər.' },
        { key: 'education', icon: 'GraduationCap', title: 'Təhsil Məsləhətçiliyi', desc: 'Tələbə sənədlərinin andlı tərcüməsi və apostil prosesləri.' },
        { key: 'health', icon: 'HeartPulse', title: 'Sağlamlıq Turizmi', desc: 'Tibbi hesabatların, xəstə sənədlərinin və sağlamlıq sənədlərinin tərcüməsi.' },
        { key: 'patent', icon: 'Building2', title: 'Patent/Ticarət Nişanı Büroları', desc: 'Patent, ticarət nişanı qeydiyyatı və hüquqi sənədlərin texniki tərcüməsi.' },
        { key: 'realestate', icon: 'Home', title: 'Daşınmaz Əmlak Büroları', desc: 'Xarici investorlar üçün çıxarış, müqavilə və rəsmi sənəd tərcüməsi.' },
        { key: 'hr', icon: 'Briefcase', title: 'İnsan Resursları Məsləhətçiliyi', desc: 'Xaricdə işədüzəltmə üçün CV, diplom və zəmanət məktubu tərcüməsi.' },
        { key: 'software', icon: 'Code', title: 'Proqram Təminatı Şirkətləri', desc: 'Veb və mobil tətbiq lokallaşdırması, texniki sənəd tərcüməsi.' },
      ],
    },
    commission: {
      title: 'Komissiya Strukturu',
      stats: {
        commissionLabel: 'Standart Komissiya',
        commissionSub: 'Hər sifarişə görə',
        periodUnit: 'Gün',
        periodLabel: 'Ödəniş dövrü',
        feeLabel: 'Başlanğıc Haqqı',
        feeSub: 'Tamamilə pulsuz',
      },
      exampleTitle: 'Nümunə Qazanc Hesablaması',
      exampleOrderLabel: 'Yönləndirdiyiniz müştəridən sifariş',
      exampleRateLabel: 'Komissiya dərəcəsi',
      exampleEarningLabel: 'Qazancınız',
      note: 'Komissiya dərəcələri və şərtləri tərəfdaş razılaşmasına tabedir.',
    },
    form: {
      title: 'Tərəfdaş Müraciət Forması',
      subtitle: 'Formanı doldurun, 1 iş günü ərzində sizinlə əlaqə saxlayacağıq.',
      fields: {
        company: 'Şirkət/Təşkilat Adı',
        sector: 'Sektor',
        contactName: 'Əlaqədar Şəxsin Adı və Soyadı',
        titleRole: 'Vəzifə',
        email: 'E-poçt',
        phone: 'Telefon',
        potential: 'Təxmini aylıq yönləndirmə potensialınız',
        note: 'Əlavə etmək istədiyiniz qeydlər',
        agreement: 'Tərəfdaş razılaşmasının şərtlərini oxudum və qəbul edirəm.',
      },
      sectorPlaceholder: 'Seçin',
      sectorOptions: ['Hüquq Bürosu', 'Viza Məsləhətçiliyi', 'Təhsil Məsləhətçiliyi', 'Sağlamlıq Turizmi', 'Patent/Ticarət Nişanı Bürosu', 'Daşınmaz Əmlak', 'İnsan Resursları Məsləhətçiliyi', 'Proqram Təminatı', 'Digər'],
      potentialOptions: ['1-5 müştəri', '5-10 müştəri', '10-20 müştəri', '20+ müştəri'],
      submit: 'Müraciəti Göndər',
      success: 'Müraciətiniz qəbul olundu. Sizinlə əlaqə saxlayacağıq.',
      note: 'Müraciətiniz 1 iş günü ərzində nəzərdən keçiriləcək.',
    },
  },

  quote: {
    seo: {
      title: 'Dərhal Qiymət Hesablama',
      description: 'Sənədinizi yükləyin və ya təfərrüatları daxil edin, dərhal ilkin qiymətinizi alın.',
    },
    hero: {
      title: 'Dərhal Qiymət Hesablama',
      subtitle: 'Sənədinizi yükləyin və ya təfərrüatları daxil edin, dərhal ilkin qiymət alın.',
    },
    upload: {
      heading: 'Sənədlərinizi Yükləyin',
      privacy: 'Məlumatlarınız məxfi saxlanılır',
      tabFile: 'Fayl Yüklə',
      tabText: 'Mətn Daxil Et',
      chooseFile: 'Sənədlərinizi Seçin',
      formats: '.docx, .xlsx, .pdf, .pptx, .jpg, .png və 50+ format qəbul edilir · Fayl başına maksimum 100MB',
      dropHint: 'Bir və ya bir neçə faylı bu sahəyə sürüşdürüb buraxa bilərsiniz.',
      textPlaceholder: 'Mətninizi buraya yapışdırın və ya yazın…',
      totalWords: 'Ümumi söz sayı',
      extracting: 'Sözlər sayılır…',
      wordsUnit: 'söz',
      remove: 'Sil',
      unsupported:
        'Bu fayl növü üçün avtomatik söz sayımı mümkün olmadı. Zəhmət olmasa mətni "Mətn Daxil Et" ilə yapışdırın; qiymət verilərkən say komandamız tərəfindən yoxlanılacaq.',
      empty:
        'Faylda seçilə bilən mətn tapılmadı (skan edilmiş/şəkil ola bilər). Zəhmət olmasa "Mətn Daxil Et"dən istifadə edin, əks halda say qiymətləndirmə zamanı yoxlanılacaq.',
      error: 'Fayl oxuna bilmədi. Zəhmət olmasa yenidən cəhd edin və ya "Mətn Daxil Et"dən istifadə edin.',
      tooLarge: 'Fayl 100MB-dan böyük ola bilməz.',
      needInput: 'Qiymət üçün zəhmət olmasa fayl yükləyin və ya mətn daxil edin.',
    },
    fields: {
      upload: 'Sənəd Yüklə (istəyə bağlı)',
      uploadHint: 'PDF, DOC, DOCX və ya TXT — maksimum 10 MB',
      sourceLang: 'Mənbə Dili',
      targetLang: 'Hədəf Dili',
      serviceType: 'Xidmət Növü',
      documentType: 'Sənəd Növü',
      wordCount: 'Təxmini Söz Sayı',
      wordCountHint: 'Sürgücdən istifadə edin və ya rəqəmi əl ilə daxil edin.',
      options: 'Əlavə seçimlər',
      calculate: 'Qiyməti hesabla',
    },
    options: {
      urgent: 'Təcili Çatdırılma',
      notarization: 'Notariat Təsdiqi',
      physicalDelivery: 'Fiziki Çatdırılma',
    },
    languages: {
      tr: 'Türk dili',
      en: 'İngilis dili',
      de: 'Alman dili',
      fr: 'Fransız dili',
      es: 'İspan dili',
      it: 'İtalyan dili',
      ru: 'Rus dili',
      ar: 'Ərəb dili',
      nl: 'Holland dili',
      az: 'Azərbaycan dili',
      pl: 'Polyak dili',
      bg: 'Bolqar dili',
      pt: 'Portuqal dili',
      da: 'Danimarka dili',
    },
    documentTypes: {
      diploma: 'Diplom',
      passport: 'Pasport',
      'civil-registry': 'Vətəndaşlıq Vəziyyəti Aktı Çıxarışı',
      contract: 'Müqavilə',
      'medical-report': 'Tibbi Hesabat',
      'technical-doc': 'Texniki Sənəd',
      'court-doc': 'Məhkəmə Sənədi',
      other: 'Digər',
    },
    result: {
      title: 'İlkin Qiymət',
      basePrice: 'Baza xidmət haqqı',
      wordPrice: 'Söz haqqı',
      addons: 'Əlavə xidmətlər',
      total: 'Cəmi',
      vat: 'ƏDV',
      delivery: 'Təxmini çatdırılma müddəti',
      deliveryUnit: 'iş günü',
      disclaimer: 'Bu ilkin qiymətdir; yekun qiymət sənəd baxışından sonra təsdiqlənir.',
      order: 'Sifariş ver',
      whatsapp: 'WhatsApp vasitəsilə əlaqə',
      estimatedWords: 'Təxmini sözlər (avtomatik — demo)',
    },
    orderConfirm: {
      title: 'Sifarişiniz qəbul olundu',
      number: 'Sifariş No',
      desc: 'Sorğunuz və sənədləriniz saxlanıldı. Ekspert komandamız sənədi nəzərdən keçirəcək və ən qısa zamanda sizinlə əlaqə saxlayacaq.',
      viewOrders: 'Sifarişlərim',
      submitting: 'Sifariş yaradılır…',
      error: 'Sifarişiniz yaradılarkən problem yarandı. Zəhmət olmasa yenidən cəhd edin.',
    },
    gate: {
      title: 'Qiymətiniz hazırdır',
      subtitle: 'Qiyməti görmək və sifariş vermək üçün daxil olun və ya məlumatlarınızı təsdiqləyin.',
      loginCta: 'Daxil ol / Qeydiyyat',
      or: 'və ya sürətlə davam edin',
      firstName: 'Ad',
      lastName: 'Soyad',
      email: 'E-poçt',
      phone: "Telefon nömrəsi",
      sendCode: 'Təsdiq Kodu Göndər',
      codeLabel: 'Təsdiq Kodu',
      codeSentA: 'ünvanına təsdiq kodu göndərildi.',
      verify: 'Təsdiqlə və Qiyməti Gör',
      resend: 'Kodu yenidən göndər',
      resent: 'Yeni kod göndərildi.',
      back: 'Məlumatları dəyiş',
      errNames: 'Ad və soyad tələb olunur.',
      errEmail: 'Etibarlı e-poçt daxil edin.',
      errPhone: "Düzgün telefon nömrəsi daxil edin.",
      errCode: 'Zəhmət olmasa kodu tam daxil edin.',
      note: 'E-poçtunuz yalnız qiymət və sifariş üçün istifadə olunur.',
    },
    note: {
      label: 'Sifarişiniz haqqında qeyd (istəyə bağlı)',
      placeholder: 'Çatdırılma, terminologiya və ya xüsusi istəklərinizi buraya yaza bilərsiniz.',
    },

    checkout: {
      title: "Çatdırılma məlumatları",
      subtitle: "Fiziki/andlı sənədiniz bu ünvana göndəriləcək.",
      firstName: "Ad",
      lastName: "Soyad",
      phone: "Telefon",
      address: "Tam ünvan",
      addressPlaceholder: "Küçə, bina və mənzil nömrəsi…",
      city: "Şəhər",
      postalCode: "Poçt kodu",
      country: "Ölkə",
      submit: "Sifarişi tamamla",
      submitting: "Sifariş yaradılır…",
      cancel: "Ləğv et",
      errRequired: "Zəhmət olmasa, məcburi sahələri doldurun.",
      note: "Bu məlumatlar yalnız kuryer çatdırılması üçün istifadə olunur.",
    },
  },

  order: {
    seo: {
      title: 'Sifariş İzləmə',
      description: 'Sifarişinizin statusunu izləyin.',
    },
    numberLabel: 'Sifariş No',
    placedOn: 'Sifariş tarixi',
    estimatedLabel: 'Təxmini tərcümə çatdırılması',
    cargoEstimatedLabel: 'Təxmini göndərmə tarixi',
    timelineTitle: 'Sifariş statusu',
    steps: {
      received: 'Sifarişiniz qəbul olundu',
      in_progress: 'İcra olunur',
      translated: 'Tərcümə tamamlandı',
      shipped: 'Göndərildi',
      delivered: 'Çatdırıldı',
      cancelled: 'Sifariş ləğv edildi',
    },
    stepDesc: {
      received: 'Sorğunuz və sənədləriniz sistemimizə çatdı. Ekspert komandamız onu nəzərdən keçirib tezliklə başlayacaq.',
      in_progress: 'Ekspert tərcüməçimiz tərcümənizə başladı.',
      translated: 'Tərcüməniz tamamlandı və yekun yoxlamalar aparıldı.',
      shipped: 'Sənədiniz kuryerə təhvil verildi; onu aşağıdakı düymə ilə izləyə bilərsiniz.',
      delivered: 'Sənədiniz sizə e-poçt vasitəsilə göndərildi.',
      cancelled: 'Bu sifariş ləğv edildi. Suallarınız üçün zəhmət olmasa bizimlə əlaqə saxlayın.',
    },
    cargoReady: 'Sənədiniz göndərildi. Onu bir toxunuşla izləyin:',
    cargoPending: 'İzləmə kodu sənədiniz göndərildikdən sonra burada görünəcək.',
    trackCargo: 'Göndərişimi İzlə',
    digitalPending: 'Tərcüməniz tamamlandıqdan sonra fayllarınız sizə e-poçt vasitəsilə göndəriləcək.',
    digitalDelivered: 'Tərcüməniz sizə e-poçt vasitəsilə göndərildi. Poçt qutunuzu (və spam qovluğunu) yoxlayın.',
    detailsTitle: 'Sifariş təfərrüatları',
    fields: {
      service: 'Xidmət',
      langs: 'Dillər',
      documentType: 'Sənəd növü',
      words: 'Sözlər',
      delivery: 'Təxmini müddət',
      total: 'Məbləğ',
      note: 'Qeydiniz',
      deliveryAddress: "Çatdırılma ünvanı",
    },
    myOrders: 'Sifarişlərim',
    backHome: 'Ana səhifəyə qayıt',
    whatsapp: 'WhatsApp vasitəsilə əlaqə',
    loading: 'Sifariş yüklənir…',
    loginRequired: {
      title: 'Sifarişinizi görmək üçün daxil olun',
      desc: 'Sifariş təfərrüatlarınıza yalnız hesabınızla daxil olduqdan sonra çıxış əldə edə bilərsiniz.',
      login: 'Daxil ol',
    },
    notFound: {
      title: 'Sifariş tapılmadı',
      desc: 'Bu sifariş nömrəsi sizə aid deyil və ya mövcud deyil. Zəhmət olmasa linki yoxlayın.',
      home: 'Ana səhifəyə qayıt',
    },
  },

  faq: {
    seo: {
      title: 'Tez-tez Verilən Suallar',
      description: 'Andlı tərcümə, çatdırılma müddəti, qiymətqoyma, notariat təsdiqi və korporativ vaxt seçimləri haqqında tez-tez verilən suallar.',
    },
    hero: { title: 'Tez-tez Verilən Suallar', subtitle: 'Axtardığınız cavab buradadır.' },
    categoriesTitle: 'Kateqoriyalar',
    searchPlaceholder: 'Sual və ya açar sözlər axtarın…',
    empty: 'Axtarışınıza uyğun sual tapılmadı. Fərqli söz sınayın və ya bizimlə əlaqə saxlayın.',
    categories: FAQ_CATEGORIES_AZ,
    items: FAQ_ITEMS_AZ,
    notFound: {
      title: 'Sualınızın cavabını tapmadınız?',
      contact: 'Bizimlə əlaqə',
      whatsapp: 'WhatsApp Dəstəyi',
    },
  },

  contact: {
    seo: {
      title: 'Əlaqə',
      description: 'TercümExpert ilə əlaqə saxlayın: telefon, e-poçt, WhatsApp və əlaqə forması.',
    },
    hero: { title: 'Əlaqə', subtitle: 'Sizə necə kömək edə bilərik?' },
    infoTitle: 'Əlaqə məlumatları',
    labels: {
      phone: 'Telefon',
      email: 'E-poçt',
      whatsapp: 'WhatsApp',
      address: 'Ünvan',
      hours: 'İş saatları',
    },
    form: {
      title: 'Bizimlə əlaqə',
      fields: {
        name: 'Ad və Soyad',
        email: 'E-poçt',
        phone: 'Telefon',
        subject: 'Mövzu',
        message: 'Mesaj',
        consent: 'KVKK Məlumatlandırma Bəyanatını oxudum və qəbul edirəm.',
      },
      submit: 'Mesaj Göndər',
      success: 'Mesajınız qəbul olundu. Tezliklə sizinlə əlaqə saxlayacağıq.',
    },
    map: {
      title: 'Yerləşdiyimiz Yer',
      subtitle: 'Bizi xəritədə tapın',
      placeholder: 'Xəritə sahəsi',
      note: 'Yerləşmə xəritəsi tezliklə burada göstəriləcək.',
    },
  },

  auth: {
    seo: {
      title: 'Daxil ol / Qeydiyyat',
      description: 'TercümExpert hesabınıza daxil olun və ya yeni hesab yaradın.',
    },
    tabs: { login: 'Daxil ol', register: 'Qeydiyyat' },
    google: 'Google ilə davam et',
    or: 'və ya',
    fields: {
      firstName: 'Ad',
      lastName: 'Soyad',
      email: 'E-poçt',
      password: 'Şifrə',
      code: 'Təsdiq Kodu',
    },
    login: {
      title: 'Hesabınıza daxil olun',
      submit: 'Daxil ol',
      noAccount: 'Hesabınız yoxdur?',
      switchToRegister: 'Qeydiyyatdan keçin',
    },
    register: {
      title: 'Yeni hesab yaradın',
      submit: 'Qeydiyyat',
      haveAccount: 'Artıq hesabınız var?',
      switchToLogin: 'Daxil olun',
      consent: 'Hesab yaratmaqla KVKK Məlumatlandırma Bəyanatını və Məxfilik Siyasətini qəbul edirəm.',
    },
    verify: {
      title: 'E-poçtunuzu təsdiqləyin',
      desc: '— bu ünvana göndərdiyimiz 6 rəqəmli kodu daxil edin.',
      submit: 'Təsdiqlə və Davam et',
      spam: 'Kod bir neçə dəqiqə gecikə bilər; həmçinin spam/junk qovluğunuzu yoxlayın.',
      resend: 'Kodu yenidən göndər',
      resent: 'Yeni kod göndərildi.',
      back: 'Geri qayıt',
    },
    signedIn: {
      title: 'Hesabım',
      greeting: 'Xoş gəldiniz',
      logout: 'Çıxış',
    },
    orders: {
      title: 'Sifarişlərim',
      empty: 'Hələ sifarişiniz yoxdur. İlk sifarişinizi Qiyməti hesabla bölməsindən yarada bilərsiniz.',
      loading: 'Sifarişlər yüklənir…',
      error: 'Sifarişlər yüklənə bilmədi. Zəhmət olmasa səhifəni yeniləyin.',
      status: {
        received: 'Qəbul olundu',
        in_progress: 'İcra olunur',
        translated: 'Tərcümə tamamlandı',
        shipped: 'Göndərildi',
        delivered: 'Çatdırıldı',
        cancelled: 'Ləğv edildi',
      },
      track: 'İzlə',
    },
    errors: {
      nameRequired: 'Ad və soyad tələb olunur.',
      emailInvalid: 'Etibarlı e-poçt daxil edin.',
      passwordShort: 'Şifrə ən azı 6 simvol olmalıdır.',
      codeInvalid: 'Zəhmət olmasa 6 rəqəmli kodu daxil edin.',
      consentRequired: 'Davam etmək üçün təsdiq tələb olunur.',
    },
  },

  blog: {
    seo: { title: 'Bloq', description: 'Tərcümə, notariat, apostil və lokallaşdırma haqqında bələdçi məzmun.' },
    hero: { title: 'Bloq', subtitle: 'Tərcümə dünyasından bələdçilər.' },
    searchPlaceholder: 'Yazıları axtarın…',
    readingTime: 'dəq oxuma',
    relatedTitle: 'Əlaqəli yazılar',
    allCategories: 'Hamısı',
    empty: 'Bu meyara uyğun yazı tapılmadı.',
  },

  legal: {
    lastUpdatedLabel: `Son yenilənmə`,
    draftNotice: `Aşağıdakı mətndə kvadrat mötərizə ilə göstərilən sahələr ([...]) şirkət məlumatlarınızla doldurulacaqdır. Mətnlər ümumi məlumatlandırma məqsədi daşıyır və dərc edilməzdən əvvəl hüquq mütəxəssisi tərəfindən nəzərdən keçirilməsi tövsiyə olunur.`,
    kvkk: {
      seo: { title: `KVKK Məlumatlandırma Mətni`, description: `6698 saylı KVKK çərçivəsində şəxsi məlumatlarınızın işlənməsinə dair məlumatlandırma mətni.` },
      title: `KVKK Məlumatlandırma Mətni`,
      sections: [
        { heading: `Məlumat Məsulu`, body: `6698 saylı Şəxsi Məlumatların Qorunması Qanunu (“KVKK”) əsasında şəxsi məlumatlarınız, məlumat məsulu sifəti ilə [ŞİRKET ÜNVANI] (“TercümExpert”) tərəfindən aşağıda izah edilən çərçivədə işlənir. Ünvan: [ADRES]. E-poçt: [E-POSTA]. Telefon: [TELEFON].` },
        { heading: `İşlənən Şəxsi Məlumatlar`, body: `Kimlik və əlaqə məlumatlarınız (ad, soyad, e-poçt ünvanı, telefon nömrəsi), çatdırılma ünvanı məlumatlarınız, sifariş və əməliyyat məlumatlarınız, tərcümə məqsədi ilə bizə göndərdiyiniz sənədlərin məzmunundakı məlumatlar, habelə saytdan istifadənizə dair əməliyyat təhlükəsizliyi məlumatları (IP ünvanı, sessiya və çərəz qeydləri) işlənir.` },
        { heading: `İşlənmə Məqsədləri`, body: `Şəxsi məlumatlarınız; tərcümə, andlı tərcümə, notariat və apostil təsdiqi ilə bağlı xidmətlərin göstərilməsi, təkliflərin hazırlanması və sifarişlərin idarə edilməsi, müştəri münasibətləri ilə müraciət və şikayətlərin idarə olunması, müqavilə və qanuni öhdəliklərin yerinə yetirilməsi və xidmət təhlükəsizliyinin təmin edilməsi məqsədləri ilə işlənir.` },
        { heading: `İşlənmənin Hüquqi Əsasları`, body: `Məlumatlarınız; müqavilənin bağlanması və ya icrası üçün zəruri olması, hüquqi öhdəliklərimizin yerinə yetirilməsi, hüququn müəyyən edilməsi və qorunması, habelə əsas hüquq və azadlıqlarınıza zərər verməmək şərti ilə qanuni maraqlarımız hüquqi əsaslarına istinadən; zəruri hallarda isə açıq razılığınıza əsasən işlənir (KVKK m.5 və m.6).` },
        { heading: `Toplanma Üsulu`, body: `Şəxsi məlumatlarınız; veb-saytdakı formalar, üzvlük və sifariş prosesləri, e-poçt və digər əlaqə kanalları vasitəsilə elektron mühitdə toplanır.` },
        { heading: `Şəxsi Məlumatların Ötürülməsi`, body: `Məlumatlarınız, xidmətin tələb etdiyi həcmdə; hostinq, infrastruktur, kimlik doğrulama, e-poçt və analitika xidmətləri aldığımız ölkə daxilində və xaricində yerləşən təchizatçılarımıza və səlahiyyətli dövlət qurum və təşkilatlarına, KVKK m.8 və m.9-dakı şərtlərə uyğun olaraq ötürülə bilər. İstifadə etdiyimiz bəzi infrastruktur və xidmət təminatçılarının serverləri xaricdə yerləşdiyindən, məlumatlarınız qanunvericilikdə nəzərdə tutulan təminatlar çərçivəsində xaricə ötürülə bilər.` },
        { heading: `Saxlanma Müddətləri`, body: `Şəxsi məlumatlarınız, işlənmə məqsədinin tələb etdiyi müddət ilə müvafiq qanunvericilikdə (vergi, ticarət və istehlakçı qanunvericiliyi kimi) nəzərdə tutulan iddia müddəti və saxlanma müddətləri boyunca saxlanılır; müddətlərin bitməsi ilə silinir, məhv edilir və ya anonimləşdirilir.` },
        { heading: `Məlumat Sahibinin Hüquqları`, body: `KVKK m.11 əsasında; şəxsi məlumatlarınızın işlənib-işlənmədiyini öyrənmə, işlənmişsə məlumat tələb etmə, işlənmə məqsədini və məqsədinə uyğun istifadə edilib-edilmədiyini öyrənmə, ölkə daxilində və ya xaricində ötürüldüyü üçüncü şəxsləri bilmə, natamam və ya səhv işlənmişsə düzəldilməsini, şərtlər yarandıqda silinməsini və ya məhv edilməsini tələb etmə, bu əməliyyatların ötürüldüyü üçüncü şəxslərə bildirilməsini tələb etmə, yalnız avtomatik sistemlərlə təhlil nəticəsində əleyhinizə bir nəticənin yaranmasına etiraz etmə və zərərə uğradığınız halda zərərin ödənilməsini tələb etmə hüquqlarına maliksiniz.` },
        { heading: `Müraciət Üsulu`, body: `Hüquqlarınıza dair müraciətlərinizi, “Veri Sorumlusuna Başvuru Usul ve Esasları Hakkında Tebliğ”ə uyğun olaraq [E-POSTA] ünvanına və ya [ADRES] ünvanına yazılı şəkildə göndərə bilərsiniz. Müraciətiniz, xarakterinə görə ən qısa müddətdə və ən geci otuz gün ərzində nəticələndirilir.` },
      ],
    },
    privacy: {
      seo: { title: `Məxfilik Siyasəti`, description: `Şəxsi məlumatlarınızın və sənədlərinizin məxfiliyinə dair siyasətimiz.` },
      title: `Məxfilik Siyasəti`,
      sections: [
        { heading: `Giriş`, body: `TercümExpert olaraq məxfiliyinizə önəm veririk. Bu Məxfilik Siyasəti, [WEB ADRESİ] vasitəsilə təqdim etdiyimiz xidmətlərdə hansı məlumatları, hansı məqsədlərlə topladığımızı və necə qoruduğumuzu izah edir. Şəxsi məlumatların işlənməsinə dair ətraflı məlumatı KVKK Məlumatlandırma Mətnindən əldə edə bilərsiniz.` },
        { heading: `Topladığımız Məlumatlar`, body: `Hesab və əlaqə məlumatları (ad, soyad, e-poçt, telefon), sifariş və çatdırılma məlumatları, tərcümə üçün bizə göndərdiyiniz sənədlər və onların məzmunu, ödənişə dair əməliyyat məlumatları və saytdan istifadənizə dair texniki məlumatlar (IP ünvanı, brauzer məlumatı, çərəz qeydləri) tərəfimizdən toplana bilər.` },
        { heading: `Məlumatların İstifadə Məqsədlərimiz`, body: `Məlumatlarınızı; xidmətləri təqdim etmək, təklif və sifarişləri idarə etmək, sizinlə əlaqə saxlamaq, qanuni öhdəliklərimizi yerinə yetirmək və xidmət keyfiyyəti ilə təhlükəsizliyini təkmilləşdirmək üçün istifadə edirik. Sənədlərinizi yalnız tələb etdiyiniz xidmətin tələb etdiyi həcmdə işləyirik.` },
        { heading: `Sənəd Məxfiliyi`, body: `Tərcüməyə mövzu olan sənədləriniz məxfi sayılır. Bu sənədlərə yalnız müvafiq xidməti həyata keçirən səlahiyyətli tərcüməçi və personal, işin tələb etdiyi müddət boyunca giriş edir; sənədləriniz xidmət məqsədi xaricində üçüncü şəxslərlə paylaşılmır.` },
        { heading: `Üçüncü Tərəf Xidmət Təminatçıları`, body: `Xidmətlərimizi təqdim edərkən hostinq və infrastruktur, kimlik doğrulama, e-poçt göndərişi, analitika və (aktivləşdirildikdə) ödəniş sahələrində etibarlı üçüncü tərəf təminatçılardan istifadə edirik. Bu təminatçılar məlumatlarınıza yalnız onlara tapşırılan xidməti göstərmək məqsədi ilə və müqavilə üzrə məxfilik öhdəlikləri altında giriş edə bilər; bir qisminin serverləri xaricdə yerləşə bilər.` },
        { heading: `Məlumat Təhlükəsizliyi`, body: `Məlumatlarınızı icazəsiz girişə qarşı qorumaq üçün ötürülmə zamanı şifrələmə, giriş məhdudiyyətləri və müvafiq inzibati və texniki tədbirləri tətbiq edirik. Heç bir üsul mütləq təhlükəsizlik təmin edə bilməsə də, məlumatlarınızı qorumaq üçün ağlabatan və müasir tədbirlər görürük.` },
        { heading: `Çərəzlər`, body: `Saytımızda çərəzlər və oxşar texnologiyalar istifadə olunur. Növləri və seçim idarəçiliyi haqqında ətraflı məlumat üçün Çərəz Siyasətini nəzərdən keçirə bilərsiniz.` },
        { heading: `Hüquqlarınız`, body: `Şəxsi məlumatlarınıza giriş, düzəliş və silmə daxil olmaqla KVKK çərçivəsindəki hüquqlarınızdan istifadə edə bilərsiniz. Müraciətləriniz üçün [E-POSTA] ünvanı vasitəsilə bizimlə əlaqə saxlaya bilərsiniz.` },
        { heading: `Uşaqların Məxfiliyi`, body: `Xidmətlərimiz 18 yaşdan kiçik şəxslərə yönəlik deyil və biz bilərəkdən uşaqlara aid şəxsi məlumat toplamırıq.` },
        { heading: `Dəyişikliklər`, body: `Bu siyasət vaxtaşırı yenilənə bilər. Ən son versiya həmişə bu səhifədə dərc olunur; mühüm dəyişikliklərdə uyğun üsullarla məlumatlandırma aparılır.` },
        { heading: `Əlaqə`, body: `Məxfiliklə bağlı suallarınız üçün: E-poçt: [E-POSTA] · Telefon: [TELEFON] · Ünvan: [ADRES].` },
      ],
    },
    distanceSales: {
      seo: { title: `Məsafəli Satış Müqaviləsi`, description: `6502 saylı Qanun çərçivəsində xidmət satışına dair məsafəli satış müqaviləsi.` },
      title: `Məsafəli Satış Müqaviləsi`,
      sections: [
        { heading: `Tərəflər`, body: `Bu Məsafəli Satış Müqaviləsi (“Müqavilə”); bir tərəfdə [ŞİRKET ÜNVANI] (“Satıcı”; ünvan: [ADRES], e-poçt: [E-POSTA], telefon: [TELEFON]) ilə digər tərəfdə sifarişi verən istehlakçı (“Alıcı”) arasında, 6502 saylı Tüketicinin Korunması Hakkında Kanun və Mesafeli Sözleşmeler Yönetmeliği əsasında elektron mühitdə bağlanmışdır.` },
        { heading: `Müqavilənin Mövzusu`, body: `Müqavilənin mövzusu; Alıcının [WEB ADRESİ] vasitəsilə elektron mühitdə sifariş etdiyi, xüsusiyyətləri və satış dəyəri sifariş xülasəsində göstərilən tərcümə, andlı tərcümə, notariat və apostil təsdiqi ilə bağlı xidmətlərin göstərilməsidir.` },
        { heading: `Xidmətin Xüsusiyyətləri və Dəyəri`, body: `Sifariş edilən xidmətin növü, əhatə dairəsi, təhvil forması (rəqəmsal və ya kargo) və vergilər daxil ümumi dəyəri, sifariş zamanı Alıcıya aydın şəkildə göstərilir və sifariş təsdiqində yer alır. Qiymətləndirmə, seçilən xidmətə və sənəd xüsusiyyətlərinə görə hesablanır.` },
        { heading: `Ödəniş`, body: `Ödəniş, sifariş mərhələsində təqdim olunan ödəniş üsulları ilə həyata keçirilir. Sifariş, ödənişin təsdiqindən sonra işə salınır.` },
        { heading: `İcra və Təhvil`, body: `Rəqəmsal təhvillərdə tərcümə, tamamlandıqdan sonra Alıcının hesabı və ya e-poçtu vasitəsilə göndərilir. Fiziki, yaş imzalı və ya andlı sənədlərdə təhvil, Alıcının bildirdiyi ünvana kargo ilə edilir. Təxmini təhvil müddətləri sifariş zamanı göstərilir; sənəd sıxlığına və təsdiq proseslərinə görə dəyişə bilər.` },
        { heading: `İmtina Hüququ`, body: `Alıcı, bir qayda olaraq xidmət göstərilməsinə dair müqavilələrdə, müqavilənin bağlandığı tarixdən etibarən on dörd (14) gün ərzində hər hansı bir səbəb göstərmədən imtina hüququna malikdir. Lakin aşağıda göstərilən istisnalar qüvvədə qalır.` },
        { heading: `İmtina Hüququnun İstisnaları`, body: `Mesafeli Sözleşmeler Yönetmeliği m.15 əsasında; Alıcının razılığı ilə icrasına başlanan və imtina müddəti bitmədən tamamlanan xidmətlərdə, habelə Alıcının istəkləri və ya şəxsi ehtiyacları əsasında xüsusi olaraq hazırlanan mal və xidmətlərdə (şəxsə və ya sənədə özəl hazırlanan tərcümə və təsdiq xidmətləri daxil) imtina hüququndan istifadə edilə bilməz. Tərcümə işinə başlanmazdan əvvəl göndərilən ləğv müraciətləri ayrıca dəyərləndirilir.` },
        { heading: `Ləğv və Geri Qaytarma`, body: `İcrasına başlanmamış sifarişlərdə ləğv müraciətləri [E-POSTA] vasitəsilə göndərilə bilər; uyğun görülən geri qaytarmalar, ödənişin edildiyi üsulla ağlabatan müddət ərzində həyata keçirilir. İcrasına başlanmış və ya tamamlanmış şəxsə özəl xidmətlərdə geri qaytarma, işin xarakteri səbəbindən mümkün olmaya bilər.` },
        { heading: `Mübahisələrin Həlli`, body: `Bu Müqavilədən yarana biləcək mübahisələrdə, Ticaret Bakanlığı tərəfindən hər il elan edilən maliyyə hədləri daxilində Alıcının yaşayış yerindəki və ya əməliyyatın aparıldığı yerdəki Tüketici Hakem Heyetleri ilə İstehlakçı Məhkəmələri səlahiyyətlidir.` },
        { heading: `Qüvvəyə Minmə`, body: `Alıcı, sifarişi təsdiq etməklə bu Müqavilənin bütün şərtlərini oxuduğunu və qəbul etdiyini bəyan edir. Müqavilə, sifarişin təsdiqi ilə qüvvəyə minir.` },
      ],
    },
    cookies: {
      seo: { title: `Çərəz Siyasəti`, description: `Saytımızda istifadə olunan çərəzlər və seçim idarəçiliyi haqqında məlumat.` },
      title: `Çərəz Siyasəti`,
      sections: [
        { heading: `Çərəz Nədir?`, body: `Çərəzlər, bir veb-saytı ziyarət etdiyiniz zaman brauzerinizə yadda saxlanılan kiçik mətn fayllarıdır. Saytı daha təhlükəsiz və funksional etmək, seçimlərinizi yadda saxlamaq və istifadə statistikası əldə etmək üçün istifadə olunur.` },
        { heading: `Nə Üçün Çərəz İstifadə Edirik?`, body: `Çərəzləri; saytın əsas funksiyalarını təmin etmək, sessiya təhlükəsizliyini qorumaq, performansı ölçmək və razılığınıza bağlı olaraq xidmətlərimizi təkmilləşdirmək ilə marketinq fəaliyyətlərini həyata keçirmək üçün istifadə edirik.` },
        { heading: `Çərəz Kateqoriyaları`, body: `Zəruri çərəzlər saytın işləməsi və təhlükəsizliyi üçün lazımdır və söndürülə bilməz. Performans və analitika çərəzləri ziyarətçi qarşılıqlı əlaqəsini anlamağımıza kömək edir. Marketinq çərəzləri maraq dairələrinizə uyğun məzmun və reklam təqdim edilməsinə dəstək olur. Seçim çərəzləri dil kimi seçimlərinizi yadda saxlayır. Analitika və marketinq çərəzləri yalnız açıq razılığınızla işləyir.` },
        { heading: `Üçüncü Tərəf Çərəzləri`, body: `Analitika və marketinq məqsədi ilə üçüncü tərəf xidmətlərdən (məsələn, ziyarətçi statistikası və reklam ölçmə vasitələrindən) istifadə edə bilərik. Bu xidmətlər öz çərəzlərini yerləşdirə və məlumatları öz məxfilik siyasətləri çərçivəsində işləyə bilər.` },
        { heading: `Çərəz Seçimlərinin İdarə Edilməsi`, body: `Zəruri olmayan çərəzlərə dair seçimlərinizi, saytda təqdim olunan çərəz seçim vasitəsi vasitəsilə istədiyiniz zaman verə və ya dəyişə bilərsiniz. Bundan əlavə, brauzerinizin parametrlərindən çərəzləri silə və ya bloklaya bilərsiniz; lakin bu halda saytın bəzi hissələri düzgün işləməyə bilər.` },
        { heading: `Saxlanma Müddətləri`, body: `Çərəzlər, növündən asılı olaraq sessiya boyunca və ya müəyyən bir müddət üçün saxlanılır. Sessiya çərəzləri brauzer bağlandıqda silinir; daimi çərəzlər isə müəyyən edilən müddət sonunda və ya siz sildikdə sona çatır.` },
        { heading: `Dəyişikliklər`, body: `Bu Çərəz Siyasəti vaxtaşırı yenilənə bilər. Ən son versiya həmişə bu səhifədə dərc olunur.` },
      ],
    },
  },

  footer: {
    tagline: 'Peşəkar tərcümə xidmətlərində etibarlı tərəfdaşınız.',
    columns: {
      quickLinks: 'Sürətli Keçidlər',
      services: 'Xidmətlər',
      contact: 'Əlaqə',
    },
    quickLinks: {
      corporate: 'Korporativ',
      services: 'Xidmətlərimiz',
      quote: 'Qiyməti hesabla',
      blog: 'Bloq',
      faq: 'Tez-tez Verilən Suallar',
      contact: 'Əlaqə',
    },
    serviceLinks: {
      sworn: 'Andlı Tərcümə',
      notarized: 'Notariat Təsdiqli Tərcümə',
      apostille: 'Apostil Prosesi',
      corporate: 'Korporativ Həllər',
      partnership: 'Tərəfdaşlıq Proqramı',
    },
    legal: {
      kvkk: 'KVKK',
      privacy: 'Məxfilik Siyasəti',
      distanceSales: 'Məsafədən Satış Müqaviləsi',
      cookies: 'Kuki Siyasəti',
    },
    socialTitle: 'Bizi izləyin',
    whatsapp: 'WhatsApp Dəstəyi',
    rights: 'Bütün hüquqlar qorunur.',
  },

  cookie: {
    title: 'Kuki seçimləri',
    desc: 'Təcrübənizi yaxşılaşdırmaq üçün kukilərdən istifadə edirik. Zəruri kukilərdən başqaları yalnız razılığınızla işləyir.',
    accept: 'Qəbul et',
    reject: 'Rədd et',
    manage: 'Seçimləri İdarə Et',
    save: 'Seçimləri Saxla',
    categories: {
      necessary: { label: 'Zəruri', desc: 'Saytın işləməsi üçün tələb olunur; söndürülə bilməz.' },
      analytics: { label: 'Analitik', desc: 'İstifadəni anlamağımıza kömək edir.' },
      marketing: { label: 'Marketinq', desc: 'Uyğun məzmun və reklamlar üçün.' },
      preferences: { label: 'Seçimlər', desc: 'Seçimlərinizi yadda saxlayır.' },
    },
  },

  chatbot: {
    nudge: 'Sizə necə kömək edə bilərəm?',
    title: 'TercümExpert Dəstəyi',
    open: 'Söhbəti aç',
    close: 'Söhbəti bağla',
    minimize: 'Kiçilt',
    clear: 'Söhbəti təmizlə',
    inputPlaceholder: 'Mesajınızı yazın…',
    send: 'Göndər',
    typing: 'Yazır…',
    welcome:
      'Salam və TercümExpert-ə xoş gəldiniz. Tərcümə, qiymətqoyma, notariat təsdiqi, apostil və ya korporativ xidmətlərdə sizə kömək edə bilərəm.',
    quickQuestions: [
      'Qiymət necə hesablanır?',
      'Andlı tərcümə nədir?',
      'Sənəd yükləmək istəyirəm',
      'Korporativ qiymət istəyirəm',
      'Notariat təsdiqi tələb olunurmu?',
      'Məni nümayəndəyə bağlayın',
    ],
    handoff: 'Nümayəndəyə bağlan',
    toWhatsapp: 'WhatsApp-a keçir',
    disclaimer: 'Bu məlumat ümumidir; dəqiq tələbləri müvafiq qurumla təsdiqləyin.',
    sensitiveWarning:
      'Zəhmət olmasa həssas şəxsi məlumatları bu söhbət vasitəsilə paylaşmayın. Sənədlərinizi təhlükəsiz yükləmə sahəsi vasitəsilə göndərə bilərsiniz.',
    answers: [
      `Qiymət; sənədinizin söz sayına, dil cütünə, xidmət növünə (andlı, notarial təsdiqli, apostil) və çatdırılma müddətinə əsasən hesablanır. Dərhal təxmini qiymət üçün Qiymət Hesabla səhifəsindən sənədinizi yükləyə və ya məlumatları daxil edə bilərsiniz.`,
      `Andlı tərcümə, andlı tərcüməçi tərəfindən edilən və tərcüməçinin imzası və möhürü ilə təsdiqlənən rəsmi tərcümədir. Rəsmi qurumlar çox vaxt andlı tərcümə tələb edir; lazım gəldikdə notarial təsdiq də əlavə oluna bilər.`,
      `Sənədinizi Qiymət Hesabla səhifəsindəki təhlükəsiz yükləmə sahəsindən göndərə bilərsiniz. Yüklədikdən sonra təxmini qiyməti dərhal görür və sifarişinizi tamamlaya bilərsiniz.`,
      `Korporativ ehtiyaclarınız üçün müntəzəm və həcmli tərcümələrdə xüsusi qiymətləndirmə və prioritet çatdırılma təklif edirik. Ətraflı məlumat üçün Korporativ səhifəmizlə tanış ola və ya bizimlə əlaqə saxlaya bilərsiniz.`,
      `Notarial təsdiq ehtiyacı, sənədi təqdim edəcəyiniz quruma və əməliyyatın növünə görə dəyişir. Bəzi əməliyyatlar yalnız andlı tərcüməni qəbul edir, bəziləri isə notarial təsdiq də tələb edir. Əmin deyilsinizsə, sizə kömək edək.`,
      `Sizi dərhal müştəri təmsilçimizə qoşaq. Aşağıdakı düymə vasitəsilə WhatsApp üzərindən bizə yaza bilərsiniz.`,
    ],
    fallback: `Sualınızla bağlı sizə ən doğru köməyi müştəri təmsilçimiz göstərə bilər. Aşağıdakı düymə vasitəsilə WhatsApp üzərindən bizə yaza bilərsiniz; mesajınız hazır şəkildə göndəriləcək.`,
  },

  notFound: {
    seo: { title: 'Səhifə tapılmadı', description: 'Axtardığınız səhifə tapılmadı.' },
    title: 'Səhifə tapılmadı',
    desc: 'Axtardığınız səhifə köçürülmüş və ya heç vaxt mövcud olmamış ola bilər.',
    home: 'Ana səhifəyə qayıt',
  },
}
