import type { PartialDictionary } from '@/types/i18n'
import { FAQ_CATEGORIES_AZ, FAQ_ITEMS_AZ } from '@/content/faq-data.az'

export const az: PartialDictionary = {
  common: {
    tagline: 'Peşəkar tərcümə xidmətlərində etibarlı tərəfdaşınız.',
    nav: {
      home: 'Ana səhifə',
      services: 'Xidmətlər',
      quote: 'Qiymət al',
      corporate: 'Korporativ',
      partnership: 'Tərəfdaşlıq',
      blog: 'Bloq',
      faq: 'FAQ',
      contact: 'Əlaqə',
    },
    actions: {
      getQuote: 'Qiymət al',
      calculatePrice: 'Qiyməti hesabla',
      uploadDocument: 'Sənəd yüklə',
      whatsapp: 'WhatsApp-da yazın',
      learnMore: 'Ətraflı öyrənin',
      viewAll: 'Hamısına baxın',
      showMore: 'Daha çox göstər',
      showLess: 'Daha az göstər',
      send: 'Göndər',
      apply: 'Müraciət et',
      order: 'Sifariş ver',
      contactUs: 'Bizimlə əlaqə',
      openMenu: 'Menyunu aç',
      closeMenu: 'Menyunu bağla',
      selectLanguage: 'Dil seçin',
      skipToContent: 'Məzmuna keç',
      login: 'Daxil ol',
      logout: 'Çıxış',
      account: 'Hesabım',
    },
    states: {
      loading: 'Yüklənir…',
      error: 'Xəta baş verdi. Zəhmət olmasa yenidən cəhd edin.',
      required: 'Bu xana mütləq doldurulmalıdır.',
      demoNotice: 'Demo: forma məlumatları hələ serverə göndərilmir.',
      unverified: 'Təsdiqlənəcək',
    },
    topbar: {
      phoneLabel: 'Telefon',
      emailLabel: 'E-poçt',
      hoursLabel: 'İş saatları',
      afterHours: 'İş saatlarından sonra təcili tərcümə dəstəyi mövcuddur.',
      workingHours: 'İş günləri 09:00 - 18:00 | İş saatlarından sonra xidmət mövcuddur',
    },
  },

  home: {
    seo: {
      title: 'TercümExpert — Peşəkar Tərcümə Xidmətləri',
      description:
        'Andlı tərcümə, notariat təsdiqi və korporativ tərcümə həlləri. Sənədinizi yükləyin, dərhal ilkin qiymət alın və peşəkar çatdırılmadan yararlanın.',
    },
    hero: {
      title: 'Peşəkar Sahədə Etibarlı Tərəfdaşınız',
      titleAccent: 'Tərcümə Xidmətləri',
      subtitle: 'Sənədinizi yükləyin, qiyməti görün, peşəkar çatdırılma alın.',
      support: 'Andlı tərcümə • Notariat təsdiqi • Korporativ həllər',
    },
    trust: {
      title: 'Nə üçün bizə etibar edirlər?',
      items: [
        { key: 'languages', label: '50+ Dil' },
        { key: 'delivery', label: '24 Saatlıq Çatdırılma' },
        { key: 'notary', label: 'Notariat Təsdiqi' },
        { key: 'quality', label: 'Keyfiyyət Zəmanəti' },
      ],
    },
    stats: {
      title: 'Rəqəmlərlə TercümExpert',
      note: 'Aşağıdakı rəqəmlər təsdiqlənənə qədər qəti iddia kimi təqdim edilmir.',
      labels: {
        satisfaction: 'Müştəri Məmnuniyyəti',
        completed: 'Tamamlanmış İşlər',
        languages: 'Dil Dəstəyi',
        corporate: 'Korporativ Müştərilər',
      },
    },
    howItWorks: {
      title: 'Necə işləyir?',
      subtitle: 'Beş addımda peşəkar tərcümə.',
      steps: [
        { key: 'upload', title: 'Yükləyin', desc: 'Sənədinizi təhlükəsiz şəkildə yükləyin.' },
        { key: 'select', title: 'Seçin', desc: 'Dili və xidmət növünü seçin.' },
        { key: 'confirm', title: 'Təsdiqləyin', desc: 'Sifarişinizi təsdiqləyin.' },
        { key: 'track', title: 'İzləyin', desc: 'Prosesi real vaxtda izləyin.' },
        { key: 'receive', title: 'Qəbul edin', desc: 'Peşəkar çatdırılmanızı alın.' },
      ],
    },
    services: {
      title: 'Xidmətlərimiz',
      subtitle: 'Hər sənəd növü üçün ekspert tərcümə.',
    },
    why: {
      title: 'Nə üçün TercümExpert?',
      subtitle: 'Bizi rəqiblərimizdən fərqləndirən xüsusiyyətlər',
      features: [
        { key: 'autoQuote', title: 'Avtomatik qiymət hesablama', desc: 'Saniyələr içində ilkin qiymət.' },
        { key: 'whatsapp', title: 'Sürətli WhatsApp qiyməti', desc: 'Bir toxunuşla əlaqə.' },
        { key: 'terminology', title: 'Terminologiya idarəetməsi', desc: 'Ardıcıl, korporativ dil.' },
        { key: 'revision', title: 'Redaktə hüququ', desc: 'Məmnuniyyətə yönəlmiş proses.' },
        { key: 'languages', title: '50+ dil dəstəyi', desc: 'Geniş dil cütü əhatəsi.' },
        { key: 'terms', title: 'Korporativ vaxt sistemi', desc: 'Şirkətlər üçün çevik ödəniş.' },
      ],
    },
    corporateCta: {
      title: 'Korporativ Həllər',
      desc: 'Şirkətinizə uyğunlaşdırılmış terminologiya idarəetməsi, vaxt seçimləri və fərdi hesab meneceri ilə peşəkar dil xidmətləri.',
      action: 'Korporativ Qiymət İstəyin',
    },
    partnershipTeaser: {
      title: 'Tərəfdaşlıq Proqramı',
      subtitle: 'Bizə yönləndirdiyiniz hər müştəriyə görə 20% komissiya qazanın.',
      items: [
        { key: 'commission', title: 'Şəffaf Komissiya', desc: 'Hər yönləndirməyə görə 20% komissiya (razılaşmaya əsasən). Real vaxt izləmə paneli ilə şəffaf qazanc.' },
        { key: 'qr', title: 'QR Kod Sistemi', desc: 'Vizit kartı inteqrasiyası ilə asan müştəri izləmə. Veb və WhatsApp QR kodları.' },
      ],
      cta: 'Tərəfdaş kimi müraciət edin',
    },
    testimonials: {
      title: 'Müştəri Rəyləri',
      subtitle: 'Real müştəri rəyləri istifadəyə verilməzdən əvvəl burada əlavə olunacaq.',
      placeholderNote: 'Yer tutucu — real rəylər inteqrasiya olunacaq.',
      items: [
        { key: 't1', role: 'Hüquq Bürosu' },
        { key: 't2', role: 'Səhiyyə Təşkilatı' },
        { key: 't3', role: 'Korporativ Müştəri' },
        { key: 't4', role: 'Fərdi Müştəri' },
      ],
    },
    blogTeaser: {
      title: 'Bloq',
      subtitle: 'Tərcümə dünyasından aktual məzmun',
      viewAll: 'Bütün Bloq Yazılarına Baxın',
    },
    finalCta: {
      title: 'İndi Başlayın',
      desc: 'Sənədlərinizi yükləyin, dərhal qiymət alın və peşəkar tərcümə xidmətlərindən yararlanın.',
      primary: 'Qiymət al',
      secondary: 'Bizimlə əlaqə',
    },
  },

  services: {
    seo: {
      title: 'Tərcümə Xidmətləri',
      description:
        'Andlı, notariat təsdiqli, hüquqi, texniki, tibbi və akademik tərcümə, həmçinin veb/mobil lokallaşdırma. Sənəd növləri, proses, çatdırılma və dil cütləri.',
    },
    hero: {
      title: 'Tərcümə Xidmətləri',
      subtitle: 'Hər ixtisas sahəsi üçün düzgün terminologiya ilə tərcümə.',
    },
    process: {
      title: 'Proses necə işləyir?',
      steps: [
        { title: 'Sənəd baxışı', desc: 'Sənədin növü və məqsədi qiymətləndirilir.' },
        { title: 'Ekspert təyinatı', desc: 'Sahə üzrə ixtisaslaşmış tərcüməçi təyin edilir.' },
        { title: 'Tərcümə və redaktə', desc: 'Tərcümə və müstəqil yekun baxış.' },
        { title: 'Təsdiq və çatdırılma', desc: 'Lazım olduqda notariat/apostil, sonra çatdırılma.' },
      ],
    },
    delivery: {
      title: 'Çatdırılma seçimləri',
      items: ['Rəqəmsal çatdırılma (PDF/DOCX)', 'Fiziki sənəd çatdırılması', 'Təcili çatdırılma'],
    },
    notaryApostille: {
      title: 'Notariat və apostil əlaqəsi',
      desc: 'Tələb olunduqda andlı tərcümə notariat təsdiqi və apostil prosesi vasitəsilə rəsmi qurumlar üçün etibarlı edilir. Dəqiq tələb sənədin təqdim olunacağı quruma görə dəyişir.',
    },
    fullService: {
      title: 'Açar Təslim, Qapınıza Qədər Çatdırılır',
      note: 'Sənədlərinizi bizə göndərin, bütün prosesi — tərcümə, notariat təsdiqi və apostil daxil — biz idarə edək. Hazır sənədləriniz kuryer vasitəsilə qapınıza çatdırılır. Siz işinizə fokuslanın, qalanını bizə buraxın.',
    },
    cta: {
      title: 'Hansı xidmətə ehtiyacınız olduğundan əmin deyilsiniz?',
      desc: 'Sənədinizi yükləyin, sizə ən uyğun xidməti və qiyməti göstərək.',
    },
    documentTypesTitle: 'Uyğun sənəd növləri',
  },

  serviceItems: {
    sworn: {
      name: 'Andlı Tərcümə',
      short: 'Andlı tərcüməçinin imzası və möhürü ilə rəsmi etibarlı tərcümə.',
      benefits: ['Rəsmi qurumlarda etibarlı', 'Andlı tərcüməçi təsdiqi', 'Sürətli proses'],
    },
    notarized: {
      name: 'Notariat Təsdiqli Tərcümə',
      short: 'Andlı tərcümənin notariat təsdiqi.',
      benefits: ['Notariat təsdiqi', 'Rəsmi müraciətlər üçün uyğun', 'Prosesi biz idarə edirik'],
    },
    apostille: {
      name: 'Apostil Prosesi Dəstəyi',
      short: 'Xaricdə etibarlılıq üçün apostil prosesində bələdçilik.',
      benefits: ['Beynəlxalq etibarlılıq', 'Proses məsləhəti', 'Qurum bələdçiliyi'],
    },
    legal: {
      name: 'Hüquqi Tərcümə',
      short: 'Müqavilələr, məhkəmə və rəsmi sənədlər üçün terminologiyaya hakim tərcümə.',
      benefits: ['Hüquqi terminologiya', 'Məxfilik zəmanəti', 'Ekspert tərcüməçi'],
    },
    technical: {
      name: 'Texniki Tərcümə',
      short: 'Təlimatlar, spesifikasiyalar və texniki sənədlər üçün ardıcıl tərcümə.',
      benefits: ['Terminologiya idarəetməsi', 'Format qorunur', 'Sənaye təcrübəsi'],
    },
    medical: {
      name: 'Tibbi Tərcümə',
      short: 'Hesabatlar, təlimatlar və tibbi sənədlər üçün dəqiq tərcümə.',
      benefits: ['Tibbi terminologiya', 'Dəqiqliyə yönəlmiş', 'Məxfilik'],
    },
    academic: {
      name: 'Akademik Tərcümə',
      short: 'Dissertasiyalar, məqalələr və diplom tərcümələri üçün akademik dil.',
      benefits: ['Akademik üslub', 'Mənbə ardıcıllığı', 'Vaxtında çatdırılma'],
    },
    localization: {
      name: 'Veb və Mobil Lokallaşdırma',
      short: 'Vebsaytların və tətbiqlərin mədəni cəhətdən uyğun lokallaşdırılması.',
      benefits: ['Mədəni uyğunlaşdırma', 'Texniki inteqrasiya', 'SEO uyğunluğu'],
    },
  },

  corporate: {
    statsLabels: {
      corporate: 'Korporativ müştərilər',
      discount: 'Toplu sifariş endirimi',
      term: 'Ödəniş vaxtı',
    },
    seo: {
      title: 'Korporativ Həllər',
      description:
        'Terminologiya idarəetməsi, vaxt seçimləri, toplu sifarişlər və fərdi hesab meneceri ilə şirkətlər üçün peşəkar dil xidmətləri.',
    },
    hero: {
      title: 'Korporativ Həllər',
      subtitle:
        'Şirkətinizə uyğunlaşdırılmış terminologiya idarəetməsi, vaxt seçimləri və fərdi hesab meneceri ilə peşəkar dil xidmətləri.',
      primaryCta: 'Korporativ Qiymət İstəyin',
      secondaryCta: 'E-poçt Göndər',
    },
    features: {
      title: 'Korporativ Xüsusiyyətlər',
      subtitle: 'Biznesinizə uyğunlaşdırılmış həllər',
      items: [
        {
          key: 'custom',
          icon: 'Target',
          title: 'Fərdiləşdirilmiş Xidmət',
          points: ['Sabit terminologiya', 'Brendin səs tonunun qorunması', 'Fərdi hesab meneceri', 'Üslub bələdçisinin yaradılması'],
        },
        {
          key: 'volume',
          icon: 'BarChart3',
          title: 'Toplu Emal və Vaxt Seçimləri',
          points: ['Aylıq tərcümə planları', 'Toplu sifariş endirimləri', '30 günə qədər vaxt', 'Fakturalaşdırma sistemi'],
        },
        {
          key: 'security',
          icon: 'Lock',
          title: 'Məxfilik və Təhlükəsizlik',
          points: ['NDA protokolu', 'Şifrələnmiş fayl ötürülməsi', 'KVKK-uyğun proseslər'],
        },
      ],
    },
    whyPackage: {
      title: 'Nə üçün Korporativ Paket?',
      items: [
        {
          key: 'terminology',
          icon: 'Building2',
          title: 'Sabit Terminologiya İdarəetməsi',
          desc: 'Şirkətinizə xas termin bankı qururuq. Brend diliniz bütün tərcümələrdə qorunur və ardıcıllığı təmin edirik. Hər layihədə eyni terminlərin işlədilməsinə diqqət yetiririk.',
        },
        {
          key: 'manager',
          icon: 'Users',
          title: 'Fərdi Hesab Meneceri',
          desc: 'Fərdi hesab meneceriniz bütün proseslərinizi izləyir. Əlçatan dəstək xətti ilə təcili vəziyyətlərdə yanınızdayıq.',
        },
        {
          key: 'security',
          icon: 'ShieldCheck',
          title: 'Məxfilik və Təhlükəsizlik',
          desc: 'NDA protokolu altında işləyirik. Güclü təhlükəsizlik infrastrukturu, şifrələnmiş fayl ötürülməsi və KVKK-uyğun proseslərlə məlumatlarınız təhlükəsizdir.',
        },
      ],
    },
    payment: {
      title: 'Ödəniş Seçimləri',
      subtitle: 'Biznesinizə uyğun çevik ödəniş planları',
      recommendedLabel: 'TÖVSİYƏ OLUNUR',
      options: [
        {
          key: 'standard',
          label: 'Dərhal Ödəniş',
          heading: 'Standart',
          desc: 'Hər sifarişdən sonra kredit kartı və ya bank köçürməsi ilə ödəniş',
          points: ['Kredit kartı ilə hissə-hissə', 'Dərhal çatdırılma'],
          recommended: false,
        },
        {
          key: 'term',
          label: 'Aylıq Vaxt',
          heading: '15-30 Gün',
          desc: 'Aylıq birləşdirilmiş fakturalaşdırma və vaxt seçimi',
          points: ['30 günlük vaxt', 'Toplu endirim', 'Aylıq hesabat'],
          recommended: true,
        },
      ],
    },
    form: {
      title: 'Korporativ Paket Müraciəti',
      desc: 'Formanı doldurun, ekspert komandamız sizinlə əlaqə saxlayacaq',
      fields: {
        company: 'Şirkət Adı',
        contactName: 'Əlaqədar Şəxsin Adı və Soyadı',
        email: 'E-poçt',
        phone: 'Telefon',
        need: 'Tərcümə ehtiyaclarınız haqqında bizə məlumat verin',
        consent: 'KVKK Məlumatlandırma Bəyanatını oxudum və qəbul edirəm.',
      },
      submit: 'Müraciəti Göndər',
      success: 'Müraciətiniz qəbul olundu. Ən qısa zamanda sizinlə əlaqə saxlayacağıq.',
      note: '1 iş günü ərzində sizinlə əlaqə saxlayacağıq.',
    },
  },

  partnership: {
    seo: {
      title: 'Tərəfdaşlıq Proqramı',
      description:
        'Yönləndirdiyiniz hər müştəriyə görə komissiya qazanın. Şəffaf hesabatlıq, QR kod yönləndirmələri və peşəkar dəstək.',
    },
    hero: {
      title: 'Tərəfdaşlıq Proqramı',
      value: 'Bizə yönləndirdiyiniz hər müştəriyə görə 20% komissiya qazanın.',
      subtitle: 'Şəffaf sistem, etibarlı ödənişlər, uzunmüddətli əməkdaşlıq.',
      cta: 'İndi Müraciət Edin',
    },
    advantages: {
      title: 'Tərəfdaş Üstünlükləri',
      subtitle: 'Nə üçün TercümExpert tərəfdaşı olmalısınız?',
      items: [
        { key: 'commission', icon: 'Wallet', title: '20% Komissiya Zəmanəti', desc: 'Yönləndirdiyiniz hər müştəri üçün şəffaf komissiya sistemi.' },
        { key: 'qr', icon: 'QrCode', title: 'QR Kod Yönləndirmə', desc: 'Vizit kartı inteqrasiyası ilə asan müştəri izləmə.' },
        { key: 'reporting', icon: 'BarChart3', title: 'Şəffaf Hesabatlıq', desc: 'Real vaxt komissiya və müştəri izləmə paneli.' },
        { key: 'support', icon: 'Users', title: 'Peşəkar Dəstək', desc: 'Fərdi tərəfdaş dəstək xətti və hesab meneceri.' },
      ],
    },
    howItWorks: {
      title: 'Necə İşləyir?',
      steps: [
        { title: 'Müraciət Edin', desc: 'Onlayn müraciət formasını doldurun. Şirkət məlumatlarınızı və əlaqə məlumatlarınızı paylaşın. Müraciətiniz 1 iş günü ərzində nəzərdən keçirilir.' },
        { title: 'Tərəfdaş Olun', desc: 'Müraciətiniz təsdiqləndikdən sonra fərdi tərəfdaş panelinizə giriş əldə edirsiniz. QR kodlarınız və yönləndirmə linkləriniz hazırdır.' },
        { title: 'Müştəri Yönləndirin', desc: 'Müştərilərinizi QR kod, xüsusi link və ya vizit kartı vasitəsilə bizə yönləndirin. Hər yönləndirmə sistemə avtomatik qeyd olunur.' },
        { title: 'Komissiya Qazanın', desc: 'Yönləndirdiyiniz müştəri hər dəfə sifariş verdikdə 20% komissiya qazanırsınız. Hər 15 gündən bir avtomatik ödənişlər alırsınız.' },
      ],
    },
    sectors: {
      title: 'Hədəf Sektorlar',
      subtitle: 'Hansı sektorlar üçün idealdır?',
      items: [
        { key: 'law', icon: 'Scale', title: 'Hüquq Büroları', desc: 'İş sənədləri, müqavilələr və hüquqi sənədlərin andlı tərcüməsinə ehtiyac.' },
        { key: 'visa', icon: 'Plane', title: 'Viza Məsləhətçiliyi', desc: 'Pasport, diplom və vətəndaşlıq sənədləri kimi andlı tərcümə tələb edən sənədlər.' },
        { key: 'education', icon: 'GraduationCap', title: 'Təhsil Məsləhətçiliyi', desc: 'Tələbə sənədlərinin andlı tərcüməsi və apostil prosesləri.' },
        { key: 'health', icon: 'HeartPulse', title: 'Sağlamlıq Turizmi', desc: 'Tibbi hesabatların, xəstə sənədlərinin və sağlamlıq sənədlərinin tərcüməsi.' },
        { key: 'patent', icon: 'Building2', title: 'Patent/Ticarət Nişanı Büroları', desc: 'Patent, ticarət nişanı qeydiyyatı və hüquqi sənədlərin texniki tərcüməsi.' },
        { key: 'realestate', icon: 'Home', title: 'Daşınmaz Əmlak Büroları', desc: 'Xarici investorlar üçün çıxarış, müqavilə və rəsmi sənəd tərcüməsi.' },
        { key: 'hr', icon: 'Briefcase', title: 'İnsan Resursları Məsləhətçiliyi', desc: 'Xaricdə işədüzəltmə üçün CV, diplom və zəmanət məktubu tərcüməsi.' },
        { key: 'software', icon: 'Code', title: 'Proqram Təminatı Şirkətləri', desc: 'Veb və mobil tətbiq lokallaşdırması, texniki sənəd tərcüməsi.' },
      ],
    },
    commission: {
      title: 'Komissiya Strukturu',
      stats: {
        commissionLabel: 'Standart Komissiya',
        commissionSub: 'Hər sifarişə görə',
        periodUnit: 'Gün',
        periodLabel: 'Ödəniş dövrü',
        feeLabel: 'Başlanğıc Haqqı',
        feeSub: 'Tamamilə pulsuz',
      },
      exampleTitle: 'Nümunə Qazanc Hesablaması',
      exampleOrderLabel: 'Yönləndirdiyiniz müştəridən sifariş',
      exampleRateLabel: 'Komissiya dərəcəsi',
      exampleEarningLabel: 'Qazancınız',
      note: 'Komissiya dərəcələri və şərtləri tərəfdaş razılaşmasına tabedir.',
    },
    form: {
      title: 'Tərəfdaş Müraciət Forması',
      subtitle: 'Formanı doldurun, 1 iş günü ərzində sizinlə əlaqə saxlayacağıq.',
      fields: {
        company: 'Şirkət/Təşkilat Adı',
        sector: 'Sektor',
        contactName: 'Əlaqədar Şəxsin Adı və Soyadı',
        titleRole: 'Vəzifə',
        email: 'E-poçt',
        phone: 'Telefon',
        potential: 'Təxmini aylıq yönləndirmə potensialınız',
        note: 'Əlavə etmək istədiyiniz qeydlər',
        agreement: 'Tərəfdaş razılaşmasının şərtlərini oxudum və qəbul edirəm.',
      },
      sectorPlaceholder: 'Seçin',
      sectorOptions: ['Hüquq Bürosu', 'Viza Məsləhətçiliyi', 'Təhsil Məsləhətçiliyi', 'Sağlamlıq Turizmi', 'Patent/Ticarət Nişanı Bürosu', 'Daşınmaz Əmlak', 'İnsan Resursları Məsləhətçiliyi', 'Proqram Təminatı', 'Digər'],
      potentialOptions: ['1-5 müştəri', '5-10 müştəri', '10-20 müştəri', '20+ müştəri'],
      submit: 'Müraciəti Göndər',
      success: 'Müraciətiniz qəbul olundu. Sizinlə əlaqə saxlayacağıq.',
      note: 'Müraciətiniz 1 iş günü ərzində nəzərdən keçiriləcək.',
    },
  },

  quote: {
    seo: {
      title: 'Dərhal Qiymət Hesablama',
      description: 'Sənədinizi yükləyin və ya təfərrüatları daxil edin, dərhal ilkin qiymətinizi alın.',
    },
    hero: {
      title: 'Dərhal Qiymət Hesablama',
      subtitle: 'Sənədinizi yükləyin və ya təfərrüatları daxil edin, dərhal ilkin qiymət alın.',
    },
    upload: {
      heading: 'Sənədlərinizi Yükləyin',
      privacy: 'Məlumatlarınız məxfi saxlanılır',
      tabFile: 'Fayl Yüklə',
      tabText: 'Mətn Daxil Et',
      chooseFile: 'Sənədlərinizi Seçin',
      formats: '.docx, .xlsx, .pdf, .pptx, .jpg, .png və 50+ format qəbul edilir · Fayl başına maksimum 100MB',
      dropHint: 'Bir və ya bir neçə faylı bu sahəyə sürüşdürüb buraxa bilərsiniz.',
      textPlaceholder: 'Mətninizi buraya yapışdırın və ya yazın…',
      totalWords: 'Ümumi söz sayı',
      extracting: 'Sözlər sayılır…',
      wordsUnit: 'söz',
      remove: 'Sil',
      unsupported:
        'Bu fayl növü üçün avtomatik söz sayımı mümkün olmadı. Zəhmət olmasa mətni "Mətn Daxil Et" ilə yapışdırın; qiymət verilərkən say komandamız tərəfindən yoxlanılacaq.',
      empty:
        'Faylda seçilə bilən mətn tapılmadı (skan edilmiş/şəkil ola bilər). Zəhmət olmasa "Mətn Daxil Et"dən istifadə edin, əks halda say qiymətləndirmə zamanı yoxlanılacaq.',
      error: 'Fayl oxuna bilmədi. Zəhmət olmasa yenidən cəhd edin və ya "Mətn Daxil Et"dən istifadə edin.',
      tooLarge: 'Fayl 100MB-dan böyük ola bilməz.',
      needInput: 'Qiymət üçün zəhmət olmasa fayl yükləyin və ya mətn daxil edin.',
    },
    fields: {
      upload: 'Sənəd Yüklə (istəyə bağlı)',
      uploadHint: 'PDF, DOC, DOCX və ya TXT — maksimum 10 MB',
      sourceLang: 'Mənbə Dili',
      targetLang: 'Hədəf Dili',
      serviceType: 'Xidmət Növü',
      documentType: 'Sənəd Növü',
      wordCount: 'Təxmini Söz Sayı',
      wordCountHint: 'Sürgücdən istifadə edin və ya rəqəmi əl ilə daxil edin.',
      options: 'Əlavə seçimlər',
      calculate: 'Qiyməti hesabla',
    },
    options: {
      urgent: 'Təcili Çatdırılma',
      notarization: 'Notariat Təsdiqi',
      physicalDelivery: 'Fiziki Çatdırılma',
    },
    languages: {
      tr: 'Türk dili',
      en: 'İngilis dili',
      de: 'Alman dili',
      fr: 'Fransız dili',
      es: 'İspan dili',
      it: 'İtalyan dili',
      ru: 'Rus dili',
      ar: 'Ərəb dili',
      nl: 'Holland dili',
      az: 'Azərbaycan dili',
      pl: 'Polyak dili',
      bg: 'Bolqar dili',
      pt: 'Portuqal dili',
      da: 'Danimarka dili',
    },
    documentTypes: {
      diploma: 'Diplom',
      passport: 'Pasport',
      'civil-registry': 'Vətəndaşlıq Vəziyyəti Aktı Çıxarışı',
      contract: 'Müqavilə',
      'medical-report': 'Tibbi Hesabat',
      'technical-doc': 'Texniki Sənəd',
      'court-doc': 'Məhkəmə Sənədi',
      other: 'Digər',
    },
    result: {
      title: 'İlkin Qiymət',
      basePrice: 'Baza xidmət haqqı',
      wordPrice: 'Söz haqqı',
      addons: 'Əlavə xidmətlər',
      total: 'Cəmi',
      vat: 'ƏDV',
      delivery: 'Təxmini çatdırılma müddəti',
      deliveryUnit: 'iş günü',
      disclaimer: 'Bu ilkin qiymətdir; yekun qiymət sənəd baxışından sonra təsdiqlənir.',
      order: 'Sifariş ver',
      whatsapp: 'WhatsApp vasitəsilə əlaqə',
      estimatedWords: 'Təxmini sözlər (avtomatik — demo)',
    },
    orderConfirm: {
      title: 'Sifarişiniz qəbul olundu',
      number: 'Sifariş No',
      desc: 'Sorğunuz və sənədləriniz saxlanıldı. Ekspert komandamız sənədi nəzərdən keçirəcək və ən qısa zamanda sizinlə əlaqə saxlayacaq.',
      viewOrders: 'Sifarişlərim',
      submitting: 'Sifariş yaradılır…',
      error: 'Sifarişiniz yaradılarkən problem yarandı. Zəhmət olmasa yenidən cəhd edin.',
    },
    gate: {
      title: 'Qiymətiniz hazırdır',
      subtitle: 'Qiyməti görmək və sifariş vermək üçün daxil olun və ya məlumatlarınızı təsdiqləyin.',
      loginCta: 'Daxil ol / Qeydiyyat',
      or: 'və ya sürətlə davam edin',
      firstName: 'Ad',
      lastName: 'Soyad',
      email: 'E-poçt',
      sendCode: 'Təsdiq Kodu Göndər',
      codeLabel: 'Təsdiq Kodu',
      codeSentA: 'ünvanına təsdiq kodu göndərildi.',
      verify: 'Təsdiqlə və Qiyməti Gör',
      resend: 'Kodu yenidən göndər',
      resent: 'Yeni kod göndərildi.',
      back: 'Məlumatları dəyiş',
      errNames: 'Ad və soyad tələb olunur.',
      errEmail: 'Etibarlı e-poçt daxil edin.',
      errCode: 'Zəhmət olmasa kodu tam daxil edin.',
      note: 'E-poçtunuz yalnız qiymət və sifariş üçün istifadə olunur.',
    },
    note: {
      label: 'Sifarişiniz haqqında qeyd (istəyə bağlı)',
      placeholder: 'Çatdırılma, terminologiya və ya xüsusi istəklərinizi buraya yaza bilərsiniz.',
    },
  },

  order: {
    seo: {
      title: 'Sifariş İzləmə',
      description: 'Sifarişinizin statusunu izləyin.',
    },
    numberLabel: 'Sifariş No',
    placedOn: 'Sifariş tarixi',
    estimatedLabel: 'Təxmini tərcümə çatdırılması',
    cargoEstimatedLabel: 'Təxmini göndərmə tarixi',
    timelineTitle: 'Sifariş statusu',
    steps: {
      received: 'Sifarişiniz qəbul olundu',
      in_progress: 'İcra olunur',
      translated: 'Tərcümə tamamlandı',
      shipped: 'Göndərildi',
      delivered: 'Çatdırıldı',
      cancelled: 'Sifariş ləğv edildi',
    },
    stepDesc: {
      received: 'Sorğunuz və sənədləriniz sistemimizə çatdı. Ekspert komandamız onu nəzərdən keçirib tezliklə başlayacaq.',
      in_progress: 'Ekspert tərcüməçimiz tərcümənizə başladı.',
      translated: 'Tərcüməniz tamamlandı və yekun yoxlamalar aparıldı.',
      shipped: 'Sənədiniz kuryerə təhvil verildi; onu aşağıdakı düymə ilə izləyə bilərsiniz.',
      delivered: 'Sənədiniz sizə e-poçt vasitəsilə göndərildi.',
      cancelled: 'Bu sifariş ləğv edildi. Suallarınız üçün zəhmət olmasa bizimlə əlaqə saxlayın.',
    },
    cargoReady: 'Sənədiniz göndərildi. Onu bir toxunuşla izləyin:',
    cargoPending: 'İzləmə kodu sənədiniz göndərildikdən sonra burada görünəcək.',
    trackCargo: 'Göndərişimi İzlə',
    digitalPending: 'Tərcüməniz tamamlandıqdan sonra fayllarınız sizə e-poçt vasitəsilə göndəriləcək.',
    digitalDelivered: 'Tərcüməniz sizə e-poçt vasitəsilə göndərildi. Poçt qutunuzu (və spam qovluğunu) yoxlayın.',
    detailsTitle: 'Sifariş təfərrüatları',
    fields: {
      service: 'Xidmət',
      langs: 'Dillər',
      documentType: 'Sənəd növü',
      words: 'Sözlər',
      delivery: 'Təxmini müddət',
      total: 'Məbləğ',
      note: 'Qeydiniz',
    },
    myOrders: 'Sifarişlərim',
    backHome: 'Ana səhifəyə qayıt',
    whatsapp: 'WhatsApp vasitəsilə əlaqə',
    loading: 'Sifariş yüklənir…',
    loginRequired: {
      title: 'Sifarişinizi görmək üçün daxil olun',
      desc: 'Sifariş təfərrüatlarınıza yalnız hesabınızla daxil olduqdan sonra çıxış əldə edə bilərsiniz.',
      login: 'Daxil ol',
    },
    notFound: {
      title: 'Sifariş tapılmadı',
      desc: 'Bu sifariş nömrəsi sizə aid deyil və ya mövcud deyil. Zəhmət olmasa linki yoxlayın.',
      home: 'Ana səhifəyə qayıt',
    },
  },

  faq: {
    seo: {
      title: 'Tez-tez Verilən Suallar',
      description: 'Andlı tərcümə, çatdırılma müddəti, qiymətqoyma, notariat təsdiqi və korporativ vaxt seçimləri haqqında tez-tez verilən suallar.',
    },
    hero: { title: 'Tez-tez Verilən Suallar', subtitle: 'Axtardığınız cavab buradadır.' },
    categoriesTitle: 'Kateqoriyalar',
    searchPlaceholder: 'Sual və ya açar sözlər axtarın…',
    empty: 'Axtarışınıza uyğun sual tapılmadı. Fərqli söz sınayın və ya bizimlə əlaqə saxlayın.',
    categories: FAQ_CATEGORIES_AZ,
    items: FAQ_ITEMS_AZ,
    notFound: {
      title: 'Sualınızın cavabını tapmadınız?',
      contact: 'Bizimlə əlaqə',
      whatsapp: 'WhatsApp Dəstəyi',
    },
  },

  contact: {
    seo: {
      title: 'Əlaqə',
      description: 'TercümExpert ilə əlaqə saxlayın: telefon, e-poçt, WhatsApp və əlaqə forması.',
    },
    hero: { title: 'Əlaqə', subtitle: 'Sizə necə kömək edə bilərik?' },
    infoTitle: 'Əlaqə məlumatları',
    labels: {
      phone: 'Telefon',
      email: 'E-poçt',
      whatsapp: 'WhatsApp',
      address: 'Ünvan',
      hours: 'İş saatları',
    },
    form: {
      title: 'Bizimlə əlaqə',
      fields: {
        name: 'Ad və Soyad',
        email: 'E-poçt',
        phone: 'Telefon',
        subject: 'Mövzu',
        message: 'Mesaj',
        consent: 'KVKK Məlumatlandırma Bəyanatını oxudum və qəbul edirəm.',
      },
      submit: 'Mesaj Göndər',
      success: 'Mesajınız qəbul olundu. Tezliklə sizinlə əlaqə saxlayacağıq.',
    },
    map: {
      title: 'Yerləşdiyimiz Yer',
      subtitle: 'Bizi xəritədə tapın',
      placeholder: 'Xəritə sahəsi',
      note: 'Yerləşmə xəritəsi tezliklə burada göstəriləcək.',
    },
  },

  auth: {
    seo: {
      title: 'Daxil ol / Qeydiyyat',
      description: 'TercümExpert hesabınıza daxil olun və ya yeni hesab yaradın.',
    },
    tabs: { login: 'Daxil ol', register: 'Qeydiyyat' },
    google: 'Google ilə davam et',
    or: 'və ya',
    fields: {
      firstName: 'Ad',
      lastName: 'Soyad',
      email: 'E-poçt',
      password: 'Şifrə',
      code: 'Təsdiq Kodu',
    },
    login: {
      title: 'Hesabınıza daxil olun',
      submit: 'Daxil ol',
      noAccount: 'Hesabınız yoxdur?',
      switchToRegister: 'Qeydiyyatdan keçin',
    },
    register: {
      title: 'Yeni hesab yaradın',
      submit: 'Qeydiyyat',
      haveAccount: 'Artıq hesabınız var?',
      switchToLogin: 'Daxil olun',
      consent: 'Hesab yaratmaqla KVKK Məlumatlandırma Bəyanatını və Məxfilik Siyasətini qəbul edirəm.',
    },
    verify: {
      title: 'E-poçtunuzu təsdiqləyin',
      desc: '— bu ünvana göndərdiyimiz 6 rəqəmli kodu daxil edin.',
      submit: 'Təsdiqlə və Davam et',
      spam: 'Kod bir neçə dəqiqə gecikə bilər; həmçinin spam/junk qovluğunuzu yoxlayın.',
      resend: 'Kodu yenidən göndər',
      resent: 'Yeni kod göndərildi.',
      back: 'Geri qayıt',
    },
    signedIn: {
      title: 'Hesabım',
      greeting: 'Xoş gəldiniz',
      logout: 'Çıxış',
    },
    orders: {
      title: 'Sifarişlərim',
      empty: 'Hələ sifarişiniz yoxdur. İlk sifarişinizi Qiyməti hesabla bölməsindən yarada bilərsiniz.',
      loading: 'Sifarişlər yüklənir…',
      error: 'Sifarişlər yüklənə bilmədi. Zəhmət olmasa səhifəni yeniləyin.',
      status: {
        received: 'Qəbul olundu',
        in_progress: 'İcra olunur',
        translated: 'Tərcümə tamamlandı',
        shipped: 'Göndərildi',
        delivered: 'Çatdırıldı',
        cancelled: 'Ləğv edildi',
      },
      track: 'İzlə',
    },
    errors: {
      nameRequired: 'Ad və soyad tələb olunur.',
      emailInvalid: 'Etibarlı e-poçt daxil edin.',
      passwordShort: 'Şifrə ən azı 6 simvol olmalıdır.',
      codeInvalid: 'Zəhmət olmasa 6 rəqəmli kodu daxil edin.',
      consentRequired: 'Davam etmək üçün təsdiq tələb olunur.',
    },
  },

  blog: {
    seo: { title: 'Bloq', description: 'Tərcümə, notariat, apostil və lokallaşdırma haqqında bələdçi məzmun.' },
    hero: { title: 'Bloq', subtitle: 'Tərcümə dünyasından bələdçilər.' },
    searchPlaceholder: 'Yazıları axtarın…',
    readingTime: 'dəq oxuma',
    relatedTitle: 'Əlaqəli yazılar',
    allCategories: 'Hamısı',
    empty: 'Bu meyara uyğun yazı tapılmadı.',
  },

  legal: {
    lastUpdatedLabel: 'Son yenilənmə',
    draftNotice:
      'Bu mətn qaralamadır və dərc edilməzdən əvvəl hüquq mütəxəssisi tərəfindən nəzərdən keçirilməlidir. Şirkət məlumatları hələ təsdiqlənməyib.',
    kvkk: {
      seo: { title: 'KVKK Məlumatlandırma Bəyanatı', description: 'Şəxsi məlumatların qorunması haqqında məlumatlandırma bəyanatı.' },
      title: 'KVKK Məlumatlandırma Bəyanatı',
      sections: [
        { heading: 'Məlumatlara Nəzarət Edən', body: 'Məlumatlara nəzarət edən şəxs və əlaqə məlumatları istifadəyə verilməzdən əvvəl əlavə olunacaq.' },
        { heading: 'Emal Olunan Şəxsi Məlumatlar', body: 'Əlaqə və sifariş prosesləri zamanı ad, əlaqə məlumatları və sənəd məlumatları emal oluna bilər.' },
        { heading: 'Emalın Məqsədləri', body: 'Xidmət göstərilməsi, qiymətlər, əlaqə və hüquqi öhdəliklər.' },
        { heading: 'Hüquqi Əsaslar', body: 'Müqavilənin icrası, açıq razılıq və qanuni maraq.' },
        { heading: 'Saxlama Müddətləri', body: 'Məlumatlar müvafiq qanunvericilikdə nəzərdə tutulan müddətlər ərzində saxlanılır.' },
        { heading: 'Ötürülmə', body: 'Yalnız xidmətin tələb etdiyi həcmdə və qanunvericiliyə uyğun ötürülür.' },
        { heading: 'Hüquqlarınız', body: 'KVKK-nın 11-ci maddəsi çərçivəsində hüquqlarınızı istifadə edə bilərsiniz.' },
        { heading: 'Necə Müraciət Etmək Olar', body: 'Sorğularınızı göstərilən əlaqə kanalları vasitəsilə təqdim edə bilərsiniz.' },
      ],
    },
    privacy: {
      seo: { title: 'Məxfilik Siyasəti', description: 'Şəxsi məlumatların və sənədlərin məxfiliyi haqqında siyasət.' },
      title: 'Məxfilik Siyasəti',
      sections: [
        { heading: 'Toplanan Məlumatlar', body: 'Əlaqə məlumatları və yüklənən sənədlər.' },
        { heading: 'İstifadə', body: 'Yalnız xidmət göstərilməsi və əlaqə üçün istifadə olunur.' },
        { heading: 'Sənəd Təhlükəsizliyi', body: 'Sənədlər şifrələnmiş ötürülmə və məxfilik prinsipləri ilə emal olunur.' },
        { heading: 'Kukilər', body: 'Təfərrüatlar Kuki Siyasətindədir.' },
      ],
    },
    distanceSales: {
      seo: { title: 'Məsafədən Satış Müqaviləsi', description: 'Xidmətlərin satışı üçün məsafədən satış müqaviləsi.' },
      title: 'Məsafədən Satış Müqaviləsi',
      sections: [
        { heading: 'Tərəflər', body: 'Satıcı və alıcı məlumatları istifadəyə verilməzdən əvvəl əlavə olunacaq.' },
        { heading: 'Xidmətin Əhatəsi', body: 'Sifariş edilən tərcümə/təsdiq xidmətlərinin əhatəsi.' },
        { heading: 'Geri Çəkilmə Hüququ və İstisnalar', body: 'Şəxsə/sifarişə xüsusi hazırlanan xidmətlərə geri çəkilmə istisnaları tətbiq oluna bilər.' },
        { heading: 'Geri Qaytarma və Ləğv', body: 'Geri qaytarma və ləğv şərtləri burada göstərilir.' },
      ],
    },
    cookies: {
      seo: { title: 'Kuki Siyasəti', description: 'Saytda istifadə olunan kuki kateqoriyaları və seçimlərin idarə edilməsi.' },
      title: 'Kuki Siyasəti',
      sections: [
        { heading: 'Kuki Nədir?', body: 'Kukilər brauzerinizdə saxlanılan kiçik fayllardır.' },
        { heading: 'Kateqoriyalar', body: 'Zəruri, analitik, marketinq və seçim kukiləri.' },
        { heading: 'Seçimlərin İdarə Edilməsi', body: 'Kuki seçimlərinizi istənilən vaxt yeniləyə bilərsiniz.' },
      ],
    },
  },

  footer: {
    tagline: 'Peşəkar tərcümə xidmətlərində etibarlı tərəfdaşınız.',
    columns: {
      quickLinks: 'Sürətli Keçidlər',
      services: 'Xidmətlər',
      contact: 'Əlaqə',
    },
    quickLinks: {
      corporate: 'Korporativ',
      services: 'Xidmətlərimiz',
      quote: 'Qiyməti hesabla',
      blog: 'Bloq',
      faq: 'Tez-tez Verilən Suallar',
      contact: 'Əlaqə',
    },
    serviceLinks: {
      sworn: 'Andlı Tərcümə',
      notarized: 'Notariat Təsdiqli Tərcümə',
      apostille: 'Apostil Prosesi',
      corporate: 'Korporativ Həllər',
      partnership: 'Tərəfdaşlıq Proqramı',
    },
    legal: {
      kvkk: 'KVKK',
      privacy: 'Məxfilik Siyasəti',
      distanceSales: 'Məsafədən Satış Müqaviləsi',
      cookies: 'Kuki Siyasəti',
    },
    socialTitle: 'Bizi izləyin',
    whatsapp: 'WhatsApp Dəstəyi',
    rights: 'Bütün hüquqlar qorunur.',
  },

  cookie: {
    title: 'Kuki seçimləri',
    desc: 'Təcrübənizi yaxşılaşdırmaq üçün kukilərdən istifadə edirik. Zəruri kukilərdən başqaları yalnız razılığınızla işləyir.',
    accept: 'Qəbul et',
    reject: 'Rədd et',
    manage: 'Seçimləri İdarə Et',
    save: 'Seçimləri Saxla',
    categories: {
      necessary: { label: 'Zəruri', desc: 'Saytın işləməsi üçün tələb olunur; söndürülə bilməz.' },
      analytics: { label: 'Analitik', desc: 'İstifadəni anlamağımıza kömək edir.' },
      marketing: { label: 'Marketinq', desc: 'Uyğun məzmun və reklamlar üçün.' },
      preferences: { label: 'Seçimlər', desc: 'Seçimlərinizi yadda saxlayır.' },
    },
  },

  chatbot: {
    title: 'TercümExpert Dəstəyi',
    open: 'Söhbəti aç',
    close: 'Söhbəti bağla',
    minimize: 'Kiçilt',
    clear: 'Söhbəti təmizlə',
    inputPlaceholder: 'Mesajınızı yazın…',
    send: 'Göndər',
    typing: 'Yazır…',
    welcome:
      'Salam və TercümExpert-ə xoş gəldiniz. Tərcümə, qiymətqoyma, notariat təsdiqi, apostil və ya korporativ xidmətlərdə sizə kömək edə bilərəm.',
    quickQuestions: [
      'Qiymət necə hesablanır?',
      'Andlı tərcümə nədir?',
      'Sənəd yükləmək istəyirəm',
      'Korporativ qiymət istəyirəm',
      'Notariat təsdiqi tələb olunurmu?',
      'Məni nümayəndəyə bağlayın',
    ],
    handoff: 'Nümayəndəyə bağlan',
    toWhatsapp: 'WhatsApp-a keçir',
    disclaimer: 'Bu məlumat ümumidir; dəqiq tələbləri müvafiq qurumla təsdiqləyin.',
    sensitiveWarning:
      'Zəhmət olmasa həssas şəxsi məlumatları bu söhbət vasitəsilə paylaşmayın. Sənədlərinizi təhlükəsiz yükləmə sahəsi vasitəsilə göndərə bilərsiniz.',
  },

  notFound: {
    seo: { title: 'Səhifə tapılmadı', description: 'Axtardığınız səhifə tapılmadı.' },
    title: 'Səhifə tapılmadı',
    desc: 'Axtardığınız səhifə köçürülmüş və ya heç vaxt mövcud olmamış ola bilər.',
    home: 'Ana səhifəyə qayıt',
  },
}
