/**
 * Source de données FAQ (français). La logique tarifaire/de paiement pourra
 * évoluer (§13). Règles d'honnêteté : AUCUNE allégation ISO/certification non
 * vérifiée ; aucun bureau physique n'est sous-entendu ; aucune assistance
 * humaine 24h/24 n'est promise ; les distinctions entre traduction assermentée,
 * certification notariée et apostille sont préservées ; aucune garantie
 * d'acceptation par les institutions n'est donnée.
 * `priority` = ordre d'importance global (plus petit = plus haut). La vue par
 * catégorie utilise le même ordre, l'ordre au sein d'une catégorie en découle.
 */
import type { FaqCategory, FaqItem } from "./faq-data"

export const FAQ_CATEGORIES_FR: FaqCategory[] = [
  { key: "general", label: "Général" },
  { key: "order", label: "Processus de commande" },
  { key: "pricing", label: "Tarifs et paiement" },
  { key: "upload", label: "Envoi de fichiers" },
  { key: "languages", label: "Langues et paires de langues" },
  { key: "services", label: "Types de services" },
  { key: "delivery", label: "Livraison et délais" },
  { key: "sworn", label: "Traduction assermentée" },
  { key: "notary", label: "Certification notariée et apostille" },
  { key: "quality", label: "Qualité et révisions" },
  { key: "privacy", label: "Confidentialité et sécurité" },
  { key: "corporate", label: "Services aux entreprises" },
  { key: "support", label: "Assistance technique" },
]

export const FAQ_ITEMS_FR: FaqItem[] = [
  // ——— TOUT : questions prioritaires tout au long du parcours client ———
  {
    id: "nasil-fiyat-alirim",
    category: "pricing",
    priority: 1,
    q: "Comment obtenir un devis ?",
    a: "Rendez-vous sur la page Calculer le prix, téléversez votre document ou collez votre texte ; dès que vous choisissez la paire de langues et le type de service, votre devis préliminaire s'affiche instantanément. Le prix dépend de la paire de langues, du type de service, du nombre de mots et des services complémentaires que vous sélectionnez.",
    keywords: ["devis", "tarif", "prix", "estimation", "coût traduction", "obtenir un devis"],
  },
  {
    id: "dosya-nasil-yuklenir",
    category: "upload",
    priority: 2,
    q: "Comment téléverser mon fichier ?",
    a: "Sur la page Calculer le prix, ouvrez l'onglet « Téléverser un fichier » : vous pouvez glisser-déposer votre document ou le sélectionner. Si vous n'avez pas de fichier, il vous suffit de coller votre texte dans l'onglet « Saisir le texte ». Pour les fichiers textuels, le système calcule automatiquement le nombre de mots.",
    keywords: ["téléverser un fichier", "envoyer un document", "ajouter un fichier", "impossible de téléverser", "comment envoyer"],
  },
  {
    id: "fiyatlandirma-neye-gore",
    category: "pricing",
    priority: 3,
    q: "Comment le prix est-il déterminé ?",
    a: "Le prix est établi en fonction de la paire de langues, du type de service, du contenu du document, du nombre de mots, du domaine de spécialité et des services complémentaires choisis. Le montant affiché à l'écran est un devis préliminaire ; le prix définitif est confirmé après examen du document.",
    keywords: ["tarification", "comment le prix", "facteurs de prix", "au mot", "tarifs"],
  },
  {
    id: "teslim-suresi-ne-kadar",
    category: "delivery",
    priority: 4,
    q: "Quel est le délai de livraison ?",
    a: "Le délai dépend de la longueur du document, de la paire de langues, du type de service et des services complémentaires choisis. L'écran de calcul du prix affiche un délai de livraison estimé propre à votre commande. Ce délai peut être réduit grâce à l'option de livraison express.",
    keywords: ["délai de livraison", "combien de jours", "quand livré", "délai", "durée"],
  },
  {
    id: "yeminli-tercume-nedir",
    category: "sworn",
    priority: 5,
    q: "Qu'est-ce qu'une traduction assermentée ?",
    a: "Une traduction assermentée est une traduction certifiée par un traducteur assermenté au moyen de sa signature et de son cachet, attestant sa conformité à l'original. Elle est fréquemment exigée pour les démarches officielles. Le caractère obligatoire dépend de l'organisme qui demande le document.",
    keywords: ["traduction assermentée", "traduction certifiée", "traduction officielle", "traduction avec cachet", "définition assermentée"],
  },
  {
    id: "hangi-dillerde-hizmet",
    category: "languages",
    priority: 6,
    q: "Dans quelles langues proposez-vous vos services ?",
    a: "Nous travaillons en turc ainsi qu'en anglais, allemand, français, espagnol, italien, arabe, russe et dans plus de 50 langues au total. Pour les langues rares, la disponibilité d'un traducteur et le délai de livraison sont confirmés séparément pour chaque commande.",
    keywords: ["langues", "quelles langues", "options de langues", "paires de langues", "combien de langues"],
  },
  {
    id: "noter-onayi-gerekir-mi",
    category: "notary",
    priority: 7,
    q: "La certification notariée est-elle nécessaire ?",
    a: "La certification notariée n'est pas obligatoire pour tous les documents ; son caractère nécessaire dépend de l'organisme qui demande le document et de l'usage prévu. Pour certaines démarches une traduction assermentée suffit, tandis que d'autres exigent en plus une certification notariée. Si vous ne savez pas quelle certification vous convient, nous pouvons vous orienter.",
    keywords: ["certification notariée", "notaire", "document notarié", "notariée nécessaire"],
  },
  {
    id: "siparis-nasil-ilerler",
    category: "order",
    priority: 8,
    q: "Comment se déroule le processus de commande ?",
    a: "Une fois votre document téléversé et le devis préliminaire validé, votre commande est créée et confiée à un traducteur spécialisé dans le domaine concerné. La traduction passe par un contrôle qualité ; si nécessaire, la certification notariée est prise en charge, puis votre document vous est livré au format numérique et, au besoin, par voie postale.",
    keywords: ["processus de commande", "comment ça marche", "étapes", "déroulement"],
  },
  {
    id: "belgelerim-guvende-mi",
    category: "privacy",
    priority: 9,
    q: "Mes documents sont-ils en sécurité ?",
    a: "Oui. Vos fichiers ne sont consultés que par l'équipe en charge de votre commande et sont traités via un transfert chiffré et des procédures conformes à la KVKK. Vos documents ne sont jamais communiqués à des tiers et la confidentialité est notre priorité.",
    keywords: ["sécurité", "confidentialité", "sécurité des documents", "sécurité des données", "kvkk"],
  },
  {
    id: "cevirimi-kim-yapar",
    category: "quality",
    priority: 10,
    q: "Qui traduit mon document ?",
    a: "Vos traductions sont réalisées par des traducteurs humains professionnels expérimentés dans le domaine concerné. Un traducteur spécialisé est affecté selon le type de document, et chaque traduction passe par un contrôle qualité avant la livraison.",
    keywords: ["qui traduit", "traducteur", "traducteur humain", "linguiste", "qui réalise"],
  },
  {
    id: "revize-hakki-var-mi",
    category: "quality",
    priority: 11,
    q: "Les révisions sont-elles incluses ?",
    a: "Oui. Une fois la traduction livrée, vous bénéficiez d'un droit de révision pour les corrections comprises dans le périmètre initial. Les corrections d'orthographe, de noms, de dates ou de cohérence en font partie. Modifier le texte source a posteriori ou ajouter du nouveau contenu peut être considéré comme un nouveau travail.",
    keywords: ["révision", "correction", "retouche", "refaire la traduction", "droit de révision"],
  },
  {
    id: "fiziksel-teslimat-yapiliyor-mu",
    category: "delivery",
    priority: 12,
    q: "Proposez-vous une livraison physique ?",
    a: "Oui. Si la livraison numérique est la norme, les documents portant une signature manuscrite originale et un cachet peuvent vous être envoyés à votre adresse par voie postale. Nous expédions dans toute la Turquie et, sur demande, à l'international. Si vous optez pour l'envoi postal, le délai d'acheminement s'ajoute au délai de livraison.",
    keywords: ["livraison physique", "envoi postal", "coursier", "livraison à l'adresse"],
  },
  {
    id: "kurumsal-ozel-sartlar",
    category: "corporate",
    priority: 13,
    q: "Existe-t-il des conditions particulières pour les clients professionnels ?",
    a: "Oui. Les clients professionnels bénéficient d'avantages sur les commandes en volume, d'options de délai de paiement, d'une gestion terminologique et d'un gestionnaire de compte dédié. Pour en savoir plus, remplissez le formulaire de demande sur notre page Entreprises.",
    keywords: ["entreprise", "professionnel", "conditions entreprise", "commande en volume", "société"],
  },
  {
    id: "apostil-nasil-yurutulur",
    category: "notary",
    priority: 14,
    q: "Comment se déroule la procédure d'apostille ?",
    a: "L'apostille est une certification délivrée par l'autorité compétente afin qu'un document soit reconnu valable à l'étranger. Nous n'effectuons pas la procédure d'apostille ; vous devez obtenir l'apostille vous-même auprès de l'autorité compétente du pays où votre document a été établi. Nous réalisons uniquement la traduction assermentée de vos documents apostillés. Dans les pays non parties à la Convention de La Haye, une légalisation consulaire peut être exigée à la place de l'apostille.",
    keywords: ["apostille", "procédure d'apostille", "légalisation", "valable à l'étranger"],
  },
  {
    id: "acil-teslimat-mumkun-mu",
    category: "delivery",
    priority: 15,
    q: "La livraison express est-elle possible ?",
    a: "Oui, la livraison express est proposée pour de nombreux documents et réduit le délai de livraison. Elle donne lieu à un supplément et sa disponibilité peut varier selon la longueur et la langue du document. Les étapes de contrôle qualité sont maintenues, même en cas d'urgence.",
    keywords: ["livraison express", "livraison rapide", "le jour même", "urgent", "délai court"],
  },
  {
    id: "odeme-nasil-yapilir",
    category: "pricing",
    priority: 16,
    q: "Comment effectuer le paiement ?",
    a: "Les paiements peuvent être effectués par carte bancaire ou par virement ; le paiement en plusieurs fois peut être proposé sur carte bancaire. Les clients professionnels bénéficient en outre d'une facturation à délai de paiement (15 à 30 jours). Le paiement est encaissé après validation du devis préliminaire.",
    keywords: ["paiement", "mode de paiement", "carte bancaire", "virement", "comment payer"],
  },
  {
    id: "dosya-yuklemeden-fiyat",
    category: "upload",
    priority: 17,
    q: "Peut-on obtenir un devis sans téléverser de fichier ?",
    a: "Oui. Si vous n'avez pas de fichier, collez votre texte dans l'onglet « Saisir le texte » pour obtenir un devis préliminaire calculé sur le nombre de mots.",
    keywords: ["devis sans fichier", "devis à partir du texte", "sans téléversement", "estimation par texte"],
  },
  {
    id: "belgenin-formati-korunur-mu",
    category: "delivery",
    priority: 18,
    q: "La mise en forme du document est-elle conservée ?",
    a: "Dans la mesure du possible, la mise en page d'origine, les tableaux et la mise en forme sont conservés dans la traduction. Selon vos besoins, le résultat peut être livré au format PDF ou Word (DOCX) modifiable. Pour les documents numérisés ou en image, nous proposons une mise en page nette et ordonnée plutôt qu'une reproduction à l'identique.",
    keywords: ["mise en forme", "format", "mise en page", "word", "pdf", "format conservé"],
  },
  {
    id: "teslim-sonrasi-destek",
    category: "quality",
    priority: 19,
    q: "Puis-je bénéficier d'une assistance après la livraison de la traduction ?",
    a: "Oui. Après la livraison, une assistance de révision est proposée pour les corrections comprises dans le périmètre, et vous pouvez contacter notre service client pour toute question. Vous pouvez transmettre vos demandes complémentaires concernant votre document par e-mail ou WhatsApp.",
    keywords: ["assistance après livraison", "après la livraison", "aide", "support"],
  },
  {
    id: "cok-sayfali-yuksek-hacim",
    category: "order",
    priority: 20,
    q: "Comment sont gérés les travaux volumineux ou à nombreuses pages ?",
    a: "Les projets à fort volume sont planifiés avec soin ; au besoin, plusieurs traducteurs et relecteurs interviennent et un glossaire commun est utilisé pour garantir la cohérence terminologique. Les projets longs peuvent être livrés par parties (livraison partielle) si vous le souhaitez. Pour les projets d'entreprise, le déroulement est coordonné par votre gestionnaire de compte.",
    keywords: ["nombreuses pages", "fort volume", "travail volumineux", "grand projet", "documents multiples"],
  },

  // ——— GÉNÉRAL ———
  {
    id: "tercumexpert-nedir",
    category: "general",
    priority: 21,
    q: "Qu'est-ce que TercümExpert ?",
    a: "TercümExpert est un prestataire de services de traduction en ligne proposant la traduction assermentée, la traduction avec certification notariée, la traduction juridique, technique, médicale et académique, ainsi que la localisation web et mobile. Vous pouvez téléverser votre document, obtenir un devis préliminaire et passer votre commande entièrement en ligne.",
    keywords: ["tercumexpert", "qu'est-ce que", "à propos", "service de traduction", "que faites-vous"],
  },
  {
    id: "hangi-hizmetler",
    category: "general",
    priority: 22,
    q: "Quels services propose TercümExpert ?",
    a: "Nous proposons la traduction assermentée et avec certification notariée, la traduction de documents apostillés, la traduction juridique, technique, médicale et académique, ainsi que la localisation de sites web et d'applications mobiles. Vous pouvez choisir le service adapté à vos besoins sur l'écran Calculer le prix.",
    keywords: ["services", "ce que vous proposez", "types de services", "quels services"],
  },
  {
    id: "kimler-hizmet-alabilir",
    category: "general",
    priority: 23,
    q: "Qui peut faire appel à vos services ?",
    a: "Aussi bien les particuliers que les entreprises et les organisations peuvent faire appel à nos services. De l'étudiant au travailleur indépendant, de la PME aux grands groupes, nous proposons des solutions adaptées à des besoins variés.",
    keywords: ["qui peut", "particuliers", "entreprises", "sociétés", "clients"],
  },
  {
    id: "ofise-gelmek-gerekir-mi",
    category: "general",
    priority: 24,
    q: "Faut-il se rendre dans un bureau en personne ?",
    a: "Notre société ne dispose pas de bureau physique ; nos services sont entièrement fournis en ligne. Il vous suffit de nous transmettre vos documents via un téléversement sécurisé ; la livraison s'effectue au format numérique et, au besoin, par voie postale. Pour toute question, vous pouvez nous joindre via WhatsApp ou à l'adresse info@tercumexpert.com.",
    keywords: ["bureau", "en personne", "agence", "adresse", "déplacement nécessaire"],
  },
  {
    id: "surec-cevrimici-mi",
    category: "general",
    priority: 25,
    q: "Tout le processus peut-il se faire en ligne ?",
    a: "Oui. Le téléversement des documents, la validation du devis, le paiement et la livraison numérique sont entièrement en ligne. L'envoi postal n'intervient que lorsqu'un document physique avec signature manuscrite originale est requis.",
    keywords: ["en ligne", "entièrement en ligne", "à distance", "internet", "tout en ligne"],
  },
  {
    id: "yurt-disindan-hizmet",
    category: "general",
    priority: 26,
    q: "Les clients à l'étranger peuvent-ils faire appel à vos services ?",
    a: "Oui. Comme le processus se déroule en ligne, vous pouvez téléverser vos documents et passer commande depuis l'étranger. La livraison numérique est disponible partout et, pour les documents à signature manuscrite originale, nous pouvons aussi expédier à l'international par voie postale.",
    keywords: ["étranger", "clients internationaux", "depuis l'étranger", "hors turquie"],
  },
  {
    id: "uyelik-zorunlu-mu",
    category: "general",
    priority: 27,
    q: "Faut-il créer un compte pour bénéficier des services ?",
    a: "La création d'un compte n'est pas obligatoire. Toutefois, pour consulter le prix et passer commande, vous devez saisir vos nom, prénom et adresse e-mail, puis confirmer le code de vérification reçu par e-mail. Si vous le souhaitez, vous pouvez créer un compte afin de suivre l'historique de vos commandes.",
    keywords: ["compte", "inscription", "adhésion", "obligatoire", "sans compte"],
  },
  {
    id: "uye-olmadan-fiyat",
    category: "general",
    priority: 28,
    q: "Peut-on obtenir un devis sans s'inscrire ?",
    a: "Oui, vous pouvez obtenir un devis sans créer de compte complet ; il suffit de vérifier vos nom, prénom et adresse e-mail. Les utilisateurs qui ne terminent pas la vérification ne peuvent ni consulter le prix ni passer commande.",
    keywords: ["devis sans compte", "sans inscription", "code de vérification", "vérification e-mail"],
  },
  {
    id: "siparis-oncesi-danismanlik",
    category: "general",
    priority: 29,
    q: "Peut-on obtenir des conseils avant de passer commande ?",
    a: "Oui. Si vous ne savez pas quel service vous convient, vous pouvez obtenir des renseignements via WhatsApp, par e-mail ou grâce à notre assistant de chat propulsé par l'intelligence artificielle. Nous déterminons ensemble le service et la démarche adaptés au type de votre document.",
    keywords: ["conseil", "renseignement", "poser une question", "aide avant commande"],
  },
  {
    id: "musteri-temsilcisi",
    category: "general",
    priority: 30,
    q: "Comment joindre un conseiller clientèle ?",
    a: "Vous pouvez joindre notre service client via WhatsApp ou par e-mail. Vos questions sont traitées par un conseiller pendant les heures ouvrables ; notre assistant de chat propulsé par l'IA peut par ailleurs vous fournir une première orientation à tout moment.",
    keywords: ["conseiller clientèle", "support", "contact", "joindre", "assistance en direct"],
  },
  {
    id: "hangi-belgeler-cevrilebilir",
    category: "general",
    priority: 31,
    q: "Quels types de documents peuvent être traduits ?",
    a: "Nous traduisons une large palette de documents, des pièces officielles et personnelles aux textes commerciaux, juridiques, techniques, médicaux et académiques. De nombreux types de documents sont pris en charge : diplômes, contrats, rapports, manuels, contenus de sites web, etc.",
    keywords: ["types de documents", "quels documents", "pièces", "que peut-on traduire"],
  },
  {
    id: "yapay-zeka-mi-insan-mi",
    category: "general",
    priority: 32,
    q: "Les traductions sont-elles réalisées par des traducteurs humains ?",
    a: "Oui. Vos traductions sont réalisées de bout en bout par des traducteurs humains professionnels. Des outils de TAO sont utilisés pour renforcer la cohérence et la terminologie ; toutefois, l'intégralité de la traduction est l'œuvre de traducteurs experts et passe par un contrôle qualité.",
    keywords: ["traducteur humain", "outil de tao", "outils de traduction", "traduction automatique", "qui traduit"],
  },
  {
    id: "el-yazili-belgeler",
    category: "general",
    priority: 33,
    q: "Les documents manuscrits ou difficiles à lire peuvent-ils être traduits ?",
    a: "Les documents manuscrits et difficiles à lire peuvent être traduits, à condition d'être lisibles. Les passages illisibles sont clairement signalés dans la traduction et, si nécessaire, nous vous demandons une copie plus nette. Pour ce type de documents, le prix est confirmé après examen.",
    keywords: ["écriture manuscrite", "manuscrit", "illisible", "peu clair", "difficile à lire"],
  },
  {
    id: "farkiniz-nedir",
    category: "general",
    priority: 34,
    q: "Qu'est-ce qui distingue TercümExpert des autres services de traduction ?",
    a: "Notre processus 100 % en ligne de bout en bout, le devis préliminaire automatisé, des traducteurs humains spécialisés et le contrôle qualité sont nos points forts. Nous livrons également les documents à signature manuscrite originale directement à votre porte par voie postale.",
    keywords: ["différence", "avantage", "pourquoi tercumexpert", "ce qui vous distingue"],
  },

  // ——— PROCESSUS DE COMMANDE ———
  {
    id: "siparis-nasil-verilir",
    category: "order",
    priority: 35,
    q: "Comment passer une commande ?",
    a: "Sur l'écran Calculer le prix, téléversez votre document ou saisissez votre texte, choisissez la paire de langues et le type de service, puis validez le devis préliminaire. Une fois votre validation effectuée, votre commande est créée.",
    keywords: ["passer commande", "comment commander", "créer une commande"],
  },
  {
    id: "siparis-icin-gerekli-bilgiler",
    category: "order",
    priority: 36,
    q: "Quelles informations sont nécessaires pour passer commande ?",
    a: "Vous avez besoin du document ou du texte à traduire, de la langue source et de la langue cible, du type de service ainsi que de vos nom, prénom et adresse e-mail pour le contact. Avec ces informations, vous pouvez créer votre commande.",
    keywords: ["informations nécessaires", "ce qu'il faut", "détails de la commande"],
  },
  {
    id: "dil-cifti-nasil-secilir",
    category: "order",
    priority: 37,
    q: "Comment choisir la paire de langues et le type de service ?",
    a: "Sur l'écran Calculer le prix, vous sélectionnez dans le menu la langue source (la langue du document), la langue cible (la langue de traduction) et le type de service (assermentée, avec certification notariée, technique, etc.). En cas de doute, notre service client ou notre assistant de chat vous oriente vers le bon choix.",
    keywords: ["choisir la paire de langues", "langue source", "langue cible", "choisir le service"],
  },
  {
    id: "bilgiler-degistirilebilir-mi",
    category: "order",
    priority: 38,
    q: "Peut-on modifier les informations après la création d'une commande ?",
    a: "Les informations telles que la langue, le type de service ou le document peuvent être modifiées avant le début de la traduction. Il vous suffit de contacter notre service client dès que possible ; à mesure que le travail avance, la marge de modification peut se réduire.",
    keywords: ["modifier les informations", "corriger la commande", "mettre à jour la commande", "mauvaise langue", "mauvais document"],
  },
  {
    id: "onaydan-once-iptal",
    category: "order",
    priority: 39,
    q: "Peut-on annuler une commande avant sa validation ?",
    a: "Oui. Vous pouvez annuler votre commande tant que le paiement et la validation ne sont pas finalisés ; aucun frais n'est appliqué à ce stade.",
    keywords: ["annulation", "annuler la commande", "renoncer"],
  },
  {
    id: "odeme-sonrasi-iptal",
    category: "order",
    priority: 40,
    q: "Une commande peut-elle être annulée après le paiement ?",
    a: "Si votre commande n'a pas encore été prise en charge par un traducteur, vous pouvez l'annuler depuis votre page de commande ou à l'adresse info@tercumexpert.com, et votre paiement est intégralement remboursé sur le moyen de paiement d'origine. Une fois que la traduction a été prise en charge par un traducteur, aucun remboursement n'est effectué, en raison de la nature personnalisée de la prestation.",
    keywords: ["annulation après paiement", "remboursement", "remboursé"],
  },
  {
    id: "siparis-durumu-takip",
    category: "order",
    priority: 41,
    q: "Où suivre l'état de sa commande ?",
    a: "Vous êtes informé de l'état de votre commande par e-mail ; si vous avez créé un compte, vous pouvez également en assurer le suivi depuis celui-ci. Vous pouvez aussi demander l'état actuel à notre service client.",
    keywords: ["suivi de commande", "état", "suivi", "statut de la commande"],
  },
  {
    id: "birden-fazla-belge",
    category: "order",
    priority: 42,
    q: "Une même commande peut-elle contenir plusieurs documents ou langues cibles ?",
    a: "Oui, vous pouvez téléverser plusieurs documents dans une même commande et faire traduire un même document vers plusieurs langues. Le nombre total de mots et chaque langue cible sont tarifés comme des traductions distinctes, et l'ensemble est coordonné au sein d'une seule demande.",
    keywords: ["plusieurs documents", "plusieurs fichiers", "plusieurs langues", "langues multiples"],
  },
  {
    id: "sonradan-dosya-eklenebilir",
    category: "order",
    priority: 43,
    q: "Peut-on ajouter un nouveau fichier à une commande par la suite ?",
    a: "Vous pouvez ajouter un nouveau fichier avant le début de la traduction ; dans ce cas, le prix est mis à jour en fonction du contenu ajouté. Les documents ajoutés une fois le travail entamé peuvent être traités comme une nouvelle ligne de commande.",
    keywords: ["ajouter un fichier", "ajouter plus tard", "nouveau fichier"],
  },
  {
    id: "eksik-belge-gonderilirse",
    category: "order",
    priority: 44,
    q: "Que se passe-t-il si un document incomplet est envoyé ?",
    a: "Lorsque nous constatons qu'une page ou un document manque, nous vous demandons de le compléter. Le téléversement de toutes les pages du document est essentiel pour que la traduction soit complète et valable.",
    keywords: ["document incomplet", "page manquante", "document manquant"],
  },
  {
    id: "terminoloji-not-referans",
    category: "order",
    priority: 45,
    q: "Peut-on ajouter des notes, une terminologie ou des fichiers de référence propres à la commande ?",
    a: "Oui. Lors de la commande, vous pouvez ajouter des instructions particulières, vos termes préférés ou une note de style, et téléverser des fichiers de référence tels que des traductions antérieures ou des glossaires. Ces informations sont transmises au traducteur et utilisées pour garantir la cohérence.",
    keywords: ["ajouter une note", "instructions particulières", "terminologie", "fichier de référence", "glossaire"],
  },
  {
    id: "eski-siparisler-goruntulenir",
    category: "order",
    priority: 46,
    q: "Peut-on accéder ultérieurement aux anciennes commandes et fichiers ?",
    a: "Si vous avez créé un compte, vous pouvez y consulter vos commandes passées et vos fichiers livrés. Pour les commandes passées sans compte, vous pouvez accéder à vos données par e-mail ; si un lien de téléchargement a expiré, vous pouvez en demander un nouveau à notre service client.",
    keywords: ["anciennes commandes", "historique des commandes", "commandes précédentes", "accès aux fichiers"],
  },

  // ——— TARIFS ET PAIEMENT ———
  {
    id: "kelime-mi-sayfa-mi",
    category: "pricing",
    priority: 47,
    q: "La facturation se fait-elle au mot ou à la page ?",
    a: "La facturation repose généralement sur le nombre de mots et le service choisi. Pour les documents textuels, le nombre de mots est extrait automatiquement ; pour les documents numérisés ou en image, il est confirmé après examen.",
    keywords: ["au mot", "à la page", "base de facturation", "comment facturé"],
  },
  {
    id: "sabit-baslangic-ucreti",
    category: "pricing",
    priority: 48,
    q: "Existe-t-il des frais fixes de départ ou un montant minimum ?",
    a: "Certains services peuvent comporter un forfait minimum, applicable aux documents courts. Le prix définitif est déterminé par le contenu du document et les services que vous choisissez, et vous pouvez voir chaque ligne sur l'écran du devis préliminaire.",
    keywords: ["frais de départ", "minimum", "forfait", "montant minimum"],
  },
  {
    id: "neler-fiyati-etkiler",
    category: "pricing",
    priority: 49,
    q: "La paire de langues, le type de document et le domaine influent-ils sur le prix ?",
    a: "Oui. La paire de langues (surtout pour les langues rares), le type de document et le domaine de spécialité (juridique, médical, technique, etc.) peuvent influer sur la densité terminologique et donc sur le prix. Pour les langues courantes, la tarification est plus prévisible.",
    keywords: ["prix paire de langues", "prix type de document", "prix domaine", "pourquoi des prix différents"],
  },
  {
    id: "yeminli-daha-pahali-mi",
    category: "pricing",
    priority: 50,
    q: "Une traduction assermentée est-elle plus chère ?",
    a: "La traduction assermentée peut être tarifée différemment d'une traduction standard, en raison de la certification et de la responsabilité du traducteur. Le montant exact s'affiche sur l'écran du devis préliminaire selon le document et la paire de langues.",
    keywords: ["prix traduction assermentée", "coût assermentée", "assermentée plus chère"],
  },
  {
    id: "noter-apostil-ucreti-dahil",
    category: "pricing",
    priority: 51,
    q: "Les frais de certification notariée et d'apostille sont-ils inclus dans le prix ?",
    a: "La certification notariée est une démarche distincte effectuée par les autorités compétentes et soumise à des tarifs officiels ; ces frais sont indiqués séparément du tarif de traduction et, comme ils suivent un tarif officiel, ils peuvent ne pas être exacts à l'avance, le montant réel étant communiqué après la démarche. La procédure d'apostille, en revanche, n'est pas effectuée par nos soins ; vous devez obtenir l'apostille vous-même auprès de l'autorité compétente, et nous traduisons uniquement votre document apostillé.",
    keywords: ["frais de notaire", "frais d'apostille", "est-ce inclus", "coût notaire", "coût apostille"],
  },
  {
    id: "on-fiyat-nihai-fark",
    category: "pricing",
    priority: 52,
    q: "Le devis préliminaire peut-il différer du prix définitif ?",
    a: "Oui. Le calcul automatique affiché à l'écran est un devis préliminaire. Après un examen fondé sur le nombre de mots, la lisibilité ou le type de document, le prix définitif peut être confirmé. Le montant final vous est communiqué avant votre validation.",
    keywords: ["devis préliminaire", "prix définitif", "écart de prix", "prix exact"],
  },
  {
    id: "otomatik-kelime-sayimi",
    category: "pricing",
    priority: 53,
    q: "Le nombre de mots est-il calculé automatiquement ? Qu'en est-il des PDF numérisés ?",
    a: "Pour les documents textuels (Word, PDF texte, texte brut), le nombre de mots est extrait automatiquement. Pour les PDF numérisés ou en image et les photos, le comptage automatique peut être peu fiable ; dans ce cas, notre équipe confirme le nombre de mots. Le devis préliminaire repose sur le comptage automatique et n'est pas contractuel ; en cas d'écart, le prix définitif est validé avec vous.",
    keywords: ["nombre de mots", "comptage automatique", "pdf numérisé", "pdf en image", "erreur de comptage"],
  },
  {
    id: "toplu-kurumsal-indirim",
    category: "pricing",
    priority: 54,
    q: "Existe-t-il des remises pour les commandes en volume ou les clients professionnels ?",
    a: "Pour les travaux à fort volume et récurrents, en particulier pour les clients professionnels, nous pouvons proposer une tarification avantageuse et des options de délai de paiement en fonction du volume et des conditions de collaboration. Pour en savoir plus, utilisez le formulaire de demande Entreprises.",
    keywords: ["remise volume", "remise quantité", "tarif entreprise", "tarifs professionnels"],
  },
  {
    id: "ucretsiz-teklif",
    category: "pricing",
    priority: 55,
    q: "Peut-on obtenir un devis gratuit et quelle est sa durée de validité ?",
    a: "Le devis préliminaire est gratuit ; vous le voyez instantanément dès que vous téléversez votre document ou saisissez votre texte. Les devis sont valables pour une courte durée, tant que les conditions (contenu/portée du document) ne changent pas.",
    keywords: ["devis gratuit", "estimation gratuite", "validité du devis", "durée de validité"],
  },
  {
    id: "fatura-kesiliyor-mu",
    category: "pricing",
    priority: 56,
    q: "Émettez-vous des factures ? Peut-on obtenir une facture au nom d'un particulier ou d'une entreprise ?",
    a: "Oui. Une facture est émise pour la prestation, et vous pouvez demander une facture au nom d'un particulier ou d'une entreprise. Les clients professionnels peuvent également bénéficier d'une facturation mensuelle regroupée. Les taxes sont appliquées conformément à la réglementation en vigueur.",
    keywords: ["facture", "facturation", "tva", "facture entreprise", "facture particulier"],
  },
  {
    id: "taksit-secenegi",
    category: "pricing",
    priority: 57,
    q: "Le paiement en plusieurs fois est-il possible ?",
    a: "Le paiement en plusieurs fois peut être proposé pour les règlements par carte bancaire. Les options d'échelonnement éligibles s'affichent à l'étape de paiement.",
    keywords: ["paiement en plusieurs fois", "échelonnement", "paiement échelonné"],
  },
  {
    id: "kurumsal-vadeli-odeme",
    category: "pricing",
    priority: 58,
    q: "Proposez-vous un délai de paiement aux clients professionnels ?",
    a: "Oui. Les clients professionnels peuvent bénéficier d'un délai de paiement pouvant aller jusqu'à 15 à 30 jours et d'une facturation mensuelle. Les conditions sont définies dans le cadre de l'accord entreprise.",
    keywords: ["délai de paiement", "paiement à échéance", "paiement entreprise"],
  },
  {
    id: "odeme-yapilmadan-baslar-mi",
    category: "pricing",
    priority: 59,
    q: "La traduction commence-t-elle avant le paiement ?",
    a: "Pour les commandes standard, la traduction débute une fois le paiement (ou la validation du délai de paiement pour les entreprises) reçu. Pour les accords d'entreprise, le déroulement peut suivre les termes du contrat.",
    keywords: ["prépaiement", "avant paiement", "paiement à l'avance", "sans paiement"],
  },
  {
    id: "iade-sureci",
    category: "pricing",
    priority: 60,
    q: "Les commandes annulées donnent-elles lieu à un remboursement ?",
    a: "Si votre commande est annulée avant d'avoir été prise en charge par un traducteur, votre paiement est intégralement remboursé sur le moyen de paiement d'origine. Une fois que la traduction a été prise en charge par un traducteur, aucun remboursement n'est effectué, en raison de la nature personnalisée de la prestation. En cas de double débit ou de débit erroné, le montant excédentaire est remboursé.",
    keywords: ["remboursement", "remboursé", "remboursement annulation", "restitution"],
  },

  // ——— ENVOI DE FICHIERS ———
  {
    id: "hangi-formatlar",
    category: "upload",
    priority: 61,
    q: "Quels formats de fichiers sont pris en charge ?",
    a: "Nous acceptons plus de 50 formats, dont Word (DOC/DOCX), PDF, texte brut (TXT), Excel, PowerPoint et les formats d'image courants (JPG, PNG). Pour les documents textuels, le nombre de mots est extrait automatiquement.",
    keywords: ["format de fichier", "formats pris en charge", "pdf", "doc", "docx", "txt"],
  },
  {
    id: "taranmis-fotograf-belge",
    category: "upload",
    priority: 62,
    q: "Acceptez-vous les documents numérisés ou photographiés ?",
    a: "Oui. Les documents numérisés et les photos nettes prises au téléphone sont acceptés. La lisibilité est importante ; les cachets, tampons et signatures doivent être visibles. Le texte des images ne pouvant pas toujours être lu automatiquement, le nombre de mots est déterminé par notre équipe.",
    keywords: ["document numérisé", "photo de document", "photo au téléphone", "envoi d'image", "image"],
  },
  {
    id: "birden-fazla-dosya-yukleme",
    category: "upload",
    priority: 63,
    q: "Peut-on téléverser plusieurs fichiers en même temps ?",
    a: "Oui, vous pouvez téléverser plusieurs fichiers simultanément. Le prix est calculé sur l'ensemble du contenu.",
    keywords: ["téléversement multiple", "plusieurs fichiers", "envoi groupé"],
  },
  {
    id: "dosya-boyutu-siniri",
    category: "upload",
    priority: 64,
    q: "Y a-t-il une limite de taille de fichier ? Comment envoyer des fichiers volumineux ?",
    a: "Vous pouvez téléverser jusqu'à environ 100 Mo par fichier. Pour des fichiers plus volumineux, contactez notre service client afin d'organiser l'envoi par e-mail ou par une autre méthode.",
    keywords: ["taille de fichier", "limite de taille", "fichier volumineux", "100 mo"],
  },
  {
    id: "yuklenen-dosya-silinebilir",
    category: "upload",
    priority: 65,
    q: "Peut-on supprimer ou remplacer un fichier téléversé ?",
    a: "Oui. Tant que la commande n'est pas finalisée, vous pouvez retirer le fichier téléversé ou le remplacer par un autre.",
    keywords: ["supprimer un fichier", "remplacer un fichier", "mauvais fichier"],
  },
  {
    id: "manuel-kelime-girisi",
    category: "upload",
    priority: 66,
    q: "Peut-on saisir manuellement le nombre de mots sans téléverser de fichier ?",
    a: "Plutôt que de saisir directement un nombre, collez votre texte dans l'onglet « Saisir le texte » : le nombre de mots est alors calculé automatiquement. Vous pouvez ainsi obtenir un devis préliminaire sans fichier.",
    keywords: ["nombre de mots manuel", "saisir des mots", "saisir le texte"],
  },
  {
    id: "dosyalar-ne-kadar-saklanir",
    category: "upload",
    priority: 67,
    q: "Combien de temps les fichiers sont-ils conservés et peut-on demander leur suppression ?",
    a: "Vos documents ne sont conservés de manière sécurisée que le temps nécessaire à la prestation. Vous pouvez à tout moment demander la suppression de vos documents ; cette demande est traitée conformément à vos droits au titre de la KVKK.",
    keywords: ["durée de conservation", "stockage des fichiers", "demande de suppression", "suppression des données"],
  },
  {
    id: "belgenin-tum-sayfalari",
    category: "upload",
    priority: 68,
    q: "Faut-il téléverser toutes les pages et le verso du document ?",
    a: "Oui. Pour que la traduction soit complète et valable, vous devez téléverser chaque page du document, y compris le verso le cas échéant. Il est important que les zones de cachet, de tampon et de signature soient nettement visibles.",
    keywords: ["toutes les pages", "verso", "document complet", "cachets et tampons"],
  },
  {
    id: "imza-kase-cevrilir-mi",
    category: "upload",
    priority: 69,
    q: "Les cachets, tampons et signatures sont-ils traduits ?",
    a: "Dans une traduction assermentée, le texte lisible figurant sur les cachets et tampons est retranscrit ; les signatures sont quant à elles mentionnées par la formule « signature présente ». Les zones illisibles sont clairement signalées dans la traduction.",
    keywords: ["traduction du cachet", "traduction du tampon", "traduction de la signature"],
  },
  {
    id: "dosya-guvenli-mi-analiz",
    category: "upload",
    priority: 70,
    q: "Le contenu du document est-il en sécurité pendant l'analyse automatique ?",
    a: "Oui. Les documents sont transférés sous forme chiffrée et les opérations telles que le comptage des mots sont réalisées dans un environnement sécurisé. Votre contenu n'est jamais communiqué à des tiers.",
    keywords: ["sécurité de l'analyse", "sécurité du contenu", "lecture automatique"],
  },

  // ——— LANGUES ET PAIRES DE LANGUES ———
  {
    id: "50-dil-ne-demek",
    category: "languages",
    priority: 71,
    q: "Que signifie la prise en charge de plus de 50 langues ?",
    a: "Cela signifie qu'en plus des langues courantes, nous pouvons aussi traduire des langues moins demandées. Pour les langues rares, la disponibilité d'un traducteur, le délai et le prix sont confirmés séparément pour chaque commande.",
    keywords: ["50 langues", "langue rare", "prise en charge des langues", "combien de langues"],
  },
  {
    id: "yaygin-dil-ciftleri",
    category: "languages",
    priority: 72,
    q: "Traduisez-vous des paires comme turc-anglais, allemand ou français ?",
    a: "Oui. Nous traduisons des paires de langues courantes telles que turc ⇄ anglais, allemand, français, espagnol, italien, arabe et russe, dans les deux sens. Des langues comme le chinois et le japonais sont également prises en charge.",
    keywords: ["turc anglais", "anglais turc", "allemand", "français", "paire de langues"],
  },
  {
    id: "yabancidan-yabanciya",
    category: "languages",
    priority: 73,
    q: "Peut-on traduire entre deux langues étrangères autres que le turc ?",
    a: "Oui, nous pouvons traduire d'une langue étrangère vers une autre, par exemple de l'anglais vers le français. La disponibilité et le délai sont évalués selon la paire de langues.",
    keywords: ["langue étrangère vers langue étrangère", "anglais français", "entre langues"],
  },
  {
    id: "nadir-dil",
    category: "languages",
    priority: 74,
    q: "Proposez-vous des services pour les langues rares ou non répertoriées ?",
    a: "Nous nous efforçons de proposer aussi les langues rares ; toutefois, la disponibilité d'un traducteur, le délai et le prix sont confirmés séparément pour ces langues. Si la langue recherchée ne figure pas dans la liste, contactez notre service client pour obtenir un devis sur mesure.",
    keywords: ["langue rare", "langue peu courante", "langue non répertoriée", "langue spéciale"],
  },
  {
    id: "dil-varyantlari",
    category: "languages",
    priority: 75,
    q: "Peut-on choisir une variante régionale d'une langue (anglais américain ou britannique par exemple) ?",
    a: "Oui, lorsque c'est possible, vous pouvez préciser une variante régionale de la langue cible (par ex. anglais américain/britannique, espagnol d'Europe/d'Amérique latine). En l'absence de variante précisée, le standard courant est utilisé.",
    keywords: ["variante", "anglais américain", "langue régionale", "dialecte"],
  },
  {
    id: "anadili-tercuman",
    category: "languages",
    priority: 76,
    q: "Travaillez-vous avec des traducteurs de langue maternelle dans la langue cible ?",
    a: "Dans la mesure du possible, nous travaillons avec des traducteurs expérimentés et parfaitement à l'aise dans la langue cible. L'objectif est d'obtenir une traduction naturelle et fidèle.",
    keywords: ["traducteur langue maternelle", "locuteur natif", "expert langue cible"],
  },
  {
    id: "osmanlica-eski-yazi",
    category: "languages",
    priority: 77,
    q: "Les documents en turc ottoman ou en ancienne écriture peuvent-ils être traduits ?",
    a: "Les documents en turc ottoman et rédigés dans l'ancien alphabet peuvent être traduits, sous réserve de la disponibilité d'un spécialiste. Pour ce type de documents, le délai et le prix sont confirmés après examen.",
    keywords: ["turc ottoman", "ancienne écriture", "ancien alphabet"],
  },
  {
    id: "karisik-dilli-belge",
    category: "languages",
    priority: 78,
    q: "Un document contenant plusieurs langues peut-il être traduit ?",
    a: "Oui. Les documents multilingues peuvent être traduits ; le prix est établi selon la quantité de contenu dans chaque langue. Il vous suffit d'indiquer la langue cible souhaitée.",
    keywords: ["langues mêlées", "document multilingue", "plusieurs langues dans un document"],
  },

  // ——— TYPES DE SERVICES ———
  {
    id: "hangi-hizmeti-secmeliyim",
    category: "services",
    priority: 79,
    q: "Quel type de service dois-je choisir ?",
    a: "L'usage prévu de votre document détermine le service : les démarches officielles requièrent le plus souvent une traduction assermentée, tandis que certaines procédures exigent une traduction avec certification notariée ou apostille. En cas de doute, notre service client ou notre assistant de chat vous oriente ; l'exigence finale dépend de l'organisme concerné.",
    keywords: ["quel service", "choix du service", "que choisir"],
  },
  {
    id: "standart-yeminli-fark",
    category: "services",
    priority: 80,
    q: "Quelle est la différence entre une traduction standard et une traduction assermentée ?",
    a: "Une traduction standard est destinée à l'information et ne comporte aucune certification officielle. Une traduction assermentée est certifiée par le cachet et la signature du traducteur assermenté et est exigée pour les démarches officielles. Le type requis dépend de l'organisme auquel le document sera présenté.",
    keywords: ["standard ou assermentée", "différence", "traduction ordinaire", "différence assermentée"],
  },
  {
    id: "yeminli-noter-ayni-mi",
    category: "services",
    priority: 81,
    q: "Une traduction assermentée et une traduction avec certification notariée sont-elles la même chose ?",
    a: "Non. Une traduction assermentée porte la certification du traducteur assermenté. Une traduction avec certification notariée est cette même traduction, en outre certifiée par un notaire. Certains organismes n'exigent qu'une traduction assermentée, tandis que d'autres demandent également la certification notariée.",
    keywords: ["assermentée ou notariée", "traduction notariée", "est-ce la même chose"],
  },
  {
    id: "hukuki-teknik-medikal",
    category: "services",
    priority: 82,
    q: "Comment l'expertise est-elle assurée pour les traductions juridiques, techniques et médicales ?",
    a: "Les contrats, documents judiciaires, documentations techniques et documents médicaux sont traduits par des traducteurs expérimentés maîtrisant la terminologie du domaine concerné. Des glossaires terminologiques et une mémoire de traduction garantissent la cohérence, les formats et les unités sont conservés, et la traduction passe par un contrôle qualité.",
    keywords: ["traduction juridique", "traduction technique", "traduction médicale", "traducteur spécialisé", "terminologie"],
  },
  {
    id: "akademik-bicim-korunur",
    category: "services",
    priority: 83,
    q: "La bibliographie et la mise en forme sont-elles conservées en traduction académique ?",
    a: "Oui. Pour les thèses, articles et textes académiques, la présentation de la bibliographie, les citations et la mise en forme sont conservées autant que possible, et la traduction respecte le style académique.",
    keywords: ["traduction académique", "thèse", "article", "bibliographie", "citations"],
  },
  {
    id: "lokalizasyon-nedir",
    category: "services",
    priority: 84,
    q: "La localisation se limite-t-elle à une traduction mot à mot ? Le SEO est-il pris en compte ?",
    a: "Non. La localisation consiste à adapter le texte à la culture et à l'usage cibles ; l'interface, les formats de date et de devise ainsi que le ton sont ajustés au public visé. Pour la localisation de sites web, les mots-clés dans la langue cible et l'optimisation SEO peuvent être pris en compte sur demande.",
    keywords: ["localisation", "traduction de site web", "traduction d'application", "seo", "adaptation"],
  },
  {
    id: "kurumsal-marka-dili",
    category: "services",
    priority: 85,
    q: "Le langage de marque est-il préservé dans les contenus d'entreprise ?",
    a: "Oui. Pour les traductions d'entreprise, une banque terminologique et un guide de style permettent de préserver la cohérence de votre langage de marque et de votre ton.",
    keywords: ["langage de marque", "ton de l'entreprise", "guide de style"],
  },
  {
    id: "vize-diploma-hangi-hizmet",
    category: "services",
    priority: 86,
    q: "Quel service faut-il pour des documents tels qu'un visa ou un diplôme ?",
    a: "Pour les demandes de visa et les traductions de diplômes, une traduction assermentée constitue le plus souvent l'exigence de base ; certaines représentations ou certains organismes peuvent en outre demander une certification notariée ou une apostille. L'exigence exacte dépend du consulat ou de l'organisme auprès duquel vous effectuez votre démarche.",
    keywords: ["document de visa", "traduction de diplôme", "relevé de notes", "consulat", "traduction visa"],
  },
  {
    id: "belge-turu-listede-yok",
    category: "services",
    priority: 87,
    q: "Que choisir si mon type de document ne figure pas dans la liste ?",
    a: "Si votre type de document ne figure pas dans la liste, sélectionnez l'option la plus proche et ajoutez une précision dans la note de commande. Si vous le souhaitez, notre service client vous aide à faire le bon choix.",
    keywords: ["type de document absent", "autre document", "hors liste"],
  },

  // ——— LIVRAISON ET DÉLAIS ———
  {
    id: "teslim-suresi-nasil-hesaplanir",
    category: "delivery",
    priority: 88,
    q: "Comment le délai de livraison est-il calculé et où est-il indiqué ?",
    a: "Le délai est calculé en fonction de la longueur du document, de la paire de langues, du type de service et des services complémentaires, et il est indiqué comme date de livraison estimée sur l'écran Calculer le prix. Pour les démarches nécessitant une certification notariée ou une apostille, des jours supplémentaires peuvent s'ajouter ; si la date de livraison change, vous en êtes informé.",
    keywords: ["calcul du délai", "livraison estimée", "quand prêt"],
  },
  {
    id: "ayni-gun-teslimat",
    category: "delivery",
    priority: 89,
    q: "Une livraison le jour même ou sous 24 heures est-elle possible ?",
    a: "Pour les documents courts, une livraison rapide/express est souvent possible ; la disponibilité dépend de la longueur et de la langue du document. Les étapes de contrôle qualité sont maintenues, même en livraison express, et l'option apparaît comme une ligne supplémentaire sur l'écran du devis préliminaire.",
    keywords: ["le jour même", "24 heures", "livraison rapide", "urgent"],
  },
  {
    id: "hafta-sonu-tatil",
    category: "delivery",
    priority: 90,
    q: "Quand les commandes du week-end ou hors heures ouvrables sont-elles traitées ?",
    a: "Vous pouvez téléverser des documents, obtenir des devis et créer des commandes à toute heure. Les commandes passées en dehors des heures ouvrables ou les jours fériés sont traitées dès le début des heures ouvrables suivantes, et le délai estimé est indiqué en conséquence.",
    keywords: ["week-end", "jour férié", "hors heures ouvrables", "commande de nuit"],
  },
  {
    id: "dijital-teslim-format",
    category: "delivery",
    priority: 91,
    q: "Comment se fait la livraison numérique et dans quel format vais-je la recevoir ?",
    a: "La traduction finalisée est livrée au format numérique via un lien de téléchargement ou par e-mail. Vous pouvez la recevoir au format PDF ou Word (DOCX) modifiable selon vos besoins ; la mise en forme d'origine est conservée autant que possible.",
    keywords: ["livraison numérique", "livraison word", "livraison pdf", "téléchargement"],
  },
  {
    id: "kargo-kapsam-takip",
    category: "delivery",
    priority: 92,
    q: "Vers quelles régions expédiez-vous et puis-je suivre l'envoi ?",
    a: "Les documents portant une signature manuscrite originale et un cachet sont expédiés par voie postale dans toute la Turquie ; sur demande, nous pouvons aussi expédier à l'international. Les informations de suivi de l'envoi vous sont communiquées et le délai d'acheminement s'ajoute au délai de livraison total.",
    keywords: ["régions d'expédition", "suivi de l'envoi", "expédition internationale", "délai d'acheminement"],
  },
  {
    id: "kismi-teslimat",
    category: "delivery",
    priority: 93,
    q: "Les projets longs peuvent-ils être livrés par parties ?",
    a: "Oui. Les projets volumineux ou longs peuvent être livrés par sections sur demande. Vous pouvez ainsi commencer à utiliser vos documents sans attendre.",
    keywords: ["livraison partielle", "par parties", "livraison par sections"],
  },

  // ——— TRADUCTION ASSERMENTÉE ———
  {
    id: "yeminli-tercuman-kim",
    category: "sworn",
    priority: 94,
    q: "Qu'est-ce qu'un traducteur assermenté ?",
    a: "Un traducteur assermenté est un traducteur ayant prêté serment devant un notaire et ayant ainsi obtenu le pouvoir de certifier ses traductions au moyen de sa signature et de son cachet. Cette certification atteste que la traduction est fidèle à l'original.",
    keywords: ["traducteur assermenté", "qui est traducteur assermenté", "traducteur certifié"],
  },
  {
    id: "yeminli-ne-zaman-gerekli",
    category: "sworn",
    priority: 95,
    q: "Quand une traduction assermentée est-elle exigée ?",
    a: "Les traductions assermentées sont fréquemment exigées pour les démarches auprès des organismes officiels, des tribunaux, des consulats et des universités. Elles ne sont toutefois pas obligatoires pour tous les documents ; l'exigence exacte est fixée par l'organisme qui demande le document.",
    keywords: ["quand assermentée exigée", "assermentée nécessaire", "où exigée"],
  },
  {
    id: "yeminli-nerede-gecerli",
    category: "sworn",
    priority: 96,
    q: "Une traduction assermentée est-elle valable devant un tribunal, un consulat et à l'étranger ?",
    a: "Une traduction assermentée peut être utilisée pour de nombreuses démarches et procédures officielles. Toutefois, les conditions d'acceptation d'un document par un organisme dépendent de sa propre réglementation ; à l'étranger notamment, une certification notariée ou une apostille peut également être exigée. Nous vous recommandons de confirmer les conditions d'acceptation auprès de l'organisme concerné.",
    keywords: ["tribunal", "consulat", "valable à l'étranger", "demande universitaire"],
  },
  {
    id: "dijital-imzali-yeminli",
    category: "sworn",
    priority: 97,
    q: "Une traduction assermentée peut-elle être établie avec une signature numérique/électronique ?",
    a: "Non. Une traduction assermentée est établie avec la signature manuscrite originale et le cachet du traducteur, et elle est livrée physiquement par voie postale.",
    keywords: ["signature électronique", "assermentée numérique", "signature numérique", "signature manuscrite originale", "cachet"],
  },
  {
    id: "yeminli-orijinal-gerekir",
    category: "sworn",
    priority: 98,
    q: "L'original du document est-il nécessaire pour une traduction assermentée ?",
    a: "La traduction peut généralement être réalisée à partir d'une copie nette du document (scan ou photo). Toutefois, si une certification notariée est requise, l'original ou une copie certifiée conforme du document peut être demandé pour cette démarche.",
    keywords: ["document original", "original nécessaire", "copie pour assermentée"],
  },
  {
    id: "yeminli-gecerlilik-suresi",
    category: "sworn",
    priority: 99,
    q: "Une traduction assermentée a-t-elle une date d'expiration ?",
    a: "La traduction elle-même n'est pas limitée dans le temps ; certains organismes peuvent toutefois demander un document de date récente. Cela dépend des exigences de l'organisme qui acceptera le document.",
    keywords: ["date d'expiration", "validité assermentée", "durée de validité"],
  },
  {
    id: "kurum-belgeyi-kabul-etmezse",
    category: "sworn",
    priority: 100,
    q: "Que faire si un organisme n'accepte pas la traduction assermentée ?",
    a: "Les conditions d'acceptation peuvent varier d'un organisme à l'autre. Si l'organisme a une exigence particulière de format ou de certification, faites-le-nous savoir et nous procéderons aux ajustements nécessaires. La décision finale d'acceptation appartient à l'organisme.",
    keywords: ["non accepté", "refus de l'organisme", "exigence de format"],
  },

  // ——— CERTIFICATION NOTARIÉE ET APOSTILLE ———
  {
    id: "noter-onayli-nedir",
    category: "notary",
    priority: 101,
    q: "Qu'est-ce qu'une traduction avec certification notariée ?",
    a: "Une traduction avec certification notariée est une traduction assermentée en outre certifiée par un notaire. Cette certification renforce la validité officielle de la traduction et est exigée par certains organismes.",
    keywords: ["traduction notariée", "certification notariée", "définition notariée"],
  },
  {
    id: "noter-yeminli-fark",
    category: "notary",
    priority: 102,
    q: "Quelle est la différence entre la certification notariée et une traduction assermentée ?",
    a: "Une traduction assermentée porte la certification du traducteur, tandis que la certification notariée correspond à la certification de cette traduction par un notaire. La certification notariée est une étape officielle supplémentaire ajoutée à une traduction assermentée.",
    keywords: ["notaire ou assermentée", "différence de certification"],
  },
  {
    id: "notere-gitmem-gerekir-mi",
    category: "notary",
    priority: 103,
    q: "Dois-je me rendre chez le notaire pour la certification notariée ?",
    a: "Dans la plupart des cas, nous pouvons effectuer la certification notariée en votre nom, sans que vous ayez à vous rendre chez le notaire en personne. Si l'original du document est requis, nous vous en informons à l'avance.",
    keywords: ["aller chez le notaire", "démarche notariée", "notaire en mon nom"],
  },
  {
    id: "apostil-nedir",
    category: "notary",
    priority: 104,
    q: "Qu'est-ce qu'une apostille et en quoi diffère-t-elle de la certification notariée ?",
    a: "L'apostille est une certification internationale délivrée par l'autorité compétente afin qu'un document officiel soit reconnu valable dans un autre pays, et elle s'applique entre les pays parties à la Convention de La Haye. La certification notariée, en revanche, est une certification au sein d'un même pays ; les deux répondent à des finalités différentes.",
    keywords: ["définition apostille", "apostille ou notaire", "convention de la haye"],
  },
  {
    id: "apostil-once-mi-ceviri-once-mi",
    category: "notary",
    priority: 105,
    q: "Que fait-on en premier : l'apostille ou la traduction ?",
    a: "L'ordre dépend du type de document et des exigences du pays où il sera utilisé. Dans certains cas, le document est d'abord apostillé puis traduit ; dans d'autres, c'est l'inverse. Nous pouvons déterminer ensemble le bon ordre.",
    keywords: ["ordre de l'apostille", "traduction ou apostille d'abord", "séquence"],
  },
  {
    id: "yabanci-belge-turkiye",
    category: "notary",
    priority: 106,
    q: "Quelle est la procédure si un document étranger doit être utilisé en Turquie ?",
    a: "Un document provenant de l'étranger est généralement d'abord apostillé dans le pays d'origine, puis fait l'objet d'une traduction assermentée (et d'une certification notariée si nécessaire) en Turquie. La procédure exacte dépend de l'organisme turc qui demande le document.",
    keywords: ["document étranger en turquie", "document entrant", "document venant de l'étranger"],
  },
  {
    id: "turk-belge-yurt-disi",
    category: "notary",
    priority: 107,
    q: "Quelle est la procédure si un document turc doit être utilisé à l'étranger ?",
    a: "Un document établi en Turquie est généralement apostillé et fait l'objet d'une traduction assermentée vers la langue cible. Si le pays de destination n'est pas partie à la Convention de La Haye, une légalisation consulaire peut être exigée à la place de l'apostille.",
    keywords: ["document turc à l'étranger", "document sortant", "légalisation consulaire"],
  },
  {
    id: "hangi-onay-gerekli-bilinmiyor",
    category: "notary",
    priority: 109,
    q: "Comment savoir si une certification notariée ou une apostille est nécessaire ?",
    a: "Le moyen le plus fiable est d'interroger l'organisme qui demande le document. Si vous le souhaitez, notre service client peut vous renseigner sur les pratiques courantes ; mais l'exigence exacte varie selon l'organisme et le pays.",
    keywords: ["quelle certification", "certification nécessaire", "notaire ou apostille"],
  },
  {
    id: "kesin-kabul-garantisi",
    category: "notary",
    priority: 110,
    q: "TercümExpert garantit-il l'acceptation ?",
    a: "Nous veillons à ce que la traduction et les certifications soient préparées de façon exacte et complète ; toutefois, les conditions d'acceptation d'un document sont fixées par l'organisme qui le demande. Pour cette raison, nous ne pouvons offrir de garantie d'acceptation inconditionnelle ; si vous nous communiquez les exigences particulières de l'organisme, nous procéderons aux ajustements nécessaires.",
    keywords: ["garantie d'acceptation", "acceptation garantie", "garantie"],
  },

  // ——— QUALITÉ ET RÉVISIONS ———
  {
    id: "tercumanlar-nasil-secilir",
    category: "quality",
    priority: 111,
    q: "Comment les traducteurs sont-ils sélectionnés et leur expertise déterminée ?",
    a: "Les traducteurs sont choisis en fonction de la paire de langues et du domaine de spécialité du document ; un document juridique est confié à un traducteur expérimenté en droit, un document médical à un traducteur expérimenté dans la santé. Le traducteur le plus adapté est affecté en tenant compte de l'expérience dans le domaine et de la maîtrise linguistique.",
    keywords: ["sélection des traducteurs", "comment les traducteurs sont choisis", "expertise", "spécialiste du domaine"],
  },
  {
    id: "kalite-kontrol",
    category: "quality",
    priority: 112,
    q: "La traduction passe-t-elle par un contrôle qualité ?",
    a: "Oui. Les traductions sont vérifiées sur les plans de l'orthographe, de la terminologie, de la cohérence des chiffres/noms/dates et de la mise en forme. Selon le type de document et le niveau de service, une étape de relecture/révision indépendante peut être appliquée.",
    keywords: ["contrôle qualité", "relecture", "relecteur", "révision"],
  },
  {
    id: "ceviri-bellegi",
    category: "quality",
    priority: 113,
    q: "Utilisez-vous une mémoire de traduction ou des listes terminologiques ?",
    a: "Oui, en particulier pour les projets techniques et d'entreprise, une mémoire de traduction et des listes terminologiques sont utilisées pour garantir la cohérence. Vous pouvez également partager votre propre liste de termes ; la terminologie des projets antérieurs est conservée.",
    keywords: ["mémoire de traduction", "liste terminologique", "cohérence"],
  },
  {
    id: "revize-kapsami",
    category: "quality",
    priority: 114,
    q: "Que couvre une révision et quand faut-il la demander ?",
    a: "Une révision couvre des points tels que les erreurs de traduction, l'orthographe, les incohérences et les omissions. Modifier le texte source a posteriori ou ajouter du nouveau contenu peut être considéré comme un nouveau travail. Nous vous recommandons d'adresser votre demande de révision dans un délai raisonnable après la livraison, par e-mail ou WhatsApp.",
    keywords: ["portée de la révision", "portée des corrections", "délai de révision", "quand réviser"],
  },
  {
    id: "tercuman-degisikligi",
    category: "quality",
    priority: 115,
    q: "Que se passe-t-il si je ne suis pas satisfait de la traduction — le traducteur peut-il être changé ?",
    a: "Si vous n'êtes pas satisfait de la traduction, nous examinons la situation et, si nécessaire, organisons des corrections avec un autre traducteur ou relecteur. L'objectif est que le résultat réponde à vos attentes.",
    keywords: ["changer de traducteur", "non satisfait", "insatisfait de la traduction"],
  },
  {
    id: "dogruluk-garanti",
    category: "quality",
    priority: 116,
    q: "L'exactitude de la traduction est-elle garantie ?",
    a: "Vos traductions sont réalisées par des traducteurs experts et passent par un contrôle qualité, et nous apportons tout le soin nécessaire à leur exactitude. Cela étant, les conditions officielles d'acceptation d'un document peuvent varier selon l'organisme qui le demande.",
    keywords: ["garantie d'exactitude", "garantie de qualité", "assurance"],
  },
  {
    id: "makine-cevirisi-kullaniliyor",
    category: "quality",
    priority: 117,
    q: "Utilisez-vous une traduction entièrement automatisée/automatique ?",
    a: "Non. Les traductions sont réalisées de bout en bout par des traducteurs humains professionnels ; nous ne proposons pas de traduction automatique. Seuls des outils de TAO sont utilisés pour renforcer la cohérence. Les traductions assermentées comportent le cachet, la signature et l'attestation de conformité à l'original du traducteur.",
    keywords: ["traduction automatique", "traduction machine", "traduction par ia", "attestation de conformité"],
  },

  // ——— CONFIDENTIALITÉ ET SÉCURITÉ ———
  {
    id: "dosyalari-kimler-gorur",
    category: "privacy",
    priority: 118,
    q: "Qui peut consulter les fichiers téléversés et sont-ils communiqués à des tiers ?",
    a: "Seuls le traducteur et l'équipe concernée en charge de votre commande peuvent accéder à vos fichiers. Sauf lorsque la prestation l'exige, vos documents ne sont jamais communiqués à des tiers ni utilisés à des fins de marketing.",
    keywords: ["qui peut voir", "accès", "tiers", "partage"],
  },
  {
    id: "nda-imzalanabilir",
    category: "privacy",
    priority: 119,
    q: "Peut-on signer un accord de confidentialité (NDA) ?",
    a: "Oui. En particulier pour les projets d'entreprise, un accord de confidentialité (NDA) peut être établi sur demande. Nos traducteurs sont eux aussi soumis à des obligations de confidentialité.",
    keywords: ["nda", "accord de confidentialité", "clause de confidentialité"],
  },
  {
    id: "kvkk-uyumlu",
    category: "privacy",
    priority: 120,
    q: "Travaillez-vous en conformité avec la KVKK et comment les données personnelles sont-elles protégées ?",
    a: "Oui. Vos données personnelles sont traitées selon des procédures conformes à la KVKK (loi turque sur la protection des données) ; elles ne sont utilisées que dans la mesure nécessaire à la prestation et sont conservées de manière sécurisée. Nous nous engageons à protéger vos données par des mesures de sécurité appropriées.",
    keywords: ["kvkk", "données personnelles", "protection des données", "conforme kvkk"],
  },
  {
    id: "sifreli-aktarim",
    category: "privacy",
    priority: 121,
    q: "Les fichiers sont-ils transférés de manière chiffrée ?",
    a: "Oui. Vos fichiers sont transférés via une connexion chiffrée et traités dans un environnement sécurisé. Notre objectif est de protéger vos données par des mesures de sécurité appropriées.",
    keywords: ["chiffré", "transfert sécurisé", "chiffrement"],
  },
  {
    id: "odeme-bilgileri-saklanir",
    category: "privacy",
    priority: 122,
    q: "Les informations de paiement/carte bancaire sont-elles conservées ?",
    a: "Les informations de votre carte ne sont pas conservées par TercümExpert ; les paiements sont traités via une infrastructure de paiement sécurisée.",
    keywords: ["informations de paiement", "sécurité carte bancaire", "conservation de la carte"],
  },
  {
    id: "belgeler-ai-egitimi",
    category: "privacy",
    priority: 123,
    q: "Mes documents sont-ils utilisés pour l'entraînement de modèles ?",
    a: "Non. Vos documents ne sont utilisés que pour votre commande ; ils ne sont jamais partagés à des fins d'entraînement de modèles ni avec des systèmes externes. Votre traduction est réalisée par des traducteurs humains dans le respect de la confidentialité.",
    keywords: ["entraînement de modèles", "utilisation des données", "entraînement ia", "confidentialité des documents"],
  },
  {
    id: "saglik-kimlik-guvenli",
    category: "privacy",
    priority: 124,
    q: "Les documents sensibles comme les pièces d'identité, passeports ou dossiers médicaux sont-ils en sécurité ?",
    a: "Oui. Tous vos fichiers, y compris les documents sensibles, sont traités dans le respect de la confidentialité, de manière conforme à la KVKK et chiffrée. L'accès est limité à l'équipe en charge de votre commande ; pour les documents hautement confidentiels, des mesures supplémentaires telles qu'un NDA et un accès restreint peuvent être appliquées.",
    keywords: ["sécurité pièce d'identité", "passeport", "données de santé", "document sensible"],
  },
  {
    id: "hesap-silinince-belgeler",
    category: "privacy",
    priority: 125,
    q: "Les documents sont-ils supprimés à la clôture d'un compte ou sur demande ?",
    a: "Sur votre demande, vos documents et vos données personnelles sont supprimés, sous réserve d'éventuelles obligations légales de conservation. Vous pouvez adresser une demande de suppression de compte ou de données à notre service client.",
    keywords: ["suppression de compte", "suppression des données", "supprimer les documents"],
  },

  // ——— SERVICES AUX ENTREPRISES ———
  {
    id: "kurumsal-hesap-nasil",
    category: "corporate",
    priority: 126,
    q: "Comment ouvrir un compte entreprise et que se passe-t-il après ma demande ?",
    a: "Il vous suffit de remplir le formulaire de demande sur notre page Entreprises ; notre équipe vous recontacte généralement sous 1 jour ouvrable, évalue vos besoins et met en place des conditions adaptées à votre situation.",
    keywords: ["compte entreprise", "compte société", "demande entreprise", "après la demande"],
  },
  {
    id: "sirket-adina-siparis",
    category: "corporate",
    priority: 127,
    q: "Peut-on passer une commande au nom d'une entreprise ?",
    a: "Oui. Vous pouvez passer commande avec les coordonnées de votre entreprise et bénéficier de la facturation professionnelle et, au besoin, des options de délai de paiement.",
    keywords: ["au nom d'une entreprise", "commande professionnelle", "commande société"],
  },
  {
    id: "ozel-hesap-yoneticisi",
    category: "corporate",
    priority: 128,
    q: "Les clients professionnels se voient-ils attribuer un gestionnaire de compte dédié ?",
    a: "Les clients professionnels peuvent se voir attribuer un gestionnaire de compte dédié qui assure le suivi de leurs projets. Vous pouvez ainsi gérer vos demandes depuis un point de contact unique et bénéficier d'une assistance prioritaire.",
    keywords: ["gestionnaire de compte", "gestionnaire dédié", "assistance entreprise", "assistance prioritaire"],
  },
  {
    id: "toplu-fatura",
    category: "corporate",
    priority: 129,
    q: "Peut-on bénéficier d'une facturation mensuelle regroupée et d'un délai de paiement ?",
    a: "Oui. Les clients professionnels peuvent bénéficier d'une facturation mensuelle regroupée et d'un délai de paiement pouvant aller jusqu'à 15 à 30 jours. Les modalités sont définies dans le cadre de l'accord.",
    keywords: ["facturation regroupée", "facture mensuelle", "délai de paiement", "paiement entreprise"],
  },
  {
    id: "terminoloji-bankasi",
    category: "corporate",
    priority: 130,
    q: "Peut-on créer une banque terminologique propre à l'entreprise ?",
    a: "Oui. Pour les projets d'entreprise, une banque terminologique et un guide de style propres à votre marque sont créés afin de préserver votre langage de marque et sa cohérence dans toutes les traductions.",
    keywords: ["banque terminologique", "guide de style", "terminologie d'entreprise"],
  },
  {
    id: "sabit-tercuman",
    category: "corporate",
    priority: 131,
    q: "Peut-on travailler avec les mêmes traducteurs sur des projets récurrents ?",
    a: "Oui. Pour les projets d'entreprise récurrents, un pool de traducteurs/une équipe dédiée peut être mis en place afin d'assurer continuité et cohérence.",
    keywords: ["traducteur dédié", "même équipe", "équipe entreprise"],
  },
  {
    id: "kurumsal-raporlama",
    category: "corporate",
    priority: 132,
    q: "Peut-on obtenir des rapports de commandes et de dépenses ?",
    a: "Les clients professionnels peuvent bénéficier d'un reporting de leurs commandes et de leurs dépenses, avec une ventilation par service si nécessaire. Pour les partenariats d'entreprise, des accords de niveau de service (SLA) et de confidentialité (NDA) peuvent également être établis.",
    keywords: ["reporting", "rapport de dépenses", "rapport de commandes", "sla"],
  },
  {
    id: "kucuk-isletme",
    category: "corporate",
    priority: 133,
    q: "Les petites entreprises peuvent-elles bénéficier des services aux entreprises et un volume minimum est-il requis ?",
    a: "Oui. Aucune condition de taille ou de volume minimum n'est requise pour bénéficier de nos services aux entreprises ; les petites entreprises peuvent elles aussi profiter d'avantages tels que le délai de paiement, la gestion terminologique et l'assistance prioritaire.",
    keywords: ["petite entreprise", "pme", "volume minimum", "volume requis"],
  },
  {
    id: "uluslararasi-sirket",
    category: "corporate",
    priority: 134,
    q: "Servez-vous les entreprises internationales et les projets multilingues ?",
    a: "Oui. Les projets couvrant plusieurs pays et plusieurs langues peuvent être coordonnés et pilotés de manière centralisée, avec une cohérence terminologique assurée sur l'ensemble. Pour les projets d'entreprise, la traduction assermentée et, au besoin, les procédures de certification notariée peuvent également être prises en charge.",
    keywords: ["entreprise internationale", "projet multilingue", "notaire apostille entreprise"],
  },

  // ——— ASSISTANCE TECHNIQUE ———
  {
    id: "nasil-uye-olunur",
    category: "support",
    priority: 135,
    q: "Comment s'inscrire sur le site ?",
    a: "Pour vous inscrire, il vous suffit de saisir vos nom, prénom et adresse e-mail, puis de confirmer le code de vérification reçu par e-mail. Vous pouvez également vous inscrire rapidement avec votre compte Apple ou Google.",
    keywords: ["s'inscrire", "inscription", "créer un compte"],
  },
  {
    id: "giris-sifre-sorunu",
    category: "support",
    priority: 136,
    q: "Que faire si je ne parviens pas à me connecter ou si j'oublie mon mot de passe ?",
    a: "Vérifiez d'abord votre adresse e-mail et votre mot de passe ; si vous avez oublié votre mot de passe, utilisez le lien « Mot de passe oublié » de l'écran de connexion pour recevoir par e-mail les instructions de réinitialisation. Si le problème persiste, vérifiez votre dossier de courriers indésirables ou contactez notre service client.",
    keywords: ["impossible de se connecter", "réinitialiser le mot de passe", "mot de passe oublié", "connexion", "identifiant"],
  },
  {
    id: "dogrulama-epostasi-gelmezse",
    category: "support",
    priority: 137,
    q: "Que faire si l'e-mail de vérification n'arrive pas ?",
    a: "Patientez quelques minutes, vérifiez votre dossier de courriers indésirables et renvoyez le code. Assurez-vous d'avoir saisi correctement votre adresse e-mail ; si le problème persiste, contactez notre service client.",
    keywords: ["e-mail de vérification", "code non reçu", "e-mail n'arrive pas", "code de vérification"],
  },
  {
    id: "dosya-yuklenmiyor",
    category: "support",
    priority: 138,
    q: "Que faire si un fichier ne se téléverse pas ou si j'obtiens une erreur de fichier non pris en charge ?",
    a: "Vérifiez la taille du fichier (jusqu'à 100 Mo) et son format, puis actualisez la page et votre navigateur. Si le format n'est pas pris en charge, convertissez le fichier vers un format tel que PDF ou DOCX, ou collez le texte dans l'onglet « Saisir le texte ». Si le problème persiste, contactez notre service client.",
    keywords: ["fichier ne se téléverse pas", "erreur de téléversement", "fichier non pris en charge", "erreur de format"],
  },
  {
    id: "kelime-sayisi-yanlis",
    category: "support",
    priority: 139,
    q: "Que faire si le nombre de mots semble incorrect ?",
    a: "Le comptage automatique peut être faussé, surtout pour les documents numérisés ou en image. Pour un résultat exact, partagez le texte via « Saisir le texte » ou ajoutez une note à votre commande ; le nombre final est confirmé par notre équipe et le prix est établi en conséquence.",
    keywords: ["nombre de mots incorrect", "erreur de comptage", "comptage erroné"],
  },
  {
    id: "odeme-basarisiz",
    category: "support",
    priority: 140,
    q: "Que faire si un paiement échoue ou si je suis débité deux fois ?",
    a: "Vérifiez les informations et le plafond de votre carte, puis réessayez ; vous pouvez aussi utiliser un autre moyen (carte/virement). Si le montant a été débité sans qu'une commande soit créée, ou en cas de double débit, contactez notre service client avec votre reçu : le montant excédentaire sera remboursé.",
    keywords: ["paiement échoué", "erreur de paiement", "débité deux fois", "double débit"],
  },
  {
    id: "teslim-dosyasi-inmiyor",
    category: "support",
    priority: 141,
    q: "Que faire si le fichier livré ne se télécharge pas ?",
    a: "Actualisez le lien et votre navigateur ; si le lien de téléchargement a expiré, vous pouvez en demander un nouveau à notre service client.",
    keywords: ["fichier ne se télécharge pas", "problème de téléchargement", "téléchargement impossible", "lien expiré"],
  },
  {
    id: "mobil-tarayici-destegi",
    category: "support",
    priority: 142,
    q: "Peut-on utiliser le site sur un appareil mobile et quels navigateurs sont pris en charge ?",
    a: "Le site est adapté aux mobiles ; vous pouvez téléverser des documents et passer commande depuis un iPhone, un téléphone Android ou une tablette. Vous pouvez utiliser le site sans difficulté avec les versions récentes de Chrome, Safari, Edge et Firefox.",
    keywords: ["mobile", "téléphone", "iphone android", "tablette", "navigateur", "chrome safari"],
  },
  {
    id: "ai-asistan-ne-yapar",
    category: "support",
    priority: 143,
    q: "Que peut faire l'assistant de chat propulsé par l'IA ?",
    a: "L'assistant de chat fournit une orientation immédiate sur le processus, les types de services et les questions générales, et vous dirige vers les bonnes étapes, comme l'obtention d'un devis. Il ne peut pas prendre de décision définitive ou contraignante concernant les conditions officielles d'acceptation ou les exigences légales (comme la certification notariée ou l'apostille) ; pour ces points, vous devez consulter l'organisme concerné.",
    keywords: ["assistant de chat", "chatbot", "assistant ia", "tarif chatbot"],
  },
  {
    id: "insana-baglanma",
    category: "support",
    priority: 144,
    q: "Comment joindre un conseiller clientèle humain ?",
    a: "Vous pouvez en faire la demande via l'assistant de chat, ou joindre directement notre service client humain par WhatsApp et par e-mail. Les demandes sont traitées pendant les heures ouvrables. Transmettre les problèmes techniques avec une capture d'écran accélère leur résolution.",
    keywords: ["joindre un humain", "conseiller clientèle", "assistance en direct", "capture d'écran"],
  },
  {
    id: "hesap-bilgileri-guncelleme",
    category: "support",
    priority: 145,
    q: "Comment mettre à jour les informations de compte et de facturation, et comment supprimer mon compte ?",
    a: "Si vous avez un compte, vous pouvez mettre à jour votre téléphone, votre adresse e-mail et vos informations de facturation dans les paramètres de votre compte, et vous pouvez également y demander la suppression de votre compte ou en faire la demande auprès de notre service client. Sur votre demande, vos données sont supprimées, sous réserve d'éventuelles obligations légales.",
    keywords: ["mettre à jour les informations", "informations de facturation", "paramètres du compte", "supprimer le compte"],
  },
  {
    id: "bildirim-tercihleri",
    category: "support",
    priority: 146,
    q: "Comment fonctionnent les notifications de commande et peut-on recevoir des notifications WhatsApp ?",
    a: "Des notifications par e-mail sont envoyées pour l'état de votre commande ; selon vos préférences, des mises à jour peuvent également être fournies via WhatsApp. Vous pouvez ajuster vos préférences de notification dans les paramètres de votre compte ou auprès de notre service client.",
    keywords: ["notifications", "sms", "notification whatsapp", "notification e-mail", "notification de commande"],
  },
]
