/**
 * SSS-lərin məlumat mənbəyi (Azərbaycan dili). Qiymət/ödəniş məntiqi sonradan
 * dəyişə bilər (§13). Dürüstlük qaydaları: təsdiqlənməmiş ISO/sertifikat iddiası
 * YOX; fiziki ofisin mövcudluğu ima edilmir; 7/24 canlı dəstək vəd edilmir;
 * andlı tərcümə / notariat təsdiqi / apostil fərqləri qorunur; qurum tərəfindən
 * qəbul üçün qəti zəmanət verilmir.
 * `priority` = qlobal əhəmiyyət sırası (kiçik = yuxarıda). Kateqoriya görünüşündə
 * də eyni sıra istifadə olunduğu üçün kateqoriya daxili sıralama bu dəyərdən çıxır.
 */
import type { FaqCategory, FaqItem } from './faq-data'

export const FAQ_CATEGORIES_AZ: FaqCategory[] = [
  { key: "general", label: "Ümumi" },
  { key: "order", label: "Sifariş Prosesi" },
  { key: "pricing", label: "Qiymətləndirmə və Ödəniş" },
  { key: "upload", label: "Fayl Yükləmə" },
  { key: "languages", label: "Dillər və Dil Cütləri" },
  { key: "services", label: "Xidmət Növləri" },
  { key: "delivery", label: "Təhvil və Müddət" },
  { key: "sworn", label: "Andlı Tərcümə" },
  { key: "notary", label: "Notariat və Apostil" },
  { key: "quality", label: "Keyfiyyət və Düzəliş" },
  { key: "privacy", label: "Məxfilik və Təhlükəsizlik" },
  { key: "corporate", label: "Korporativ Xidmətlər" },
  { key: "support", label: "Texniki Dəstək" },
]

export const FAQ_ITEMS_AZ: FaqItem[] = [
  // ——— HAMISI: müştəri yolu üzrə ən öncəlikli suallar ———
  {
    id: "nasil-fiyat-alirim",
    category: "pricing",
    priority: 1,
    q: "Necə qiymət ala bilərəm?",
    a: "Qiymət Hesabla səhifəsində sənədinizi yükləyin və ya mətninizi yapışdırın; dil cütünü və xidmət növünü seçdiyiniz anda ilkin qiymətinizi dərhal görürsünüz. Qiymət dil cütünə, xidmət növünə, söz sayına və seçdiyiniz əlavə xidmətlərə görə hesablanır.",
    keywords: ["qiymət", "qiymət təklifi", "dəyər", "qiymət almaq", "qiymət hesablama", "tərcümə qiyməti"],
  },
  {
    id: "dosya-nasil-yuklenir",
    category: "upload",
    priority: 2,
    q: "Faylımı necə yükləyə bilərəm?",
    a: "Qiymət Hesabla səhifəsindəki 'Fayl Yüklə' bölməsindən sənədinizi sürükləyib-buraxa və ya seçərək yükləyə bilərsiniz. Faylınız yoxdursa, 'Mətn Daxil Et' bölməsinə mətninizi yapışdırmanız kifayətdir. Mətn əsaslı fayllarda sistem söz sayını avtomatik çıxarır.",
    keywords: ["fayl yükləmə", "sənəd yüklə", "fayl əlavə etmə", "fayl yüklənmir", "necə yükləyirəm"],
  },
  {
    id: "fiyatlandirma-neye-gore",
    category: "pricing",
    priority: 3,
    q: "Qiymətləndirmə nəyə görə aparılır?",
    a: "Qiymət dil cütünə, xidmət növünə, sənədin məzmununa, söz sayına, ixtisas sahəsinə və seçdiyiniz əlavə xidmətlərə görə müəyyən edilir. Ekranda gördüyünüz məbləğ ilkin qiymətdir; sənəd nəzərdən keçirildikdən sonra son məbləğ dəqiqləşir.",
    keywords: ["qiymətləndirmə", "dəyərləndirmə", "qiymət necə", "nəyə görə qiymət", "söz başına"],
  },
  {
    id: "teslim-suresi-ne-kadar",
    category: "delivery",
    priority: 4,
    q: "Təhvil müddəti nə qədərdir?",
    a: "Müddət sənədin uzunluğuna, dil cütünə, xidmət növünə və seçdiyiniz əlavə xidmətlərə görə dəyişir. Qiymət hesablama ekranında sifarişinizə uyğun təxmini təhvil müddəti göstərilir. Təcili təhvil seçimi ilə bu müddət qısaldıla bilər.",
    keywords: ["təhvil müddəti", "neçə günə", "nə vaxt təhvil", "müddət", "neçə gün"],
  },
  {
    id: "yeminli-tercume-nedir",
    category: "sworn",
    priority: 5,
    q: "Andlı tərcümə nədir?",
    a: "Andlı tərcümə, andlı tərcüməçinin imzası və möhürü ilə təsdiqlədiyi, orijinala uyğunluğu bəyan edilən tərcümədir. Rəsmi müraciətlərdə çox vaxt tələb olunur. Qəti tələb sənədi istəyən quruma görə dəyişir.",
    keywords: ["andlı tərcümə", "təsdiqli tərcümə", "möhürlü tərcümə", "rəsmi tərcümə", "andlı nədir"],
  },
  {
    id: "hangi-dillerde-hizmet",
    category: "languages",
    priority: 6,
    q: "Hansı dillərdə xidmət göstərirsiniz?",
    a: "Türk dili başda olmaqla İngilis, Alman, Fransız, İspan, İtalyan, Ərəb və Rus dilləri kimi dillərdə, ümumilikdə 50-dən çox dildə xidmət göstəririk. Nadir dillərdə tərcüməçinin mövcudluğu və təhvil müddəti hər sifariş üçün ayrıca təsdiqlənir.",
    keywords: ["dillər", "hansı dillər", "dil seçimləri", "dil cütləri", "neçə dil"],
  },
  {
    id: "noter-onayi-gerekir-mi",
    category: "notary",
    priority: 7,
    q: "Notariat təsdiqi lazımdırmı?",
    a: "Notariat təsdiqi hər sənəd üçün məcburi deyil; onun lazım olub-olmaması sənədi istəyən quruma və istifadə məqsədinə görə dəyişir. Bəzi işlərdə andlı tərcümə kifayət edirsə, bəzilərində əlavə olaraq notariat təsdiqi də tələb olunur. Hansı təsdiqin lazım olduğuna əmin deyilsinizsə, sizə yol göstərə bilərik.",
    keywords: ["notariat təsdiqi", "notarial təsdiq", "notariat", "notariat lazımdır"],
  },
  {
    id: "siparis-nasil-ilerler",
    category: "order",
    priority: 8,
    q: "Sifariş prosesi necə gedir?",
    a: "Sənədinizi yükləyib ilkin qiyməti təsdiqlədikdən sonra sifarişiniz yaradılır və müvafiq sahədə ixtisaslaşmış tərcüməçiyə təyin edilir. Tərcümə keyfiyyət nəzarətindən keçir; lazım gəldikdə notariat/apostil prosesi aparılır və sənədiniz rəqəmsal şəkildə, tələb olunduqda kuryerlə təhvil verilir.",
    keywords: ["sifariş prosesi", "necə gedir", "mərhələlər", "proses"],
  },
  {
    id: "belgelerim-guvende-mi",
    category: "privacy",
    priority: 9,
    q: "Sənədlərim təhlükəsizdirmi?",
    a: "Bəli. Fayllarınızı yalnız sifarişinizdə çalışan komanda görür; onlar şifrələnmiş ötürmə və KVKK-ya (Türkiyənin fərdi məlumatların qorunması qanunu) uyğun proseslərlə işlənir. Sənədləriniz üçüncü şəxslərlə paylaşılmır və məxfilik əsas götürülür.",
    keywords: ["təhlükəsizlik", "məxfilik", "sənəd təhlükəsizliyi", "məlumat təhlükəsizliyi", "kvkk"],
  },
  {
    id: "cevirimi-kim-yapar",
    category: "quality",
    priority: 10,
    q: "Tərcüməmi kim edir?",
    a: "Tərcümələriniz müvafiq sahədə təcrübəli peşəkar insan tərcüməçilər tərəfindən edilir. Sənədin növünə görə ixtisaslı tərcüməçi təyin olunur və tərcümə təhvildən əvvəl keyfiyyət nəzarətindən keçir.",
    keywords: ["kim tərcümə edir", "tərcüməçi", "insan tərcüməçi", "peşəkar tərcüməçi", "kim edir"],
  },
  {
    id: "revize-hakki-var-mi",
    category: "quality",
    priority: 11,
    q: "Düzəliş hüququ varmı?",
    a: "Bəli. Təhvil verilən tərcümədə əhatə daxilində olan düzəliş tələbləriniz üçün düzəliş hüququ təqdim olunur. Orfoqrafiya, ad, tarix və ya uyğunluqla bağlı düzəlişlər bu əhatəyə daxildir. Mənbə mətnin sonradan dəyişdirilməsi və ya yeni məzmun əlavə edilməsi yeni iş sayıla bilər.",
    keywords: ["düzəliş", "korreksiya", "yenidən baxış", "təkrar tərcümə", "düzəliş hüququ"],
  },
  {
    id: "fiziksel-teslimat-yapiliyor-mu",
    category: "delivery",
    priority: 12,
    q: "Fiziki çatdırılma edilirmi?",
    a: "Bəli. Rəqəmsal təhvil əsas olsa da, orijinal əl imzası və möhürü olan sənədlər kuryerlə ünvanınıza göndərilə bilər. Türkiyənin hər yerinə və tələbinizə görə xaricə fiziki göndəriş edilə bilər. Kuryer seçimində göndəriş müddəti təhvil müddətinə əlavə olunur.",
    keywords: ["fiziki çatdırılma", "kuryer", "ünvana çatdırılma", "poçt göndərişi"],
  },
  {
    id: "kurumsal-ozel-sartlar",
    category: "corporate",
    priority: 13,
    q: "Korporativ müştərilər üçün xüsusi şərtlər varmı?",
    a: "Bəli. Korporativ müştərilərə toplu sifariş üstünlükləri, ödəniş müddəti seçimləri, terminologiya idarəetməsi və xüsusi hesab meneceri təqdim olunur. Ətraflı məlumat üçün Korporativ səhifəsindəki müraciət formasını doldura bilərsiniz.",
    keywords: ["korporativ", "şirkət", "korporativ xüsusi", "toplu sifariş", "korporativ şərtlər"],
  },
  {
    id: "apostil-nasil-yurutulur",
    category: "notary",
    priority: 14,
    q: "Apostil prosesi necə aparılır?",
    a: "Apostil, bir sənədin xaricdə etibarlı sayılması üçün səlahiyyətli orqan tərəfindən verilən təsdiqdir. Prosesi sizin adınıza aparıla bilərik; hansı sənədə apostil lazım olduğu və əməliyyat sırası sənədin istifadə olunacağı ölkəyə görə dəyişir. Haaqa Konvensiyasının tərəfi olmayan ölkələrdə apostil əvəzinə konsulluq təsdiqi tələb oluna bilər.",
    keywords: ["apostil", "apostil prosesi", "apostil təsdiqi", "xaricdə etibarlı"],
  },
  {
    id: "acil-teslimat-mumkun-mu",
    category: "delivery",
    priority: 15,
    q: "Təcili təhvil mümkündürmü?",
    a: "Bəli, bir çox sənəd üçün təcili təhvil seçimi təqdim olunur və təhvil müddəti qısaldılır. Təcili təhvil əlavə haqqa tabedir; sənədin uzunluğuna və dilinə görə mövcudluğu dəyişə bilər. Təcili hallarda da keyfiyyət nəzarəti mərhələləri qorunur.",
    keywords: ["təcili təhvil", "sürətli təhvil", "eyni gün", "ekspres", "təcili"],
  },
  {
    id: "odeme-nasil-yapilir",
    category: "pricing",
    priority: 16,
    q: "Ödəniş necə edilir?",
    a: "Ödənişlər kredit/debet kartı və bank köçürməsi ilə edilə bilər; kredit kartında hissə-hissə ödəniş imkanı təqdim oluna bilər. Korporativ müştərilərə əlavə olaraq ödəniş müddətli (15-30 gün) faktura seçimi verilir. Ödəniş ilkin qiyməti təsdiqlədikdən sonra alınır.",
    keywords: ["ödəniş", "ödəniş üsulu", "kredit kartı", "bank köçürməsi", "necə ödəniş"],
  },
  {
    id: "dosya-yuklemeden-fiyat",
    category: "upload",
    priority: 17,
    q: "Fayl yükləmədən qiymət almaq olarmı?",
    a: "Bəli. Faylınız yoxdursa, 'Mətn Daxil Et' bölməsinə mətninizi yapışdıraraq söz sayına görə ilkin qiymət ala bilərsiniz.",
    keywords: ["faylsız qiymət", "mətn daxil edərək", "fayl yükləmədən", "mətnlə qiymət"],
  },
  {
    id: "belgenin-formati-korunur-mu",
    category: "delivery",
    priority: 18,
    q: "Sənədin formatı qorunurmu?",
    a: "Mümkün qədər orijinal səhifə düzümü, cədvəllər və format qorunaraq tərcümə edilir. Nəticə ehtiyacınıza görə PDF və ya redaktə oluna bilən Word (DOCX) formatında təhvil verilə bilər. Skan edilmiş/təsvirli sənədlərdə birə-bir format əvəzinə səliqəli bir düzüm təmin olunur.",
    keywords: ["format", "düzüm", "səhifə düzümü", "word", "pdf", "format qorunur"],
  },
  {
    id: "teslim-sonrasi-destek",
    category: "quality",
    priority: 19,
    q: "Tərcümə təhvil verildikdən sonra dəstək ala bilərəmmi?",
    a: "Bəli. Təhvildən sonra əhatə daxilində olan düzəlişlər üçün düzəliş dəstəyi təqdim olunur və suallarınız üçün müştəri dəstək xəttimizə müraciət edə bilərsiniz. Sənədinizlə bağlı əlavə tələbləri e-poçt və ya WhatsApp vasitəsilə çatdıra bilərsiniz.",
    keywords: ["təhvildən sonra dəstək", "sonradan dəstək", "kömək", "dəstək"],
  },
  {
    id: "cok-sayfali-yuksek-hacim",
    category: "order",
    priority: 20,
    q: "Çoxsəhifəli və ya yüksək həcmli işlər necə idarə olunur?",
    a: "Yüksək həcmli layihələr planlaşdırılaraq aparılır; lazım gəldikdə bir neçə tərcüməçi və redaktor cəlb olunur, terminologiya uyğunluğu üçün ümumi lüğət istifadə edilir. Uzun layihələr tələbinizə görə hissə-hissə (qismən) təhvil verilə bilər. Korporativ layihələrdə proses hesab meneceriniz tərəfindən koordinasiya olunur.",
    keywords: ["çox səhifə", "yüksək həcm", "toplu iş", "böyük layihə", "çoxlu sənəd"],
  },

  // ——— ÜMUMİ ———
  {
    id: "tercumexpert-nedir",
    category: "general",
    priority: 21,
    q: "TercümExpert kimdir?",
    a: "TercümExpert; andlı tərcümə, notariat təsdiqli tərcümə, hüquqi, texniki, tibbi və akademik tərcümə ilə veb/mobil lokalizasiya xidmətləri göstərən onlayn tərcümə xidməti təminatçısıdır. Sənədinizi yükləyib ilkin qiymətinizi ala, sifarişinizi tamamilə onlayn verə bilərsiniz.",
    keywords: ["tercumexpert", "kimdir", "nədir", "tərcümə xidməti", "nə iş görür"],
  },
  {
    id: "hangi-hizmetler",
    category: "general",
    priority: 22,
    q: "TercümExpert hansı xidmətləri təqdim edir?",
    a: "Andlı və notariat təsdiqli tərcümə, apostil prosesi dəstəyi, hüquqi, texniki, tibbi və akademik tərcümə ilə veb və mobil tətbiq lokalizasiyası təqdim edirik. Ehtiyacınıza uyğun xidməti Qiymət Hesabla ekranında seçə bilərsiniz.",
    keywords: ["xidmətlər", "nə edir", "xidmət növləri", "hansı xidmət"],
  },
  {
    id: "kimler-hizmet-alabilir",
    category: "general",
    priority: 23,
    q: "Kimlər xidmət ala bilər?",
    a: "Həm fərdi müştərilər, həm də şirkət və qurumlar xidmət ala bilər. Tələbədən sərbəst çalışana, kiçik və orta biznesdən böyük qurumlara qədər müxtəlif ehtiyaclara uyğun həllər təqdim olunur.",
    keywords: ["kimlər", "fərdi", "korporativ", "kim ala bilər", "şirkət"],
  },
  {
    id: "ofise-gelmek-gerekir-mi",
    category: "general",
    priority: 24,
    q: "Fiziki ofisə gəlmək lazımdırmı?",
    a: "Xeyr. Bütün proses — qiymət almaq, sifariş, ödəniş və təhvil — onlayn aparıla bilər. Sənədlərinizi yükləməniz və təsdiqləməniz kifayətdir; heç bir yerə gəlmənizə ehtiyac yoxdur.",
    keywords: ["ofis", "ofisə gəlmə", "filial", "ünvan", "gəlmək məcburi"],
  },
  {
    id: "surec-cevrimici-mi",
    category: "general",
    priority: 25,
    q: "Bütün proses onlayn aparıla bilərmi?",
    a: "Bəli. Sənəd yükləmə, qiymət təsdiqi, ödəniş və rəqəmsal təhvilin hamısı onlayndır. Yalnız orijinal əl imzalı fiziki sənəd lazım olduqda kuryer işə düşür.",
    keywords: ["onlayn", "onlayn proses", "internetdən", "uzaqdan", "hər şey onlayn"],
  },
  {
    id: "yurt-disindan-hizmet",
    category: "general",
    priority: 26,
    q: "Xaricdəki müştərilər xidmət ala bilərmi?",
    a: "Bəli. Proses onlayn olduğu üçün xaricdən də sənəd yükləyib sifariş verə bilərsiniz. Rəqəmsal təhvil hər yerə edilir; orijinal əl imzalı sənəd üçün xaricə kuryer göndərişi də təmin edilə bilər.",
    keywords: ["xaric", "xaricdən", "başqa ölkə", "xaricdən xidmət"],
  },
  {
    id: "uyelik-zorunlu-mu",
    category: "general",
    priority: 27,
    q: "Xidmət almaq üçün üzvlük məcburidirmi?",
    a: "Üzvlük məcburi deyil. Lakin qiyməti görmək və sifariş vermək üçün ad, soyad və e-poçt məlumatlarınızı daxil edib e-poçtunuza gələn təsdiq kodunu təsdiqləməniz lazımdır. İstəsəniz, üzvlük yaradaraq sifariş tarixçənizi də izləyə bilərsiniz.",
    keywords: ["üzvlük", "qeydiyyat", "hesab yaratma", "məcburidir", "üzvlüksüz"],
  },
  {
    id: "uye-olmadan-fiyat",
    category: "general",
    priority: 28,
    q: "Qeydiyyatdan keçmədən qiymət almaq olarmı?",
    a: "Bəli, tam hesab yaratmadan da qiymət ala bilərsiniz; yalnız ad, soyad və e-poçt təsdiqi lazımdır. Təsdiqi tamamlamayan istifadəçilər qiyməti görə və sifariş verə bilməz.",
    keywords: ["qeydiyyatsız qiymət", "üzvlüksüz qiymət", "təsdiq kodu", "e-poçt təsdiqi"],
  },
  {
    id: "siparis-oncesi-danismanlik",
    category: "general",
    priority: 29,
    q: "Sifariş verməzdən əvvəl məsləhət almaq olarmı?",
    a: "Bəli. Hansı xidmətə ehtiyacınız olduğuna əmin deyilsinizsə, WhatsApp, e-poçt və ya süni intellekt dəstəkli çat köməkçimiz vasitəsilə məlumat ala bilərsiniz. Sənədinizin növünə görə uyğun xidməti və prosesi birlikdə müəyyən edirik.",
    keywords: ["məsləhət", "məlumat almaq", "sual vermə", "ilkin görüş"],
  },
  {
    id: "musteri-temsilcisi",
    category: "general",
    priority: 30,
    q: "Müştəri nümayəndəsinə necə çatmaq olar?",
    a: "Müştəri dəstək xəttimizə WhatsApp və ya e-poçt vasitəsilə çata bilərsiniz. Suallarınız iş saatları ərzində bir nümayəndə tərəfindən cavablandırılır; həmçinin süni intellekt dəstəkli çat köməkçimiz istənilən vaxt ilkin yönləndirmə edə bilər.",
    keywords: ["müştəri nümayəndəsi", "dəstək", "əlaqə", "çatmaq", "canlı dəstək"],
  },
  {
    id: "hangi-belgeler-cevrilebilir",
    category: "general",
    priority: 31,
    q: "Hansı sənəd növləri tərcümə edilə bilər?",
    a: "Rəsmi və şəxsi sənədlərdən tutmuş ticari, hüquqi, texniki, tibbi və akademik mətnlərə qədər geniş çeşiddə tərcümə edirik. Diplom, müqavilə, hesabat, təlimat, veb sayt mətni kimi bir çox sənəd növü dəstəklənir.",
    keywords: ["sənəd növləri", "hansı sənədlər", "sənəd", "nə tərcümə olunur"],
  },
  {
    id: "yapay-zeka-mi-insan-mi",
    category: "general",
    priority: 32,
    q: "Tərcümələr insan tərcüməçilər tərəfindən edilirmi?",
    a: "Bəli. Tərcümələriniz əvvəldən sona qədər peşəkar insan tərcüməçilər tərəfindən edilir. Uyğunluq və terminologiya üçün peşəkar tərcümə alətləri (CAT aləti) dəstəyi istifadə olunur; lakin tərcümənin hamısı ixtisaslı tərcüməçilərin işidir və keyfiyyət nəzarətindən keçir.",
    keywords: ["insan tərcüməçi", "cat aləti", "tərcümə aləti", "maşın tərcüməsi", "kim tərcümə edir"],
  },
  {
    id: "el-yazili-belgeler",
    category: "general",
    priority: 33,
    q: "Əlyazması və ya oxunması çətin sənədlər tərcümə edilə bilərmi?",
    a: "Əlyazması və oxunması çətin sənədlər oxunaqlı olmaq şərti ilə tərcümə edilə bilər. Oxunmayan hissələr tərcümədə açıq şəkildə qeyd olunur və lazım gəldikdə sizdən daha aydın nüsxə istənilir. Bu cür sənədlərdə qiymət nəzərdən keçirildikdən sonra dəqiqləşir.",
    keywords: ["əlyazması", "əl yazısı", "oxunmayan", "aydın deyil", "oxunması çətin"],
  },
  {
    id: "farkiniz-nedir",
    category: "general",
    priority: 34,
    q: "TercümExpert-in digər tərcümə xidmətlərindən fərqi nədir?",
    a: "Prosesi başdan-başa onlayn aparmağımız, avtomatik ilkin qiymətləndirmə, sahəsində ixtisaslı insan tərcüməçilər və keyfiyyət nəzarəti öndə gələn cəhətlərimizdir. Bundan əlavə, orijinal əl imzalı sənədləri qapınıza qədər kuryerlə çatdırırıq.",
    keywords: ["fərq", "üstünlük", "niyə tercumexpert", "fərqiniz"],
  },

  // ——— SİFARİŞ PROSESİ ———
  {
    id: "siparis-nasil-verilir",
    category: "order",
    priority: 35,
    q: "Sifariş necə verilir?",
    a: "Qiymət Hesabla ekranından sənədinizi yükləyin və ya mətninizi daxil edin, dil cütünü və xidmət növünü seçin və ilkin qiyməti təsdiqləyin. Təsdiqdən sonra sifarişiniz yaradılır.",
    keywords: ["sifariş vermə", "necə sifariş", "sifariş yaratma"],
  },
  {
    id: "siparis-icin-gerekli-bilgiler",
    category: "order",
    priority: 36,
    q: "Sifariş vermək üçün hansı məlumatlar lazımdır?",
    a: "Tərcümə olunacaq sənəd və ya mətn, mənbə və hədəf dil, xidmət növü və əlaqə üçün ad-soyad ilə e-poçt məlumatı lazımdır. Bu məlumatlarla sifarişinizi yarada bilərsiniz.",
    keywords: ["lazımi məlumat", "hansı məlumatlar", "sifariş məlumatları"],
  },
  {
    id: "dil-cifti-nasil-secilir",
    category: "order",
    priority: 37,
    q: "Dil cütü və xidmət növü necə seçilir?",
    a: "Qiymət Hesabla ekranında mənbə dili (sənədin dili), hədəf dili (tərcümə dili) və xidmət növünü (andlı, notariat təsdiqli, texniki və s.) menyudan seçirsiniz. Əmin deyilsinizsə, dəstək xəttimiz və ya çat köməkçimiz düzgün seçimdə yönləndirir.",
    keywords: ["dil cütü seçmə", "mənbə dil", "hədəf dil", "xidmət növü seçmə"],
  },
  {
    id: "bilgiler-degistirilebilir-mi",
    category: "order",
    priority: 38,
    q: "Sifariş yaradıldıqdan sonra məlumatlar dəyişdirilə bilərmi?",
    a: "Tərcümə başlamazdan əvvəl dil, xidmət növü və ya sənəd kimi məlumatlar yenilənə bilər. Bunun üçün dəstək xəttimizə mümkün qədər tez müraciət etməniz kifayətdir; iş irəlilədikcə dəyişiklik əhatəsi məhdudlaşa bilər.",
    keywords: ["məlumat dəyişmə", "düzəliş", "sifariş yeniləmə", "səhv dil", "səhv sənəd"],
  },
  {
    id: "onaydan-once-iptal",
    category: "order",
    priority: 39,
    q: "Sifariş təsdiqlənmədən əvvəl ləğv edilə bilərmi?",
    a: "Bəli. Ödəniş və təsdiq tamamlanmadan sifarişinizi ləğv edə bilərsiniz; bu mərhələdə heç bir haqq alınmır.",
    keywords: ["ləğv", "sifariş ləğvi", "imtina"],
  },
  {
    id: "odeme-sonrasi-iptal",
    category: "order",
    priority: 40,
    q: "Ödənişdən sonra sifariş ləğv edilə bilərmi?",
    a: "Tərcümə başlamayıbsa, ləğv və geri qaytarma ümumiyyətlə mümkündür. İş başlayıbsa, tamamlanan hissəyə görə qismən haqq tətbiq oluna bilər. Ləğv tələbinizi mümkün qədər tez çatdırmağınız prosesinizi asanlaşdırır.",
    keywords: ["ödənişdən sonra ləğv", "geri qaytarma", "pul geri"],
  },
  {
    id: "siparis-durumu-takip",
    category: "order",
    priority: 41,
    q: "Sifarişin statusu haradan izlənilir?",
    a: "Sifarişinizin statusu barədə e-poçt ilə məlumatlandırılırsınız; üzvlük yaratmısınızsa, hesabınızdan da izləyə bilərsiniz. Həmçinin dəstək xəttimizdən cari statusu soruşa bilərsiniz.",
    keywords: ["sifariş izləmə", "status", "harada izlənilir", "sifariş statusu"],
  },
  {
    id: "birden-fazla-belge",
    category: "order",
    priority: 42,
    q: "Eyni sifarişdə bir neçə sənəd və ya hədəf dil ola bilərmi?",
    a: "Bəli, eyni sifarişdə bir neçə sənəd yükləyə və eyni sənədi bir neçə dilə tərcümə etdirə bilərsiniz. Ümumi söz sayı və hər hədəf dil ayrıca tərcümə kimi qiymətləndirilir; proses tək tələb üzərindən koordinasiya olunur.",
    keywords: ["çoxlu sənəd", "bir neçə fayl", "çoxlu dil", "bir neçə dil"],
  },
  {
    id: "sonradan-dosya-eklenebilir",
    category: "order",
    priority: 43,
    q: "Sifarişə sonradan yeni fayl əlavə edilə bilərmi?",
    a: "Tərcümə başlamazdan əvvəl yeni fayl əlavə edilə bilər; bu halda qiymət əlavə olunan məzmuna görə yenilənir. İş irəlilədikdən sonra əlavə olunan sənədlər yeni bir maddə kimi qiymətləndirilə bilər.",
    keywords: ["fayl əlavə etmə", "sonradan əlavə", "yeni fayl"],
  },
  {
    id: "eksik-belge-gonderilirse",
    category: "order",
    priority: 44,
    q: "Natamam sənəd göndərilərsə nə olur?",
    a: "Çatışmayan səhifə və ya sənəd aşkar edildikdə sizdən onu tamamlamağınızı istəyirik. Sənədin bütün səhifələrinin yüklənməsi tərcümənin tam və etibarlı olması üçün vacibdir.",
    keywords: ["natamam sənəd", "çatışmayan səhifə", "əskik sənəd"],
  },
  {
    id: "terminoloji-not-referans",
    category: "order",
    priority: 45,
    q: "Sifarişə xüsusi qeyd, terminologiya və ya istinad faylı əlavə edilə bilərmi?",
    a: "Bəli. Sifariş zamanı xüsusi təlimat, üstünlük verdiyiniz terminlər və ya üslub qeydi əlavə edə; əvvəlki tərcümələr və lüğət kimi istinad fayllarını yükləyə bilərsiniz. Bu məlumatlar tərcüməçiyə ötürülür və uyğunluq üçün istifadə olunur.",
    keywords: ["qeyd əlavə etmə", "xüsusi təlimat", "terminologiya", "istinad faylı", "lüğət"],
  },
  {
    id: "eski-siparisler-goruntulenir",
    category: "order",
    priority: 46,
    q: "Köhnə sifarişlərə və fayllara sonradan çıxış mümkündürmü?",
    a: "Üzvlük yaratmısınızsa, keçmiş sifarişlərinizi və təhvil verilən fayllarınızı hesabınızdan görə bilərsiniz. Üzvlüksüz sifarişlərdə qeydlərinizə e-poçt vasitəsilə çata bilərsiniz; endirmə keçidlərinin müddəti bitdikdə dəstək xəttimizdən yeni keçid tələb edə bilərsiniz.",
    keywords: ["köhnə sifariş", "sifariş tarixçəsi", "keçmiş", "fayla çıxış"],
  },

  // ——— QİYMƏTLƏNDİRMƏ VƏ ÖDƏNİŞ ———
  {
    id: "kelime-mi-sayfa-mi",
    category: "pricing",
    priority: 47,
    q: "Söz başına, yoxsa səhifə başına qiymətləndirmə aparılır?",
    a: "Qiymətləndirmə adətən söz sayına və seçilən xidmətə görə aparılır. Mətn əsaslı sənədlərdə söz sayı avtomatik çıxarılır; skan edilmiş/təsvirli sənədlərdə say nəzərdən keçirildikdən sonra təsdiqlənir.",
    keywords: ["söz başına", "səhifə başına", "qiymətləndirmə", "necə qiymət"],
  },
  {
    id: "sabit-baslangic-ucreti",
    category: "pricing",
    priority: 48,
    q: "Sabit başlanğıc haqqı və ya minimum məbləğ varmı?",
    a: "Bəzi xidmətlərdə minimum xidmət haqqı tətbiq oluna bilər; qısa sənədlərdə bu minimum məbləğ keçərli ola bilər. Son qiymət sənədin məzmununa və seçdiyiniz xidmətlərə görə müəyyən edilir və bütün maddələri ilkin qiymət ekranında görə bilərsiniz.",
    keywords: ["başlanğıc haqqı", "minimum", "sabit haqq", "minimum məbləğ"],
  },
  {
    id: "neler-fiyati-etkiler",
    category: "pricing",
    priority: 49,
    q: "Dil cütü, sənəd növü və ixtisas sahəsi qiymətə təsir edirmi?",
    a: "Bəli. Dil cütü (xüsusən nadir dillər), sənəd növü və ixtisas sahəsi (hüquqi, tibbi, texniki və s.) terminologiya sıxlığına və beləliklə qiymətə təsir edə bilər. Geniş yayılmış dillərdə qiymət daha proqnozlaşdırıla biləndir.",
    keywords: ["dil cütü qiymət", "sənəd növü qiymət", "ixtisas qiymət", "niyə fərqli qiymət"],
  },
  {
    id: "yeminli-daha-pahali-mi",
    category: "pricing",
    priority: 50,
    q: "Andlı tərcümə daha bahalıdırmı?",
    a: "Andlı tərcümə, tərcüməçinin təsdiqi və məsuliyyəti səbəbindən standart tərcümədən fərqli qiymətləndirilə bilər. Qəti məbləğ sənəd və dil cütünə görə ilkin qiymət ekranında göstərilir.",
    keywords: ["andlı qiymət", "andlı bahalıdır", "andlı dəyər"],
  },
  {
    id: "noter-apostil-ucreti-dahil",
    category: "pricing",
    priority: 51,
    q: "Notariat təsdiqi və apostil haqqı qiymətə daxildirmi?",
    a: "Notariat təsdiqi və apostil səlahiyyətli orqanlar tərəfindən aparılan ayrı əməliyyatlardır və rəsmi tarifə tabedir. Bu xərclər tərcümə haqqından ayrıca göstərilir; rəsmi tarifə bağlı olduğundan əvvəlcədən qəti olmaya bilər və faktiki məbləğ əməliyyatdan sonra bildirilir.",
    keywords: ["notariat haqqı", "apostil haqqı", "daxildir", "notariat xərci", "apostil xərci"],
  },
  {
    id: "on-fiyat-nihai-fark",
    category: "pricing",
    priority: 52,
    q: "İlkin qiymətlə son qiymət arasında fərq ola bilərmi?",
    a: "Bəli. Ekranda gördüyünüz avtomatik hesablama ilkin qiymətdir. Söz sayı, oxunaqlılıq və ya sənəd növünə bağlı nəzərdən keçirmədən sonra son qiymət dəqiqləşə bilər. Təsdiqləmədən əvvəl son məbləğ sizə çatdırılır.",
    keywords: ["ilkin qiymət", "son qiymət", "qiymət fərqi", "qəti qiymət"],
  },
  {
    id: "otomatik-kelime-sayimi",
    category: "pricing",
    priority: 53,
    q: "Söz sayı avtomatik hesablanırmı? Skan edilmiş PDF-lərdə necə olur?",
    a: "Mətn əsaslı sənədlərdə (Word, mətn PDF-i, düz mətn) söz sayı avtomatik çıxarılır. Skan edilmiş/təsvirli PDF və fotoşəkillərdə avtomatik say etibarlı olmaya bilər; bu halda say komandamız tərəfindən təsdiqlənir. İlkin qiymət avtomatik saya əsaslanır və bağlayıcı deyil; fərq yaranarsa son qiymət sizə təsdiqlətdirilir.",
    keywords: ["söz sayımı", "avtomatik say", "skan pdf", "təsvirli pdf", "say xətası"],
  },
  {
    id: "toplu-kurumsal-indirim",
    category: "pricing",
    priority: 54,
    q: "Toplu sifariş və ya korporativ müştərilər üçün endirim varmı?",
    a: "Yüksək həcmli və müntəzəm işlərdə, xüsusən korporativ müştərilərə həcmə və əməkdaşlıq şərtlərinə görə sərfəli qiymətləndirmə və ödəniş müddəti seçimləri təqdim oluna bilər. Ətraflı məlumat üçün Korporativ müraciət formasını istifadə edə bilərsiniz.",
    keywords: ["toplu endirim", "həcm endirimi", "korporativ qiymət", "şirkət qiyməti"],
  },
  {
    id: "ucretsiz-teklif",
    category: "pricing",
    priority: 55,
    q: "Pulsuz qiymət təklifi almaq olarmı? Təklif nə qədər etibarlıdır?",
    a: "İlkin qiymət təklifi pulsuzdur; sənədinizi yükləyib və ya mətni daxil etdiyinizdə təklifi dərhal görürsünüz. Təkliflər, şərtlər (sənədin məzmunu/əhatəsi) dəyişmədiyi müddətdə qısa müddət üçün etibarlıdır.",
    keywords: ["pulsuz təklif", "pulsuz qiymət", "təklif müddəti", "etibarlılıq"],
  },
  {
    id: "fatura-kesiliyor-mu",
    category: "pricing",
    priority: 56,
    q: "Faktura verilirmi? Fərdi və korporativ faktura tərtib edilə bilərmi?",
    a: "Bəli. Xidmət müqabilində faktura tərtib olunur; fərdi və ya korporativ faktura tələb edə bilərsiniz. Korporativ müştərilərə aylıq toplu fakturalaşdırma da təqdim oluna bilər. Vergilər qüvvədə olan qanunvericiliyə uyğun tətbiq olunur.",
    keywords: ["faktura", "faktura vermə", "ədv", "korporativ faktura", "fərdi faktura"],
  },
  {
    id: "taksit-secenegi",
    category: "pricing",
    priority: 57,
    q: "Hissə-hissə ödəniş seçimi varmı?",
    a: "Kredit kartı ilə ödənişdə hissə-hissə ödəniş imkanı təqdim oluna bilər. Uyğun hissə-hissə ödəniş seçimləri ödəniş mərhələsində göstərilir.",
    keywords: ["hissə-hissə", "hissə-hissə ödəniş"],
  },
  {
    id: "kurumsal-vadeli-odeme",
    category: "pricing",
    priority: 58,
    q: "Korporativ müştərilərə ödəniş müddəti təqdim olunurmu?",
    a: "Bəli. Korporativ müştərilərə 15-30 günə qədər ödəniş müddəti və aylıq fakturalaşdırma seçimləri təqdim oluna bilər. Şərtlər korporativ əməkdaşlıq çərçivəsində müəyyən edilir.",
    keywords: ["ödəniş müddəti", "müddət", "korporativ ödəniş"],
  },
  {
    id: "odeme-yapilmadan-baslar-mi",
    category: "pricing",
    priority: 59,
    q: "Ödəniş edilmədən tərcümə başlayırmı?",
    a: "Standart sifarişlərdə tərcümə ödənişin (və ya korporativ ödəniş müddəti təsdiqinin) alınmasından sonra başlayır. Korporativ razılaşmalarda proses müqaviləyə görə gedə bilər.",
    keywords: ["ilkin ödəniş", "ödənişdən əvvəl", "avans", "ödəniş edilmədən"],
  },
  {
    id: "iade-sureci",
    category: "pricing",
    priority: 60,
    q: "Ləğv edilən sifarişlərdə haqq geri qaytarılırmı?",
    a: "Tərcümə başlamazdan əvvəl ləğv edilən sifarişlərdə ödəniş geri qaytarılır. İş başlayıbsa, tamamlanan hissə çıxılaraq qalan məbləğ geri qaytarıla bilər. Təkrar çəkilmə kimi hallarda artıq məbləğ geri qaytarılır.",
    keywords: ["geri qaytarma", "haqqın geri qaytarılması", "pul geri", "ləğv geri qaytarma"],
  },

  // ——— FAYL YÜKLƏMƏ ———
  {
    id: "hangi-formatlar",
    category: "upload",
    priority: 61,
    q: "Hansı fayl formatları dəstəklənir?",
    a: "Word (DOC/DOCX), PDF, düz mətn (TXT), Excel, PowerPoint və geniş yayılmış təsvir formatları (JPG, PNG) daxil olmaqla 50-dən çox format qəbul edilir. Mətn əsaslı sənədlərdə söz sayı avtomatik çıxarılır.",
    keywords: ["format", "fayl formatı", "dəstəklənən formatlar", "pdf", "doc", "docx", "txt"],
  },
  {
    id: "taranmis-fotograf-belge",
    category: "upload",
    priority: 62,
    q: "Skan edilmiş və ya şəkli çəkilmiş sənəd qəbul edilirmi?",
    a: "Bəli. Skan edilmiş sənədlər və telefonla çəkilmiş aydın fotoşəkillər qəbul edilir. Oxunaqlılıq vacibdir; möhür, ştamp və imzaların görünən olması lazımdır. Təsvirlərdə mətn avtomatik oxunmaya biləcəyi üçün söz sayı komandamız tərəfindən müəyyən edilir.",
    keywords: ["skan sənəd", "foto sənəd", "telefonla çəkilmiş", "təsvir yükləmə", "şəkil"],
  },
  {
    id: "birden-fazla-dosya-yukleme",
    category: "upload",
    priority: 63,
    q: "Bir neçə fayl eyni anda yüklənə bilərmi?",
    a: "Bəli, eyni anda bir neçə fayl yükləyə bilərsiniz. Qiymət ümumi məzmun üzərindən hesablanır.",
    keywords: ["çoxlu yükləmə", "bir neçə fayl", "toplu yükləmə"],
  },
  {
    id: "dosya-boyutu-siniri",
    category: "upload",
    priority: 64,
    q: "Fayl ölçüsü məhdudiyyəti varmı? Böyük fayllar necə göndərilir?",
    a: "Hər fayl üçün təxminən 100 MB-a qədər yükləmə edə bilərsiniz. Daha böyük fayllar üçün dəstək xəttimizlə əlaqə saxlayaraq e-poçt və ya alternativ göndəriş üsulu təmin edə bilərsiniz.",
    keywords: ["fayl ölçüsü", "ölçü məhdudiyyəti", "böyük fayl", "100 mb"],
  },
  {
    id: "yuklenen-dosya-silinebilir",
    category: "upload",
    priority: 65,
    q: "Yüklənən fayl silinə və ya dəyişdirilə bilərmi?",
    a: "Bəli. Sifariş tamamlanmadan yüklədiyiniz faylı silə və ya yenisi ilə əvəz edə bilərsiniz.",
    keywords: ["fayl silmə", "fayl dəyişdirmə", "səhv fayl"],
  },
  {
    id: "manuel-kelime-girisi",
    category: "upload",
    priority: 66,
    q: "Fayl yükləmədən əl ilə söz sayı daxil edilə bilərmi?",
    a: "Birbaşa rəqəm daxil etmək əvəzinə, mətninizi 'Mətn Daxil Et' bölməsinə yapışdırdığınızda söz sayı avtomatik hesablanır. Beləliklə faylsız da ilkin qiymət ala bilərsiniz.",
    keywords: ["əl ilə söz", "söz daxil etmə", "mətn daxil etmə"],
  },
  {
    id: "dosyalar-ne-kadar-saklanir",
    category: "upload",
    priority: 67,
    q: "Fayllar nə qədər müddət saxlanılır, silinməsi tələb edilə bilərmi?",
    a: "Sənədləriniz yalnız xidmətin tələb etdiyi müddət ərzində təhlükəsiz şəkildə saxlanılır. İstədiyiniz vaxt sənədlərinizin silinməsini tələb edə bilərsiniz; bu tələb KVKK çərçivəsindəki hüquqlarınıza uyğun yerinə yetirilir.",
    keywords: ["saxlama müddəti", "fayl saxlama", "fayl silmə tələbi", "məlumat silmə"],
  },
  {
    id: "belgenin-tum-sayfalari",
    category: "upload",
    priority: 68,
    q: "Sənədin bütün səhifələri və arxa üzləri yüklənməlidirmi?",
    a: "Bəli. Tərcümənin tam və etibarlı olması üçün sənədin bütün səhifələrini, varsa arxa üzlərini yükləməniz lazımdır. Möhür, ştamp və imza sahələrinin aydın görünməsi vacibdir.",
    keywords: ["bütün səhifələr", "arxa üz", "tam sənəd", "möhür ştamp"],
  },
  {
    id: "imza-kase-cevrilir-mi",
    category: "upload",
    priority: 69,
    q: "Ştamp, möhür və imzalar tərcümə edilirmi?",
    a: "Andlı tərcümədə ştamp və möhür üzərindəki oxunaqlı yazılar köçürülür; imzalar isə \"imza vardır\" şəklində qeyd olunur. Oxunmayan sahələr tərcümədə açıq şəkildə qeyd edilir.",
    keywords: ["ştamp tərcüməsi", "möhür tərcüməsi", "imza tərcüməsi"],
  },
  {
    id: "dosya-guvenli-mi-analiz",
    category: "upload",
    priority: 70,
    q: "Avtomatik təhlil zamanı sənədin məzmunu təhlükəsizdirmi?",
    a: "Bəli. Sənədlər şifrələnmiş şəkildə ötürülür və söz sayımı kimi əməliyyatlar təhlükəsiz mühitdə aparılır. Məzmununuz üçüncü şəxslərlə paylaşılmır.",
    keywords: ["təhlil təhlükəsiz", "məzmun təhlükəsizliyi", "avtomatik oxuma"],
  },

  // ——— DİLLƏR VƏ DİL CÜTLƏRİ ———
  {
    id: "50-dil-ne-demek",
    category: "languages",
    priority: 71,
    q: "50-dən çox dil dəstəyi nə deməkdir?",
    a: "Geniş yayılmış dillərlə yanaşı, daha az tələb olunan dillərdə də tərcümə edə bildiyimiz mənasına gəlir. Nadir dillərdə tərcüməçinin mövcudluğu, təhvil müddəti və qiymət hər sifariş üçün ayrıca təsdiqlənir.",
    keywords: ["50 dil", "nadir dil", "dil dəstəyi", "neçə dil"],
  },
  {
    id: "yaygin-dil-ciftleri",
    category: "languages",
    priority: 72,
    q: "Türkcə-İngiliscə, Almanca, Fransızca kimi dil cütlərində tərcümə edilirmi?",
    a: "Bəli. Türkcə ⇄ İngiliscə, Almanca, Fransızca, İspanca, İtalyanca, Ərəbcə və Rusca kimi geniş yayılmış dil cütlərində hər iki istiqamətdə tərcümə edilir. Çincə, Yaponca kimi dillər də dəstəklənir.",
    keywords: ["türkcə ingiliscə", "ingiliscə türkcə", "almanca", "fransızca", "dil cütü"],
  },
  {
    id: "yabancidan-yabanciya",
    category: "languages",
    priority: 73,
    q: "İki xarici dil arasında (Türk dili olmadan) tərcümə edilə bilərmi?",
    a: "Bəli, İngiliscə-Fransızca kimi bir xarici dildən digərinə tərcümələr edilə bilər. Mövcudluq və müddət dil cütünə görə qiymətləndirilir.",
    keywords: ["xarici xarici", "ingiliscə fransızca", "dillər arası"],
  },
  {
    id: "nadir-dil",
    category: "languages",
    priority: 74,
    q: "Nadir və ya siyahıda olmayan dillər üçün xidmət göstərilirmi?",
    a: "Nadir dillərdə də xidmət göstərməyə çalışırıq; lakin tərcüməçinin mövcudluğu, müddət və qiymət bu dillərdə ayrıca təsdiqlənir. Axtardığınız dil siyahıda yoxdursa, dəstək xəttimizə yazaraq sizə xüsusi təklif istəyə bilərsiniz.",
    keywords: ["nadir dil", "az istifadə olunan dil", "siyahıda olmayan", "xüsusi dil"],
  },
  {
    id: "dil-varyantlari",
    category: "languages",
    priority: 75,
    q: "Regional dil variantları (Amerikan/Britaniya İngiliscəsi kimi) seçilə bilərmi?",
    a: "Bəli, mümkün olduqda hədəf dilin regional variantını (məs. Amerikan/Britaniya İngiliscəsi, Avropa/Latın Amerikası İspancası) qeyd edə bilərsiniz. Variant qeyd olunmazsa, geniş yayılmış standart istifadə olunur.",
    keywords: ["variant", "amerikan ingiliscə", "regional dil", "ləhcə"],
  },
  {
    id: "anadili-tercuman",
    category: "languages",
    priority: 76,
    q: "Ana dili hədəf dil olan tərcüməçilərlə işləyirsiniz?",
    a: "Mümkün olduqca hədəf dildə səriştəli, sahəsində təcrübəli tərcüməçilərlə işləyirik. Məqsəd təbii və doğru tərcümə təmin etməkdir.",
    keywords: ["ana dili tərcüməçi", "doğma danışan", "hədəf dil mütəxəssisi"],
  },
  {
    id: "osmanlica-eski-yazi",
    category: "languages",
    priority: 77,
    q: "Osmanlıca və ya köhnə əlifba ilə yazılmış sənədlər tərcümə edilə bilərmi?",
    a: "Osmanlıca və köhnə əlifba ilə yazılmış sənədlər mütəxəssisin mövcudluğundan asılı olaraq tərcümə edilə bilər. Bu cür sənədlərdə müddət və qiymət nəzərdən keçirildikdən sonra dəqiqləşir.",
    keywords: ["osmanlıca", "köhnə yazı", "köhnə əlifba"],
  },
  {
    id: "karisik-dilli-belge",
    category: "languages",
    priority: 78,
    q: "Bir sənəddə bir neçə dil varsa tərcümə edilə bilərmi?",
    a: "Bəli. Qarışıq dilli sənədlər tərcümə edilə bilər; qiymət hər dildəki məzmun miqdarına görə müəyyən edilir. Ehtiyac duyduğunuz hədəf dili qeyd etməniz kifayətdir.",
    keywords: ["qarışıq dil", "çoxdilli sənəd", "sənəddə bir neçə dil"],
  },

  // ——— XİDMƏT NÖVLƏRİ ———
  {
    id: "hangi-hizmeti-secmeliyim",
    category: "services",
    priority: 79,
    q: "Hansı xidmət növünü seçməliyəm?",
    a: "Sənədinizin harada istifadə olunacağı xidmət seçimini müəyyən edir: rəsmi müraciətlər çox vaxt andlı, bəzi işlər notariat təsdiqli və ya apostilli tərcümə tələb edir. Əmin deyilsinizsə, dəstək xəttimiz və ya çat köməkçimiz yönləndirir; qəti tələb müvafiq quruma görə dəyişir.",
    keywords: ["hansı xidmət", "xidmət seçimi", "nə seçməliyəm"],
  },
  {
    id: "standart-yeminli-fark",
    category: "services",
    priority: 80,
    q: "Standart tərcümə ilə andlı tərcümə arasındakı fərq nədir?",
    a: "Standart tərcümə rəsmi təsdiq olmayan, məlumat məqsədli tərcümədir. Andlı tərcümə isə andlı tərcüməçinin möhürü və imzası ilə təsdiqlənir və rəsmi müraciətlərdə tələb olunur. Hansının lazım olduğu sənədin təqdim ediləcəyi quruma bağlıdır.",
    keywords: ["standart andlı", "fərq", "adi tərcümə", "andlı fərq"],
  },
  {
    id: "yeminli-noter-ayni-mi",
    category: "services",
    priority: 81,
    q: "Andlı tərcümə ilə notariat təsdiqli tərcümə eyni şeydirmi?",
    a: "Xeyr. Andlı tərcümə andlı tərcüməçinin təsdiqini daşıyır. Notariat təsdiqli tərcümə isə bu tərcümənin əlavə olaraq notarius tərəfindən təsdiqlənməsidir. Bəzi qurumlar yalnız andlı tərcümə istəyir, bəziləri isə notariat təsdiqi də tələb edir.",
    keywords: ["andlı notariat fərq", "notariat təsdiqli", "eynidir"],
  },
  {
    id: "hukuki-teknik-medikal",
    category: "services",
    priority: 82,
    q: "Hüquqi, texniki və tibbi tərcümələrdə ixtisas necə təmin edilir?",
    a: "Müqavilə, məhkəmə sənədi, texniki sənədləşmə və tibbi sənədlər müvafiq sahənin terminologiyasına bələd olan təcrübəli tərcüməçilər tərəfindən tərcümə olunur. Terminologiya lüğətləri və tərcümə yaddaşı ilə uyğunluq təmin edilir, format və vahidlər qorunur və tərcümə keyfiyyət nəzarətindən keçir.",
    keywords: ["hüquqi tərcümə", "texniki tərcümə", "tibbi tərcümə", "ixtisaslı tərcüməçi", "terminologiya"],
  },
  {
    id: "akademik-bicim-korunur",
    category: "services",
    priority: 83,
    q: "Akademik tərcümədə istinadlar və format qorunurmu?",
    a: "Bəli. Dissertasiya, məqalə və akademik mətnlərdə ədəbiyyat siyahısının düzümü, istinadlar və format mümkün qədər qorunur; akademik üsluba uyğun tərcümə edilir.",
    keywords: ["akademik tərcümə", "dissertasiya", "məqalə", "ədəbiyyat siyahısı"],
  },
  {
    id: "lokalizasyon-nedir",
    category: "services",
    priority: 84,
    q: "Lokalizasiya sadəcə söz tərcüməsidir? SEO nəzərə alınırmı?",
    a: "Xeyr. Lokalizasiya mətni hədəf mədəniyyətə və istifadəyə uyğunlaşdırmağı əhatə edir; interfeys, tarix/valyuta formatları və ifadə tərzi hədəf auditoriyaya görə tənzimlənir. Veb sayt lokalizasiyasında tələbinizə görə hədəf dildəki açar sözlər və SEO uyğunluğu nəzərə alına bilər.",
    keywords: ["lokalizasiya", "yerliləşdirmə", "veb tərcümə", "seo", "tətbiq tərcüməsi"],
  },
  {
    id: "kurumsal-marka-dili",
    category: "services",
    priority: 85,
    q: "Korporativ mətnlərdə brend dili qorunurmu?",
    a: "Bəli. Korporativ tərcümələrdə terminologiya bankası və üslub bələdçisi ilə brend diliniz və ton uyğunluğunuz qorunur.",
    keywords: ["brend dili", "korporativ ton", "üslub bələdçisi"],
  },
  {
    id: "vize-diploma-hangi-hizmet",
    category: "services",
    priority: 86,
    q: "Viza və ya diplom kimi sənədlər üçün hansı xidmət lazımdır?",
    a: "Viza müraciətləri və diplom tərcümələrində çox vaxt andlı tərcümə əsas tələbdir; bəzi nümayəndəliklər və ya qurumlar əlavə olaraq notariat təsdiqi və ya apostil istəyə bilər. Qəti tələb müraciət etdiyiniz konsulluğa və ya quruma görə dəyişir.",
    keywords: ["viza sənədi", "diplom tərcüməsi", "transkript", "konsulluq", "viza tərcümə"],
  },
  {
    id: "belge-turu-listede-yok",
    category: "services",
    priority: 87,
    q: "Sənəd növüm siyahıda yoxdursa nə seçməliyəm?",
    a: "Sənəd növünüz siyahıda yoxdursa, ən yaxın seçimi işarələyib sifariş qeydinə izahat əlavə edə bilərsiniz. İstəsəniz, dəstək xəttimiz düzgün seçimdə kömək edir.",
    keywords: ["sənəd növü siyahıda yox", "digər sənəd", "siyahıdan kənar"],
  },

  // ——— TƏHVİL VƏ MÜDDƏT ———
  {
    id: "teslim-suresi-nasil-hesaplanir",
    category: "delivery",
    priority: 88,
    q: "Təhvil müddəti necə hesablanır və harada göstərilir?",
    a: "Müddət sənədin uzunluğuna, dil cütünə, xidmət növünə və əlavə xidmətlərə görə hesablanır və Qiymət Hesabla ekranında təxmini təhvil tarixi kimi göstərilir. Notariat/apostil tələb edən işlərdə bu müddətə əlavə günlər əlavə oluna bilər; təhvil tarixi dəyişərsə məlumatlandırılırsınız.",
    keywords: ["təhvil müddəti hesablama", "təxmini təhvil", "nə vaxt hazır"],
  },
  {
    id: "ayni-gun-teslimat",
    category: "delivery",
    priority: 89,
    q: "Eyni gün və ya 24 saat ərzində təhvil mümkündürmü?",
    a: "Qısa sənədlər üçün sürətli/təcili təhvil çox vaxt mümkündür; mövcudluq sənədin uzunluğuna və dilinə görə dəyişir. Təcili təhvildə də keyfiyyət nəzarəti mərhələləri qorunur və seçim ilkin qiymət ekranında əlavə maddə kimi göstərilir.",
    keywords: ["eyni gün", "24 saat", "sürətli təhvil", "təcili"],
  },
  {
    id: "hafta-sonu-tatil",
    category: "delivery",
    priority: 90,
    q: "Həftə sonu və ya iş saatlarından kənar sifarişlər nə vaxt işlənir?",
    a: "Sənəd yükləmə, qiymət almaq və sifariş yaratmanı günün istənilən saatında edə bilərsiniz. İş saatlarından kənar və bayram günlərində verilən sifarişlər ilk iş saatlarında işlənir; təxmini təhvil müddəti buna görə göstərilir.",
    keywords: ["həftə sonu", "bayram", "iş saatlarından kənar", "gecə sifariş"],
  },
  {
    id: "dijital-teslim-format",
    category: "delivery",
    priority: 91,
    q: "Rəqəmsal təhvil necə edilir, hansı formatda alıram?",
    a: "Tamamlanan tərcümə endirilə bilən keçid və ya e-poçt vasitəsilə rəqəmsal şəkildə təhvil verilir. Ehtiyacınıza görə PDF və ya redaktə oluna bilən Word (DOCX) formatında ala bilərsiniz; orijinal format mümkün qədər qorunur.",
    keywords: ["rəqəmsal təhvil", "word təhvil", "pdf təhvil", "endirmə"],
  },
  {
    id: "kargo-kapsam-takip",
    category: "delivery",
    priority: 92,
    q: "Kuryer hansı bölgələrə göndərilir və izlənilə bilərmi?",
    a: "Orijinal əl imzalı/möhürlü sənədlər Türkiyənin hər yerinə kuryerlə göndərilir; tələbinizə görə xaricə də fiziki göndəriş edilə bilər. Kuryer izləmə məlumatı sizinlə paylaşılır və göndəriş müddəti ümumi təhvil müddətinə əlavə olunur.",
    keywords: ["kuryer bölgə", "kuryer izləmə", "xaricə göndəriş", "göndəriş müddəti"],
  },
  {
    id: "kismi-teslimat",
    category: "delivery",
    priority: 93,
    q: "Uzun layihələr hissə-hissə (qismən) təhvil verilə bilərmi?",
    a: "Bəli. Yüksək həcmli və ya uzun layihələr tələbinizə görə hissələr şəklində təhvil verilə bilər. Beləliklə sənədlərinizi gözləmədən istifadə etməyə başlaya bilərsiniz.",
    keywords: ["qismən təhvil", "hissə-hissə", "bölmə təhvili"],
  },

  // ——— ANDLI TƏRCÜMƏ ———
  {
    id: "yeminli-tercuman-kim",
    category: "sworn",
    priority: 94,
    q: "Andlı tərcüməçi kimdir?",
    a: "Andlı tərcüməçi, notarius qarşısında and içərək tərcümələrini imza və möhürü ilə təsdiqləmək səlahiyyəti qazanmış tərcüməçidir. Bu təsdiq tərcümənin orijinala uyğunluğuna dair bir bəyandır.",
    keywords: ["andlı tərcüməçi", "andlı tərcüməçi kim", "təsdiqli tərcüməçi"],
  },
  {
    id: "yeminli-ne-zaman-gerekli",
    category: "sworn",
    priority: 95,
    q: "Andlı tərcümə nə vaxt lazımdır?",
    a: "Rəsmi qurum, məhkəmə, konsulluq və universitet müraciətlərində çox vaxt andlı tərcümə tələb olunur. Lakin hər sənəd üçün məcburi deyil; qəti tələb sənədi istəyən qurum tərəfindən müəyyən edilir.",
    keywords: ["andlı nə vaxt", "andlı lazımdır", "harada tələb olunur"],
  },
  {
    id: "yeminli-nerede-gecerli",
    category: "sworn",
    priority: 96,
    q: "Andlı tərcümə məhkəmədə, konsullluqda və xaricdə etibarlıdırmı?",
    a: "Andlı tərcümə bir çox rəsmi işdə və müraciətdə istifadə oluna bilər. Lakin bir qurumun sənədi qəbul şərtləri onun öz qanunvericiliyinə bağlıdır; xüsusən xaricdə notariat təsdiqi və ya apostil də tələb oluna bilər. Qəbul şərtlərini müvafiq qurumdan təsdiqləməniz tövsiyə olunur.",
    keywords: ["məhkəmə", "konsulluq", "xaricdə etibarlı", "universitet müraciəti"],
  },
  {
    id: "dijital-imzali-yeminli",
    category: "sworn",
    priority: 97,
    q: "Rəqəmsal/e-imzalı andlı tərcümə edilə bilərmi?",
    a: "Xeyr. Andlı tərcümə tərcüməçinin orijinal əl imzası və möhürü ilə hazırlanır və fiziki olaraq kuryerlə təhvil verilir.",
    keywords: ["e-imza", "rəqəmsal andlı", "elektron imza", "orijinal əl imzası", "möhür"],
  },
  {
    id: "yeminli-orijinal-gerekir",
    category: "sworn",
    priority: 98,
    q: "Andlı tərcümədə sənədin orijinalı lazımdırmı?",
    a: "Tərcümə çox vaxt sənədin aydın nüsxəsi (skan/foto) üzərindən edilə bilər. Lakin notariat təsdiqi lazımdırsa, həmin əməliyyat üçün sənədin əsli və ya təsdiqli nüsxəsi tələb oluna bilər.",
    keywords: ["orijinal sənəd", "əsli lazımdır", "nüsxə andlı"],
  },
  {
    id: "yeminli-gecerlilik-suresi",
    category: "sworn",
    priority: 99,
    q: "Andlı tərcümənin etibarlılıq müddəti varmı?",
    a: "Tərcümənin özü müddətlə məhdud deyil; lakin bəzi qurumlar cari tarixli sənəd istəyə bilər. Bu, sənədi qəbul edəcək qurumun şərtinə bağlıdır.",
    keywords: ["etibarlılıq müddəti", "andlı müddət", "nə qədər etibarlı"],
  },
  {
    id: "kurum-belgeyi-kabul-etmezse",
    category: "sworn",
    priority: 100,
    q: "Qurum andlı tərcüməni qəbul etməzsə nə edilir?",
    a: "Qəbul şərtləri qurumdan quruma dəyişə bilər. Qurumun xüsusi format və ya təsdiq tələbi varsa, bunu bizə çatdırdığınız halda lazımi düzəlişi edirik. Yekun qəbul qərarı müvafiq quruma aiddir.",
    keywords: ["qəbul etməzsə", "qurum imtinası", "format tələbi"],
  },

  // ——— NOTARİAT VƏ APOSTİL ———
  {
    id: "noter-onayli-nedir",
    category: "notary",
    priority: 101,
    q: "Notariat təsdiqli tərcümə nədir?",
    a: "Notariat təsdiqli tərcümə, andlı tərcümənin əlavə olaraq notarius tərəfindən təsdiqlənməsidir. Bu təsdiq tərcümənin rəsmi etibarlılığını gücləndirir və bəzi qurumlar tərəfindən tələb olunur.",
    keywords: ["notariat təsdiqli tərcümə", "notarial təsdiq", "notariat nədir"],
  },
  {
    id: "noter-yeminli-fark",
    category: "notary",
    priority: 102,
    q: "Notariat təsdiqi ilə andlı tərcümə arasındakı fərq nədir?",
    a: "Andlı tərcümə tərcüməçinin təsdiqini, notariat təsdiqi isə bu tərcümənin notarius tərəfindən təsdiqlənməsini ifadə edir. Notariat təsdiqi andlı tərcümənin üzərinə əlavə olunan əlavə rəsmi addımdır.",
    keywords: ["notariat andlı fərq", "təsdiq fərqi"],
  },
  {
    id: "notere-gitmem-gerekir-mi",
    category: "notary",
    priority: 103,
    q: "Notariat əməliyyatları üçün notariusa getməliyəmmi?",
    a: "Əksər hallarda notariat əməliyyatlarını sizin adınıza apara bilərik; hər halda notariusa şəxsən gəlməyiniz lazım deyil. Sənədin əsli lazımdırsa, bunu əvvəlcədən bildiririk.",
    keywords: ["notariusa getmə", "notariat əməliyyatı", "vəkalətlə notariat"],
  },
  {
    id: "apostil-nedir",
    category: "notary",
    priority: 104,
    q: "Apostil nədir və notariat təsdiqindən fərqi nədir?",
    a: "Apostil, bir rəsmi sənədin başqa ölkədə etibarlı sayılması üçün səlahiyyətli orqan tərəfindən verilən beynəlxalq təsdiqdir və Haaqa Konvensiyasının tərəfi olan ölkələr arasında etibarlıdır. Notariat təsdiqi isə ölkə daxilindəki bir təsdiq əməliyyatıdır; ikisi fərqli məqsədlərə xidmət edir.",
    keywords: ["apostil nədir", "apostil notariat fərq", "haaqa"],
  },
  {
    id: "apostil-once-mi-ceviri-once-mi",
    category: "notary",
    priority: 105,
    q: "Apostil əvvəl, yoxsa tərcümə əvvəl edilir?",
    a: "Sıralama sənədin növünə və istifadə olunacağı ölkənin şərtlərinə görə dəyişir. Bəzi hallarda əvvəl sənədə apostil alınır, sonra tərcümə edilir; bəzilərində tərsi keçərlidir. Düzgün sıranı birlikdə müəyyən edə bilərik.",
    keywords: ["apostil sırası", "əvvəl tərcümə əvvəl apostil", "ardıcıllıq"],
  },
  {
    id: "yabanci-belge-turkiye",
    category: "notary",
    priority: 106,
    q: "Xarici sənəd Türkiyədə istifadə olunacaqsa proses necədir?",
    a: "Xaricdən gələn sənəd çox vaxt əvvəl müvafiq ölkədə apostillənir, sonra Türkiyədə andlı tərcüməsi (lazım gələrsə notariat təsdiqi) edilir. Qəti proses sənədi istəyən Türk quruma görə dəyişir.",
    keywords: ["xarici sənəd türkiyə", "gələn sənəd", "xaricdən sənəd"],
  },
  {
    id: "turk-belge-yurt-disi",
    category: "notary",
    priority: 107,
    q: "Türk sənədi xaricdə istifadə olunacaqsa proses necədir?",
    a: "Türkiyədə tərtib olunan sənədə çox vaxt apostil alınır və hədəf dilə andlı tərcüməsi edilir. Hədəf ölkə Haaqa Konvensiyasının tərəfi deyilsə, apostil əvəzinə konsulluq təsdiqi tələb oluna bilər.",
    keywords: ["türk sənədi xaric", "gedən sənəd", "konsulluq təsdiqi"],
  },
  {
    id: "hangi-onay-gerekli-bilinmiyor",
    category: "notary",
    priority: 109,
    q: "Notariat və ya apostil lazım olub-olmadığı necə öyrənilir?",
    a: "Ən etibarlı yol sənədi istəyən quruma müraciət etməkdir. İstəsəniz, dəstək xəttimiz geniş yayılmış təcrübələr barədə yol göstərir; lakin qəti tələb quruma və ölkəyə görə dəyişir.",
    keywords: ["hansı təsdiq", "təsdiq lazımdır", "notariat yoxsa apostil"],
  },
  {
    id: "kesin-kabul-garantisi",
    category: "notary",
    priority: 110,
    q: "TercümExpert qəti qəbul zəmanəti verirmi?",
    a: "Tərcümənin və təsdiqlərin doğru və tam hazırlanmasını təmin edirik; lakin sənədin qəbuluna dair şərtlər sənədi istəyən qurum tərəfindən müəyyən edilir. Bu səbəbdən şərtsiz qəbul zəmanəti verilə bilməz; qurumun xüsusi tələblərini bizə çatdırsanız lazımi düzəlişi edirik.",
    keywords: ["qəbul zəmanəti", "qəti qəbul", "zəmanət"],
  },

  // ——— KEYFİYYƏT VƏ DÜZƏLİŞ ———
  {
    id: "tercumanlar-nasil-secilir",
    category: "quality",
    priority: 111,
    q: "Tərcüməçilər necə seçilir və ixtisasları necə müəyyən olunur?",
    a: "Tərcüməçilər dil cütünə və sənədin ixtisas sahəsinə görə müəyyən edilir; hüquqi sənəd hüquq, tibbi sənəd səhiyyə sahəsində təcrübəli tərcüməçiyə təyin olunur. Sahə təcrübəsi və dil səriştəsi nəzərə alınaraq ən uyğun tərcüməçi cəlb olunur.",
    keywords: ["tərcüməçi seçimi", "tərcüməçi necə", "ixtisas", "sahə mütəxəssisi"],
  },
  {
    id: "kalite-kontrol",
    category: "quality",
    priority: 112,
    q: "Tərcümə keyfiyyət nəzarətindən keçirmi?",
    a: "Bəli. Tərcümələr orfoqrafiya, terminologiya, rəqəm/ad/tarix uyğunluğu və format baxımından yoxlanılır. Sənədin növünə və xidmət səviyyəsinə görə müstəqil redaktor/son oxu mərhələsi tətbiq oluna bilər.",
    keywords: ["keyfiyyət nəzarəti", "son oxu", "redaktor", "yoxlama"],
  },
  {
    id: "ceviri-bellegi",
    category: "quality",
    priority: 113,
    q: "Tərcümə yaddaşı və ya terminologiya siyahısı istifadə olunurmu?",
    a: "Bəli, xüsusən texniki və korporativ layihələrdə tərcümə yaddaşı və terminologiya siyahıları istifadə edilərək uyğunluq təmin edilir. Öz termin siyahınızı da paylaşa bilərsiniz; əvvəlki layihələrdəki terminologiya qorunur.",
    keywords: ["tərcümə yaddaşı", "terminologiya siyahısı", "uyğunluq"],
  },
  {
    id: "revize-kapsami",
    category: "quality",
    priority: 114,
    q: "Düzəliş hansı halları əhatə edir və nə vaxt tələb edilir?",
    a: "Düzəliş; tərcümə xətası, orfoqrafiya, uyğunsuzluq və çatışmayan aktarma kimi halları əhatə edir. Mənbə mətnin sonradan dəyişdirilməsi və ya yeni məzmun əlavə edilməsi yeni iş sayıla bilər. Düzəliş tələbinizi təhvildən sonra ağlabatan müddət ərzində e-poçt və ya WhatsApp ilə çatdırmağınız tövsiyə olunur.",
    keywords: ["düzəliş əhatəsi", "korreksiya əhatəsi", "düzəliş müddəti", "nə vaxt düzəliş"],
  },
  {
    id: "tercuman-degisikligi",
    category: "quality",
    priority: 115,
    q: "Tərcümədən razı qalmasam nə olur, tərcüməçi dəyişdirilə bilərmi?",
    a: "Tərcümədən razı qalmasanız, vəziyyəti qiymətləndirir, lazım gəldikdə fərqli bir tərcüməçi və ya redaktorla düzəliş təmin edirik. Məqsəd nəticənin gözləntinizi qarşılamasıdır.",
    keywords: ["tərcüməçi dəyişikliyi", "razı qalmama", "bəyənmədim"],
  },
  {
    id: "dogruluk-garanti",
    category: "quality",
    priority: 116,
    q: "Tərcümənin doğruluğu zəmanət altındadırmı?",
    a: "Tərcümələrinizi ixtisaslı tərcüməçilər hazırlayır və keyfiyyət nəzarətindən keçiririk; doğruluq üçün lazımi diqqəti göstəririk. Yenə də sənədin rəsmi qəbul şərtləri sənədi istəyən quruma görə dəyişə bilər.",
    keywords: ["doğruluq zəmanəti", "keyfiyyət zəmanəti", "təminat"],
  },
  {
    id: "makine-cevirisi-kullaniliyor",
    category: "quality",
    priority: 117,
    q: "Tamamilə avtomatik/maşın tərcüməsi istifadə olunurmu?",
    a: "Xeyr. Tərcümələr əvvəldən sona qədər peşəkar insan tərcüməçilər tərəfindən edilir; maşına buraxılan avtomatik tərcümə təqdim olunmur. Uyğunluq üçün yalnız peşəkar tərcümə alətləri (CAT aləti) dəstəyi istifadə olunur. Andlı tərcümələrdə tərcüməçinin möhürü və imzası ilə orijinala uyğunluq bəyanı yer alır.",
    keywords: ["maşın tərcüməsi", "avtomatik tərcümə", "süni intellekt tərcüməsi", "tərcümə bəyanı"],
  },

  // ——— MƏXFİLİK VƏ TƏHLÜKƏSİZLİK ———
  {
    id: "dosyalari-kimler-gorur",
    category: "privacy",
    priority: 118,
    q: "Yüklənən faylları kimlər görə bilər, üçüncü şəxslərlə paylaşılırmı?",
    a: "Fayllarınıza yalnız sifarişinizdə çalışan tərcüməçi və müvafiq komanda çıxış edə bilər. Sənədləriniz xidmətin tələb etdiyi hallar istisna olmaqla üçüncü şəxslərlə paylaşılmır və marketinq məqsədilə istifadə edilmir.",
    keywords: ["kimlər görür", "çıxış", "üçüncü şəxs", "paylaşım"],
  },
  {
    id: "nda-imzalanabilir",
    category: "privacy",
    priority: 119,
    q: "Məxfilik sazişi (NDA) imzalana bilərmi?",
    a: "Bəli. Xüsusən korporativ layihələrdə tələbinizə görə məxfilik sazişi (NDA) tərtib edilə bilər. Tərcüməçilərimiz də məxfilik öhdəliyinə tabedir.",
    keywords: ["nda", "məxfilik sazişi", "gizlilik sazişi"],
  },
  {
    id: "kvkk-uyumlu",
    category: "privacy",
    priority: 120,
    q: "KVKK-ya uyğun çalışırsınız, şəxsi məlumatlar necə qorunur?",
    a: "Bəli. Şəxsi məlumatlarınız KVKK-ya uyğun proseslərlə işlənir; yalnız xidmətin tələb etdiyi ölçüdə istifadə olunur və təhlükəsiz şəkildə saxlanılır. Məlumatlarınızı uyğun təhlükəsizlik tədbirləri ilə qorumağı əsas götürürük.",
    keywords: ["kvkk", "şəxsi məlumat", "məlumatların qorunması", "kvkk uyğun"],
  },
  {
    id: "sifreli-aktarim",
    category: "privacy",
    priority: 121,
    q: "Fayllar şifrələnmiş şəkildə ötürülürmü?",
    a: "Bəli. Fayllarınız şifrələnmiş bağlantı üzərindən ötürülür və təhlükəsiz mühitdə işlənir. Məqsədimiz məlumatlarınızı uyğun təhlükəsizlik tədbirləri ilə qorumaqdır.",
    keywords: ["şifrələnmiş", "təhlükəsiz ötürmə", "şifrələmə"],
  },
  {
    id: "odeme-bilgileri-saklanir",
    category: "privacy",
    priority: 122,
    q: "Ödəniş/kredit kartı məlumatları saxlanılırmı?",
    a: "Kart məlumatlarınız TercümExpert tərəfindən saxlanılmır; ödəniş əməliyyatları təhlükəsiz ödəniş infrastrukturu üzərindən aparılır.",
    keywords: ["ödəniş məlumatı", "kredit kartı təhlükəsiz", "kart saxlama"],
  },
  {
    id: "belgeler-ai-egitimi",
    category: "privacy",
    priority: 123,
    q: "Sənədlərim model təlimi üçün istifadə olunurmu?",
    a: "Xeyr. Sənədləriniz yalnız sizin sifarişiniz üçün istifadə olunur; hər hansı model təlimi məqsədilə və ya xarici sistemlərlə paylaşılmır. Tərcüməniz insan tərcüməçilər tərəfindən məxfilik əsasında hazırlanır.",
    keywords: ["məlumat təlimi", "model təlimi", "məlumat istifadəsi", "sənəd məxfiliyi"],
  },
  {
    id: "saglik-kimlik-guvenli",
    category: "privacy",
    priority: 124,
    q: "Şəxsiyyət vəsiqəsi, pasport və ya sağlamlıq kimi həssas sənədlər təhlükəsizdirmi?",
    a: "Bəli. Həssas sənədlər də daxil olmaqla bütün fayllarınız məxfilik əsasında, KVKK-ya uyğun və şifrələnmiş şəkildə işlənir. Çıxış yalnız çalışan komanda ilə məhduddur; yüksək məxfilik tələb edən sənədlər üçün NDA və məhdud çıxış kimi əlavə tədbirlər tətbiq oluna bilər.",
    keywords: ["şəxsiyyət vəsiqəsi təhlükəsiz", "pasport", "sağlamlıq məlumatı", "həssas sənəd"],
  },
  {
    id: "hesap-silinince-belgeler",
    category: "privacy",
    priority: 125,
    q: "Hesab silindikdə və ya tələb edildikdə sənədlər silinirmi?",
    a: "Tələbiniz əsasında sənədləriniz və şəxsi məlumatlarınız qanuni saxlama öhdəlikləri saxlanılmaqla silinir. Hesab silmə və ya məlumat silmə tələbinizi dəstək xəttimizə çatdıra bilərsiniz.",
    keywords: ["hesab silmə", "məlumat silmə", "sənəd silmə"],
  },

  // ——— KORPORATİV XİDMƏTLƏR ———
  {
    id: "kurumsal-hesap-nasil",
    category: "corporate",
    priority: 126,
    q: "Korporativ hesab necə açılır, müraciətdən sonra nə olur?",
    a: "Korporativ səhifəsindəki müraciət formasını doldurmanız kifayətdir; komandamız adətən 1 iş günü ərzində sizinlə əlaqə saxlayır, ehtiyaclarınızı qiymətləndirir və sizə uyğun şərtləri müəyyən edir.",
    keywords: ["korporativ hesab", "şirkət hesabı", "korporativ müraciət", "müraciətdən sonra"],
  },
  {
    id: "sirket-adina-siparis",
    category: "corporate",
    priority: 127,
    q: "Şirkət adına sifariş verilə bilərmi?",
    a: "Bəli. Şirkət məlumatlarınızla sifariş verə, korporativ faktura və lazım gəldikdə ödəniş müddəti seçimlərindən faydalana bilərsiniz.",
    keywords: ["şirkət adına", "korporativ sifariş", "şirkət sifarişi"],
  },
  {
    id: "ozel-hesap-yoneticisi",
    category: "corporate",
    priority: 128,
    q: "Korporativ müştərilərə xüsusi hesab meneceri təyin olunurmu?",
    a: "Korporativ müştərilərə proseslərini izləyən xüsusi bir hesab meneceri təyin oluna bilər. Beləliklə tələblərinizi tək nöqtədən idarə edə və prioritet dəstək ala bilərsiniz.",
    keywords: ["hesab meneceri", "xüsusi menecer", "korporativ dəstək", "prioritet dəstək"],
  },
  {
    id: "toplu-fatura",
    category: "corporate",
    priority: 129,
    q: "Aylıq toplu faktura və ödəniş müddəti almaq olarmı?",
    a: "Bəli. Korporativ müştərilərə aylıq toplu fakturalaşdırma və 15-30 günə qədər ödəniş müddəti seçimləri təqdim oluna bilər. Təfərrüatlar əməkdaşlıq çərçivəsində müəyyən edilir.",
    keywords: ["toplu faktura", "aylıq faktura", "ödəniş müddəti", "korporativ ödəniş"],
  },
  {
    id: "terminoloji-bankasi",
    category: "corporate",
    priority: 130,
    q: "Şirkətə özəl terminologiya bankası yaradıla bilərmi?",
    a: "Bəli. Korporativ layihələrdə brendinizə özəl terminologiya bankası və üslub bələdçisi yaradılaraq bütün tərcümələrdə brend diliniz və uyğunluq qorunur.",
    keywords: ["terminologiya bankası", "üslub bələdçisi", "korporativ terminologiya"],
  },
  {
    id: "sabit-tercuman",
    category: "corporate",
    priority: 131,
    q: "Müntəzəm layihələrdə eyni tərcüməçilərlə işləmək olarmı?",
    a: "Bəli. Müntəzəm korporativ layihələrdə davamlılıq və uyğunluq təmin etmək üçün sabit bir tərcüməçi/komanda hovuzu yaradıla bilər.",
    keywords: ["sabit tərcüməçi", "eyni komanda", "korporativ komanda"],
  },
  {
    id: "kurumsal-raporlama",
    category: "corporate",
    priority: 132,
    q: "Sifariş və xərc hesabatı almaq olarmı?",
    a: "Korporativ müştərilərə sifariş və xərclərinə yönəlik hesabat təqdim oluna bilər; ehtiyac olduqda şöbə əsaslı bölgü aparıla bilər. Korporativ əməkdaşlıqlarda xidmət səviyyəsi (SLA) və məxfilik (NDA) sazişləri də tərtib edilə bilər.",
    keywords: ["hesabat", "xərc hesabatı", "sifariş hesabatı", "sla"],
  },
  {
    id: "kucuk-isletme",
    category: "corporate",
    priority: 133,
    q: "Kiçik müəssisələr də korporativ xidmət ala bilərmi, həcm məcburidirmi?",
    a: "Bəli. Korporativ xidmətlərdən faydalanmaq üçün müəyyən bir ölçü və ya minimum həcm şərti yoxdur; kiçik müəssisələr də ödəniş müddəti, terminologiya və prioritet dəstək kimi üstünlüklərdən faydalana bilər.",
    keywords: ["kiçik müəssisə", "kob", "həcm məcburi", "minimum həcm"],
  },
  {
    id: "uluslararasi-sirket",
    category: "corporate",
    priority: 134,
    q: "Beynəlxalq şirkətlərə və çoxdilli layihələrə xidmət göstərilirmi?",
    a: "Bəli. Bir neçə ölkə və dil əhatə edən layihələr koordinasiya olunaraq aparıla bilər; terminologiya uyğunluğu mərkəzi şəkildə təmin edilir. Korporativ layihələrdə andlı tərcümə, lazım gəldikdə notariat təsdiqi və apostil prosesləri də aparıla bilər.",
    keywords: ["beynəlxalq şirkət", "çoxdilli layihə", "korporativ notariat apostil"],
  },

  // ——— TEXNİKİ DƏSTƏK ———
  {
    id: "nasil-uye-olunur",
    category: "support",
    priority: 135,
    q: "Sayta necə üzv olmaq olar?",
    a: "Üzvlük üçün ad, soyad və e-poçt məlumatlarınızı daxil edib e-poçtunuza gələn təsdiq kodunu təsdiqləməniz kifayətdir. Apple və ya Google hesabınızla da sürətlə üzv ola bilərsiniz.",
    keywords: ["üzv olma", "qeydiyyat", "hesab yaratma"],
  },
  {
    id: "giris-sifre-sorunu",
    category: "support",
    priority: 136,
    q: "Daxil ola bilmirsinizsə və ya şifrəni unutmusunuzsa nə etməli?",
    a: "Əvvəlcə e-poçt və şifrənizi yoxlayın; şifrənizi unutmusunuzsa, giriş ekranındakı 'Şifrəni unutdum' bağlantısı ilə e-poçtunuza sıfırlama təlimatı göndərin. Problem davam edərsə spam qovluğunu yoxlayın və ya dəstək xəttimizə yazın.",
    keywords: ["daxil ola bilmirəm", "şifrə sıfırlama", "şifrəni unutdum", "parol", "giriş"],
  },
  {
    id: "dogrulama-epostasi-gelmezse",
    category: "support",
    priority: 137,
    q: "Təsdiq e-poçtu gəlmirsə nə etməli?",
    a: "Bir neçə dəqiqə gözləyin, spam/lazımsız qovluğunu yoxlayın və kodu yenidən göndərin. E-poçt ünvanınızı doğru yazdığınızdan əmin olun; problem davam edərsə dəstək xəttimizə yazın.",
    keywords: ["təsdiq e-poçtu", "kod gəlmədi", "e-poçt gəlmir", "təsdiq kodu"],
  },
  {
    id: "dosya-yuklenmiyor",
    category: "support",
    priority: 138,
    q: "Fayl yüklənmirsə və ya dəstəklənməyən fayl xətası alırsınızsa nə etməli?",
    a: "Fayl ölçüsünü (100 MB-a qədər) və formatını yoxlayın, səhifəni və brauzerinizi yeniləyin. Format dəstəklənmirsə, faylı PDF və ya DOCX kimi bir formata çevirə və ya mətni 'Mətn Daxil Et' bölməsinə yapışdıra bilərsiniz. Problem davam edərsə dəstək xəttimizə yazın.",
    keywords: ["fayl yüklənmir", "yükləmə xətası", "dəstəklənməyən fayl", "format xətası"],
  },
  {
    id: "kelime-sayisi-yanlis",
    category: "support",
    priority: 139,
    q: "Söz sayı səhv görünürsə nə etməli?",
    a: "Avtomatik say xüsusən skan edilmiş/təsvirli sənədlərdə fərqli ola bilər. Doğru nəticə üçün mətni 'Mətn Daxil Et' ilə paylaşa və ya sifarişə qeyd əlavə edə bilərsiniz; yekun say komandamız tərəfindən təsdiqlənir və qiymət buna görə dəqiqləşir.",
    keywords: ["söz səhv", "say xətası", "söz sayı səhv"],
  },
  {
    id: "odeme-basarisiz",
    category: "support",
    priority: 140,
    q: "Ödəniş uğursuz olarsa və ya iki dəfə çəkilərsə nə etməli?",
    a: "Kart məlumatlarınızı və limitinizi yoxlayıb yenidən cəhd edin; fərqli bir üsul (kart/bank köçürməsi) da istifadə edə bilərsiniz. Məbləğ çəkildiyi halda sifariş yaradılmayıbsa və ya təkrar çəkilmə baş veribsə, qəbzinizlə birlikdə dəstək xəttimizə yazın; artıq məbləğ geri qaytarılır.",
    keywords: ["ödəniş uğursuz", "ödəniş xətası", "iki dəfə çəkildi", "təkrar ödəniş"],
  },
  {
    id: "teslim-dosyasi-inmiyor",
    category: "support",
    priority: 141,
    q: "Təhvil faylı endirilmirsə nə etməli?",
    a: "Bağlantını və brauzerinizi yeniləyin; endirmə bağlantısının müddəti bitibsə dəstək xəttimizdən yeni bağlantı tələb edə bilərsiniz.",
    keywords: ["fayl endirilmir", "endirmə problemi", "təhvil endirilmir", "bağlantı müddəti"],
  },
  {
    id: "mobil-tarayici-destegi",
    category: "support",
    priority: 142,
    q: "Mobil cihazdan işləmək olarmı, hansı brauzerlər dəstəklənir?",
    a: "Sayt mobil uyğundur; iPhone, Android telefon və planşetlərdən sənəd yükləyib sifariş verə bilərsiniz. Güncəl Chrome, Safari, Edge və Firefox brauzerləri ilə saytı problemsiz istifadə edə bilərsiniz.",
    keywords: ["mobil", "telefon", "iphone android", "planşet", "brauzer", "chrome safari"],
  },
  {
    id: "ai-asistan-ne-yapar",
    category: "support",
    priority: 143,
    q: "Süni intellekt dəstəkli çat köməkçisi nə edə bilər?",
    a: "Çat köməkçisi; proses, xidmət növləri və ümumi suallarınızda dərhal yönləndirmə edir və sizi qiymət almaq kimi doğru addımlara çatdırır. Rəsmi qəbul şərtləri və hüquqi tələblər (notariat/apostil kimi) barədə qəti və bağlayıcı qərar verə bilməz; bu məsələlərdə müvafiq quruma müraciət etməlisiniz.",
    keywords: ["çat köməkçisi", "çatbot", "süni intellekt köməkçi", "çatbot qiymət"],
  },
  {
    id: "insana-baglanma",
    category: "support",
    priority: 144,
    q: "İnsan müştəri nümayəndəsinə necə qoşulmaq olar?",
    a: "Çat köməkçisi vasitəsilə tələb edərək və ya birbaşa WhatsApp və e-poçt yolu ilə insan dəstək xəttimizə çata bilərsiniz. Tələblər iş saatları ərzində cavablandırılır. Texniki problemləri ekran görüntüsü ilə çatdırmağınız həllini sürətləndirir.",
    keywords: ["insana qoşulma", "müştəri nümayəndəsi", "canlı dəstək", "ekran görüntüsü"],
  },
  {
    id: "hesap-bilgileri-guncelleme",
    category: "support",
    priority: 145,
    q: "Hesab və faktura məlumatları necə yenilənir, hesab necə silinir?",
    a: "Üzvsünüzsə, telefon, e-poçt və faktura məlumatlarınızı hesab ayarlarınızdan yeniləyə, hesabınızın silinməsini də buradan və ya dəstək xəttimizə tələb göndərərək təmin edə bilərsiniz. Tələbiniz əsasında məlumatlarınız qanuni öhdəliklər saxlanılmaqla silinir.",
    keywords: ["məlumat yeniləmə", "faktura məlumatı", "hesab ayarları", "hesab silmə"],
  },
  {
    id: "bildirim-tercihleri",
    category: "support",
    priority: 146,
    q: "Sifariş bildirişləri necə işləyir, WhatsApp bildirişi almaq olarmı?",
    a: "Sifariş statusu üçün e-poçt bildirişləri göndərilir; seçimlərinizə görə WhatsApp vasitəsilə də məlumatlandırma təmin edilə bilər. Bildiriş seçimlərinizi hesab ayarlarından və ya dəstək xəttimizdən tənzimləyə bilərsiniz.",
    keywords: ["bildiriş", "sms", "whatsapp bildiriş", "e-poçt bildiriş", "sifariş bildirişi"],
  },
]
