/**
 * FAQ data source (English). Pricing/payment logic may change later (§13).
 * Honesty rules: NO unverified ISO/certification claims; no physical office is
 * implied; no 24/7 human support is promised; the sworn / notarization /
 * apostille distinctions are preserved; no guaranteed institutional acceptance.
 * `priority` = global importance order (lower = higher up). The category view
 * uses the same order, so within-category ordering is derived from this value.
 */
import type { FaqCategory, FaqItem } from './faq-data'

export const FAQ_CATEGORIES_EN: FaqCategory[] = [
  { key: 'general', label: 'General' },
  { key: 'order', label: 'Order Process' },
  { key: 'pricing', label: 'Pricing & Payment' },
  { key: 'upload', label: 'File Upload' },
  { key: 'languages', label: 'Languages & Language Pairs' },
  { key: 'services', label: 'Service Types' },
  { key: 'delivery', label: 'Delivery & Turnaround' },
  { key: 'sworn', label: 'Sworn Translation' },
  { key: 'notary', label: 'Notarization & Apostille' },
  { key: 'quality', label: 'Quality & Revisions' },
  { key: 'privacy', label: 'Privacy & Security' },
  { key: 'corporate', label: 'Corporate Services' },
  { key: 'support', label: 'Technical Support' },
]

export const FAQ_ITEMS_EN: FaqItem[] = [
  // ——— ALL: highest-priority questions along the customer journey ———
  {
    id: 'nasil-fiyat-alirim',
    category: 'pricing',
    priority: 1,
    q: 'How do I get a quote?',
    a: "Go to the Get a Quote page and upload your document or paste your text; once you select the language pair and service type, your preliminary quote appears instantly. The price is based on the language pair, service type, word count, and any add-ons you choose.",
    keywords: ['get a quote', 'pricing', 'translation cost', 'price estimate', 'quote', 'how much'],
  },
  {
    id: 'dosya-nasil-yuklenir',
    category: 'upload',
    priority: 2,
    q: 'How do I upload my file?',
    a: "On the Get a Quote page, open the 'Upload File' tab and drag and drop your document or browse to select it. If you don't have a file, just paste your text into the 'Enter Text' tab. For text-based files, the system counts the words automatically.",
    keywords: ['upload file', 'add document', 'attach file', 'cannot upload', 'how to upload'],
  },
  {
    id: 'fiyatlandirma-neye-gore',
    category: 'pricing',
    priority: 3,
    q: 'How is pricing determined?',
    a: 'The price is based on the language pair, service type, document content, word count, subject area, and any add-ons you select. The amount shown on screen is a preliminary quote; the final price is confirmed after we review the document.',
    keywords: ['pricing', 'how is price set', 'cost factors', 'per word', 'rates'],
  },
  {
    id: 'teslim-suresi-ne-kadar',
    category: 'delivery',
    priority: 4,
    q: 'What is the turnaround time?',
    a: 'Turnaround depends on the length of the document, the language pair, the service type, and any add-ons you select. The quote screen shows an estimated delivery time specific to your order. You can shorten this with the rush delivery option.',
    keywords: ['turnaround time', 'delivery time', 'how many days', 'when delivered', 'how long'],
  },
  {
    id: 'yeminli-tercume-nedir',
    category: 'sworn',
    priority: 5,
    q: 'What is a sworn translation?',
    a: 'A sworn translation is a translation certified by a sworn translator with their signature and stamp, declaring it a true and accurate rendering of the original. It is frequently required for official applications. Whether it is required depends on the institution requesting the document.',
    keywords: ['sworn translation', 'certified translation', 'stamped translation', 'official translation', 'what is sworn'],
  },
  {
    id: 'hangi-dillerde-hizmet',
    category: 'languages',
    priority: 6,
    q: 'Which languages do you offer?',
    a: 'We work with Turkish as well as English, German, French, Spanish, Italian, Arabic, Russian, and more than 50 languages in total. For rare languages, translator availability and turnaround are confirmed separately for each order.',
    keywords: ['languages', 'which languages', 'language options', 'language pairs', 'how many languages'],
  },
  {
    id: 'noter-onayi-gerekir-mi',
    category: 'notary',
    priority: 7,
    q: 'Do I need notarization?',
    a: 'Notarization is not mandatory for every document; whether it is needed depends on the institution requesting the document and the intended use. For some procedures a sworn translation is enough, while others also require notarization. If you are unsure which certification you need, we can help guide you.',
    keywords: ['notarization', 'notary certification', 'notarized', 'do i need notary'],
  },
  {
    id: 'siparis-nasil-ilerler',
    category: 'order',
    priority: 8,
    q: 'How does the order process work?',
    a: 'Once you upload your document and approve the preliminary quote, your order is created and assigned to a translator who specializes in the relevant field. The translation goes through quality control; if needed, the notarization process is handled, and your document is delivered digitally and, when required, by courier.',
    keywords: ['order process', 'how it works', 'steps', 'workflow'],
  },
  {
    id: 'belgelerim-guvende-mi',
    category: 'privacy',
    priority: 9,
    q: 'Are my documents secure?',
    a: 'Yes. Your files are seen only by the team working on your order and are handled through encrypted transfer and KVKK-compliant processes. Your documents are never shared with third parties, and confidentiality is our priority.',
    keywords: ['security', 'confidentiality', 'document security', 'data security', 'kvkk'],
  },
  {
    id: 'cevirimi-kim-yapar',
    category: 'quality',
    priority: 10,
    q: 'Who translates my document?',
    a: 'Your translations are done by professional human translators experienced in the relevant field. A specialist translator is assigned based on the type of document, and every translation goes through quality control before delivery.',
    keywords: ['who translates', 'translator', 'human translator', 'linguist', 'who does it'],
  },
  {
    id: 'revize-hakki-var-mi',
    category: 'quality',
    priority: 11,
    q: 'Are revisions included?',
    a: 'Yes. Once a translation is delivered, you have the right to request revisions for corrections within the original scope. Fixes to spelling, names, dates, or consistency are included. Changing the source text afterward or adding new content may count as new work.',
    keywords: ['revisions', 'corrections', 'revision', 'redo translation', 'revision policy'],
  },
  {
    id: 'fiziksel-teslimat-yapiliyor-mu',
    category: 'delivery',
    priority: 12,
    q: 'Do you offer physical delivery?',
    a: 'Yes. While digital delivery is standard, documents with a wet-ink signature and stamp can be shipped to your address by courier. We ship throughout Türkiye and, on request, internationally. If you choose courier delivery, shipping time is added to the turnaround.',
    keywords: ['physical delivery', 'courier', 'shipping', 'delivery to address'],
  },
  {
    id: 'kurumsal-ozel-sartlar',
    category: 'corporate',
    priority: 13,
    q: 'Are there special terms for corporate clients?',
    a: 'Yes. Corporate clients enjoy volume-order advantages, payment-term options, terminology management, and a dedicated account manager. For details, fill out the application form on our Corporate page.',
    keywords: ['corporate', 'business', 'company terms', 'bulk order', 'corporate terms'],
  },
  {
    id: 'apostil-nasil-yurutulur',
    category: 'notary',
    priority: 14,
    q: 'How does the apostille process work?',
    a: "An apostille is a certification issued by the competent authority so that a document is recognized as valid abroad. We do not carry out the apostille process; you must obtain the apostille yourself from the competent authority in the country where your document was issued. We only provide the sworn translation of your apostilled documents. In countries that are not party to the Hague Convention, consular certification may be required instead of an apostille.",
    keywords: ['apostille', 'apostille process', 'apostille certification', 'valid abroad'],
  },
  {
    id: 'acil-teslimat-mumkun-mu',
    category: 'delivery',
    priority: 15,
    q: 'Is rush delivery possible?',
    a: 'Yes, rush delivery is available for many documents and shortens the turnaround. Rush delivery carries an additional fee, and its availability may vary depending on the length and language of the document. Quality-control steps are preserved even for rush orders.',
    keywords: ['rush delivery', 'fast delivery', 'same day', 'express', 'urgent'],
  },
  {
    id: 'odeme-nasil-yapilir',
    category: 'pricing',
    priority: 16,
    q: 'How do I pay?',
    a: 'Payments can be made by credit/debit card or bank transfer (wire/EFT); installment options may be available for credit cards. Corporate clients are also offered invoicing on payment terms (15–30 days). Payment is collected after you approve the preliminary quote.',
    keywords: ['payment', 'payment method', 'credit card', 'bank transfer', 'how to pay'],
  },
  {
    id: 'dosya-yuklemeden-fiyat',
    category: 'upload',
    priority: 17,
    q: 'Can I get a quote without uploading a file?',
    a: "Yes. If you don't have a file, paste your text into the 'Enter Text' tab to get a preliminary quote based on the word count.",
    keywords: ['quote without file', 'quote from text', 'no upload', 'text based quote'],
  },
  {
    id: 'belgenin-formati-korunur-mu',
    category: 'delivery',
    priority: 18,
    q: 'Is the document formatting preserved?',
    a: 'As much as possible, we keep the original page layout, tables, and formatting in the translation. Depending on your needs, the output can be delivered as a PDF or an editable Word (DOCX) file. For scanned or image-based documents, we provide a clean, organized layout rather than an exact replica.',
    keywords: ['formatting', 'layout', 'page layout', 'word', 'pdf', 'format preserved'],
  },
  {
    id: 'teslim-sonrasi-destek',
    category: 'quality',
    priority: 19,
    q: 'Can I get support after the translation is delivered?',
    a: 'Yes. After delivery, revision support is available for in-scope corrections, and you can reach our customer support line with any questions. You can send additional requests about your document by email or WhatsApp.',
    keywords: ['post delivery support', 'after delivery', 'help', 'support'],
  },
  {
    id: 'cok-sayfali-yuksek-hacim',
    category: 'order',
    priority: 20,
    q: 'How are multi-page or high-volume projects handled?',
    a: 'High-volume projects are carefully planned; when needed, multiple translators and editors are involved, and a shared glossary is used for terminology consistency. Long projects can be delivered in parts (partial delivery) if you prefer. For corporate projects, the process is coordinated by your account manager.',
    keywords: ['many pages', 'high volume', 'bulk work', 'large project', 'multiple documents'],
  },

  // ——— GENERAL ———
  {
    id: 'tercumexpert-nedir',
    category: 'general',
    priority: 21,
    q: 'What is TercümExpert?',
    a: 'TercümExpert is an online translation service provider offering sworn translation, notarized translation, legal, technical, medical, and academic translation, and web/mobile localization. You can upload your document, get a preliminary quote, and place your order entirely online.',
    keywords: ['tercumexpert', 'what is it', 'about', 'translation service', 'what do you do'],
  },
  {
    id: 'hangi-hizmetler',
    category: 'general',
    priority: 22,
    q: 'What services does TercümExpert offer?',
    a: 'We offer sworn and notarized translation, translation of apostilled documents, legal, technical, medical, and academic translation, and website and mobile app localization. You can choose the service that fits your needs on the Get a Quote screen.',
    keywords: ['services', 'what you offer', 'service types', 'which services'],
  },
  {
    id: 'kimler-hizmet-alabilir',
    category: 'general',
    priority: 23,
    q: 'Who can use your services?',
    a: 'Both individual customers and companies and organizations can use our services. From students to freelancers, and from small businesses to large enterprises, we offer solutions tailored to different needs.',
    keywords: ['who can use', 'individuals', 'businesses', 'companies', 'clients'],
  },
  {
    id: 'ofise-gelmek-gerekir-mi',
    category: 'general',
    priority: 24,
    q: 'Do I need to visit an office in person?',
    a: 'We do not have a physical office; our services are provided entirely online. You simply send your documents via secure upload, and delivery is made digitally and, where needed, by courier. For any questions you can reach us via WhatsApp or at info@tercumexpert.com.',
    keywords: ['office', 'in person', 'branch', 'address', 'visit required'],
  },
  {
    id: 'surec-cevrimici-mi',
    category: 'general',
    priority: 25,
    q: 'Can the whole process be handled online?',
    a: 'Yes. Uploading documents, approving the quote, payment, and digital delivery are all online. A courier is only involved when a physical, wet-ink signed document is required.',
    keywords: ['online', 'fully online', 'remote', 'internet', 'everything online'],
  },
  {
    id: 'yurt-disindan-hizmet',
    category: 'general',
    priority: 26,
    q: 'Can customers abroad use your services?',
    a: 'Yes. Because the process is online, you can upload documents and place orders from abroad. Digital delivery is available everywhere, and for wet-ink signed documents we can also ship internationally by courier.',
    keywords: ['abroad', 'international customers', 'from overseas', 'outside turkey'],
  },
  {
    id: 'uyelik-zorunlu-mu',
    category: 'general',
    priority: 27,
    q: 'Do I need an account to use your services?',
    a: 'An account is not required. However, to view the price and place an order, you need to enter your first name, last name, and email, then confirm the verification code sent to your email. If you like, you can create an account to keep track of your order history.',
    keywords: ['account', 'sign up', 'registration', 'required', 'without account'],
  },
  {
    id: 'uye-olmadan-fiyat',
    category: 'general',
    priority: 28,
    q: 'Can I get a quote without registering?',
    a: 'Yes, you can get a quote without creating a full account; you only need to verify your first name, last name, and email. Users who do not complete verification cannot view the price or place an order.',
    keywords: ['quote without account', 'no registration', 'verification code', 'email verification'],
  },
  {
    id: 'siparis-oncesi-danismanlik',
    category: 'general',
    priority: 29,
    q: 'Can I get advice before placing an order?',
    a: 'Yes. If you are not sure which service you need, you can get information via WhatsApp, email, or our AI-powered chat assistant. We will help you determine the right service and process based on the type of your document.',
    keywords: ['advice', 'consultation', 'ask a question', 'pre-order help'],
  },
  {
    id: 'musteri-temsilcisi',
    category: 'general',
    priority: 30,
    q: 'How do I reach a customer representative?',
    a: 'You can reach our customer support line via WhatsApp or email. Your questions are answered by a representative during business hours; our AI-powered chat assistant can also provide initial guidance at any time.',
    keywords: ['customer representative', 'support', 'contact', 'get in touch', 'live support'],
  },
  {
    id: 'hangi-belgeler-cevrilebilir',
    category: 'general',
    priority: 31,
    q: 'What types of documents can be translated?',
    a: 'We translate a wide range, from official and personal documents to commercial, legal, technical, medical, and academic texts. Many document types are supported, including diplomas, contracts, reports, manuals, and website content.',
    keywords: ['document types', 'which documents', 'paperwork', 'what can be translated'],
  },
  {
    id: 'yapay-zeka-mi-insan-mi',
    category: 'general',
    priority: 32,
    q: 'Are translations done by human translators?',
    a: 'Yes. Your translations are done from start to finish by professional human translators. CAT tools are used to support consistency and terminology, but the entire translation is the work of expert translators and goes through quality control.',
    keywords: ['human translator', 'cat tool', 'translation tools', 'machine translation', 'who translates'],
  },
  {
    id: 'el-yazili-belgeler',
    category: 'general',
    priority: 33,
    q: 'Can handwritten or hard-to-read documents be translated?',
    a: 'Handwritten and hard-to-read documents can be translated as long as they are legible. Any illegible parts are clearly noted in the translation, and if needed we may ask you for a clearer copy. For such documents, the price is confirmed after review.',
    keywords: ['handwriting', 'handwritten', 'illegible', 'unclear', 'hard to read'],
  },
  {
    id: 'farkiniz-nedir',
    category: 'general',
    priority: 34,
    q: 'What sets TercümExpert apart from other translation services?',
    a: 'Our end-to-end online process, automated preliminary quotes, specialist human translators, and quality control are what stand out. We also deliver wet-ink signed documents right to your door by courier.',
    keywords: ['difference', 'advantage', 'why tercumexpert', 'what makes you different'],
  },

  // ——— ORDER PROCESS ———
  {
    id: 'siparis-nasil-verilir',
    category: 'order',
    priority: 35,
    q: 'How do I place an order?',
    a: 'On the Get a Quote screen, upload your document or enter your text, select the language pair and service type, and approve the preliminary quote. Once you approve, your order is created.',
    keywords: ['place order', 'how to order', 'create order'],
  },
  {
    id: 'siparis-icin-gerekli-bilgiler',
    category: 'order',
    priority: 36,
    q: 'What information is needed to place an order?',
    a: 'You need the document or text to be translated, the source and target languages, the service type, and your name and email for contact. With this information, you can create your order.',
    keywords: ['required information', 'what is needed', 'order details'],
  },
  {
    id: 'dil-cifti-nasil-secilir',
    category: 'order',
    priority: 37,
    q: 'How do I choose the language pair and service type?',
    a: 'On the Get a Quote screen, you select the source language (the document language), the target language (the translation language), and the service type (sworn, notarized, technical, etc.) from the menu. If you are unsure, our support line or chat assistant can guide you to the right choice.',
    keywords: ['choose language pair', 'source language', 'target language', 'select service'],
  },
  {
    id: 'bilgiler-degistirilebilir-mi',
    category: 'order',
    priority: 38,
    q: 'Can I change the details after creating an order?',
    a: 'Details such as the language, service type, or document can be updated before translation begins. Just contact our support line as soon as possible; once work is underway, the scope for changes may become limited.',
    keywords: ['change details', 'edit order', 'update order', 'wrong language', 'wrong document'],
  },
  {
    id: 'onaydan-once-iptal',
    category: 'order',
    priority: 39,
    q: 'Can I cancel an order before it is approved?',
    a: 'Yes. You can cancel your order before payment and approval are completed; no charge is applied at this stage.',
    keywords: ['cancel', 'cancel order', 'back out'],
  },
  {
    id: 'odeme-sonrasi-iptal',
    category: 'order',
    priority: 40,
    q: 'Can an order be canceled after payment?',
    a: 'If your order has not yet been taken into processing by a translator, you can cancel it from your order page or via info@tercumexpert.com, and your payment is refunded in full to the original payment method. Once the translation has been taken into processing by a translator, no refund is made, owing to the person-specific nature of the work.',
    keywords: ['cancel after payment', 'refund', 'money back'],
  },
  {
    id: 'siparis-durumu-takip',
    category: 'order',
    priority: 41,
    q: 'Where can I track my order status?',
    a: 'You are notified about your order status by email, and if you have created an account you can also track it there. You can also ask our support line for the latest status.',
    keywords: ['track order', 'status', 'order tracking', 'order status'],
  },
  {
    id: 'birden-fazla-belge',
    category: 'order',
    priority: 42,
    q: 'Can one order include multiple documents or target languages?',
    a: 'Yes, you can upload multiple documents in a single order and have the same document translated into multiple languages. The total word count and each target language are priced as separate translations, and the process is coordinated under one request.',
    keywords: ['multiple documents', 'multiple files', 'multiple languages', 'several languages'],
  },
  {
    id: 'sonradan-dosya-eklenebilir',
    category: 'order',
    priority: 43,
    q: 'Can I add a new file to an order later?',
    a: 'You can add a new file before translation begins; in that case, the price is updated based on the added content. Documents added after work is underway may be treated as a new line item.',
    keywords: ['add file', 'add later', 'new file'],
  },
  {
    id: 'eksik-belge-gonderilirse',
    category: 'order',
    priority: 44,
    q: 'What happens if I send an incomplete document?',
    a: 'When we notice a missing page or document, we will ask you to complete it. Uploading all pages of the document is important for the translation to be complete and valid.',
    keywords: ['incomplete document', 'missing page', 'missing document'],
  },
  {
    id: 'terminoloji-not-referans',
    category: 'order',
    priority: 45,
    q: 'Can I add order-specific notes, terminology, or reference files?',
    a: 'Yes. During the order, you can add special instructions, preferred terms, or a style note, and upload reference files such as previous translations and glossaries. This information is passed to the translator and used for consistency.',
    keywords: ['add note', 'special instructions', 'terminology', 'reference file', 'glossary'],
  },
  {
    id: 'eski-siparisler-goruntulenir',
    category: 'order',
    priority: 46,
    q: 'Can I access past orders and files later?',
    a: 'If you have created an account, you can view your past orders and delivered files there. For orders placed without an account, you can access your records by email; if a download link has expired, you can request a new one from our support line.',
    keywords: ['past orders', 'order history', 'previous orders', 'access files'],
  },

  // ——— PRICING & PAYMENT ———
  {
    id: 'kelime-mi-sayfa-mi',
    category: 'pricing',
    priority: 47,
    q: 'Do you charge per word or per page?',
    a: 'Pricing is usually based on word count and the selected service. For text-based documents, the word count is extracted automatically; for scanned or image-based documents, the count is confirmed after review.',
    keywords: ['per word', 'per page', 'pricing basis', 'how charged'],
  },
  {
    id: 'sabit-baslangic-ucreti',
    category: 'pricing',
    priority: 48,
    q: 'Is there a fixed starting fee or minimum charge?',
    a: 'Some services may have a minimum service fee, which can apply to short documents. The final price is determined by the document content and the services you select, and you can see every line item on the preliminary quote screen.',
    keywords: ['starting fee', 'minimum', 'flat fee', 'minimum charge'],
  },
  {
    id: 'neler-fiyati-etkiler',
    category: 'pricing',
    priority: 49,
    q: 'Do the language pair, document type, and subject area affect the price?',
    a: 'Yes. The language pair (especially rare languages), the document type, and the subject area (legal, medical, technical, etc.) can affect terminology intensity and therefore the price. For common languages, pricing is more predictable.',
    keywords: ['language pair price', 'document type price', 'subject area price', 'why prices differ'],
  },
  {
    id: 'yeminli-daha-pahali-mi',
    category: 'pricing',
    priority: 50,
    q: 'Is sworn translation more expensive?',
    a: 'Sworn translation may be priced differently from standard translation because of the translator’s certification and responsibility. The exact amount is shown on the preliminary quote screen based on the document and language pair.',
    keywords: ['sworn translation price', 'sworn cost', 'is sworn expensive'],
  },
  {
    id: 'noter-apostil-ucreti-dahil',
    category: 'pricing',
    priority: 51,
    q: 'Are notarization and apostille fees included in the price?',
    a: 'Notarization is a separate procedure carried out by the relevant authorities and is subject to official tariffs; this cost is shown separately from the translation fee, and because it follows an official tariff it may not be exact in advance, with the actual amount confirmed after the procedure. The apostille process, however, is not carried out by us; you must obtain the apostille yourself from the competent authority, and we only translate your apostilled document.',
    keywords: ['notary fee', 'apostille fee', 'is it included', 'notary cost', 'apostille cost'],
  },
  {
    id: 'on-fiyat-nihai-fark',
    category: 'pricing',
    priority: 52,
    q: 'Can the preliminary quote differ from the final price?',
    a: 'Yes. The automatic calculation you see on screen is a preliminary quote. After a review based on word count, legibility, or document type, the final price may be confirmed. The final amount is shared with you before you approve.',
    keywords: ['preliminary quote', 'final price', 'price difference', 'exact price'],
  },
  {
    id: 'otomatik-kelime-sayimi',
    category: 'pricing',
    priority: 53,
    q: 'Is the word count calculated automatically? What about scanned PDFs?',
    a: 'For text-based documents (Word, text PDFs, plain text), the word count is extracted automatically. For scanned or image-based PDFs and photos, automatic counting may not be reliable, so our team confirms the count. The preliminary quote is based on the automatic count and is not binding; if there is a discrepancy, the final price is confirmed with you.',
    keywords: ['word count', 'automatic count', 'scanned pdf', 'image pdf', 'count error'],
  },
  {
    id: 'toplu-kurumsal-indirim',
    category: 'pricing',
    priority: 54,
    q: 'Are there discounts for bulk orders or corporate clients?',
    a: 'For high-volume and recurring work, especially for corporate clients, we can offer favorable pricing and payment-term options based on volume and the terms of cooperation. For details, use the Corporate application form.',
    keywords: ['bulk discount', 'volume discount', 'corporate pricing', 'business rates'],
  },
  {
    id: 'ucretsiz-teklif',
    category: 'pricing',
    priority: 55,
    q: 'Can I get a free quote, and how long is it valid?',
    a: 'The preliminary quote is free; you see it instantly when you upload your document or enter your text. Quotes are valid for a short period as long as the conditions (document content/scope) do not change.',
    keywords: ['free quote', 'no cost estimate', 'quote validity', 'how long valid'],
  },
  {
    id: 'fatura-kesiliyor-mu',
    category: 'pricing',
    priority: 56,
    q: 'Do you issue invoices? Can I get an individual or corporate invoice?',
    a: 'Yes. An invoice is issued for the service, and you can request an individual or corporate invoice. Corporate clients can also be offered monthly consolidated invoicing. Taxes are applied in accordance with the applicable regulations.',
    keywords: ['invoice', 'billing', 'tax', 'corporate invoice', 'individual invoice'],
  },
  {
    id: 'taksit-secenegi',
    category: 'pricing',
    priority: 57,
    q: 'Are installment options available?',
    a: 'Installment options may be available for credit card payments. Any eligible installment plans are shown at the payment step.',
    keywords: ['installments', 'installment payment', 'pay in installments'],
  },
  {
    id: 'kurumsal-vadeli-odeme',
    category: 'pricing',
    priority: 58,
    q: 'Do you offer payment terms for corporate clients?',
    a: 'Yes. Corporate clients can be offered payment terms of up to 15–30 days and monthly invoicing. The terms are set as part of the corporate arrangement.',
    keywords: ['payment terms', 'net terms', 'corporate payment'],
  },
  {
    id: 'odeme-yapilmadan-baslar-mi',
    category: 'pricing',
    priority: 59,
    q: 'Does translation start before payment?',
    a: 'For standard orders, translation begins after payment (or corporate payment-term approval) is received. For corporate agreements, the process may proceed according to the contract.',
    keywords: ['prepayment', 'before payment', 'upfront payment', 'without payment'],
  },
  {
    id: 'iade-sureci',
    category: 'pricing',
    priority: 60,
    q: 'Are refunds issued for canceled orders?',
    a: 'If your order is canceled before it has been taken into processing by a translator, your payment is refunded in full to the original payment method. Once the translation has been taken into processing by a translator, no refund is made, owing to the person-specific nature of the work. In cases such as a duplicate or erroneous charge, the excess amount is refunded.',
    keywords: ['refund', 'money back', 'cancellation refund', 'reimbursement'],
  },

  // ——— FILE UPLOAD ———
  {
    id: 'hangi-formatlar',
    category: 'upload',
    priority: 61,
    q: 'Which file formats are supported?',
    a: 'We accept more than 50 formats, including Word (DOC/DOCX), PDF, plain text (TXT), Excel, PowerPoint, and common image formats (JPG, PNG). For text-based documents, the word count is extracted automatically.',
    keywords: ['file format', 'supported formats', 'pdf', 'doc', 'docx', 'txt'],
  },
  {
    id: 'taranmis-fotograf-belge',
    category: 'upload',
    priority: 62,
    q: 'Do you accept scanned documents or photos?',
    a: 'Yes. Scanned documents and clear photos taken with a phone are accepted. Legibility matters; seals, stamps, and signatures must be visible. Because text in images may not be read automatically, our team determines the word count.',
    keywords: ['scanned document', 'photo of document', 'phone photo', 'image upload', 'picture'],
  },
  {
    id: 'birden-fazla-dosya-yukleme',
    category: 'upload',
    priority: 63,
    q: 'Can I upload multiple files at once?',
    a: 'Yes, you can upload multiple files at the same time. The price is calculated based on the total content.',
    keywords: ['multiple upload', 'multiple files', 'bulk upload'],
  },
  {
    id: 'dosya-boyutu-siniri',
    category: 'upload',
    priority: 64,
    q: 'Is there a file size limit? How do I send large files?',
    a: 'You can upload up to about 100 MB per file. For larger files, contact our support line to arrange delivery by email or an alternative method.',
    keywords: ['file size', 'size limit', 'large file', '100 mb'],
  },
  {
    id: 'yuklenen-dosya-silinebilir',
    category: 'upload',
    priority: 65,
    q: 'Can I delete or replace an uploaded file?',
    a: 'Yes. Before the order is completed, you can remove the file you uploaded or replace it with a new one.',
    keywords: ['delete file', 'replace file', 'wrong file'],
  },
  {
    id: 'manuel-kelime-girisi',
    category: 'upload',
    priority: 66,
    q: 'Can I enter the word count manually without uploading a file?',
    a: "Rather than entering a number directly, paste your text into the 'Enter Text' tab and the word count is calculated automatically. That way you can get a preliminary quote without a file.",
    keywords: ['manual word count', 'enter words', 'enter text'],
  },
  {
    id: 'dosyalar-ne-kadar-saklanir',
    category: 'upload',
    priority: 67,
    q: 'How long are files kept, and can I request deletion?',
    a: 'Your documents are stored securely only for as long as the service requires. You can request the deletion of your documents at any time; this request is honored in line with your rights under KVKK.',
    keywords: ['retention period', 'file storage', 'deletion request', 'delete data'],
  },
  {
    id: 'belgenin-tum-sayfalari',
    category: 'upload',
    priority: 68,
    q: 'Do I need to upload all pages and the backs of the document?',
    a: 'Yes. For the translation to be complete and valid, you need to upload every page of the document, including the backs where applicable. It is important that seal, stamp, and signature areas are clearly visible.',
    keywords: ['all pages', 'back side', 'complete document', 'seals and stamps'],
  },
  {
    id: 'imza-kase-cevrilir-mi',
    category: 'upload',
    priority: 69,
    q: 'Are stamps, seals, and signatures translated?',
    a: 'In a sworn translation, legible text on stamps and seals is transcribed; signatures are noted as "signature present." Any illegible areas are clearly marked in the translation.',
    keywords: ['stamp translation', 'seal translation', 'signature translation'],
  },
  {
    id: 'dosya-guvenli-mi-analiz',
    category: 'upload',
    priority: 70,
    q: 'Is my document content secure during automatic analysis?',
    a: 'Yes. Documents are transferred in encrypted form, and processes such as word counting are done in a secure environment. Your content is never shared with third parties.',
    keywords: ['analysis security', 'content security', 'automatic reading'],
  },

  // ——— LANGUAGES & LANGUAGE PAIRS ———
  {
    id: '50-dil-ne-demek',
    category: 'languages',
    priority: 71,
    q: 'What does support for more than 50 languages mean?',
    a: 'It means that, alongside common languages, we can also translate less-requested languages. For rare languages, translator availability, turnaround, and price are confirmed separately for each order.',
    keywords: ['50 languages', 'rare language', 'language support', 'how many languages'],
  },
  {
    id: 'yaygin-dil-ciftleri',
    category: 'languages',
    priority: 72,
    q: 'Do you translate pairs like Turkish-English, German, and French?',
    a: 'Yes. We translate common language pairs such as Turkish ⇄ English, German, French, Spanish, Italian, Arabic, and Russian in both directions. Languages such as Chinese and Japanese are also supported.',
    keywords: ['turkish english', 'english turkish', 'german', 'french', 'language pair'],
  },
  {
    id: 'yabancidan-yabanciya',
    category: 'languages',
    priority: 73,
    q: 'Can you translate between two foreign languages other than Turkish?',
    a: 'Yes, we can translate from one foreign language to another, such as English to French. Availability and turnaround are assessed based on the language pair.',
    keywords: ['foreign to foreign', 'english french', 'between languages'],
  },
  {
    id: 'nadir-dil',
    category: 'languages',
    priority: 74,
    q: 'Do you offer services for rare or unlisted languages?',
    a: 'We aim to offer rare languages too; however, translator availability, turnaround, and price are confirmed separately for these languages. If the language you need is not listed, contact our support line to request a custom quote.',
    keywords: ['rare language', 'uncommon language', 'unlisted language', 'special language'],
  },
  {
    id: 'dil-varyantlari',
    category: 'languages',
    priority: 75,
    q: 'Can I choose a regional language variant (like American vs. British English)?',
    a: 'Yes, where possible you can specify a regional variant of the target language (e.g., American/British English, European/Latin American Spanish). If no variant is specified, the common standard is used.',
    keywords: ['variant', 'american english', 'regional language', 'dialect'],
  },
  {
    id: 'anadili-tercuman',
    category: 'languages',
    priority: 76,
    q: 'Do you work with translators who are native in the target language?',
    a: 'Wherever possible, we work with experienced translators who are proficient in the target language. The goal is to deliver a natural and accurate translation.',
    keywords: ['native translator', 'native speaker', 'target language expert'],
  },
  {
    id: 'osmanlica-eski-yazi',
    category: 'languages',
    priority: 77,
    q: 'Can Ottoman Turkish or old-script documents be translated?',
    a: 'Ottoman Turkish and documents written in the old alphabet can be translated, subject to specialist availability. For such documents, turnaround and price are confirmed after review.',
    keywords: ['ottoman turkish', 'old script', 'old alphabet'],
  },
  {
    id: 'karisik-dilli-belge',
    category: 'languages',
    priority: 78,
    q: 'Can a document be translated if it contains more than one language?',
    a: 'Yes. Mixed-language documents can be translated; the price is based on the amount of content in each language. Just let us know the target language you need.',
    keywords: ['mixed language', 'multilingual document', 'multiple languages in document'],
  },

  // ——— SERVICE TYPES ———
  {
    id: 'hangi-hizmeti-secmeliyim',
    category: 'services',
    priority: 79,
    q: 'Which service type should I choose?',
    a: 'Where your document will be used determines the service: official applications mostly require a sworn translation, while some procedures require a notarized or apostilled translation. If you are unsure, our support line or chat assistant can guide you; the final requirement depends on the relevant institution.',
    keywords: ['which service', 'service selection', 'what to choose'],
  },
  {
    id: 'standart-yeminli-fark',
    category: 'services',
    priority: 80,
    q: 'What is the difference between standard and sworn translation?',
    a: 'A standard translation is for informational purposes and carries no official certification. A sworn translation is certified with the sworn translator’s stamp and signature and is required for official applications. Which one you need depends on the institution the document will be submitted to.',
    keywords: ['standard vs sworn', 'difference', 'regular translation', 'sworn difference'],
  },
  {
    id: 'yeminli-noter-ayni-mi',
    category: 'services',
    priority: 81,
    q: 'Are sworn translation and notarized translation the same thing?',
    a: 'No. A sworn translation carries the sworn translator’s certification. A notarized translation is that translation additionally certified by a notary. Some institutions require only a sworn translation, while others also require notarization.',
    keywords: ['sworn vs notarized', 'notarized translation', 'are they the same'],
  },
  {
    id: 'hukuki-teknik-medikal',
    category: 'services',
    priority: 82,
    q: 'How is expertise ensured for legal, technical, and medical translations?',
    a: 'Contracts, court documents, technical documentation, and medical documents are translated by experienced translators who know the terminology of the relevant field. Terminology glossaries and translation memory ensure consistency, formats and units are preserved, and the translation goes through quality control.',
    keywords: ['legal translation', 'technical translation', 'medical translation', 'specialist translator', 'terminology'],
  },
  {
    id: 'akademik-bicim-korunur',
    category: 'services',
    priority: 83,
    q: 'Are references and formatting preserved in academic translation?',
    a: 'Yes. In theses, articles, and academic texts, the reference layout, citations, and formatting are preserved as much as possible, and the translation follows academic style.',
    keywords: ['academic translation', 'thesis', 'article', 'references', 'citations'],
  },
  {
    id: 'lokalizasyon-nedir',
    category: 'services',
    priority: 84,
    q: 'Is localization just word-for-word translation? Is SEO considered?',
    a: 'No. Localization means adapting the text to the target culture and use; the interface, date/currency formats, and tone are adjusted to the target audience. In website localization, target-language keywords and SEO alignment can be taken into account on request.',
    keywords: ['localization', 'website translation', 'app translation', 'seo', 'localize'],
  },
  {
    id: 'kurumsal-marka-dili',
    category: 'services',
    priority: 85,
    q: 'Is brand voice preserved in corporate content?',
    a: 'Yes. In corporate translations, a terminology bank and style guide keep your brand voice and tone consistent.',
    keywords: ['brand voice', 'corporate tone', 'style guide'],
  },
  {
    id: 'vize-diploma-hangi-hizmet',
    category: 'services',
    priority: 86,
    q: 'Which service do I need for documents like a visa or diploma?',
    a: 'For visa applications and diploma translations, a sworn translation is usually the core requirement; some missions or institutions may also ask for notarization or an apostille. The exact requirement depends on the consulate or institution you are applying to.',
    keywords: ['visa document', 'diploma translation', 'transcript', 'consulate', 'visa translation'],
  },
  {
    id: 'belge-turu-listede-yok',
    category: 'services',
    priority: 87,
    q: 'What should I select if my document type is not on the list?',
    a: 'If your document type is not listed, choose the closest option and add an explanation in the order note. If you like, our support line can help you make the right choice.',
    keywords: ['document type not listed', 'other document', 'not on list'],
  },

  // ——— DELIVERY & TURNAROUND ———
  {
    id: 'teslim-suresi-nasil-hesaplanir',
    category: 'delivery',
    priority: 88,
    q: 'How is turnaround calculated and where is it shown?',
    a: 'Turnaround is calculated based on the length of the document, the language pair, the service type, and any add-ons, and is shown as an estimated delivery date on the Get a Quote screen. For procedures that require notarization or an apostille, extra days may be added; if the delivery date changes, you are notified.',
    keywords: ['turnaround calculation', 'estimated delivery', 'when ready'],
  },
  {
    id: 'ayni-gun-teslimat',
    category: 'delivery',
    priority: 89,
    q: 'Is same-day or 24-hour delivery possible?',
    a: 'For short documents, fast/rush delivery is often possible; availability depends on the length and language of the document. Quality-control steps are preserved even for rush delivery, and the option is shown as an additional line item on the preliminary quote screen.',
    keywords: ['same day', '24 hours', 'fast delivery', 'urgent'],
  },
  {
    id: 'hafta-sonu-tatil',
    category: 'delivery',
    priority: 90,
    q: 'When are weekend or after-hours orders processed?',
    a: 'You can upload documents, get quotes, and create orders around the clock. Orders placed after hours or on holidays are processed at the start of the next business hours, and the estimated turnaround is shown accordingly.',
    keywords: ['weekend', 'holiday', 'after hours', 'night order'],
  },
  {
    id: 'dijital-teslim-format',
    category: 'delivery',
    priority: 91,
    q: 'How is digital delivery done, and in which format do I receive it?',
    a: 'The completed translation is delivered digitally via a downloadable link or by email. You can receive it as a PDF or an editable Word (DOCX) file depending on your needs; the original formatting is preserved as much as possible.',
    keywords: ['digital delivery', 'word delivery', 'pdf delivery', 'download'],
  },
  {
    id: 'kargo-kapsam-takip',
    category: 'delivery',
    priority: 92,
    q: 'Which regions do you ship to, and can I track the shipment?',
    a: 'Documents with a wet-ink signature and stamp are shipped by courier throughout Türkiye; on request, we can also ship internationally. Courier tracking information is shared with you, and shipping time is added to the total turnaround.',
    keywords: ['shipping regions', 'courier tracking', 'international shipping', 'shipping time'],
  },
  {
    id: 'kismi-teslimat',
    category: 'delivery',
    priority: 93,
    q: 'Can long projects be delivered in parts?',
    a: 'Yes. High-volume or long projects can be delivered in sections on request. That way, you can start using your documents without waiting.',
    keywords: ['partial delivery', 'in parts', 'section delivery'],
  },

  // ——— SWORN TRANSLATION ———
  {
    id: 'yeminli-tercuman-kim',
    category: 'sworn',
    priority: 94,
    q: 'Who is a sworn translator?',
    a: 'A sworn translator is a translator who has taken an oath before a notary and thereby earned the authority to certify their translations with a signature and stamp. This certification is a declaration that the translation faithfully reflects the original.',
    keywords: ['sworn translator', 'who is sworn translator', 'certified translator'],
  },
  {
    id: 'yeminli-ne-zaman-gerekli',
    category: 'sworn',
    priority: 95,
    q: 'When is a sworn translation required?',
    a: 'Sworn translations are frequently required for applications to official institutions, courts, consulates, and universities. However, they are not mandatory for every document; the exact requirement is set by the institution requesting the document.',
    keywords: ['when sworn required', 'is sworn needed', 'where required'],
  },
  {
    id: 'yeminli-nerede-gecerli',
    category: 'sworn',
    priority: 96,
    q: 'Is a sworn translation valid in court, at a consulate, and abroad?',
    a: 'A sworn translation can be used in many official procedures and applications. However, an institution’s conditions for accepting a document depend on its own regulations; abroad in particular, notarization or an apostille may also be required. We recommend confirming the acceptance requirements with the relevant institution.',
    keywords: ['court', 'consulate', 'valid abroad', 'university application'],
  },
  {
    id: 'dijital-imzali-yeminli',
    category: 'sworn',
    priority: 97,
    q: 'Can a sworn translation be issued with a digital/e-signature?',
    a: 'No. A sworn translation is prepared with the translator’s wet-ink signature and stamp and is delivered physically by courier.',
    keywords: ['e-signature', 'digital sworn', 'electronic signature', 'wet-ink signature', 'stamp'],
  },
  {
    id: 'yeminli-orijinal-gerekir',
    category: 'sworn',
    priority: 98,
    q: 'Is the original document required for a sworn translation?',
    a: 'The translation can usually be done from a clear copy (scan or photo) of the document. However, if notarization is required, the original or a certified copy of the document may be requested for that procedure.',
    keywords: ['original document', 'is original needed', 'copy for sworn'],
  },
  {
    id: 'yeminli-gecerlilik-suresi',
    category: 'sworn',
    priority: 99,
    q: 'Does a sworn translation have an expiration date?',
    a: 'The translation itself is not time-limited; however, some institutions may ask for a recently dated document. This depends on the requirements of the institution that will accept the document.',
    keywords: ['expiration date', 'sworn validity', 'how long valid'],
  },
  {
    id: 'kurum-belgeyi-kabul-etmezse',
    category: 'sworn',
    priority: 100,
    q: 'What happens if an institution does not accept the sworn translation?',
    a: 'Acceptance requirements can vary from institution to institution. If the institution has a specific format or certification requirement, let us know and we will make the necessary adjustments. The final acceptance decision rests with the institution.',
    keywords: ['not accepted', 'institution rejection', 'format requirement'],
  },

  // ——— NOTARIZATION & APOSTILLE ———
  {
    id: 'noter-onayli-nedir',
    category: 'notary',
    priority: 101,
    q: 'What is a notarized translation?',
    a: 'A notarized translation is a sworn translation that is additionally certified by a notary. This certification reinforces the official validity of the translation and is required by some institutions.',
    keywords: ['notarized translation', 'notary certification', 'what is notarized'],
  },
  {
    id: 'noter-yeminli-fark',
    category: 'notary',
    priority: 102,
    q: 'What is the difference between notarization and a sworn translation?',
    a: 'A sworn translation carries the translator’s certification, while notarization is the notary’s certification of that translation. Notarization is an additional official step layered on top of a sworn translation.',
    keywords: ['notary vs sworn', 'certification difference'],
  },
  {
    id: 'notere-gitmem-gerekir-mi',
    category: 'notary',
    priority: 103,
    q: 'Do I have to go to the notary for notarization?',
    a: 'In most cases we can handle the notarization on your behalf, so you do not need to go to the notary in person. If the original document is required, we will let you know in advance.',
    keywords: ['go to notary', 'notary procedure', 'notary on my behalf'],
  },
  {
    id: 'apostil-nedir',
    category: 'notary',
    priority: 104,
    q: 'What is an apostille, and how does it differ from notarization?',
    a: 'An apostille is an international certification issued by the competent authority so that an official document is recognized as valid in another country, and it applies among countries party to the Hague Convention. Notarization, on the other hand, is a certification within a country; the two serve different purposes.',
    keywords: ['what is apostille', 'apostille vs notary', 'hague convention'],
  },
  {
    id: 'apostil-once-mi-ceviri-once-mi',
    category: 'notary',
    priority: 105,
    q: 'Which comes first, the apostille or the translation?',
    a: 'The order depends on the type of document and the requirements of the country where it will be used. In some cases the document is apostilled first and then translated; in others it is the reverse. We can determine the correct order together.',
    keywords: ['apostille order', 'translation first or apostille first', 'sequence'],
  },
  {
    id: 'yabanci-belge-turkiye',
    category: 'notary',
    priority: 106,
    q: 'What is the process if a foreign document will be used in Türkiye?',
    a: 'A document coming from abroad is usually apostilled first in the country of origin, then given a sworn translation (and notarization, if needed) in Türkiye. The exact process depends on the Turkish institution requesting the document.',
    keywords: ['foreign document in turkey', 'incoming document', 'document from abroad'],
  },
  {
    id: 'turk-belge-yurt-disi',
    category: 'notary',
    priority: 107,
    q: 'What is the process if a Turkish document will be used abroad?',
    a: 'A document issued in Türkiye is usually apostilled and given a sworn translation into the target language. If the destination country is not party to the Hague Convention, consular certification may be required instead of an apostille.',
    keywords: ['turkish document abroad', 'outgoing document', 'consular certification'],
  },
  {
    id: 'hangi-onay-gerekli-bilinmiyor',
    category: 'notary',
    priority: 109,
    q: 'How do I find out whether notarization or an apostille is needed?',
    a: 'The most reliable way is to ask the institution requesting the document. If you like, our support line can point you to common practices; but the exact requirement varies by institution and country.',
    keywords: ['which certification', 'is certification needed', 'notary or apostille'],
  },
  {
    id: 'kesin-kabul-garantisi',
    category: 'notary',
    priority: 110,
    q: 'Does TercümExpert guarantee acceptance?',
    a: 'We make sure the translation and certifications are prepared accurately and completely; however, the conditions for accepting a document are set by the institution requesting it. For that reason, we cannot offer an unconditional acceptance guarantee; if you share the institution’s specific requirements, we will make the necessary adjustments.',
    keywords: ['acceptance guarantee', 'guaranteed acceptance', 'guarantee'],
  },

  // ——— QUALITY & REVISIONS ———
  {
    id: 'tercumanlar-nasil-secilir',
    category: 'quality',
    priority: 111,
    q: 'How are translators selected and their expertise determined?',
    a: 'Translators are chosen based on the language pair and the subject area of the document; a legal document goes to a translator experienced in law, and a medical document to one experienced in healthcare. The most suitable translator is assigned with an eye to field experience and language proficiency.',
    keywords: ['translator selection', 'how translators chosen', 'expertise', 'subject expert'],
  },
  {
    id: 'kalite-kontrol',
    category: 'quality',
    priority: 112,
    q: 'Does the translation go through quality control?',
    a: 'Yes. Translations are checked for spelling, terminology, consistency of numbers/names/dates, and formatting. Depending on the type of document and the service level, an independent editor/proofreading step may be applied.',
    keywords: ['quality control', 'proofreading', 'editor', 'review'],
  },
  {
    id: 'ceviri-bellegi',
    category: 'quality',
    priority: 113,
    q: 'Do you use translation memory or terminology lists?',
    a: 'Yes, especially in technical and corporate projects, translation memory and terminology lists are used to ensure consistency. You can also share your own term list; terminology from previous projects is preserved.',
    keywords: ['translation memory', 'terminology list', 'consistency'],
  },
  {
    id: 'revize-kapsami',
    category: 'quality',
    priority: 114,
    q: 'What does a revision cover and when should I request it?',
    a: 'A revision covers issues such as translation errors, spelling, inconsistencies, and omissions. Changing the source text afterward or adding new content may count as new work. We recommend sending your revision request within a reasonable time after delivery by email or WhatsApp.',
    keywords: ['revision scope', 'correction scope', 'revision window', 'when to revise'],
  },
  {
    id: 'tercuman-degisikligi',
    category: 'quality',
    priority: 115,
    q: 'What if I am not satisfied with the translation — can the translator be changed?',
    a: 'If you are not satisfied with the translation, we review the situation and, if needed, arrange corrections with a different translator or editor. The goal is for the result to meet your expectations.',
    keywords: ['change translator', 'not satisfied', 'unhappy with translation'],
  },
  {
    id: 'dogruluk-garanti',
    category: 'quality',
    priority: 116,
    q: 'Is the accuracy of the translation guaranteed?',
    a: 'Your translations are prepared by expert translators and go through quality control, and we take the care needed for accuracy. That said, the official acceptance requirements for a document may vary depending on the institution requesting it.',
    keywords: ['accuracy guarantee', 'quality guarantee', 'assurance'],
  },
  {
    id: 'makine-cevirisi-kullaniliyor',
    category: 'quality',
    priority: 117,
    q: 'Do you use fully automated/machine translation?',
    a: 'No. Translations are done from start to finish by professional human translators; we do not offer automated machine translation. Only CAT tools are used to support consistency. Sworn translations include the translator’s stamp, signature, and declaration of fidelity to the original.',
    keywords: ['machine translation', 'automated translation', 'ai translation', 'certification statement'],
  },

  // ——— PRIVACY & SECURITY ———
  {
    id: 'dosyalari-kimler-gorur',
    category: 'privacy',
    priority: 118,
    q: 'Who can see uploaded files, and are they shared with third parties?',
    a: 'Only the translator and the relevant team working on your order can access your files. Except where the service requires it, your documents are never shared with third parties and are not used for marketing.',
    keywords: ['who can see', 'access', 'third party', 'sharing'],
  },
  {
    id: 'nda-imzalanabilir',
    category: 'privacy',
    priority: 119,
    q: 'Can a non-disclosure agreement (NDA) be signed?',
    a: 'Yes. Especially for corporate projects, a non-disclosure agreement (NDA) can be arranged on request. Our translators are also bound by confidentiality obligations.',
    keywords: ['nda', 'non-disclosure agreement', 'confidentiality agreement'],
  },
  {
    id: 'kvkk-uyumlu',
    category: 'privacy',
    priority: 120,
    q: 'Do you work in compliance with KVKK, and how is personal data protected?',
    a: 'Yes. Your personal data is processed through KVKK-compliant procedures; it is used only to the extent the service requires and is stored securely. We are committed to protecting your data with appropriate security measures.',
    keywords: ['kvkk', 'personal data', 'data protection', 'kvkk compliant'],
  },
  {
    id: 'sifreli-aktarim',
    category: 'privacy',
    priority: 121,
    q: 'Are files transferred with encryption?',
    a: 'Yes. Your files are transferred over an encrypted connection and processed in a secure environment. Our aim is to protect your data with appropriate security measures.',
    keywords: ['encrypted', 'secure transfer', 'encryption'],
  },
  {
    id: 'odeme-bilgileri-saklanir',
    category: 'privacy',
    priority: 122,
    q: 'Are payment/credit card details stored?',
    a: 'Your card details are not stored by TercümExpert; payments are processed through a secure payment infrastructure.',
    keywords: ['payment details', 'credit card security', 'card storage'],
  },
  {
    id: 'belgeler-ai-egitimi',
    category: 'privacy',
    priority: 123,
    q: 'Are my documents used for model training?',
    a: 'No. Your documents are used only for your order; they are never shared for any model training or with external systems. Your translation is prepared by human translators on a confidential basis.',
    keywords: ['model training', 'data usage', 'ai training', 'document privacy'],
  },
  {
    id: 'saglik-kimlik-guvenli',
    category: 'privacy',
    priority: 124,
    q: 'Are sensitive documents like IDs, passports, or health records secure?',
    a: 'Yes. All your files, including sensitive documents, are processed confidentially, in a KVKK-compliant and encrypted manner. Access is limited to the team working on your order; for highly confidential documents, additional measures such as an NDA and restricted access can be applied.',
    keywords: ['id security', 'passport', 'health data', 'sensitive document'],
  },
  {
    id: 'hesap-silinince-belgeler',
    category: 'privacy',
    priority: 125,
    q: 'Are documents deleted when an account is deleted or upon request?',
    a: 'Upon your request, your documents and personal data are deleted, subject to any legal retention obligations. You can send an account deletion or data deletion request to our support line.',
    keywords: ['account deletion', 'data deletion', 'delete documents'],
  },

  // ——— CORPORATE SERVICES ———
  {
    id: 'kurumsal-hesap-nasil',
    category: 'corporate',
    priority: 126,
    q: 'How do I open a corporate account, and what happens after I apply?',
    a: 'Just fill out the application form on our Corporate page; our team usually contacts you within 1 business day, assesses your needs, and sets up terms tailored to you.',
    keywords: ['corporate account', 'company account', 'corporate application', 'after applying'],
  },
  {
    id: 'sirket-adina-siparis',
    category: 'corporate',
    priority: 127,
    q: 'Can I place an order on behalf of a company?',
    a: 'Yes. You can place an order with your company details and take advantage of corporate invoicing and, when needed, payment-term options.',
    keywords: ['on behalf of company', 'corporate order', 'company order'],
  },
  {
    id: 'ozel-hesap-yoneticisi',
    category: 'corporate',
    priority: 128,
    q: 'Are corporate clients assigned a dedicated account manager?',
    a: 'Corporate clients can be assigned a dedicated account manager who follows their processes. That way you can manage your requests from a single point of contact and receive priority support.',
    keywords: ['account manager', 'dedicated manager', 'corporate support', 'priority support'],
  },
  {
    id: 'toplu-fatura',
    category: 'corporate',
    priority: 129,
    q: 'Can I get monthly consolidated invoicing and payment terms?',
    a: 'Yes. Corporate clients can be offered monthly consolidated invoicing and payment terms of up to 15–30 days. The details are set as part of the arrangement.',
    keywords: ['consolidated invoicing', 'monthly invoice', 'payment terms', 'corporate payment'],
  },
  {
    id: 'terminoloji-bankasi',
    category: 'corporate',
    priority: 130,
    q: 'Can a company-specific terminology bank be created?',
    a: 'Yes. For corporate projects, a terminology bank and style guide specific to your brand are created so that your brand voice and consistency are preserved across all translations.',
    keywords: ['terminology bank', 'style guide', 'corporate terminology'],
  },
  {
    id: 'sabit-tercuman',
    category: 'corporate',
    priority: 131,
    q: 'Can we work with the same translators on recurring projects?',
    a: 'Yes. For recurring corporate projects, a dedicated translator/team pool can be set up to ensure continuity and consistency.',
    keywords: ['dedicated translator', 'same team', 'corporate team'],
  },
  {
    id: 'kurumsal-raporlama',
    category: 'corporate',
    priority: 132,
    q: 'Can I get order and spending reports?',
    a: 'Corporate clients can be offered reporting on their orders and spending, with a department-level breakdown if needed. For corporate partnerships, service-level (SLA) and confidentiality (NDA) agreements can also be arranged.',
    keywords: ['reporting', 'spending report', 'order report', 'sla'],
  },
  {
    id: 'kucuk-isletme',
    category: 'corporate',
    priority: 133,
    q: 'Can small businesses use corporate services, and is a minimum volume required?',
    a: 'Yes. There is no minimum size or volume requirement to use our corporate services; small businesses can also benefit from advantages such as payment terms, terminology management, and priority support.',
    keywords: ['small business', 'sme', 'minimum volume', 'volume required'],
  },
  {
    id: 'uluslararasi-sirket',
    category: 'corporate',
    priority: 134,
    q: 'Do you serve international companies and multilingual projects?',
    a: 'Yes. Projects spanning multiple countries and languages can be coordinated and run centrally, with terminology consistency ensured across the board. For corporate projects, sworn translation and, where needed, notarization processes can also be handled.',
    keywords: ['international company', 'multilingual project', 'corporate notary apostille'],
  },

  // ——— TECHNICAL SUPPORT ———
  {
    id: 'nasil-uye-olunur',
    category: 'support',
    priority: 135,
    q: 'How do I sign up for the site?',
    a: 'To sign up, just enter your first name, last name, and email, then confirm the verification code sent to your email. You can also sign up quickly with your Apple or Google account.',
    keywords: ['sign up', 'register', 'create account'],
  },
  {
    id: 'giris-sifre-sorunu',
    category: 'support',
    priority: 136,
    q: 'What should I do if I cannot log in or forget my password?',
    a: "First, check your email and password; if you forgot your password, use the 'Forgot password' link on the login screen to send reset instructions to your email. If the problem persists, check your spam folder or contact our support line.",
    keywords: ['cannot log in', 'reset password', 'forgot password', 'login', 'sign in'],
  },
  {
    id: 'dogrulama-epostasi-gelmezse',
    category: 'support',
    priority: 137,
    q: 'What should I do if the verification email does not arrive?',
    a: 'Wait a few minutes, check your spam/junk folder, and resend the code. Make sure you entered your email address correctly; if the problem persists, contact our support line.',
    keywords: ['verification email', 'code not received', 'email not arriving', 'verification code'],
  },
  {
    id: 'dosya-yuklenmiyor',
    category: 'support',
    priority: 138,
    q: 'What should I do if a file will not upload or I get an unsupported file error?',
    a: "Check the file size (up to 100 MB) and format, and refresh the page and your browser. If the format is not supported, convert the file to a format like PDF or DOCX, or paste the text into the 'Enter Text' tab. If the problem persists, contact our support line.",
    keywords: ['file will not upload', 'upload error', 'unsupported file', 'format error'],
  },
  {
    id: 'kelime-sayisi-yanlis',
    category: 'support',
    priority: 139,
    q: 'What should I do if the word count looks wrong?',
    a: "Automatic counting can be off, especially for scanned or image-based documents. For an accurate result, share the text via 'Enter Text' or add a note to your order; the final count is confirmed by our team and the price is finalized accordingly.",
    keywords: ['wrong word count', 'count error', 'incorrect word count'],
  },
  {
    id: 'odeme-basarisiz',
    category: 'support',
    priority: 140,
    q: 'What should I do if a payment fails or I am charged twice?',
    a: 'Check your card details and limit and try again; you can also use a different method (card/bank transfer). If the amount was charged but no order was created, or if there was a duplicate charge, contact our support line with your receipt and the excess amount will be refunded.',
    keywords: ['payment failed', 'payment error', 'charged twice', 'duplicate charge'],
  },
  {
    id: 'teslim-dosyasi-inmiyor',
    category: 'support',
    priority: 141,
    q: 'What should I do if the delivered file will not download?',
    a: 'Refresh the link and your browser; if the download link has expired, you can request a new one from our support line.',
    keywords: ['file will not download', 'download problem', 'cannot download delivery', 'link expired'],
  },
  {
    id: 'mobil-tarayici-destegi',
    category: 'support',
    priority: 142,
    q: 'Can I use the site on a mobile device, and which browsers are supported?',
    a: 'The site is mobile-friendly; you can upload documents and place orders from an iPhone, Android phone, or tablet. You can use the site smoothly with current versions of Chrome, Safari, Edge, and Firefox.',
    keywords: ['mobile', 'phone', 'iphone android', 'tablet', 'browser', 'chrome safari'],
  },
  {
    id: 'ai-asistan-ne-yapar',
    category: 'support',
    priority: 143,
    q: 'What can the AI-powered chat assistant do?',
    a: 'The chat assistant provides instant guidance on the process, service types, and general questions, and points you to the right steps, such as getting a quote. It cannot make final or binding decisions about official acceptance requirements or legal requirements (like notarization or apostille); for those, you should consult the relevant institution.',
    keywords: ['chat assistant', 'chatbot', 'ai assistant', 'chatbot pricing'],
  },
  {
    id: 'insana-baglanma',
    category: 'support',
    priority: 144,
    q: 'How do I reach a human customer representative?',
    a: 'You can request it through the chat assistant, or reach our human support line directly via WhatsApp and email. Requests are answered during business hours. Sending technical issues with a screenshot helps speed up the resolution.',
    keywords: ['reach a human', 'customer representative', 'live support', 'screenshot'],
  },
  {
    id: 'hesap-bilgileri-guncelleme',
    category: 'support',
    priority: 145,
    q: 'How do I update account and billing details, and how do I delete my account?',
    a: 'If you have an account, you can update your phone, email, and billing details in your account settings, and you can also request account deletion there or by contacting our support line. Upon your request, your data is deleted, subject to any legal obligations.',
    keywords: ['update details', 'billing information', 'account settings', 'delete account'],
  },
  {
    id: 'bildirim-tercihleri',
    category: 'support',
    priority: 146,
    q: 'How do order notifications work, and can I get WhatsApp notifications?',
    a: 'Email notifications are sent for your order status; based on your preferences, updates can also be provided via WhatsApp. You can adjust your notification preferences in your account settings or through our support line.',
    keywords: ['notifications', 'sms', 'whatsapp notification', 'email notification', 'order notification'],
  },
]
