/**
 * FAQ-gegevensbron (Nederlands). Prijs-/betaallogica kan later wijzigen (§13).
 * Eerlijkheidsregels: GEEN niet-geverifieerde ISO-/certificeringsclaims; er wordt
 * geen fysiek kantoor gesuggereerd; geen 24/7 menselijke ondersteuning beloofd;
 * het onderscheid beëdigde vertaling / notariële bekrachtiging / apostille blijft
 * behouden; geen gegarandeerde acceptatie door instanties.
 * `priority` = wereldwijde belangrijkheidsvolgorde (lager = hoger). De
 * categorieweergave gebruikt dezelfde volgorde, dus de volgorde binnen een
 * categorie wordt van deze waarde afgeleid.
 */
import type { FaqCategory, FaqItem } from './faq-data'

export const FAQ_CATEGORIES_NL: FaqCategory[] = [
  { key: "general", label: "Algemeen" },
  { key: "order", label: "Bestelproces" },
  { key: "pricing", label: "Prijzen en betaling" },
  { key: "upload", label: "Bestanden uploaden" },
  { key: "languages", label: "Talen en talenparen" },
  { key: "services", label: "Soorten diensten" },
  { key: "delivery", label: "Levering en levertijd" },
  { key: "sworn", label: "Beëdigde vertaling" },
  { key: "notary", label: "Notariële bekrachtiging en apostille" },
  { key: "quality", label: "Kwaliteit en revisies" },
  { key: "privacy", label: "Privacy en beveiliging" },
  { key: "corporate", label: "Zakelijke diensten" },
  { key: "support", label: "Technische ondersteuning" },
]

export const FAQ_ITEMS_NL: FaqItem[] = [
  // ——— ALLE: belangrijkste vragen langs de klantreis ———
  {
    id: 'nasil-fiyat-alirim',
    category: 'pricing',
    priority: 1,
    q: "Hoe krijg ik een offerte?",
    a: "Ga naar de pagina Prijs berekenen en upload uw document of plak uw tekst; zodra u het talenpaar en het soort dienst kiest, verschijnt uw prijsindicatie meteen. De prijs is gebaseerd op het talenpaar, het soort dienst, het aantal woorden en de aanvullende diensten die u kiest.",
    keywords: ["offerte", "prijs", "vertaalkosten", "prijs opvragen", "prijsindicatie", "wat kost een vertaling"],
  },
  {
    id: 'dosya-nasil-yuklenir',
    category: 'upload',
    priority: 2,
    q: "Hoe upload ik mijn bestand?",
    a: "Open op de pagina Prijs berekenen het tabblad 'Bestand uploaden' en sleep uw document erin of selecteer het handmatig. Heeft u geen bestand? Plak dan gewoon uw tekst in het tabblad 'Tekst invoeren'. Bij tekstbestanden telt het systeem het aantal woorden automatisch.",
    keywords: ["bestand uploaden", "document toevoegen", "bijlage", "kan niet uploaden", "hoe uploaden"],
  },
  {
    id: 'fiyatlandirma-neye-gore',
    category: 'pricing',
    priority: 3,
    q: "Waarop is de prijs gebaseerd?",
    a: "De prijs wordt bepaald door het talenpaar, het soort dienst, de inhoud van het document, het aantal woorden, het vakgebied en de aanvullende diensten die u kiest. Het bedrag dat u op het scherm ziet, is een voorlopige offerte; de definitieve prijs wordt bevestigd nadat wij het document hebben beoordeeld.",
    keywords: ["prijsbepaling", "tarief", "hoe wordt de prijs bepaald", "waar hangt de prijs van af", "per woord"],
  },
  {
    id: 'teslim-suresi-ne-kadar',
    category: 'delivery',
    priority: 4,
    q: "Wat is de levertijd?",
    a: "De levertijd hangt af van de lengte van het document, het talenpaar, het soort dienst en de aanvullende diensten die u kiest. Op het scherm Prijs berekenen ziet u een geschatte levertijd die specifiek is voor uw bestelling. Met de optie spoedlevering kunt u deze levertijd verkorten.",
    keywords: ["levertijd", "hoeveel dagen", "wanneer geleverd", "doorlooptijd", "hoe lang"],
  },
  {
    id: 'yeminli-tercume-nedir',
    category: 'sworn',
    priority: 5,
    q: "Wat is een beëdigde vertaling?",
    a: "Een beëdigde vertaling is een vertaling die door een beëdigd vertaler met handtekening en stempel wordt bekrachtigd, waarmee wordt verklaard dat de vertaling het origineel getrouw weergeeft. Ze wordt vaak gevraagd bij officiële aanvragen. Of ze verplicht is, hangt af van de instantie die het document opvraagt.",
    keywords: ["beëdigde vertaling", "officiële vertaling", "gestempelde vertaling", "wat is beëdigd", "beëdigd vertaler"],
  },
  {
    id: 'hangi-dillerde-hizmet',
    category: 'languages',
    priority: 6,
    q: "In welke talen bieden jullie diensten aan?",
    a: "Naast het Turks werken wij met talen als Engels, Duits, Frans, Spaans, Italiaans, Arabisch en Russisch, en in totaal in meer dan 50 talen. Voor zeldzame talen worden de beschikbaarheid van een vertaler en de levertijd per bestelling apart bevestigd.",
    keywords: ["talen", "welke talen", "taalopties", "talenparen", "hoeveel talen"],
  },
  {
    id: 'noter-onayi-gerekir-mi',
    category: 'notary',
    priority: 7,
    q: "Is notariële bekrachtiging nodig?",
    a: "Notariële bekrachtiging is niet voor elk document verplicht; of het nodig is, hangt af van de instantie die het document opvraagt en van het beoogde gebruik. Voor sommige procedures volstaat een beëdigde vertaling, terwijl voor andere ook notariële bekrachtiging wordt gevraagd. Weet u niet zeker welke bekrachtiging u nodig heeft, dan helpen wij u graag op weg.",
    keywords: ["notariële bekrachtiging", "notarieel", "notaris", "is notaris nodig"],
  },
  {
    id: 'siparis-nasil-ilerler',
    category: 'order',
    priority: 8,
    q: "Hoe verloopt het bestelproces?",
    a: "Zodra u uw document heeft geüpload en de voorlopige offerte heeft goedgekeurd, wordt uw bestelling aangemaakt en toegewezen aan een vertaler die gespecialiseerd is in het betreffende vakgebied. De vertaling gaat door een kwaliteitscontrole; indien nodig wordt de notariële bekrachtiging geregeld en wordt uw document digitaal geleverd, en waar nodig per koerier.",
    keywords: ["bestelproces", "hoe werkt het", "stappen", "proces"],
  },
  {
    id: 'belgelerim-guvende-mi',
    category: 'privacy',
    priority: 9,
    q: "Zijn mijn documenten veilig?",
    a: "Ja. Uw bestanden worden alleen ingezien door het team dat aan uw bestelling werkt en worden verwerkt via versleutelde overdracht en KVKK-conforme processen. Uw documenten worden nooit met derden gedeeld en vertrouwelijkheid staat voorop.",
    keywords: ["beveiliging", "vertrouwelijkheid", "documentbeveiliging", "gegevensbeveiliging", "kvkk"],
  },
  {
    id: 'cevirimi-kim-yapar',
    category: 'quality',
    priority: 10,
    q: "Wie vertaalt mijn document?",
    a: "Uw vertalingen worden gemaakt door professionele menselijke vertalers met ervaring in het betreffende vakgebied. Afhankelijk van het soort document wordt een gespecialiseerde vertaler toegewezen, en elke vertaling gaat vóór levering door een kwaliteitscontrole.",
    keywords: ["wie vertaalt", "vertaler", "menselijke vertaler", "wie doet het", "vertaalexpert"],
  },
  {
    id: 'revize-hakki-var-mi',
    category: 'quality',
    priority: 11,
    q: "Zijn revisies inbegrepen?",
    a: "Ja. Na levering van een vertaling heeft u recht op revisie voor correcties die binnen de oorspronkelijke opdracht vallen. Correcties van spelling, namen, datums of consistentie vallen hieronder. Het achteraf wijzigen van de brontekst of het toevoegen van nieuwe inhoud kan als nieuw werk gelden.",
    keywords: ["revisie", "correctie", "aanpassing", "opnieuw vertalen", "revisiebeleid"],
  },
  {
    id: 'fiziksel-teslimat-yapiliyor-mu',
    category: 'delivery',
    priority: 12,
    q: "Bieden jullie fysieke levering aan?",
    a: "Ja. Hoewel digitale levering standaard is, kunnen documenten met een originele handgeschreven handtekening en stempel per koerier naar uw adres worden gestuurd. Wij verzenden binnen heel Turkije en op verzoek ook naar het buitenland. Kiest u voor koerierlevering, dan wordt de verzendtijd bij de levertijd opgeteld.",
    keywords: ["fysieke levering", "koerier", "postbezorging", "levering op adres"],
  },
  {
    id: 'kurumsal-ozel-sartlar',
    category: 'corporate',
    priority: 13,
    q: "Zijn er speciale voorwaarden voor zakelijke klanten?",
    a: "Ja. Zakelijke klanten profiteren van voordelen bij grote bestellingen, betaaltermijnopties, terminologiebeheer en een vaste accountmanager. Voor meer informatie kunt u het aanvraagformulier op onze pagina Zakelijk invullen.",
    keywords: ["zakelijk", "bedrijf", "zakelijke voorwaarden", "grote bestelling", "bedrijfsklant"],
  },
  {
    id: 'apostil-nasil-yurutulur',
    category: 'notary',
    priority: 14,
    q: "Hoe verloopt de apostilleprocedure?",
    a: "Een apostille is een bekrachtiging die door de bevoegde autoriteit wordt afgegeven zodat een document in het buitenland als geldig wordt erkend. Wij voeren de apostilleprocedure niet uit; de apostille dient u zelf te verkrijgen bij de bevoegde autoriteit van het land waar uw document is opgesteld. Wij verzorgen uitsluitend de beëdigde vertaling van uw geapostilleerde documenten. In landen die geen partij zijn bij het Apostilleverdrag (Haags Verdrag) kan in plaats van een apostille een consulaire legalisatie nodig zijn.",
    keywords: ["apostille", "apostilleprocedure", "legalisatie", "geldig in buitenland"],
  },
  {
    id: 'acil-teslimat-mumkun-mu',
    category: 'delivery',
    priority: 15,
    q: "Is spoedlevering mogelijk?",
    a: "Ja, voor veel documenten is spoedlevering beschikbaar en wordt de levertijd verkort. Spoedlevering brengt extra kosten met zich mee; de beschikbaarheid kan variëren afhankelijk van de lengte en de taal van het document. Ook bij spoedbestellingen blijven de kwaliteitscontrolestappen behouden.",
    keywords: ["spoedlevering", "snelle levering", "dezelfde dag", "express", "spoed"],
  },
  {
    id: 'odeme-nasil-yapilir',
    category: 'pricing',
    priority: 16,
    q: "Hoe kan ik betalen?",
    a: "Betalingen kunnen worden gedaan met creditcard/betaalkaart of via bankoverschrijving; bij creditcards kan gespreid betalen beschikbaar zijn. Zakelijke klanten kunnen daarnaast op betaaltermijn factureren (15–30 dagen). De betaling wordt geïnd nadat u de voorlopige offerte heeft goedgekeurd.",
    keywords: ["betaling", "betaalmethode", "creditcard", "bankoverschrijving", "hoe betalen"],
  },
  {
    id: 'dosya-yuklemeden-fiyat',
    category: 'upload',
    priority: 17,
    q: "Kan ik een offerte krijgen zonder een bestand te uploaden?",
    a: "Ja. Heeft u geen bestand, plak dan uw tekst in het tabblad 'Tekst invoeren' om een voorlopige offerte op basis van het aantal woorden te krijgen.",
    keywords: ["offerte zonder bestand", "offerte via tekst", "zonder upload", "prijs met tekst"],
  },
  {
    id: 'belgenin-formati-korunur-mu',
    category: 'delivery',
    priority: 18,
    q: "Blijft de opmaak van het document behouden?",
    a: "Wij behouden de oorspronkelijke pagina-indeling, tabellen en opmaak in de vertaling zoveel mogelijk. Afhankelijk van uw wens kan de vertaling worden geleverd als pdf of als een bewerkbaar Word-bestand (DOCX). Bij gescande of beelddocumenten zorgen wij voor een nette, verzorgde indeling in plaats van een exacte kopie.",
    keywords: ["opmaak", "indeling", "pagina-indeling", "word", "pdf", "opmaak behouden"],
  },
  {
    id: 'teslim-sonrasi-destek',
    category: 'quality',
    priority: 19,
    q: "Kan ik ondersteuning krijgen nadat de vertaling is geleverd?",
    a: "Ja. Na levering is revisieondersteuning beschikbaar voor correcties binnen de opdracht, en u kunt met vragen contact opnemen met onze klantenservice. Aanvullende verzoeken over uw document kunt u per e-mail of via WhatsApp doorgeven.",
    keywords: ["ondersteuning na levering", "hulp na levering", "hulp", "support"],
  },
  {
    id: 'cok-sayfali-yuksek-hacim',
    category: 'order',
    priority: 20,
    q: "Hoe worden omvangrijke of grote projecten aangepakt?",
    a: "Grote projecten worden zorgvuldig gepland; waar nodig worden meerdere vertalers en redacteuren ingezet, en een gedeelde woordenlijst zorgt voor consistente terminologie. Lange projecten kunnen op verzoek in delen (gedeeltelijke levering) worden geleverd. Bij zakelijke projecten wordt het proces gecoördineerd door uw accountmanager.",
    keywords: ["veel pagina's", "groot volume", "grote opdracht", "groot project", "meerdere documenten"],
  },

  // ——— ALGEMEEN ———
  {
    id: 'tercumexpert-nedir',
    category: 'general',
    priority: 21,
    q: "Wat is TercümExpert?",
    a: "TercümExpert is een online aanbieder van vertaaldiensten die beëdigde vertalingen, notarieel bekrachtigde vertalingen, juridische, technische, medische en academische vertalingen en web-/mobiele lokalisatie aanbiedt. U kunt uw document uploaden, een voorlopige offerte ontvangen en uw bestelling volledig online plaatsen.",
    keywords: ["tercumexpert", "wat is het", "over ons", "vertaaldienst", "wat doen jullie"],
  },
  {
    id: 'hangi-hizmetler',
    category: 'general',
    priority: 22,
    q: "Welke diensten biedt TercümExpert aan?",
    a: "Wij bieden beëdigde en notarieel bekrachtigde vertalingen, de vertaling van geapostilleerde documenten, juridische, technische, medische en academische vertalingen en lokalisatie van websites en mobiele apps. Op het scherm Prijs berekenen kiest u de dienst die bij uw behoefte past.",
    keywords: ["diensten", "wat bieden jullie", "soorten diensten", "welke diensten"],
  },
  {
    id: 'kimler-hizmet-alabilir',
    category: 'general',
    priority: 23,
    q: "Wie kan gebruikmaken van jullie diensten?",
    a: "Zowel particuliere klanten als bedrijven en organisaties kunnen bij ons terecht. Van studenten tot zzp'ers en van kleine ondernemingen tot grote organisaties: wij bieden oplossingen die op verschillende behoeften zijn afgestemd.",
    keywords: ["wie kan gebruiken", "particulier", "zakelijk", "bedrijven", "klanten"],
  },
  {
    id: 'ofise-gelmek-gerekir-mi',
    category: 'general',
    priority: 24,
    q: "Moet ik langskomen op een kantoor?",
    a: "Ons bedrijf beschikt niet over een fysiek kantoor; onze diensten worden volledig online geleverd. U bezorgt ons uw documenten uitsluitend via een beveiligde upload; de levering vindt digitaal plaats en, waar nodig, per koerier. Voor vragen kunt u ons bereiken via WhatsApp of op info@tercumexpert.com.",
    keywords: ["kantoor", "langskomen", "vestiging", "adres", "bezoek nodig"],
  },
  {
    id: 'surec-cevrimici-mi',
    category: 'general',
    priority: 25,
    q: "Kan het hele proces online worden afgehandeld?",
    a: "Ja. Het uploaden van documenten, het goedkeuren van de offerte, de betaling en de digitale levering verlopen allemaal online. Alleen wanneer een fysiek document met originele handgeschreven handtekening nodig is, komt een koerier eraan te pas.",
    keywords: ["online", "volledig online", "op afstand", "via internet", "alles online"],
  },
  {
    id: 'yurt-disindan-hizmet',
    category: 'general',
    priority: 26,
    q: "Kunnen klanten in het buitenland gebruikmaken van jullie diensten?",
    a: "Ja. Omdat het proces online is, kunt u ook vanuit het buitenland documenten uploaden en bestellingen plaatsen. Digitale levering is overal mogelijk; voor documenten met een originele handgeschreven handtekening kunnen wij ook naar het buitenland verzenden.",
    keywords: ["buitenland", "internationale klanten", "vanuit het buitenland", "buiten turkije"],
  },
  {
    id: 'uyelik-zorunlu-mu',
    category: 'general',
    priority: 27,
    q: "Is een account verplicht om jullie diensten te gebruiken?",
    a: "Een account is niet verplicht. Om de prijs te bekijken en een bestelling te plaatsen, moet u wel uw voornaam, achternaam en e-mailadres invoeren en de verificatiecode bevestigen die naar uw e-mail wordt gestuurd. Desgewenst kunt u een account aanmaken om uw bestelgeschiedenis bij te houden.",
    keywords: ["account", "registreren", "aanmelden", "verplicht", "zonder account"],
  },
  {
    id: 'uye-olmadan-fiyat',
    category: 'general',
    priority: 28,
    q: "Kan ik een offerte krijgen zonder me te registreren?",
    a: "Ja, u kunt een offerte krijgen zonder een volledig account aan te maken; u hoeft alleen uw voornaam, achternaam en e-mailadres te verifiëren. Gebruikers die de verificatie niet voltooien, kunnen de prijs niet bekijken en geen bestelling plaatsen.",
    keywords: ["offerte zonder account", "zonder registratie", "verificatiecode", "e-mailverificatie"],
  },
  {
    id: 'siparis-oncesi-danismanlik',
    category: 'general',
    priority: 29,
    q: "Kan ik advies krijgen voordat ik bestel?",
    a: "Ja. Weet u niet zeker welke dienst u nodig heeft, dan kunt u informatie inwinnen via WhatsApp, e-mail of onze AI-chatassistent. Op basis van het soort document bepalen wij samen de juiste dienst en het juiste proces.",
    keywords: ["advies", "informatie", "vraag stellen", "hulp vooraf"],
  },
  {
    id: 'musteri-temsilcisi',
    category: 'general',
    priority: 30,
    q: "Hoe bereik ik een klantenservicemedewerker?",
    a: "U kunt onze klantenservice bereiken via WhatsApp of e-mail. Uw vragen worden tijdens kantooruren door een medewerker beantwoord; daarnaast kan onze AI-chatassistent op elk moment een eerste hulp bieden.",
    keywords: ["klantenservicemedewerker", "support", "contact", "bereiken", "live hulp"],
  },
  {
    id: 'hangi-belgeler-cevrilebilir',
    category: 'general',
    priority: 31,
    q: "Welke soorten documenten kunnen worden vertaald?",
    a: "Wij vertalen een breed scala, van officiële en persoonlijke documenten tot commerciële, juridische, technische, medische en academische teksten. Veel soorten documenten worden ondersteund, zoals diploma's, contracten, rapporten, handleidingen en websiteteksten.",
    keywords: ["soorten documenten", "welke documenten", "papieren", "wat kan vertaald worden"],
  },
  {
    id: 'yapay-zeka-mi-insan-mi',
    category: 'general',
    priority: 32,
    q: "Worden vertalingen door menselijke vertalers gemaakt?",
    a: "Ja. Uw vertalingen worden van begin tot eind gemaakt door professionele menselijke vertalers. Ter ondersteuning van consistentie en terminologie worden professionele vertaalhulpmiddelen (CAT-tools) gebruikt; de vertaling zelf is echter volledig het werk van gespecialiseerde vertalers en gaat door een kwaliteitscontrole.",
    keywords: ["menselijke vertaler", "cat-tool", "vertaalhulpmiddel", "machinevertaling", "wie vertaalt"],
  },
  {
    id: 'el-yazili-belgeler',
    category: 'general',
    priority: 33,
    q: "Kunnen handgeschreven of moeilijk leesbare documenten worden vertaald?",
    a: "Handgeschreven en moeilijk leesbare documenten kunnen worden vertaald, zolang ze leesbaar zijn. Onleesbare delen worden duidelijk in de vertaling aangegeven, en zo nodig vragen wij u om een duidelijkere kopie. Bij zulke documenten wordt de prijs na beoordeling definitief.",
    keywords: ["handschrift", "handgeschreven", "onleesbaar", "onduidelijk", "moeilijk leesbaar"],
  },
  {
    id: 'farkiniz-nedir',
    category: 'general',
    priority: 34,
    q: "Wat onderscheidt TercümExpert van andere vertaaldiensten?",
    a: "Ons volledig online proces, de automatische voorlopige offerte, gespecialiseerde menselijke vertalers en de kwaliteitscontrole zijn onze sterke punten. Bovendien bezorgen wij documenten met een originele handgeschreven handtekening per koerier tot bij u thuis.",
    keywords: ["verschil", "voordeel", "waarom tercumexpert", "wat maakt jullie anders"],
  },

  // ——— BESTELPROCES ———
  {
    id: 'siparis-nasil-verilir',
    category: 'order',
    priority: 35,
    q: "Hoe plaats ik een bestelling?",
    a: "Upload op het scherm Prijs berekenen uw document of voer uw tekst in, kies het talenpaar en het soort dienst en keur de voorlopige offerte goed. Zodra u goedkeurt, wordt uw bestelling aangemaakt.",
    keywords: ["bestelling plaatsen", "hoe bestellen", "bestelling aanmaken"],
  },
  {
    id: 'siparis-icin-gerekli-bilgiler',
    category: 'order',
    priority: 36,
    q: "Welke gegevens heb ik nodig om te bestellen?",
    a: "U heeft het te vertalen document of de te vertalen tekst, de bron- en doeltaal, het soort dienst en uw naam en e-mailadres voor contact nodig. Met deze gegevens kunt u uw bestelling aanmaken.",
    keywords: ["benodigde gegevens", "welke gegevens", "bestelgegevens"],
  },
  {
    id: 'dil-cifti-nasil-secilir',
    category: 'order',
    priority: 37,
    q: "Hoe kies ik het talenpaar en het soort dienst?",
    a: "Op het scherm Prijs berekenen kiest u in het menu de brontaal (de taal van het document), de doeltaal (de taal van de vertaling) en het soort dienst (beëdigd, notarieel bekrachtigd, technisch enz.). Weet u het niet zeker, dan helpen onze klantenservice of chatassistent u bij de juiste keuze.",
    keywords: ["talenpaar kiezen", "brontaal", "doeltaal", "dienst kiezen"],
  },
  {
    id: 'bilgiler-degistirilebilir-mi',
    category: 'order',
    priority: 38,
    q: "Kan ik de gegevens wijzigen nadat ik een bestelling heb aangemaakt?",
    a: "Gegevens zoals de taal, het soort dienst of het document kunnen worden aangepast voordat de vertaling begint. Neem hiervoor zo snel mogelijk contact op met onze klantenservice; naarmate het werk vordert, kan de ruimte voor wijzigingen beperkt worden.",
    keywords: ["gegevens wijzigen", "bestelling aanpassen", "bestelling bijwerken", "verkeerde taal", "verkeerd document"],
  },
  {
    id: 'onaydan-once-iptal',
    category: 'order',
    priority: 39,
    q: "Kan ik een bestelling annuleren voordat deze is goedgekeurd?",
    a: "Ja. U kunt uw bestelling annuleren voordat de betaling en de goedkeuring zijn voltooid; in dit stadium worden geen kosten in rekening gebracht.",
    keywords: ["annuleren", "bestelling annuleren", "afzien"],
  },
  {
    id: 'odeme-sonrasi-iptal',
    category: 'order',
    priority: 40,
    q: "Kan een bestelling na betaling worden geannuleerd?",
    a: "Zolang uw bestelling nog niet door een vertaler is aangenomen, kunt u deze annuleren via uw bestelpagina of via info@tercumexpert.com, en wordt uw betaling volledig terugbetaald via het oorspronkelijke betaalmiddel. Zodra de vertaling door een vertaler in behandeling is genomen, vindt gezien de persoonsgebonden aard van de dienst geen terugbetaling plaats.",
    keywords: ["annuleren na betaling", "terugbetaling", "geld terug"],
  },
  {
    id: 'siparis-durumu-takip',
    category: 'order',
    priority: 41,
    q: "Waar kan ik de status van mijn bestelling volgen?",
    a: "U wordt per e-mail op de hoogte gehouden van de status van uw bestelling, en als u een account heeft aangemaakt, kunt u deze daar ook volgen. Ook kunt u de actuele status opvragen bij onze klantenservice.",
    keywords: ["bestelling volgen", "status", "bestelstatus", "waar volgen"],
  },
  {
    id: 'birden-fazla-belge',
    category: 'order',
    priority: 42,
    q: "Kan één bestelling meerdere documenten of doeltalen bevatten?",
    a: "Ja, u kunt meerdere documenten in één bestelling uploaden en hetzelfde document naar meerdere talen laten vertalen. Het totale aantal woorden en elke doeltaal worden als afzonderlijke vertalingen geprijsd; het proces wordt via één aanvraag gecoördineerd.",
    keywords: ["meerdere documenten", "meerdere bestanden", "meerdere talen", "verschillende talen"],
  },
  {
    id: 'sonradan-dosya-eklenebilir',
    category: 'order',
    priority: 43,
    q: "Kan ik later een nieuw bestand aan een bestelling toevoegen?",
    a: "U kunt een nieuw bestand toevoegen voordat de vertaling begint; in dat geval wordt de prijs op basis van de toegevoegde inhoud bijgewerkt. Documenten die na de start van het werk worden toegevoegd, kunnen als een nieuwe post worden behandeld.",
    keywords: ["bestand toevoegen", "later toevoegen", "nieuw bestand"],
  },
  {
    id: 'eksik-belge-gonderilirse',
    category: 'order',
    priority: 44,
    q: "Wat gebeurt er als ik een onvolledig document instuur?",
    a: "Wanneer wij een ontbrekende pagina of een ontbrekend document opmerken, vragen wij u om het aan te vullen. Het uploaden van alle pagina's van het document is belangrijk om de vertaling volledig en geldig te maken.",
    keywords: ["onvolledig document", "ontbrekende pagina", "ontbrekend document"],
  },
  {
    id: 'terminoloji-not-referans',
    category: 'order',
    priority: 45,
    q: "Kan ik bestellingsspecifieke notities, terminologie of referentiebestanden toevoegen?",
    a: "Ja. Tijdens het bestellen kunt u speciale instructies, voorkeurstermen of een stijlnotitie toevoegen en referentiebestanden zoals eerdere vertalingen en woordenlijsten uploaden. Deze informatie wordt aan de vertaler doorgegeven en gebruikt voor consistentie.",
    keywords: ["notitie toevoegen", "speciale instructies", "terminologie", "referentiebestand", "woordenlijst"],
  },
  {
    id: 'eski-siparisler-goruntulenir',
    category: 'order',
    priority: 46,
    q: "Kan ik eerdere bestellingen en bestanden later inzien?",
    a: "Heeft u een account aangemaakt, dan kunt u uw eerdere bestellingen en geleverde bestanden daar bekijken. Bij bestellingen zonder account kunt u uw gegevens per e-mail raadplegen; is een downloadlink verlopen, dan kunt u bij onze klantenservice een nieuwe link aanvragen.",
    keywords: ["eerdere bestellingen", "bestelgeschiedenis", "vorige bestellingen", "toegang tot bestanden"],
  },

  // ——— PRIJZEN EN BETALING ———
  {
    id: 'kelime-mi-sayfa-mi',
    category: 'pricing',
    priority: 47,
    q: "Rekenen jullie per woord of per pagina?",
    a: "De prijs wordt doorgaans berekend op basis van het aantal woorden en de gekozen dienst. Bij tekstbestanden wordt het aantal woorden automatisch bepaald; bij gescande of beelddocumenten wordt het aantal na beoordeling bevestigd.",
    keywords: ["per woord", "per pagina", "prijsberekening", "hoe wordt gerekend"],
  },
  {
    id: 'sabit-baslangic-ucreti',
    category: 'pricing',
    priority: 48,
    q: "Is er een vast starttarief of een minimumbedrag?",
    a: "Bij sommige diensten kan een minimumtarief gelden, dat op korte documenten van toepassing kan zijn. De definitieve prijs wordt bepaald door de inhoud van het document en de diensten die u kiest, en u ziet alle posten op het scherm met de voorlopige offerte.",
    keywords: ["starttarief", "minimum", "vast tarief", "minimumbedrag"],
  },
  {
    id: 'neler-fiyati-etkiler',
    category: 'pricing',
    priority: 49,
    q: "Hebben het talenpaar, het soort document en het vakgebied invloed op de prijs?",
    a: "Ja. Het talenpaar (vooral zeldzame talen), het soort document en het vakgebied (juridisch, medisch, technisch enz.) kunnen de terminologische complexiteit en daarmee de prijs beïnvloeden. Bij veelvoorkomende talen is de prijs beter voorspelbaar.",
    keywords: ["talenpaar prijs", "documentsoort prijs", "vakgebied prijs", "waarom prijsverschil"],
  },
  {
    id: 'yeminli-daha-pahali-mi',
    category: 'pricing',
    priority: 50,
    q: "Is een beëdigde vertaling duurder?",
    a: "Een beëdigde vertaling kan anders geprijsd zijn dan een standaardvertaling vanwege de bekrachtiging en de verantwoordelijkheid van de vertaler. Het exacte bedrag wordt op het scherm met de voorlopige offerte getoond op basis van het document en het talenpaar.",
    keywords: ["prijs beëdigde vertaling", "kosten beëdigd", "is beëdigd duurder"],
  },
  {
    id: 'noter-apostil-ucreti-dahil',
    category: 'pricing',
    priority: 51,
    q: "Zijn de kosten voor notariële bekrachtiging en apostille bij de prijs inbegrepen?",
    a: "De notariële bekrachtiging is een afzonderlijke procedure die door de bevoegde instanties wordt uitgevoerd en aan officiële tarieven onderworpen is; deze kosten worden apart van de vertaalprijs weergegeven, en omdat ze een officieel tarief volgen, kunnen ze vooraf niet altijd exact zijn, waarbij het werkelijke bedrag na de procedure wordt meegedeeld. De apostilleprocedure voeren wij daarentegen niet uit; de apostille dient u zelf te verkrijgen bij de bevoegde autoriteit, en wij vertalen uitsluitend uw geapostilleerde document.",
    keywords: ["notariskosten", "apostillekosten", "inbegrepen", "notaris kosten", "apostille kosten"],
  },
  {
    id: 'on-fiyat-nihai-fark',
    category: 'pricing',
    priority: 52,
    q: "Kan de voorlopige offerte afwijken van de definitieve prijs?",
    a: "Ja. De automatische berekening die u op het scherm ziet, is een voorlopige offerte. Na een beoordeling op basis van het aantal woorden, de leesbaarheid of het soort document kan de definitieve prijs worden bevestigd. Het definitieve bedrag wordt met u gedeeld voordat u goedkeurt.",
    keywords: ["voorlopige offerte", "definitieve prijs", "prijsverschil", "exacte prijs"],
  },
  {
    id: 'otomatik-kelime-sayimi',
    category: 'pricing',
    priority: 53,
    q: "Wordt het aantal woorden automatisch berekend? En bij gescande pdf's?",
    a: "Bij tekstbestanden (Word, tekst-pdf, platte tekst) wordt het aantal woorden automatisch bepaald. Bij gescande of beeld-pdf's en foto's is automatisch tellen mogelijk niet betrouwbaar; in dat geval bevestigt ons team het aantal. De voorlopige offerte is gebaseerd op het automatische aantal en is niet bindend; bij een afwijking wordt de definitieve prijs aan u ter goedkeuring voorgelegd.",
    keywords: ["woorden tellen", "automatische telling", "gescande pdf", "beeld-pdf", "telfout"],
  },
  {
    id: 'toplu-kurumsal-indirim',
    category: 'pricing',
    priority: 54,
    q: "Zijn er kortingen voor grote bestellingen of zakelijke klanten?",
    a: "Voor grote en terugkerende opdrachten, in het bijzonder voor zakelijke klanten, kunnen wij voordelige prijzen en betaaltermijnopties aanbieden op basis van het volume en de samenwerkingsvoorwaarden. Voor meer informatie kunt u het aanvraagformulier op de pagina Zakelijk gebruiken.",
    keywords: ["kwantumkorting", "volumekorting", "zakelijke prijs", "bedrijfstarief"],
  },
  {
    id: 'ucretsiz-teklif',
    category: 'pricing',
    priority: 55,
    q: "Kan ik een gratis offerte krijgen en hoe lang is deze geldig?",
    a: "De voorlopige offerte is gratis; u ziet deze meteen wanneer u uw document uploadt of uw tekst invoert. Offertes zijn een korte periode geldig, zolang de omstandigheden (de inhoud/omvang van het document) niet veranderen.",
    keywords: ["gratis offerte", "kosteloze prijs", "geldigheid offerte", "hoe lang geldig"],
  },
  {
    id: 'fatura-kesiliyor-mu',
    category: 'pricing',
    priority: 56,
    q: "Ontvang ik een factuur? Kan ik een particuliere of zakelijke factuur krijgen?",
    a: "Ja. Voor de dienst wordt een factuur opgesteld, en u kunt een particuliere of zakelijke factuur aanvragen. Zakelijke klanten kunnen ook maandelijkse verzamelfacturen ontvangen. Belastingen worden toegepast volgens de geldende regelgeving.",
    keywords: ["factuur", "facturering", "btw", "zakelijke factuur", "particuliere factuur"],
  },
  {
    id: 'taksit-secenegi',
    category: 'pricing',
    priority: 57,
    q: "Is gespreid betalen mogelijk?",
    a: "Bij betaling met creditcard kan gespreid betalen beschikbaar zijn. Eventuele beschikbare termijnopties worden bij de betaalstap getoond.",
    keywords: ["gespreid betalen", "termijnbetaling", "in termijnen betalen"],
  },
  {
    id: 'kurumsal-vadeli-odeme',
    category: 'pricing',
    priority: 58,
    q: "Bieden jullie betaaltermijnen voor zakelijke klanten?",
    a: "Ja. Zakelijke klanten kunnen betaaltermijnen tot 15–30 dagen en maandelijkse facturering krijgen. De voorwaarden worden vastgelegd binnen de zakelijke afspraak.",
    keywords: ["betaaltermijn", "op rekening", "zakelijke betaling"],
  },
  {
    id: 'odeme-yapilmadan-baslar-mi',
    category: 'pricing',
    priority: 59,
    q: "Begint de vertaling voordat er is betaald?",
    a: "Bij standaardbestellingen begint de vertaling nadat de betaling (of de goedkeuring van de zakelijke betaaltermijn) is ontvangen. Bij zakelijke overeenkomsten kan het proces volgens het contract verlopen.",
    keywords: ["vooruitbetaling", "voor betaling", "vooraf betalen", "zonder betaling"],
  },
  {
    id: 'iade-sureci',
    category: 'pricing',
    priority: 60,
    q: "Worden geannuleerde bestellingen terugbetaald?",
    a: "Wordt uw bestelling geannuleerd voordat deze door een vertaler is aangenomen, dan wordt uw betaling volledig terugbetaald via het oorspronkelijke betaalmiddel. Zodra de vertaling door een vertaler in behandeling is genomen, vindt gezien de persoonsgebonden aard van de dienst geen terugbetaling plaats. In gevallen als een dubbele of onjuiste afschrijving wordt het te veel betaalde bedrag terugbetaald.",
    keywords: ["terugbetaling", "geld terug", "terugbetaling bij annulering", "restitutie"],
  },

  // ——— BESTANDEN UPLOADEN ———
  {
    id: 'hangi-formatlar',
    category: 'upload',
    priority: 61,
    q: "Welke bestandsformaten worden ondersteund?",
    a: "Wij accepteren meer dan 50 formaten, waaronder Word (DOC/DOCX), PDF, platte tekst (TXT), Excel, PowerPoint en veelvoorkomende beeldformaten (JPG, PNG). Bij tekstbestanden wordt het aantal woorden automatisch bepaald.",
    keywords: ["bestandsformaat", "ondersteunde formaten", "pdf", "doc", "docx", "txt"],
  },
  {
    id: 'taranmis-fotograf-belge',
    category: 'upload',
    priority: 62,
    q: "Worden gescande documenten of foto's geaccepteerd?",
    a: "Ja. Gescande documenten en duidelijke foto's die met een telefoon zijn gemaakt, worden geaccepteerd. Leesbaarheid is belangrijk; zegels, stempels en handtekeningen moeten zichtbaar zijn. Omdat tekst in afbeeldingen mogelijk niet automatisch wordt gelezen, bepaalt ons team het aantal woorden.",
    keywords: ["gescand document", "foto van document", "telefoonfoto", "afbeelding uploaden", "foto"],
  },
  {
    id: 'birden-fazla-dosya-yukleme',
    category: 'upload',
    priority: 63,
    q: "Kan ik meerdere bestanden tegelijk uploaden?",
    a: "Ja, u kunt meerdere bestanden tegelijk uploaden. De prijs wordt berekend op basis van de totale inhoud.",
    keywords: ["meerdere uploaden", "meerdere bestanden", "bulk uploaden"],
  },
  {
    id: 'dosya-boyutu-siniri',
    category: 'upload',
    priority: 64,
    q: "Is er een limiet voor de bestandsgrootte? Hoe verstuur ik grote bestanden?",
    a: "U kunt tot ongeveer 100 MB per bestand uploaden. Voor grotere bestanden kunt u contact opnemen met onze klantenservice om levering per e-mail of via een andere methode te regelen.",
    keywords: ["bestandsgrootte", "groottelimiet", "groot bestand", "100 mb"],
  },
  {
    id: 'yuklenen-dosya-silinebilir',
    category: 'upload',
    priority: 65,
    q: "Kan ik een geüpload bestand verwijderen of vervangen?",
    a: "Ja. Voordat de bestelling is voltooid, kunt u het geüploade bestand verwijderen of door een nieuw bestand vervangen.",
    keywords: ["bestand verwijderen", "bestand vervangen", "verkeerd bestand"],
  },
  {
    id: 'manuel-kelime-girisi',
    category: 'upload',
    priority: 66,
    q: "Kan ik het aantal woorden handmatig invoeren zonder een bestand te uploaden?",
    a: "In plaats van een aantal rechtstreeks in te voeren, plakt u uw tekst in het tabblad 'Tekst invoeren' en wordt het aantal woorden automatisch berekend. Zo krijgt u een voorlopige offerte zonder bestand.",
    keywords: ["handmatig woorden", "woorden invoeren", "tekst invoeren"],
  },
  {
    id: 'dosyalar-ne-kadar-saklanir',
    category: 'upload',
    priority: 67,
    q: "Hoe lang worden bestanden bewaard en kan ik verwijdering aanvragen?",
    a: "Uw documenten worden alleen zo lang als de dienst dat vereist veilig bewaard. U kunt op elk moment verzoeken om uw documenten te verwijderen; dit verzoek wordt gehonoreerd in overeenstemming met uw rechten onder de KVKK.",
    keywords: ["bewaartermijn", "bestandsopslag", "verwijderingsverzoek", "gegevens verwijderen"],
  },
  {
    id: 'belgenin-tum-sayfalari',
    category: 'upload',
    priority: 68,
    q: "Moet ik alle pagina's en de achterzijden van het document uploaden?",
    a: "Ja. Om de vertaling volledig en geldig te maken, moet u alle pagina's van het document uploaden, waar van toepassing inclusief de achterzijden. Het is belangrijk dat de zones met zegel, stempel en handtekening duidelijk zichtbaar zijn.",
    keywords: ["alle pagina's", "achterzijde", "volledig document", "zegel en stempel"],
  },
  {
    id: 'imza-kase-cevrilir-mi',
    category: 'upload',
    priority: 69,
    q: "Worden stempels, zegels en handtekeningen vertaald?",
    a: "Bij een beëdigde vertaling wordt de leesbare tekst op stempels en zegels overgenomen; handtekeningen worden aangeduid als \"handtekening aanwezig\". Onleesbare zones worden duidelijk in de vertaling aangegeven.",
    keywords: ["stempel vertalen", "zegel vertalen", "handtekening vertalen"],
  },
  {
    id: 'dosya-guvenli-mi-analiz',
    category: 'upload',
    priority: 70,
    q: "Is de inhoud van mijn document veilig tijdens de automatische analyse?",
    a: "Ja. Documenten worden versleuteld overgedragen en bewerkingen zoals het tellen van woorden gebeuren in een beveiligde omgeving. Uw inhoud wordt nooit met derden gedeeld.",
    keywords: ["veilige analyse", "inhoudsbeveiliging", "automatisch uitlezen"],
  },

  // ——— TALEN EN TALENPAREN ———
  {
    id: '50-dil-ne-demek',
    category: 'languages',
    priority: 71,
    q: "Wat betekent ondersteuning voor meer dan 50 talen?",
    a: "Het betekent dat wij naast veelvoorkomende talen ook minder gevraagde talen kunnen vertalen. Voor zeldzame talen worden de beschikbaarheid van een vertaler, de levertijd en de prijs per bestelling apart bevestigd.",
    keywords: ["50 talen", "zeldzame taal", "taalondersteuning", "hoeveel talen"],
  },
  {
    id: 'yaygin-dil-ciftleri',
    category: 'languages',
    priority: 72,
    q: "Vertalen jullie talenparen zoals Turks-Engels, Duits en Frans?",
    a: "Ja. Wij vertalen veelvoorkomende talenparen zoals Turks ⇄ Engels, Duits, Frans, Spaans, Italiaans, Arabisch en Russisch in beide richtingen. Talen als Chinees en Japans worden ook ondersteund.",
    keywords: ["turks engels", "engels turks", "duits", "frans", "talenpaar"],
  },
  {
    id: 'yabancidan-yabanciya',
    category: 'languages',
    priority: 73,
    q: "Kunnen jullie vertalen tussen twee vreemde talen anders dan het Turks?",
    a: "Ja, wij kunnen van de ene vreemde taal naar de andere vertalen, bijvoorbeeld Engels naar Frans. Beschikbaarheid en levertijd worden beoordeeld op basis van het talenpaar.",
    keywords: ["vreemde taal naar vreemde taal", "engels frans", "tussen talen"],
  },
  {
    id: 'nadir-dil',
    category: 'languages',
    priority: 74,
    q: "Bieden jullie diensten aan voor zeldzame of niet-vermelde talen?",
    a: "Wij streven ernaar ook zeldzame talen aan te bieden; de beschikbaarheid van een vertaler, de levertijd en de prijs worden voor deze talen echter apart bevestigd. Staat de taal die u nodig heeft niet in de lijst, neem dan contact op met onze klantenservice voor een offerte op maat.",
    keywords: ["zeldzame taal", "ongebruikelijke taal", "niet-vermelde taal", "bijzondere taal"],
  },
  {
    id: 'dil-varyantlari',
    category: 'languages',
    priority: 75,
    q: "Kan ik een regionale taalvariant kiezen (zoals Amerikaans of Brits Engels)?",
    a: "Ja, waar mogelijk kunt u een regionale variant van de doeltaal opgeven (bijv. Amerikaans/Brits Engels, Europees/Latijns-Amerikaans Spaans). Geeft u geen variant op, dan wordt de gangbare standaard gebruikt.",
    keywords: ["variant", "amerikaans engels", "regionale taal", "dialect"],
  },
  {
    id: 'anadili-tercuman',
    category: 'languages',
    priority: 76,
    q: "Werken jullie met vertalers die de doeltaal als moedertaal hebben?",
    a: "Waar mogelijk werken wij met ervaren vertalers die de doeltaal beheersen. Het doel is een natuurlijke en accurate vertaling te leveren.",
    keywords: ["moedertaalvertaler", "native speaker", "doeltaalexpert"],
  },
  {
    id: 'osmanlica-eski-yazi',
    category: 'languages',
    priority: 77,
    q: "Kunnen documenten in het Ottomaans-Turks of oud schrift worden vertaald?",
    a: "Documenten in het Ottomaans-Turks en in het oude alfabet kunnen worden vertaald, afhankelijk van de beschikbaarheid van een specialist. Bij zulke documenten worden de levertijd en de prijs na beoordeling definitief.",
    keywords: ["ottomaans-turks", "oud schrift", "oud alfabet"],
  },
  {
    id: 'karisik-dilli-belge',
    category: 'languages',
    priority: 78,
    q: "Kan een document worden vertaald als het meer dan één taal bevat?",
    a: "Ja. Documenten met gemengde talen kunnen worden vertaald; de prijs wordt bepaald door de hoeveelheid inhoud in elke taal. U hoeft alleen de gewenste doeltaal op te geven.",
    keywords: ["gemengde taal", "meertalig document", "meerdere talen in document"],
  },

  // ——— SOORTEN DIENSTEN ———
  {
    id: 'hangi-hizmeti-secmeliyim',
    category: 'services',
    priority: 79,
    q: "Welk soort dienst moet ik kiezen?",
    a: "Waar u het document zult gebruiken, bepaalt de keuze van de dienst: officiële aanvragen vereisen meestal een beëdigde vertaling, terwijl sommige procedures een notarieel bekrachtigde of geapostilleerde vertaling vragen. Weet u het niet zeker, dan helpen onze klantenservice of chatassistent u; de definitieve vereiste hangt af van de betreffende instantie.",
    keywords: ["welke dienst", "dienstkeuze", "wat kiezen"],
  },
  {
    id: 'standart-yeminli-fark',
    category: 'services',
    priority: 80,
    q: "Wat is het verschil tussen een standaardvertaling en een beëdigde vertaling?",
    a: "Een standaardvertaling is bedoeld ter informatie en draagt geen officiële bekrachtiging. Een beëdigde vertaling wordt bekrachtigd met de stempel en handtekening van de beëdigd vertaler en is vereist bij officiële aanvragen. Welke u nodig heeft, hangt af van de instantie waarbij het document wordt ingediend.",
    keywords: ["standaard versus beëdigd", "verschil", "gewone vertaling", "beëdigd verschil"],
  },
  {
    id: 'yeminli-noter-ayni-mi',
    category: 'services',
    priority: 81,
    q: "Zijn een beëdigde vertaling en een notarieel bekrachtigde vertaling hetzelfde?",
    a: "Nee. Een beëdigde vertaling draagt de bekrachtiging van de beëdigd vertaler. Een notarieel bekrachtigde vertaling is diezelfde vertaling die daarnaast door een notaris wordt bekrachtigd. Sommige instanties vragen alleen een beëdigde vertaling, andere vragen ook notariële bekrachtiging.",
    keywords: ["beëdigd versus notarieel", "notarieel bekrachtigde vertaling", "zijn ze hetzelfde"],
  },
  {
    id: 'hukuki-teknik-medikal',
    category: 'services',
    priority: 82,
    q: "Hoe wordt de expertise geborgd bij juridische, technische en medische vertalingen?",
    a: "Contracten, gerechtelijke documenten, technische documentatie en medische documenten worden vertaald door ervaren vertalers die de terminologie van het betreffende vakgebied beheersen. Terminologielijsten en vertaalgeheugen zorgen voor consistentie, opmaak en eenheden blijven behouden en de vertaling gaat door een kwaliteitscontrole.",
    keywords: ["juridische vertaling", "technische vertaling", "medische vertaling", "gespecialiseerde vertaler", "terminologie"],
  },
  {
    id: 'akademik-bicim-korunur',
    category: 'services',
    priority: 83,
    q: "Blijven de literatuurlijst en opmaak behouden bij academische vertalingen?",
    a: "Ja. Bij scripties, artikelen en academische teksten blijven de opmaak van de literatuurlijst, de bronvermeldingen en de opmaak zoveel mogelijk behouden, en de vertaling volgt de academische stijl.",
    keywords: ["academische vertaling", "scriptie", "artikel", "literatuurlijst", "bronvermeldingen"],
  },
  {
    id: 'lokalizasyon-nedir',
    category: 'services',
    priority: 84,
    q: "Is lokalisatie alleen een woord-voor-woordvertaling? Wordt er rekening gehouden met SEO?",
    a: "Nee. Lokalisatie betekent dat de tekst wordt aangepast aan de doelcultuur en het gebruik; de interface, de datum-/valutaopmaak en de toon worden op de doelgroep afgestemd. Bij websitelokalisatie kunnen op verzoek zoekwoorden in de doeltaal en SEO-afstemming worden meegenomen.",
    keywords: ["lokalisatie", "vertaling website", "app-vertaling", "seo", "lokaliseren"],
  },
  {
    id: 'kurumsal-marka-dili',
    category: 'services',
    priority: 85,
    q: "Blijft de merkstijl behouden bij zakelijke teksten?",
    a: "Ja. Bij zakelijke vertalingen zorgen een terminologiebank en een stijlgids ervoor dat uw merkstijl en toon consistent blijven.",
    keywords: ["merkstijl", "zakelijke toon", "stijlgids"],
  },
  {
    id: 'vize-diploma-hangi-hizmet',
    category: 'services',
    priority: 86,
    q: "Welke dienst heb ik nodig voor documenten zoals een visum of diploma?",
    a: "Voor visumaanvragen en diplomavertalingen is een beëdigde vertaling meestal de basisvereiste; sommige vertegenwoordigingen of instanties kunnen daarnaast om notariële bekrachtiging of een apostille vragen. De precieze vereiste hangt af van het consulaat of de instantie waar u de aanvraag indient.",
    keywords: ["visumdocument", "diplomavertaling", "cijferlijst", "consulaat", "visumvertaling"],
  },
  {
    id: 'belge-turu-listede-yok',
    category: 'services',
    priority: 87,
    q: "Wat moet ik kiezen als mijn soort document niet in de lijst staat?",
    a: "Staat uw soort document niet in de lijst, kies dan de dichtstbijzijnde optie en voeg een toelichting toe in de bestelnotitie. Desgewenst helpt onze klantenservice u bij de juiste keuze.",
    keywords: ["documentsoort niet vermeld", "ander document", "niet in lijst"],
  },

  // ——— LEVERING EN LEVERTIJD ———
  {
    id: 'teslim-suresi-nasil-hesaplanir',
    category: 'delivery',
    priority: 88,
    q: "Hoe wordt de levertijd berekend en waar wordt deze getoond?",
    a: "De levertijd wordt berekend op basis van de lengte van het document, het talenpaar, het soort dienst en de aanvullende diensten, en wordt als geschatte leverdatum getoond op het scherm Prijs berekenen. Bij procedures die notariële bekrachtiging of een apostille vereisen, kunnen extra dagen worden toegevoegd; verandert de leverdatum, dan wordt u op de hoogte gebracht.",
    keywords: ["berekening levertijd", "geschatte levering", "wanneer klaar"],
  },
  {
    id: 'ayni-gun-teslimat',
    category: 'delivery',
    priority: 89,
    q: "Is levering op dezelfde dag of binnen 24 uur mogelijk?",
    a: "Voor korte documenten is snelle of spoedlevering vaak mogelijk; de beschikbaarheid hangt af van de lengte en de taal van het document. Ook bij spoedlevering blijven de kwaliteitscontrolestappen behouden, en de optie wordt als een extra post getoond op het scherm met de voorlopige offerte.",
    keywords: ["dezelfde dag", "24 uur", "snelle levering", "spoed"],
  },
  {
    id: 'hafta-sonu-tatil',
    category: 'delivery',
    priority: 90,
    q: "Wanneer worden bestellingen in het weekend of buiten kantooruren verwerkt?",
    a: "U kunt op elk moment documenten uploaden, offertes opvragen en bestellingen aanmaken. Bestellingen die buiten kantooruren of op feestdagen worden geplaatst, worden aan het begin van de volgende werkuren verwerkt, en de geschatte levertijd wordt daarop afgestemd.",
    keywords: ["weekend", "feestdag", "buiten kantooruren", "bestelling 's nachts"],
  },
  {
    id: 'dijital-teslim-format',
    category: 'delivery',
    priority: 91,
    q: "Hoe verloopt de digitale levering en in welk formaat ontvang ik de vertaling?",
    a: "De voltooide vertaling wordt digitaal geleverd via een downloadlink of per e-mail. Afhankelijk van uw wens kunt u deze ontvangen als pdf of als een bewerkbaar Word-bestand (DOCX); de oorspronkelijke opmaak blijft zoveel mogelijk behouden.",
    keywords: ["digitale levering", "levering in word", "levering in pdf", "downloaden"],
  },
  {
    id: 'kargo-kapsam-takip',
    category: 'delivery',
    priority: 92,
    q: "Naar welke regio's verzenden jullie en kan ik de zending volgen?",
    a: "Documenten met een originele handgeschreven handtekening en stempel worden per koerier binnen heel Turkije verzonden; op verzoek verzenden wij ook naar het buitenland. De trackinggegevens van de koerier worden met u gedeeld, en de verzendtijd wordt bij de totale levertijd opgeteld.",
    keywords: ["verzendregio's", "koerier volgen", "internationale verzending", "verzendtijd"],
  },
  {
    id: 'kismi-teslimat',
    category: 'delivery',
    priority: 93,
    q: "Kunnen lange projecten in delen worden geleverd?",
    a: "Ja. Grote of lange projecten kunnen op verzoek in delen worden geleverd. Zo kunt u uw documenten gebruiken zonder te hoeven wachten.",
    keywords: ["gedeeltelijke levering", "in delen", "levering per deel"],
  },

  // ——— BEËDIGDE VERTALING ———
  {
    id: 'yeminli-tercuman-kim',
    category: 'sworn',
    priority: 94,
    q: "Wie is een beëdigd vertaler?",
    a: "Een beëdigd vertaler is een vertaler die ten overstaan van een notaris een eed heeft afgelegd en daarmee de bevoegdheid heeft verkregen om zijn vertalingen met een handtekening en stempel te bekrachtigen. Deze bekrachtiging is een verklaring dat de vertaling het origineel getrouw weergeeft.",
    keywords: ["beëdigd vertaler", "wie is beëdigd vertaler", "gecertificeerd vertaler"],
  },
  {
    id: 'yeminli-ne-zaman-gerekli',
    category: 'sworn',
    priority: 95,
    q: "Wanneer is een beëdigde vertaling vereist?",
    a: "Beëdigde vertalingen worden vaak gevraagd bij aanvragen bij officiële instanties, rechtbanken, consulaten en universiteiten. Ze zijn echter niet voor elk document verplicht; de precieze vereiste wordt bepaald door de instantie die het document opvraagt.",
    keywords: ["wanneer beëdigd vereist", "is beëdigd nodig", "waar vereist"],
  },
  {
    id: 'yeminli-nerede-gecerli',
    category: 'sworn',
    priority: 96,
    q: "Is een beëdigde vertaling geldig bij de rechtbank, het consulaat en in het buitenland?",
    a: "Een beëdigde vertaling kan bij veel officiële procedures en aanvragen worden gebruikt. De voorwaarden waaronder een instantie een document accepteert, hangen echter af van haar eigen regelgeving; vooral in het buitenland kan ook notariële bekrachtiging of een apostille vereist zijn. Wij raden u aan de acceptatievereisten bij de betreffende instantie te bevestigen.",
    keywords: ["rechtbank", "consulaat", "geldig in buitenland", "universiteitsaanvraag"],
  },
  {
    id: 'dijital-imzali-yeminli',
    category: 'sworn',
    priority: 97,
    q: "Kan een beëdigde vertaling met een digitale/elektronische handtekening worden afgegeven?",
    a: "Nee. Een beëdigde vertaling wordt opgesteld met de originele handgeschreven handtekening en stempel van de vertaler en wordt fysiek per koerier geleverd.",
    keywords: ["elektronische handtekening", "digitaal beëdigd", "e-handtekening", "originele handtekening", "stempel"],
  },
  {
    id: 'yeminli-orijinal-gerekir',
    category: 'sworn',
    priority: 98,
    q: "Is het originele document nodig voor een beëdigde vertaling?",
    a: "De vertaling kan doorgaans worden gemaakt op basis van een duidelijke kopie (scan of foto) van het document. Is echter notariële bekrachtiging vereist, dan kan voor die procedure het origineel of een gewaarmerkt afschrift van het document worden gevraagd.",
    keywords: ["origineel document", "is origineel nodig", "kopie voor beëdigd"],
  },
  {
    id: 'yeminli-gecerlilik-suresi',
    category: 'sworn',
    priority: 99,
    q: "Heeft een beëdigde vertaling een houdbaarheidsdatum?",
    a: "De vertaling zelf is niet aan een termijn gebonden; sommige instanties kunnen echter om een recent gedateerd document vragen. Dit hangt af van de vereisten van de instantie die het document zal accepteren.",
    keywords: ["houdbaarheidsdatum", "geldigheid beëdigd", "hoe lang geldig"],
  },
  {
    id: 'kurum-belgeyi-kabul-etmezse',
    category: 'sworn',
    priority: 100,
    q: "Wat gebeurt er als een instantie de beëdigde vertaling niet accepteert?",
    a: "Acceptatievereisten kunnen per instantie verschillen. Heeft de instantie een specifieke opmaak- of bekrachtigingseis, laat het ons dan weten en wij brengen de nodige aanpassingen aan. De uiteindelijke beslissing over acceptatie ligt bij de instantie.",
    keywords: ["niet geaccepteerd", "afwijzing door instantie", "opmaakeis"],
  },

  // ——— NOTARIËLE BEKRACHTIGING EN APOSTILLE ———
  {
    id: 'noter-onayli-nedir',
    category: 'notary',
    priority: 101,
    q: "Wat is een notarieel bekrachtigde vertaling?",
    a: "Een notarieel bekrachtigde vertaling is een beëdigde vertaling die daarnaast door een notaris wordt bekrachtigd. Deze bekrachtiging versterkt de officiële geldigheid van de vertaling en wordt door sommige instanties gevraagd.",
    keywords: ["notarieel bekrachtigde vertaling", "notariële bekrachtiging", "wat is notarieel"],
  },
  {
    id: 'noter-yeminli-fark',
    category: 'notary',
    priority: 102,
    q: "Wat is het verschil tussen notariële bekrachtiging en een beëdigde vertaling?",
    a: "Een beëdigde vertaling draagt de bekrachtiging van de vertaler, terwijl notariële bekrachtiging de bekrachtiging van die vertaling door de notaris is. Notariële bekrachtiging is een aanvullende officiële stap boven op een beëdigde vertaling.",
    keywords: ["notarieel versus beëdigd", "verschil in bekrachtiging"],
  },
  {
    id: 'notere-gitmem-gerekir-mi',
    category: 'notary',
    priority: 103,
    q: "Moet ik voor de notariële bekrachtiging naar de notaris?",
    a: "In de meeste gevallen kunnen wij de notariële bekrachtiging voor u regelen, zodat u niet zelf naar de notaris hoeft. Is het originele document vereist, dan laten wij u dat vooraf weten.",
    keywords: ["naar de notaris", "notarisprocedure", "notaris namens mij"],
  },
  {
    id: 'apostil-nedir',
    category: 'notary',
    priority: 104,
    q: "Wat is een apostille en hoe verschilt deze van notariële bekrachtiging?",
    a: "Een apostille is een internationale bekrachtiging die door de bevoegde autoriteit wordt afgegeven zodat een officieel document in een ander land als geldig wordt erkend, en geldt tussen landen die partij zijn bij het Apostilleverdrag (Haags Verdrag). Notariële bekrachtiging is daarentegen een bekrachtiging binnen een land; beide dienen een verschillend doel.",
    keywords: ["wat is apostille", "apostille versus notaris", "haags verdrag"],
  },
  {
    id: 'apostil-once-mi-ceviri-once-mi',
    category: 'notary',
    priority: 105,
    q: "Wat komt eerst, de apostille of de vertaling?",
    a: "De volgorde hangt af van het soort document en de vereisten van het land waar het zal worden gebruikt. In sommige gevallen wordt het document eerst geapostilleerd en daarna vertaald; in andere gevallen is het andersom. Wij kunnen de juiste volgorde samen bepalen.",
    keywords: ["volgorde apostille", "eerst vertalen of eerst apostille", "volgorde"],
  },
  {
    id: 'yabanci-belge-turkiye',
    category: 'notary',
    priority: 106,
    q: "Hoe verloopt het proces als een buitenlands document in Turkije wordt gebruikt?",
    a: "Een document uit het buitenland wordt doorgaans eerst in het land van herkomst geapostilleerd en vervolgens in Turkije beëdigd vertaald (en indien nodig notarieel bekrachtigd). Het precieze proces hangt af van de Turkse instantie die het document opvraagt.",
    keywords: ["buitenlands document in turkije", "inkomend document", "document uit buitenland"],
  },
  {
    id: 'turk-belge-yurt-disi',
    category: 'notary',
    priority: 107,
    q: "Hoe verloopt het proces als een Turks document in het buitenland wordt gebruikt?",
    a: "Een in Turkije opgesteld document wordt doorgaans geapostilleerd en beëdigd vertaald naar de doeltaal. Is het land van bestemming geen partij bij het Apostilleverdrag (Haags Verdrag), dan kan in plaats van een apostille een consulaire legalisatie nodig zijn.",
    keywords: ["turks document in buitenland", "uitgaand document", "consulaire legalisatie"],
  },
  {
    id: 'hangi-onay-gerekli-bilinmiyor',
    category: 'notary',
    priority: 109,
    q: "Hoe kom ik erachter of notariële bekrachtiging of een apostille nodig is?",
    a: "De betrouwbaarste manier is het vragen aan de instantie die het document opvraagt. Desgewenst kan onze klantenservice u wijzen op gangbare praktijken; de precieze vereiste verschilt echter per instantie en per land.",
    keywords: ["welke bekrachtiging", "is bekrachtiging nodig", "notaris of apostille"],
  },
  {
    id: 'kesin-kabul-garantisi',
    category: 'notary',
    priority: 110,
    q: "Garandeert TercümExpert acceptatie?",
    a: "Wij zorgen ervoor dat de vertaling en de bekrachtigingen correct en volledig worden opgesteld; de voorwaarden voor acceptatie van een document worden echter bepaald door de instantie die het opvraagt. Daarom kunnen wij geen onvoorwaardelijke acceptatiegarantie bieden; deelt u de specifieke vereisten van de instantie, dan brengen wij de nodige aanpassingen aan.",
    keywords: ["acceptatiegarantie", "gegarandeerde acceptatie", "garantie"],
  },

  // ——— KWALITEIT EN REVISIES ———
  {
    id: 'tercumanlar-nasil-secilir',
    category: 'quality',
    priority: 111,
    q: "Hoe worden vertalers geselecteerd en hoe wordt hun expertise bepaald?",
    a: "Vertalers worden gekozen op basis van het talenpaar en het vakgebied van het document; een juridisch document gaat naar een vertaler met ervaring in het recht en een medisch document naar een vertaler met ervaring in de zorg. De meest geschikte vertaler wordt toegewezen met oog voor vakervaring en taalbeheersing.",
    keywords: ["selectie vertaler", "hoe worden vertalers gekozen", "expertise", "vakexpert"],
  },
  {
    id: 'kalite-kontrol',
    category: 'quality',
    priority: 112,
    q: "Gaat de vertaling door een kwaliteitscontrole?",
    a: "Ja. Vertalingen worden gecontroleerd op spelling, terminologie, consistentie van getallen/namen/datums en opmaak. Afhankelijk van het soort document en het serviceniveau kan een onafhankelijke redactie-/proefleesstap worden toegepast.",
    keywords: ["kwaliteitscontrole", "proeflezen", "redacteur", "controle"],
  },
  {
    id: 'ceviri-bellegi',
    category: 'quality',
    priority: 113,
    q: "Gebruiken jullie een vertaalgeheugen of terminologielijsten?",
    a: "Ja, vooral bij technische en zakelijke projecten worden een vertaalgeheugen en terminologielijsten gebruikt om consistentie te waarborgen. U kunt ook uw eigen termenlijst delen; de terminologie uit eerdere projecten blijft behouden.",
    keywords: ["vertaalgeheugen", "terminologielijst", "consistentie"],
  },
  {
    id: 'revize-kapsami',
    category: 'quality',
    priority: 114,
    q: "Wat valt onder een revisie en wanneer moet ik deze aanvragen?",
    a: "Een revisie dekt zaken als vertaalfouten, spelling, inconsistenties en weggelaten passages. Het achteraf wijzigen van de brontekst of het toevoegen van nieuwe inhoud kan als nieuw werk gelden. Wij raden u aan uw revisieverzoek binnen een redelijke termijn na levering per e-mail of via WhatsApp door te geven.",
    keywords: ["omvang revisie", "omvang correctie", "revisietermijn", "wanneer revisie"],
  },
  {
    id: 'tercuman-degisikligi',
    category: 'quality',
    priority: 115,
    q: "Wat als ik niet tevreden ben over de vertaling — kan de vertaler worden gewijzigd?",
    a: "Bent u niet tevreden over de vertaling, dan bekijken wij de situatie en regelen wij zo nodig correcties met een andere vertaler of redacteur. Het doel is dat het resultaat aan uw verwachtingen voldoet.",
    keywords: ["vertaler wijzigen", "niet tevreden", "ontevreden over vertaling"],
  },
  {
    id: 'dogruluk-garanti',
    category: 'quality',
    priority: 116,
    q: "Wordt de juistheid van de vertaling gegarandeerd?",
    a: "Uw vertalingen worden opgesteld door gespecialiseerde vertalers en gaan door een kwaliteitscontrole, en wij besteden de nodige zorg aan de juistheid. Desondanks kunnen de officiële acceptatievereisten voor een document verschillen afhankelijk van de instantie die het opvraagt.",
    keywords: ["garantie juistheid", "kwaliteitsgarantie", "waarborg"],
  },
  {
    id: 'makine-cevirisi-kullaniliyor',
    category: 'quality',
    priority: 117,
    q: "Gebruiken jullie volledig geautomatiseerde/machinevertaling?",
    a: "Nee. Vertalingen worden van begin tot eind gemaakt door professionele menselijke vertalers; wij bieden geen geautomatiseerde machinevertaling aan. Alleen CAT-tools worden gebruikt ter ondersteuning van de consistentie. Beëdigde vertalingen bevatten de stempel en handtekening van de vertaler en een verklaring van getrouwheid aan het origineel.",
    keywords: ["machinevertaling", "geautomatiseerde vertaling", "ai-vertaling", "verklaring van getrouwheid"],
  },

  // ——— PRIVACY EN BEVEILIGING ———
  {
    id: 'dosyalari-kimler-gorur',
    category: 'privacy',
    priority: 118,
    q: "Wie kan geüploade bestanden inzien en worden ze met derden gedeeld?",
    a: "Alleen de vertaler en het betrokken team dat aan uw bestelling werkt, hebben toegang tot uw bestanden. Behalve waar de dienst dat vereist, worden uw documenten nooit met derden gedeeld en niet voor marketing gebruikt.",
    keywords: ["wie kan zien", "toegang", "derden", "delen"],
  },
  {
    id: 'nda-imzalanabilir',
    category: 'privacy',
    priority: 119,
    q: "Kan er een geheimhoudingsovereenkomst (NDA) worden getekend?",
    a: "Ja. Vooral bij zakelijke projecten kan op verzoek een geheimhoudingsovereenkomst (NDA) worden opgesteld. Ook onze vertalers zijn gebonden aan geheimhoudingsverplichtingen.",
    keywords: ["nda", "geheimhoudingsovereenkomst", "vertrouwelijkheidsovereenkomst"],
  },
  {
    id: 'kvkk-uyumlu',
    category: 'privacy',
    priority: 120,
    q: "Werken jullie in overeenstemming met de KVKK en hoe worden persoonsgegevens beschermd?",
    a: "Ja. Uw persoonsgegevens worden verwerkt via KVKK-conforme processen (KVKK is de Turkse wet op de gegevensbescherming); ze worden alleen gebruikt voor zover de dienst dat vereist en veilig bewaard. Wij zetten ons in om uw gegevens met passende beveiligingsmaatregelen te beschermen.",
    keywords: ["kvkk", "persoonsgegevens", "gegevensbescherming", "kvkk-conform"],
  },
  {
    id: 'sifreli-aktarim',
    category: 'privacy',
    priority: 121,
    q: "Worden bestanden versleuteld overgedragen?",
    a: "Ja. Uw bestanden worden via een versleutelde verbinding overgedragen en in een beveiligde omgeving verwerkt. Ons doel is uw gegevens met passende beveiligingsmaatregelen te beschermen.",
    keywords: ["versleuteld", "veilige overdracht", "versleuteling"],
  },
  {
    id: 'odeme-bilgileri-saklanir',
    category: 'privacy',
    priority: 122,
    q: "Worden betaal-/creditcardgegevens bewaard?",
    a: "Uw kaartgegevens worden niet door TercümExpert bewaard; betalingen worden verwerkt via een beveiligde betaalinfrastructuur.",
    keywords: ["betaalgegevens", "creditcardbeveiliging", "kaartopslag"],
  },
  {
    id: 'belgeler-ai-egitimi',
    category: 'privacy',
    priority: 123,
    q: "Worden mijn documenten gebruikt voor het trainen van modellen?",
    a: "Nee. Uw documenten worden alleen voor uw bestelling gebruikt; ze worden nooit gedeeld voor het trainen van modellen of met externe systemen. Uw vertaling wordt door menselijke vertalers op vertrouwelijke basis opgesteld.",
    keywords: ["modeltraining", "gegevensgebruik", "ai-training", "documentprivacy"],
  },
  {
    id: 'saglik-kimlik-guvenli',
    category: 'privacy',
    priority: 124,
    q: "Zijn gevoelige documenten zoals identiteitsbewijzen, paspoorten of medische dossiers veilig?",
    a: "Ja. Al uw bestanden, inclusief gevoelige documenten, worden vertrouwelijk, KVKK-conform en versleuteld verwerkt. De toegang is beperkt tot het team dat aan uw bestelling werkt; voor zeer vertrouwelijke documenten kunnen aanvullende maatregelen zoals een NDA en beperkte toegang worden toegepast.",
    keywords: ["beveiliging identiteitsbewijs", "paspoort", "medische gegevens", "gevoelig document"],
  },
  {
    id: 'hesap-silinince-belgeler',
    category: 'privacy',
    priority: 125,
    q: "Worden documenten verwijderd wanneer een account wordt verwijderd of op verzoek?",
    a: "Op uw verzoek worden uw documenten en persoonsgegevens verwijderd, behoudens eventuele wettelijke bewaarplichten. U kunt een verzoek tot verwijdering van uw account of gegevens sturen naar onze klantenservice.",
    keywords: ["account verwijderen", "gegevens verwijderen", "documenten verwijderen"],
  },

  // ——— ZAKELIJKE DIENSTEN ———
  {
    id: 'kurumsal-hesap-nasil',
    category: 'corporate',
    priority: 126,
    q: "Hoe open ik een zakelijk account en wat gebeurt er nadat ik een aanvraag heb ingediend?",
    a: "Vul gewoon het aanvraagformulier op onze pagina Zakelijk in; ons team neemt doorgaans binnen 1 werkdag contact met u op, beoordeelt uw behoeften en stelt voorwaarden op maat op.",
    keywords: ["zakelijk account", "bedrijfsaccount", "zakelijke aanvraag", "na aanvraag"],
  },
  {
    id: 'sirket-adina-siparis',
    category: 'corporate',
    priority: 127,
    q: "Kan ik een bestelling namens een bedrijf plaatsen?",
    a: "Ja. U kunt een bestelling plaatsen met uw bedrijfsgegevens en profiteren van zakelijke facturering en, waar nodig, betaaltermijnopties.",
    keywords: ["namens bedrijf", "zakelijke bestelling", "bestelling bedrijf"],
  },
  {
    id: 'ozel-hesap-yoneticisi',
    category: 'corporate',
    priority: 128,
    q: "Krijgen zakelijke klanten een vaste accountmanager toegewezen?",
    a: "Zakelijke klanten kunnen een vaste accountmanager toegewezen krijgen die hun processen opvolgt. Zo kunt u uw aanvragen vanuit één aanspreekpunt beheren en ontvangt u ondersteuning met voorrang.",
    keywords: ["accountmanager", "vaste manager", "zakelijke ondersteuning", "ondersteuning met voorrang"],
  },
  {
    id: 'toplu-fatura',
    category: 'corporate',
    priority: 129,
    q: "Kan ik maandelijkse verzamelfacturen en betaaltermijnen krijgen?",
    a: "Ja. Zakelijke klanten kunnen maandelijkse verzamelfacturen en betaaltermijnen tot 15–30 dagen krijgen. De details worden binnen de afspraak vastgelegd.",
    keywords: ["verzamelfactuur", "maandfactuur", "betaaltermijn", "zakelijke betaling"],
  },
  {
    id: 'terminoloji-bankasi',
    category: 'corporate',
    priority: 130,
    q: "Kan er een bedrijfsspecifieke terminologiebank worden aangelegd?",
    a: "Ja. Voor zakelijke projecten wordt een terminologiebank en stijlgids specifiek voor uw merk aangelegd, zodat uw merkstijl en consistentie in alle vertalingen behouden blijven.",
    keywords: ["terminologiebank", "stijlgids", "zakelijke terminologie"],
  },
  {
    id: 'sabit-tercuman',
    category: 'corporate',
    priority: 131,
    q: "Kunnen wij bij terugkerende projecten met dezelfde vertalers werken?",
    a: "Ja. Voor terugkerende zakelijke projecten kan een vaste pool van vertalers/een vast team worden ingericht om continuïteit en consistentie te waarborgen.",
    keywords: ["vaste vertaler", "hetzelfde team", "zakelijk team"],
  },
  {
    id: 'kurumsal-raporlama',
    category: 'corporate',
    priority: 132,
    q: "Kan ik rapportages over bestellingen en uitgaven krijgen?",
    a: "Zakelijke klanten kunnen rapportages over hun bestellingen en uitgaven krijgen, zo nodig uitgesplitst per afdeling. Voor zakelijke samenwerkingen kunnen ook serviceniveau- (SLA) en geheimhoudingsovereenkomsten (NDA) worden opgesteld.",
    keywords: ["rapportage", "uitgavenrapport", "bestelrapport", "sla"],
  },
  {
    id: 'kucuk-isletme',
    category: 'corporate',
    priority: 133,
    q: "Kunnen kleine ondernemingen zakelijke diensten gebruiken en is er een minimumvolume vereist?",
    a: "Ja. Er geldt geen minimumomvang of minimumvolume om gebruik te maken van onze zakelijke diensten; ook kleine ondernemingen kunnen profiteren van voordelen zoals betaaltermijnen, terminologiebeheer en ondersteuning met voorrang.",
    keywords: ["kleine onderneming", "mkb", "minimumvolume", "volume vereist"],
  },
  {
    id: 'uluslararasi-sirket',
    category: 'corporate',
    priority: 134,
    q: "Bedienen jullie internationale bedrijven en meertalige projecten?",
    a: "Ja. Projecten die meerdere landen en talen omvatten, kunnen centraal worden gecoördineerd en uitgevoerd, met over de hele linie consistente terminologie. Voor zakelijke projecten kunnen ook beëdigde vertalingen en, waar nodig, notariële bekrachtiging worden geregeld.",
    keywords: ["internationaal bedrijf", "meertalig project", "zakelijk notaris apostille"],
  },

  // ——— TECHNISCHE ONDERSTEUNING ———
  {
    id: 'nasil-uye-olunur',
    category: 'support',
    priority: 135,
    q: "Hoe meld ik me aan op de site?",
    a: "Om u aan te melden, voert u uw voornaam, achternaam en e-mailadres in en bevestigt u de verificatiecode die naar uw e-mail wordt gestuurd. U kunt zich ook snel aanmelden met uw Apple- of Google-account.",
    keywords: ["aanmelden", "registreren", "account aanmaken"],
  },
  {
    id: 'giris-sifre-sorunu',
    category: 'support',
    priority: 136,
    q: "Wat moet ik doen als ik niet kan inloggen of mijn wachtwoord ben vergeten?",
    a: "Controleer eerst uw e-mailadres en wachtwoord; bent u uw wachtwoord vergeten, gebruik dan de link 'Wachtwoord vergeten' op het inlogscherm om herstelinstructies naar uw e-mail te sturen. Blijft het probleem bestaan, controleer dan uw spammap of neem contact op met onze klantenservice.",
    keywords: ["kan niet inloggen", "wachtwoord herstellen", "wachtwoord vergeten", "inloggen", "aanmelden"],
  },
  {
    id: 'dogrulama-epostasi-gelmezse',
    category: 'support',
    priority: 137,
    q: "Wat moet ik doen als de verificatiemail niet aankomt?",
    a: "Wacht een paar minuten, controleer uw spam-/ongewenste-mailmap en verstuur de code opnieuw. Zorg dat u uw e-mailadres correct heeft ingevoerd; blijft het probleem bestaan, neem dan contact op met onze klantenservice.",
    keywords: ["verificatiemail", "code niet ontvangen", "e-mail komt niet aan", "verificatiecode"],
  },
  {
    id: 'dosya-yuklenmiyor',
    category: 'support',
    priority: 138,
    q: "Wat moet ik doen als een bestand niet wil uploaden of ik een foutmelding voor een niet-ondersteund bestand krijg?",
    a: "Controleer de bestandsgrootte (tot 100 MB) en het formaat en vernieuw de pagina en uw browser. Wordt het formaat niet ondersteund, zet het bestand dan om naar een formaat als PDF of DOCX, of plak de tekst in het tabblad 'Tekst invoeren'. Blijft het probleem bestaan, neem dan contact op met onze klantenservice.",
    keywords: ["bestand uploadt niet", "uploadfout", "niet-ondersteund bestand", "formaatfout"],
  },
  {
    id: 'kelime-sayisi-yanlis',
    category: 'support',
    priority: 139,
    q: "Wat moet ik doen als het aantal woorden niet lijkt te kloppen?",
    a: "Automatisch tellen kan afwijken, vooral bij gescande of beelddocumenten. Voor een juist resultaat kunt u de tekst delen via 'Tekst invoeren' of een notitie aan uw bestelling toevoegen; het definitieve aantal wordt door ons team bevestigd en de prijs wordt daarop afgestemd.",
    keywords: ["verkeerd aantal woorden", "telfout", "onjuist aantal woorden"],
  },
  {
    id: 'odeme-basarisiz',
    category: 'support',
    priority: 140,
    q: "Wat moet ik doen als een betaling mislukt of ik twee keer word afgeschreven?",
    a: "Controleer uw kaartgegevens en limiet en probeer het opnieuw; u kunt ook een andere methode gebruiken (kaart/bankoverschrijving). Is het bedrag afgeschreven maar geen bestelling aangemaakt, of is er een dubbele afschrijving, neem dan met uw betaalbewijs contact op met onze klantenservice; het te veel betaalde bedrag wordt terugbetaald.",
    keywords: ["betaling mislukt", "betaalfout", "twee keer afgeschreven", "dubbele afschrijving"],
  },
  {
    id: 'teslim-dosyasi-inmiyor',
    category: 'support',
    priority: 141,
    q: "Wat moet ik doen als het geleverde bestand niet wil downloaden?",
    a: "Vernieuw de link en uw browser; is de downloadlink verlopen, dan kunt u bij onze klantenservice een nieuwe link aanvragen.",
    keywords: ["bestand downloadt niet", "downloadprobleem", "kan levering niet downloaden", "link verlopen"],
  },
  {
    id: 'mobil-tarayici-destegi',
    category: 'support',
    priority: 142,
    q: "Kan ik de site op een mobiel apparaat gebruiken en welke browsers worden ondersteund?",
    a: "De site is geschikt voor mobiel; u kunt documenten uploaden en bestellingen plaatsen vanaf een iPhone, Android-telefoon of tablet. Met actuele versies van Chrome, Safari, Edge en Firefox gebruikt u de site probleemloos.",
    keywords: ["mobiel", "telefoon", "iphone android", "tablet", "browser", "chrome safari"],
  },
  {
    id: 'ai-asistan-ne-yapar',
    category: 'support',
    priority: 143,
    q: "Wat kan de AI-chatassistent doen?",
    a: "De chatassistent geeft direct hulp bij vragen over het proces, de soorten diensten en algemene onderwerpen, en wijst u de juiste stappen zoals het opvragen van een offerte. De assistent kan geen definitieve of bindende beslissingen nemen over officiële acceptatievereisten of wettelijke vereisten (zoals notariële bekrachtiging of apostille); daarvoor moet u de betreffende instantie raadplegen.",
    keywords: ["chatassistent", "chatbot", "ai-assistent", "chatbot prijs"],
  },
  {
    id: 'insana-baglanma',
    category: 'support',
    priority: 144,
    q: "Hoe bereik ik een menselijke klantenservicemedewerker?",
    a: "U kunt dit aanvragen via de chatassistent of onze menselijke klantenservice rechtstreeks bereiken via WhatsApp en e-mail. Verzoeken worden tijdens kantooruren beantwoord. Technische problemen met een schermafbeelding doorsturen versnelt de oplossing.",
    keywords: ["mens bereiken", "klantenservicemedewerker", "live hulp", "schermafbeelding"],
  },
  {
    id: 'hesap-bilgileri-guncelleme',
    category: 'support',
    priority: 145,
    q: "Hoe werk ik mijn account- en factuurgegevens bij en hoe verwijder ik mijn account?",
    a: "Heeft u een account, dan kunt u uw telefoonnummer, e-mailadres en factuurgegevens bijwerken in uw accountinstellingen, en u kunt daar of via onze klantenservice ook verzoeken om verwijdering van uw account. Op uw verzoek worden uw gegevens verwijderd, behoudens eventuele wettelijke verplichtingen.",
    keywords: ["gegevens bijwerken", "factuurgegevens", "accountinstellingen", "account verwijderen"],
  },
  {
    id: 'bildirim-tercihleri',
    category: 'support',
    priority: 146,
    q: "Hoe werken bestelmeldingen en kan ik meldingen via WhatsApp krijgen?",
    a: "Voor de status van uw bestelling worden e-mailmeldingen verstuurd; op basis van uw voorkeuren kunnen updates ook via WhatsApp worden gegeven. U kunt uw meldingsvoorkeuren aanpassen in uw accountinstellingen of via onze klantenservice.",
    keywords: ["meldingen", "sms", "whatsapp-melding", "e-mailmelding", "bestelmelding"],
  },
]
