/**
 * Źródło danych FAQ (polski). Logika cen/płatności może się później zmienić (§13).
 * Zasady rzetelności: BRAK niezweryfikowanych deklaracji ISO/certyfikatów; nie
 * sugerujemy istnienia biura stacjonarnego; nie obiecujemy wsparcia ludzkiego 24/7;
 * zachowane rozróżnienia tłumaczenie przysięgłe / poświadczenie notarialne /
 * apostille; brak gwarancji przyjęcia dokumentu przez instytucję.
 * `priority` = globalna kolejność ważności (mniejsza = wyżej). Widok kategorii
 * używa tej samej kolejności, więc porządek wewnątrz kategorii wynika z tej wartości.
 */
import type { FaqCategory, FaqItem } from './faq-data'

export const FAQ_CATEGORIES_PL: FaqCategory[] = [
  { key: "general", label: "Informacje ogólne" },
  { key: "order", label: "Proces zamówienia" },
  { key: "pricing", label: "Cennik i płatności" },
  { key: "upload", label: "Przesyłanie plików" },
  { key: "languages", label: "Języki i pary językowe" },
  { key: "services", label: "Rodzaje usług" },
  { key: "delivery", label: "Dostawa i czas realizacji" },
  { key: "sworn", label: "Tłumaczenie przysięgłe" },
  { key: "notary", label: "Poświadczenie notarialne i apostille" },
  { key: "quality", label: "Jakość i korekty" },
  { key: "privacy", label: "Prywatność i bezpieczeństwo" },
  { key: "corporate", label: "Usługi dla firm" },
  { key: "support", label: "Pomoc techniczna" },
]

export const FAQ_ITEMS_PL: FaqItem[] = [
  // ——— WSZYSTKIE: najważniejsze pytania wzdłuż ścieżki klienta ———
  {
    id: "nasil-fiyat-alirim",
    category: "pricing",
    priority: 1,
    q: "Jak otrzymam wycenę?",
    a: "Na stronie Oblicz cenę proszę przesłać dokument lub wkleić tekst; po wybraniu pary językowej i rodzaju usługi wstępna wycena pojawi się natychmiast. Cena zależy od pary językowej, rodzaju usługi, liczby słów oraz wybranych usług dodatkowych.",
    keywords: ["wycena", "cena tłumaczenia", "koszt", "wstępna wycena", "jak wycenić", "ile kosztuje"],
  },
  {
    id: "dosya-nasil-yuklenir",
    category: "upload",
    priority: 2,
    q: "Jak przesłać plik?",
    a: "Na stronie Oblicz cenę proszę otworzyć zakładkę „Prześlij plik” i przeciągnąć dokument lub wskazać go ręcznie. Jeśli nie mają Państwo pliku, wystarczy wkleić tekst w zakładce „Wprowadź tekst”. W przypadku plików tekstowych system automatycznie zliczy liczbę słów.",
    keywords: ["przesyłanie pliku", "prześlij dokument", "dodaj plik", "nie mogę przesłać", "jak przesłać"],
  },
  {
    id: "fiyatlandirma-neye-gore",
    category: "pricing",
    priority: 3,
    q: "Na jakiej podstawie ustalana jest cena?",
    a: "Cena zależy od pary językowej, rodzaju usługi, treści dokumentu, liczby słów, dziedziny specjalistycznej oraz wybranych usług dodatkowych. Kwota widoczna na ekranie to wstępna wycena; ostateczna cena zostaje potwierdzona po sprawdzeniu dokumentu.",
    keywords: ["cennik", "jak ustalana cena", "czynniki ceny", "za słowo", "stawki"],
  },
  {
    id: "teslim-suresi-ne-kadar",
    category: "delivery",
    priority: 4,
    q: "Jaki jest czas realizacji?",
    a: "Czas realizacji zależy od długości dokumentu, pary językowej, rodzaju usługi oraz wybranych usług dodatkowych. Na ekranie wyceny wyświetla się szacowany czas realizacji przypisany do Państwa zamówienia. Można go skrócić, wybierając opcję realizacji ekspresowej.",
    keywords: ["czas realizacji", "termin", "ile dni", "kiedy gotowe", "jak długo"],
  },
  {
    id: "yeminli-tercume-nedir",
    category: "sworn",
    priority: 5,
    q: "Czym jest tłumaczenie przysięgłe?",
    a: "Tłumaczenie przysięgłe to tłumaczenie poświadczone przez tłumacza przysięgłego jego podpisem i pieczęcią, w którym stwierdza się zgodność z oryginałem. Jest często wymagane przy oficjalnych postępowaniach. To, czy jest ono konieczne, zależy od instytucji żądającej dokumentu.",
    keywords: ["tłumaczenie przysięgłe", "tłumaczenie poświadczone", "tłumaczenie z pieczęcią", "tłumaczenie urzędowe", "co to przysięgłe"],
  },
  {
    id: "hangi-dillerde-hizmet",
    category: "languages",
    priority: 6,
    q: "W jakich językach świadczą Państwo usługi?",
    a: "Pracujemy z językiem tureckim, a także angielskim, niemieckim, francuskim, hiszpańskim, włoskim, arabskim i rosyjskim oraz w ponad 50 językach łącznie. W przypadku języków rzadkich dostępność tłumacza i czas realizacji potwierdzamy osobno dla każdego zamówienia.",
    keywords: ["języki", "jakie języki", "dostępne języki", "pary językowe", "ile języków"],
  },
  {
    id: "noter-onayi-gerekir-mi",
    category: "notary",
    priority: 7,
    q: "Czy potrzebne jest poświadczenie notarialne?",
    a: "Poświadczenie notarialne nie jest wymagane dla każdego dokumentu; to, czy jest potrzebne, zależy od instytucji żądającej dokumentu oraz celu jego wykorzystania. W niektórych procedurach wystarczy tłumaczenie przysięgłe, w innych wymagane jest dodatkowo poświadczenie notarialne. Jeśli nie mają Państwo pewności, które poświadczenie jest potrzebne, chętnie doradzimy.",
    keywords: ["poświadczenie notarialne", "notariusz", "notarialnie", "czy potrzebny notariusz"],
  },
  {
    id: "siparis-nasil-ilerler",
    category: "order",
    priority: 8,
    q: "Jak przebiega proces zamówienia?",
    a: "Po przesłaniu dokumentu i zatwierdzeniu wstępnej wyceny tworzone jest Państwa zamówienie i przydzielane tłumaczowi specjalizującemu się w danej dziedzinie. Tłumaczenie przechodzi kontrolę jakości; w razie potrzeby realizowany jest proces poświadczenia notarialnego, a dokument dostarczamy cyfrowo oraz, gdy jest to konieczne, kurierem.",
    keywords: ["proces zamówienia", "jak przebiega", "etapy", "przebieg"],
  },
  {
    id: "belgelerim-guvende-mi",
    category: "privacy",
    priority: 9,
    q: "Czy moje dokumenty są bezpieczne?",
    a: "Tak. Państwa pliki widzi wyłącznie zespół realizujący zamówienie, a ich przetwarzanie odbywa się z użyciem szyfrowanej transmisji i procesów zgodnych z KVKK (tureckie prawo o ochronie danych osobowych). Państwa dokumenty nie są udostępniane osobom trzecim, a poufność jest dla nas priorytetem.",
    keywords: ["bezpieczeństwo", "poufność", "bezpieczeństwo dokumentów", "ochrona danych", "kvkk"],
  },
  {
    id: "cevirimi-kim-yapar",
    category: "quality",
    priority: 10,
    q: "Kto wykonuje moje tłumaczenie?",
    a: "Państwa tłumaczenia wykonują profesjonalni tłumacze — ludzie — doświadczeni w danej dziedzinie. Do rodzaju dokumentu przydzielany jest tłumacz specjalista, a każde tłumaczenie przed dostarczeniem przechodzi kontrolę jakości.",
    keywords: ["kto tłumaczy", "tłumacz", "tłumacz człowiek", "specjalista", "kto wykonuje"],
  },
  {
    id: "revize-hakki-var-mi",
    category: "quality",
    priority: 11,
    q: "Czy przysługuje korekta?",
    a: "Tak. Po dostarczeniu tłumaczenia mają Państwo prawo zgłosić poprawki mieszczące się w pierwotnym zakresie. Poprawki dotyczące pisowni, nazwisk, dat czy spójności są objęte tym zakresem. Późniejsza zmiana tekstu źródłowego lub dodanie nowej treści może zostać uznane za nowe zlecenie.",
    keywords: ["korekta", "poprawki", "rewizja", "ponowne tłumaczenie", "zasady korekty"],
  },
  {
    id: "fiziksel-teslimat-yapiliyor-mu",
    category: "delivery",
    priority: 12,
    q: "Czy oferują Państwo dostawę fizyczną?",
    a: "Tak. Choć standardem jest dostawa cyfrowa, dokumenty z własnoręcznym oryginalnym podpisem i pieczęcią możemy wysłać na Państwa adres kurierem. Wysyłamy na terenie całej Turcji, a na życzenie także za granicę. Przy wyborze przesyłki czas wysyłki dolicza się do czasu realizacji.",
    keywords: ["dostawa fizyczna", "kurier", "przesyłka pocztowa", "dostawa na adres"],
  },
  {
    id: "kurumsal-ozel-sartlar",
    category: "corporate",
    priority: 13,
    q: "Czy dla klientów biznesowych obowiązują specjalne warunki?",
    a: "Tak. Klientom biznesowym oferujemy korzyści przy zamówieniach zbiorczych, opcje terminów płatności, zarządzanie terminologią oraz dedykowanego opiekuna klienta. Szczegóły znajdą Państwo, wypełniając formularz zgłoszeniowy na stronie dla firm.",
    keywords: ["firmy", "biznes", "warunki dla firm", "zamówienie zbiorcze", "warunki firmowe"],
  },
  {
    id: "apostil-nasil-yurutulur",
    category: "notary",
    priority: 14,
    q: "Jak przebiega proces apostille?",
    a: "Apostille to poświadczenie wydawane przez właściwy organ, dzięki któremu dokument jest uznawany za ważny za granicą. Nie przeprowadzamy procesu apostille; apostille należy uzyskać samodzielnie we właściwym organie w kraju, w którym dokument został wystawiony. Zapewniamy wyłącznie tłumaczenie przysięgłe Państwa dokumentów opatrzonych apostille. W krajach, które nie są stroną konwencji haskiej, zamiast apostille może być wymagane poświadczenie konsularne.",
    keywords: ["apostille", "proces apostille", "poświadczenie apostille", "ważny za granicą"],
  },
  {
    id: "acil-teslimat-mumkun-mu",
    category: "delivery",
    priority: 15,
    q: "Czy możliwa jest realizacja ekspresowa?",
    a: "Tak, dla wielu dokumentów dostępna jest realizacja ekspresowa, która skraca czas wykonania. Realizacja ekspresowa wiąże się z dodatkową opłatą, a jej dostępność może zależeć od długości i języka dokumentu. Etapy kontroli jakości są zachowane również przy zamówieniach ekspresowych.",
    keywords: ["realizacja ekspresowa", "szybka realizacja", "ten sam dzień", "ekspres", "pilne"],
  },
  {
    id: "odeme-nasil-yapilir",
    category: "pricing",
    priority: 16,
    q: "Jak dokonać płatności?",
    a: "Płatności można dokonać kartą kredytową/debetową lub przelewem bankowym; w przypadku kart kredytowych może być dostępna płatność ratalna. Klientom biznesowym oferujemy również fakturowanie z odroczonym terminem płatności (15–30 dni). Płatność pobierana jest po zatwierdzeniu wstępnej wyceny.",
    keywords: ["płatność", "metoda płatności", "karta kredytowa", "przelew", "jak zapłacić"],
  },
  {
    id: "dosya-yuklemeden-fiyat",
    category: "upload",
    priority: 17,
    q: "Czy mogę otrzymać wycenę bez przesyłania pliku?",
    a: "Tak. Jeśli nie mają Państwo pliku, proszę wkleić tekst w zakładce „Wprowadź tekst”, aby otrzymać wstępną wycenę na podstawie liczby słów.",
    keywords: ["wycena bez pliku", "wycena z tekstu", "bez przesyłania", "wycena tekstu"],
  },
  {
    id: "belgenin-formati-korunur-mu",
    category: "delivery",
    priority: 18,
    q: "Czy formatowanie dokumentu zostaje zachowane?",
    a: "W miarę możliwości zachowujemy w tłumaczeniu oryginalny układ strony, tabele i formatowanie. W zależności od potrzeb tłumaczenie możemy dostarczyć w formacie PDF lub edytowalnym Word (DOCX). W przypadku dokumentów zeskanowanych lub obrazowych zapewniamy uporządkowany układ zamiast wiernej kopii.",
    keywords: ["formatowanie", "układ", "układ strony", "word", "pdf", "zachowanie formatu"],
  },
  {
    id: "teslim-sonrasi-destek",
    category: "quality",
    priority: 19,
    q: "Czy mogę uzyskać wsparcie po dostarczeniu tłumaczenia?",
    a: "Tak. Po dostarczeniu oferujemy wsparcie w zakresie korekt mieszczących się w pierwotnym zakresie, a z pytaniami mogą się Państwo zwrócić do naszej linii wsparcia klienta. Dodatkowe prośby dotyczące dokumentu można przesłać e-mailem lub przez WhatsApp.",
    keywords: ["wsparcie po dostawie", "po dostarczeniu", "pomoc", "wsparcie"],
  },
  {
    id: "cok-sayfali-yuksek-hacim",
    category: "order",
    priority: 20,
    q: "Jak realizowane są projekty wielostronicowe lub o dużej objętości?",
    a: "Projekty o dużej objętości są starannie planowane; w razie potrzeby zaangażowanych jest kilku tłumaczy i redaktorów, a dla zachowania spójności terminologii stosujemy wspólny glosariusz. Długie projekty mogą być dostarczane w częściach (dostawa częściowa), jeśli sobie Państwo tego życzą. W projektach firmowych proces koordynuje Państwa opiekun klienta.",
    keywords: ["wiele stron", "duża objętość", "praca zbiorcza", "duży projekt", "wiele dokumentów"],
  },

  // ——— INFORMACJE OGÓLNE ———
  {
    id: "tercumexpert-nedir",
    category: "general",
    priority: 21,
    q: "Czym jest TercümExpert?",
    a: "TercümExpert to internetowy dostawca usług tłumaczeniowych oferujący tłumaczenie przysięgłe, tłumaczenie z poświadczeniem notarialnym, tłumaczenia prawnicze, techniczne, medyczne i akademickie oraz lokalizację stron internetowych i aplikacji mobilnych. Mogą Państwo przesłać dokument, otrzymać wstępną wycenę i złożyć zamówienie w całości online.",
    keywords: ["tercumexpert", "co to jest", "o nas", "usługa tłumaczeniowa", "czym się zajmujecie"],
  },
  {
    id: "hangi-hizmetler",
    category: "general",
    priority: 22,
    q: "Jakie usługi oferuje TercümExpert?",
    a: "Oferujemy tłumaczenia przysięgłe i z poświadczeniem notarialnym, tłumaczenie dokumentów opatrzonych apostille, tłumaczenia prawnicze, techniczne, medyczne i akademickie oraz lokalizację stron internetowych i aplikacji mobilnych. Usługę odpowiadającą Państwa potrzebom można wybrać na ekranie Oblicz cenę.",
    keywords: ["usługi", "co oferujecie", "rodzaje usług", "jakie usługi"],
  },
  {
    id: "kimler-hizmet-alabilir",
    category: "general",
    priority: 23,
    q: "Kto może skorzystać z usług?",
    a: "Z naszych usług mogą korzystać zarówno klienci indywidualni, jak i firmy oraz instytucje. Od studentów po freelancerów i od małych firm po duże przedsiębiorstwa — oferujemy rozwiązania dopasowane do różnych potrzeb.",
    keywords: ["kto może", "klienci indywidualni", "firmy", "przedsiębiorstwa", "klienci"],
  },
  {
    id: "ofise-gelmek-gerekir-mi",
    category: "general",
    priority: 24,
    q: "Czy trzeba osobiście odwiedzić biuro?",
    a: "Nie. Nie mamy fizycznego biura; nasze usługi świadczone są w pełni online. Wystarczy przesłać dokumenty za pomocą bezpiecznego przesyłania, a dostawa realizowana jest cyfrowo oraz, w razie potrzeby, kurierem. W razie pytań mogą Państwo skontaktować się z nami przez WhatsApp lub pod adresem info@tercumexpert.com.",
    keywords: ["biuro", "osobiście", "oddział", "adres", "wizyta wymagana"],
  },
  {
    id: "surec-cevrimici-mi",
    category: "general",
    priority: 25,
    q: "Czy cały proces można przeprowadzić online?",
    a: "Tak. Przesyłanie dokumentów, zatwierdzenie wyceny, płatność i dostawa cyfrowa odbywają się w całości online. Kurier jest angażowany wyłącznie wtedy, gdy potrzebny jest fizyczny dokument z własnoręcznym oryginalnym podpisem.",
    keywords: ["online", "całkowicie online", "zdalnie", "internet", "wszystko online"],
  },
  {
    id: "yurt-disindan-hizmet",
    category: "general",
    priority: 26,
    q: "Czy klienci z zagranicy mogą skorzystać z usług?",
    a: "Tak. Ponieważ proces odbywa się online, mogą Państwo przesyłać dokumenty i składać zamówienia z zagranicy. Dostawa cyfrowa jest dostępna wszędzie, a dokumenty z własnoręcznym oryginalnym podpisem możemy wysłać kurierem również za granicę.",
    keywords: ["zagranica", "klienci zagraniczni", "z zagranicy", "poza turcją"],
  },
  {
    id: "uyelik-zorunlu-mu",
    category: "general",
    priority: 27,
    q: "Czy do skorzystania z usług wymagane jest konto?",
    a: "Konto nie jest wymagane. Aby jednak zobaczyć cenę i złożyć zamówienie, należy podać imię, nazwisko i adres e-mail, a następnie potwierdzić kod weryfikacyjny wysłany na e-mail. Jeśli sobie Państwo życzą, mogą Państwo założyć konto, aby śledzić historię zamówień.",
    keywords: ["konto", "rejestracja", "założenie konta", "czy wymagane", "bez konta"],
  },
  {
    id: "uye-olmadan-fiyat",
    category: "general",
    priority: 28,
    q: "Czy mogę otrzymać wycenę bez rejestracji?",
    a: "Tak, wycenę można otrzymać bez zakładania pełnego konta; wystarczy zweryfikować imię, nazwisko i adres e-mail. Użytkownicy, którzy nie ukończą weryfikacji, nie zobaczą ceny ani nie złożą zamówienia.",
    keywords: ["wycena bez konta", "bez rejestracji", "kod weryfikacyjny", "weryfikacja e-mail"],
  },
  {
    id: "siparis-oncesi-danismanlik",
    category: "general",
    priority: 29,
    q: "Czy mogę uzyskać poradę przed złożeniem zamówienia?",
    a: "Tak. Jeśli nie mają Państwo pewności, jakiej usługi potrzebują, mogą Państwo uzyskać informacje przez WhatsApp, e-mail lub naszego asystenta czatu opartego na sztucznej inteligencji. Wspólnie ustalimy odpowiednią usługę i przebieg procesu w zależności od rodzaju dokumentu.",
    keywords: ["porada", "konsultacja", "zadaj pytanie", "pomoc przed zamówieniem"],
  },
  {
    id: "musteri-temsilcisi",
    category: "general",
    priority: 30,
    q: "Jak skontaktować się z przedstawicielem obsługi klienta?",
    a: "Z naszą linią wsparcia klienta można skontaktować się przez WhatsApp lub e-mail. Państwa pytania są rozpatrywane przez przedstawiciela w godzinach pracy; nasz asystent czatu oparty na sztucznej inteligencji może również w każdej chwili udzielić wstępnych wskazówek.",
    keywords: ["przedstawiciel obsługi", "wsparcie", "kontakt", "połączenie", "obsługa na żywo"],
  },
  {
    id: "hangi-belgeler-cevrilebilir",
    category: "general",
    priority: 31,
    q: "Jakie rodzaje dokumentów można tłumaczyć?",
    a: "Tłumaczymy szeroki zakres tekstów — od dokumentów urzędowych i osobistych po teksty handlowe, prawnicze, techniczne, medyczne i akademickie. Obsługujemy wiele rodzajów dokumentów, w tym dyplomy, umowy, raporty, instrukcje i treści stron internetowych.",
    keywords: ["rodzaje dokumentów", "jakie dokumenty", "dokumentacja", "co można tłumaczyć"],
  },
  {
    id: "yapay-zeka-mi-insan-mi",
    category: "general",
    priority: 32,
    q: "Czy tłumaczenia wykonują tłumacze będący ludźmi?",
    a: "Tak. Państwa tłumaczenia od początku do końca wykonują profesjonalni tłumacze — ludzie. Do wsparcia spójności i terminologii wykorzystujemy narzędzia CAT, jednak całość tłumaczenia jest dziełem tłumaczy specjalistów i przechodzi kontrolę jakości.",
    keywords: ["tłumacz człowiek", "narzędzie cat", "narzędzia tłumaczeniowe", "tłumaczenie maszynowe", "kto tłumaczy"],
  },
  {
    id: "el-yazili-belgeler",
    category: "general",
    priority: 33,
    q: "Czy można tłumaczyć dokumenty pisane ręcznie lub trudne do odczytania?",
    a: "Dokumenty pisane ręcznie i trudne do odczytania można tłumaczyć, o ile są czytelne. Nieczytelne fragmenty są wyraźnie zaznaczane w tłumaczeniu, a w razie potrzeby możemy poprosić o wyraźniejszą kopię. W przypadku takich dokumentów cena zostaje potwierdzona po weryfikacji.",
    keywords: ["pismo ręczne", "pisane ręcznie", "nieczytelne", "niewyraźne", "trudne do odczytania"],
  },
  {
    id: "farkiniz-nedir",
    category: "general",
    priority: 34,
    q: "Czym TercümExpert wyróżnia się na tle innych usług tłumaczeniowych?",
    a: "Wyróżniają nas w pełni internetowy proces od początku do końca, automatyczna wstępna wycena, tłumacze specjaliści będący ludźmi oraz kontrola jakości. Dostarczamy również dokumenty z własnoręcznym oryginalnym podpisem prosto pod Państwa drzwi kurierem.",
    keywords: ["różnica", "przewaga", "dlaczego tercumexpert", "co was wyróżnia"],
  },

  // ——— PROCES ZAMÓWIENIA ———
  {
    id: "siparis-nasil-verilir",
    category: "order",
    priority: 35,
    q: "Jak złożyć zamówienie?",
    a: "Na ekranie Oblicz cenę proszę przesłać dokument lub wprowadzić tekst, wybrać parę językową i rodzaj usługi oraz zatwierdzić wstępną wycenę. Po zatwierdzeniu tworzone jest Państwa zamówienie.",
    keywords: ["złożenie zamówienia", "jak zamówić", "utworzenie zamówienia", "zamów tłumaczenie"],
  },
  {
    id: "siparis-icin-gerekli-bilgiler",
    category: "order",
    priority: 36,
    q: "Jakie informacje są potrzebne do złożenia zamówienia?",
    a: "Potrzebny jest dokument lub tekst do przetłumaczenia, język źródłowy i docelowy, rodzaj usługi oraz imię, nazwisko i adres e-mail do kontaktu. Na podstawie tych danych mogą Państwo utworzyć zamówienie.",
    keywords: ["wymagane informacje", "co potrzebne", "dane zamówienia", "dane do zamówienia"],
  },
  {
    id: "dil-cifti-nasil-secilir",
    category: "order",
    priority: 37,
    q: "Jak wybrać parę językową i rodzaj usługi?",
    a: "Na ekranie Oblicz cenę wybierają Państwo z menu język źródłowy (język dokumentu), język docelowy (język tłumaczenia) oraz rodzaj usługi (przysięgłe, z poświadczeniem notarialnym, techniczne itp.). W razie wątpliwości nasza linia wsparcia lub asystent czatu pomoże dokonać właściwego wyboru.",
    keywords: ["wybór pary językowej", "język źródłowy", "język docelowy", "wybór usługi"],
  },
  {
    id: "bilgiler-degistirilebilir-mi",
    category: "order",
    priority: 38,
    q: "Czy po utworzeniu zamówienia można zmienić dane?",
    a: "Dane takie jak język, rodzaj usługi czy dokument można zaktualizować, zanim rozpocznie się tłumaczenie. Wystarczy jak najszybciej skontaktować się z naszą linią wsparcia; w miarę postępu prac zakres możliwych zmian może się ograniczać.",
    keywords: ["zmiana danych", "edycja zamówienia", "aktualizacja zamówienia", "błędny język", "błędny dokument"],
  },
  {
    id: "onaydan-once-iptal",
    category: "order",
    priority: 39,
    q: "Czy mogę anulować zamówienie przed jego zatwierdzeniem?",
    a: "Tak. Zamówienie można anulować, zanim płatność i zatwierdzenie zostaną ukończone; na tym etapie nie jest pobierana żadna opłata.",
    keywords: ["anulowanie", "anuluj zamówienie", "rezygnacja", "anulowanie przed zatwierdzeniem"],
  },
  {
    id: "odeme-sonrasi-iptal",
    category: "order",
    priority: 40,
    q: "Czy zamówienie można anulować po dokonaniu płatności?",
    a: "Jeśli tłumaczenie nie zostało jeszcze podjęte przez tłumacza, mogą Państwo anulować zamówienie na stronie zamówienia lub pod adresem info@tercumexpert.com, a płatność zostanie zwrócona w całości na pierwotną metodę płatności. Po podjęciu tłumaczenia przez tłumacza zwrot nie jest dokonywany ze względu na zindywidualizowany charakter świadczenia.",
    keywords: ["anulowanie po płatności", "zwrot", "zwrot pieniędzy", "rezygnacja z zamówienia"],
  },
  {
    id: "siparis-durumu-takip",
    category: "order",
    priority: 41,
    q: "Gdzie mogę śledzić status zamówienia?",
    a: "O statusie zamówienia informujemy Państwa e-mailem, a jeśli założyli Państwo konto, można go również śledzić w panelu. O aktualny status można też zapytać naszą linię wsparcia.",
    keywords: ["śledzenie zamówienia", "status", "śledzenie", "status zamówienia"],
  },
  {
    id: "birden-fazla-belge",
    category: "order",
    priority: 42,
    q: "Czy jedno zamówienie może obejmować wiele dokumentów lub języków docelowych?",
    a: "Tak, w jednym zamówieniu mogą Państwo przesłać wiele dokumentów i zlecić tłumaczenie tego samego dokumentu na kilka języków. Łączna liczba słów oraz każdy język docelowy są wyceniane jako oddzielne tłumaczenia, a proces koordynowany jest w ramach jednego zgłoszenia.",
    keywords: ["wiele dokumentów", "wiele plików", "wiele języków", "kilka języków"],
  },
  {
    id: "sonradan-dosya-eklenebilir",
    category: "order",
    priority: 43,
    q: "Czy mogę później dodać nowy plik do zamówienia?",
    a: "Nowy plik można dodać, zanim rozpocznie się tłumaczenie; w takim przypadku cena zostaje zaktualizowana o dodaną treść. Dokumenty dodane po rozpoczęciu prac mogą być traktowane jako nowa pozycja.",
    keywords: ["dodanie pliku", "dodaj później", "nowy plik", "dodanie dokumentu"],
  },
  {
    id: "eksik-belge-gonderilirse",
    category: "order",
    priority: 44,
    q: "Co się stanie, jeśli prześlę niekompletny dokument?",
    a: "Gdy zauważymy brakującą stronę lub dokument, poprosimy o jego uzupełnienie. Przesłanie wszystkich stron dokumentu jest istotne, aby tłumaczenie było kompletne i ważne.",
    keywords: ["niekompletny dokument", "brakująca strona", "brakujący dokument", "niepełny dokument"],
  },
  {
    id: "terminoloji-not-referans",
    category: "order",
    priority: 45,
    q: "Czy mogę dodać do zamówienia uwagi, terminologię lub pliki referencyjne?",
    a: "Tak. Podczas składania zamówienia mogą Państwo dodać specjalne instrukcje, preferowane terminy lub uwagi stylistyczne oraz przesłać pliki referencyjne, takie jak wcześniejsze tłumaczenia i glosariusze. Informacje te przekazujemy tłumaczowi i wykorzystujemy dla zachowania spójności.",
    keywords: ["dodanie uwagi", "specjalne instrukcje", "terminologia", "plik referencyjny", "glosariusz"],
  },
  {
    id: "eski-siparisler-goruntulenir",
    category: "order",
    priority: 46,
    q: "Czy mogę później uzyskać dostęp do wcześniejszych zamówień i plików?",
    a: "Jeśli założyli Państwo konto, mogą Państwo przeglądać w nim wcześniejsze zamówienia i dostarczone pliki. W przypadku zamówień składanych bez konta dostęp do zapisów uzyskają Państwo przez e-mail; jeśli link do pobrania wygasł, mogą Państwo poprosić o nowy naszą linię wsparcia.",
    keywords: ["wcześniejsze zamówienia", "historia zamówień", "poprzednie zamówienia", "dostęp do plików"],
  },

  // ——— CENNIK I PŁATNOŚCI ———
  {
    id: "kelime-mi-sayfa-mi",
    category: "pricing",
    priority: 47,
    q: "Czy naliczają Państwo opłatę za słowo, czy za stronę?",
    a: "Cena jest zwykle ustalana na podstawie liczby słów i wybranej usługi. W przypadku dokumentów tekstowych liczba słów jest zliczana automatycznie; w przypadku dokumentów zeskanowanych lub obrazowych liczba ta zostaje potwierdzona po weryfikacji.",
    keywords: ["za słowo", "za stronę", "podstawa wyceny", "jak naliczane"],
  },
  {
    id: "sabit-baslangic-ucreti",
    category: "pricing",
    priority: 48,
    q: "Czy obowiązuje stała opłata początkowa lub kwota minimalna?",
    a: "W niektórych usługach może obowiązywać minimalna opłata za usługę, która może dotyczyć krótkich dokumentów. Ostateczna cena zależy od treści dokumentu i wybranych usług, a wszystkie pozycje widoczne są na ekranie wstępnej wyceny.",
    keywords: ["opłata początkowa", "minimum", "opłata stała", "kwota minimalna"],
  },
  {
    id: "neler-fiyati-etkiler",
    category: "pricing",
    priority: 49,
    q: "Czy para językowa, rodzaj dokumentu i dziedzina wpływają na cenę?",
    a: "Tak. Para językowa (zwłaszcza języki rzadkie), rodzaj dokumentu oraz dziedzina (prawnicza, medyczna, techniczna itp.) mogą wpływać na intensywność terminologii, a tym samym na cenę. W przypadku popularnych języków cena jest bardziej przewidywalna.",
    keywords: ["cena pary językowej", "cena rodzaju dokumentu", "cena dziedziny", "dlaczego różne ceny"],
  },
  {
    id: "yeminli-daha-pahali-mi",
    category: "pricing",
    priority: 50,
    q: "Czy tłumaczenie przysięgłe jest droższe?",
    a: "Tłumaczenie przysięgłe może być wyceniane inaczej niż tłumaczenie standardowe ze względu na poświadczenie i odpowiedzialność tłumacza. Dokładna kwota wyświetla się na ekranie wstępnej wyceny w zależności od dokumentu i pary językowej.",
    keywords: ["cena przysięgłego", "koszt przysięgłego", "czy przysięgłe droższe", "stawka przysięgłego"],
  },
  {
    id: "noter-apostil-ucreti-dahil",
    category: "pricing",
    priority: 51,
    q: "Czy opłaty za poświadczenie notarialne i apostille są wliczone w cenę?",
    a: "Poświadczenie notarialne to odrębna procedura wykonywana przez właściwe organy i podlegająca urzędowym taryfom; koszt ten jest wykazywany oddzielnie od opłaty za tłumaczenie, a ponieważ wynika z urzędowej taryfy, może nie być z góry dokładny — rzeczywista kwota jest potwierdzana po zakończeniu procedury. Procesu apostille natomiast nie przeprowadzamy; apostille należy uzyskać samodzielnie we właściwym organie, a my jedynie tłumaczymy Państwa dokument opatrzony apostille.",
    keywords: ["opłata notarialna", "opłata za apostille", "czy wliczone", "koszt notariusza", "koszt apostille"],
  },
  {
    id: "on-fiyat-nihai-fark",
    category: "pricing",
    priority: 52,
    q: "Czy wstępna wycena może różnić się od ceny ostatecznej?",
    a: "Tak. Automatyczne wyliczenie widoczne na ekranie to wstępna wycena. Po weryfikacji uwzględniającej liczbę słów, czytelność lub rodzaj dokumentu ostateczna cena może zostać potwierdzona. Ostateczną kwotę przekazujemy Państwu przed zatwierdzeniem.",
    keywords: ["wstępna wycena", "cena ostateczna", "różnica w cenie", "dokładna cena"],
  },
  {
    id: "otomatik-kelime-sayimi",
    category: "pricing",
    priority: 53,
    q: "Czy liczba słów jest obliczana automatycznie? Jak jest w przypadku zeskanowanych plików PDF?",
    a: "W przypadku dokumentów tekstowych (Word, tekstowy PDF, zwykły tekst) liczba słów jest zliczana automatycznie. W przypadku zeskanowanych lub obrazowych plików PDF i zdjęć automatyczne zliczanie może nie być wiarygodne, dlatego liczbę tę potwierdza nasz zespół. Wstępna wycena opiera się na automatycznym zliczeniu i nie jest wiążąca; w razie rozbieżności ostateczna cena zostaje z Państwem potwierdzona.",
    keywords: ["liczenie słów", "automatyczne zliczanie", "zeskanowany pdf", "obrazowy pdf", "błąd zliczania"],
  },
  {
    id: "toplu-kurumsal-indirim",
    category: "pricing",
    priority: 54,
    q: "Czy istnieją zniżki dla zamówień zbiorczych lub klientów biznesowych?",
    a: "Przy dużych i regularnych zleceniach, szczególnie dla klientów biznesowych, możemy zaoferować korzystne ceny i opcje terminów płatności w zależności od objętości i warunków współpracy. Szczegóły znajdą Państwo w formularzu zgłoszeniowym dla firm.",
    keywords: ["zniżka zbiorcza", "rabat ilościowy", "ceny dla firm", "stawki biznesowe"],
  },
  {
    id: "ucretsiz-teklif",
    category: "pricing",
    priority: 55,
    q: "Czy mogę otrzymać bezpłatną wycenę i jak długo jest ona ważna?",
    a: "Wstępna wycena jest bezpłatna; widzą ją Państwo natychmiast po przesłaniu dokumentu lub wprowadzeniu tekstu. Wyceny są ważne przez krótki czas, o ile warunki (treść/zakres dokumentu) nie ulegną zmianie.",
    keywords: ["bezpłatna wycena", "darmowa wycena", "ważność wyceny", "jak długo ważna"],
  },
  {
    id: "fatura-kesiliyor-mu",
    category: "pricing",
    priority: 56,
    q: "Czy wystawiają Państwo faktury? Czy mogę otrzymać fakturę indywidualną lub firmową?",
    a: "Tak. Za usługę wystawiamy fakturę, a Państwo mogą poprosić o fakturę indywidualną lub firmową. Klientom biznesowym możemy również zaoferować miesięczne fakturowanie zbiorcze. Podatki naliczane są zgodnie z obowiązującymi przepisami.",
    keywords: ["faktura", "fakturowanie", "vat", "faktura firmowa", "faktura indywidualna"],
  },
  {
    id: "taksit-secenegi",
    category: "pricing",
    priority: 57,
    q: "Czy dostępna jest płatność ratalna?",
    a: "Płatność ratalna może być dostępna przy płatnościach kartą kredytową. Dostępne plany ratalne wyświetlają się na etapie płatności.",
    keywords: ["raty", "płatność ratalna", "płatność w ratach", "rozłożenie na raty"],
  },
  {
    id: "kurumsal-vadeli-odeme",
    category: "pricing",
    priority: 58,
    q: "Czy oferują Państwo klientom biznesowym odroczony termin płatności?",
    a: "Tak. Klientom biznesowym możemy zaoferować odroczony termin płatności do 15–30 dni oraz miesięczne fakturowanie. Warunki ustalane są w ramach współpracy biznesowej.",
    keywords: ["odroczony termin płatności", "termin płatności", "płatność firmowa", "płatność odroczona"],
  },
  {
    id: "odeme-yapilmadan-baslar-mi",
    category: "pricing",
    priority: 59,
    q: "Czy tłumaczenie rozpoczyna się przed dokonaniem płatności?",
    a: "W przypadku zamówień standardowych tłumaczenie rozpoczyna się po otrzymaniu płatności (lub zatwierdzeniu odroczonego terminu płatności dla firm). W przypadku umów firmowych proces może przebiegać zgodnie z umową.",
    keywords: ["przedpłata", "przed płatnością", "płatność z góry", "bez płatności"],
  },
  {
    id: "iade-sureci",
    category: "pricing",
    priority: 60,
    q: "Czy w przypadku anulowanych zamówień dokonują Państwo zwrotów?",
    a: "W przypadku zamówień anulowanych, zanim tłumacz podjął tłumaczenie, płatność jest zwracana w całości na pierwotną metodę płatności. Po podjęciu tłumaczenia przez tłumacza zwrot nie jest dokonywany ze względu na zindywidualizowany charakter świadczenia. W sytuacjach takich jak podwójne lub błędne obciążenie zwracamy nadpłaconą kwotę.",
    keywords: ["zwrot", "zwrot pieniędzy", "zwrot za anulowanie", "rekompensata"],
  },

  // ——— PRZESYŁANIE PLIKÓW ———
  {
    id: "hangi-formatlar",
    category: "upload",
    priority: 61,
    q: "Jakie formaty plików są obsługiwane?",
    a: "Akceptujemy ponad 50 formatów, w tym Word (DOC/DOCX), PDF, zwykły tekst (TXT), Excel, PowerPoint oraz popularne formaty graficzne (JPG, PNG). W przypadku dokumentów tekstowych liczba słów jest zliczana automatycznie.",
    keywords: ["format pliku", "obsługiwane formaty", "pdf", "doc", "docx", "txt"],
  },
  {
    id: "taranmis-fotograf-belge",
    category: "upload",
    priority: 62,
    q: "Czy akceptują Państwo dokumenty zeskanowane lub zdjęcia?",
    a: "Tak. Akceptujemy dokumenty zeskanowane oraz wyraźne zdjęcia zrobione telefonem. Czytelność ma znaczenie; pieczęcie, stemple i podpisy muszą być widoczne. Ponieważ tekst na obrazach może nie zostać odczytany automatycznie, liczbę słów ustala nasz zespół.",
    keywords: ["dokument zeskanowany", "zdjęcie dokumentu", "zdjęcie telefonem", "przesyłanie obrazu", "zdjęcie"],
  },
  {
    id: "birden-fazla-dosya-yukleme",
    category: "upload",
    priority: 63,
    q: "Czy mogę przesłać wiele plików jednocześnie?",
    a: "Tak, mogą Państwo przesłać wiele plików jednocześnie. Cena obliczana jest na podstawie łącznej treści.",
    keywords: ["przesyłanie wielu", "wiele plików", "przesyłanie zbiorcze", "kilka plików naraz"],
  },
  {
    id: "dosya-boyutu-siniri",
    category: "upload",
    priority: 64,
    q: "Czy istnieje limit rozmiaru pliku? Jak wysłać duże pliki?",
    a: "Można przesłać pliki o rozmiarze do około 100 MB na plik. W przypadku większych plików proszę skontaktować się z naszą linią wsparcia, aby ustalić przesłanie e-mailem lub inną metodą.",
    keywords: ["rozmiar pliku", "limit rozmiaru", "duży plik", "100 mb"],
  },
  {
    id: "yuklenen-dosya-silinebilir",
    category: "upload",
    priority: 65,
    q: "Czy mogę usunąć lub zamienić przesłany plik?",
    a: "Tak. Zanim zamówienie zostanie ukończone, mogą Państwo usunąć przesłany plik lub zastąpić go nowym.",
    keywords: ["usunięcie pliku", "zamiana pliku", "błędny plik", "zmiana pliku"],
  },
  {
    id: "manuel-kelime-girisi",
    category: "upload",
    priority: 66,
    q: "Czy mogę wpisać liczbę słów ręcznie bez przesyłania pliku?",
    a: "Zamiast wpisywać liczbę bezpośrednio, proszę wkleić tekst w zakładce „Wprowadź tekst”, a liczba słów zostanie obliczona automatycznie. W ten sposób mogą Państwo otrzymać wstępną wycenę bez pliku.",
    keywords: ["ręczna liczba słów", "wpisanie słów", "wprowadź tekst", "wycena bez pliku"],
  },
  {
    id: "dosyalar-ne-kadar-saklanir",
    category: "upload",
    priority: 67,
    q: "Jak długo przechowywane są pliki i czy mogę zażądać ich usunięcia?",
    a: "Państwa dokumenty przechowujemy bezpiecznie tylko przez czas niezbędny do realizacji usługi. W dowolnym momencie mogą Państwo zażądać usunięcia dokumentów; taka prośba jest realizowana zgodnie z Państwa prawami wynikającymi z KVKK.",
    keywords: ["okres przechowywania", "przechowywanie plików", "prośba o usunięcie", "usunięcie danych"],
  },
  {
    id: "belgenin-tum-sayfalari",
    category: "upload",
    priority: 68,
    q: "Czy należy przesłać wszystkie strony i rewersy dokumentu?",
    a: "Tak. Aby tłumaczenie było kompletne i ważne, należy przesłać każdą stronę dokumentu, w tym rewersy, jeśli występują. Ważne, aby obszary z pieczęciami, stemplami i podpisami były wyraźnie widoczne.",
    keywords: ["wszystkie strony", "rewers", "kompletny dokument", "pieczęcie i stemple"],
  },
  {
    id: "imza-kase-cevrilir-mi",
    category: "upload",
    priority: 69,
    q: "Czy pieczęcie, stemple i podpisy są tłumaczone?",
    a: "W tłumaczeniu przysięgłym czytelny tekst na stemplach i pieczęciach jest przenoszony; podpisy odnotowuje się jako „podpis obecny”. Wszelkie nieczytelne obszary są wyraźnie zaznaczane w tłumaczeniu.",
    keywords: ["tłumaczenie stempla", "tłumaczenie pieczęci", "tłumaczenie podpisu", "pieczęcie i podpisy"],
  },
  {
    id: "dosya-guvenli-mi-analiz",
    category: "upload",
    priority: 70,
    q: "Czy treść dokumentu jest bezpieczna podczas automatycznej analizy?",
    a: "Tak. Dokumenty są przesyłane w postaci zaszyfrowanej, a procesy takie jak zliczanie słów odbywają się w bezpiecznym środowisku. Państwa treść nie jest udostępniana osobom trzecim.",
    keywords: ["bezpieczeństwo analizy", "bezpieczeństwo treści", "automatyczne odczytywanie", "poufność analizy"],
  },

  // ——— JĘZYKI I PARY JĘZYKOWE ———
  {
    id: "50-dil-ne-demek",
    category: "languages",
    priority: 71,
    q: "Co oznacza obsługa ponad 50 języków?",
    a: "Oznacza to, że oprócz języków popularnych możemy również tłumaczyć języki rzadziej wybierane. W przypadku języków rzadkich dostępność tłumacza, czas realizacji i cenę potwierdzamy osobno dla każdego zamówienia.",
    keywords: ["50 języków", "język rzadki", "obsługa językowa", "ile języków"],
  },
  {
    id: "yaygin-dil-ciftleri",
    category: "languages",
    priority: 72,
    q: "Czy tłumaczą Państwo pary takie jak turecko-angielska, niemiecka i francuska?",
    a: "Tak. Tłumaczymy popularne pary językowe, takie jak turecki ⇄ angielski, niemiecki, francuski, hiszpański, włoski, arabski i rosyjski, w obu kierunkach. Obsługujemy również języki takie jak chiński i japoński.",
    keywords: ["turecki angielski", "angielski turecki", "niemiecki", "francuski", "para językowa"],
  },
  {
    id: "yabancidan-yabanciya",
    category: "languages",
    priority: 73,
    q: "Czy można tłumaczyć między dwoma językami obcymi innymi niż turecki?",
    a: "Tak, możemy tłumaczyć z jednego języka obcego na drugi, na przykład z angielskiego na francuski. Dostępność i czas realizacji oceniamy w zależności od pary językowej.",
    keywords: ["obcy na obcy", "angielski francuski", "między językami", "język obcy na obcy"],
  },
  {
    id: "nadir-dil",
    category: "languages",
    priority: 74,
    q: "Czy świadczą Państwo usługi dla języków rzadkich lub spoza listy?",
    a: "Staramy się oferować również języki rzadkie; dostępność tłumacza, czas realizacji i cenę potwierdzamy jednak osobno dla tych języków. Jeśli potrzebnego języka nie ma na liście, proszę napisać do naszej linii wsparcia, aby poprosić o indywidualną wycenę.",
    keywords: ["język rzadki", "język mniej popularny", "język spoza listy", "język specjalny"],
  },
  {
    id: "dil-varyantlari",
    category: "languages",
    priority: 75,
    q: "Czy mogę wybrać regionalny wariant języka (np. angielski amerykański lub brytyjski)?",
    a: "Tak, w miarę możliwości mogą Państwo określić regionalny wariant języka docelowego (np. angielski amerykański/brytyjski, hiszpański europejski/latynoamerykański). Jeśli wariant nie zostanie wskazany, stosujemy powszechny standard.",
    keywords: ["wariant", "angielski amerykański", "wariant regionalny", "dialekt"],
  },
  {
    id: "anadili-tercuman",
    category: "languages",
    priority: 76,
    q: "Czy pracują Państwo z tłumaczami, dla których język docelowy jest ojczysty?",
    a: "W miarę możliwości pracujemy z doświadczonymi tłumaczami biegłymi w języku docelowym. Celem jest zapewnienie naturalnego i wiernego tłumaczenia.",
    keywords: ["tłumacz native", "native speaker", "specjalista języka docelowego", "język ojczysty"],
  },
  {
    id: "osmanlica-eski-yazi",
    category: "languages",
    priority: 77,
    q: "Czy można tłumaczyć dokumenty w języku osmańskim lub dawnym piśmie?",
    a: "Dokumenty w języku osmańskim i zapisane dawnym alfabetem można tłumaczyć, w zależności od dostępności specjalisty. W przypadku takich dokumentów czas realizacji i cenę potwierdzamy po weryfikacji.",
    keywords: ["język osmański", "dawne pismo", "dawny alfabet", "stare pismo"],
  },
  {
    id: "karisik-dilli-belge",
    category: "languages",
    priority: 78,
    q: "Czy można przetłumaczyć dokument, jeśli zawiera więcej niż jeden język?",
    a: "Tak. Dokumenty wielojęzyczne można tłumaczyć; cena zależy od ilości treści w każdym języku. Wystarczy wskazać potrzebny język docelowy.",
    keywords: ["język mieszany", "dokument wielojęzyczny", "wiele języków w dokumencie", "dwa języki"],
  },

  // ——— RODZAJE USŁUG ———
  {
    id: "hangi-hizmeti-secmeliyim",
    category: "services",
    priority: 79,
    q: "Jaki rodzaj usługi powinienem wybrać?",
    a: "O wyborze usługi decyduje to, gdzie dokument będzie używany: postępowania urzędowe zwykle wymagają tłumaczenia przysięgłego, a niektóre procedury — tłumaczenia z poświadczeniem notarialnym lub apostille. W razie wątpliwości nasza linia wsparcia lub asystent czatu doradzi; ostateczny wymóg zależy od danej instytucji.",
    keywords: ["jaka usługa", "wybór usługi", "co wybrać", "który rodzaj usługi"],
  },
  {
    id: "standart-yeminli-fark",
    category: "services",
    priority: 80,
    q: "Jaka jest różnica między tłumaczeniem standardowym a przysięgłym?",
    a: "Tłumaczenie standardowe ma charakter informacyjny i nie zawiera oficjalnego poświadczenia. Tłumaczenie przysięgłe jest natomiast poświadczone pieczęcią i podpisem tłumacza przysięgłego i wymagane przy oficjalnych postępowaniach. To, które z nich jest potrzebne, zależy od instytucji, do której dokument zostanie złożony.",
    keywords: ["standardowe a przysięgłe", "różnica", "zwykłe tłumaczenie", "różnica przysięgłe"],
  },
  {
    id: "yeminli-noter-ayni-mi",
    category: "services",
    priority: 81,
    q: "Czy tłumaczenie przysięgłe i tłumaczenie z poświadczeniem notarialnym to to samo?",
    a: "Nie. Tłumaczenie przysięgłe nosi poświadczenie tłumacza przysięgłego. Tłumaczenie z poświadczeniem notarialnym to takie tłumaczenie dodatkowo poświadczone przez notariusza. Niektóre instytucje wymagają wyłącznie tłumaczenia przysięgłego, inne żądają również poświadczenia notarialnego.",
    keywords: ["przysięgłe a notarialne", "poświadczenie notarialne", "czy to samo", "różnica przysięgłe notarialne"],
  },
  {
    id: "hukuki-teknik-medikal",
    category: "services",
    priority: 82,
    q: "Jak zapewniana jest specjalizacja w tłumaczeniach prawniczych, technicznych i medycznych?",
    a: "Umowy, dokumenty sądowe, dokumentacja techniczna i dokumenty medyczne są tłumaczone przez doświadczonych tłumaczy znających terminologię danej dziedziny. Glosariusze terminologiczne i pamięć tłumaczeniowa zapewniają spójność, formaty i jednostki są zachowywane, a tłumaczenie przechodzi kontrolę jakości.",
    keywords: ["tłumaczenie prawnicze", "tłumaczenie techniczne", "tłumaczenie medyczne", "tłumacz specjalista", "terminologia"],
  },
  {
    id: "akademik-bicim-korunur",
    category: "services",
    priority: 83,
    q: "Czy w tłumaczeniu akademickim zachowywana jest bibliografia i formatowanie?",
    a: "Tak. W pracach dyplomowych, artykułach i tekstach akademickich układ bibliografii, przypisy i formatowanie są zachowywane w miarę możliwości, a tłumaczenie odpowiada stylowi akademickiemu.",
    keywords: ["tłumaczenie akademickie", "praca dyplomowa", "artykuł", "bibliografia", "przypisy"],
  },
  {
    id: "lokalizasyon-nedir",
    category: "services",
    priority: 84,
    q: "Czy lokalizacja to tylko dosłowne tłumaczenie słów? Czy uwzględniane jest SEO?",
    a: "Nie. Lokalizacja polega na dostosowaniu tekstu do kultury i sposobu użytkowania w kraju docelowym; interfejs, formaty daty/waluty oraz ton są dopasowywane do odbiorcy docelowego. W lokalizacji stron internetowych, na życzenie, możemy uwzględnić słowa kluczowe w języku docelowym oraz zgodność z SEO.",
    keywords: ["lokalizacja", "tłumaczenie strony", "tłumaczenie aplikacji", "seo", "zlokalizuj"],
  },
  {
    id: "kurumsal-marka-dili",
    category: "services",
    priority: 85,
    q: "Czy w treściach firmowych zachowywany jest język marki?",
    a: "Tak. W tłumaczeniach firmowych baza terminologiczna i przewodnik stylistyczny pozwalają zachować spójność języka i tonu Państwa marki.",
    keywords: ["język marki", "ton firmowy", "przewodnik stylistyczny", "spójność marki"],
  },
  {
    id: "vize-diploma-hangi-hizmet",
    category: "services",
    priority: 86,
    q: "Jaka usługa jest potrzebna dla dokumentów takich jak wiza lub dyplom?",
    a: "W przypadku wniosków wizowych i tłumaczeń dyplomów podstawowym wymogiem jest zwykle tłumaczenie przysięgłe; niektóre placówki lub instytucje mogą dodatkowo wymagać poświadczenia notarialnego lub apostille. Dokładny wymóg zależy od konsulatu lub instytucji, do której składają Państwo wniosek.",
    keywords: ["dokument wizowy", "tłumaczenie dyplomu", "suplement", "konsulat", "tłumaczenie do wizy"],
  },
  {
    id: "belge-turu-listede-yok",
    category: "services",
    priority: 87,
    q: "Co wybrać, jeśli rodzaju mojego dokumentu nie ma na liście?",
    a: "Jeśli rodzaju Państwa dokumentu nie ma na liście, proszę wybrać najbliższą opcję i dodać wyjaśnienie w uwadze do zamówienia. W razie potrzeby nasza linia wsparcia pomoże dokonać właściwego wyboru.",
    keywords: ["rodzaj dokumentu spoza listy", "inny dokument", "brak na liście", "dokument nietypowy"],
  },

  // ——— DOSTAWA I CZAS REALIZACJI ———
  {
    id: "teslim-suresi-nasil-hesaplanir",
    category: "delivery",
    priority: 88,
    q: "Jak obliczany jest czas realizacji i gdzie jest wyświetlany?",
    a: "Czas realizacji obliczany jest na podstawie długości dokumentu, pary językowej, rodzaju usługi oraz usług dodatkowych i wyświetlany jako szacowana data dostarczenia na ekranie Oblicz cenę. W przypadku procedur wymagających poświadczenia notarialnego lub apostille mogą zostać doliczone dodatkowe dni; jeśli data dostarczenia się zmieni, poinformujemy Państwa o tym.",
    keywords: ["obliczanie czasu realizacji", "szacowana dostawa", "kiedy gotowe", "szacowany termin"],
  },
  {
    id: "ayni-gun-teslimat",
    category: "delivery",
    priority: 89,
    q: "Czy możliwa jest dostawa tego samego dnia lub w ciągu 24 godzin?",
    a: "W przypadku krótkich dokumentów szybka/ekspresowa realizacja jest często możliwa; dostępność zależy od długości i języka dokumentu. Etapy kontroli jakości są zachowane również przy realizacji ekspresowej, a opcja ta wyświetla się jako dodatkowa pozycja na ekranie wstępnej wyceny.",
    keywords: ["ten sam dzień", "24 godziny", "szybka dostawa", "pilne"],
  },
  {
    id: "hafta-sonu-tatil",
    category: "delivery",
    priority: 90,
    q: "Kiedy realizowane są zamówienia złożone w weekend lub poza godzinami pracy?",
    a: "Dokumenty można przesyłać, wyceniać i składać zamówienia o każdej porze. Zamówienia złożone poza godzinami pracy lub w dni wolne są przyjmowane do realizacji z początkiem najbliższych godzin pracy, a szacowany czas realizacji wyświetlany jest odpowiednio.",
    keywords: ["weekend", "dzień wolny", "poza godzinami pracy", "zamówienie nocne"],
  },
  {
    id: "dijital-teslim-format",
    category: "delivery",
    priority: 91,
    q: "Jak przebiega dostawa cyfrowa i w jakim formacie ją otrzymam?",
    a: "Gotowe tłumaczenie dostarczamy cyfrowo za pomocą linku do pobrania lub e-mailem. Mogą je Państwo otrzymać w formacie PDF lub edytowalnym Word (DOCX) w zależności od potrzeb; oryginalne formatowanie jest zachowywane w miarę możliwości.",
    keywords: ["dostawa cyfrowa", "dostawa word", "dostawa pdf", "pobieranie"],
  },
  {
    id: "kargo-kapsam-takip",
    category: "delivery",
    priority: 92,
    q: "Do jakich regionów wysyłają Państwo przesyłki i czy mogę śledzić przesyłkę?",
    a: "Dokumenty z własnoręcznym oryginalnym podpisem i pieczęcią wysyłamy kurierem na terenie całej Turcji; na życzenie możemy wysłać je również za granicę. Informacje o śledzeniu przesyłki są Państwu udostępniane, a czas wysyłki dolicza się do łącznego czasu realizacji.",
    keywords: ["regiony wysyłki", "śledzenie przesyłki", "wysyłka zagraniczna", "czas wysyłki"],
  },
  {
    id: "kismi-teslimat",
    category: "delivery",
    priority: 93,
    q: "Czy długie projekty mogą być dostarczane w częściach?",
    a: "Tak. Projekty o dużej objętości lub długie mogą być dostarczane w częściach na życzenie. Dzięki temu mogą Państwo zacząć korzystać z dokumentów bez czekania.",
    keywords: ["dostawa częściowa", "w częściach", "dostawa etapami", "tłumaczenie w częściach"],
  },

  // ——— TŁUMACZENIE PRZYSIĘGŁE ———
  {
    id: "yeminli-tercuman-kim",
    category: "sworn",
    priority: 94,
    q: "Kim jest tłumacz przysięgły?",
    a: "Tłumacz przysięgły to tłumacz, który złożył przysięgę przed notariuszem i tym samym uzyskał uprawnienie do poświadczania swoich tłumaczeń podpisem i pieczęcią. Poświadczenie to jest oświadczeniem, że tłumaczenie wiernie odzwierciedla oryginał.",
    keywords: ["tłumacz przysięgły", "kto to tłumacz przysięgły", "tłumacz poświadczający", "uprawnienia tłumacza"],
  },
  {
    id: "yeminli-ne-zaman-gerekli",
    category: "sworn",
    priority: 95,
    q: "Kiedy wymagane jest tłumaczenie przysięgłe?",
    a: "Tłumaczenia przysięgłe są często wymagane przy wnioskach do instytucji urzędowych, sądów, konsulatów i uczelni. Nie są jednak obowiązkowe dla każdego dokumentu; dokładny wymóg określa instytucja żądająca dokumentu.",
    keywords: ["kiedy przysięgłe wymagane", "czy potrzebne przysięgłe", "gdzie wymagane", "kiedy konieczne"],
  },
  {
    id: "yeminli-nerede-gecerli",
    category: "sworn",
    priority: 96,
    q: "Czy tłumaczenie przysięgłe jest ważne w sądzie, konsulacie i za granicą?",
    a: "Tłumaczenie przysięgłe może być używane w wielu oficjalnych procedurach i wnioskach. Warunki przyjęcia dokumentu przez daną instytucję zależą jednak od jej własnych przepisów; szczególnie za granicą może być wymagane również poświadczenie notarialne lub apostille. Zalecamy potwierdzenie wymogów przyjęcia w odpowiedniej instytucji.",
    keywords: ["sąd", "konsulat", "ważny za granicą", "wniosek na uczelnię"],
  },
  {
    id: "dijital-imzali-yeminli",
    category: "sworn",
    priority: 97,
    q: "Czy tłumaczenie przysięgłe można wystawić z podpisem cyfrowym/elektronicznym?",
    a: "Nie. Tłumaczenie przysięgłe przygotowywane jest z własnoręcznym oryginalnym podpisem i pieczęcią tłumacza i dostarczane fizycznie kurierem.",
    keywords: ["podpis elektroniczny", "cyfrowe przysięgłe", "e-podpis", "własnoręczny oryginalny podpis", "pieczęć"],
  },
  {
    id: "yeminli-orijinal-gerekir",
    category: "sworn",
    priority: 98,
    q: "Czy do tłumaczenia przysięgłego wymagany jest oryginał dokumentu?",
    a: "Tłumaczenie zwykle można wykonać na podstawie wyraźnej kopii dokumentu (skanu lub zdjęcia). Jeśli jednak wymagane jest poświadczenie notarialne, na potrzeby tej procedury może być wymagany oryginał lub poświadczony odpis dokumentu.",
    keywords: ["oryginał dokumentu", "czy potrzebny oryginał", "kopia do przysięgłego", "skan czy oryginał"],
  },
  {
    id: "yeminli-gecerlilik-suresi",
    category: "sworn",
    priority: 99,
    q: "Czy tłumaczenie przysięgłe ma datę ważności?",
    a: "Samo tłumaczenie nie jest ograniczone czasowo; niektóre instytucje mogą jednak wymagać dokumentu z aktualną datą. Zależy to od wymogów instytucji, która przyjmie dokument.",
    keywords: ["data ważności", "ważność przysięgłego", "jak długo ważne", "termin ważności"],
  },
  {
    id: "kurum-belgeyi-kabul-etmezse",
    category: "sworn",
    priority: 100,
    q: "Co się stanie, jeśli instytucja nie przyjmie tłumaczenia przysięgłego?",
    a: "Wymogi przyjęcia mogą różnić się w zależności od instytucji. Jeśli instytucja ma szczególny wymóg dotyczący formatu lub poświadczenia, proszę nas o tym poinformować, a wprowadzimy niezbędne zmiany. Ostateczna decyzja o przyjęciu należy do instytucji.",
    keywords: ["nieprzyjęcie", "odmowa instytucji", "wymóg formatu", "brak akceptacji"],
  },

  // ——— POŚWIADCZENIE NOTARIALNE I APOSTILLE ———
  {
    id: "noter-onayli-nedir",
    category: "notary",
    priority: 101,
    q: "Czym jest tłumaczenie z poświadczeniem notarialnym?",
    a: "Tłumaczenie z poświadczeniem notarialnym to tłumaczenie przysięgłe dodatkowo poświadczone przez notariusza. Poświadczenie to wzmacnia oficjalną ważność tłumaczenia i jest wymagane przez niektóre instytucje.",
    keywords: ["tłumaczenie z poświadczeniem notarialnym", "poświadczenie notarialne", "co to notarialne", "notariusz"],
  },
  {
    id: "noter-yeminli-fark",
    category: "notary",
    priority: 102,
    q: "Jaka jest różnica między poświadczeniem notarialnym a tłumaczeniem przysięgłym?",
    a: "Tłumaczenie przysięgłe nosi poświadczenie tłumacza, natomiast poświadczenie notarialne to potwierdzenie tego tłumaczenia przez notariusza. Poświadczenie notarialne jest dodatkowym oficjalnym krokiem nakładanym na tłumaczenie przysięgłe.",
    keywords: ["notarialne a przysięgłe", "różnica poświadczeń", "notariusz a tłumacz przysięgły", "różnica notariusz przysięgły"],
  },
  {
    id: "notere-gitmem-gerekir-mi",
    category: "notary",
    priority: 103,
    q: "Czy muszę udać się do notariusza w celu poświadczenia notarialnego?",
    a: "W większości przypadków możemy przeprowadzić poświadczenie notarialne w Państwa imieniu, więc nie muszą Państwo osobiście udawać się do notariusza. Jeśli wymagany będzie oryginał dokumentu, poinformujemy o tym z wyprzedzeniem.",
    keywords: ["wizyta u notariusza", "procedura notarialna", "notariusz w moim imieniu", "czy iść do notariusza"],
  },
  {
    id: "apostil-nedir",
    category: "notary",
    priority: 104,
    q: "Czym jest apostille i czym różni się od poświadczenia notarialnego?",
    a: "Apostille to międzynarodowe poświadczenie wydawane przez właściwy organ, dzięki któremu dokument urzędowy jest uznawany za ważny w innym kraju, i obowiązuje między krajami będącymi stronami konwencji haskiej. Poświadczenie notarialne jest natomiast poświadczeniem w obrębie danego kraju; oba służą różnym celom.",
    keywords: ["co to apostille", "apostille a notariusz", "konwencja haska", "czym jest apostille"],
  },
  {
    id: "apostil-once-mi-ceviri-once-mi",
    category: "notary",
    priority: 105,
    q: "Co jest pierwsze — apostille czy tłumaczenie?",
    a: "Kolejność zależy od rodzaju dokumentu i wymogów kraju, w którym będzie używany. W niektórych przypadkach dokument jest najpierw opatrywany apostille, a następnie tłumaczony; w innych jest odwrotnie. Właściwą kolejność możemy ustalić wspólnie.",
    keywords: ["kolejność apostille", "najpierw tłumaczenie czy apostille", "kolejność", "apostille przed tłumaczeniem"],
  },
  {
    id: "yabanci-belge-turkiye",
    category: "notary",
    priority: 106,
    q: "Jak wygląda proces, jeśli dokument zagraniczny ma być używany w Turcji?",
    a: "Dokument pochodzący z zagranicy jest zwykle najpierw opatrywany apostille w kraju pochodzenia, a następnie w Turcji wykonuje się jego tłumaczenie przysięgłe (i w razie potrzeby poświadczenie notarialne). Dokładny proces zależy od tureckiej instytucji żądającej dokumentu.",
    keywords: ["dokument zagraniczny w turcji", "dokument przychodzący", "dokument z zagranicy", "zagraniczny dokument"],
  },
  {
    id: "turk-belge-yurt-disi",
    category: "notary",
    priority: 107,
    q: "Jak wygląda proces, jeśli dokument turecki ma być używany za granicą?",
    a: "Dokument wystawiony w Turcji jest zwykle opatrywany apostille i tłumaczony przysięgle na język docelowy. Jeśli kraj docelowy nie jest stroną konwencji haskiej, zamiast apostille może być wymagane poświadczenie konsularne.",
    keywords: ["dokument turecki za granicą", "dokument wychodzący", "poświadczenie konsularne", "dokument do użytku za granicą"],
  },
  {
    id: "hangi-onay-gerekli-bilinmiyor",
    category: "notary",
    priority: 109,
    q: "Jak sprawdzić, czy potrzebne jest poświadczenie notarialne, czy apostille?",
    a: "Najpewniejszym sposobem jest zapytanie instytucji żądającej dokumentu. W razie potrzeby nasza linia wsparcia może wskazać powszechne praktyki; dokładny wymóg zależy jednak od instytucji i kraju.",
    keywords: ["które poświadczenie", "czy potrzebne poświadczenie", "notariusz czy apostille", "jakie poświadczenie"],
  },
  {
    id: "kesin-kabul-garantisi",
    category: "notary",
    priority: 110,
    q: "Czy TercümExpert gwarantuje przyjęcie dokumentu?",
    a: "Dbamy o to, aby tłumaczenie i poświadczenia były przygotowane rzetelnie i kompletnie; warunki przyjęcia dokumentu określa jednak instytucja, która go żąda. Z tego powodu nie możemy zaoferować bezwarunkowej gwarancji przyjęcia; jeśli przekażą nam Państwo szczególne wymogi instytucji, wprowadzimy niezbędne zmiany.",
    keywords: ["gwarancja przyjęcia", "gwarantowane przyjęcie", "gwarancja", "czy przyjmą dokument"],
  },

  // ——— JAKOŚĆ I KOREKTY ———
  {
    id: "tercumanlar-nasil-secilir",
    category: "quality",
    priority: 111,
    q: "Jak dobierani są tłumacze i jak ustalana jest ich specjalizacja?",
    a: "Tłumacze są dobierani na podstawie pary językowej i dziedziny dokumentu; dokument prawniczy trafia do tłumacza doświadczonego w prawie, a dokument medyczny — do tłumacza doświadczonego w ochronie zdrowia. Najbardziej odpowiedni tłumacz jest przydzielany z uwzględnieniem doświadczenia w dziedzinie i biegłości językowej.",
    keywords: ["dobór tłumacza", "jak dobierani tłumacze", "specjalizacja", "ekspert dziedzinowy"],
  },
  {
    id: "kalite-kontrol",
    category: "quality",
    priority: 112,
    q: "Czy tłumaczenie przechodzi kontrolę jakości?",
    a: "Tak. Tłumaczenia są sprawdzane pod kątem pisowni, terminologii, spójności liczb/nazwisk/dat oraz formatowania. W zależności od rodzaju dokumentu i poziomu usługi może zostać zastosowany niezależny etap redakcji/korekty.",
    keywords: ["kontrola jakości", "korekta", "redaktor", "weryfikacja"],
  },
  {
    id: "ceviri-bellegi",
    category: "quality",
    priority: 113,
    q: "Czy stosują Państwo pamięć tłumaczeniową lub listy terminologiczne?",
    a: "Tak, szczególnie w projektach technicznych i firmowych stosujemy pamięć tłumaczeniową i listy terminologiczne w celu zapewnienia spójności. Mogą Państwo również udostępnić własną listę terminów; terminologia z wcześniejszych projektów jest zachowywana.",
    keywords: ["pamięć tłumaczeniowa", "lista terminologiczna", "spójność", "glosariusz"],
  },
  {
    id: "revize-kapsami",
    category: "quality",
    priority: 114,
    q: "Co obejmuje korekta i kiedy należy o nią prosić?",
    a: "Korekta obejmuje kwestie takie jak błędy tłumaczeniowe, pisownia, niespójności i pominięcia. Późniejsza zmiana tekstu źródłowego lub dodanie nowej treści może zostać uznane za nowe zlecenie. Zalecamy przesłanie prośby o korektę w rozsądnym czasie po dostarczeniu, e-mailem lub przez WhatsApp.",
    keywords: ["zakres korekty", "zakres poprawek", "termin korekty", "kiedy korekta"],
  },
  {
    id: "tercuman-degisikligi",
    category: "quality",
    priority: 115,
    q: "Co jeśli nie jestem zadowolony z tłumaczenia — czy można zmienić tłumacza?",
    a: "Jeśli nie są Państwo zadowoleni z tłumaczenia, analizujemy sytuację i w razie potrzeby organizujemy poprawki z udziałem innego tłumacza lub redaktora. Celem jest, aby wynik spełnił Państwa oczekiwania.",
    keywords: ["zmiana tłumacza", "brak zadowolenia", "niezadowolenie z tłumaczenia", "inny tłumacz"],
  },
  {
    id: "dogruluk-garanti",
    category: "quality",
    priority: 116,
    q: "Czy poprawność tłumaczenia jest gwarantowana?",
    a: "Państwa tłumaczenia przygotowują tłumacze specjaliści, a następnie przechodzą one kontrolę jakości i dokładamy należytej staranności o poprawność. Mimo to wymogi oficjalnego przyjęcia dokumentu mogą różnić się w zależności od instytucji, która go żąda.",
    keywords: ["gwarancja poprawności", "gwarancja jakości", "zapewnienie", "rzetelność tłumaczenia"],
  },
  {
    id: "makine-cevirisi-kullaniliyor",
    category: "quality",
    priority: 117,
    q: "Czy stosują Państwo w pełni automatyczne tłumaczenie maszynowe?",
    a: "Nie. Tłumaczenia od początku do końca wykonują profesjonalni tłumacze — ludzie; nie oferujemy automatycznego tłumaczenia maszynowego. Do wsparcia spójności wykorzystujemy jedynie narzędzia CAT. Tłumaczenia przysięgłe zawierają pieczęć, podpis tłumacza oraz oświadczenie o zgodności z oryginałem.",
    keywords: ["tłumaczenie maszynowe", "tłumaczenie automatyczne", "tłumaczenie ai", "oświadczenie o zgodności"],
  },

  // ——— PRYWATNOŚĆ I BEZPIECZEŃSTWO ———
  {
    id: "dosyalari-kimler-gorur",
    category: "privacy",
    priority: 118,
    q: "Kto może zobaczyć przesłane pliki i czy są udostępniane osobom trzecim?",
    a: "Dostęp do Państwa plików mają wyłącznie tłumacz i zespół realizujący zamówienie. Poza sytuacjami wymaganymi do świadczenia usługi Państwa dokumenty nie są nigdy udostępniane osobom trzecim ani wykorzystywane do celów marketingowych.",
    keywords: ["kto widzi", "dostęp", "osoba trzecia", "udostępnianie"],
  },
  {
    id: "nda-imzalanabilir",
    category: "privacy",
    priority: 119,
    q: "Czy można podpisać umowę o zachowaniu poufności (NDA)?",
    a: "Tak. Szczególnie w projektach firmowych umowa o zachowaniu poufności (NDA) może zostać zawarta na życzenie. Nasi tłumacze są również związani zobowiązaniami do zachowania poufności.",
    keywords: ["nda", "umowa o zachowaniu poufności", "umowa poufności", "poufność"],
  },
  {
    id: "kvkk-uyumlu",
    category: "privacy",
    priority: 120,
    q: "Czy pracują Państwo zgodnie z KVKK i jak chronione są dane osobowe?",
    a: "Tak. Państwa dane osobowe przetwarzamy zgodnie z procesami odpowiadającymi KVKK; są one wykorzystywane wyłącznie w zakresie niezbędnym do świadczenia usługi i przechowywane w bezpieczny sposób. Zobowiązujemy się chronić Państwa dane za pomocą odpowiednich środków bezpieczeństwa.",
    keywords: ["kvkk", "dane osobowe", "ochrona danych", "zgodność z kvkk"],
  },
  {
    id: "sifreli-aktarim",
    category: "privacy",
    priority: 121,
    q: "Czy pliki są przesyłane z użyciem szyfrowania?",
    a: "Tak. Państwa pliki są przesyłane szyfrowanym połączeniem i przetwarzane w bezpiecznym środowisku. Naszym celem jest ochrona Państwa danych za pomocą odpowiednich środków bezpieczeństwa.",
    keywords: ["szyfrowane", "bezpieczny transfer", "szyfrowanie", "szyfrowane połączenie"],
  },
  {
    id: "odeme-bilgileri-saklanir",
    category: "privacy",
    priority: 122,
    q: "Czy dane płatności/karty kredytowej są przechowywane?",
    a: "Dane Państwa karty nie są przechowywane przez TercümExpert; płatności są realizowane za pośrednictwem bezpiecznej infrastruktury płatniczej.",
    keywords: ["dane płatności", "bezpieczeństwo karty", "przechowywanie karty", "dane karty"],
  },
  {
    id: "belgeler-ai-egitimi",
    category: "privacy",
    priority: 123,
    q: "Czy moje dokumenty są wykorzystywane do trenowania modeli?",
    a: "Nie. Państwa dokumenty są wykorzystywane wyłącznie do realizacji Państwa zamówienia; nie są nigdy udostępniane do trenowania jakichkolwiek modeli ani systemom zewnętrznym. Państwa tłumaczenie przygotowują tłumacze będący ludźmi, z zachowaniem poufności.",
    keywords: ["trenowanie modeli", "wykorzystanie danych", "trenowanie ai", "prywatność dokumentów"],
  },
  {
    id: "saglik-kimlik-guvenli",
    category: "privacy",
    priority: 124,
    q: "Czy dokumenty wrażliwe, takie jak dowody tożsamości, paszporty czy dokumentacja medyczna, są bezpieczne?",
    a: "Tak. Wszystkie Państwa pliki, w tym dokumenty wrażliwe, są przetwarzane poufnie, w sposób zgodny z KVKK i szyfrowany. Dostęp jest ograniczony do zespołu realizującego zamówienie; w przypadku dokumentów o wysokim stopniu poufności można zastosować dodatkowe środki, takie jak NDA i ograniczony dostęp.",
    keywords: ["bezpieczeństwo dowodu", "paszport", "dane medyczne", "dokument wrażliwy"],
  },
  {
    id: "hesap-silinince-belgeler",
    category: "privacy",
    priority: 125,
    q: "Czy dokumenty są usuwane po usunięciu konta lub na żądanie?",
    a: "Na Państwa żądanie dokumenty i dane osobowe są usuwane, z zastrzeżeniem ewentualnych prawnych obowiązków przechowywania. Prośbę o usunięcie konta lub danych mogą Państwo przesłać do naszej linii wsparcia.",
    keywords: ["usunięcie konta", "usunięcie danych", "usunięcie dokumentów", "kasowanie danych"],
  },

  // ——— USŁUGI DLA FIRM ———
  {
    id: "kurumsal-hesap-nasil",
    category: "corporate",
    priority: 126,
    q: "Jak założyć konto firmowe i co dzieje się po złożeniu wniosku?",
    a: "Wystarczy wypełnić formularz zgłoszeniowy na stronie dla firm; nasz zespół zwykle kontaktuje się z Państwem w ciągu 1 dnia roboczego, ocenia potrzeby i ustala dopasowane warunki.",
    keywords: ["konto firmowe", "konto przedsiębiorstwa", "zgłoszenie firmowe", "po złożeniu wniosku"],
  },
  {
    id: "sirket-adina-siparis",
    category: "corporate",
    priority: 127,
    q: "Czy mogę złożyć zamówienie w imieniu firmy?",
    a: "Tak. Mogą Państwo złożyć zamówienie z danymi firmy i skorzystać z fakturowania firmowego oraz, w razie potrzeby, z opcji terminów płatności.",
    keywords: ["w imieniu firmy", "zamówienie firmowe", "zamówienie dla firmy", "faktura firmowa"],
  },
  {
    id: "ozel-hesap-yoneticisi",
    category: "corporate",
    priority: 128,
    q: "Czy klientom biznesowym przydzielany jest dedykowany opiekun klienta?",
    a: "Klientom biznesowym może zostać przydzielony dedykowany opiekun klienta, który czuwa nad ich procesami. Dzięki temu mogą Państwo zarządzać zleceniami z jednego punktu kontaktowego i otrzymywać priorytetowe wsparcie.",
    keywords: ["opiekun klienta", "dedykowany opiekun", "wsparcie firmowe", "priorytetowe wsparcie"],
  },
  {
    id: "toplu-fatura",
    category: "corporate",
    priority: 129,
    q: "Czy mogę otrzymać miesięczne fakturowanie zbiorcze i odroczony termin płatności?",
    a: "Tak. Klientom biznesowym możemy zaoferować miesięczne fakturowanie zbiorcze oraz odroczony termin płatności do 15–30 dni. Szczegóły ustalane są w ramach współpracy.",
    keywords: ["fakturowanie zbiorcze", "faktura miesięczna", "termin płatności", "płatność firmowa"],
  },
  {
    id: "terminoloji-bankasi",
    category: "corporate",
    priority: 130,
    q: "Czy można utworzyć bazę terminologiczną dla konkretnej firmy?",
    a: "Tak. W projektach firmowych tworzymy bazę terminologiczną i przewodnik stylistyczny dopasowane do Państwa marki, aby język i spójność marki były zachowane we wszystkich tłumaczeniach.",
    keywords: ["baza terminologiczna", "przewodnik stylistyczny", "terminologia firmowa", "słownik marki"],
  },
  {
    id: "sabit-tercuman",
    category: "corporate",
    priority: 131,
    q: "Czy przy powtarzalnych projektach możemy pracować z tymi samymi tłumaczami?",
    a: "Tak. Przy powtarzalnych projektach firmowych można utworzyć dedykowany zespół tłumaczy, aby zapewnić ciągłość i spójność.",
    keywords: ["dedykowany tłumacz", "ten sam zespół", "zespół firmowy", "stały tłumacz"],
  },
  {
    id: "kurumsal-raporlama",
    category: "corporate",
    priority: 132,
    q: "Czy mogę otrzymać raporty zamówień i wydatków?",
    a: "Klientom biznesowym możemy zaoferować raportowanie zamówień i wydatków, w razie potrzeby z podziałem na działy. Przy współpracy firmowej można również zawrzeć umowy dotyczące poziomu usług (SLA) i poufności (NDA).",
    keywords: ["raportowanie", "raport wydatków", "raport zamówień", "sla"],
  },
  {
    id: "kucuk-isletme",
    category: "corporate",
    priority: 133,
    q: "Czy małe firmy mogą korzystać z usług dla firm i czy wymagana jest minimalna objętość?",
    a: "Tak. Do korzystania z naszych usług dla firm nie ma wymogu minimalnej wielkości ani objętości; również małe firmy mogą korzystać z takich korzyści jak terminy płatności, zarządzanie terminologią i priorytetowe wsparcie.",
    keywords: ["mała firma", "msp", "minimalna objętość", "wymagana objętość"],
  },
  {
    id: "uluslararasi-sirket",
    category: "corporate",
    priority: 134,
    q: "Czy obsługują Państwo firmy międzynarodowe i projekty wielojęzyczne?",
    a: "Tak. Projekty obejmujące wiele krajów i języków mogą być koordynowane i prowadzone centralnie, z zapewnieniem spójności terminologii na całym ich zakresie. W projektach firmowych możemy również wykonać tłumaczenie przysięgłe oraz, w razie potrzeby, przeprowadzić proces poświadczenia notarialnego.",
    keywords: ["firma międzynarodowa", "projekt wielojęzyczny", "notariusz apostille dla firm", "projekt międzynarodowy"],
  },

  // ——— POMOC TECHNICZNA ———
  {
    id: "nasil-uye-olunur",
    category: "support",
    priority: 135,
    q: "Jak zarejestrować się w serwisie?",
    a: "Aby się zarejestrować, wystarczy podać imię, nazwisko i adres e-mail, a następnie potwierdzić kod weryfikacyjny wysłany na e-mail. Można się również szybko zarejestrować za pomocą konta Apple lub Google.",
    keywords: ["rejestracja", "zarejestruj", "utworzenie konta", "załóż konto"],
  },
  {
    id: "giris-sifre-sorunu",
    category: "support",
    priority: 136,
    q: "Co zrobić, jeśli nie mogę się zalogować lub zapomniałem hasła?",
    a: "Najpierw proszę sprawdzić e-mail i hasło; jeśli zapomnieli Państwo hasła, proszę skorzystać z linku „Nie pamiętam hasła” na ekranie logowania, aby wysłać instrukcje resetowania na e-mail. Jeśli problem będzie się powtarzał, proszę sprawdzić folder spam lub skontaktować się z naszą linią wsparcia.",
    keywords: ["nie mogę się zalogować", "reset hasła", "nie pamiętam hasła", "logowanie", "zaloguj się"],
  },
  {
    id: "dogrulama-epostasi-gelmezse",
    category: "support",
    priority: 137,
    q: "Co zrobić, jeśli e-mail weryfikacyjny nie dotarł?",
    a: "Proszę odczekać kilka minut, sprawdzić folder spam/wiadomości-śmieci i ponownie wysłać kod. Proszę upewnić się, że adres e-mail został wpisany poprawnie; jeśli problem będzie się powtarzał, proszę skontaktować się z naszą linią wsparcia.",
    keywords: ["e-mail weryfikacyjny", "kod nie dotarł", "e-mail nie przychodzi", "kod weryfikacyjny"],
  },
  {
    id: "dosya-yuklenmiyor",
    category: "support",
    priority: 138,
    q: "Co zrobić, jeśli plik się nie przesyła lub pojawia się błąd nieobsługiwanego pliku?",
    a: "Proszę sprawdzić rozmiar pliku (do 100 MB) i format oraz odświeżyć stronę i przeglądarkę. Jeśli format nie jest obsługiwany, proszę przekonwertować plik na format taki jak PDF lub DOCX albo wkleić tekst w zakładce „Wprowadź tekst”. Jeśli problem będzie się powtarzał, proszę skontaktować się z naszą linią wsparcia.",
    keywords: ["plik się nie przesyła", "błąd przesyłania", "nieobsługiwany plik", "błąd formatu"],
  },
  {
    id: "kelime-sayisi-yanlis",
    category: "support",
    priority: 139,
    q: "Co zrobić, jeśli liczba słów wygląda na błędną?",
    a: "Automatyczne zliczanie może być niedokładne, zwłaszcza w przypadku dokumentów zeskanowanych lub obrazowych. Aby uzyskać dokładny wynik, proszę udostępnić tekst przez „Wprowadź tekst” lub dodać uwagę do zamówienia; ostateczną liczbę potwierdza nasz zespół, a cena jest ustalana odpowiednio.",
    keywords: ["błędna liczba słów", "błąd zliczania", "nieprawidłowa liczba słów", "zła liczba słów"],
  },
  {
    id: "odeme-basarisiz",
    category: "support",
    priority: 140,
    q: "Co zrobić, jeśli płatność się nie powiedzie lub zostanę obciążony dwukrotnie?",
    a: "Proszę sprawdzić dane karty i limit oraz spróbować ponownie; można też skorzystać z innej metody (karta/przelew). Jeśli kwota została pobrana, ale nie utworzono zamówienia, lub jeśli doszło do podwójnego obciążenia, proszę skontaktować się z naszą linią wsparcia i przesłać potwierdzenie płatności, a nadpłacona kwota zostanie zwrócona.",
    keywords: ["płatność nieudana", "błąd płatności", "podwójne obciążenie", "obciążenie dwukrotne"],
  },
  {
    id: "teslim-dosyasi-inmiyor",
    category: "support",
    priority: 141,
    q: "Co zrobić, jeśli dostarczony plik się nie pobiera?",
    a: "Proszę odświeżyć link i przeglądarkę; jeśli link do pobrania wygasł, mogą Państwo poprosić o nowy naszą linię wsparcia.",
    keywords: ["plik się nie pobiera", "problem z pobieraniem", "nie można pobrać dostawy", "link wygasł"],
  },
  {
    id: "mobil-tarayici-destegi",
    category: "support",
    priority: 142,
    q: "Czy mogę korzystać z serwisu na urządzeniu mobilnym i które przeglądarki są obsługiwane?",
    a: "Serwis jest przyjazny dla urządzeń mobilnych; dokumenty można przesyłać i składać zamówienia z iPhone’a, telefonu z Androidem lub tabletu. Serwis działa płynnie w aktualnych wersjach przeglądarek Chrome, Safari, Edge i Firefox.",
    keywords: ["mobilny", "telefon", "iphone android", "tablet", "przeglądarka", "chrome safari"],
  },
  {
    id: "ai-asistan-ne-yapar",
    category: "support",
    priority: 143,
    q: "Co potrafi asystent czatu oparty na sztucznej inteligencji?",
    a: "Asystent czatu udziela natychmiastowych wskazówek dotyczących procesu, rodzajów usług i pytań ogólnych oraz kieruje Państwa do właściwych kroków, takich jak uzyskanie wyceny. Nie może podejmować ostatecznych ani wiążących decyzji dotyczących wymogów oficjalnego przyjęcia ani wymogów prawnych (takich jak poświadczenie notarialne czy apostille); w tych kwestiach należy skonsultować się z odpowiednią instytucją.",
    keywords: ["asystent czatu", "chatbot", "asystent ai", "cennik chatbota"],
  },
  {
    id: "insana-baglanma",
    category: "support",
    priority: 144,
    q: "Jak połączyć się z przedstawicielem obsługi klienta będącym człowiekiem?",
    a: "Można o to poprosić przez asystenta czatu lub skontaktować się bezpośrednio z naszą ludzką linią wsparcia przez WhatsApp i e-mail. Zgłoszenia są rozpatrywane w godzinach pracy. Przesłanie problemów technicznych ze zrzutem ekranu przyspiesza ich rozwiązanie.",
    keywords: ["połączenie z człowiekiem", "przedstawiciel obsługi", "obsługa na żywo", "zrzut ekranu"],
  },
  {
    id: "hesap-bilgileri-guncelleme",
    category: "support",
    priority: 145,
    q: "Jak zaktualizować dane konta i rozliczeniowe oraz jak usunąć konto?",
    a: "Jeśli mają Państwo konto, mogą Państwo zaktualizować numer telefonu, adres e-mail i dane rozliczeniowe w ustawieniach konta, a także zażądać tam usunięcia konta lub kontaktując się z naszą linią wsparcia. Na Państwa żądanie dane są usuwane, z zastrzeżeniem ewentualnych obowiązków prawnych.",
    keywords: ["aktualizacja danych", "dane rozliczeniowe", "ustawienia konta", "usunięcie konta"],
  },
  {
    id: "bildirim-tercihleri",
    category: "support",
    priority: 146,
    q: "Jak działają powiadomienia o zamówieniach i czy mogę otrzymywać powiadomienia przez WhatsApp?",
    a: "O statusie zamówienia wysyłamy powiadomienia e-mail; zgodnie z Państwa preferencjami aktualizacje mogą być przekazywane również przez WhatsApp. Preferencje powiadomień mogą Państwo zmienić w ustawieniach konta lub za pośrednictwem naszej linii wsparcia.",
    keywords: ["powiadomienia", "sms", "powiadomienie whatsapp", "powiadomienie e-mail", "powiadomienie o zamówieniu"],
  },
]
