/**
 * SSS veri kaynağı (Türkçe). Fiyat/ödeme mantığı ileride değişebilir (§13).
 * Dürüstlük kuralları: doğrulanmamış ISO/sertifika iddiası YOK; fiziksel ofis
 * varlığı ima edilmez; 7/24 insan desteği vaat edilmez; yeminli/noter/apostil
 * ayrımı korunur; kesin kurum kabul garantisi verilmez.
 * `priority` = küresel önem sırası (küçük = üstte). Kategori görünümünde de aynı
 * sıra kullanıldığından, kategori içi sıralama bu değerden türetilir.
 */
export interface FaqCategory {
  key: string
  label: string
}

export interface FaqItem {
  id: string
  category: string
  priority: number
  q: string
  a: string
  keywords: string[]
}

export const FAQ_CATEGORIES: FaqCategory[] = [
  { key: 'general', label: 'Genel' },
  { key: 'order', label: 'Sipariş Süreci' },
  { key: 'pricing', label: 'Fiyatlandırma ve Ödeme' },
  { key: 'upload', label: 'Dosya Yükleme' },
  { key: 'languages', label: 'Diller ve Dil Çiftleri' },
  { key: 'services', label: 'Hizmet Türleri' },
  { key: 'delivery', label: 'Teslimat ve Süre' },
  { key: 'sworn', label: 'Yeminli Tercüme' },
  { key: 'notary', label: 'Noter ve Apostil' },
  { key: 'quality', label: 'Kalite ve Revize' },
  { key: 'privacy', label: 'Gizlilik ve Güvenlik' },
  { key: 'corporate', label: 'Kurumsal Hizmetler' },
  { key: 'support', label: 'Teknik Destek' },
]

export const FAQ_ITEMS: FaqItem[] = [
  // ——— TÜMÜ: kullanıcı yolculuğuna göre en öncelikli sorular ———
  {
    id: 'nasil-fiyat-alirim',
    category: 'pricing',
    priority: 1,
    q: 'Nasıl fiyat alırım?',
    a: "Fiyat Hesapla sayfasından belgenizi yükleyin ya da metninizi yapıştırın; dil çifti ve hizmet türünü seçtiğinizde ön fiyatınızı anında görürsünüz. Ücret; dil çifti, hizmet türü, kelime sayısı ve seçtiğiniz ek hizmetlere göre hesaplanır.",
    keywords: ['fiyat', 'teklif', 'ucret', 'fiyat alma', 'fiyat hesaplama', 'tercume fiyati'],
  },
  {
    id: 'dosya-nasil-yuklenir',
    category: 'upload',
    priority: 2,
    q: 'Dosyamı nasıl yüklerim?',
    a: "Fiyat Hesapla sayfasındaki 'Dosya Yükle' sekmesinden belgenizi sürükleyip bırakabilir veya seçerek yükleyebilirsiniz. Belgeniz yoksa 'Metin Gir' sekmesine metninizi yapıştırmanız yeterlidir. Metin tabanlı dosyalarda sistem kelime sayısını otomatik çıkarır.",
    keywords: ['dosya yukleme', 'belge yukle', 'dosya ekleme', 'dosya yukleyemiyorum', 'nasil yuklerim'],
  },
  {
    id: 'fiyatlandirma-neye-gore',
    category: 'pricing',
    priority: 3,
    q: 'Fiyatlandırma neye göre yapılır?',
    a: 'Ücret; dil çifti, hizmet türü, belge içeriği, kelime sayısı, uzmanlık alanı ve seçtiğiniz ek hizmetlere göre belirlenir. Ekranda gördüğünüz tutar bir ön fiyattır; belgenin incelenmesinin ardından nihai tutar netleşir.',
    keywords: ['fiyatlandirma', 'ucretlendirme', 'fiyat nasil', 'neye gore fiyat', 'kelime basi'],
  },
  {
    id: 'teslim-suresi-ne-kadar',
    category: 'delivery',
    priority: 4,
    q: 'Teslim süresi ne kadardır?',
    a: 'Süre; belgenin uzunluğu, dil çifti, hizmet türü ve seçtiğiniz ek hizmetlere göre değişir. Fiyat hesaplama ekranında siparişinize özel tahmini teslim süresi gösterilir. Acil teslimat seçeneğiyle bu süre kısaltılabilir.',
    keywords: ['teslim suresi', 'kac gunde', 'ne zaman teslim', 'sure', 'kac gun'],
  },
  {
    id: 'yeminli-tercume-nedir',
    category: 'sworn',
    priority: 5,
    q: 'Yeminli tercüme nedir?',
    a: 'Yeminli tercüme, yeminli çevirmenin imza ve kaşesiyle onayladığı, aslına uygunluğu beyan edilen çeviridir. Resmî başvurularda sıklıkla istenir. Kesin gereklilik, belgeyi talep eden kuruma göre değişir.',
    keywords: ['yeminli tercume', 'yeminli ceviri', 'kaseli tercume', 'resmi ceviri', 'yeminli nedir'],
  },
  {
    id: 'hangi-dillerde-hizmet',
    category: 'languages',
    priority: 6,
    q: 'Hangi dillerde hizmet veriyorsunuz?',
    a: "Türkçe başta olmak üzere İngilizce, Almanca, Fransızca, İspanyolca, İtalyanca, Arapça ve Rusça gibi dillerde ve 50'den fazla dilde hizmet sunuyoruz. Nadir dillerde tercüman uygunluğu ve teslim süresi siparişe göre ayrıca doğrulanır.",
    keywords: ['diller', 'hangi diller', 'dil secenekleri', 'dil ciftleri', 'kac dil'],
  },
  {
    id: 'noter-onayi-gerekir-mi',
    category: 'notary',
    priority: 7,
    q: 'Noter onayı gerekir mi?',
    a: 'Noter onayı her belge için zorunlu değildir; gerekliliği, belgeyi talep eden kuruma ve kullanım amacına göre değişir. Bazı işlemlerde yeminli tercüme yeterliyken, bazılarında ayrıca noter onayı istenir. Hangi onayın gerektiğinden emin değilseniz size yol gösterebiliriz.',
    keywords: ['noter onayi', 'noter tasdik', 'noterli', 'noter gerekli mi'],
  },
  {
    id: 'siparis-nasil-ilerler',
    category: 'order',
    priority: 8,
    q: 'Sipariş süreci nasıl ilerler?',
    a: 'Belgenizi yükleyip ön fiyatı onayladıktan sonra siparişiniz oluşturulur ve alanında uzman bir tercümana atanır. Çeviri kalite kontrolünden geçirilir; gerekiyorsa noter onayı süreci yürütülür ve belgeniz dijital olarak, gerektiğinde kargoyla teslim edilir.',
    keywords: ['siparis sureci', 'nasil ilerler', 'asamalar', 'surec'],
  },
  {
    id: 'belgelerim-guvende-mi',
    category: 'privacy',
    priority: 9,
    q: 'Belgelerim güvende mi?',
    a: 'Evet. Dosyalarınız yalnızca siparişinizde görevli ekip tarafından görülür; şifreli aktarım ve KVKK’ya uygun süreçlerle işlenir. Belgeleriniz üçüncü kişilerle paylaşılmaz ve gizlilik esas alınır.',
    keywords: ['guvenlik', 'gizlilik', 'belge guvenligi', 'veri guvenligi', 'kvkk'],
  },
  {
    id: 'cevirimi-kim-yapar',
    category: 'quality',
    priority: 10,
    q: 'Çevirimi kim yapar?',
    a: 'Çevirileriniz, ilgili alanda deneyimli profesyonel insan tercümanlar tarafından yapılır. Belgenin türüne göre uzman çevirmen atanır ve çeviri, teslimden önce kalite kontrolünden geçer.',
    keywords: ['kim cevirir', 'tercuman', 'cevirmen', 'insan tercuman', 'kim yapar'],
  },
  {
    id: 'revize-hakki-var-mi',
    category: 'quality',
    priority: 11,
    q: 'Revize hakkı var mı?',
    a: 'Evet. Teslim edilen çeviride, kapsam içindeki düzeltme talepleriniz için revize hakkı sunulur. Yazım, isim, tarih veya tutarlılıkla ilgili düzeltmeler bu kapsamdadır. Kaynak metnin sonradan değiştirilmesi veya yeni içerik eklenmesi yeni bir iş sayılabilir.',
    keywords: ['revize', 'duzeltme', 'revizyon', 'tekrar ceviri', 'revize hakki'],
  },
  {
    id: 'fiziksel-teslimat-yapiliyor-mu',
    category: 'delivery',
    priority: 12,
    q: 'Fiziksel teslimat yapılıyor mu?',
    a: 'Evet. Dijital teslimat esas olmakla birlikte, ıslak imzalı/kaşeli belgeler kargoyla adresinize gönderilebilir. Türkiye geneline ve talebinize göre yurt dışına fiziksel gönderim yapılabilir. Kargo tercihinde teslim süresine gönderim süresi eklenir.',
    keywords: ['fiziksel teslimat', 'kargo', 'adrese teslim', 'kargoyla'],
  },
  {
    id: 'kurumsal-ozel-sartlar',
    category: 'corporate',
    priority: 13,
    q: 'Kurumsal müşteriler için özel şartlar var mı?',
    a: 'Evet. Kurumsal müşterilere toplu sipariş avantajları, vade seçenekleri, terminoloji yönetimi ve özel hesap yöneticisi sunulur. Detaylar için Kurumsal sayfasındaki başvuru formunu doldurabilirsiniz.',
    keywords: ['kurumsal', 'sirket', 'kurumsal ozel', 'toplu siparis', 'kurumsal sartlar'],
  },
  {
    id: 'apostil-nasil-yurutulur',
    category: 'notary',
    priority: 14,
    q: 'Apostil işlemi nasıl yürütülür?',
    a: 'Apostil, bir belgenin yurt dışında geçerli sayılması için yetkili makam tarafından verilen tasdiktir. Apostil işlemini biz yürütmeyiz; apostili, belgenizin düzenlendiği ülkedeki yetkili makamdan bizzat almanız gerekir. Biz yalnızca apostilli belgelerinizin yeminli çevirisini yaparız. Lahey Sözleşmesi’ne taraf olmayan ülkelerde apostil yerine konsolosluk tasdiki gerekebilir.',
    keywords: ['apostil', 'apostil islemi', 'apostil tasdik', 'yurt disi gecerli'],
  },
  {
    id: 'acil-teslimat-mumkun-mu',
    category: 'delivery',
    priority: 15,
    q: 'Acil teslimat mümkün mü?',
    a: 'Evet, birçok belge için acil teslimat seçeneği sunulur ve teslim süresi kısaltılır. Acil teslimat ek ücrete tabidir; belgenin uzunluğu ve diline göre uygunluğu değişebilir. Aciliyette de kalite kontrol adımları korunur.',
    keywords: ['acil teslimat', 'hizli teslim', 'ayni gun', 'express', 'acil'],
  },
  {
    id: 'odeme-nasil-yapilir',
    category: 'pricing',
    priority: 16,
    q: 'Ödeme nasıl yapılır?',
    a: 'Ödemeler kredi/banka kartı ve havale/EFT ile yapılabilir; kredi kartında taksit imkânı sunulabilir. Kurumsal müşterilere ayrıca vadeli (15-30 gün) fatura seçeneği sağlanır. Ödeme, ön fiyatı onayladıktan sonra alınır.',
    keywords: ['odeme', 'odeme yontemi', 'kredi karti', 'havale', 'eft', 'nasil odeme'],
  },
  {
    id: 'dosya-yuklemeden-fiyat',
    category: 'upload',
    priority: 17,
    q: 'Dosya yüklemeden fiyat alınabilir mi?',
    a: "Evet. Belgeniz yoksa 'Metin Gir' sekmesine metninizi yapıştırarak kelime sayısına göre ön fiyat alabilirsiniz.",
    keywords: ['dosyasiz fiyat', 'metin girerek', 'dosya yuklemeden', 'metin ile fiyat'],
  },
  {
    id: 'belgenin-formati-korunur-mu',
    category: 'delivery',
    priority: 18,
    q: 'Belgenin formatı korunur mu?',
    a: 'Mümkün olduğunca özgün sayfa düzeni, tablo ve biçim korunarak çeviri yapılır. Çıktı, ihtiyacınıza göre PDF veya düzenlenebilir Word (DOCX) formatında teslim edilebilir. Taranmış/görsel belgelerde birebir biçim yerine düzenli bir yerleşim sağlanır.',
    keywords: ['format', 'bicim', 'sayfa duzeni', 'word', 'pdf', 'format korunur'],
  },
  {
    id: 'teslim-sonrasi-destek',
    category: 'quality',
    priority: 19,
    q: 'Çeviri teslim edildikten sonra destek alabilir miyim?',
    a: 'Evet. Teslimden sonra kapsam içindeki düzeltmeler için revize desteği sunulur ve sorularınız için müşteri destek hattımıza ulaşabilirsiniz. Belgenizle ilgili ek talepleri e-posta veya WhatsApp üzerinden iletebilirsiniz.',
    keywords: ['teslim sonrasi destek', 'sonrasinda destek', 'yardim', 'destek'],
  },
  {
    id: 'cok-sayfali-yuksek-hacim',
    category: 'order',
    priority: 20,
    q: 'Çok sayfalı veya yüksek hacimli işler nasıl yönetilir?',
    a: 'Yüksek hacimli projeler planlanarak yürütülür; gerektiğinde birden fazla tercüman ve editör görev alır, terminoloji tutarlılığı için ortak sözlük kullanılır. Uzun projeler, talebinize göre parça parça (kısmi) teslim edilebilir. Kurumsal projelerde süreç hesap yöneticiniz tarafından koordine edilir.',
    keywords: ['cok sayfa', 'yuksek hacim', 'toplu is', 'buyuk proje', 'coklu belge'],
  },

  // ——— GENEL ———
  {
    id: 'tercumexpert-nedir',
    category: 'general',
    priority: 21,
    q: 'TercümExpert kimdir?',
    a: 'TercümExpert; yeminli tercüme, noter onaylı çeviri, hukuki, teknik, medikal ve akademik çeviri ile web/mobil lokalizasyon hizmetleri sunan çevrim içi bir çeviri hizmeti sağlayıcısıdır. Belgenizi yükleyip ön fiyatınızı alabilir, siparişinizi tamamen çevrim içi verebilirsiniz.',
    keywords: ['tercumexpert', 'kimdir', 'nedir', 'ceviri hizmeti', 'ne is yapar'],
  },
  {
    id: 'hangi-hizmetler',
    category: 'general',
    priority: 22,
    q: 'TercümExpert hangi hizmetleri sunar?',
    a: 'Yeminli ve noter onaylı tercüme, apostilli belgelerin çevirisi, hukuki, teknik, medikal ve akademik çeviri ile web ve mobil uygulama lokalizasyonu sunuyoruz. İhtiyacınıza uygun hizmeti Fiyat Hesapla ekranında seçebilirsiniz.',
    keywords: ['hizmetler', 'ne yapar', 'hizmet turleri', 'hangi hizmet'],
  },
  {
    id: 'kimler-hizmet-alabilir',
    category: 'general',
    priority: 23,
    q: 'Kimler hizmet alabilir?',
    a: 'Hem bireysel müşteriler hem de şirket ve kurumlar hizmet alabilir. Öğrenciden serbest çalışana, KOBİ’den büyük kurumlara kadar farklı ihtiyaçlara uygun çözümler sunulur.',
    keywords: ['kimler', 'bireysel', 'kurumsal', 'kim alabilir', 'sirket'],
  },
  {
    id: 'ofise-gelmek-gerekir-mi',
    category: 'general',
    priority: 24,
    q: 'Fiziksel ofise gelmek gerekir mi?',
    a: 'Firmamızın fiziksel bir ofisi bulunmamaktadır; hizmetlerimizi tamamen çevrim içi olarak sunuyoruz. Belgelerinizi güvenli yükleme yoluyla iletmeniz yeterlidir; teslimat dijital olarak, gerektiğinde kargoyla yapılır. Sorularınız için WhatsApp veya info@tercumexpert.com üzerinden bize ulaşabilirsiniz.',
    keywords: ['ofis', 'ofise gelme', 'sube', 'adres', 'gelmek zorunda'],
  },
  {
    id: 'surec-cevrimici-mi',
    category: 'general',
    priority: 25,
    q: 'Tüm süreç çevrim içi yürütülebilir mi?',
    a: 'Evet. Belge yükleme, fiyat onayı, ödeme ve dijital teslimatın tamamı çevrim içidir. Yalnızca ıslak imzalı fiziksel belge gerektiğinde kargo devreye girer.',
    keywords: ['online', 'cevrimici', 'internetten', 'uzaktan', 'her sey online'],
  },
  {
    id: 'yurt-disindan-hizmet',
    category: 'general',
    priority: 26,
    q: 'Yurt dışındaki müşteriler hizmet alabilir mi?',
    a: 'Evet. Süreç çevrim içi olduğundan yurt dışından da belge yükleyip sipariş verebilirsiniz. Dijital teslimat her yere yapılır; ıslak imzalı belge için yurt dışına kargo gönderimi de sağlanabilir.',
    keywords: ['yurt disi', 'yurtdisindan', 'farkli ulke', 'yurt disindan hizmet'],
  },
  {
    id: 'uyelik-zorunlu-mu',
    category: 'general',
    priority: 27,
    q: 'Hizmet almak için üyelik zorunlu mu?',
    a: 'Üyelik zorunlu değildir. Ancak fiyatı görüntülemek ve sipariş vermek için ad, soyad ve e-posta bilgilerinizi girip e-postanıza gelen doğrulama kodunu onaylamanız gerekir. Dilerseniz üyelik oluşturarak sipariş geçmişinizi de takip edebilirsiniz.',
    keywords: ['uyelik', 'uye olma', 'kayit', 'zorunlu mu', 'uyeliksiz'],
  },
  {
    id: 'uye-olmadan-fiyat',
    category: 'general',
    priority: 28,
    q: 'Üye olmadan fiyat alınabilir mi?',
    a: 'Evet, tam üyelik oluşturmadan da fiyat alabilirsiniz; yalnızca ad, soyad ve e-posta doğrulaması gerekir. Doğrulamayı tamamlamayan kullanıcılar fiyatı göremez ve sipariş veremez.',
    keywords: ['uye olmadan', 'uyeliksiz fiyat', 'dogrulama kodu', 'e-posta dogrulama'],
  },
  {
    id: 'siparis-oncesi-danismanlik',
    category: 'general',
    priority: 29,
    q: 'Sipariş vermeden önce danışmanlık alınabilir mi?',
    a: 'Evet. Hangi hizmete ihtiyacınız olduğundan emin değilseniz WhatsApp, e-posta veya yapay zekâ destekli sohbet asistanımız üzerinden bilgi alabilirsiniz. Belgenizin türüne göre uygun hizmeti ve süreci birlikte belirleriz.',
    keywords: ['danismanlik', 'bilgi alma', 'soru sorma', 'on gorusme'],
  },
  {
    id: 'musteri-temsilcisi',
    category: 'general',
    priority: 30,
    q: 'Müşteri temsilcisine nasıl ulaşılır?',
    a: 'Müşteri destek hattımıza WhatsApp veya e-posta üzerinden ulaşabilirsiniz. Sorularınız mesai saatleri içinde bir temsilci tarafından yanıtlanır; ayrıca yapay zekâ destekli sohbet asistanımız her zaman ilk yönlendirmeyi yapabilir.',
    keywords: ['musteri temsilcisi', 'destek', 'iletisim', 'ulasma', 'canli destek'],
  },
  {
    id: 'hangi-belgeler-cevrilebilir',
    category: 'general',
    priority: 31,
    q: 'Hangi belge türleri çevrilebilir?',
    a: 'Resmî ve kişisel belgelerden ticari, hukuki, teknik, medikal ve akademik metinlere kadar geniş bir yelpazede çeviri yapıyoruz. Diploma, sözleşme, rapor, kılavuz, web sitesi metni gibi birçok belge türü desteklenir.',
    keywords: ['belge turleri', 'hangi belgeler', 'evrak', 'ne cevrilir'],
  },
  {
    id: 'yapay-zeka-mi-insan-mi',
    category: 'general',
    priority: 32,
    q: 'Çeviriler insan tercümanlar tarafından mı yapılır?',
    a: 'Evet. Çevirileriniz baştan sona profesyonel insan tercümanlar tarafından yapılır. Tutarlılık ve terminoloji için profesyonel çeviri araçları (CAT tool) desteği kullanılır; ancak çevirinin tamamı uzman tercümanların işidir ve kalite kontrolünden geçer.',
    keywords: ['insan tercuman', 'cat tool', 'ceviri araci', 'makine cevirisi', 'kim cevirir'],
  },
  {
    id: 'el-yazili-belgeler',
    category: 'general',
    priority: 33,
    q: 'El yazılı veya okunması zor belgeler çevrilebilir mi?',
    a: 'El yazılı ve okunması güç belgeler, okunabilir olmak kaydıyla çevrilebilir. Okunamayan bölümler çeviride açıkça belirtilir ve gerektiğinde sizden daha net bir kopya istenir. Bu tür belgelerde fiyat, inceleme sonrası netleşir.',
    keywords: ['el yazisi', 'el yazili', 'okunmayan', 'net degil', 'okunmasi zor'],
  },
  {
    id: 'farkiniz-nedir',
    category: 'general',
    priority: 34,
    q: 'TercümExpert’in diğer çeviri hizmetlerinden farkı nedir?',
    a: 'Süreci uçtan uca çevrim içi yürütmemiz, otomatik ön fiyatlandırma, alanında uzman insan tercümanlar ve kalite kontrolü öne çıkan yönlerimizdir. Ayrıca ıslak imzalı belgeleri kapınıza kadar kargoyla ulaştırırız.',
    keywords: ['fark', 'avantaj', 'neden tercumexpert', 'farkiniz'],
  },

  // ——— SİPARİŞ SÜRECİ ———
  {
    id: 'siparis-nasil-verilir',
    category: 'order',
    priority: 35,
    q: 'Sipariş nasıl verilir?',
    a: 'Fiyat Hesapla ekranından belgenizi yükleyin veya metninizi girin, dil çifti ve hizmet türünü seçin ve ön fiyatı onaylayın. Onayın ardından siparişiniz oluşturulur.',
    keywords: ['siparis verme', 'nasil siparis', 'siparis olusturma'],
  },
  {
    id: 'siparis-icin-gerekli-bilgiler',
    category: 'order',
    priority: 36,
    q: 'Sipariş vermek için hangi bilgiler gerekir?',
    a: 'Çevrilecek belge veya metin, kaynak ve hedef dil, hizmet türü ve iletişim için ad-soyad ile e-posta bilgisi gerekir. Bu bilgilerle siparişinizi oluşturabilirsiniz.',
    keywords: ['gerekli bilgi', 'hangi bilgiler', 'siparis bilgileri'],
  },
  {
    id: 'dil-cifti-nasil-secilir',
    category: 'order',
    priority: 37,
    q: 'Dil çifti ve hizmet türü nasıl seçilir?',
    a: 'Fiyat Hesapla ekranında kaynak dili (belgenin dili), hedef dili (çeviri dili) ve hizmet türünü (yeminli, noter onaylı, teknik vb.) menüden seçersiniz. Emin değilseniz destek hattımız veya sohbet asistanımız doğru seçimde yönlendirir.',
    keywords: ['dil cifti secme', 'kaynak dil', 'hedef dil', 'hizmet turu secme'],
  },
  {
    id: 'bilgiler-degistirilebilir-mi',
    category: 'order',
    priority: 38,
    q: 'Sipariş oluşturduktan sonra bilgiler değiştirilebilir mi?',
    a: 'Çeviri başlamadan önce dil, hizmet türü veya belge gibi bilgiler güncellenebilir. Bunun için destek hattımıza en kısa sürede ulaşmanız yeterlidir; iş ilerledikçe değişiklik kapsamı sınırlanabilir.',
    keywords: ['bilgi degistirme', 'duzeltme', 'guncelleme siparis', 'yanlis dil', 'yanlis belge'],
  },
  {
    id: 'onaydan-once-iptal',
    category: 'order',
    priority: 39,
    q: 'Sipariş onaylanmadan önce iptal edilebilir mi?',
    a: 'Evet. Ödeme ve onay tamamlanmadan siparişinizi iptal edebilirsiniz; bu aşamada herhangi bir ücret alınmaz.',
    keywords: ['iptal', 'siparis iptali', 'vazgecme'],
  },
  {
    id: 'odeme-sonrasi-iptal',
    category: 'order',
    priority: 40,
    q: 'Ödeme sonrası sipariş iptal edilebilir mi?',
    a: 'Siparişiniz bir tercüman tarafından işleme alınmadıysa, sipariş sayfanızdan veya info@tercumexpert.com üzerinden iptal edebilirsiniz; ödemeniz, ödemeyi yaptığınız yönteme tam olarak iade edilir. Çeviri bir tercüman tarafından işleme alındıktan sonra, işin kişiye özel niteliği gereği iade yapılmaz.',
    keywords: ['odeme sonrasi iptal', 'iade', 'geri odeme'],
  },
  {
    id: 'siparis-durumu-takip',
    category: 'order',
    priority: 41,
    q: 'Siparişin durumu nereden takip edilir?',
    a: 'Siparişinizin durumu hakkında e-posta ile bilgilendirilirsiniz; üyelik oluşturduysanız hesabınızdan da takip edebilirsiniz. Ayrıca destek hattımızdan güncel durumu sorabilirsiniz.',
    keywords: ['siparis takip', 'durum', 'nerede takip', 'siparis durumu'],
  },
  {
    id: 'birden-fazla-belge',
    category: 'order',
    priority: 42,
    q: 'Aynı siparişte birden fazla belge veya hedef dil olabilir mi?',
    a: 'Evet, aynı siparişte birden fazla belge yükleyebilir ve aynı belgeyi birden fazla dile çevirtebilirsiniz. Toplam kelime sayısı ve her hedef dil ayrı çeviri olarak fiyatlandırılır; süreç tek talep üzerinden koordine edilir.',
    keywords: ['coklu belge', 'birden fazla dosya', 'coklu dil', 'birden fazla dil'],
  },
  {
    id: 'sonradan-dosya-eklenebilir',
    category: 'order',
    priority: 43,
    q: 'Siparişe sonradan yeni dosya eklenebilir mi?',
    a: 'Çeviri başlamadan yeni dosya eklenebilir; bu durumda fiyat, eklenen içeriğe göre güncellenir. İş ilerledikten sonra eklenen belgeler yeni bir kalem olarak değerlendirilebilir.',
    keywords: ['dosya ekleme', 'sonradan ekleme', 'yeni dosya'],
  },
  {
    id: 'eksik-belge-gonderilirse',
    category: 'order',
    priority: 44,
    q: 'Eksik belge gönderilirse ne olur?',
    a: 'Eksik sayfa veya belge fark edildiğinde sizden tamamlamanızı isteriz. Belgenin tüm sayfalarının yüklenmesi, çevirinin eksiksiz ve geçerli olması için önemlidir.',
    keywords: ['eksik belge', 'eksik sayfa', 'eksik evrak'],
  },
  {
    id: 'terminoloji-not-referans',
    category: 'order',
    priority: 45,
    q: 'Siparişe özel not, terminoloji veya referans dosya eklenebilir mi?',
    a: 'Evet. Sipariş sırasında özel talimat, tercih ettiğiniz terimler veya stil notu ekleyebilir; önceki çeviriler ve sözlük gibi referans dosyaları yükleyebilirsiniz. Bu bilgiler tercümana iletilir ve tutarlılık için kullanılır.',
    keywords: ['not ekleme', 'ozel talimat', 'terminoloji', 'referans dosya', 'sozluk'],
  },
  {
    id: 'eski-siparisler-goruntulenir',
    category: 'order',
    priority: 46,
    q: 'Eski siparişler ve dosyalara sonradan erişilebilir mi?',
    a: 'Üyelik oluşturduysanız geçmiş siparişlerinizi ve teslim dosyalarınızı hesabınızdan görüntüleyebilirsiniz. Üyeliksiz siparişlerde kayıtlarınıza e-posta üzerinden ulaşabilirsiniz; indirme bağlantılarının süresi dolduğunda destek hattımızdan yeni bağlantı talep edebilirsiniz.',
    keywords: ['eski siparis', 'siparis gecmisi', 'gecmis', 'dosyaya erisim'],
  },

  // ——— FİYATLANDIRMA VE ÖDEME ———
  {
    id: 'kelime-mi-sayfa-mi',
    category: 'pricing',
    priority: 47,
    q: 'Kelime başına mı, sayfa başına mı ücretlendirme yapılır?',
    a: 'Ücretlendirme genellikle kelime sayısı ve seçilen hizmete göre yapılır. Metin tabanlı belgelerde kelime sayısı otomatik çıkarılır; taranmış/görsel belgelerde sayı, inceleme sonrasında doğrulanır.',
    keywords: ['kelime basi', 'sayfa basi', 'ucretlendirme', 'nasil ucret'],
  },
  {
    id: 'sabit-baslangic-ucreti',
    category: 'pricing',
    priority: 48,
    q: 'Sabit başlangıç ücreti veya minimum tutar var mı?',
    a: 'Bazı hizmetlerde asgari bir hizmet bedeli uygulanabilir; kısa belgelerde bu asgari tutar geçerli olabilir. Nihai fiyat, belgenin içeriği ve seçtiğiniz hizmetlere göre belirlenir ve tüm kalemleri ön fiyat ekranında görebilirsiniz.',
    keywords: ['baslangic ucreti', 'minimum', 'sabit ucret', 'asgari tutar'],
  },
  {
    id: 'neler-fiyati-etkiler',
    category: 'pricing',
    priority: 49,
    q: 'Dil çifti, belge türü ve uzmanlık alanı fiyatı etkiler mi?',
    a: 'Evet. Dil çifti (özellikle nadir diller), belge türü ve uzmanlık alanı (hukuki, medikal, teknik vb.) terminoloji yoğunluğunu ve dolayısıyla fiyatı etkileyebilir. Yaygın dillerde fiyat daha öngörülebilirdir.',
    keywords: ['dil cifti fiyat', 'belge turu fiyat', 'uzmanlik fiyat', 'neden farkli fiyat'],
  },
  {
    id: 'yeminli-daha-pahali-mi',
    category: 'pricing',
    priority: 50,
    q: 'Yeminli tercüme daha mı pahalıdır?',
    a: 'Yeminli tercüme, çevirmenin onay ve sorumluluğu nedeniyle standart çeviriden farklı fiyatlanabilir. Kesin tutar, belge ve dil çiftine göre ön fiyat ekranında gösterilir.',
    keywords: ['yeminli fiyat', 'yeminli pahali mi', 'yeminli ucret'],
  },
  {
    id: 'noter-apostil-ucreti-dahil',
    category: 'pricing',
    priority: 51,
    q: 'Noter onayı ve apostil ücreti fiyata dahil midir?',
    a: 'Noter onayı, yetkili makamlarca yapılan ayrı bir işlemdir ve resmî tarifeye tabidir; bu masraf çeviri ücretinden ayrı gösterilir, resmî tarifeye bağlı olduğundan önceden kesin olmayabilir ve gerçekleşen tutar işlem sonrası bildirilir. Apostil işlemini ise biz yürütmeyiz; apostili yetkili makamdan bizzat sizin almanız gerekir, biz yalnızca apostilli belgenizin çevirisini yaparız.',
    keywords: ['noter ucreti', 'apostil ucreti', 'dahil mi', 'noter masraf', 'apostil masraf'],
  },
  {
    id: 'on-fiyat-nihai-fark',
    category: 'pricing',
    priority: 52,
    q: 'Ön fiyat ile nihai fiyat arasında fark olabilir mi?',
    a: 'Evet. Ekranda gördüğünüz otomatik hesap bir ön fiyattır. Kelime sayısı, okunabilirlik veya belge türüne bağlı inceleme sonrasında nihai fiyat netleşebilir. Onaylamadan önce nihai tutar size iletilir.',
    keywords: ['on fiyat', 'nihai fiyat', 'fiyat farki', 'kesin fiyat'],
  },
  {
    id: 'otomatik-kelime-sayimi',
    category: 'pricing',
    priority: 53,
    q: 'Kelime sayısı otomatik hesaplanır mı? Taranmış PDF’lerde nasıl olur?',
    a: 'Metin tabanlı belgelerde (Word, metin PDF’i, düz metin) kelime sayısı otomatik çıkarılır. Taranmış/görsel PDF ve fotoğraflarda otomatik sayım güvenilir olmayabilir; bu durumda sayı ekibimizce doğrulanır. Ön fiyat otomatik sayıma dayanır ve bağlayıcı değildir; sapma olursa nihai fiyat size onaylatılır.',
    keywords: ['kelime sayimi', 'otomatik sayim', 'taranmis pdf', 'gorsel pdf', 'sayim hatasi'],
  },
  {
    id: 'toplu-kurumsal-indirim',
    category: 'pricing',
    priority: 54,
    q: 'Toplu sipariş veya kurumsal müşteriler için indirim var mı?',
    a: 'Yüksek hacimli ve düzenli işlerde, özellikle kurumsal müşterilere hacme ve iş birliği koşullarına göre avantajlı fiyatlandırma ve vade seçenekleri sunulabilir. Detaylar için Kurumsal başvuru formunu kullanabilirsiniz.',
    keywords: ['toplu indirim', 'hacim indirimi', 'kurumsal fiyat', 'sirket fiyati'],
  },
  {
    id: 'ucretsiz-teklif',
    category: 'pricing',
    priority: 55,
    q: 'Ücretsiz fiyat teklifi alınabilir mi? Teklif ne kadar geçerlidir?',
    a: 'Ön fiyat teklifi ücretsizdir; belgenizi yükleyip veya metni girdiğinizde teklifi anında görürsünüz. Teklifler, koşullar (belge içeriği/kapsam) değişmediği sürece kısa bir süre için geçerlidir.',
    keywords: ['ucretsiz teklif', 'bedava fiyat', 'teklif suresi', 'gecerlilik'],
  },
  {
    id: 'fatura-kesiliyor-mu',
    category: 'pricing',
    priority: 56,
    q: 'Fatura kesiliyor mu? Bireysel ve kurumsal fatura düzenlenebilir mi?',
    a: 'Evet. Hizmet karşılığında fatura düzenlenir; bireysel veya kurumsal fatura talep edebilirsiniz. Kurumsal müşterilere aylık toplu faturalama da sunulabilir. Vergiler yürürlükteki mevzuata göre uygulanır.',
    keywords: ['fatura', 'fatura kesme', 'kdv', 'kurumsal fatura', 'bireysel fatura'],
  },
  {
    id: 'taksit-secenegi',
    category: 'pricing',
    priority: 57,
    q: 'Taksit seçeneği var mı?',
    a: 'Kredi kartıyla ödemede taksit imkânı sunulabilir. Uygun taksit seçenekleri ödeme adımında gösterilir.',
    keywords: ['taksit', 'taksitli odeme'],
  },
  {
    id: 'kurumsal-vadeli-odeme',
    category: 'pricing',
    priority: 58,
    q: 'Kurumsal müşterilere vadeli ödeme sunulur mu?',
    a: 'Evet. Kurumsal müşterilere 15-30 güne kadar vade ve aylık faturalama seçenekleri sunulabilir. Koşullar, kurumsal iş birliği kapsamında belirlenir.',
    keywords: ['vadeli odeme', 'vade', 'kurumsal odeme'],
  },
  {
    id: 'odeme-yapilmadan-baslar-mi',
    category: 'pricing',
    priority: 59,
    q: 'Ödeme yapılmadan çeviri başlar mı?',
    a: 'Standart siparişlerde çeviri, ödemenin (veya kurumsal vade onayının) alınmasının ardından başlar. Kurumsal anlaşmalarda süreç, sözleşmeye göre işleyebilir.',
    keywords: ['on odeme', 'odeme oncesi', 'pesin', 'odeme yapilmadan'],
  },
  {
    id: 'iade-sureci',
    category: 'pricing',
    priority: 60,
    q: 'İptal edilen siparişlerde ücret iadesi yapılır mı?',
    a: 'Siparişiniz bir tercüman tarafından işleme alınmadan iptal edilirse, ödemeniz ödemeyi yaptığınız yönteme tam olarak iade edilir. Çeviri bir tercüman tarafından işleme alındıktan sonra, işin kişiye özel niteliği gereği iade yapılmaz. Mükerrer veya hatalı çekim gibi durumlarda fazla tutar iade edilir.',
    keywords: ['iade', 'ucret iadesi', 'geri odeme', 'iptal iade'],
  },

  // ——— DOSYA YÜKLEME ———
  {
    id: 'hangi-formatlar',
    category: 'upload',
    priority: 61,
    q: 'Hangi dosya formatları desteklenir?',
    a: "Word (DOC/DOCX), PDF, düz metin (TXT), Excel, PowerPoint ve yaygın görsel formatları (JPG, PNG) dâhil 50'den fazla format kabul edilir. Metin tabanlı belgelerde kelime sayısı otomatik çıkarılır.",
    keywords: ['format', 'dosya formati', 'desteklenen formatlar', 'pdf', 'doc', 'docx', 'txt'],
  },
  {
    id: 'taranmis-fotograf-belge',
    category: 'upload',
    priority: 62,
    q: 'Taranmış veya fotoğrafı çekilmiş belge kabul edilir mi?',
    a: 'Evet. Taranmış belgeler ve telefonla çekilmiş net fotoğraflar kabul edilir. Okunabilirlik önemlidir; mühür, kaşe ve imzaların görünür olması gerekir. Görsellerde metin otomatik okunamayabileceğinden kelime sayısı ekibimizce belirlenir.',
    keywords: ['taranmis belge', 'fotograf belge', 'telefonla cekilen', 'gorsel yukleme', 'resim'],
  },
  {
    id: 'birden-fazla-dosya-yukleme',
    category: 'upload',
    priority: 63,
    q: 'Birden fazla dosya aynı anda yüklenebilir mi?',
    a: 'Evet, aynı anda birden fazla dosya yükleyebilirsiniz. Toplam içerik üzerinden fiyat hesaplanır.',
    keywords: ['coklu yukleme', 'birden fazla dosya', 'toplu yukleme'],
  },
  {
    id: 'dosya-boyutu-siniri',
    category: 'upload',
    priority: 64,
    q: 'Dosya boyutu sınırı var mı? Büyük dosyalar nasıl gönderilir?',
    a: "Dosya başına yaklaşık 100 MB'a kadar yükleme yapabilirsiniz. Daha büyük dosyalar için destek hattımızla iletişime geçerek e-posta veya alternatif gönderim yöntemi sağlayabilirsiniz.",
    keywords: ['dosya boyutu', 'boyut siniri', 'buyuk dosya', '100 mb'],
  },
  {
    id: 'yuklenen-dosya-silinebilir',
    category: 'upload',
    priority: 65,
    q: 'Yüklenen dosya silinebilir veya değiştirilebilir mi?',
    a: 'Evet. Sipariş tamamlanmadan yüklediğiniz dosyayı kaldırabilir veya yenisiyle değiştirebilirsiniz.',
    keywords: ['dosya silme', 'dosya degistirme', 'yanlis dosya'],
  },
  {
    id: 'manuel-kelime-girisi',
    category: 'upload',
    priority: 66,
    q: 'Dosya yüklemeden manuel kelime sayısı girilebilir mi?',
    a: "Doğrudan bir sayı girmek yerine, metninizi 'Metin Gir' sekmesine yapıştırdığınızda kelime sayısı otomatik hesaplanır. Böylece dosyasız da ön fiyat alabilirsiniz.",
    keywords: ['manuel kelime', 'kelime girme', 'metin girme'],
  },
  {
    id: 'dosyalar-ne-kadar-saklanir',
    category: 'upload',
    priority: 67,
    q: 'Dosyalar ne kadar süre saklanır, silinmesi talep edilebilir mi?',
    a: 'Belgeleriniz yalnızca hizmetin gerektirdiği süre boyunca güvenli biçimde saklanır. Dilediğiniz zaman belgelerinizin silinmesini talep edebilirsiniz; bu talep KVKK kapsamındaki haklarınız doğrultusunda karşılanır.',
    keywords: ['saklama suresi', 'dosya saklama', 'dosya silme talebi', 'veri silme'],
  },
  {
    id: 'belgenin-tum-sayfalari',
    category: 'upload',
    priority: 68,
    q: 'Belgenin tüm sayfaları ve arka yüzleri yüklenmeli midir?',
    a: 'Evet. Çevirinin eksiksiz ve geçerli olması için belgenin tüm sayfalarını, varsa arka yüzlerini yüklemeniz gerekir. Mühür, kaşe ve imza alanlarının net görünmesi önemlidir.',
    keywords: ['tum sayfalar', 'arka yuz', 'eksiksiz belge', 'muhur kase'],
  },
  {
    id: 'imza-kase-cevrilir-mi',
    category: 'upload',
    priority: 69,
    q: 'Kaşe, mühür ve imzalar çevrilir mi?',
    a: 'Yeminli çeviride kaşe ve mühür üzerindeki okunabilir yazılar aktarılır; imzalar ise “imza vardır” şeklinde belirtilir. Okunamayan alanlar çeviride açıkça not edilir.',
    keywords: ['kase cevirisi', 'muhur ceviri', 'imza ceviri'],
  },
  {
    id: 'dosya-guvenli-mi-analiz',
    category: 'upload',
    priority: 70,
    q: 'Otomatik analiz sırasında belge içeriği güvende midir?',
    a: 'Evet. Belgeler şifreli biçimde aktarılır ve kelime sayımı gibi işlemler güvenli ortamda yapılır. İçeriğiniz üçüncü kişilerle paylaşılmaz.',
    keywords: ['analiz guvenli', 'icerik guvenligi', 'otomatik okuma'],
  },

  // ——— DİLLER VE DİL ÇİFTLERİ ———
  {
    id: '50-dil-ne-demek',
    category: 'languages',
    priority: 71,
    q: "50'den fazla dil desteği ne anlama gelir?",
    a: 'Yaygın dillerin yanı sıra daha az talep gören dillerde de çeviri yapabildiğimiz anlamına gelir. Nadir dillerde tercüman uygunluğu, teslim süresi ve fiyat siparişe göre ayrıca doğrulanır.',
    keywords: ['50 dil', 'nadir dil', 'dil destegi', 'kac dil'],
  },
  {
    id: 'yaygin-dil-ciftleri',
    category: 'languages',
    priority: 72,
    q: 'Türkçe-İngilizce, Almanca, Fransızca gibi dil çiftlerinde çeviri yapılır mı?',
    a: 'Evet. Türkçe ⇄ İngilizce, Almanca, Fransızca, İspanyolca, İtalyanca, Arapça ve Rusça gibi yaygın dil çiftlerinde her iki yönde de çeviri yapılır. Çince, Japonca gibi diller de desteklenir.',
    keywords: ['turkce ingilizce', 'ingilizce turkce', 'almanca', 'fransizca', 'dil cifti'],
  },
  {
    id: 'yabancidan-yabanciya',
    category: 'languages',
    priority: 73,
    q: 'Türkçe dışındaki iki yabancı dil arasında çeviri yapılabilir mi?',
    a: 'Evet, İngilizce-Fransızca gibi yabancı dilden yabancı dile çeviriler yapılabilir. Uygunluk ve süre, dil çiftine göre değerlendirilir.',
    keywords: ['yabanci yabanci', 'ingilizce fransizca', 'dil arasi'],
  },
  {
    id: 'nadir-dil',
    category: 'languages',
    priority: 74,
    q: 'Nadir veya listede olmayan diller için hizmet verilir mi?',
    a: 'Nadir dillerde de hizmet sunmaya çalışırız; ancak tercüman uygunluğu, süre ve fiyat bu dillerde ayrıca doğrulanır. Aradığınız dil listede yoksa destek hattımıza yazarak size özel teklif isteyebilirsiniz.',
    keywords: ['nadir dil', 'az kullanilan dil', 'listede olmayan', 'ozel dil'],
  },
  {
    id: 'dil-varyantlari',
    category: 'languages',
    priority: 75,
    q: 'Bölgesel dil varyantları (Amerikan/İngiliz İngilizcesi gibi) seçilebilir mi?',
    a: 'Evet, mümkün olduğunda hedef dilin bölgesel varyantını (ör. Amerikan/İngiliz İngilizcesi, Avrupa/Latin Amerika İspanyolcası) belirtebilirsiniz. Varyant belirtilmezse yaygın standart kullanılır.',
    keywords: ['varyant', 'amerikan ingilizce', 'bolgesel dil', 'lehce'],
  },
  {
    id: 'anadili-tercuman',
    category: 'languages',
    priority: 76,
    q: 'Ana dili hedef dil olan tercümanlarla mı çalışılır?',
    a: 'Mümkün olduğunca hedef dilde yetkin, alanında deneyimli tercümanlarla çalışırız. Amaç, doğal ve doğru bir çeviri sağlamaktır.',
    keywords: ['anadili tercuman', 'native', 'hedef dil uzmani'],
  },
  {
    id: 'osmanlica-eski-yazi',
    category: 'languages',
    priority: 77,
    q: 'Osmanlıca veya eski yazı belgeleri çevrilebilir mi?',
    a: 'Osmanlıca ve eski alfabeyle yazılmış belgeler, uzman uygunluğuna bağlı olarak çevrilebilir. Bu tür belgelerde süre ve fiyat, inceleme sonrası netleşir.',
    keywords: ['osmanlica', 'eski yazi', 'eski alfabe'],
  },
  {
    id: 'karisik-dilli-belge',
    category: 'languages',
    priority: 78,
    q: 'Bir belgede birden fazla dil varsa çevrilebilir mi?',
    a: 'Evet. Karışık dilli belgeler çevrilebilir; fiyat, her dildeki içerik miktarına göre belirlenir. İhtiyaç duyulan hedef dili belirtmeniz yeterlidir.',
    keywords: ['karisik dil', 'cok dilli belge', 'birden fazla dil belge'],
  },

  // ——— HİZMET TÜRLERİ ———
  {
    id: 'hangi-hizmeti-secmeliyim',
    category: 'services',
    priority: 79,
    q: 'Hangi hizmet türünü seçmeliyim?',
    a: 'Belgenizin nerede kullanılacağı hizmet seçimini belirler: resmî başvurular çoğunlukla yeminli, bazı işlemler noter onaylı veya apostilli çeviri gerektirir. Emin değilseniz destek hattımız veya sohbet asistanımız yönlendirir; nihai gereklilik ilgili kuruma göre değişir.',
    keywords: ['hangi hizmet', 'hizmet secimi', 'ne secmeliyim'],
  },
  {
    id: 'standart-yeminli-fark',
    category: 'services',
    priority: 80,
    q: 'Standart çeviri ile yeminli çeviri arasındaki fark nedir?',
    a: 'Standart çeviri, resmî onay içermeyen bilgi amaçlı çeviridir. Yeminli çeviri ise yeminli çevirmenin kaşe ve imzasıyla onaylanır ve resmî başvurularda istenir. Hangisinin gerektiği, belgenin sunulacağı kuruma bağlıdır.',
    keywords: ['standart yeminli', 'fark', 'normal ceviri', 'yeminli fark'],
  },
  {
    id: 'yeminli-noter-ayni-mi',
    category: 'services',
    priority: 81,
    q: 'Yeminli çeviri ile noter onaylı çeviri aynı şey midir?',
    a: 'Hayır. Yeminli çeviri, yeminli çevirmenin onayını taşır. Noter onaylı çeviri ise bu çevirinin ayrıca noter tarafından tasdik edilmesidir. Bazı kurumlar yalnızca yeminli çeviri isterken, bazıları noter onayı da talep eder.',
    keywords: ['yeminli noter fark', 'noter onayli', 'ayni mi'],
  },
  {
    id: 'hukuki-teknik-medikal',
    category: 'services',
    priority: 82,
    q: 'Hukuki, teknik ve medikal çevirilerde uzmanlık nasıl sağlanır?',
    a: 'Sözleşme, mahkeme, teknik doküman ve tıbbi belgeler; ilgili alanın terminolojisine hâkim, deneyimli tercümanlarca çevrilir. Terminoloji sözlükleri ve çeviri belleğiyle tutarlılık sağlanır, format ve birimler korunur ve çeviri kalite kontrolünden geçer.',
    keywords: ['hukuki ceviri', 'teknik ceviri', 'medikal ceviri', 'uzman tercuman', 'terminoloji'],
  },
  {
    id: 'akademik-bicim-korunur',
    category: 'services',
    priority: 83,
    q: 'Akademik çeviride kaynakça ve biçim korunur mu?',
    a: 'Evet. Tez, makale ve akademik metinlerde kaynakça düzeni, atıflar ve biçim mümkün olduğunca korunur; akademik üsluba uygun çeviri yapılır.',
    keywords: ['akademik ceviri', 'tez', 'makale', 'kaynakca'],
  },
  {
    id: 'lokalizasyon-nedir',
    category: 'services',
    priority: 84,
    q: 'Lokalizasyon sadece kelime çevirisi midir? SEO dikkate alınır mı?',
    a: 'Hayır. Lokalizasyon, metni hedef kültüre ve kullanıma uyarlamayı içerir; arayüz, tarih/para birimi biçimleri ve ifade tarzı hedef kitleye göre düzenlenir. Web sitesi lokalizasyonunda, talebinize göre hedef dildeki anahtar kelimeler ve SEO uyumu gözetilebilir.',
    keywords: ['lokalizasyon', 'yerellestirme', 'web ceviri', 'seo', 'uygulama ceviri'],
  },
  {
    id: 'kurumsal-marka-dili',
    category: 'services',
    priority: 85,
    q: 'Kurumsal metinlerde marka dili korunur mu?',
    a: 'Evet. Kurumsal çevirilerde terminoloji bankası ve stil kılavuzuyla marka diliniz ve ton tutarlılığınız korunur.',
    keywords: ['marka dili', 'kurumsal ton', 'stil kilavuzu'],
  },
  {
    id: 'vize-diploma-hangi-hizmet',
    category: 'services',
    priority: 86,
    q: 'Vize veya diploma gibi belgeler için hangi hizmet gerekir?',
    a: 'Vize başvuruları ve diploma çevirilerinde çoğunlukla yeminli tercüme temel gerekliliktir; bazı temsilcilikler veya kurumlar ek olarak noter onayı ya da apostil isteyebilir. Kesin gereklilik, başvurduğunuz konsolosluk veya kuruma göre değişir.',
    keywords: ['vize belgesi', 'diploma ceviri', 'transkript', 'konsolosluk', 'vize tercume'],
  },
  {
    id: 'belge-turu-listede-yok',
    category: 'services',
    priority: 87,
    q: 'Belge türüm listede yoksa ne seçmeliyim?',
    a: 'Belge türünüz listede yoksa en yakın seçeneği işaretleyip sipariş notuna açıklama ekleyebilirsiniz. Dilerseniz destek hattımız doğru seçimde yardımcı olur.',
    keywords: ['belge turu listede yok', 'diger belge', 'liste disi'],
  },

  // ——— TESLİMAT VE SÜRE ———
  {
    id: 'teslim-suresi-nasil-hesaplanir',
    category: 'delivery',
    priority: 88,
    q: 'Teslim süresi nasıl hesaplanır ve nerede gösterilir?',
    a: 'Süre; belgenin uzunluğu, dil çifti, hizmet türü ve ek hizmetlere göre hesaplanır ve Fiyat Hesapla ekranında tahmini teslim tarihi olarak gösterilir. Noter/apostil gereken işlemlerde bu süreye ek gün eklenebilir; teslim tarihi değişirse bilgilendirilirsiniz.',
    keywords: ['teslim suresi hesaplama', 'tahmini teslim', 'ne zaman hazir'],
  },
  {
    id: 'ayni-gun-teslimat',
    category: 'delivery',
    priority: 89,
    q: 'Aynı gün veya 24 saat içinde teslimat mümkün mü?',
    a: 'Kısa belgeler için hızlı/acil teslimat çoğu zaman mümkündür; uygunluk, belgenin uzunluğu ve diline göre değişir. Acil teslimatta da kalite kontrol adımları korunur ve seçenek ön fiyat ekranında ek kalem olarak gösterilir.',
    keywords: ['ayni gun', '24 saat', 'hizli teslimat', 'acil'],
  },
  {
    id: 'hafta-sonu-tatil',
    category: 'delivery',
    priority: 90,
    q: 'Hafta sonu veya mesai dışı siparişler ne zaman işleme alınır?',
    a: 'Belge yükleme, fiyat alma ve sipariş oluşturmayı günün her saati yapabilirsiniz. Mesai dışında ve tatil günlerinde verilen siparişler, ilk iş saatlerinde işleme alınır; tahmini teslim süresi buna göre gösterilir.',
    keywords: ['hafta sonu', 'tatil', 'mesai disi', 'gece siparis'],
  },
  {
    id: 'dijital-teslim-format',
    category: 'delivery',
    priority: 91,
    q: 'Dijital teslimat nasıl yapılır, hangi formatta alırım?',
    a: 'Tamamlanan çeviri, indirilebilir bir bağlantı veya e-posta yoluyla dijital olarak teslim edilir. İhtiyacınıza göre PDF veya düzenlenebilir Word (DOCX) formatında alabilirsiniz; özgün biçim mümkün olduğunca korunur.',
    keywords: ['dijital teslimat', 'word teslim', 'pdf teslim', 'indirme'],
  },
  {
    id: 'kargo-kapsam-takip',
    category: 'delivery',
    priority: 92,
    q: 'Kargo hangi bölgelere yapılır ve takip edilebilir mi?',
    a: 'Islak imzalı/kaşeli belgeler Türkiye geneline kargoyla gönderilir; talebinize göre yurt dışına da fiziksel gönderim yapılabilir. Kargo takip bilgisi sizinle paylaşılır ve gönderim süresi toplam teslim süresine eklenir.',
    keywords: ['kargo bolge', 'kargo takip', 'yurt disi kargo', 'kargo suresi'],
  },
  {
    id: 'kismi-teslimat',
    category: 'delivery',
    priority: 93,
    q: 'Uzun projeler parça parça (kısmi) teslim edilebilir mi?',
    a: 'Evet. Yüksek hacimli veya uzun projeler, talebinize göre bölümler hâlinde teslim edilebilir. Böylece belgelerinizi beklemeden kullanmaya başlayabilirsiniz.',
    keywords: ['kismi teslimat', 'parca parca', 'bolum teslim'],
  },

  // ——— YEMİNLİ TERCÜME ———
  {
    id: 'yeminli-tercuman-kim',
    category: 'sworn',
    priority: 94,
    q: 'Yeminli tercüman kimdir?',
    a: 'Yeminli tercüman, bir noter huzurunda yemin ederek çevirilerini imza ve kaşesiyle onaylama yetkisi kazanmış çevirmendir. Bu onay, çevirinin aslına uygunluğuna dair bir beyandır.',
    keywords: ['yeminli tercuman', 'yeminli cevirmen kim'],
  },
  {
    id: 'yeminli-ne-zaman-gerekli',
    category: 'sworn',
    priority: 95,
    q: 'Yeminli tercüme ne zaman gereklidir?',
    a: 'Resmî kurum, mahkeme, konsolosluk ve üniversite başvurularında sıklıkla yeminli tercüme istenir. Ancak her belge için zorunlu değildir; kesin gereklilik, belgeyi talep eden kuruma göre belirlenir.',
    keywords: ['yeminli ne zaman', 'yeminli gerekli mi', 'nerede istenir'],
  },
  {
    id: 'yeminli-nerede-gecerli',
    category: 'sworn',
    priority: 96,
    q: 'Yeminli tercüme mahkemede, konsoloslukta ve yurt dışında geçerli midir?',
    a: 'Yeminli tercüme, birçok resmî işlemde ve başvuruda kullanılabilir. Ancak bir kurumun belgeyi kabul koşulları kendi mevzuatına bağlıdır; özellikle yurt dışında noter onayı veya apostil de istenebilir. Kabul şartlarını ilgili kurumdan teyit etmeniz önerilir.',
    keywords: ['mahkeme', 'konsolosluk', 'yurt disi gecerli', 'universite basvuru'],
  },
  {
    id: 'dijital-imzali-yeminli',
    category: 'sworn',
    priority: 97,
    q: 'Dijital/e-imzalı yeminli tercüme yapılabilir mi?',
    a: 'Hayır. Yeminli tercüme, çevirmenin ıslak imzası ve kaşesiyle hazırlanır ve fiziksel olarak kargoyla teslim edilir.',
    keywords: ['e-imza', 'dijital yeminli', 'elektronik imza', 'islak imza', 'kase'],
  },
  {
    id: 'yeminli-orijinal-gerekir',
    category: 'sworn',
    priority: 98,
    q: 'Yeminli tercümede belgenin orijinali gerekir mi?',
    a: 'Çeviri çoğunlukla belgenin net bir kopyası (tarama/fotoğraf) üzerinden yapılabilir. Ancak noter onayı gerekiyorsa, ilgili işlemde belgenin aslı veya onaylı örneği istenebilir.',
    keywords: ['orijinal belge', 'asli gerekir mi', 'fotokopi yeminli'],
  },
  {
    id: 'yeminli-gecerlilik-suresi',
    category: 'sworn',
    priority: 99,
    q: 'Yeminli tercümenin geçerlilik süresi var mı?',
    a: 'Çevirinin kendisi süreyle sınırlı değildir; ancak bazı kurumlar güncel tarihli belge isteyebilir. Bu, belgeyi kabul edecek kurumun şartına bağlıdır.',
    keywords: ['gecerlilik suresi', 'yeminli sure', 'ne kadar gecerli'],
  },
  {
    id: 'kurum-belgeyi-kabul-etmezse',
    category: 'sworn',
    priority: 100,
    q: 'Kurum yeminli çeviriyi kabul etmezse ne yapılır?',
    a: 'Kabul şartları kurumdan kuruma değişebilir. Kurumun özel format veya onay talebi varsa bunu bize iletmeniz hâlinde gerekli düzenlemeyi yaparız. Nihai kabul kararı ilgili kuruma aittir.',
    keywords: ['kabul etmezse', 'kurum reddi', 'format talebi'],
  },

  // ——— NOTER VE APOSTİL ———
  {
    id: 'noter-onayli-nedir',
    category: 'notary',
    priority: 101,
    q: 'Noter onaylı tercüme nedir?',
    a: 'Noter onaylı tercüme, yeminli çevirinin ayrıca noter tarafından tasdik edilmesidir. Bu onay, çevirinin resmî geçerliliğini pekiştirir ve bazı kurumlarca talep edilir.',
    keywords: ['noter onayli tercume', 'noter tasdik', 'noter nedir'],
  },
  {
    id: 'noter-yeminli-fark',
    category: 'notary',
    priority: 102,
    q: 'Noter onayı ile yeminli tercüme arasındaki fark nedir?',
    a: 'Yeminli tercüme çevirmenin onayını, noter onayı ise bu çevirinin noter tarafından tasdikini ifade eder. Noter onayı, yeminli çevirinin üzerine eklenen ek bir resmî adımdır.',
    keywords: ['noter yeminli fark', 'tasdik farki'],
  },
  {
    id: 'notere-gitmem-gerekir-mi',
    category: 'notary',
    priority: 103,
    q: 'Noter işlemleri için notere gitmem gerekir mi?',
    a: 'Çoğu durumda noter işlemlerini sizin adınıza yürütebiliriz; her durumda notere bizzat gelmeniz gerekmez. Belgenin aslı gerekiyorsa bunu önceden bildiririz.',
    keywords: ['notere gitme', 'noter islemi', 'vekaleten noter'],
  },
  {
    id: 'apostil-nedir',
    category: 'notary',
    priority: 104,
    q: 'Apostil nedir ve noter onayından farkı nedir?',
    a: 'Apostil, bir resmî belgenin başka bir ülkede geçerli sayılması için yetkili makamca verilen uluslararası tasdiktir ve Lahey Sözleşmesi’ne taraf ülkeler arasında geçerlidir. Noter onayı ise ülke içindeki bir tasdik işlemidir; ikisi farklı amaçlara hizmet eder.',
    keywords: ['apostil nedir', 'apostil noter fark', 'lahey'],
  },
  {
    id: 'apostil-once-mi-ceviri-once-mi',
    category: 'notary',
    priority: 105,
    q: 'Apostil önce mi, çeviri önce mi yapılır?',
    a: 'Sıralama, belgenin türüne ve kullanılacağı ülkenin şartlarına göre değişir. Bazı durumlarda önce belgeye apostil alınır, sonra çeviri yapılır; bazılarında tersi geçerlidir. Doğru sırayı birlikte belirleyebiliriz.',
    keywords: ['apostil sirasi', 'once ceviri once apostil'],
  },
  {
    id: 'yabanci-belge-turkiye',
    category: 'notary',
    priority: 106,
    q: 'Yabancı belge Türkiye’de kullanılacaksa süreç nasıldır?',
    a: 'Yurt dışından gelen belge çoğunlukla önce ilgili ülkede apostillenir, ardından Türkiye’de yeminli çevirisi (gerekirse noter onayı) yapılır. Kesin süreç, belgeyi isteyen Türk kurumuna göre değişir.',
    keywords: ['yabanci belge turkiye', 'gelen belge', 'yurt disindan belge'],
  },
  {
    id: 'turk-belge-yurt-disi',
    category: 'notary',
    priority: 107,
    q: 'Türk belgesi yurt dışında kullanılacaksa süreç nasıldır?',
    a: 'Türkiye’de düzenlenen belgeye çoğunlukla apostil alınır ve hedef dile yeminli çevirisi yapılır. Hedef ülke Lahey Sözleşmesi’ne taraf değilse apostil yerine konsolosluk tasdiki gerekebilir.',
    keywords: ['turk belge yurt disi', 'giden belge', 'konsolosluk tasdiki'],
  },
  {
    id: 'hangi-onay-gerekli-bilinmiyor',
    category: 'notary',
    priority: 109,
    q: 'Noter veya apostil gerekip gerekmediği nasıl öğrenilir?',
    a: 'En güvenilir yol, belgeyi talep eden kuruma sormaktır. Dilerseniz destek hattımız yaygın uygulamalar konusunda yol gösterir; ancak kesin gereklilik, kuruma ve ülkeye göre değişir.',
    keywords: ['hangi onay', 'onay gerekli mi', 'noter mi apostil mi'],
  },
  {
    id: 'kesin-kabul-garantisi',
    category: 'notary',
    priority: 110,
    q: 'TercümExpert kesin kabul garantisi verir mi?',
    a: 'Çevirinin ve onayların doğru ve eksiksiz hazırlanmasını sağlarız; ancak belgenin kabulüne ilişkin şartlar, belgeyi talep eden kurum tarafından belirlenir. Bu nedenle koşulsuz kabul garantisi verilemez; kurumun özel taleplerini bize iletirseniz gerekli düzenlemeyi yaparız.',
    keywords: ['kabul garantisi', 'kesin kabul', 'garanti'],
  },

  // ——— KALİTE VE REVİZE ———
  {
    id: 'tercumanlar-nasil-secilir',
    category: 'quality',
    priority: 111,
    q: 'Tercümanlar nasıl seçilir ve uzmanlıkları nasıl belirlenir?',
    a: 'Tercümanlar, dil çifti ve belgenin uzmanlık alanına göre belirlenir; hukuki belge hukuk, medikal belge sağlık alanında deneyimli bir çevirmene atanır. Alan deneyimi ve dil yetkinliği gözetilerek en uygun çevirmen görevlendirilir.',
    keywords: ['tercuman secimi', 'cevirmen nasil', 'uzmanlik', 'alan uzmani'],
  },
  {
    id: 'kalite-kontrol',
    category: 'quality',
    priority: 112,
    q: 'Çeviri kalite kontrolden geçer mi?',
    a: 'Evet. Çeviriler; yazım, terminoloji, sayı/isim/tarih tutarlılığı ve biçim açısından kontrol edilir. Belgenin türüne ve hizmet düzeyine göre bağımsız bir editör/son okuma adımı uygulanabilir.',
    keywords: ['kalite kontrol', 'son okuma', 'editor', 'kontrol'],
  },
  {
    id: 'ceviri-bellegi',
    category: 'quality',
    priority: 113,
    q: 'Çeviri belleği veya terminoloji listesi kullanılır mı?',
    a: 'Evet, özellikle teknik ve kurumsal projelerde çeviri belleği ve terminoloji listeleri kullanılarak tutarlılık sağlanır. Kendi terim listenizi de paylaşabilirsiniz; önceki projelerdeki terminoloji korunur.',
    keywords: ['ceviri bellegi', 'terminoloji listesi', 'tutarlilik'],
  },
  {
    id: 'revize-kapsami',
    category: 'quality',
    priority: 114,
    q: 'Revize hangi durumları kapsar ve ne zaman talep edilir?',
    a: 'Revize; çeviri hatası, yazım, tutarsızlık ve eksik aktarım gibi durumları kapsar. Kaynak metnin sonradan değiştirilmesi veya yeni içerik eklenmesi yeni bir iş sayılabilir. Revize talebinizi teslimden sonra makul bir süre içinde e-posta veya WhatsApp ile iletmeniz önerilir.',
    keywords: ['revize kapsam', 'duzeltme kapsami', 'revize suresi', 'ne zaman revize'],
  },
  {
    id: 'tercuman-degisikligi',
    category: 'quality',
    priority: 115,
    q: 'Çeviriden memnun kalmazsam ne olur, tercüman değiştirilebilir mi?',
    a: 'Çeviriden memnun kalmazsanız durumu değerlendirir, gerektiğinde farklı bir tercüman veya editörle düzeltme sağlarız. Amaç, sonucun beklentinizi karşılamasıdır.',
    keywords: ['tercuman degisikligi', 'memnun kalmama', 'begenmedim'],
  },
  {
    id: 'dogruluk-garanti',
    category: 'quality',
    priority: 116,
    q: 'Çevirinin doğruluğu garanti edilir mi?',
    a: 'Çevirilerinizi uzman tercümanlar hazırlar ve kalite kontrolünden geçiririz; doğruluk için gereken özeni gösteririz. Yine de belgenin resmî kabul şartları, belgeyi talep eden kuruma göre değişebilir.',
    keywords: ['dogruluk garanti', 'kalite garanti', 'guvence'],
  },
  {
    id: 'makine-cevirisi-kullaniliyor',
    category: 'quality',
    priority: 117,
    q: 'Tamamen otomatik/makine çevirisi kullanılıyor mu?',
    a: 'Hayır. Çeviriler baştan sona profesyonel insan tercümanlar tarafından yapılır; makineye bırakılan otomatik çeviri sunulmaz. Tutarlılık için yalnızca profesyonel çeviri araçları (CAT tool) desteği kullanılır. Yeminli çevirilerde çevirmenin kaşe ve imzasıyla aslına uygunluk beyanı yer alır.',
    keywords: ['makine cevirisi', 'otomatik ceviri', 'ai ceviri', 'ceviri beyani'],
  },

  // ——— GİZLİLİK VE GÜVENLİK ———
  {
    id: 'dosyalari-kimler-gorur',
    category: 'privacy',
    priority: 118,
    q: 'Yüklenen dosyaları kimler görebilir, üçüncü kişilerle paylaşılır mı?',
    a: 'Dosyalarınıza yalnızca siparişinizde görevli tercüman ve ilgili ekip erişebilir. Belgeleriniz, hizmetin gerektirdiği durumlar dışında üçüncü kişilerle paylaşılmaz ve pazarlama amacıyla kullanılmaz.',
    keywords: ['kimler gorur', 'erisim', 'ucuncu kisi', 'paylasim'],
  },
  {
    id: 'nda-imzalanabilir',
    category: 'privacy',
    priority: 119,
    q: 'Gizlilik sözleşmesi (NDA) imzalanabilir mi?',
    a: 'Evet. Özellikle kurumsal projelerde talebinize göre gizlilik sözleşmesi (NDA) düzenlenebilir. Tercümanlarımız da gizlilik yükümlülüğüne tabidir.',
    keywords: ['nda', 'gizlilik sozlesmesi', 'gizlilik anlasmasi'],
  },
  {
    id: 'kvkk-uyumlu',
    category: 'privacy',
    priority: 120,
    q: 'KVKK’ya uygun çalışılıyor mu, kişisel veriler nasıl korunur?',
    a: 'Evet. Kişisel verileriniz KVKK’ya uygun süreçlerle işlenir; yalnızca hizmetin gerektirdiği ölçüde kullanılır ve güvenli biçimde saklanır. Verilerinizi uygun güvenlik tedbirleriyle korumayı esas alırız.',
    keywords: ['kvkk', 'kisisel veri', 'veri koruma', 'kvkk uyumlu'],
  },
  {
    id: 'sifreli-aktarim',
    category: 'privacy',
    priority: 121,
    q: 'Dosyalar şifreli olarak mı aktarılır?',
    a: 'Evet. Dosyalarınız şifreli bağlantı üzerinden aktarılır ve güvenli ortamda işlenir. Amacımız verilerinizi uygun güvenlik tedbirleriyle korumaktır.',
    keywords: ['sifreli', 'guvenli aktarim', 'sifreleme'],
  },
  {
    id: 'odeme-bilgileri-saklanir',
    category: 'privacy',
    priority: 122,
    q: 'Ödeme/kredi kartı bilgileri saklanır mı?',
    a: 'Kart bilgileriniz TercümExpert tarafından saklanmaz; ödeme işlemleri güvenli ödeme altyapısı üzerinden yürütülür.',
    keywords: ['odeme bilgisi', 'kredi karti guvenli', 'kart saklama'],
  },
  {
    id: 'belgeler-ai-egitimi',
    category: 'privacy',
    priority: 123,
    q: 'Belgelerim model eğitimi için kullanılır mı?',
    a: 'Hayır. Belgeleriniz yalnızca sizin siparişiniz için kullanılır; herhangi bir model eğitimi amacıyla veya dış sistemlerle paylaşılmaz. Çeviriniz insan tercümanlar tarafından gizlilik esasıyla hazırlanır.',
    keywords: ['veri egitimi', 'model egitimi', 'veri kullanimi', 'belge gizlilik'],
  },
  {
    id: 'saglik-kimlik-guvenli',
    category: 'privacy',
    priority: 124,
    q: 'Kimlik, pasaport veya sağlık gibi hassas belgeler güvenli midir?',
    a: 'Evet. Hassas belgeler de dâhil tüm dosyalarınız gizlilik esasıyla, KVKK’ya uygun ve şifreli biçimde işlenir. Erişim yalnızca görevli ekiple sınırlıdır; yüksek gizlilik gerektiren belgeler için NDA ve sınırlı erişim gibi ek tedbirler uygulanabilir.',
    keywords: ['kimlik guvenli', 'pasaport', 'saglik verisi', 'hassas belge'],
  },
  {
    id: 'hesap-silinince-belgeler',
    category: 'privacy',
    priority: 125,
    q: 'Hesap silindiğinde veya talep edildiğinde belgeler silinir mi?',
    a: 'Talebiniz üzerine belgeleriniz ve kişisel verileriniz, yasal saklama yükümlülükleri saklı kalmak kaydıyla silinir. Hesap silme veya veri silme talebinizi destek hattımıza iletebilirsiniz.',
    keywords: ['hesap silme', 'veri silme', 'belge silme'],
  },

  // ——— KURUMSAL HİZMETLER ———
  {
    id: 'kurumsal-hesap-nasil',
    category: 'corporate',
    priority: 126,
    q: 'Kurumsal hesap nasıl açılır, başvuru sonrası ne olur?',
    a: 'Kurumsal sayfasındaki başvuru formunu doldurmanız yeterlidir; ekibimiz genellikle 1 iş günü içinde sizinle iletişime geçer, ihtiyaçlarınızı değerlendirir ve size özel koşulları belirler.',
    keywords: ['kurumsal hesap', 'sirket hesabi', 'kurumsal basvuru', 'basvuru sonrasi'],
  },
  {
    id: 'sirket-adina-siparis',
    category: 'corporate',
    priority: 127,
    q: 'Şirket adına sipariş verilebilir mi?',
    a: 'Evet. Şirket bilgilerinizle sipariş verebilir, kurumsal fatura ve gerektiğinde vade seçeneklerinden yararlanabilirsiniz.',
    keywords: ['sirket adina', 'kurumsal siparis'],
  },
  {
    id: 'ozel-hesap-yoneticisi',
    category: 'corporate',
    priority: 128,
    q: 'Kurumsal müşterilere özel hesap yöneticisi atanır mı?',
    a: 'Kurumsal müşterilere, süreçlerini takip eden özel bir hesap yöneticisi atanabilir. Böylece taleplerinizi tek noktadan yönetebilir ve öncelikli destek alabilirsiniz.',
    keywords: ['hesap yoneticisi', 'ozel yonetici', 'kurumsal destek', 'oncelikli destek'],
  },
  {
    id: 'toplu-fatura',
    category: 'corporate',
    priority: 129,
    q: 'Aylık toplu fatura ve vade alınabilir mi?',
    a: 'Evet. Kurumsal müşterilere aylık toplu faturalama ve 15-30 güne kadar vade seçenekleri sunulabilir. Detaylar iş birliği kapsamında belirlenir.',
    keywords: ['toplu fatura', 'aylik fatura', 'vade', 'kurumsal odeme'],
  },
  {
    id: 'terminoloji-bankasi',
    category: 'corporate',
    priority: 130,
    q: 'Şirkete özel terminoloji bankası oluşturulur mu?',
    a: 'Evet. Kurumsal projelerde markanıza özel terminoloji bankası ve stil kılavuzu oluşturularak tüm çevirilerde marka diliniz ve tutarlılık korunur.',
    keywords: ['terminoloji bankasi', 'stil kilavuzu', 'kurumsal terminoloji'],
  },
  {
    id: 'sabit-tercuman',
    category: 'corporate',
    priority: 131,
    q: 'Düzenli projelerde aynı tercümanlarla çalışılabilir mi?',
    a: 'Evet. Düzenli kurumsal projelerde sabit bir tercüman/ekip havuzu oluşturularak süreklilik ve tutarlılık sağlanabilir.',
    keywords: ['sabit tercuman', 'ayni ekip', 'kurumsal ekip'],
  },
  {
    id: 'kurumsal-raporlama',
    category: 'corporate',
    priority: 132,
    q: 'Sipariş ve harcama raporu alınabilir mi?',
    a: 'Kurumsal müşterilere sipariş ve harcamalarına yönelik raporlama sunulabilir; ihtiyaç hâlinde departman bazlı ayrım yapılabilir. Kurumsal iş birliklerinde hizmet düzeyi (SLA) ve gizlilik (NDA) sözleşmeleri de düzenlenebilir.',
    keywords: ['raporlama', 'harcama raporu', 'siparis raporu', 'sla'],
  },
  {
    id: 'kucuk-isletme',
    category: 'corporate',
    priority: 133,
    q: 'Küçük işletmeler de kurumsal hizmet alabilir mi, hacim zorunlu mu?',
    a: 'Evet. Kurumsal hizmetlerden yararlanmak için belirli bir büyüklük veya asgari hacim şartı yoktur; küçük işletmeler de vade, terminoloji ve öncelikli destek gibi avantajlardan faydalanabilir.',
    keywords: ['kucuk isletme', 'kobi', 'hacim zorunlu', 'minimum hacim'],
  },
  {
    id: 'uluslararasi-sirket',
    category: 'corporate',
    priority: 134,
    q: 'Uluslararası şirketlere ve çok dilli projelere hizmet verilir mi?',
    a: 'Evet. Birden fazla ülke ve dil içeren projeler koordine edilerek yürütülebilir; terminoloji tutarlılığı merkezî olarak sağlanır. Kurumsal projelerde yeminli çeviri ve gerektiğinde noter onayı süreçleri de yürütülebilir.',
    keywords: ['uluslararasi sirket', 'cok dilli proje', 'kurumsal noter apostil'],
  },

  // ——— TEKNİK DESTEK ———
  {
    id: 'nasil-uye-olunur',
    category: 'support',
    priority: 135,
    q: 'Siteye nasıl üye olunur?',
    a: 'Üyelik için ad, soyad ve e-posta bilgilerinizi girip e-postanıza gelen doğrulama kodunu onaylamanız yeterlidir. Apple veya Google hesabınızla da hızlıca üye olabilirsiniz.',
    keywords: ['uye olma', 'kayit', 'uyelik olusturma'],
  },
  {
    id: 'giris-sifre-sorunu',
    category: 'support',
    priority: 136,
    q: 'Giriş yapılamıyorsa veya şifre unutulursa ne yapılır?',
    a: "Önce e-posta ve şifrenizi kontrol edin; şifrenizi unuttuysanız giriş ekranındaki 'Şifremi unuttum' bağlantısıyla e-postanıza sıfırlama talimatı gönderin. Sorun sürerse spam klasörünü kontrol edin veya destek hattımıza yazın.",
    keywords: ['giris yapilamiyor', 'sifre sifirlama', 'sifremi unuttum', 'parola', 'login'],
  },
  {
    id: 'dogrulama-epostasi-gelmezse',
    category: 'support',
    priority: 137,
    q: 'Doğrulama e-postası gelmezse ne yapılır?',
    a: 'Birkaç dakika bekleyip spam/gereksiz klasörünü kontrol edin ve kodu yeniden gönderin. E-posta adresinizi doğru yazdığınızdan emin olun; sorun sürerse destek hattımıza yazın.',
    keywords: ['dogrulama epostasi', 'kod gelmedi', 'e-posta gelmiyor', 'dogrulama kodu'],
  },
  {
    id: 'dosya-yuklenmiyor',
    category: 'support',
    priority: 138,
    q: 'Dosya yüklenmiyorsa veya desteklenmeyen dosya hatası alınırsa ne yapılır?',
    a: "Dosya boyutunu (100 MB'a kadar) ve formatını kontrol edin, sayfayı ve tarayıcınızı yenileyin. Format desteklenmiyorsa dosyayı PDF veya DOCX gibi bir formata dönüştürebilir ya da metni 'Metin Gir' sekmesine yapıştırabilirsiniz. Sorun sürerse destek hattımıza yazın.",
    keywords: ['dosya yuklenmiyor', 'yukleme hatasi', 'desteklenmeyen dosya', 'format hatasi'],
  },
  {
    id: 'kelime-sayisi-yanlis',
    category: 'support',
    priority: 139,
    q: 'Kelime sayısı yanlış görünüyorsa ne yapılır?',
    a: "Otomatik sayım özellikle taranmış/görsel belgelerde sapabilir. Doğru sonuç için metni 'Metin Gir' ile paylaşabilir veya siparişte not düşebilirsiniz; nihai sayı ekibimizce doğrulanır ve fiyat buna göre netleşir.",
    keywords: ['kelime yanlis', 'sayim hatasi', 'kelime sayisi hatali'],
  },
  {
    id: 'odeme-basarisiz',
    category: 'support',
    priority: 140,
    q: 'Ödeme başarısız olursa veya iki kez çekilirse ne yapılır?',
    a: 'Kart bilgilerinizi ve limitinizi kontrol edip tekrar deneyin; farklı bir yöntem (kart/havale) de kullanabilirsiniz. Tutar çekildiği hâlde sipariş oluşmadıysa veya mükerrer çekim olduysa, dekontunuzla birlikte destek hattımıza yazın; fazla tutar iade edilir.',
    keywords: ['odeme basarisiz', 'odeme hatasi', 'iki kez cekildi', 'mukerrer odeme'],
  },
  {
    id: 'teslim-dosyasi-inmiyor',
    category: 'support',
    priority: 141,
    q: 'Teslim dosyası indirilemiyorsa ne yapılır?',
    a: 'Bağlantıyı ve tarayıcınızı yenileyin; indirme bağlantısının süresi dolduysa destek hattımızdan yeni bağlantı talep edebilirsiniz.',
    keywords: ['dosya inmiyor', 'indirme sorunu', 'teslim indirilemiyor', 'baglanti suresi'],
  },
  {
    id: 'mobil-tarayici-destegi',
    category: 'support',
    priority: 142,
    q: 'Mobil cihazdan işlem yapılabilir mi, hangi tarayıcılar desteklenir?',
    a: 'Site mobil uyumludur; iPhone, Android telefon ve tabletlerden belge yükleyip sipariş verebilirsiniz. Güncel Chrome, Safari, Edge ve Firefox tarayıcılarıyla siteyi sorunsuz kullanabilirsiniz.',
    keywords: ['mobil', 'telefon', 'iphone android', 'tablet', 'tarayici', 'chrome safari'],
  },
  {
    id: 'ai-asistan-ne-yapar',
    category: 'support',
    priority: 143,
    q: 'Yapay zekâ destekli sohbet asistanı ne yapabilir?',
    a: 'Sohbet asistanı; süreç, hizmet türleri ve genel sorularınızda anında yönlendirme yapar ve sizi fiyat alma gibi doğru adımlara ulaştırır. Resmî kabul şartları ve hukuki gereklilikler (noter/apostil gibi) konusunda kesin ve bağlayıcı karar veremez; bu konularda ilgili kuruma danışmanız gerekir.',
    keywords: ['sohbet asistani', 'chatbot', 'ai asistan', 'chatbot fiyat'],
  },
  {
    id: 'insana-baglanma',
    category: 'support',
    priority: 144,
    q: 'İnsan müşteri temsilcisine nasıl bağlanılır?',
    a: 'Sohbet asistanı üzerinden talep ederek veya doğrudan WhatsApp ve e-posta yoluyla insan destek hattımıza ulaşabilirsiniz. Talepler mesai saatleri içinde yanıtlanır. Teknik sorunları ekran görüntüsüyle iletmeniz çözümü hızlandırır.',
    keywords: ['insana baglanma', 'musteri temsilcisi', 'canli destek', 'ekran goruntusu'],
  },
  {
    id: 'hesap-bilgileri-guncelleme',
    category: 'support',
    priority: 145,
    q: 'Hesap ve fatura bilgileri nasıl güncellenir, hesap nasıl silinir?',
    a: 'Üyeyseniz telefon, e-posta ve fatura bilgilerinizi hesap ayarlarınızdan güncelleyebilir, hesabınızın silinmesini de buradan veya destek hattımıza talep göndererek sağlayabilirsiniz. Talebiniz üzerine verileriniz, yasal yükümlülükler saklı kalmak kaydıyla silinir.',
    keywords: ['bilgi guncelleme', 'fatura bilgisi', 'hesap ayarlari', 'hesap silme'],
  },
  {
    id: 'bildirim-tercihleri',
    category: 'support',
    priority: 146,
    q: 'Sipariş bildirimleri nasıl çalışır, WhatsApp bildirimi alınabilir mi?',
    a: 'Sipariş durumu için e-posta bildirimleri gönderilir; tercihlerinize göre WhatsApp üzerinden de bilgilendirme sağlanabilir. Bildirim tercihlerinizi hesap ayarlarından veya destek hattımızdan düzenleyebilirsiniz.',
    keywords: ['bildirim', 'sms', 'whatsapp bildirim', 'e-posta bildirim', 'siparis bildirimi'],
  },
]
