/**
 * Fonte de dados das FAQ (português europeu). A lógica de preços/pagamento pode
 * mudar mais tarde (§13). Regras de honestidade: SEM alegações de ISO/certificação
 * não verificadas; não se subentende a existência de um escritório físico; não se
 * promete apoio humano 24/7; preservam-se as distinções entre tradução
 * ajuramentada / certificação notarial / apostila; não se garante a aceitação
 * institucional. `priority` = ordem de importância global (menor = mais acima). A
 * vista por categoria usa a mesma ordem, pelo que a ordenação dentro de cada
 * categoria deriva deste valor.
 */
import type { FaqCategory, FaqItem } from './faq-data'

export const FAQ_CATEGORIES_PT: FaqCategory[] = [
  { key: "general", label: "Geral" },
  { key: "order", label: "Processo de Encomenda" },
  { key: "pricing", label: "Preços e Pagamento" },
  { key: "upload", label: "Envio de Ficheiros" },
  { key: "languages", label: "Línguas e Pares de Línguas" },
  { key: "services", label: "Tipos de Serviço" },
  { key: "delivery", label: "Entrega e Prazos" },
  { key: "sworn", label: "Tradução Ajuramentada" },
  { key: "notary", label: "Certificação Notarial e Apostila" },
  { key: "quality", label: "Qualidade e Revisões" },
  { key: "privacy", label: "Privacidade e Segurança" },
  { key: "corporate", label: "Serviços Empresariais" },
  { key: "support", label: "Apoio Técnico" },
]

export const FAQ_ITEMS_PT: FaqItem[] = [
  // ——— TODOS: perguntas prioritárias ao longo do percurso do cliente ———
  {
    id: "nasil-fiyat-alirim",
    category: "pricing",
    priority: 1,
    q: "Como obtenho um orçamento?",
    a: "Aceda à página Calcular Preço e carregue o seu documento ou cole o seu texto; assim que selecionar o par de línguas e o tipo de serviço, o seu orçamento preliminar surge de imediato. O valor é calculado com base no par de línguas, no tipo de serviço, no número de palavras e nos serviços adicionais que escolher.",
    keywords: ["orçamento", "preço", "custo da tradução", "estimativa de preço", "pedir orçamento"],
  },
  {
    id: "dosya-nasil-yuklenir",
    category: "upload",
    priority: 2,
    q: "Como carrego o meu ficheiro?",
    a: "Na página Calcular Preço, abra o separador 'Carregar Ficheiro' e arraste e largue o seu documento ou selecione-o manualmente. Se não tiver um ficheiro, basta colar o seu texto no separador 'Introduzir Texto'. Nos ficheiros de texto, o sistema conta as palavras automaticamente.",
    keywords: ["carregar ficheiro", "enviar documento", "anexar ficheiro", "não consigo carregar", "como carregar"],
  },
  {
    id: "fiyatlandirma-neye-gore",
    category: "pricing",
    priority: 3,
    q: "Como é determinado o preço?",
    a: "O valor é definido com base no par de línguas, no tipo de serviço, no conteúdo do documento, no número de palavras, na área de especialidade e nos serviços adicionais que selecionar. O montante que vê no ecrã é um orçamento preliminar; o valor final é confirmado após a análise do documento.",
    keywords: ["preços", "como é definido o preço", "fatores de preço", "por palavra", "tarifas"],
  },
  {
    id: "teslim-suresi-ne-kadar",
    category: "delivery",
    priority: 4,
    q: "Qual é o prazo de entrega?",
    a: "O prazo depende da extensão do documento, do par de línguas, do tipo de serviço e dos serviços adicionais que selecionar. O ecrã de orçamento indica um prazo de entrega estimado específico para a sua encomenda. Este prazo pode ser reduzido com a opção de entrega urgente.",
    keywords: ["prazo de entrega", "tempo de entrega", "quantos dias", "quando é entregue", "quanto tempo"],
  },
  {
    id: "yeminli-tercume-nedir",
    category: "sworn",
    priority: 5,
    q: "O que é uma tradução ajuramentada?",
    a: "Uma tradução ajuramentada é uma tradução certificada por um tradutor ajuramentado com a sua assinatura e carimbo, declarando-a fiel e conforme ao original. É frequentemente exigida em processos oficiais. A sua obrigatoriedade depende da instituição que solicita o documento.",
    keywords: ["tradução ajuramentada", "tradução certificada", "tradução com carimbo", "tradução oficial", "o que é ajuramentada"],
  },
  {
    id: "hangi-dillerde-hizmet",
    category: "languages",
    priority: 6,
    q: "Em que línguas trabalham?",
    a: "Trabalhamos com o turco, bem como com o inglês, o alemão, o francês, o espanhol, o italiano, o árabe, o russo e mais de 50 línguas no total. Nas línguas raras, a disponibilidade de tradutor e o prazo de entrega são confirmados separadamente para cada encomenda.",
    keywords: ["línguas", "que línguas", "opções de línguas", "pares de línguas", "quantas línguas"],
  },
  {
    id: "noter-onayi-gerekir-mi",
    category: "notary",
    priority: 7,
    q: "É necessária certificação notarial?",
    a: "A certificação notarial não é obrigatória para todos os documentos; a sua necessidade depende da instituição que solicita o documento e da finalidade de utilização. Em alguns procedimentos basta uma tradução ajuramentada, ao passo que outros exigem também certificação notarial. Se não tiver a certeza de qual a certificação necessária, podemos orientá-lo.",
    keywords: ["certificação notarial", "certificação por notário", "documento notariado", "preciso de notário"],
  },
  {
    id: "siparis-nasil-ilerler",
    category: "order",
    priority: 8,
    q: "Como funciona o processo de encomenda?",
    a: "Assim que carregar o seu documento e aprovar o orçamento preliminar, a sua encomenda é criada e atribuída a um tradutor especializado na área relevante. A tradução passa por controlo de qualidade; se necessário, tratamos do processo de certificação notarial/apostila e o seu documento é entregue digitalmente e, quando necessário, por correio.",
    keywords: ["processo de encomenda", "como funciona", "etapas", "fluxo de trabalho"],
  },
  {
    id: "belgelerim-guvende-mi",
    category: "privacy",
    priority: 9,
    q: "Os meus documentos estão seguros?",
    a: "Sim. Os seus ficheiros só são vistos pela equipa que trabalha na sua encomenda e são tratados através de transferência encriptada e de processos em conformidade com a KVKK (lei turca de proteção de dados). Os seus documentos nunca são partilhados com terceiros e a confidencialidade é a nossa prioridade.",
    keywords: ["segurança", "confidencialidade", "segurança dos documentos", "segurança dos dados", "kvkk"],
  },
  {
    id: "cevirimi-kim-yapar",
    category: "quality",
    priority: 10,
    q: "Quem traduz o meu documento?",
    a: "As suas traduções são realizadas por tradutores humanos profissionais com experiência na área relevante. É atribuído um tradutor especialista consoante o tipo de documento, e todas as traduções passam por controlo de qualidade antes da entrega.",
    keywords: ["quem traduz", "tradutor", "tradutor humano", "linguista", "quem faz"],
  },
  {
    id: "revize-hakki-var-mi",
    category: "quality",
    priority: 11,
    q: "As revisões estão incluídas?",
    a: "Sim. Após a entrega de uma tradução, tem direito a solicitar revisões para correções dentro do âmbito inicial. Estão incluídas correções de ortografia, nomes, datas ou coerência. Alterar o texto de origem posteriormente ou acrescentar novo conteúdo pode ser considerado um trabalho novo.",
    keywords: ["revisões", "correções", "revisão", "refazer tradução", "política de revisões"],
  },
  {
    id: "fiziksel-teslimat-yapiliyor-mu",
    category: "delivery",
    priority: 12,
    q: "Fazem entrega física?",
    a: "Sim. Embora a entrega digital seja a norma, os documentos com assinatura manuscrita original e carimbo podem ser enviados para a sua morada por correio. Fazemos envios para toda a Turquia e, mediante pedido, para o estrangeiro. Se optar pela entrega por correio, o tempo de envio acresce ao prazo de entrega.",
    keywords: ["entrega física", "correio", "transportadora", "entrega na morada"],
  },
  {
    id: "kurumsal-ozel-sartlar",
    category: "corporate",
    priority: 13,
    q: "Existem condições especiais para clientes empresariais?",
    a: "Sim. Os clientes empresariais beneficiam de vantagens em encomendas de grande volume, opções de prazo de pagamento, gestão de terminologia e um gestor de conta dedicado. Para mais informações, preencha o formulário de candidatura na nossa página Empresas.",
    keywords: ["empresas", "empresarial", "condições para empresas", "encomenda em volume", "condições empresariais"],
  },
  {
    id: "apostil-nasil-yurutulur",
    category: "notary",
    priority: 14,
    q: "Como decorre o processo de apostila?",
    a: "A apostila é uma certificação emitida pela autoridade competente para que um documento seja reconhecido como válido no estrangeiro. Podemos tratar do processo em seu nome; o documento que necessita de apostila e a ordem dos passos dependem do país onde o documento será utilizado. Nos países que não são parte na Convenção de Haia, poderá ser necessária a certificação consular em vez da apostila.",
    keywords: ["apostila", "processo de apostila", "certificação apostila", "válido no estrangeiro"],
  },
  {
    id: "acil-teslimat-mumkun-mu",
    category: "delivery",
    priority: 15,
    q: "É possível entrega urgente?",
    a: "Sim, a entrega urgente está disponível para muitos documentos e reduz o prazo de entrega. A entrega urgente implica um custo adicional e a sua disponibilidade pode variar consoante a extensão e a língua do documento. As etapas de controlo de qualidade são mantidas mesmo nas encomendas urgentes.",
    keywords: ["entrega urgente", "entrega rápida", "no próprio dia", "expresso", "urgente"],
  },
  {
    id: "odeme-nasil-yapilir",
    category: "pricing",
    priority: 16,
    q: "Como faço o pagamento?",
    a: "Os pagamentos podem ser efetuados por cartão de crédito/débito ou por transferência bancária; podem estar disponíveis opções de pagamento a prestações no cartão de crédito. Os clientes empresariais dispõem ainda da opção de faturação com prazo de pagamento (15 a 30 dias). O pagamento é cobrado após aprovar o orçamento preliminar.",
    keywords: ["pagamento", "forma de pagamento", "cartão de crédito", "transferência bancária", "como pagar"],
  },
  {
    id: "dosya-yuklemeden-fiyat",
    category: "upload",
    priority: 17,
    q: "Posso obter um orçamento sem carregar um ficheiro?",
    a: "Sim. Se não tiver um ficheiro, cole o seu texto no separador 'Introduzir Texto' para obter um orçamento preliminar com base no número de palavras.",
    keywords: ["orçamento sem ficheiro", "orçamento a partir de texto", "sem carregar", "orçamento por texto"],
  },
  {
    id: "belgenin-formati-korunur-mu",
    category: "delivery",
    priority: 18,
    q: "A formatação do documento é preservada?",
    a: "Na medida do possível, mantemos na tradução a disposição de página, as tabelas e a formatação originais. Consoante as suas necessidades, o resultado pode ser entregue em PDF ou num ficheiro Word (DOCX) editável. Nos documentos digitalizados ou em imagem, disponibilizamos uma disposição limpa e organizada em vez de uma réplica exata.",
    keywords: ["formatação", "formato", "disposição de página", "word", "pdf", "formato preservado"],
  },
  {
    id: "teslim-sonrasi-destek",
    category: "quality",
    priority: 19,
    q: "Posso obter apoio depois de a tradução ser entregue?",
    a: "Sim. Após a entrega, disponibilizamos apoio de revisão para correções dentro do âmbito e pode contactar a nossa linha de apoio ao cliente com quaisquer questões. Pode enviar pedidos adicionais sobre o seu documento por correio eletrónico ou WhatsApp.",
    keywords: ["apoio após entrega", "depois da entrega", "ajuda", "apoio"],
  },
  {
    id: "cok-sayfali-yuksek-hacim",
    category: "order",
    priority: 20,
    q: "Como são geridos os projetos com muitas páginas ou de grande volume?",
    a: "Os projetos de grande volume são cuidadosamente planeados; quando necessário, participam vários tradutores e revisores e utiliza-se um glossário partilhado para garantir a coerência terminológica. Os projetos longos podem ser entregues por partes (entrega parcial), se preferir. Nos projetos empresariais, o processo é coordenado pelo seu gestor de conta.",
    keywords: ["muitas páginas", "grande volume", "trabalho em massa", "projeto extenso", "vários documentos"],
  },

  // ——— GERAL ———
  {
    id: "tercumexpert-nedir",
    category: "general",
    priority: 21,
    q: "O que é a TercümExpert?",
    a: "A TercümExpert é um prestador de serviços de tradução em linha que oferece tradução ajuramentada, tradução com certificação notarial, tradução jurídica, técnica, médica e académica, bem como localização web e móvel. Pode carregar o seu documento, obter um orçamento preliminar e efetuar a sua encomenda totalmente em linha.",
    keywords: ["tercumexpert", "o que é", "sobre", "serviço de tradução", "o que fazem"],
  },
  {
    id: "hangi-hizmetler",
    category: "general",
    priority: 22,
    q: "Que serviços oferece a TercümExpert?",
    a: "Oferecemos tradução ajuramentada e com certificação notarial, apoio no processo de apostila, tradução jurídica, técnica, médica e académica, bem como localização de sites e de aplicações móveis. Pode escolher o serviço adequado às suas necessidades no ecrã Calcular Preço.",
    keywords: ["serviços", "o que oferecem", "tipos de serviço", "que serviços"],
  },
  {
    id: "kimler-hizmet-alabilir",
    category: "general",
    priority: 23,
    q: "Quem pode utilizar os vossos serviços?",
    a: "Tanto os clientes particulares como as empresas e organizações podem utilizar os nossos serviços. De estudantes a trabalhadores independentes, de pequenas empresas a grandes organizações, oferecemos soluções adaptadas a diferentes necessidades.",
    keywords: ["quem pode utilizar", "particulares", "empresas", "organizações", "clientes"],
  },
  {
    id: "ofise-gelmek-gerekir-mi",
    category: "general",
    priority: 24,
    q: "É necessário deslocar-me a um escritório?",
    a: "Não. Todo o processo — obter orçamento, encomendar, pagar e receber — pode ser tratado em linha. Basta carregar e aprovar os seus documentos; não é necessário deslocar-se a qualquer lugar.",
    keywords: ["escritório", "presencial", "sucursal", "morada", "deslocação necessária"],
  },
  {
    id: "surec-cevrimici-mi",
    category: "general",
    priority: 25,
    q: "Todo o processo pode ser tratado em linha?",
    a: "Sim. O carregamento de documentos, a aprovação do orçamento, o pagamento e a entrega digital são totalmente em linha. O correio só é utilizado quando é necessário um documento físico com assinatura manuscrita original.",
    keywords: ["em linha", "totalmente online", "à distância", "internet", "tudo online"],
  },
  {
    id: "yurt-disindan-hizmet",
    category: "general",
    priority: 26,
    q: "Os clientes no estrangeiro podem utilizar os vossos serviços?",
    a: "Sim. Como o processo é em linha, pode carregar documentos e efetuar encomendas a partir do estrangeiro. A entrega digital está disponível para qualquer lugar e, no caso de documentos com assinatura manuscrita original, também podemos enviar por correio para o estrangeiro.",
    keywords: ["estrangeiro", "clientes internacionais", "fora do país", "a partir do estrangeiro"],
  },
  {
    id: "uyelik-zorunlu-mu",
    category: "general",
    priority: 27,
    q: "É obrigatório ter conta para utilizar os vossos serviços?",
    a: "Não é obrigatório ter conta. No entanto, para visualizar o preço e efetuar uma encomenda, tem de introduzir o nome, o apelido e o correio eletrónico e, em seguida, confirmar o código de verificação enviado para o seu e-mail. Se quiser, pode criar uma conta para acompanhar o seu histórico de encomendas.",
    keywords: ["conta", "registo", "inscrição", "obrigatório", "sem conta"],
  },
  {
    id: "uye-olmadan-fiyat",
    category: "general",
    priority: 28,
    q: "Posso obter um orçamento sem me registar?",
    a: "Sim, pode obter um orçamento sem criar uma conta completa; basta verificar o nome, o apelido e o correio eletrónico. Os utilizadores que não concluam a verificação não conseguem visualizar o preço nem efetuar uma encomenda.",
    keywords: ["orçamento sem conta", "sem registo", "código de verificação", "verificação de e-mail"],
  },
  {
    id: "siparis-oncesi-danismanlik",
    category: "general",
    priority: 29,
    q: "Posso obter aconselhamento antes de fazer uma encomenda?",
    a: "Sim. Se não tiver a certeza de qual o serviço de que necessita, pode obter informações através do WhatsApp, do correio eletrónico ou do nosso assistente de chat com apoio de inteligência artificial. Ajudamo-lo a determinar o serviço e o processo adequados consoante o tipo de documento.",
    keywords: ["aconselhamento", "consultoria", "colocar uma questão", "ajuda antes da encomenda"],
  },
  {
    id: "musteri-temsilcisi",
    category: "general",
    priority: 30,
    q: "Como contacto um representante de apoio ao cliente?",
    a: "Pode contactar a nossa linha de apoio ao cliente através do WhatsApp ou do correio eletrónico. As suas questões são respondidas por um representante durante o horário de expediente; o nosso assistente de chat com apoio de inteligência artificial também pode prestar uma primeira orientação a qualquer momento.",
    keywords: ["representante de apoio", "apoio", "contacto", "entrar em contacto", "apoio ao vivo"],
  },
  {
    id: "hangi-belgeler-cevrilebilir",
    category: "general",
    priority: 31,
    q: "Que tipos de documentos podem ser traduzidos?",
    a: "Traduzimos uma grande variedade, desde documentos oficiais e pessoais a textos comerciais, jurídicos, técnicos, médicos e académicos. São suportados muitos tipos de documentos, incluindo diplomas, contratos, relatórios, manuais e conteúdos de sites.",
    keywords: ["tipos de documentos", "que documentos", "documentação", "o que pode ser traduzido"],
  },
  {
    id: "yapay-zeka-mi-insan-mi",
    category: "general",
    priority: 32,
    q: "As traduções são feitas por tradutores humanos?",
    a: "Sim. As suas traduções são realizadas do início ao fim por tradutores humanos profissionais. Utilizam-se ferramentas CAT para apoiar a coerência e a terminologia, mas a totalidade da tradução é obra de tradutores especializados e passa por controlo de qualidade.",
    keywords: ["tradutor humano", "ferramenta cat", "ferramentas de tradução", "tradução automática", "quem traduz"],
  },
  {
    id: "el-yazili-belgeler",
    category: "general",
    priority: 33,
    q: "Podem ser traduzidos documentos manuscritos ou de difícil leitura?",
    a: "Os documentos manuscritos e de difícil leitura podem ser traduzidos desde que sejam legíveis. Quaisquer partes ilegíveis são claramente assinaladas na tradução e, se necessário, poderemos solicitar-lhe uma cópia mais nítida. Nestes documentos, o preço é confirmado após análise.",
    keywords: ["manuscrito", "escrita à mão", "ilegível", "pouco claro", "difícil de ler"],
  },
  {
    id: "farkiniz-nedir",
    category: "general",
    priority: 34,
    q: "O que distingue a TercümExpert de outros serviços de tradução?",
    a: "O nosso processo totalmente em linha, os orçamentos preliminares automáticos, os tradutores humanos especializados e o controlo de qualidade são os aspetos que se destacam. Além disso, entregamos os documentos com assinatura manuscrita original à sua porta por correio.",
    keywords: ["diferença", "vantagem", "porquê a tercumexpert", "o que vos distingue"],
  },

  // ——— PROCESSO DE ENCOMENDA ———
  {
    id: "siparis-nasil-verilir",
    category: "order",
    priority: 35,
    q: "Como faço uma encomenda?",
    a: "No ecrã Calcular Preço, carregue o seu documento ou introduza o seu texto, selecione o par de línguas e o tipo de serviço e aprove o orçamento preliminar. Após a aprovação, a sua encomenda é criada.",
    keywords: ["fazer encomenda", "como encomendar", "criar encomenda"],
  },
  {
    id: "siparis-icin-gerekli-bilgiler",
    category: "order",
    priority: 36,
    q: "Que informações são necessárias para fazer uma encomenda?",
    a: "São necessários o documento ou texto a traduzir, as línguas de origem e de destino, o tipo de serviço e o seu nome e correio eletrónico para contacto. Com estas informações, pode criar a sua encomenda.",
    keywords: ["informações necessárias", "o que é preciso", "dados da encomenda"],
  },
  {
    id: "dil-cifti-nasil-secilir",
    category: "order",
    priority: 37,
    q: "Como escolho o par de línguas e o tipo de serviço?",
    a: "No ecrã Calcular Preço, seleciona no menu a língua de origem (a língua do documento), a língua de destino (a língua da tradução) e o tipo de serviço (ajuramentada, com certificação notarial, técnica, etc.). Se tiver dúvidas, a nossa linha de apoio ou o assistente de chat podem orientá-lo na escolha correta.",
    keywords: ["escolher par de línguas", "língua de origem", "língua de destino", "selecionar serviço"],
  },
  {
    id: "bilgiler-degistirilebilir-mi",
    category: "order",
    priority: 38,
    q: "Posso alterar os dados depois de criar uma encomenda?",
    a: "Dados como a língua, o tipo de serviço ou o documento podem ser atualizados antes de a tradução começar. Basta contactar a nossa linha de apoio o mais rapidamente possível; assim que o trabalho estiver em curso, a margem para alterações pode ficar limitada.",
    keywords: ["alterar dados", "editar encomenda", "atualizar encomenda", "língua errada", "documento errado"],
  },
  {
    id: "onaydan-once-iptal",
    category: "order",
    priority: 39,
    q: "Posso cancelar uma encomenda antes de ser aprovada?",
    a: "Sim. Pode cancelar a sua encomenda antes de o pagamento e a aprovação estarem concluídos; nesta fase não é cobrado qualquer valor.",
    keywords: ["cancelar", "cancelar encomenda", "desistir"],
  },
  {
    id: "odeme-sonrasi-iptal",
    category: "order",
    priority: 40,
    q: "Uma encomenda pode ser cancelada após o pagamento?",
    a: "Se a tradução ainda não tiver começado, o cancelamento e o reembolso são geralmente possíveis. Se o trabalho já tiver começado, poderá ser aplicada uma cobrança parcial correspondente à parte concluída. Enviar o seu pedido de cancelamento o mais cedo possível torna o processo mais simples.",
    keywords: ["cancelar após pagamento", "reembolso", "devolução do dinheiro"],
  },
  {
    id: "siparis-durumu-takip",
    category: "order",
    priority: 41,
    q: "Onde posso acompanhar o estado da minha encomenda?",
    a: "É notificado sobre o estado da sua encomenda por correio eletrónico e, se tiver criado uma conta, também pode acompanhá-lo aí. Pode ainda pedir o estado mais recente à nossa linha de apoio.",
    keywords: ["acompanhar encomenda", "estado", "seguimento da encomenda", "estado da encomenda"],
  },
  {
    id: "birden-fazla-belge",
    category: "order",
    priority: 42,
    q: "Uma encomenda pode incluir vários documentos ou línguas de destino?",
    a: "Sim, pode carregar vários documentos numa única encomenda e mandar traduzir o mesmo documento para várias línguas. O número total de palavras e cada língua de destino são orçamentados como traduções distintas, e o processo é coordenado num único pedido.",
    keywords: ["vários documentos", "vários ficheiros", "várias línguas", "múltiplas línguas"],
  },
  {
    id: "sonradan-dosya-eklenebilir",
    category: "order",
    priority: 43,
    q: "Posso acrescentar um novo ficheiro a uma encomenda mais tarde?",
    a: "Pode acrescentar um novo ficheiro antes de a tradução começar; nesse caso, o preço é atualizado com base no conteúdo acrescentado. Os documentos acrescentados depois de o trabalho estar em curso podem ser tratados como uma nova rubrica.",
    keywords: ["acrescentar ficheiro", "adicionar mais tarde", "novo ficheiro"],
  },
  {
    id: "eksik-belge-gonderilirse",
    category: "order",
    priority: 44,
    q: "O que acontece se enviar um documento incompleto?",
    a: "Quando detetamos uma página ou documento em falta, pedimos-lhe que o complete. Carregar todas as páginas do documento é importante para que a tradução seja completa e válida.",
    keywords: ["documento incompleto", "página em falta", "documento em falta"],
  },
  {
    id: "terminoloji-not-referans",
    category: "order",
    priority: 45,
    q: "Posso acrescentar notas, terminologia ou ficheiros de referência específicos à encomenda?",
    a: "Sim. Durante a encomenda, pode acrescentar instruções especiais, termos preferenciais ou uma nota de estilo, e carregar ficheiros de referência como traduções anteriores e glossários. Estas informações são transmitidas ao tradutor e utilizadas para garantir a coerência.",
    keywords: ["acrescentar nota", "instruções especiais", "terminologia", "ficheiro de referência", "glossário"],
  },
  {
    id: "eski-siparisler-goruntulenir",
    category: "order",
    priority: 46,
    q: "Posso aceder mais tarde a encomendas e ficheiros anteriores?",
    a: "Se tiver criado uma conta, pode consultar aí as suas encomendas anteriores e os ficheiros entregues. Nas encomendas efetuadas sem conta, pode aceder aos seus registos por correio eletrónico; se uma ligação de transferência tiver expirado, pode solicitar uma nova à nossa linha de apoio.",
    keywords: ["encomendas anteriores", "histórico de encomendas", "encomendas passadas", "aceder a ficheiros"],
  },

  // ——— PREÇOS E PAGAMENTO ———
  {
    id: "kelime-mi-sayfa-mi",
    category: "pricing",
    priority: 47,
    q: "Cobram por palavra ou por página?",
    a: "O preço baseia-se normalmente no número de palavras e no serviço selecionado. Nos documentos de texto, o número de palavras é extraído automaticamente; nos documentos digitalizados ou em imagem, a contagem é confirmada após análise.",
    keywords: ["por palavra", "por página", "base de cálculo", "como é cobrado"],
  },
  {
    id: "sabit-baslangic-ucreti",
    category: "pricing",
    priority: 48,
    q: "Existe uma taxa inicial fixa ou um valor mínimo?",
    a: "Alguns serviços podem ter um valor mínimo de serviço, aplicável a documentos curtos. O preço final é determinado pelo conteúdo do documento e pelos serviços que selecionar, e pode ver todas as rubricas no ecrã de orçamento preliminar.",
    keywords: ["taxa inicial", "mínimo", "taxa fixa", "valor mínimo"],
  },
  {
    id: "neler-fiyati-etkiler",
    category: "pricing",
    priority: 49,
    q: "O par de línguas, o tipo de documento e a área de especialidade afetam o preço?",
    a: "Sim. O par de línguas (sobretudo línguas raras), o tipo de documento e a área de especialidade (jurídica, médica, técnica, etc.) podem influenciar a densidade terminológica e, por conseguinte, o preço. Nas línguas mais comuns, o preço é mais previsível.",
    keywords: ["preço do par de línguas", "preço por tipo de documento", "preço por especialidade", "porque variam os preços"],
  },
  {
    id: "yeminli-daha-pahali-mi",
    category: "pricing",
    priority: 50,
    q: "A tradução ajuramentada é mais cara?",
    a: "A tradução ajuramentada pode ter um preço diferente do da tradução padrão, devido à certificação e à responsabilidade do tradutor. O valor exato é apresentado no ecrã de orçamento preliminar, consoante o documento e o par de línguas.",
    keywords: ["preço da tradução ajuramentada", "custo ajuramentada", "ajuramentada é cara"],
  },
  {
    id: "noter-apostil-ucreti-dahil",
    category: "pricing",
    priority: 51,
    q: "As taxas de certificação notarial e de apostila estão incluídas no preço?",
    a: "A certificação notarial e a apostila são procedimentos distintos realizados pelas autoridades competentes e sujeitos a tarifas oficiais. Estes custos são apresentados em separado do valor da tradução; por seguirem uma tarifa oficial, podem não ser exatos à partida, sendo o valor efetivo confirmado após o procedimento.",
    keywords: ["taxa notarial", "taxa de apostila", "está incluído", "custo notarial", "custo da apostila"],
  },
  {
    id: "on-fiyat-nihai-fark",
    category: "pricing",
    priority: 52,
    q: "O orçamento preliminar pode diferir do preço final?",
    a: "Sim. O cálculo automático que vê no ecrã é um orçamento preliminar. Após uma análise baseada no número de palavras, na legibilidade ou no tipo de documento, o preço final pode ser confirmado. O valor final é-lhe comunicado antes de aprovar.",
    keywords: ["orçamento preliminar", "preço final", "diferença de preço", "preço exato"],
  },
  {
    id: "otomatik-kelime-sayimi",
    category: "pricing",
    priority: 53,
    q: "O número de palavras é calculado automaticamente? E nos PDF digitalizados?",
    a: "Nos documentos de texto (Word, PDF de texto, texto simples), o número de palavras é extraído automaticamente. Nos PDF digitalizados ou em imagem e nas fotografias, a contagem automática pode não ser fiável, pelo que a nossa equipa a confirma. O orçamento preliminar baseia-se na contagem automática e não é vinculativo; havendo divergência, o preço final é confirmado consigo.",
    keywords: ["contagem de palavras", "contagem automática", "pdf digitalizado", "pdf em imagem", "erro de contagem"],
  },
  {
    id: "toplu-kurumsal-indirim",
    category: "pricing",
    priority: 54,
    q: "Existem descontos para encomendas em volume ou clientes empresariais?",
    a: "Em trabalhos de grande volume e recorrentes, sobretudo para clientes empresariais, podemos oferecer preços vantajosos e opções de prazo de pagamento consoante o volume e as condições de colaboração. Para mais informações, utilize o formulário de candidatura Empresas.",
    keywords: ["desconto por volume", "desconto em quantidade", "preço para empresas", "tarifas empresariais"],
  },
  {
    id: "ucretsiz-teklif",
    category: "pricing",
    priority: 55,
    q: "Posso obter um orçamento gratuito e qual a sua validade?",
    a: "O orçamento preliminar é gratuito; vê-o de imediato ao carregar o seu documento ou ao introduzir o seu texto. Os orçamentos são válidos por um curto período, desde que as condições (conteúdo/âmbito do documento) não se alterem.",
    keywords: ["orçamento gratuito", "estimativa sem custo", "validade do orçamento", "quanto tempo é válido"],
  },
  {
    id: "fatura-kesiliyor-mu",
    category: "pricing",
    priority: 56,
    q: "Emitem fatura? Posso obter fatura em nome individual ou empresarial?",
    a: "Sim. É emitida fatura pelo serviço, podendo solicitar uma fatura individual ou empresarial. Aos clientes empresariais pode ainda ser oferecida a faturação mensal consolidada. Os impostos são aplicados de acordo com a legislação em vigor.",
    keywords: ["fatura", "faturação", "iva", "fatura empresarial", "fatura individual"],
  },
  {
    id: "taksit-secenegi",
    category: "pricing",
    priority: 57,
    q: "Existe opção de pagamento a prestações?",
    a: "Podem estar disponíveis opções de pagamento a prestações nos pagamentos com cartão de crédito. Os planos de prestações elegíveis são apresentados no passo de pagamento.",
    keywords: ["prestações", "pagamento a prestações", "pagar a prestações"],
  },
  {
    id: "kurumsal-vadeli-odeme",
    category: "pricing",
    priority: 58,
    q: "Oferecem prazos de pagamento a clientes empresariais?",
    a: "Sim. Aos clientes empresariais podem ser oferecidos prazos de pagamento até 15 a 30 dias e faturação mensal. As condições são definidas no âmbito do acordo empresarial.",
    keywords: ["prazo de pagamento", "pagamento a prazo", "pagamento empresarial"],
  },
  {
    id: "odeme-yapilmadan-baslar-mi",
    category: "pricing",
    priority: 59,
    q: "A tradução começa antes do pagamento?",
    a: "Nas encomendas padrão, a tradução começa depois de recebido o pagamento (ou a aprovação do prazo de pagamento empresarial). Nos acordos empresariais, o processo pode decorrer de acordo com o contrato.",
    keywords: ["pagamento antecipado", "antes do pagamento", "pagamento adiantado", "sem pagamento"],
  },
  {
    id: "iade-sureci",
    category: "pricing",
    priority: 60,
    q: "São feitos reembolsos em encomendas canceladas?",
    a: "Nas encomendas canceladas antes de a tradução começar, o pagamento é reembolsado. Se o trabalho já tiver começado, o valor restante pode ser reembolsado após dedução da parte concluída. Em situações como uma cobrança em duplicado, o valor excedente é reembolsado.",
    keywords: ["reembolso", "devolução do dinheiro", "reembolso por cancelamento", "restituição"],
  },

  // ——— ENVIO DE FICHEIROS ———
  {
    id: "hangi-formatlar",
    category: "upload",
    priority: 61,
    q: "Que formatos de ficheiro são suportados?",
    a: "Aceitamos mais de 50 formatos, incluindo Word (DOC/DOCX), PDF, texto simples (TXT), Excel, PowerPoint e formatos de imagem comuns (JPG, PNG). Nos documentos de texto, o número de palavras é extraído automaticamente.",
    keywords: ["formato de ficheiro", "formatos suportados", "pdf", "doc", "docx", "txt"],
  },
  {
    id: "taranmis-fotograf-belge",
    category: "upload",
    priority: 62,
    q: "Aceitam documentos digitalizados ou fotografados?",
    a: "Sim. São aceites documentos digitalizados e fotografias nítidas tiradas com o telemóvel. A legibilidade é importante; os selos, carimbos e assinaturas têm de estar visíveis. Como o texto nas imagens pode não ser lido automaticamente, a nossa equipa determina o número de palavras.",
    keywords: ["documento digitalizado", "fotografia do documento", "foto de telemóvel", "envio de imagem", "imagem"],
  },
  {
    id: "birden-fazla-dosya-yukleme",
    category: "upload",
    priority: 63,
    q: "Posso carregar vários ficheiros de uma só vez?",
    a: "Sim, pode carregar vários ficheiros em simultâneo. O preço é calculado com base no conteúdo total.",
    keywords: ["carregar vários", "vários ficheiros", "carregamento em massa"],
  },
  {
    id: "dosya-boyutu-siniri",
    category: "upload",
    priority: 64,
    q: "Existe um limite de tamanho de ficheiro? Como envio ficheiros grandes?",
    a: "Pode carregar até cerca de 100 MB por ficheiro. Para ficheiros maiores, contacte a nossa linha de apoio para combinar o envio por correio eletrónico ou por um método alternativo.",
    keywords: ["tamanho do ficheiro", "limite de tamanho", "ficheiro grande", "100 mb"],
  },
  {
    id: "yuklenen-dosya-silinebilir",
    category: "upload",
    priority: 65,
    q: "Posso eliminar ou substituir um ficheiro carregado?",
    a: "Sim. Antes de a encomenda estar concluída, pode remover o ficheiro que carregou ou substituí-lo por um novo.",
    keywords: ["eliminar ficheiro", "substituir ficheiro", "ficheiro errado"],
  },
  {
    id: "manuel-kelime-girisi",
    category: "upload",
    priority: 66,
    q: "Posso introduzir o número de palavras manualmente sem carregar um ficheiro?",
    a: "Em vez de introduzir um número diretamente, cole o seu texto no separador 'Introduzir Texto' e o número de palavras é calculado automaticamente. Assim, pode obter um orçamento preliminar sem ficheiro.",
    keywords: ["número de palavras manual", "introduzir palavras", "introduzir texto"],
  },
  {
    id: "dosyalar-ne-kadar-saklanir",
    category: "upload",
    priority: 67,
    q: "Durante quanto tempo os ficheiros são guardados e posso pedir a sua eliminação?",
    a: "Os seus documentos são guardados de forma segura apenas durante o tempo necessário à prestação do serviço. Pode solicitar a eliminação dos seus documentos a qualquer momento; este pedido é atendido em conformidade com os seus direitos ao abrigo da KVKK.",
    keywords: ["período de conservação", "armazenamento de ficheiros", "pedido de eliminação", "eliminar dados"],
  },
  {
    id: "belgenin-tum-sayfalari",
    category: "upload",
    priority: 68,
    q: "É necessário carregar todas as páginas e os versos do documento?",
    a: "Sim. Para que a tradução seja completa e válida, tem de carregar todas as páginas do documento, incluindo os versos, quando aplicável. É importante que as áreas de selo, carimbo e assinatura estejam claramente visíveis.",
    keywords: ["todas as páginas", "verso", "documento completo", "selos e carimbos"],
  },
  {
    id: "imza-kase-cevrilir-mi",
    category: "upload",
    priority: 69,
    q: "Os carimbos, selos e assinaturas são traduzidos?",
    a: "Numa tradução ajuramentada, o texto legível dos carimbos e selos é transcrito; as assinaturas são indicadas como \"consta assinatura\". Quaisquer áreas ilegíveis são claramente assinaladas na tradução.",
    keywords: ["tradução de carimbo", "tradução de selo", "tradução de assinatura"],
  },
  {
    id: "dosya-guvenli-mi-analiz",
    category: "upload",
    priority: 70,
    q: "O conteúdo do meu documento está seguro durante a análise automática?",
    a: "Sim. Os documentos são transferidos de forma encriptada e operações como a contagem de palavras são realizadas num ambiente seguro. O seu conteúdo nunca é partilhado com terceiros.",
    keywords: ["segurança da análise", "segurança do conteúdo", "leitura automática"],
  },

  // ——— LÍNGUAS E PARES DE LÍNGUAS ———
  {
    id: "50-dil-ne-demek",
    category: "languages",
    priority: 71,
    q: "O que significa o suporte de mais de 50 línguas?",
    a: "Significa que, além das línguas comuns, também conseguimos traduzir línguas menos procuradas. Nas línguas raras, a disponibilidade de tradutor, o prazo de entrega e o preço são confirmados separadamente para cada encomenda.",
    keywords: ["50 línguas", "língua rara", "suporte de línguas", "quantas línguas"],
  },
  {
    id: "yaygin-dil-ciftleri",
    category: "languages",
    priority: 72,
    q: "Traduzem pares como turco-inglês, alemão e francês?",
    a: "Sim. Traduzimos pares de línguas comuns como turco ⇄ inglês, alemão, francês, espanhol, italiano, árabe e russo, em ambos os sentidos. Línguas como o chinês e o japonês também são suportadas.",
    keywords: ["turco inglês", "inglês turco", "alemão", "francês", "par de línguas"],
  },
  {
    id: "yabancidan-yabanciya",
    category: "languages",
    priority: 73,
    q: "Podem traduzir entre duas línguas estrangeiras que não o turco?",
    a: "Sim, podemos traduzir de uma língua estrangeira para outra, como do inglês para o francês. A disponibilidade e o prazo de entrega são avaliados consoante o par de línguas.",
    keywords: ["estrangeira para estrangeira", "inglês francês", "entre línguas"],
  },
  {
    id: "nadir-dil",
    category: "languages",
    priority: 74,
    q: "Oferecem serviços para línguas raras ou não listadas?",
    a: "Procuramos também oferecer línguas raras; no entanto, a disponibilidade de tradutor, o prazo de entrega e o preço são confirmados separadamente para estas línguas. Se a língua de que necessita não constar da lista, contacte a nossa linha de apoio para pedir um orçamento personalizado.",
    keywords: ["língua rara", "língua pouco comum", "língua não listada", "língua especial"],
  },
  {
    id: "dil-varyantlari",
    category: "languages",
    priority: 75,
    q: "Posso escolher uma variante regional (como inglês americano ou britânico)?",
    a: "Sim, sempre que possível pode indicar uma variante regional da língua de destino (por exemplo, inglês americano/britânico, espanhol europeu/latino-americano). Se não indicar uma variante, é utilizado o padrão comum.",
    keywords: ["variante", "inglês americano", "língua regional", "dialeto"],
  },
  {
    id: "anadili-tercuman",
    category: "languages",
    priority: 76,
    q: "Trabalham com tradutores cuja língua materna é a língua de destino?",
    a: "Sempre que possível, trabalhamos com tradutores experientes com domínio da língua de destino. O objetivo é assegurar uma tradução natural e rigorosa.",
    keywords: ["tradutor nativo", "falante nativo", "especialista na língua de destino"],
  },
  {
    id: "osmanlica-eski-yazi",
    category: "languages",
    priority: 77,
    q: "Podem ser traduzidos documentos em turco otomano ou em escrita antiga?",
    a: "Os documentos em turco otomano e escritos no alfabeto antigo podem ser traduzidos, mediante a disponibilidade de um especialista. Nestes documentos, o prazo de entrega e o preço são confirmados após análise.",
    keywords: ["turco otomano", "escrita antiga", "alfabeto antigo"],
  },
  {
    id: "karisik-dilli-belge",
    category: "languages",
    priority: 78,
    q: "Um documento pode ser traduzido se contiver mais do que uma língua?",
    a: "Sim. Os documentos com várias línguas podem ser traduzidos; o preço baseia-se na quantidade de conteúdo em cada língua. Basta indicar-nos a língua de destino de que necessita.",
    keywords: ["línguas mistas", "documento multilingue", "várias línguas num documento"],
  },

  // ——— TIPOS DE SERVIÇO ———
  {
    id: "hangi-hizmeti-secmeliyim",
    category: "services",
    priority: 79,
    q: "Que tipo de serviço devo escolher?",
    a: "O local onde o seu documento será utilizado determina o serviço: os processos oficiais exigem, na maioria dos casos, uma tradução ajuramentada, enquanto alguns procedimentos exigem uma tradução com certificação notarial ou com apostila. Se tiver dúvidas, a nossa linha de apoio ou o assistente de chat podem orientá-lo; a exigência final depende da instituição relevante.",
    keywords: ["que serviço", "seleção de serviço", "o que escolher"],
  },
  {
    id: "standart-yeminli-fark",
    category: "services",
    priority: 80,
    q: "Qual a diferença entre tradução padrão e tradução ajuramentada?",
    a: "Uma tradução padrão destina-se a fins informativos e não tem qualquer certificação oficial. Uma tradução ajuramentada é certificada com o carimbo e a assinatura do tradutor ajuramentado e é exigida em processos oficiais. Qual delas necessita depende da instituição a que o documento será apresentado.",
    keywords: ["padrão vs ajuramentada", "diferença", "tradução simples", "diferença ajuramentada"],
  },
  {
    id: "yeminli-noter-ayni-mi",
    category: "services",
    priority: 81,
    q: "A tradução ajuramentada e a tradução com certificação notarial são a mesma coisa?",
    a: "Não. Uma tradução ajuramentada tem a certificação do tradutor ajuramentado. Uma tradução com certificação notarial é essa tradução certificada adicionalmente por um notário. Algumas instituições exigem apenas uma tradução ajuramentada, ao passo que outras exigem também a certificação notarial.",
    keywords: ["ajuramentada vs notarial", "tradução notarial", "são a mesma coisa"],
  },
  {
    id: "hukuki-teknik-medikal",
    category: "services",
    priority: 82,
    q: "Como é assegurada a especialização nas traduções jurídicas, técnicas e médicas?",
    a: "Os contratos, documentos judiciais, documentação técnica e documentos médicos são traduzidos por tradutores experientes que dominam a terminologia da área relevante. Os glossários terminológicos e a memória de tradução asseguram a coerência, os formatos e as unidades são preservados e a tradução passa por controlo de qualidade.",
    keywords: ["tradução jurídica", "tradução técnica", "tradução médica", "tradutor especializado", "terminologia"],
  },
  {
    id: "akademik-bicim-korunur",
    category: "services",
    priority: 83,
    q: "As referências e a formatação são preservadas na tradução académica?",
    a: "Sim. Nas teses, artigos e textos académicos, a disposição das referências, as citações e a formatação são preservadas na medida do possível, e a tradução segue o estilo académico.",
    keywords: ["tradução académica", "tese", "artigo", "referências", "citações"],
  },
  {
    id: "lokalizasyon-nedir",
    category: "services",
    priority: 84,
    q: "A localização é apenas tradução palavra a palavra? O SEO é tido em conta?",
    a: "Não. A localização consiste em adaptar o texto à cultura e à utilização de destino; a interface, os formatos de data/moeda e o tom são ajustados ao público-alvo. Na localização de sites, as palavras-chave na língua de destino e o alinhamento com o SEO podem ser tidos em conta mediante pedido.",
    keywords: ["localização", "tradução de sites", "tradução de aplicações", "seo", "localizar"],
  },
  {
    id: "kurumsal-marka-dili",
    category: "services",
    priority: 85,
    q: "A voz da marca é preservada nos conteúdos empresariais?",
    a: "Sim. Nas traduções empresariais, um banco de terminologia e um guia de estilo mantêm a voz e o tom da sua marca coerentes.",
    keywords: ["voz da marca", "tom empresarial", "guia de estilo"],
  },
  {
    id: "vize-diploma-hangi-hizmet",
    category: "services",
    priority: 86,
    q: "Que serviço é necessário para documentos como um visto ou um diploma?",
    a: "Para pedidos de visto e traduções de diplomas, a tradução ajuramentada é, geralmente, a exigência de base; algumas representações ou instituições podem exigir também a certificação notarial ou uma apostila. A exigência exata depende do consulado ou da instituição a que se dirige.",
    keywords: ["documento de visto", "tradução de diploma", "certificado de habilitações", "consulado", "tradução para visto"],
  },
  {
    id: "belge-turu-listede-yok",
    category: "services",
    priority: 87,
    q: "O que devo selecionar se o meu tipo de documento não constar da lista?",
    a: "Se o seu tipo de documento não constar da lista, escolha a opção mais aproximada e acrescente uma explicação na nota da encomenda. Se quiser, a nossa linha de apoio pode ajudá-lo a fazer a escolha correta.",
    keywords: ["tipo de documento não listado", "outro documento", "fora da lista"],
  },

  // ——— ENTREGA E PRAZOS ———
  {
    id: "teslim-suresi-nasil-hesaplanir",
    category: "delivery",
    priority: 88,
    q: "Como é calculado o prazo de entrega e onde é apresentado?",
    a: "O prazo é calculado com base na extensão do documento, no par de línguas, no tipo de serviço e nos serviços adicionais, e é apresentado como data de entrega estimada no ecrã Calcular Preço. Nos procedimentos que exigem certificação notarial ou apostila, podem acrescer dias; se a data de entrega mudar, será notificado.",
    keywords: ["cálculo do prazo", "entrega estimada", "quando estará pronto"],
  },
  {
    id: "ayni-gun-teslimat",
    category: "delivery",
    priority: 89,
    q: "É possível a entrega no próprio dia ou em 24 horas?",
    a: "Para documentos curtos, a entrega rápida/urgente é muitas vezes possível; a disponibilidade depende da extensão e da língua do documento. As etapas de controlo de qualidade são mantidas mesmo na entrega urgente, e a opção é apresentada como rubrica adicional no ecrã de orçamento preliminar.",
    keywords: ["no próprio dia", "24 horas", "entrega rápida", "urgente"],
  },
  {
    id: "hafta-sonu-tatil",
    category: "delivery",
    priority: 90,
    q: "Quando são processadas as encomendas ao fim de semana ou fora do horário?",
    a: "Pode carregar documentos, obter orçamentos e criar encomendas a qualquer hora do dia. As encomendas efetuadas fora do horário ou em dias feriados são processadas no início do horário de expediente seguinte, e o prazo de entrega estimado é apresentado em conformidade.",
    keywords: ["fim de semana", "feriado", "fora do horário", "encomenda noturna"],
  },
  {
    id: "dijital-teslim-format",
    category: "delivery",
    priority: 91,
    q: "Como é feita a entrega digital e em que formato a recebo?",
    a: "A tradução concluída é entregue digitalmente através de uma ligação para transferência ou por correio eletrónico. Pode recebê-la em PDF ou num ficheiro Word (DOCX) editável, consoante as suas necessidades; a formatação original é preservada na medida do possível.",
    keywords: ["entrega digital", "entrega em word", "entrega em pdf", "transferência"],
  },
  {
    id: "kargo-kapsam-takip",
    category: "delivery",
    priority: 92,
    q: "Para que regiões fazem envios e posso acompanhar a encomenda?",
    a: "Os documentos com assinatura manuscrita original e carimbo são enviados por correio para toda a Turquia; mediante pedido, também podemos enviar para o estrangeiro. As informações de seguimento do envio são partilhadas consigo, e o tempo de envio acresce ao prazo de entrega total.",
    keywords: ["regiões de envio", "seguimento do envio", "envio internacional", "tempo de envio"],
  },
  {
    id: "kismi-teslimat",
    category: "delivery",
    priority: 93,
    q: "Os projetos longos podem ser entregues por partes?",
    a: "Sim. Os projetos de grande volume ou longos podem ser entregues por secções, mediante pedido. Assim, pode começar a utilizar os seus documentos sem ter de esperar.",
    keywords: ["entrega parcial", "por partes", "entrega por secções"],
  },

  // ——— TRADUÇÃO AJURAMENTADA ———
  {
    id: "yeminli-tercuman-kim",
    category: "sworn",
    priority: 94,
    q: "Quem é um tradutor ajuramentado?",
    a: "Um tradutor ajuramentado é um tradutor que prestou juramento perante um notário e adquiriu, assim, a competência para certificar as suas traduções com assinatura e carimbo. Esta certificação é uma declaração de que a tradução reflete fielmente o original.",
    keywords: ["tradutor ajuramentado", "quem é tradutor ajuramentado", "tradutor certificado"],
  },
  {
    id: "yeminli-ne-zaman-gerekli",
    category: "sworn",
    priority: 95,
    q: "Quando é exigida uma tradução ajuramentada?",
    a: "As traduções ajuramentadas são frequentemente exigidas em processos junto de instituições oficiais, tribunais, consulados e universidades. No entanto, não são obrigatórias para todos os documentos; a exigência exata é definida pela instituição que solicita o documento.",
    keywords: ["quando é exigida ajuramentada", "é necessária ajuramentada", "onde é exigida"],
  },
  {
    id: "yeminli-nerede-gecerli",
    category: "sworn",
    priority: 96,
    q: "Uma tradução ajuramentada é válida em tribunal, no consulado e no estrangeiro?",
    a: "Uma tradução ajuramentada pode ser utilizada em muitos processos e procedimentos oficiais. No entanto, as condições de aceitação de um documento por uma instituição dependem da sua própria regulamentação; no estrangeiro, em particular, pode ser também exigida a certificação notarial ou uma apostila. Recomendamos que confirme os requisitos de aceitação junto da instituição relevante.",
    keywords: ["tribunal", "consulado", "válido no estrangeiro", "candidatura universitária"],
  },
  {
    id: "dijital-imzali-yeminli",
    category: "sworn",
    priority: 97,
    q: "Uma tradução ajuramentada pode ser emitida com assinatura digital/eletrónica?",
    a: "Não. Uma tradução ajuramentada é preparada com a assinatura manuscrita original e o carimbo do tradutor e é entregue fisicamente por correio.",
    keywords: ["assinatura eletrónica", "ajuramentada digital", "assinatura digital", "assinatura manuscrita original", "carimbo"],
  },
  {
    id: "yeminli-orijinal-gerekir",
    category: "sworn",
    priority: 98,
    q: "É necessário o documento original para uma tradução ajuramentada?",
    a: "A tradução pode, geralmente, ser feita a partir de uma cópia nítida (digitalização ou fotografia) do documento. No entanto, se for necessária a certificação notarial, poderá ser solicitado o original ou uma cópia certificada do documento para esse procedimento.",
    keywords: ["documento original", "é necessário o original", "cópia para ajuramentada"],
  },
  {
    id: "yeminli-gecerlilik-suresi",
    category: "sworn",
    priority: 99,
    q: "Uma tradução ajuramentada tem prazo de validade?",
    a: "A tradução em si não tem limite temporal; contudo, algumas instituições podem exigir um documento com data recente. Isto depende dos requisitos da instituição que irá aceitar o documento.",
    keywords: ["prazo de validade", "validade da ajuramentada", "quanto tempo é válida"],
  },
  {
    id: "kurum-belgeyi-kabul-etmezse",
    category: "sworn",
    priority: 100,
    q: "O que acontece se uma instituição não aceitar a tradução ajuramentada?",
    a: "Os requisitos de aceitação podem variar de instituição para instituição. Se a instituição tiver um requisito específico de formato ou de certificação, informe-nos e faremos os ajustes necessários. A decisão final de aceitação cabe à instituição.",
    keywords: ["não aceite", "recusa da instituição", "requisito de formato"],
  },

  // ——— CERTIFICAÇÃO NOTARIAL E APOSTILA ———
  {
    id: "noter-onayli-nedir",
    category: "notary",
    priority: 101,
    q: "O que é uma tradução com certificação notarial?",
    a: "Uma tradução com certificação notarial é uma tradução ajuramentada que é certificada adicionalmente por um notário. Esta certificação reforça a validade oficial da tradução e é exigida por algumas instituições.",
    keywords: ["tradução com certificação notarial", "certificação por notário", "o que é notarial"],
  },
  {
    id: "noter-yeminli-fark",
    category: "notary",
    priority: 102,
    q: "Qual a diferença entre a certificação notarial e uma tradução ajuramentada?",
    a: "Uma tradução ajuramentada tem a certificação do tradutor, ao passo que a certificação notarial é a certificação dessa tradução pelo notário. A certificação notarial é um passo oficial adicional que acresce a uma tradução ajuramentada.",
    keywords: ["notarial vs ajuramentada", "diferença de certificação"],
  },
  {
    id: "notere-gitmem-gerekir-mi",
    category: "notary",
    priority: 103,
    q: "Tenho de me deslocar ao notário para a certificação notarial?",
    a: "Na maioria dos casos, podemos tratar da certificação notarial em seu nome, pelo que não precisa de se deslocar pessoalmente ao notário. Se for necessário o documento original, informamo-lo com antecedência.",
    keywords: ["ir ao notário", "procedimento notarial", "notário em meu nome"],
  },
  {
    id: "apostil-nedir",
    category: "notary",
    priority: 104,
    q: "O que é uma apostila e em que difere da certificação notarial?",
    a: "A apostila é uma certificação internacional emitida pela autoridade competente para que um documento oficial seja reconhecido como válido noutro país, aplicando-se entre os países que são parte na Convenção de Haia. A certificação notarial, por seu lado, é uma certificação dentro de um país; as duas servem finalidades diferentes.",
    keywords: ["o que é apostila", "apostila vs notário", "convenção de haia"],
  },
  {
    id: "apostil-once-mi-ceviri-once-mi",
    category: "notary",
    priority: 105,
    q: "O que vem primeiro, a apostila ou a tradução?",
    a: "A ordem depende do tipo de documento e dos requisitos do país onde será utilizado. Em alguns casos, o documento é apostilado primeiro e só depois traduzido; noutros, é o contrário. Podemos determinar em conjunto a ordem correta.",
    keywords: ["ordem da apostila", "tradução ou apostila primeiro", "sequência"],
  },
  {
    id: "yabanci-belge-turkiye",
    category: "notary",
    priority: 106,
    q: "Qual é o processo se um documento estrangeiro for utilizado na Turquia?",
    a: "Um documento proveniente do estrangeiro é, geralmente, apostilado primeiro no país de origem e, em seguida, objeto de uma tradução ajuramentada (e certificação notarial, se necessário) na Turquia. O processo exato depende da instituição turca que solicita o documento.",
    keywords: ["documento estrangeiro na turquia", "documento recebido", "documento do estrangeiro"],
  },
  {
    id: "turk-belge-yurt-disi",
    category: "notary",
    priority: 107,
    q: "Qual é o processo se um documento turco for utilizado no estrangeiro?",
    a: "Um documento emitido na Turquia é, geralmente, apostilado e objeto de uma tradução ajuramentada para a língua de destino. Se o país de destino não for parte na Convenção de Haia, poderá ser necessária a certificação consular em vez da apostila.",
    keywords: ["documento turco no estrangeiro", "documento a enviar", "certificação consular"],
  },
  {
    id: "hangi-onay-gerekli-bilinmiyor",
    category: "notary",
    priority: 109,
    q: "Como sei se é necessária certificação notarial ou uma apostila?",
    a: "A forma mais fiável é perguntar à instituição que solicita o documento. Se quiser, a nossa linha de apoio pode indicar-lhe as práticas mais comuns; contudo, a exigência exata varia consoante a instituição e o país.",
    keywords: ["que certificação", "é necessária certificação", "notário ou apostila"],
  },
  {
    id: "kesin-kabul-garantisi",
    category: "notary",
    priority: 110,
    q: "A TercümExpert garante a aceitação?",
    a: "Asseguramos que a tradução e as certificações são preparadas de forma rigorosa e completa; no entanto, as condições de aceitação de um documento são definidas pela instituição que o solicita. Por esse motivo, não podemos oferecer uma garantia de aceitação incondicional; se nos indicar os requisitos específicos da instituição, faremos os ajustes necessários.",
    keywords: ["garantia de aceitação", "aceitação garantida", "garantia"],
  },

  // ——— QUALIDADE E REVISÕES ———
  {
    id: "tercumanlar-nasil-secilir",
    category: "quality",
    priority: 111,
    q: "Como são selecionados os tradutores e determinada a sua especialização?",
    a: "Os tradutores são escolhidos consoante o par de línguas e a área de especialidade do documento; um documento jurídico é atribuído a um tradutor com experiência em direito e um documento médico a um com experiência na área da saúde. É atribuído o tradutor mais adequado, tendo em conta a experiência na área e o domínio da língua.",
    keywords: ["seleção de tradutores", "como são escolhidos os tradutores", "especialização", "especialista na área"],
  },
  {
    id: "kalite-kontrol",
    category: "quality",
    priority: 112,
    q: "A tradução passa por controlo de qualidade?",
    a: "Sim. As traduções são verificadas quanto à ortografia, à terminologia, à coerência de números/nomes/datas e à formatação. Consoante o tipo de documento e o nível de serviço, pode aplicar-se uma etapa de revisão independente por um revisor.",
    keywords: ["controlo de qualidade", "revisão", "revisor", "verificação"],
  },
  {
    id: "ceviri-bellegi",
    category: "quality",
    priority: 113,
    q: "Utilizam memória de tradução ou listas de terminologia?",
    a: "Sim, sobretudo em projetos técnicos e empresariais, utiliza-se memória de tradução e listas de terminologia para assegurar a coerência. Pode também partilhar a sua própria lista de termos; a terminologia de projetos anteriores é preservada.",
    keywords: ["memória de tradução", "lista de terminologia", "coerência"],
  },
  {
    id: "revize-kapsami",
    category: "quality",
    priority: 114,
    q: "O que abrange uma revisão e quando a devo solicitar?",
    a: "Uma revisão abrange questões como erros de tradução, ortografia, incoerências e omissões. Alterar o texto de origem posteriormente ou acrescentar novo conteúdo pode ser considerado um trabalho novo. Recomendamos que envie o seu pedido de revisão dentro de um prazo razoável após a entrega, por correio eletrónico ou WhatsApp.",
    keywords: ["âmbito da revisão", "âmbito da correção", "prazo de revisão", "quando pedir revisão"],
  },
  {
    id: "tercuman-degisikligi",
    category: "quality",
    priority: 115,
    q: "E se não ficar satisfeito com a tradução — o tradutor pode ser mudado?",
    a: "Se não ficar satisfeito com a tradução, analisamos a situação e, se necessário, tratamos das correções com um tradutor ou revisor diferente. O objetivo é que o resultado corresponda às suas expetativas.",
    keywords: ["mudar de tradutor", "não satisfeito", "insatisfeito com a tradução"],
  },
  {
    id: "dogruluk-garanti",
    category: "quality",
    priority: 116,
    q: "A exatidão da tradução é garantida?",
    a: "As suas traduções são preparadas por tradutores especializados e passam por controlo de qualidade, e temos todo o cuidado necessário para assegurar a exatidão. Ainda assim, os requisitos de aceitação oficial de um documento podem variar consoante a instituição que o solicita.",
    keywords: ["garantia de exatidão", "garantia de qualidade", "garantia"],
  },
  {
    id: "makine-cevirisi-kullaniliyor",
    category: "quality",
    priority: 117,
    q: "Utilizam tradução totalmente automática/tradução automática?",
    a: "Não. As traduções são realizadas do início ao fim por tradutores humanos profissionais; não oferecemos tradução automática. Utilizam-se apenas ferramentas CAT para apoiar a coerência. As traduções ajuramentadas incluem o carimbo, a assinatura e a declaração de conformidade com o original do tradutor.",
    keywords: ["tradução automática", "tradução automatizada", "tradução por ia", "declaração de conformidade"],
  },

  // ——— PRIVACIDADE E SEGURANÇA ———
  {
    id: "dosyalari-kimler-gorur",
    category: "privacy",
    priority: 118,
    q: "Quem pode ver os ficheiros carregados e são partilhados com terceiros?",
    a: "Apenas o tradutor e a equipa relevante que trabalha na sua encomenda podem aceder aos seus ficheiros. Salvo quando o serviço o exige, os seus documentos nunca são partilhados com terceiros nem utilizados para fins de marketing.",
    keywords: ["quem pode ver", "acesso", "terceiros", "partilha"],
  },
  {
    id: "nda-imzalanabilir",
    category: "privacy",
    priority: 119,
    q: "É possível assinar um acordo de confidencialidade (NDA)?",
    a: "Sim. Sobretudo em projetos empresariais, pode ser celebrado um acordo de confidencialidade (NDA) mediante pedido. Os nossos tradutores estão igualmente vinculados a obrigações de confidencialidade.",
    keywords: ["nda", "acordo de confidencialidade", "acordo de não divulgação"],
  },
  {
    id: "kvkk-uyumlu",
    category: "privacy",
    priority: 120,
    q: "Trabalham em conformidade com a KVKK e como são protegidos os dados pessoais?",
    a: "Sim. Os seus dados pessoais são tratados através de processos em conformidade com a KVKK; são utilizados apenas na medida do necessário à prestação do serviço e guardados de forma segura. Comprometemo-nos a proteger os seus dados com medidas de segurança adequadas.",
    keywords: ["kvkk", "dados pessoais", "proteção de dados", "conformidade com a kvkk"],
  },
  {
    id: "sifreli-aktarim",
    category: "privacy",
    priority: 121,
    q: "Os ficheiros são transferidos de forma encriptada?",
    a: "Sim. Os seus ficheiros são transferidos através de uma ligação encriptada e tratados num ambiente seguro. O nosso objetivo é proteger os seus dados com medidas de segurança adequadas.",
    keywords: ["encriptado", "transferência segura", "encriptação"],
  },
  {
    id: "odeme-bilgileri-saklanir",
    category: "privacy",
    priority: 122,
    q: "Os dados de pagamento/cartão de crédito são guardados?",
    a: "Os dados do seu cartão não são guardados pela TercümExpert; os pagamentos são processados através de uma infraestrutura de pagamento segura.",
    keywords: ["dados de pagamento", "segurança do cartão de crédito", "armazenamento do cartão"],
  },
  {
    id: "belgeler-ai-egitimi",
    category: "privacy",
    priority: 123,
    q: "Os meus documentos são utilizados para treino de modelos?",
    a: "Não. Os seus documentos são utilizados apenas para a sua encomenda; nunca são partilhados para qualquer treino de modelos nem com sistemas externos. A sua tradução é preparada por tradutores humanos, com base na confidencialidade.",
    keywords: ["treino de modelos", "utilização de dados", "treino de ia", "privacidade dos documentos"],
  },
  {
    id: "saglik-kimlik-guvenli",
    category: "privacy",
    priority: 124,
    q: "Os documentos sensíveis, como documentos de identificação, passaportes ou registos de saúde, estão seguros?",
    a: "Sim. Todos os seus ficheiros, incluindo os documentos sensíveis, são tratados de forma confidencial, em conformidade com a KVKK e de modo encriptado. O acesso está limitado à equipa que trabalha na sua encomenda; para documentos altamente confidenciais, podem aplicar-se medidas adicionais como um NDA e acesso restrito.",
    keywords: ["segurança do documento de identificação", "passaporte", "dados de saúde", "documento sensível"],
  },
  {
    id: "hesap-silinince-belgeler",
    category: "privacy",
    priority: 125,
    q: "Os documentos são eliminados quando a conta é eliminada ou mediante pedido?",
    a: "Mediante o seu pedido, os seus documentos e dados pessoais são eliminados, salvo eventuais obrigações legais de conservação. Pode enviar um pedido de eliminação da conta ou dos dados à nossa linha de apoio.",
    keywords: ["eliminação da conta", "eliminação de dados", "eliminar documentos"],
  },

  // ——— SERVIÇOS EMPRESARIAIS ———
  {
    id: "kurumsal-hesap-nasil",
    category: "corporate",
    priority: 126,
    q: "Como abro uma conta empresarial e o que acontece depois de me candidatar?",
    a: "Basta preencher o formulário de candidatura na nossa página Empresas; a nossa equipa contacta-o normalmente no prazo de 1 dia útil, avalia as suas necessidades e define condições adaptadas a si.",
    keywords: ["conta empresarial", "conta de empresa", "candidatura empresarial", "após a candidatura"],
  },
  {
    id: "sirket-adina-siparis",
    category: "corporate",
    priority: 127,
    q: "Posso fazer uma encomenda em nome de uma empresa?",
    a: "Sim. Pode fazer uma encomenda com os dados da sua empresa e beneficiar de faturação empresarial e, quando necessário, de opções de prazo de pagamento.",
    keywords: ["em nome da empresa", "encomenda empresarial", "encomenda da empresa"],
  },
  {
    id: "ozel-hesap-yoneticisi",
    category: "corporate",
    priority: 128,
    q: "É atribuído um gestor de conta dedicado aos clientes empresariais?",
    a: "Aos clientes empresariais pode ser atribuído um gestor de conta dedicado que acompanha os seus processos. Assim, pode gerir os seus pedidos a partir de um único ponto de contacto e receber apoio prioritário.",
    keywords: ["gestor de conta", "gestor dedicado", "apoio empresarial", "apoio prioritário"],
  },
  {
    id: "toplu-fatura",
    category: "corporate",
    priority: 129,
    q: "Posso obter faturação mensal consolidada e prazos de pagamento?",
    a: "Sim. Aos clientes empresariais pode ser oferecida a faturação mensal consolidada e prazos de pagamento até 15 a 30 dias. Os detalhes são definidos no âmbito do acordo.",
    keywords: ["faturação consolidada", "fatura mensal", "prazos de pagamento", "pagamento empresarial"],
  },
  {
    id: "terminoloji-bankasi",
    category: "corporate",
    priority: 130,
    q: "Pode ser criado um banco de terminologia específico para a empresa?",
    a: "Sim. Nos projetos empresariais, é criado um banco de terminologia e um guia de estilo específicos para a sua marca, de modo a preservar a voz da marca e a coerência em todas as traduções.",
    keywords: ["banco de terminologia", "guia de estilo", "terminologia empresarial"],
  },
  {
    id: "sabit-tercuman",
    category: "corporate",
    priority: 131,
    q: "Podemos trabalhar com os mesmos tradutores em projetos recorrentes?",
    a: "Sim. Para projetos empresariais recorrentes, pode ser criada uma bolsa de tradutores/equipa dedicada, de modo a assegurar a continuidade e a coerência.",
    keywords: ["tradutor dedicado", "mesma equipa", "equipa empresarial"],
  },
  {
    id: "kurumsal-raporlama",
    category: "corporate",
    priority: 132,
    q: "Posso obter relatórios de encomendas e de despesas?",
    a: "Aos clientes empresariais pode ser oferecida a elaboração de relatórios sobre as suas encomendas e despesas, com uma discriminação por departamento, se necessário. Nas parcerias empresariais, podem também ser celebrados acordos de nível de serviço (SLA) e de confidencialidade (NDA).",
    keywords: ["relatórios", "relatório de despesas", "relatório de encomendas", "sla"],
  },
  {
    id: "kucuk-isletme",
    category: "corporate",
    priority: 133,
    q: "As pequenas empresas podem utilizar os serviços empresariais e é exigido um volume mínimo?",
    a: "Sim. Não existe qualquer requisito de dimensão ou de volume mínimo para utilizar os nossos serviços empresariais; as pequenas empresas também podem beneficiar de vantagens como prazos de pagamento, gestão de terminologia e apoio prioritário.",
    keywords: ["pequena empresa", "pme", "volume mínimo", "volume exigido"],
  },
  {
    id: "uluslararasi-sirket",
    category: "corporate",
    priority: 134,
    q: "Prestam serviços a empresas internacionais e a projetos multilingues?",
    a: "Sim. Os projetos que abrangem vários países e línguas podem ser coordenados e conduzidos de forma centralizada, assegurando a coerência terminológica em toda a linha. Nos projetos empresariais, podem também ser tratados a tradução ajuramentada e, quando necessário, os processos de certificação notarial e de apostila.",
    keywords: ["empresa internacional", "projeto multilingue", "notarial e apostila empresarial"],
  },

  // ——— APOIO TÉCNICO ———
  {
    id: "nasil-uye-olunur",
    category: "support",
    priority: 135,
    q: "Como me registo no site?",
    a: "Para se registar, basta introduzir o nome, o apelido e o correio eletrónico e, em seguida, confirmar o código de verificação enviado para o seu e-mail. Também se pode registar rapidamente com a sua conta Apple ou Google.",
    keywords: ["registar", "registo", "criar conta"],
  },
  {
    id: "giris-sifre-sorunu",
    category: "support",
    priority: 136,
    q: "O que devo fazer se não conseguir iniciar sessão ou se me esquecer da palavra-passe?",
    a: "Primeiro, verifique o seu correio eletrónico e a palavra-passe; se se esqueceu da palavra-passe, utilize a ligação 'Esqueci-me da palavra-passe' no ecrã de início de sessão para enviar as instruções de reposição para o seu e-mail. Se o problema persistir, verifique a pasta de spam ou contacte a nossa linha de apoio.",
    keywords: ["não consigo iniciar sessão", "repor palavra-passe", "esqueci-me da palavra-passe", "início de sessão", "entrar"],
  },
  {
    id: "dogrulama-epostasi-gelmezse",
    category: "support",
    priority: 137,
    q: "O que devo fazer se o e-mail de verificação não chegar?",
    a: "Aguarde alguns minutos, verifique a pasta de spam/lixo e reenvie o código. Certifique-se de que introduziu corretamente o seu endereço de correio eletrónico; se o problema persistir, contacte a nossa linha de apoio.",
    keywords: ["e-mail de verificação", "código não recebido", "e-mail não chega", "código de verificação"],
  },
  {
    id: "dosya-yuklenmiyor",
    category: "support",
    priority: 138,
    q: "O que devo fazer se um ficheiro não carregar ou se receber um erro de ficheiro não suportado?",
    a: "Verifique o tamanho do ficheiro (até 100 MB) e o formato, e atualize a página e o navegador. Se o formato não for suportado, converta o ficheiro para um formato como PDF ou DOCX, ou cole o texto no separador 'Introduzir Texto'. Se o problema persistir, contacte a nossa linha de apoio.",
    keywords: ["ficheiro não carrega", "erro de carregamento", "ficheiro não suportado", "erro de formato"],
  },
  {
    id: "kelime-sayisi-yanlis",
    category: "support",
    priority: 139,
    q: "O que devo fazer se o número de palavras parecer incorreto?",
    a: "A contagem automática pode falhar, sobretudo em documentos digitalizados ou em imagem. Para um resultado exato, partilhe o texto através de 'Introduzir Texto' ou acrescente uma nota à sua encomenda; a contagem final é confirmada pela nossa equipa e o preço é definido em conformidade.",
    keywords: ["número de palavras errado", "erro de contagem", "contagem de palavras incorreta"],
  },
  {
    id: "odeme-basarisiz",
    category: "support",
    priority: 140,
    q: "O que devo fazer se um pagamento falhar ou se for cobrado duas vezes?",
    a: "Verifique os dados e o limite do seu cartão e tente novamente; também pode utilizar um método diferente (cartão/transferência bancária). Se o valor foi cobrado mas não foi criada nenhuma encomenda, ou se houve uma cobrança em duplicado, contacte a nossa linha de apoio com o seu comprovativo e o valor excedente será reembolsado.",
    keywords: ["pagamento falhou", "erro de pagamento", "cobrado duas vezes", "cobrança em duplicado"],
  },
  {
    id: "teslim-dosyasi-inmiyor",
    category: "support",
    priority: 141,
    q: "O que devo fazer se o ficheiro entregue não for transferido?",
    a: "Atualize a ligação e o seu navegador; se a ligação de transferência tiver expirado, pode solicitar uma nova à nossa linha de apoio.",
    keywords: ["ficheiro não descarrega", "problema de transferência", "não consigo descarregar a entrega", "ligação expirada"],
  },
  {
    id: "mobil-tarayici-destegi",
    category: "support",
    priority: 142,
    q: "Posso utilizar o site num dispositivo móvel e que navegadores são suportados?",
    a: "O site está otimizado para dispositivos móveis; pode carregar documentos e efetuar encomendas a partir de um iPhone, telemóvel Android ou tablet. Pode utilizar o site sem problemas com versões atuais do Chrome, Safari, Edge e Firefox.",
    keywords: ["móvel", "telemóvel", "iphone android", "tablet", "navegador", "chrome safari"],
  },
  {
    id: "ai-asistan-ne-yapar",
    category: "support",
    priority: 143,
    q: "O que pode fazer o assistente de chat com apoio de inteligência artificial?",
    a: "O assistente de chat presta orientação imediata sobre o processo, os tipos de serviço e questões gerais, e encaminha-o para os passos corretos, como obter um orçamento. Não pode tomar decisões finais ou vinculativas sobre requisitos de aceitação oficial ou requisitos legais (como a certificação notarial ou a apostila); nesses casos, deve consultar a instituição relevante.",
    keywords: ["assistente de chat", "chatbot", "assistente de ia", "preços do chatbot"],
  },
  {
    id: "insana-baglanma",
    category: "support",
    priority: 144,
    q: "Como contacto um representante de apoio ao cliente humano?",
    a: "Pode solicitá-lo através do assistente de chat ou contactar diretamente a nossa linha de apoio humano através do WhatsApp e do correio eletrónico. Os pedidos são respondidos durante o horário de expediente. Enviar os problemas técnicos com uma captura de ecrã ajuda a acelerar a resolução.",
    keywords: ["falar com um humano", "representante de apoio", "apoio ao vivo", "captura de ecrã"],
  },
  {
    id: "hesap-bilgileri-guncelleme",
    category: "support",
    priority: 145,
    q: "Como atualizo os dados da conta e de faturação e como elimino a minha conta?",
    a: "Se tiver conta, pode atualizar o telefone, o correio eletrónico e os dados de faturação nas definições da conta, e pode também solicitar aí a eliminação da conta ou contactando a nossa linha de apoio. Mediante o seu pedido, os seus dados são eliminados, salvo eventuais obrigações legais.",
    keywords: ["atualizar dados", "dados de faturação", "definições da conta", "eliminar conta"],
  },
  {
    id: "bildirim-tercihleri",
    category: "support",
    priority: 146,
    q: "Como funcionam as notificações de encomenda e posso receber notificações por WhatsApp?",
    a: "São enviadas notificações por correio eletrónico sobre o estado da sua encomenda; consoante as suas preferências, também podem ser fornecidas atualizações por WhatsApp. Pode ajustar as suas preferências de notificação nas definições da conta ou através da nossa linha de apoio.",
    keywords: ["notificações", "sms", "notificação por whatsapp", "notificação por e-mail", "notificação de encomenda"],
  },
]
