/**
 * Fuente de datos de FAQ (español). La lógica de precios/pago puede cambiar más
 * adelante (§13). Reglas de honestidad: SIN afirmaciones no verificadas de
 * ISO/certificación; no se da a entender una oficina física; no se promete
 * soporte humano 24/7; se preservan las distinciones jurada / certificación
 * notarial / apostilla; no se garantiza la aceptación institucional.
 * `priority` = orden de importancia global (menor = más arriba). La vista por
 * categoría usa el mismo orden, por lo que la ordenación dentro de cada
 * categoría se deriva de este valor.
 */
import type { FaqCategory, FaqItem } from "./faq-data"

export const FAQ_CATEGORIES_ES: FaqCategory[] = [
  { key: "general", label: "General" },
  { key: "order", label: "Proceso de pedido" },
  { key: "pricing", label: "Precios y pago" },
  { key: "upload", label: "Subida de archivos" },
  { key: "languages", label: "Idiomas y pares de idiomas" },
  { key: "services", label: "Tipos de servicio" },
  { key: "delivery", label: "Entrega y plazos" },
  { key: "sworn", label: "Traducción jurada" },
  { key: "notary", label: "Certificación notarial y apostilla" },
  { key: "quality", label: "Calidad y revisiones" },
  { key: "privacy", label: "Privacidad y seguridad" },
  { key: "corporate", label: "Servicios para empresas" },
  { key: "support", label: "Soporte técnico" },
]

export const FAQ_ITEMS_ES: FaqItem[] = [
  // ——— TODOS: preguntas prioritarias a lo largo del recorrido del cliente ———
  {
    id: "nasil-fiyat-alirim",
    category: "pricing",
    priority: 1,
    q: "¿Cómo obtengo un presupuesto?",
    a: "Entre en la página Calcular presupuesto y suba su documento o pegue su texto; en cuanto seleccione el par de idiomas y el tipo de servicio, verá al instante su estimación preliminar. El importe se calcula en función del par de idiomas, el tipo de servicio, el número de palabras y los servicios adicionales que elija.",
    keywords: ["presupuesto", "estimación", "precio", "cuánto cuesta", "calcular precio", "coste traducción"],
  },
  {
    id: "dosya-nasil-yuklenir",
    category: "upload",
    priority: 2,
    q: "¿Cómo subo mi archivo?",
    a: "En la página Calcular presupuesto, abra la pestaña 'Subir archivo' y arrastre y suelte su documento o selecciónelo para cargarlo. Si no dispone de un archivo, basta con pegar su texto en la pestaña 'Introducir texto'. En los archivos de texto, el sistema cuenta las palabras automáticamente.",
    keywords: ["subir archivo", "cargar documento", "adjuntar archivo", "no puedo subir", "cómo subir"],
  },
  {
    id: "fiyatlandirma-neye-gore",
    category: "pricing",
    priority: 3,
    q: "¿Cómo se determina el precio?",
    a: "El importe se establece en función del par de idiomas, el tipo de servicio, el contenido del documento, el número de palabras, el área de especialidad y los servicios adicionales que seleccione. La cifra que ve en pantalla es un presupuesto preliminar; el importe final se confirma tras revisar el documento.",
    keywords: ["precios", "cómo se calcula", "factores del precio", "por palabra", "tarifas"],
  },
  {
    id: "teslim-suresi-ne-kadar",
    category: "delivery",
    priority: 4,
    q: "¿Cuál es el plazo de entrega?",
    a: "El plazo depende de la extensión del documento, el par de idiomas, el tipo de servicio y los servicios adicionales que seleccione. La pantalla de presupuesto muestra un plazo de entrega estimado específico para su pedido. Puede acortarlo con la opción de entrega urgente.",
    keywords: ["plazo de entrega", "cuántos días", "cuándo se entrega", "tiempo de entrega", "cuánto tarda"],
  },
  {
    id: "yeminli-tercume-nedir",
    category: "sworn",
    priority: 5,
    q: "¿Qué es una traducción jurada?",
    a: "Una traducción jurada es aquella que el traductor jurado certifica con su firma y sello, declarando su fidelidad al documento original. Se solicita con frecuencia en trámites oficiales. Su exigencia concreta depende de la institución que solicita el documento.",
    keywords: ["traducción jurada", "traducción certificada", "traducción con sello", "traducción oficial", "qué es jurada"],
  },
  {
    id: "hangi-dillerde-hizmet",
    category: "languages",
    priority: 6,
    q: "¿En qué idiomas ofrecen servicio?",
    a: "Trabajamos con el turco, así como con el inglés, el alemán, el francés, el español, el italiano, el árabe y el ruso, entre más de 50 idiomas en total. En idiomas poco frecuentes, la disponibilidad del traductor y el plazo de entrega se confirman por separado para cada pedido.",
    keywords: ["idiomas", "qué idiomas", "opciones de idioma", "pares de idiomas", "cuántos idiomas"],
  },
  {
    id: "noter-onayi-gerekir-mi",
    category: "notary",
    priority: 7,
    q: "¿Necesito certificación notarial?",
    a: "La certificación notarial no es obligatoria para todos los documentos; su necesidad depende de la institución que solicita el documento y del uso previsto. En algunos trámites basta con una traducción jurada, mientras que en otros se exige además certificación notarial. Si no está seguro de qué certificación necesita, podemos orientarle.",
    keywords: ["certificación notarial", "notario", "notarizado", "necesito notario"],
  },
  {
    id: "siparis-nasil-ilerler",
    category: "order",
    priority: 8,
    q: "¿Cómo funciona el proceso de pedido?",
    a: "Una vez que sube su documento y aprueba el presupuesto preliminar, se crea su pedido y se asigna a un traductor especializado en el área correspondiente. La traducción pasa por un control de calidad; si es necesario, se gestiona el proceso de certificación notarial o apostilla, y su documento se entrega de forma digital y, cuando es preciso, por mensajería.",
    keywords: ["proceso de pedido", "cómo funciona", "fases", "flujo de trabajo"],
  },
  {
    id: "belgelerim-guvende-mi",
    category: "privacy",
    priority: 9,
    q: "¿Están seguros mis documentos?",
    a: "Sí. Sus archivos solo son vistos por el equipo asignado a su pedido y se tratan mediante transferencia cifrada y procesos conformes con la KVKK (ley turca de protección de datos). Sus documentos no se comparten con terceros y la confidencialidad es nuestra prioridad.",
    keywords: ["seguridad", "confidencialidad", "seguridad de documentos", "protección de datos", "kvkk"],
  },
  {
    id: "cevirimi-kim-yapar",
    category: "quality",
    priority: 10,
    q: "¿Quién realiza mi traducción?",
    a: "Sus traducciones las realizan traductores humanos profesionales con experiencia en el área correspondiente. Se asigna un traductor especializado según el tipo de documento, y toda traducción pasa por un control de calidad antes de la entrega.",
    keywords: ["quién traduce", "traductor", "traductor humano", "profesional", "quién lo hace"],
  },
  {
    id: "revize-hakki-var-mi",
    category: "quality",
    priority: 11,
    q: "¿Se incluyen revisiones?",
    a: "Sí. Una vez entregada la traducción, tiene derecho a solicitar revisiones para las correcciones que estén dentro del alcance original. Las correcciones de ortografía, nombres, fechas o coherencia están incluidas. Modificar el texto de origen posteriormente o añadir contenido nuevo puede considerarse un trabajo nuevo.",
    keywords: ["revisiones", "correcciones", "revisión", "rehacer traducción", "política de revisión"],
  },
  {
    id: "fiziksel-teslimat-yapiliyor-mu",
    category: "delivery",
    priority: 12,
    q: "¿Ofrecen entrega física?",
    a: "Sí. Aunque la entrega digital es lo habitual, los documentos con firma manuscrita original y sello pueden enviarse a su dirección por mensajería. Realizamos envíos a toda Turquía y, si lo solicita, también al extranjero. Si elige el envío por mensajería, el tiempo de envío se suma al plazo de entrega.",
    keywords: ["entrega física", "mensajería", "envío postal", "entrega a domicilio"],
  },
  {
    id: "kurumsal-ozel-sartlar",
    category: "corporate",
    priority: 13,
    q: "¿Hay condiciones especiales para clientes de empresa?",
    a: "Sí. Los clientes de empresa disfrutan de ventajas por pedidos de gran volumen, opciones de plazos de pago, gestión terminológica y un gestor de cuenta dedicado. Para más detalles, rellene el formulario de solicitud de nuestra página para Empresas.",
    keywords: ["empresas", "corporativo", "condiciones para empresas", "pedido en volumen", "clientes corporativos"],
  },
  {
    id: "apostil-nasil-yurutulur",
    category: "notary",
    priority: 14,
    q: "¿Cómo se gestiona el trámite de apostilla?",
    a: "La apostilla es una certificación emitida por la autoridad competente para que un documento se reconozca como válido en el extranjero. Podemos gestionar el trámite en su nombre; qué documento necesita apostilla y el orden de los pasos dependen del país donde se vaya a utilizar. En los países que no son parte del Convenio de La Haya, puede ser necesaria una legalización consular en lugar de la apostilla.",
    keywords: ["apostilla", "trámite de apostilla", "legalización", "válido en el extranjero"],
  },
  {
    id: "acil-teslimat-mumkun-mu",
    category: "delivery",
    priority: 15,
    q: "¿Es posible la entrega urgente?",
    a: "Sí, la entrega urgente está disponible para muchos documentos y acorta el plazo. La entrega urgente conlleva un recargo, y su disponibilidad puede variar según la extensión y el idioma del documento. Los pasos de control de calidad se mantienen también en los pedidos urgentes.",
    keywords: ["entrega urgente", "entrega rápida", "mismo día", "exprés", "urgente"],
  },
  {
    id: "odeme-nasil-yapilir",
    category: "pricing",
    priority: 16,
    q: "¿Cómo se realiza el pago?",
    a: "Los pagos pueden efectuarse con tarjeta de crédito o débito y mediante transferencia bancaria; en el pago con tarjeta puede ofrecerse la posibilidad de fraccionar. A los clientes de empresa se les ofrece además la opción de facturación con plazo de pago (15-30 días). El cobro se realiza tras aprobar el presupuesto preliminar.",
    keywords: ["pago", "forma de pago", "tarjeta de crédito", "transferencia", "cómo pagar"],
  },
  {
    id: "dosya-yuklemeden-fiyat",
    category: "upload",
    priority: 17,
    q: "¿Puedo obtener un presupuesto sin subir un archivo?",
    a: "Sí. Si no dispone de un archivo, pegue su texto en la pestaña 'Introducir texto' para obtener un presupuesto preliminar según el número de palabras.",
    keywords: ["presupuesto sin archivo", "presupuesto con texto", "sin subir archivo", "estimación por texto"],
  },
  {
    id: "belgenin-formati-korunur-mu",
    category: "delivery",
    priority: 18,
    q: "¿Se conserva el formato del documento?",
    a: "En la medida de lo posible, mantenemos en la traducción la maquetación original, las tablas y el formato. Según sus necesidades, el resultado puede entregarse en PDF o en un archivo Word (DOCX) editable. En los documentos escaneados o basados en imagen, ofrecemos una disposición limpia y ordenada en lugar de una réplica exacta.",
    keywords: ["formato", "maquetación", "diseño de página", "word", "pdf", "conservar formato"],
  },
  {
    id: "teslim-sonrasi-destek",
    category: "quality",
    priority: 19,
    q: "¿Puedo recibir asistencia después de la entrega de la traducción?",
    a: "Sí. Tras la entrega, dispone de asistencia de revisión para las correcciones dentro del alcance, y puede contactar con nuestra línea de atención al cliente para cualquier consulta. Puede enviar solicitudes adicionales sobre su documento por correo electrónico o WhatsApp.",
    keywords: ["asistencia posterior", "después de la entrega", "ayuda", "soporte"],
  },
  {
    id: "cok-sayfali-yuksek-hacim",
    category: "order",
    priority: 20,
    q: "¿Cómo se gestionan los trabajos de muchas páginas o gran volumen?",
    a: "Los proyectos de gran volumen se ejecutan de forma planificada; cuando es necesario, participan varios traductores y editores, y se utiliza un glosario común para garantizar la coherencia terminológica. Los proyectos largos pueden entregarse por partes (entrega parcial) si así lo prefiere. En los proyectos de empresa, el proceso lo coordina su gestor de cuenta.",
    keywords: ["muchas páginas", "gran volumen", "trabajo extenso", "proyecto grande", "varios documentos"],
  },

  // ——— GENERAL ———
  {
    id: "tercumexpert-nedir",
    category: "general",
    priority: 21,
    q: "¿Qué es TercümExpert?",
    a: "TercümExpert es un proveedor de servicios de traducción en línea que ofrece traducción jurada, traducción con certificación notarial, traducción jurídica, técnica, médica y académica, y localización web y móvil. Puede subir su documento, obtener un presupuesto preliminar y realizar su pedido íntegramente en línea.",
    keywords: ["tercumexpert", "qué es", "sobre nosotros", "servicio de traducción", "a qué se dedica"],
  },
  {
    id: "hangi-hizmetler",
    category: "general",
    priority: 22,
    q: "¿Qué servicios ofrece TercümExpert?",
    a: "Ofrecemos traducción jurada y con certificación notarial, apoyo en el trámite de apostilla, traducción jurídica, técnica, médica y académica, y localización de sitios web y aplicaciones móviles. Puede elegir el servicio que se ajuste a sus necesidades en la pantalla Calcular presupuesto.",
    keywords: ["servicios", "qué ofrecen", "tipos de servicio", "qué servicios"],
  },
  {
    id: "kimler-hizmet-alabilir",
    category: "general",
    priority: 23,
    q: "¿Quién puede contratar sus servicios?",
    a: "Pueden contratar nuestros servicios tanto clientes particulares como empresas y organizaciones. Desde estudiantes hasta profesionales autónomos, y desde pequeñas empresas hasta grandes organizaciones, ofrecemos soluciones adaptadas a distintas necesidades.",
    keywords: ["quién puede", "particulares", "empresas", "compañías", "clientes"],
  },
  {
    id: "ofise-gelmek-gerekir-mi",
    category: "general",
    priority: 24,
    q: "¿Es necesario acudir a una oficina en persona?",
    a: "No. Todo el proceso —presupuesto, pedido, pago y entrega— puede gestionarse en línea. Solo tiene que subir y aprobar sus documentos; no necesita desplazarse a ningún sitio.",
    keywords: ["oficina", "en persona", "sucursal", "dirección", "hay que acudir"],
  },
  {
    id: "surec-cevrimici-mi",
    category: "general",
    priority: 25,
    q: "¿Puede gestionarse todo el proceso en línea?",
    a: "Sí. La subida de documentos, la aprobación del presupuesto, el pago y la entrega digital son totalmente en línea. Solo se recurre a la mensajería cuando se requiere un documento físico con firma manuscrita original.",
    keywords: ["en línea", "totalmente en línea", "a distancia", "por internet", "todo online"],
  },
  {
    id: "yurt-disindan-hizmet",
    category: "general",
    priority: 26,
    q: "¿Pueden contratar el servicio los clientes desde el extranjero?",
    a: "Sí. Como el proceso es en línea, puede subir documentos y realizar pedidos desde el extranjero. La entrega digital está disponible en cualquier lugar y, para documentos con firma manuscrita original, también podemos realizar envíos internacionales por mensajería.",
    keywords: ["extranjero", "clientes internacionales", "desde el exterior", "fuera de turquía"],
  },
  {
    id: "uyelik-zorunlu-mu",
    category: "general",
    priority: 27,
    q: "¿Es obligatorio registrarse para contratar el servicio?",
    a: "El registro no es obligatorio. No obstante, para ver el precio y realizar un pedido debe introducir su nombre, apellidos y correo electrónico, y confirmar el código de verificación que reciba por correo. Si lo desea, puede crear una cuenta para llevar el seguimiento de su historial de pedidos.",
    keywords: ["registro", "darse de alta", "cuenta", "obligatorio", "sin registro"],
  },
  {
    id: "uye-olmadan-fiyat",
    category: "general",
    priority: 28,
    q: "¿Puedo obtener un presupuesto sin registrarme?",
    a: "Sí, puede obtener un presupuesto sin crear una cuenta completa; solo necesita verificar su nombre, apellidos y correo electrónico. Los usuarios que no completen la verificación no pueden ver el precio ni realizar un pedido.",
    keywords: ["presupuesto sin cuenta", "sin registro", "código de verificación", "verificación por correo"],
  },
  {
    id: "siparis-oncesi-danismanlik",
    category: "general",
    priority: 29,
    q: "¿Puedo recibir asesoramiento antes de hacer un pedido?",
    a: "Sí. Si no está seguro de qué servicio necesita, puede solicitar información por WhatsApp, correo electrónico o a través de nuestro asistente de chat con inteligencia artificial. Le ayudaremos a determinar el servicio y el proceso adecuados según el tipo de su documento.",
    keywords: ["asesoramiento", "consulta", "hacer una pregunta", "ayuda previa"],
  },
  {
    id: "musteri-temsilcisi",
    category: "general",
    priority: 30,
    q: "¿Cómo contacto con un agente de atención al cliente?",
    a: "Puede contactar con nuestra línea de atención al cliente por WhatsApp o correo electrónico. Sus consultas las responde un agente en horario laboral; además, nuestro asistente de chat con inteligencia artificial puede ofrecerle una primera orientación en cualquier momento.",
    keywords: ["agente de atención", "soporte", "contacto", "ponerse en contacto", "atención en directo"],
  },
  {
    id: "hangi-belgeler-cevrilebilir",
    category: "general",
    priority: 31,
    q: "¿Qué tipos de documentos pueden traducirse?",
    a: "Traducimos una amplia variedad, desde documentos oficiales y personales hasta textos comerciales, jurídicos, técnicos, médicos y académicos. Se admiten numerosos tipos de documentos, como diplomas y títulos, contratos, informes, manuales y contenido de sitios web.",
    keywords: ["tipos de documento", "qué documentos", "documentación", "qué se puede traducir"],
  },
  {
    id: "yapay-zeka-mi-insan-mi",
    category: "general",
    priority: 32,
    q: "¿Las traducciones las realizan traductores humanos?",
    a: "Sí. Sus traducciones las realizan de principio a fin traductores humanos profesionales. Se emplean herramientas TAO para favorecer la coherencia y la terminología, pero toda la traducción es obra de traductores expertos y pasa por un control de calidad.",
    keywords: ["traductor humano", "herramienta tao", "herramientas de traducción", "traducción automática", "quién traduce"],
  },
  {
    id: "el-yazili-belgeler",
    category: "general",
    priority: 33,
    q: "¿Pueden traducirse documentos manuscritos o difíciles de leer?",
    a: "Los documentos manuscritos y difíciles de leer pueden traducirse siempre que sean legibles. Las partes ilegibles se indican con claridad en la traducción y, si es necesario, podemos pedirle una copia más nítida. En este tipo de documentos, el precio se confirma tras su revisión.",
    keywords: ["manuscrito", "escrito a mano", "ilegible", "poco claro", "difícil de leer"],
  },
  {
    id: "farkiniz-nedir",
    category: "general",
    priority: 34,
    q: "¿Qué distingue a TercümExpert de otros servicios de traducción?",
    a: "Lo que nos distingue es nuestro proceso íntegramente en línea, el presupuesto preliminar automático, los traductores humanos especializados y el control de calidad. Además, entregamos los documentos con firma manuscrita original directamente en su domicilio por mensajería.",
    keywords: ["diferencia", "ventaja", "por qué tercumexpert", "qué os hace diferentes"],
  },

  // ——— PROCESO DE PEDIDO ———
  {
    id: "siparis-nasil-verilir",
    category: "order",
    priority: 35,
    q: "¿Cómo realizo un pedido?",
    a: "En la pantalla Calcular presupuesto, suba su documento o introduzca su texto, seleccione el par de idiomas y el tipo de servicio, y apruebe el presupuesto preliminar. Una vez aprobado, se crea su pedido.",
    keywords: ["realizar pedido", "cómo pedir", "crear pedido", "hacer un pedido"],
  },
  {
    id: "siparis-icin-gerekli-bilgiler",
    category: "order",
    priority: 36,
    q: "¿Qué información se necesita para realizar un pedido?",
    a: "Necesita el documento o texto que desea traducir, el idioma de origen y el de destino, el tipo de servicio y sus datos de contacto (nombre, apellidos y correo electrónico). Con esta información puede crear su pedido.",
    keywords: ["información necesaria", "qué se necesita", "datos del pedido", "requisitos del pedido"],
  },
  {
    id: "dil-cifti-nasil-secilir",
    category: "order",
    priority: 37,
    q: "¿Cómo elijo el par de idiomas y el tipo de servicio?",
    a: "En la pantalla Calcular presupuesto, seleccione en el menú el idioma de origen (el del documento), el idioma de destino (el de la traducción) y el tipo de servicio (jurada, con certificación notarial, técnica, etc.). Si tiene dudas, nuestra línea de atención o el asistente de chat pueden orientarle hacia la opción correcta.",
    keywords: ["elegir par de idiomas", "idioma de origen", "idioma de destino", "seleccionar servicio"],
  },
  {
    id: "bilgiler-degistirilebilir-mi",
    category: "order",
    priority: 38,
    q: "¿Puedo cambiar los datos después de crear un pedido?",
    a: "Datos como el idioma, el tipo de servicio o el documento pueden actualizarse antes de que comience la traducción. Basta con contactar con nuestra línea de atención lo antes posible; una vez iniciado el trabajo, el margen para introducir cambios puede reducirse.",
    keywords: ["cambiar datos", "editar pedido", "actualizar pedido", "idioma incorrecto", "documento incorrecto"],
  },
  {
    id: "onaydan-once-iptal",
    category: "order",
    priority: 39,
    q: "¿Puedo cancelar un pedido antes de aprobarlo?",
    a: "Sí. Puede cancelar su pedido antes de completar el pago y la aprobación; en esta fase no se aplica ningún cargo.",
    keywords: ["cancelar", "cancelar pedido", "desistir", "anular pedido"],
  },
  {
    id: "odeme-sonrasi-iptal",
    category: "order",
    priority: 40,
    q: "¿Puede cancelarse un pedido después del pago?",
    a: "Si la traducción aún no ha comenzado, la cancelación y el reembolso suelen ser posibles. Si el trabajo ya ha empezado, puede aplicarse un cargo parcial en función de la parte completada. Comunicar su solicitud de cancelación cuanto antes agiliza el proceso.",
    keywords: ["cancelar tras el pago", "reembolso", "devolución del dinero", "cancelar después de pagar"],
  },
  {
    id: "siparis-durumu-takip",
    category: "order",
    priority: 41,
    q: "¿Dónde puedo seguir el estado de mi pedido?",
    a: "Se le informa del estado de su pedido por correo electrónico y, si ha creado una cuenta, también puede consultarlo desde ella. Asimismo, puede solicitar el estado actualizado a nuestra línea de atención.",
    keywords: ["seguir pedido", "estado", "seguimiento del pedido", "estado del pedido"],
  },
  {
    id: "birden-fazla-belge",
    category: "order",
    priority: 42,
    q: "¿Puede un pedido incluir varios documentos o idiomas de destino?",
    a: "Sí, puede subir varios documentos en un mismo pedido y traducir el mismo documento a varios idiomas. El número total de palabras y cada idioma de destino se presupuestan como traducciones independientes, y el proceso se coordina bajo una única solicitud.",
    keywords: ["varios documentos", "varios archivos", "varios idiomas", "múltiples idiomas"],
  },
  {
    id: "sonradan-dosya-eklenebilir",
    category: "order",
    priority: 43,
    q: "¿Puedo añadir un archivo nuevo a un pedido más adelante?",
    a: "Puede añadir un archivo nuevo antes de que comience la traducción; en ese caso, el precio se actualiza según el contenido añadido. Los documentos añadidos una vez iniciado el trabajo pueden tratarse como una partida nueva.",
    keywords: ["añadir archivo", "añadir después", "archivo nuevo", "agregar documento"],
  },
  {
    id: "eksik-belge-gonderilirse",
    category: "order",
    priority: 44,
    q: "¿Qué ocurre si envío un documento incompleto?",
    a: "Cuando detectamos una página o un documento que falta, le pedimos que lo complete. Subir todas las páginas del documento es importante para que la traducción sea completa y válida.",
    keywords: ["documento incompleto", "falta una página", "documento faltante", "páginas que faltan"],
  },
  {
    id: "terminoloji-not-referans",
    category: "order",
    priority: 45,
    q: "¿Puedo añadir notas, terminología o archivos de referencia específicos del pedido?",
    a: "Sí. Durante el pedido puede añadir instrucciones especiales, términos preferidos o una nota de estilo, y subir archivos de referencia como traducciones anteriores y glosarios. Esta información se transmite al traductor y se utiliza para garantizar la coherencia.",
    keywords: ["añadir nota", "instrucciones especiales", "terminología", "archivo de referencia", "glosario"],
  },
  {
    id: "eski-siparisler-goruntulenir",
    category: "order",
    priority: 46,
    q: "¿Puedo acceder más adelante a pedidos y archivos anteriores?",
    a: "Si ha creado una cuenta, puede consultar en ella sus pedidos anteriores y los archivos entregados. En los pedidos realizados sin cuenta, puede acceder a sus registros por correo electrónico; si un enlace de descarga ha caducado, puede solicitar uno nuevo a nuestra línea de atención.",
    keywords: ["pedidos anteriores", "historial de pedidos", "pedidos previos", "acceder a archivos"],
  },

  // ——— PRECIOS Y PAGO ———
  {
    id: "kelime-mi-sayfa-mi",
    category: "pricing",
    priority: 47,
    q: "¿Cobran por palabra o por página?",
    a: "El precio suele basarse en el número de palabras y en el servicio seleccionado. En los documentos de texto, el número de palabras se extrae automáticamente; en los documentos escaneados o basados en imagen, el recuento se confirma tras su revisión.",
    keywords: ["por palabra", "por página", "base del precio", "cómo se cobra"],
  },
  {
    id: "sabit-baslangic-ucreti",
    category: "pricing",
    priority: 48,
    q: "¿Existe una tarifa mínima o un importe inicial fijo?",
    a: "Algunos servicios pueden tener una tarifa mínima, que puede aplicarse a documentos breves. El precio final se determina según el contenido del documento y los servicios que seleccione, y puede ver cada partida en la pantalla de presupuesto preliminar.",
    keywords: ["tarifa inicial", "mínimo", "tarifa fija", "importe mínimo"],
  },
  {
    id: "neler-fiyati-etkiler",
    category: "pricing",
    priority: 49,
    q: "¿El par de idiomas, el tipo de documento y el área de especialidad afectan al precio?",
    a: "Sí. El par de idiomas (especialmente los idiomas poco frecuentes), el tipo de documento y el área de especialidad (jurídica, médica, técnica, etc.) pueden influir en la densidad terminológica y, por tanto, en el precio. En los idiomas más comunes, el precio es más previsible.",
    keywords: ["precio par de idiomas", "precio tipo de documento", "precio especialidad", "por qué varían los precios"],
  },
  {
    id: "yeminli-daha-pahali-mi",
    category: "pricing",
    priority: 50,
    q: "¿Es más cara la traducción jurada?",
    a: "La traducción jurada puede tener un precio distinto al de la traducción estándar debido a la certificación y la responsabilidad del traductor. El importe exacto se muestra en la pantalla de presupuesto preliminar según el documento y el par de idiomas.",
    keywords: ["precio traducción jurada", "coste jurada", "es cara la jurada", "tarifa jurada"],
  },
  {
    id: "noter-apostil-ucreti-dahil",
    category: "pricing",
    priority: 51,
    q: "¿Están incluidas en el precio las tasas de certificación notarial y apostilla?",
    a: "La certificación notarial y la apostilla son trámites independientes que realizan las autoridades competentes y están sujetos a tarifas oficiales. Estos costes se muestran por separado del importe de la traducción; al depender de una tarifa oficial, pueden no ser exactos por adelantado, y el importe real se comunica una vez realizado el trámite.",
    keywords: ["tasa notarial", "tasa de apostilla", "está incluido", "coste notario", "coste apostilla"],
  },
  {
    id: "on-fiyat-nihai-fark",
    category: "pricing",
    priority: 52,
    q: "¿Puede diferir el presupuesto preliminar del precio final?",
    a: "Sí. El cálculo automático que ve en pantalla es un presupuesto preliminar. Tras una revisión basada en el número de palabras, la legibilidad o el tipo de documento, el precio final puede confirmarse. El importe definitivo se le comunica antes de que lo apruebe.",
    keywords: ["presupuesto preliminar", "precio final", "diferencia de precio", "precio exacto"],
  },
  {
    id: "otomatik-kelime-sayimi",
    category: "pricing",
    priority: 53,
    q: "¿El número de palabras se calcula automáticamente? ¿Qué ocurre con los PDF escaneados?",
    a: "En los documentos de texto (Word, PDF de texto, texto sin formato), el número de palabras se extrae automáticamente. En los PDF escaneados o basados en imagen y en las fotografías, el recuento automático puede no ser fiable, por lo que nuestro equipo lo confirma. El presupuesto preliminar se basa en el recuento automático y no es vinculante; si hay una discrepancia, el precio final se confirma con usted.",
    keywords: ["recuento de palabras", "conteo automático", "pdf escaneado", "pdf de imagen", "error de recuento"],
  },
  {
    id: "toplu-kurumsal-indirim",
    category: "pricing",
    priority: 54,
    q: "¿Hay descuentos para pedidos de gran volumen o clientes de empresa?",
    a: "Para trabajos de gran volumen y recurrentes, especialmente para clientes de empresa, podemos ofrecer precios ventajosos y opciones de plazos de pago en función del volumen y de las condiciones de colaboración. Para más detalles, utilice el formulario de solicitud para Empresas.",
    keywords: ["descuento por volumen", "descuento cantidad", "precio para empresas", "tarifas corporativas"],
  },
  {
    id: "ucretsiz-teklif",
    category: "pricing",
    priority: 55,
    q: "¿Puedo obtener un presupuesto gratuito? ¿Cuánto tiempo es válido?",
    a: "El presupuesto preliminar es gratuito; lo ve al instante cuando sube su documento o introduce su texto. Los presupuestos son válidos durante un breve periodo, siempre que las condiciones (contenido o alcance del documento) no cambien.",
    keywords: ["presupuesto gratis", "estimación gratuita", "validez del presupuesto", "cuánto tiempo válido"],
  },
  {
    id: "fatura-kesiliyor-mu",
    category: "pricing",
    priority: 56,
    q: "¿Emiten factura? ¿Puedo obtener factura como particular o como empresa?",
    a: "Sí. Se emite factura por el servicio, y puede solicitarla como particular o como empresa. A los clientes de empresa también se les puede ofrecer facturación mensual consolidada. Los impuestos se aplican conforme a la normativa vigente.",
    keywords: ["factura", "facturación", "impuestos", "factura de empresa", "factura de particular"],
  },
  {
    id: "taksit-secenegi",
    category: "pricing",
    priority: 57,
    q: "¿Hay opción de pago fraccionado?",
    a: "En los pagos con tarjeta de crédito puede ofrecerse la posibilidad de fraccionar el pago. Las opciones de fraccionamiento disponibles se muestran en el paso de pago.",
    keywords: ["pago fraccionado", "a plazos", "pagar en cuotas", "cuotas"],
  },
  {
    id: "kurumsal-vadeli-odeme",
    category: "pricing",
    priority: 58,
    q: "¿Ofrecen plazos de pago a los clientes de empresa?",
    a: "Sí. A los clientes de empresa se les pueden ofrecer plazos de pago de hasta 15-30 días y facturación mensual. Las condiciones se establecen en el marco de la colaboración corporativa.",
    keywords: ["plazo de pago", "pago aplazado", "pago para empresas", "vencimiento de pago"],
  },
  {
    id: "odeme-yapilmadan-baslar-mi",
    category: "pricing",
    priority: 59,
    q: "¿Comienza la traducción antes del pago?",
    a: "En los pedidos estándar, la traducción comienza tras recibir el pago (o la aprobación del plazo de pago para empresas). En los acuerdos corporativos, el proceso puede desarrollarse según lo establecido en el contrato.",
    keywords: ["pago por adelantado", "antes del pago", "prepago", "sin pago"],
  },
  {
    id: "iade-sureci",
    category: "pricing",
    priority: 60,
    q: "¿Se reembolsan los pedidos cancelados?",
    a: "En los pedidos cancelados antes de que comience la traducción, se reembolsa el pago. Si el trabajo ya ha empezado, puede reembolsarse el importe restante tras descontar la parte completada. En casos como un cargo duplicado, se reembolsa el importe sobrante.",
    keywords: ["reembolso", "devolución del dinero", "reembolso por cancelación", "devolución"],
  },

  // ——— SUBIDA DE ARCHIVOS ———
  {
    id: "hangi-formatlar",
    category: "upload",
    priority: 61,
    q: "¿Qué formatos de archivo se admiten?",
    a: "Admitimos más de 50 formatos, incluidos Word (DOC/DOCX), PDF, texto sin formato (TXT), Excel, PowerPoint y los formatos de imagen habituales (JPG, PNG). En los documentos de texto, el número de palabras se extrae automáticamente.",
    keywords: ["formato de archivo", "formatos admitidos", "pdf", "doc", "docx", "txt"],
  },
  {
    id: "taranmis-fotograf-belge",
    category: "upload",
    priority: 62,
    q: "¿Se admiten documentos escaneados o fotografiados?",
    a: "Sí. Se admiten documentos escaneados y fotografías nítidas tomadas con el móvil. La legibilidad es importante; los sellos, cuños y firmas deben ser visibles. Como el texto de las imágenes puede no leerse de forma automática, nuestro equipo determina el número de palabras.",
    keywords: ["documento escaneado", "foto del documento", "foto con el móvil", "subir imagen", "fotografía"],
  },
  {
    id: "birden-fazla-dosya-yukleme",
    category: "upload",
    priority: 63,
    q: "¿Puedo subir varios archivos a la vez?",
    a: "Sí, puede subir varios archivos al mismo tiempo. El precio se calcula en función del contenido total.",
    keywords: ["subida múltiple", "varios archivos", "subir en lote", "subir a la vez"],
  },
  {
    id: "dosya-boyutu-siniri",
    category: "upload",
    priority: 64,
    q: "¿Hay un límite de tamaño de archivo? ¿Cómo envío archivos grandes?",
    a: "Puede subir hasta unos 100 MB por archivo. Para archivos de mayor tamaño, contacte con nuestra línea de atención para acordar el envío por correo electrónico u otro método alternativo.",
    keywords: ["tamaño de archivo", "límite de tamaño", "archivo grande", "100 mb"],
  },
  {
    id: "yuklenen-dosya-silinebilir",
    category: "upload",
    priority: 65,
    q: "¿Puedo eliminar o reemplazar un archivo subido?",
    a: "Sí. Antes de completar el pedido, puede eliminar el archivo que ha subido o reemplazarlo por uno nuevo.",
    keywords: ["eliminar archivo", "reemplazar archivo", "archivo incorrecto", "borrar archivo"],
  },
  {
    id: "manuel-kelime-girisi",
    category: "upload",
    priority: 66,
    q: "¿Puedo introducir el número de palabras manualmente sin subir un archivo?",
    a: "En lugar de introducir una cifra directamente, pegue su texto en la pestaña 'Introducir texto' y el número de palabras se calculará automáticamente. Así puede obtener un presupuesto preliminar sin un archivo.",
    keywords: ["recuento manual", "introducir palabras", "introducir texto", "conteo manual"],
  },
  {
    id: "dosyalar-ne-kadar-saklanir",
    category: "upload",
    priority: 67,
    q: "¿Cuánto tiempo se conservan los archivos? ¿Puedo solicitar su eliminación?",
    a: "Sus documentos se conservan de forma segura únicamente durante el tiempo que requiere el servicio. Puede solicitar la eliminación de sus documentos en cualquier momento; esta solicitud se atiende conforme a sus derechos en virtud de la KVKK.",
    keywords: ["plazo de conservación", "almacenamiento de archivos", "solicitud de eliminación", "borrar datos"],
  },
  {
    id: "belgenin-tum-sayfalari",
    category: "upload",
    priority: 68,
    q: "¿Debo subir todas las páginas y los reversos del documento?",
    a: "Sí. Para que la traducción sea completa y válida, debe subir todas las páginas del documento, incluidos los reversos cuando corresponda. Es importante que las zonas de sellos, cuños y firmas se vean con claridad.",
    keywords: ["todas las páginas", "reverso", "documento completo", "sellos y cuños"],
  },
  {
    id: "imza-kase-cevrilir-mi",
    category: "upload",
    priority: 69,
    q: "¿Se traducen los sellos, cuños y firmas?",
    a: "En una traducción jurada, el texto legible de los sellos y cuños se transcribe; las firmas se indican como \"firma presente\". Las zonas ilegibles se señalan con claridad en la traducción.",
    keywords: ["traducción de sello", "traducción de cuño", "traducción de firma", "sellos y firmas"],
  },
  {
    id: "dosya-guvenli-mi-analiz",
    category: "upload",
    priority: 70,
    q: "¿El contenido del documento está seguro durante el análisis automático?",
    a: "Sí. Los documentos se transfieren de forma cifrada, y procesos como el recuento de palabras se realizan en un entorno seguro. Su contenido no se comparte con terceros.",
    keywords: ["seguridad del análisis", "seguridad del contenido", "lectura automática", "análisis seguro"],
  },

  // ——— IDIOMAS Y PARES DE IDIOMAS ———
  {
    id: "50-dil-ne-demek",
    category: "languages",
    priority: 71,
    q: "¿Qué significa el soporte de más de 50 idiomas?",
    a: "Significa que, además de los idiomas más comunes, también podemos traducir idiomas con menor demanda. En los idiomas poco frecuentes, la disponibilidad del traductor, el plazo de entrega y el precio se confirman por separado para cada pedido.",
    keywords: ["50 idiomas", "idioma poco frecuente", "soporte de idiomas", "cuántos idiomas"],
  },
  {
    id: "yaygin-dil-ciftleri",
    category: "languages",
    priority: 72,
    q: "¿Traducen pares como turco-inglés, alemán o francés?",
    a: "Sí. Traducimos pares de idiomas comunes como turco ⇄ inglés, alemán, francés, español, italiano, árabe y ruso, en ambas direcciones. También se admiten idiomas como el chino y el japonés.",
    keywords: ["turco inglés", "inglés turco", "alemán", "francés", "par de idiomas"],
  },
  {
    id: "yabancidan-yabanciya",
    category: "languages",
    priority: 73,
    q: "¿Pueden traducir entre dos idiomas extranjeros distintos del turco?",
    a: "Sí, podemos traducir de un idioma extranjero a otro, por ejemplo del inglés al francés. La disponibilidad y el plazo se valoran según el par de idiomas.",
    keywords: ["extranjero a extranjero", "inglés francés", "entre idiomas", "idioma a idioma"],
  },
  {
    id: "nadir-dil",
    category: "languages",
    priority: 74,
    q: "¿Ofrecen servicio para idiomas poco frecuentes o que no figuran en la lista?",
    a: "Procuramos ofrecer también idiomas poco frecuentes; no obstante, la disponibilidad del traductor, el plazo y el precio se confirman por separado para estos idiomas. Si el idioma que necesita no figura en la lista, contacte con nuestra línea de atención para solicitar un presupuesto personalizado.",
    keywords: ["idioma poco frecuente", "idioma poco común", "idioma no listado", "idioma especial"],
  },
  {
    id: "dil-varyantlari",
    category: "languages",
    priority: 75,
    q: "¿Puedo elegir una variante regional del idioma (como inglés americano o británico)?",
    a: "Sí, siempre que sea posible puede indicar una variante regional del idioma de destino (por ejemplo, inglés americano o británico, español europeo o latinoamericano). Si no se especifica ninguna variante, se utiliza el estándar más común.",
    keywords: ["variante", "inglés americano", "idioma regional", "dialecto"],
  },
  {
    id: "anadili-tercuman",
    category: "languages",
    priority: 76,
    q: "¿Trabajan con traductores cuya lengua materna es el idioma de destino?",
    a: "Siempre que es posible, trabajamos con traductores experimentados y competentes en el idioma de destino. El objetivo es ofrecer una traducción natural y precisa.",
    keywords: ["traductor nativo", "hablante nativo", "experto en idioma de destino", "traductor de lengua materna"],
  },
  {
    id: "osmanlica-eski-yazi",
    category: "languages",
    priority: 77,
    q: "¿Pueden traducirse documentos en turco otomano o en escritura antigua?",
    a: "Los documentos en turco otomano y escritos en el alfabeto antiguo pueden traducirse, según la disponibilidad de un especialista. En este tipo de documentos, el plazo y el precio se confirman tras su revisión.",
    keywords: ["turco otomano", "escritura antigua", "alfabeto antiguo", "documentos antiguos"],
  },
  {
    id: "karisik-dilli-belge",
    category: "languages",
    priority: 78,
    q: "¿Puede traducirse un documento que contiene más de un idioma?",
    a: "Sí. Los documentos con varios idiomas pueden traducirse; el precio se determina según la cantidad de contenido en cada idioma. Basta con que nos indique el idioma de destino que necesita.",
    keywords: ["idioma mixto", "documento multilingüe", "varios idiomas en el documento", "documento en varios idiomas"],
  },

  // ——— TIPOS DE SERVICIO ———
  {
    id: "hangi-hizmeti-secmeliyim",
    category: "services",
    priority: 79,
    q: "¿Qué tipo de servicio debo elegir?",
    a: "El lugar donde se vaya a utilizar su documento determina el servicio: los trámites oficiales suelen requerir una traducción jurada, mientras que algunos exigen una traducción con certificación notarial o apostillada. Si tiene dudas, nuestra línea de atención o el asistente de chat pueden orientarle; el requisito final depende de la institución correspondiente.",
    keywords: ["qué servicio", "selección de servicio", "qué elegir", "elegir servicio"],
  },
  {
    id: "standart-yeminli-fark",
    category: "services",
    priority: 80,
    q: "¿Cuál es la diferencia entre la traducción estándar y la jurada?",
    a: "Una traducción estándar tiene fines informativos y carece de certificación oficial. Una traducción jurada la certifica el traductor jurado con su sello y firma, y se exige en trámites oficiales. Cuál de las dos necesita depende de la institución a la que se presentará el documento.",
    keywords: ["estándar frente a jurada", "diferencia", "traducción normal", "diferencia jurada"],
  },
  {
    id: "yeminli-noter-ayni-mi",
    category: "services",
    priority: 81,
    q: "¿Son lo mismo la traducción jurada y la traducción con certificación notarial?",
    a: "No. Una traducción jurada lleva la certificación del traductor jurado. Una traducción con certificación notarial es esa traducción certificada, además, por un notario. Algunas instituciones exigen solo la traducción jurada, mientras que otras requieren también la certificación notarial.",
    keywords: ["jurada frente a notarial", "traducción notarial", "son lo mismo", "jurada o notarial"],
  },
  {
    id: "hukuki-teknik-medikal",
    category: "services",
    priority: 82,
    q: "¿Cómo se garantiza la especialización en las traducciones jurídicas, técnicas y médicas?",
    a: "Los contratos, documentos judiciales, documentación técnica y documentos médicos los traducen traductores experimentados que dominan la terminología del área correspondiente. Los glosarios terminológicos y la memoria de traducción garantizan la coherencia, se conservan los formatos y las unidades, y la traducción pasa por un control de calidad.",
    keywords: ["traducción jurídica", "traducción técnica", "traducción médica", "traductor especializado", "terminología"],
  },
  {
    id: "akademik-bicim-korunur",
    category: "services",
    priority: 83,
    q: "¿Se conservan la bibliografía y el formato en la traducción académica?",
    a: "Sí. En tesis, artículos y textos académicos, se conservan en la medida de lo posible la disposición de la bibliografía, las citas y el formato, y la traducción se ajusta al estilo académico.",
    keywords: ["traducción académica", "tesis", "artículo", "bibliografía", "citas"],
  },
  {
    id: "lokalizasyon-nedir",
    category: "services",
    priority: 84,
    q: "¿La localización es solo traducción palabra por palabra? ¿Se tiene en cuenta el SEO?",
    a: "No. La localización consiste en adaptar el texto a la cultura y el uso de destino; la interfaz, los formatos de fecha y moneda y el tono se ajustan al público objetivo. En la localización de sitios web, si lo solicita, pueden tenerse en cuenta las palabras clave en el idioma de destino y la optimización SEO.",
    keywords: ["localización", "traducción web", "traducción de aplicaciones", "seo", "adaptación"],
  },
  {
    id: "kurumsal-marka-dili",
    category: "services",
    priority: 85,
    q: "¿Se conserva la voz de marca en los contenidos corporativos?",
    a: "Sí. En las traducciones corporativas, un banco terminológico y una guía de estilo mantienen la coherencia de la voz y el tono de su marca.",
    keywords: ["voz de marca", "tono corporativo", "guía de estilo", "identidad de marca"],
  },
  {
    id: "vize-diploma-hangi-hizmet",
    category: "services",
    priority: 86,
    q: "¿Qué servicio necesito para documentos como un visado o un diploma?",
    a: "Para las solicitudes de visado y las traducciones de diplomas y títulos, la traducción jurada suele ser el requisito básico; algunas representaciones o instituciones pueden pedir además la certificación notarial o una apostilla. El requisito exacto depende del consulado o la institución ante la que presente la solicitud.",
    keywords: ["documento de visado", "traducción de diploma", "expediente académico", "consulado", "traducción para visado"],
  },
  {
    id: "belge-turu-listede-yok",
    category: "services",
    priority: 87,
    q: "¿Qué debo seleccionar si el tipo de mi documento no figura en la lista?",
    a: "Si el tipo de su documento no figura en la lista, elija la opción más parecida y añada una aclaración en la nota del pedido. Si lo desea, nuestra línea de atención puede ayudarle a hacer la elección correcta.",
    keywords: ["tipo de documento no listado", "otro documento", "no está en la lista", "documento no listado"],
  },

  // ——— ENTREGA Y PLAZOS ———
  {
    id: "teslim-suresi-nasil-hesaplanir",
    category: "delivery",
    priority: 88,
    q: "¿Cómo se calcula el plazo de entrega y dónde se muestra?",
    a: "El plazo se calcula en función de la extensión del documento, el par de idiomas, el tipo de servicio y los servicios adicionales, y se muestra como fecha de entrega estimada en la pantalla Calcular presupuesto. En los trámites que requieren certificación notarial o apostilla, pueden añadirse días adicionales; si la fecha de entrega cambia, se le informa.",
    keywords: ["cálculo del plazo", "entrega estimada", "cuándo estará listo", "plazo estimado"],
  },
  {
    id: "ayni-gun-teslimat",
    category: "delivery",
    priority: 89,
    q: "¿Es posible la entrega en el mismo día o en 24 horas?",
    a: "En documentos breves, la entrega rápida o urgente suele ser posible; la disponibilidad depende de la extensión y el idioma del documento. Los pasos de control de calidad se mantienen incluso en la entrega urgente, y la opción se muestra como una partida adicional en la pantalla de presupuesto preliminar.",
    keywords: ["mismo día", "24 horas", "entrega rápida", "urgente"],
  },
  {
    id: "hafta-sonu-tatil",
    category: "delivery",
    priority: 90,
    q: "¿Cuándo se procesan los pedidos de fin de semana o fuera del horario laboral?",
    a: "Puede subir documentos, obtener presupuestos y crear pedidos a cualquier hora del día. Los pedidos realizados fuera del horario laboral o en días festivos se procesan al inicio del siguiente horario laboral, y el plazo de entrega estimado se muestra en consecuencia.",
    keywords: ["fin de semana", "festivo", "fuera de horario", "pedido nocturno"],
  },
  {
    id: "dijital-teslim-format",
    category: "delivery",
    priority: 91,
    q: "¿Cómo se realiza la entrega digital y en qué formato la recibo?",
    a: "La traducción terminada se entrega de forma digital a través de un enlace de descarga o por correo electrónico. Puede recibirla en PDF o en un archivo Word (DOCX) editable, según sus necesidades; el formato original se conserva en la medida de lo posible.",
    keywords: ["entrega digital", "entrega en word", "entrega en pdf", "descarga"],
  },
  {
    id: "kargo-kapsam-takip",
    category: "delivery",
    priority: 92,
    q: "¿A qué regiones envían y puedo hacer el seguimiento del envío?",
    a: "Los documentos con firma manuscrita original y sello se envían por mensajería a toda Turquía; si lo solicita, también podemos realizar envíos internacionales. La información de seguimiento del envío se comparte con usted, y el tiempo de envío se suma al plazo de entrega total.",
    keywords: ["regiones de envío", "seguimiento del envío", "envío internacional", "tiempo de envío"],
  },
  {
    id: "kismi-teslimat",
    category: "delivery",
    priority: 93,
    q: "¿Pueden entregarse por partes los proyectos largos?",
    a: "Sí. Los proyectos de gran volumen o largos pueden entregarse por secciones si lo solicita. Así puede empezar a utilizar sus documentos sin esperar.",
    keywords: ["entrega parcial", "por partes", "entrega por secciones", "entregas parciales"],
  },

  // ——— TRADUCCIÓN JURADA ———
  {
    id: "yeminli-tercuman-kim",
    category: "sworn",
    priority: 94,
    q: "¿Quién es un traductor jurado?",
    a: "Un traductor jurado es un traductor que ha prestado juramento ante un notario y que, por ello, ha obtenido la facultad de certificar sus traducciones con su firma y sello. Esta certificación es una declaración de que la traducción refleja fielmente el original.",
    keywords: ["traductor jurado", "quién es traductor jurado", "traductor certificado", "qué es un traductor jurado"],
  },
  {
    id: "yeminli-ne-zaman-gerekli",
    category: "sworn",
    priority: 95,
    q: "¿Cuándo se exige una traducción jurada?",
    a: "Las traducciones juradas se exigen con frecuencia en las solicitudes ante instituciones oficiales, tribunales, consulados y universidades. No obstante, no son obligatorias para todos los documentos; el requisito exacto lo establece la institución que solicita el documento.",
    keywords: ["cuándo se exige jurada", "es necesaria la jurada", "dónde se exige", "cuándo hace falta jurada"],
  },
  {
    id: "yeminli-nerede-gecerli",
    category: "sworn",
    priority: 96,
    q: "¿Es válida una traducción jurada ante los tribunales, en un consulado y en el extranjero?",
    a: "Una traducción jurada puede utilizarse en numerosos trámites y solicitudes oficiales. No obstante, las condiciones de una institución para aceptar un documento dependen de su propia normativa; en el extranjero, en particular, puede exigirse además la certificación notarial o una apostilla. Le recomendamos confirmar los requisitos de aceptación con la institución correspondiente.",
    keywords: ["tribunal", "consulado", "válida en el extranjero", "solicitud universitaria"],
  },
  {
    id: "dijital-imzali-yeminli",
    category: "sworn",
    priority: 97,
    q: "¿Puede emitirse una traducción jurada con firma digital o electrónica?",
    a: "No. Una traducción jurada se prepara con la firma manuscrita original y el sello del traductor, y se entrega físicamente por mensajería.",
    keywords: ["firma electrónica", "jurada digital", "firma digital", "firma manuscrita original", "sello"],
  },
  {
    id: "yeminli-orijinal-gerekir",
    category: "sworn",
    priority: 98,
    q: "¿Se necesita el documento original para una traducción jurada?",
    a: "La traducción suele poder realizarse a partir de una copia nítida del documento (escaneo o fotografía). No obstante, si se requiere la certificación notarial, para ese trámite puede solicitarse el original o una copia compulsada del documento.",
    keywords: ["documento original", "se necesita el original", "copia para la jurada", "original para jurada"],
  },
  {
    id: "yeminli-gecerlilik-suresi",
    category: "sworn",
    priority: 99,
    q: "¿Tiene fecha de caducidad una traducción jurada?",
    a: "La traducción en sí no está limitada en el tiempo; sin embargo, algunas instituciones pueden solicitar un documento con fecha reciente. Esto depende de los requisitos de la institución que aceptará el documento.",
    keywords: ["fecha de caducidad", "validez de la jurada", "cuánto tiempo válida", "caducidad de la jurada"],
  },
  {
    id: "kurum-belgeyi-kabul-etmezse",
    category: "sworn",
    priority: 100,
    q: "¿Qué ocurre si una institución no acepta la traducción jurada?",
    a: "Los requisitos de aceptación pueden variar de una institución a otra. Si la institución tiene un requisito específico de formato o de certificación, comuníquenoslo y realizaremos los ajustes necesarios. La decisión final de aceptación corresponde a la institución.",
    keywords: ["no aceptada", "rechazo de la institución", "requisito de formato", "documento rechazado"],
  },

  // ——— CERTIFICACIÓN NOTARIAL Y APOSTILLA ———
  {
    id: "noter-onayli-nedir",
    category: "notary",
    priority: 101,
    q: "¿Qué es una traducción con certificación notarial?",
    a: "Una traducción con certificación notarial es una traducción jurada que, además, certifica un notario. Esta certificación refuerza la validez oficial de la traducción y algunas instituciones la exigen.",
    keywords: ["traducción notarial", "certificación notarial", "qué es notarial", "qué es notarial", "traducción con notario"],
  },
  {
    id: "noter-yeminli-fark",
    category: "notary",
    priority: 102,
    q: "¿Cuál es la diferencia entre la certificación notarial y la traducción jurada?",
    a: "La traducción jurada lleva la certificación del traductor, mientras que la certificación notarial es la del notario sobre esa traducción. La certificación notarial es un paso oficial adicional que se añade sobre una traducción jurada.",
    keywords: ["notarial frente a jurada", "diferencia de certificación", "notarial y jurada", "diferencia notario"],
  },
  {
    id: "notere-gitmem-gerekir-mi",
    category: "notary",
    priority: 103,
    q: "¿Tengo que acudir al notario para la certificación notarial?",
    a: "En la mayoría de los casos podemos gestionar la certificación notarial en su nombre, por lo que no necesita acudir al notario en persona. Si se requiere el documento original, se lo comunicaremos con antelación.",
    keywords: ["ir al notario", "trámite notarial", "notario en mi nombre", "acudir al notario"],
  },
  {
    id: "apostil-nedir",
    category: "notary",
    priority: 104,
    q: "¿Qué es una apostilla y en qué se diferencia de la certificación notarial?",
    a: "La apostilla es una certificación internacional emitida por la autoridad competente para que un documento oficial se reconozca como válido en otro país, y es aplicable entre los países parte del Convenio de La Haya. La certificación notarial, en cambio, es una certificación dentro de un país; ambas cumplen finalidades distintas.",
    keywords: ["qué es apostilla", "apostilla frente a notario", "convenio de la haya", "qué es la apostilla"],
  },
  {
    id: "apostil-once-mi-ceviri-once-mi",
    category: "notary",
    priority: 105,
    q: "¿Qué se hace primero, la apostilla o la traducción?",
    a: "El orden depende del tipo de documento y de los requisitos del país donde se vaya a utilizar. En algunos casos, primero se apostilla el documento y luego se traduce; en otros, es al revés. Podemos determinar juntos el orden correcto.",
    keywords: ["orden de la apostilla", "primero traducción o apostilla", "secuencia", "orden apostilla traducción"],
  },
  {
    id: "yabanci-belge-turkiye",
    category: "notary",
    priority: 106,
    q: "¿Cuál es el proceso si un documento extranjero se va a utilizar en Turquía?",
    a: "Un documento procedente del extranjero suele apostillarse primero en el país de origen y, a continuación, se realiza en Turquía su traducción jurada (y la certificación notarial, si es necesaria). El proceso exacto depende de la institución turca que solicita el documento.",
    keywords: ["documento extranjero en turquía", "documento entrante", "documento del extranjero", "documento del exterior"],
  },
  {
    id: "turk-belge-yurt-disi",
    category: "notary",
    priority: 107,
    q: "¿Cuál es el proceso si un documento turco se va a utilizar en el extranjero?",
    a: "Un documento emitido en Turquía suele apostillarse y se realiza su traducción jurada al idioma de destino. Si el país de destino no es parte del Convenio de La Haya, puede ser necesaria una legalización consular en lugar de la apostilla.",
    keywords: ["documento turco en el extranjero", "documento saliente", "legalización consular", "documento hacia el extranjero"],
  },
  {
    id: "hangi-onay-gerekli-bilinmiyor",
    category: "notary",
    priority: 109,
    q: "¿Cómo averiguo si se necesita certificación notarial o apostilla?",
    a: "La forma más fiable es preguntar a la institución que solicita el documento. Si lo desea, nuestra línea de atención puede orientarle sobre las prácticas habituales; no obstante, el requisito exacto varía según la institución y el país.",
    keywords: ["qué certificación", "se necesita certificación", "notario o apostilla", "necesito notario o apostilla"],
  },
  {
    id: "kesin-kabul-garantisi",
    category: "notary",
    priority: 110,
    q: "¿TercümExpert garantiza la aceptación?",
    a: "Nos aseguramos de que la traducción y las certificaciones se preparen de forma precisa y completa; no obstante, las condiciones de aceptación de un documento las establece la institución que lo solicita. Por ese motivo, no podemos ofrecer una garantía de aceptación incondicional; si nos comunica los requisitos específicos de la institución, realizaremos los ajustes necesarios.",
    keywords: ["garantía de aceptación", "aceptación garantizada", "garantía", "aceptación garantizada institución"],
  },

  // ——— CALIDAD Y REVISIONES ———
  {
    id: "tercumanlar-nasil-secilir",
    category: "quality",
    priority: 111,
    q: "¿Cómo se seleccionan los traductores y se determina su especialización?",
    a: "Los traductores se eligen según el par de idiomas y el área de especialidad del documento; un documento jurídico se asigna a un traductor con experiencia en derecho, y uno médico a otro con experiencia en el ámbito sanitario. Se asigna el traductor más adecuado atendiendo a la experiencia en el área y la competencia lingüística.",
    keywords: ["selección de traductores", "cómo se eligen los traductores", "especialización", "experto en la materia"],
  },
  {
    id: "kalite-kontrol",
    category: "quality",
    priority: 112,
    q: "¿La traducción pasa por un control de calidad?",
    a: "Sí. Las traducciones se revisan en cuanto a ortografía, terminología, coherencia de cifras, nombres y fechas, y formato. Según el tipo de documento y el nivel de servicio, puede aplicarse un paso independiente de edición o revisión final.",
    keywords: ["control de calidad", "revisión final", "editor", "revisión"],
  },
  {
    id: "ceviri-bellegi",
    category: "quality",
    priority: 113,
    q: "¿Utilizan memoria de traducción o listas de terminología?",
    a: "Sí, especialmente en los proyectos técnicos y corporativos, se utilizan memorias de traducción y listas de terminología para garantizar la coherencia. También puede compartir su propia lista de términos; la terminología de proyectos anteriores se conserva.",
    keywords: ["memoria de traducción", "lista de terminología", "coherencia", "glosario"],
  },
  {
    id: "revize-kapsami",
    category: "quality",
    priority: 114,
    q: "¿Qué cubre una revisión y cuándo debo solicitarla?",
    a: "Una revisión cubre cuestiones como errores de traducción, ortografía, incoherencias y omisiones. Modificar el texto de origen posteriormente o añadir contenido nuevo puede considerarse un trabajo nuevo. Le recomendamos enviar su solicitud de revisión dentro de un plazo razonable tras la entrega, por correo electrónico o WhatsApp.",
    keywords: ["alcance de la revisión", "alcance de correcciones", "plazo de revisión", "cuándo revisar"],
  },
  {
    id: "tercuman-degisikligi",
    category: "quality",
    priority: 115,
    q: "¿Qué ocurre si no quedo satisfecho con la traducción? ¿Puede cambiarse el traductor?",
    a: "Si no queda satisfecho con la traducción, revisamos la situación y, si es necesario, gestionamos las correcciones con un traductor o editor distinto. El objetivo es que el resultado cumpla sus expectativas.",
    keywords: ["cambiar de traductor", "no satisfecho", "insatisfecho con la traducción", "reasignar traductor"],
  },
  {
    id: "dogruluk-garanti",
    category: "quality",
    priority: 116,
    q: "¿Se garantiza la exactitud de la traducción?",
    a: "Sus traducciones las preparan traductores expertos y pasan por un control de calidad, y ponemos el cuidado necesario en su exactitud. Dicho esto, los requisitos de aceptación oficial de un documento pueden variar según la institución que lo solicita.",
    keywords: ["garantía de exactitud", "garantía de calidad", "aseguramiento", "fiabilidad de la traducción"],
  },
  {
    id: "makine-cevirisi-kullaniliyor",
    category: "quality",
    priority: 117,
    q: "¿Utilizan traducción totalmente automática o automática por máquina?",
    a: "No. Las traducciones las realizan de principio a fin traductores humanos profesionales; no ofrecemos traducción automática por máquina. Solo se emplean herramientas TAO para favorecer la coherencia. Las traducciones juradas incluyen el sello y la firma del traductor y la declaración de fidelidad al original.",
    keywords: ["traducción automática", "traducción por máquina", "traducción con ia", "declaración de certificación"],
  },

  // ——— PRIVACIDAD Y SEGURIDAD ———
  {
    id: "dosyalari-kimler-gorur",
    category: "privacy",
    priority: 118,
    q: "¿Quién puede ver los archivos subidos y se comparten con terceros?",
    a: "Solo el traductor y el equipo asignado a su pedido pueden acceder a sus archivos. Salvo cuando el servicio lo requiere, sus documentos no se comparten con terceros ni se utilizan con fines de marketing.",
    keywords: ["quién puede verlos", "acceso", "terceros", "compartir"],
  },
  {
    id: "nda-imzalanabilir",
    category: "privacy",
    priority: 119,
    q: "¿Puede firmarse un acuerdo de confidencialidad (NDA)?",
    a: "Sí. Especialmente en los proyectos corporativos, puede formalizarse un acuerdo de confidencialidad (NDA) si lo solicita. Nuestros traductores también están sujetos a obligaciones de confidencialidad.",
    keywords: ["nda", "acuerdo de confidencialidad", "contrato de confidencialidad", "confidencialidad"],
  },
  {
    id: "kvkk-uyumlu",
    category: "privacy",
    priority: 120,
    q: "¿Trabajan conforme a la KVKK y cómo se protegen los datos personales?",
    a: "Sí. Sus datos personales se tratan mediante procesos conformes con la KVKK (ley turca de protección de datos); se utilizan únicamente en la medida en que el servicio lo requiere y se almacenan de forma segura. Nos comprometemos a proteger sus datos con las medidas de seguridad adecuadas.",
    keywords: ["kvkk", "datos personales", "protección de datos", "conforme a la kvkk"],
  },
  {
    id: "sifreli-aktarim",
    category: "privacy",
    priority: 121,
    q: "¿Los archivos se transfieren cifrados?",
    a: "Sí. Sus archivos se transfieren a través de una conexión cifrada y se procesan en un entorno seguro. Nuestro objetivo es proteger sus datos con las medidas de seguridad adecuadas.",
    keywords: ["cifrado", "transferencia segura", "encriptación", "conexión cifrada"],
  },
  {
    id: "odeme-bilgileri-saklanir",
    category: "privacy",
    priority: 122,
    q: "¿Se almacenan los datos de pago o de la tarjeta de crédito?",
    a: "TercümExpert no almacena los datos de su tarjeta; los pagos se procesan a través de una infraestructura de pago segura.",
    keywords: ["datos de pago", "seguridad de la tarjeta", "almacenamiento de la tarjeta", "seguridad del pago"],
  },
  {
    id: "belgeler-ai-egitimi",
    category: "privacy",
    priority: 123,
    q: "¿Se utilizan mis documentos para entrenar modelos?",
    a: "No. Sus documentos se utilizan únicamente para su pedido; nunca se comparten para entrenar modelos ni con sistemas externos. Su traducción la preparan traductores humanos con carácter confidencial.",
    keywords: ["entrenamiento de modelos", "uso de datos", "entrenamiento de ia", "privacidad del documento"],
  },
  {
    id: "saglik-kimlik-guvenli",
    category: "privacy",
    priority: 124,
    q: "¿Son seguros los documentos sensibles como el DNI, el pasaporte o los informes médicos?",
    a: "Sí. Todos sus archivos, incluidos los documentos sensibles, se procesan de forma confidencial, conforme a la KVKK y cifrada. El acceso se limita al equipo asignado a su pedido; para documentos de alta confidencialidad pueden aplicarse medidas adicionales como un NDA y el acceso restringido.",
    keywords: ["seguridad del dni", "pasaporte", "datos de salud", "documento sensible"],
  },
  {
    id: "hesap-silinince-belgeler",
    category: "privacy",
    priority: 125,
    q: "¿Se eliminan los documentos al eliminar la cuenta o cuando se solicita?",
    a: "A petición suya, sus documentos y datos personales se eliminan, sin perjuicio de las obligaciones legales de conservación. Puede enviar una solicitud de eliminación de cuenta o de datos a nuestra línea de atención.",
    keywords: ["eliminación de cuenta", "eliminación de datos", "borrar documentos", "borrar cuenta y datos"],
  },

  // ——— SERVICIOS PARA EMPRESAS ———
  {
    id: "kurumsal-hesap-nasil",
    category: "corporate",
    priority: 126,
    q: "¿Cómo abro una cuenta de empresa y qué ocurre después de solicitarla?",
    a: "Basta con rellenar el formulario de solicitud de nuestra página para Empresas; nuestro equipo suele ponerse en contacto con usted en un plazo de 1 día laborable, evalúa sus necesidades y establece unas condiciones adaptadas a su caso.",
    keywords: ["cuenta de empresa", "cuenta corporativa", "solicitud de empresa", "después de solicitar"],
  },
  {
    id: "sirket-adina-siparis",
    category: "corporate",
    priority: 127,
    q: "¿Puedo realizar un pedido en nombre de una empresa?",
    a: "Sí. Puede realizar un pedido con los datos de su empresa y beneficiarse de la facturación corporativa y, cuando sea necesario, de las opciones de plazos de pago.",
    keywords: ["en nombre de la empresa", "pedido corporativo", "pedido de empresa", "facturar a empresa"],
  },
  {
    id: "ozel-hesap-yoneticisi",
    category: "corporate",
    priority: 128,
    q: "¿Se asigna a los clientes de empresa un gestor de cuenta dedicado?",
    a: "A los clientes de empresa se les puede asignar un gestor de cuenta dedicado que hace el seguimiento de sus procesos. Así puede gestionar sus solicitudes desde un único punto de contacto y recibir soporte prioritario.",
    keywords: ["gestor de cuenta", "gestor dedicado", "soporte para empresas", "soporte prioritario"],
  },
  {
    id: "toplu-fatura",
    category: "corporate",
    priority: 129,
    q: "¿Puedo obtener facturación mensual consolidada y plazos de pago?",
    a: "Sí. A los clientes de empresa se les puede ofrecer facturación mensual consolidada y plazos de pago de hasta 15-30 días. Los detalles se establecen en el marco de la colaboración.",
    keywords: ["facturación consolidada", "factura mensual", "plazos de pago", "pago para empresas"],
  },
  {
    id: "terminoloji-bankasi",
    category: "corporate",
    priority: 130,
    q: "¿Puede crearse un banco terminológico específico para la empresa?",
    a: "Sí. En los proyectos corporativos se crean un banco terminológico y una guía de estilo específicos para su marca, de modo que la voz de marca y la coherencia se conserven en todas las traducciones.",
    keywords: ["banco terminológico", "guía de estilo", "terminología corporativa", "glosario de empresa"],
  },
  {
    id: "sabit-tercuman",
    category: "corporate",
    priority: 131,
    q: "¿Podemos trabajar con los mismos traductores en proyectos recurrentes?",
    a: "Sí. En los proyectos corporativos recurrentes puede configurarse un grupo fijo de traductores o un equipo dedicado para garantizar la continuidad y la coherencia.",
    keywords: ["traductor dedicado", "mismo equipo", "equipo corporativo", "traductor fijo"],
  },
  {
    id: "kurumsal-raporlama",
    category: "corporate",
    priority: 132,
    q: "¿Puedo obtener informes de pedidos y de gasto?",
    a: "A los clientes de empresa se les puede ofrecer informes de sus pedidos y de su gasto, con un desglose por departamentos si es necesario. En las colaboraciones corporativas también pueden formalizarse acuerdos de nivel de servicio (SLA) y de confidencialidad (NDA).",
    keywords: ["informes", "informe de gasto", "informe de pedidos", "sla"],
  },
  {
    id: "kucuk-isletme",
    category: "corporate",
    priority: 133,
    q: "¿Pueden las pequeñas empresas contratar los servicios corporativos? ¿Se exige un volumen mínimo?",
    a: "Sí. No existe un requisito de tamaño ni de volumen mínimo para contratar nuestros servicios corporativos; las pequeñas empresas también pueden beneficiarse de ventajas como los plazos de pago, la gestión terminológica y el soporte prioritario.",
    keywords: ["pequeña empresa", "pyme", "volumen mínimo", "se exige volumen"],
  },
  {
    id: "uluslararasi-sirket",
    category: "corporate",
    priority: 134,
    q: "¿Prestan servicio a empresas internacionales y proyectos multilingües?",
    a: "Sí. Los proyectos que abarcan varios países e idiomas pueden coordinarse y ejecutarse de forma centralizada, garantizando la coherencia terminológica en su conjunto. En los proyectos corporativos también pueden gestionarse la traducción jurada y, cuando es necesario, los trámites de certificación notarial y apostilla.",
    keywords: ["empresa internacional", "proyecto multilingüe", "notario y apostilla para empresas", "proyecto internacional"],
  },

  // ——— SOPORTE TÉCNICO ———
  {
    id: "nasil-uye-olunur",
    category: "support",
    priority: 135,
    q: "¿Cómo me registro en el sitio?",
    a: "Para registrarse, basta con introducir su nombre, apellidos y correo electrónico, y confirmar el código de verificación que reciba por correo. También puede registrarse rápidamente con su cuenta de Apple o de Google.",
    keywords: ["registrarse", "darse de alta", "crear cuenta", "registro"],
  },
  {
    id: "giris-sifre-sorunu",
    category: "support",
    priority: 136,
    q: "¿Qué hago si no puedo iniciar sesión o he olvidado mi contraseña?",
    a: "Primero, compruebe su correo electrónico y su contraseña; si ha olvidado la contraseña, utilice el enlace 'He olvidado mi contraseña' de la pantalla de inicio de sesión para recibir las instrucciones de restablecimiento por correo. Si el problema persiste, revise su carpeta de correo no deseado o contacte con nuestra línea de atención.",
    keywords: ["no puedo iniciar sesión", "restablecer contraseña", "olvidé la contraseña", "inicio de sesión", "acceder"],
  },
  {
    id: "dogrulama-epostasi-gelmezse",
    category: "support",
    priority: 137,
    q: "¿Qué hago si no llega el correo de verificación?",
    a: "Espere unos minutos, revise su carpeta de correo no deseado y vuelva a enviar el código. Asegúrese de haber introducido correctamente su dirección de correo electrónico; si el problema persiste, contacte con nuestra línea de atención.",
    keywords: ["correo de verificación", "no llega el código", "correo no llega", "código de verificación"],
  },
  {
    id: "dosya-yuklenmiyor",
    category: "support",
    priority: 138,
    q: "¿Qué hago si un archivo no se sube o recibo un error de archivo no admitido?",
    a: "Compruebe el tamaño (hasta 100 MB) y el formato del archivo, y actualice la página y su navegador. Si el formato no se admite, convierta el archivo a un formato como PDF o DOCX, o pegue el texto en la pestaña 'Introducir texto'. Si el problema persiste, contacte con nuestra línea de atención.",
    keywords: ["el archivo no se sube", "error de subida", "archivo no admitido", "error de formato"],
  },
  {
    id: "kelime-sayisi-yanlis",
    category: "support",
    priority: 139,
    q: "¿Qué hago si el número de palabras parece incorrecto?",
    a: "El recuento automático puede desviarse, especialmente en los documentos escaneados o basados en imagen. Para obtener un resultado exacto, comparta el texto mediante 'Introducir texto' o añada una nota a su pedido; el recuento final lo confirma nuestro equipo y el precio se ajusta en consecuencia.",
    keywords: ["número de palabras incorrecto", "error de recuento", "recuento erróneo", "palabras mal contadas"],
  },
  {
    id: "odeme-basarisiz",
    category: "support",
    priority: 140,
    q: "¿Qué hago si un pago falla o me cobran dos veces?",
    a: "Compruebe los datos y el límite de su tarjeta e inténtelo de nuevo; también puede utilizar otro método (tarjeta o transferencia). Si se cobró el importe pero no se creó ningún pedido, o si hubo un cargo duplicado, contacte con nuestra línea de atención con su justificante y se reembolsará el importe sobrante.",
    keywords: ["pago fallido", "error de pago", "cobrado dos veces", "cargo duplicado"],
  },
  {
    id: "teslim-dosyasi-inmiyor",
    category: "support",
    priority: 141,
    q: "¿Qué hago si el archivo entregado no se descarga?",
    a: "Actualice el enlace y su navegador; si el enlace de descarga ha caducado, puede solicitar uno nuevo a nuestra línea de atención.",
    keywords: ["el archivo no se descarga", "problema de descarga", "no puedo descargar la entrega", "enlace caducado"],
  },
  {
    id: "mobil-tarayici-destegi",
    category: "support",
    priority: 142,
    q: "¿Puedo usar el sitio en un dispositivo móvil y qué navegadores se admiten?",
    a: "El sitio es compatible con móviles; puede subir documentos y realizar pedidos desde un iPhone, un teléfono Android o una tableta. Puede utilizar el sitio sin problemas con las versiones actuales de Chrome, Safari, Edge y Firefox.",
    keywords: ["móvil", "teléfono", "iphone android", "tableta", "navegador", "chrome safari"],
  },
  {
    id: "ai-asistan-ne-yapar",
    category: "support",
    priority: 143,
    q: "¿Qué puede hacer el asistente de chat con inteligencia artificial?",
    a: "El asistente de chat ofrece orientación instantánea sobre el proceso, los tipos de servicio y las consultas generales, y le dirige a los pasos correctos, como obtener un presupuesto. No puede tomar decisiones definitivas ni vinculantes sobre los requisitos de aceptación oficial ni los requisitos legales (como la certificación notarial o la apostilla); para ello, debe consultar a la institución correspondiente.",
    keywords: ["asistente de chat", "chatbot", "asistente de ia", "precio del chatbot"],
  },
  {
    id: "insana-baglanma",
    category: "support",
    priority: 144,
    q: "¿Cómo contacto con un agente de atención al cliente humano?",
    a: "Puede solicitarlo a través del asistente de chat o contactar directamente con nuestra línea de soporte humano por WhatsApp y correo electrónico. Las solicitudes se responden en horario laboral. Enviar las incidencias técnicas con una captura de pantalla ayuda a agilizar la resolución.",
    keywords: ["contactar con una persona", "agente de atención", "atención en directo", "captura de pantalla"],
  },
  {
    id: "hesap-bilgileri-guncelleme",
    category: "support",
    priority: 145,
    q: "¿Cómo actualizo los datos de la cuenta y de facturación y cómo elimino mi cuenta?",
    a: "Si tiene una cuenta, puede actualizar su teléfono, correo electrónico y datos de facturación en la configuración de la cuenta, y también solicitar allí la eliminación de la cuenta o contactando con nuestra línea de atención. A petición suya, sus datos se eliminan, sin perjuicio de las obligaciones legales.",
    keywords: ["actualizar datos", "datos de facturación", "configuración de la cuenta", "eliminar cuenta"],
  },
  {
    id: "bildirim-tercihleri",
    category: "support",
    priority: 146,
    q: "¿Cómo funcionan las notificaciones de pedido y puedo recibir notificaciones por WhatsApp?",
    a: "Se envían notificaciones por correo electrónico sobre el estado de su pedido; según sus preferencias, también pueden proporcionarse actualizaciones por WhatsApp. Puede ajustar sus preferencias de notificación en la configuración de la cuenta o a través de nuestra línea de atención.",
    keywords: ["notificaciones", "sms", "notificación por whatsapp", "notificación por correo", "notificación de pedido"],
  },
]
