/**
 * FAQ data source (Italian). Pricing/payment logic may change later (§13).
 * Honesty rules: NO unverified ISO/certification claims; no physical office is
 * implied; no 24/7 human support is promised; the sworn / notarization /
 * apostille distinctions are preserved; no guaranteed institutional acceptance.
 * `priority` = global importance order (lower = higher up). The category view
 * uses the same order, so within-category ordering is derived from this value.
 */
import type { FaqCategory, FaqItem } from "./faq-data"

export const FAQ_CATEGORIES_IT: FaqCategory[] = [
  { key: "general", label: "Informazioni generali" },
  { key: "order", label: "Processo d'ordine" },
  { key: "pricing", label: "Prezzi e pagamento" },
  { key: "upload", label: "Caricamento dei file" },
  { key: "languages", label: "Lingue e combinazioni linguistiche" },
  { key: "services", label: "Tipi di servizio" },
  { key: "delivery", label: "Consegna e tempistiche" },
  { key: "sworn", label: "Traduzione giurata" },
  { key: "notary", label: "Autenticazione notarile e apostille" },
  { key: "quality", label: "Qualità e revisioni" },
  { key: "privacy", label: "Riservatezza e sicurezza" },
  { key: "corporate", label: "Servizi per le aziende" },
  { key: "support", label: "Assistenza tecnica" },
]

export const FAQ_ITEMS_IT: FaqItem[] = [
  // ——— ALL: highest-priority questions along the customer journey ———
  {
    id: "nasil-fiyat-alirim",
    category: "pricing",
    priority: 1,
    q: "Come ottengo un preventivo?",
    a: "Vada alla pagina Calcola il preventivo e carichi il Suo documento oppure incolli il testo; una volta selezionate la combinazione linguistica e il tipo di servizio, il preventivo preliminare compare all'istante. La tariffa dipende dalla combinazione linguistica, dal tipo di servizio, dal numero di parole e dagli eventuali servizi aggiuntivi che sceglie.",
    keywords: ["preventivo", "prezzo", "costo traduzione", "stima prezzo", "quanto costa", "calcola preventivo"],
  },
  {
    id: "dosya-nasil-yuklenir",
    category: "upload",
    priority: 2,
    q: "Come carico il mio file?",
    a: "Nella pagina Calcola il preventivo apra la scheda 'Carica file' e trascini il documento oppure lo selezioni dal Suo dispositivo. Se non dispone di un file, è sufficiente incollare il testo nella scheda 'Inserisci testo'. Per i file con testo selezionabile il sistema conta le parole in automatico.",
    keywords: ["caricare file", "aggiungere documento", "allegare file", "non riesco a caricare", "come caricare"],
  },
  {
    id: "fiyatlandirma-neye-gore",
    category: "pricing",
    priority: 3,
    q: "Come viene determinato il prezzo?",
    a: "La tariffa dipende dalla combinazione linguistica, dal tipo di servizio, dal contenuto del documento, dal numero di parole, dall'area di specializzazione e dagli eventuali servizi aggiuntivi selezionati. L'importo mostrato a schermo è un preventivo preliminare; il prezzo definitivo si conferma dopo l'esame del documento.",
    keywords: ["prezzi", "come si calcola il prezzo", "fattori di costo", "a parola", "tariffe"],
  },
  {
    id: "teslim-suresi-ne-kadar",
    category: "delivery",
    priority: 4,
    q: "Quali sono i tempi di consegna?",
    a: "I tempi di consegna dipendono dalla lunghezza del documento, dalla combinazione linguistica, dal tipo di servizio e dagli eventuali servizi aggiuntivi selezionati. La schermata del preventivo mostra una data di consegna stimata specifica per il Suo ordine. Con l'opzione di consegna urgente è possibile ridurre questi tempi.",
    keywords: ["tempi di consegna", "quando consegnate", "quanti giorni", "tempistiche", "durata"],
  },
  {
    id: "yeminli-tercume-nedir",
    category: "sworn",
    priority: 5,
    q: "Che cos'è una traduzione giurata?",
    a: "La traduzione giurata (asseverata) è una traduzione certificata da un traduttore giurato con la propria firma e il proprio timbro, che ne dichiara la conformità all'originale. Viene spesso richiesta per le pratiche ufficiali. Se sia necessaria dipende dall'ente che richiede il documento.",
    keywords: ["traduzione giurata", "traduzione asseverata", "traduzione con timbro", "traduzione ufficiale", "cos'è giurata"],
  },
  {
    id: "hangi-dillerde-hizmet",
    category: "languages",
    priority: 6,
    q: "Con quali lingue lavorate?",
    a: "Lavoriamo con il turco e con l'inglese, il tedesco, il francese, lo spagnolo, l'italiano, l'arabo, il russo e oltre 50 lingue in totale. Per le lingue rare la disponibilità del traduttore e i tempi di consegna vengono verificati separatamente per ciascun ordine.",
    keywords: ["lingue", "quali lingue", "opzioni linguistiche", "combinazioni linguistiche", "quante lingue"],
  },
  {
    id: "noter-onayi-gerekir-mi",
    category: "notary",
    priority: 7,
    q: "È necessaria l'autenticazione notarile?",
    a: "L'autenticazione notarile non è obbligatoria per ogni documento; la sua necessità dipende dall'ente che richiede il documento e dall'uso previsto. Per alcune pratiche è sufficiente una traduzione giurata (asseverata), mentre per altre serve anche l'autenticazione notarile. Se non è sicuro di quale certificazione Le occorra, possiamo aiutarLa a orientarsi.",
    keywords: ["autenticazione notarile", "notaio", "traduzione notarile", "serve il notaio"],
  },
  {
    id: "siparis-nasil-ilerler",
    category: "order",
    priority: 8,
    q: "Come si svolge il processo d'ordine?",
    a: "Dopo aver caricato il documento e approvato il preventivo preliminare, il Suo ordine viene creato e assegnato a un traduttore specializzato nel settore pertinente. La traduzione passa attraverso il controllo qualità; se necessario, viene gestita la procedura di autenticazione notarile e il documento Le viene consegnato in formato digitale e, quando richiesto, tramite corriere.",
    keywords: ["processo d'ordine", "come funziona", "fasi", "flusso di lavoro"],
  },
  {
    id: "belgelerim-guvende-mi",
    category: "privacy",
    priority: 9,
    q: "I miei documenti sono al sicuro?",
    a: "Sì. I Suoi file sono visibili solo al team che si occupa del Suo ordine e vengono gestiti tramite trasferimento cifrato e processi conformi alla KVKK (legge turca sulla protezione dei dati). I Suoi documenti non vengono mai condivisi con terzi e la riservatezza è la nostra priorità.",
    keywords: ["sicurezza", "riservatezza", "sicurezza dei documenti", "sicurezza dei dati", "kvkk"],
  },
  {
    id: "cevirimi-kim-yapar",
    category: "quality",
    priority: 10,
    q: "Chi traduce il mio documento?",
    a: "Le Sue traduzioni sono realizzate da traduttori professionisti in carne e ossa con esperienza nel settore pertinente. In base al tipo di documento viene assegnato un traduttore specializzato e ogni traduzione passa attraverso il controllo qualità prima della consegna.",
    keywords: ["chi traduce", "traduttore", "traduttore umano", "linguista", "chi lo fa"],
  },
  {
    id: "revize-hakki-var-mi",
    category: "quality",
    priority: 11,
    q: "Le revisioni sono incluse?",
    a: "Sì. Una volta consegnata la traduzione, ha diritto a richiedere revisioni per le correzioni rientranti nell'ambito originario. Le correzioni di ortografia, nomi, date o coerenza sono incluse. La modifica successiva del testo di partenza o l'aggiunta di nuovi contenuti può configurarsi come un nuovo lavoro.",
    keywords: ["revisioni", "correzioni", "revisione", "rifare traduzione", "diritto di revisione"],
  },
  {
    id: "fiziksel-teslimat-yapiliyor-mu",
    category: "delivery",
    priority: 12,
    q: "Effettuate la consegna fisica?",
    a: "Sì. Sebbene la consegna digitale sia lo standard, i documenti con firma autografa originale e timbro possono essere spediti al Suo indirizzo tramite corriere. Effettuiamo spedizioni in tutta la Turchia e, su richiesta, all'estero. Se sceglie la consegna tramite corriere, i tempi di spedizione si aggiungono a quelli di consegna.",
    keywords: ["consegna fisica", "corriere", "spedizione postale", "consegna a domicilio"],
  },
  {
    id: "kurumsal-ozel-sartlar",
    category: "corporate",
    priority: 13,
    q: "Esistono condizioni particolari per i clienti aziendali?",
    a: "Sì. I clienti aziendali beneficiano di vantaggi sugli ordini di grande volume, di opzioni sui termini di pagamento, della gestione della terminologia e di un account manager dedicato. Per i dettagli, compili il modulo di richiesta nella pagina Aziende.",
    keywords: ["aziende", "impresa", "condizioni aziendali", "ordini in blocco", "clienti aziendali"],
  },
  {
    id: "apostil-nasil-yurutulur",
    category: "notary",
    priority: 14,
    q: "Come si svolge la procedura di apostille?",
    a: "L'apostille è una certificazione rilasciata dall'autorità competente affinché un documento sia riconosciuto come valido all'estero. Non effettuiamo la procedura di apostille; deve ottenerla Lei stesso presso l'autorità competente del Paese in cui il Suo documento è stato rilasciato. Ci occupiamo esclusivamente della traduzione giurata dei Suoi documenti apostillati. Nei Paesi non aderenti alla Convenzione dell'Aia, al posto dell'apostille può essere richiesta la legalizzazione consolare.",
    keywords: ["apostille", "procedura di apostille", "legalizzazione apostille", "valido all'estero"],
  },
  {
    id: "acil-teslimat-mumkun-mu",
    category: "delivery",
    priority: 15,
    q: "È possibile la consegna urgente?",
    a: "Sì, la consegna urgente è disponibile per molti documenti e riduce i tempi di consegna. La consegna urgente comporta un supplemento e la sua disponibilità può variare in base alla lunghezza e alla lingua del documento. Anche per gli ordini urgenti vengono mantenute le fasi di controllo qualità.",
    keywords: ["consegna urgente", "consegna rapida", "in giornata", "express", "urgente"],
  },
  {
    id: "odeme-nasil-yapilir",
    category: "pricing",
    priority: 16,
    q: "Come si effettua il pagamento?",
    a: "I pagamenti possono essere effettuati con carta di credito/debito oppure con bonifico bancario; per le carte di credito possono essere disponibili opzioni di rateizzazione. Ai clienti aziendali viene inoltre offerta la fatturazione con termine di pagamento (15-30 giorni). Il pagamento viene incassato dopo che Lei ha approvato il preventivo preliminare.",
    keywords: ["pagamento", "metodo di pagamento", "carta di credito", "bonifico", "come pagare"],
  },
  {
    id: "dosya-yuklemeden-fiyat",
    category: "upload",
    priority: 17,
    q: "Posso ottenere un preventivo senza caricare un file?",
    a: "Sì. Se non dispone di un file, incolli il testo nella scheda 'Inserisci testo' per ottenere un preventivo preliminare basato sul numero di parole.",
    keywords: ["preventivo senza file", "preventivo da testo", "senza caricamento", "preventivo da testo incollato"],
  },
  {
    id: "belgenin-formati-korunur-mu",
    category: "delivery",
    priority: 18,
    q: "Viene mantenuta la formattazione del documento?",
    a: "Per quanto possibile, manteniamo nella traduzione l'impaginazione originale, le tabelle e la formattazione. In base alle Sue esigenze, il risultato può essere consegnato in formato PDF o Word (DOCX) modificabile. Per i documenti scansionati o basati su immagini forniamo un'impaginazione ordinata e pulita, anziché una replica identica.",
    keywords: ["formattazione", "impaginazione", "layout della pagina", "word", "pdf", "formato mantenuto"],
  },
  {
    id: "teslim-sonrasi-destek",
    category: "quality",
    priority: 19,
    q: "Posso ricevere assistenza dopo la consegna della traduzione?",
    a: "Sì. Dopo la consegna è disponibile il supporto per le revisioni relative alle correzioni rientranti nell'ambito previsto e può contattare il nostro servizio clienti per qualsiasi domanda. Può inviarci eventuali richieste aggiuntive sul Suo documento via e-mail o WhatsApp.",
    keywords: ["assistenza post consegna", "supporto dopo consegna", "aiuto", "assistenza"],
  },
  {
    id: "cok-sayfali-yuksek-hacim",
    category: "order",
    priority: 20,
    q: "Come vengono gestiti i progetti di grande volume o con molte pagine?",
    a: "I progetti di grande volume vengono pianificati con cura; quando serve, vi lavorano più traduttori ed editor e si utilizza un glossario condiviso per la coerenza terminologica. I progetti lunghi possono essere consegnati per parti (consegna parziale), se lo preferisce. Nei progetti aziendali il processo è coordinato dal Suo account manager.",
    keywords: ["molte pagine", "grande volume", "lavoro in blocco", "progetto ampio", "documenti multipli"],
  },

  // ——— GENERAL ———
  {
    id: "tercumexpert-nedir",
    category: "general",
    priority: 21,
    q: "Che cos'è TercümExpert?",
    a: "TercümExpert è un fornitore di servizi di traduzione online che offre traduzione giurata (asseverata), traduzione con autenticazione notarile, traduzione legale, tecnica, medica e accademica, oltre alla localizzazione web e mobile. Può caricare il Suo documento, ottenere un preventivo preliminare ed effettuare l'ordine interamente online.",
    keywords: ["tercumexpert", "cos'è", "chi siamo", "servizio di traduzione", "di cosa vi occupate"],
  },
  {
    id: "hangi-hizmetler",
    category: "general",
    priority: 22,
    q: "Quali servizi offre TercümExpert?",
    a: "Offriamo traduzione giurata (asseverata) e con autenticazione notarile, traduzione di documenti apostillati, traduzione legale, tecnica, medica e accademica, oltre alla localizzazione di siti web e app mobili. Può scegliere il servizio più adatto alle Sue esigenze nella schermata Calcola il preventivo.",
    keywords: ["servizi", "cosa offrite", "tipi di servizio", "quali servizi"],
  },
  {
    id: "kimler-hizmet-alabilir",
    category: "general",
    priority: 23,
    q: "Chi può usufruire dei vostri servizi?",
    a: "Possono usufruire dei nostri servizi sia i clienti privati sia le aziende e gli enti. Dagli studenti ai liberi professionisti, dalle piccole imprese alle grandi realtà, offriamo soluzioni su misura per esigenze diverse.",
    keywords: ["chi può", "privati", "aziende", "imprese", "clienti"],
  },
  {
    id: "ofise-gelmek-gerekir-mi",
    category: "general",
    priority: 24,
    q: "È necessario recarsi di persona in un ufficio?",
    a: "No, non disponiamo di un ufficio fisico; i nostri servizi vengono erogati interamente online. Le basta inviarci i Suoi documenti tramite caricamento sicuro, e la consegna avviene in formato digitale e, quando richiesto, tramite corriere. Per qualsiasi domanda può contattarci su WhatsApp o all'indirizzo info@tercumexpert.com.",
    keywords: ["ufficio", "di persona", "filiale", "indirizzo", "serve recarsi"],
  },
  {
    id: "surec-cevrimici-mi",
    category: "general",
    priority: 25,
    q: "L'intero processo può essere gestito online?",
    a: "Sì. Il caricamento dei documenti, l'approvazione del preventivo, il pagamento e la consegna digitale avvengono tutti online. Il corriere interviene soltanto quando è necessario un documento fisico con firma autografa originale.",
    keywords: ["online", "tutto online", "a distanza", "via internet", "interamente online"],
  },
  {
    id: "yurt-disindan-hizmet",
    category: "general",
    priority: 26,
    q: "I clienti all'estero possono usufruire dei vostri servizi?",
    a: "Sì. Poiché il processo è online, può caricare documenti ed effettuare ordini dall'estero. La consegna digitale è disponibile ovunque e, per i documenti con firma autografa originale, possiamo anche spedire all'estero tramite corriere.",
    keywords: ["estero", "clienti internazionali", "dall'estero", "fuori dalla turchia"],
  },
  {
    id: "uyelik-zorunlu-mu",
    category: "general",
    priority: 27,
    q: "È necessario registrarsi per usufruire dei servizi?",
    a: "La registrazione non è obbligatoria. Tuttavia, per visualizzare il prezzo ed effettuare un ordine deve inserire nome, cognome ed e-mail, quindi confermare il codice di verifica inviato alla Sua e-mail. Se lo desidera, può creare un account per tenere traccia dello storico dei Suoi ordini.",
    keywords: ["account", "registrazione", "iscrizione", "obbligatorio", "senza registrazione"],
  },
  {
    id: "uye-olmadan-fiyat",
    category: "general",
    priority: 28,
    q: "Posso ottenere un preventivo senza registrarmi?",
    a: "Sì, può ottenere un preventivo senza creare un account completo; deve solo verificare nome, cognome ed e-mail. Gli utenti che non completano la verifica non possono visualizzare il prezzo né effettuare un ordine.",
    keywords: ["preventivo senza account", "senza registrazione", "codice di verifica", "verifica e-mail"],
  },
  {
    id: "siparis-oncesi-danismanlik",
    category: "general",
    priority: 29,
    q: "Posso ricevere una consulenza prima di effettuare un ordine?",
    a: "Sì. Se non è sicuro di quale servizio Le occorra, può richiedere informazioni tramite WhatsApp, e-mail o il nostro assistente chat basato su intelligenza artificiale. La aiuteremo a individuare il servizio e il processo più adatti al tipo del Suo documento.",
    keywords: ["consulenza", "informazioni", "fare una domanda", "aiuto prima dell'ordine"],
  },
  {
    id: "musteri-temsilcisi",
    category: "general",
    priority: 30,
    q: "Come contatto un operatore del servizio clienti?",
    a: "Può contattare il nostro servizio clienti tramite WhatsApp o e-mail. Le Sue domande vengono gestite da un operatore durante l'orario di lavoro; inoltre il nostro assistente chat basato su intelligenza artificiale può fornire in qualsiasi momento un primo orientamento.",
    keywords: ["operatore", "assistenza", "contatto", "come contattarvi", "supporto"],
  },
  {
    id: "hangi-belgeler-cevrilebilir",
    category: "general",
    priority: 31,
    q: "Quali tipi di documenti possono essere tradotti?",
    a: "Traduciamo un'ampia gamma di documenti, da quelli ufficiali e personali ai testi commerciali, legali, tecnici, medici e accademici. Sono supportati molti tipi di documento, tra cui diplomi, contratti, relazioni, manuali e contenuti per siti web.",
    keywords: ["tipi di documento", "quali documenti", "documenti", "cosa si può tradurre"],
  },
  {
    id: "yapay-zeka-mi-insan-mi",
    category: "general",
    priority: 32,
    q: "Le traduzioni sono realizzate da traduttori umani?",
    a: "Sì. Le Sue traduzioni sono realizzate dall'inizio alla fine da traduttori professionisti in carne e ossa. Per favorire la coerenza e la terminologia ci avvaliamo del supporto di strumenti CAT, ma l'intera traduzione è opera di traduttori esperti e passa attraverso il controllo qualità.",
    keywords: ["traduttore umano", "strumento cat", "strumenti di traduzione", "traduzione automatica", "chi traduce"],
  },
  {
    id: "el-yazili-belgeler",
    category: "general",
    priority: 33,
    q: "È possibile tradurre documenti manoscritti o di difficile lettura?",
    a: "I documenti manoscritti e di difficile lettura possono essere tradotti purché siano leggibili. Le eventuali parti illeggibili vengono chiaramente segnalate nella traduzione e, se necessario, potremmo chiederLe una copia più nitida. Per questi documenti il prezzo si conferma dopo l'esame.",
    keywords: ["manoscritto", "scritto a mano", "illeggibile", "poco chiaro", "difficile da leggere"],
  },
  {
    id: "farkiniz-nedir",
    category: "general",
    priority: 34,
    q: "Che cosa distingue TercümExpert dagli altri servizi di traduzione?",
    a: "Il nostro processo interamente online, i preventivi preliminari automatici, i traduttori specialisti in carne e ossa e il controllo qualità sono i nostri punti di forza. Inoltre consegniamo i documenti con firma autografa originale direttamente a domicilio tramite corriere.",
    keywords: ["differenza", "vantaggio", "perché tercumexpert", "cosa vi distingue"],
  },

  // ——— ORDER PROCESS ———
  {
    id: "siparis-nasil-verilir",
    category: "order",
    priority: 35,
    q: "Come effettuo un ordine?",
    a: "Nella schermata Calcola il preventivo carichi il documento o inserisca il testo, selezioni la combinazione linguistica e il tipo di servizio, quindi approvi il preventivo preliminare. Una volta approvato, il Suo ordine viene creato.",
    keywords: ["effettuare ordine", "come ordinare", "creare ordine", "come fare un ordine", "procedura ordine"],
  },
  {
    id: "siparis-icin-gerekli-bilgiler",
    category: "order",
    priority: 36,
    q: "Quali informazioni servono per effettuare un ordine?",
    a: "Servono il documento o il testo da tradurre, la lingua di partenza e quella di arrivo, il tipo di servizio e il Suo nome ed e-mail per i contatti. Con queste informazioni può creare il Suo ordine.",
    keywords: ["informazioni necessarie", "cosa serve", "dettagli dell'ordine", "dati richiesti", "cosa serve per ordinare"],
  },
  {
    id: "dil-cifti-nasil-secilir",
    category: "order",
    priority: 37,
    q: "Come scelgo la combinazione linguistica e il tipo di servizio?",
    a: "Nella schermata Calcola il preventivo seleziona dal menu la lingua di partenza (la lingua del documento), la lingua di arrivo (la lingua della traduzione) e il tipo di servizio (giurata, con autenticazione notarile, tecnica, ecc.). Se ha dei dubbi, il nostro servizio clienti o l'assistente chat possono orientarLa verso la scelta corretta.",
    keywords: ["scegliere combinazione linguistica", "lingua di partenza", "lingua di arrivo", "selezionare servizio"],
  },
  {
    id: "bilgiler-degistirilebilir-mi",
    category: "order",
    priority: 38,
    q: "Posso modificare i dettagli dopo aver creato un ordine?",
    a: "I dettagli come la lingua, il tipo di servizio o il documento possono essere aggiornati prima che inizi la traduzione. Le basta contattare il nostro servizio clienti il prima possibile; una volta avviato il lavoro, il margine per le modifiche può ridursi.",
    keywords: ["modificare dettagli", "correggere ordine", "aggiornare ordine", "lingua sbagliata", "documento sbagliato"],
  },
  {
    id: "onaydan-once-iptal",
    category: "order",
    priority: 39,
    q: "Posso annullare un ordine prima che venga approvato?",
    a: "Sì. Può annullare il Suo ordine prima che il pagamento e l'approvazione siano completati; in questa fase non viene applicato alcun addebito.",
    keywords: ["annullare", "annullare ordine", "rinunciare", "annullamento prima dell'approvazione", "cancellare ordine"],
  },
  {
    id: "odeme-sonrasi-iptal",
    category: "order",
    priority: 40,
    q: "Un ordine può essere annullato dopo il pagamento?",
    a: "Se il Suo ordine non è ancora stato preso in carico da un traduttore, può annullarlo dalla Sua pagina dell'ordine o all'indirizzo info@tercumexpert.com, e il pagamento Le viene interamente rimborsato con lo stesso metodo utilizzato. Una volta che la traduzione è stata presa in carico da un traduttore, il rimborso non viene effettuato, in ragione della natura personale della prestazione.",
    keywords: ["annullamento dopo pagamento", "rimborso", "restituzione denaro", "annullare dopo aver pagato", "cancellare ordine pagato"],
  },
  {
    id: "siparis-durumu-takip",
    category: "order",
    priority: 41,
    q: "Dove posso seguire lo stato del mio ordine?",
    a: "Viene informato sullo stato del Suo ordine via e-mail e, se ha creato un account, può seguirlo anche da lì. Può inoltre chiedere l'aggiornamento più recente al nostro servizio clienti.",
    keywords: ["seguire ordine", "stato", "tracciamento ordine", "stato dell'ordine"],
  },
  {
    id: "birden-fazla-belge",
    category: "order",
    priority: 42,
    q: "Un unico ordine può includere più documenti o lingue di arrivo?",
    a: "Sì, può caricare più documenti in un unico ordine e far tradurre lo stesso documento in più lingue. Il numero totale di parole e ciascuna lingua di arrivo vengono tariffati come traduzioni separate e il processo è coordinato all'interno di un'unica richiesta.",
    keywords: ["documenti multipli", "più file", "più lingue", "diverse lingue"],
  },
  {
    id: "sonradan-dosya-eklenebilir",
    category: "order",
    priority: 43,
    q: "Posso aggiungere un nuovo file a un ordine in un secondo momento?",
    a: "Può aggiungere un nuovo file prima che inizi la traduzione; in tal caso il prezzo viene aggiornato in base al contenuto aggiunto. I documenti aggiunti dopo l'avvio del lavoro possono essere trattati come una nuova voce.",
    keywords: ["aggiungere file", "aggiungere dopo", "nuovo file", "aggiungere documento all'ordine", "file aggiuntivo"],
  },
  {
    id: "eksik-belge-gonderilirse",
    category: "order",
    priority: 44,
    q: "Cosa succede se invio un documento incompleto?",
    a: "Quando notiamo la mancanza di una pagina o di un documento, Le chiediamo di completarlo. Caricare tutte le pagine del documento è importante affinché la traduzione sia completa e valida.",
    keywords: ["documento incompleto", "pagina mancante", "documento mancante", "pagine mancanti", "documento parziale"],
  },
  {
    id: "terminoloji-not-referans",
    category: "order",
    priority: 45,
    q: "Posso aggiungere note, terminologia o file di riferimento specifici per l'ordine?",
    a: "Sì. Durante l'ordine può aggiungere istruzioni particolari, termini preferiti o una nota sullo stile e caricare file di riferimento come traduzioni precedenti e glossari. Queste informazioni vengono trasmesse al traduttore e utilizzate per la coerenza.",
    keywords: ["aggiungere nota", "istruzioni particolari", "terminologia", "file di riferimento", "glossario"],
  },
  {
    id: "eski-siparisler-goruntulenir",
    category: "order",
    priority: 46,
    q: "Posso accedere agli ordini e ai file passati in un secondo momento?",
    a: "Se ha creato un account, può consultare da lì gli ordini passati e i file consegnati. Per gli ordini effettuati senza account può accedere ai Suoi dati via e-mail; se un link di download è scaduto, può richiederne uno nuovo al nostro servizio clienti.",
    keywords: ["ordini passati", "storico ordini", "ordini precedenti", "accesso ai file"],
  },

  // ——— PRICING & PAYMENT ———
  {
    id: "kelime-mi-sayfa-mi",
    category: "pricing",
    priority: 47,
    q: "Tariffate a parola o a pagina?",
    a: "La tariffazione avviene di solito in base al numero di parole e al servizio selezionato. Per i documenti con testo selezionabile il numero di parole viene estratto in automatico; per i documenti scansionati o basati su immagini il conteggio viene confermato dopo l'esame.",
    keywords: ["a parola", "a pagina", "base di calcolo", "come si tariffa"],
  },
  {
    id: "sabit-baslangic-ucreti",
    category: "pricing",
    priority: 48,
    q: "Esiste una tariffa minima o un costo di partenza fisso?",
    a: "Alcuni servizi possono prevedere una tariffa minima, che può applicarsi ai documenti brevi. Il prezzo definitivo è determinato dal contenuto del documento e dai servizi selezionati e può visualizzare tutte le voci nella schermata del preventivo preliminare.",
    keywords: ["costo di partenza", "minimo", "tariffa fissa", "tariffa minima"],
  },
  {
    id: "neler-fiyati-etkiler",
    category: "pricing",
    priority: 49,
    q: "La combinazione linguistica, il tipo di documento e l'area di specializzazione influiscono sul prezzo?",
    a: "Sì. La combinazione linguistica (in particolare le lingue rare), il tipo di documento e l'area di specializzazione (legale, medica, tecnica, ecc.) possono influire sulla densità terminologica e quindi sul prezzo. Per le lingue comuni la tariffazione è più prevedibile.",
    keywords: ["prezzo combinazione linguistica", "prezzo tipo di documento", "prezzo specializzazione", "perché i prezzi variano"],
  },
  {
    id: "yeminli-daha-pahali-mi",
    category: "pricing",
    priority: 50,
    q: "La traduzione giurata è più costosa?",
    a: "La traduzione giurata (asseverata) può essere tariffata in modo diverso rispetto alla traduzione standard, per via della certificazione e della responsabilità del traduttore. L'importo esatto viene mostrato nella schermata del preventivo preliminare in base al documento e alla combinazione linguistica.",
    keywords: ["prezzo traduzione giurata", "costo giurata", "giurata più costosa", "tariffa asseverazione", "quanto costa la giurata"],
  },
  {
    id: "noter-apostil-ucreti-dahil",
    category: "pricing",
    priority: 51,
    q: "Le spese di autenticazione notarile e di apostille sono incluse nel prezzo?",
    a: "L'autenticazione notarile è una procedura distinta svolta dalle autorità competenti e soggetta a tariffe ufficiali; questo costo viene indicato separatamente dalla tariffa di traduzione e, poiché segue una tariffa ufficiale, può non essere esatto in anticipo, con l'importo effettivo confermato al termine della procedura. La procedura di apostille, invece, non viene svolta da noi; deve ottenerla Lei stesso presso l'autorità competente, e ci limitiamo a tradurre il Suo documento apostillato.",
    keywords: ["spese notarili", "spese apostille", "sono incluse", "costo notaio", "costo apostille"],
  },
  {
    id: "on-fiyat-nihai-fark",
    category: "pricing",
    priority: 52,
    q: "Il preventivo preliminare può differire dal prezzo definitivo?",
    a: "Sì. Il calcolo automatico che vede a schermo è un preventivo preliminare. Dopo un esame basato sul numero di parole, sulla leggibilità o sul tipo di documento, il prezzo definitivo può essere confermato. L'importo definitivo Le viene comunicato prima che Lei approvi.",
    keywords: ["preventivo preliminare", "prezzo definitivo", "differenza di prezzo", "prezzo esatto"],
  },
  {
    id: "otomatik-kelime-sayimi",
    category: "pricing",
    priority: 53,
    q: "Il numero di parole viene calcolato in automatico? E per i PDF scansionati?",
    a: "Per i documenti con testo selezionabile (Word, PDF di testo, testo semplice) il numero di parole viene estratto in automatico. Per i PDF scansionati o basati su immagini e per le foto il conteggio automatico può non essere affidabile, perciò il nostro team conferma il conteggio. Il preventivo preliminare si basa sul conteggio automatico e non è vincolante; in caso di scostamento, il prezzo definitivo viene confermato con Lei.",
    keywords: ["conteggio parole", "conteggio automatico", "pdf scansionato", "pdf immagine", "errore di conteggio"],
  },
  {
    id: "toplu-kurumsal-indirim",
    category: "pricing",
    priority: 54,
    q: "Sono previsti sconti per ordini di grande volume o clienti aziendali?",
    a: "Per i lavori di grande volume e ricorrenti, in particolare per i clienti aziendali, possiamo offrire tariffe vantaggiose e opzioni sui termini di pagamento in base al volume e alle condizioni di collaborazione. Per i dettagli, utilizzi il modulo di richiesta della pagina Aziende.",
    keywords: ["sconto volume", "sconto quantità", "prezzi aziendali", "tariffe imprese"],
  },
  {
    id: "ucretsiz-teklif",
    category: "pricing",
    priority: 55,
    q: "Posso ottenere un preventivo gratuito e per quanto tempo è valido?",
    a: "Il preventivo preliminare è gratuito; lo vede all'istante quando carica il documento o inserisce il testo. I preventivi sono validi per un breve periodo, purché le condizioni (contenuto/ambito del documento) non cambino.",
    keywords: ["preventivo gratuito", "stima gratuita", "validità preventivo", "quanto è valido"],
  },
  {
    id: "fatura-kesiliyor-mu",
    category: "pricing",
    priority: 56,
    q: "Emettete fattura? Posso avere una fattura per privati o aziendale?",
    a: "Sì. Per il servizio viene emessa fattura e può richiedere una fattura per privati o aziendale. Ai clienti aziendali può essere offerta anche la fatturazione mensile riepilogativa. Le imposte vengono applicate in conformità alla normativa vigente.",
    keywords: ["fattura", "fatturazione", "iva", "fattura aziendale", "fattura per privati"],
  },
  {
    id: "taksit-secenegi",
    category: "pricing",
    priority: 57,
    q: "Sono disponibili opzioni di rateizzazione?",
    a: "Per i pagamenti con carta di credito possono essere disponibili opzioni di rateizzazione. Gli eventuali piani rateali idonei vengono mostrati nella fase di pagamento.",
    keywords: ["rate", "pagamento a rate", "rateizzazione", "pagare a rate", "piano rateale"],
  },
  {
    id: "kurumsal-vadeli-odeme",
    category: "pricing",
    priority: 58,
    q: "Offrite termini di pagamento ai clienti aziendali?",
    a: "Sì. Ai clienti aziendali possono essere offerti termini di pagamento fino a 15-30 giorni e la fatturazione mensile. Le condizioni vengono definite nell'ambito dell'accordo aziendale.",
    keywords: ["termini di pagamento", "pagamento dilazionato", "pagamento aziendale", "dilazione aziendale", "pagamento a 30 giorni"],
  },
  {
    id: "odeme-yapilmadan-baslar-mi",
    category: "pricing",
    priority: 59,
    q: "La traduzione inizia prima del pagamento?",
    a: "Per gli ordini standard la traduzione inizia dopo aver ricevuto il pagamento (o l'approvazione del termine di pagamento aziendale). Per gli accordi aziendali il processo può procedere secondo quanto previsto dal contratto.",
    keywords: ["pagamento anticipato", "prima del pagamento", "anticipo", "senza pagamento"],
  },
  {
    id: "iade-sureci",
    category: "pricing",
    priority: 60,
    q: "Vengono emessi rimborsi per gli ordini annullati?",
    a: "Se il Suo ordine viene annullato prima di essere preso in carico da un traduttore, il pagamento Le viene interamente rimborsato con lo stesso metodo utilizzato. Una volta che la traduzione è stata presa in carico da un traduttore, il rimborso non viene effettuato, in ragione della natura personale della prestazione. In casi come un doppio addebito o un addebito erroneo, viene rimborsato l'importo in eccesso.",
    keywords: ["rimborso", "restituzione denaro", "rimborso annullamento", "rimborso ordine"],
  },

  // ——— FILE UPLOAD ———
  {
    id: "hangi-formatlar",
    category: "upload",
    priority: 61,
    q: "Quali formati di file sono supportati?",
    a: "Accettiamo oltre 50 formati, tra cui Word (DOC/DOCX), PDF, testo semplice (TXT), Excel, PowerPoint e i comuni formati immagine (JPG, PNG). Per i documenti con testo selezionabile il numero di parole viene estratto in automatico.",
    keywords: ["formato file", "formati supportati", "pdf", "doc", "docx", "txt"],
  },
  {
    id: "taranmis-fotograf-belge",
    category: "upload",
    priority: 62,
    q: "Accettate documenti scansionati o fotografie?",
    a: "Sì. Sono accettati i documenti scansionati e le foto nitide scattate con il telefono. La leggibilità è importante; timbri, sigilli e firme devono essere visibili. Poiché il testo nelle immagini può non essere letto in automatico, il nostro team determina il numero di parole.",
    keywords: ["documento scansionato", "foto del documento", "foto da telefono", "caricamento immagine", "immagine"],
  },
  {
    id: "birden-fazla-dosya-yukleme",
    category: "upload",
    priority: 63,
    q: "Posso caricare più file contemporaneamente?",
    a: "Sì, può caricare più file allo stesso tempo. Il prezzo viene calcolato in base al contenuto complessivo.",
    keywords: ["caricamento multiplo", "più file", "caricamento in blocco", "caricare più documenti", "upload multiplo"],
  },
  {
    id: "dosya-boyutu-siniri",
    category: "upload",
    priority: 64,
    q: "Esiste un limite di dimensione del file? Come invio file di grandi dimensioni?",
    a: "Può caricare fino a circa 100 MB per file. Per file più grandi contatti il nostro servizio clienti per concordare l'invio via e-mail o con un metodo alternativo.",
    keywords: ["dimensione file", "limite di dimensione", "file grande", "100 mb"],
  },
  {
    id: "yuklenen-dosya-silinebilir",
    category: "upload",
    priority: 65,
    q: "Posso eliminare o sostituire un file caricato?",
    a: "Sì. Prima che l'ordine sia completato, può rimuovere il file caricato o sostituirlo con uno nuovo.",
    keywords: ["eliminare file", "sostituire file", "file sbagliato", "rimuovere documento", "cambiare file caricato"],
  },
  {
    id: "manuel-kelime-girisi",
    category: "upload",
    priority: 66,
    q: "Posso inserire manualmente il numero di parole senza caricare un file?",
    a: "Anziché inserire direttamente un numero, incolli il testo nella scheda 'Inserisci testo' e il numero di parole viene calcolato in automatico. In questo modo può ottenere un preventivo preliminare senza un file.",
    keywords: ["conteggio manuale", "inserire parole", "inserire testo", "numero parole a mano", "preventivo senza file"],
  },
  {
    id: "dosyalar-ne-kadar-saklanir",
    category: "upload",
    priority: 67,
    q: "Per quanto tempo vengono conservati i file e posso richiederne l'eliminazione?",
    a: "I Suoi documenti vengono conservati in modo sicuro solo per il tempo necessario al servizio. Può richiedere l'eliminazione dei Suoi documenti in qualsiasi momento; questa richiesta viene evasa nel rispetto dei Suoi diritti ai sensi della KVKK.",
    keywords: ["periodo di conservazione", "conservazione file", "richiesta di eliminazione", "cancellazione dati"],
  },
  {
    id: "belgenin-tum-sayfalari",
    category: "upload",
    priority: 68,
    q: "Devo caricare tutte le pagine e i retro del documento?",
    a: "Sì. Affinché la traduzione sia completa e valida, deve caricare tutte le pagine del documento, compresi i retro ove presenti. È importante che le aree con sigilli, timbri e firme siano chiaramente visibili.",
    keywords: ["tutte le pagine", "retro", "documento completo", "sigilli e timbri"],
  },
  {
    id: "imza-kase-cevrilir-mi",
    category: "upload",
    priority: 69,
    q: "Timbri, sigilli e firme vengono tradotti?",
    a: "In una traduzione giurata, il testo leggibile su timbri e sigilli viene trascritto; le firme vengono indicate con la dicitura “firma presente”. Le eventuali aree illeggibili vengono chiaramente segnalate nella traduzione.",
    keywords: ["traduzione timbro", "traduzione sigillo", "traduzione firma", "timbri e sigilli", "firma presente"],
  },
  {
    id: "dosya-guvenli-mi-analiz",
    category: "upload",
    priority: 70,
    q: "Il contenuto del mio documento è al sicuro durante l'analisi automatica?",
    a: "Sì. I documenti vengono trasferiti in forma cifrata e operazioni come il conteggio delle parole avvengono in un ambiente sicuro. Il Suo contenuto non viene mai condiviso con terzi.",
    keywords: ["sicurezza analisi", "sicurezza contenuto", "lettura automatica", "documento al sicuro", "analisi automatica sicura"],
  },

  // ——— LANGUAGES & LANGUAGE PAIRS ———
  {
    id: "50-dil-ne-demek",
    category: "languages",
    priority: 71,
    q: "Cosa significa il supporto di oltre 50 lingue?",
    a: "Significa che, oltre alle lingue comuni, possiamo tradurre anche lingue meno richieste. Per le lingue rare la disponibilità del traduttore, i tempi di consegna e il prezzo vengono verificati separatamente per ciascun ordine.",
    keywords: ["50 lingue", "lingua rara", "supporto linguistico", "quante lingue"],
  },
  {
    id: "yaygin-dil-ciftleri",
    category: "languages",
    priority: 72,
    q: "Traducete combinazioni come turco-inglese, tedesco e francese?",
    a: "Sì. Traduciamo le combinazioni linguistiche comuni come turco ⇄ inglese, tedesco, francese, spagnolo, italiano, arabo e russo in entrambe le direzioni. Sono supportate anche lingue come il cinese e il giapponese.",
    keywords: ["turco inglese", "inglese turco", "tedesco", "francese", "combinazione linguistica"],
  },
  {
    id: "yabancidan-yabanciya",
    category: "languages",
    priority: 73,
    q: "Potete tradurre tra due lingue straniere diverse dal turco?",
    a: "Sì, possiamo tradurre da una lingua straniera a un'altra, ad esempio dall'inglese al francese. La disponibilità e i tempi di consegna vengono valutati in base alla combinazione linguistica.",
    keywords: ["da straniera a straniera", "inglese francese", "tra lingue straniere", "lingua straniera a lingua straniera", "senza turco"],
  },
  {
    id: "nadir-dil",
    category: "languages",
    priority: 74,
    q: "Offrite servizi per lingue rare o non presenti in elenco?",
    a: "Cerchiamo di offrire anche le lingue rare; tuttavia, per queste lingue la disponibilità del traduttore, i tempi di consegna e il prezzo vengono verificati separatamente. Se la lingua che Le occorre non è in elenco, contatti il nostro servizio clienti per richiedere un preventivo personalizzato.",
    keywords: ["lingua rara", "lingua poco comune", "lingua non in elenco", "lingua particolare"],
  },
  {
    id: "dil-varyantlari",
    category: "languages",
    priority: 75,
    q: "Posso scegliere una variante regionale della lingua (come inglese americano o britannico)?",
    a: "Sì, ove possibile può specificare una variante regionale della lingua di arrivo (ad es. inglese americano/britannico, spagnolo europeo/latinoamericano). Se non viene specificata alcuna variante, si utilizza lo standard comune.",
    keywords: ["variante", "inglese americano", "lingua regionale", "dialetto"],
  },
  {
    id: "anadili-tercuman",
    category: "languages",
    priority: 76,
    q: "Lavorate con traduttori madrelingua nella lingua di arrivo?",
    a: "Ove possibile, lavoriamo con traduttori esperti e competenti nella lingua di arrivo. L'obiettivo è offrire una traduzione naturale e accurata.",
    keywords: ["traduttore madrelingua", "madrelingua", "esperto lingua di arrivo", "traduttore nativo", "competenza linguistica"],
  },
  {
    id: "osmanlica-eski-yazi",
    category: "languages",
    priority: 77,
    q: "È possibile tradurre documenti in turco ottomano o in grafia antica?",
    a: "Il turco ottomano e i documenti scritti nell'alfabeto antico possono essere tradotti, in base alla disponibilità di uno specialista. Per questi documenti i tempi di consegna e il prezzo si confermano dopo l'esame.",
    keywords: ["turco ottomano", "grafia antica", "alfabeto antico", "documento antico", "scrittura antica"],
  },
  {
    id: "karisik-dilli-belge",
    category: "languages",
    priority: 78,
    q: "Un documento può essere tradotto se contiene più di una lingua?",
    a: "Sì. I documenti in più lingue possono essere tradotti; il prezzo si basa sulla quantità di contenuto in ciascuna lingua. Le basta indicarci la lingua di arrivo che Le occorre.",
    keywords: ["più lingue", "documento multilingue", "più lingue nel documento", "documento misto", "lingue miste"],
  },

  // ——— SERVICE TYPES ———
  {
    id: "hangi-hizmeti-secmeliyim",
    category: "services",
    priority: 79,
    q: "Quale tipo di servizio devo scegliere?",
    a: "L'uso a cui è destinato il documento determina il servizio: le pratiche ufficiali richiedono in genere una traduzione giurata (asseverata), mentre alcune procedure richiedono una traduzione con autenticazione notarile o con apostille. Se ha dei dubbi, il nostro servizio clienti o l'assistente chat possono orientarLa; il requisito definitivo dipende dall'ente pertinente.",
    keywords: ["quale servizio", "scelta del servizio", "cosa scegliere", "tipo di servizio", "quale traduzione scegliere"],
  },
  {
    id: "standart-yeminli-fark",
    category: "services",
    priority: 80,
    q: "Qual è la differenza tra traduzione standard e traduzione giurata?",
    a: "La traduzione standard ha scopo informativo e non comporta alcuna certificazione ufficiale. La traduzione giurata (asseverata), invece, è certificata con il timbro e la firma del traduttore giurato ed è richiesta per le pratiche ufficiali. Quale sia necessaria dipende dall'ente a cui verrà presentato il documento.",
    keywords: ["standard e giurata", "differenza", "traduzione normale", "differenza giurata"],
  },
  {
    id: "yeminli-noter-ayni-mi",
    category: "services",
    priority: 81,
    q: "La traduzione giurata e la traduzione con autenticazione notarile sono la stessa cosa?",
    a: "No. La traduzione giurata reca la certificazione del traduttore giurato. La traduzione con autenticazione notarile è quella stessa traduzione ulteriormente certificata da un notaio. Alcuni enti richiedono solo una traduzione giurata, mentre altri richiedono anche l'autenticazione notarile.",
    keywords: ["giurata e notarile", "traduzione notarile", "sono la stessa cosa", "differenza giurata notarile", "asseverata o notarile"],
  },
  {
    id: "hukuki-teknik-medikal",
    category: "services",
    priority: 82,
    q: "Come viene garantita la competenza nelle traduzioni legali, tecniche e mediche?",
    a: "Contratti, documenti giudiziari, documentazione tecnica e documenti medici vengono tradotti da traduttori esperti che conoscono la terminologia del settore pertinente. I glossari terminologici e la memoria di traduzione garantiscono la coerenza, i formati e le unità di misura vengono mantenuti e la traduzione passa attraverso il controllo qualità.",
    keywords: ["traduzione legale", "traduzione tecnica", "traduzione medica", "traduttore specializzato", "terminologia"],
  },
  {
    id: "akademik-bicim-korunur",
    category: "services",
    priority: 83,
    q: "Nella traduzione accademica vengono mantenuti la bibliografia e la formattazione?",
    a: "Sì. In tesi, articoli e testi accademici l'impostazione della bibliografia, le citazioni e la formattazione vengono mantenute per quanto possibile e la traduzione segue lo stile accademico.",
    keywords: ["traduzione accademica", "tesi", "articolo", "bibliografia", "citazioni"],
  },
  {
    id: "lokalizasyon-nedir",
    category: "services",
    priority: 84,
    q: "La localizzazione è solo traduzione parola per parola? Si tiene conto della SEO?",
    a: "No. La localizzazione consiste nell'adattare il testo alla cultura e all'uso di destinazione; l'interfaccia, i formati di data/valuta e il tono vengono adeguati al pubblico di arrivo. Nella localizzazione dei siti web, su richiesta si possono considerare le parole chiave nella lingua di arrivo e l'allineamento SEO.",
    keywords: ["localizzazione", "traduzione sito web", "traduzione app", "seo", "localizzare"],
  },
  {
    id: "kurumsal-marka-dili",
    category: "services",
    priority: 85,
    q: "Nei contenuti aziendali viene mantenuta l'identità verbale del marchio?",
    a: "Sì. Nelle traduzioni aziendali un database terminologico e una guida di stile mantengono coerenti l'identità verbale del Suo marchio e il tono.",
    keywords: ["identità verbale del marchio", "tono aziendale", "guida di stile", "coerenza del marchio", "voce del brand"],
  },
  {
    id: "vize-diploma-hangi-hizmet",
    category: "services",
    priority: 86,
    q: "Quale servizio serve per documenti come un visto o un diploma?",
    a: "Per le richieste di visto e le traduzioni di diplomi, il requisito principale è di solito una traduzione giurata (asseverata); alcune rappresentanze o enti possono richiedere anche l'autenticazione notarile o un'apostille. Il requisito esatto dipende dal consolato o dall'ente a cui presenta la domanda.",
    keywords: ["documento per visto", "traduzione diploma", "certificato di laurea", "consolato", "traduzione visto"],
  },
  {
    id: "belge-turu-listede-yok",
    category: "services",
    priority: 87,
    q: "Cosa devo selezionare se il tipo del mio documento non è in elenco?",
    a: "Se il tipo del Suo documento non è in elenco, scelga l'opzione più simile e aggiunga una spiegazione nella nota dell'ordine. Se lo desidera, il nostro servizio clienti può aiutarLa a fare la scelta giusta.",
    keywords: ["tipo documento non in elenco", "altro documento", "non in elenco", "documento non presente", "opzione più simile"],
  },

  // ——— DELIVERY & TURNAROUND ———
  {
    id: "teslim-suresi-nasil-hesaplanir",
    category: "delivery",
    priority: 88,
    q: "Come vengono calcolati i tempi di consegna e dove sono indicati?",
    a: "I tempi di consegna vengono calcolati in base alla lunghezza del documento, alla combinazione linguistica, al tipo di servizio e agli eventuali servizi aggiuntivi e sono indicati come data di consegna stimata nella schermata Calcola il preventivo. Per le procedure che richiedono l'autenticazione notarile o un'apostille possono aggiungersi giorni supplementari; se la data di consegna cambia, viene informato.",
    keywords: ["calcolo tempi di consegna", "consegna stimata", "quando è pronto", "data di consegna", "tempi di consegna"],
  },
  {
    id: "ayni-gun-teslimat",
    category: "delivery",
    priority: 89,
    q: "È possibile la consegna in giornata o entro 24 ore?",
    a: "Per i documenti brevi la consegna rapida/urgente è spesso possibile; la disponibilità dipende dalla lunghezza e dalla lingua del documento. Anche per la consegna urgente vengono mantenute le fasi di controllo qualità e l'opzione è indicata come voce aggiuntiva nella schermata del preventivo preliminare.",
    keywords: ["in giornata", "24 ore", "consegna rapida", "urgente"],
  },
  {
    id: "hafta-sonu-tatil",
    category: "delivery",
    priority: 90,
    q: "Quando vengono elaborati gli ordini del fine settimana o fuori dall'orario di lavoro?",
    a: "Può caricare documenti, ottenere preventivi e creare ordini a qualsiasi ora. Gli ordini effettuati fuori dall'orario di lavoro o nei giorni festivi vengono elaborati all'inizio dell'orario di lavoro successivo e i tempi di consegna stimati vengono mostrati di conseguenza.",
    keywords: ["fine settimana", "giorno festivo", "fuori orario", "ordine notturno"],
  },
  {
    id: "dijital-teslim-format",
    category: "delivery",
    priority: 91,
    q: "Come avviene la consegna digitale e in quale formato la ricevo?",
    a: "La traduzione completata viene consegnata in formato digitale tramite un link di download o via e-mail. Può riceverla in formato PDF o Word (DOCX) modificabile in base alle Sue esigenze; la formattazione originale viene mantenuta per quanto possibile.",
    keywords: ["consegna digitale", "consegna word", "consegna pdf", "download"],
  },
  {
    id: "kargo-kapsam-takip",
    category: "delivery",
    priority: 92,
    q: "In quali aree effettuate spedizioni e posso tracciare la spedizione?",
    a: "I documenti con firma autografa originale e timbro vengono spediti tramite corriere in tutta la Turchia; su richiesta possiamo spedire anche all'estero. Le informazioni di tracciamento del corriere Le vengono comunicate e i tempi di spedizione si aggiungono ai tempi di consegna complessivi.",
    keywords: ["aree di spedizione", "tracciamento corriere", "spedizione internazionale", "tempi di spedizione"],
  },
  {
    id: "kismi-teslimat",
    category: "delivery",
    priority: 93,
    q: "I progetti lunghi possono essere consegnati per parti?",
    a: "Sì. I progetti di grande volume o lunghi possono essere consegnati per sezioni su richiesta. In questo modo può iniziare a utilizzare i Suoi documenti senza attendere.",
    keywords: ["consegna parziale", "per parti", "consegna a sezioni", "consegna a tappe", "progetto lungo"],
  },

  // ——— SWORN TRANSLATION ———
  {
    id: "yeminli-tercuman-kim",
    category: "sworn",
    priority: 94,
    q: "Chi è un traduttore giurato?",
    a: "Il traduttore giurato è un traduttore che ha prestato giuramento dinanzi a un notaio e ha così acquisito il potere di certificare le proprie traduzioni con firma e timbro. Questa certificazione è una dichiarazione che la traduzione riflette fedelmente l'originale.",
    keywords: ["traduttore giurato", "chi è il traduttore giurato", "traduttore certificato", "giuramento traduttore", "traduttore asseveratore"],
  },
  {
    id: "yeminli-ne-zaman-gerekli",
    category: "sworn",
    priority: 95,
    q: "Quando è richiesta una traduzione giurata?",
    a: "Le traduzioni giurate (asseverate) sono spesso richieste per le pratiche presso enti ufficiali, tribunali, consolati e università. Tuttavia, non sono obbligatorie per ogni documento; il requisito esatto è stabilito dall'ente che richiede il documento.",
    keywords: ["quando serve la giurata", "serve la giurata", "dove è richiesta", "traduzione giurata obbligatoria", "quando è necessaria"],
  },
  {
    id: "yeminli-nerede-gecerli",
    category: "sworn",
    priority: 96,
    q: "Una traduzione giurata è valida in tribunale, presso un consolato e all'estero?",
    a: "Una traduzione giurata può essere utilizzata in molte procedure e pratiche ufficiali. Tuttavia, le condizioni di accettazione di un documento da parte di un ente dipendono dalla sua stessa normativa; all'estero in particolare possono essere richieste anche l'autenticazione notarile o un'apostille. Consigliamo di verificare i requisiti di accettazione presso l'ente pertinente.",
    keywords: ["tribunale", "consolato", "valido all'estero", "domanda universitaria"],
  },
  {
    id: "dijital-imzali-yeminli",
    category: "sworn",
    priority: 97,
    q: "Una traduzione giurata può essere rilasciata con firma digitale/elettronica?",
    a: "No. La traduzione giurata viene predisposta con la firma autografa originale e il timbro del traduttore e viene consegnata fisicamente tramite corriere.",
    keywords: ["firma elettronica", "giurata digitale", "firma digitale", "firma autografa originale", "timbro"],
  },
  {
    id: "yeminli-orijinal-gerekir",
    category: "sworn",
    priority: 98,
    q: "Per una traduzione giurata è richiesto il documento originale?",
    a: "La traduzione può di solito essere eseguita da una copia nitida (scansione o foto) del documento. Tuttavia, se è richiesta l'autenticazione notarile, per quella procedura può essere richiesto l'originale o una copia autenticata del documento.",
    keywords: ["documento originale", "serve l'originale", "copia per la giurata", "originale per asseverazione", "scansione o originale"],
  },
  {
    id: "yeminli-gecerlilik-suresi",
    category: "sworn",
    priority: 99,
    q: "Una traduzione giurata ha una data di scadenza?",
    a: "La traduzione in sé non ha limiti di tempo; tuttavia, alcuni enti possono richiedere un documento con data recente. Ciò dipende dai requisiti dell'ente che accetterà il documento.",
    keywords: ["data di scadenza", "validità giurata", "quanto è valida", "scadenza traduzione", "validità nel tempo"],
  },
  {
    id: "kurum-belgeyi-kabul-etmezse",
    category: "sworn",
    priority: 100,
    q: "Cosa succede se un ente non accetta la traduzione giurata?",
    a: "I requisiti di accettazione possono variare da ente a ente. Se l'ente ha un requisito specifico di formato o certificazione, ce lo comunichi e apporteremo le modifiche necessarie. La decisione finale sull'accettazione spetta all'ente.",
    keywords: ["non accettata", "rifiuto dell'ente", "requisito di formato", "documento respinto", "ente non accetta"],
  },

  // ——— NOTARIZATION & APOSTILLE ———
  {
    id: "noter-onayli-nedir",
    category: "notary",
    priority: 101,
    q: "Che cos'è una traduzione con autenticazione notarile?",
    a: "La traduzione con autenticazione notarile è una traduzione giurata (asseverata) ulteriormente certificata da un notaio. Questa certificazione rafforza la validità ufficiale della traduzione ed è richiesta da alcuni enti.",
    keywords: ["traduzione notarile", "autenticazione notarile", "cos'è la notarile", "traduzione con notaio", "certificazione notaio"],
  },
  {
    id: "noter-yeminli-fark",
    category: "notary",
    priority: 102,
    q: "Qual è la differenza tra l'autenticazione notarile e una traduzione giurata?",
    a: "La traduzione giurata reca la certificazione del traduttore, mentre l'autenticazione notarile è la certificazione di quella traduzione da parte del notaio. L'autenticazione notarile è un passaggio ufficiale aggiuntivo che si sovrappone a una traduzione giurata.",
    keywords: ["notarile e giurata", "differenza di certificazione", "notaio o giurata", "asseverazione e notaio", "differenza notarile giurata"],
  },
  {
    id: "notere-gitmem-gerekir-mi",
    category: "notary",
    priority: 103,
    q: "Devo recarmi dal notaio per l'autenticazione notarile?",
    a: "Nella maggior parte dei casi possiamo gestire l'autenticazione notarile per Suo conto, così non deve recarsi di persona dal notaio. Se è richiesto il documento originale, La informeremo in anticipo.",
    keywords: ["andare dal notaio", "procedura notarile", "notaio per mio conto", "recarsi dal notaio", "notaio senza presenza"],
  },
  {
    id: "apostil-nedir",
    category: "notary",
    priority: 104,
    q: "Che cos'è un'apostille e in cosa differisce dall'autenticazione notarile?",
    a: "L'apostille è una certificazione internazionale rilasciata dall'autorità competente affinché un documento ufficiale sia riconosciuto come valido in un altro Paese e si applica tra i Paesi aderenti alla Convenzione dell'Aia. L'autenticazione notarile, invece, è una certificazione all'interno di un Paese; le due hanno finalità diverse.",
    keywords: ["cos'è l'apostille", "apostille e notaio", "convenzione dell'aia", "apostille differenza", "validità internazionale"],
  },
  {
    id: "apostil-once-mi-ceviri-once-mi",
    category: "notary",
    priority: 105,
    q: "Cosa viene prima, l'apostille o la traduzione?",
    a: "L'ordine dipende dal tipo di documento e dai requisiti del Paese in cui verrà utilizzato. In alcuni casi il documento viene prima apostillato e poi tradotto; in altri l'ordine è inverso. Possiamo individuare insieme la sequenza corretta.",
    keywords: ["ordine apostille", "prima traduzione o prima apostille", "sequenza", "apostille prima o dopo", "ordine dei passaggi"],
  },
  {
    id: "yabanci-belge-turkiye",
    category: "notary",
    priority: 106,
    q: "Qual è la procedura se un documento straniero verrà utilizzato in Turchia?",
    a: "Un documento proveniente dall'estero viene di solito prima apostillato nel Paese d'origine, quindi tradotto in modo giurato (e, se necessario, autenticato dal notaio) in Turchia. La procedura esatta dipende dall'ente turco che richiede il documento.",
    keywords: ["documento straniero in turchia", "documento in entrata", "documento dall'estero", "apostille estera", "uso in turchia"],
  },
  {
    id: "turk-belge-yurt-disi",
    category: "notary",
    priority: 107,
    q: "Qual è la procedura se un documento turco verrà utilizzato all'estero?",
    a: "Un documento emesso in Turchia viene di solito apostillato e tradotto in modo giurato nella lingua di arrivo. Se il Paese di destinazione non aderisce alla Convenzione dell'Aia, al posto dell'apostille può essere richiesta la legalizzazione consolare.",
    keywords: ["documento turco all'estero", "documento in uscita", "legalizzazione consolare", "apostille per l'estero", "uso all'estero"],
  },
  {
    id: "hangi-onay-gerekli-bilinmiyor",
    category: "notary",
    priority: 109,
    q: "Come faccio a sapere se è necessaria l'autenticazione notarile o un'apostille?",
    a: "Il modo più affidabile è chiedere all'ente che richiede il documento. Se lo desidera, il nostro servizio clienti può indicarLe le prassi più comuni; tuttavia il requisito esatto varia in base all'ente e al Paese.",
    keywords: ["quale certificazione", "serve una certificazione", "notaio o apostille", "come sapere la certificazione", "requisito dell'ente"],
  },
  {
    id: "kesin-kabul-garantisi",
    category: "notary",
    priority: 110,
    q: "TercümExpert garantisce l'accettazione?",
    a: "Ci assicuriamo che la traduzione e le certificazioni siano predisposte in modo accurato e completo; tuttavia, le condizioni di accettazione di un documento sono stabilite dall'ente che lo richiede. Per questo motivo non possiamo offrire una garanzia di accettazione incondizionata; se ci comunica i requisiti specifici dell'ente, apporteremo le modifiche necessarie.",
    keywords: ["garanzia di accettazione", "accettazione garantita", "garanzia", "documento accettato", "garanzia dell'ente"],
  },

  // ——— QUALITY & REVISIONS ———
  {
    id: "tercumanlar-nasil-secilir",
    category: "quality",
    priority: 111,
    q: "Come vengono selezionati i traduttori e come si determina la loro competenza?",
    a: "I traduttori vengono scelti in base alla combinazione linguistica e all'area di specializzazione del documento; un documento legale va a un traduttore esperto in diritto e un documento medico a uno esperto in ambito sanitario. Il traduttore più adatto viene assegnato tenendo conto dell'esperienza nel settore e della competenza linguistica.",
    keywords: ["selezione traduttore", "come si scelgono i traduttori", "competenza", "esperto di settore"],
  },
  {
    id: "kalite-kontrol",
    category: "quality",
    priority: 112,
    q: "La traduzione passa attraverso il controllo qualità?",
    a: "Sì. Le traduzioni vengono verificate per ortografia, terminologia, coerenza di numeri/nomi/date e formattazione. In base al tipo di documento e al livello di servizio può essere applicata una fase di editing/revisione indipendente.",
    keywords: ["controllo qualità", "revisione", "editor", "verifica"],
  },
  {
    id: "ceviri-bellegi",
    category: "quality",
    priority: 113,
    q: "Utilizzate memorie di traduzione o elenchi terminologici?",
    a: "Sì, soprattutto nei progetti tecnici e aziendali, si utilizzano memorie di traduzione ed elenchi terminologici per garantire la coerenza. Può anche condividere il Suo elenco di termini; la terminologia dei progetti precedenti viene mantenuta.",
    keywords: ["memoria di traduzione", "elenco terminologico", "coerenza", "glossario", "terminologia coerente"],
  },
  {
    id: "revize-kapsami",
    category: "quality",
    priority: 114,
    q: "Cosa copre una revisione e quando devo richiederla?",
    a: "Una revisione copre aspetti come errori di traduzione, ortografia, incoerenze e omissioni. La modifica successiva del testo di partenza o l'aggiunta di nuovi contenuti può configurarsi come un nuovo lavoro. Consigliamo di inviare la richiesta di revisione entro un tempo ragionevole dalla consegna, via e-mail o WhatsApp.",
    keywords: ["ambito della revisione", "ambito delle correzioni", "termine per la revisione", "quando richiedere la revisione"],
  },
  {
    id: "tercuman-degisikligi",
    category: "quality",
    priority: 115,
    q: "Cosa succede se non sono soddisfatto della traduzione: il traduttore può essere cambiato?",
    a: "Se non è soddisfatto della traduzione, esaminiamo la situazione e, se necessario, disponiamo le correzioni con un traduttore o un editor diverso. L'obiettivo è che il risultato soddisfi le Sue aspettative.",
    keywords: ["cambiare traduttore", "non soddisfatto", "insoddisfatto della traduzione", "cambio traduttore", "traduzione non soddisfacente"],
  },
  {
    id: "dogruluk-garanti",
    category: "quality",
    priority: 116,
    q: "L'accuratezza della traduzione è garantita?",
    a: "Le Sue traduzioni sono predisposte da traduttori esperti e passano attraverso il controllo qualità e mettiamo la cura necessaria per l'accuratezza. Ciò detto, i requisiti di accettazione ufficiale di un documento possono variare a seconda dell'ente che lo richiede.",
    keywords: ["garanzia di accuratezza", "garanzia di qualità", "garanzia", "traduzione accurata", "affidabilità traduzione"],
  },
  {
    id: "makine-cevirisi-kullaniliyor",
    category: "quality",
    priority: 117,
    q: "Utilizzate la traduzione automatica interamente automatizzata?",
    a: "No. Le traduzioni sono realizzate dall'inizio alla fine da traduttori professionisti in carne e ossa; non offriamo traduzione automatica. Ci avvaliamo solo di strumenti CAT per favorire la coerenza. Le traduzioni giurate includono il timbro, la firma e la dichiarazione di fedeltà all'originale del traduttore.",
    keywords: ["traduzione automatica", "traduzione automatizzata", "traduzione ia", "dichiarazione di certificazione"],
  },

  // ——— PRIVACY & SECURITY ———
  {
    id: "dosyalari-kimler-gorur",
    category: "privacy",
    priority: 118,
    q: "Chi può vedere i file caricati e vengono condivisi con terzi?",
    a: "Solo il traduttore e il team pertinente che si occupa del Suo ordine possono accedere ai Suoi file. Tranne quando il servizio lo richiede, i Suoi documenti non vengono mai condivisi con terzi né utilizzati per finalità di marketing.",
    keywords: ["chi può vedere", "accesso", "terzi", "condivisione"],
  },
  {
    id: "nda-imzalanabilir",
    category: "privacy",
    priority: 119,
    q: "È possibile firmare un accordo di riservatezza (NDA)?",
    a: "Sì. Soprattutto per i progetti aziendali, su richiesta è possibile predisporre un accordo di riservatezza (NDA). Anche i nostri traduttori sono vincolati da obblighi di riservatezza.",
    keywords: ["nda", "accordo di riservatezza", "accordo di non divulgazione", "patto di riservatezza", "riservatezza contrattuale"],
  },
  {
    id: "kvkk-uyumlu",
    category: "privacy",
    priority: 120,
    q: "Operate in conformità alla KVKK e come vengono protetti i dati personali?",
    a: "Sì. I Suoi dati personali vengono trattati tramite processi conformi alla KVKK (legge turca sulla protezione dei dati); vengono utilizzati solo nella misura necessaria al servizio e conservati in modo sicuro. Ci impegniamo a proteggere i Suoi dati con misure di sicurezza adeguate.",
    keywords: ["kvkk", "dati personali", "protezione dei dati", "conforme alla kvkk"],
  },
  {
    id: "sifreli-aktarim",
    category: "privacy",
    priority: 121,
    q: "I file vengono trasferiti in modo cifrato?",
    a: "Sì. I Suoi file vengono trasferiti tramite una connessione cifrata e trattati in un ambiente sicuro. Il nostro obiettivo è proteggere i Suoi dati con misure di sicurezza adeguate.",
    keywords: ["cifrato", "trasferimento sicuro", "crittografia", "connessione cifrata", "invio sicuro file"],
  },
  {
    id: "odeme-bilgileri-saklanir",
    category: "privacy",
    priority: 122,
    q: "I dati di pagamento/della carta di credito vengono conservati?",
    a: "I dati della Sua carta non vengono conservati da TercümExpert; i pagamenti vengono elaborati tramite un'infrastruttura di pagamento sicura.",
    keywords: ["dati di pagamento", "sicurezza carta di credito", "conservazione carta", "dati carta salvati", "pagamento sicuro"],
  },
  {
    id: "belgeler-ai-egitimi",
    category: "privacy",
    priority: 123,
    q: "I miei documenti vengono utilizzati per l'addestramento di modelli?",
    a: "No. I Suoi documenti vengono utilizzati solo per il Suo ordine; non vengono mai condivisi per alcun addestramento di modelli né con sistemi esterni. La Sua traduzione viene predisposta da traduttori in carne e ossa in regime di riservatezza.",
    keywords: ["addestramento modelli", "uso dei dati", "addestramento ia", "riservatezza documenti"],
  },
  {
    id: "saglik-kimlik-guvenli",
    category: "privacy",
    priority: 124,
    q: "I documenti sensibili come carte d'identità, passaporti o cartelle cliniche sono al sicuro?",
    a: "Sì. Tutti i Suoi file, compresi i documenti sensibili, vengono trattati in regime di riservatezza, in modo conforme alla KVKK e cifrato. L'accesso è limitato al team che si occupa del Suo ordine; per i documenti altamente riservati possono essere applicate misure aggiuntive come un NDA e l'accesso limitato.",
    keywords: ["sicurezza carta d'identità", "passaporto", "dati sanitari", "documento sensibile"],
  },
  {
    id: "hesap-silinince-belgeler",
    category: "privacy",
    priority: 125,
    q: "I documenti vengono eliminati alla cancellazione dell'account o su richiesta?",
    a: "Su Sua richiesta, i Suoi documenti e dati personali vengono eliminati, fatti salvi eventuali obblighi legali di conservazione. Può inviare una richiesta di cancellazione dell'account o di eliminazione dei dati al nostro servizio clienti.",
    keywords: ["cancellazione account", "eliminazione dati", "eliminare documenti", "cancellare dati", "rimozione documenti"],
  },

  // ——— CORPORATE SERVICES ———
  {
    id: "kurumsal-hesap-nasil",
    category: "corporate",
    priority: 126,
    q: "Come apro un account aziendale e cosa succede dopo la richiesta?",
    a: "Le basta compilare il modulo di richiesta nella pagina Aziende; il nostro team di solito La contatta entro 1 giorno lavorativo, valuta le Sue esigenze e definisce condizioni su misura per Lei.",
    keywords: ["account aziendale", "account impresa", "richiesta aziendale", "dopo la richiesta"],
  },
  {
    id: "sirket-adina-siparis",
    category: "corporate",
    priority: 127,
    q: "Posso effettuare un ordine per conto di un'azienda?",
    a: "Sì. Può effettuare un ordine con i dati della Sua azienda e usufruire della fatturazione aziendale e, quando necessario, delle opzioni sui termini di pagamento.",
    keywords: ["per conto dell'azienda", "ordine aziendale", "ordine impresa", "ordinare per l'azienda", "fatturazione aziendale"],
  },
  {
    id: "ozel-hesap-yoneticisi",
    category: "corporate",
    priority: 128,
    q: "Ai clienti aziendali viene assegnato un account manager dedicato?",
    a: "Ai clienti aziendali può essere assegnato un account manager dedicato che segue i loro processi. In questo modo può gestire le Sue richieste da un unico punto di contatto e ricevere assistenza prioritaria.",
    keywords: ["account manager", "responsabile dedicato", "assistenza aziendale", "assistenza prioritaria"],
  },
  {
    id: "toplu-fatura",
    category: "corporate",
    priority: 129,
    q: "Posso ottenere la fatturazione mensile riepilogativa e i termini di pagamento?",
    a: "Sì. Ai clienti aziendali possono essere offerte la fatturazione mensile riepilogativa e termini di pagamento fino a 15-30 giorni. I dettagli vengono definiti nell'ambito dell'accordo.",
    keywords: ["fatturazione riepilogativa", "fattura mensile", "termini di pagamento", "pagamento aziendale"],
  },
  {
    id: "terminoloji-bankasi",
    category: "corporate",
    priority: 130,
    q: "È possibile creare un database terminologico specifico per l'azienda?",
    a: "Sì. Per i progetti aziendali vengono creati un database terminologico e una guida di stile specifici per il Suo marchio, così che l'identità verbale del marchio e la coerenza siano mantenute in tutte le traduzioni.",
    keywords: ["database terminologico", "guida di stile", "terminologia aziendale", "glossario aziendale", "terminologia del marchio"],
  },
  {
    id: "sabit-tercuman",
    category: "corporate",
    priority: 131,
    q: "Possiamo lavorare con gli stessi traduttori nei progetti ricorrenti?",
    a: "Sì. Per i progetti aziendali ricorrenti è possibile costituire un pool dedicato di traduttori/team per garantire continuità e coerenza.",
    keywords: ["traduttore dedicato", "stesso team", "team aziendale", "traduttore fisso", "continuità traduttore"],
  },
  {
    id: "kurumsal-raporlama",
    category: "corporate",
    priority: 132,
    q: "Posso ottenere report sugli ordini e sulle spese?",
    a: "Ai clienti aziendali possono essere offerti report su ordini e spese, con una ripartizione a livello di reparto se necessario. Per le collaborazioni aziendali è possibile predisporre anche accordi sul livello di servizio (SLA) e di riservatezza (NDA).",
    keywords: ["reportistica", "report spese", "report ordini", "sla"],
  },
  {
    id: "kucuk-isletme",
    category: "corporate",
    priority: 133,
    q: "Le piccole imprese possono usufruire dei servizi per le aziende ed è richiesto un volume minimo?",
    a: "Sì. Non è richiesta alcuna dimensione minima o volume minimo per usufruire dei nostri servizi per le aziende; anche le piccole imprese possono beneficiare di vantaggi come i termini di pagamento, la gestione della terminologia e l'assistenza prioritaria.",
    keywords: ["piccola impresa", "pmi", "volume minimo", "serve un volume"],
  },
  {
    id: "uluslararasi-sirket",
    category: "corporate",
    priority: 134,
    q: "Servite aziende internazionali e progetti multilingue?",
    a: "Sì. I progetti che coinvolgono più Paesi e lingue possono essere coordinati e gestiti in modo centralizzato, con coerenza terminologica garantita su tutta la linea. Per i progetti aziendali è possibile gestire anche la traduzione giurata e, ove necessario, le procedure di autenticazione notarile.",
    keywords: ["azienda internazionale", "progetto multilingue", "notaio apostille aziendale", "progetti multipaese", "coordinamento multilingue"],
  },

  // ——— TECHNICAL SUPPORT ———
  {
    id: "nasil-uye-olunur",
    category: "support",
    priority: 135,
    q: "Come mi registro al sito?",
    a: "Per registrarsi le basta inserire nome, cognome ed e-mail, quindi confermare il codice di verifica inviato alla Sua e-mail. Può anche registrarsi rapidamente con il Suo account Apple o Google.",
    keywords: ["registrarsi", "iscrizione", "creare account", "registrazione al sito", "account apple google"],
  },
  {
    id: "giris-sifre-sorunu",
    category: "support",
    priority: 136,
    q: "Cosa devo fare se non riesco ad accedere o ho dimenticato la password?",
    a: "Per prima cosa verifichi e-mail e password; se ha dimenticato la password, utilizzi il link 'Password dimenticata' nella schermata di accesso per inviare le istruzioni di reimpostazione alla Sua e-mail. Se il problema persiste, controlli la cartella spam o contatti il nostro servizio clienti.",
    keywords: ["non riesco ad accedere", "reimpostare password", "password dimenticata", "login", "accesso"],
  },
  {
    id: "dogrulama-epostasi-gelmezse",
    category: "support",
    priority: 137,
    q: "Cosa devo fare se l'e-mail di verifica non arriva?",
    a: "Attenda qualche minuto, controlli la cartella spam/posta indesiderata e invii nuovamente il codice. Si assicuri di aver inserito correttamente l'indirizzo e-mail; se il problema persiste, contatti il nostro servizio clienti.",
    keywords: ["e-mail di verifica", "codice non ricevuto", "e-mail non arriva", "codice di verifica"],
  },
  {
    id: "dosya-yuklenmiyor",
    category: "support",
    priority: 138,
    q: "Cosa devo fare se un file non si carica o ricevo un errore di file non supportato?",
    a: "Verifichi la dimensione (fino a 100 MB) e il formato del file, quindi aggiorni la pagina e il browser. Se il formato non è supportato, converta il file in un formato come PDF o DOCX, oppure incolli il testo nella scheda 'Inserisci testo'. Se il problema persiste, contatti il nostro servizio clienti.",
    keywords: ["file non si carica", "errore di caricamento", "file non supportato", "errore di formato"],
  },
  {
    id: "kelime-sayisi-yanlis",
    category: "support",
    priority: 139,
    q: "Cosa devo fare se il numero di parole sembra errato?",
    a: "Il conteggio automatico può essere impreciso, soprattutto per i documenti scansionati o basati su immagini. Per un risultato accurato, condivida il testo tramite 'Inserisci testo' o aggiunga una nota all'ordine; il conteggio definitivo viene confermato dal nostro team e il prezzo viene stabilito di conseguenza.",
    keywords: ["numero di parole errato", "errore di conteggio", "conteggio parole sbagliato", "parole non corrette", "conteggio impreciso"],
  },
  {
    id: "odeme-basarisiz",
    category: "support",
    priority: 140,
    q: "Cosa devo fare se un pagamento non va a buon fine o vengo addebitato due volte?",
    a: "Verifichi i dati e il massimale della carta e riprovi; può anche utilizzare un metodo diverso (carta/bonifico). Se l'importo è stato addebitato ma non è stato creato alcun ordine, oppure in caso di doppio addebito, contatti il nostro servizio clienti con la ricevuta e l'importo in eccesso Le verrà rimborsato.",
    keywords: ["pagamento non riuscito", "errore di pagamento", "addebito doppio", "doppio addebito"],
  },
  {
    id: "teslim-dosyasi-inmiyor",
    category: "support",
    priority: 141,
    q: "Cosa devo fare se il file consegnato non si scarica?",
    a: "Aggiorni il link e il browser; se il link di download è scaduto, può richiederne uno nuovo al nostro servizio clienti.",
    keywords: ["file non si scarica", "problema di download", "non riesco a scaricare la consegna", "link scaduto"],
  },
  {
    id: "mobil-tarayici-destegi",
    category: "support",
    priority: 142,
    q: "Posso usare il sito da un dispositivo mobile e quali browser sono supportati?",
    a: "Il sito è ottimizzato per i dispositivi mobili; può caricare documenti ed effettuare ordini da iPhone, telefono Android o tablet. Può utilizzare il sito senza problemi con le versioni aggiornate di Chrome, Safari, Edge e Firefox.",
    keywords: ["mobile", "telefono", "iphone android", "tablet", "browser", "chrome safari"],
  },
  {
    id: "ai-asistan-ne-yapar",
    category: "support",
    priority: 143,
    q: "Cosa può fare l'assistente chat basato su intelligenza artificiale?",
    a: "L'assistente chat fornisce un orientamento immediato su processo, tipi di servizio e domande generali e La indirizza verso i passaggi corretti, come la richiesta di un preventivo. Non può prendere decisioni definitive o vincolanti sui requisiti di accettazione ufficiale o sui requisiti legali (come l'autenticazione notarile o l'apostille); per questi aspetti deve rivolgersi all'ente pertinente.",
    keywords: ["assistente chat", "chatbot", "assistente ia", "prezzi chatbot"],
  },
  {
    id: "insana-baglanma",
    category: "support",
    priority: 144,
    q: "Come contatto un operatore umano del servizio clienti?",
    a: "Può richiederlo tramite l'assistente chat oppure contattare direttamente il nostro servizio di assistenza umana via WhatsApp ed e-mail. Le richieste vengono gestite durante l'orario di lavoro. Inviare i problemi tecnici con uno screenshot aiuta ad accelerare la risoluzione.",
    keywords: ["contattare un operatore", "operatore", "assistenza dal vivo", "screenshot"],
  },
  {
    id: "hesap-bilgileri-guncelleme",
    category: "support",
    priority: 145,
    q: "Come aggiorno i dati dell'account e di fatturazione e come elimino l'account?",
    a: "Se ha un account, può aggiornare telefono, e-mail e dati di fatturazione nelle impostazioni dell'account e può richiedere l'eliminazione dell'account sempre da lì o contattando il nostro servizio clienti. Su Sua richiesta, i Suoi dati vengono eliminati, fatti salvi eventuali obblighi legali.",
    keywords: ["aggiornare dati", "dati di fatturazione", "impostazioni account", "eliminare account"],
  },
  {
    id: "bildirim-tercihleri",
    category: "support",
    priority: 146,
    q: "Come funzionano le notifiche degli ordini e posso ricevere notifiche su WhatsApp?",
    a: "Per lo stato del Suo ordine vengono inviate notifiche via e-mail; in base alle Sue preferenze, gli aggiornamenti possono essere forniti anche tramite WhatsApp. Può regolare le Sue preferenze di notifica nelle impostazioni dell'account o tramite il nostro servizio clienti.",
    keywords: ["notifiche", "sms", "notifica whatsapp", "notifica e-mail", "notifica ordine"],
  },
]
