import type { PartialDictionary } from '@/types/i18n'
import { FAQ_CATEGORIES_DA, FAQ_ITEMS_DA } from '@/content/faq-data.da'

/**
 * DANSK — fuld oversættelse, identisk struktur som en/index.ts.
 * Kun tekstværdierne er oversat; nøgler, ikoner og tekniske tokens
 * forbliver uændrede. Manglende nøgler falder tilbage til engelsk (§10).
 * FAQ-data hentes fra content/faq-data.da.
 */
export const da: PartialDictionary = {
  delivery: {
    "ready": "Din oversættelse er klar",
    "download": "Download oversættelse",
    "hint": "Din oversættelse er også blevet sendt til din e-mailadresse. Tjek din indbakke (og spam-mappen)."
  },

  partnerPanel: {
    qrDownload: "Download QR-kode",
    qrAlt: "Invitations-QR-kode",
    colMembers: "Medlemmer",
    sectorAll: "Alle brancher",
    back: "Tilbage",
    noPartners: "Ingen partnere endnu.",
    tabPayments: "Betalinger",
    payHint: "Betalinger foretages den 2. og 17. i hver måned. På betalingsdagen skal du uploade hver partners kvittering og trykke på “Betalt”; knappen virker ikke, før en kvittering er uploadet. Kun saldi til rådighed for udbetaling (efter 7-dages spærringen) vises; partnere med en saldo på 0 vises ikke.",
    noPayments: "Ingen partnere afventer betaling.",
    paid: "Betaling registreret, og partneren er underrettet.",
    noApplications: "Ingen ventende ansøgninger.",
    approve: "Godkend",
    reject: "Afvis",
    noIban: "Ingen IBAN afventer godkendelse.",
    approveIban: "Godkend IBAN",
    adminTitle: "Partneradministration",
    tabApplications: "Ansøgninger",
    tabIban: "IBAN-godkendelser",
    tabPartners: "Partnere",
    colPartner: "Partner",
    colCompany: "Virksomhed",
    partnerShareLabel: "Partnerandel",
    adminNet: "Resterende (firma)",
    fltPartner: "Partnernavn",
    fltCompany: "Virksomhed",
    yourEarning: "Din indtjening",
    tabAllOrders: "Alle ordrer",
    fltOrderNo: "Ordrenr.",
    fltDateFrom: "Fra",
    fltDateTo: "Til",
    custFilter: "Søg efter navn",
    custEmpty: "Du har endnu ikke henvist nogen medlemmer. Del dit invitationslink.",
    colName: "Navn",
    colEmail: "E-mail",
    colPhone: "Telefon",
    colJoined: "Tilmeldt",
    custOrderCount: "Ordrer",
    custTotal: "Samlet beløb",
    ordEmpty: "Ingen ordrer på dette trin.",
    colOrderNo: "Ordre",
    colCustomer: "Kunde",
    colService: "Ydelse",
    colLangs: "Sprog",
    colAmount: "Beløb",
    colDate: "Dato",
    loadError: "Kunne ikke indlæses. Prøv igen.",
    walPayInfo: "Din indtjening tilføjes din tegnebog, når opgaven er afsluttet; den er spærret i 7 dage og bliver derefter til rådighed for udbetaling. Udbetalinger til den disponible saldo sker den 2. og 17. i hver måned.",
    ibanPending: "Dine IBAN-oplysninger afventer godkendelse fra administrationen.",
    ibanPolicy: "Indtil din IBAN og kontohaver er godkendt af vores team, kan du ikke modtage betalinger. Din indtjening fortsætter med at samle sig i din tegnebog i denne periode. Når dine oplysninger er godkendt, kan du hæve saldi, hvor den 7-dages spærring siden salget er udløbet.",
    fillRequired: "Udfyld venligst de påkrævede felter.",
    phoneLockNote: "Dit telefonnummer kan opdateres, når SMS-bekræftelse aktiveres.",
    panelTitle: "Partnerpanel",
    tabProfile: "Min profil",
    tabCustomers: "Mine kunder",
    tabOrdersNew: "Indkomne ordrer",
    tabOrdersActive: "Under behandling",
    tabOrdersDelivery: "Afventer levering",
    tabOrdersDone: "Afsluttet",
    tabWallet: "Tegnebog",
    soon: "Meget snart.",
    save: "Gem",
    saved: "Gemt.",
    statusApproved: "Godkendt partner",
    ibanVerified: "IBAN bekræftet",
    ibanNotVerified: "IBAN ikke bekræftet",
    ibanReminder: "Angiv din IBAN og kontohaver, så du kan modtage betalinger.",
    refCodeLabel: "Din invitationskode",
    seoTitle: "Partnerpanel",
    seoDesc: "Send din partneransøgning, og få dit invitationslink her.",
    loading: "Indlæser…",
    loginTitle: "Partner-login",
    loginDesc: "Log ind eller opret en konto for at ansøge eller få adgang til dit panel.",
    login: "Log ind / Opret konto",
    setupTitle: "Opsætning ikke fuldført",
    setupDesc: "Partnersystemet er ikke klar endnu.",
    applyTitle: "Partneransøgning",
    applyDesc: "Udfyld dine oplysninger; dit invitationslink aktiveres, når din ansøgning er godkendt.",
    applyNote: "Din ansøgning bliver behandlet snart.",
    sectorOther: "Angiv din branche",
    submit: "Send ansøgning",
    submitting: "Sender…",
    saveError: "Din ansøgning kunne ikke gemmes. Prøv igen.",
    pendingTitle: "Ansøgning modtaget",
    pendingDesc: "Din ansøgning er under behandling. Når den er godkendt, aktiveres dit invitationslink og dit panel her.",
    cancelApplication: "Annullér ansøgning",
    rejectedTitle: "Ansøgning ikke godkendt",
    rejectedDesc: "Denne ansøgning blev ikke godkendt. Du kan opdatere dine oplysninger og ansøge igen.",
    reapply: "Ansøg igen",
    approvedTitle: "Din partnerkonto er aktiv",
    approvedDesc: "Kunder, der tilmelder sig via dit invitationslink nedenfor, knyttes permanent til din konto.",
    panelSoon: "Et detaljeret panel med dine kunder, ordrer og din tegnebog kommer her meget snart.",
    verifyTitle: "E-mailbekræftelse",
    verifyDesc: "Bekræft din e-mailadresse, så du kan modtage betalinger. Vi sender dig en bekræftelseskode.",
    verifiedLabel: "E-mail bekræftet",
    sendCode: "Send bekræftelseskode",
    sending: "Sender…",
    codeSent: "Vi har sendt koden til din e-mail. Tjek din indbakke og spammappe.",
    codePlaceholder: "6-cifret kode",
    verifyBtn: "Bekræft",
    verifying: "Bekræfter…",
    verifyError: "Koden er ugyldig eller udløbet. Anmod om en ny.",
    refTitle: "Dit invitationslink",
    refDesc: "Del dette link; kunder, der kommer via det og tilmelder sig, knyttes permanent til dig.",
    refCopy: "Kopiér link",
    refCopied: "Kopieret",
  },
  adminHub: {
    tabMembers: "Medlemmer",
    tabTranslators: "Oversættere",
    tabPartners: "Partnere",
    tabManage: "Administrer medlemmer",
    bMember: "Medlem",
    bCustomer: "Kunde",
    bTranslator: "Oversætter",
    bPartner: "Partner",
    bReferred: "Henvist",
    bBanned: "Bortvist",
    filterAll: "Alle",
    memHint: "Alle medlemmer med en konto i systemet, undtagen administratoren.",
    memNone: "Ingen medlemmer.",
    trHint: "Alle oversættere i systemet.",
    trNone: "Ingen oversættere.",
    trJoinedRole: "Oversætter siden",
    prtHint: "Alle partnere i systemet.",
    prtNone: "Ingen partnere.",
    prtCompany: "Virksomhed",
    prtJoinedRole: "Partner siden",
    mgHint: "Administrer medlemmer: udeluk eller slet konti. Handlinger kræver bekræftelse.",
    mgNone: "Ingen medlemmer.",
    banBtn: "Udeluk",
    unbanBtn: "Ophæv udelukkelse",
    deleteBtn: "Slet konto",
    banConfirm: "Er du sikker på, at du vil udelukke dette medlem? Medlemmet kan ikke logge ind.",
    unbanConfirm: "Er du sikker på, at du vil ophæve udelukkelsen af dette medlem?",
    deleteConfirm: "Er du sikker på, at du vil slette denne konto PERMANENT? Dette kan ikke fortrydes.",
    confirmYes: "Ja, fortsæt",
    confirmNo: "Annuller",
    actionDone: "Færdig.",
    actionFail: "Handlingen mislykkedes. Prøv igen.",
    tabChats: "Chatbot-logfiler",
    "tabCustomers": "Kunder",
    "tabUploads": "Uploadede filer",
    "loading": "Indlæser…",
    "loadError": "Kunne ikke indlæses. Prøv venligst igen.",
    "back": "Tilbage",
    custHint: "Alle registrerede kunder, der har afgivet mindst én ordre.",
    "custSearch": "Søg efter navn, e-mail eller telefon…",
    "custName": "Fulde navn",
    "custEmail": "E-mail",
    "custPhone": "Telefon",
    "custOrders": "Ordrer",
    "custTotal": "Samlet beløb",
    "custJoined": "Tilmeldt",
    "custNone": "Ingen kundeposter endnu.",
    "custOrderList": "Ordrer",
    "custNoOrders": "Denne kunde har ingen ordrer.",
    "orderNo": "Ordrenr.",
    "orderDate": "Dato",
    "orderStatus": "Status",
    "upHint": "Alle filer uploadet på tilbudssiden (gemmes, selv hvis der ikke afgives en ordre).",
    "upFile": "Fil",
    "upUploader": "Uploadet af",
    "upWhen": "Dato",
    "upWords": "Ord",
    "upSize": "Størrelse",
    "upDownload": "Download",
    "upNone": "Ingen uploadede filer endnu.",
    "upGuest": "Gæst"
  },

  smsVerify: {
    "sendCode": "Send kode",
    "resend": "Send kode igen",
    "codeLabel": "SMS-kode",
    "confirm": "Bekræft",
    "verified": "Telefon bekræftet",
    "sent": "Der er sendt en kode til din telefon.",
    "mustVerify": "For at fortsætte skal du bekræfte dit telefonnummer via SMS.",
    "reverifyHint": "Hvis du ændrer dit telefonnummer, skal du bekræfte det nye nummer igen via SMS.",
    "invalid": "Forkert kode. Prøv venligst igen.",
    "expired": "Koden er udløbet. Anmod venligst om en ny.",
    "rateLimited": "For mange forsøg. Vent venligst et øjeblik, og prøv igen.",
    "notConfigured": "SMS-bekræftelse er i øjeblikket ikke tilgængelig. Prøv venligst igen senere, eller kontakt supporten.",
    "sendFailed": "Koden kunne ikke sendes. Kontrollér dit nummer, og prøv igen.",
    "enterPhone": "Indtast venligst et gyldigt telefonnummer først.",
    "error": "Noget gik galt. Prøv venligst igen.",
    "devCode": "Testtilstand — din bekræftelseskode: {code}"
  },
  common: {
      "brand": "TercümExpert",
    tagline: "Din pålidelige partner inden for professionelle oversættelsestjenester.",
    nav: {
      home: "Forside",
      services: "Ydelser",
      quote: "Få et tilbud",
      corporate: "Erhverv",
      partnership: "Partnerskab",
      blog: "Blog",
      faq: "Ofte stillede spørgsmål",
      contact: "Kontakt",
    },
    actions: {
      getQuote: "Få et tilbud",
      calculatePrice: "Beregn pris",
      uploadDocument: "Upload dokument",
      whatsapp: "Chat på WhatsApp",
      learnMore: "Læs mere",
      viewAll: "Se alle",
      showMore: "Vis mere",
      showLess: "Vis mindre",
      send: "Send",
      apply: "Ansøg",
      order: "Afgiv bestilling",
      contactUs: "Kontakt os",
      openMenu: "Åbn menu",
      closeMenu: "Luk menu",
      selectLanguage: "Vælg sprog",
      skipToContent: "Gå til indhold",
      login: "Log ind",
      logout: "Log ud",
      account: "Min konto",
    },
    states: {
      loading: "Indlæser…",
      error: "Noget gik galt. Prøv venligst igen.",
      required: "Dette felt er påkrævet.",
      demoNotice: "Demo: Formulardata sendes endnu ikke til en server.",
      unverified: "Skal bekræftes",
    },
    topbar: {
      phoneLabel: "Telefon",
      emailLabel: "E-mail",
      hoursLabel: "Åbningstider",
      afterHours: "Akut oversættelsessupport uden for åbningstiden er tilgængelig.",
      workingHours: "Hverdage 09:00 - 18:00 | Service uden for åbningstiden tilgængelig",
    },
  },

  home: {
    seo: {
      title: "TercümExpert — Professionelle oversættelsestjenester",
      description:
        "Autoriseret oversættelse, notarpåtegning og oversættelsesløsninger til erhverv. Upload dit dokument, få et øjeblikkeligt foreløbigt tilbud og professionel levering.",
    },
    hero: {
      title: "Din pålidelige partner inden for professionelle",
      titleAccent: "Oversættelsestjenester",
      subtitle: "Upload dit dokument, se prisen, få professionel levering.",
      support: "Autoriseret oversættelse • Notarpåtegning • Løsninger til erhverv",
    },
    trust: {
      title: "Hvorfor stoler de på os?",
      items: [
        { key: 'languages', label: "50+ sprog" },
        { key: 'delivery', label: "Levering inden for 24 timer" },
        { key: 'notary', label: "Notarpåtegning" },
        { key: 'quality', label: "Kvalitetssikring" },
      ],
    },
    stats: {
      title: "TercümExpert i tal",
      note: "Nedenstående tal præsenteres ikke som endelige udsagn, før de er bekræftet.",
      labels: {
        satisfaction: "Kundetilfredshed",
        completed: "Gennemførte opgaver",
        languages: "Sprogunderstøttelse",
        corporate: "Erhvervskunder",
      },
    },
    howItWorks: {
      title: "Hvordan fungerer det?",
      subtitle: "Professionel oversættelse i fem trin.",
      steps: [
        { key: 'upload', title: "Upload", desc: "Upload dit dokument sikkert." },
        { key: 'select', title: "Vælg", desc: "Vælg sprog og ydelsestype." },
        { key: 'confirm', title: "Bekræft", desc: "Bekræft din bestilling." },
        { key: 'track', title: "Følg", desc: "Følg processen i realtid." },
        { key: 'receive', title: "Modtag", desc: "Få din professionelle levering." },
      ],
    },
    services: {
      title: "Vores ydelser",
      subtitle: "Ekspertoversættelse til enhver dokumenttype.",
    },
    why: {
      title: "Hvorfor TercümExpert?",
      subtitle: "De egenskaber, der adskiller os fra konkurrenterne",
      features: [
        { key: 'autoQuote', title: "Automatisk prisberegning", desc: "En foreløbig pris på få sekunder." },
        { key: 'whatsapp', title: "Hurtigt tilbud via WhatsApp", desc: "Kontakt med ét tryk." },
        { key: 'terminology', title: "Terminologistyring", desc: "Ensartet, virksomhedstilpasset sprog." },
        { key: 'revision', title: "Revisionsret", desc: "En tilfredshedsfokuseret proces." },
        { key: 'languages', title: "Understøttelse af 50+ sprog", desc: "Bred dækning af sprogpar." },
        { key: 'terms', title: "Kreditsystem til erhverv", desc: "Fleksibel betaling for virksomheder." },
      ],
    },
    corporateCta: {
      title: "Løsninger til erhverv",
      desc: "Professionelle sprogydelser med terminologistyring, kreditmuligheder og en dedikeret kundeansvarlig, der er skræddersyet til din virksomhed.",
      action: "Anmod om et erhvervstilbud",
    },
    partnershipTeaser: {
      title: "Partnerprogram",
      subtitle: "Tjen 20 % i provision på hver kunde, du henviser til os.",
      items: [
        { key: 'commission', title: "Gennemsigtig provision", desc: "20 % provision for hver henvisning (efter aftale). Gennemsigtig indtjening med et sporingspanel i realtid." },
        { key: 'qr', title: "QR-kode-system", desc: "Nem kundesporing med visitkortsintegration. QR-koder til web og WhatsApp." },
      ],
      cta: "Ansøg som partner",
    },
    testimonials: {
      title: "Kundeanmeldelser",
      subtitle: "Rigtige kundeanmeldelser tilføjes her inden lancering.",
      placeholderNote: "Pladsholder — rigtige anmeldelser integreres.",
      items: [
        { key: 't1', role: "Advokatfirma" },
        { key: 't2', role: "Sundhedsorganisation" },
        { key: 't3', role: "Erhvervskunde" },
        { key: 't4', role: "Privatkunde" },
      ],
    },
    blogTeaser: {
      title: "Blog",
      subtitle: "Aktuelt indhold fra oversættelsens verden",
      viewAll: "Se alle blogindlæg",
    },
    finalCta: {
      title: "Kom i gang nu",
      desc: "Upload dine dokumenter, få et øjeblikkeligt tilbud og gør brug af professionelle oversættelsestjenester.",
      primary: "Få et tilbud",
      secondary: "Kontakt os",
    },
  },

  services: {
    seo: {
      title: "Oversættelsestjenester",
      description:
        "Autoriseret, notarpåtegnet, juridisk, teknisk, medicinsk og akademisk oversættelse samt web-/mobillokalisering. Dokumenttyper, proces, levering og sprogpar.",
    },
    hero: {
      title: "Oversættelsestjenester",
      subtitle: "Oversættelse med den rette terminologi til hvert fagområde.",
    },
    process: {
      title: "Hvordan fungerer processen?",
      steps: [
        { title: "Gennemgang af dokument", desc: "Dokumenttypen og formålet vurderes." },
        { title: "Ekspertmatch", desc: "En specialiseret oversætter på området tildeles." },
        { title: "Oversættelse og korrektur", desc: "Oversættelse og en uafhængig endelig gennemgang." },
        { title: "Godkendelse og levering", desc: "Notarpåtegning/apostille om nødvendigt, derefter levering." },
      ],
    },
    delivery: {
      title: "Leveringsmuligheder",
      items: ["Digital levering (PDF/DOCX)", "Fysisk levering af dokument", "Hasteopgave"],
    },
    notaryApostille: {
      title: "Sammenhæng mellem notarpåtegning og apostille",
      desc: "Når det er påkrævet, gøres en autoriseret oversættelse gyldig over for offentlige myndigheder gennem notarpåtegning og apostilleprocessen. Det præcise krav afhænger af den myndighed, hvor dokumentet skal indleveres.",
    },
    fullService: {
      title: "Nøglefærdigt, leveret til din dør",
      note: "Send os dine dokumenter, så håndterer vi hele processen — oversættelse, notarpåtegning og apostille inklusive. Dine færdige dokumenter leveres til din dør med kurér. Fokusér på dit arbejde, og overlad resten til os.",
    },
    cta: {
      title: "Er du i tvivl om, hvilken ydelse du har brug for?",
      desc: "Upload dit dokument, så viser vi dig den mest passende ydelse og pris.",
    },
    documentTypesTitle: "Egnede dokumenttyper",
  },

  serviceItems: {
    sworn: {
      name: "Autoriseret oversættelse",
      short: "Officielt gyldig oversættelse med en autoriseret oversætters underskrift og stempel.",
      benefits: ["Gyldig hos offentlige myndigheder", "Godkendelse fra autoriseret oversætter", "Hurtig proces"],
    },
    notarized: {
      name: "Oversættelse med notarpåtegning",
      short: "Notarpåtegning af en autoriseret oversættelse.",
      benefits: ["Notarpåtegning", "Egnet til officielle ansøgninger", "Vi håndterer processen"],
    },
    apostille: {
      name: "Støtte til apostilleproces",
      short: "Vejledning gennem apostilleprocessen med henblik på gyldighed i udlandet.",
      benefits: ["International gyldighed", "Procesrådgivning", "Vejledning om myndigheder"],
    },
    legal: {
      name: "Juridisk oversættelse",
      short: "Oversættelse med styr på terminologien til kontrakter, retssager og officielle dokumenter.",
      benefits: ["Juridisk terminologi", "Fortrolighedsgaranti", "Ekspertoversætter"],
    },
    technical: {
      name: "Teknisk oversættelse",
      short: "Ensartet oversættelse til manualer, specifikationer og tekniske dokumenter.",
      benefits: ["Terminologistyring", "Format bevaret", "Brancheekspertise"],
    },
    medical: {
      name: "Medicinsk oversættelse",
      short: "Præcis oversættelse til journaler, indlægssedler og medicinske dokumenter.",
      benefits: ["Medicinsk terminologi", "Fokus på nøjagtighed", "Fortrolighed"],
    },
    academic: {
      name: "Akademisk oversættelse",
      short: "Akademisk sprog til specialer, artikler og eksamensbevisoversættelser.",
      benefits: ["Akademisk stil", "Kildekonsistens", "Levering til tiden"],
    },
    localization: {
      name: "Web- og mobillokalisering",
      short: "Kulturelt tilpasset lokalisering af websteder og applikationer.",
      benefits: ["Kulturel tilpasning", "Teknisk integration", "SEO-kompatibilitet"],
    },
  },

  corporate: {
    statsLabels: {
      corporate: "Erhvervskunder",
      discount: "Mængderabat",
      term: "Betalingsfrist",
    },
    seo: {
      title: "Løsninger til erhverv",
      description:
        "Professionelle sprogydelser til virksomheder med terminologistyring, kreditmuligheder, storordrer og en dedikeret kundeansvarlig.",
    },
    hero: {
      title: "Løsninger til erhverv",
      subtitle:
        "Professionelle sprogydelser med terminologistyring, kreditmuligheder og en dedikeret kundeansvarlig, der er skræddersyet til din virksomhed.",
      primaryCta: "Anmod om et erhvervstilbud",
      secondaryCta: "Send e-mail",
    },
    features: {
      title: "Erhvervsfunktioner",
      subtitle: "Løsninger skræddersyet til din virksomhed",
      items: [
        {
          key: 'custom',
          icon: 'Target',
          title: "Skræddersyet ydelse",
          points: ["Fast terminologi", "Bevarelse af brandets tone", "Dedikeret kundeansvarlig", "Udarbejdelse af stilguide"],
        },
        {
          key: 'volume',
          icon: 'BarChart3',
          title: "Bulkbehandling og kredit",
          points: ["Månedlige oversættelsesplaner", "Mængderabatter", "Kredit op til 30 dage", "Faktureringssystem"],
        },
        {
          key: 'security',
          icon: 'Lock',
          title: "Databeskyttelse og sikkerhed",
          points: ["NDA-protokol", "Krypteret filoverførsel", "KVKK-kompatible processer"],
        },
      ],
    },
    whyPackage: {
      title: "Hvorfor en erhvervspakke?",
      items: [
        {
          key: 'terminology',
          icon: 'Building2',
          title: "Fast terminologistyring",
          desc: "Vi opbygger en termbank, der er specifik for din virksomhed. Dit brandsprog bevares på tværs af alle oversættelser, og vi sikrer konsistens. Vi lægger vægt på at bruge de samme termer i hvert projekt.",
        },
        {
          key: 'manager',
          icon: 'Users',
          title: "Dedikeret kundeansvarlig",
          desc: "Din dedikerede kundeansvarlige følger alle dine processer. Med en tilgængelig supportlinje står vi ved din side i akutte situationer.",
        },
        {
          key: 'security',
          icon: 'ShieldCheck',
          title: "Databeskyttelse og sikkerhed",
          desc: "Vi arbejder under en NDA-protokol. Dine data er sikre med en stærk sikkerhedsinfrastruktur, krypteret filoverførsel og KVKK-kompatible processer.",
        },
      ],
    },
    payment: {
      title: "Betalingsmuligheder",
      subtitle: "Fleksible betalingsplaner tilpasset din virksomhed",
      recommendedLabel: "ANBEFALET",
      options: [
        {
          key: 'standard',
          label: "Øjeblikkelig betaling",
          heading: "Standard",
          desc: "Betaling med betalingskort eller bankoverførsel efter hver bestilling",
          points: ["Kortbetaling i rater", "Øjeblikkelig levering"],
          recommended: false,
        },
        {
          key: 'term',
          label: "Månedlig kredit",
          heading: "15-30 dage",
          desc: "Månedlig samlefakturering og kreditmulighed",
          points: ["30 dages kredit", "Mængderabat", "Månedlig rapport"],
          recommended: true,
        },
      ],
    },
    form: {
      title: "Ansøgning om erhvervspakke",
      desc: "Udfyld formularen, så kontakter vores ekspertteam dig",
      fields: {
        company: "Virksomhedsnavn",
        contactName: "Kontaktpersonens fulde navn",
        email: "E-mail",
        phone: "Telefon",
        need: "Fortæl os om dine oversættelsesbehov",
        consent: "Jeg har læst og godkender <kvkk>KVKK-oplysningserklæringen</kvkk>.",
      },
      submit: "Send ansøgning",
      success: "Din ansøgning er modtaget. Vi vender tilbage til dig hurtigst muligt.",
      note: "Vi vender tilbage til dig inden for 1 arbejdsdag.",
    },
  },

  partnership: {
    seo: {
      title: "Partnerprogram",
      description:
        "Tjen provision på hver kunde, du henviser. Gennemsigtig rapportering, henvisninger via QR-kode og professionel support.",
    },
    hero: {
      title: "Partnerprogram",
      value: "Tjen 20 % i provision på hver kunde, du henviser til os.",
      subtitle: "Et gennemsigtigt system, pålidelige udbetalinger, langsigtet samarbejde.",
      cta: "Ansøg nu",
    },
    advantages: {
      title: "Partnerfordele",
      subtitle: "Hvorfor blive TercümExpert-partner?",
      items: [
        { key: 'commission', icon: 'Wallet', title: "20 % provisionsgaranti", desc: "Et gennemsigtigt provisionssystem for hver kunde, du henviser." },
        { key: 'qr', icon: 'QrCode', title: "Henvisning via QR-kode", desc: "Nem kundesporing med visitkortsintegration." },
        { key: 'reporting', icon: 'BarChart3', title: "Gennemsigtig rapportering", desc: "Panel til provisions- og kundesporing i realtid." },
        { key: 'support', icon: 'Users', title: "Professionel support", desc: "En dedikeret partnersupportlinje og kundeansvarlig." },
      ],
    },
    howItWorks: {
      title: "Hvordan fungerer det?",
      steps: [
        { title: "Ansøg", desc: "Udfyld den online ansøgningsformular. Del dine virksomhedsoplysninger og kontaktoplysninger. Din ansøgning gennemgås inden for 1 arbejdsdag." },
        { title: "Bliv partner", desc: "Når din ansøgning er godkendt, får du adgang til dit dedikerede partnerpanel. Dine QR-koder og henvisningslinks er klar." },
        { title: "Henvis kunder", desc: "Henvis dine kunder til os via QR-kode, et personligt link eller visitkort. Hver henvisning registreres automatisk i systemet." },
        { title: "Tjen provision", desc: "Du tjener 20 % i provision, hver gang en kunde, du har henvist, afgiver en bestilling. Du modtager automatiske udbetalinger hver 15. dag." },
      ],
    },
    sectors: {
      title: "Målbrancher",
      subtitle: "Hvilke brancher er det ideelt til?",
      items: [
        { key: 'law', icon: 'Scale', title: "Advokatfirmaer", desc: "Behov for autoriseret oversættelse af sagsakter, kontrakter og juridiske dokumenter." },
        { key: 'visa', icon: 'Plane', title: "Visumrådgivning", desc: "Dokumenter, der kræver autoriseret oversættelse, såsom pas, eksamensbeviser og personattester." },
        { key: 'education', icon: 'GraduationCap', title: "Uddannelsesrådgivning", desc: "Autoriseret oversættelse af studiedokumenter og apostilleprocesser." },
        { key: 'health', icon: 'HeartPulse', title: "Sundhedsturisme", desc: "Oversættelse af lægejournaler, patientmapper og sundhedsdokumenter." },
        { key: 'patent', icon: 'Building2', title: "Patent-/varemærkekontorer", desc: "Teknisk oversættelse af patent-, varemærkeregistrerings- og juridiske dokumenter." },
        { key: 'realestate', icon: 'Home', title: "Ejendomsmæglere", desc: "Oversættelse af skøder, kontrakter og officielle dokumenter til udenlandske investorer." },
        { key: 'hr', icon: 'Briefcase', title: "HR-rådgivning", desc: "Oversættelse af CV'er, eksamensbeviser og anbefalingsbreve til placering i udlandet." },
        { key: 'software', icon: 'Code', title: "Softwarevirksomheder", desc: "Lokalisering af web- og mobilapps, oversættelse af tekniske dokumenter." },
      ],
    },
    commission: {
      title: "Provisionsstruktur",
      stats: {
        commissionLabel: "Standardprovision",
        commissionSub: "På hver bestilling",
        periodUnit: "Dage",
        periodLabel: "Betalingsperiode",
        feeLabel: "Oprettelsesgebyr",
        feeSub: "Helt gratis",
      },
      exampleTitle: "Eksempel på indtjeningsberegning",
      exampleOrderLabel: "Bestilling fra den kunde, du henviste",
      exampleRateLabel: "Provisionssats",
      exampleEarningLabel: "Din indtjening",
      note: "Provisionssatser og vilkår er underlagt partneraftalen.",
    },
    form: {
      title: "Partneransøgningsformular",
      subtitle: "Udfyld formularen, så vender vi tilbage til dig inden for 1 arbejdsdag.",
      fields: {
        company: "Virksomhedens/organisationens navn",
        sector: "Branche",
        contactName: "Kontaktpersonens fulde navn",
        titleRole: "Titel",
        email: "E-mail",
        phone: "Telefon",
        potential: "Dit anslåede månedlige henvisningspotentiale",
        note: "Eventuelle bemærkninger, du vil tilføje",
        agreement: "Jeg har læst og accepterer vilkårene i <partnership>partneraftalen</partnership>.",
      },
      sectorPlaceholder: "Vælg",
      sectorOptions: ["Advokatfirma", "Visumrådgivning", "Uddannelsesrådgivning", "Sundhedsturisme", "Patent-/varemærkekontor", "Ejendomsmægler", "HR-rådgivning", "Software", "Andet"],
      potentialOptions: ["1-5 kunder", "5-10 kunder", "10-20 kunder", "20+ kunder"],
      submit: "Send ansøgning",
      success: "Din ansøgning er modtaget. Vi kontakter dig.",
      note: "Din ansøgning gennemgås inden for 1 arbejdsdag.",
    },
  },

  quote: {
    cancelPolicy: "Bemærk: din ordre kan annulleres fra din ordreside, indtil en oversætter begynder at arbejde på den, og din betaling refunderes. Når en oversætter har påtaget sig opgaven, er annullering ikke længere mulig.",
    "areas": {
      "academic": "Akademisk oversættelse",
      "legal": "Juridisk oversættelse",
      "official": "Oversættelse af officielle dokumenter",
      "medical": "Medicinsk oversættelse",
      "technical": "Teknisk oversættelse",
      "commercial": "Erhvervs- og finansiel oversættelse",
      "localization": "Web- og mobillokalisering",
      "literary": "Litterær oversættelse",
      "general": "Generel / anden oversættelse"
    },
    "docTypes": {
      "diploma": "Eksamensbevis",
      "transcript": "Karakterudskrift",
      "student-certificate": "Studiebekræftelse",
      "diploma-supplement": "Eksamensbevistillæg",
      "thesis": "Speciale",
      "reference-letter": "Anbefaling",
      "academic-article": "Videnskabelig artikel",
      "contract": "Kontrakt",
      "court-decision": "Retsafgørelse",
      "power-of-attorney": "Fuldmagt",
      "petition": "Stævning",
      "consent-statement": "Samtykkeerklæring",
      "warning-notice": "Advarsel",
      "litigation-doc": "Retsdokumenter",
      "passport": "Pas",
      "id-card": "Identitetskort",
      "civil-registry": "Udskrift fra folkeregistret",
      "birth-certificate": "Fødselsattest",
      "marriage-certificate": "Vielsesattest",
      "driver-license": "Kørekort",
      "criminal-record": "Straffeattest",
      "military-status": "Dokument for militær status",
      "medical-report": "Lægeerklæring",
      "epicrisis": "Epikrise (udskrivningsresumé)",
      "prescription": "Recept",
      "lab-result": "Prøve-/analysesvar",
      "medical-article": "Medicinsk artikel",
      "patient-consent": "Patientsamtykkeerklæring",
      "user-manual": "Brugervejledning",
      "technical-spec": "Teknisk specifikation",
      "patent": "Patent",
      "product-catalog": "Produktkatalog",
      "datasheet": "Datablad",
      "installation-guide": "Installationsvejledning",
      "safety-data-sheet": "Sikkerhedsdatablad",
      "invoice": "Faktura",
      "balance-sheet": "Balance",
      "commercial-contract": "Handelskontrakt",
      "financial-report": "Årsregnskab",
      "tax-document": "Skattedokument",
      "activity-certificate": "Virksomhedsattest",
      "bank-statement": "Kontoudtog",
      "website": "Websted",
      "mobile-app": "Mobilapp",
      "software-ui": "Softwarebrugerflade",
      "game": "Spil",
      "marketing-content": "Marketingindhold",
      "subtitle": "Undertekster",
      "e-commerce": "E-handelsindhold",
      "book": "Bog",
      "short-story": "Novelle",
      "poem": "Digt",
      "screenplay": "Manuskript",
      "essay": "Essay",
      "article": "Artikel",
      "general-document": "Generelt dokument",
      "correspondence": "Korrespondance / brev",
      "cv": "CV",
      "presentation": "Præsentation",
      "other": "Andet"
    },
    seo: {
      title: "Øjeblikkelig prisberegning",
      description: "Upload dit dokument eller indtast oplysningerne, og få dit øjeblikkelige foreløbige tilbud.",
    },
    hero: {
      title: "Øjeblikkelig prisberegning",
      subtitle: "Upload dit dokument eller indtast oplysningerne, og få et øjeblikkeligt foreløbigt tilbud.",
    },
    upload: {
      heading: "Upload dine dokumenter",
      privacy: "Dine data behandles fortroligt",
      tabFile: "Upload fil",
      tabText: "Indtast tekst",
      chooseFile: "Vælg dine dokumenter",
      formats: ".docx, .xlsx, .pdf, .pptx, .jpg, .png og 50+ formater accepteres · Maks. 100MB pr. fil",
      dropHint: "Du kan trække og slippe en eller flere filer ind i dette område.",
      textPlaceholder: "Indsæt eller skriv din tekst her…",
      totalWords: "Samlet ordantal",
      extracting: "Tæller ord…",
      wordsUnit: "ord",
      remove: "Fjern",
      unsupported:
        "Automatisk ordoptælling var ikke mulig for denne filtype. Indsæt venligst teksten via \"Indtast tekst\"; antallet bekræftes af vores team ved tilbudsgivning.",
      empty:
        "Der blev ikke fundet nogen markerbar tekst i filen (den kan være scannet/et billede). Brug venligst \"Indtast tekst\", ellers bekræftes antallet under tilbudsgivningen.",
      error: "Filen kunne ikke læses. Prøv venligst igen, eller brug \"Indtast tekst\".",
      tooLarge: "Filen må ikke være større end 100MB.",
      needInput: "For at få en pris skal du uploade en fil eller indtaste tekst.",
    },
    fields: {
      upload: "Upload dokument (valgfrit)",
      uploadHint: "PDF, DOC, DOCX eller TXT — maks. 10 MB",
      sourceLang: "Kildesprog",
      targetLang: "Målsprog",
      serviceType: "Ydelsestype",
      documentType: "Dokumenttype",
      wordCount: "Anslået ordantal",
      wordCountHint: "Brug skyderen, eller indtast tallet manuelt.",
      options: "Yderligere muligheder",
      calculate: "Beregn pris",
    },
    options: {
      "sworn": "Autoriseret (bekræftet) oversættelse",
      "apostille": "Hjælp til apostille-processen",
      "swornNotaryHint": "Notarpåtegning omfatter allerede autoriseret oversættelse; du skal blot vælge den ene mulighed, der passer til dit behov.",
      "physicalRequiredHint": "Autoriserede og notarbekræftede oversættelser leveres som underskrevne/stemplede originaler, så fysisk levering tilføjes automatisk.",
      urgent: "Hasteopgave",
      notarization: "Notarpåtegning",
      physicalDelivery: "Fysisk levering",
    },
    languages: {
      tr: "Tyrkisk",
      en: "Engelsk",
      de: "Tysk",
      fr: "Fransk",
      es: "Spansk",
      it: "Italiensk",
      ru: "Russisk",
      ar: "Arabisk",
      nl: "Nederlandsk",
      az: "Aserbajdsjansk",
      pl: "Polsk",
      bg: "Bulgarsk",
      pt: "Portugisisk",
      da: "Dansk",
    },
    documentTypes: {
      diploma: "Eksamensbevis",
      passport: "Pas",
      'civil-registry': "Personattest",
      contract: "Kontrakt",
      'medical-report': "Lægejournal",
      'technical-doc': "Teknisk dokument",
      'court-doc': "Retsdokument",
      other: "Andet",
    },
    result: {
      title: "Foreløbigt tilbud",
      basePrice: "Grundgebyr for ydelse",
      wordPrice: "Ordgebyr",
      addons: "Tillægsydelser",
      total: "I alt",
      vat: "moms",
      delivery: "Anslået leveringstid",
      deliveryUnit: "arbejdsdage",
      disclaimer: "Dette er et foreløbigt tilbud; den endelige pris bekræftes efter gennemgang af dokumentet.",
      order: "Afgiv bestilling",
      whatsapp: "Kontakt via WhatsApp",
      estimatedWords: "Anslåede ord (automatisk — demo)",
    },
    orderConfirm: {
      title: "Din bestilling er modtaget",
      number: "Bestillingsnr.",
      desc: "Din anmodning og dine dokumenter er gemt. Vores ekspertteam gennemgår dokumentet og kontakter dig hurtigst muligt.",
      viewOrders: "Mine bestillinger",
      submitting: "Opretter bestilling…",
      error: "Der opstod et problem med oprettelsen af din bestilling. Prøv venligst igen.",
    },
    gate: {
      title: "Din pris er klar",
      subtitle: "Log ind, eller bekræft dine oplysninger for at se prisen og afgive en bestilling.",
      loginCta: "Log ind / Opret konto",
      or: "eller fortsæt hurtigt",
      firstName: "Fornavn",
      lastName: "Efternavn",
      email: "E-mail",
      phone: "Telefonnummer",
      sendCode: "Send bekræftelseskode",
      codeLabel: "Bekræftelseskode",
      codeSentA: "har fået tilsendt en bekræftelseskode.",
      verify: "Bekræft og se pris",
      resend: "Send kode igen",
      resent: "En ny kode er sendt.",
      back: "Ret oplysninger",
      errNames: "Fornavn og efternavn er påkrævet.",
      errEmail: "Indtast en gyldig e-mail.",
      errPhone: "Indtast et gyldigt telefonnummer.",
      errCode: "Indtast venligst koden fuldstændigt.",
      note: "Din e-mail bruges kun til tilbuddet og bestillingen.",
    },
    note: {
      label: "Bemærkning til din bestilling (valgfrit)",
      placeholder: "Du kan skrive dine ønsker om levering, terminologi eller andre særlige forhold her.",
    },

    checkout: {
      "selectCountry": "Vælg land",
      "selectCity": "Vælg by / region",
      "cityNeedsCountry": "Vælg først et land",
      title: "Leveringsoplysninger",
      subtitle: "Dit fysiske/autoriserede dokument sendes til denne adresse.",
      firstName: "Fornavn",
      lastName: "Efternavn",
      phone: "Telefon",
      address: "Fuld adresse",
      addressPlaceholder: "Vej, hus- og lejlighedsnummer…",
      city: "By",
      postalCode: "Postnummer",
      country: "Land",
      submit: "Gennemfør bestilling",
      submitting: "Opretter bestilling…",
      cancel: "Annuller",
      errRequired: "Udfyld de påkrævede felter.",
      note: "Disse oplysninger bruges kun til levering med kurér.",
    },
  },

  order: {
    cancel: {
      eligible: "Din ordre er stadig i puljen; du kan annullere den og få pengene tilbage, indtil en oversætter påtager sig opgaven.",
      button: "Annuller ordre",
      error: "Ordren kunne ikke annulleres. En oversætter har muligvis påtaget sig den i mellemtiden. Opdater venligst siden.",
      confirmTitle: "Annuller ordre",
      confirmDesc: "Er du sikker på, at du vil annullere denne ordre? Dette kan ikke fortrydes; din betaling refunderes.",
      keep: "Behold",
      confirmYes: "Ja, annuller",
      canceling: "Annullerer…",
    },
      "trackingCodeLabel": "Sporingsnummer",
    seo: {
      title: "Ordresporing",
      description: "Følg status på din bestilling.",
    },
    numberLabel: "Bestillingsnr.",
    placedOn: "Bestillingsdato",
    estimatedLabel: "Anslået levering af oversættelse",
    cargoEstimatedLabel: "Anslået forsendelsesdato",
    timelineTitle: "Ordrestatus",
    steps: {
      received: "Din bestilling er modtaget",
      in_progress: "Under behandling",
      translated: "Oversættelse gennemført",
      shipped: "Afsendt",
      delivered: "Leveret",
      cancelled: "Bestilling annulleret",
    },
    stepDesc: {
      received: "Din anmodning og dine dokumenter er nået frem til vores system. Vores ekspertteam gennemgår det og går snart i gang.",
      in_progress: "Vores ekspertoversætter er gået i gang med din oversættelse.",
      translated: "Din oversættelse er færdig, og de endelige kontroller er udført.",
      shipped: "Dit dokument er overdraget til kuréren; du kan følge det med knappen nedenfor.",
      delivered: "Dit dokument er sendt til dig pr. e-mail.",
      cancelled: "Denne bestilling er annulleret. Kontakt os venligst, hvis du har spørgsmål.",
    },
    cargoReady: "Dit dokument er afsendt. Følg det med ét tryk:",
    cargoPending: "Sporingskoden vises her, når dit dokument er afsendt.",
    trackCargo: "Følg min forsendelse",
    digitalPending: "Når din oversættelse er færdig, sendes dine filer til dig pr. e-mail.",
    digitalDelivered: "Din oversættelse er sendt til dig pr. e-mail. Tjek din indbakke (og spammappen).",
    detailsTitle: "Bestillingsoplysninger",
    fields: {
      service: "Ydelse",
      langs: "Sprog",
      documentType: "Dokumenttype",
      words: "Ord",
      delivery: "Anslået tid",
      total: "Beløb",
      note: "Din bemærkning",
      deliveryAddress: "Leveringsadresse",
    },
    myOrders: "Mine bestillinger",
    backHome: "Tilbage til forsiden",
    whatsapp: "Kontakt via WhatsApp",
    loading: "Indlæser bestilling…",
    loginRequired: {
      title: "Log ind for at se din bestilling",
      desc: "Du kan kun få adgang til dine bestillingsoplysninger, når du er logget ind med din konto.",
      login: "Log ind",
    },

    notFound: {
      title: "Bestilling ikke fundet",
      desc: "Dette bestillingsnummer tilhører ikke dig eller findes ikke. Tjek venligst linket.",
      home: "Tilbage til forsiden",
    },
  },

  faq: {
    seo: {
      title: "Ofte stillede spørgsmål",
      description: "Ofte stillede spørgsmål om autoriseret oversættelse, leveringstid, priser, notarpåtegning og erhvervskredit.",
    },
    hero: { title: "Ofte stillede spørgsmål", subtitle: "Det svar, du leder efter, findes her." },
    categoriesTitle: "Kategorier",
    searchPlaceholder: "Søg efter spørgsmål eller nøgleord…",
    empty: "Ingen spørgsmål matchede din søgning. Prøv et andet ord, eller kontakt os.",
    categories: FAQ_CATEGORIES_DA,
    items: FAQ_ITEMS_DA,
    notFound: {
      title: "Fandt du ikke svaret på dit spørgsmål?",
      contact: "Kontakt os",
      whatsapp: "WhatsApp-support",
    },
  },

  contact: {
      introTitle: `Velkommen`,
      introDesc: `Før vi begynder, må jeg da bede om Deres navn og e-mailadresse, så jeg bedre kan hjælpe Dem?`,
      start: `Start chat`,
      introError: `Indtast venligst Deres navn og e-mailadresse.`,
    seo: {
      title: "Kontakt",
      description: "Kom i kontakt med TercümExpert: telefon, e-mail, WhatsApp og kontaktformular.",
    },
    hero: { title: "Kontakt", subtitle: "Hvordan kan vi hjælpe dig?" },
    infoTitle: "Kontaktoplysninger",
    labels: {
      phone: "Telefon",
      email: "E-mail",
      whatsapp: "WhatsApp",
      address: "Adresse",
      hours: "Åbningstider",
    },
    form: {
      title: "Kontakt os",
      fields: {
        name: "Fulde navn",
        email: "E-mail",
        phone: "Telefon",
        subject: "Emne",
        message: "Besked",
        consent: "Jeg har læst og godkender <kvkk>KVKK-oplysningserklæringen</kvkk>.",
      },
      submit: "Send besked",
      success: "Din besked er modtaget. Vi vender tilbage til dig hurtigst muligt.",
    },
    map: {
      title: "Vores placering",
      subtitle: "Find os på kortet",
      placeholder: "Kortområde",
      note: "Placeringskortet vises her snart.",
    },
  },

  auth: {
    seo: {
      title: "Log ind / Opret konto",
      description: "Log ind på din TercümExpert-konto, eller opret en ny.",
    },
    tabs: { login: "Log ind", register: "Opret konto" },
    google: "Fortsæt med Google",
    or: "eller",
    fields: {
      firstName: "Fornavn",
      lastName: "Efternavn",
      email: "E-mail",
      password: "Adgangskode",
      code: "Bekræftelseskode",
    },
    login: {
      title: "Log ind på din konto",
      submit: "Log ind",
      noAccount: "Har du ikke en konto?",
      switchToRegister: "Opret konto",
    },
    register: {
      title: "Opret en ny konto",
      submit: "Opret konto",
      haveAccount: "Har du allerede en konto?",
      switchToLogin: "Log ind",
      consent: "Ved at oprette en konto accepterer jeg <kvkk>KVKK-oplysningserklæringen</kvkk> og <privacy>privatlivspolitikken</privacy>.",
    },
    verify: {
      title: "Bekræft din e-mail",
      desc: "— indtast den 6-cifrede kode, vi sendte til denne adresse.",
      submit: "Bekræft og fortsæt",
      spam: "Koden kan være forsinket et par minutter; tjek også din spam-/uønsket post-mappe.",
      resend: "Send kode igen",
      resent: "En ny kode er sendt.",
      back: "Gå tilbage",
    },
    signedIn: {
      title: "Min konto",
      greeting: "Velkommen",
      logout: "Log ud",
    },
    orders: {
      title: "Mine bestillinger",
      empty: "Du har ingen bestillinger endnu. Du kan oprette din første bestilling via Beregn pris.",
      loading: "Indlæser bestillinger…",
      error: "Bestillingerne kunne ikke indlæses. Opdater venligst siden.",
      status: {
        received: "Modtaget",
        in_progress: "Under behandling",
        translated: "Oversættelse gennemført",
        shipped: "Afsendt",
        delivered: "Leveret",
        cancelled: "Annulleret",
      },
      track: "Følg",
    },
    errors: {
      nameRequired: "Fornavn og efternavn er påkrævet.",
      emailInvalid: "Indtast en gyldig e-mail.",
      passwordShort: "Adgangskoden skal være på mindst 6 tegn.",
      codeInvalid: "Indtast venligst den 6-cifrede kode.",
      consentRequired: "Godkendelse er påkrævet for at fortsætte.",
    },
  },

  blog: {
    seo: { title: "Blog", description: "Vejledende indhold om oversættelse, notarpåtegning, apostille og lokalisering." },
    hero: { title: "Blog", subtitle: "Vejledninger fra oversættelsens verden." },
    searchPlaceholder: "Søg i indlæg…",
    readingTime: "min. læsning",
    relatedTitle: "Relaterede indlæg",
    allCategories: "Alle",
    empty: "Ingen indlæg matchede dette kriterium.",
  },

  legal: {
    lastUpdatedLabel: `Senest opdateret`,
    draftNotice: `I nedenstående tekst udfyldes de felter, der er angivet i kantede parenteser ([...]), med jeres virksomhedsoplysninger. Teksterne er alene af generel oplysende karakter, og det anbefales, at de gennemgås af en juridisk sagkyndig, inden de offentliggøres.`,
    kvkk: {
      seo: { title: `KVKK-oplysningstekst`, description: `Oplysningstekst om behandlingen af dine personoplysninger i henhold til KVKK nr. 6698.` },
      title: `KVKK-oplysningstekst`,
      sections: [
        { heading: `Dataansvarlig`, body: `I henhold til lov nr. 6698 om beskyttelse af personoplysninger (“KVKK”) behandles dine personoplysninger i det nedenfor beskrevne omfang af [ŞİRKET ÜNVANI] (“TercümExpert”) i egenskab af dataansvarlig. Adresse: [ADRES]. E-mail: [E-POSTA]. Telefon: [TELEFON].` },
        { heading: `Behandlede personoplysninger`, body: `Der behandles dine identitets- og kontaktoplysninger (fornavn, efternavn, e-mailadresse, telefonnummer), dine leveringsadresseoplysninger, dine ordre- og transaktionsoplysninger, oplysninger indeholdt i de dokumenter, du fremsender til os med henblik på oversættelse, samt behandlingssikkerhedsoplysninger vedrørende din brug af webstedet (IP-adresse, sessions- og cookieregistreringer).` },
        { heading: `Behandlingsformål`, body: `Dine personoplysninger behandles med henblik på levering af ydelser vedrørende oversættelse, autoriseret tolkning samt notar- og apostillebekræftelse, udarbejdelse af tilbud og administration af ordrer, kunderelationer samt håndtering af henvendelser og klager, opfyldelse af kontraktlige og lovmæssige forpligtelser samt sikring af ydelsernes sikkerhed.` },
        { heading: `Behandlingens retsgrundlag`, body: `Dine oplysninger behandles på grundlag af, at behandlingen er nødvendig for indgåelse eller opfyldelse af en aftale, opfyldelse af vores retlige forpligtelser, fastlæggelse og forsvar af en rettighed samt vores legitime interesser, forudsat at dette ikke krænker dine grundlæggende rettigheder og frihedsrettigheder; hvor det er påkrævet, behandles de på grundlag af dit udtrykkelige samtykke (KVKK m.5 og m.6).` },
        { heading: `Indsamlingsmetode`, body: `Dine personoplysninger indsamles elektronisk via formularer på webstedet, medlemskabs- og ordreprocesser, e-mail og øvrige kommunikationskanaler.` },
        { heading: `Videregivelse af personoplysninger`, body: `Dine oplysninger kan i det omfang, ydelsen kræver det, videregives til vores leverandører i ind- og udland, hos hvem vi indkøber hosting, infrastruktur, autentificering, e-mail og analyse, samt til kompetente offentlige myndigheder og institutioner, i overensstemmelse med betingelserne i KVKK m.8 og m.9. Da serverne hos visse af de infrastruktur- og tjenesteudbydere, vi anvender, er beliggende i udlandet, kan dine oplysninger overføres til udlandet inden for rammerne af de garantier, der er fastsat i lovgivningen.` },
        { heading: `Opbevaringsperioder`, body: `Dine personoplysninger opbevares i den periode, som behandlingsformålet kræver, samt i de forældelses- og opbevaringsperioder, der er fastsat i den relevante lovgivning (såsom skatte-, handels- og forbrugerlovgivning); ved periodernes udløb slettes, tilintetgøres eller anonymiseres de.` },
        { heading: `Den registreredes rettigheder`, body: `I henhold til KVKK m.11 har du ret til at få oplyst, om dine personoplysninger behandles, og hvis dette er tilfældet at anmode om oplysninger herom, at få oplyst behandlingsformålet og hvorvidt oplysningerne anvendes i overensstemmelse hermed, at kende de tredjeparter i ind- eller udland, som oplysningerne er videregivet til, at kræve berigtigelse, hvis oplysningerne er ufuldstændige eller urigtige, at kræve sletning eller tilintetgørelse, når betingelserne herfor er opfyldt, at kræve, at disse handlinger meddeles de tredjeparter, som oplysningerne er videregivet til, at gøre indsigelse mod et resultat til ugunst for dig, som fremkommer alene ved automatiseret analyse, samt at kræve erstatning for et tab, du måtte lide.` },
        { heading: `Fremgangsmåde for henvendelse`, body: `Du kan fremsætte dine anmodninger vedrørende dine rettigheder skriftligt til [E-POSTA] eller til adressen [ADRES] i overensstemmelse med “Veri Sorumlusuna Başvuru Usul ve Esasları Hakkında Tebliğ”. Din anmodning behandles afhængigt af dens art hurtigst muligt og senest inden for tredive dage.` },
      ],
    },
    privacy: {
      seo: { title: `Privatlivspolitik`, description: `Vores politik vedrørende fortroligheden af dine personoplysninger og dokumenter.` },
      title: `Privatlivspolitik`,
      sections: [
        { heading: `Indledning`, body: `Hos TercümExpert lægger vi vægt på dit privatliv. Denne privatlivspolitik beskriver, hvilke oplysninger vi indsamler, til hvilke formål og hvordan vi beskytter dem i forbindelse med de ydelser, vi leverer via [WEB ADRESİ]. Du kan finde nærmere oplysninger om behandlingen af personoplysninger i KVKK-oplysningsteksten.` },
        { heading: `Oplysninger, vi indsamler`, body: `Vi kan indsamle konto- og kontaktoplysninger (fornavn, efternavn, e-mail, telefon), ordre- og leveringsoplysninger, de dokumenter og deres indhold, som du fremsender til os med henblik på oversættelse, transaktionsoplysninger vedrørende betaling samt tekniske data om din brug af webstedet (IP-adresse, browseroplysninger, cookieregistreringer).` },
        { heading: `Formål med brugen af oplysninger`, body: `Vi anvender dine oplysninger til at levere ydelserne, administrere tilbud og ordrer, kommunikere med dig, opfylde vores lovmæssige forpligtelser samt forbedre ydelsernes kvalitet og sikkerhed. Vi behandler dine dokumenter alene i det omfang, den ydelse, du har anmodet om, kræver det.` },
        { heading: `Dokumentfortrolighed`, body: `De dokumenter, der er genstand for oversættelse, behandles som fortrolige. Kun den autoriserede oversætter og det personale, der udfører den pågældende ydelse, har adgang til disse dokumenter i den periode, opgaven kræver; dine dokumenter deles ikke med tredjeparter til andre formål end ydelsens udførelse.` },
        { heading: `Tredjeparts tjenesteudbydere`, body: `Ved leveringen af vores ydelser gør vi brug af pålidelige tredjepartsudbydere inden for hosting og infrastruktur, autentificering, e-mailudsendelse, analyse og (når det er aktiveret) betaling. Disse udbydere kan alene tilgå dine oplysninger med henblik på at levere den ydelse, de er blevet betroet, og er underlagt kontraktlige fortrolighedsforpligtelser; nogle af dem kan have servere beliggende i udlandet.` },
        { heading: `Datasikkerhed`, body: `For at beskytte dine oplysninger mod uautoriseret adgang anvender vi kryptering under overførsel, adgangsbegrænsninger samt passende administrative og tekniske foranstaltninger. Selvom ingen metode kan garantere absolut sikkerhed, træffer vi rimelige og tidssvarende foranstaltninger for at beskytte dine oplysninger.` },
        { heading: `Cookies`, body: `Der anvendes cookies og lignende teknologier på vores websted. For nærmere oplysninger om typerne og administration af dine præferencer kan du gennemgå vores cookiepolitik.` },
        { heading: `Dine rettigheder`, body: `Du kan udøve dine rettigheder i henhold til KVKK, herunder retten til indsigt i, berigtigelse og sletning af dine personoplysninger. Du kan kontakte os vedrørende dine anmodninger via [E-POSTA].` },
        { heading: `Børns privatliv`, body: `Vores ydelser er ikke rettet mod personer under 18 år, og vi indsamler ikke bevidst personoplysninger om børn.` },
        { heading: `Ændringer`, body: `Denne politik kan blive opdateret fra tid til anden. Den gældende version offentliggøres altid på denne side; ved væsentlige ændringer informeres der på passende vis.` },
        { heading: `Kontakt`, body: `Ved spørgsmål vedrørende privatliv: E-mail: [E-POSTA] · Telefon: [TELEFON] · Adresse: [ADRES].` },
      ],
    },
    distanceSales: {
      seo: { title: `Aftale om fjernsalg`, description: `Aftale om fjernsalg vedrørende salg af ydelser i henhold til lov nr. 6502.` },
      title: `Aftale om fjernsalg`,
      sections: [
        { heading: `Parterne`, body: `Denne aftale om fjernsalg (“Aftalen”) er indgået elektronisk mellem på den ene side [ŞİRKET ÜNVANI] (“Sælger”; adresse: [ADRES], e-mail: [E-POSTA], telefon: [TELEFON]) og på den anden side den forbruger, der afgiver ordren (“Køber”), i henhold til lov nr. 6502 om forbrugerbeskyttelse og Mesafeli Sözleşmeler Yönetmeliği.` },
        { heading: `Aftalens genstand`, body: `Aftalens genstand er levering af ydelser vedrørende oversættelse, autoriseret tolkning samt notar- og apostillebekræftelse, som Køber har bestilt elektronisk via [WEB ADRESİ], og hvis egenskaber og salgspris er angivet i ordreoversigten.` },
        { heading: `Ydelsens egenskaber og pris`, body: `Den bestilte ydelses type, omfang, leveringsform (digital eller fragt) og samlede pris inklusive afgifter vises tydeligt for Køber under bestillingen og fremgår af ordrebekræftelsen. Prisen beregnes ud fra den valgte ydelse og dokumentets egenskaber.` },
        { heading: `Betaling`, body: `Betalingen gennemføres med de betalingsmetoder, der tilbydes i ordretrinnet. Ordren behandles, efter at betalingen er blevet bekræftet.` },
        { heading: `Opfyldelse og levering`, body: `Ved digital levering fremsendes oversættelsen efter færdiggørelsen via Købers konto eller e-mail. Ved fysiske dokumenter med original underskrift eller autoriserede dokumenter sker leveringen med fragt til den adresse, Køber har oplyst. De forventede leveringstider angives under bestillingen; de kan variere afhængigt af dokumentmængden og bekræftelsesprocesserne.` },
        { heading: `Fortrydelsesret`, body: `Køber har som udgangspunkt ved aftaler om levering af ydelser fortrydelsesret inden for fjorten (14) dage fra aftalens indgåelse uden at skulle angive nogen begrundelse. De nedenfor anførte undtagelser gælder dog.` },
        { heading: `Undtagelser fra fortrydelsesretten`, body: `I henhold til Mesafeli Sözleşmeler Yönetmeliği m.15 kan fortrydelsesretten ikke udøves for ydelser, hvis udførelse er påbegyndt med Købers samtykke og fuldført inden fortrydelsesfristens udløb, samt for varer og ydelser, der er fremstillet særligt efter Købers ønsker eller personlige behov (herunder oversættelses- og bekræftelsesydelser, der er udarbejdet specifikt til en person eller et dokument). Anmodninger om annullering, der fremsendes, inden oversættelsesarbejdet er påbegyndt, vurderes særskilt.` },
        { heading: `Annullering og tilbagebetaling`, body: `For ordrer, hvis udførelse ikke er påbegyndt, kan anmodninger om annullering fremsendes via [E-POSTA]; godkendte tilbagebetalinger gennemføres inden for rimelig tid med den betalingsmetode, der er anvendt. For personligt tilpassede ydelser, hvis udførelse er påbegyndt eller fuldført, kan tilbagebetaling som følge af opgavens art ikke være mulig.` },
        { heading: `Tvistløsning`, body: `Ved tvister, der måtte udspringe af denne Aftale, er Tüketici Hakem Heyetleri på Købers bopæl eller på det sted, hvor transaktionen er gennemført, samt forbrugerdomstolene kompetente inden for de beløbsgrænser, som Ticaret Bakanlığı hvert år bekendtgør.` },
        { heading: `Ikrafttræden`, body: `Ved at bekræfte ordren erklærer Køber at have læst og accepteret alle vilkårene i denne Aftale. Aftalen træder i kraft ved bekræftelsen af ordren.` },
      ],
    },
    cookies: {
      seo: { title: `Cookiepolitik`, description: `Oplysninger om de cookies, der anvendes på vores websted, og administration af præferencer.` },
      title: `Cookiepolitik`,
      sections: [
        { heading: `Hvad er en cookie?`, body: `Cookies er små tekstfiler, der gemmes i din browser, når du besøger et websted. De anvendes til at gøre webstedet mere sikkert og funktionelt, til at huske dine præferencer og til at indhente brugsstatistikker.` },
        { heading: `Hvorfor anvender vi cookies?`, body: `Vi anvender cookies til at sikre webstedets grundlæggende funktioner, beskytte sessionssikkerheden, måle ydeevnen og, afhængigt af dit samtykke, forbedre vores ydelser samt udføre markedsføringsaktiviteter.` },
        { heading: `Cookiekategorier`, body: `Nødvendige cookies er påkrævede for webstedets drift og sikkerhed og kan ikke fravælges. Ydelses- og analysecookies hjælper os med at forstå de besøgendes interaktion. Markedsføringscookies understøtter levering af indhold og annoncer, der passer til dine interesser. Præferencecookies husker dine valg såsom sprog. Analyse- og markedsføringscookies aktiveres alene med dit udtrykkelige samtykke.` },
        { heading: `Tredjepartscookies`, body: `Til analyse- og markedsføringsformål kan vi gøre brug af tredjepartstjenester (for eksempel værktøjer til besøgsstatistik og annoncemåling). Disse tjenester kan placere deres egne cookies og behandle data inden for rammerne af deres egne privatlivspolitikker.` },
        { heading: `Administration af cookiepræferencer`, body: `Du kan til enhver tid give eller ændre dine præferencer vedrørende ikke-nødvendige cookies via det cookiepræferenceværktøj, der tilbydes på webstedet. Du kan desuden slette eller blokere cookies i din browsers indstillinger; i så fald vil visse dele af webstedet dog muligvis ikke fungere korrekt.` },
        { heading: `Opbevaringsperioder`, body: `Cookies opbevares afhængigt af deres type i sessionens varighed eller i en bestemt periode. Sessionscookies slettes, når browseren lukkes; permanente cookies udløber ved udgangen af den fastsatte periode, eller når du sletter dem.` },
        { heading: `Ændringer`, body: `Denne cookiepolitik kan blive opdateret fra tid til anden. Den gældende version offentliggøres altid på denne side.` },
      ],
    },
    partnership: {
      seo: { title: "Partneraftale", description: "Vilkår og betingelser for TercümExperts partnerprogram (henvisningsprogram)." },
      title: "Partneraftale",
      sections: [
        { heading: "Parter og genstand", body: "Denne Partneraftale indgås mellem [VIRKSOMHEDSNAVN] (“TercümExpert”) på den ene side og den forretningspartner, der ansøger om og godkendes til programmet (“Partner”), på den anden side, med henblik på at regulere vilkårene for TercümExperts henvisningsprogram (partnerprogram)." },
        { heading: "Ansøgning og godkendelse", body: "Partnerstatus opnås ved at udfylde ansøgningsformularen på partnersiden og blive godkendt af TercümExpert. Godkendelse sker efter TercümExperts skøn, og en ansøgning kan afvises. Partneren bekræfter sin e-mailadresse som led i programmet; der opkræves intet oprettelsesgebyr for at deltage." },
        { heading: "Invitationslink og kundetilknytning", body: "Hver godkendt Partner tildeles et unikt, personligt invitationslink og en tilhørende QR-kode. En kunde, der ankommer via dette link eller QR-kode og tilmelder sig for første gang, tilknyttes permanent den pågældende Partner; tilknytningen sker i det øjeblik, tilmeldingen sker første gang, og kan ikke ændres efterfølgende. Provision opstår kun af ordrer fra kunder, der er tilknyttet Partneren på denne måde." },
        { heading: "Provisionsstruktur", body: "Partnerens andel beregnes eksklusive merværdiafgift (moms) og eksklusive forskelle for tillægsydelser, som følger: 20% af grundoversættelsesprisen; hvis hastelevering vælges, 20% af haste­leveringsforskellen; hvis autoriseret (edsvoren) oversættelse vælges, 10% af forskellen for den edsvorne oversættelse. Af gebyrer for notarbekræftelse, apostille­støtte og fysisk (kurér)levering udbetales der ingen andel til Partneren, og momsen tages ikke som grundlag for provisionen. Disse procenter er faste; satserne forbliver gyldige, selv om priserne ændres. TercümExpert kan opdatere satser og vilkår mod forudgående varsel." },
        { heading: "Optjening og tegnebog", body: "Provisionen tilføjes Partnerens tegnebog, når den henviste kundes ordre er afsluttet, og forbliver låst i syv (7) dage fra tilføjelsesdatoen; den bliver til rådighed for udbetaling, når denne periode udløber. Annullerede, refunderede eller ubetalte ordrer tages ikke som grundlag for provisionen." },
        { heading: "Betalinger", body: "Beløb til rådighed for udbetaling udbetales til den af Partneren angivne IBAN den 2. og 17. i hver måned. For at en betaling kan foretages, skal de obligatoriske felter i Partnerens profil være fuldt udfyldt, og IBAN samt kontohaveroplysningerne skal være godkendt af TercümExpert. Skattemæssige forpligtelser vedrørende betalinger er underlagt den gældende lovgivning." },
        { heading: "Partnerens forpligtelser", body: "Partneren accepterer at anvende korrekte og ikke-vildledende oplysninger i sin markedsføring, at afstå fra adfærd, der skader TercümExperts brand og omdømme, at holde sine kontakt- og betalingsoplysninger opdaterede og at overholde den gældende lovgivning." },
        { heading: "Forbudt adfærd", body: "Spam og uopfordrede massebeskeder, vildledende reklame, falske eller selvhenvisninger (herunder at Partneren afgiver ordrer via sin egen konto) og adfærd, der udgør illoyal konkurrence, er forbudt. Sådanne overtrædelser er grundlag for annullering af de pågældende provisioner og opsigelse af Aftalen." },
        { heading: "Brug af varemærke", body: "Partneren må kun anvende TercümExperts varemærke, logo og markedsføringsmateriale med TercümExperts skriftlige godkendelse og inden for de regler, som TercümExpert stiller til rådighed." },
        { heading: "Fortrolighed og personoplysninger", body: "Parterne forpligter sig til at beskytte de fortrolige oplysninger, de modtager i henhold til Aftalen. Partneren behandler henviste kunders personoplysninger udelukkende til programmets formål og i overensstemmelse med den gældende databeskyttelseslovgivning." },
        { heading: "Uafhængig part", body: "Partneren er en uafhængig part; Partneren er ikke ansat, repræsentant eller agent for TercümExpert og kan ikke indgå forpligtelser over for tredjemand på TercümExperts vegne." },
        { heading: "Varighed og opsigelse", body: "Aftalen forbliver i kraft, indtil en af parterne varsler opsigelse. TercümExpert kan opsige Aftalen med øjeblikkelig virkning i tilfælde af misligholdelse af forpligtelser; provisioner, der stammer fra uretmæssige eller misbrugende henvisninger, udbetales ikke. Ved opsigelse udbetales frigivne, retmæssige beløb i overensstemmelse med de gældende vilkår." },
        { heading: "Ændringer, tvister og ikrafttræden", body: "TercümExpert kan fra tid til anden opdatere denne Aftale; den gældende version offentliggøres altid på denne side. Aftalen er underlagt lovgivningen i Republikken Tyrkiet. Ved at bekræfte ansøgningen erklærer Partneren at have læst og accepteret alle Aftalens vilkår." },
      ],
    },
  },

  admin: {
    attachmentImage: 'Billede',
    attachmentFile: 'Dokument',
    title: "Administrationspanel",
    summary: `{total} samtaler · {leads} kontaktanmodninger`,
    onlyLeads: `Kun kontaktanmodninger`,
    loading: `Indlæser optegnelser…`,
    error: `Optegnelserne kunne ikke indlæses. Kontrollér, om Supabase-tabellen og tilladelserne (RLS) er konfigureret.`,
    empty: `Der er endnu ingen optegnelser.`,
    selectHint: `Vælg en samtale til venstre for at få den vist.`,
    contactRequest: `Kontaktanmodning`,
    contactInfo: `Kontaktoplysninger`,
    fieldName: `Navn`,
    fieldEmail: `E-mail`,
    fieldPhone: `Telefon`,
    fieldMessage: `Besked`,
    requestBadge: `anmodning`,
    noMessages: `Der er ingen beskeder i denne optegnelse (kun en kontaktanmodning).`,
    loginTitle: `Login påkrævet`,
    loginDesc: `Log ind med en administratorkonto for at få vist denne side.`,
    login: `Log ind`,
    noAccessTitle: `De har ikke adgang`,
    noAccessDesc: `Denne side er kun tilgængelig for administratorer.`,
    loadingAuth: `Indlæser…`,
  },
  footer: {
    tagline: "Din pålidelige partner inden for professionelle oversættelsestjenester.",
    columns: {
      quickLinks: "Hurtige links",
      services: "Ydelser",
      contact: "Kontakt",
    },
    quickLinks: {
      corporate: "Erhverv",
      services: "Vores ydelser",
      quote: "Beregn pris",
      blog: "Blog",
      faq: "Ofte stillede spørgsmål",
      contact: "Kontakt",
    },
    serviceLinks: {
      sworn: "Autoriseret oversættelse",
      notarized: "Oversættelse med notarpåtegning",
      apostille: "Apostilleproces",
      corporate: "Løsninger til erhverv",
      partnership: "Partnerprogram",
    },
    legal: {
      kvkk: "KVKK",
      privacy: "Privatlivspolitik",
      distanceSales: "Fjernsalgsaftale",
      cookies: "Cookiepolitik",
    },
    socialTitle: "Følg os",
    whatsapp: "WhatsApp-support",
    rights: "Alle rettigheder forbeholdes.",
  },

  cookie: {
    title: "Cookiepræferencer",
    desc: "Vi bruger cookies til at forbedre din oplevelse. Andre cookies end de nødvendige kører kun med dit samtykke.",
    accept: "Accepter",
    reject: "Afvis",
    manage: "Administrer præferencer",
    save: "Gem præferencer",
    categories: {
      necessary: { label: "Nødvendige", desc: "Påkrævet for, at webstedet fungerer; kan ikke deaktiveres." },
      analytics: { label: "Analyse", desc: "Hjælper os med at forstå brugen." },
      marketing: { label: "Marketing", desc: "Til relevant indhold og annoncer." },
      preferences: { label: "Præferencer", desc: "Husker dine præferencer." },
    },
  },

  chatbot: {
    attach: {
      button: 'Vedhæft fil',
      tooLarge: 'Filen er for stor (maks. 25 MB).',
      unsupported: 'Jeg kan ikke analysere lyd- eller videofiler i chatten. Du kan uploade dem på tilbudssiden.',
      cannotRead: 'Jeg kunne ikke læse denne fil. Du kan uploade den på tilbudssiden eller prøve et andet format.',
      reading: 'Læser filen…',
      remove: 'Fjern',
    },
    nudge: 'Hvordan kan jeg hjælpe dig?',
    title: "TercümExpert-support",
    open: "Åbn chat",
    close: "Luk chat",
    minimize: "Minimér",
    clear: "Ryd samtale",
    inputPlaceholder: "Skriv din besked…",
    send: "Send",
    typing: "Skriver…",
    welcome:
      "Hej og velkommen til TercümExpert. Jeg kan hjælpe dig med oversættelse, priser, notarpåtegning, apostille eller erhvervsydelser.",
    quickQuestions: [
      "Hvordan beregnes prisen?",
      "Hvad er autoriseret oversættelse?",
      "Jeg vil uploade et dokument",
      "Jeg vil have et erhvervstilbud",
      "Er notarpåtegning påkrævet?",
      "Sæt mig i forbindelse med en medarbejder",
    ],
    handoff: "Kom i forbindelse med en medarbejder",
    toWhatsapp: "Overfør til WhatsApp",
    disclaimer: "Disse oplysninger er generelle; bekræft venligst de præcise krav med den relevante myndighed.",
    sensitiveWarning:
      "Del venligst ikke følsomme personoplysninger via denne chat. Du kan sende dine dokumenter via det sikre uploadområde.",
    answers: [
      `Prisen beregnes ud fra dokumentets antal ord, sprogkombinationen, typen af ydelse (autoriseret, notarbekræftet, apostille) og den ønskede leveringstid. For at få et øjeblikkeligt prisestimat kan De uploade Deres dokument eller indtaste oplysningerne på siden Beregn Pris.`,
      `En autoriseret oversættelse er en officiel oversættelse udført af en autoriseret translatør og bekræftet med translatørens underskrift og stempel. Offentlige myndigheder kræver oftest en autoriseret oversættelse, og en notarbekræftelse kan tilføjes efter behov.`,
      `De kan sende Deres dokument via det sikre uploadfelt på siden Beregn Pris. Efter uploaden ser De med det samme et prisestimat og kan færdiggøre Deres bestilling.`,
      `Til Deres erhvervsmæssige behov tilbyder vi særlige priser og prioriteret levering ved regelmæssige og større oversættelsesopgaver. For nærmere oplysninger kan De læse mere på vores Erhvervsside eller kontakte os.`,
      `Behovet for en notarbekræftelse afhænger af den myndighed, De skal indlevere dokumentet til, samt af sagens art. Nogle sager accepterer udelukkende en autoriseret oversættelse, mens andre også kræver en notarbekræftelse. Er De i tvivl, hjælper vi Dem gerne.`,
      `Lad os straks sætte Dem i forbindelse med en af vores kunderådgivere. Via knappen nedenfor kan De skrive til os på WhatsApp.`,
    ],
    fallback: `En af vores kunderådgivere kan give Dem den mest præcise hjælp med Deres spørgsmål. Via knappen nedenfor kan De skrive til os på WhatsApp, og Deres besked videresendes klar til afsendelse.`,
    contact: {
      "introTitle": "Velkommen",
      "introDesc": "For at kunne hjælpe dig bedre, må jeg først få dit navn og din e-mailadresse?",
      "start": "Start samtalen",
      "introError": "Indtast venligst dit navn og din e-mailadresse.",
      whatsapp: `WhatsApp`,
      email: `E-mail`,
      phone: `Telefon`,
      leaveInfo: `Efterlad mine kontaktoplysninger`,
      formTitle: `Lad os kontakte Dem`,
      formDesc: `Efterlad Deres oplysninger, så kontakter vores team Dem hurtigst muligt.`,
      name: `Deres navn`,
      emailField: `E-mail`,
      phoneField: `Telefon`,
      message: `Deres besked (valgfrit)`,
      submit: `Send`,
      submitting: `Sender…`,
      thanks: `Tak, vores team kontakter Dem hurtigst muligt.`,
      errorRequired: `Indtast venligst en e-mail eller et telefonnummer.`,
      back: `Tilbage`,
    },
  },

  translator: {
    "seo": {
      "title": "Oversætterpanel — TercümExpert",
      "description": "Oversætteransøgning og arbejdspanel."
    },
    "loading": "Indlæser…",
    "loginTitle": "Login påkrævet",
    "loginDesc": "Dette område er kun for oversættere og administratorer. Log venligst ind for at fortsætte.",
    "login": "Log ind",
    "setupTitle": "Panelet er ikke klart endnu",
    "setupDesc": "Oversætterinfrastrukturen (databasen) er endnu ikke opsat. Panelet aktiveres, når opsætningen er fuldført.",
    "applyTitle": "Oversætteransøgning",
    "applyDesc": "Udfyld dine oplysninger for at blive en del af vores netværk af freelanceoversættere. Din ansøgning aktiveres efter godkendelse fra administrator.",
    "applyNote": "Dine oplysninger anvendes kun til evaluering og betaling.",
    "form": {
      "fullName": "Fulde navn",
      "birthDate": "Fødselsdato",
      "phone": "Telefon",
      "country": "Land",
      "city": "By / Region",
      "selectCountry": "Vælg land",
      "selectCity": "Vælg by / region",
      "cityNeedsCountry": "Vælg et land først",
      "address": "Fuld adresse",
      "isSworn": "Er du en autoriseret (statsautoriseret) oversætter?",
      "isSwornHint": "Markér dette, hvis du har en notariseret edsaflæggelse. Du vil blive prioriteret til opgaver, der kræver autoriseret oversættelse.",
      "iban": "IBAN",
      "ibanName": "IBAN-indehaver (fulde navn)",
      "languagePairs": "Sprogpar",
      "source": "Kildesprog",
      "target": "Målsprog",
      "addPair": "Tilføj",
      "removePair": "Fjern",
      "swap": "Byt retning",
      "expertise": "Ekspertiseområder",
      "submit": "Indsend ansøgning",
      "submitting": "Indsender…",
      "saved": "Dine oplysninger er blevet gemt.",
      "saveError": "Kunne ikke gemme. Prøv venligst igen.",
      "required": "Udfyld venligst de påkrævede felter.",
      "atLeastOnePair": "Tilføj mindst ét sprogpar."
    },
    "expertiseLabels": {
      "legal": "Juridisk",
      "medical": "Medicinsk",
      "technical": "Teknisk",
      "academic": "Akademisk",
      "commercial": "Kommerciel",
      "financial": "Finansiel",
      "literary": "Litterær",
      "official": "Officielle dokumenter",
      "localization": "Web / Software",
      "general": "Generel"
    },
    "pendingTitle": "Din ansøgning er under behandling",
    "pendingDesc": "Vi har modtaget din oversætteransøgning. Adgang til panelet åbnes efter administratorens gennemgang.",
    "rejectedTitle": "Ansøgning ikke godkendt",
    "rejectedDesc": "Din ansøgning blev ikke godkendt på nuværende tidspunkt. Du kan opdatere dine oplysninger og prøve igen.",
    "reapply": "Prøv igen",
    "cancelApplication": "Annuller ansøgning",
    "cancelConfirm": "Er du sikker på, at du vil annullere din ansøgning? Din registrering slettes; du kan ansøge igen senere, hvis du ønsker det.",
    "panelTitle": "Oversætterpanel",
    "tabs": {
      "profile": "Min profil",
      "pool": "Oversættelsespulje",
      "active": "Aktive opgaver",
      "pending": "Afventer godkendelse",
      "approved": "Godkendt",
      "completed": "Fuldført",
      "wallet": "Tegnebog"
    },
    "soon": "Dette afsnit kommer i næste trin.",
    "jobs": {
      "empty": "Der er ingen opgaver i dette afsnit lige nu.",
      "translator": "Oversætter",
      "sourceFiles": "Kildedokumenter",
      "translationFiles": "Uploadet oversættelse",
      "tracking": "Sporing",
      "rejectionReason": "Årsag til afvisning",
      "chooseFiles": "Vælg oversættelsesfiler",
      "filesSelected": "fil(er) valgt",
      "uploadHint": "Upload din oversættelse og, hvis nødvendigt, en digital kopi af kilden, og send den derefter til godkendelse.",
      "submit": "Send til godkendelse",
      "sending": "Sender…",
      "needFiles": "Vælg venligst mindst én fil.",
      "uploadError": "Filerne kunne ikke uploades. Prøv venligst igen.",
      "submittedMsg": "Oversættelse sendt til godkendelse.",
      "actionError": "Handlingen kunne ikke gennemføres. Prøv venligst igen.",
      "waitingApproval": "Din oversættelse afventer ledelsens godkendelse. Når den er godkendt, vises leveringstrinnet under “Godkendt”.",
      "trackingPlaceholder": "Sporingsnummer / link",
      "needTracking": "Et sporingsnummer er påkrævet ved fragtlevering.",
      "markShipped": "Afsendt — fuldfør",
      "markDelivered": "Leveret — fuldfør",
      "completedMsg": "Opgave fuldført. Din indtjening er blevet tilføjet din tegnebog.",
      "reasonPlaceholder": "Ved afvisning skal du skrive årsagen (synlig for oversætteren)…",
      "approve": "Godkend",
      "reject": "Afvis",
      "needReason": "Skriv en årsag for at afvise.",
      "approvedMsg": "Oversættelse godkendt.",
      "rejectedMsg": "Oversættelse afvist; returneret til oversætteren.",
      "statusLabel": "Status",
      "status_claimed": "Under behandling",
      "status_submitted": "Afventer godkendelse",
      "status_approved": "Godkendt — leveringstrin",
      "status_completed": "Fuldført"
    },
    "pool": {
      "loading": "Indlæser pulje…",
      "empty": "Der er ingen afventende ordrer, der matcher dine sprogpar og ekspertise lige nu.",
      "error": "Kunne ikke indlæse puljen. Prøv venligst igen.",
      "orderNo": "Ordre",
      "service": "Servicetype",
      "documentType": "Dokumenttype",
      "langPair": "Sprogpar",
      "words": "Ord",
      "pagesUnit": "sider",
      "deadline": "Frist",
      "daysUnit": "arbejdsdage",
      "note": "Kundens bemærkning",
      "customerInfo": "Kundeoplysninger",
      "deliveryInfo": "Kunde- og leveringsoplysninger",
      "customerName": "Fulde navn",
      "customerEmail": "E-mail",
      "customerPhone": "Telefon",
      "deliveryAddress": "Leveringsadresse",
      "text": "Ordretekst",
      "files": "Dokumenter",
      "earning": "Din indtjening for denne opgave",
      "urgent": "Haster",
      "sworn": "Autoriseret",
      "notary": "Notariseret",
      "apostille": "Apostille",
      "cargo": "Fragtlevering",
      "digital": "Digital levering",
      "claim": "Tag denne opgave",
      "claiming": "Tager…",
      "claimed": "Du har taget opgaven.",
      "claimError": "Kunne ikke tage opgaven. Den kan være taget af en anden; opdater listen.",
      "ibanRequired": "Før du kan tage opgaver, skal dine IBAN-oplysninger verificeres af ledelsen. Indtast din IBAN i din profil; når den er verificeret, kan du tage opgaver fra puljen."
    },
    "profile": {
      "statusApproved": "Godkendt oversætter",
      "verifiedIban": "IBAN verificeret",
      "unverifiedIban": "IBAN ikke verificeret",
      "current": "Gemt",
      "edit": "Gem oplysninger",
      "ibanReminder": "For at modtage dine betalinger skal du indtaste og gemme dine IBAN-oplysninger. Når de er verificeret af administrator, foretages betalinger til denne konto.",
      "lockedHint": "Kan ikke ændres efter godkendelse",
      "revokeTitle": "Denne ændring vil tilbagekalde din godkendelse",
      "revokeWarning": "Hvis du ændrer dine sprogpar, autoriseringsstatus eller ekspertiseområder, sendes din konto tilbage til ledelsens gennemgang (sat til afventende). Dine opgaver, registreringer og tegnebog BEVARES; når du er godkendt igen, fortsætter du, hvor du slap.",
      "consent": "Jeg har læst og accepterer",
      "ibanReverify": "Du ændrer din IBAN. Den nye IBAN sendes tilbage til ledelsens gennemgang; din konto forbliver aktiv, men du kan ikke tage nye opgaver fra puljen, før IBAN er verificeret."
    },
    "admin": {
      "title": "Ledelsespanel",
      "translatorsTab": "Oversættere",
      "applicationsTab": "Ansøgninger",
      "ibanTab": "IBAN-godkendelser",
      "ordersTab": "Ordrer",
      "paymentsTab": "Betalinger",
      "noIbanPending": "Ingen oversættere afventer IBAN-godkendelse.",
      "ibanHint": "Godkend nyligt indtastede eller ændrede IBAN'er her. Indtil de er godkendt, kan oversætteren ikke tage nye opgaver fra puljen.",
      "ibanApprove": "Godkend IBAN",
      "paymentsHint": "På betalingsdagen (den 1. og 16. i hver måned): for hver oversætter, du har betalt, skal du uploade kvitteringen og klikke på “Markér som betalt”. Knappen virker ikke uden en kvittering. Oversættere med en nulsaldo vises ikke her.",
      "noPayments": "Ingen oversættere med en saldo, der skal betales.",
      "paymentAmount": "Beløb til betaling",
      "uploadReceipt": "Upload kvittering",
      "receiptUploaded": "Kvittering uploadet",
      "receiptRequired": "Upload en kvittering først",
      "uploading": "Uploader…",
      "markPaid": "Markér som betalt",
      "paid": "Betaling registreret, og oversætteren blev underrettet med kvitteringen.",
      "panelHint": "Følg godkendte oversættere efter profil, gennemgå ansøgninger og administrer arbejdsgangen for alle ordrer.",
      "summary": "{total} oversættere · {pending} afventende ansøgninger",
      "applicationsSummary": "{total} ansøgninger · {pending} afventer gennemgang",
      "noApproved": "Ingen godkendte oversættere endnu.",
      "noPending": "Ingen afventende ansøgninger.",
      "noMatch": "Ingen registreringer matcher filtrene.",
      "loadError": "Kunne ikke indlæse registreringer. Kontrollér databasen og rettighederne (RLS).",
      "noApplications": "Ingen oversætterregistreringer endnu.",
      "filters": {
        "namePlaceholder": "Søg efter navn…",
        "country": "Land",
        "city": "By / Region",
        "anyCountry": "Alle lande",
        "anyCity": "Alle byer",
        "cityNeedsCountry": "Vælg et land først",
        "sourceLang": "Kildesprog",
        "targetLang": "Målsprog",
        "anyLang": "Alle",
        "eitherDirection": "Begge retninger (kilde↔mål)",
        "expertise": "Ekspertiseområder",
        "clear": "Ryd filtre",
        "results": "{n} registreringer"
      },
      "orders": {
        "loadError": "Kunne ikke indlæse ordrer. Prøv venligst igen.",
        "empty": "Ingen ordrer endnu.",
        "searchPlaceholder": "Søg efter ordrenr. eller kundenavn…",
        "results": "{n} ordrer",
        "customer": "Kunde",
        "translator": "Oversætter",
        "unassigned": "Ikke tildelt",
        "status": "Status",
        "done": "Fuldført",
        "inProgress": "Under behandling",
        "completedOn": "Fuldført den",
        "placedOn": "Ordredato",
        "total": "I alt",
        "statusAvailable": "I pulje (ikke taget)",
        "statusClaimed": "Under oversættelse",
        "statusSubmitted": "Afventer godkendelse",
        "statusApproved": "Leveringstrin",
        "statusCompleted": "Fuldført",
        "statusCancelled": "Annulleret"
      },
      "profile": {
        "back": "Tilbage til oversættere",
        "adminOnly": "Denne profil er kun for ledelsen; oversætteren kan ikke se den.",
        "infoTitle": "Oplysninger",
        "walletTitle": "Tegnebog",
        "jobsTitle": "Opgaver",
        "noJobs": "Denne oversætter har ingen opgaver endnu."
      },
      "approve": "Godkend",
      "reject": "Afvis",
      "colLangs": "Sprogpar",
      "colExpertise": "Ekspertise",
      "colLocation": "By / Land",
      "swornBadge": "Autoriseret",
      "returningBadge": "Tilbagevendende oversætter",
      "ibanVerified": "IBAN verificeret",
      "ibanNotVerified": "IBAN ikke verificeret",
      "verifyIban": "Verificér IBAN",
      "unverifyIban": "Fjern verificering",
      "statusPending": "Afventer",
      "statusApproved": "Godkendt",
      "statusRejected": "Afvist",
      "actionError": "Handlingen kunne ikke gennemføres."
    },
    "wallet": {
      "total": "Samlet indtjening",
      "locked": "Låst",
      "withdrawable": "Kan udbetales",
      "paid": "Udbetalt",
      "payInfo": "Indtjening tilføjes din tegnebog, når en opgave fuldføres; den forbliver låst i 7 dage og bliver derefter tilgængelig for udbetaling. Betalinger foretages til den udbetalbare saldo den 1. og 16. i hver måned.",
      "empty": "Ingen indtjening endnu. Indtjening fra fuldførte opgaver vises her.",
      "entryOrder": "Ordre",
      "date": "Dato",
      "statusCol": "Status",
      "amount": "Beløb",
      "statusPaid": "Betalt",
      "statusUnlocked": "Kan udbetales",
      "statusPending": "Låst",
      "loadError": "Kunne ikke indlæse tegnebogen. Prøv venligst igen."
    },
    "adminWallet": {
      "firmShare": "Virksomhedens andel (inkl. moms)",
      "firmShareHint": "Virksomhedens andel = samlet beløb for fuldførte ordrer (inkl. moms) minus oversætternes indtjening.",
      "ciro": "Samlet omsætning (inkl. moms)",
      "kdv": "Moms (til staten)",
      "payouts": "Betalt til oversættere",
      "net": "Virksomhedens nettobeløb",
      "count": "{n} fuldførte ordrer",
      "empty": "Ingen fuldførte ordrer endnu.",
      "colOrder": "Ordre",
      "colTranslator": "Oversætter",
      "colDate": "Dato",
      "colTotal": "I alt (inkl. moms)",
      "colPayout": "Oversætter",
      "colFirm": "Virksomhedens andel",
      "loadError": "Kunne ikke indlæse tegnebogen. Prøv venligst igen."
    }
  },
  authx: {
    "rememberMe": "Husk mig",
    "showPassword": "Vis adgangskode",
    "hidePassword": "Skjul adgangskode",
    "forgot": "Glemt min adgangskode",
    "forgotTitle": "Nulstil adgangskode",
    "forgotDesc": "Indtast din registrerede e-mailadresse, og vi sender dig et engangslink til at nulstille din adgangskode.",
    "forgotEmail": "E-mail",
    "forgotSubmit": "Send nulstillingslink",
    "forgotSent": "Linket er blevet sendt til din e-mail. Tjek din indbakke (og din spammappe).",
    "forgotBack": "Tilbage til login",
    "resetTitle": "Angiv en ny adgangskode",
    "resetDesc": "Indtast din nye adgangskode, og bekræft den ved at skrive den igen.",
    "newPassword": "Ny adgangskode",
    "newPasswordRepeat": "Ny adgangskode (gentag)",
    "mismatch": "Adgangskoderne stemmer ikke overens.",
    "weak": "Adgangskoden skal være på mindst 6 tegn.",
    "resetSubmit": "Opdater adgangskode",
    "resetSuccess": "Din adgangskode er blevet opdateret. Du kan nu logge ind med din nye adgangskode.",
    "resetInvalid": "Linket er ugyldigt eller udløbet. Anmod venligst om et nyt nulstillingslink.",
    "goLogin": "Log ind",
    err: {
      "invalidCredentials": "Forkert e-mailadresse eller adgangskode. Kontrollér venligst dine oplysninger, og prøv igen.",
      "emailNotConfirmed": "Din e-mailadresse er endnu ikke bekræftet. Klik på bekræftelseslinket i din indbakke.",
      "alreadyRegistered": "Denne e-mailadresse er allerede registreret. Prøv at logge ind eller nulstille din adgangskode.",
      "weakPassword": "Adgangskoden skal være på mindst 6 tegn.",
      "otpInvalid": "Bekræftelseskoden er forkert eller udløbet. Anmod om en ny kode.",
      "rateLimited": "For mange forsøg. Vent venligst et øjeblik, og prøv igen.",
      "generic": "Der opstod en fejl. Prøv venligst igen senere."
    }
  },
  notFound: {
    seo: { title: "Siden blev ikke fundet", description: "Den side, du leder efter, kunne ikke findes." },
    title: "Siden blev ikke fundet",
    desc: "Den side, du leder efter, kan være blevet flyttet eller har måske aldrig eksisteret.",
    home: "Tilbage til forsiden",
  },
}
