import type { PartialDictionary } from '@/types/i18n'
import { FAQ_CATEGORIES_DE, FAQ_ITEMS_DE } from '@/content/faq-data.de'

/**
 * DEUTSCH — vollständige Übersetzung auf Basis der englischen Fassung.
 * Fallback-Kette: TR (Quelle) <- EN (Basis) <- weitere Sprachen.
 * FAQ-Fragen/-Antworten (faq.categories / faq.items) stammen aus einem
 * eigenen, sprachspezifischen Datensatz (content/faq-data.de).
 */
export const de: PartialDictionary = {
  delivery: {
    "ready": "Ihre Übersetzung ist fertig",
    "download": "Übersetzung herunterladen",
    "hint": "Ihre Übersetzung wurde auch an Ihre E-Mail-Adresse gesendet. Bitte prüfen Sie Ihren Posteingang (und den Spam-Ordner)."
  },

  partnerPanel: {
    seoTitle: "Partner-Bereich",
    seoDesc: "Reichen Sie Ihre Partneranfrage ein und erhalten Sie hier Ihren Einladungslink.",
    loading: "Wird geladen…",
    loginTitle: "Partner-Anmeldung",
    loginDesc: "Melden Sie sich an oder erstellen Sie ein Konto, um sich zu bewerben oder auf Ihren Bereich zuzugreifen.",
    login: "Anmelden / Registrieren",
    setupTitle: "Einrichtung nicht abgeschlossen",
    setupDesc: "Das Partnersystem ist noch nicht bereit.",
    applyTitle: "Partneranfrage",
    applyDesc: "Füllen Sie Ihre Angaben aus; Ihr Einladungslink wird nach Genehmigung Ihrer Anfrage aktiviert.",
    applyNote: "Ihre Anfrage wird in Kürze geprüft.",
    sectorOther: "Geben Sie Ihre Branche an",
    submit: "Anfrage senden",
    submitting: "Wird gesendet…",
    saveError: "Ihre Anfrage konnte nicht gespeichert werden. Bitte versuchen Sie es erneut.",
    pendingTitle: "Anfrage eingegangen",
    pendingDesc: "Ihre Anfrage wird geprüft. Nach der Genehmigung werden Ihr Einladungslink und Ihr Bereich hier aktiviert.",
    cancelApplication: "Anfrage abbrechen",
    rejectedTitle: "Anfrage nicht genehmigt",
    rejectedDesc: "Diese Anfrage wurde nicht genehmigt. Sie können Ihre Angaben aktualisieren und sich erneut bewerben.",
    reapply: "Erneut bewerben",
    approvedTitle: "Ihr Partnerkonto ist aktiv",
    approvedDesc: "Kunden, die sich über Ihren untenstehenden Einladungslink registrieren, werden dauerhaft mit Ihrem Konto verknüpft.",
    panelSoon: "Ein detaillierter Bereich mit Ihren Kunden, Bestellungen und Ihrem Guthaben folgt hier in Kürze.",
    verifyTitle: "E-Mail-Bestätigung",
    verifyDesc: "Bestätigen Sie Ihre E-Mail-Adresse, damit Sie Zahlungen erhalten können. Wir senden Ihnen einen Bestätigungscode.",
    verifiedLabel: "E-Mail bestätigt",
    sendCode: "Bestätigungscode senden",
    sending: "Wird gesendet…",
    codeSent: "Wir haben den Code an Ihre E-Mail-Adresse gesendet. Bitte prüfen Sie Ihren Posteingang und den Spam-Ordner.",
    codePlaceholder: "6-stelliger Code",
    verifyBtn: "Bestätigen",
    verifying: "Wird bestätigt…",
    verifyError: "Der Code ist ungültig oder abgelaufen. Fordern Sie einen neuen an.",
    refTitle: "Ihr Einladungslink",
    refDesc: "Teilen Sie diesen Link; Kunden, die darüber kommen und sich registrieren, werden dauerhaft mit Ihnen verknüpft.",
    refCopy: "Link kopieren",
    refCopied: "Kopiert",
  },
  adminHub: {
    "tabChats": "Konversationen",
    "tabCustomers": "Kunden",
    "tabUploads": "Hochgeladene Dateien",
    "loading": "Wird geladen…",
    "loadError": "Laden fehlgeschlagen. Bitte versuchen Sie es erneut.",
    "back": "Zurück",
    "custHint": "Alle im System registrierten Kunden (Übersetzer ausgenommen).",
    "custSearch": "Name, E-Mail oder Telefon suchen…",
    "custName": "Vollständiger Name",
    "custEmail": "E-Mail",
    "custPhone": "Telefon",
    "custOrders": "Bestellungen",
    "custTotal": "Gesamtbetrag",
    "custJoined": "Beigetreten",
    "custNone": "Noch keine Kundendatensätze vorhanden.",
    "custOrderList": "Bestellungen",
    "custNoOrders": "Dieser Kunde hat keine Bestellungen.",
    "orderNo": "Bestellnr.",
    "orderDate": "Datum",
    "orderStatus": "Status",
    "upHint": "Alle auf der Angebotsseite hochgeladenen Dateien (auch ohne Bestellung gespeichert).",
    "upFile": "Datei",
    "upUploader": "Hochgeladen von",
    "upWhen": "Datum",
    "upWords": "Wörter",
    "upSize": "Größe",
    "upDownload": "Herunterladen",
    "upNone": "Noch keine hochgeladenen Dateien vorhanden.",
    "upGuest": "Gast"
  },

  smsVerify: {
    "sendCode": "Code senden",
    "resend": "Code erneut senden",
    "codeLabel": "SMS-Code",
    "confirm": "Bestätigen",
    "verified": "Telefon verifiziert",
    "sent": "Ein Code wurde an Ihr Telefon gesendet.",
    "mustVerify": "Um fortzufahren, verifizieren Sie bitte Ihre Telefonnummer per SMS.",
    "reverifyHint": "Wenn Sie Ihre Telefonnummer ändern, müssen Sie die neue Nummer erneut per SMS verifizieren.",
    "invalid": "Falscher Code. Bitte versuchen Sie es erneut.",
    "expired": "Der Code ist abgelaufen. Bitte fordern Sie einen neuen an.",
    "rateLimited": "Zu viele Versuche. Bitte warten Sie einen Moment und versuchen Sie es erneut.",
    "notConfigured": "Die SMS-Verifizierung ist derzeit nicht verfügbar. Bitte versuchen Sie es später erneut oder wenden Sie sich an den Support.",
    "sendFailed": "Der Code konnte nicht gesendet werden. Überprüfen Sie Ihre Nummer und versuchen Sie es erneut.",
    "enterPhone": "Bitte geben Sie zunächst eine gültige Telefonnummer ein.",
    "error": "Es ist ein Fehler aufgetreten. Bitte versuchen Sie es erneut.",
    "devCode": "Testmodus — Ihr Verifizierungscode: {code}"
  },
  common: {
      "brand": "TercümExpert",
    tagline: 'Ihr zuverlässiger Partner für professionelle Übersetzungsdienstleistungen.',
    nav: {
      home: 'Startseite',
      services: 'Leistungen',
      quote: 'Angebot einholen',
      corporate: 'Unternehmen',
      partnership: 'Partnerschaft',
      blog: 'Blog',
      faq: 'FAQ',
      contact: 'Kontakt',
    },
    actions: {
      getQuote: 'Angebot einholen',
      calculatePrice: 'Preis berechnen',
      uploadDocument: 'Dokument hochladen',
      whatsapp: 'Über WhatsApp schreiben',
      learnMore: 'Mehr erfahren',
      viewAll: 'Alle anzeigen',
      showMore: 'Mehr anzeigen',
      showLess: 'Weniger anzeigen',
      send: 'Senden',
      apply: 'Bewerben',
      order: 'Bestellung aufgeben',
      contactUs: 'Kontakt',
      openMenu: 'Menü öffnen',
      closeMenu: 'Menü schließen',
      selectLanguage: 'Sprache auswählen',
      skipToContent: 'Zum Inhalt springen',
      login: 'Anmelden',
      logout: 'Abmelden',
      account: 'Mein Konto',
    },
    states: {
      loading: 'Wird geladen…',
      error: 'Etwas ist schiefgelaufen. Bitte versuchen Sie es erneut.',
      required: 'Dieses Feld ist erforderlich.',
      demoNotice: 'Demo: Formulardaten werden noch nicht an einen Server gesendet.',
      unverified: 'Noch zu bestätigen',
    },
    topbar: {
      phoneLabel: 'Telefon',
      emailLabel: 'E-Mail',
      hoursLabel: 'Öffnungszeiten',
      afterHours: 'Auch außerhalb der Geschäftszeiten ist ein Eil-Übersetzungsservice verfügbar.',
      workingHours: 'Wochentags 09:00 - 18:00 Uhr | Service außerhalb der Geschäftszeiten verfügbar',
    },
  },

  home: {
    seo: {
      title: 'TercümExpert — Professionelle Übersetzungsdienstleistungen',
      description:
        'Beglaubigte Übersetzung, notarielle Beglaubigung und Übersetzungslösungen für Unternehmen. Laden Sie Ihr Dokument hoch, erhalten Sie sofort ein unverbindliches Angebot und eine professionelle Lieferung.',
    },
    hero: {
      title: 'Ihr zuverlässiger Partner für professionelle',
      titleAccent: 'Übersetzungsdienstleistungen',
      subtitle: 'Laden Sie Ihr Dokument hoch, sehen Sie den Preis und erhalten Sie eine professionelle Lieferung.',
      support: 'Beglaubigte Übersetzung • Notarielle Beglaubigung • Lösungen für Unternehmen',
    },
    trust: {
      title: 'Warum vertraut man uns?',
      items: [
        { key: 'languages', label: 'Über 50 Sprachen' },
        { key: 'delivery', label: 'Lieferung in 24 Stunden' },
        { key: 'notary', label: 'Notarielle Beglaubigung' },
        { key: 'quality', label: 'Qualitätssicherung' },
      ],
    },
    stats: {
      title: 'TercümExpert in Zahlen',
      note: 'Die folgenden Zahlen werden bis zu ihrer Bestätigung nicht als endgültige Angaben dargestellt.',
      labels: {
        satisfaction: 'Kundenzufriedenheit',
        completed: 'Abgeschlossene Aufträge',
        languages: 'Sprachunterstützung',
        corporate: 'Firmenkunden',
      },
    },
    howItWorks: {
      title: 'Wie funktioniert es?',
      subtitle: 'Professionelle Übersetzung in fünf Schritten.',
      steps: [
        { key: 'upload', title: 'Hochladen', desc: 'Laden Sie Ihr Dokument sicher hoch.' },
        { key: 'select', title: 'Auswählen', desc: 'Wählen Sie Sprache und Serviceart.' },
        { key: 'confirm', title: 'Bestätigen', desc: 'Bestätigen Sie Ihre Bestellung.' },
        { key: 'track', title: 'Verfolgen', desc: 'Verfolgen Sie den Prozess in Echtzeit.' },
        { key: 'receive', title: 'Erhalten', desc: 'Erhalten Sie Ihre professionelle Lieferung.' },
      ],
    },
    services: {
      title: 'Unsere Leistungen',
      subtitle: 'Fachgerechte Übersetzung für jeden Dokumententyp.',
    },
    why: {
      title: 'Warum TercümExpert?',
      subtitle: 'Die Merkmale, die uns vom Wettbewerb abheben',
      features: [
        { key: 'autoQuote', title: 'Automatische Preisberechnung', desc: 'Ein Richtpreis in Sekunden.' },
        { key: 'whatsapp', title: 'Schnelles WhatsApp-Angebot', desc: 'Kontakt mit einem Fingertipp.' },
        { key: 'terminology', title: 'Terminologiemanagement', desc: 'Einheitliche, unternehmensgerechte Sprache.' },
        { key: 'revision', title: 'Korrekturrecht', desc: 'Ein auf Zufriedenheit ausgerichteter Prozess.' },
        { key: 'languages', title: 'Unterstützung von über 50 Sprachen', desc: 'Breite Abdeckung an Sprachpaaren.' },
        { key: 'terms', title: 'Firmenkonto-System', desc: 'Flexible Zahlung für Unternehmen.' },
      ],
    },
    corporateCta: {
      title: 'Lösungen für Unternehmen',
      desc: 'Professionelle Sprachdienstleistungen mit Terminologiemanagement, Zahlungszieloptionen und einem persönlichen Kundenbetreuer, individuell auf Ihr Unternehmen zugeschnitten.',
      action: 'Firmenangebot anfordern',
    },
    partnershipTeaser: {
      title: 'Partnerprogramm',
      subtitle: 'Verdienen Sie 20 % Provision für jeden Kunden, den Sie an uns vermitteln.',
      items: [
        { key: 'commission', title: 'Transparente Provision', desc: '20 % Provision für jede Vermittlung (nach Vereinbarung). Transparente Einnahmen mit einem Echtzeit-Tracking-Panel.' },
        { key: 'qr', title: 'QR-Code-System', desc: 'Einfache Kundenverfolgung mit Visitenkartenintegration. Web- und WhatsApp-QR-Codes.' },
      ],
      cta: 'Als Partner bewerben',
    },
    testimonials: {
      title: 'Kundenbewertungen',
      subtitle: 'Echte Kundenbewertungen werden hier vor dem Start ergänzt.',
      placeholderNote: 'Platzhalter — echte Bewertungen werden integriert.',
      items: [
        { key: 't1', role: 'Anwaltskanzlei' },
        { key: 't2', role: 'Gesundheitseinrichtung' },
        { key: 't3', role: 'Firmenkunde' },
        { key: 't4', role: 'Privatkunde' },
      ],
    },
    blogTeaser: {
      title: 'Blog',
      subtitle: 'Aktuelle Inhalte aus der Welt der Übersetzung',
      viewAll: 'Alle Blogbeiträge anzeigen',
    },
    finalCta: {
      title: 'Jetzt loslegen',
      desc: 'Laden Sie Ihre Dokumente hoch, erhalten Sie sofort ein Angebot und profitieren Sie von professionellen Übersetzungsdienstleistungen.',
      primary: 'Angebot einholen',
      secondary: 'Kontakt',
    },
  },

  services: {
    seo: {
      title: 'Übersetzungsdienstleistungen',
      description:
        'Beglaubigte, notariell beglaubigte, juristische, technische, medizinische und akademische Übersetzung sowie Web-/Mobile-Lokalisierung. Dokumententypen, Ablauf, Lieferung und Sprachpaare.',
    },
    hero: {
      title: 'Übersetzungsdienstleistungen',
      subtitle: 'Übersetzung mit der richtigen Terminologie für jedes Fachgebiet.',
    },
    process: {
      title: 'Wie läuft der Prozess ab?',
      steps: [
        { title: 'Dokumentenprüfung', desc: 'Dokumententyp und Verwendungszweck werden beurteilt.' },
        { title: 'Fachliche Zuordnung', desc: 'Ein auf das Fachgebiet spezialisierter Übersetzer wird zugewiesen.' },
        { title: 'Übersetzung & Lektorat', desc: 'Übersetzung und eine unabhängige Endkontrolle.' },
        { title: 'Beglaubigung & Lieferung', desc: 'Bei Bedarf notarielle Beglaubigung/Apostille, anschließend Lieferung.' },
      ],
    },
    delivery: {
      title: 'Lieferoptionen',
      items: ['Digitale Lieferung (PDF/DOCX)', 'Lieferung physischer Dokumente', 'Eillieferung'],
    },
    notaryApostille: {
      title: 'Zusammenhang zwischen notarieller Beglaubigung und Apostille',
      desc: 'Bei Bedarf wird eine beglaubigte Übersetzung durch notarielle Beglaubigung und das Apostille-Verfahren für offizielle Institutionen gültig gemacht. Die genaue Anforderung hängt von der Institution ab, bei der das Dokument eingereicht wird.',
    },
    fullService: {
      title: 'Schlüsselfertig, bis zu Ihrer Haustür geliefert',
      note: 'Senden Sie uns Ihre Dokumente und wir übernehmen den gesamten Prozess — Übersetzung, notarielle Beglaubigung und Apostille inklusive. Ihre fertigen Dokumente kommen per Kurier bis an Ihre Haustür. Konzentrieren Sie sich auf Ihre Arbeit und überlassen Sie den Rest uns.',
    },
    cta: {
      title: 'Nicht sicher, welche Leistung Sie benötigen?',
      desc: 'Laden Sie Ihr Dokument hoch und wir zeigen Ihnen die passendste Leistung und den passenden Preis.',
    },
    documentTypesTitle: 'Geeignete Dokumententypen',
  },

  serviceItems: {
    sworn: {
      name: 'Beglaubigte Übersetzung',
      short: 'Offiziell gültige Übersetzung mit Unterschrift und Stempel eines vereidigten Übersetzers.',
      benefits: ['Gültig bei offiziellen Institutionen', 'Bestätigung durch vereidigten Übersetzer', 'Schneller Ablauf'],
    },
    notarized: {
      name: 'Notariell beglaubigte Übersetzung',
      short: 'Notarielle Beglaubigung einer beglaubigten Übersetzung.',
      benefits: ['Notarielle Beurkundung', 'Geeignet für offizielle Anträge', 'Wir übernehmen den Prozess'],
    },
    apostille: {
      name: 'Unterstützung beim Apostille-Verfahren',
      short: 'Begleitung durch das Apostille-Verfahren für die Gültigkeit im Ausland.',
      benefits: ['Internationale Gültigkeit', 'Verfahrensberatung', 'Behördenführung'],
    },
    legal: {
      name: 'Juristische Übersetzung',
      short: 'Übersetzung mit sicherer Beherrschung der Terminologie für Verträge, Gerichts- und amtliche Dokumente.',
      benefits: ['Juristische Terminologie', 'Vertraulichkeitsgarantie', 'Fachübersetzer'],
    },
    technical: {
      name: 'Technische Übersetzung',
      short: 'Einheitliche Übersetzung für Handbücher, Spezifikationen und technische Dokumente.',
      benefits: ['Terminologiemanagement', 'Format bleibt erhalten', 'Branchenexpertise'],
    },
    medical: {
      name: 'Medizinische Übersetzung',
      short: 'Präzise Übersetzung für Befunde, Beipackzettel und medizinische Dokumente.',
      benefits: ['Medizinische Terminologie', 'Genauigkeitsorientiert', 'Vertraulichkeit'],
    },
    academic: {
      name: 'Akademische Übersetzung',
      short: 'Akademische Sprache für Abschlussarbeiten, Artikel und Diplomübersetzungen.',
      benefits: ['Akademischer Stil', 'Quellenkonsistenz', 'Termingerechte Lieferung'],
    },
    localization: {
      name: 'Web- und Mobile-Lokalisierung',
      short: 'Kulturell angemessene Lokalisierung von Websites und Anwendungen.',
      benefits: ['Kulturelle Anpassung', 'Technische Integration', 'SEO-Kompatibilität'],
    },
  },

  corporate: {
    statsLabels: {
      corporate: 'Firmenkunden',
      discount: 'Rabatt bei Sammelaufträgen',
      term: 'Zahlungsziel',
    },
    seo: {
      title: 'Lösungen für Unternehmen',
      description:
        'Professionelle Sprachdienstleistungen für Unternehmen mit Terminologiemanagement, Zahlungszieloptionen, Sammelaufträgen und einem persönlichen Kundenbetreuer.',
    },
    hero: {
      title: 'Lösungen für Unternehmen',
      subtitle:
        'Professionelle Sprachdienstleistungen mit Terminologiemanagement, Zahlungszieloptionen und einem persönlichen Kundenbetreuer, individuell auf Ihr Unternehmen zugeschnitten.',
      primaryCta: 'Firmenangebot anfordern',
      secondaryCta: 'E-Mail senden',
    },
    features: {
      title: 'Funktionen für Unternehmen',
      subtitle: 'Auf Ihr Unternehmen zugeschnittene Lösungen',
      items: [
        {
          key: 'custom',
          icon: 'Target',
          title: 'Maßgeschneiderter Service',
          points: ['Feste Terminologie', 'Wahrung der Markentonalität', 'Persönlicher Kundenbetreuer', 'Erstellung eines Style Guides'],
        },
        {
          key: 'volume',
          icon: 'BarChart3',
          title: 'Sammelabwicklung und Zahlungsziele',
          points: ['Monatliche Übersetzungspläne', 'Rabatte bei Sammelaufträgen', 'Zahlungsziele bis zu 30 Tagen', 'Rechnungssystem'],
        },
        {
          key: 'security',
          icon: 'Lock',
          title: 'Datenschutz und Sicherheit',
          points: ['NDA-Protokoll', 'Verschlüsselte Dateiübertragung', 'KVKK-konforme Prozesse'],
        },
      ],
    },
    whyPackage: {
      title: 'Warum ein Firmenpaket?',
      items: [
        {
          key: 'terminology',
          icon: 'Building2',
          title: 'Festes Terminologiemanagement',
          desc: 'Wir bauen eine unternehmensspezifische Terminologiedatenbank auf. Ihre Markensprache bleibt über alle Übersetzungen hinweg erhalten und wir sorgen für Konsistenz. Wir achten darauf, in jedem Projekt dieselben Begriffe zu verwenden.',
        },
        {
          key: 'manager',
          icon: 'Users',
          title: 'Persönlicher Kundenbetreuer',
          desc: 'Ihr persönlicher Kundenbetreuer verfolgt alle Ihre Prozesse. Mit einer gut erreichbaren Support-Line stehen wir Ihnen in dringenden Situationen zur Seite.',
        },
        {
          key: 'security',
          icon: 'ShieldCheck',
          title: 'Datenschutz und Sicherheit',
          desc: 'Wir arbeiten unter einem NDA-Protokoll. Ihre Daten sind mit einer starken Sicherheitsinfrastruktur, verschlüsselter Dateiübertragung und KVKK-konformen Prozessen sicher.',
        },
      ],
    },
    payment: {
      title: 'Zahlungsoptionen',
      subtitle: 'Flexible Zahlungspläne, passend zu Ihrem Unternehmen',
      recommendedLabel: 'EMPFOHLEN',
      options: [
        {
          key: 'standard',
          label: 'Sofortzahlung',
          heading: 'Standard',
          desc: 'Zahlung per Kreditkarte oder Banküberweisung nach jeder Bestellung',
          points: ['Kreditkartenraten', 'Sofortige Lieferung'],
          recommended: false,
        },
        {
          key: 'term',
          label: 'Monatliches Zahlungsziel',
          heading: '15-30 Tage',
          desc: 'Monatlich zusammengefasste Rechnungsstellung und Zahlungszieloption',
          points: ['30 Tage Zahlungsziel', 'Mengenrabatt', 'Monatsbericht'],
          recommended: true,
        },
      ],
    },
    form: {
      title: 'Antrag auf ein Firmenpaket',
      desc: 'Füllen Sie das Formular aus und unser Expertenteam wird sich mit Ihnen in Verbindung setzen',
      fields: {
        company: 'Firmenname',
        contactName: 'Vollständiger Name der Kontaktperson',
        email: 'E-Mail',
        phone: 'Telefon',
        need: 'Beschreiben Sie uns Ihren Übersetzungsbedarf',
        consent: 'Ich habe die <kvkk>KVKK-Datenschutzerklärung</kvkk> gelesen und stimme ihr zu.',
      },
      submit: 'Antrag absenden',
      success: 'Ihr Antrag ist bei uns eingegangen. Wir melden uns schnellstmöglich bei Ihnen.',
      note: 'Wir melden uns innerhalb von 1 Werktag bei Ihnen.',
    },
  },

  partnership: {
    seo: {
      title: 'Partnerprogramm',
      description:
        'Verdienen Sie Provision für jeden Kunden, den Sie vermitteln. Transparente Berichterstattung, QR-Code-Vermittlungen und professioneller Support.',
    },
    hero: {
      title: 'Partnerprogramm',
      value: 'Verdienen Sie 20 % Provision für jeden Kunden, den Sie an uns vermitteln.',
      subtitle: 'Ein transparentes System, zuverlässige Zahlungen, langfristige Zusammenarbeit.',
      cta: 'Jetzt bewerben',
    },
    advantages: {
      title: 'Partnervorteile',
      subtitle: 'Warum TercümExpert-Partner werden?',
      items: [
        { key: 'commission', icon: 'Wallet', title: '20 % Provisionsgarantie', desc: 'Ein transparentes Provisionssystem für jeden Kunden, den Sie vermitteln.' },
        { key: 'qr', icon: 'QrCode', title: 'QR-Code-Vermittlung', desc: 'Einfache Kundenverfolgung mit Visitenkartenintegration.' },
        { key: 'reporting', icon: 'BarChart3', title: 'Transparente Berichterstattung', desc: 'Echtzeit-Panel zur Provisions- und Kundenverfolgung.' },
        { key: 'support', icon: 'Users', title: 'Professioneller Support', desc: 'Eine eigene Partner-Support-Line und ein Kundenbetreuer.' },
      ],
    },
    howItWorks: {
      title: 'Wie funktioniert es?',
      steps: [
        { title: 'Bewerben', desc: 'Füllen Sie das Online-Bewerbungsformular aus. Teilen Sie Ihre Firmen- und Kontaktdaten mit. Ihre Bewerbung wird innerhalb von 1 Werktag geprüft.' },
        { title: 'Partner werden', desc: 'Sobald Ihre Bewerbung genehmigt ist, erhalten Sie Zugang zu Ihrem persönlichen Partner-Panel. Ihre QR-Codes und Vermittlungslinks sind bereit.' },
        { title: 'Kunden vermitteln', desc: 'Vermitteln Sie Ihre Kunden per QR-Code, individuellem Link oder Visitenkarte an uns. Jede Vermittlung wird automatisch im System erfasst.' },
        { title: 'Provision verdienen', desc: 'Sie verdienen 20 % Provision, jedes Mal wenn ein von Ihnen vermittelter Kunde eine Bestellung aufgibt. Sie erhalten alle 15 Tage automatische Zahlungen.' },
      ],
    },
    sectors: {
      title: 'Zielbranchen',
      subtitle: 'Für welche Branchen ist es ideal?',
      items: [
        { key: 'law', icon: 'Scale', title: 'Anwaltskanzleien', desc: 'Bedarf an beglaubigter Übersetzung von Akten, Verträgen und juristischen Dokumenten.' },
        { key: 'visa', icon: 'Plane', title: 'Visa-Beratung', desc: 'Dokumente, die eine beglaubigte Übersetzung erfordern, wie Reisepässe, Diplome und Personenstandsurkunden.' },
        { key: 'education', icon: 'GraduationCap', title: 'Bildungsberatung', desc: 'Beglaubigte Übersetzung von Studierendendokumenten und Apostille-Verfahren.' },
        { key: 'health', icon: 'HeartPulse', title: 'Gesundheitstourismus', desc: 'Übersetzung von medizinischen Befunden, Patientenakten und Gesundheitsdokumenten.' },
        { key: 'patent', icon: 'Building2', title: 'Patent-/Markenämter', desc: 'Technische Übersetzung von Patent-, Markenanmeldungs- und Rechtsdokumenten.' },
        { key: 'realestate', icon: 'Home', title: 'Immobilienbüros', desc: 'Übersetzung von Grundbuchauszügen, Verträgen und amtlichen Dokumenten für ausländische Investoren.' },
        { key: 'hr', icon: 'Briefcase', title: 'Personalberatung', desc: 'Übersetzung von Lebensläufen, Diplomen und Empfehlungsschreiben für die Vermittlung ins Ausland.' },
        { key: 'software', icon: 'Code', title: 'Softwareunternehmen', desc: 'Lokalisierung von Web- und Mobile-Apps, Übersetzung technischer Dokumente.' },
      ],
    },
    commission: {
      title: 'Provisionsstruktur',
      stats: {
        commissionLabel: 'Standardprovision',
        commissionSub: 'Bei jeder Bestellung',
        periodUnit: 'Tage',
        periodLabel: 'Zahlungszeitraum',
        feeLabel: 'Startgebühr',
        feeSub: 'Völlig kostenlos',
      },
      exampleTitle: 'Beispielhafte Verdienstberechnung',
      exampleOrderLabel: 'Bestellung des von Ihnen vermittelten Kunden',
      exampleRateLabel: 'Provisionssatz',
      exampleEarningLabel: 'Ihr Verdienst',
      note: 'Provisionssätze und -bedingungen unterliegen der Partnervereinbarung.',
    },
    form: {
      title: 'Partner-Bewerbungsformular',
      subtitle: 'Füllen Sie das Formular aus und wir melden uns innerhalb von 1 Werktag bei Ihnen.',
      fields: {
        company: 'Name des Unternehmens/der Organisation',
        sector: 'Branche',
        contactName: 'Vollständiger Name der Kontaktperson',
        titleRole: 'Position',
        email: 'E-Mail',
        phone: 'Telefon',
        potential: 'Ihr geschätztes monatliches Vermittlungspotenzial',
        note: 'Anmerkungen, die Sie hinzufügen möchten',
        agreement: 'Ich habe die Bedingungen der <partnership>Partnervereinbarung</partnership> gelesen und akzeptiere sie.',
      },
      sectorPlaceholder: 'Auswählen',
      sectorOptions: ['Anwaltskanzlei', 'Visa-Beratung', 'Bildungsberatung', 'Gesundheitstourismus', 'Patent-/Markenamt', 'Immobilien', 'Personalberatung', 'Software', 'Sonstige'],
      potentialOptions: ['1-5 Kunden', '5-10 Kunden', '10-20 Kunden', 'Über 20 Kunden'],
      submit: 'Antrag absenden',
      success: 'Ihre Bewerbung ist bei uns eingegangen. Wir werden Sie kontaktieren.',
      note: 'Ihre Bewerbung wird innerhalb von 1 Werktag geprüft.',
    },
  },

  quote: {
    "areas": {
      "academic": "Wissenschaftliche Übersetzung",
      "legal": "Juristische Übersetzung",
      "official": "Übersetzung amtlicher Dokumente",
      "medical": "Medizinische Übersetzung",
      "technical": "Technische Übersetzung",
      "commercial": "Wirtschafts- und Finanzübersetzung",
      "localization": "Web- und App-Lokalisierung",
      "literary": "Literarische Übersetzung",
      "general": "Allgemeine / sonstige Übersetzung"
    },
    "docTypes": {
      "diploma": "Diplom",
      "transcript": "Notenübersicht",
      "student-certificate": "Immatrikulationsbescheinigung",
      "diploma-supplement": "Diploma Supplement",
      "thesis": "Abschlussarbeit",
      "reference-letter": "Empfehlungsschreiben",
      "academic-article": "Wissenschaftlicher Artikel",
      "contract": "Vertrag",
      "court-decision": "Gerichtsurteil",
      "power-of-attorney": "Vollmacht",
      "petition": "Antragsschrift",
      "consent-statement": "Einverständniserklärung",
      "warning-notice": "Abmahnung",
      "litigation-doc": "Prozessunterlagen",
      "passport": "Reisepass",
      "id-card": "Personalausweis",
      "civil-registry": "Auszug aus dem Personenstandsregister",
      "birth-certificate": "Geburtsurkunde",
      "marriage-certificate": "Heiratsurkunde",
      "driver-license": "Führerschein",
      "criminal-record": "Führungszeugnis",
      "military-status": "Wehrdienstbescheinigung",
      "medical-report": "Ärztlicher Befund",
      "epicrisis": "Entlassungsbericht (Epikrise)",
      "prescription": "Rezept",
      "lab-result": "Labor- / Untersuchungsbefund",
      "medical-article": "Medizinischer Fachartikel",
      "patient-consent": "Patienteneinwilligungserklärung",
      "user-manual": "Bedienungsanleitung",
      "technical-spec": "Technische Spezifikation",
      "patent": "Patent",
      "product-catalog": "Produktkatalog",
      "datasheet": "Datenblatt",
      "installation-guide": "Installationsanleitung",
      "safety-data-sheet": "Sicherheitsdatenblatt",
      "invoice": "Rechnung",
      "balance-sheet": "Bilanz",
      "commercial-contract": "Handelsvertrag",
      "financial-report": "Finanzbericht",
      "tax-document": "Steuerdokument",
      "activity-certificate": "Gewerbebescheinigung",
      "bank-statement": "Kontoauszug",
      "website": "Website",
      "mobile-app": "Mobile App",
      "software-ui": "Software-Benutzeroberfläche",
      "game": "Spiel",
      "marketing-content": "Marketinginhalte",
      "subtitle": "Untertitel",
      "e-commerce": "E-Commerce-Inhalte",
      "book": "Buch",
      "short-story": "Kurzgeschichte",
      "poem": "Gedicht",
      "screenplay": "Drehbuch",
      "essay": "Essay",
      "article": "Artikel",
      "general-document": "Allgemeines Dokument",
      "correspondence": "Schriftverkehr / Brief",
      "cv": "Lebenslauf",
      "presentation": "Präsentation",
      "other": "Sonstiges"
    },
    seo: {
      title: 'Sofortige Preisberechnung',
      description: 'Laden Sie Ihr Dokument hoch oder geben Sie die Details ein und erhalten Sie sofort Ihr unverbindliches Angebot.',
    },
    hero: {
      title: 'Sofortige Preisberechnung',
      subtitle: 'Laden Sie Ihr Dokument hoch oder geben Sie die Details ein und erhalten Sie sofort ein unverbindliches Angebot.',
    },
    upload: {
      heading: 'Laden Sie Ihre Dokumente hoch',
      privacy: 'Ihre Daten werden vertraulich behandelt',
      tabFile: 'Datei hochladen',
      tabText: 'Text eingeben',
      chooseFile: 'Wählen Sie Ihre Dokumente',
      formats: '.docx, .xlsx, .pdf, .pptx, .jpg, .png und über 50 Formate werden akzeptiert · Max. 100 MB pro Datei',
      dropHint: 'Sie können eine oder mehrere Dateien in diesen Bereich ziehen und ablegen.',
      textPlaceholder: 'Fügen Sie Ihren Text hier ein oder tippen Sie ihn…',
      totalWords: 'Gesamtwortzahl',
      extracting: 'Wörter werden gezählt…',
      wordsUnit: 'Wörter',
      remove: 'Entfernen',
      unsupported:
        'Für diesen Dateityp war eine automatische Wortzählung nicht möglich. Bitte fügen Sie den Text über „Text eingeben“ ein; die Zählung wird bei der Angebotserstellung von unserem Team überprüft.',
      empty:
        'In der Datei wurde kein auswählbarer Text gefunden (möglicherweise ein Scan/Bild). Bitte verwenden Sie „Text eingeben“, andernfalls wird die Zählung bei der Angebotserstellung überprüft.',
      error: 'Die Datei konnte nicht gelesen werden. Bitte versuchen Sie es erneut oder verwenden Sie „Text eingeben“.',
      tooLarge: 'Die Datei darf nicht größer als 100 MB sein.',
      needInput: 'Für einen Preis laden Sie bitte eine Datei hoch oder geben Sie Text ein.',
    },
    fields: {
      upload: 'Dokument hochladen (optional)',
      uploadHint: 'PDF, DOC, DOCX oder TXT — max. 10 MB',
      sourceLang: 'Ausgangssprache',
      targetLang: 'Zielsprache',
      serviceType: 'Serviceart',
      documentType: 'Dokumententyp',
      wordCount: 'Geschätzte Wortzahl',
      wordCountHint: 'Verwenden Sie den Schieberegler oder geben Sie die Zahl manuell ein.',
      options: 'Zusätzliche Optionen',
      calculate: 'Preis berechnen',
    },
    options: {
      "sworn": "Beeidigte (beglaubigte) Übersetzung",
      "apostille": "Unterstützung beim Apostille-Verfahren",
      "swornNotaryHint": "Die notarielle Beglaubigung umfasst bereits die beeidigte Übersetzung; Sie müssen nur die eine Option auswählen, die Ihrem Bedarf entspricht.",
      "physicalRequiredHint": "Beeidigte und notariell beglaubigte Übersetzungen werden als unterschriebene/gestempelte Originale geliefert, daher wird der Postversand automatisch hinzugefügt.",
      urgent: 'Eillieferung',
      notarization: 'Notarielle Beglaubigung',
      physicalDelivery: 'Physische Lieferung',
    },
    languages: {
      tr: 'Türkisch',
      en: 'Englisch',
      de: 'Deutsch',
      fr: 'Französisch',
      es: 'Spanisch',
      it: 'Italienisch',
      ru: 'Russisch',
      ar: 'Arabisch',
      nl: 'Niederländisch',
      az: 'Aserbaidschanisch',
      pl: 'Polnisch',
      bg: 'Bulgarisch',
      pt: 'Portugiesisch',
      da: 'Dänisch',
    },
    documentTypes: {
      diploma: 'Diplom',
      passport: 'Reisepass',
      'civil-registry': 'Personenstandsauszug',
      contract: 'Vertrag',
      'medical-report': 'Ärztlicher Befund',
      'technical-doc': 'Technisches Dokument',
      'court-doc': 'Gerichtsdokument',
      other: 'Sonstiges',
    },
    result: {
      title: 'Unverbindliches Angebot',
      basePrice: 'Grundservicegebühr',
      wordPrice: 'Wortgebühr',
      addons: 'Zusatzleistungen',
      total: 'Gesamt',
      vat: 'MwSt.',
      delivery: 'Voraussichtliche Lieferzeit',
      deliveryUnit: 'Werktage',
      disclaimer: 'Dies ist ein unverbindliches Angebot; der Endpreis wird nach der Dokumentenprüfung bestätigt.',
      order: 'Bestellung aufgeben',
      whatsapp: 'Kontakt über WhatsApp',
      estimatedWords: 'Geschätzte Wörter (automatisch — Demo)',
    },
    orderConfirm: {
      title: 'Ihre Bestellung ist eingegangen',
      number: 'Bestellnr.',
      desc: 'Ihre Anfrage und Dokumente wurden gespeichert. Unser Expertenteam prüft das Dokument und setzt sich schnellstmöglich mit Ihnen in Verbindung.',
      viewOrders: 'Meine Bestellungen',
      submitting: 'Bestellung wird erstellt…',
      error: 'Beim Erstellen Ihrer Bestellung ist ein Problem aufgetreten. Bitte versuchen Sie es erneut.',
    },
    gate: {
      title: 'Ihr Preis ist bereit',
      subtitle: 'Melden Sie sich an oder bestätigen Sie Ihre Daten, um den Preis zu sehen und eine Bestellung aufzugeben.',
      loginCta: 'Anmelden / Registrieren',
      or: 'oder schnell fortfahren',
      firstName: 'Vorname',
      lastName: 'Nachname',
      email: 'E-Mail',
      phone: "Telefonnummer",
      sendCode: 'Bestätigungscode senden',
      codeLabel: 'Bestätigungscode',
      codeSentA: 'wurde ein Bestätigungscode gesendet.',
      verify: 'Bestätigen und Preis ansehen',
      resend: 'Code erneut senden',
      resent: 'Ein neuer Code wurde gesendet.',
      back: 'Daten ändern',
      errNames: 'Vor- und Nachname sind erforderlich.',
      errEmail: 'Geben Sie eine gültige E-Mail-Adresse ein.',
      errPhone: "Bitte geben Sie eine gültige Telefonnummer ein.",
      errCode: 'Bitte geben Sie den Code vollständig ein.',
      note: 'Ihre E-Mail-Adresse wird nur für das Angebot und die Bestellung verwendet.',
    },
    note: {
      label: 'Anmerkung zu Ihrer Bestellung (optional)',
      placeholder: 'Hier können Sie Ihre Wünsche zu Lieferung, Terminologie oder besondere Anliegen notieren.',
    },

    checkout: {
      "selectCountry": "Land auswählen",
      "selectCity": "Stadt / Bundesland auswählen",
      "cityNeedsCountry": "Bitte zuerst ein Land auswählen",
      title: "Lieferdetails",
      subtitle: "Ihr physisches/beglaubigtes Dokument wird an diese Adresse versendet.",
      firstName: "Vorname",
      lastName: "Nachname",
      phone: "Telefon",
      address: "Vollständige Adresse",
      addressPlaceholder: "Straße, Haus- und Wohnungsnummer…",
      city: "Stadt",
      postalCode: "Postleitzahl",
      country: "Land",
      submit: "Bestellung abschließen",
      submitting: "Bestellung wird erstellt…",
      cancel: "Abbrechen",
      errRequired: "Bitte füllen Sie die Pflichtfelder aus.",
      note: "Diese Angaben werden nur für den Kurierversand verwendet.",
    },
  },

  order: {
      "trackingCodeLabel": "Sendungsnummer",
    seo: {
      title: 'Bestellverfolgung',
      description: 'Verfolgen Sie den Status Ihrer Bestellung.',
    },
    numberLabel: 'Bestellnr.',
    placedOn: 'Bestelldatum',
    estimatedLabel: 'Voraussichtliche Lieferung der Übersetzung',
    cargoEstimatedLabel: 'Voraussichtliches Versanddatum',
    timelineTitle: 'Bestellstatus',
    steps: {
      received: 'Ihre Bestellung ist eingegangen',
      in_progress: 'In Bearbeitung',
      translated: 'Übersetzung abgeschlossen',
      shipped: 'Versendet',
      delivered: 'Zugestellt',
      cancelled: 'Bestellung storniert',
    },
    stepDesc: {
      received: 'Ihre Anfrage und Dokumente haben unser System erreicht. Unser Expertenteam prüft sie und beginnt in Kürze.',
      in_progress: 'Unser Fachübersetzer hat mit Ihrer Übersetzung begonnen.',
      translated: 'Ihre Übersetzung ist fertig und die abschließenden Kontrollen wurden durchgeführt.',
      shipped: 'Ihr Dokument wurde dem Kurier übergeben; Sie können es über die Schaltfläche unten verfolgen.',
      delivered: 'Ihr Dokument wurde Ihnen per E-Mail zugesandt.',
      cancelled: 'Diese Bestellung wurde storniert. Bei Fragen kontaktieren Sie uns bitte.',
    },
    cargoReady: 'Ihr Dokument wurde versendet. Verfolgen Sie es mit einem Fingertipp:',
    cargoPending: 'Der Sendungsverfolgungscode erscheint hier, sobald Ihr Dokument versendet wurde.',
    trackCargo: 'Meine Sendung verfolgen',
    digitalPending: 'Sobald Ihre Übersetzung fertig ist, werden Ihre Dateien Ihnen per E-Mail zugesandt.',
    digitalDelivered: 'Ihre Übersetzung wurde Ihnen per E-Mail zugesandt. Überprüfen Sie Ihren Posteingang (und den Spam-Ordner).',
    detailsTitle: 'Bestelldetails',
    fields: {
      service: 'Leistung',
      langs: 'Sprachen',
      documentType: 'Dokumententyp',
      words: 'Wörter',
      delivery: 'Voraussichtliche Zeit',
      total: 'Betrag',
      note: 'Ihre Anmerkung',
      deliveryAddress: "Lieferadresse",
    },
    myOrders: 'Meine Bestellungen',
    backHome: 'Zurück zur Startseite',
    whatsapp: 'Kontakt über WhatsApp',
    loading: 'Bestellung wird geladen…',
    loginRequired: {
      title: 'Melden Sie sich an, um Ihre Bestellung anzuzeigen',
      desc: 'Sie können auf Ihre Bestelldetails erst zugreifen, nachdem Sie sich mit Ihrem Konto angemeldet haben.',
      login: 'Anmelden',
    },

    notFound: {
      title: 'Bestellung nicht gefunden',
      desc: 'Diese Bestellnummer gehört nicht zu Ihnen oder existiert nicht. Bitte überprüfen Sie den Link.',
      home: 'Zurück zur Startseite',
    },
  },

  faq: {
    seo: {
      title: 'Häufig gestellte Fragen',
      description: 'Häufig gestellte Fragen zu beglaubigter Übersetzung, Lieferzeit, Preisgestaltung, notarieller Beglaubigung und Firmenkonditionen.',
    },
    hero: { title: 'Häufig gestellte Fragen', subtitle: 'Die Antwort, die Sie suchen, finden Sie hier.' },
    categoriesTitle: 'Kategorien',
    searchPlaceholder: 'Fragen oder Stichwörter suchen…',
    empty: 'Keine Fragen entsprachen Ihrer Suche. Versuchen Sie ein anderes Wort oder kontaktieren Sie uns.',
    categories: FAQ_CATEGORIES_DE,
    items: FAQ_ITEMS_DE,
    notFound: {
      title: 'Haben Sie die Antwort auf Ihre Frage nicht gefunden?',
      contact: 'Kontakt',
      whatsapp: 'WhatsApp-Support',
    },
  },

  contact: {
      introTitle: `Willkommen`,
      introDesc: `Bevor wir beginnen, dürfte ich Ihren Namen und Ihre E-Mail-Adresse erfahren, damit ich Ihnen besser helfen kann?`,
      start: `Chat starten`,
      introError: `Bitte geben Sie Ihren Namen und Ihre E-Mail-Adresse ein.`,
    seo: {
      title: 'Kontakt',
      description: 'Nehmen Sie Kontakt mit TercümExpert auf: Telefon, E-Mail, WhatsApp und Kontaktformular.',
    },
    hero: { title: 'Kontakt', subtitle: 'Wie können wir Ihnen helfen?' },
    infoTitle: 'Kontaktinformationen',
    labels: {
      phone: 'Telefon',
      email: 'E-Mail',
      whatsapp: 'WhatsApp',
      address: 'Adresse',
      hours: 'Öffnungszeiten',
    },
    form: {
      title: 'Kontakt',
      fields: {
        name: 'Vollständiger Name',
        email: 'E-Mail',
        phone: 'Telefon',
        subject: 'Betreff',
        message: 'Nachricht',
        consent: 'Ich habe die <kvkk>KVKK-Datenschutzerklärung</kvkk> gelesen und stimme ihr zu.',
      },
      submit: 'Nachricht senden',
      success: 'Ihre Nachricht ist bei uns eingegangen. Wir melden uns in Kürze bei Ihnen.',
    },
    map: {
      title: 'Unser Standort',
      subtitle: 'Finden Sie uns auf der Karte',
      placeholder: 'Kartenbereich',
      note: 'Die Standortkarte wird hier in Kürze angezeigt.',
    },
  },

  auth: {
    seo: {
      title: 'Anmelden / Registrieren',
      description: 'Melden Sie sich bei Ihrem TercümExpert-Konto an oder erstellen Sie ein neues.',
    },
    tabs: { login: 'Anmelden', register: 'Registrieren' },
    google: 'Mit Google fortfahren',
    or: 'oder',
    fields: {
      firstName: 'Vorname',
      lastName: 'Nachname',
      email: 'E-Mail',
      password: 'Passwort',
      code: 'Bestätigungscode',
    },
    login: {
      title: 'Melden Sie sich bei Ihrem Konto an',
      submit: 'Anmelden',
      noAccount: 'Sie haben noch kein Konto?',
      switchToRegister: 'Registrieren',
    },
    register: {
      title: 'Neues Konto erstellen',
      submit: 'Registrieren',
      haveAccount: 'Sie haben bereits ein Konto?',
      switchToLogin: 'Anmelden',
      consent: 'Mit der Erstellung eines Kontos akzeptiere ich die <kvkk>KVKK-Datenschutzerklärung</kvkk> und die <privacy>Datenschutzrichtlinie</privacy>.',
    },
    verify: {
      title: 'Bestätigen Sie Ihre E-Mail-Adresse',
      desc: '— geben Sie den 6-stelligen Code ein, den wir an diese Adresse gesendet haben.',
      submit: 'Bestätigen und fortfahren',
      spam: 'Der Code kann sich um einige Minuten verzögern; prüfen Sie auch Ihren Spam-/Junk-Ordner.',
      resend: 'Code erneut senden',
      resent: 'Ein neuer Code wurde gesendet.',
      back: 'Zurück',
    },
    signedIn: {
      title: 'Mein Konto',
      greeting: 'Willkommen',
      logout: 'Abmelden',
    },
    orders: {
      title: 'Meine Bestellungen',
      empty: 'Sie haben noch keine Bestellungen. Sie können Ihre erste Bestellung über „Preis berechnen“ erstellen.',
      loading: 'Bestellungen werden geladen…',
      error: 'Bestellungen konnten nicht geladen werden. Bitte aktualisieren Sie die Seite.',
      status: {
        received: 'Eingegangen',
        in_progress: 'In Bearbeitung',
        translated: 'Übersetzung abgeschlossen',
        shipped: 'Versendet',
        delivered: 'Zugestellt',
        cancelled: 'Storniert',
      },
      track: 'Verfolgen',
    },
    errors: {
      nameRequired: 'Vor- und Nachname sind erforderlich.',
      emailInvalid: 'Geben Sie eine gültige E-Mail-Adresse ein.',
      passwordShort: 'Das Passwort muss mindestens 6 Zeichen lang sein.',
      codeInvalid: 'Bitte geben Sie den 6-stelligen Code ein.',
      consentRequired: 'Zur Fortsetzung ist eine Zustimmung erforderlich.',
    },
  },

  blog: {
    seo: { title: 'Blog', description: 'Ratgeberinhalte zu Übersetzung, notarieller Beglaubigung, Apostille und Lokalisierung.' },
    hero: { title: 'Blog', subtitle: 'Ratgeber aus der Welt der Übersetzung.' },
    searchPlaceholder: 'Beiträge suchen…',
    readingTime: 'Min. Lesezeit',
    relatedTitle: 'Ähnliche Beiträge',
    allCategories: 'Alle',
    empty: 'Keine Beiträge entsprachen diesem Kriterium.',
  },

  legal: {
    lastUpdatedLabel: `Letzte Aktualisierung`,
    draftNotice: `Die im nachstehenden Text in eckigen Klammern gekennzeichneten Felder ([...]) sind mit den Angaben Ihres Unternehmens auszufüllen. Die Texte dienen der allgemeinen Information; es wird empfohlen, sie vor der Veröffentlichung von einer Rechtsexpertin oder einem Rechtsexperten prüfen zu lassen.`,
    kvkk: {
      seo: { title: `KVKK-Informationstext`, description: `Informationstext zur Verarbeitung Ihrer personenbezogenen Daten nach dem KVKK Nr. 6698.` },
      title: `KVKK-Informationstext`,
      sections: [
        { heading: `Verantwortlicher`, body: `Gemäß dem Gesetz über den Schutz personenbezogener Daten Nr. 6698 (“KVKK”) werden Ihre personenbezogenen Daten in der Eigenschaft als Verantwortlicher durch [ŞİRKET ÜNVANI] (“TercümExpert”) in dem nachstehend erläuterten Umfang verarbeitet. Anschrift: [ADRES]. E-Mail: [E-POSTA]. Telefon: [TELEFON].` },
        { heading: `Verarbeitete personenbezogene Daten`, body: `Verarbeitet werden Ihre Identitäts- und Kontaktdaten (Vorname, Nachname, E-Mail-Adresse, Telefonnummer), Ihre Lieferadressdaten, Ihre Bestell- und Transaktionsdaten, die in den zu Übersetzungszwecken an uns übermittelten Dokumenten enthaltenen Daten sowie die Daten zur Transaktionssicherheit im Zusammenhang mit Ihrer Nutzung der Website (IP-Adresse, Sitzungs- und Cookie-Protokolle).` },
        { heading: `Zwecke der Verarbeitung`, body: `Ihre personenbezogenen Daten werden zu folgenden Zwecken verarbeitet: Erbringung von Leistungen im Zusammenhang mit Übersetzung, beeidigter Übersetzung, notarieller Beglaubigung und Apostille, Erstellung von Angeboten und Verwaltung von Bestellungen, Pflege der Kundenbeziehungen sowie Bearbeitung von Anfragen und Beschwerden, Erfüllung vertraglicher und gesetzlicher Verpflichtungen sowie Gewährleistung der Sicherheit der Leistungen.` },
        { heading: `Rechtsgrundlagen der Verarbeitung`, body: `Ihre Daten werden auf folgenden Rechtsgrundlagen verarbeitet: Erforderlichkeit für den Abschluss oder die Erfüllung eines Vertrags, Erfüllung unserer rechtlichen Verpflichtungen, Begründung und Wahrung eines Rechts sowie unsere berechtigten Interessen, sofern Ihre Grundrechte und Grundfreiheiten dadurch nicht beeinträchtigt werden; erforderlichenfalls erfolgt die Verarbeitung auf Grundlage Ihrer ausdrücklichen Einwilligung (KVKK m.5 und m.6).` },
        { heading: `Erhebungsmethode`, body: `Ihre personenbezogenen Daten werden auf elektronischem Wege über die Formulare auf der Website, die Registrierungs- und Bestellprozesse, per E-Mail sowie über sonstige Kommunikationskanäle erhoben.` },
        { heading: `Übermittlung personenbezogener Daten`, body: `Ihre Daten können im für die Leistungserbringung erforderlichen Umfang an unsere im In- und Ausland ansässigen Dienstleister, von denen wir Hosting-, Infrastruktur-, Authentifizierungs-, E-Mail- und Analysedienste beziehen, sowie an die zuständigen öffentlichen Stellen und Einrichtungen im Einklang mit den Voraussetzungen der KVKK m.8 und m.9 übermittelt werden. Da sich die Server einiger von uns genutzter Infrastruktur- und Dienstleister im Ausland befinden, können Ihre Daten im Rahmen der gesetzlich vorgesehenen Garantien ins Ausland übermittelt werden.` },
        { heading: `Aufbewahrungsfristen`, body: `Ihre personenbezogenen Daten werden für die durch den Verarbeitungszweck erforderliche Dauer sowie während der in den einschlägigen Rechtsvorschriften (etwa im Steuer-, Handels- und Verbraucherrecht) vorgesehenen Verjährungs- und Aufbewahrungsfristen aufbewahrt; nach Ablauf dieser Fristen werden sie gelöscht, vernichtet oder anonymisiert.` },
        { heading: `Rechte der betroffenen Person`, body: `Gemäß KVKK m.11 haben Sie das Recht, zu erfahren, ob Ihre personenbezogenen Daten verarbeitet werden, im Falle der Verarbeitung Auskunft hierüber zu verlangen, den Zweck der Verarbeitung und zu erfahren, ob die Daten zweckentsprechend verwendet werden, die im In- oder Ausland belieferten Dritten zu erfahren, im Falle einer unvollständigen oder unrichtigen Verarbeitung deren Berichtigung sowie bei Vorliegen der Voraussetzungen deren Löschung oder Vernichtung zu verlangen, die Mitteilung dieser Vorgänge an die Dritten, an die die Daten übermittelt wurden, zu verlangen, einem ausschließlich durch automatisierte Systeme herbeigeführten, für Sie nachteiligen Ergebnis zu widersprechen sowie im Falle eines Ihnen entstandenen Schadens dessen Ersatz zu verlangen.` },
        { heading: `Antragsverfahren`, body: `Ihre Anträge in Bezug auf Ihre Rechte können Sie im Einklang mit dem “Veri Sorumlusuna Başvuru Usul ve Esasları Hakkında Tebliğ” schriftlich an die E-Mail-Adresse [E-POSTA] oder an die Anschrift [ADRES] richten. Ihr Antrag wird je nach seiner Art so schnell wie möglich, spätestens jedoch innerhalb von dreißig Tagen, bearbeitet.` },
      ],
    },
    privacy: {
      seo: { title: `Datenschutzerklärung`, description: `Unsere Richtlinie zur Vertraulichkeit Ihrer personenbezogenen Daten und Ihrer Dokumente.` },
      title: `Datenschutzerklärung`,
      sections: [
        { heading: `Einleitung`, body: `Bei TercümExpert legen wir Wert auf Ihre Privatsphäre. Diese Datenschutzerklärung erläutert, welche Informationen wir bei den über [WEB ADRESİ] angebotenen Leistungen zu welchen Zwecken erheben und wie wir sie schützen. Ausführliche Informationen zur Verarbeitung personenbezogener Daten finden Sie im KVKK-Informationstext.` },
        { heading: `Von uns erhobene Informationen`, body: `Wir können Konto- und Kontaktdaten (Vorname, Nachname, E-Mail, Telefon), Bestell- und Lieferdaten, die zur Übersetzung an uns übermittelten Dokumente und deren Inhalte, zahlungsbezogene Transaktionsdaten sowie technische Daten zu Ihrer Nutzung der Website (IP-Adresse, Browserinformationen, Cookie-Protokolle) erheben.` },
        { heading: `Zwecke der Verwendung Ihrer Informationen`, body: `Wir verwenden Ihre Informationen, um die Leistungen zu erbringen, Angebote und Bestellungen zu verwalten, mit Ihnen zu kommunizieren, unsere gesetzlichen Verpflichtungen zu erfüllen sowie die Qualität und Sicherheit der Leistungen zu verbessern. Ihre Dokumente verarbeiten wir ausschließlich in dem Umfang, den die von Ihnen beauftragte Leistung erfordert.` },
        { heading: `Vertraulichkeit der Dokumente`, body: `Die zur Übersetzung übermittelten Dokumente werden als vertraulich behandelt. Zugriff auf diese Dokumente haben ausschließlich die mit der jeweiligen Leistung befassten befugten Übersetzer und Mitarbeiter, und zwar nur für die zur Auftragsdurchführung erforderliche Dauer; Ihre Dokumente werden über den Leistungszweck hinaus nicht an Dritte weitergegeben.` },
        { heading: `Drittanbieter von Dienstleistungen`, body: `Bei der Erbringung unserer Leistungen greifen wir in den Bereichen Hosting und Infrastruktur, Authentifizierung, E-Mail-Versand, Analyse und (sofern aktiviert) Zahlung auf vertrauenswürdige Drittanbieter zurück. Diese Anbieter können auf Ihre Daten ausschließlich zu dem Zweck zugreifen, die ihnen übertragene Leistung zu erbringen, und unterliegen dabei vertraglichen Vertraulichkeitspflichten; die Server einiger von ihnen können sich im Ausland befinden.` },
        { heading: `Datensicherheit`, body: `Um Ihre Daten vor unbefugtem Zugriff zu schützen, setzen wir Verschlüsselung bei der Übertragung, Zugriffsbeschränkungen sowie geeignete organisatorische und technische Maßnahmen ein. Auch wenn keine Methode absolute Sicherheit gewährleisten kann, treffen wir angemessene und aktuelle Vorkehrungen zum Schutz Ihrer Daten.` },
        { heading: `Cookies`, body: `Auf unserer Website werden Cookies und ähnliche Technologien verwendet. Ausführliche Informationen zu deren Arten und zur Verwaltung Ihrer Präferenzen können Sie der Cookie-Richtlinie entnehmen.` },
        { heading: `Ihre Rechte`, body: `Sie können Ihre Rechte nach dem KVKK ausüben, einschließlich des Rechts auf Zugang zu Ihren personenbezogenen Daten sowie auf deren Berichtigung und Löschung. Für Ihre Anträge können Sie sich unter der E-Mail-Adresse [E-POSTA] mit uns in Verbindung setzen.` },
        { heading: `Datenschutz von Kindern`, body: `Unsere Leistungen richten sich nicht an Personen unter 18 Jahren, und wir erheben nicht wissentlich personenbezogene Daten von Kindern.` },
        { heading: `Änderungen`, body: `Diese Richtlinie kann von Zeit zu Zeit aktualisiert werden. Die jeweils aktuelle Fassung wird stets auf dieser Seite veröffentlicht; bei wesentlichen Änderungen erfolgt eine Information auf geeignete Weise.` },
        { heading: `Kontakt`, body: `Bei Fragen zum Datenschutz: E-Mail: [E-POSTA] · Telefon: [TELEFON] · Anschrift: [ADRES].` },
      ],
    },
    distanceSales: {
      seo: { title: `Fernabsatzvertrag`, description: `Fernabsatzvertrag über den Verkauf von Dienstleistungen im Rahmen des Gesetzes Nr. 6502.` },
      title: `Fernabsatzvertrag`,
      sections: [
        { heading: `Vertragsparteien`, body: `Der vorliegende Fernabsatzvertrag (“Vertrag”) wird auf elektronischem Wege gemäß dem Gesetz zum Schutz der Verbraucher Nr. 6502 und der Mesafeli Sözleşmeler Yönetmeliği zwischen [ŞİRKET ÜNVANI] (“Verkäufer”; Anschrift: [ADRES], E-Mail: [E-POSTA], Telefon: [TELEFON]) einerseits und dem bestellenden Verbraucher (“Käufer”) andererseits geschlossen.` },
        { heading: `Gegenstand des Vertrags`, body: `Gegenstand des Vertrags ist die Erbringung der vom Käufer über [WEB ADRESİ] auf elektronischem Wege bestellten Leistungen im Zusammenhang mit Übersetzung, beeidigter Übersetzung, notarieller Beglaubigung und Apostille, deren Eigenschaften und Verkaufspreis in der Bestellübersicht angegeben sind.` },
        { heading: `Eigenschaften und Preis der Leistung`, body: `Die Art und der Umfang der bestellten Leistung, die Art der Lieferung (digital oder per Versand) sowie der Gesamtpreis einschließlich Steuern werden dem Käufer bei der Bestellung deutlich angezeigt und in der Bestellbestätigung ausgewiesen. Die Preisgestaltung richtet sich nach der gewählten Leistung und den Eigenschaften des Dokuments.` },
        { heading: `Zahlung`, body: `Die Zahlung erfolgt über die im Bestellschritt angebotenen Zahlungsmethoden. Die Bestellung wird nach Bestätigung der Zahlung bearbeitet.` },
        { heading: `Erfüllung und Lieferung`, body: `Bei digitalen Lieferungen wird die Übersetzung nach ihrer Fertigstellung über das Konto oder die E-Mail-Adresse des Käufers übermittelt. Bei physischen, im Original unterzeichneten oder beeidigten Dokumenten erfolgt die Lieferung per Versand an die vom Käufer angegebene Anschrift. Die voraussichtlichen Lieferzeiten werden bei der Bestellung angegeben; sie können sich je nach Umfang der Dokumente und den Beglaubigungsprozessen ändern.` },
        { heading: `Widerrufsrecht`, body: `Bei Verträgen über die Erbringung von Dienstleistungen steht dem Käufer grundsätzlich das Recht zu, innerhalb von vierzehn (14) Tagen ab dem Tag des Vertragsschlusses ohne Angabe von Gründen zu widerrufen. Die nachstehend genannten Ausnahmen bleiben jedoch vorbehalten.` },
        { heading: `Ausnahmen vom Widerrufsrecht`, body: `Gemäß der Mesafeli Sözleşmeler Yönetmeliği m.15 kann das Widerrufsrecht nicht ausgeübt werden bei Dienstleistungen, mit deren Erbringung mit Zustimmung des Käufers begonnen wurde und die vor Ablauf der Widerrufsfrist vollständig erbracht wurden, sowie bei Waren und Dienstleistungen, die nach den Wünschen oder den persönlichen Bedürfnissen des Käufers eigens angefertigt werden (einschließlich personen- oder dokumentenbezogen erstellter Übersetzungs- und Beglaubigungsleistungen). Vor Beginn der Übersetzungsarbeit übermittelte Stornierungsanträge werden gesondert geprüft.` },
        { heading: `Stornierung und Rückerstattung`, body: `Bei Bestellungen, mit deren Erfüllung noch nicht begonnen wurde, können Stornierungsanträge über [E-POSTA] übermittelt werden; als berechtigt anerkannte Rückerstattungen erfolgen innerhalb einer angemessenen Frist über die Zahlungsmethode, mit der die Zahlung geleistet wurde. Bei personenbezogenen Leistungen, mit deren Erfüllung begonnen wurde oder die bereits abgeschlossen sind, kann eine Rückerstattung aufgrund der Art des Auftrags ausgeschlossen sein.` },
        { heading: `Beilegung von Streitigkeiten`, body: `Bei Streitigkeiten, die sich aus diesem Vertrag ergeben können, sind im Rahmen der vom Ticaret Bakanlığı jährlich bekannt gegebenen Wertgrenzen die Tüketici Hakem Heyetleri sowie die Verbrauchergerichte am Wohnort des Käufers oder am Ort der Transaktion zuständig.` },
        { heading: `Inkrafttreten`, body: `Mit der Bestätigung der Bestellung erklärt der Käufer, sämtliche Bedingungen dieses Vertrags gelesen und akzeptiert zu haben. Der Vertrag tritt mit der Bestätigung der Bestellung in Kraft.` },
      ],
    },
    cookies: {
      seo: { title: `Cookie-Richtlinie`, description: `Informationen über die auf unserer Website verwendeten Cookies und die Verwaltung Ihrer Präferenzen.` },
      title: `Cookie-Richtlinie`,
      sections: [
        { heading: `Was ist ein Cookie?`, body: `Cookies sind kleine Textdateien, die beim Besuch einer Website in Ihrem Browser gespeichert werden. Sie dienen dazu, die Website sicherer und funktionaler zu gestalten, Ihre Präferenzen zu speichern und Nutzungsstatistiken zu gewinnen.` },
        { heading: `Warum verwenden wir Cookies?`, body: `Wir verwenden Cookies, um die grundlegenden Funktionen der Website bereitzustellen, die Sitzungssicherheit zu gewährleisten, die Leistung zu messen und – vorbehaltlich Ihrer Einwilligung – unsere Leistungen zu verbessern sowie Marketingaktivitäten durchzuführen.` },
        { heading: `Cookie-Kategorien`, body: `Zwingend erforderliche Cookies sind für den Betrieb und die Sicherheit der Website notwendig und können nicht deaktiviert werden. Leistungs- und Analyse-Cookies helfen uns, die Interaktionen der Besucher zu verstehen. Marketing-Cookies unterstützen die Bereitstellung von Inhalten und Werbung, die Ihren Interessen entsprechen. Präferenz-Cookies speichern Ihre Auswahl, etwa die Sprache. Analyse- und Marketing-Cookies werden ausschließlich mit Ihrer ausdrücklichen Einwilligung eingesetzt.` },
        { heading: `Cookies von Drittanbietern`, body: `Zu Analyse- und Marketingzwecken können wir Dienste von Drittanbietern (etwa Werkzeuge für Besucherstatistiken und Werbemessung) nutzen. Diese Dienste können eigene Cookies setzen und Daten im Rahmen ihrer eigenen Datenschutzrichtlinien verarbeiten.` },
        { heading: `Verwaltung der Cookie-Präferenzen`, body: `Ihre Präferenzen hinsichtlich nicht zwingend erforderlicher Cookies können Sie jederzeit über das auf der Website bereitgestellte Cookie-Präferenztool erteilen oder ändern. Darüber hinaus können Sie Cookies über die Einstellungen Ihres Browsers löschen oder blockieren; in diesem Fall funktionieren jedoch möglicherweise einige Bereiche der Website nicht ordnungsgemäß.` },
        { heading: `Aufbewahrungsfristen`, body: `Cookies werden je nach Art für die Dauer der Sitzung oder für einen bestimmten Zeitraum gespeichert. Sitzungs-Cookies werden beim Schließen des Browsers gelöscht; dauerhafte Cookies enden nach Ablauf des festgelegten Zeitraums oder wenn Sie sie löschen.` },
        { heading: `Änderungen`, body: `Diese Cookie-Richtlinie kann von Zeit zu Zeit aktualisiert werden. Die jeweils aktuelle Fassung wird stets auf dieser Seite veröffentlicht.` },
      ],
    },
    partnership: {
      seo: { title: `Partnerschaftsvertrag`, description: `Die Bedingungen des Partnerprogramms von TercümExpert.` },
      title: `Partnerschaftsvertrag`,
      sections: [
        { heading: `Vertragsparteien und Gegenstand`, body: `Der vorliegende Partnerschaftsvertrag wird einerseits zwischen [ŞİRKET ÜNVANI] („TercümExpert“) und andererseits dem sich für das Programm bewerbenden Partner („Partner“) geschlossen, um die Bedingungen und Konditionen des Partnerprogramms (Empfehlungsprogramms) von TercümExpert zu regeln.` },
        { heading: `Programmumfang`, body: `Der Partner verweist über sein eigenes Netzwerk und seine eigenen Kanäle Kunden an TercümExpert. Sofern der verwiesene Kunde über TercümExpert eine Dienstleistung erwirbt, erwirbt der Partner Anspruch auf die in diesem Vertrag festgelegte Provision.` },
        { heading: `Provision`, body: `Der Partner erwirbt für jede gültige und bestätigte Empfehlung einen Provisionsanspruch in Höhe von %20 des von dem verwiesenen Kunden gezahlten Dienstleistungsentgelts. Der Provisionssatz sowie dessen Bedingungen können von TercümExpert unter Vorbehalt einer vorherigen Mitteilung aktualisiert werden. Stornierte, zurückerstattete oder nicht vollständig bezahlte Transaktionen werden der Provision nicht zugrunde gelegt.` },
        { heading: `Nachverfolgung und Anspruchserwerb`, body: `Empfehlungen werden über den dem Partner bereitgestellten Tracking-Link, einen QR-Code oder das von TercümExpert festgelegte Verfahren zugeordnet. Ein Provisionsanspruch entsteht ausschließlich für Transaktionen, die auf diese Weise ordnungsgemäß zugeordnet und vollständig bezahlt wurden.` },
        { heading: `Zahlung`, body: `Die erworbenen Provisionen werden auf das vom Partner angegebene Konto ausgezahlt. Der Zahlungszeitraum und die Zahlungsbedingungen werden zwischen den Parteien gesondert festgelegt. Die steuerlichen Verpflichtungen im Zusammenhang mit der Zahlung unterliegen den geltenden Rechtsvorschriften.` },
        { heading: `Pflichten des Partners`, body: `Der Partner verpflichtet sich, in seinen Werbemaßnahmen zutreffende und nicht irreführende Informationen zu verwenden, Verhaltensweisen zu unterlassen, die der Marke und dem Ansehen von TercümExpert schaden, und die geltenden Rechtsvorschriften einzuhalten.` },
        { heading: `Untersagte Verhaltensweisen`, body: `Der Versand von Spam und unerwünschten Massennachrichten, irreführende Werbung sowie Verhaltensweisen, die durch gefälschte oder Eigenempfehlungen unlauteren Wettbewerb begründen, sind untersagt. Derartige Verhaltensweisen stellen einen Grund für die Stornierung der Provision und die Kündigung des Vertrags dar.` },
        { heading: `Markennutzung`, body: `Der Partner darf die Marke, das Logo und die Werbematerialien von TercümExpert ausschließlich im Rahmen der schriftlichen Zustimmung und der von TercümExpert bereitgestellten Vorgaben verwenden.` },
        { heading: `Vertraulichkeit`, body: `Die Parteien verpflichten sich, die im Rahmen dieses Vertrags erlangten vertraulichen Informationen zu schützen und ausschließlich zum Zweck des Programms zu verwenden.` },
        { heading: `Unabhängige Partei`, body: `Der Partner ist eine unabhängige Partei; er ist weder Arbeitnehmer, Vertreter noch Handelsvertreter von TercümExpert und darf gegenüber Dritten keine Verpflichtungen im Namen von TercümExpert eingehen.` },
        { heading: `Laufzeit und Kündigung`, body: `Der Vertrag bleibt in Kraft, bis eine der Parteien dessen Kündigung erklärt. TercümExpert kann den Vertrag im Falle eines Verstoßes gegen die Verpflichtungen mit sofortiger Wirkung kündigen; in diesem Fall werden Provisionen aus regelwidrigen Empfehlungen nicht ausgezahlt.` },
        { heading: `Streitigkeiten und Geltung`, body: `Der vorliegende Vertrag unterliegt dem Recht der Türkiye Cumhuriyeti. Der Partner erklärt mit der Bestätigung der Bewerbung, die Vertragsbedingungen gelesen und akzeptiert zu haben.` },
      ],
    },
  },

  admin: {
    attachmentImage: 'Bild',
    attachmentFile: 'Dokument',
    title: `Chatverläufe`,
    summary: `{total} Chats · {leads} Kontaktanfragen`,
    onlyLeads: `Nur Kontaktanfragen`,
    loading: `Verläufe werden geladen…`,
    error: `Verläufe konnten nicht gelesen werden. Bitte prüfen Sie, ob die Supabase-Tabelle und die Berechtigungen (RLS) eingerichtet sind.`,
    empty: `Noch keine Einträge vorhanden.`,
    selectHint: `Wählen Sie links einen Chat aus, um ihn anzuzeigen.`,
    contactRequest: `Kontaktanfrage`,
    contactInfo: `Kontaktdaten`,
    fieldName: `Name`,
    fieldEmail: `E-Mail`,
    fieldPhone: `Telefon`,
    fieldMessage: `Nachricht`,
    requestBadge: `Anfrage`,
    noMessages: `In diesem Eintrag sind keine Nachrichten vorhanden (nur eine Kontaktanfrage).`,
    loginTitle: `Anmeldung erforderlich`,
    loginDesc: `Bitte melden Sie sich mit einem Administratorkonto an, um diese Seite anzuzeigen.`,
    login: `Anmelden`,
    noAccessTitle: `Kein Zugriff`,
    noAccessDesc: `Diese Seite ist nur für Administratoren zugänglich.`,
    loadingAuth: `Wird geladen…`,
  },
  footer: {
    tagline: 'Ihr zuverlässiger Partner für professionelle Übersetzungsdienstleistungen.',
    columns: {
      quickLinks: 'Schnellzugriff',
      services: 'Leistungen',
      contact: 'Kontakt',
    },
    quickLinks: {
      corporate: 'Unternehmen',
      services: 'Unsere Leistungen',
      quote: 'Preis berechnen',
      blog: 'Blog',
      faq: 'Häufig gestellte Fragen',
      contact: 'Kontakt',
    },
    serviceLinks: {
      sworn: 'Beglaubigte Übersetzung',
      notarized: 'Notariell beglaubigte Übersetzung',
      apostille: 'Apostille-Verfahren',
      corporate: 'Lösungen für Unternehmen',
      partnership: 'Partnerprogramm',
    },
    legal: {
      kvkk: 'KVKK',
      privacy: 'Datenschutzrichtlinie',
      distanceSales: 'Fernabsatzvertrag',
      cookies: 'Cookie-Richtlinie',
    },
    socialTitle: 'Folgen Sie uns',
    whatsapp: 'WhatsApp-Support',
    rights: 'Alle Rechte vorbehalten.',
  },

  cookie: {
    title: 'Cookie-Einstellungen',
    desc: 'Wir verwenden Cookies, um Ihr Erlebnis zu verbessern. Andere als notwendige Cookies werden nur mit Ihrer Einwilligung ausgeführt.',
    accept: 'Akzeptieren',
    reject: 'Ablehnen',
    manage: 'Einstellungen verwalten',
    save: 'Einstellungen speichern',
    categories: {
      necessary: { label: 'Notwendig', desc: 'Für die Funktion der Website erforderlich; kann nicht deaktiviert werden.' },
      analytics: { label: 'Analyse', desc: 'Hilft uns, die Nutzung zu verstehen.' },
      marketing: { label: 'Marketing', desc: 'Für relevante Inhalte und Werbung.' },
      preferences: { label: 'Präferenzen', desc: 'Merkt sich Ihre Präferenzen.' },
    },
  },

  chatbot: {
    attach: {
      button: 'Datei anhängen',
      tooLarge: 'Datei ist zu groß (max. 25 MB).',
      unsupported: 'Audio- und Videodateien kann ich im Chat nicht auswerten. Sie können sie auf der Angebotsseite hochladen.',
      cannotRead: 'Ich konnte diese Datei nicht lesen. Sie können sie auf der Angebotsseite hochladen oder ein anderes Format versuchen.',
      reading: 'Datei wird gelesen…',
      remove: 'Entfernen',
    },
    nudge: 'Wie kann ich Ihnen helfen?',
    title: 'TercümExpert-Support',
    open: 'Chat öffnen',
    close: 'Chat schließen',
    minimize: 'Minimieren',
    clear: 'Konversation löschen',
    inputPlaceholder: 'Geben Sie Ihre Nachricht ein…',
    send: 'Senden',
    typing: 'Schreibt…',
    welcome:
      'Hallo und herzlich willkommen bei TercümExpert. Ich kann Ihnen bei Übersetzung, Preisgestaltung, notarieller Beglaubigung, Apostille oder Firmenleistungen helfen.',
    quickQuestions: [
      'Wie wird der Preis berechnet?',
      'Was ist eine beglaubigte Übersetzung?',
      'Ich möchte ein Dokument hochladen',
      'Ich möchte ein Firmenangebot',
      'Ist eine notarielle Beglaubigung erforderlich?',
      'Verbinden Sie mich mit einem Mitarbeiter',
    ],
    handoff: 'Mit einem Mitarbeiter verbinden',
    toWhatsapp: 'An WhatsApp übergeben',
    disclaimer: 'Diese Informationen sind allgemeiner Natur; bitte bestätigen Sie die genauen Anforderungen bei der zuständigen Institution.',
    sensitiveWarning:
      'Bitte teilen Sie keine sensiblen personenbezogenen Daten über diesen Chat mit. Ihre Dokumente können Sie über den sicheren Upload-Bereich senden.',
    answers: [
      `Der Preis richtet sich nach der Wortzahl Ihres Dokuments, der Sprachkombination, der Art der Leistung (beglaubigt, notariell beglaubigt, Apostille) sowie der Lieferzeit. Für einen sofortigen Preisvorschlag können Sie Ihr Dokument auf der Seite Preis berechnen hochladen oder die entsprechenden Angaben eingeben.`,
      `Eine beglaubigte Übersetzung ist eine offizielle Übersetzung, die von einem vereidigten Übersetzer angefertigt und mit dessen Unterschrift und Stempel bestätigt wird. Behörden verlangen in der Regel beglaubigte Übersetzungen; bei Bedarf kann zusätzlich eine notarielle Beglaubigung hinzugefügt werden.`,
      `Sie können Ihr Dokument über den sicheren Upload-Bereich auf der Seite Preis berechnen an uns übermitteln. Direkt nach dem Hochladen sehen Sie den voraussichtlichen Preis und können Ihre Bestellung abschließen.`,
      `Für Ihren geschäftlichen Bedarf bieten wir bei regelmäßigen und umfangreichen Übersetzungen individuelle Preise und eine bevorzugte Lieferung an. Weitere Einzelheiten finden Sie auf unserer Seite für Geschäftskunden, oder Sie nehmen einfach Kontakt mit uns auf.`,
      `Ob eine notarielle Beglaubigung erforderlich ist, hängt von der Behörde, bei der Sie das Dokument einreichen, und von der Art des Vorgangs ab. Manche Stellen akzeptieren ausschließlich beglaubigte Übersetzungen, während andere zusätzlich eine notarielle Beglaubigung verlangen. Falls Sie sich nicht sicher sind, helfen wir Ihnen gerne weiter.`,
      `Gerne verbinden wir Sie sofort mit einem unserer Kundenberater. Über die Schaltfläche unten können Sie uns per WhatsApp schreiben.`,
    ],
    fallback: `Bei Ihrer Frage kann Ihnen einer unserer Kundenberater am besten weiterhelfen. Über die Schaltfläche unten können Sie uns per WhatsApp schreiben; Ihre Nachricht wird dabei bereits vorbereitet übermittelt.`,
    contact: {
      "introTitle": "Willkommen",
      "introDesc": "Damit ich Ihnen besser helfen kann, dürfte ich zunächst Ihren Namen und Ihre E-Mail-Adresse erfahren?",
      "start": "Chat starten",
      "introError": "Bitte geben Sie Ihren Namen und Ihre E-Mail-Adresse ein.",
      whatsapp: `WhatsApp`,
      email: `E-Mail`,
      phone: `Telefon`,
      leaveInfo: `Meine Kontaktdaten hinterlassen`,
      formTitle: `Lassen Sie uns Sie kontaktieren`,
      formDesc: `Hinterlassen Sie Ihre Daten, unser Team meldet sich schnellstmöglich bei Ihnen.`,
      name: `Ihr Name`,
      emailField: `E-Mail`,
      phoneField: `Telefon`,
      message: `Ihre Nachricht (optional)`,
      submit: `Senden`,
      submitting: `Wird gesendet…`,
      thanks: `Vielen Dank, unser Team wird sich in Kürze mit Ihnen in Verbindung setzen.`,
      errorRequired: `Bitte geben Sie eine E-Mail-Adresse oder Telefonnummer ein.`,
      back: `Zurück`,
    },
  },

  translator: {
    "seo": {
      "title": "Übersetzer-Panel — TercümExpert",
      "description": "Übersetzerbewerbung und Arbeitsbereich."
    },
    "loading": "Wird geladen…",
    "loginTitle": "Anmeldung erforderlich",
    "loginDesc": "Dieser Bereich ist ausschließlich für Übersetzer und Administratoren bestimmt. Bitte melden Sie sich an, um fortzufahren.",
    "login": "Anmelden",
    "setupTitle": "Panel noch nicht bereit",
    "setupDesc": "Die Übersetzer-Infrastruktur (Datenbank) wurde noch nicht eingerichtet. Das Panel wird aktiviert, sobald die Einrichtung abgeschlossen ist.",
    "applyTitle": "Übersetzerbewerbung",
    "applyDesc": "Füllen Sie Ihre Angaben aus, um unserem Netzwerk freiberuflicher Übersetzer beizutreten. Ihre Bewerbung wird nach Freigabe durch den Administrator aktiviert.",
    "applyNote": "Ihre Angaben werden ausschließlich zur Bewertung und Zahlung verwendet.",
    "form": {
      "fullName": "Vollständiger Name",
      "birthDate": "Geburtsdatum",
      "phone": "Telefon",
      "country": "Land",
      "city": "Stadt / Bundesland",
      "selectCountry": "Land auswählen",
      "selectCity": "Stadt / Bundesland auswählen",
      "cityNeedsCountry": "Bitte wählen Sie zuerst ein Land",
      "address": "Vollständige Adresse",
      "isSworn": "Sind Sie ein vereidigter (beglaubigter) Übersetzer?",
      "isSwornHint": "Aktivieren Sie diese Option, wenn Sie über eine notariell beglaubigte Vereidigung verfügen. Sie werden bei Aufträgen, die eine beglaubigte Übersetzung erfordern, bevorzugt berücksichtigt.",
      "iban": "IBAN",
      "ibanName": "IBAN-Inhaber (vollständiger Name)",
      "languagePairs": "Sprachpaare",
      "source": "Ausgangssprache",
      "target": "Zielsprache",
      "addPair": "Hinzufügen",
      "removePair": "Entfernen",
      "swap": "Richtung tauschen",
      "expertise": "Fachgebiete",
      "submit": "Bewerbung absenden",
      "submitting": "Wird gesendet…",
      "saved": "Ihre Angaben wurden gespeichert.",
      "saveError": "Speichern fehlgeschlagen. Bitte versuchen Sie es erneut.",
      "required": "Bitte füllen Sie die Pflichtfelder aus.",
      "atLeastOnePair": "Fügen Sie mindestens ein Sprachpaar hinzu."
    },
    "expertiseLabels": {
      "legal": "Recht",
      "medical": "Medizin",
      "technical": "Technik",
      "academic": "Wissenschaft",
      "commercial": "Handel",
      "financial": "Finanzen",
      "literary": "Literatur",
      "official": "Amtliche Dokumente",
      "localization": "Web / Software",
      "general": "Allgemein"
    },
    "pendingTitle": "Ihre Bewerbung wird geprüft",
    "pendingDesc": "Wir haben Ihre Übersetzerbewerbung erhalten. Der Zugang zum Panel wird nach der Prüfung durch den Administrator freigeschaltet.",
    "rejectedTitle": "Bewerbung nicht genehmigt",
    "rejectedDesc": "Ihre Bewerbung wurde derzeit nicht genehmigt. Sie können Ihre Angaben aktualisieren und es erneut versuchen.",
    "reapply": "Erneut versuchen",
    "cancelApplication": "Bewerbung zurückziehen",
    "cancelConfirm": "Sind Sie sicher, dass Sie Ihre Bewerbung zurückziehen möchten? Ihr Datensatz wird gelöscht; Sie können sich bei Bedarf später erneut bewerben.",
    "panelTitle": "Übersetzer-Panel",
    "tabs": {
      "profile": "Mein Profil",
      "pool": "Übersetzungspool",
      "active": "Aktive Aufträge",
      "pending": "Ausstehende Freigabe",
      "approved": "Genehmigt",
      "completed": "Abgeschlossen",
      "wallet": "Wallet"
    },
    "soon": "Dieser Bereich folgt im nächsten Schritt.",
    "jobs": {
      "empty": "In diesem Bereich gibt es derzeit keine Aufträge.",
      "translator": "Übersetzer",
      "sourceFiles": "Ausgangsdokumente",
      "translationFiles": "Hochgeladene Übersetzung",
      "tracking": "Sendungsverfolgung",
      "rejectionReason": "Ablehnungsgrund",
      "chooseFiles": "Übersetzungsdateien auswählen",
      "filesSelected": "Datei(en) ausgewählt",
      "uploadHint": "Laden Sie Ihre Übersetzung und bei Bedarf eine digitale Kopie des Ausgangsdokuments hoch und senden Sie diese zur Freigabe.",
      "submit": "Zur Freigabe senden",
      "sending": "Wird gesendet…",
      "needFiles": "Bitte wählen Sie mindestens eine Datei aus.",
      "uploadError": "Die Dateien konnten nicht hochgeladen werden. Bitte versuchen Sie es erneut.",
      "submittedMsg": "Übersetzung zur Freigabe gesendet.",
      "actionError": "Die Aktion konnte nicht abgeschlossen werden. Bitte versuchen Sie es erneut.",
      "waitingApproval": "Ihre Übersetzung wartet auf die Freigabe durch die Verwaltung. Nach der Freigabe erscheint der Zustellschritt unter „Genehmigt“.",
      "trackingPlaceholder": "Sendungsnummer / Link",
      "needTracking": "Für die Zustellung per Kurier ist eine Sendungsnummer erforderlich.",
      "markShipped": "Versandt — abschließen",
      "markDelivered": "Zugestellt — abschließen",
      "completedMsg": "Auftrag abgeschlossen. Ihr Verdienst wurde Ihrem Wallet gutgeschrieben.",
      "reasonPlaceholder": "Bei Ablehnung geben Sie den Grund an (für den Übersetzer sichtbar)…",
      "approve": "Genehmigen",
      "reject": "Ablehnen",
      "needReason": "Geben Sie einen Grund für die Ablehnung an.",
      "approvedMsg": "Übersetzung genehmigt.",
      "rejectedMsg": "Übersetzung abgelehnt; an den Übersetzer zurückgegeben.",
      "statusLabel": "Status",
      "status_claimed": "In Bearbeitung",
      "status_submitted": "Ausstehende Freigabe",
      "status_approved": "Genehmigt — Zustellphase",
      "status_completed": "Abgeschlossen"
    },
    "pool": {
      "loading": "Pool wird geladen…",
      "empty": "Es gibt derzeit keine ausstehenden Aufträge, die zu Ihren Sprachpaaren und Fachgebieten passen.",
      "error": "Der Pool konnte nicht geladen werden. Bitte versuchen Sie es erneut.",
      "orderNo": "Auftrag",
      "service": "Leistungsart",
      "documentType": "Dokumentart",
      "langPair": "Sprachpaar",
      "words": "Wörter",
      "pagesUnit": "Seiten",
      "deadline": "Frist",
      "daysUnit": "Werktage",
      "note": "Kundenhinweis",
      "customerInfo": "Kundendaten",
      "deliveryInfo": "Kunden- und Zustelldaten",
      "customerName": "Vollständiger Name",
      "customerEmail": "E-Mail",
      "customerPhone": "Telefon",
      "deliveryAddress": "Lieferadresse",
      "text": "Auftragstext",
      "files": "Dokumente",
      "earning": "Ihr Verdienst für diesen Auftrag",
      "urgent": "Dringend",
      "sworn": "Beglaubigt",
      "notary": "Notariell beglaubigt",
      "apostille": "Apostille",
      "cargo": "Kurierzustellung",
      "digital": "Digitale Zustellung",
      "claim": "Diesen Auftrag übernehmen",
      "claiming": "Wird übernommen…",
      "claimed": "Sie haben den Auftrag erfolgreich übernommen.",
      "claimError": "Der Auftrag konnte nicht übernommen werden. Möglicherweise wurde er bereits von jemand anderem übernommen; aktualisieren Sie die Liste.",
      "ibanRequired": "Bevor Sie Aufträge übernehmen können, müssen Ihre IBAN-Angaben von der Verwaltung verifiziert werden. Geben Sie Ihre IBAN in Ihrem Profil ein; nach der Verifizierung können Sie Aufträge aus dem Pool übernehmen."
    },
    "profile": {
      "statusApproved": "Genehmigter Übersetzer",
      "verifiedIban": "IBAN verifiziert",
      "unverifiedIban": "IBAN nicht verifiziert",
      "current": "Gespeichert",
      "edit": "Angaben speichern",
      "ibanReminder": "Um Ihre Zahlungen zu erhalten, geben Sie bitte Ihre IBAN-Angaben ein und speichern Sie diese. Nach der Verifizierung durch den Administrator werden die Zahlungen auf dieses Konto überwiesen.",
      "lockedHint": "Nach der Genehmigung nicht mehr änderbar",
      "revokeTitle": "Diese Änderung widerruft Ihre Genehmigung",
      "revokeWarning": "Wenn Sie Ihre Sprachpaare, Ihren Vereidigungsstatus oder Ihre Fachgebiete ändern, kehrt Ihr Konto zur Prüfung durch die Verwaltung zurück (Status: ausstehend). Ihre Aufträge, Datensätze und Ihr Wallet BLEIBEN ERHALTEN; nach erneuter Genehmigung setzen Sie dort fort, wo Sie aufgehört haben.",
      "consent": "Ich habe die Angaben gelesen und akzeptiere sie",
      "ibanReverify": "Sie ändern Ihre IBAN. Die neue IBAN wird erneut der Verwaltung zur Prüfung vorgelegt; Ihr Konto bleibt aktiv, Sie können jedoch keine neuen Aufträge aus dem Pool übernehmen, bis die IBAN verifiziert ist."
    },
    "admin": {
      "title": "Verwaltungspanel",
      "translatorsTab": "Übersetzer",
      "applicationsTab": "Bewerbungen",
      "ibanTab": "IBAN-Freigaben",
      "ordersTab": "Aufträge",
      "paymentsTab": "Zahlungen",
      "noIbanPending": "Keine Übersetzer warten auf eine IBAN-Freigabe.",
      "ibanHint": "Genehmigen Sie hier neu eingegebene oder geänderte IBANs. Bis zur Genehmigung kann der Übersetzer keine neuen Aufträge aus dem Pool übernehmen.",
      "ibanApprove": "IBAN genehmigen",
      "paymentsHint": "Am Zahltag (jeweils am 1. und 16. jedes Monats): Laden Sie für jeden Übersetzer, den Sie bezahlt haben, den Beleg hoch und klicken Sie auf „Als bezahlt markieren“. Ohne Beleg funktioniert die Schaltfläche nicht. Übersetzer mit einem Guthaben von null werden hier nicht aufgeführt.",
      "noPayments": "Keine Übersetzer mit auszuzahlendem Guthaben.",
      "paymentAmount": "Auszuzahlender Betrag",
      "uploadReceipt": "Beleg hochladen",
      "receiptUploaded": "Beleg hochgeladen",
      "receiptRequired": "Laden Sie zuerst einen Beleg hoch",
      "uploading": "Wird hochgeladen…",
      "markPaid": "Als bezahlt markieren",
      "paid": "Zahlung erfasst und der Übersetzer wurde mit dem Beleg benachrichtigt.",
      "panelHint": "Verfolgen Sie genehmigte Übersetzer nach Profil, prüfen Sie Bewerbungen und verwalten Sie den Ablauf aller Aufträge.",
      "summary": "{total} Übersetzer · {pending} ausstehende Bewerbungen",
      "applicationsSummary": "{total} Bewerbungen · {pending} zur Prüfung ausstehend",
      "noApproved": "Noch keine genehmigten Übersetzer.",
      "noPending": "Keine ausstehenden Bewerbungen.",
      "noMatch": "Keine Datensätze entsprechen den Filtern.",
      "loadError": "Datensätze konnten nicht geladen werden. Überprüfen Sie die Datenbank und die Berechtigungen (RLS).",
      "noApplications": "Noch keine Übersetzerdatensätze.",
      "filters": {
        "namePlaceholder": "Nach Name suchen…",
        "country": "Land",
        "city": "Stadt / Bundesland",
        "anyCountry": "Alle Länder",
        "anyCity": "Alle Städte",
        "cityNeedsCountry": "Bitte wählen Sie zuerst ein Land",
        "sourceLang": "Ausgangssprache",
        "targetLang": "Zielsprache",
        "anyLang": "Beliebig",
        "eitherDirection": "Beide Richtungen (Ausgangssprache↔Zielsprache)",
        "expertise": "Fachgebiete",
        "clear": "Filter zurücksetzen",
        "results": "{n} Datensätze"
      },
      "orders": {
        "loadError": "Aufträge konnten nicht geladen werden. Bitte versuchen Sie es erneut.",
        "empty": "Noch keine Aufträge.",
        "searchPlaceholder": "Nach Auftragsnummer oder Kundenname suchen…",
        "results": "{n} Aufträge",
        "customer": "Kunde",
        "translator": "Übersetzer",
        "unassigned": "Nicht zugewiesen",
        "status": "Status",
        "done": "Abgeschlossen",
        "inProgress": "In Bearbeitung",
        "completedOn": "Abgeschlossen am",
        "placedOn": "Auftragsdatum",
        "total": "Gesamt",
        "statusAvailable": "Im Pool (nicht übernommen)",
        "statusClaimed": "In Übersetzung",
        "statusSubmitted": "Ausstehende Freigabe",
        "statusApproved": "Zustellphase",
        "statusCompleted": "Abgeschlossen",
        "statusCancelled": "Storniert"
      },
      "profile": {
        "back": "Zurück zu den Übersetzern",
        "adminOnly": "Dieses Profil ist ausschließlich für die Verwaltung bestimmt; der Übersetzer kann es nicht sehen.",
        "infoTitle": "Angaben",
        "walletTitle": "Wallet",
        "jobsTitle": "Aufträge",
        "noJobs": "Dieser Übersetzer hat noch keine Aufträge."
      },
      "approve": "Genehmigen",
      "reject": "Ablehnen",
      "colLangs": "Sprachpaare",
      "colExpertise": "Fachgebiete",
      "colLocation": "Stadt / Land",
      "swornBadge": "Beglaubigt",
      "returningBadge": "Wiederkehrender Übersetzer",
      "ibanVerified": "IBAN verifiziert",
      "ibanNotVerified": "IBAN nicht verifiziert",
      "verifyIban": "IBAN verifizieren",
      "unverifyIban": "Verifizierung aufheben",
      "statusPending": "Ausstehend",
      "statusApproved": "Genehmigt",
      "statusRejected": "Abgelehnt",
      "actionError": "Die Aktion konnte nicht abgeschlossen werden."
    },
    "wallet": {
      "total": "Gesamtverdienst",
      "locked": "Gesperrt",
      "withdrawable": "Auszahlbar",
      "paid": "Ausgezahlt",
      "payInfo": "Verdienste werden Ihrem Wallet gutgeschrieben, wenn ein Auftrag abgeschlossen wird; sie bleiben 7 Tage lang gesperrt und werden anschließend auszahlbar. Zahlungen auf das auszahlbare Guthaben erfolgen am 1. und 16. jedes Monats.",
      "empty": "Noch keine Verdienste. Verdienste aus abgeschlossenen Aufträgen erscheinen hier.",
      "entryOrder": "Auftrag",
      "date": "Datum",
      "statusCol": "Status",
      "amount": "Betrag",
      "statusPaid": "Bezahlt",
      "statusUnlocked": "Auszahlbar",
      "statusPending": "Gesperrt",
      "loadError": "Das Wallet konnte nicht geladen werden. Bitte versuchen Sie es erneut."
    },
    "adminWallet": {
      "firmShare": "Firmenanteil (inkl. MwSt.)",
      "firmShareHint": "Firmenanteil = Summe der abgeschlossenen Aufträge (inkl. MwSt.) abzüglich der Übersetzerverdienste.",
      "ciro": "Gesamtumsatz (inkl. MwSt.)",
      "kdv": "MwSt. (an den Staat)",
      "payouts": "An Übersetzer ausgezahlt",
      "net": "Firmen-Netto",
      "count": "{n} abgeschlossene Aufträge",
      "empty": "Noch keine abgeschlossenen Aufträge.",
      "colOrder": "Auftrag",
      "colTranslator": "Übersetzer",
      "colDate": "Datum",
      "colTotal": "Gesamt (inkl. MwSt.)",
      "colPayout": "Übersetzer",
      "colFirm": "Firmenanteil",
      "loadError": "Das Wallet konnte nicht geladen werden. Bitte versuchen Sie es erneut."
    }
  },
  authx: {
    "rememberMe": "Angemeldet bleiben",
    "showPassword": "Passwort anzeigen",
    "hidePassword": "Passwort verbergen",
    "forgot": "Passwort vergessen",
    "forgotTitle": "Passwort zurücksetzen",
    "forgotDesc": "Geben Sie Ihre registrierte E-Mail-Adresse ein, und wir senden Ihnen einen einmaligen Link zum Zurücksetzen Ihres Passworts.",
    "forgotEmail": "E-Mail",
    "forgotSubmit": "Link zum Zurücksetzen senden",
    "forgotSent": "Der Link wurde an Ihre E-Mail-Adresse gesendet. Überprüfen Sie Ihren Posteingang (und Ihren Spam-Ordner).",
    "forgotBack": "Zurück zur Anmeldung",
    "resetTitle": "Neues Passwort festlegen",
    "resetDesc": "Geben Sie Ihr neues Passwort ein und bestätigen Sie es, indem Sie es erneut eingeben.",
    "newPassword": "Neues Passwort",
    "newPasswordRepeat": "Neues Passwort (wiederholen)",
    "mismatch": "Die Passwörter stimmen nicht überein.",
    "weak": "Das Passwort muss mindestens 6 Zeichen lang sein.",
    "resetSubmit": "Passwort aktualisieren",
    "resetSuccess": "Ihr Passwort wurde aktualisiert. Sie können sich jetzt mit Ihrem neuen Passwort anmelden.",
    "resetInvalid": "Der Link ist ungültig oder abgelaufen. Bitte fordern Sie einen neuen Link zum Zurücksetzen an.",
    "goLogin": "Anmelden",
    err: {
      "invalidCredentials": "E-Mail-Adresse oder Passwort ist falsch. Bitte überprüfen Sie Ihre Angaben und versuchen Sie es erneut.",
      "emailNotConfirmed": "Ihre E-Mail-Adresse wurde noch nicht bestätigt. Klicken Sie auf den Bestätigungslink in Ihrem Posteingang.",
      "alreadyRegistered": "Diese E-Mail-Adresse ist bereits registriert. Bitte melden Sie sich an oder setzen Sie Ihr Passwort zurück.",
      "weakPassword": "Das Passwort muss mindestens 6 Zeichen lang sein.",
      "otpInvalid": "Der Bestätigungscode ist falsch oder abgelaufen. Bitte fordern Sie einen neuen Code an.",
      "rateLimited": "Zu viele Versuche. Bitte warten Sie einen Moment und versuchen Sie es erneut.",
      "generic": "Es ist ein Fehler aufgetreten. Bitte versuchen Sie es später erneut."
    }
  },
  notFound: {
    seo: { title: 'Seite nicht gefunden', description: 'Die von Ihnen gesuchte Seite konnte nicht gefunden werden.' },
    title: 'Seite nicht gefunden',
    desc: 'Die von Ihnen gesuchte Seite wurde möglicherweise verschoben oder hat nie existiert.',
    home: 'Zurück zur Startseite',
  },
}
