import type { PartialDictionary } from '@/types/i18n'
import { FAQ_CATEGORIES_PT, FAQ_ITEMS_PT } from '@/content/faq-data.pt'

/**
 * PORTUGUÊS (pt-PT) — tradução europeia completa. Clone estrutural de en/index.ts.
 * As perguntas/respostas das FAQ (faq.categories / faq.items) provêm de um
 * conjunto de dados por localidade (content/faq-data.pt).
 */
export const pt: PartialDictionary = {
  delivery: {
    "ready": "A sua tradução está pronta",
    "download": "Descarregar tradução",
    "hint": "A sua tradução também foi enviada para o seu endereço de e-mail. Verifique a sua caixa de entrada (e a pasta de spam)."
  },

  partnerPanel: {
    seoTitle: "Painel de parceiro",
    seoDesc: "Envie a sua candidatura de parceria e obtenha aqui a sua ligação de convite.",
    loading: "A carregar…",
    loginTitle: "Início de sessão de parceiro",
    loginDesc: "Inicie sessão ou crie uma conta para se candidatar ou aceder ao seu painel.",
    login: "Iniciar sessão / Registar",
    setupTitle: "Configuração incompleta",
    setupDesc: "O sistema de parceiros ainda não está pronto.",
    applyTitle: "Candidatura de parceria",
    applyDesc: "Preencha os seus dados; a sua ligação de convite é ativada assim que a sua candidatura for aprovada.",
    applyNote: "A sua candidatura será analisada em breve.",
    sectorOther: "Indique o seu setor",
    submit: "Enviar candidatura",
    submitting: "A enviar…",
    saveError: "Não foi possível guardar a sua candidatura. Tente novamente.",
    pendingTitle: "Candidatura recebida",
    pendingDesc: "A sua candidatura está em análise. Após a aprovação, a sua ligação de convite e o seu painel serão ativados aqui.",
    cancelApplication: "Cancelar candidatura",
    rejectedTitle: "Candidatura não aprovada",
    rejectedDesc: "Esta candidatura não foi aprovada. Pode atualizar os seus dados e candidatar-se novamente.",
    reapply: "Candidatar novamente",
    approvedTitle: "A sua conta de parceiro está ativa",
    approvedDesc: "Os clientes que se registarem através da sua ligação de convite abaixo ficam permanentemente associados à sua conta.",
    panelSoon: "Um painel detalhado com os seus clientes, encomendas e carteira chegará aqui muito em breve.",
    verifyTitle: "Verificação de e-mail",
    verifyDesc: "Verifique o seu endereço de e-mail para poder receber pagamentos. Enviar-lhe-emos um código de verificação.",
    verifiedLabel: "E-mail verificado",
    sendCode: "Enviar código de verificação",
    sending: "A enviar…",
    codeSent: "Enviámos o código para o seu e-mail. Verifique a sua caixa de entrada e a pasta de spam.",
    codePlaceholder: "Código de 6 dígitos",
    verifyBtn: "Verificar",
    verifying: "A verificar…",
    verifyError: "O código é inválido ou expirou. Solicite um novo.",
    refTitle: "A sua ligação de convite",
    refDesc: "Partilhe esta ligação; os clientes que chegam através dela e se registam ficam permanentemente associados a si.",
    refCopy: "Copiar ligação",
    refCopied: "Copiado",
  },
  adminHub: {
    "tabChats": "Conversas",
    "tabCustomers": "Clientes",
    "tabUploads": "Ficheiros carregados",
    "loading": "A carregar…",
    "loadError": "Não foi possível carregar. Tente novamente.",
    "back": "Voltar",
    "custHint": "Todos os clientes registados no sistema (tradutores excluídos).",
    "custSearch": "Pesquisar nome, e-mail ou telefone…",
    "custName": "Nome completo",
    "custEmail": "E-mail",
    "custPhone": "Telefone",
    "custOrders": "Encomendas",
    "custTotal": "Montante total",
    "custJoined": "Registado",
    "custNone": "Ainda não há registos de clientes.",
    "custOrderList": "Encomendas",
    "custNoOrders": "Este cliente não tem encomendas.",
    "orderNo": "N.º da encomenda",
    "orderDate": "Data",
    "orderStatus": "Estado",
    "upHint": "Todos os ficheiros carregados na página de orçamento (guardados mesmo sem encomenda).",
    "upFile": "Ficheiro",
    "upUploader": "Carregado por",
    "upWhen": "Data",
    "upWords": "Palavras",
    "upSize": "Tamanho",
    "upDownload": "Descarregar",
    "upNone": "Ainda não há ficheiros carregados.",
    "upGuest": "Convidado"
  },

  smsVerify: {
    "sendCode": "Enviar código",
    "resend": "Reenviar código",
    "codeLabel": "Código SMS",
    "confirm": "Confirmar",
    "verified": "Telefone verificado",
    "sent": "Foi enviado um código para o seu telemóvel.",
    "mustVerify": "Para continuar, verifique o seu número de telefone através de SMS.",
    "reverifyHint": "Se alterar o seu número de telefone, terá de verificar novamente o novo número através de SMS.",
    "invalid": "Código incorreto. Tente novamente.",
    "expired": "O código expirou. Solicite um novo.",
    "rateLimited": "Demasiadas tentativas. Aguarde um momento e tente novamente.",
    "notConfigured": "A verificação por SMS está atualmente indisponível. Tente novamente mais tarde ou contacte o suporte.",
    "sendFailed": "Não foi possível enviar o código. Verifique o seu número e tente novamente.",
    "enterPhone": "Introduza primeiro um número de telefone válido.",
    "error": "Ocorreu um erro. Tente novamente.",
    "devCode": "Modo de teste — o seu código de verificação: {code}"
  },
  common: {
      "brand": "TercümExpert",
    tagline: 'O seu parceiro de confiança em serviços de tradução profissional.',
    nav: {
      home: 'Início',
      services: 'Serviços',
      quote: 'Obter orçamento',
      corporate: 'Empresas',
      partnership: 'Parcerias',
      blog: 'Blogue',
      faq: 'FAQ',
      contact: 'Contacto',
    },
    actions: {
      getQuote: 'Obter orçamento',
      calculatePrice: 'Calcular preço',
      uploadDocument: 'Carregar documento',
      whatsapp: 'Conversar no WhatsApp',
      learnMore: 'Saber mais',
      viewAll: 'Ver tudo',
      showMore: 'Mostrar mais',
      showLess: 'Mostrar menos',
      send: 'Enviar',
      apply: 'Candidatar-se',
      order: 'Efetuar encomenda',
      contactUs: 'Contacte-nos',
      openMenu: 'Abrir menu',
      closeMenu: 'Fechar menu',
      selectLanguage: 'Selecionar idioma',
      skipToContent: 'Saltar para o conteúdo',
      login: 'Iniciar sessão',
      logout: 'Terminar sessão',
      account: 'A minha conta',
    },
    states: {
      loading: 'A carregar…',
      error: 'Ocorreu um problema. Tente novamente.',
      required: 'Este campo é obrigatório.',
      demoNotice: 'Demonstração: os dados do formulário ainda não são enviados para um servidor.',
      unverified: 'A confirmar',
    },
    topbar: {
      phoneLabel: 'Telefone',
      emailLabel: 'Email',
      hoursLabel: 'Horário de funcionamento',
      afterHours: 'Está disponível apoio de tradução urgente fora do horário de expediente.',
      workingHours: 'Dias úteis 09:00 - 18:00 | Serviço fora do horário disponível',
    },
  },

  home: {
    seo: {
      title: 'TercümExpert — Serviços de Tradução Profissional',
      description:
        'Soluções de tradução ajuramentada, certificação notarial e tradução para empresas. Carregue o seu documento, obtenha um orçamento preliminar imediato e uma entrega profissional.',
    },
    hero: {
      title: 'O Seu Parceiro de Confiança em Serviços',
      titleAccent: 'de Tradução Profissional',
      subtitle: 'Carregue o seu documento, veja o preço e receba uma entrega profissional.',
      support: 'Tradução ajuramentada • Certificação notarial • Soluções para empresas',
    },
    trust: {
      title: 'Porque confiam em nós?',
      items: [
        { key: 'languages', label: 'Mais de 50 idiomas' },
        { key: 'delivery', label: 'Entrega em 24 horas' },
        { key: 'notary', label: 'Certificação notarial' },
        { key: 'quality', label: 'Garantia de qualidade' },
      ],
    },
    stats: {
      title: 'A TercümExpert em números',
      note: 'Os números abaixo não são apresentados como afirmações definitivas até serem confirmados.',
      labels: {
        satisfaction: 'Satisfação dos clientes',
        completed: 'Trabalhos concluídos',
        languages: 'Idiomas suportados',
        corporate: 'Clientes empresariais',
      },
    },
    howItWorks: {
      title: 'Como funciona?',
      subtitle: 'Tradução profissional em cinco passos.',
      steps: [
        { key: 'upload', title: 'Carregar', desc: 'Carregue o seu documento em segurança.' },
        { key: 'select', title: 'Selecionar', desc: 'Escolha o idioma e o tipo de serviço.' },
        { key: 'confirm', title: 'Confirmar', desc: 'Confirme a sua encomenda.' },
        { key: 'track', title: 'Acompanhar', desc: 'Acompanhe o processo em tempo real.' },
        { key: 'receive', title: 'Receber', desc: 'Receba a sua entrega profissional.' },
      ],
    },
    services: {
      title: 'Os nossos serviços',
      subtitle: 'Tradução especializada para todos os tipos de documento.',
    },
    why: {
      title: 'Porquê a TercümExpert?',
      subtitle: 'As características que nos distinguem da concorrência',
      features: [
        { key: 'autoQuote', title: 'Cálculo automático do preço', desc: 'Um preço preliminar em segundos.' },
        { key: 'whatsapp', title: 'Orçamento rápido por WhatsApp', desc: 'Contacto com um único toque.' },
        { key: 'terminology', title: 'Gestão de terminologia', desc: 'Linguagem corporativa e consistente.' },
        { key: 'revision', title: 'Direito a revisão', desc: 'Um processo centrado na satisfação.' },
        { key: 'languages', title: 'Mais de 50 idiomas', desc: 'Ampla cobertura de pares de línguas.' },
        { key: 'terms', title: 'Sistema de crédito para empresas', desc: 'Pagamento flexível para empresas.' },
      ],
    },
    corporateCta: {
      title: 'Soluções para empresas',
      desc: 'Serviços linguísticos profissionais com gestão de terminologia, opções de crédito e um gestor de conta dedicado, adaptados à sua empresa.',
      action: 'Pedir orçamento para empresas',
    },
    partnershipTeaser: {
      title: 'Programa de parcerias',
      subtitle: 'Ganhe 20% de comissão por cada cliente que nos referenciar.',
      items: [
        { key: 'commission', title: 'Comissão transparente', desc: '20% de comissão por cada referência (sujeito a acordo). Ganhos transparentes com um painel de acompanhamento em tempo real.' },
        { key: 'qr', title: 'Sistema de código QR', desc: 'Acompanhamento fácil de clientes com integração em cartão de visita. Códigos QR para web e WhatsApp.' },
      ],
      cta: 'Candidatar-se como parceiro',
    },
    testimonials: {
      title: 'Avaliações de clientes',
      subtitle: 'Serão adicionadas aqui avaliações reais de clientes antes do lançamento.',
      placeholderNote: 'Marcador de posição — serão integradas avaliações reais.',
      items: [
        { key: 't1', role: 'Escritório de advogados' },
        { key: 't2', role: 'Instituição de saúde' },
        { key: 't3', role: 'Cliente empresarial' },
        { key: 't4', role: 'Cliente particular' },
      ],
    },
    blogTeaser: {
      title: 'Blogue',
      subtitle: 'Conteúdos atuais do mundo da tradução',
      viewAll: 'Ver todos os artigos do blogue',
    },
    finalCta: {
      title: 'Comece já',
      desc: 'Carregue os seus documentos, obtenha um orçamento imediato e beneficie de serviços de tradução profissional.',
      primary: 'Obter orçamento',
      secondary: 'Contacte-nos',
    },
  },

  services: {
    seo: {
      title: 'Serviços de tradução',
      description:
        'Tradução ajuramentada, com certificação notarial, jurídica, técnica, médica e académica, além de localização web/móvel. Tipos de documento, processo, entrega e pares de línguas.',
    },
    hero: {
      title: 'Serviços de tradução',
      subtitle: 'Tradução com a terminologia correta para cada área de especialização.',
    },
    process: {
      title: 'Como funciona o processo?',
      steps: [
        { title: 'Análise do documento', desc: 'Avaliam-se o tipo e a finalidade do documento.' },
        { title: 'Atribuição de especialista', desc: 'É atribuído um tradutor especializado na área.' },
        { title: 'Tradução e edição', desc: 'Tradução e revisão final independente.' },
        { title: 'Aprovação e entrega', desc: 'Certificação notarial/apostila, se necessário, e depois entrega.' },
      ],
    },
    delivery: {
      title: 'Opções de entrega',
      items: ['Entrega digital (PDF/DOCX)', 'Entrega física do documento', 'Entrega urgente'],
    },
    notaryApostille: {
      title: 'Relação entre certificação notarial e apostila',
      desc: 'Quando necessário, a tradução ajuramentada torna-se válida para instituições oficiais através da certificação notarial e do processo de apostila. O requisito exato depende da instituição à qual o documento será apresentado.',
    },
    fullService: {
      title: 'Chave na mão, entregue à sua porta',
      note: 'Envie-nos os seus documentos e nós tratamos de todo o processo — tradução, certificação notarial e apostila incluídas. Os seus documentos finalizados chegam à sua porta por correio expresso. Concentre-se no seu trabalho e deixe o resto connosco.',
    },
    cta: {
      title: 'Não tem a certeza de qual serviço precisa?',
      desc: 'Carregue o seu documento e mostramos-lhe o serviço e o preço mais adequados.',
    },
    documentTypesTitle: 'Tipos de documento adequados',
  },

  serviceItems: {
    sworn: {
      name: 'Tradução ajuramentada',
      short: 'Tradução oficialmente válida com a assinatura e o carimbo de um tradutor ajuramentado.',
      benefits: ['Válida em instituições oficiais', 'Aprovação de tradutor ajuramentado', 'Processo rápido'],
    },
    notarized: {
      name: 'Tradução com certificação notarial',
      short: 'Certificação notarial de uma tradução ajuramentada.',
      benefits: ['Certificação notarial', 'Adequada a processos oficiais', 'Tratamos do processo'],
    },
    apostille: {
      name: 'Apoio ao processo de apostila',
      short: 'Orientação no processo de apostila para validade no estrangeiro.',
      benefits: ['Validade internacional', 'Consultoria no processo', 'Orientação institucional'],
    },
    legal: {
      name: 'Tradução jurídica',
      short: 'Tradução com domínio da terminologia para contratos, tribunais e documentos oficiais.',
      benefits: ['Terminologia jurídica', 'Garantia de confidencialidade', 'Tradutor especializado'],
    },
    technical: {
      name: 'Tradução técnica',
      short: 'Tradução consistente para manuais, especificações e documentos técnicos.',
      benefits: ['Gestão de terminologia', 'Formato preservado', 'Especialização setorial'],
    },
    medical: {
      name: 'Tradução médica',
      short: 'Tradução rigorosa para relatórios, folhetos informativos e documentos médicos.',
      benefits: ['Terminologia médica', 'Centrada no rigor', 'Confidencialidade'],
    },
    academic: {
      name: 'Tradução académica',
      short: 'Linguagem académica para teses, artigos e traduções de diplomas.',
      benefits: ['Estilo académico', 'Consistência com a fonte', 'Entrega dentro do prazo'],
    },
    localization: {
      name: 'Localização web e móvel',
      short: 'Localização culturalmente adequada de sites e aplicações.',
      benefits: ['Adaptação cultural', 'Integração técnica', 'Compatibilidade com SEO'],
    },
  },

  corporate: {
    statsLabels: {
      corporate: 'Clientes empresariais',
      discount: 'Desconto para encomendas em volume',
      term: 'Prazo de pagamento',
    },
    seo: {
      title: 'Soluções para empresas',
      description:
        'Serviços linguísticos profissionais para empresas com gestão de terminologia, opções de crédito, encomendas em volume e um gestor de conta dedicado.',
    },
    hero: {
      title: 'Soluções para empresas',
      subtitle:
        'Serviços linguísticos profissionais com gestão de terminologia, opções de crédito e um gestor de conta dedicado, adaptados à sua empresa.',
      primaryCta: 'Pedir orçamento para empresas',
      secondaryCta: 'Enviar email',
    },
    features: {
      title: 'Funcionalidades para empresas',
      subtitle: 'Soluções adaptadas ao seu negócio',
      items: [
        {
          key: 'custom',
          icon: 'Target',
          title: 'Serviço personalizado',
          points: ['Terminologia fixa', 'Preservação do tom de voz da marca', 'Gestor de conta dedicado', 'Criação de guia de estilo'],
        },
        {
          key: 'volume',
          icon: 'BarChart3',
          title: 'Processamento em volume e crédito',
          points: ['Planos mensais de tradução', 'Descontos para encomendas em volume', 'Crédito até 30 dias', 'Sistema de faturação'],
        },
        {
          key: 'security',
          icon: 'Lock',
          title: 'Privacidade e segurança',
          points: ['Protocolo NDA', 'Transferência de ficheiros encriptada', 'Processos em conformidade com a KVKK'],
        },
      ],
    },
    whyPackage: {
      title: 'Porquê um pacote empresarial?',
      items: [
        {
          key: 'terminology',
          icon: 'Building2',
          title: 'Gestão de terminologia fixa',
          desc: 'Criamos um banco de termos específico para a sua empresa. A linguagem da sua marca é preservada em todas as traduções e asseguramos a consistência. Temos o cuidado de utilizar os mesmos termos em cada projeto.',
        },
        {
          key: 'manager',
          icon: 'Users',
          title: 'Gestor de conta dedicado',
          desc: 'O seu gestor de conta dedicado acompanha todos os seus processos. Com uma linha de apoio acessível, estamos ao seu lado em situações urgentes.',
        },
        {
          key: 'security',
          icon: 'ShieldCheck',
          title: 'Privacidade e segurança',
          desc: 'Trabalhamos ao abrigo de um protocolo NDA. Os seus dados estão seguros com uma infraestrutura de segurança robusta, transferência de ficheiros encriptada e processos em conformidade com a KVKK.',
        },
      ],
    },
    payment: {
      title: 'Opções de pagamento',
      subtitle: 'Planos de pagamento flexíveis adequados ao seu negócio',
      recommendedLabel: 'RECOMENDADO',
      options: [
        {
          key: 'standard',
          label: 'Pagamento imediato',
          heading: 'Padrão',
          desc: 'Pagamento por cartão de crédito ou transferência bancária após cada encomenda',
          points: ['Pagamento a prestações com cartão de crédito', 'Entrega imediata'],
          recommended: false,
        },
        {
          key: 'term',
          label: 'Crédito mensal',
          heading: '15-30 dias',
          desc: 'Faturação mensal consolidada e opção de crédito',
          points: ['Crédito a 30 dias', 'Desconto para volume', 'Relatório mensal'],
          recommended: true,
        },
      ],
    },
    form: {
      title: 'Candidatura a pacote empresarial',
      desc: 'Preencha o formulário e a nossa equipa especializada entrará em contacto consigo',
      fields: {
        company: 'Nome da empresa',
        contactName: 'Nome completo do contacto',
        email: 'Email',
        phone: 'Telefone',
        need: 'Fale-nos das suas necessidades de tradução',
        consent: 'Li e aceito a <kvkk>Declaração de Esclarecimento da KVKK</kvkk>.',
      },
      submit: 'Enviar candidatura',
      success: 'A sua candidatura foi recebida. Entraremos em contacto consigo o mais rapidamente possível.',
      note: 'Entraremos em contacto consigo no prazo de 1 dia útil.',
    },
  },

  partnership: {
    seo: {
      title: 'Programa de parcerias',
      description:
        'Ganhe comissão por cada cliente que referenciar. Relatórios transparentes, referências por código QR e apoio profissional.',
    },
    hero: {
      title: 'Programa de parcerias',
      value: 'Ganhe 20% de comissão por cada cliente que nos referenciar.',
      subtitle: 'Um sistema transparente, pagamentos fiáveis e cooperação a longo prazo.',
      cta: 'Candidatar-se agora',
    },
    advantages: {
      title: 'Vantagens para parceiros',
      subtitle: 'Porquê tornar-se parceiro da TercümExpert?',
      items: [
        { key: 'commission', icon: 'Wallet', title: 'Garantia de 20% de comissão', desc: 'Um sistema de comissões transparente por cada cliente que referenciar.' },
        { key: 'qr', icon: 'QrCode', title: 'Referência por código QR', desc: 'Acompanhamento fácil de clientes com integração em cartão de visita.' },
        { key: 'reporting', icon: 'BarChart3', title: 'Relatórios transparentes', desc: 'Painel de acompanhamento de comissões e clientes em tempo real.' },
        { key: 'support', icon: 'Users', title: 'Apoio profissional', desc: 'Uma linha de apoio a parceiros dedicada e um gestor de conta.' },
      ],
    },
    howItWorks: {
      title: 'Como funciona?',
      steps: [
        { title: 'Candidatar-se', desc: 'Preencha o formulário de candidatura online. Partilhe os dados da sua empresa e os seus contactos. A sua candidatura é analisada no prazo de 1 dia útil.' },
        { title: 'Tornar-se parceiro', desc: 'Assim que a sua candidatura for aprovada, obtém acesso ao seu painel de parceiro dedicado. Os seus códigos QR e ligações de referência ficam prontos.' },
        { title: 'Referenciar clientes', desc: 'Referencie os seus clientes através de código QR, de uma ligação personalizada ou de cartão de visita. Cada referência é registada automaticamente no sistema.' },
        { title: 'Ganhar comissão', desc: 'Ganha 20% de comissão sempre que um cliente que referenciou efetua uma encomenda. Recebe pagamentos automáticos a cada 15 dias.' },
      ],
    },
    sectors: {
      title: 'Setores-alvo',
      subtitle: 'Para que setores é ideal?',
      items: [
        { key: 'law', icon: 'Scale', title: 'Escritórios de advogados', desc: 'Necessidade de tradução ajuramentada de processos, contratos e documentos jurídicos.' },
        { key: 'visa', icon: 'Plane', title: 'Consultoria de vistos', desc: 'Documentos que exigem tradução ajuramentada, como passaportes, diplomas e registos civis.' },
        { key: 'education', icon: 'GraduationCap', title: 'Consultoria educativa', desc: 'Tradução ajuramentada de documentos de estudantes e processos de apostila.' },
        { key: 'health', icon: 'HeartPulse', title: 'Turismo de saúde', desc: 'Tradução de relatórios médicos, processos de doentes e documentos de saúde.' },
        { key: 'patent', icon: 'Building2', title: 'Gabinetes de patentes/marcas', desc: 'Tradução técnica de patentes, registos de marcas e documentos jurídicos.' },
        { key: 'realestate', icon: 'Home', title: 'Agências imobiliárias', desc: 'Tradução de títulos de propriedade, contratos e documentos oficiais para investidores estrangeiros.' },
        { key: 'hr', icon: 'Briefcase', title: 'Consultoria de recursos humanos', desc: 'Tradução de CV, diplomas e cartas de recomendação para colocação no estrangeiro.' },
        { key: 'software', icon: 'Code', title: 'Empresas de software', desc: 'Localização de aplicações web e móveis e tradução de documentação técnica.' },
      ],
    },
    commission: {
      title: 'Estrutura de comissões',
      stats: {
        commissionLabel: 'Comissão padrão',
        commissionSub: 'Por cada encomenda',
        periodUnit: 'Dias',
        periodLabel: 'Período de pagamento',
        feeLabel: 'Taxa de adesão',
        feeSub: 'Totalmente gratuita',
      },
      exampleTitle: 'Exemplo de cálculo de ganhos',
      exampleOrderLabel: 'Encomenda do cliente que referenciou',
      exampleRateLabel: 'Taxa de comissão',
      exampleEarningLabel: 'Os seus ganhos',
      note: 'As taxas de comissão e as condições estão sujeitas ao acordo de parceria.',
    },
    form: {
      title: 'Formulário de candidatura a parceiro',
      subtitle: 'Preencha o formulário e entraremos em contacto consigo no prazo de 1 dia útil.',
      fields: {
        company: 'Nome da empresa/organização',
        sector: 'Setor',
        contactName: 'Nome completo do contacto',
        titleRole: 'Cargo',
        email: 'Email',
        phone: 'Telefone',
        potential: 'A sua estimativa mensal de potencial de referências',
        note: 'Notas que gostaria de acrescentar',
        agreement: 'Li e aceito os termos do <partnership>acordo de parceria</partnership>.',
      },
      sectorPlaceholder: 'Selecionar',
      sectorOptions: ['Escritório de advogados', 'Consultoria de vistos', 'Consultoria educativa', 'Turismo de saúde', 'Gabinete de patentes/marcas', 'Imobiliário', 'Consultoria de recursos humanos', 'Software', 'Outro'],
      potentialOptions: ['1-5 clientes', '5-10 clientes', '10-20 clientes', 'Mais de 20 clientes'],
      submit: 'Enviar candidatura',
      success: 'A sua candidatura foi recebida. Entraremos em contacto consigo.',
      note: 'A sua candidatura será analisada no prazo de 1 dia útil.',
    },
  },

  quote: {
    "areas": {
      "academic": "Tradução académica",
      "legal": "Tradução jurídica",
      "official": "Tradução de documentos oficiais",
      "medical": "Tradução médica",
      "technical": "Tradução técnica",
      "commercial": "Tradução comercial e financeira",
      "localization": "Localização web e móvel",
      "literary": "Tradução literária",
      "general": "Tradução geral / outra"
    },
    "docTypes": {
      "diploma": "Diploma",
      "transcript": "Histórico académico",
      "student-certificate": "Declaração de matrícula",
      "diploma-supplement": "Suplemento ao diploma",
      "thesis": "Tese",
      "reference-letter": "Carta de recomendação",
      "academic-article": "Artigo académico",
      "contract": "Contrato",
      "court-decision": "Decisão judicial",
      "power-of-attorney": "Procuração",
      "petition": "Petição",
      "consent-statement": "Declaração de consentimento",
      "warning-notice": "Notificação de advertência",
      "litigation-doc": "Documentos processuais",
      "passport": "Passaporte",
      "id-card": "Cartão de cidadão",
      "civil-registry": "Certidão do registo civil",
      "birth-certificate": "Certidão de nascimento",
      "marriage-certificate": "Certidão de casamento",
      "driver-license": "Carta de condução",
      "criminal-record": "Registo criminal",
      "military-status": "Documento de situação militar",
      "medical-report": "Relatório médico",
      "epicrisis": "Epícrise (relatório de alta)",
      "prescription": "Receita médica",
      "lab-result": "Resultado de análises / exames",
      "medical-article": "Artigo médico",
      "patient-consent": "Formulário de consentimento do doente",
      "user-manual": "Manual do utilizador",
      "technical-spec": "Especificação técnica",
      "patent": "Patente",
      "product-catalog": "Catálogo de produtos",
      "datasheet": "Ficha técnica",
      "installation-guide": "Guia de instalação",
      "safety-data-sheet": "Ficha de dados de segurança",
      "invoice": "Fatura",
      "balance-sheet": "Balanço",
      "commercial-contract": "Contrato comercial",
      "financial-report": "Relatório financeiro",
      "tax-document": "Documento fiscal",
      "activity-certificate": "Certidão de atividade",
      "bank-statement": "Extrato bancário",
      "website": "Website",
      "mobile-app": "Aplicação móvel",
      "software-ui": "Interface de software",
      "game": "Jogo",
      "marketing-content": "Conteúdo de marketing",
      "subtitle": "Legendas",
      "e-commerce": "Conteúdo de comércio eletrónico",
      "book": "Livro",
      "short-story": "Conto",
      "poem": "Poema",
      "screenplay": "Argumento",
      "essay": "Ensaio",
      "article": "Artigo",
      "general-document": "Documento geral",
      "correspondence": "Correspondência / carta",
      "cv": "Curriculum vitae (CV)",
      "presentation": "Apresentação",
      "other": "Outro"
    },
    seo: {
      title: 'Cálculo de preço imediato',
      description: 'Carregue o seu documento ou introduza os dados e obtenha o seu orçamento preliminar imediato.',
    },
    hero: {
      title: 'Cálculo de preço imediato',
      subtitle: 'Carregue o seu documento ou introduza os dados e obtenha um orçamento preliminar imediato.',
    },
    upload: {
      heading: 'Carregue os seus documentos',
      privacy: 'Os seus dados são mantidos confidenciais',
      tabFile: 'Carregar ficheiro',
      tabText: 'Introduzir texto',
      chooseFile: 'Escolha os seus documentos',
      formats: '.docx, .xlsx, .pdf, .pptx, .jpg, .png e mais de 50 formatos aceites · Máx. 100MB por ficheiro',
      dropHint: 'Pode arrastar e largar um ou mais ficheiros nesta área.',
      textPlaceholder: 'Cole ou escreva o seu texto aqui…',
      totalWords: 'Contagem total de palavras',
      extracting: 'A contar palavras…',
      wordsUnit: 'palavras',
      remove: 'Remover',
      unsupported:
        'Não foi possível contar automaticamente as palavras deste tipo de ficheiro. Cole o texto em "Introduzir texto"; a contagem será verificada pela nossa equipa ao elaborar o orçamento.',
      empty:
        'Não foi encontrado texto selecionável no ficheiro (pode ser digitalizado/uma imagem). Utilize "Introduzir texto" ou a contagem será verificada durante a elaboração do orçamento.',
      error: 'Não foi possível ler o ficheiro. Tente novamente ou utilize "Introduzir texto".',
      tooLarge: 'O ficheiro não pode ter mais de 100MB.',
      needInput: 'Para obter um preço, carregue um ficheiro ou introduza texto.',
    },
    fields: {
      upload: 'Carregar documento (opcional)',
      uploadHint: 'PDF, DOC, DOCX ou TXT — máx. 10 MB',
      sourceLang: 'Idioma de origem',
      targetLang: 'Idioma de destino',
      serviceType: 'Tipo de serviço',
      documentType: 'Tipo de documento',
      wordCount: 'Contagem estimada de palavras',
      wordCountHint: 'Utilize o cursor ou introduza o número manualmente.',
      options: 'Opções adicionais',
      calculate: 'Calcular preço',
    },
    options: {
      "sworn": "Tradução ajuramentada (certificada)",
      "apostille": "Apoio no processo de apostila",
      "swornNotaryHint": "A certificação notarial já abrange a tradução ajuramentada; basta selecionar a única opção que se adequa à sua necessidade.",
      "physicalRequiredHint": "As traduções ajuramentadas e notariais são entregues como originais assinados/carimbados, pelo que a entrega física é adicionada automaticamente.",
      urgent: 'Entrega urgente',
      notarization: 'Certificação notarial',
      physicalDelivery: 'Entrega física',
    },
    languages: {
      tr: 'Turco',
      en: 'Inglês',
      de: 'Alemão',
      fr: 'Francês',
      es: 'Espanhol',
      it: 'Italiano',
      ru: 'Russo',
      ar: 'Árabe',
      nl: 'Neerlandês',
      az: 'Azerbaijano',
      pl: 'Polaco',
      bg: 'Búlgaro',
      pt: 'Português',
      da: 'Dinamarquês',
    },
    documentTypes: {
      diploma: 'Diploma',
      passport: 'Passaporte',
      'civil-registry': 'Certidão do registo civil',
      contract: 'Contrato',
      'medical-report': 'Relatório médico',
      'technical-doc': 'Documento técnico',
      'court-doc': 'Documento judicial',
      other: 'Outro',
    },
    result: {
      title: 'Orçamento preliminar',
      basePrice: 'Taxa base do serviço',
      wordPrice: 'Taxa por palavra',
      addons: 'Serviços adicionais',
      total: 'Total',
      vat: 'IVA',
      delivery: 'Prazo de entrega estimado',
      deliveryUnit: 'dias úteis',
      disclaimer: 'Este é um orçamento preliminar; o preço final é confirmado após a análise do documento.',
      order: 'Efetuar encomenda',
      whatsapp: 'Contactar por WhatsApp',
      estimatedWords: 'Palavras estimadas (automático — demonstração)',
    },
    orderConfirm: {
      title: 'A sua encomenda foi recebida',
      number: 'N.º da encomenda',
      desc: 'O seu pedido e documentos foram guardados. A nossa equipa especializada analisará o documento e entrará em contacto consigo o mais rapidamente possível.',
      viewOrders: 'As minhas encomendas',
      submitting: 'A criar encomenda…',
      error: 'Ocorreu um problema ao criar a sua encomenda. Tente novamente.',
    },
    gate: {
      title: 'O seu preço está pronto',
      subtitle: 'Inicie sessão ou confirme os seus dados para ver o preço e efetuar uma encomenda.',
      loginCta: 'Iniciar sessão / Registar',
      or: 'ou continue rapidamente',
      firstName: 'Nome próprio',
      lastName: 'Apelido',
      email: 'Email',
      phone: "Número de telefone",
      sendCode: 'Enviar código de verificação',
      codeLabel: 'Código de verificação',
      codeSentA: 'recebeu um código de verificação.',
      verify: 'Verificar e ver o preço',
      resend: 'Reenviar código',
      resent: 'Foi enviado um novo código.',
      back: 'Alterar dados',
      errNames: 'O nome próprio e o apelido são obrigatórios.',
      errEmail: 'Introduza um email válido.',
      errPhone: "Introduza um número de telefone válido.",
      errCode: 'Introduza o código completo.',
      note: 'O seu email é utilizado apenas para o orçamento e a encomenda.',
    },
    note: {
      label: 'Nota sobre a sua encomenda (opcional)',
      placeholder: 'Pode escrever aqui os seus pedidos de entrega, terminologia ou pedidos especiais.',
    },

    checkout: {
      "selectCountry": "Selecione o país",
      "selectCity": "Selecione a cidade / distrito",
      "cityNeedsCountry": "Selecione primeiro um país",
      title: "Detalhes de entrega",
      subtitle: "O seu documento físico/ajuramentado será enviado para esta morada.",
      firstName: "Nome próprio",
      lastName: "Apelido",
      phone: "Telefone",
      address: "Morada completa",
      addressPlaceholder: "Rua, número do edifício e do apartamento…",
      city: "Cidade",
      postalCode: "Código postal",
      country: "País",
      submit: "Concluir encomenda",
      submitting: "A criar a encomenda…",
      cancel: "Cancelar",
      errRequired: "Preencha os campos obrigatórios.",
      note: "Estas informações são utilizadas apenas para a entrega por correio.",
    },
  },

  order: {
      "trackingCodeLabel": "Número de seguimento",
    seo: {
      title: 'Acompanhamento da encomenda',
      description: 'Acompanhe o estado da sua encomenda.',
    },
    numberLabel: 'N.º da encomenda',
    placedOn: 'Data da encomenda',
    estimatedLabel: 'Entrega estimada da tradução',
    cargoEstimatedLabel: 'Data de envio estimada',
    timelineTitle: 'Estado da encomenda',
    steps: {
      received: 'A sua encomenda foi recebida',
      in_progress: 'Em curso',
      translated: 'Tradução concluída',
      shipped: 'Enviada',
      delivered: 'Entregue',
      cancelled: 'Encomenda cancelada',
    },
    stepDesc: {
      received: 'O seu pedido e documentos chegaram ao nosso sistema. A nossa equipa especializada irá analisá-lo e começar em breve.',
      in_progress: 'O nosso tradutor especializado iniciou a sua tradução.',
      translated: 'A sua tradução está concluída e as verificações finais foram efetuadas.',
      shipped: 'O seu documento foi entregue ao correio expresso; pode acompanhá-lo com o botão abaixo.',
      delivered: 'O seu documento foi-lhe enviado por email.',
      cancelled: 'Esta encomenda foi cancelada. Contacte-nos caso tenha alguma questão.',
    },
    cargoReady: 'O seu documento foi enviado. Acompanhe-o com um toque:',
    cargoPending: 'O código de acompanhamento aparecerá aqui assim que o seu documento for enviado.',
    trackCargo: 'Acompanhar o meu envio',
    digitalPending: 'Assim que a sua tradução estiver concluída, os seus ficheiros ser-lhe-ão enviados por email.',
    digitalDelivered: 'A sua tradução foi-lhe enviada por email. Verifique a sua caixa de entrada (e a pasta de spam).',
    detailsTitle: 'Detalhes da encomenda',
    fields: {
      service: 'Serviço',
      langs: 'Idiomas',
      documentType: 'Tipo de documento',
      words: 'Palavras',
      delivery: 'Prazo estimado',
      total: 'Montante',
      note: 'A sua nota',
      deliveryAddress: "Morada de entrega",
    },
    myOrders: 'As minhas encomendas',
    backHome: 'Voltar ao início',
    whatsapp: 'Contactar por WhatsApp',
    loading: 'A carregar encomenda…',
    loginRequired: {
      title: 'Inicie sessão para ver a sua encomenda',
      desc: 'Só pode aceder aos detalhes da sua encomenda depois de iniciar sessão com a sua conta.',
      login: 'Iniciar sessão',
    },

    notFound: {
      title: 'Encomenda não encontrada',
      desc: 'Este número de encomenda não lhe pertence ou não existe. Verifique a ligação.',
      home: 'Voltar ao início',
    },
  },

  faq: {
    seo: {
      title: 'Perguntas frequentes',
      description: 'Perguntas frequentes sobre tradução ajuramentada, prazo de entrega, preços, certificação notarial e crédito para empresas.',
    },
    hero: { title: 'Perguntas frequentes', subtitle: 'A resposta que procura está aqui.' },
    categoriesTitle: 'Categorias',
    searchPlaceholder: 'Pesquise perguntas ou palavras-chave…',
    empty: 'Nenhuma pergunta corresponde à sua pesquisa. Experimente outra palavra ou contacte-nos.',
    categories: FAQ_CATEGORIES_PT,
    items: FAQ_ITEMS_PT,
    notFound: {
      title: 'Não encontrou a resposta à sua pergunta?',
      contact: 'Contacte-nos',
      whatsapp: 'Apoio por WhatsApp',
    },
  },

  contact: {
      introTitle: `Bem-vindo`,
      introDesc: `Antes de começarmos, poderia indicar-me o seu nome e o seu endereço de e-mail para que o possa ajudar melhor?`,
      start: `Iniciar conversa`,
      introError: `Por favor, introduza o seu nome e o seu endereço de e-mail.`,
    seo: {
      title: 'Contacto',
      description: 'Entre em contacto com a TercümExpert: telefone, email, WhatsApp e formulário de contacto.',
    },
    hero: { title: 'Contacto', subtitle: 'Como o podemos ajudar?' },
    infoTitle: 'Informações de contacto',
    labels: {
      phone: 'Telefone',
      email: 'Email',
      whatsapp: 'WhatsApp',
      address: 'Morada',
      hours: 'Horário de funcionamento',
    },
    form: {
      title: 'Contacte-nos',
      fields: {
        name: 'Nome completo',
        email: 'Email',
        phone: 'Telefone',
        subject: 'Assunto',
        message: 'Mensagem',
        consent: 'Li e aceito a <kvkk>Declaração de Esclarecimento da KVKK</kvkk>.',
      },
      submit: 'Enviar mensagem',
      success: 'A sua mensagem foi recebida. Entraremos em contacto consigo em breve.',
    },
    map: {
      title: 'A nossa localização',
      subtitle: 'Encontre-nos no mapa',
      placeholder: 'Área do mapa',
      note: 'O mapa da localização será apresentado aqui em breve.',
    },
  },

  auth: {
    seo: {
      title: 'Iniciar sessão / Registar',
      description: 'Inicie sessão na sua conta TercümExpert ou crie uma nova.',
    },
    tabs: { login: 'Iniciar sessão', register: 'Registar' },
    google: 'Continuar com o Google',
    or: 'ou',
    fields: {
      firstName: 'Nome próprio',
      lastName: 'Apelido',
      email: 'Email',
      password: 'Palavra-passe',
      code: 'Código de verificação',
    },
    login: {
      title: 'Inicie sessão na sua conta',
      submit: 'Iniciar sessão',
      noAccount: 'Ainda não tem conta?',
      switchToRegister: 'Registar',
    },
    register: {
      title: 'Criar uma nova conta',
      submit: 'Registar',
      haveAccount: 'Já tem conta?',
      switchToLogin: 'Iniciar sessão',
      consent: 'Ao criar uma conta, aceito a <kvkk>Declaração de Esclarecimento da KVKK</kvkk> e a <privacy>Política de Privacidade</privacy>.',
    },
    verify: {
      title: 'Verifique o seu email',
      desc: '— introduza o código de 6 dígitos que enviámos para este endereço.',
      submit: 'Verificar e continuar',
      spam: 'O código pode demorar alguns minutos; verifique também a sua pasta de spam/lixo.',
      resend: 'Reenviar código',
      resent: 'Foi enviado um novo código.',
      back: 'Voltar',
    },
    signedIn: {
      title: 'A minha conta',
      greeting: 'Bem-vindo',
      logout: 'Terminar sessão',
    },
    orders: {
      title: 'As minhas encomendas',
      empty: 'Ainda não tem encomendas. Pode criar a sua primeira encomenda a partir de Calcular preço.',
      loading: 'A carregar encomendas…',
      error: 'Não foi possível carregar as encomendas. Atualize a página.',
      status: {
        received: 'Recebida',
        in_progress: 'Em curso',
        translated: 'Tradução concluída',
        shipped: 'Enviada',
        delivered: 'Entregue',
        cancelled: 'Cancelada',
      },
      track: 'Acompanhar',
    },
    errors: {
      nameRequired: 'O nome próprio e o apelido são obrigatórios.',
      emailInvalid: 'Introduza um email válido.',
      passwordShort: 'A palavra-passe deve ter, no mínimo, 6 caracteres.',
      codeInvalid: 'Introduza o código de 6 dígitos.',
      consentRequired: 'É necessária a aceitação para continuar.',
    },
  },

  blog: {
    seo: { title: 'Blogue', description: 'Conteúdos de orientação sobre tradução, certificação notarial, apostila e localização.' },
    hero: { title: 'Blogue', subtitle: 'Guias do mundo da tradução.' },
    searchPlaceholder: 'Pesquisar artigos…',
    readingTime: 'min de leitura',
    relatedTitle: 'Artigos relacionados',
    allCategories: 'Todas',
    empty: 'Nenhum artigo corresponde a este critério.',
  },

  legal: {
    lastUpdatedLabel: `Última atualização`,
    draftNotice: `No texto que se segue, os campos assinalados entre parênteses retos ([...]) deverão ser preenchidos com os dados da sua empresa. Os textos têm caráter meramente informativo e recomenda-se a sua revisão por um jurista antes da publicação.`,
    kvkk: {
      seo: { title: `Aviso de Informação KVKK`, description: `Aviso de informação relativo ao tratamento dos seus dados pessoais no âmbito da Lei KVKK n.º 6698.` },
      title: `Aviso de Informação KVKK`,
      sections: [
        { heading: `Responsável pelo Tratamento`, body: `Nos termos da Lei n.º 6698 sobre a Proteção de Dados Pessoais (“KVKK”), os seus dados pessoais são tratados, na qualidade de responsável pelo tratamento, por [ŞİRKET ÜNVANI] (“TercümExpert”), no âmbito adiante descrito. Morada: [ADRES]. Correio eletrónico: [E-POSTA]. Telefone: [TELEFON].` },
        { heading: `Dados Pessoais Tratados`, body: `São tratados os seus dados de identificação e de contacto (nome, apelido, endereço de correio eletrónico, número de telefone), os dados da morada de entrega, os dados de encomendas e transações, os dados contidos nos documentos que nos remete para efeitos de tradução, bem como os dados de segurança das operações relativos à sua utilização do sítio (endereço IP, registos de sessão e de cookies).` },
        { heading: `Finalidades do Tratamento`, body: `Os seus dados pessoais são tratados para as seguintes finalidades: a prestação de serviços de tradução, tradução ajuramentada, reconhecimento notarial e apostila; a elaboração de orçamentos e a gestão de encomendas; a gestão das relações com os clientes e o tratamento de pedidos e reclamações; o cumprimento de obrigações contratuais e legais; e a garantia da segurança do serviço.` },
        { heading: `Fundamentos Jurídicos do Tratamento`, body: `Os seus dados são tratados com base nos seguintes fundamentos jurídicos: a necessidade para a celebração ou execução de um contrato, o cumprimento das nossas obrigações legais, o exercício e a defesa de um direito e os nossos interesses legítimos, desde que não prejudiquem os seus direitos e liberdades fundamentais; e, nos casos em que tal seja necessário, com base no seu consentimento expresso (KVKK m.5 e m.6).` },
        { heading: `Método de Recolha`, body: `Os seus dados pessoais são recolhidos por meios eletrónicos, através dos formulários do sítio Web, dos processos de registo e de encomenda, do correio eletrónico e de outros canais de comunicação.` },
        { heading: `Transferência de Dados Pessoais`, body: `Na medida exigida pela prestação do serviço, os seus dados podem ser transferidos para os nossos fornecedores situados no país e no estrangeiro dos quais recebemos serviços de alojamento, infraestrutura, autenticação, correio eletrónico e análise, bem como para as autoridades e organismos públicos competentes, em conformidade com os requisitos previstos nos artigos m.8 e m.9 da KVKK. Uma vez que os servidores de alguns dos fornecedores de infraestrutura e de serviços que utilizamos se encontram no estrangeiro, os seus dados podem ser transferidos para fora do país no quadro das garantias previstas na legislação.` },
        { heading: `Prazos de Conservação`, body: `Os seus dados pessoais são conservados durante o período exigido pela finalidade do tratamento e durante os prazos de prescrição e de conservação previstos na legislação aplicável (como a legislação fiscal, comercial e de defesa do consumidor); findos esses prazos, são apagados, destruídos ou anonimizados.` },
        { heading: `Direitos do Titular dos Dados`, body: `Nos termos do artigo m.11 da KVKK, assistem-lhe os seguintes direitos: saber se os seus dados pessoais são ou não tratados; solicitar informações caso o sejam; conhecer a finalidade do tratamento e saber se os dados são utilizados em conformidade com essa finalidade; conhecer os terceiros para quem os dados são transferidos no país ou no estrangeiro; solicitar a retificação dos dados incompletos ou incorretos; solicitar o seu apagamento ou destruição quando se verifiquem os respetivos pressupostos; solicitar que estas operações sejam comunicadas aos terceiros para quem os dados tenham sido transferidos; opor-se à produção de um resultado desfavorável decorrente exclusivamente da análise por sistemas automatizados; e exigir a reparação dos danos em caso de prejuízo.` },
        { heading: `Método de Apresentação de Pedidos`, body: `Pode apresentar os pedidos relativos aos seus direitos, em conformidade com o “Veri Sorumlusuna Başvuru Usul ve Esasları Hakkında Tebliğ”, por escrito, para o endereço [E-POSTA] ou para a morada [ADRES]. O seu pedido será respondido no mais curto prazo possível e, o mais tardar, no prazo de trinta dias, consoante a sua natureza.` },
      ],
    },
    privacy: {
      seo: { title: `Política de Privacidade`, description: `A nossa política relativa à confidencialidade dos seus dados pessoais e dos seus documentos.` },
      title: `Política de Privacidade`,
      sections: [
        { heading: `Introdução`, body: `Na TercümExpert, damos importância à sua privacidade. A presente Política de Privacidade explica quais as informações que recolhemos, para que finalidades e de que forma as protegemos nos serviços que prestamos através de [WEB ADRESİ]. Para informações pormenorizadas sobre o tratamento de dados pessoais, pode consultar o Aviso de Informação KVKK.` },
        { heading: `Informações que Recolhemos`, body: `Podem ser recolhidos por nós os dados de conta e de contacto (nome, apelido, correio eletrónico, telefone), os dados de encomenda e de entrega, os documentos que nos remete para tradução e o respetivo conteúdo, os dados das transações relativas ao pagamento e os dados técnicos relativos à sua utilização do sítio (endereço IP, informação do navegador, registos de cookies).` },
        { heading: `Finalidades de Utilização das Informações`, body: `Utilizamos as suas informações para prestar os serviços, gerir orçamentos e encomendas, comunicar consigo, cumprir as nossas obrigações legais e melhorar a qualidade e a segurança do serviço. Tratamos os seus documentos apenas na medida exigida pelo serviço que solicitou.` },
        { heading: `Confidencialidade dos Documentos`, body: `Os documentos objeto de tradução são tratados como confidenciais. A esses documentos apenas acedem o tradutor e o pessoal autorizado que executam o serviço em causa, durante o período exigido pelo trabalho; os seus documentos não são partilhados com terceiros para finalidades alheias à prestação do serviço.` },
        { heading: `Prestadores de Serviços Terceiros`, body: `Na prestação dos nossos serviços, recorremos a prestadores terceiros de confiança nos domínios do alojamento e da infraestrutura, da autenticação, do envio de correio eletrónico, da análise e (quando ativado) do pagamento. Estes prestadores apenas podem aceder aos seus dados para efeitos da prestação do serviço que lhes é confiado e sob obrigações contratuais de confidencialidade; os servidores de alguns deles podem situar-se no estrangeiro.` },
        { heading: `Segurança dos Dados`, body: `Para proteger os seus dados contra o acesso não autorizado, aplicamos a cifragem na transmissão, restrições de acesso e as medidas administrativas e técnicas adequadas. Embora nenhum método possa garantir uma segurança absoluta, adotamos medidas razoáveis e atualizadas para proteger os seus dados.` },
        { heading: `Cookies`, body: `No nosso sítio são utilizados cookies e tecnologias semelhantes. Para informações pormenorizadas sobre os seus tipos e sobre a gestão de preferências, pode consultar a Política de Cookies.` },
        { heading: `Os Seus Direitos`, body: `Pode exercer os direitos que lhe são conferidos pela KVKK, incluindo o acesso, a retificação e o apagamento dos seus dados pessoais. Para os seus pedidos, pode contactar-nos através do endereço [E-POSTA].` },
        { heading: `Privacidade das Crianças`, body: `Os nossos serviços não se destinam a pessoas com idade inferior a 18 anos e não recolhemos conscientemente dados pessoais de crianças.` },
        { heading: `Alterações`, body: `A presente política pode ser atualizada periodicamente. A versão em vigor é sempre publicada nesta página; em caso de alterações significativas, será prestada informação através dos meios adequados.` },
        { heading: `Contacto`, body: `Para questões relacionadas com a privacidade: Correio eletrónico: [E-POSTA] · Telefone: [TELEFON] · Morada: [ADRES].` },
      ],
    },
    distanceSales: {
      seo: { title: `Contrato de Venda à Distância`, description: `Contrato de venda à distância relativo à venda de serviços no âmbito da Lei n.º 6502.` },
      title: `Contrato de Venda à Distância`,
      sections: [
        { heading: `Partes`, body: `O presente Contrato de Venda à Distância (“Contrato”) é celebrado por meios eletrónicos entre, por um lado, [ŞİRKET ÜNVANI] (“Vendedor”; morada: [ADRES], correio eletrónico: [E-POSTA], telefone: [TELEFON]) e, por outro, o consumidor que efetua a encomenda (“Comprador”), nos termos da Lei n.º 6502 sobre a Proteção do Consumidor e do Mesafeli Sözleşmeler Yönetmeliği.` },
        { heading: `Objeto do Contrato`, body: `O objeto do Contrato é a prestação dos serviços de tradução, tradução ajuramentada, reconhecimento notarial e apostila que o Comprador encomenda por meios eletrónicos através de [WEB ADRESİ], cujas características e preço de venda constam do resumo da encomenda.` },
        { heading: `Características e Preço do Serviço`, body: `O tipo e o âmbito do serviço encomendado, a forma de entrega (digital ou por transportadora) e o preço total, incluindo impostos, são apresentados de forma clara ao Comprador durante a encomenda e constam da confirmação da encomenda. O preço é calculado em função do serviço selecionado e das características dos documentos.` },
        { heading: `Pagamento`, body: `O pagamento é efetuado através dos métodos de pagamento disponibilizados na fase de encomenda. A encomenda é processada após a confirmação do pagamento.` },
        { heading: `Execução e Entrega`, body: `Nas entregas digitais, a tradução é disponibilizada, após a sua conclusão, através da conta ou do endereço de correio eletrónico do Comprador. Nos documentos físicos, com assinatura autógrafa ou ajuramentados, a entrega é efetuada por transportadora para a morada indicada pelo Comprador. Os prazos estimados de entrega são indicados no momento da encomenda e podem variar em função do volume dos documentos e dos processos de reconhecimento.` },
        { heading: `Direito de Livre Resolução`, body: `Em regra, nos contratos relativos à prestação de serviços, o Comprador dispõe do direito de livre resolução no prazo de catorze (14) dias a contar da data de celebração do contrato, sem necessidade de indicar qualquer motivo. Ressalvam-se, contudo, as exceções adiante indicadas.` },
        { heading: `Exceções ao Direito de Livre Resolução`, body: `Nos termos do artigo m.15 do Mesafeli Sözleşmeler Yönetmeliği, o direito de livre resolução não pode ser exercido nos serviços cuja execução se tenha iniciado com o consentimento do Comprador e que sejam concluídos antes do termo do prazo de resolução, bem como nos bens e serviços preparados por medida em função dos pedidos ou das necessidades pessoais do Comprador (incluindo os serviços de tradução e de reconhecimento preparados especificamente para uma pessoa ou um documento). Os pedidos de cancelamento apresentados antes do início do trabalho de tradução são objeto de apreciação autónoma.` },
        { heading: `Cancelamento e Reembolso`, body: `Nas encomendas cuja execução ainda não tenha sido iniciada, os pedidos de cancelamento podem ser apresentados através de [E-POSTA]; os reembolsos considerados procedentes são efetuados, num prazo razoável, pelo mesmo método utilizado no pagamento. Nos serviços personalizados cuja execução já se tenha iniciado ou tenha sido concluída, o reembolso pode não ser possível devido à natureza do trabalho.` },
        { heading: `Resolução de Litígios`, body: `Nos litígios que possam decorrer do presente Contrato, são competentes, dentro dos limites monetários anualmente divulgados pelo Ticaret Bakanlığı, os Tüketici Hakem Heyetleri e os Tribunais do Consumidor do local de residência do Comprador ou do local onde a transação foi realizada.` },
        { heading: `Entrada em Vigor`, body: `Ao confirmar a encomenda, o Comprador declara ter lido e aceite todas as condições do presente Contrato. O Contrato entra em vigor com a confirmação da encomenda.` },
      ],
    },
    cookies: {
      seo: { title: `Política de Cookies`, description: `Informações sobre os cookies utilizados no nosso sítio e sobre a gestão de preferências.` },
      title: `Política de Cookies`,
      sections: [
        { heading: `O que é um Cookie?`, body: `Os cookies são pequenos ficheiros de texto que são guardados no seu navegador quando visita um sítio Web. São utilizados para tornar o sítio mais seguro e funcional, recordar as suas preferências e obter estatísticas de utilização.` },
        { heading: `Porque Utilizamos Cookies?`, body: `Utilizamos os cookies para assegurar as funções essenciais do sítio, proteger a segurança da sessão, medir o desempenho e, mediante o seu consentimento, melhorar os nossos serviços e desenvolver atividades de marketing.` },
        { heading: `Categorias de Cookies`, body: `Os cookies estritamente necessários são indispensáveis ao funcionamento e à segurança do sítio e não podem ser desativados. Os cookies de desempenho e de análise ajudam-nos a compreender a interação dos visitantes. Os cookies de marketing contribuem para a apresentação de conteúdos e anúncios adequados aos seus interesses. Os cookies de preferências recordam as suas escolhas, como o idioma. Os cookies de análise e de marketing apenas funcionam com o seu consentimento expresso.` },
        { heading: `Cookies de Terceiros`, body: `Para efeitos de análise e de marketing, podemos recorrer a serviços de terceiros (por exemplo, ferramentas de estatística de visitantes e de medição de publicidade). Estes serviços podem colocar os seus próprios cookies e tratar os dados no âmbito das suas próprias políticas de privacidade.` },
        { heading: `Gestão das Preferências de Cookies`, body: `Pode expressar ou alterar, a qualquer momento, as suas preferências relativas aos cookies não obrigatórios através da ferramenta de gestão de preferências de cookies disponibilizada no sítio. Pode ainda apagar ou bloquear os cookies nas definições do seu navegador; contudo, nesse caso, algumas secções do sítio poderão não funcionar corretamente.` },
        { heading: `Prazos de Conservação`, body: `Consoante o seu tipo, os cookies são conservados durante a sessão ou por um período determinado. Os cookies de sessão são apagados quando o navegador é fechado; os cookies persistentes cessam no termo do prazo estabelecido ou quando os apagar.` },
        { heading: `Alterações`, body: `A presente Política de Cookies pode ser atualizada periodicamente. A versão em vigor é sempre publicada nesta página.` },
      ],
    },
    partnership: {
      seo: { title: `Contrato de Parceria Comercial`, description: `Termos e condições do programa de parceria comercial (parceiro) da TercümExpert.` },
      title: `Contrato de Parceria Comercial`,
      sections: [
        { heading: `Partes e Objeto`, body: `O presente Contrato de Parceria Comercial é celebrado entre, por um lado, a [ŞİRKET ÜNVANI] (“TercümExpert”) e, por outro lado, o parceiro comercial que se candidata ao programa (“Parceiro”), com o objetivo de regular os termos e condições do programa de parceria comercial (de indicação) da TercümExpert.` },
        { heading: `Âmbito do Programa`, body: `O Parceiro encaminha clientes à TercümExpert através da sua própria rede e dos seus canais. Caso o cliente indicado adquira serviços através da TercümExpert, o Parceiro adquire o direito à comissão prevista no presente Contrato.` },
        { heading: `Comissão`, body: `O Parceiro adquire o direito a uma comissão à taxa de %20 sobre o valor do serviço pago pelo cliente indicado, por cada indicação válida e aprovada. A taxa e as condições da comissão podem ser atualizadas pela TercümExpert, mediante aviso prévio. As transações canceladas, reembolsadas ou cujo pagamento não seja concluído não são consideradas para efeitos de comissão.` },
        { heading: `Acompanhamento e Aquisição do Direito`, body: `As indicações são associadas através da ligação de acompanhamento fornecida ao Parceiro, de um código QR ou do método determinado pela TercümExpert. O direito à comissão apenas se constitui relativamente às transações corretamente associadas por estes métodos e cujo pagamento tenha sido concluído.` },
        { heading: `Pagamento`, body: `As comissões adquiridas são pagas na conta indicada pelo Parceiro. O período e as condições de pagamento são estabelecidos separadamente entre as partes. As obrigações fiscais relativas ao pagamento estão sujeitas à legislação em vigor.` },
        { heading: `Obrigações do Parceiro`, body: `O Parceiro compromete-se a utilizar informações corretas e não enganosas nas suas ações de divulgação, a abster-se de comportamentos suscetíveis de prejudicar a marca e a reputação da TercümExpert e a cumprir a legislação em vigor.` },
        { heading: `Comportamentos Proibidos`, body: `São proibidos o envio de spam e de comunicações em massa não solicitadas, a publicidade enganosa, bem como os comportamentos que constituam concorrência desleal através de indicações falsas ou de autoindicação. Tais comportamentos constituem fundamento para o cancelamento da comissão e para a resolução do Contrato.` },
        { heading: `Utilização da Marca`, body: `O Parceiro apenas pode utilizar a marca, o logótipo e os materiais promocionais da TercümExpert mediante autorização escrita da TercümExpert e no âmbito das regras por esta fornecidas.` },
        { heading: `Confidencialidade`, body: `As partes comprometem-se a proteger as informações confidenciais obtidas no âmbito do presente Contrato e a utilizá-las exclusivamente para os fins do programa.` },
        { heading: `Parte Independente`, body: `O Parceiro é uma parte independente; não é trabalhador, representante ou agente da TercümExpert e não pode assumir compromissos perante terceiros em nome da TercümExpert.` },
        { heading: `Vigência e Resolução`, body: `O Contrato mantém-se em vigor até que uma das partes comunique a sua resolução. A TercümExpert pode resolver o Contrato de imediato em caso de incumprimento das obrigações; nesse caso, não são pagas as comissões resultantes de indicações irregulares.` },
        { heading: `Litígios e Lei Aplicável`, body: `O presente Contrato rege-se pelo direito da Türkiye Cumhuriyeti. Ao aprovar a candidatura, o Parceiro declara ter lido e aceite os termos do Contrato.` },
      ],
    },
  },

    admin: {
    attachmentImage: 'Imagem',
    attachmentFile: 'Documento',
        title: `Registos de Conversas`,
        summary: `{total} conversas · {leads} pedidos de contacto`,
        onlyLeads: `Apenas pedidos de contacto`,
        loading: `A carregar registos…`,
        error: `Não foi possível ler os registos. Verifique se a tabela do Supabase e as permissões (RLS) estão configuradas.`,
        empty: `Ainda não existem registos.`,
        selectHint: `Selecione uma conversa à esquerda para a visualizar.`,
        contactRequest: `Pedido de contacto`,
        contactInfo: `Dados de contacto`,
        fieldName: `Nome`,
        fieldEmail: `Correio eletrónico`,
        fieldPhone: `Telefone`,
        fieldMessage: `Mensagem`,
        requestBadge: `pedido`,
        noMessages: `Este registo não contém mensagens (apenas um pedido de contacto).`,
        loginTitle: `Início de sessão necessário`,
        loginDesc: `Para visualizar esta página, inicie sessão com uma conta de administrador.`,
        login: `Iniciar Sessão`,
        noAccessTitle: `Não tem autorização de acesso`,
        noAccessDesc: `Esta página está disponível apenas para administradores.`,
        loadingAuth: `A carregar…`,
    },
  footer: {
    tagline: 'O seu parceiro de confiança em serviços de tradução profissional.',
    columns: {
      quickLinks: 'Ligações rápidas',
      services: 'Serviços',
      contact: 'Contacto',
    },
    quickLinks: {
      corporate: 'Empresas',
      services: 'Os nossos serviços',
      quote: 'Calcular preço',
      blog: 'Blogue',
      faq: 'Perguntas frequentes',
      contact: 'Contacto',
    },
    serviceLinks: {
      sworn: 'Tradução ajuramentada',
      notarized: 'Tradução com certificação notarial',
      apostille: 'Processo de apostila',
      corporate: 'Soluções para empresas',
      partnership: 'Programa de parcerias',
    },
    legal: {
      kvkk: 'KVKK',
      privacy: 'Política de Privacidade',
      distanceSales: 'Contrato de Venda à Distância',
      cookies: 'Política de Cookies',
    },
    socialTitle: 'Siga-nos',
    whatsapp: 'Apoio por WhatsApp',
    rights: 'Todos os direitos reservados.',
  },

  cookie: {
    title: 'Preferências de cookies',
    desc: 'Utilizamos cookies para melhorar a sua experiência. Os cookies além dos necessários funcionam apenas com o seu consentimento.',
    accept: 'Aceitar',
    reject: 'Rejeitar',
    manage: 'Gerir preferências',
    save: 'Guardar preferências',
    categories: {
      necessary: { label: 'Necessários', desc: 'Indispensáveis ao funcionamento do site; não podem ser desativados.' },
      analytics: { label: 'Análise', desc: 'Ajudam-nos a compreender a utilização.' },
      marketing: { label: 'Marketing', desc: 'Para conteúdos e anúncios relevantes.' },
      preferences: { label: 'Preferências', desc: 'Memorizam as suas preferências.' },
    },
  },

  chatbot: {
    attach: {
      button: 'Anexar ficheiro',
      tooLarge: 'O ficheiro é demasiado grande (máx. 25 MB).',
      unsupported: 'Não consigo analisar ficheiros de áudio ou vídeo no chat. Pode carregá-los na página de orçamento.',
      cannotRead: 'Não consegui ler este ficheiro. Pode carregá-lo na página de orçamento ou tentar outro formato.',
      reading: 'A ler o ficheiro…',
      remove: 'Remover',
    },
    nudge: 'Como posso ajudá-lo?',
    title: 'Apoio TercümExpert',
    open: 'Abrir conversa',
    close: 'Fechar conversa',
    minimize: 'Minimizar',
    clear: 'Limpar conversa',
    inputPlaceholder: 'Escreva a sua mensagem…',
    send: 'Enviar',
    typing: 'A escrever…',
    welcome:
      'Olá e bem-vindo à TercümExpert. Posso ajudá-lo com tradução, preços, certificação notarial, apostila ou serviços para empresas.',
    quickQuestions: [
      'Como é calculado o preço?',
      'O que é a tradução ajuramentada?',
      'Quero carregar um documento',
      'Quero um orçamento para empresas',
      'É necessária certificação notarial?',
      'Coloque-me em contacto com um representante',
    ],
    handoff: 'Falar com um representante',
    toWhatsapp: 'Transferir para o WhatsApp',
    disclaimer: 'Estas informações são gerais; confirme os requisitos exatos junto da instituição competente.',
    sensitiveWarning:
      'Não partilhe dados pessoais sensíveis através desta conversa. Pode enviar os seus documentos através da área de carregamento segura.',
    answers: [
      `O preço é calculado com base no número de palavras do seu documento, no par de idiomas, no tipo de serviço (tradução ajuramentada, reconhecimento notarial, apostila) e no prazo de entrega. Para obter uma estimativa imediata, pode carregar o seu documento ou introduzir os dados na página Calcular Preço.`,
      `A tradução ajuramentada é uma tradução oficial realizada por um tradutor ajuramentado e validada com a sua assinatura e carimbo. As entidades oficiais exigem, na maioria dos casos, uma tradução ajuramentada; sempre que necessário, pode ainda acrescentar-se o reconhecimento notarial.`,
      `Pode enviar o seu documento através da área de carregamento segura disponível na página Calcular Preço. Após o carregamento, verá de imediato uma estimativa de preço e poderá concluir a sua encomenda.`,
      `Para as necessidades da sua empresa, oferecemos preços especiais e entrega prioritária em traduções regulares e de grande volume. Para mais informações, consulte a nossa página Empresas ou entre em contacto connosco.`,
      `A necessidade de reconhecimento notarial depende da entidade a que o documento se destina e do tipo de procedimento. Alguns procedimentos aceitam apenas a tradução ajuramentada, enquanto outros exigem também o reconhecimento notarial. Se tiver dúvidas, teremos todo o gosto em ajudar.`,
      `Vamos colocá-lo de imediato em contacto com um dos nossos representantes. Pode escrever-nos através do WhatsApp no botão abaixo.`,
    ],
    fallback: `Um dos nossos representantes poderá prestar-lhe o apoio mais adequado à sua questão. Pode escrever-nos através do WhatsApp no botão abaixo; a sua mensagem será enviada já preenchida.`,
    contact: {
      "introTitle": "Bem-vindo",
      "introDesc": "Para poder ajudá-lo melhor, poderia indicar-me primeiro o seu nome e o seu endereço de e-mail?",
      "start": "Iniciar conversa",
      "introError": "Por favor, introduza o seu nome e o seu endereço de e-mail.",
      whatsapp: `WhatsApp`,
      email: `E-mail`,
      phone: `Telefone`,
      leaveInfo: `Deixar os meus dados de contacto`,
      formTitle: `Entremos em contacto consigo`,
      formDesc: `Deixe os seus dados e a nossa equipa entrará em contacto o mais brevemente possível.`,
      name: `O seu nome`,
      emailField: `E-mail`,
      phoneField: `Telefone`,
      message: `A sua mensagem (opcional)`,
      submit: `Enviar`,
      submitting: `A enviar…`,
      thanks: `Obrigado, a nossa equipa entrará em contacto consigo o mais brevemente possível.`,
      errorRequired: `Por favor, introduza um e-mail ou telefone.`,
      back: `Voltar`,
    },
  },

  translator: {
    "seo": {
      "title": "Painel do Tradutor — TercümExpert",
      "description": "Candidatura e painel de trabalho do tradutor."
    },
    "loading": "A carregar…",
    "loginTitle": "Início de sessão obrigatório",
    "loginDesc": "Esta área destina-se apenas a tradutores e administradores. Inicie sessão para continuar.",
    "login": "Iniciar sessão",
    "setupTitle": "Painel ainda não está pronto",
    "setupDesc": "A infraestrutura de tradutores (base de dados) ainda não foi configurada. O painel é ativado assim que a configuração estiver concluída.",
    "applyTitle": "Candidatura de Tradutor",
    "applyDesc": "Preencha os seus dados para integrar a nossa rede de tradutores freelance. A sua candidatura é ativada após aprovação do administrador.",
    "applyNote": "As suas informações são utilizadas apenas para avaliação e pagamento.",
    "form": {
      "fullName": "Nome completo",
      "birthDate": "Data de nascimento",
      "phone": "Telefone",
      "country": "País",
      "city": "Cidade / Distrito",
      "selectCountry": "Selecione o país",
      "selectCity": "Selecione a cidade / distrito",
      "cityNeedsCountry": "Selecione primeiro um país",
      "address": "Morada completa",
      "isSworn": "É tradutor ajuramentado (certificado)?",
      "isSwornHint": "Assinale esta opção se possui um registo de ajuramentação notarial. Terá prioridade em trabalhos que exijam tradução ajuramentada.",
      "iban": "IBAN",
      "ibanName": "Titular do IBAN (nome completo)",
      "languagePairs": "Pares de idiomas",
      "source": "Idioma de origem",
      "target": "Idioma de destino",
      "addPair": "Adicionar",
      "removePair": "Remover",
      "swap": "Inverter direção",
      "expertise": "Áreas de especialização",
      "submit": "Submeter candidatura",
      "submitting": "A submeter…",
      "saved": "Os seus dados foram guardados.",
      "saveError": "Não foi possível guardar. Tente novamente.",
      "required": "Preencha os campos obrigatórios.",
      "atLeastOnePair": "Adicione pelo menos um par de idiomas."
    },
    "expertiseLabels": {
      "legal": "Jurídica",
      "medical": "Médica",
      "technical": "Técnica",
      "academic": "Académica",
      "commercial": "Comercial",
      "financial": "Financeira",
      "literary": "Literária",
      "official": "Documentos oficiais",
      "localization": "Web / Software",
      "general": "Geral"
    },
    "pendingTitle": "A sua candidatura está em análise",
    "pendingDesc": "Recebemos a sua candidatura de tradutor. O acesso ao painel é concedido após análise do administrador.",
    "rejectedTitle": "Candidatura não aprovada",
    "rejectedDesc": "A sua candidatura não foi aprovada neste momento. Pode atualizar os seus dados e tentar novamente.",
    "reapply": "Tentar novamente",
    "cancelApplication": "Cancelar candidatura",
    "cancelConfirm": "Tem a certeza de que pretende cancelar a sua candidatura? O seu registo será eliminado; poderá candidatar-se novamente mais tarde, se desejar.",
    "panelTitle": "Painel do Tradutor",
    "tabs": {
      "profile": "O Meu Perfil",
      "pool": "Bolsa de Traduções",
      "active": "Trabalhos Ativos",
      "pending": "A Aguardar Aprovação",
      "approved": "Aprovados",
      "completed": "Concluídos",
      "wallet": "Carteira"
    },
    "soon": "Esta secção estará disponível no próximo passo.",
    "jobs": {
      "empty": "Não existem trabalhos nesta secção de momento.",
      "translator": "Tradutor",
      "sourceFiles": "Documentos de origem",
      "translationFiles": "Tradução carregada",
      "tracking": "Rastreio",
      "rejectionReason": "Motivo da rejeição",
      "chooseFiles": "Escolher ficheiros de tradução",
      "filesSelected": "ficheiro(s) selecionado(s)",
      "uploadHint": "Carregue a sua tradução e, se necessário, uma cópia digital do original e, em seguida, envie-a para aprovação.",
      "submit": "Enviar para aprovação",
      "sending": "A enviar…",
      "needFiles": "Selecione pelo menos um ficheiro.",
      "uploadError": "Não foi possível carregar os ficheiros. Tente novamente.",
      "submittedMsg": "Tradução enviada para aprovação.",
      "actionError": "Não foi possível concluir a ação. Tente novamente.",
      "waitingApproval": "A sua tradução aguarda aprovação da gestão. Após aprovação, o passo de entrega aparece em “Aprovados”.",
      "trackingPlaceholder": "Número / ligação de rastreio",
      "needTracking": "É necessário um número de rastreio para a entrega por transportadora.",
      "markShipped": "Expedido — concluir",
      "markDelivered": "Entregue — concluir",
      "completedMsg": "Trabalho concluído. O seu ganho foi adicionado à sua carteira.",
      "reasonPlaceholder": "Em caso de rejeição, escreva o motivo (visível para o tradutor)…",
      "approve": "Aprovar",
      "reject": "Rejeitar",
      "needReason": "Escreva um motivo para rejeitar.",
      "approvedMsg": "Tradução aprovada.",
      "rejectedMsg": "Tradução rejeitada; devolvida ao tradutor.",
      "statusLabel": "Estado",
      "status_claimed": "Em curso",
      "status_submitted": "A aguardar aprovação",
      "status_approved": "Aprovado — fase de entrega",
      "status_completed": "Concluído"
    },
    "pool": {
      "loading": "A carregar a bolsa…",
      "empty": "Não existem encomendas pendentes que correspondam aos seus pares de idiomas e especialização de momento.",
      "error": "Não foi possível carregar a bolsa. Tente novamente.",
      "orderNo": "Encomenda",
      "service": "Tipo de serviço",
      "documentType": "Tipo de documento",
      "langPair": "Par de idiomas",
      "words": "Palavras",
      "pagesUnit": "páginas",
      "deadline": "Prazo",
      "daysUnit": "dias úteis",
      "note": "Nota do cliente",
      "customerInfo": "Dados do cliente",
      "deliveryInfo": "Dados do cliente e de entrega",
      "customerName": "Nome completo",
      "customerEmail": "E-mail",
      "customerPhone": "Telefone",
      "deliveryAddress": "Morada de entrega",
      "text": "Texto da encomenda",
      "files": "Documentos",
      "earning": "O seu ganho por este trabalho",
      "urgent": "Urgente",
      "sworn": "Ajuramentada",
      "notary": "Reconhecimento notarial",
      "apostille": "Apostila",
      "cargo": "Entrega por transportadora",
      "digital": "Entrega digital",
      "claim": "Aceitar este trabalho",
      "claiming": "A aceitar…",
      "claimed": "Aceitou o trabalho com sucesso.",
      "claimError": "Não foi possível aceitar o trabalho. Pode ter sido aceite por outra pessoa; atualize a lista.",
      "ibanRequired": "Antes de poder aceitar trabalhos, os seus dados de IBAN têm de ser verificados pela gestão. Introduza o seu IBAN no seu perfil; após verificação, poderá aceitar trabalhos da bolsa."
    },
    "profile": {
      "statusApproved": "Tradutor aprovado",
      "verifiedIban": "IBAN verificado",
      "unverifiedIban": "IBAN não verificado",
      "current": "Guardado",
      "edit": "Guardar dados",
      "ibanReminder": "Para receber os seus pagamentos, introduza e guarde os seus dados de IBAN. Após verificação pelo administrador, os pagamentos serão efetuados para esta conta.",
      "lockedHint": "Não pode ser alterado após a aprovação",
      "revokeTitle": "Esta alteração revogará a sua aprovação",
      "revokeWarning": "Se alterar os seus pares de idiomas, o estado de ajuramentação ou as áreas de especialização, a sua conta regressa à análise da gestão (fica pendente). Os seus trabalhos, registos e carteira são PRESERVADOS; após nova aprovação, continua de onde ficou.",
      "consent": "Li e aceito",
      "ibanReverify": "Está a alterar o seu IBAN. O novo IBAN regressa à análise da gestão; a sua conta permanece ativa, mas não pode aceitar novos trabalhos da bolsa até o IBAN ser verificado."
    },
    "admin": {
      "title": "Painel de Gestão",
      "translatorsTab": "Tradutores",
      "applicationsTab": "Candidaturas",
      "ibanTab": "Aprovações de IBAN",
      "ordersTab": "Encomendas",
      "paymentsTab": "Pagamentos",
      "noIbanPending": "Nenhum tradutor a aguardar aprovação de IBAN.",
      "ibanHint": "Aprove aqui os IBAN recém-introduzidos ou alterados. Até serem aprovados, o tradutor não pode aceitar novos trabalhos da bolsa.",
      "ibanApprove": "Aprovar IBAN",
      "paymentsHint": "No dia de pagamento (dias 1 e 16 de cada mês): para cada tradutor que tenha pago, carregue o comprovativo e clique em “Marcar como pago”. O botão não funcionará sem um comprovativo. Os tradutores com saldo zero não são listados aqui.",
      "noPayments": "Nenhum tradutor com saldo a pagar.",
      "paymentAmount": "Montante a pagar",
      "uploadReceipt": "Carregar comprovativo",
      "receiptUploaded": "Comprovativo carregado",
      "receiptRequired": "Carregue primeiro um comprovativo",
      "uploading": "A carregar…",
      "markPaid": "Marcar como pago",
      "paid": "Pagamento registado e o tradutor foi notificado com o comprovativo.",
      "panelHint": "Acompanhe os tradutores aprovados por perfil, analise candidaturas e faça a gestão do fluxo de trabalho de todas as encomendas.",
      "summary": "{total} tradutores · {pending} candidaturas pendentes",
      "applicationsSummary": "{total} candidaturas · {pending} a aguardar análise",
      "noApproved": "Ainda não existem tradutores aprovados.",
      "noPending": "Nenhuma candidatura pendente.",
      "noMatch": "Nenhum registo corresponde aos filtros.",
      "loadError": "Não foi possível carregar os registos. Verifique a base de dados e as permissões (RLS).",
      "noApplications": "Ainda não existem registos de tradutores.",
      "filters": {
        "namePlaceholder": "Pesquisar por nome…",
        "country": "País",
        "city": "Cidade / Distrito",
        "anyCountry": "Todos os países",
        "anyCity": "Todas as cidades",
        "cityNeedsCountry": "Selecione primeiro um país",
        "sourceLang": "Idioma de origem",
        "targetLang": "Idioma de destino",
        "anyLang": "Qualquer",
        "eitherDirection": "Qualquer direção (origem↔destino)",
        "expertise": "Áreas de especialização",
        "clear": "Limpar filtros",
        "results": "{n} registos"
      },
      "orders": {
        "loadError": "Não foi possível carregar as encomendas. Tente novamente.",
        "empty": "Ainda não existem encomendas.",
        "searchPlaceholder": "Pesquisar por n.º de encomenda ou nome do cliente…",
        "results": "{n} encomendas",
        "customer": "Cliente",
        "translator": "Tradutor",
        "unassigned": "Não atribuída",
        "status": "Estado",
        "done": "Concluída",
        "inProgress": "Em curso",
        "completedOn": "Concluída em",
        "placedOn": "Data da encomenda",
        "total": "Total",
        "statusAvailable": "Na bolsa (não aceite)",
        "statusClaimed": "Em tradução",
        "statusSubmitted": "A aguardar aprovação",
        "statusApproved": "Fase de entrega",
        "statusCompleted": "Concluída",
        "statusCancelled": "Cancelada"
      },
      "profile": {
        "back": "Voltar aos tradutores",
        "adminOnly": "Este perfil é exclusivo da gestão; o tradutor não o pode ver.",
        "infoTitle": "Dados",
        "walletTitle": "Carteira",
        "jobsTitle": "Trabalhos",
        "noJobs": "Este tradutor ainda não tem trabalhos."
      },
      "approve": "Aprovar",
      "reject": "Rejeitar",
      "colLangs": "Pares de idiomas",
      "colExpertise": "Especialização",
      "colLocation": "Cidade / País",
      "swornBadge": "Ajuramentada",
      "returningBadge": "Tradutor recorrente",
      "ibanVerified": "IBAN verificado",
      "ibanNotVerified": "IBAN não verificado",
      "verifyIban": "Verificar IBAN",
      "unverifyIban": "Anular verificação",
      "statusPending": "Pendente",
      "statusApproved": "Aprovado",
      "statusRejected": "Rejeitado",
      "actionError": "Não foi possível concluir a ação."
    },
    "wallet": {
      "total": "Ganhos totais",
      "locked": "Bloqueado",
      "withdrawable": "Levantável",
      "paid": "Pago",
      "payInfo": "Os ganhos são adicionados à sua carteira quando um trabalho é concluído; ficam bloqueados durante 7 dias e depois tornam-se levantáveis. Os pagamentos são efetuados sobre o saldo levantável nos dias 1 e 16 de cada mês.",
      "empty": "Ainda não existem ganhos. Os ganhos de trabalhos concluídos aparecem aqui.",
      "entryOrder": "Encomenda",
      "date": "Data",
      "statusCol": "Estado",
      "amount": "Montante",
      "statusPaid": "Pago",
      "statusUnlocked": "Levantável",
      "statusPending": "Bloqueado",
      "loadError": "Não foi possível carregar a carteira. Tente novamente."
    },
    "adminWallet": {
      "firmShare": "Quota da empresa (com IVA)",
      "firmShareHint": "Quota da empresa = total das encomendas concluídas (com IVA) menos os ganhos dos tradutores.",
      "ciro": "Receita total (com IVA)",
      "kdv": "IVA (para o Estado)",
      "payouts": "Pago aos tradutores",
      "net": "Líquido da empresa",
      "count": "{n} encomendas concluídas",
      "empty": "Ainda não existem encomendas concluídas.",
      "colOrder": "Encomenda",
      "colTranslator": "Tradutor",
      "colDate": "Data",
      "colTotal": "Total (com IVA)",
      "colPayout": "Tradutor",
      "colFirm": "Quota da empresa",
      "loadError": "Não foi possível carregar a carteira. Tente novamente."
    }
  },
  authx: {
    "rememberMe": "Lembrar-me",
    "showPassword": "Mostrar palavra-passe",
    "hidePassword": "Ocultar palavra-passe",
    "forgot": "Esqueci-me da palavra-passe",
    "forgotTitle": "Repor palavra-passe",
    "forgotDesc": "Introduza o endereço de correio eletrónico com que se registou e enviar-lhe-emos uma ligação de utilização única para repor a sua palavra-passe.",
    "forgotEmail": "Correio eletrónico",
    "forgotSubmit": "Enviar ligação de reposição",
    "forgotSent": "A ligação foi enviada para o seu correio eletrónico. Verifique a sua caixa de entrada (e a pasta de spam).",
    "forgotBack": "Voltar ao início de sessão",
    "resetTitle": "Definir uma nova palavra-passe",
    "resetDesc": "Introduza a sua nova palavra-passe e confirme-a escrevendo-a novamente.",
    "newPassword": "Nova palavra-passe",
    "newPasswordRepeat": "Nova palavra-passe (repetir)",
    "mismatch": "As palavras-passe não coincidem.",
    "weak": "A palavra-passe deve ter, pelo menos, 6 caracteres.",
    "resetSubmit": "Atualizar palavra-passe",
    "resetSuccess": "A sua palavra-passe foi atualizada. Pode agora iniciar sessão com a sua nova palavra-passe.",
    "resetInvalid": "A ligação é inválida ou expirou. Solicite uma nova ligação de reposição.",
    "goLogin": "Iniciar sessão",
    err: {
      "invalidCredentials": "Email ou palavra-passe incorretos. Verifique os seus dados e tente novamente.",
      "emailNotConfirmed": "O seu endereço de email ainda não foi verificado. Clique na ligação de verificação na sua caixa de entrada.",
      "alreadyRegistered": "Este endereço de email já se encontra registado. Tente iniciar sessão ou repor a sua palavra-passe.",
      "weakPassword": "A palavra-passe deve ter, no mínimo, 6 caracteres.",
      "otpInvalid": "O código de verificação está incorreto ou expirou. Solicite um novo código.",
      "rateLimited": "Demasiadas tentativas. Aguarde um momento e tente novamente.",
      "generic": "Ocorreu um erro. Tente novamente mais tarde."
    }
  },
  notFound: {
    seo: { title: 'Página não encontrada', description: 'Não foi possível encontrar a página que procura.' },
    title: 'Página não encontrada',
    desc: 'A página que procura pode ter sido movida ou pode nunca ter existido.',
    home: 'Voltar ao início',
  },
}
